/* FCE Prep extra bank: listening week 5 */
(function () {
var BANK = [
  { id: "fce-lis5-01", title: "Talk: Volunteering on an Archaeological Dig", kind: "monologue",
    script: "Thanks for inviting me to talk about my summer volunteering on an archaeological dig. Let me say straight away: it was nothing like the films. Nobody handed me a brush and a golden mask on day one. In fact, for the first week I mostly moved wheelbarrows of soil and learned to recognise the difference between a medieval roof tile and, well, a modern brick — which is harder than it sounds when everything is covered in mud. The dig was at a farm site about forty minutes from York, where a team from the university is uncovering a village that was abandoned in the fourteenth century. Volunteers don't need experience, but you do need to book months ahead, because places go quickly — there were over two hundred applications for thirty spots this year. What surprised me most was how methodical everything is. Before you lift anything out of the ground, it gets photographed, measured, and recorded on a tablet, and each find goes into a labelled tray with the exact location written on it. My supervisor said an object without its context is 'just a thing' — it's the position that tells the story. My best moment came in week three, when I uncovered a bone comb, small enough to fit in my palm, with a pattern of circles carved along the edge. Holding something last touched six hundred years ago changes how you think about ordinary objects, honestly. If you're considering it, my advice is: bring proper boots, expect rain, and don't worry about your back — you get used to kneeling. And keep a diary, because the days blur together and you'll want to remember them.",
    questions: [
      { q: "What did the speaker mainly do during her first week?", options: ["She moved soil in wheelbarrows.", "She photographed golden objects.", "She cleaned medieval roof tiles.", "She recorded finds on a tablet."], answer: 0, explanation: "For the first week she 'mostly moved wheelbarrows of soil' — nothing like the films." },
      { q: "Why is it necessary to apply early for a volunteer place?", options: ["The farm closes in summer.", "Places are limited and demand is high.", "Volunteers need long training first.", "The university charges less for early bookings."], answer: 1, explanation: "You must book months ahead: 'over two hundred applications for thirty spots'." },
      { q: "What did the supervisor mean by 'just a thing'?", options: ["Most finds are modern rubbish.", "Small objects are less valuable.", "An object without its recorded position loses its story.", "Bone objects need special care."], answer: 2, explanation: "An object without its context is 'just a thing' — 'it's the position that tells the story'." },
      { q: "How did finding the comb affect the speaker?", options: ["It made her want to study carving.", "It convinced her to keep it.", "It made her nervous about damaging finds.", "It changed how she thinks about everyday objects."], answer: 3, explanation: "Holding something six hundred years old 'changes how you think about ordinary objects'." },
      { q: "Why does the speaker recommend keeping a diary?", options: ["Because the days blur together.", "Because supervisors require written records.", "Because it helps with back pain.", "Because volunteers must report the weather."], answer: 0, explanation: "She advises a diary 'because the days blur together and you'll want to remember them'." }
    ] },
  { id: "fce-lis5-02", title: "Interview: Running a Family Restaurant", kind: "dialogue",
    script: "Presenter: My guest today is Elena, who two years ago left a well-paid marketing job to take over her parents' restaurant. Elena, was that a hard decision?\nElena: Harder than I admitted at the time. My parents were ready to retire and the choice was stark: either I took it on, or we sold a place that had been in the family for thirty-one years. I told everyone it was a business decision, but honestly it was an emotional one.\nPresenter: What did people expect would happen?\nElena: Plenty of friends predicted I'd modernise everything — new name, new menu, food designed for photographs. And I did consider it. But when I actually studied the accounts, the numbers told a different story. Our regulars, some of whom have eaten with us every week for decades, were the backbone of the business. Chasing a trendier crowd risked losing them for customers who might vanish with the next fashion.\nPresenter: So what did you change?\nElena: The things customers never see. The booking system was a paper diary by the phone; now it's digital, which alone cut our empty tables by a fifth, because we can fill cancellations. I renegotiated with suppliers, fixed the draughty windows, and — this was the controversial one — closed on Mondays. My father thought closing one day meant losing money. In fact, staff come back rested, mistakes are down, and Tuesday takings have actually risen.\nPresenter: And the menu survived untouched?\nElena: Almost. I kept every classic — my mother still checks the sauce personally — but shortened it. Forty dishes became twenty-five. A long menu looks generous, but it really means waste in the kitchen and slower service. Nobody has complained about missing dishes; they mostly never noticed.\nPresenter: Any regrets?\nElena: Only that I waited so long to ask my parents how the place actually ran. We assume our parents will always be there to ask.",
    questions: [
      { q: "Why did Elena describe her choice as 'stark'?", options: ["The restaurant was losing money fast.", "It was take over the restaurant or sell it.", "Her parents disagreed about retiring.", "Her marketing job was ending anyway."], answer: 1, explanation: "Either she took it on 'or we sold a place that had been in the family for thirty-one years'." },
      { q: "Why did Elena decide NOT to modernise the restaurant's image?", options: ["The regular customers were the core of the business.", "Her friends advised her against it.", "A new name was too expensive.", "Her mother refused to allow it."], answer: 0, explanation: "The accounts showed the regulars 'were the backbone of the business'; chasing trends risked losing them." },
      { q: "What was one result of the digital booking system?", options: ["Suppliers lowered their prices.", "The restaurant could open on Mondays.", "Empty tables were reduced by about twenty per cent.", "Staff made fewer cooking mistakes."], answer: 2, explanation: "Going digital 'cut our empty tables by a fifth, because we can fill cancellations'." },
      { q: "What happened after the restaurant started closing on Mondays?", options: ["Her father took over Mondays.", "Weekly income fell as predicted.", "Customers moved to other restaurants.", "Tuesday earnings went up."], answer: 3, explanation: "Staff return rested, mistakes are down, 'and Tuesday takings have actually risen'." },
      { q: "Why did Elena shorten the menu?", options: ["A long menu caused waste and slow service.", "Her mother could no longer cook forty dishes.", "Customers complained it was confusing.", "Suppliers could not deliver enough ingredients."], answer: 0, explanation: "'A long menu looks generous, but it really means waste in the kitchen and slower service.'" }
    ] }
,
  {
    id: "fce-lis5-03",
    title: "Talk: My Year Without a Smartphone",
    kind: "monologue",
    script: "When I tell people I spent last year without a smartphone, they usually assume it was some kind of digital health experiment. Actually, the reason was embarrassingly ordinary: I dropped mine in a canal on the second of January, and because I'd just started a poorly paid internship, I simply couldn't afford a new one. I bought a fifteen-pound phone that could call and text, and told myself I'd upgrade in a month or two. The first fortnight was genuinely difficult, and not for the reasons I expected. I didn't miss social media much, but I'd never realised how often I used the map. I got lost three times in the first week, and had to do something I hadn't done for years: ask strangers for directions. That, oddly enough, became the best part of the experience. Conversations with strangers turned out to be little gifts — a taxi driver told me about a hidden bakery I still visit every week. My friends adapted quickly; they knew a call would reach me when a message wouldn't. My mother, on the other hand, never stopped worrying, convinced that without a map I was permanently on the verge of disappearing. By summer I had savings again, and everyone expected me to buy a proper phone. I did — but it mostly lives in a drawer at home. I take it out for train tickets and long journeys. What I learned is not that technology is bad; it's that my attention is valuable, and for a whole year, nobody was renting it for free.",
    questions: [
      { q: "Why did the speaker originally give up her smartphone?",
        options: ["She was taking part in a health experiment", "She dropped it in a canal and couldn't afford a replacement", "Her doctor advised her to stop using it", "Her internship did not allow phones"],
        answer: 1,
        explanation: "She dropped it in a canal, and with 'a poorly paid internship' she 'simply couldn't afford a new one'." },
      { q: "What did she find hardest to live without at first?",
        options: ["Social media", "Her camera", "The map", "Music streaming"],
        answer: 2,
        explanation: "She 'didn't miss social media much', but had 'never realised how often I used the map'." },
      { q: "What became the best part of the experience?",
        options: ["Conversations with strangers", "Saving money for the summer", "Visiting a hidden bakery every day", "Learning the city streets by heart"],
        answer: 0,
        explanation: "Asking strangers for directions 'became the best part'; those conversations 'turned out to be little gifts'." },
      { q: "How did the speaker's mother react to the change?",
        options: ["She adapted more quickly than the friends did", "She refused to call the cheap phone", "She bought her daughter a new smartphone", "She kept worrying that the speaker would get lost"],
        answer: 3,
        explanation: "Her mother 'never stopped worrying', convinced she was 'permanently on the verge of disappearing'." },
      { q: "What conclusion does the speaker draw from the year?",
        options: ["Modern technology is fundamentally bad", "Smartphones should be banned on trains", "Her attention is valuable and shouldn't be given away for free", "Everyone should spend a year without a phone"],
        answer: 2,
        explanation: "'My attention is valuable, and for a whole year, nobody was renting it for free.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
