/* FCE Prep extra bank: listening week 5 */
(function () {
var BANK = [
  { id: "fce-lis5-01", title: "Talk: Volunteering on an Archaeological Dig", kind: "monologue",
    script: "Thanks for inviting me to talk about my summer volunteering on an archaeological dig. Let me say straight away: it was nothing like the films. Nobody handed me a brush and a golden mask on day one. In fact, for the first week I mostly moved wheelbarrows of soil and learned to recognise the difference between a medieval roof tile and, well, a modern brick — which is harder than it sounds when everything is covered in mud. The dig was at a farm site about forty minutes from York, where a team from the university is uncovering a village that was abandoned in the fourteenth century. Volunteers don't need experience, but you do need to book months ahead, because places go quickly — there were over two hundred applications for thirty spots this year. What surprised me most was how methodical everything is. Before you lift anything out of the ground, it gets photographed, measured, and recorded on a tablet, and each find goes into a labelled tray with the exact location written on it. My supervisor said an object without its context is 'just a thing' — it's the position that tells the story. My best moment came in week three, when I uncovered a bone comb, small enough to fit in my palm, with a pattern of circles carved along the edge. Holding something last touched six hundred years ago changes how you think about ordinary objects, honestly. If you're considering it, my advice is: bring proper boots, expect rain, and don't worry about your back — you get used to kneeling. And keep a diary, because the days blur together and you'll want to remember them.",
    questions: [
      { q: "What did the speaker mainly do during her first week?", options: ["She moved soil in wheelbarrows.", "She photographed golden objects.", "She cleaned medieval roof tiles.", "She recorded finds on a tablet."], answer: 0, explanation: "For the first week she 'mostly moved wheelbarrows of soil' — nothing like the films." },
      { q: "Why is it necessary to apply early for a volunteer place?", options: ["The farm closes in summer.", "Places are limited and demand is high.", "Volunteers need long training first.", "The university charges less for early bookings."], answer: 1, explanation: "You must book months ahead: 'over two hundred applications for thirty spots'." },
      { q: "What did the supervisor mean by 'just a thing'?", options: ["Most finds are modern rubbish.", "Small objects are less valuable.", "An object without its recorded position loses its story.", "Bone objects need special care."], answer: 2, explanation: "An object without its context is 'just a thing' — 'it's the position that tells the story'." },
      { q: "How did finding the comb affect the speaker?", options: ["It made her want to study carving.", "It convinced her to keep it.", "It made her nervous about damaging finds.", "It changed how she thinks about everyday objects."], answer: 3, explanation: "Holding something six hundred years old 'changes how you think about ordinary objects'." },
      { q: "Why does the speaker recommend keeping a diary?", options: ["Because the days blur together.", "Because supervisors require written records.", "Because it helps with back pain.", "Because volunteers must report the weather."], answer: 0, explanation: "She advises a diary 'because the days blur together and you'll want to remember them'." }
    ] },
  { id: "fce-lis5-02", title: "Interview: Running a Family Restaurant", kind: "dialogue",
    script: "Presenter: My guest today is Elena, who two years ago left a well-paid marketing job to take over her parents' restaurant. Elena, was that a hard decision?\nElena: Harder than I admitted at the time. My parents were ready to retire and the choice was stark: either I took it on, or we sold a place that had been in the family for thirty-one years. I told everyone it was a business decision, but honestly it was an emotional one.\nPresenter: What did people expect would happen?\nElena: Plenty of friends predicted I'd modernise everything — new name, new menu, food designed for photographs. And I did consider it. But when I actually studied the accounts, the numbers told a different story. Our regulars, some of whom have eaten with us every week for decades, were the backbone of the business. Chasing a trendier crowd risked losing them for customers who might vanish with the next fashion.\nPresenter: So what did you change?\nElena: The things customers never see. The booking system was a paper diary by the phone; now it's digital, which alone cut our empty tables by a fifth, because we can fill cancellations. I renegotiated with suppliers, fixed the draughty windows, and — this was the controversial one — closed on Mondays. My father thought closing one day meant losing money. In fact, staff come back rested, mistakes are down, and Tuesday takings have actually risen.\nPresenter: And the menu survived untouched?\nElena: Almost. I kept every classic — my mother still checks the sauce personally — but shortened it. Forty dishes became twenty-five. A long menu looks generous, but it really means waste in the kitchen and slower service. Nobody has complained about missing dishes; they mostly never noticed.\nPresenter: Any regrets?\nElena: Only that I waited so long to ask my parents how the place actually ran. We assume our parents will always be there to ask.",
    questions: [
      { q: "Why did Elena describe her choice as 'stark'?", options: ["The restaurant was losing money fast.", "It was take over the restaurant or sell it.", "Her parents disagreed about retiring.", "Her marketing job was ending anyway."], answer: 1, explanation: "Either she took it on 'or we sold a place that had been in the family for thirty-one years'." },
      { q: "Why did Elena decide NOT to modernise the restaurant's image?", options: ["The regular customers were the core of the business.", "Her friends advised her against it.", "A new name was too expensive.", "Her mother refused to allow it."], answer: 0, explanation: "The accounts showed the regulars 'were the backbone of the business'; chasing trends risked losing them." },
      { q: "What was one result of the digital booking system?", options: ["Suppliers lowered their prices.", "The restaurant could open on Mondays.", "Empty tables were reduced by about twenty per cent.", "Staff made fewer cooking mistakes."], answer: 2, explanation: "Going digital 'cut our empty tables by a fifth, because we can fill cancellations'." },
      { q: "What happened after the restaurant started closing on Mondays?", options: ["Her father took over Mondays.", "Weekly income fell as predicted.", "Customers moved to other restaurants.", "Tuesday earnings went up."], answer: 3, explanation: "Staff return rested, mistakes are down, 'and Tuesday takings have actually risen'." },
      { q: "Why did Elena shorten the menu?", options: ["A long menu caused waste and slow service.", "Her mother could no longer cook forty dishes.", "Customers complained it was confusing.", "Suppliers could not deliver enough ingredients."], answer: 0, explanation: "'A long menu looks generous, but it really means waste in the kitchen and slower service.'" }
    ] }
,
  {
    id: "fce-lis5-03",
    title: "Talk: My Year Without a Smartphone",
    kind: "monologue",
    script: "When I tell people I spent last year without a smartphone, they usually assume it was some kind of digital health experiment. Actually, the reason was embarrassingly ordinary: I dropped mine in a canal on the second of January, and because I'd just started a poorly paid internship, I simply couldn't afford a new one. I bought a fifteen-pound phone that could call and text, and told myself I'd upgrade in a month or two. The first fortnight was genuinely difficult, and not for the reasons I expected. I didn't miss social media much, but I'd never realised how often I used the map. I got lost three times in the first week, and had to do something I hadn't done for years: ask strangers for directions. That, oddly enough, became the best part of the experience. Conversations with strangers turned out to be little gifts — a taxi driver told me about a hidden bakery I still visit every week. My friends adapted quickly; they knew a call would reach me when a message wouldn't. My mother, on the other hand, never stopped worrying, convinced that without a map I was permanently on the verge of disappearing. By summer I had savings again, and everyone expected me to buy a proper phone. I did — but it mostly lives in a drawer at home. I take it out for train tickets and long journeys. What I learned is not that technology is bad; it's that my attention is valuable, and for a whole year, nobody was renting it for free.",
    questions: [
      { q: "Why did the speaker originally give up her smartphone?",
        options: ["She was taking part in a health experiment", "She dropped it in a canal and couldn't afford a replacement", "Her doctor advised her to stop using it", "Her internship did not allow phones"],
        answer: 1,
        explanation: "She dropped it in a canal, and with 'a poorly paid internship' she 'simply couldn't afford a new one'." },
      { q: "What did she find hardest to live without at first?",
        options: ["Social media", "Her camera", "The map", "Music streaming"],
        answer: 2,
        explanation: "She 'didn't miss social media much', but had 'never realised how often I used the map'." },
      { q: "What became the best part of the experience?",
        options: ["Conversations with strangers", "Saving money for the summer", "Visiting a hidden bakery every day", "Learning the city streets by heart"],
        answer: 0,
        explanation: "Asking strangers for directions 'became the best part'; those conversations 'turned out to be little gifts'." },
      { q: "How did the speaker's mother react to the change?",
        options: ["She adapted more quickly than the friends did", "She refused to call the cheap phone", "She bought her daughter a new smartphone", "She kept worrying that the speaker would get lost"],
        answer: 3,
        explanation: "Her mother 'never stopped worrying', convinced she was 'permanently on the verge of disappearing'." },
      { q: "What conclusion does the speaker draw from the year?",
        options: ["Modern technology is fundamentally bad", "Smartphones should be banned on trains", "Her attention is valuable and shouldn't be given away for free", "Everyone should spend a year without a phone"],
        answer: 2,
        explanation: "'My attention is valuable, and for a whole year, nobody was renting it for free.'" }
    ]
  }
,
  { id: "fce-lis5-04", title: "Talk: Restoring a Vintage Sailing Boat", kind: "monologue",
    script: "When I told my colleagues I'd bought a fifty-year-old wooden sailing boat, most of them assumed I'd lost my mind, and looking back, they had a point. I found Kestrel — that's her name — in a farmer's barn, where she'd been sitting under a plastic sheet for eleven years. The farmer's late father had raced her in the seventies, and there was a box of faded trophies on board to prove it. I paid less for the boat than most people spend on a holiday, which should have warned me about what was coming. My original plan was a quick six-month tidy-up: a coat of paint, new ropes, maybe a new sail. In the end, the restoration took me three and a half years. The hull looked sound at first, but when we stripped the old paint we found that a long section near the keel had rotted and had to be rebuilt plank by plank. I couldn't have done that myself, so I signed up for evening classes at a traditional boatbuilding school, which honestly turned out to be the best part of the whole project. I expected to learn about wood; I didn't expect to end up with a completely new circle of friends, several of whom gave up their weekends to help me. People always ask about the cost, and I've genuinely stopped counting. My honest advice to anyone tempted is this: don't do it to save money, because you won't, and don't do it for the finished boat. Do it because you'll enjoy the process itself — the smell of wood shavings, the slow progress, the problem-solving. The first time Kestrel touched the water again, with the farmer's family watching from the quay, every difficult weekend felt worthwhile.",
    questions: [
      { q: "What does the speaker suggest about the price he paid for the boat?", options: ["The low price should have made him suspicious.", "It was far more than the boat was worth.", "He refuses to say how much it was.", "It was similar to the price of a new boat."], answer: 0, explanation: "He paid less than most people spend on a holiday, 'which should have warned me about what was coming'." },
      { q: "What discovery changed the scale of the project?", options: ["The trophies on board were valuable.", "Rotten wood near the keel had to be rebuilt.", "The sail was the wrong size.", "The boat had been raced in the seventies."], answer: 1, explanation: "When the paint was stripped, 'a long section near the keel had rotted and had to be rebuilt plank by plank'." },
      { q: "What does the speaker say was the best part of the project?", options: ["Winning new trophies.", "Finishing ahead of schedule.", "The evening classes and the friends he made there.", "Learning to sail properly."], answer: 2, explanation: "The boatbuilding classes 'turned out to be the best part' — he gained a new circle of friends." },
      { q: "What is his advice to people tempted to restore a boat?", options: ["Calculate the full cost first.", "Buy the newest boat you can find.", "Hire professionals for everything.", "Do it because you will enjoy the process itself."], answer: 3, explanation: "His advice: don't do it for money or the finished boat, but 'because you'll enjoy the process itself'." },
      { q: "Who watched Kestrel return to the water?", options: ["The farmer's family.", "His work colleagues.", "The boatbuilding school teachers.", "The previous racing crew."], answer: 0, explanation: "She touched the water 'with the farmer's family watching from the quay'." }
    ] },
  { id: "fce-lis5-05", title: "Interview: Life as a Zoo Nutritionist", kind: "dialogue",
    script: "Interviewer: My guest today is Dr Priya Shah, who has what might be the most unusual job in the city: she plans the meals for over two thousand animals at the zoo. Priya, how does someone end up in this career?\nPriya: Almost by accident. I trained as a human dietician, and I was working in a hospital when the zoo advertised for someone to review the diets of their older animals. I took it as a six-month project — that was nine years ago.\nInterviewer: What does a typical day look like?\nPriya: There genuinely isn't one, which is what I love. This morning I was weighing food portions for a giraffe with a sore tooth; this afternoon I'm redesigning the penguins' fish order because our supplier is changing. The kitchen here gets through more fresh vegetables in a week than a large restaurant.\nInterviewer: Is the job mostly about keeping animals full?\nPriya: That's the common misunderstanding. The hard part isn't quantity, it's behaviour. In the wild, a bear might spend eight hours finding food. If we simply hand over a full bowl, the bear is fed but bored, and boredom causes real health problems. So we hide food, freeze it in blocks of ice, hang it from trees. The eating should take effort.\nInterviewer: Any foods that surprise people?\nPriya: Visitors are always shocked that we barely use bananas. The ones grown for humans are far sweeter than wild fruit, so for most of our monkeys they're basically dessert. Too many, and you see the same problems you'd see in people: weight gain and bad teeth.\nInterviewer: What's the most difficult animal to feed?\nPriya: Without question, our koalas. They eat only eucalyptus, but each koala has personal preferences about which type, and they'll simply refuse the wrong leaves. We grow twelve varieties on a farm two hours away just to keep them happy.\nInterviewer: A demanding audience!\nPriya: The most demanding. But when a sick animal starts eating again because of a menu we designed, there's no better feeling.",
    questions: [
      { q: "How did Priya originally come to work at the zoo?", options: ["She answered an advert for a six-month project.", "She had always dreamed of working with animals.", "The hospital transferred her there.", "She began as a volunteer keeper."], answer: 0, explanation: "The zoo advertised for someone to review older animals' diets: 'I took it as a six-month project — that was nine years ago.'" },
      { q: "According to Priya, what is the hardest part of her job?", options: ["Ordering enough vegetables every week.", "Making eating take effort, not just providing quantity.", "Cooking for two thousand animals daily.", "Working with changing suppliers."], answer: 1, explanation: "'The hard part isn't quantity, it's behaviour' — food must be hidden or frozen so eating takes effort." },
      { q: "Why does the zoo barely use bananas?", options: ["The monkeys refuse to eat them.", "They are too expensive to import.", "Cultivated bananas are too sweet and cause health problems.", "Wild fruit is easier to obtain."], answer: 2, explanation: "Bananas grown for humans 'are far sweeter than wild fruit', causing weight gain and bad teeth." },
      { q: "What makes the koalas so difficult to feed?", options: ["They only eat at night.", "They eat more than any other animal.", "Their food must be frozen in ice.", "Each one insists on particular types of eucalyptus."], answer: 3, explanation: "Each koala 'has personal preferences about which type' and refuses the wrong leaves." },
      { q: "What gives Priya the greatest satisfaction?", options: ["When a sick animal starts eating again.", "Designing the penguin fish order.", "Growing twelve varieties of eucalyptus.", "Surprising visitors with unusual facts."], answer: 0, explanation: "'When a sick animal starts eating again because of a menu we designed, there's no better feeling.'" }
    ] },
  { id: "fce-lis5-06", title: "Talk: My Week on a Silent Retreat", kind: "monologue",
    script: "Last October, I did something my friends still tease me about: I paid to spend seven days at a retreat centre in the mountains where nobody is allowed to speak. No phones, no books, no music, no eye contact even — just silence from five in the morning until nine at night, broken only by a bell for meals and meditation sessions. I should admit straight away that I didn't go searching for spiritual enlightenment. I went because I'd noticed something worrying: I couldn't finish a cup of coffee without reaching for my phone. My concentration, which used to be my professional strength — I edit legal documents for a living — had shrunk to the length of a social media video. The first two days were, frankly, awful. Without conversation or screens to distract me, my brain produced an endless replay of old arguments, embarrassing moments from school and things I should have said in meetings years ago. One woman left after breakfast on day two, and I very nearly followed her to the car park. But somewhere around the fourth day, the noise in my head began to quieten, and what replaced it surprised me. I started noticing absurdly small things with enormous pleasure — the pattern of frost on a fence post, the exact moment the valley filled with morning light. Meals became fascinating; I discovered that porridge actually has a taste if you're not scrolling while eating it. Am I a changed person? Let's not exaggerate. Within a week of returning I was checking my phone at breakfast again. But two habits have survived. I now leave my phone outside the bedroom at night, and every Sunday morning I take a walk — an hour, alone, no headphones. My concentration at work has genuinely improved, though my colleagues are less impressed by my new habit of describing frost patterns at lunch.",
    questions: [
      { q: "Why did the speaker decide to attend the retreat?", options: ["Her friends recommended it.", "She wanted a spiritual experience.", "She was worried about her shrinking concentration.", "Her employer sent her there."], answer: 2, explanation: "She noticed she couldn't finish a coffee without her phone and her professional concentration had shrunk." },
      { q: "What made the first two days difficult?", options: ["The early morning bell.", "Her mind endlessly replayed old arguments and embarrassments.", "The other guests kept breaking the silence.", "The meals were too small."], answer: 1, explanation: "Without distraction, her brain produced 'an endless replay of old arguments' and embarrassing memories." },
      { q: "What happened around the fourth day?", options: ["She followed another guest to the car park.", "She was allowed to speak at meals.", "She began editing documents again.", "Her mind quietened and she began enjoying small details."], answer: 3, explanation: "Around day four 'the noise in my head began to quieten' and she noticed small things with pleasure." },
      { q: "What does the speaker say about porridge?", options: ["It has a taste if you eat without scrolling.", "It was the only food served.", "She refused to eat it.", "It was better than at home."], answer: 0, explanation: "'Porridge actually has a taste if you're not scrolling while eating it.'" },
      { q: "Which change has lasted since the retreat?", options: ["She no longer uses a phone at all.", "She keeps her phone out of the bedroom at night.", "She meditates every morning at five.", "She eats breakfast in silence."], answer: 1, explanation: "Two habits survived: the phone stays outside the bedroom, and a weekly headphone-free walk." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
