/* FCE Prep extra bank: part1 wave 5 */
(function () {
  var BANK = [
    {"text": "She has a real ____ for languages — she speaks four fluently.", "options": ["ability", "knowledge", "gift", "practice"], "answer": 2, "explanation": "A 'gift for' something is a natural talent. 'Ability' takes 'to' + verb, and 'knowledge' takes 'of'."},
    {"text": "I didn't ____ to offend you — it was only a joke.", "options": ["mean", "suppose", "regard", "accuse"], "answer": 0, "explanation": "'I didn't mean to…' = it was not my intention. The other verbs don't fit this pattern."},
    { text: "The storm caused severe ____ to the roof of the sports centre.", options: ["damage", "harm", "injury", "hurt"], answer: 0, explanation: "'Damage' is used for things and buildings; 'injury' and 'harm' are usually for people." },
    { text: "Could you ____ me a favour and water the plants while I'm away?", options: ["make", "do", "give", "hold"], answer: 1, explanation: "The fixed collocation is 'do someone a favour'." },
    { text: "The match was postponed ____ to the heavy snow overnight.", options: ["owing", "because", "since", "despite"], answer: 0, explanation: "'Owing to' + noun explains a cause; 'because' needs 'of' before a noun." },
    { text: "She takes great ____ in keeping her garden tidy all year round.", options: ["pride", "proud", "praise", "prize"], answer: 0, explanation: "The collocation is 'take pride in something'." },
    { text: "The train was so crowded that we had to ____ all the way home.", options: ["rise", "stay", "stand", "step"], answer: 2, explanation: "'Stand' means remain on your feet; the others don't describe travelling without a seat." },
    { text: "I'm sorry, I didn't quite ____ what you said — could you repeat it?", options: ["catch", "listen", "reach", "notice"], answer: 0, explanation: "'Catch' means manage to hear; 'listen' cannot take an object this way." },
    { text: "The company plans to ____ a new model of electric scooter this spring.", options: ["invent", "launch", "discover", "found"], answer: 1, explanation: "'Launch' means to introduce a product to the market." },
    { text: "Take the medicine three times a day, ____ to the doctor's instructions.", options: ["according", "regarding", "relating", "referring"], answer: 0, explanation: "'According to' means as stated by." },
    { text: "We were completely ____ by the beauty of the sunset over the bay.", options: ["taken aback", "put off", "let down", "run over"], answer: 0, explanation: "'Taken aback' means very surprised; the others have negative meanings." },
    { text: "My brother is always ____ excuses for being late.", options: ["doing", "telling", "making", "saying"], answer: 2, explanation: "The collocation is 'make excuses'." },
    { text: "The path was ____ ice, so we walked very carefully.", options: ["filled with", "covered in", "full up", "spread on"], answer: 1, explanation: "'Covered in' describes a surface with a layer of something on it." },
    { text: "It's not worth ____ over such a small mistake.", options: ["worrying", "to worry", "worry", "worried"], answer: 0, explanation: "'It's not worth' is followed by the -ing form." },
    { text: "The teacher ____ the class into four groups for the project.", options: ["shared", "divided", "cut", "parted"], answer: 1, explanation: "'Divide into groups' is the standard collocation." },
    { text: "Can you keep a ____? I'm planning a surprise for Ana's birthday.", options: ["secret", "silence", "mystery", "quiet"], answer: 0, explanation: "The collocation is 'keep a secret'." },
    { text: "The hotel offers a free shuttle ____ to and from the airport.", options: ["voyage", "travel", "service", "movement"], answer: 2, explanation: "A 'shuttle service' is regular transport between two places." },
    { text: "He found it hard to ____ up with the faster runners in the group.", options: ["keep", "hold", "stay", "catch"], answer: 0, explanation: "'Keep up with' means to move at the same speed as others." },
    { text: "The documentary gives a fascinating ____ into life in the Arctic.", options: ["insight", "outlook", "sight", "vision"], answer: 0, explanation: "'Insight into' means a deep understanding of something." },
    { text: "I'm afraid your library books are ____ — they were due back on Monday.", options: ["overdue", "delayed", "expired", "behind"], answer: 0, explanation: "'Overdue' describes something that should have been returned earlier." },
    { text: "The children were on their best ____ when their grandparents visited.", options: ["attitude", "manner", "behaviour", "action"], answer: 2, explanation: "The fixed phrase is 'on their best behaviour'." },
    { text: "The recipe ____ of only five simple ingredients.", options: ["consists", "includes", "contains", "involves"], answer: 0, explanation: "'Consist of' means to be made up of; the other verbs take a direct object without 'of'." },
    { text: "The alarm went off, but nobody paid any ____ to it.", options: ["notice", "attention", "interest", "care"], answer: 1, explanation: "The collocation is 'pay attention to'." },
    { text: "We managed to catch the last bus by a ____ of seconds.", options: ["matter", "count", "number", "piece"], answer: 0, explanation: "'A matter of seconds' means only a few seconds." },
    { text: "She's very good at ____ with difficult customers calmly.", options: ["treating", "handling", "dealing", "managing"], answer: 2, explanation: "'Deal with' means to handle a person or problem; only 'dealing' fits with 'with'." },
    { text: "The town has ____ a lot since I lived here as a child.", options: ["changed", "turned", "varied", "moved"], answer: 0, explanation: "'Change' describes becoming different over time." },
    { text: "I can't ____ the difference between the original painting and the copy.", options: ["say", "tell", "speak", "know"], answer: 1, explanation: "'Tell the difference' is the fixed expression." },
    { text: "The festival attracts visitors from all ____ the world.", options: ["along", "over", "through", "across"], answer: 1, explanation: "The fixed phrase is 'from all over the world'." },
    { text: "He was ____ of stealing the money, but the charges were later dropped.", options: ["blamed", "charged", "accused", "arrested"], answer: 2, explanation: "'Accuse someone of something' is the correct pattern; 'charged' takes 'with'." },
    { text: "You'll need to ____ a form before you can join the gym.", options: ["fill in", "write down", "put up", "take out"], answer: 0, explanation: "'Fill in a form' means to complete it." },
    { text: "The two sides finally reached an ____ after months of talks.", options: ["agreement", "argument", "arrangement", "approval"], answer: 0, explanation: "'Reach an agreement' means to agree after discussion." },
    { text: "The smoke alarm makes a loud ____ noise when the battery is low.", options: ["beating", "beeping", "banging", "blowing"], answer: 1, explanation: "'Beeping' is the short electronic sound an alarm makes." },
    { text: "Don't ____ to conclusions before you've heard the whole story.", options: ["jump", "run", "hurry", "step"], answer: 0, explanation: "The idiom 'jump to conclusions' means to judge too quickly." },
    { text: "The job requires a driving licence and at least two years' ____.", options: ["practice", "experience", "training", "background"], answer: 1, explanation: "'Experience' is the standard word for time spent doing a job." },
    { text: "The lake ____ over completely during the coldest weeks of winter.", options: ["froze", "melted", "cooled", "hardened"], answer: 0, explanation: "'Freeze over' describes water turning to ice on the surface." },
    { text: "I'd like to ____ this opportunity to thank everyone who helped us.", options: ["catch", "take", "hold", "grab"], answer: 1, explanation: "The formal phrase is 'take this opportunity to'." },
    { text: "The film didn't ____ up to my expectations at all.", options: ["live", "reach", "come", "stand"], answer: 0, explanation: "'Live up to expectations' means to be as good as hoped." },
    { text: "There's a ____ chance of showers this afternoon, so take a jacket.", options: ["slight", "thin", "weak", "narrow"], answer: 0, explanation: "'A slight chance' means a small possibility." },
    { text: "The librarian asked us to ____ our voices down.", options: ["put", "keep", "let", "set"], answer: 1, explanation: "'Keep your voice down' means to speak quietly." },
    { text: "He has a very good ____ of humour and makes everyone laugh.", options: ["feeling", "spirit", "sense", "touch"], answer: 2, explanation: "The fixed phrase is 'sense of humour'." },
    { text: "The bridge is closed to traffic while repairs are ____ out.", options: ["worked", "brought", "carried", "taken"], answer: 2, explanation: "'Carry out repairs' means to perform them." },
    { text: "The story takes ____ in a small fishing village in Norway.", options: ["part", "place", "role", "scene"], answer: 1, explanation: "'Take place' means to happen or be set somewhere." },
    { text: "You should always read the small ____ before signing a contract.", options: ["print", "letters", "words", "writing"], answer: 0, explanation: "'The small print' means the details of a contract in tiny letters." },
    { text: "The team's victory was ____ down to excellent preparation.", options: ["set", "put", "held", "cut"], answer: 1, explanation: "'Put something down to' means to explain it as the result of." },
    { text: "The doctor advised him to cut ____ on salty snacks.", options: ["off", "out", "down", "away"], answer: 2, explanation: "'Cut down on' means to reduce the amount of something." },
    { text: "The view from the tower simply takes your ____ away.", options: ["breath", "mind", "voice", "sight"], answer: 0, explanation: "'Take your breath away' means to amaze you." },
    { text: "The museum entrance is free of ____ on the first Sunday of each month.", options: ["cost", "price", "charge", "money"], answer: 2, explanation: "'Free of charge' is the fixed phrase for costing nothing." },
    { text: "I completely lost ____ of time and missed my stop.", options: ["track", "count", "touch", "control"], answer: 0, explanation: "'Lose track of time' means to stop noticing what time it is." },
    { text: "The manager promised to look ____ the matter immediately.", options: ["after", "into", "over", "up"], answer: 1, explanation: "'Look into' means to investigate." },
    { text: "The song became popular by word of ____ long before it was on the radio.", options: ["ear", "voice", "mouth", "tongue"], answer: 2, explanation: "'Word of mouth' means information spread by people talking." },
    { text: "Heavy rain ____ the river to burst its banks.", options: ["caused", "made", "let", "forced"], answer: 0, explanation: "'Cause something to do something' is the correct pattern; 'made' would need a bare infinitive." },
    { text: "It suddenly ____ on me that I had left the oven on.", options: ["dawned", "appeared", "struck", "occurred"], answer: 0, explanation: "'It dawned on me' means I gradually realised; 'occurred' would need 'to me'." },
    { text: "There was a power ____ during the storm, and the whole street went dark.", options: ["break", "cut", "stop", "loss"], answer: 1, explanation: "A 'power cut' is an interruption to the electricity supply." },
    { text: "I'm not very ____ on seafood, to be honest.", options: ["keen", "fond", "interested", "eager"], answer: 0, explanation: "'Keen on' means liking something; 'fond' takes 'of'." },
    { text: "The two schools ____ a strong rivalry in every sport.", options: ["share", "join", "divide", "unite"], answer: 0, explanation: "'Share a rivalry' means both take part in it." },
    { text: "Her latest novel is ____ loosely on her grandmother's diaries.", options: ["based", "built", "formed", "grounded"], answer: 0, explanation: "'Based on' means using something as a starting point." },
    { text: "The mechanic said the engine was beyond ____ and not worth fixing.", options: ["repair", "hope", "recovery", "control"], answer: 0, explanation: "'Beyond repair' means too damaged to fix." },
    { text: "The audience burst ____ applause as the curtain fell.", options: ["onto", "into", "out", "over"], answer: 1, explanation: "'Burst into applause' means to suddenly start clapping." },
    { text: "The council has ____ a ban on cars in the old town.", options: ["introduced", "invented", "installed", "included"], answer: 0, explanation: "'Introduce a ban' means to bring in a new rule." },
    { text: "The players were in high ____ after winning the semi-final.", options: ["moods", "spirits", "feelings", "emotions"], answer: 1, explanation: "'In high spirits' means cheerful and excited." },
    { text: "We got ____ in traffic and missed the beginning of the play.", options: ["held", "stuck", "kept", "caught"], answer: 1, explanation: "'Get stuck in traffic' means to be unable to move." },
    { text: "The tour guide has a detailed ____ of the city's history.", options: ["knowledge", "information", "learning", "wisdom"], answer: 0, explanation: "'Knowledge of' is the standard collocation; 'information' takes 'about'." },
    { text: "She glanced at her watch and ____ that she had to leave.", options: ["remarked", "reminded", "noticed", "warned"], answer: 0, explanation: "'Remark that' means to say casually; 'remind' needs an object." },
    { text: "The trip was called off at the last ____ because of the strike.", options: ["minute", "point", "hour", "time"], answer: 0, explanation: "'At the last minute' means at the latest possible time." },
    { text: "The new law comes into ____ on the first of January.", options: ["effect", "action", "work", "power"], answer: 0, explanation: "'Come into effect' means to start applying." },
    { text: "The children were ____ absorbed in the puppet show to notice the rain.", options: ["so", "very", "too", "quite"], answer: 2, explanation: "'Too + adjective + to' means more than enough to prevent something." },
    { text: "It took her years to ____ the courage to sing in public.", options: ["pick up", "build up", "bring up", "put up"], answer: 1, explanation: "'Build up courage' means to develop it gradually." },
    { text: "The restaurant was ____ with people celebrating the festival.", options: ["packed", "loaded", "stuffed", "compressed"], answer: 0, explanation: "'Packed with people' means extremely crowded." },
    { text: "My phone battery is running ____ — can I borrow your charger?", options: ["down", "low", "out", "off"], answer: 1, explanation: "'Run low' means to have little left; 'run out' would need 'of'." },
    { text: "The coach told us to give it our best ____ in the final.", options: ["shot", "trial", "test", "aim"], answer: 0, explanation: "'Give it your best shot' means to try as hard as possible." },
    { text: "The village is only ____ by boat during the rainy season.", options: ["accessible", "available", "possible", "reachable"], answer: 0, explanation: "'Accessible' describes a place that can be reached." },
    { text: "The report ____ attention to the lack of cycle paths in the city.", options: ["draws", "pulls", "brings", "carries"], answer: 0, explanation: "'Draw attention to' means to make people notice." },
    { text: "The twins get ____ very well, even though they argue about football.", options: ["on", "up", "by", "through"], answer: 0, explanation: "'Get on (well)' means to have a good relationship." },
    { text: "I had to ____ my breath after running up six flights of stairs.", options: ["take", "hold", "catch", "keep"], answer: 2, explanation: "'Catch your breath' means to rest until you breathe normally again." },
    { text: "The price of the holiday ____ flights, meals and excursions.", options: ["contains", "includes", "consists", "involves"], answer: 1, explanation: "'Include' means to have as part of the total; 'consists' would need 'of'." },
    { text: "The singer refused to give ____ any details about her next album.", options: ["away", "out", "off", "back"], answer: 0, explanation: "'Give away details' means to reveal secrets." },
    { text: "The class was ____ silence as the results were read out.", options: ["at", "on", "in", "under"], answer: 2, explanation: "'In silence' means without speaking." },
    { text: "The bad weather ____ us from reaching the summit.", options: ["avoided", "prevented", "refused", "forbade"], answer: 1, explanation: "'Prevent someone from doing' is the correct pattern." },
    { text: "The film has an unexpected ____ that nobody sees coming.", options: ["turn", "twist", "bend", "curve"], answer: 1, explanation: "A 'twist' is a surprising change in a story." },
    { text: "The shop assistant was very ____ and found exactly what I needed.", options: ["helpful", "useful", "convenient", "practical"], answer: 0, explanation: "'Helpful' describes a person willing to help; 'useful' is for things." },
    { text: "The results are in ____ with what the scientists predicted.", options: ["order", "line", "step", "row"], answer: 1, explanation: "'In line with' means consistent with." },
    { text: "The neighbours have fallen ____ over the fence between their gardens.", options: ["off", "down", "out", "apart"], answer: 2, explanation: "'Fall out' means to argue and stop being friendly." },
    { text: "The old factory has been ____ into a modern art gallery.", options: ["turned", "changed", "moved", "grown"], answer: 0, explanation: "'Turn something into' means to change it into something different." },
    { text: "The lecture was cancelled at short ____ because the speaker was ill.", options: ["notice", "warning", "term", "signal"], answer: 0, explanation: "'At short notice' means with little warning time." },
    { text: "The team ____ a plan to raise money for the school trip.", options: ["came up with", "put up with", "got on with", "ran out of"], answer: 0, explanation: "'Come up with' means to think of an idea." },
    { text: "The mountain rescue team was ____ standby all weekend.", options: ["at", "on", "in", "by"], answer: 1, explanation: "'On standby' means ready to act if needed." },
    { text: "The scandal seriously damaged the minister's ____.", options: ["reputation", "fame", "publicity", "celebrity"], answer: 0, explanation: "'Reputation' is the general opinion people have of someone." },
    { text: "The boat trip ____ three hours, including a stop for lunch.", options: ["spends", "lasts", "passes", "goes"], answer: 1, explanation: "'Last' describes how long something continues." },
    { text: "Would you mind ____ the window? It's freezing in here.", options: ["close", "to close", "closing", "closed"], answer: 2, explanation: "'Would you mind' is followed by the -ing form." },
    { text: "The company is ____ new staff for its customer service team.", options: ["taking on", "putting on", "getting on", "carrying on"], answer: 0, explanation: "'Take on' means to employ." },
    { text: "The smell of fresh bread ____ me of my grandmother's kitchen.", options: ["remembers", "recalls", "reminds", "memorises"], answer: 2, explanation: "'Remind someone of something' is the correct pattern." },
    { text: "The road was blocked, so we had to make a ____ through the back streets.", options: ["diversion", "detour", "deviation", "digression"], answer: 1, explanation: "A 'detour' is a longer alternative route." },
    { text: "The volunteers worked around the ____ to prepare the shelters.", options: ["clock", "hour", "watch", "day"], answer: 0, explanation: "'Around the clock' means all day and all night." },
    { text: "The committee will ____ the winner's name on Friday.", options: ["announce", "advertise", "pronounce", "declare to"], answer: 0, explanation: "'Announce' means to make known publicly." },
    { text: "I only know her by ____ — we've never actually spoken.", options: ["sight", "view", "look", "sign"], answer: 0, explanation: "'Know someone by sight' means to recognise their face only." },
    { text: "The garden was ____ with weeds after months of neglect.", options: ["overgrown", "overtaken", "overcome", "overloaded"], answer: 0, explanation: "'Overgrown with weeds' describes a garden left untended." },
    { text: "He ____ a living by repairing musical instruments.", options: ["wins", "gains", "earns", "gets"], answer: 2, explanation: "'Earn a living' is the standard collocation." },
    { text: "The ferry service was ____ because of the high winds.", options: ["suspended", "expelled", "dismissed", "excluded"], answer: 0, explanation: "'Suspend a service' means to stop it temporarily." },
    { text: "The story was so moving that it brought ____ to my eyes.", options: ["tears", "drops", "water", "cries"], answer: 0, explanation: "'Bring tears to your eyes' means to make you nearly cry." },
    { text: "The plane was ____ to land when the fog suddenly lifted.", options: ["about", "near", "close", "ready"], answer: 0, explanation: "'Be about to do something' means be on the point of doing it." },
    { text: "The gallery ____ a record number of visitors last summer.", options: ["attracted", "appealed", "invited", "tempted"], answer: 0, explanation: "'Attract visitors' is the standard collocation." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part1 = QUESTIONS.part1.concat(BANK);
})();
