/* FCE Prep extra bank: part2 wave 5 */
(function () {
  var BANK = [
    {"text": "The film was so dull that we left before it came to ____ end.", "answers": ["an"], "explanation": "The fixed phrase is 'come to an end'."},
    {"text": "____ having studied all night, he still failed the test.", "answers": ["despite"], "explanation": "'Despite + -ing' introduces a contrast: Despite having studied…"},
    { text: "It took a while to get used ____ driving on the left when we moved to Malta.", answers: ["to"], explanation: "The pattern is 'get used to + -ing'; 'to' is a preposition here, not part of an infinitive." },
    { text: "There's no point ____ arguing with the referee once the decision has been made.", answers: ["in"], explanation: "The fixed pattern is 'there's no point in doing something'." },
    { text: "The concert had hardly begun ____ the lights suddenly went out.", answers: ["when"], explanation: "The structure 'hardly ... when' links two events happening almost together." },
    { text: "You'd better take an umbrella in ____ it rains later this afternoon.", answers: ["case"], explanation: "'In case' means as a precaution against something happening." },
    { text: "The new sports hall, ____ took two years to build, opened last month.", answers: ["which"], explanation: "The relative pronoun 'which' introduces a non-defining clause about a thing." },
    { text: "She's not as tall ____ her older sister, but she's a faster runner.", answers: ["as"], explanation: "The comparison 'as ... as' requires the second 'as' before the person compared." },
    { text: "We set ____ at dawn to avoid the worst of the traffic.", answers: ["off", "out"], explanation: "The phrasal verbs 'set off' and 'set out' both mean to start a journey." },
    { text: "I'd rather you ____ not mention the surprise party to anyone at work.", answers: ["did"], explanation: "After 'I'd rather you', a past form is used to talk about the present: 'I'd rather you did not'." },
    { text: "The museum is well worth ____ visit if you're ever in the area.", answers: ["a"], explanation: "The fixed phrase is 'well worth a visit'." },
    { text: "____ from a few showers in the morning, the weather was perfect all week.", answers: ["apart", "aside"], explanation: "'Apart from' (or 'aside from') means except for." },
    { text: "The higher we climbed, ____ colder the wind became.", answers: ["the"], explanation: "The comparative structure 'the higher ..., the colder ...' requires 'the' in both halves." },
    { text: "He turned ____ the job offer because it involved moving abroad.", answers: ["down"], explanation: "The phrasal verb 'turn down' means to refuse an offer." },
    { text: "By the time we arrived, most of the food ____ already been eaten.", answers: ["had"], explanation: "The past perfect 'had been eaten' shows the action happened before another past action." },
    { text: "You can borrow my laptop as ____ as you promise to return it by Friday.", answers: ["long"], explanation: "'As long as' means on condition that." },
    { text: "The manager insisted ____ seeing the report before the meeting.", answers: ["on", "upon"], explanation: "The verb 'insist' is followed by the preposition 'on' (or formal 'upon')." },
    { text: "____ of the twins wants to share a room any more.", answers: ["neither"], explanation: "'Neither of + plural noun' takes a singular verb and means not one and not the other." },
    { text: "It was only when I got home ____ I realised my keys were missing.", answers: ["that"], explanation: "The cleft structure 'It was only when ... that ...' emphasises the time." },
    { text: "The bridge was named ____ the engineer who designed it.", answers: ["after"], explanation: "'Named after someone' means given that person's name." },
    { text: "____ average, students spend three hours a day on their phones.", answers: ["on"], explanation: "The fixed phrase is 'on average'." },
    { text: "I came ____ some old photos while I was clearing out the garage.", answers: ["across", "upon"], explanation: "The phrasal verb 'come across' means to find by chance." },
    { text: "Hard ____ she tried, she couldn't open the jar.", answers: ["as", "though"], explanation: "The inverted concession 'Hard as she tried' means although she tried hard." },
    { text: "The play was called ____ at the last minute because the lead actor was ill.", answers: ["off"], explanation: "The phrasal verb 'call off' means to cancel." },
    { text: "We are looking forward ____ hearing from you soon.", answers: ["to"], explanation: "'Look forward to' is followed by a noun or -ing form; 'to' is a preposition here." },
    { text: "____ my opinion, the first version of the song was much better.", answers: ["in"], explanation: "The fixed phrase is 'in my opinion'." },
    { text: "She must ____ forgotten about our meeting; she never usually misses one.", answers: ["have"], explanation: "'Must have + past participle' expresses a confident guess about the past." },
    { text: "The instructions were far ____ complicated for most users to follow.", answers: ["too"], explanation: "'Far too + adjective' means much more than is acceptable." },
    { text: "It's high time we ____ something about the leaking roof.", answers: ["did"], explanation: "After 'it's high time', a past form refers to the present: 'it's high time we did'." },
    { text: "The village lies at the foot ____ a spectacular mountain range.", answers: ["of"], explanation: "The fixed phrase is 'at the foot of'." },
    { text: "Take your time; there's no need to make ____ your mind today.", answers: ["up"], explanation: "The phrasal verb 'make up your mind' means to decide." },
    { text: "____ it not been for the map, we would have got completely lost.", answers: ["had"], explanation: "The inverted conditional 'Had it not been for' means without/if it had not been for." },
    { text: "The company has taken ____ twenty new staff since January.", answers: ["on"], explanation: "The phrasal verb 'take on' means to employ." },
    { text: "Very few people succeed ____ giving up sugar completely.", answers: ["in"], explanation: "The verb 'succeed' is followed by 'in + -ing'." },
    { text: "The two paintings are so alike that I can't tell one ____ the other.", answers: ["from"], explanation: "'Tell one from the other' means distinguish between them." },
    { text: "____ matter how carefully you plan, something unexpected always happens.", answers: ["no"], explanation: "'No matter how' means it makes no difference how." },
    { text: "The results will be announced ____ the end of the month at the latest.", answers: ["by"], explanation: "'By + time' means not later than that time." },
    { text: "He gave up smoking two years ago and hasn't touched a cigarette ____ then.", answers: ["since"], explanation: "'Since then' refers back to the point in the past when something started." },
    { text: "____ though the ticket was expensive, the show was worth every cent.", answers: ["even"], explanation: "'Even though' introduces a strong contrast." },
    { text: "Her success is due to hard work rather ____ luck.", answers: ["than"], explanation: "The structure 'rather than' contrasts two ideas." },
    { text: "The medicine should be kept out of ____ of small children.", answers: ["reach"], explanation: "The fixed phrase is 'out of reach of'." },
    { text: "The hotel was fully booked, so we ended ____ sleeping in the car.", answers: ["up"], explanation: "The phrasal verb 'end up doing' means to finally be in a situation." },
    { text: "The teacher asked us to hand ____ our essays before Friday.", answers: ["in"], explanation: "The phrasal verb 'hand in' means to submit work." },
    { text: "You should insure the parcel in the event ____ it getting lost in the post.", answers: ["of"], explanation: "The formal phrase 'in the event of' means if something happens." },
    { text: "Not until the final whistle ____ the home fans start to celebrate.", answers: ["did"], explanation: "After negative 'Not until' at the start, the auxiliary and subject invert: 'did the fans start'." },
    { text: "She takes ____ her mother — they have exactly the same laugh.", answers: ["after"], explanation: "The phrasal verb 'take after' means to resemble an older relative." },
    { text: "The castle dates ____ to the twelfth century.", answers: ["back"], explanation: "'Date back to' means to have existed since that time." },
    { text: "There were far ____ people at the festival than the organisers expected.", answers: ["more", "fewer"], explanation: "A comparative quantifier is needed before 'people ... than'; both 'more' and 'fewer' fit grammatically." },
    { text: "____ whole, I think the changes to the timetable have been positive.", answers: ["on"], explanation: "The fixed phrase 'on the whole' means in general — here 'On (the) whole' begins the sentence." },
    { text: "I'm afraid we've run ____ of milk; could you buy some on your way home?", answers: ["out"], explanation: "The phrasal verb 'run out of' means to have none left." },
    { text: "The lecture was ____ boring that half the audience fell asleep.", answers: ["so"], explanation: "'So + adjective + that' expresses result." },
    { text: "You are not allowed to park here ____ any circumstances.", answers: ["under", "in"], explanation: "The phrase 'under no/any circumstances' means never, whatever happens." },
    { text: "The story is based ____ real events that took place in the 1950s.", answers: ["on", "upon"], explanation: "The verb 'base' is followed by 'on': 'based on real events'." },
    { text: "Could you keep an eye ____ my bag while I buy the tickets?", answers: ["on"], explanation: "'Keep an eye on' means to watch carefully." },
    { text: "____ soon as the rain stops, we'll continue the match.", answers: ["as"], explanation: "'As soon as' means immediately when." },
    { text: "He apologised for the delay, ____ was caused by an accident on the motorway.", answers: ["which"], explanation: "'Which' introduces a non-defining relative clause referring to 'the delay'." },
    { text: "My grandmother is hard ____ hearing, so speak up a little.", answers: ["of"], explanation: "The fixed phrase 'hard of hearing' means slightly deaf." },
    { text: "We'd better set an earlier deadline so ____ to leave time for corrections.", answers: ["as"], explanation: "The structure 'so as to + infinitive' expresses purpose." },
    { text: "The team pulled together and, against ____ odds, reached the final.", answers: ["the", "all"], explanation: "The phrase 'against the/all odds' means despite great difficulty." },
    { text: "I bumped ____ an old classmate at the airport yesterday.", answers: ["into"], explanation: "The phrasal verb 'bump into' means to meet by chance." },
    { text: "The recipe calls ____ two eggs, but one will do at a push.", answers: ["for"], explanation: "'Call for' means to require." },
    { text: "____ being tired after the flight, she went straight to the meeting.", answers: ["despite"], explanation: "'Despite + -ing' introduces a contrast within one sentence." },
    { text: "The bus broke down, ____ which case we would have missed the ferry anyway.", answers: ["in"], explanation: "The linking phrase 'in which case' refers back to the situation just mentioned." },
    { text: "Success in music has more to do ____ practice than talent.", answers: ["with"], explanation: "The phrase 'have to do with' means to be connected with." },
    { text: "Little ____ he know that the surprise had been planned for weeks.", answers: ["did"], explanation: "After negative adverb 'Little' at the start, subject and auxiliary invert: 'Little did he know'." },
    { text: "The shop lets you try the shoes ____ before you buy them.", answers: ["on"], explanation: "The phrasal verb 'try on' means to put clothes on to test the fit." },
    { text: "____ regards accommodation, the college offers rooms to all first-year students.", answers: ["as"], explanation: "The formal linker 'as regards' means concerning." },
    { text: "It never crossed my ____ that the email might be a trick.", answers: ["mind"], explanation: "The fixed phrase 'cross your mind' means to occur to you as a thought." },
    { text: "The plane took ____ two hours late because of fog at the airport.", answers: ["off"], explanation: "The phrasal verb 'take off' means to leave the ground." },
    { text: "She succeeded ____ her third attempt at the driving test.", answers: ["at", "on"], explanation: "We say 'at/on the third attempt' to show which try was successful." },
    { text: "There is a limit to ____ much noise the neighbours will put up with.", answers: ["how"], explanation: "'How much' introduces the clause after 'a limit to'." },
    { text: "The offer sounds too good to be true, ____ it probably is.", answers: ["so"], explanation: "'So' links the logical conclusion to the previous statement." },
    { text: "He is, ____ doubt, the finest goalkeeper of his generation.", answers: ["without"], explanation: "The phrase 'without doubt' emphasises certainty." },
    { text: "The children were told ____ no account to open the door to strangers.", answers: ["on"], explanation: "The phrase 'on no account' means absolutely not." },
    { text: "The song reminds me ____ the summer we spent by the lake.", answers: ["of"], explanation: "'Remind someone of something' means to make them think of it." },
    { text: "Rents in the city centre have gone ____ sharply over the past year.", answers: ["up"], explanation: "The phrasal verb 'go up' means to increase." },
    { text: "____ the exception of Kim, everyone agreed to the new rota.", answers: ["with"], explanation: "The phrase 'with the exception of' means apart from." },
    { text: "The teacher spoke slowly so ____ everyone could follow the instructions.", answers: ["that"], explanation: "'So that' introduces a clause of purpose." },
    { text: "The two countries finally put an end ____ the long border dispute.", answers: ["to"], explanation: "The phrase 'put an end to' means to stop something." },
    { text: "My cousin is thinking ____ opening a small bakery next spring.", answers: ["of", "about"], explanation: "'Think of/about + -ing' means to consider doing something." },
    { text: "____ first sight, the twins look identical, but their personalities are very different.", answers: ["at"], explanation: "The fixed phrase 'at first sight' means when first seen." },
    { text: "The report pointed ____ several weaknesses in the security system.", answers: ["out"], explanation: "The phrasal verb 'point out' means to draw attention to." },
    { text: "You can't rely ____ the trains running on time during the strike.", answers: ["on", "upon"], explanation: "The verb 'rely' takes the preposition 'on'." },
    { text: "Rarely ____ we see such teamwork from players so young.", answers: ["do"], explanation: "After the negative adverb 'Rarely' at the start, subject and auxiliary invert." },
    { text: "The village has changed so much that it bears no resemblance ____ the place I grew up in.", answers: ["to"], explanation: "The noun 'resemblance' takes the preposition 'to'." },
    { text: "I'll lend you the money ____ condition that you pay it back this month.", answers: ["on"], explanation: "The phrase 'on condition that' means only if." },
    { text: "The fire is thought to ____ been started by a faulty heater.", answers: ["have"], explanation: "The passive reporting structure 'is thought to have been' refers to a past event." },
    { text: "She broke the school record, ____ nobody had managed for twenty years.", answers: ["which"], explanation: "'Which' refers back to the whole previous clause." },
    { text: "The city is famous ____ its covered markets and street food.", answers: ["for"], explanation: "'Famous for' introduces the reason for fame." },
    { text: "We were about to give up ____ the engine finally started.", answers: ["when"], explanation: "'Be about to do something when...' shows an interrupted action." },
    { text: "The library is free of ____ to all residents of the town.", answers: ["charge"], explanation: "The fixed phrase 'free of charge' means costing nothing." },
    { text: "Whether we play on Saturday depends entirely ____ the weather.", answers: ["on", "upon"], explanation: "'Depend on' is the standard collocation." },
    { text: "The trainer made the squad ____ an extra lap for arriving late.", answers: ["run"], explanation: "'Make someone do something' takes the bare infinitive 'run'." },
    { text: "The picture must be worth a fortune, judging ____ the crowds around it.", answers: ["by", "from"], explanation: "'Judging by/from' introduces the evidence for a guess." },
    { text: "____ time goes by, the memories of that trip grow even fonder.", answers: ["as"], explanation: "'As time goes by' means while time passes." },
    { text: "Our neighbours are moving out at the end of the month; a young couple is moving ____.", answers: ["in"], explanation: "The phrasal verb 'move in' means to start living in a place." },
    { text: "The strike resulted ____ hundreds of flights being cancelled.", answers: ["in"], explanation: "'Result in' introduces the consequence." },
    { text: "It goes without ____ that all entries must be the writer's own work.", answers: ["saying"], explanation: "The fixed phrase 'it goes without saying' means it is obvious." },
    { text: "I didn't recognise her at first because she ____ dyed her hair.", answers: ["had"], explanation: "The past perfect 'had dyed' shows the change happened before the meeting." },
    { text: "The path was steep, and to make matters ____, it started to snow.", answers: ["worse"], explanation: "The fixed phrase 'to make matters worse' introduces an additional problem." },
    { text: "The players warmed ____ for half an hour before the match began.", answers: ["up"], explanation: "The phrasal verb 'warm up' means to prepare the body with gentle exercise." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part2 = QUESTIONS.part2.concat(BANK);
})();
