/* FCE Prep bank: reading multiple-choice (wave 8) */
(function () {
var BANK = [
  {
    id: "fce-rmc8-01",
    title: "The Bus That Went the Wrong Way",
    text: "For eleven years the number 6 bus left our village at 7.15 and reached the town centre at 7.52, and for eleven years almost nobody used it. The council ran it because the contract said they must, and twice a year somebody proposed cutting it. What saved the route was a question asked by a woman called Bern, who drove it on Tuesdays and Thursdays. She wanted to know why the timetable had been written the way it had. The answer, when the transport office eventually found the file, was that the times had been set in 2009 to connect with a train that no longer existed. The train had been withdrawn in 2013; the bus had gone on meeting it for a decade. Bern's proposal was not to add buses or spend money, but to move the departure by twenty-two minutes. At 7.37 the bus would reach the town at 8.14, which was nine minutes before the shift change at the food processing plant and four minutes before the doors of the secondary school opened. The transport office resisted, not out of stubbornness but out of caution: passenger numbers were so low that the route was already marginal, and any change carried the risk of losing the few regulars it had. Bern's answer was to ask for a trial of one school term, with the old times printed alongside the new ones for the first fortnight. In the first month, use of the route rose from an average of four passengers per journey to nineteen. By the end of the term the figure was thirty-one, and the council was discussing a second morning service. What interests me about this story is not the numbers but the eleven years. The information required to fix the route had been sitting in a filing cabinet the whole time. Nobody had asked the question because the timetable had the particular authority of things that have always been that way.",
    questions: [
      { q: "Why did the council continue to run the number 6 bus?", options: ["They were obliged to by the terms of a contract.","It was the only service to the food processing plant.","Cutting it had been rejected by the village.","It was popular with a small group of regulars."], answer: 0, explanation: "'The council ran it because the contract said they must.'" },
      { q: "What did Bern discover about the timetable?", options: ["It had never been formally approved.","It was designed to meet a train that had been withdrawn.","It had been changed several times without record.","It had been copied from a neighbouring route."], answer: 1, explanation: "The times were set in 2009 to connect with a train withdrawn in 2013; 'the bus had gone on meeting it for a decade'." },
      { q: "What was unusual about Bern's proposal?", options: ["It involved changing the route as well as the times.","It had already been tried in another village.","It required neither extra buses nor extra money.","It would have doubled the number of journeys."], answer: 2, explanation: "It was 'not to add buses or spend money, but to move the departure by twenty-two minutes'." },
      { q: "Why did the transport office hesitate?", options: ["They were planning to withdraw the route anyway.","They doubted Bern's figures were accurate.","They had no authority to alter the contract.","They feared losing the few passengers they had."], answer: 3, explanation: "The route was 'already marginal, and any change carried the risk of losing the few regulars it had'." },
      { q: "How did Bern reduce the risk of the change?", options: ["By proposing a limited trial with both timetables displayed.", "By surveying passengers before any change was made.", "By offering to drive the extra journeys herself.", "By keeping the old service running in parallel."], answer: 0, explanation: "She asked for 'a trial of one school term, with the old times printed alongside the new ones for the first fortnight'." },
      { q: "What does the writer find most striking about the episode?", options: ["That the solution required no new resources.","That an obvious problem went unquestioned for so long.","The willingness of the council to fund a second service.","The speed with which passenger numbers grew."], answer: 1, explanation: "'What interests me about this story is not the numbers but the eleven years' — nobody had asked the question." }
    ]
  },
  {
    id: "fce-rmc8-02",
    title: "Three Weeks on the Weather Ship",
    text: "I had imagined that a research vessel would be full of scientists staring at screens. In fact, for most of my three weeks aboard the Aranda, the busiest people on board were the two technicians who looked after the instruments, and the busiest thing they did was clean. Salt is the enemy of everything at sea. A sensor that has been out on the mast for a fortnight develops a fine crust that changes its readings by a fraction of a degree, and a fraction of a degree, repeated across thousands of measurements, is the difference between a useful dataset and a misleading one. My job, as the least qualified person on the ship, was to record every cleaning: which instrument, at what time, by whom, and what the reading had been immediately before and after. I thought this was busywork designed to keep a student out of the way. Dr Halme corrected me on the fourth day. Without that log, she said, we cannot tell the difference between the ocean changing and our equipment drifting, and if we cannot tell the difference, we have not measured anything at all. I have thought about that sentence a great deal since. The most memorable moment of the trip had nothing to do with instruments. On the twelfth night we passed through a bloom of luminescent plankton, and the wake of the ship glowed a pale green for as far back as we could see. Everyone came on deck, including the cook, who had not left the galley for three days. The second officer, who had been at sea for nineteen years, took photographs like a tourist. It occurred to me then that the crew's endless carefulness with salt and logs was not the opposite of that wonder but the price of it. You cannot say anything reliable about the ocean unless somebody, every single day, wipes down a sensor and writes the time in a book.",
    questions: [
      { q: "What surprised the writer about life on the research vessel?", options: ["How rough the weather was for most of the trip.","How modern the instruments were.","How little time was spent looking at data.","How few scientists were on board."], answer: 2, explanation: "The writer expected scientists 'staring at screens', but the busiest work was cleaning instruments." },
      { q: "Why is salt described as 'the enemy of everything at sea'?", options: ["It makes the deck dangerous to walk on.","It damages the electrical supply to the mast.","It corrodes the ship's structure over time.","It forms a crust that slightly alters sensor readings."], answer: 3, explanation: "A crust 'changes its readings by a fraction of a degree'." },
      { q: "What did the writer initially think of the cleaning log?", options: ["That it was a task invented to occupy a student.","That it should have been done electronically.","That it was too detailed to complete accurately.","That it duplicated work the technicians already did."], answer: 0, explanation: "'I thought this was busywork designed to keep a student out of the way.'" },
      { q: "What was Dr Halme's argument for keeping the log?", options: ["It is required by the organisation funding the voyage.","Without it, instrument drift cannot be separated from real change.","It protects the team against accusations of carelessness.","It allows equipment faults to be repaired more quickly."], answer: 1, explanation: "'We cannot tell the difference between the ocean changing and our equipment drifting.'" },
      { q: "Why does the writer mention the second officer's photographs?", options: ["To contrast the officer's behaviour with the scientists'.","To explain how the event came to be documented.","To show that even the experienced crew were moved by the sight.","To suggest the crew had little else to occupy them."], answer: 2, explanation: "Someone with nineteen years at sea 'took photographs like a tourist'." },
      { q: "What conclusion does the writer reach?", options: ["The crew value beauty more highly than measurement.","Modern instruments have made careful logging unnecessary.","Scientific work at sea is less rewarding than expected.","Routine care is what makes reliable discovery possible."], answer: 3, explanation: "The carefulness 'was not the opposite of that wonder but the price of it'." }
    ]
  },
  {
    id: "fce-rmc8-03",
    title: "Why the Library Moved Its Shelves",
    text: "When the new city librarian, Adeyemi Okonjo, arrived, the first thing he did was spend a fortnight sitting in the reading room doing nothing in particular. Staff found this unnerving. The library was under pressure: visitor numbers had fallen for six consecutive years, and the council had made it clear that the building's future depended on reversing that. Everyone assumed the new appointment would arrive with a plan involving computers, a café, or both. Instead he watched. What he noticed was that people came in, hesitated near the entrance, and then went to one of three places: the newspapers, the toilets, or straight back out again. The fiction shelves, which occupied the whole of the bright southern side of the building, were visited by a small and remarkably consistent group of about forty people. Almost nobody else went further than eight metres from the door. His conclusion was not that the library needed new services but that it was laid out as if everyone entering already knew what they wanted. He moved the returns trolley — the shelf of books other people had just brought back — from a corridor behind the desk to a position directly in the visitor's line of sight, three metres inside the entrance. The reasoning was simple: a returned book carries an implicit recommendation, and a browsing visitor who has no particular title in mind will more readily pick up something another reader has just finished than face nine thousand spines arranged by author. He also turned the first three fiction bays to face the door rather than sit end-on to it. Neither change cost anything beyond an afternoon's work. Borrowing rose eighteen per cent in the following quarter, and the proportion of loans made to people who had not borrowed anything in the previous year rose from six per cent to nearly a quarter. Okonjo is careful, in interviews, not to claim this as a general solution. What worked here, he says, was not the trolley. It was the fortnight of watching before anything was moved.",
    questions: [
      { q: "Why did the librarian's first action unsettle the staff?", options: ["He appeared to be doing nothing while the library was under threat.","He refused to discuss the council's demands.","He spent the budget before making any plans.","He criticised the layout before consulting them."], answer: 0, explanation: "He spent a fortnight 'doing nothing in particular' while numbers were falling; 'staff found this unnerving'." },
      { q: "What had staff expected the new librarian to propose?", options: ["Moving to a smaller building.","Technology, a café, or both.","Recruiting more volunteers.","Reducing the opening hours."], answer: 1, explanation: "'Everyone assumed the new appointment would arrive with a plan involving computers, a café, or both.'" },
      { q: "What did Okonjo observe about most visitors?", options: ["They spent longer in the building than expected.","They preferred the darker northern side.","They went no further than a few metres from the entrance.","They came mainly to use the newspapers."], answer: 2, explanation: "'Almost nobody else went further than eight metres from the door.'" },
      { q: "What was his diagnosis of the problem?", options: ["Staff were not approachable enough.","The stock was out of date and unattractive.","The building was too large for its readership.","The layout assumed visitors knew what they came for."], answer: 3, explanation: "It 'was laid out as if everyone entering already knew what they wanted'." },
      { q: "Why did he believe the returns trolley would work?", options: ["A recently returned book carries an implied recommendation.","It is easier to reach than the main shelves.","Returned books are usually in better condition.","It saves staff from re-shelving immediately."], answer: 0, explanation: "'A returned book carries an implicit recommendation.'" },
      { q: "What does Okonjo emphasise when discussing his success?", options: ["That the changes cost almost nothing.", "That observation, not the trolley itself, was the key.", "That the results may not last beyond a year.", "That the council deserves much of the credit."], answer: 1, explanation: "'What worked here… was not the trolley. It was the fortnight of watching before anything was moved.'" }
    ]
  },
  {
    id: "fce-rmc8-04",
    title: "The Man Who Repaired Kettles",
    text: "There is a stall at the Thursday market where a man called Petar mends small electrical appliances. He is not, as people assume, a nostalgic figure resisting the modern world. He is a former quality engineer who spent twenty-six years in a factory that made the very kettles he now takes apart, and his opinions on the subject are precise rather than sentimental. Roughly two thirds of the kettles brought to him, he says, have failed for one of three reasons, and all three are trivial: a limescale-blocked element, a switch contact worn thin, or a broken cable at the point where it enters the base. None of these requires a new appliance. What makes them expensive to fix is not the part, which usually costs less than a coffee, but the casing. Most modern kettles are sealed with plastic clips designed to be assembled by a machine in one direction and never opened again. Petar's workbench is largely a collection of tools he has made himself for getting into things that were not meant to be got into. He is careful to say that this is not a conspiracy. The clips are cheaper than screws, faster to assemble, and produce a joint that does not loosen; the designer who chose them was solving a real problem, and repairability was simply not one of the criteria they were given. The change he would like is not a ban on clips but a line in the specification: that any joint a repairer must open should be openable without destroying the part. He estimates this would add between forty and ninety cents to a kettle. On my last visit he was working on a machine from 1994 that had been brought in by the granddaughter of its original owner. It needed a cable and forty minutes. Petar charged her twelve euros and told her, with some satisfaction, that it would probably outlast anything she could buy that afternoon.",
    questions: [
      { q: "How does the writer correct a common assumption about Petar?", options: ["He did not train as an engineer.","He is not as skilled as his customers believe.","He is not opposed to modern technology.","He does not actually make a living from repairs."], answer: 2, explanation: "'He is not, as people assume, a nostalgic figure resisting the modern world.'" },
      { q: "What gives particular weight to Petar's opinions?", options: ["He has repaired more kettles than anyone in the region.","He publishes his findings for other repairers.","He advises the manufacturers directly.","He worked for years making the same appliances."], answer: 3, explanation: "He 'spent twenty-six years in a factory that made the very kettles he now takes apart'." },
      { q: "According to Petar, what makes most repairs expensive?", options: ["The difficulty of opening the casing.","The cost of testing the appliance afterwards.","The rarity of the replacement parts.","The time needed to diagnose the fault."], answer: 0, explanation: "'What makes them expensive to fix is not the part… but the casing.'" },
      { q: "Why does Petar make his own tools?", options: ["The appliances are too varied for standard tools.","The casings were never intended to be opened.","Commercial tools are too expensive for a market stall.","He prefers tools adapted to his own hands."], answer: 1, explanation: "They are 'tools he has made himself for getting into things that were not meant to be got into'." },
      { q: "What is Petar's view of the designers who chose plastic clips?", options: ["They were overruled by the sales department.","They failed to test the joints properly.","They were solving a genuine problem within their brief.","They deliberately made repair impossible."], answer: 2, explanation: "'The designer who chose them was solving a real problem, and repairability was simply not one of the criteria they were given.'" },
      { q: "What change does Petar actually want?", options: ["Longer guarantees on small appliances.","Lower prices for replacement parts.","A legal ban on sealed plastic casings.","A requirement that joints open without being destroyed."], answer: 3, explanation: "'Any joint a repairer must open should be openable without destroying the part.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
