/* FCE Prep bank: reading multiple-choice (wave 11) */
(function () {
var BANK = [
  {
    id: "fce-rmc11-01",
    title: "The Weight of a Rucksack",
    text: "On my first long walk I carried nineteen kilos for six days and arrived with an injured knee and a firm belief that I was simply not built for it. Four years later I walked the same route with eight kilos and enjoyed every hour of it. Nothing about my fitness had changed. What had changed was that somebody had made me tip the contents of the bag onto a hostel floor and account for each item aloud. The exercise is humbling. Roughly a third of what I was carrying existed to solve problems I had imagined rather than experienced: a second torch in case the first failed, a repair kit for a stove I had never once needed to repair, four hundred grams of first-aid supplies of which I could identify perhaps a quarter. The heaviest single item was a book I had carried for six days and not opened. Experienced walkers talk about the base weight, meaning everything except food, water and fuel, and they talk about it obsessively because it is the only part you control. Food and water are dictated by the distance between resupply points; the tent and the sleeping bag are dictated by the season. What is left is the accumulation of small anxieties, and each of them weighs between fifty and three hundred grams. The rule I was taught, and which I now pass on, is not to leave things behind but to write down what you actually used. After a trip, anything untouched goes on a list, and if it survives three trips untouched it stays at home unless there is a specific reason to take it. The reason clause matters. A whistle is never used and always carried. The list is a record of what happened, not a rule about what might.",
    questions: [
      { q: "What did the writer conclude after the first walk?", options: ["That they were unsuited to long-distance walking.","That the equipment was of poor quality.","That six days was too long a trip.","That the route was too difficult."], answer: 0, explanation: "'A firm belief that I was simply not built for it.'" },
      { q: "What made the difference on the second walk?", options: ["Walking with more experienced companions.","A much lighter load.","Improved fitness after four years.","Better weather conditions."], answer: 1, explanation: "Eight kilos instead of nineteen; 'nothing about my fitness had changed'." },
      { q: "What did the floor exercise reveal?", options: ["Several items were damaged or unusable.", "The bag itself was heavier than necessary.", "Much of the load addressed imagined problems.", "Food made up most of the weight."], answer: 2, explanation: "'A third of what I was carrying existed to solve problems I had imagined rather than experienced.'" },
      { q: "Why do experienced walkers focus on base weight?", options: ["It determines how fast they can walk.","It is what airlines measure.","It is the heaviest part of the load.","It is the part the walker can control."], answer: 3, explanation: "'They talk about it obsessively because it is the only part you control.'" },
      { q: "What is the rule the writer was taught?", options: ["Record what was actually used on each trip.","Never carry more than ten kilos.","Replace heavy items with lighter versions.","Pack the bag three times before leaving."], answer: 0, explanation: "'Write down what you actually used'; untouched items go on a list." },
      { q: "Why does the writer mention a whistle?", options: ["To explain how they were rescued once.","To show why some unused items must still be carried.","To give an example of an item easily forgotten.","To illustrate how light safety gear can be."], answer: 1, explanation: "'A whistle is never used and always carried' — the 'reason clause' exception." }
    ]
  },
  {
    id: "fce-rmc11-02",
    title: "The Clock That Runs on Rain",
    text: "In the courtyard of a technical college in Ljubljana there is a clock that has kept time for nineteen years without a battery, a mains supply or any solar panel. It runs on rain. The mechanism is not sophisticated, and its designer, a former student named Anja Kos, is quick to say that nothing about it is new. A funnel of roughly two square metres collects rainfall into a tank; the water drains slowly through a valve, turning a small wheel; the wheel winds a spring; the spring drives the clock. Every component would have been familiar to a millwright in 1750. What is unusual is the sizing, and this is where the interesting engineering lies. Ljubljana receives around 1,400 millimetres of rain a year, but it does not receive it evenly. There are summers with six dry weeks. Kos's calculation was not about average rainfall at all; it was about the longest credible gap, which she took from a century of records as fifty-two days, and then multiplied by one and a half. Everything else followed: the tank had to hold enough to run the clock for seventy-eight days, and the funnel had to refill that tank during a wet fortnight. The clock has stopped twice. Once in 2011, when the valve blocked with pine needles, and once in 2019, during a drought that came within nine days of exhausting the reserve. After the first stoppage a mesh was added. After the second, nothing was changed. Kos was asked whether she would enlarge the tank and said that a system which survives a one-in-forty-year event with nine days to spare is correctly sized, and that the instinct to add margin after a near miss is how simple things become complicated ones.",
    questions: [
      { q: "What is unusual about the clock?", options: ["It was built entirely by students.", "It has never needed repair.", "It runs without any conventional power source.", "It keeps time more accurately than an atomic clock."], answer: 2, explanation: "It has run 'without a battery, a mains supply or any solar panel'." },
      { q: "What does Kos say about the mechanism?", options: ["It took years to design.","It is protected by a patent.","It cannot be copied elsewhere.","It uses no new technology at all."], answer: 3, explanation: "'Every component would have been familiar to a millwright in 1750.'" },
      { q: "What figure did Kos base her design on?", options: ["The longest likely dry period.","The heaviest recorded downpour.","The clock's power consumption per day.","The city's average annual rainfall."], answer: 0, explanation: "'It was about the longest credible gap, which she took from a century of records as fifty-two days.'" },
      { q: "Why did the clock stop in 2011?", options: ["The funnel was blocked by leaves.","The valve became blocked with pine needles.","The tank developed a leak.","The spring broke under strain."], answer: 1, explanation: "'The valve blocked with pine needles.'" },
      { q: "What was done after the 2019 stoppage?", options: ["The tank was enlarged.","A backup battery was added.","Nothing was changed.","A mesh filter was installed."], answer: 2, explanation: "'After the second, nothing was changed.'" },
      { q: "What is Kos's argument against enlarging the tank?", options: ["Droughts of that severity will not recur.","The cost would exceed the clock's value.","The courtyard has no space for a larger one.","Adding margin after a near miss creates complexity."], answer: 3, explanation: "'The instinct to add margin after a near miss is how simple things become complicated ones.'" }
    ]
  },
  {
    id: "fce-rmc11-03",
    title: "Learning to Lose at Chess",
    text: "The junior club I joined at eleven had one unusual custom. After every game, the loser explained the game to the room, and the winner said nothing. Not a summary of the moves, but an account of where the game had been decided and why. If you could not identify the moment, the club's founder, a retired postman called Douglas, would ask you to sit with the board until you could. It was, I now realise, an unusually sophisticated piece of teaching disguised as an eccentricity. The obvious value is that losing becomes informative rather than merely unpleasant. The less obvious value is what it does to winning. A player who knows that their opponent will shortly explain the game in front of everyone has an incentive to win in a way that they can respect, and the club had almost no gamesmanship: no clock slamming, no theatrical sighing, none of the small cruelties that competitive children discover on their own. Douglas never forbade any of it. He simply arranged matters so that the person best placed to describe your behaviour was the person you had just beaten. I have wondered since whether the custom would survive contact with a stronger club, and I suspect not. Where the stakes are ratings and selection, few players will volunteer a clear account of their own mistake in public. Douglas would probably have said that this is an argument about what the club is for rather than about the custom. He was not producing tournament players and never pretended to be. Of the roughly sixty children who passed through in the years I was there, one became a strong county player. What the rest acquired was the habit of examining a defeat closely enough to say something true about it, which is a rarer skill than being good at chess and considerably more useful.",
    questions: [
      { q: "What happened after each game at the club?", options: ["The loser explained where the game turned.","Both players wrote down the key moves.","Douglas gave his own analysis.","The winner analysed the game aloud."], answer: 0, explanation: "'The loser explained the game to the room, and the winner said nothing.'" },
      { q: "What did Douglas do if a player could not identify the decisive moment?", options: ["He asked them to replay the game.","He had them sit with the board until they could.","He moved on to the next game.","He explained it to them privately."], answer: 1, explanation: "He 'would ask you to sit with the board until you could'." },
      { q: "What less obvious effect did the custom have?", options: ["It encouraged players to take more risks.","It improved players' opening knowledge.","It made winners behave better.","It shortened the length of games."], answer: 2, explanation: "Winners had 'an incentive to win in a way that they can respect'; the club had 'almost no gamesmanship'." },
      { q: "How did Douglas discourage bad behaviour?", options: ["By supervising every game personally.","By setting out clear rules and penalties.","By excluding repeat offenders.","By arranging who would describe your conduct."], answer: 3, explanation: "'The person best placed to describe your behaviour was the person you had just beaten.'" },
      { q: "Why does the writer doubt the custom would work elsewhere?", options: ["Players would not admit mistakes where stakes are high.","Stronger players analyse games differently.","Larger clubs have no time for it.","Coaches would object to the method."], answer: 0, explanation: "'Where the stakes are ratings and selection, few players will volunteer a clear account of their own mistake in public.'" },
      { q: "What does the writer value most from the experience?", options: ["The discipline of regular practice.","The habit of examining defeat honestly.","The friendships formed at the club.","A lasting interest in competitive chess."], answer: 1, explanation: "'The habit of examining a defeat closely enough to say something true about it.'" }
    ]
  },
  {
    id: "fce-rmc11-04",
    title: "The Restaurant With One Table",
    text: "Kenji Moriyama's restaurant seats six people at a single counter, opens four evenings a week, and has been fully booked for eleven years. Journalists who visit tend to write about scarcity, and Moriyama finds this irritating. He did not design the restaurant to be difficult to get into. He designed it around a limit he discovered when he was thirty-four and working as a sous-chef in a hotel: he could hold about six people's meals in his head at once, and above that number he began to cook by procedure rather than by attention. The distinction matters to him more than any question of style. Cooking by procedure means executing a plan made earlier; cooking by attention means noticing that this particular piece of fish, tonight, in this pan, is behaving differently from the last one. He is emphatic that the second is not superior in general. A hotel kitchen serving four hundred covers must work by procedure, and does it magnificently; the failure would be to attempt attention at that scale and deliver neither. The economics are less romantic than the philosophy. Six covers cannot support two staff, so Moriyama works alone and his wife handles bookings from home. He buys at the market each morning and the menu is written on a card at four o'clock. There is no wine list; he pours what he has. When a well-known investor offered to fund a second location with a trained successor, Moriyama declined, and the reason he gave has been quoted often enough that he is tired of it. He said that a restaurant built around one person's attention cannot be copied, because what would be copied is the room and the recipes, which are not the thing.",
    questions: [
      { q: "What annoys Moriyama about press coverage?", options: ["It misreports his cooking methods.","It ignores his wife's contribution.","It focuses on how hard it is to get a booking.","It criticises his prices."], answer: 2, explanation: "'Journalists who visit tend to write about scarcity, and Moriyama finds this irritating.'" },
      { q: "Why does the restaurant seat only six?", options: ["Licensing rules restrict the numbers.","He wanted to create exclusivity.","The premises cannot hold more.","Six is the limit of what he can cook attentively."], answer: 3, explanation: "'He could hold about six people's meals in his head at once.'" },
      { q: "What is 'cooking by procedure'?", options: ["Executing a plan made earlier.","Cooking without tasting.","Following recipes written by someone else.","Preparing dishes in advance of service."], answer: 0, explanation: "'Cooking by procedure means executing a plan made earlier.'" },
      { q: "What is his view of large hotel kitchens?", options: ["They train chefs badly.","They do procedure well and should not attempt attention.","They produce food of poor quality.","They should reduce their number of covers."], answer: 1, explanation: "They 'must work by procedure, and does it magnificently'; attempting attention at that scale would 'deliver neither'." },
      { q: "How does the restaurant operate day to day?", options: ["The menu is fixed for each season.","Bookings are taken at the door.","He works alone and writes the menu at four.","A small team prepares the menu each morning."], answer: 2, explanation: "'Moriyama works alone… the menu is written on a card at four o'clock.'" },
      { q: "Why did he refuse the investor's offer?", options: ["He did not trust the investor's motives.","He had no wish to train a successor.","The funding offered was insufficient.","A second site would copy only the room and recipes."], answer: 3, explanation: "'What would be copied is the room and the recipes, which are not the thing.'" }
    ]
  },
  {
    id: "fce-rmc11-05",
    title: "Counting Birds in the Dark",
    text: "Between March and May, a small number of volunteers across northern Europe spend their nights listening to the sky. Many migrating songbirds travel after dark, and although they cannot be seen, most species call as they fly. A recording microphone pointed upwards for eight hours produces a file in which, if you know what you are listening for, a night's migration can be counted. The technique is called nocturnal flight call monitoring, and until recently it was a niche pursuit for people with unusual ears. What has changed is not the recording but the listening. Automated classifiers can now identify the commoner species with accuracy comparable to a skilled human, which means a volunteer who once spent forty hours reviewing a week of audio can spend two. This has had an effect nobody predicted. The bottleneck moved. When analysis was the slow part, more microphones would have been useless; now that analysis is fast, the limiting factor is how many places are being recorded, and the network has grown from around ninety sites to over two thousand in six years. The picture that emerges is different from what daytime counts suggested. Migration is far more concentrated in time than anyone assumed: on the Dutch coast, a single night in late April can carry more thrushes than the preceding three weeks combined. It is also more sensitive to weather at a fine scale. A shift in wind direction of thirty degrees, sustained for a night, can move the entire front two hundred kilometres. None of this was invisible before; it was simply unmeasurable at the resolution needed. What the volunteers have built, without much funding and largely for their own interest, is the first continental record of migration by the hour rather than by the season.",
    questions: [
      { q: "Why can migrating songbirds be counted at night?", options: ["Most species call as they fly.","They land regularly to rest.","Radar picks up their movement.","They fly low enough to be seen by torchlight."], answer: 0, explanation: "'Most species call as they fly.'" },
      { q: "What has recently changed about the technique?", options: ["More species can now be recorded.","Software can identify common species automatically.","Recording is permitted in more countries.","Microphones have become far cheaper."], answer: 1, explanation: "'Automated classifiers can now identify the commoner species with accuracy comparable to a skilled human.'" },
      { q: "What unexpected effect did this have?", options: ["Accuracy fell below earlier standards.","Funding was withdrawn from the project.","The limiting factor shifted to the number of sites.","Volunteers lost interest in the work."], answer: 2, explanation: "'The bottleneck moved'; the network grew from ninety sites to over two thousand." },
      { q: "What does the data show about the timing of migration?", options: ["It has shifted later in recent years.","It is spread evenly through the spring.","It occurs mainly in the early morning.","It is concentrated into very few nights."], answer: 3, explanation: "'A single night in late April can carry more thrushes than the preceding three weeks combined.'" },
      { q: "What effect can a change in wind direction have?", options: ["It can shift the migration front by hundreds of kilometres.", "It can stop migration entirely for a week.", "It changes which species call in flight.", "It makes recordings impossible to analyse."], answer: 0, explanation: "'A shift in wind direction of thirty degrees… can move the entire front two hundred kilometres.'" },
      { q: "How does the writer summarise the volunteers' achievement?", options: ["They have secured funding for a permanent network.","They have created the first hour-by-hour record of migration.","They have identified several previously unknown species.","They have proved earlier daytime counts were wrong."], answer: 1, explanation: "'The first continental record of migration by the hour rather than by the season.'" }
    ]
  },
  {
    id: "fce-rmc11-06",
    title: "The Uniform Nobody Wanted",
    text: "When Brookvale Secondary consulted on replacing its uniform, the head teacher expected a familiar argument between those who wanted to abolish it and those who wanted to keep it. What she got instead was a survey result that nobody on the leadership team believed until it was checked twice. Eighty-one per cent of pupils wanted a uniform. Their objections were entirely to the specific one they had. The blazer cost fifty-four pounds and could be bought from a single supplier. The skirt and the trousers were cut in a way that pupils described, with some accuracy, as designed by somebody who had never worn either. The tie required a knot that took four minutes to learn and was the subject of a detention policy. None of this is about uniform in principle; it is about procurement. The school's response was to separate the two questions. A uniform would continue, but the specification was rewritten in terms of colour and type rather than supplier: navy blazer, any supplier, school badge available separately as an iron-on for three pounds. The tie was replaced with an optional one. The total cost of a full set fell from around one hundred and ten pounds to under forty for a family willing to buy in a supermarket. Two years on, the results are mixed in an instructive way. Complaints about cost have essentially disappeared, and the second-hand exchange the parents' association runs has trebled in volume because garments are now interchangeable between families. But the head teacher notes a genuine loss. When every blazer came from one supplier, the differences between a new one and a fourth-hand one were small. They are now visible, and she has not found a good answer to that.",
    questions: [
      { q: "What surprised the leadership team?", options: ["That staff were divided on the issue.","How few pupils responded to the survey.","That most pupils wanted to keep a uniform.","That parents opposed any change."], answer: 2, explanation: "'Eighty-one per cent of pupils wanted a uniform' — checked twice because it was not believed." },
      { q: "What were the pupils actually objecting to?", options: ["The rules about wearing it correctly.","Having to wear it in hot weather.","The colour scheme of the school.","The particular uniform they were given."], answer: 3, explanation: "'Their objections were entirely to the specific one they had.'" },
      { q: "What does the writer say the real issue was?", options: ["Procurement.","Comfort.","Discipline.","Tradition."], answer: 0, explanation: "'None of this is about uniform in principle; it is about procurement.'" },
      { q: "How was the specification changed?", options: ["A second approved supplier was added.","It described colour and type rather than a supplier.","Pupils were allowed to design their own.","The blazer was replaced by a sweatshirt."], answer: 1, explanation: "'Navy blazer, any supplier, school badge available separately as an iron-on.'" },
      { q: "Why has the second-hand exchange grown?", options: ["More families are unable to buy new.","Parents are required to donate old items.","Garments now work across different families.","The school subsidises the exchange."], answer: 2, explanation: "'Garments are now interchangeable between families.'" },
      { q: "What drawback does the head teacher acknowledge?", options: ["Staff find the rules harder to enforce.","The uniform looks less smart overall.","Pupils no longer wear the badge.","Differences in wear are now more visible."], answer: 3, explanation: "Differences between new and fourth-hand garments 'are now visible, and she has not found a good answer to that'." }
    ]
  },
  {
    id: "fce-rmc11-07",
    title: "A Year Without Deliveries",
    text: "The island has one shop, a population of ninety-one, and a supply boat that is supposed to come on Tuesdays. Between November and March it comes when the weather allows, which in the winter I spent there meant an average of one week in three. I had assumed this would be the defining hardship. It was not. The islanders had solved the supply problem generations ago in the only way available, which is to hold enough of everything to be indifferent to the boat, and the shop's back room contains what is essentially a strategic reserve: flour, oil, rice, tinned fish, and two chest freezers that are never allowed below half full. What the winter actually tested was something less obvious. When the boat does not come, the post does not come either, and neither do the two things the islanders miss most: fresh vegetables and visitors. The absence of visitors turned out to matter more than the absence of vegetables. A community of ninety-one people who have known each other for decades is not short of conversation, but it is short of new information, and by February the effect was tangible. Disagreements that would have dissipated in summer acquired an importance out of proportion to their content. The island's answer, which predates my visit by many years, is the Thursday hall. Every Thursday between November and March, whoever wishes to comes to the community hall, and the only rule is that the evening must contain something nobody present has done before. It has produced a Portuguese class taught by a woman who had lived in Lisbon for two years in the 1980s, a term of very poor recorder playing, and one memorable evening dedicated to the repair of a boat engine on a tarpaulin in the middle of the floor. It is not a social occasion in the usual sense. It is, quite deliberately, a supply of newness.",
    questions: [
      { q: "What did the writer wrongly expect to be the hardest thing?", options: ["The lack of reliable supplies.", "The cold and darkness.", "The absence of medical help.", "The small size of the community."], answer: 0, explanation: "The supply problem 'was not' the defining hardship; islanders keep large reserves." },
      { q: "How have the islanders solved the supply problem?", options: ["By using a second boat in winter.","By keeping large stocks at all times.","By rationing goods between households.","By fishing and growing their own food."], answer: 1, explanation: "They 'hold enough of everything to be indifferent to the boat'." },
      { q: "What did the winter actually test?", options: ["The reliability of the electricity supply.","Relations with the mainland authorities.","The community's supply of new information.","The condition of the island's buildings."], answer: 2, explanation: "'It is short of new information, and by February the effect was tangible.'" },
      { q: "What effect did the writer notice by February?", options: ["Several families left for the mainland.","The shop began to run short of staples.","People stopped attending community events.","Minor disagreements became disproportionately important."], answer: 3, explanation: "Disagreements 'acquired an importance out of proportion to their content'." },
      { q: "What is the rule of the Thursday hall?", options: ["The evening must include something new to all present.","No one may speak about island business.","Everyone must attend at least once a month.","Only islanders may take part."], answer: 0, explanation: "'The evening must contain something nobody present has done before.'" },
      { q: "How does the writer characterise the Thursday hall?", options: ["As a substitute for the missing post.","As a deliberate supply of novelty.","As an ordinary social gathering.","As a way of teaching practical skills."], answer: 1, explanation: "'It is, quite deliberately, a supply of newness.'" }
    ]
  },
  {
    id: "fce-rmc11-08",
    title: "The Photograph That Was Not Retouched",
    text: "In 2016 a picture agency circulated a photograph of a flooded street in which the reflection of a road sign was slightly wrong. The story that followed was predictable: accusations of manipulation, a trending hashtag, and an apology from a newspaper that had run it on page one. The photographer, Ilse Brandt, spent four months proving that the image was untouched. She won, in the sense that the agency reinstated her and the newspaper printed a correction of a hundred and twenty words. The reflection was wrong because the sign had been struck by a vehicle two days earlier and was bent at an angle that made no sense to anybody who had not stood in that street. What interests Brandt now is not the accusation but the speed of it. The claim of manipulation was made forty minutes after publication, by someone who had noticed something genuinely odd. That is not a bad instinct; it is a good one, applied without the second step. Her argument is that the culture of image scepticism has developed its detection reflex far faster than its verification habit, and that the two are not the same. Noticing an anomaly is easy and increasingly automated. Establishing what caused it requires a phone call to somebody who was there, and almost nobody makes it. She now teaches a short course to journalism students that consists almost entirely of exercises in which they are given a suspicious image and forbidden to publish an opinion until they have spoken to a human being connected to it. Her students report that the exercise is uncomfortable, mainly because the phone call usually takes two days and the story has moved on by then. Brandt regards that discomfort as the entire content of the course.",
    questions: [
      { q: "Why was the photograph accused of being manipulated?", options: ["The photographer had a history of editing.","It resembled an earlier image.","A reflection in it looked wrong.","The colours had been enhanced."], answer: 2, explanation: "'The reflection of a road sign was slightly wrong.'" },
      { q: "What was the actual explanation?", options: ["The water distorted the reflection.","The camera lens had a fault.","The image had been cropped unusually.","The sign had been bent by a vehicle."], answer: 3, explanation: "'The sign had been struck by a vehicle two days earlier and was bent at an angle.'" },
      { q: "What does Brandt find most significant about the episode?", options: ["How quickly the accusation was made.", "How little the newspaper apologised.", "How long the agency took to reinstate her.", "How many people shared the image."], answer: 0, explanation: "'What interests Brandt now is not the accusation but the speed of it.'" },
      { q: "How does she regard the person who raised the alarm?", options: ["As acting maliciously.", "As having a good instinct but no follow-up.", "As technically incompetent.", "As motivated by professional rivalry."], answer: 1, explanation: "'That is not a bad instinct; it is a good one, applied without the second step.'" },
      { q: "What distinction does she draw?", options: ["Between amateur and professional photography.", "Between print and online publication.", "Between noticing an anomaly and verifying it.", "Between editing and manipulation."], answer: 2, explanation: "'Noticing an anomaly is easy… Establishing what caused it requires a phone call.'" },
      { q: "Why do her students find the exercise uncomfortable?", options: ["They are asked to defend images they distrust.","The images are disturbing in content.","They must contact people who refuse to speak.","The verification takes longer than the news cycle."], answer: 3, explanation: "'The phone call usually takes two days and the story has moved on by then.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
