/* FCE Prep bank: reading multiple-choice (wave 12) */
(function () {
var BANK = [
  {
    id: "fce-rmc12-01",
    title: "The Library That Lends Tools",
    text: "In the basement of a public library in Sheffield there is a room with no books in it. It contains four hundred and twelve tools, from cordless drills to a machine for stripping wallpaper, and any member of the library may borrow one for a week in exactly the way they would borrow a novel. The idea is not new — the first tool libraries appeared in North America in the 1970s — but it took Marta Vieira four years to persuade her council to fund this one, and she is candid about which argument finally worked. It was not the environmental case, although she believes in it. It was a single figure: the average domestic electric drill is used for around thirteen minutes in its entire working life. Councillors who had listened politely to arguments about waste sat up at the thought of a cupboard in every house holding an object that would be in use for a quarter of an hour and stored for twenty years. The practical obstacles were not the ones she had expected. Theft has been negligible; in six years, eleven tools out of some nine thousand loans have failed to come back. Damage is common but cheap, and a group of retired engineers repairs most of it on Tuesday mornings. The genuine difficulty was insurance. No standard policy covered lending a circular saw to a member of the public, and the eventual solution involved a short safety briefing, a signature, and a category of tools that may only be used inside the building. The collection now grows faster than the budget, because people clearing a relative's house bring in whole workshops. Vieira refuses to measure the scheme by the number of loans. What she counts, imperfectly, is purchases avoided: at the point of borrowing, members are asked whether they would otherwise have bought the item. About half say yes. She regards that half as the entire justification, and the other half as people who now finish jobs they would have left undone.",
    questions: [
      { q: "What is unusual about the basement room?", options: ["It holds tools rather than books.","It is open only to trade members.","It was built by local volunteers.","It contains the library's oldest collection."], answer: 0, explanation: "'A room with no books in it. It contains four hundred and twelve tools.'" },
      { q: "Which argument finally persuaded the council?", options: ["The environmental benefits of sharing.","A figure showing how little a drill is used.","The success of similar schemes abroad.","The low cost of running the room."], answer: 1, explanation: "'It was not the environmental case… It was a single figure: the average domestic electric drill is used for around thirteen minutes.'" },
      { q: "What has proved to be a very minor problem?", options: ["Storage space in the basement.","Damage to expensive machines.","Tools being stolen or not returned.","Members misusing the equipment."], answer: 2, explanation: "'Theft has been negligible; in six years, eleven tools out of some nine thousand loans have failed to come back.'" },
      { q: "What was the hardest obstacle to solve?", options: ["Recruiting enough volunteers.","Persuading members to pay a fee.","Finding a supplier of spare parts.","Obtaining suitable insurance cover."], answer: 3, explanation: "'The genuine difficulty was insurance. No standard policy covered lending a circular saw to a member of the public.'" },
      { q: "Why does the collection grow so quickly?", options: ["People donate tools when clearing houses.","The council increases the budget each year.","Manufacturers supply new models free.","Members are required to donate a tool."], answer: 0, explanation: "'People clearing a relative's house bring in whole workshops.'" },
      { q: "How does Vieira judge whether the scheme works?", options: ["By the number of loans each month.","By purchases that members avoided making.","By how many tools survive five years.","By the amount of waste sent to landfill."], answer: 1, explanation: "'She refuses to measure the scheme by the number of loans. What she counts… is purchases avoided.'" }
    ]
  },
  {
    id: "fce-rmc12-02",
    title: "The Colour of the Street Lights",
    text: "When the borough of Ashfield replaced eleven thousand street lamps in 2019, the case put to residents was entirely about money. The old sodium lamps, which cast the orange glow that anyone who grew up in a British town will remember, drew four times the power of the units replacing them, and the projected saving over fifteen years ran to several million pounds. What the consultation did not mention, because nobody involved thought to raise it, was colour. The new lamps produced a light close to daylight, and within a month the council had received more complaints than the entire lighting department had logged in the previous decade. Some were about glare, which was a design problem and was largely fixed by fitting shields; the units had been aimed at the road but scattered light into bedroom windows. The complaints that proved harder to answer were about how the town felt. Residents described the light as clinical, hospital-like, and several said they had stopped walking in the evening, which was the opposite of what the brighter lamps were supposed to achieve. A separate objection arrived from an entomologist at the local university, who pointed out that the blue-rich light of the new lamps attracts night-flying insects far more strongly than sodium ever did, and that a street lamp which draws insects out of hedgerows all night is a small ecological drain repeated eleven thousand times. The eventual settlement satisfied most people. The lamps were re-fitted with warmer units, closer in tone to candlelight than to daylight, and programmed to dim by half after half past midnight. The council's lighting engineer, Dev Raman, has since advised four other boroughs, and the point he makes first is not about tone or insects. Most of the saving, he says, came from the dimming schedule rather than the lamps themselves, and any authority that installs new lamps without a dimming programme has bought the expensive half of the improvement and left the cheap half behind.",
    questions: [
      { q: "How was the change presented to residents?", options: ["As part of a national safety programme.","As an experiment that could be reversed.","As a way to reduce electricity costs.","As a response to complaints about dark streets."], answer: 2, explanation: "'The case put to residents was entirely about money.'" },
      { q: "What issue was left out of the consultation?", options: ["The time the work would take.","The disposal of the old lamps.","The cost of installing the new lamps.","The colour of the light produced."], answer: 3, explanation: "'What the consultation did not mention… was colour.'" },
      { q: "How was the glare problem solved?", options: ["By fitting shields to the units.","By turning some lamps off at night.","By lowering the height of the lamps.","By reducing the number of lamps."], answer: 0, explanation: "'Glare, which was a design problem and was largely fixed by fitting shields.'" },
      { q: "What did some residents do in response to the new light?", options: ["They complained about their electricity bills.","They stopped going out in the evening.","They installed their own lighting.","They signed a petition to the council."], answer: 1, explanation: "'Several said they had stopped walking in the evening.'" },
      { q: "What was the entomologist's concern?", options: ["Insects damage the new light fittings.","The old lamps were safer for wildlife in winter.","The new light draws insects out of hedgerows.","The lamps disturb nesting birds."], answer: 2, explanation: "'The blue-rich light of the new lamps attracts night-flying insects far more strongly than sodium ever did.'" },
      { q: "What does Raman tell other councils first?", options: ["To replace lamps gradually over several years.","That warmer lamps cost no more to run.","To consult residents about the colour.","That the dimming schedule delivers most of the saving."], answer: 3, explanation: "'Most of the saving… came from the dimming schedule rather than the lamps themselves.'" }
    ]
  },
  {
    id: "fce-rmc12-03",
    title: "The Ferry That Waits",
    text: "The ferry to Inishmore leaves at ten past four, except that it does not always leave at ten past four. If the skipper can see somebody hurrying down the hill road with a bag, he waits, and visitors who have grown up with timetables find this unsettling. A management consultant hired by the operating company in 2018 found it unacceptable, and her first report recommended a strict departure time, on the grounds that punctuality was the single measure by which every other route in the fleet was judged. Her second report, written five months later, recommended the opposite, and the reason she changed her mind is instructive. The fleet's punctuality statistic counted departures within three minutes of the scheduled time. It did not count passengers. On a route with six sailings a day, a missed boat costs a passenger twenty minutes; on this route, where there is one sailing, it costs them a day, a night's accommodation they had not planned and, quite often, a missed hospital appointment on the mainland. The consultant recalculated using the passengers' time rather than the company's and found that the skipper's habit, which delayed the boat by an average of ninety seconds, saved several hundred wasted days a year. What she could not do was write it into the operating manual, and she says this was the most interesting finding of the whole exercise. A published rule that the ferry waits would become an entitlement. Passengers would leave later, the delay would grow, and the skipper would lose the judgement that makes the practice work: he waits for the person he can already see, not for the person who telephones to say they are twenty minutes away. The company's compromise was to remove the route from the fleet punctuality table altogether and say nothing further. Eight years on, the average delay is still under two minutes, and nobody has written anything down.",
    questions: [
      { q: "What surprises visitors about the ferry?", options: ["It waits for passengers it can see coming.","It has no published timetable at all.","It often leaves earlier than advertised.","It sails only when it is full."], answer: 0, explanation: "'If the skipper can see somebody hurrying down the hill road with a bag, he waits.'" },
      { q: "What did the consultant recommend at first?", options: ["Replacing the skipper with a new crew.","A strictly enforced departure time.","An extra sailing each afternoon.","A booking system for all passengers."], answer: 1, explanation: "'Her first report recommended a strict departure time.'" },
      { q: "What was wrong with the fleet's punctuality measure?", options: ["It applied only to the largest routes.","It was calculated only once a year.","It measured departures, not passengers.","It ignored delays caused by weather."], answer: 2, explanation: "'It did not count passengers.'" },
      { q: "Why is a missed sailing so costly on this route?", options: ["The island has no accommodation available.","Tickets cannot be transferred to another day.","The alternative crossing is far more expensive.","Passengers must wait a full day for the next one."], answer: 3, explanation: "'On this route, where there is one sailing, it costs them a day.'" },
      { q: "Why did she advise against writing the practice down?", options: ["A published rule would become an entitlement.","The crew objected to a written rule.","Regulators would not have approved it.","The delay was too small to record."], answer: 0, explanation: "'A published rule that the ferry waits would become an entitlement.'" },
      { q: "What did the company finally do?", options: ["It gave the skipper a formal warning.","It took the route out of the punctuality table.","It set a maximum delay of two minutes.","It published a revised timetable."], answer: 1, explanation: "'The company's compromise was to remove the route from the fleet punctuality table altogether.'" }
    ]
  },
  {
    id: "fce-rmc12-04",
    title: "Bread That Takes Three Days",
    text: "Aled Pryce bakes about ninety loaves a day in a converted garage outside Aberystwyth, and each of them takes three days from start to finish. Almost none of that time involves him doing anything. The flour and water sit together for an hour before the starter is added; the dough rests, is folded four times over five hours, and then spends between thirty-six and forty hours in a cold room at four degrees before it is shaped and baked. Customers who visit expect to find a craftsman performing difficult manoeuvres and are usually disappointed. The skill, Pryce says, is almost entirely in judging when to do very little, and the equipment that matters most is not the oven but the refrigerator. This is why the process resisted an attempt to copy it. Three years ago a regional supermarket chain approached him about producing the same loaf at volume, and the negotiation collapsed not over money or recipes, which he offered freely, but over space. Ninety loaves resting for forty hours occupy roughly two cubic metres of chilled storage. Four thousand loaves a day would require a cold room the size of the bakery the chain had planned to build, held at a temperature no other product in it could tolerate. Their food technologists proposed the standard solution, which is to warm the dough and shorten the rest to four hours, compensating with additional yeast and a dough conditioner. Pryce did not object on principle. He agreed to taste the result and said, publicly and without malice, that it was a perfectly good loaf that was not his. What he found harder to explain was why the long rest matters at all, since the difference is not one that most people can describe. The best account he has managed is that the slow version keeps better: it is still worth eating on the third day, and a loaf that lasts three days is a different object from one that must be eaten by evening.",
    questions: [
      { q: "What does Pryce spend most of the three days doing?", options: ["Preparing the starter each morning.","Adjusting the temperature of the oven.","Very little, while the dough rests.","Shaping the loaves by hand."], answer: 2, explanation: "'Almost none of that time involves him doing anything.'" },
      { q: "Which piece of equipment does he value most?", options: ["The oven.","The scales.","The mixer.","The refrigerator."], answer: 3, explanation: "'The equipment that matters most is not the oven but the refrigerator.'" },
      { q: "Why did the supermarket negotiation fail?", options: ["Chilled space at that scale was impractical.","He could not guarantee daily supply.","He refused to reveal his recipe.","The chain offered too little money."], answer: 0, explanation: "'The negotiation collapsed not over money or recipes… but over space.'" },
      { q: "What did the food technologists suggest?", options: ["Using a different variety of flour.","Warming the dough and shortening the rest.","Buying a second cold room.","Reducing the number of loaves."], answer: 1, explanation: "'To warm the dough and shorten the rest to four hours.'" },
      { q: "How did Pryce respond to their version?", options: ["He complained to the trade press.","He argued that it was unsafe to eat.","He said it was good but not his loaf.","He refused to taste it."], answer: 2, explanation: "'It was a perfectly good loaf that was not his.'" },
      { q: "What is his best explanation of the long rest?", options: ["It makes the dough easier to shape.","It reduces the amount of yeast needed.","It gives the crust a darker colour.","The bread stays good for three days."], answer: 3, explanation: "'The slow version keeps better: it is still worth eating on the third day.'" }
    ]
  },
  {
    id: "fce-rmc12-05",
    title: "A Second Language at Sixty",
    text: "The class meets on Thursday mornings in a community centre in Leeds, and the youngest student is fifty-eight. They are learning Portuguese, most of them from scratch, and the teacher, Ana Duarte, has taught the same course to university students for eleven years. Asked which group learns faster, she gives an answer that surprises people. Over a term, she says, the older group covers less ground; over three years, the gap closes almost entirely; and the reasons have little to do with memory. The widespread belief that adult brains cannot absorb vocabulary is, she argues, largely a misreading of what is being compared. Her students at the university are immersed for twenty hours a week and have nothing else to do. Her Thursday students get ninety minutes, and some of them are caring for a parent. When she has compared learners at equal hours of exposure, the difference in vocabulary retention was small enough that she stopped reporting it. What does differ, sharply, is willingness to speak badly. A nineteen-year-old will guess at a verb ending in front of twelve strangers; a sixty-five-year-old who has spent forty years being competent at things will often wait until they are sure, and waiting until you are sure is fatal in a language class. Duarte's response is not encouragement, which she says does not work, but structure. Nobody in her class speaks to the room. They speak in pairs, then in fours, and only in the last ten minutes does anyone address everyone, by which time the sentence has been said twice already. She also refuses to correct anything in the first half of a lesson, a rule she introduced reluctantly and now regards as the most effective change she has made. Her students describe her as demanding. She points out that the demand is not accuracy, which comes later, but volume: she wants each of them talking for at least a third of the session, and she counts.",
    questions: [
      { q: "What does Duarte say about the two groups over three years?", options: ["The gap between them nearly disappears.","The older group overtakes the younger one.","Both groups stop making progress.","The younger group stays well ahead."], answer: 0, explanation: "'Over three years, the gap closes almost entirely.'" },
      { q: "Why do her university students progress faster at first?", options: ["They are tested more frequently.","They have far more hours of exposure.","They have better teaching materials.","They already know a related language."], answer: 1, explanation: "'Her students at the university are immersed for twenty hours a week and have nothing else to do.'" },
      { q: "What did she find when hours of exposure were equal?", options: ["Older learners needed more revision.","Younger learners forgot vocabulary faster.","The difference in retention was very small.","Age made no difference to pronunciation."], answer: 2, explanation: "'The difference in vocabulary retention was small enough that she stopped reporting it.'" },
      { q: "What is the real disadvantage for older learners?", options: ["They find grammar rules harder to follow.","They study alone rather than in groups.","They lose confidence after making errors.","They are unwilling to speak before they are sure."], answer: 3, explanation: "'A sixty-five-year-old… will often wait until they are sure, and waiting until you are sure is fatal in a language class.'" },
      { q: "How is her lesson organised?", options: ["Students speak in pairs before addressing the room.","Students prepare speeches in advance.","The teacher speaks only in Portuguese.","Each student answers a question in turn."], answer: 0, explanation: "'They speak in pairs, then in fours, and only in the last ten minutes does anyone address everyone.'" },
      { q: "What does she demand of her students?", options: ["Accuracy from the very first lesson.","A large amount of speaking time each session.","Two hours of homework a week.","Attendance at every single class."], answer: 1, explanation: "'She wants each of them talking for at least a third of the session, and she counts.'" }
    ]
  },
  {
    id: "fce-rmc12-06",
    title: "The Man Who Mends Benches",
    text: "There are one hundred and forty memorial benches along the river path at Bewdley, each with a small brass plate, and for eleven years a retired joiner named Peter Ellis has been repairing them without being asked. He carries a bag with screws, a chisel and a tin of preservative, and he works slowly, on average one bench a fortnight. The council's position on this has moved through three distinct stages, and the sequence says something about how institutions handle unofficial help. At first he was written to and told to stop, on the reasonable ground that an untrained person working on council property creates a liability. He replied that he had been a joiner for forty-one years and that the alternative was benches that were unsafe to sit on. Nothing happened for two years, which is the second stage and the longest one: the letters stopped, no permission was given, and both sides behaved as though the matter had been settled without either of them having conceded anything. The third stage began when a bench he had not yet reached collapsed under a visitor, who was not hurt but complained. The obvious response would have been to formalise Ellis's role, and the council did consider it. What stopped them was that a volunteer with a formal role requires training, insurance and supervision, and the officer responsible calculated that supervising one man repairing twenty-six benches a year would cost more than employing a contractor to repair all one hundred and forty. So they employed the contractor, on a three-year cycle, and Ellis continues in exactly the same way as before, unmentioned in any document. He says he does not mind, and that the plates are the reason he does it: most of the names mean nothing to him, but four of them do, and he has never told the council which four.",
    questions: [
      { q: "What does Ellis do along the river path?", options: ["He cuts back plants beside the benches.","He installs new benches for families.","He repairs memorial benches unpaid.","He records the names on the brass plates."], answer: 2, explanation: "'A retired joiner named Peter Ellis has been repairing them without being asked.'" },
      { q: "Why did the council first tell him to stop?", options: ["The benches were due to be replaced.","His repairs were of poor quality.","Residents had complained about him.","An untrained person creates a liability."], answer: 3, explanation: "'An untrained person working on council property creates a liability.'" },
      { q: "What characterised the second stage?", options: ["Nothing was said by either side.","The council inspected his work monthly.","He stopped working for two years.","Ellis was given written permission."], answer: 0, explanation: "'The letters stopped, no permission was given, and both sides behaved as though the matter had been settled.'" },
      { q: "What prompted the council to reconsider?", options: ["A newspaper article about Ellis.","A bench collapsed under a visitor.","A change of officer in the department.","An offer of funding from a charity."], answer: 1, explanation: "'A bench he had not yet reached collapsed under a visitor.'" },
      { q: "Why did they not give Ellis an official role?", options: ["Insurance for volunteers was unavailable.","He was considered too old for the work.","Supervising him would cost more than a contractor.","He refused to accept any training."], answer: 2, explanation: "'Supervising one man repairing twenty-six benches a year would cost more than employing a contractor.'" },
      { q: "Why does Ellis say he continues?", options: ["He has nothing else to occupy his time.","He hopes to be paid for the work eventually.","He wants recognition from the council.","Four of the names on the plates matter to him."], answer: 3, explanation: "'Four of them do, and he has never told the council which four.'" }
    ]
  },
  {
    id: "fce-rmc12-07",
    title: "The Club That Owns Itself",
    text: "When Ardwick Town was minutes from being wound up in 2004, four hundred supporters put in an average of six hundred pounds each and bought it. Twenty-two years later the club is still supporter-owned, still in the fourth tier, and is quoted in every discussion of football ownership as either a model or a warning, depending on who is quoting it. Both readings have something to them. The case for the model is straightforward: the club has never come close to insolvency since, its ground has been improved without being sold, and season tickets cost less in real terms than they did in 2004. The case for the warning is that Ardwick has been promoted once and relegated once and has finished, on average, eleventh. Supporters vote on any expenditure above two hundred thousand pounds, which means the club cannot move quickly in a transfer market where decisions are made in hours. Their chief executive, Ruth Ngata, describes this as a real cost rather than a misunderstanding, and refuses the argument that fan ownership would work better with fewer votes. Reduce the votes, she says, and you have an ordinary club with an unusually large mailing list. What she does dispute is the comparison being made. Critics measure Ardwick against clubs that were promoted, and the honest comparison is against the clubs that took the other road at the same moment. Of the eleven clubs in similar financial trouble that year, four no longer exist, three play in stadiums they rent from the people who sold them, and one has changed its name twice. Ngata's summary has been repeated widely enough to become a slogan she now dislikes: the members did not buy a football club that would win things, they bought a football club that would still be there. She adds, when allowed to finish, that this was a choice and not a consolation, and that the members knew exactly what they were choosing.",
    questions: [
      { q: "How was the club saved in 2004?", options: ["Supporters raised the money and bought it.","The council took ownership of the ground.","A local businessman bought it outright.","The league provided emergency funding."], answer: 0, explanation: "'Four hundred supporters put in an average of six hundred pounds each and bought it.'" },
      { q: "Which of these is given as evidence the model works?", options: ["The club has won two promotions.","The club has avoided financial collapse.","Attendances have doubled since 2004.","The club has produced several international players."], answer: 1, explanation: "'The club has never come close to insolvency since.'" },
      { q: "Why can the club not act quickly on transfers?", options: ["League rules restrict its spending.","Its budget is set a year in advance.","Members must vote on large spending.","It has no full-time scouting staff."], answer: 2, explanation: "'Supporters vote on any expenditure above two hundred thousand pounds… decisions are made in hours.'" },
      { q: "What does Ngata say about reducing the number of votes?", options: ["It would be rejected by the members.","It would breach the club's constitution.","It would speed up decisions without any loss.","It would leave an ordinary club with a big mailing list."], answer: 3, explanation: "'Reduce the votes… and you have an ordinary club with an unusually large mailing list.'" },
      { q: "What comparison does she think is fair?", options: ["With clubs in the same trouble in 2004.","With supporter-owned clubs abroad.","With the club's own record before 2004.","With clubs promoted from the fourth tier."], answer: 0, explanation: "'The honest comparison is against the clubs that took the other road at the same moment.'" },
      { q: "Why does she dislike her own best-known remark?", options: ["It suggests the members were badly advised.","It is usually cut before her main point.","It was made by someone else originally.","It was misquoted by a newspaper."], answer: 1, explanation: "She adds 'when allowed to finish' that it was 'a choice and not a consolation'." }
    ]
  },
  {
    id: "fce-rmc12-08",
    title: "The Sound of an Empty Hall",
    text: "A concert hall with nobody in it sounds nothing like the same hall with two thousand people in it, and the difference is larger than most listeners would guess. A seated audience absorbs sound, particularly at higher frequencies; clothing, hair and skin between them soak up energy that would otherwise return from the walls. In a hall tuned for a full house, an empty rehearsal can have a reverberation time nearly twice as long, which is why an orchestra that has rehearsed happily all afternoon can find the evening performance oddly dry and hear themselves less well than they expect. The standard solution is upholstery. Modern seats are designed so that the empty seat absorbs roughly as much sound as a seated person does, achieved with perforated undersides and thick padding, and in a well-designed hall the difference between empty and full is now a few per cent rather than a factor of two. There is a cost, and it is one that older halls did not pay. Heavily absorbing seats take energy out of the room whether or not anyone is sitting in them, which means the hall can never be made brighter by leaving it empty, and a chamber ensemble that would benefit from a livelier acoustic has no way to obtain one. This is where the profession divides. One school holds that a hall should be acoustically neutral and predictable, so that performers can prepare with confidence. The other holds that predictability is bought at the price of the top of the sound, and points to a handful of nineteenth-century halls with hard wooden seats that are difficult to rehearse in and extraordinary when full. Neither position is unreasonable, and the argument is rarely settled by measurement, because the quantity in dispute — what musicians mean when they say a room gives something back — has resisted every attempt to define it in numbers.",
    questions: [
      { q: "What effect does an audience have on a hall?", options: ["It increases the reverberation time.","It has little measurable effect.","It absorbs sound, especially higher frequencies.","It reflects sound towards the stage."], answer: 2, explanation: "'A seated audience absorbs sound, particularly at higher frequencies.'" },
      { q: "Why can a performance feel dry after a good rehearsal?", options: ["The lighting changes the players' hearing.","The stage is moved for the performance.","The players are tired by the evening.","The hall is much less reverberant when full."], answer: 3, explanation: "'An empty rehearsal can have a reverberation time nearly twice as long.'" },
      { q: "How do modern seats solve the problem?", options: ["They absorb about as much as a person does.","They can be adjusted for each concert.","They are removed when the hall is empty.","They reflect sound back from the stalls."], answer: 0, explanation: "'The empty seat absorbs roughly as much sound as a seated person does.'" },
      { q: "What is the drawback of such seats?", options: ["They wear out faster than wooden seats.","The hall can never be made livelier.","They are expensive to maintain.","They are uncomfortable for long concerts."], answer: 1, explanation: "'The hall can never be made brighter by leaving it empty.'" },
      { q: "What do supporters of older halls argue?", options: ["Old halls are easier to rehearse in.","Modern halls are too small for orchestras.","Predictability costs the top of the sound.","Wooden seats are cheaper to install."], answer: 2, explanation: "'Predictability is bought at the price of the top of the sound.'" },
      { q: "Why is the argument hard to settle?", options: ["Musicians rarely agree to take part.","The equipment needed is too costly.","Few halls allow acoustic testing.","The key quality cannot be measured."], answer: 3, explanation: "'What musicians mean when they say a room gives something back — has resisted every attempt to define it in numbers.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
