/* FCE Prep bank: reading multiple-choice (wave 5) */
(function () {
var BANK = [
  {
    id: "fce-rmc5-01",
    title: "The Year Without a Phone",
    text: "When journalist Sara Mendes announced that she was giving up her smartphone for a year, the reaction from colleagues fell into two camps: those who admired her, and those who quietly assumed she would give up within a fortnight. Sara herself belonged, secretly, to the second camp. Her phone was the first thing she touched in the morning and the last thing she saw at night; she navigated by it, paid with it, and — as she puts it — 'outsourced my memory to it'. The first month, she admits, was genuinely difficult, and not in the ways she had predicted. She had expected to miss social media; in fact, what nearly defeated her was the practical scaffolding of modern life. Train tickets, banking, parking meters, even the menu at her local café had migrated to screens. She bought a paper diary, a road atlas, and an alarm clock, and discovered that arranging to meet friends without the ability to send a 'running late' message required a punctuality she hadn't practised in years. Yet by the third month, something unexpected happened: her concentration returned. She read nineteen books over the year, more than the previous five years combined. Long train journeys, once a blur of scrolling, became her most productive writing time. She is careful, however, not to romanticise the experiment. Certain costs were real and never disappeared: she missed photographs of her niece growing up, was unreachable during a family emergency, and felt excluded from group decisions that happened in chats she couldn't see. Her conclusion, after returning to a smartphone this January, is deliberately unheroic. She now treats the device, she says, 'like a kitchen knife — genuinely useful, slightly dangerous, and not something I carry around all day for comfort'.",
    questions: [
      { q: "How did Sara privately feel about her own challenge at the start?", options: ["Confident she would complete it", "Doubtful she would last long", "Angry with her colleagues", "Certain it would improve her writing"], answer: 1, explanation: "She 'belonged, secretly, to the second camp' — those who assumed she would give up within a fortnight." },
      { q: "What surprised Sara most during the first month?", options: ["How much she missed social media", "How quickly her memory improved", "How many everyday services depended on phones", "How cheap paper alternatives were"], answer: 2, explanation: "What nearly defeated her was 'the practical scaffolding of modern life' — tickets, banking, menus all on screens." },
      { q: "What does the writer suggest about meeting friends without a phone?", options: ["It forced Sara to be more punctual", "It became impossible after a month", "It required a paper diary", "Her friends refused to arrange meetings"], answer: 0, explanation: "Without 'running late' messages, meetings 'required a punctuality she hadn't practised in years'." },
      { q: "What changed for Sara by the third month?", options: ["She bought a smartphone again", "Her ability to concentrate came back", "She stopped writing on trains", "She finished her first book"], answer: 1, explanation: "By the third month 'her concentration returned', and she read nineteen books that year." },
      { q: "Why does Sara mention her niece and the family emergency?", options: ["To show the real costs of the experiment", "To explain why she gave up early", "To criticise her family's phone use", "To show how her memory failed her"], answer: 0, explanation: "She is 'careful not to romanticise the experiment' — these were costs that 'were real and never disappeared'." },
      { q: "What does Sara's kitchen knife comparison suggest about phones?", options: ["They should be banned from kitchens", "They are useful tools to be handled with care", "They are more dangerous than useful", "They belong at home, not at work"], answer: 1, explanation: "She treats the phone as 'genuinely useful, slightly dangerous' — a tool, not a comfort object." }
    ]
  },
  {
    id: "fce-rmc5-02",
    title: "The Return of the Night Train",
    text: "A decade ago, the sleeper train seemed destined for the transport museum. Airlines offered flights between European capitals for the price of a restaurant meal, and railway companies, unable to compete, quietly withdrew their night services one by one. The carriages were sold, the routes deleted from timetables, and travellers barely noticed. Yet in the past few years, night trains have staged a remarkable comeback, with new routes linking cities across the continent and tickets on some services selling out weeks in advance. Several forces lie behind the revival. The most obvious is environmental: a passenger travelling by night train typically generates a small fraction of the carbon emissions of the equivalent flight, and a growing number of travellers — particularly younger ones — say this influences how they book. But environmental concern alone rarely fills a train. Operators have understood that the product itself needed rethinking. The new generation of sleepers offers private compartments with proper mattresses, charging points and breakfast included, aimed less at backpackers than at professionals who would otherwise fly. As one operator put it, 'We are not selling transport; we are selling a hotel room that arrives somewhere.' The economics remain delicate. Night trains are expensive to run: they need special carriages that earn money only once a day, staff working unsociable hours, and access to tracks in several countries, each with its own fees and rules. Critics argue that without public subsidy, many routes will struggle once the novelty fades. Supporters respond that aviation enjoys its own hidden subsidies, from untaxed fuel to publicly funded airports, and that a fair comparison would transform the railways' position. What is certain is that a mode of travel written off as obsolete has found a new audience — and that, for now at least, falling asleep in one country and waking in another has recovered its old romance.",
    questions: [
      { q: "What happened to night trains a decade ago?", options: ["They were gradually withdrawn", "They became museums", "They were replaced by new carriages", "They doubled their routes"], answer: 0, explanation: "Railway companies 'quietly withdrew their night services one by one' as cheap flights took over." },
      { q: "What does the writer say about environmental concern?", options: ["It is the only reason for the revival", "It matters mainly to older travellers", "It influences bookings but is not enough by itself", "It has been exaggerated by operators"], answer: 2, explanation: "Younger travellers say it influences bookings, 'but environmental concern alone rarely fills a train'." },
      { q: "Who are the new sleeper services mainly designed for?", options: ["Backpackers on a budget", "Professionals who would otherwise fly", "Families with young children", "Railway staff"], answer: 1, explanation: "The new sleepers are 'aimed less at backpackers than at professionals who would otherwise fly'." },
      { q: "What does the operator's comment about 'a hotel room that arrives somewhere' emphasise?", options: ["The comfort of the new product", "The high price of tickets", "The speed of night trains", "The difficulty of crossing borders"], answer: 0, explanation: "The quote illustrates rethinking the product as comfortable accommodation, not mere transport." },
      { q: "Why do critics doubt the future of night trains?", options: ["Passengers dislike sleeping on trains", "The routes cross too many countries", "The novelty has already faded", "They may not survive without public subsidy"], answer: 3, explanation: "Critics argue that 'without public subsidy, many routes will struggle once the novelty fades'." },
      { q: "How do supporters answer the critics?", options: ["By pointing to aviation's hidden subsidies", "By promising cheaper tickets", "By proposing to tax train fuel", "By building private airports"], answer: 0, explanation: "Supporters respond that 'aviation enjoys its own hidden subsidies, from untaxed fuel to publicly funded airports'." }
    ]
  },
  {
    id: "fce-rmc5-03",
    title: "The Sound Collector",
    text: "For the past nine years, Ivo Marsh has been recording the sounds of our town before they disappear. It began by accident. Testing a second-hand microphone in 2016, he captured the Thursday fish van's distinctive three-note horn — a sound that vanished for good when the van stopped coming the following month. 'I played the file back and realised I owned the only copy of something everyone in this town knew by heart,' he says. 'That felt like a responsibility.' Since then, Marsh has built an archive of more than two thousand recordings: the old swimming pool's diving board, the level-crossing bell replaced in 2019 by a silent barrier, the particular echo of the covered market before its roof was rebuilt. He is careful to distinguish what he does from nostalgia. 'I'm not saying the town was better when the crossing bell rang. Some of these sounds drove people mad. I'm saying it was different, and difference is worth documenting.' The archive nearly ended two years ago when Marsh's hard drives failed within a week of each other; he lost forty recordings and now keeps copies in three places, including the town library, which added the collection to its local history section last year. That partnership has changed the project's direction. Librarians noticed that elderly visitors, including several with memory difficulties, responded strongly to the recordings — one woman who rarely spoke described her first job in detail after hearing the market echo. Marsh now runs monthly listening sessions at the library, though he resists calling them therapy. 'I collect sounds,' he says. 'What people find in them is their own business.' His current worry is quieter than a failing hard drive: the town is running out of distinctive sounds to record. 'Everywhere is starting to sound like everywhere else. That's the recording I can't make — the sound of sameness arriving.'",
    questions: [
      { q: "How did Marsh's project begin?", options: ["The fish van driver asked him to record the horn", "He recorded a sound by chance while testing equipment", "The library asked him to document the town", "He wanted to preserve the covered market"], answer: 1, explanation: "It 'began by accident' when he was 'testing a second-hand microphone' and captured the fish van's horn." },
      { q: "Why did the fish van recording feel important to Marsh?", options: ["He possessed the only copy of a familiar sound", "It was his first successful recording", "The van driver had become a friend", "It proved his microphone worked well"], answer: 0, explanation: "He realised he 'owned the only copy of something everyone in this town knew by heart'." },
      { q: "How does Marsh answer the charge of nostalgia?", options: ["He admits the town was better in the past", "He says annoying sounds are not worth keeping", "He argues difference deserves recording, not praise", "He claims young people also enjoy the archive"], answer: 2, explanation: "He is 'not saying the town was better', but that 'it was different, and difference is worth documenting'." },
      { q: "What changed after the hard drives failed?", options: ["Marsh stopped adding new recordings", "The library rebuilt the lost recordings", "Marsh gave the whole archive to the library", "Copies are now stored in several locations"], answer: 3, explanation: "He lost forty recordings and 'now keeps copies in three places, including the town library'." },
      { q: "What did librarians notice about the recordings?", options: ["Older visitors reacted strongly to them", "They attracted new members to the library", "They were the most borrowed local history items", "Children used them for school projects"], answer: 0, explanation: "Librarians noticed that 'elderly visitors... responded strongly to the recordings', like the woman who described her first job." },
      { q: "What is Marsh's current concern?", options: ["His equipment is becoming outdated", "Towns are losing their distinctive sounds", "The library may end the partnership", "The listening sessions feel too much like therapy"], answer: 1, explanation: "His worry is that 'everywhere is starting to sound like everywhere else' — the town is running out of distinctive sounds." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
