/* FCE Prep bank: reading multiple-choice (wave 17) */
(function () {
var BANK = [
  {
    id: "fce-rmc17-01",
    title: "The Riders Who Work for Nothing",
    text: "Between seven in the evening and six in the morning, blood, milk for premature babies, surgical instruments and test samples move between hospitals in most parts of Britain on the back of motorcycles ridden by volunteers. The groups that do this are charities, they own their machines or are lent them, and no rider is paid. The service exists because hospitals need transport at night that they cannot justify staffing for. A courier company charges by the job and must cover a driver waiting to be called; a hospital that needs three deliveries on Tuesday and none on Wednesday is a poor customer, and the cost of a taxi to carry a single sample across a county at two in the morning is difficult to defend at any budget meeting. What the volunteers supply is not really transport. It is availability. Riders take a shift, stay at home with a phone, and go when called, which may be four times in a night or not at all. The rules are stricter than most people expect. Riders must hold an advanced qualification, machines are inspected, and the groups are emphatic in public and in private that this is not an emergency service: nobody uses lights or sirens, nobody exceeds a speed limit, and a rider who treats it as a race is removed. Marc Devlin, who has ridden for eleven years and now trains new volunteers, says the hardest thing to teach is that the urgency is the hospital's and not the rider's. Recruitment is not difficult; retention over five years is. What keeps people, in his experience, is not the sense of being useful, which fades, but the fact that the shift is genuinely bounded. A volunteer knows exactly what is being asked, when it starts and when it ends, which he contrasts with the open-ended commitments that exhaust people in other charities and that he has seen drive away better volunteers than himself.",
    questions: [
      { q: "What do the volunteers transport?", options: ["medical items between hospitals at night","patients who cannot travel by ambulance","staff working late shifts","equipment for community clinics"], answer: 0, explanation: "'blood, milk for premature babies, surgical instruments and test samples move between hospitals'" },
      { q: "Why do hospitals rely on them?", options: ["they can carry heavier loads","night transport is hard to justify staffing for","commercial couriers refuse the work","they arrive faster than any other transport"], answer: 1, explanation: "'hospitals need transport at night that they cannot justify staffing for'" },
      { q: "What do the volunteers really provide?", options: ["additional staff for busy wards","a cheaper alternative to taxis","availability rather than transport itself","a service for rural areas only"], answer: 2, explanation: "'It is availability.'" },
      { q: "What do the groups insist about the service?", options: ["riders must be under a certain age","every journey must be logged in advance","only local hospitals may be served","it is not an emergency service"], answer: 3, explanation: "'this is not an emergency service: nobody uses lights or sirens'" },
      { q: "What does Devlin find hardest to teach?", options: ["that the urgency belongs to the hospital","how to plan the fastest route","the correct handling of samples","how to maintain the machines"], answer: 0, explanation: "'the urgency is the hospital's and not the rider's'" },
      { q: "Why do volunteers stay, in his experience?", options: ["the training is enjoyable in itself","the commitment has clear limits","they are recognised publicly","the work varies from night to night"], answer: 1, explanation: "'the shift is genuinely bounded'" }
    ]
  },
  {
    id: "fce-rmc17-02",
    title: "The Village Turbine",
    text: "The wind turbine above Cwm Ffynnon is owned by four hundred and six people, almost all of whom live within sight of it, and this fact rather than the engineering is what makes it interesting. Community energy schemes have a poor reputation for delivery: they take years, they are defeated by grid connection costs, and roughly half the projects begun in Britain since 2010 never generated a unit. Cwm Ffynnon took nine years from first meeting to first output. Its treasurer, Nia Bowen, is precise about where the nine years went, because she thinks the delays are misunderstood. Planning permission took eleven months, which is unremarkable. The grid connection quotation, which arrived at a figure that would have ended the project, took two years to renegotiate and was reduced only because a neighbouring scheme was refused and released capacity. Raising the money took three years of asking the same people repeatedly. Bowen says the standard account of local opposition, in which a village divides over the view from the hill, did not really happen here, and that this was not luck but sequence: the group spent its first two years asking what the village wanted from any income before choosing a site, so the argument about the turbine occurred after the argument about the money rather than before it. The scheme now returns about ninety thousand pounds a year, of which the members receive a modest interest payment and the remainder goes to a fund controlled by a committee elected at a public meeting. It has paid for a minibus, insulation for eleven houses and, in the year electricity prices rose sharply, direct payments to households. Bowen regards the last of these as the decision that secured the scheme's future, and adds that the committee argued about it for two months, which she also regards as the point.",
    questions: [
      { q: "What makes the turbine unusual?", options: ["it was built without planning permission","it supplies only the village itself","it is owned by hundreds of local people","it is the largest in the region"], answer: 2, explanation: "'owned by four hundred and six people, almost all of whom live within sight of it'" },
      { q: "What is said about community energy schemes generally?", options: ["they rarely obtain planning permission","they are cheaper to build than commercial ones","they usually face strong local opposition","about half never generate anything"], answer: 3, explanation: "'roughly half the projects begun in Britain since 2010 never generated a unit'" },
      { q: "Which stage caused the longest delay?", options: ["renegotiating the grid connection","choosing a suitable site","selecting the turbine itself","obtaining planning permission"], answer: 0, explanation: "'took two years to renegotiate'" },
      { q: "Why was there little local opposition?", options: ["the turbine is unusually quiet","the money was discussed before the site","the site is not visible from the village","residents were paid for their support"], answer: 1, explanation: "'the group spent its first two years asking what the village wanted from any income before choosing a site'" },
      { q: "How is most of the income used?", options: ["it repays the original loan","it is reinvested in a second turbine","it goes to a fund controlled by an elected committee","it is shared equally among members"], answer: 2, explanation: "'the remainder goes to a fund controlled by a committee elected at a public meeting'" },
      { q: "Which decision does Bowen think secured its future?", options: ["insulating eleven houses","raising the interest paid to members","buying the minibus","paying households directly when prices rose"], answer: 3, explanation: "'direct payments to households. Bowen regards the last of these as the decision that secured the scheme's future'" }
    ]
  },
  {
    id: "fce-rmc17-03",
    title: "Learning to Read at Thirty-Eight",
    text: "About one adult in six in England reads at or below the level expected of an eleven-year-old, and the majority of them are in work. This last point is the one that surprises people and it explains a good deal about why the problem is invisible. An adult who cannot read well does not usually announce it. They develop an elaborate and exhausting set of arrangements: a partner who fills in forms, a claim to have forgotten their glasses, a job chosen partly because it involves little paperwork, and an alertness to any situation in which reading might suddenly be required. Vic Anand, who tutors adults through a charity in Leicester, says the first session is never about reading. It is about the fact that the learner has walked through the door, which many attempt several times before managing. His learners are typically in their thirties and forties and almost all of them describe a specific event that pushed them into it. A child who has started to notice. A promotion that would require a written report. One man who came to him had been offered a supervisor's job three times over eleven years and had refused it three times without explaining why. The teaching itself is not mysterious and uses much the same phonics-based approach as a primary school, but the pace is different and so are the materials, since an adult who is asked to read about a cat on a mat correctly concludes that they are being treated as a child. Anand uses letters from the council, safety notices, the learner's own payslip. Progress is fast at first and then slows sharply, and he warns about this in advance for the same reason a swimming teacher would. His completion rate is around sixty per cent, which he says is high for the sector and which he refuses to describe as a success, on the grounds that four in ten people who found the courage to come through the door did not get what they came for.",
    questions: [
      { q: "What surprises people about adults with low literacy?", options: ["most of them have jobs","most of them are elderly","most live in large cities","most left school very early"], answer: 0, explanation: "'the majority of them are in work'" },
      { q: "How do such adults usually cope?", options: ["they avoid work with any writing","they rely on elaborate arrangements to hide it","they use technology to read for them","they ask colleagues openly for help"], answer: 1, explanation: "'They develop an elaborate and exhausting set of arrangements'" },
      { q: "What does Anand say about the first session?", options: ["it establishes the learner's reading level","it is usually the hardest to teach","it is not about reading at all","it decides whether the learner can continue"], answer: 2, explanation: "'the first session is never about reading'" },
      { q: "Why did one man refuse promotion three times?", options: ["he did not want extra responsibility","the pay increase was too small","he was planning to leave the company","he would have had to write reports"], answer: 3, explanation: "'A promotion that would require a written report.'" },
      { q: "Why does he avoid children's materials?", options: ["adults conclude they are being treated as children","they are too expensive to buy","they contain unfamiliar vocabulary","the charity does not supply them"], answer: 0, explanation: "'an adult who is asked to read about a cat on a mat correctly concludes that they are being treated as a child'" },
      { q: "Why does he refuse to call his rate a success?", options: ["other tutors achieve better results","four in ten learners still leave without what they came for","the figure has fallen in recent years","completion is measured inconsistently"], answer: 1, explanation: "'four in ten people who found the courage to come through the door did not get what they came for'" }
    ]
  },
  {
    id: "fce-rmc17-04",
    title: "The Invigilator",
    text: "For three weeks each summer Barbara Lennox stands at the front of a sports hall and does almost nothing, which is a description of the job she uses herself and defends carefully. Invigilators are not teachers, are usually not employed by the school for the rest of the year, and are trained principally in what not to do. They may not explain a question. They may not indicate that a candidate has missed a page, express encouragement, or answer anything except a query about the paper being defective, and the reason for each of these rules is the same: a candidate who receives help that others do not has been advantaged, however small the help and however kindly meant. Lennox says the rule people find hardest to accept is the one about distress. A sixteen-year-old crying quietly at a desk may be comforted, taken out and looked after, and may not be given more time unless a documented arrangement already exists, because the alternative is a system in which the calm are penalised. What the job actually consists of, she says, is noticing. An invigilator who is genuinely watching will spot a candidate who has stopped writing entirely twenty minutes before the end, one who is on the wrong paper, one whose desk has been placed where the sun will move onto it at ten past two, and the mobile phone that its owner has forgotten is in a blazer pocket, which is the commonest cause of a serious penalty and is almost never deliberate. Lennox reckons she prevents more damage by the phone announcement, made slowly and twice, than by anything else she does. Asked whether the work is dull, she says that it is, that this is the point, and that an invigilator who finds it interesting is probably doing something they should not be. She has worked twenty-six seasons and reported four incidents, three of which were phones.",
    questions: [
      { q: "How does Lennox describe her job?", options: ["marking papers as they are handed in","preparing the hall before each session","standing at the front doing almost nothing","supervising teachers during examinations"], answer: 2, explanation: "'stands at the front of a sports hall and does almost nothing'" },
      { q: "What are invigilators mainly trained in?", options: ["how to detect cheating","examination regulations for each subject","first aid and emergency procedures","what they must not do"], answer: 3, explanation: "'are trained principally in what not to do'" },
      { q: "Why may a distressed candidate not be given extra time?", options: ["otherwise calm candidates are penalised","there is no way to record the extra time","the school would have to be informed","the rules cannot be changed during a paper"], answer: 0, explanation: "'the alternative is a system in which the calm are penalised'" },
      { q: "What does she say the job really involves?", options: ["managing the timing precisely","noticing things","keeping the room silent","checking documents carefully"], answer: 1, explanation: "'What the job actually consists of, she says, is noticing.'" },
      { q: "What causes most serious penalties?", options: ["notes hidden in equipment","working after time is called","a phone forgotten in a pocket","candidates talking to each other"], answer: 2, explanation: "'the mobile phone that its owner has forgotten is in a blazer pocket, which is the commonest cause of a serious penalty'" },
      { q: "What does she say about the work being dull?", options: ["most invigilators leave for that reason","it varies greatly between schools","it becomes interesting with experience","being dull is exactly the point"], answer: 3, explanation: "'she says that it is, that this is the point'" }
    ]
  },
  {
    id: "fce-rmc17-05",
    title: "Who Names the Streets",
    text: "When a hundred and forty houses were built on the old quarry site at Draymoor, somebody had to decide what the six new streets would be called, and the process that followed is more constrained than most people imagine. Street naming is a legal function of the local council, not of the developer, although developers usually propose. The proposals are checked against a set of rules that exist because of the ambulance service. There may not be another street of the same or a similar name anywhere in the postal area, which rules out most of the obvious ideas immediately. Names that sound alike when spoken over a radio are rejected even where the spelling differs. Names beginning with the same three letters as an existing street in the same town are discouraged, and anything that could be misheard as a word used in emergency communication is refused outright. What remains is narrower than a committee expects, and the officer at Draymoor rejected the developer's first list of six in a single afternoon. The second constraint is more recent and more argued about. Many councils now have a policy on commemorative naming, requiring that a person be dead, that they have a documented connection to the area, and that the family be consulted. These rules were introduced after a series of awkward reversals elsewhere, and their effect is that new streets are named after geography and history rather than people. Draymoor's streets are called after the quarry's rock faces, which were named by the men who worked them and appear on a map of 1911. The officer responsible says this was not a difficult decision because the alternative proposals were a list of trees, none of which grow there. She adds that residents will attach meaning to whatever the streets are called within about two years, and that the naming matters far less to them than it does to everybody arguing about it beforehand.",
    questions: [
      { q: "Who has the legal power to name streets?", options: ["the local council","the developer of the site","the postal service","the county surveyor"], answer: 0, explanation: "'Street naming is a legal function of the local council'" },
      { q: "Why do the naming rules exist?", options: ["to make maps easier to print","because of the ambulance service","to satisfy planning law","to preserve local history"], answer: 1, explanation: "'The proposals are checked against a set of rules that exist because of the ambulance service.'" },
      { q: "Which names are rejected outright?", options: ["names longer than two words","names already used in another county","names resembling emergency terms","names of living local people"], answer: 2, explanation: "'anything that could be misheard as a word used in emergency communication is refused outright'" },
      { q: "What happened to the developer's first list?", options: ["it was accepted with two changes","it was referred to a committee","it was withdrawn by the developer","all six names were rejected"], answer: 3, explanation: "'the officer at Draymoor rejected the developer's first list of six in a single afternoon'" },
      { q: "What do commemorative naming policies require?", options: ["the person to be dead and locally connected","approval from the county council","that the name has never been used","a public vote in the area"], answer: 0, explanation: "'requiring that a person be dead, that they have a documented connection to the area'" },
      { q: "What does the officer say about residents?", options: ["they were consulted at every stage","they attach their own meaning within a couple of years","they preferred the list of trees","they usually object to historical names"], answer: 1, explanation: "'residents will attach meaning to whatever the streets are called within about two years'" }
    ]
  },
  {
    id: "fce-rmc17-06",
    title: "The Piano in the School Hall",
    text: "A piano contains something over two hundred strings held at a combined tension of around eighteen tonnes, pulling constantly against a wooden frame that responds to every change in the air around it. This is why pianos go out of tune without being played and why the instrument in a school hall is almost always the worst-treated one in the district. Ilse Brenner tunes about six hundred pianos a year, of which perhaps eighty are in schools, and she says the damage is rarely caused by children. It is caused by the heating, which comes on in October and turns off in April, dropping the humidity in the hall to a level at which the soundboard shrinks and the tuning collapses within days. A piano tuned in November in an unhumidified hall will be noticeably wrong by Christmas whatever anybody does to it, and Brenner spends a good deal of her time explaining to business managers that they are not being sold a service that failed. Her advice, when asked, is usually not to tune the piano. It is to spend a fraction of the money on a humidifier fitted inside the case, which costs about a fifth of the annual tuning bill and does more for the instrument than tuning does. She estimates that about one school in ten takes this advice, and that the obstacle is not cost but the fact that a humidifier does not appear on any inspection list while a tuned piano does. The instruments themselves she describes with some affection. School pianos are usually old, frequently better made than anything the school could afford now, and occasionally remarkable: she has found two in the last decade that were worth more than the buildings they stood in, both of which had been marked for disposal because the case was scratched.",
    questions: [
      { q: "Why do pianos go out of tune when unplayed?", options: ["dust affects the moving parts","the strings stretch over time","the wooden frame responds to the air","the tension gradually increases"], answer: 2, explanation: "'a wooden frame that responds to every change in the air around it'" },
      { q: "What causes most damage to school pianos?", options: ["insufficient tuning","careless handling by pupils","being moved between rooms","the heating and its effect on humidity"], answer: 3, explanation: "'It is caused by the heating'" },
      { q: "What happens to a piano tuned in November?", options: ["it will be noticeably wrong by Christmas","it stays in tune until the spring","it improves as the hall warms up","it must be retuned by January at the latest"], answer: 0, explanation: "'A piano tuned in November in an unhumidified hall will be noticeably wrong by Christmas'" },
      { q: "What does Brenner usually advise schools to buy?", options: ["a thermometer for the hall","a humidifier fitted inside the case","a cover for the instrument","a cheaper tuning contract"], answer: 1, explanation: "'to spend a fraction of the money on a humidifier fitted inside the case'" },
      { q: "Why do few schools follow her advice?", options: ["staff do not know how to use it","a humidifier is not on any inspection list","the equipment is difficult to obtain","it costs more than tuning"], answer: 2, explanation: "'a humidifier does not appear on any inspection list while a tuned piano does'" },
      { q: "What does she say about the instruments themselves?", options: ["they are unsuitable for teaching","they are usually too old to repair","most should be replaced with digital ones","some are worth more than expected"], answer: 3, explanation: "'she has found two in the last decade that were worth more than the buildings they stood in'" }
    ]
  },
  {
    id: "fce-rmc17-07",
    title: "Keeping the Path Open",
    text: "A public footpath in England exists whether or not anybody can walk along it. The right is recorded on a map held by the county council, and it does not lapse because a hedge has grown across it, a farmer has ploughed it or a gate has been locked for twenty years. What does happen, reliably, is that a path nobody uses becomes a path nobody can use, and then a path nobody remembers. The volunteers who prevent this are organised by parish, walk their allocated paths several times a year, and report obstructions to the council, which has a legal duty to act and, in most counties, a budget that assumes it will not have to very often. Ray Whitcombe has covered the same eleven paths near his village since 2004. He is careful to describe the work accurately, because it is often romanticised. Most of what he reports is not a dispute with a landowner. It is a broken stile, a missing waymark, a fallen ash, a stretch that floods every winter and needs a plank. Genuine obstruction is rare and, when it occurs, is usually the result of a farm changing hands: the new owner has bought a field and does not know a path crosses it, and a conversation resolves it more often than a letter from the council does. Where it is deliberate, the process is slow and Whitcombe has been through it twice, one case taking four years. His stronger view concerns paths that are legally open and practically lost. A route that crosses three fields of standing crops each August is not blocked, but a family with a pushchair will turn back, and a right that is only exercised by the determined is, he thinks, in the process of quietly disappearing. He walks those ones deliberately, in company, with a camera, and says the point is not to win an argument but to keep the line of the path visible in the grass.",
    questions: [
      { q: "What is true of a public footpath?", options: ["the right remains even if the path is blocked","it lapses if unused for twenty years","it must be maintained by the landowner","it can be closed by the parish council"], answer: 0, explanation: "'it does not lapse because a hedge has grown across it'" },
      { q: "What does the writer say happens to unused paths?", options: ["they are re-routed by the council","they become impossible to use and then forgotten","they are recorded as private","they are absorbed into neighbouring fields"], answer: 1, explanation: "'a path nobody uses becomes a path nobody can use, and then a path nobody remembers'" },
      { q: "What does Whitcombe mostly report?", options: ["landowners refusing access","errors on the official map","damaged stiles and fallen trees","walkers straying from the route"], answer: 2, explanation: "'It is a broken stile, a missing waymark, a fallen ash'" },
      { q: "What usually causes genuine obstruction?", options: ["disputes over the map's accuracy","damage caused by heavy machinery","landowners objecting to walkers","a farm changing hands"], answer: 3, explanation: "'is usually the result of a farm changing hands'" },
      { q: "What concerns him more than blocked paths?", options: ["routes that are open but nobody can realistically use","paths that are unsafe in winter","the cost of repairs to the council","the loss of old waymarks"], answer: 0, explanation: "'A route that crosses three fields of standing crops each August is not blocked, but a family with a pushchair will turn back'" },
      { q: "Why does he walk those routes deliberately?", options: ["to gather evidence for a legal case","to keep the line of the path visible","to encourage others to join him","to check the crops are not damaged"], answer: 1, explanation: "'the point is not to win an argument but to keep the line of the path visible in the grass'" }
    ]
  },
  {
    id: "fce-rmc17-08",
    title: "Where the Donated Clothes Go",
    text: "A charity shop in a medium-sized town receives about four tonnes of clothing a year and sells, on the shop floor, perhaps a fifth of it. What happens to the rest is the part of the system donors know least about and would probably want to know most. Items that cannot be sold locally are sorted into grades. The best of what is left goes to other shops in the chain where it will sell better, which is why a jacket donated in one town frequently appears in another. Below that, clothing is sold by weight to merchants who export it, principally to markets in West Africa and eastern Europe, and this is where the arithmetic becomes uncomfortable. The export trade supports large numbers of traders and supplies clothing far more cheaply than local manufacture can. It also, in some markets, arrives in volumes those markets cannot absorb, and a proportion of what arrives is unsellable there too and becomes waste in a country with less capacity to handle it than the one that sent it. The shop's manager, Grace Oyelaran, is impatient with both of the usual accounts. The claim that donating clothes is straightforwardly generous is wrong, and so is the claim that it is a scandal in which rubbish is dumped on poorer countries: most of what is exported is worn by somebody, and the traders buying it are running businesses, not receiving charity. What she asks donors to do is narrower and more useful. Sort before you give. A bag containing a single wet towel contaminates everything in it and the whole bag is thrown away, which happens to roughly one bag in twelve. Donate in spring rather than in the fortnight after Christmas, when the sorting capacity of every shop in the country is overwhelmed at once. And accept, she says, that the honest description of a worn-out garment is not a donation but a disposal, and that pretending otherwise simply moves the decision to somebody with fewer options.",
    questions: [
      { q: "How much of the clothing is sold in the shop itself?", options: ["almost all of it","less than a tenth","about a fifth of it","roughly half of it"], answer: 2, explanation: "'sells, on the shop floor, perhaps a fifth of it'" },
      { q: "Why might a donated jacket appear in another town?", options: ["shops exchange stock every month","it was rejected by the first shop","donors move it themselves","it is sent where it will sell better"], answer: 3, explanation: "'goes to other shops in the chain where it will sell better'" },
      { q: "What is the problem with the export trade?", options: ["some markets receive more than they can absorb","transport costs outweigh the value","the clothing is of very poor quality","traders cannot afford to buy it"], answer: 0, explanation: "'arrives in volumes those markets cannot absorb'" },
      { q: "What does Oyelaran say about the usual accounts?", options: ["charities should explain the system better","both of them are wrong","the critical one is broadly correct","donors are generally well informed"], answer: 1, explanation: "'She is impatient with both of the usual accounts.'" },
      { q: "What happens to a bag containing a wet towel?", options: ["it is dried and sorted later","it is sold by weight for export","the whole bag is thrown away","the towel alone is discarded"], answer: 2, explanation: "'A bag containing a single wet towel contaminates everything in it and the whole bag is thrown away'" },
      { q: "Why does she suggest donating in spring?", options: ["shops are short of stock then","transport is cheaper in spring","clothing sells better at that time","sorting capacity is overwhelmed after Christmas"], answer: 3, explanation: "'when the sorting capacity of every shop in the country is overwhelmed at once'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
