/* FCE Prep bank: reading multiple-choice (wave 14) */
(function () {
var BANK = [
  {
    id: "fce-rmc14-01",
    title: "The Toad Tunnel",
    text: "For about three weeks every spring, common toads leave the woods above Carron Brae and walk downhill to the pond where they were spawned, crossing a road on the way. Before 2011 the crossing killed between four and six hundred of them a year, and a group of volunteers used to stand out in the rain with buckets, carrying toads across by hand. The tunnel that replaced them cost eighty-one thousand pounds, which is a figure the scheme's critics quote often, and it consists of two concrete channels under the road with a low wall arranged so that an animal walking downhill meets the wall and follows it to an opening. The design is not the interesting part; such tunnels have been built across northern Europe since the 1980s and the specifications are well established. What is interesting is how easy it turned out to be to build one that does not work. The first tunnel, installed by a neighbouring council in 2009, was a straight pipe with no wall, and monitoring found that toads used it at a rate that could not be distinguished from chance. Toads do not look for tunnels. They walk in a direction, meet an obstacle, and turn along it, which means the wall is not a supporting feature but the entire mechanism, and a tunnel without one is a hole in the ground. The Carron Brae scheme has been counted every year since it opened, by the same volunteers who used to carry the buckets, and road deaths are down by roughly ninety per cent. The volunteers still turn out, because the count is the only way to know whether the wall has been damaged by ploughing, which has happened twice. One of them told me that the tunnel had not taken away their job. It had changed it from carrying toads to checking that the toads no longer needed carrying, which she regarded as a promotion.",
    questions: [
      { q: "What did volunteers do before 2011?", options: ["they carried toads across the road by hand","they closed the road during the migration","they built temporary barriers each spring","they counted the toads killed by traffic"], answer: 0, explanation: "'a group of volunteers used to stand out in the rain with buckets, carrying toads across by hand'" },
      { q: "What does the writer say about the tunnel design?", options: ["it was developed specially for this site","it is well established and not the interesting part","it was cheaper than the volunteers' method","it required an unusual type of concrete"], answer: 1, explanation: "'such tunnels have been built across northern Europe since the 1980s and the specifications are well established'" },
      { q: "Why did the 2009 tunnel fail?", options: ["it was built too far from the pond","it flooded during heavy rain","it had no wall to guide the animals","it was blocked by fallen leaves"], answer: 2, explanation: "'The first tunnel… was a straight pipe with no wall'" },
      { q: "How do toads actually reach the opening?", options: ["they are attracted by the damp air inside","they follow the same route every year","they are guided by the sound of water","they meet an obstacle and turn along it"], answer: 3, explanation: "'They walk in a direction, meet an obstacle, and turn along it'" },
      { q: "Why do the volunteers still come out each spring?", options: ["to check that the wall is undamaged","to repair the tunnel entrances","to guide toads that miss the tunnel","to record the size of the population"], answer: 0, explanation: "'the count is the only way to know whether the wall has been damaged by ploughing'" },
      { q: "How does one volunteer describe the change?", options: ["as a disappointing loss of purpose","as a promotion rather than a redundancy","as proof that money was well spent","as the end of a long argument"], answer: 1, explanation: "'checking that the toads no longer needed carrying, which she regarded as a promotion'" }
    ]
  },
  {
    id: "fce-rmc14-02",
    title: "Ninety Years of Rainfall",
    text: "In a garden in Ludlow there is a rain gauge that has been read at nine o'clock every morning since 1934. Three generations of the same family have done the reading, and the record has never been broken by more than four consecutive days, those being in 1962 when the whole household had influenza and a neighbour who had been shown how to do it read it wrong. The current keeper, Judith Amery, took over from her father in 1998 and describes the job as ninety seconds of work and a great deal of not going away. The scientific value of such records is easy to state and easy to underestimate. A single garden gauge tells you nothing much about the climate. Two thousand of them, read consistently for a century, tell you a great deal, and the crucial word is consistently: an instrument that has not moved, in a garden whose surroundings have changed slowly, read at the same time each day by people using the same method, produces a series that can be compared with itself. Satellite data, which is vastly richer, cannot do this, because it begins in the 1970s and because each new sensor has to be calibrated against something. That something is usually the ground stations. Amery is realistic about the future of her own record. Her children live in other countries and she has begun negotiating with the neighbouring primary school, whose head teacher is enthusiastic and whose staff turnover is, in Amery's phrase, the problem you cannot see from here. The Met Office runs a training scheme for volunteer observers and its literature emphasises accuracy, calibration and the correct siting of the instrument. Amery says the literature is entirely right and entirely misses the difficulty, which is not doing it properly. It is doing it on the ninth of August, on Christmas morning, and on the day of a funeral, for ninety years.",
    questions: [
      { q: "What is unusual about the rain gauge?", options: ["it is the oldest instrument in the country","it records temperature as well as rainfall","it has been read daily for ninety years","it was designed by the family themselves"], answer: 2, explanation: "'a rain gauge that has been read at nine o'clock every morning since 1934'" },
      { q: "What happened in 1962?", options: ["the record was lost in a fire","a new instrument was installed","the gauge was moved to another garden","the family missed four days' readings"], answer: 3, explanation: "'the record has never been broken by more than four consecutive days, those being in 1962'" },
      { q: "Why does consistency matter so much?", options: ["the series can be compared with itself","it allows daily forecasts to be issued","it makes the readings easier to publish","it reduces the cost of collecting data"], answer: 0, explanation: "'produces a series that can be compared with itself'" },
      { q: "What limitation of satellite data is mentioned?", options: ["it covers only part of the country","it is recent and needs calibrating against ground stations","it cannot measure rainfall accurately","it is not available to the public"], answer: 1, explanation: "'it begins in the 1970s and… each new sensor has to be calibrated against something'" },
      { q: "What worries Amery about the school taking over?", options: ["the pupils would read it incorrectly","the head teacher is not interested","the staff there change too often","the site is unsuitable for a gauge"], answer: 2, explanation: "'whose staff turnover is, in Amery's phrase, the problem you cannot see from here'" },
      { q: "What does she say the official guidance misses?", options: ["the need for a second observer","the value of comparing nearby stations","the cost of maintaining an instrument","the difficulty of never missing a day"], answer: 3, explanation: "'It is doing it on the ninth of August, on Christmas morning, and on the day of a funeral, for ninety years.'" }
    ]
  },
  {
    id: "fce-rmc14-03",
    title: "The Café With No Prices",
    text: "The menu at Otto's, on a side street in Dundee, lists what is available and does not say what anything costs. At the end of the meal a card explains that the suggested contribution is six pounds, that paying more covers somebody who cannot, and that paying nothing is a normal and expected outcome requiring no explanation to anybody. The model is not new and most attempts at it close within two years. Otto's has been open for nine, and its founder, Bea Lindqvist, attributes this less to generosity than to two decisions that sound minor. The first is that the suggested figure is printed. Cafés that leave the amount entirely open receive, on average, less than those that suggest one, and Lindqvist says the reason is not meanness but anxiety: a customer who does not know what is normal will often avoid the situation altogether by not coming back. The second decision concerns the till. Payment is made into a box by the door, out of sight of the counter, and nobody who works there knows what any individual paid. This removes the transaction that ruins such schemes, in which a member of staff sees a small contribution and reacts, or is thought to have reacted, which amounts to the same thing. Lindqvist is impatient with the word charity and refuses interviews that use it as a frame. Her argument is that the café is a business with an unusual pricing mechanism, that it has met its costs every year but one, and that describing it as charitable implies the customers who pay nothing are receiving something the others are not. They are receiving lunch. So is everybody else. The one year it did not break even was 2020, when it closed for four months, and the shortfall was made up by regulars who had continued paying six pounds a week into the box for a café they could not enter.",
    questions: [
      { q: "What does the card at the end of the meal explain?", options: ["that a suggested contribution applies","that prices vary by time of day","that payment must be made in cash","that regular customers pay less"], answer: 0, explanation: "'the suggested contribution is six pounds'" },
      { q: "Why does Otto's print a suggested figure?", options: ["to cover its costs more reliably","because customers who do not know what is normal stay away","because the law requires a stated price","to discourage very large donations"], answer: 1, explanation: "'a customer who does not know what is normal will often avoid the situation altogether by not coming back'" },
      { q: "Why is payment made into a box by the door?", options: ["it is quicker at busy times","it reduces the risk of theft","staff cannot see what anyone paid","it allows contactless payment"], answer: 2, explanation: "'nobody who works there knows what any individual paid'" },
      { q: "What ruins such schemes, according to Lindqvist?", options: ["customers who pay nothing too often","suppliers refusing to deliver","poor locations with little passing trade","staff reacting to a small contribution"], answer: 3, explanation: "'a member of staff sees a small contribution and reacts, or is thought to have reacted'" },
      { q: "Why does she object to the word charity?", options: ["it suggests some customers get something different","it discourages people from paying","it is inaccurate under company law","it was used unfairly by a newspaper"], answer: 0, explanation: "'describing it as charitable implies the customers who pay nothing are receiving something the others are not'" },
      { q: "How was the 2020 shortfall covered?", options: ["by a grant from the council","by regulars who kept paying while it was shut","by raising the suggested contribution","by opening a second branch"], answer: 1, explanation: "'regulars who had continued paying six pounds a week into the box for a café they could not enter'" }
    ]
  },
  {
    id: "fce-rmc14-04",
    title: "Learning the Bells",
    text: "English change ringing is not tune playing and is frequently mistaken for it. A tower has six or eight or twelve bells, each rung by one person pulling a rope, and the bells are sounded in a continuously changing order determined by a set of rules learned by heart. Nobody reads music. What a ringer memorises is a pattern of movement: which bell to follow, when to move up the order and when to move down, sustained for anything from five minutes to three hours without a mistake, because a mistake is audible for half a mile. The band at St Aldate's has eleven members, of whom four joined in the last two years, which makes it unusual. Most towers are short of ringers and describe the shortage in terms of ageing membership, but the tower captain, Dan Prosser, thinks the diagnosis is wrong. His view is that recruitment is not the problem and never has been; open days attract plenty of interested people. The problem is the second month. Learning to handle a bell safely takes six to ten sessions and is physically awkward, and during that period the learner cannot take part in anything, cannot make a sound anybody wants to hear, and stands watching for most of the evening. Almost everyone who gives up gives up there. Prosser's response was to change the order of teaching. Learners at St Aldate's begin with the theory, on a computer simulator that lets them ring a virtual bell in a real pattern from the first evening, and only then learn the rope. It halves neither the awkwardness nor the ten sessions, but the learner arrives at the tower already able to do the interesting half of the activity, and the four new members are the result. Prosser is careful to add that he did not invent the method and that two other towers were doing it first. What he did was stop describing the problem as young people not being interested.",
    questions: [
      { q: "What does a ringer have to memorise?", options: ["the names of all the bells","the timing of each hour of the day","a pattern of movement through the order","a piece of written music"], answer: 2, explanation: "'What a ringer memorises is a pattern of movement'" },
      { q: "Why is a mistake serious?", options: ["the band must start again from the beginning","it is recorded in the tower's log","it can damage the bell mechanism","it can be heard half a mile away"], answer: 3, explanation: "'a mistake is audible for half a mile'" },
      { q: "What does Prosser think is misdiagnosed?", options: ["the reason towers lack ringers","the number of bells a tower needs","the difficulty of the patterns","the cost of maintaining the bells"], answer: 0, explanation: "'His view is that recruitment is not the problem and never has been'" },
      { q: "Why do most learners give up in the second month?", options: ["the other members are unwelcoming","they cannot yet take part in anything","the sessions are held too late in the evening","they find the theory too complicated"], answer: 1, explanation: "'the learner cannot take part in anything… and stands watching for most of the evening'" },
      { q: "What change did he make?", options: ["practices were moved to the weekend","new members ring a smaller bell first","learners start on a simulator before the rope","learners are paired with an experienced ringer"], answer: 2, explanation: "'Learners at St Aldate's begin with the theory, on a computer simulator'" },
      { q: "What does Prosser stress about his method?", options: ["it works only in larger towers","it requires expensive equipment","it shortens the training considerably","other towers were using it before him"], answer: 3, explanation: "'two other towers were doing it first'" }
    ]
  },
  {
    id: "fce-rmc14-05",
    title: "The Signs in the Hospital",
    text: "St Brendan's hospital replaced its signage in 2021 after an audit found that patients arriving for appointments were late, on average, by nine minutes, and that a quarter of them had asked at least two members of staff for directions. The old system was not badly designed by the standards of the time. It used clear typefaces, high contrast and consistent arrows, and it failed anyway, for a reason the design team says is the single most common error in wayfinding. The signs were written from the point of view of the building. They named departments, wings and floors, all of which are meaningful to somebody who already knows the hospital and meaningless to a person holding a letter that says Cardiology, Clinic 4B. The new system reversed this. Every sign now begins with the words that appear on the appointment letter, and the letters themselves were rewritten first, which took longer than the signage and involved four separate administrative systems. Arrows were reduced in number, because the team found that an arrow at a junction where the route does not turn is ignored on the way out and mistrusted on the way back. Colour coding was abandoned entirely; it works well for staff and poorly for visitors, who cannot learn a colour scheme in the four minutes they spend in a corridor, and it excludes a significant minority of colour-blind patients. What replaced it was repetition. The name of the destination appears at every decision point, unchanged, until the patient arrives, which is more signs and less information on each of them. Average lateness is now under three minutes. The design lead is dismissive of any suggestion that this was clever work. She says the hospital had spent thirty years describing itself to itself, and all her team did was write down what patients were already saying at the enquiry desk.",
    questions: [
      { q: "What did the audit find?", options: ["patients were arriving late and asking for directions","staff could not find their own departments","the signs were difficult to read","appointments were being booked incorrectly"], answer: 0, explanation: "'patients arriving for appointments were late, on average, by nine minutes'" },
      { q: "What was wrong with the old signs?", options: ["they used unclear typefaces","they were written from the building's point of view","there were too few of them","they had faded and were not replaced"], answer: 1, explanation: "'The signs were written from the point of view of the building.'" },
      { q: "What had to be done before the new signs?", options: ["a survey of every corridor","training for reception staff","the appointment letters were rewritten","the departments were renamed"], answer: 2, explanation: "'the letters themselves were rewritten first'" },
      { q: "Why were arrows reduced?", options: ["they were expensive to produce","they confused non-English speakers","they took up too much space","an arrow where the route does not turn is mistrusted"], answer: 3, explanation: "'an arrow at a junction where the route does not turn is ignored on the way out and mistrusted on the way back'" },
      { q: "Why was colour coding dropped?", options: ["visitors cannot learn it in a few minutes","it was difficult to keep consistent","the colours faded under the lighting","staff found it unhelpful"], answer: 0, explanation: "'it works well for staff and poorly for visitors, who cannot learn a colour scheme in the four minutes they spend in a corridor'" },
      { q: "How does the design lead describe her team's work?", options: ["as a technically difficult project","as writing down what patients already said","as a compromise forced by the budget","as the first scheme of its kind"], answer: 1, explanation: "'all her team did was write down what patients were already saying at the enquiry desk'" }
    ]
  },
  {
    id: "fce-rmc14-06",
    title: "The Beavers Came Back",
    text: "Beavers were hunted out of Britain some four hundred years ago and returned, unofficially and without anybody admitting responsibility, to a river in Devon at some point before 2013. The government's first instinct was to remove them. What prevented this was a five-year monitored trial, and the results have shaped every argument since. On the credit side the figures are striking. The dams on one tributary held back enough water to reduce peak flow downstream by around thirty per cent during heavy rain, which matters to a village that had flooded three times in a decade. Water leaving the beaver ponds carried substantially less sediment and less phosphate than water entering them. Species counts rose, particularly among amphibians and water beetles, and a stretch of ditch that had been dry each August held water throughout. None of this was a surprise to anybody who had read the European literature. The costs are equally real and fall on a small number of people. A beaver does not distinguish between a willow nobody wants and an orchard tree somebody planted, and a dam built in the wrong culvert can flood a field of standing crops in a night. The farmers affected are not the people who benefit from reduced flooding twelve kilometres downstream, and early attempts to discuss the matter foundered on exactly that point. What has emerged since is a management system rather than a decision: dams that cause damage can be notched or fitted with a pipe that lowers the pond level without removing the structure, individual trees are protected with mesh, and there is a compensation route for losses that cannot be prevented. It satisfies nobody entirely. The ecologist who ran the trial regards this as the correct outcome, on the grounds that any scheme which one side describes as a complete victory has almost certainly loaded the costs onto somebody who was not in the room.",
    questions: [
      { q: "How did beavers return to Devon?", options: ["they crossed from a wildlife park","they were brought in by farmers","nobody admitted releasing them","they were reintroduced by the government"], answer: 2, explanation: "'unofficially and without anybody admitting responsibility'" },
      { q: "What effect did the dams have during heavy rain?", options: ["they had no measurable effect","they increased the amount of sediment","they raised water levels upstream dangerously","they cut peak flow downstream by about a third"], answer: 3, explanation: "'reduce peak flow downstream by around thirty per cent'" },
      { q: "What does the writer say about these findings?", options: ["they surprised nobody familiar with European research","they applied only to that one river","they contradicted earlier studies","they were disputed by the ecologists"], answer: 0, explanation: "'None of this was a surprise to anybody who had read the European literature.'" },
      { q: "Why is the situation difficult for farmers?", options: ["compensation is not available to them","those who bear the costs are not those who benefit","they were not consulted about the trial","beavers damage riverbanks in winter"], answer: 1, explanation: "'The farmers affected are not the people who benefit from reduced flooding twelve kilometres downstream'" },
      { q: "What is done about a dam causing damage?", options: ["the field is bought by the authorities","the river is diverted around it","it can be notched or fitted with a pipe","it is removed and the beavers relocated"], answer: 2, explanation: "'dams that cause damage can be notched or fitted with a pipe'" },
      { q: "Why does the ecologist accept a compromise?", options: ["the law does not allow anything else","public opinion is evenly divided","further research is still needed","a complete victory usually hides costs borne by others"], answer: 3, explanation: "'any scheme which one side describes as a complete victory has almost certainly loaded the costs onto somebody who was not in the room'" }
    ]
  },
  {
    id: "fce-rmc14-07",
    title: "The Lost Property Office",
    text: "The lost property office of a large transport network receives about three hundred thousand items a year, and the manager will tell you, without being asked twice, that the popular image of the job is wrong in every particular. There is no room full of umbrellas. Umbrellas arrive in quantity but are claimed at a lower rate than almost anything else, because an umbrella is worth less than the journey required to collect it, and unclaimed items are cleared after three months. The objects that stay longest are the ones nobody can identify and nobody will throw away: a wedding dress, a set of dentures, an urn. Reclaim rates follow a pattern that has held for decades and that the office uses to decide where to put its effort. Anything with a name in it is returned in about eighty per cent of cases. Anything with a phone number is higher still. Bags are claimed more often than the items inside them, because a person who has lost a bag knows they have lost a bag, whereas a person who has lost a single glove often does not discover it for a week and by then cannot say where. Laptops are almost always claimed and almost never claimed quickly, the delay being the time it takes the owner to exhaust every other explanation. The manager's practical advice, repeated in every interview she gives, is unglamorous and evidently effective. Write your name and a number on a card and put it inside the bag, not on the outside where it can be read by anybody, and take a photograph of anything you carry regularly, because the single greatest obstacle to returning an item is not honesty. Roughly ninety-five per cent of what is handed in is handed in by the public. It is that the owner, standing at the counter, cannot describe what they lost well enough for the staff to find it.",
    questions: [
      { q: "What does the manager say about umbrellas?", options: ["they are claimed less often than most items","they make up most of the storage space","they are usually returned within a week","they are rarely handed in at all"], answer: 0, explanation: "'Umbrellas arrive in quantity but are claimed at a lower rate than almost anything else'" },
      { q: "Which items stay longest in the office?", options: ["expensive electronic devices","things nobody can identify or discard","items left on the busiest routes","luggage from international services"], answer: 1, explanation: "'the ones nobody can identify and nobody will throw away'" },
      { q: "Why are bags claimed more often than gloves?", options: ["bags are more valuable to their owners","gloves are usually damaged","the owner notices the loss immediately","gloves are not accepted by the office"], answer: 2, explanation: "'a person who has lost a bag knows they have lost a bag'" },
      { q: "Why are laptops claimed slowly?", options: ["the office checks ownership carefully","owners must provide proof of purchase","they are stored at a separate site","owners first rule out every other possibility"], answer: 3, explanation: "'the delay being the time it takes the owner to exhaust every other explanation'" },
      { q: "What does she advise people to do?", options: ["put a name and number inside the bag","attach a label to the outside of the bag","report a loss on the same day","insure anything valuable they carry"], answer: 0, explanation: "'Write your name and a number on a card and put it inside the bag'" },
      { q: "What is the main obstacle to returning items?", options: ["items are not handed in by the public","owners cannot describe what they lost","the office is open for limited hours","records are kept for too short a time"], answer: 1, explanation: "'cannot describe what they lost well enough for the staff to find it'" }
    ]
  },
  {
    id: "fce-rmc14-08",
    title: "The Pacer at Twenty-Six Miles",
    text: "At most large marathons a number of runners carry a small flag showing a finishing time, and their job is to run that time as exactly as they can so that anybody hoping to achieve it can simply stay with them. Pacers are volunteers, they are considerably faster than the time they are pacing, and the skill involved is not endurance but restraint. Marta Rusu, who has paced the four-hour group eleven times, says the hardest part of the race is the first three kilometres, when the group is fresh, the crowd is loud and forty people want to go faster than the plan. Her method is to be boring on purpose. She talks continuously, announces the pace at every kilometre, and refuses to accelerate on downhill sections, which is the commonest way a group destroys itself without noticing. What she is managing, she says, is not speed but arithmetic that people cannot do while running. Thirty seconds a kilometre too fast for eight kilometres feels like enthusiasm and costs four minutes at the end, and no runner in that state believes it. The part of the job nobody warns pacers about is the last eight kilometres, when the group has shrunk from forty to perhaps nine and the runners still there are in difficulty. Rusu describes this as the only stage where anything she says matters. Her rule is never to promise that it will get easier, because it will not, and because a runner who is lied to at kilometre thirty-five stops trusting everything else. What she offers instead is arithmetic again: the number of minutes remaining, stated plainly, and the observation that they are currently doing the thing they have just said they cannot do. She has finished within twenty seconds of four hours on nine of her eleven attempts. The two misses were both too fast, which she regards as the worse error, and can describe in detail.",
    questions: [
      { q: "What is a pacer's job?", options: ["to win the race for their club","to check the course is correctly marked","to run a set finishing time exactly","to encourage the slowest runners"], answer: 2, explanation: "'their job is to run that time as exactly as they can'" },
      { q: "What quality does the work require?", options: ["detailed knowledge of the course","experience of competing abroad","exceptional endurance","restraint rather than speed"], answer: 3, explanation: "'the skill involved is not endurance but restraint'" },
      { q: "Why does Rusu refuse to speed up downhill?", options: ["it is how a group ruins its race unnoticed","the course is measured on the flat","it increases the risk of injury","the flag is hard to carry at speed"], answer: 0, explanation: "'which is the commonest way a group destroys itself without noticing'" },
      { q: "What does she say she is really managing?", options: ["the group's water intake","arithmetic runners cannot do while running","the mood of the crowd","the distance between runners"], answer: 1, explanation: "'not speed but arithmetic that people cannot do while running'" },
      { q: "Why will she never say it gets easier?", options: ["it distracts runners near the finish","the organisers discourage it","a runner who is lied to stops trusting her","she does not want to slow the group"], answer: 2, explanation: "'a runner who is lied to at kilometre thirty-five stops trusting everything else'" },
      { q: "How does she regard her two failed attempts?", options: ["as the fault of the group she led","as unimportant compared with nine successes","as bad luck with the weather","as the worse kind of error because she was too fast"], answer: 3, explanation: "'The two misses were both too fast, which she regards as the worse error'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
