/* FCE Prep bank: reading multiple-choice (wave 18) */
(function () {
var BANK = [
  {
    id: "fce-rmc18-01",
    title: "Forecasting the Avalanche",
    text: "An avalanche forecaster does not predict avalanches. The distinction sounds like modesty and is in fact the whole discipline: what is issued each afternoon is a statement about how likely a slope of a given angle and aspect is to fail if it is disturbed, expressed on a five-point scale that most of the public reads as a measure of danger and that professionals read as a description of a snowpack. Nils Aaberg, who has forecast for a Norwegian region for sixteen years, says the hardest part of the work is the layer he cannot see. Snow arrives in distinct falls, each with its own crystal structure, and the strength of the whole depends on the weakest joint between two of them, which may have formed in November and lain buried and stable for two months. Such a layer does not announce itself. It is found by digging a pit, isolating a column and loading it until it shears, a test that takes twenty minutes and describes one square metre of a mountain range. The forecaster's job is to reason outwards from a handful of such pits, and Aaberg is blunt that the reasoning is closer to a detective's than an engineer's. What has changed the field is not better modelling but better reporting. Skiers now submit observations through an app, and a photograph of a crack running ahead of a ski at a stated altitude and aspect is worth more than a great deal of theory. The volume is such that the region receives more field observations in a week than it used to receive in a season. Aaberg's concern is the opposite of the one people expect. He does not worry that the public misunderstands the scale. He worries that a forecast which has been right all winter teaches people to substitute it for their own judgement, and that the worst accidents in his region have consistently involved experienced parties on days rated moderate, travelling on a number rather than on what was under their feet.",
    questions: [
      { q: "What does a forecast actually describe?", options: ["how likely a slope is to fail if disturbed","where avalanches will occur that day","the depth of snow on each mountain","the weather expected in the next week"], answer: 0, explanation: "'a statement about how likely a slope of a given angle and aspect is to fail if it is disturbed'" },
      { q: "What makes the work difficult?", options: ["forecasts must be issued very early","the weakest layer is buried and invisible","instruments fail in low temperatures","the region is too large to visit"], answer: 1, explanation: "'the hardest part of the work is the layer he cannot see'" },
      { q: "What is the limitation of digging a pit?", options: ["it takes most of a day to complete","it can only be done in fresh snow","it describes one square metre","it disturbs the slope being tested"], answer: 2, explanation: "'a test that takes twenty minutes and describes one square metre of a mountain range'" },
      { q: "How does Aaberg describe the reasoning involved?", options: ["as largely mathematical","as based on long experience alone","as guided by computer models","as closer to a detective's than an engineer's"], answer: 3, explanation: "'the reasoning is closer to a detective's than an engineer's'" },
      { q: "What has most improved forecasting?", options: ["observations submitted by skiers","more accurate weather models","new measuring equipment","larger forecasting teams"], answer: 0, explanation: "'What has changed the field is not better modelling but better reporting.'" },
      { q: "What is his main worry?", options: ["the public misreads the five-point scale","people rely on the forecast instead of their own judgement","too many observations are submitted","forecasts are issued too late in the day"], answer: 1, explanation: "'travelling on a number rather than on what was under their feet'" }
    ]
  },
  {
    id: "fce-rmc18-02",
    title: "Why the Fax Machine Is Still There",
    text: "In a corridor of a large teaching hospital there is a fax machine that receives about sixty pages a day and has been scheduled for removal four times. Its survival is often reported as an example of institutional backwardness, and the people who work with it give a more interesting account. A fax is a document that arrives complete, in one piece, on paper, at a machine in a known physical location, and it is received whether or not the recipient has an account, a password, a compatible system or any prior relationship with the sender. A general practitioner in a small practice using software that will never speak to the hospital's software can send a referral in ninety seconds. The replacement, when it arrives, is not a better machine but an agreement between two organisations, and agreements are slower to build than devices are to install. The hospital's digital lead, Ana Petrescu, has removed fourteen fax machines in six years and describes the method as unglamorous. She does not campaign against the machine. She finds out what each one is used for, which is never what the official list says, and then removes the reason. One machine turned out to exist entirely because a single laboratory would not accept results by any other route, and disappeared the week that laboratory changed its policy. Another was receiving death certificates from a coroner's office with a legal requirement about signatures that had been satisfied electronically in 2019 and that nobody had told the hospital about. Her rule is that a fax machine is never the problem; it is the visible end of a process that has no other way of completing. She adds that the four failed attempts at removing the corridor machine were all made by people who began by announcing a deadline, and that each of them produced the same result, which was a second machine appearing quietly in an office two floors down.",
    questions: [
      { q: "What advantage of a fax does the article describe?", options: ["it keeps a permanent record automatically","it is more secure than email","it arrives complete without needing an account","it is cheaper than electronic systems"], answer: 2, explanation: "'it is received whether or not the recipient has an account, a password, a compatible system'" },
      { q: "Why is the replacement difficult?", options: ["staff are unwilling to be trained","the hospital's network is unreliable","the new equipment is expensive","it requires an agreement between organisations"], answer: 3, explanation: "'The replacement… is not a better machine but an agreement between two organisations'" },
      { q: "How does Petrescu approach removal?", options: ["by finding out what each is really used for","by asking staff to vote on it","by setting a firm deadline for each machine","by replacing them with scanners"], answer: 0, explanation: "'She finds out what each one is used for'" },
      { q: "Why did one machine disappear?", options: ["staff found a quicker alternative","a laboratory changed its policy","it broke down and was not replaced","the office using it was closed"], answer: 1, explanation: "'disappeared the week that laboratory changed its policy'" },
      { q: "What is her rule about fax machines?", options: ["no machine should last more than five years","each department should decide for itself","a fax machine is never the real problem","every machine should be logged centrally"], answer: 2, explanation: "'a fax machine is never the problem; it is the visible end of a process'" },
      { q: "What happened when others announced a deadline?", options: ["the deadline was extended repeatedly","the machine was used more heavily","staff complained to management","another machine quietly appeared elsewhere"], answer: 3, explanation: "'a second machine appearing quietly in an office two floors down'" }
    ]
  },
  {
    id: "fce-rmc18-03",
    title: "The Recipe That Works at Home",
    text: "A recipe published in a magazine has usually been cooked between six and fifteen times before anybody outside the building sees it, and most of that work is not about whether the dish tastes good. It is about whether it survives being made by somebody who is not in the test kitchen. Priya Kulkarni, who has developed recipes for eleven years, says the failures cluster in a small number of places and that almost none of them concern skill. Pan size is the most common. A recipe developed in a twenty-eight centimetre pan and made in a twenty-four centimetre one has a deeper layer of liquid, which changes the evaporation and therefore the timing, and the reader who follows the stated time exactly gets a different dish and concludes that they cannot cook. Oven temperature is worse, because domestic ovens are frequently out by twenty degrees and almost nobody knows which direction theirs runs in. Kulkarni's response to both is to write the destination rather than the route: not eighteen minutes but until the edges are set and the centre still moves; not medium heat but until it smells nutty and turns the colour of a paper bag. She says this is harder to write, longer on the page, and resisted by editors on grounds of space, and that she has never lost the argument once she has watched somebody test both versions. The other systematic failure is the ingredient that is not what it says. A tablespoon of a wetter yoghurt behaves differently. Flour absorbs different amounts depending on the season. She now tests every recipe once with the cheapest supermarket versions of everything in it, having realised that recipes developed with good ingredients frequently rely on them without saying so, and that the reader who follows such a recipe faithfully and produces something disappointing has been failed by the writer rather than the other way round.",
    questions: [
      { q: "What is most of the testing about?", options: ["whether the dish works outside the test kitchen","whether the dish tastes good enough","how quickly it can be prepared","how it will photograph"], answer: 0, explanation: "'It is about whether it survives being made by somebody who is not in the test kitchen.'" },
      { q: "Why does pan size matter so much?", options: ["larger pans need more ingredients","it changes evaporation and therefore timing","small pans heat unevenly","it affects how the dish is served"], answer: 1, explanation: "'a deeper layer of liquid, which changes the evaporation and therefore the timing'" },
      { q: "What is the problem with domestic ovens?", options: ["they take longer to heat up","they cannot hold a steady temperature","they are often wrong and owners do not know it","they vary between brands"], answer: 2, explanation: "'domestic ovens are frequently out by twenty degrees and almost nobody knows which direction theirs runs in'" },
      { q: "How does Kulkarni write instructions?", options: ["with precise times for every stage","using measurements by weight only","in the shortest form possible","describing the result rather than the timing"], answer: 3, explanation: "'to write the destination rather than the route'" },
      { q: "Why do editors resist her approach?", options: ["it takes up more space on the page","readers find it confusing","it makes recipes seem difficult","it cannot be translated easily"], answer: 0, explanation: "'resisted by editors on grounds of space'" },
      { q: "Why does she test with cheap ingredients?", options: ["to keep the cost of testing down","recipes may secretly depend on good ones","supermarkets sponsor the magazine","readers requested it"], answer: 1, explanation: "'recipes developed with good ingredients frequently rely on them without saying so'" }
    ]
  },
  {
    id: "fce-rmc18-04",
    title: "The Woman Who Grades Fleece",
    text: "At a wool depot in the Borders, fleeces arrive in bales and leave in grades, and the sorting between those two states is done by hand and by eye at a rate of about one fleece every fifteen seconds. Morag Sinclair has done it for twenty-two years. She takes a fleece, throws it open on a table, and assigns it to one of dozens of categories based on the diameter of the fibre, the length of the staple, the crimp, the colour, the amount of vegetable matter caught in it and the presence of any of a list of faults that will ruin a spinning batch. The most serious of these faults is the one nobody outside the trade has heard of: a break, meaning a weak point along the length of every fibre in the fleece, caused by an illness or a shortage of food several months earlier. A fleece with a break looks entirely normal and falls apart under tension. Machines can now measure fibre diameter more precisely than any human, and the depot uses them. What the machines do not do is take in the whole fleece at once, and Sinclair's speed comes from assessing several properties simultaneously in a way she cannot fully describe. She has tried to teach it and reports that the part that transfers easily is the list, and the part that does not is knowing where to look first. Her trainees take about two years to become useful and about five to become fast. She is not sentimental about the trade's future. British wool prices have been low for two decades, many farmers now regard shearing as a cost rather than a crop, and the depot handles less than half the volume it did when she started. What she wants recorded, if the work does disappear, is that it was skilled: that a fleece is not a uniform material, and that somebody spent a working life being able to tell.",
    questions: [
      { q: "How quickly does Sinclair sort a fleece?", options: ["in five to ten seconds","in about three minutes","in about fifteen seconds","in roughly a minute"], answer: 2, explanation: "'a rate of about one fleece every fifteen seconds'" },
      { q: "What is a break in a fleece?", options: ["a patch of discoloured wool","a gap where wool has been lost","a tear caused during shearing","a weak point along every fibre"], answer: 3, explanation: "'a weak point along the length of every fibre in the fleece'" },
      { q: "Why is a break so serious?", options: ["the fleece looks normal but falls apart","it reduces the weight of the fleece","it spreads to other fleeces in the bale","it cannot be detected by machines"], answer: 0, explanation: "'A fleece with a break looks entirely normal and falls apart under tension.'" },
      { q: "What can machines not do?", options: ["detect vegetable matter","assess the whole fleece at once","measure fibre diameter accurately","work at commercial speed"], answer: 1, explanation: "'What the machines do not do is take in the whole fleece at once'" },
      { q: "What is hardest to teach?", options: ["how to handle the fleece safely","the names of the grades","knowing where to look first","the list of possible faults"], answer: 2, explanation: "'the part that does not is knowing where to look first'" },
      { q: "What does she want recorded about the work?", options: ["that machines cannot replace it","that it should be taught in schools","that it was better paid than people assume","that it was genuinely skilled"], answer: 3, explanation: "'What she wants recorded, if the work does disappear, is that it was skilled'" }
    ]
  },
  {
    id: "fce-rmc18-05",
    title: "The People Under the Flight Path",
    text: "When an airport applies to change its night flight arrangements, it must publish noise contours: lines on a map joining points of equal average sound level, drawn in a way that has been standard for decades and that almost everybody living under them regards as misleading. The complaint is not that the measurements are wrong. It is that an average conceals the thing being complained about. A person woken at four in the morning by one aircraft has not experienced an average; they have experienced an event, and a night containing six such events and eight hours of near silence produces a low average and a poor night's sleep. Research on sleep disturbance supports the residents rather than the contours, and the regulator now requires supplementary measures based on the number of events above a threshold, which is a substantial change and is still not what appears on the map that the public sees. Dr Owen Marsh, who studies aircraft noise, is careful to point out where the residents' case is weaker. Complaint volume is a poor measure of anything: a single determined household can lodge four hundred complaints in a month, and the areas that complain most are not always the areas that are loudest, being instead the areas where people expected quiet when they moved. He also notes that noise from a given aircraft type has fallen substantially since the 1990s, and that this real improvement is invisible to residents because the number of flights rose over the same period. His own recommendation is procedural rather than technical. He argues that airports should publish, alongside the contours, the number of nights in the year on which a given postcode can expect to be woken, because it is a number that residents recognise and that can be checked against their own experience, and because a figure nobody believes is worse than no figure at all.",
    questions: [
      { q: "What is the objection to noise contours?", options: ["an average hides the individual events","the measurements are inaccurate","they are published too late","they cover too small an area"], answer: 0, explanation: "'an average conceals the thing being complained about'" },
      { q: "What does the research on sleep support?", options: ["the airports' position","the residents' position","neither position clearly","the need for more flights at night"], answer: 1, explanation: "'Research on sleep disturbance supports the residents rather than the contours'" },
      { q: "Why is complaint volume a poor measure?", options: ["complaints are not recorded consistently","most people never complain at all","one household can lodge hundreds","complaints arrive months later"], answer: 2, explanation: "'a single determined household can lodge four hundred complaints in a month'" },
      { q: "Why is the improvement in aircraft noise invisible?", options: ["it happened before most residents arrived","manufacturers have not published the data","the improvement is very small","the number of flights increased"], answer: 3, explanation: "'this real improvement is invisible to residents because the number of flights rose over the same period'" },
      { q: "What does Marsh recommend publishing?", options: ["how many nights a postcode expects to be woken","a map of complaint numbers by area","the noise level of each aircraft type","the times of all night flights"], answer: 0, explanation: "'the number of nights in the year on which a given postcode can expect to be woken'" },
      { q: "Why does he prefer that figure?", options: ["it is cheaper to calculate","residents can check it against their experience","it favours neither side","it is required by the regulator"], answer: 1, explanation: "'it is a number that residents recognise and that can be checked against their own experience'" }
    ]
  },
  {
    id: "fce-rmc18-06",
    title: "The Last Bank in Town",
    text: "When the fourth and final bank branch in Ardsley closed, the response followed a pattern now familiar across small towns: a petition, a meeting, a statement about changing customer behaviour, and a closure on the announced date. What happened afterwards was less usual. The town has a market, and the market has traders, and traders take cash. A trader with three hundred pounds in coins at the end of a Saturday now faced a forty-minute drive, and within a year two had stopped trading and one had gone card-only and lost a fifth of his turnover. The problem was not that residents could not bank. It was that a small number of businesses could not deposit, and the effect of their difficulties fell on everybody who shopped there. The solution, when it came, was a shared banking hub: a single counter, open five days a week, staffed by the Post Office, at which customers of any of the major banks can pay in, withdraw and check a balance, with each bank sending a representative one day a week for anything more complicated. It is not a branch and cannot do what a branch did. Loans, disputes and anything requiring a decision are handled elsewhere or online. What it does do is accept a bag of coins, which turns out to be the function that mattered. The hub has been open two years and the market has recovered its traders. The town council's clerk, who spent eighteen months on the application, has a warning for other towns based on what she learned: the criteria are national, they are based on population and distance rather than on local circumstances, and Ardsley qualified narrowly on a measure that has nothing to do with the reason it needed one. She advises applicants to argue on the criteria as written rather than on the situation they actually face, which she describes as the least satisfying advice she has ever given anybody.",
    questions: [
      { q: "What was the real problem after the closure?", options: ["the town lost a major employer","house prices in the town fell","businesses could not deposit their takings","residents could not withdraw cash"], answer: 2, explanation: "'a small number of businesses could not deposit'" },
      { q: "What happened to one market trader?", options: ["he began banking by post","he moved to a larger town","he stopped trading altogether","he went card-only and lost turnover"], answer: 3, explanation: "'one had gone card-only and lost a fifth of his turnover'" },
      { q: "What is a shared banking hub?", options: ["one counter serving customers of all banks","a branch shared between two banks","a mobile van visiting once a week","an online service with local support"], answer: 0, explanation: "'a single counter… at which customers of any of the major banks can pay in, withdraw and check a balance'" },
      { q: "What can the hub not do?", options: ["open on more than two days","handle anything requiring a decision","accept cash deposits","serve business customers"], answer: 1, explanation: "'Loans, disputes and anything requiring a decision are handled elsewhere or online.'" },
      { q: "Which function turned out to matter most?", options: ["checking account balances","giving advice to older customers","accepting a bag of coins","providing a place to meet bank staff"], answer: 2, explanation: "'What it does do is accept a bag of coins, which turns out to be the function that mattered.'" },
      { q: "What is the clerk's warning to other towns?", options: ["apply before the last branch closes","the process takes at least three years","local support makes little difference","argue on the written criteria, not local need"], answer: 3, explanation: "'She advises applicants to argue on the criteria as written rather than on the situation they actually face'" }
    ]
  },
  {
    id: "fce-rmc18-07",
    title: "The Lifeguard and the Quiet Sea",
    text: "The beach at Trevorrick looks safest on the days it is most dangerous. A rip current is a narrow channel of water flowing away from the shore, formed where water pushed up the beach by breaking waves finds a route back out, and it is marked by a stretch of surface that is calmer, darker and less broken than the water on either side. To a swimmer standing at the water's edge choosing where to go in, that stretch is the obvious choice. Sam Trelawny, who has been a seasonal lifeguard on this coast for nine summers, says the entire safety message can be reduced to this single counter-intuitive fact and that it still takes most of a season to get it across. Rips do not pull people under; they carry them out, at a speed a strong swimmer cannot fight for long, and the danger is exhaustion followed by panic. The advice is to float, to signal, and if swimming, to swim parallel to the shore until out of the channel. What Trelawny finds hardest is not the tourists. It is the confident local swimmer who has been in this water for thirty years and who has, in that time, never been in a rip, because rips move and appear where the sandbanks put them. He describes the busiest days as the easiest to work, since a crowded beach between the flags is a beach where he can see everybody, and the incidents that worry him happen at seven in the evening after the flags come down, when the sea is at its calmest and the last few people are still in the water. His service has begun putting a sign at the entrance describing what a rip looks like, with a photograph rather than a diagram, and the early evidence is that a photograph works and a diagram does not, which he says is the only piece of research he has ever read that matched what he already believed.",
    questions: [
      { q: "How does a rip current appear from the shore?", options: ["as calmer, darker water","as a line of breaking waves","as a patch of foam","as water moving along the beach"], answer: 0, explanation: "'a stretch of surface that is calmer, darker and less broken'" },
      { q: "Why is this dangerous for swimmers?", options: ["the water there is much deeper","it is the part a swimmer will choose","it is furthest from the lifeguards","the current changes direction suddenly"], answer: 1, explanation: "'that stretch is the obvious choice'" },
      { q: "What is the real danger of a rip?", options: ["being carried onto rocks","cold water shock","exhaustion and then panic","being pulled beneath the surface"], answer: 2, explanation: "'the danger is exhaustion followed by panic'" },
      { q: "Who does Trelawny worry about most?", options: ["children swimming alone","visitors who cannot swim","surfers in poor weather","confident local swimmers"], answer: 3, explanation: "'It is the confident local swimmer who has been in this water for thirty years'" },
      { q: "Why are busy days easier for him?", options: ["everyone is between the flags where he can see","the sea is rougher and people stay out","more lifeguards are on duty","swimmers stay closer to the shore"], answer: 0, explanation: "'a crowded beach between the flags is a beach where he can see everybody'" },
      { q: "What has the new sign shown?", options: ["signs are ignored by most visitors","photographs work better than diagrams","warnings must be repeated to be effective","local swimmers read them most"], answer: 1, explanation: "'a photograph works and a diagram does not'" }
    ]
  },
  {
    id: "fce-rmc18-08",
    title: "The Night of the Street Count",
    text: "On one night each autumn, teams of volunteers walk a set of routes through their district between midnight and six and record every person they find sleeping outside. The figure produced is the official count, it is published, it is compared with last year's, and almost everybody involved in producing it will tell you that it is an undercount. This is not a criticism of the method so much as a description of what the method can do. A team walking a route sees the people who are visible from it. It does not see somebody in a stairwell, in woodland at the edge of town, in a car in a retail park, or on a night bus, and it counts nobody who is sleeping on a friend's floor, which is where the majority of people without housing actually are. Marek Duda, who has co-ordinated counts in his borough for six years, says the number's value lies almost entirely in its consistency. Counted the same way, on the same night of the year, by teams following the same routes, the figure is a poor measure of the size of the problem and a reasonably good measure of the direction it is moving. Trouble arises when it is used as the former. He describes a year in which a neighbouring authority's published figure fell by a third, which was reported locally as a success and was in fact the result of a demolished underpass, its occupants having moved half a kilometre into a district that counted them instead. His own team now publishes a short note alongside the number, listing what changed in the district that year: a car park closed, a new shelter opened, a route altered. He says the note takes an hour to write, that no journalist has ever quoted it, and that he will keep writing it because the first person to compare his figures carefully in ten years will need it.",
    questions: [
      { q: "What do the volunteers record?", options: ["people staying with friends","the number of empty buildings","everyone sleeping outside on their routes","everyone using homeless services"], answer: 2, explanation: "'record every person they find sleeping outside'" },
      { q: "What do those involved say about the figure?", options: ["it is rising too fast to measure","it should be published less often","it is broadly accurate","it is an undercount"], answer: 3, explanation: "'almost everybody involved in producing it will tell you that it is an undercount'" },
      { q: "Where are most people without housing?", options: ["sleeping on friends' floors","in temporary shelters","in cars in retail parks","in woodland outside towns"], answer: 0, explanation: "'which is where the majority of people without housing actually are'" },
      { q: "What does Duda say the number is good for?", options: ["setting the budget for services","showing which direction things are moving","comparing districts with each other","estimating the total need for housing"], answer: 1, explanation: "'a reasonably good measure of the direction it is moving'" },
      { q: "Why did a neighbouring figure fall by a third?", options: ["fewer volunteers took part","a shelter opened that year","an underpass was demolished","the count was held on a rainy night"], answer: 2, explanation: "'the result of a demolished underpass'" },
      { q: "Why does he publish an explanatory note?", options: ["the council requires it","it improves the accuracy of the count","journalists have asked for one","someone comparing the figures later will need it"], answer: 3, explanation: "'the first person to compare his figures carefully in ten years will need it'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
