/* FCE Prep bank: reading multiple-choice (wave 20) */
(function () {
var BANK = [
  {
    id: "fce-rmc20-01",
    title: "Painting the Bridge",
    text: "The idea that painting a large steel bridge is a task which begins again the moment it finishes is one of those pieces of common knowledge that was true once and has not been for fifty years. It was broadly accurate in the era of lead-based paints, which weathered visibly within a decade and were applied by gangs working continuously. Modern coating systems last between twenty and thirty years, and the work is done in campaigns with long gaps between them, which means the phrase survives as a metaphor long after it stopped describing anything. Erin Mbeki, who manages the maintenance of an estuary crossing carrying forty thousand vehicles a day, says the persistence of the myth is a small nuisance in an otherwise serious problem: the public believes the bridge is being looked after continuously and is therefore surprised, and suspicious, when a closure is announced. The actual work is less about paint than about what is under it. A coating fails from beneath, where water has found a way in at a joint or a bolt, and the expensive part of any campaign is the preparation: stripping back to bare steel, treating corrosion, and doing this inside a sealed enclosure that catches every particle, because the old coatings on any bridge built before 1980 must be treated as hazardous. Access alone can be half the cost. Mbeki's team now uses drones for inspection, which she describes as genuinely transformative for a reason that is not obvious. The saving is not in the flying. It is that an inspector who previously had to justify the cost of a platform before looking at a suspect area can now look first, which means the decision about whether to investigate has become cheap, and the number of small problems found early has roughly tripled. Her budget has not increased. What has changed is that she now spends it on things she chose rather than on things that had already failed.",
    questions: [
      { q: "What was true in the era of lead paint?", options: ["coatings weathered within about ten years","bridges were painted only once","paint was applied by machine","the work was done every summer"], answer: 0, explanation: "'which weathered visibly within a decade'" },
      { q: "Why is the old saying a nuisance?", options: ["it makes the work sound easy","the public is surprised by closures","it discourages recruitment","engineers find it insulting"], answer: 1, explanation: "'the public believes the bridge is being looked after continuously and is therefore surprised, and suspicious, when a closure is announced'" },
      { q: "How does a coating usually fail?", options: ["from sunlight on the surface","because the wrong paint was chosen","from beneath, where water gets in","through damage from traffic"], answer: 2, explanation: "'A coating fails from beneath, where water has found a way in at a joint or a bolt'" },
      { q: "Why must old coatings be enclosed?", options: ["to protect the paint from rain","to keep the work out of sight","to allow work in winter","because they are hazardous"], answer: 3, explanation: "'the old coatings on any bridge built before 1980 must be treated as hazardous'" },
      { q: "What is the real benefit of drones?", options: ["looking at a suspect area has become cheap","flying is faster than climbing","they can work in bad weather","they produce better photographs"], answer: 0, explanation: "'the decision about whether to investigate has become cheap'" },
      { q: "How has her spending changed?", options: ["it has increased substantially","she spends on chosen work rather than failures","more goes on access equipment","less is spent on inspection"], answer: 1, explanation: "'she now spends it on things she chose rather than on things that had already failed'" }
    ]
  },
  {
    id: "fce-rmc20-02",
    title: "The Orchestra's Librarian",
    text: "An orchestra of ninety players cannot simply open a box of music and begin. Somebody has to obtain the correct edition, check it against the conductor's, mark every string part with the bowings agreed at the first rehearsal, arrange the page turns so that no player is required to turn during a passage they are playing, and have all of it on the stands before anybody arrives. That person is the librarian, and Joanna Feltrin has done the job for a mid-sized orchestra for sixteen years. She describes it as a job in which everything visible is a mistake. Nobody notices a well-prepared part. Everybody notices a violinist reaching for a page with a bow in their hand. The bowings are the largest single task and the least understood outside the profession. When the principal of a string section decides how a phrase will be bowed, that decision must appear in every copy of that part, because a section in which half the bows move up and half move down produces a visibly and audibly ragged sound. On a busy week this is several thousand pencil marks, and Feltrin employs two casual copyists during festival season. Digital parts on tablets have been arriving slowly, and her view of them is not the one people expect from a person whose job involves paper. She thinks they solve the page turn problem completely and create two new ones: a battery is a single point of failure in a live performance, and a tablet cannot be marked as fast as a pencil can during a rehearsal in which a conductor is changing their mind. Her orchestra now runs both. The music that is technically difficult and unlikely to change stays on tablets. Anything new, or anything with a conductor she has not worked with, stays on paper, and she says that this second category is not about technology at all but about how much correction she expects to be doing at half past nine on a Thursday night.",
    questions: [
      { q: "What must be done before a rehearsal?", options: ["the conductor must approve the seating","the hall must be tested for acoustics","parts must be prepared, marked and laid out","players must collect their own music"], answer: 2, explanation: "'have all of it on the stands before anybody arrives'" },
      { q: "How does Feltrin describe her job?", options: ["as impossible to do without help","as more musical than administrative","as the busiest role in the orchestra","as one where everything visible is a mistake"], answer: 3, explanation: "'a job in which everything visible is a mistake'" },
      { q: "Why must bowings be copied into every part?", options: ["mixed bowing looks and sounds ragged","players cannot memorise them","the conductor checks each copy","the publisher requires it"], answer: 0, explanation: "'a section in which half the bows move up and half move down produces a visibly and audibly ragged sound'" },
      { q: "What does she do in festival season?", options: ["she uses printed bowings from the publisher","she employs extra copyists","she works from home","she reduces the number of works played"], answer: 1, explanation: "'Feltrin employs two casual copyists during festival season'" },
      { q: "What problems do tablets create?", options: ["they are too heavy for music stands","they are expensive to replace","batteries fail and marking is slow","the screens are hard to read on stage"], answer: 2, explanation: "'a battery is a single point of failure… and a tablet cannot be marked as fast as a pencil'" },
      { q: "What stays on paper?", options: ["the most technically difficult music","music the orchestra plays regularly","anything for a large audience","anything likely to need corrections"], answer: 3, explanation: "'about how much correction she expects to be doing at half past nine on a Thursday night'" }
    ]
  },
  {
    id: "fce-rmc20-03",
    title: "The Date in the Timber",
    text: "The barn behind a farmhouse in Herefordshire was assumed by everybody who owned it to be Victorian. It is in fact a substantial timber-framed building of 1428, and this is known to the year because trees lay down one ring each growing season and the width of each ring depends on the weather that year, so a sequence of rings from a beam is a record of a run of seasons and can be matched against a master sequence built from timbers already dated. The technique is dendrochronology and its precision surprises people who expect archaeological dating to be approximate. Where the outermost layer of the tree survives, the felling can be dated to a season: winter 1428 rather than 1428. Since medieval builders used timber green, within a year or two of felling, the felling date is usually the building date. The limitations are real and specific. The method needs enough rings, so fast-grown timber with thirty rings is useless while slow-grown oak with a hundred and twenty is ideal. It needs the outer wood to survive, and a beam that has been squared off by a carpenter has lost the very layers that matter. It works well for oak in Britain because the master sequences are long and detailed, and poorly for species and regions where they are not. Dr Rhian Talbot, who dates buildings for a living, says the part of the job that has changed most is not the science but the conversation afterwards. Owners are frequently told their house is older than they believed, which pleases them, and occasionally told it is younger, which does not. She has learned to explain the method before giving the result rather than after, having discovered that a person who has just been told their sixteenth-century cottage was built in 1732 will hear an explanation as an excuse.",
    questions: [
      { q: "How old is the barn actually?", options: ["it dates from 1428","it is Victorian as assumed","it was built in 1732","its age cannot be established"], answer: 0, explanation: "'a substantial timber-framed building of 1428'" },
      { q: "What makes the rings useful for dating?", options: ["each ring is exactly the same width","ring width records the weather of that year","rings can be counted from photographs","trees grow at a constant known rate"], answer: 1, explanation: "'the width of each ring depends on the weather that year'" },
      { q: "Why is the felling date usually the building date?", options: ["timber was stored for many years","records of building work survive","builders used timber while still green","trees were felled only when needed"], answer: 2, explanation: "'medieval builders used timber green, within a year or two of felling'" },
      { q: "What kind of timber works best?", options: ["young, fast-grown wood","timber from any species","recently felled timber","slow-grown oak with many rings"], answer: 3, explanation: "'slow-grown oak with a hundred and twenty is ideal'" },
      { q: "Why can a squared beam be useless?", options: ["the outer layers have been cut away","it is usually too small to sample","the surface has been treated","carpenters mixed timbers together"], answer: 0, explanation: "'a beam that has been squared off by a carpenter has lost the very layers that matter'" },
      { q: "Why does Talbot explain the method first?", options: ["the explanation takes a long time","otherwise it sounds like an excuse","the result is easier to understand then","owners ask for it in advance"], answer: 1, explanation: "'will hear an explanation as an excuse'" }
    ]
  },
  {
    id: "fce-rmc20-04",
    title: "Reading Scans at Night",
    text: "A patient scanned at two in the morning in a British hospital may have the images reported by a radiologist in Australia, for whom it is mid-afternoon, and this arrangement is now routine enough that most people affected by it are unaware it exists. The logic is straightforward. Radiology reporting requires concentration of a kind that degrades sharply with fatigue, night shifts are known to produce more errors than day shifts in every profession where the comparison has been made, and a doctor working a normal day somewhere else is, on the evidence, safer than a tired one nearby. The arrangement is also expensive, which is why it is used for urgent overnight work rather than for everything. Dr Simon Bataille, who both reports for a teleradiology service and works in a British hospital, is a supporter with a specific reservation, and it is not about competence. Reporting is a task performed on images; it can be done anywhere. What cannot be done from twelve thousand kilometres away is the conversation. A radiologist in the building can be asked to look again, can walk to the ward, can say that a finding is probably nothing but that the patient's history makes them uneasy, and can be present when a decision is made at four in the morning by people who are frightened. Bataille says that the written report captures perhaps eighty per cent of what a radiologist knows and that the missing portion is the part that is hardest to write down and most useful in a difficult case. His own service now runs a video link staffed for the whole shift, which he says is used far less than it should be and mostly by junior doctors, who are the group least likely to feel entitled to ask and most likely to need to. Persuading them to use it, he says, has proved considerably harder than setting it up.",
    questions: [
      { q: "Why is overnight work sent abroad?", options: ["the equipment is better elsewhere","it is cheaper than paying local staff","a rested doctor makes fewer errors","British radiologists are in short supply"], answer: 2, explanation: "'a doctor working a normal day somewhere else is, on the evidence, safer than a tired one nearby'" },
      { q: "Why is it used only for urgent work?", options: ["time zones do not always match","the images take too long to send","hospitals prefer local reporting","the arrangement is expensive"], answer: 3, explanation: "'The arrangement is also expensive'" },
      { q: "What is Bataille's reservation about?", options: ["the conversation that cannot happen","the time taken to send reports","the competence of remote radiologists","the security of patient images"], answer: 0, explanation: "'What cannot be done from twelve thousand kilometres away is the conversation.'" },
      { q: "What does a written report fail to capture?", options: ["the quality of the images","the part hardest to write down","the exact location of a finding","the patient's medical history"], answer: 1, explanation: "'the missing portion is the part that is hardest to write down and most useful in a difficult case'" },
      { q: "Who mostly uses the video link?", options: ["nursing staff","radiographers","junior doctors","senior consultants"], answer: 2, explanation: "'mostly by junior doctors'" },
      { q: "What has proved hardest?", options: ["funding the service overnight","training staff to operate it","finding radiologists in other time zones","getting doctors to use the link"], answer: 3, explanation: "'Persuading them to use it, he says, has proved considerably harder than setting it up.'" }
    ]
  },
  {
    id: "fce-rmc20-05",
    title: "The Seeds in the Freezer",
    text: "A seed bank is not a museum. The seeds held in one are alive, they are expected to be planted eventually, and the entire operation is organised around the fact that they are slowly dying. Dried to about five per cent moisture and held at minus twenty degrees, the seeds of most species remain capable of germinating for decades and in some cases for centuries, but the rate of loss varies enormously and cannot be predicted from anything obvious about the plant. This is why the least glamorous activity in the building is also the most important. At intervals, a sample from each collection is taken out, warmed, sown and counted, and if germination has fallen below a threshold the collection must be grown out and replaced with fresh seed. Growing out is difficult, expensive and risky. It requires enough plants to preserve the genetic variation of the original collection, which for a wind-pollinated grass may mean several hundred individuals, and it requires isolation from related plants so that nothing crosses in. A collection regrown carelessly is not the collection that was deposited. Dr Aoife Brennan, who manages a national collection of crop wild relatives, says the public conversation about seed banks concentrates almost entirely on the vault and almost never on the field, which she regards as understandable and unfortunate: a vault is photogenic and a regeneration plot is a field of unremarkable grass. She also resists the common description of such banks as insurance against catastrophe. Their routine use is much duller and more valuable. Breeders request material constantly, and the wild relative of a crop, collected from a dry hillside in 1974 by somebody who had no particular reason to think it mattered, is where resistance to a new disease is most likely to be found. Brennan says the collections that turn out to matter are almost never the ones anybody predicted, which is the argument for collecting broadly and the hardest argument to fund.",
    questions: [
      { q: "How are the seeds stored?", options: ["dried and kept at minus twenty degrees","in sealed jars at room temperature","in soil in controlled greenhouses","frozen in water"], answer: 0, explanation: "'Dried to about five per cent moisture and held at minus twenty degrees'" },
      { q: "Why is testing germination so important?", options: ["it identifies mislabelled collections","seeds lose viability at unpredictable rates","it is required by international rules","it shows which species grow fastest"], answer: 1, explanation: "'the rate of loss varies enormously and cannot be predicted'" },
      { q: "What does growing out require?", options: ["a short growing season","the original collector's records","enough plants to keep the genetic variation","seeds from more than one bank"], answer: 2, explanation: "'It requires enough plants to preserve the genetic variation of the original collection'" },
      { q: "Why does the public focus on the vault?", options: ["it is where the work is done","it is open to visitors","the fieldwork is kept private","a field of grass is unremarkable"], answer: 3, explanation: "'a vault is photogenic and a regeneration plot is a field of unremarkable grass'" },
      { q: "How are the collections mostly used?", options: ["by breeders requesting material","as a reserve after disasters","for teaching and research visits","to restore damaged habitats"], answer: 0, explanation: "'Breeders request material constantly'" },
      { q: "What is Brennan's argument for broad collecting?", options: ["rare species disappear fastest","the useful collections are never predicted","storage costs are falling","other countries expect it"], answer: 1, explanation: "'the collections that turn out to matter are almost never the ones anybody predicted'" }
    ]
  },
  {
    id: "fce-rmc20-06",
    title: "The Laboratory That Breaks Toys",
    text: "In a testing laboratory on an industrial estate, a machine drops a wooden train onto a steel plate a hundred times from a metre, another pulls the arm of a soft toy with a force of ninety newtons, and a technician pushes a set of gauges into every opening on a plastic tractor. The work looks destructive and is entirely procedural: every test corresponds to a numbered clause in a standard, and the laboratory's job is not to decide whether a toy is safe but to establish whether it does what the standard says it must. Whether the standard is right is a different argument conducted elsewhere. The most consequential tests are the least dramatic. A small parts cylinder is a tube of specified dimensions representing the throat of a child under three; anything that fits inside it entirely is a choking hazard and the toy fails. A magnet test measures flux, because two small magnets swallowed separately can attract each other through the wall of the gut, which is the reason a particular class of toy vanished from the market. Cords are measured for length and loops for circumference. The laboratory's manager, Tanvir Shah, says the pattern of failures has changed markedly in the fifteen years he has worked there. Established manufacturers rarely fail on design now, having internalised the standards, and fail instead on production changes: a supplier substituting a slightly different fabric, a paint reformulated for cost. What has genuinely changed the picture is direct online sale, where a product arrives from a factory to a customer without any importer who is legally responsible for testing it. Shah is careful about how he puts this. He does not say such products are dangerous, because most are fine and his laboratory sees a biased sample. What he says is narrower: nobody has checked, and the entire system he works in assumes that somebody has.",
    questions: [
      { q: "What is the laboratory's role?", options: ["to design safer products","to investigate accidents","to check whether toys meet the standard","to decide which toys are safe"], answer: 2, explanation: "'not to decide whether a toy is safe but to establish whether it does what the standard says it must'" },
      { q: "What does the small parts cylinder represent?", options: ["a standard packing size","the gap in a cot","a child's hand","the throat of a young child"], answer: 3, explanation: "'a tube of specified dimensions representing the throat of a child under three'" },
      { q: "Why are magnets tested?", options: ["swallowed magnets can attract through the gut","they detach easily from toys","they can overheat in use","they interfere with electronics"], answer: 0, explanation: "'two small magnets swallowed separately can attract each other through the wall of the gut'" },
      { q: "How do established manufacturers now fail?", options: ["by selling online directly","through changes in production","by ignoring new standards","by using untested designs"], answer: 1, explanation: "'fail instead on production changes'" },
      { q: "What has changed the picture most?", options: ["cheaper testing equipment","more complex electronic toys","direct online selling without an importer","stricter European standards"], answer: 2, explanation: "'direct online sale, where a product arrives from a factory to a customer without any importer'" },
      { q: "What does Shah carefully avoid saying?", options: ["that his laboratory is overloaded","that manufacturers are dishonest","that the standards are too weak","that such products are dangerous"], answer: 3, explanation: "'He does not say such products are dangerous'" }
    ]
  },
  {
    id: "fce-rmc20-07",
    title: "The Interpreter in Court",
    text: "A court interpreter does not translate. The distinction is enforced strictly and is the first thing explained on any training course: the interpreter renders what was said, in the register in which it was said, without improving it, shortening it or repairing it. If a witness gives a rambling answer, the interpreter gives a rambling answer. If a witness swears, so does the interpreter, in the first person, in a courtroom, which trainees find harder than any technical vocabulary. The reason for the rule is that the court is assessing the witness, and a witness whose evidence has been tidied up by a helpful interpreter is not the witness the court believes it is hearing. Ivana Petrić has interpreted between Croatian and English in criminal courts for twelve years and says the hardest part of the work is not vocabulary or speed but the moment when she must interrupt. An interpreter is required to stop proceedings if she is unsure, if a term has no equivalent, or if she has made an error, and doing so means telling a judge, in front of a jury, that the last two minutes need repeating. She says a new interpreter's instinct is always to guess and catch up, that this is the source of almost every serious failure in the profession, and that the confidence to interrupt takes about three years to acquire. There are structural problems she is less able to solve. Rates for court work have not risen in over a decade, the qualified pool for some languages is very small, and a case may be adjourned because no interpreter of a given language is available within a day's travel, which is expensive for everybody and is generally reported as an administrative failure rather than as the predictable result of what the work pays. Petrić continues because, she says, the alternative for the defendant is a hearing they cannot follow, and she has seen one of those.",
    questions: [
      { q: "What must an interpreter do with a rambling answer?", options: ["render it exactly as it was given","summarise it for the court","ask the witness to repeat it clearly","record it for later translation"], answer: 0, explanation: "'If a witness gives a rambling answer, the interpreter gives a rambling answer.'" },
      { q: "Why must nothing be tidied up?", options: ["the rules of evidence forbid editing","the court is assessing the witness","the recording must match the transcript","lawyers object to any changes"], answer: 1, explanation: "'the court is assessing the witness'" },
      { q: "What does Petrić find hardest?", options: ["keeping up with rapid speech","learning legal vocabulary","having to interrupt the proceedings","working in front of a jury"], answer: 2, explanation: "'the hardest part of the work is not vocabulary or speed but the moment when she must interrupt'" },
      { q: "What causes most serious failures?", options: ["poor training in legal terms","interpreters working when tired","courts rushing the proceedings","guessing rather than stopping"], answer: 3, explanation: "'a new interpreter's instinct is always to guess and catch up, that this is the source of almost every serious failure'" },
      { q: "How is an adjournment for lack of an interpreter usually reported?", options: ["as an administrative failure","as a problem with court funding","as the fault of the interpreter","as a consequence of low pay"], answer: 0, explanation: "'is generally reported as an administrative failure'" },
      { q: "Why does she continue with the work?", options: ["the pay is better than other translation","she has seen a defendant unable to follow a hearing","there are few other interpreters available","the hours suit her circumstances"], answer: 1, explanation: "'the alternative for the defendant is a hearing they cannot follow, and she has seen one of those'" }
    ]
  },
  {
    id: "fce-rmc20-08",
    title: "The Painting That Was Not by Anyone",
    text: "In 1961 a regional museum bought a small portrait attributed to a minor seventeenth-century Dutch painter, and in 2016 a conservator removing discoloured varnish found beneath it a passage of painting that could not have been made before about 1890. The picture is a forgery, of a competent and unambitious kind, and what happened next is more interesting than the discovery. The obvious course was to remove it from display, and the museum did the opposite. It is now shown in a case of its own with the technical evidence beside it: the ultraviolet photograph, the paint cross-section, the canvas analysis and a plain account of how the museum came to buy it, including the fact that the dealer was reputable and that two specialists of the period agreed with the attribution at the time. The curator responsible, Helena Vondra, says the decision was not a gesture of institutional honesty so much as a recognition that the object had become more useful than it had been. As a minor Dutch portrait it was one of eleven similar things in the collection and was rarely looked at. As a forgery with its workings shown, it is the most visited case in the building, and school groups do more thinking in front of it than in front of anything else. Her argument goes further than the individual picture. Museums, she says, present conclusions and hide the process by which conclusions were reached, and the effect is to teach visitors that expertise is a matter of authority rather than of evidence that can be examined and can turn out to be wrong. She accepts that this cannot be done with everything, since a gallery in which every label rehearsed its own uncertainty would be unreadable. Her compromise is one case per gallery, and she says the difficulty is not curatorial but emotional: the objects that would teach the most are the ones the museum is most embarrassed about.",
    questions: [
      { q: "How was the forgery discovered?", options: ["through a study of museum records","when the dealer admitted it","during cleaning of the varnish","by comparing it with another painting"], answer: 2, explanation: "'a conservator removing discoloured varnish found beneath it a passage of painting'" },
      { q: "What did the museum do with the painting?", options: ["it returned it to the dealer","it sold it to a private collector","it put it in storage","it displayed it with the evidence"], answer: 3, explanation: "'It is now shown in a case of its own with the technical evidence beside it'" },
      { q: "Why does Vondra say the decision was made?", options: ["the object had become more useful","the museum wished to appear honest","the trustees insisted on it","it attracted press attention"], answer: 0, explanation: "'a recognition that the object had become more useful than it had been'" },
      { q: "What was the painting like before?", options: ["kept in a separate building","one of eleven similar and rarely noticed","one of the most popular works there","damaged and rarely lent out"], answer: 1, explanation: "'it was one of eleven similar things in the collection and was rarely looked at'" },
      { q: "What does she say museums usually do?", options: ["rely too heavily on outside experts","overstate the value of their collections","present conclusions and hide the process","avoid displaying recent acquisitions"], answer: 2, explanation: "'Museums, she says, present conclusions and hide the process'" },
      { q: "What does she say the real difficulty is?", options: ["disagreement among curators","finding space for such displays","the cost of technical analysis","embarrassment about the best examples"], answer: 3, explanation: "'the objects that would teach the most are the ones the museum is most embarrassed about'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
