/* FCE Prep bank: reading multiple-choice (wave 19) */
(function () {
var BANK = [
  {
    id: "fce-rmc19-01",
    title: "The Post Boat",
    text: "The mail for the four inhabited islands in the sound is carried by a boat that leaves at half past seven and calls at each of them in an order determined by the tide rather than by the timetable. Callum Ross has skippered it for fourteen years. He is employed as a boatman and describes his actual role as considerably broader, since the boat carries not only letters and parcels but prescriptions from the mainland pharmacy, a weekly newspaper order, occasional livestock, and any islander who needs to be somewhere. None of these except the mail appears in his contract. The arrangement works because everybody involved treats the contract as a floor rather than a description, and it is the kind of arrangement that inspection regimes find difficult to accommodate. Ross has twice been visited by people from head office who wanted to know why the boat was thirty minutes later than scheduled on Thursdays, and both times the answer was a resident who has an appointment on the mainland on Thursdays and cannot manage the earlier crossing. The islands' population is ninety-one, of whom nineteen are over seventy-five, and the delivery round is the mechanism by which somebody checks on them. Ross carries a list of six households where, if the previous day's post is still in the box, he knocks. He has used it four times in fourteen years and on two of those occasions it mattered. He is careful when talking about this, because he has read the newspaper articles about postal workers as a lifeline and finds them faintly ridiculous: he says he is not a care service, has no training, and would rather the islands had a properly funded one. What he objects to is not the description but its use as a substitute. A service that depends on the boatman noticing is a service that ends when a boatman is appointed who has not thought about it, and nobody, he points out, has ever written that requirement into the job.",
    questions: [
      { q: "What determines the order of the boat's calls?", options: ["the tide rather than the timetable","the amount of mail for each island","the weather forecast that morning","requests made by residents"], answer: 0, explanation: "'in an order determined by the tide rather than by the timetable'" },
      { q: "What does the boat carry besides mail?", options: ["building materials for the islands","prescriptions, newspapers and passengers","fuel for the island generators","school pupils to the mainland"], answer: 1, explanation: "'prescriptions from the mainland pharmacy, a weekly newspaper order, occasional livestock, and any islander who needs to be somewhere'" },
      { q: "Why is the boat late on Thursdays?", options: ["the tide is unfavourable then","extra deliveries must be sorted","a resident has a mainland appointment","the boat is refuelled that day"], answer: 2, explanation: "'a resident who has an appointment on the mainland on Thursdays'" },
      { q: "What is his list of six households for?", options: ["households that receive most post","those who pay for a special service","new residents needing directions","people he checks on if post is uncollected"], answer: 3, explanation: "'if the previous day's post is still in the box, he knocks'" },
      { q: "How does he react to being called a lifeline?", options: ["he finds the description faintly ridiculous","he accepts it with some pride","he says it applies to other routes","he refuses to discuss it at all"], answer: 0, explanation: "'finds them faintly ridiculous'" },
      { q: "What is his actual objection?", options: ["the work is not properly paid","the description is used as a substitute for a real service","head office does not understand the islands","the timetable should be rewritten"], answer: 1, explanation: "'What he objects to is not the description but its use as a substitute.'" }
    ]
  },
  {
    id: "fce-rmc19-02",
    title: "The Woodland That Was Planted Wrong",
    text: "Twenty-two thousand trees were planted on a hillside above Brackenthwaite in the winter of 2009, and by 2019 rather fewer than half were alive. The failure was not caused by neglect: the site was fenced, the trees were weeded for three years and the planting was done properly. What went wrong was the choice, and it went wrong in three separate ways that between them account for most failed planting schemes in Britain. The first was the species mix, which was designed for a soil type recorded on a map made in 1974 and not for the soil that is actually there. The second was provenance. The saplings were grown from seed collected several hundred kilometres to the south, which produces trees that come into leaf too early for a Cumbrian spring and are cut back by late frosts year after year until they give up. The third was the most avoidable. Planting was funded by a grant with a deadline, the deadline fell in a wet autumn, and the contractor planted anyway because the alternative was losing the money. Dr Elin Vaughan, who has surveyed the site three times, uses it in teaching because every one of these problems was known before 2009 and none of them was a matter of opinion. Her wider point concerns how such schemes are counted. The grant was reported as twenty-two thousand trees planted, which was true, and no mechanism existed for reporting the number alive at ten years, which is the number that matters and which nobody was required to collect. The scheme's successor programme now pays in three instalments, the last of which depends on survival at year five, and Vaughan describes this as the single most useful change made in her working life. She adds that the surviving trees at Brackenthwaite, being the ones that suited the site, are now seeding themselves down the slope, and that the wood will eventually establish itself in roughly the shape it would have taken without any of them.",
    questions: [
      { q: "Why did the planting fail?", options: ["the trees were never weeded","the hillside was too exposed","the wrong choices were made from the start","the site was not properly fenced"], answer: 2, explanation: "'What went wrong was the choice'" },
      { q: "What was wrong with the species mix?", options: ["the trees were planted too closely together","it contained too few species","the species were not native to Britain","it suited a soil recorded on an old map"], answer: 3, explanation: "'designed for a soil type recorded on a map made in 1974 and not for the soil that is actually there'" },
      { q: "Why did the provenance matter?", options: ["the trees came into leaf too early","the seed was collected too late in the year","southern seed was more expensive","the saplings carried a disease"], answer: 0, explanation: "'trees that come into leaf too early for a Cumbrian spring and are cut back by late frosts'" },
      { q: "Why did planting go ahead in a wet autumn?", options: ["the site was drier than expected","the grant deadline would otherwise be missed","the weather forecast was wrong","the trees would not have survived storage"], answer: 1, explanation: "'the contractor planted anyway because the alternative was losing the money'" },
      { q: "What was wrong with how the scheme was reported?", options: ["the costs were not published","the survey came too late","nobody had to record survival at ten years","the number planted was exaggerated"], answer: 2, explanation: "'no mechanism existed for reporting the number alive at ten years'" },
      { q: "What change does Vaughan most approve of?", options: ["longer deadlines for planting","independent surveys of every site","stricter rules on seed collection","payment partly dependent on survival"], answer: 3, explanation: "'the last of which depends on survival at year five'" }
    ]
  },
  {
    id: "fce-rmc19-03",
    title: "The Dog That Finds Newts",
    text: "Before a development can proceed on a site where great crested newts may be present, somebody has to establish whether they are. The traditional method involves visiting ponds at night with a torch for several weeks in spring, and it produces a great many negative results that mean only that nobody saw one. For about a decade some surveys have used dogs instead. A trained detection dog can locate newts in their terrestrial phase, under logs and stones and hundreds of metres from any water, at a season when the torch method finds nothing at all. Handler Fiona Naylor works with two spaniels and is precise about what the dogs do and do not offer. They are fast, they cover ground a surveyor cannot, and they find animals in places nobody would have looked. They are not a substitute for the survey, because a dog cannot count a population or say anything about breeding. What they are extremely good at is the negative result: a site a trained dog has worked thoroughly and found nothing on is a site that is probably genuinely empty, and that conclusion is worth a great deal to a developer who would otherwise be paying for six weeks of torchlight. The training takes about eighteen months and the difficult part is not teaching the dog the scent. It is the handler. Naylor says a handler who wants to find newts will unconsciously direct the dog towards likely-looking ground, and the dog, which is reading the handler continuously, will produce an indication to please them. The standard test for this is a blind trial in which the handler does not know whether anything is present, and she says that failing one is a normal part of training and that any handler who claims never to have failed one has not been tested properly. She works her dogs for forty minutes at a time. After that, she says, they are still willing, which is exactly the problem.",
    questions: [
      { q: "What is the drawback of the torch method?", options: ["it produces many meaningless negative results","it disturbs the newts' breeding","it can only be used in summer","it requires expensive equipment"], answer: 0, explanation: "'it produces a great many negative results that mean only that nobody saw one'" },
      { q: "What can a detection dog do that surveyors cannot?", options: ["count the size of a population","find newts far from water and under cover","identify individual animals","work in complete darkness"], answer: 1, explanation: "'locate newts in their terrestrial phase, under logs and stones and hundreds of metres from any water'" },
      { q: "What are the dogs especially useful for?", options: ["confirming that a site is occupied","checking sites during the breeding season","establishing that a site is empty","monitoring ponds over several years"], answer: 2, explanation: "'What they are extremely good at is the negative result'" },
      { q: "What is the hardest part of training?", options: ["teaching the dog the correct scent","keeping the dog working for long periods","finding suitable sites for practice","training the handler"], answer: 3, explanation: "'It is the handler.'" },
      { q: "What mistake do handlers make?", options: ["they steer the dog towards likely ground","they work the dogs for too long","they ignore the dog's indications","they test on sites that are too easy"], answer: 0, explanation: "'a handler who wants to find newts will unconsciously direct the dog towards likely-looking ground'" },
      { q: "Why does she stop after forty minutes?", options: ["the scent becomes harder to detect","the dogs remain willing when they should not be","the legal limit is forty minutes","the handler loses concentration"], answer: 1, explanation: "'they are still willing, which is exactly the problem'" }
    ]
  },
  {
    id: "fce-rmc19-04",
    title: "The Box on the Village Green",
    text: "The disused telephone kiosk on the green at Nether Cawton now contains a defibrillator, which is the commonest second life for such a box and one of the more useful things a parish council can arrange. The equipment cost about eleven hundred pounds, raised at two events, and the kiosk itself was bought from the telephone company for one pound. What the parish council did not initially understand, and what the ambulance service explained at some length, is that the machine is the least important part of the arrangement. Survival after a cardiac arrest outside hospital depends overwhelmingly on two things happening in the first few minutes: somebody starting chest compressions, and a shock being delivered if the rhythm is one that responds to it. A defibrillator in a box four hundred metres away contributes nothing unless a second person is present to fetch it, which is why the ambulance service's advice is that the caller should never leave the patient to collect it. The village therefore did the part that takes longer than fundraising. Forty-one residents have now been through a two-hour session, the box is registered on the national database so that the emergency operator can direct a caller to it, and the code is given out by the operator rather than displayed, which surprises visitors and prevents the equipment being taken. The parish clerk checks the machine monthly and records it, a task she describes as the least interesting recurring item in her life and the one she would be least willing to give up, since a defibrillator with a flat battery is worse than none at all: it is a piece of equipment everybody believes in. The machine has been used twice. On the first occasion the patient survived; on the second he did not, and the clerk says the village's reaction to the second, which was to hold another training session rather than to conclude that the scheme had failed, is the thing she is proudest of.",
    questions: [
      { q: "What does the old telephone box now hold?", options: ["a village noticeboard","emergency supplies","a defibrillator","a small library of books"], answer: 2, explanation: "'now contains a defibrillator'" },
      { q: "What did the ambulance service explain?", options: ["the equipment needs annual servicing","only trained people may use it","the box must be locked at all times","the machine is the least important part"], answer: 3, explanation: "'the machine is the least important part of the arrangement'" },
      { q: "Why should a caller never fetch it themselves?", options: ["the patient must not be left alone","the machine takes time to start","the code may not work","the box may be too far away"], answer: 0, explanation: "'the caller should never leave the patient to collect it'" },
      { q: "Why is the code not displayed on the box?", options: ["the operator prefers to record each use","it prevents the equipment being stolen","it changes every month","residents would forget it"], answer: 1, explanation: "'prevents the equipment being taken'" },
      { q: "Why does the clerk value the monthly check?", options: ["it reminds residents that it is there","the battery must be replaced often","a defibrillator with a flat battery is worse than none","the council requires a written record"], answer: 2, explanation: "'a defibrillator with a flat battery is worse than none at all'" },
      { q: "What is she proudest of?", options: ["the number of residents trained","being registered on the national database","the amount of money raised","the village's response after the second use"], answer: 3, explanation: "'to hold another training session rather than to conclude that the scheme had failed'" }
    ]
  },
  {
    id: "fce-rmc19-05",
    title: "Deciding to Grit",
    text: "The decision to send out gritting lorries is made once or twice a day through the winter by a duty officer looking at a forecast of road surface temperature, which is not the same as air temperature and can differ from it by four or five degrees. Roads lose heat by radiation to a clear sky, so a still, cloudless night produces ice on a surface that never fell below freezing in any air-temperature forecast, while a windy night at minus two may produce none at all. The forecasts are specific to individual stretches of road, generated from sensors buried in the carriageway at sites chosen to represent a wider network: a bridge deck, which cools fastest; a sheltered valley bottom, where cold air collects; an exposed ridge. Duty officer Sam Okonjo describes the job as a series of decisions with asymmetric consequences. Gritting unnecessarily costs about nine thousand pounds a night across his area, wastes salt, and is invisible to the public. Not gritting when it was needed produces collisions and appears on the local news. The asymmetry pushes every officer towards caution, and the discipline of the job is resisting that push, because a service that grits every marginal night runs out of budget in February and has nothing left for the nights that matter. The change he regards as most useful is not technological. It is that his authority now publishes its decisions and the reasoning, briefly, each morning. The first winter of doing this was uncomfortable, since the record makes wrong calls visible, but complaints have fallen and he attributes this to the difference between a service that appears not to have bothered and one that can be seen to have decided. He adds that the mornings he most dreads are not the icy ones. They are the ones where he decided not to grit and was right, and nothing happened, and nobody knows there was a decision at all.",
    questions: [
      { q: "Why is air temperature not enough?", options: ["road surface temperature can differ by several degrees","air temperature is measured too infrequently","roads freeze at a higher temperature","forecasts of air temperature are unreliable"], answer: 0, explanation: "'which is not the same as air temperature and can differ from it by four or five degrees'" },
      { q: "When can ice form despite mild air temperatures?", options: ["on windy nights","on still, cloudless nights","after heavy rainfall","when traffic is heavy"], answer: 1, explanation: "'a still, cloudless night produces ice on a surface that never fell below freezing'" },
      { q: "Why are sensor sites chosen carefully?", options: ["to keep installation costs down","to avoid damage from traffic","to represent different parts of the network","to make maintenance easier"], answer: 2, explanation: "'at sites chosen to represent a wider network'" },
      { q: "What does Okonjo mean by asymmetric consequences?", options: ["decisions must be made very quickly","some roads matter more than others","costs vary between areas","the two kinds of mistake are not equal"], answer: 3, explanation: "Gritting unnecessarily is 'invisible to the public' while not gritting 'appears on the local news'." },
      { q: "Why must officers resist being over-cautious?", options: ["the budget would run out too early","salt supplies are limited nationally","the lorries would wear out","the public would stop taking care"], answer: 0, explanation: "'a service that grits every marginal night runs out of budget in February'" },
      { q: "What effect did publishing decisions have?", options: ["more people questioned the reasoning","the number of complaints fell","other authorities copied the practice","decisions took longer to make"], answer: 1, explanation: "'complaints have fallen'" }
    ]
  },
  {
    id: "fce-rmc19-06",
    title: "Three in the Morning on the Helpline",
    text: "The volunteer who answers a listening helpline at three in the morning is trained principally not to do the thing that everybody's instinct demands, which is to fix the problem. The training runs to about sixty hours and a substantial part of it consists of exercises in which trainees are stopped, repeatedly, at the moment they begin a sentence with the words have you tried. Delia Whitmore, who has volunteered for nine years and now trains others, explains the reasoning without much sentiment. A caller at three in the morning has usually had a great deal of advice. What they have not had is the experience of describing their situation to somebody who does not interrupt, does not become upset, does not need them to feel better by the end of the call, and will not tell anybody. The last of these is the one callers test, often in the first minute, and the reason the service is anonymous in both directions. Volunteers work in pairs in a room, take calls for four hours, and are required to talk to somebody before going home, which is not optional and is the main thing that keeps them doing it. Whitmore says the calls people expect to be hardest are not. A caller in acute crisis is frightening but the volunteer's role is clear. What wears people down is the long call about nothing much, from somebody who is simply alone, which offers no resolution and no sense of having been useful, and which is arguably the call the service exists for. She is direct about what the work is not: it is not counselling, volunteers are not clinicians, and the training is explicit that a volunteer who begins to think of themselves as anybody's therapist is heading for a mistake. Her own summary, which she says she stole from somebody else, is that the job is to be the person who does not flinch, and that this is a much smaller thing than it sounds and much rarer.",
    questions: [
      { q: "What are volunteers trained not to do?", options: ["end the call too early","take notes during the call","try to solve the caller's problem","ask about the caller's background"], answer: 2, explanation: "'which is to fix the problem'" },
      { q: "What have most callers already had plenty of?", options: ["time to think alone","support from family","contact with medical services","advice"], answer: 3, explanation: "'A caller at three in the morning has usually had a great deal of advice.'" },
      { q: "What do callers often test early in the call?", options: ["whether the volunteer will tell anyone","whether anyone is really listening","whether the volunteer is trained","how long they may speak for"], answer: 0, explanation: "'The last of these is the one callers test, often in the first minute'" },
      { q: "What must volunteers do before going home?", options: ["review the calls with a manager","talk to somebody","complete a written report","hand over to the next pair"], answer: 1, explanation: "'are required to talk to somebody before going home'" },
      { q: "Which calls wear volunteers down most?", options: ["calls that are repeated night after night","calls where the caller is angry","long calls from people who are simply alone","calls from people in acute crisis"], answer: 2, explanation: "'What wears people down is the long call about nothing much'" },
      { q: "How does Whitmore summarise the job?", options: ["staying calm under pressure","giving people time to think","listening without judging","being the person who does not flinch"], answer: 3, explanation: "'the job is to be the person who does not flinch'" }
    ]
  },
  {
    id: "fce-rmc19-07",
    title: "Putting the Bends Back",
    text: "The river through the Aldworth estate was straightened in the 1840s, deepened in the 1930s and confined between raised banks in 1971, each time for a reason that made sense to the people doing it: to drain the meadows, to move water away faster, to protect the village downstream. In 2018 a contractor spent nine weeks putting the bends back. The reasoning behind such projects is easier to grasp once the straightening is understood as a device for moving water quickly, which is exactly what it is. A straight, deep, smooth channel delivers a rainstorm to the next settlement downstream faster and in a sharper peak than a winding, shallow, rough one does. In a small catchment this can be the difference between a flood and a wet field. Re-meandering restores length, roughness and the connection between the river and the ground beside it, so that a high flow spreads sideways into a floodplain designed to be flooded, which is a phrase that took the estate's manager two years of public meetings to make sound reasonable. The results at Aldworth are measurable and modest, which is the honest description of most such schemes. The peak flow downstream is lower by an amount that matters in a moderate event and would be overwhelmed in an extreme one. Water temperature in summer has fallen slightly, invertebrate diversity has risen substantially, and two species of fish have returned to a stretch where they had not been recorded since the 1950s. What the manager stresses most, when showing people round, is the meadow. Restoring the river meant accepting that eleven hectares of grazing would be under water several times a winter, which is a real cost carried by a real tenant, and he says any presentation that leaves this out will eventually be found out by somebody who farms and will discredit everything else in it.",
    questions: [
      { q: "Why was the river altered in the past?", options: ["for reasons that seemed sound at the time","because of pressure from landowners","to create a route for boats","to supply water to the village"], answer: 0, explanation: "'each time for a reason that made sense to the people doing it'" },
      { q: "What does a straightened channel do?", options: ["hold more water in the meadows","move water downstream faster","reduce erosion of the banks","keep the water cooler in summer"], answer: 1, explanation: "'a device for moving water quickly'" },
      { q: "What does re-meandering restore?", options: ["the original course from old maps","the depth of the channel","length, roughness and the link to the floodplain","the fish stocks of the 1840s"], answer: 2, explanation: "'restores length, roughness and the connection between the river and the ground beside it'" },
      { q: "How are the results described?", options: ["disappointing compared with predictions","better than any other scheme locally","impossible to measure so far","measurable and modest"], answer: 3, explanation: "'The results at Aldworth are measurable and modest'" },
      { q: "What has returned to the river?", options: ["two species of fish","a rare water plant","nesting birds","otters"], answer: 0, explanation: "'two species of fish have returned to a stretch where they had not been recorded since the 1950s'" },
      { q: "Why does the manager stress the meadow?", options: ["it is the most attractive part of the site","a real cost falls on a real tenant","it was the hardest part to construct","it will flood less than expected"], answer: 1, explanation: "'a real cost carried by a real tenant'" }
    ]
  },
  {
    id: "fce-rmc19-08",
    title: "The Trial That Could Not Recruit",
    text: "A clinical trial that cannot enrol enough participants does not usually fail dramatically. It runs late, extends its recruitment window, lowers its target, reports an underpowered result that answers nothing, and disappears. Roughly half of all trials fail to recruit to target, a proportion that has not improved in twenty years despite being extremely well documented, and the reasons are known in some detail. Trials are designed by people who see the illness and not the week. A protocol requiring five hospital visits in three months is trivial to write and, for a person who works shifts and has no car, an impossibility. Eligibility criteria are drawn tightly to produce a clean result and exclude the patients most likely to be prescribed the treatment afterwards. Recruitment depends on busy clinicians remembering to mention the trial in a twelve-minute appointment during which they have other things to do. Dr Marcus Feld, who has run trials for eighteen years and has had two fail to recruit, says the change that made most difference to his own work was neither funding nor advertising. It was asking patients to read the protocol before it was submitted. The first time he did this, a group of four people with the condition being studied removed two of the five visits by pointing out that the tests could be done locally, objected to a diary that had to be completed daily rather than weekly, and asked why the trial excluded anyone over seventy-five, a question to which the honest answer was that the previous trial had done so. That trial recruited to target in nine months. Feld is careful not to present this as a discovery, since patient involvement has been formally required by British funders for over a decade. His point is narrower and less comfortable: the requirement is frequently met by a signature on a form, and the difference between meeting it and doing it is the difference between his two failed trials and his last four.",
    questions: [
      { q: "What usually happens to a trial that cannot recruit?", options: ["its results are never published at all","it is stopped by the funder","it fades away with a useless result","it is redesigned and restarted"], answer: 2, explanation: "'reports an underpowered result that answers nothing, and disappears'" },
      { q: "What does the writer say about trial designers?", options: ["they have too little clinical experience","they rarely consult other researchers","they underestimate the costs involved","they see the illness and not the week"], answer: 3, explanation: "'Trials are designed by people who see the illness and not the week.'" },
      { q: "What is the effect of tight eligibility criteria?", options: ["the patients who would use the drug are excluded","the trial becomes more expensive","results take longer to analyse","fewer hospitals can take part"], answer: 0, explanation: "'exclude the patients most likely to be prescribed the treatment afterwards'" },
      { q: "What change made most difference for Feld?", options: ["recruiting through general practice","letting patients read the protocol first","increasing the advertising budget","paying participants' travel costs"], answer: 1, explanation: "'It was asking patients to read the protocol before it was submitted.'" },
      { q: "What did the patient group point out?", options: ["the treatment was already available","the diary was unnecessary","some tests could be done locally","the trial was too short"], answer: 2, explanation: "'by pointing out that the tests could be done locally'" },
      { q: "What is his less comfortable point?", options: ["clinicians resist changes to protocols","the problem cannot be solved at all","funders do not enforce their own rules","patient involvement is often only a signature"], answer: 3, explanation: "'the requirement is frequently met by a signature on a form'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
