/* FCE Prep bank: reading multiple-choice (wave 16) */
(function () {
var BANK = [
  {
    id: "fce-rmc16-01",
    title: "The Fifty-Year Experiment",
    text: "On the edge of an agricultural research station in Hertfordshire there are twenty-four narrow strips of grassland that have been treated in exactly the same way, each of them differently, since before anybody now working there was born. One strip has received no fertiliser at all. One has received nitrogen every spring. One is limed and one is not, and the boundary between them, invisible in the soil, is obvious from a distance because the plants growing on either side are not the same plants. The value of such an experiment is that it answers questions nobody thought to ask when it began. Its designers were interested in hay yields. What the strips have since been used for includes the acidification of soil by nitrogen, the loss of plant diversity under fertiliser, the accumulation of heavy metals from the atmosphere and, most recently, the changing chemistry of rainfall, none of which were live questions in the nineteenth century. Samples of soil and of the crop have been dried and stored from the beginning, which means a researcher can now measure something in a jar of soil from 1876 using an instrument invented in 2019. The threats to a long experiment are not scientific. They are administrative, and the station's staff describe them with the weariness of people who have fought the same argument for decades: a change of ownership, a new director with a strategic plan, a car park that has to go somewhere, a funding cycle that asks what has been discovered in the last three years. The current custodian, Dr Priya Raman, says her real job is not the science but continuity, and that she measures success by whether the person doing it in 2075 still has twenty-four strips. She adds that the experiment's greatest contribution may not have been made yet, which is an unusual thing to be able to say about anything, and the only argument for keeping it that she has found genuinely persuades sceptical committees.",
    questions: [
      { q: "What is unusual about the twenty-four strips?", options: ["each has been treated the same way for over a century","they are all planted with the same crop","they were laid out only recently","they receive no treatment at all"], answer: 0, explanation: "'treated in exactly the same way, each of them differently, since before anybody now working there was born'" },
      { q: "How can the boundary between two strips be seen?", options: ["by a fence between them","by the difference in the plants growing","by markers placed along the edge","by the colour of the soil"], answer: 1, explanation: "'the plants growing on either side are not the same plants'" },
      { q: "Why is the experiment so valuable?", options: ["it produces higher yields than modern methods","it costs very little to maintain","it answers questions nobody originally asked","it is the only one of its kind"], answer: 2, explanation: "'it answers questions nobody thought to ask when it began'" },
      { q: "Why does the stored material matter?", options: ["it can be sold to other institutions","it proves the records are genuine","it saves the cost of new sampling","old samples can be tested with new instruments"], answer: 3, explanation: "'a researcher can now measure something in a jar of soil from 1876 using an instrument invented in 2019'" },
      { q: "What are the main threats to the experiment?", options: ["administrative rather than scientific ones","changes in the local climate","damage caused by visitors","the loss of skilled technicians"], answer: 0, explanation: "'They are administrative'" },
      { q: "How does Raman measure success?", options: ["by the number of papers published","by whether the strips still exist in 2075","by the amount of funding secured","by the interest shown by other stations"], answer: 1, explanation: "'whether the person doing it in 2075 still has twenty-four strips'" }
    ]
  },
  {
    id: "fce-rmc16-02",
    title: "Moving Back From the Sea",
    text: "The coast at Ellersby is retreating by about a metre and a half a year, and in a bad winter it takes considerably more. Six houses have gone since 1998. The county has spent thirty years defending the village with rock armour and groynes, and in 2020 it stopped, adopting instead a policy that is called managed realignment in official documents and moving back everywhere else. The engineering case for stopping is not seriously contested. The cliff is soft glacial till, which cannot be held indefinitely by anything affordable, and the defences at Ellersby were demonstrably increasing erosion four kilometres to the south by starving that beach of the sediment the cliff had been supplying. What was contested, bitterly, was everything to do with the people. The compensation scheme available at the time paid for demolition but not for the value of the house, on the grounds that coastal erosion is a natural process and the state does not insure against it. Residents pointed out that the same state had granted planning permission in the 1970s, had built the defences that persuaded people the village was safe, and was now describing the outcome as nature. The scheme has since been revised twice and remains, by common agreement, inadequate. What has worked better is the part nobody planned. A community group negotiated the purchase of a field inland, secured permission for eleven plots, and the households who wanted to stay in the village moved four hundred metres up the hill over six years. Ellersby did not disappear; it relocated, imperfectly and mostly at its own expense. The county's coastal officer is candid that this outcome depended on the field being available and on two residents who happened to be a solicitor and a retired planner, and that the next village along the coast has neither, which is the part of the story that keeps him awake.",
    questions: [
      { q: "What did the county stop doing in 2020?", options: ["granting planning permission locally","monitoring the rate of erosion","defending the village against the sea","paying compensation to residents"], answer: 2, explanation: "'The county has spent thirty years defending the village… and in 2020 it stopped'" },
      { q: "What harm did the defences cause?", options: ["they blocked access to the shore","they damaged the cliff at Ellersby itself","they made the beach unsafe for swimmers","they increased erosion further south"], answer: 3, explanation: "'increasing erosion four kilometres to the south by starving that beach of the sediment'" },
      { q: "What did residents object to in the compensation scheme?", options: ["it did not pay for the value of the house","it took too long to process claims","it applied only to older properties","payments were made in instalments"], answer: 0, explanation: "'paid for demolition but not for the value of the house'" },
      { q: "What argument did residents make in reply?", options: ["the defences had never been maintained","the state had encouraged them to build and stay","erosion had been faster than predicted","other villages had been treated better"], answer: 1, explanation: "'the same state had granted planning permission in the 1970s, had built the defences that persuaded people the village was safe'" },
      { q: "What happened to the village in the end?", options: ["it was bought by the county","it was abandoned completely","it moved a short distance inland","it was rebuilt behind a new sea wall"], answer: 2, explanation: "'the households who wanted to stay in the village moved four hundred metres up the hill'" },
      { q: "Why is the coastal officer still worried?", options: ["the new site may also be at risk","the compensation scheme has not been revised","the cost was higher than expected","the next village lacks the same advantages"], answer: 3, explanation: "'the next village along the coast has neither'" }
    ]
  },
  {
    id: "fce-rmc16-03",
    title: "The Wall That Holds Itself Up",
    text: "A dry stone wall contains no mortar of any kind. It stands because each stone is placed so that its weight presses the stones beneath it inwards, and a properly built wall becomes more stable as it settles, which is the opposite of what happens to most structures. There are perhaps a hundred and fifty full-time wallers left in Britain, and Ewan Fairlie, who has been one for thirty-one years, says the trade's problem is not that the skill is hard to learn. It takes about two years to become competent and the principles can be explained in an afternoon. The problem is the comparison with a fence. A contractor can erect two hundred metres of post and wire in a day for a fraction of what a waller charges to rebuild twenty metres, and a farmer looking at a quotation is not being foolish to choose the fence. Fairlie's argument, which he makes without much hope, is that the comparison is between two different lengths of time. The fence will need replacing in twenty years and again in forty. The wall he rebuilt for that farmer's grandfather is the wall he is rebuilding now, using the same stones, most of which were taken out of the field they enclose. He accepts that this is a poor argument for anybody who does not expect to be farming the same land in 2070, and that most people do not. Where the trade survives is in national parks, on estates with conservation obligations, and in the growing business of repairing walls for people who value them without needing them. Fairlie takes on one apprentice at a time and has trained nine. Six are still walling. He is more encouraged by this than by anything else in his working life, and notes that all six came to it from another job, none straight from school, which he has stopped trying to explain and now simply expects.",
    questions: [
      { q: "What holds a dry stone wall together?", options: ["the weight of the stones pressing inwards","a thin layer of mortar between courses","posts set into the ground at intervals","wire threaded through the stones"], answer: 0, explanation: "'each stone is placed so that its weight presses the stones beneath it inwards'" },
      { q: "What happens as such a wall settles?", options: ["it needs regular repointing","it becomes more stable","it gradually leans to one side","it must be rebuilt from the base"], answer: 1, explanation: "'a properly built wall becomes more stable as it settles'" },
      { q: "What does Fairlie say is not the trade's problem?", options: ["the cost of transporting stone","competition from other wallers","the difficulty of learning the skill","the weather during winter months"], answer: 2, explanation: "'the trade's problem is not that the skill is hard to learn'" },
      { q: "Why do farmers usually choose fencing?", options: ["it lasts longer than a stone wall","it can be moved when fields change","it needs no maintenance at all","far more can be built for the money"], answer: 3, explanation: "'A contractor can erect two hundred metres of post and wire in a day for a fraction of what a waller charges'" },
      { q: "What is the weakness of his own argument?", options: ["few people expect to farm the same land for decades","stone is no longer available locally","walls are less effective at containing animals","conservation rules may change"], answer: 0, explanation: "'a poor argument for anybody who does not expect to be farming the same land in 2070'" },
      { q: "What does he find most encouraging?", options: ["the growth of repair work on estates","six of his nine apprentices still work as wallers","interest from visitors to national parks","the rising price of his services"], answer: 1, explanation: "'Six are still walling.'" }
    ]
  },
  {
    id: "fce-rmc16-04",
    title: "The Voice on the Platform",
    text: "The announcements at most British stations are assembled rather than recorded. A voice artist spends several days in a studio reading numbers, place names, hours, minutes and fragments of sentence, each spoken three times with a different intonation so that the system can choose a version that rises, falls or stays level depending on where the fragment lands. The result is that a station can announce a train to a destination the artist has never read aloud, provided the parts exist. It also explains the small oddities regular passengers notice, where a place name arrives at a slightly wrong pitch, or a pause falls where no human would put one. Getting this right is a design problem rather than a technical one, and the person responsible for it at one operator, Lena Whitcombe, spends most of her effort on a question that surprises people: how much should be said at all. Her department's research found that passengers stop listening after about eight seconds, and that the announcement most often missed is the one immediately following a long one. Automated systems are extremely willing to be thorough. Left alone they will apologise, explain, list the calling points, name the operator and offer an apology again, by which time nobody has heard the platform number, which was the only part anybody needed. Her rule now is that the first six words carry the information and everything else is optional. She is also responsible for deciding when a human should override the system, and says the boundary is not about content but about uncertainty. A system can say a train is delayed by twenty minutes. Only a person can say that nobody currently knows how long the delay will be, that they will come back in ten minutes, and that they are sorry, and Whitcombe's surveys show that passengers rate this last announcement, which contains no information at all, more highly than any accurate estimate the machine produces.",
    questions: [
      { q: "How are most station announcements produced?", options: ["generated entirely by computer speech","read live by a person in a control room","assembled from separately recorded fragments","recorded fully by staff at each station"], answer: 2, explanation: "'A voice artist spends several days in a studio reading numbers, place names, hours, minutes and fragments of sentence'" },
      { q: "Why is each fragment recorded three times?", options: ["to cover several regional accents","in case one recording is damaged","to allow for changes in pronunciation","to provide different intonations"], answer: 3, explanation: "'each spoken three times with a different intonation'" },
      { q: "What does Whitcombe spend most effort on?", options: ["deciding how much to say","improving the sound quality","choosing the voice artist","training staff to use the system"], answer: 0, explanation: "'how much should be said at all'" },
      { q: "What did the research find about listening?", options: ["younger passengers listen less","passengers stop listening after about eight seconds","announcements are clearest in quiet stations","repeated announcements are ignored"], answer: 1, explanation: "'passengers stop listening after about eight seconds'" },
      { q: "What is the danger of a thorough system?", options: ["it wears out the equipment","it delays other announcements","the key detail is never heard","it confuses foreign visitors"], answer: 2, explanation: "'by which time nobody has heard the platform number'" },
      { q: "When should a human take over?", options: ["when the system develops a fault","when the station is very crowded","when several trains are delayed","when nobody knows what will happen"], answer: 3, explanation: "'Only a person can say that nobody currently knows how long the delay will be'" }
    ]
  },
  {
    id: "fce-rmc16-05",
    title: "When the Networks Go Down",
    text: "During a storm in 2021 that removed power from a large part of one county for four days, the local resilience group was co-ordinated for the first thirty hours by a retired teacher sitting in a garden shed with a radio set and a car battery. This is less surprising than it sounds. Amateur radio operators have been part of emergency planning in most countries for a century, and the reason is structural rather than nostalgic: a mobile network depends on masts, which depend on mains power and on a backhaul connection, and a mast with a flat battery is a metal tower. A radio operator with a wire aerial and a battery depends on nothing between themselves and the person they are talking to. The trade-off is capacity. The system carries voice and short text and nothing else, it requires an operator at each end, and it cannot be used by the public. Emergency planners are clear that it is not a replacement for anything; it is what remains when the rest has gone, and its value is measured in the first hours rather than the first week. The community has an obvious problem, which its own surveys describe frankly. The average licensed operator in Britain is over sixty. Recruitment has been attempted through the usual channels for thirty years with little effect, and the parts of the hobby that once attracted teenagers, principally building equipment and talking to strangers far away, are now available more easily by other means. What has worked, in a small way, is emergency exercise itself. Two counties now run annual exercises in which schools take part, operating under supervision, and the licensing body reports that the number of candidates under eighteen has risen for four consecutive years from a very low base. The retired teacher in the shed, asked whether the hobby has a future, said that this was the wrong question, and that the right one is whether the county can find somebody with a radio in 2045.",
    questions: [
      { q: "Who co-ordinated the response for the first thirty hours?", options: ["a retired teacher with a radio set","the county emergency planning team","a mobile network engineer","a group of volunteers at the town hall"], answer: 0, explanation: "'a retired teacher sitting in a garden shed with a radio set and a car battery'" },
      { q: "Why do mobile networks fail in such events?", options: ["too many people try to use them","masts depend on power and a connection","the equipment is damaged by wind","operators shut them down for safety"], answer: 1, explanation: "'a mobile network depends on masts, which depend on mains power and on a backhaul connection'" },
      { q: "What is the main limitation of amateur radio?", options: ["it works only over short distances","it is unreliable in bad weather","it carries little and needs an operator at each end","it is expensive to set up"], answer: 2, explanation: "'The system carries voice and short text and nothing else, it requires an operator at each end'" },
      { q: "How do emergency planners describe its value?", options: ["as the most reliable system available","as useful mainly in rural areas","as a replacement for mobile networks","as what remains when everything else has gone"], answer: 3, explanation: "'it is what remains when the rest has gone'" },
      { q: "Why has recruitment become harder?", options: ["what once attracted young people is now easier elsewhere","licences are more difficult to obtain","equipment costs have risen sharply","the hobby has a poor public image"], answer: 0, explanation: "'are now available more easily by other means'" },
      { q: "What has had some success?", options: ["advertising in local newspapers","school participation in emergency exercises","reducing the cost of a licence","shorter training courses"], answer: 1, explanation: "'Two counties now run annual exercises in which schools take part'" }
    ]
  },
  {
    id: "fce-rmc16-06",
    title: "The Kitchen Inside the Prison",
    text: "The training kitchen at one category C prison produces about four hundred meals a day for the wing and puts twelve men at a time through a recognised catering qualification. Its manager, Dele Osagie, is a chef by trade and has been running it for seven years, and he is unusually careful with claims about what it achieves. The figures that get quoted about such schemes, he says, are almost always misleading in the same direction. Men who complete a qualification in prison do reoffend less than men who do not. They are also, by definition, men who applied for a place, waited for one, and stayed out of trouble long enough to keep it, which is a group you would expect to do better anyway. The honest position is that the effect is real but smaller than the headline, and that anybody who tells you otherwise is raising money. What the kitchen does undeniably provide is a working day with a start time, a supervisor who will tell you when the work is not good enough, and a certificate that means the same thing outside as inside. Osagie regards the third of these as the most important and the most fragile. The qualification is nationally recognised and does not state where it was obtained, but a gap of four years on a curriculum vitae states something, and roughly half of his leavers are not asked about it and half are. He spends part of every week on the outside, talking to restaurant owners, and describes this as the actual job. Nine local employers now take his leavers regularly. He is under no illusion about why: two of the nine had a relative in prison, one employs a former leaver who has been with him since 2019, and the rest were persuaded slowly by a man who kept turning up. He says the scheme is not scalable, in the sense that it consists almost entirely of relationships that somebody has to maintain in person.",
    questions: [
      { q: "Why are the usual figures misleading?", options: ["reoffending is recorded inconsistently","the schemes are compared with nothing","participants would probably do better anyway","the numbers are too small to be reliable"], answer: 2, explanation: "'a group you would expect to do better anyway'" },
      { q: "What does Osagie say the kitchen definitely provides?", options: ["a higher income while in prison","contact with families outside","a guaranteed job on release","a structured working day and a real qualification"], answer: 3, explanation: "'a working day with a start time, a supervisor… and a certificate that means the same thing outside as inside'" },
      { q: "Which part does he consider most fragile?", options: ["the value of the qualification outside","the quality of the meals produced","the supervision of the men","the funding for the kitchen"], answer: 0, explanation: "He regards 'the third of these as the most important and the most fragile'." },
      { q: "What problem do leavers face despite the certificate?", options: ["few kitchens are hiring locally","a gap in their record raises questions","the qualification expires quickly","employers cannot verify it"], answer: 1, explanation: "'a gap of four years on a curriculum vitae states something'" },
      { q: "How does he describe his real job?", options: ["managing the prison's food budget","writing reports on each leaver","talking to employers outside the prison","training the men in the kitchen"], answer: 2, explanation: "'He spends part of every week on the outside, talking to restaurant owners, and describes this as the actual job.'" },
      { q: "Why does he say the scheme cannot be scaled up?", options: ["funding is agreed only year by year","few prisons have suitable premises","the kitchen is already at capacity","it depends on relationships maintained in person"], answer: 3, explanation: "'it consists almost entirely of relationships that somebody has to maintain in person'" }
    ]
  },
  {
    id: "fce-rmc16-07",
    title: "The Cargo Bike Depot",
    text: "A small warehouse three streets from the centre of Bristol receives lorries in the early morning and sends out bicycles for the rest of the day. Parcels arrive in bulk, are sorted onto trailers, and are delivered within a radius of about three kilometres by riders on electric cargo bikes, each of which carries up to a hundred and eighty kilograms. The arrangement is now common enough in European cities to have a standard economic argument attached to it, and the argument is not primarily about emissions. It is about the last mile, which in a dense city centre is the expensive one. A van entering the centre spends most of its time not moving. It queues, it circles for a place to stop, it parks illegally and collects fines that the operator budgets for, and the driver walks a considerable distance from wherever the van finally stopped. The bike does not solve this by being faster in a straight line, because it is not. It solves it by stopping directly outside, by using routes closed to vehicles, and by not needing to be parked. Where the model breaks down is at the edges. Beyond about four kilometres the economics reverse and a van wins comfortably. Heavy single items cannot be carried at all. Rain reduces rider productivity by a measurable amount and rider retention by more, and the depot's manager says staff turnover is the number that determines whether a site succeeds, not the number of parcels. Her own site pays above the market rate for riders, provides proper waterproofs and treats the job as skilled, which she describes as an expensive discovery rather than a philosophy: the first year was run on the assumption that riding a bicycle is something anybody can do, and it cost more in recruitment than the pay rise has since.",
    questions: [
      { q: "How does the depot operate?", options: ["lorries deliver and bicycles distribute","bicycles collect from customers and return","vans and bicycles share each route","parcels are sorted at the roadside"], answer: 0, explanation: "'receives lorries in the early morning and sends out bicycles for the rest of the day'" },
      { q: "What is the main argument for the model?", options: ["it reduces emissions in the city centre","the last mile is the expensive part","bicycles are cheaper to buy than vans","customers prefer bicycle delivery"], answer: 1, explanation: "'It is about the last mile, which in a dense city centre is the expensive one.'" },
      { q: "Why is a van costly in the centre?", options: ["it must be loaded twice","parking fines are unpredictable","it spends most of its time not moving","fuel prices are higher there"], answer: 2, explanation: "'A van entering the centre spends most of its time not moving.'" },
      { q: "How does the bike win?", options: ["it travels faster between stops","it carries more than a van","it can work through the night","it stops outside and needs no parking"], answer: 3, explanation: "'It solves it by stopping directly outside, by using routes closed to vehicles, and by not needing to be parked.'" },
      { q: "Where does the model fail?", options: ["over longer distances and with heavy items","where parcels are very small","in cities without cycle lanes","in areas with narrow streets"], answer: 0, explanation: "'Beyond about four kilometres the economics reverse'" },
      { q: "What determines whether a depot succeeds?", options: ["the distance from the city centre","how many riders stay in the job","the size of the warehouse","the number of parcels handled"], answer: 1, explanation: "'staff turnover is the number that determines whether a site succeeds'" }
    ]
  },
  {
    id: "fce-rmc16-08",
    title: "The Archive of Ordinary Paper",
    text: "A room above a former shop in Hull holds around ninety thousand items that nobody was ever meant to keep: bus timetables, till receipts, football programmes, price lists, the printed card that used to come inside a packet of tea. The collection was begun in 1974 by a postal worker named Alan Fothergill, who noticed that the local studies library held newspapers, minutes and photographs but nothing that told you what a loaf of bread cost in the week his daughter was born. He collected for thirty-eight years, and the archive that bears his name is now used by social historians, television production companies and, increasingly, by people researching their own families. The reason such material is valuable is that it was not written to be read later. A newspaper report of a strike is an account composed for an audience; a wage slip from the same factory in the same month is evidence that nobody arranged. Ephemera also records what the official record ignores, which tends to be the everyday: how much a haircut cost, which shops opened on a Sunday, what the bus fare was for a child and at what age a child stopped being one. The archive's cataloguer, Su-Lin Cheong, says her main difficulty is that the collection is arranged by Fothergill's own logic, which is neither alphabetical nor chronological and which he never wrote down. She has spent four years reconstructing it and now believes it is organised by where he obtained things, which is useless for retrieval and fascinating as a record of one man's routes around a city over four decades. She has decided not to reorganise it. Her argument is that a catalogue can be built on top of any arrangement, that the arrangement is itself a document, and that the day somebody sorts the boxes alphabetically is the day the last piece of information about Alan Fothergill is thrown away.",
    questions: [
      { q: "What kind of material does the archive hold?", options: ["photographs of the city","personal letters and diaries","items never intended to be kept","official records from local government"], answer: 2, explanation: "'around ninety thousand items that nobody was ever meant to keep'" },
      { q: "Why did Fothergill start collecting?", options: ["he had inherited a similar collection","he was asked to by the local library","he wanted to sell the items later","the library had nothing about everyday costs"], answer: 3, explanation: "'nothing that told you what a loaf of bread cost in the week his daughter was born'" },
      { q: "Why is such material valuable to historians?", options: ["it was not composed for an audience","it is easier to date accurately","it was produced in large quantities","it is rarer than newspapers"], answer: 0, explanation: "'a wage slip from the same factory in the same month is evidence that nobody arranged'" },
      { q: "What does ephemera record particularly well?", options: ["changes in local industry","everyday details the official record ignores","political events of the period","the opinions of ordinary people"], answer: 1, explanation: "'Ephemera also records what the official record ignores, which tends to be the everyday'" },
      { q: "What has Cheong concluded about the arrangement?", options: ["it was changed after his death","it is broadly chronological","it reflects where Fothergill obtained things","it follows no system at all"], answer: 2, explanation: "'it is organised by where he obtained things'" },
      { q: "Why has she decided to leave it as it is?", options: ["the owners will not permit changes","a new catalogue would be inaccurate","reorganising it would take too long","the arrangement is itself a record"], answer: 3, explanation: "'the arrangement is itself a document'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
