/* FCE Prep bank: reading multiple-choice (wave 7) */
(function () {
var BANK = [
  {
    id: "fce-rmc7-01",
    title: "The Orchard Nobody Owned",
    text: "Behind the row of garages at the end of Turner Street there are nineteen apple trees. Nobody planted them for us; they are what remains of a farm that was swallowed by the town in the 1950s, and for decades the fruit simply fell, rotted and fed the wasps. My neighbour Iris, who is seventy-nine and has lived on the street longer than anyone, once told me she used to send her children over the wall with a bucket. Then somebody put up a fence, and the trees became invisible in the way that things do when they belong to no one in particular. What changed was a phone call. A friend of mine works for the council and, out of curiosity, looked up who owned the land. The answer was nobody obvious: the plot had passed to the local authority when the farm was broken up, and it appeared on their records as 'amenity land, unmanaged'. That phrase turned out to be an invitation. Within three months we had a licence, a mowing rota and, to my surprise, forty-one people on a message group. Our first harvest was a lesson in humility. We picked nine hundred kilos of apples, which sounds magnificent until you try to store them. Apples bruise, bruised apples rot, and rot spreads through a crate in days. We gave away what we could, and we still threw a third of it into the compost. The following year we hired a mobile press for a Saturday, and the same quantity of fruit came out as three hundred and twenty litres of juice, which keeps for a year if you pasteurise it properly. Now the orchard has a small paid job attached to it: a school leaver spends six weeks each summer pruning and mapping the trees, and their wages come from the juice. Iris cannot climb ladders any more, but she sits under the oldest tree and tells the pickers, quite firmly, which branches her children were allowed to touch and which they were not.",
    questions: [
      { q: "Why had the apple trees been neglected for so long?", options: ["They produced fruit of poor quality.", "The council had banned access to the land.", "No one in particular was responsible for them.", "The trees were too old to be worth picking."], answer: 2, explanation: "The trees 'became invisible in the way that things do when they belong to no one in particular'." },
      { q: "What did the writer's friend discover?", options: ["The land was recorded as unmanaged amenity land.", "The farm had never legally been sold.", "The land was scheduled for building.", "Iris's family still owned the plot."], answer: 0, explanation: "The plot 'appeared on their records as \"amenity land, unmanaged\"'." },
      { q: "What does the writer mean by calling the first harvest 'a lesson in humility'?", options: ["Fewer apples were picked than expected.", "Volunteers argued about how to share the fruit.", "The group discovered they could not store what they picked.", "The trees were damaged by inexperienced pickers."], answer: 2, explanation: "Nine hundred kilos 'sounds magnificent until you try to store them'; a third was lost to bruising and rot." },
      { q: "What advantage did pressing the apples bring?", options: ["It attracted more volunteers to the group.", "The product could be kept for a year.", "It removed the need for a mowing rota.", "It produced a larger harvest the next season."], answer: 1, explanation: "The juice 'keeps for a year if you pasteurise it properly', unlike the fruit itself." },
      { q: "How is the summer worker paid?", options: ["By the local authority.", "Through donations from the message group.", "From the sale of the juice.", "The post is unpaid work experience."], answer: 2, explanation: "'A school leaver spends six weeks each summer pruning and mapping the trees, and their wages come from the juice.'" },
      { q: "What impression does the writer give of Iris at the end?", options: ["She resents the newcomers running the orchard.", "She is disappointed by how the trees have been pruned.", "She has lost interest since she can no longer pick fruit.", "She remains an authority on the orchard's history."], answer: 3, explanation: "She tells the pickers 'quite firmly' which branches her children were allowed to touch — a figure of authority about the place." }
    ]
  },
  {
    id: "fce-rmc7-02",
    title: "Working in the Costume Store",
    text: "The costume store of a repertory theatre is not a glamorous place. Ours occupies the top two floors of a building behind the loading bay, it smells faintly of dust and old wool, and in August it is forty degrees under the roof. I spent a year there between school and university, and I have never had a job that taught me more about how the pieces of a production fit together. The store holds roughly eleven thousand items, arranged not by colour or by play but by period and by size, which is the only system that works when a director phones at four o'clock wanting six Edwardian waistcoats by Thursday. My first task each morning was returns: unpacking whatever had come back from the previous night, checking it against the list, and separating what could go straight back on the rail from what needed cleaning or repair. The temptation is to hang everything up quickly and deal with the damage later. Sofia, who ran the store and had done so for twenty-two years, cured me of that in a week. A costume returned with a torn seam and hung in the wrong place, she said, is not one problem; it is three, and the third one happens ten minutes before a performance eight months from now. What I had not understood before was how much of theatre is memory. Sofia could stand in front of a rail and tell you that a particular coat had been a soldier in 1998, a butler in 2004 and a ghost in 2011, and that the ghost had required the lining to be replaced. Almost none of this was written down. When she retired in the spring, we spent six weeks photographing and cataloguing before she left, and even then we all knew we were capturing perhaps a tenth of what she carried in her head. My last job for her was to sew a label into the ghost's coat, listing its three lives. It is still the only garment in eleven thousand that has its own history attached to it.",
    questions: [
      { q: "How are the costumes organised in the store?", options: ["By period and size.", "By colour and fabric.", "By the production they were made for.", "By how often they are used."], answer: 0, explanation: "They are arranged 'not by colour or by play but by period and by size'." },
      { q: "Why is that system used?", options: ["It saves the most space under the roof.", "It allows urgent, specific requests to be met quickly.", "It is the traditional method in repertory theatre.", "It makes cleaning and repair easier to track."], answer: 1, explanation: "It 'is the only system that works when a director phones at four o'clock wanting six Edwardian waistcoats by Thursday'." },
      { q: "What point was Sofia making about a damaged costume put back on the rail?", options: ["It will be too expensive to repair later.", "It sets a bad example to new staff.", "It will cause a crisis long afterwards.", "It may damage the garments beside it."], answer: 2, explanation: "'It is three [problems], and the third one happens ten minutes before a performance eight months from now.'" },
      { q: "What does the writer find remarkable about Sofia's knowledge?", options: ["She had memorised the entire catalogue system.", "She could date any garment by its fabric.", "She had personally repaired most of the items.", "She held the store's history in her head, unwritten."], answer: 3, explanation: "She could recount a coat's three roles, yet 'almost none of this was written down'." },
      { q: "What does the writer suggest about the cataloguing project?", options: ["It captured only a fraction of Sofia's knowledge.", "It was finished just in time for her retirement.", "It proved that the old records were inaccurate.", "It was resisted by the rest of the staff."], answer: 0, explanation: "'We all knew we were capturing perhaps a tenth of what she carried in her head.'" },
      { q: "Why does the writer mention the label sewn into the ghost's coat?", options: ["To show how carefully costumes are repaired.", "To explain why that coat is no longer used.", "To highlight how rarely a garment's story is recorded.", "To illustrate the writer's new sewing skills."], answer: 2, explanation: "It is 'the only garment in eleven thousand that has its own history attached to it'." }
    ]
  },
  {
    id: "fce-rmc7-03",
    title: "Learning to Read the Tides",
    text: "The causeway to Saint Ninian's Isle is covered twice a day, and every summer somebody has to be rescued from it. This is not, as visitors assume, because the sea arrives suddenly. It arrives at a speed you could easily walk away from. The danger is subtler: the water covers the low middle section of the causeway long before it reaches the ends, so a walker who sets out on dry stone can turn round twenty minutes later to find a channel of moving water between themselves and the shore they came from. I learned this on my second week as a volunteer with the coastal ranger service, from a woman called Marta who had been reading these tides for thirty years. Her first lesson was that the printed tide table is a beginning, not an answer. The table tells you when high water occurs at the harbour, which is two miles away and around a headland; on our causeway the same tide arrives about thirty-five minutes earlier. Add a strong southerly wind and it can arrive earlier still, and higher than the table predicts. Marta's second lesson concerned the human element. In three decades of incidents, she said, almost none involved people who had no information. They involved people who had information and then made an exception for themselves: they had checked the table, seen the risk, and decided that this once, because the light was beautiful or because the crossing had been fine yesterday, it would be all right. Our rescue records bear her out. The most common profile is not the ignorant tourist but the confident returner. So we stopped printing more warnings, which nobody reads, and installed a simple board at the entrance with two figures chalked on each morning: SAFE UNTIL, and beneath it, in larger numerals, MINUTES REMAINING, updated by whoever passes. Incidents fell by two thirds in the first season. It turns out that people who ignore an abstract risk will often respect a number that is counting down.",
    questions: [
      { q: "Why is the causeway more dangerous than visitors expect?", options: ["The tide rises faster than a person can walk.", "The middle section floods before the ends do.", "The stone becomes slippery when wet.", "Fog often descends without warning."], answer: 1, explanation: "'The water covers the low middle section of the causeway long before it reaches the ends', cutting walkers off." },
      { q: "What does Marta say about the printed tide table?", options: ["It is unreliable and should be ignored.", "It is accurate only in calm weather.", "It gives times for a different location.", "It is too complicated for most visitors."], answer: 2, explanation: "It gives high water at the harbour, 'two miles away and around a headland'; the causeway tide arrives about 35 minutes earlier." },
      { q: "What effect can a strong southerly wind have?", options: ["It delays the tide by around half an hour.", "It makes the water calmer but deeper.", "It has little effect on this stretch of coast.", "It brings the tide in earlier and higher."], answer: 3, explanation: "'Add a strong southerly wind and it can arrive earlier still, and higher than the table predicts.'" },
      { q: "According to Marta, what causes most incidents?", options: ["People who know the risk but exempt themselves from it.", "Visitors who have never seen a tide table.", "Groups who walk too slowly to return in time.", "Tourists misled by out-of-date information."], answer: 0, explanation: "They 'had information and then made an exception for themselves' — the 'confident returner'." },
      { q: "Why did the rangers stop producing more warning notices?", options: ["The notices were too expensive to replace.", "Warnings go unread, so they had little effect.", "The landowner objected to the signs.", "Visitors complained that they spoiled the view."], answer: 1, explanation: "They 'stopped printing more warnings, which nobody reads'." },
      { q: "What does the writer conclude about the chalked board?", options: ["It works because volunteers update it every hour.", "Its success is likely to be temporary.", "A countdown is more persuasive than an abstract warning.", "It should be replaced by an electronic display."], answer: 2, explanation: "'People who ignore an abstract risk will often respect a number that is counting down.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
