/* KET Prep extra bank: listening week 4 */
(function () {
var BANK = [
  { id: "k-lis4-01", title: "Announcement: School Library News", kind: "monologue",
    script: "Good morning, students. This is Mrs Okafor, the school librarian, with some news about the library. Please listen, because there are three important changes. First, from this week the library is open at lunchtime every day, from twelve thirty to one fifteen. You can come to read, do homework, or play chess, but please eat your lunch in the dining hall first, because food is not allowed near the books. Second, we have two hundred new books! There are new adventure stories, books about space, and funny comic books in the corner by the window. You can now borrow four books at one time, not two like before, and you can keep them for three weeks. Please remember to bring back your old books first. If your book is late, you cannot borrow new ones until you return it. Third, some exciting news: we are starting a reading club on Thursday afternoons after school, from three thirty to four fifteen. Each month we will all read the same book and then talk about it together, with juice and biscuits. The first meeting is this Thursday, and the first book is free for every member. If you want to join, come and see me at the library desk before Wednesday. Thank you, and happy reading!",
    questions: [
      { q: "When is the library now open at lunchtime?", options: ["From twelve thirty to one fifteen.", "From twelve to one.", "From one to two.", "Only on Thursdays."], answer: 0, explanation: "Mrs Okafor says the library is open at lunchtime 'from twelve thirty to one fifteen' every day." },
      { q: "Why must students eat lunch in the dining hall first?", options: ["The library is too small.", "Food is not allowed near the books.", "The dining hall closes early.", "Teachers eat in the library."], answer: 1, explanation: "She says to eat first 'because food is not allowed near the books'." },
      { q: "How many books can students borrow now?", options: ["Two.", "Three.", "Four.", "Two hundred."], answer: 2, explanation: "She says 'You can now borrow four books at one time, not two like before'." },
      { q: "What happens if a student's book is late?", options: ["They pay some money.", "They cannot borrow new books.", "They must join the reading club.", "They lose their library card."], answer: 1, explanation: "She says if a book is late 'you cannot borrow new ones until you return it'." },
      { q: "What should students do to join the reading club?", options: ["Come to the club on Friday.", "Ask their class teacher.", "Buy the first book.", "See Mrs Okafor before Wednesday."], answer: 3, explanation: "She says 'come and see me at the library desk before Wednesday' to join." }
    ] },
  { id: "k-lis4-02", title: "Phone Message: A Party Invitation", kind: "monologue",
    script: "Hi Katie, it's Daniel. I'm calling to invite you to my birthday party! I'm going to be thirteen, and I'm having a party on Saturday the fourteenth. I hope you can come, because you are one of my best friends. So, here is the plan. The party is not at my house this year. My mum booked the bowling place in Bridge Street, the new one next to the cinema. We meet there at two o'clock in the afternoon. We will bowl for two hours, and then we will have food, burgers and chips, and my birthday cake, of course. My mum is making it. It's going to be a football cake, because you know I love football. The party finishes at six, and my dad can drive you home after, so tell your parents they only need to bring you. Oh, and important: wear socks! You cannot bowl without socks, they told us. You don't need to bring anything else, just yourself. Please don't buy me a big present, honestly. A small thing or just a card is fine. Can you send me a message tonight or tomorrow to say yes or no? I hope you can come! OK, see you soon, bye!",
    questions: [
      { q: "Why is Daniel calling Katie?", options: ["To invite her to his party.", "To ask about homework.", "To talk about football.", "To say thank you for a present."], answer: 0, explanation: "Daniel says 'I'm calling to invite you to my birthday party!'" },
      { q: "Where is the party?", options: ["At Daniel's house.", "At the bowling place in Bridge Street.", "At the cinema.", "At a burger restaurant."], answer: 1, explanation: "He says his mum 'booked the bowling place in Bridge Street, the new one next to the cinema'." },
      { q: "What kind of cake will there be?", options: ["A chocolate cake.", "A bowling cake.", "A football cake.", "A fruit cake."], answer: 2, explanation: "Daniel says 'It's going to be a football cake, because you know I love football'." },
      { q: "How will Katie get home after the party?", options: ["Her parents will collect her.", "She will walk home.", "She will take a bus.", "Daniel's dad will drive her."], answer: 3, explanation: "Daniel says 'my dad can drive you home after' so her parents only bring her." },
      { q: "What must Katie wear at the party?", options: ["Socks.", "A football shirt.", "A party dress.", "Special shoes from home."], answer: 0, explanation: "Daniel says 'wear socks! You cannot bowl without socks'." }
    ] },
  { id: "k-lis4-03", title: "Radio Chat: Tom's Fishing Weekends", kind: "dialogue",
    script: "Presenter: Welcome back! Our guest now is Tom, who is thirteen and loves a hobby that many people think is only for older people: fishing. Tom, hello!\nTom: Hello! Yes, people always laugh when I tell them, but fishing is great.\nPresenter: How did you start?\nTom: My uncle took me two years ago. He goes fishing at the lake every weekend, and one Saturday my parents were working, so I went with him. I caught nothing that day, but I loved it.\nPresenter: You caught nothing, and you loved it? Why?\nTom: Because it is so quiet and calm. The lake in the early morning is beautiful. You hear the birds, you see the water, and you wait. No phone, no noise, no hurry. My uncle says it is like a holiday for your head, and he is right.\nPresenter: When did you catch your first fish?\nTom: On my third trip. It was very small, and we put it back in the water. We always put the fish back. For us it's not about eating them.\nPresenter: How often do you go now?\nTom: Most Sundays, from six in the morning until about eleven. In winter we go less, maybe once a month, because it's so cold.\nPresenter: And what do you need for this hobby?\nTom: Not much. My uncle gave me his old fishing things, so I only buy little things sometimes. It's a cheap hobby, really. And my mum makes us sandwiches, that's the most important part!",
    questions: [
      { q: "How did Tom start fishing?", options: ["His school had a fishing club.", "His uncle took him one Saturday.", "He watched it on television.", "His parents taught him."], answer: 1, explanation: "Tom says 'My uncle took me two years ago' when his parents were working." },
      { q: "Why does Tom love fishing?", options: ["It is quiet and calm.", "He catches big fish.", "He likes eating fish.", "He can use his phone there."], answer: 0, explanation: "Tom says 'it is so quiet and calm... No phone, no noise, no hurry.'" },
      { q: "What do Tom and his uncle do with the fish they catch?", options: ["They cook them at home.", "They give them to friends.", "They put them back in the water.", "They sell them at the market."], answer: 2, explanation: "Tom says 'We always put the fish back. For us it's not about eating them.'" },
      { q: "How often does Tom go fishing in winter?", options: ["Every Sunday.", "About once a month.", "Twice a week.", "Never in winter."], answer: 1, explanation: "Tom says in winter they go 'maybe once a month, because it's so cold'." },
      { q: "Why is fishing a cheap hobby for Tom?", options: ["The lake tickets are free.", "He shares things with friends.", "His mum pays for everything.", "His uncle gave him his old fishing things."], answer: 3, explanation: "Tom says 'My uncle gave me his old fishing things, so I only buy little things sometimes'." }
    ] },
  { id: "k-lis4-04", title: "Conversation: At the Fruit Market", kind: "dialogue",
    script: "Seller: Good morning, young man! Lovely fresh fruit today. What would you like?\nHugo: Good morning. My mum sent me with a list. First, she wants a kilo of apples.\nSeller: Red or green? The green ones are a bit cheaper this week, one pound sixty the kilo. The red ones are two pounds.\nHugo: The list just says apples... I'll take the red ones. My little brother only eats the red ones. He says green apples are for dinosaurs.\nSeller: Ha ha! Smart boy. What else?\nHugo: Six bananas, please, but not too yellow. Mum says they should be a little green, then they are good for the whole week.\nSeller: Very wise, your mum. Here you are, six bananas, one pound twenty. Next?\nHugo: Strawberries. Are they good today?\nSeller: They are wonderful, from my own farm, picked this morning. Two pounds fifty a box. Try one!\nHugo: Mmm, so sweet! I'll take two boxes then. Mum wants to make a strawberry cake for my grandpa. He is coming for dinner on Sunday.\nSeller: Lovely! So that's the apples, the bananas, and two boxes of strawberries. Nine pounds twenty all together, please.\nHugo: Oh no. Mum only gave me nine pounds.\nSeller: Don't worry. For a good customer like you, nine pounds is fine. And here, one orange, free, for the little dinosaur brother.\nHugo: Thank you so much! See you next Saturday!",
    questions: [
      { q: "Why does Hugo take the red apples?", options: ["They are cheaper.", "His brother only eats red ones.", "They are on the list.", "The green ones are old."], answer: 1, explanation: "Hugo says 'My little brother only eats the red ones' even though green is cheaper." },
      { q: "Why should the bananas be a little green?", options: ["Green ones taste sweeter.", "His mum likes the colour.", "Then they are good all week.", "They cost less money."], answer: 2, explanation: "Hugo says his mum wants them a little green so 'they are good for the whole week'." },
      { q: "What does the seller say about the strawberries?", options: ["They were picked this morning.", "They come from Spain.", "They are the last box.", "They are half price today."], answer: 0, explanation: "The seller says they are 'from my own farm, picked this morning'." },
      { q: "Why does Hugo's mum want strawberries?", options: ["To eat them at breakfast.", "To sell them at school.", "To give them to a neighbour.", "To make a cake for Hugo's grandpa."], answer: 3, explanation: "Hugo says 'Mum wants to make a strawberry cake for my grandpa' who comes on Sunday." },
      { q: "What problem does Hugo have at the end?", options: ["He does not have enough money.", "He forgot the shopping list.", "He dropped the strawberries.", "The market is closing."], answer: 0, explanation: "The total is nine pounds twenty, but Hugo says 'Mum only gave me nine pounds'." }
    ] },
  { id: "k-lis4-05", title: "Podcast: My First Camping Trip", kind: "monologue",
    script: "Hello, listeners! It's Ava here, and today I want to tell you about my first camping trip, which was last month. My dad loves camping, and he always talks about the trips he did when he was young. So, for his birthday, my mum said, let's all go camping in the mountains. I was not happy at first, if I'm honest. No shower? No wifi? Sleeping on the ground? No, thank you. But my parents said it was only for two nights, so I packed my bag and went. And do you know what? It was one of the best weekends of my life. We walked for three hours to a small green place next to a river. Putting up the tent was funny, because my dad said he remembered how to do it, but he didn't, and it fell down twice. In the evening we made a small fire and cooked sausages, and my mum told scary stories. I slept really well, which was a big surprise. The best moment was the second morning. I woke up early and opened the tent, and there were two deer drinking at the river, very close to us. I didn't move for ten minutes. I just watched them. No photo, no phone, just me and the deer. Now I understand my dad. We are going again in August, and this time, I can't wait.",
    questions: [
      { q: "Why did the family go camping?", options: ["For the dad's birthday.", "For a school project.", "Because hotels were expensive.", "For the mum's holiday."], answer: 0, explanation: "For the dad's birthday, the mum said 'let's all go camping in the mountains'." },
      { q: "How did Ava feel about the trip at first?", options: ["She was very excited.", "She was not happy.", "She was afraid of animals.", "She wanted a longer trip."], answer: 1, explanation: "Ava says 'I was not happy at first' - no shower, no wifi, sleeping on the ground." },
      { q: "What was funny about putting up the tent?", options: ["It was much too small.", "The wind took it away.", "It fell down twice.", "They forgot the tent at home."], answer: 2, explanation: "Her dad said he remembered how to do it, 'but he didn't, and it fell down twice'." },
      { q: "What was the best moment of the trip for Ava?", options: ["Cooking sausages on the fire.", "Her mum's scary stories.", "The three-hour walk.", "Watching two deer at the river."], answer: 3, explanation: "She says the best moment was seeing 'two deer drinking at the river, very close to us'." },
      { q: "How does Ava feel about camping now?", options: ["She can't wait to go again.", "She still prefers hotels.", "She will only go with friends.", "She thinks two nights is too long."], answer: 0, explanation: "She says 'We are going again in August, and this time, I can't wait.'" }
    ] },
  { id: "k-lis4-06", title: "Radio Chat: Sara Talks About Dancing", kind: "dialogue",
    script: "Host: You are listening to Afternoon Radio, and with me now is Sara, who dances in a group that won a big prize last week. Congratulations, Sara!\nSara: Thank you! We are all still so happy about it.\nHost: Tell us about your group.\nSara: We are called the Red Shoes, and there are eight of us, six girls and two boys. We are all between eleven and fourteen years old, and we practise in the hall behind the market.\nHost: How often do you practise?\nSara: Twice a week normally, on Monday and Friday evenings. But before the competition, we practised every day for two weeks. My legs hurt so much!\nHost: I can believe that! And what kind of dancing do you do?\nSara: Street dance, mostly. It's fast and fun. Our teacher, Miss Joy, makes all our dances. She was a dancer in music videos when she was younger, in London.\nHost: Wow! Now, tell us about the competition.\nSara: It was in the big theatre in town. Fifteen groups danced, some from very far away. When they said our name for first prize, I cried. My mum cried more!\nHost: What did you win?\nSara: A silver cup, and free dance classes for a year. But the best thing is different: a dance school in London saw us, and they invited our group to dance in a show there this summer.\nHost: That's fantastic, Sara. Good luck in London!",
    questions: [
      { q: "How many dancers are in the Red Shoes?", options: ["Six.", "Eight.", "Eleven.", "Fifteen."], answer: 1, explanation: "Sara says 'there are eight of us, six girls and two boys'." },
      { q: "How often did they practise before the competition?", options: ["Twice a week.", "On Fridays only.", "Every day for two weeks.", "Once a month."], answer: 2, explanation: "Sara says 'before the competition, we practised every day for two weeks'." },
      { q: "What did Miss Joy do when she was younger?", options: ["She danced in music videos.", "She taught at a school.", "She sang in a group.", "She worked in a theatre."], answer: 0, explanation: "Sara says Miss Joy 'was a dancer in music videos when she was younger, in London'." },
      { q: "Where was the competition?", options: ["In London.", "In the hall behind the market.", "At Sara's school.", "In the big theatre in town."], answer: 3, explanation: "Sara says 'It was in the big theatre in town' with fifteen groups." },
      { q: "What is the best thing about winning, for Sara?", options: ["The silver cup.", "An invitation to dance in London.", "Free classes for a year.", "Her photo in the newspaper."], answer: 1, explanation: "She says 'the best thing is different' - a London dance school invited them to a show." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
