/* KET Prep extra bank: listening week 2 */
(function () {
var BANK = [
  { id: "k-lis2-01", title: "Announcement: The School Trip to the Zoo", kind: "monologue",
    script: "Hello, Class 6. This is Miss Porter with information about our trip to the city zoo on Wednesday. Please listen and tell your parents tonight. The bus will leave from the school car park at eight forty-five in the morning, so please arrive at school at eight thirty, fifteen minutes earlier than normal. Do not be late, because the bus cannot wait. The trip costs seven pounds. Please bring the money in an envelope with your name on it and give it to me on Monday or Tuesday. At the zoo, we will first visit the elephants and the lions in the morning. Then, at twelve o'clock, we will have lunch at the picnic area near the lake. The zoo café is very expensive, so please bring a packed lunch and a drink from home. In the afternoon, there is a special show about birds, and a zoo worker will talk to us about how they look after the baby penguins. That is my favourite part! You do not need to wear school uniform, but please wear comfortable shoes because we will walk a lot. We will be back at school at four o'clock. Any questions? Come and ask me at break time.",
    questions: [
      { q: "What time should students arrive at school on Wednesday?", options: ["At eight forty-five.", "At eight thirty.", "At nine o'clock.", "At eight fifteen."], answer: 1, explanation: "Miss Porter says 'please arrive at school at eight thirty' because the bus leaves at eight forty-five." },
      { q: "How should students bring the money?", options: ["In an envelope with their name.", "In their school bag.", "They pay at the zoo.", "Their parents pay online."], answer: 0, explanation: "She says 'bring the money in an envelope with your name on it'." },
      { q: "Why should students bring a packed lunch?", options: ["The zoo has no café.", "There is no time for lunch.", "The zoo café is very expensive.", "The picnic area is closed."], answer: 2, explanation: "She says 'The zoo café is very expensive, so please bring a packed lunch'." },
      { q: "What will happen in the afternoon?", options: ["They will visit the lions.", "They will swim in the lake.", "They will go home early.", "They will see a show about birds."], answer: 3, explanation: "In the afternoon 'there is a special show about birds' and a talk about baby penguins." },
      { q: "What should students wear?", options: ["School uniform.", "Comfortable shoes.", "A white shirt.", "Warm coats."], answer: 1, explanation: "Uniform is not needed, but she says 'wear comfortable shoes because we will walk a lot'." }
    ] },
  { id: "k-lis2-02", title: "Radio Chat: Lucy the Young Tennis Player", kind: "dialogue",
    script: "Host: Welcome back to Sport Time. Our next guest is Lucy Reed, who is twelve and plays tennis very well. Hello, Lucy!\nLucy: Hello! Thank you for asking me on your show.\nHost: When did you start playing tennis?\nLucy: When I was seven. My mum plays every Sunday, and one day she took me with her. I loved it from the first minute.\nHost: How often do you practise now?\nLucy: Four times a week. Tuesday and Thursday evenings after school, and Saturday and Sunday mornings. My coach is called Marco. He is from Italy and he is really funny, but he also works us very hard.\nHost: Do you ever get tired of it?\nLucy: Sometimes, in winter, when it is dark and cold and I want to stay at home and watch TV. But when I win a match, I forget all that.\nHost: What about school? Is it difficult to do both?\nLucy: A little. I do my homework on the bus and at lunchtime. My teachers help me a lot when I miss a lesson for a competition.\nHost: And what is your dream, Lucy?\nLucy: I want to play at the big competitions in other countries one day. But first, I want to win the schools cup next month. Our final is against a very strong girl from the north.\nHost: Well, good luck, Lucy. We will all watch you!",
    questions: [
      { q: "How did Lucy start playing tennis?", options: ["Her school had lessons.", "Her mum took her one day.", "Her coach found her.", "She watched it on TV."], answer: 1, explanation: "Lucy says her mum plays on Sundays and 'one day she took me with her'." },
      { q: "How often does Lucy practise?", options: ["Four times a week.", "Every day.", "Twice a week.", "Only at weekends."], answer: 0, explanation: "Lucy says she practises 'four times a week' - two evenings and two mornings." },
      { q: "What does Lucy say about her coach Marco?", options: ["He is from the north.", "He is her mum's friend.", "He is funny but works them hard.", "He teaches at her school."], answer: 2, explanation: "She says Marco 'is really funny, but he also works us very hard'." },
      { q: "When does Lucy sometimes get tired of tennis?", options: ["In winter.", "After school.", "At competitions.", "On Sunday mornings."], answer: 0, explanation: "She says 'Sometimes, in winter, when it is dark and cold' she wants to stay at home." },
      { q: "What does Lucy want to do first?", options: ["Play in other countries.", "Win the schools cup.", "Become a coach.", "Watch more TV."], answer: 1, explanation: "She says 'first, I want to win the schools cup next month'; other countries are her later dream." }
    ] },
  { id: "k-lis2-03", title: "Phone Message: Grandma's Visit", kind: "monologue",
    script: "Hi Tom, it's Grandma here. I hope you are well, dear. I'm calling about my visit this weekend. Your mum said I can stay in the small bedroom, which is lovely. Now, listen carefully, because I need your help with two things. First, my train arrives on Saturday at eleven twenty in the morning, not at ten like last time. Can you and your dad meet me at the station? I will have a big bag because I'm bringing presents and some of my apple cakes, and you know your dad loves those. Second, please tell your mum that I can't eat cheese now. The doctor says it's not good for me. So no cheese in the dinner, please, but everything else is fine. Oh, and I want to see your new school on Monday morning before I go home. Your mum says it has a beautiful garden where you grow vegetables. Can you show me? My train home leaves at three in the afternoon on Monday, so we have time for lunch together first. Right, that's everything. Oh, one more thing! Happy birthday for last Tuesday! Your present is in my big bag. I can't wait to see your face. Lots of love. Bye bye, dear.",
    questions: [
      { q: "What time does Grandma's train arrive on Saturday?", options: ["At ten o'clock.", "At eleven twenty.", "At three in the afternoon.", "At eleven o'clock."], answer: 1, explanation: "She says her train 'arrives on Saturday at eleven twenty in the morning, not at ten like last time'." },
      { q: "Why will Grandma have a big bag?", options: ["She is bringing presents and cakes.", "She is staying for a month.", "She is bringing vegetables.", "She bought new clothes."], answer: 0, explanation: "She says the bag is big 'because I'm bringing presents and some of my apple cakes'." },
      { q: "What can't Grandma eat now?", options: ["Apple cake.", "Vegetables.", "Cheese.", "Chicken."], answer: 2, explanation: "She says 'I can't eat cheese now' because the doctor says it's not good for her." },
      { q: "What does Grandma want to see on Monday?", options: ["Tom's new school.", "The doctor.", "The train station.", "A vegetable shop."], answer: 0, explanation: "She says 'I want to see your new school on Monday morning', especially the garden." },
      { q: "What is in Grandma's bag for Tom?", options: ["A school book.", "A birthday present.", "Some cheese.", "Train tickets."], answer: 1, explanation: "She says 'Happy birthday for last Tuesday! Your present is in my big bag.'" }
    ] },
  { id: "k-lis2-04", title: "Conversation: At the Bakery", kind: "dialogue",
    script: "Baker: Good morning! What can I get you today?\nSam: Good morning. I need some things for my mum's birthday breakfast. It's a surprise.\nBaker: How nice! Well, the croissants are fresh from the oven, still warm.\nSam: Great, I'll take four croissants, please. How much are they?\nBaker: They are one pound twenty each, so that's four pounds eighty.\nSam: OK. And do you have any of that chocolate cake? The one with the strawberries on top? My mum loves it.\nBaker: Ah, I'm sorry, the chocolate cake is only ready after twelve o'clock. But I have a lovely lemon cake, and this carrot cake here is very popular too.\nSam: Hmm, no chocolate... My mum doesn't really like lemon. I'll take the carrot cake then. Is it big enough for five people?\nBaker: Oh yes, easily. It's six pounds fifty. Would you like a birthday candle for it? They are free with every cake this month.\nSam: Yes, please! That's perfect. And six brown rolls as well, for my dad.\nBaker: Of course. So, four croissants, one carrot cake, and six rolls. That's thirteen pounds ten all together.\nSam: Here you are, fifteen pounds.\nBaker: And one pound ninety back. Have a lovely party, and happy birthday to your mum!\nSam: Thank you very much! Bye!",
    questions: [
      { q: "Why is Sam at the bakery?", options: ["To buy his lunch.", "To buy things for a birthday breakfast.", "To order a wedding cake.", "To meet his mum."], answer: 1, explanation: "Sam says he needs things 'for my mum's birthday breakfast. It's a surprise.'" },
      { q: "How many croissants does Sam buy?", options: ["Six.", "Five.", "Four.", "Two."], answer: 2, explanation: "Sam says 'I'll take four croissants, please', which costs four pounds eighty." },
      { q: "Why can't Sam buy the chocolate cake?", options: ["It is too expensive.", "It is only ready after twelve.", "It is too small.", "The baker sold the last one."], answer: 1, explanation: "The baker says 'the chocolate cake is only ready after twelve o'clock'." },
      { q: "Which cake does Sam buy?", options: ["The carrot cake.", "The lemon cake.", "The chocolate cake.", "The strawberry cake."], answer: 0, explanation: "Because his mum doesn't like lemon, Sam says 'I'll take the carrot cake then'." },
      { q: "What is free with every cake this month?", options: ["Six brown rolls.", "A croissant.", "A box.", "A birthday candle."], answer: 3, explanation: "The baker says candles 'are free with every cake this month'." }
    ] },
  { id: "k-lis2-05", title: "Podcast: My Little Garden", kind: "monologue",
    script: "Hello, friends! This is Marta, and this is my small podcast about my small garden. Last year, my family moved from a flat in the city to a house with a garden. The garden was not beautiful then. There was old grass, a broken chair and a lot of stones. My parents were busy with the house, so they said the garden could be my job. I was happy, but I knew nothing about plants! I watched videos, and my neighbour, Mr Evans, helped me a lot. He is seventy years old and knows everything about gardens. First, we cleaned everything and took away the stones. Then, in spring, I planted tomatoes, carrots and some flowers called sunflowers. The tomatoes were difficult. Birds ate the first ones, so Mr Evans gave me a net to put over them. The carrots were easy, and the sunflowers grew taller than my dad! He is one metre eighty, so that is very tall. Now, in summer, we eat my tomatoes in our salads, and my mum says they taste better than the ones from the supermarket. My next plan is strawberries. Mr Evans says they are easy, but I must plant them in a sunny corner. I will tell you everything next time. Bye for now!",
    questions: [
      { q: "Where did Marta's family live before?", options: ["In a house with a garden.", "In a flat in the city.", "In Mr Evans' house.", "In a village."], answer: 1, explanation: "Marta says her family 'moved from a flat in the city to a house with a garden'." },
      { q: "Why did the garden become Marta's job?", options: ["Her parents were busy with the house.", "She studied plants at school.", "Mr Evans asked her to do it.", "Her parents don't like gardens."], answer: 0, explanation: "She says 'My parents were busy with the house, so they said the garden could be my job'." },
      { q: "Who helped Marta with the garden?", options: ["Her dad.", "Her teacher.", "Her neighbour.", "Her mum."], answer: 2, explanation: "She says 'my neighbour, Mr Evans, helped me a lot' - he knows everything about gardens." },
      { q: "What problem did Marta have with the tomatoes?", options: ["They did not grow at all.", "Birds ate the first ones.", "They were too tall.", "They tasted bad."], answer: 1, explanation: "She says 'Birds ate the first ones, so Mr Evans gave me a net'." },
      { q: "What does Marta want to grow next?", options: ["Strawberries.", "Sunflowers.", "Carrots.", "Salad."], answer: 0, explanation: "She says 'My next plan is strawberries' in a sunny corner of the garden." }
    ] },
  { id: "k-lis2-06", title: "Radio Chat: A Boy and His Bicycle Club", kind: "dialogue",
    script: "Presenter: Good afternoon, listeners. Today we meet Oscar, who started a bicycle club at his school. Oscar, welcome!\nOscar: Thanks! It's nice to be here.\nPresenter: So, why did you start a bicycle club?\nOscar: Well, I ride my bike to school every day, about twenty minutes each way. Lots of my friends wanted to ride too, but their parents were worried because the roads are busy. I thought, if we ride together in a big group, it is safer.\nPresenter: Clever idea! How many students are in the club now?\nOscar: We started with five people in September. Now we are twenty-three! We meet at the supermarket car park at eight o'clock and ride to school together. A teacher, Mr Field, rides with us too.\nPresenter: Do you do anything else, or just ride to school?\nOscar: Oh, lots more! On the first Sunday of every month, we do a long ride in the countryside. Last month we rode to the old castle, thirty kilometres there and back. And once a term, a man from the bike shop comes and teaches us to repair our bikes. Last week I learned to fix a flat tyre.\nPresenter: Fantastic. And what do your parents think?\nOscar: They love it. My mum says I am always hungry now, but also always happy. And I am never late for school!\nPresenter: Wonderful. Thank you, Oscar!",
    questions: [
      { q: "Why did Oscar start the bicycle club?", options: ["To win a school prize.", "To make riding to school safer.", "Because the bus was expensive.", "Because he had no friends."], answer: 1, explanation: "Parents were worried about busy roads, so Oscar thought 'if we ride together in a big group, it is safer'." },
      { q: "How many students are in the club now?", options: ["Five.", "Twenty.", "Twenty-three.", "Thirty."], answer: 2, explanation: "Oscar says 'We started with five people in September. Now we are twenty-three!'" },
      { q: "Where does the club meet in the morning?", options: ["At the supermarket car park.", "At the school gate.", "At the bike shop.", "At the old castle."], answer: 0, explanation: "He says 'We meet at the supermarket car park at eight o'clock'." },
      { q: "What did Oscar learn last week?", options: ["To ride with no hands.", "To fix a flat tyre.", "To ride thirty kilometres.", "To teach younger students."], answer: 1, explanation: "A man from the bike shop teaches repairs, and Oscar says 'Last week I learned to fix a flat tyre'." },
      { q: "What does Oscar's mum say about him now?", options: ["He is always hungry but happy.", "He is often late for school.", "He should ride more slowly.", "He spends too much money."], answer: 0, explanation: "His mum says he is 'always hungry now, but also always happy'." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
