/* KET Prep extra bank: part3 wave 1 */
(function () {
  var BANK = [
    { stem: "PLAY", text: "The best ____ in our basketball team is only twelve years old.", answers: ["player"], explanation: "We need a person noun. Add '-er' to 'play' to make 'player'." },
    { stem: "TEACH", text: "My maths ____ always explains things twice so we understand.", answers: ["teacher"], explanation: "A person who teaches is a 'teacher'. Add '-er' to the verb." },
    { stem: "SING", text: "The ____ on the radio this morning had a lovely voice.", answers: ["singer"], explanation: "A person who sings is a 'singer'. Add '-er' to 'sing'." },
    { stem: "DANCE", text: "My sister wants to be a ____ when she grows up.", answers: ["dancer"], explanation: "A person who dances is a 'dancer'. Add '-r' to 'dance'." },
    { stem: "SWIM", text: "Tom is a fast ____ and he practises in the pool every day.", answers: ["swimmer"], explanation: "A person who swims is a 'swimmer'. Double the 'm' and add '-er'." },
    { stem: "RUN", text: "The fastest ____ in the race came from our school.", answers: ["runner"], explanation: "A person who runs is a 'runner'. Double the 'n' and add '-er'." },
    { stem: "DRIVE", text: "The bus ____ said hello to everyone this morning.", answers: ["driver"], explanation: "A person who drives is a 'driver'. Add '-r' to 'drive'." },
    { stem: "PAINT", text: "A famous ____ made this picture over a hundred years ago.", answers: ["painter"], explanation: "A person who paints is a 'painter'. Add '-er' to 'paint'." },
    { stem: "WRITE", text: "My favourite ____ has written more than twenty books for children.", answers: ["writer"], explanation: "A person who writes books is a 'writer'. Add '-r' to 'write'." },
    { stem: "WORK", text: "Every ____ at the factory gets a free lunch on Fridays.", answers: ["worker"], explanation: "A person who works is a 'worker'. Add '-er' to 'work'." },
    { stem: "FARM", text: "The ____ gets up at five o'clock to feed his cows.", answers: ["farmer"], explanation: "A person who works on a farm is a 'farmer'. Add '-er'." },
    { stem: "BUILD", text: "A ____ is coming next week to repair our garden wall.", answers: ["builder"], explanation: "A person who builds things is a 'builder'. Add '-er' to 'build'." },
    { stem: "CLEAN", text: "The ____ comes to our office every evening at six.", answers: ["cleaner"], explanation: "A person who cleans is a 'cleaner'. Add '-er' to 'clean'." },
    { stem: "BAKE", text: "The ____ in our street makes wonderful chocolate cakes.", answers: ["baker"], explanation: "A person who bakes bread and cakes is a 'baker'. Add '-r'." },
    { stem: "WIN", text: "The ____ of the competition will get a new bicycle.", answers: ["winner"], explanation: "A person who wins is a 'winner'. Double the 'n' and add '-er'." },
    { stem: "VISIT", text: "Every ____ to the museum gets a free map at the door.", answers: ["visitor"], explanation: "A person who visits is a 'visitor'. Add '-or' to 'visit'." },
    { stem: "ACT", text: "That ____ was in my favourite film last year.", answers: ["actor"], explanation: "A person who acts in films is an 'actor'. Add '-or' to 'act'." },
    { stem: "SAIL", text: "My grandfather was a ____ and travelled all over the world.", answers: ["sailor"], explanation: "A person who sails is a 'sailor'. Add '-or' to 'sail'." },
    { stem: "WAIT", text: "The ____ brought us the menu and some water.", answers: ["waiter"], explanation: "A man who serves food in a restaurant is a 'waiter'. Add '-er'." },
    { stem: "SHOP", text: "Every ____ at the market was looking for cheap fruit.", answers: ["shopper"], explanation: "A person who shops is a 'shopper'. Double the 'p' and add '-er'." },
    { stem: "REPORT", text: "A ____ from the local newspaper asked us about the school play.", answers: ["reporter"], explanation: "A person who reports news is a 'reporter'. Add '-er'." },
    { stem: "MANAGE", text: "The ____ of the hotel showed us to our room.", answers: ["manager"], explanation: "A person who manages a place is a 'manager'. Add '-r'." },
    { stem: "OWN", text: "The ____ of the cafe knows all his customers' names.", answers: ["owner"], explanation: "A person who owns something is the 'owner'. Add '-er' to 'own'." },
    { stem: "GARDEN", text: "The ____ planted some new roses in the park.", answers: ["gardener"], explanation: "A person who works in gardens is a 'gardener'. Add '-er'." },
    { stem: "FOOTBALL", text: "My uncle was a famous ____ when he was young.", answers: ["footballer"], explanation: "A person who plays football is a 'footballer'. Add '-er'." },
    { stem: "SUN", text: "Take your hat because it will be very ____ this afternoon.", answers: ["sunny"], explanation: "We need an adjective for weather. 'Sun' becomes 'sunny' with double 'n' and '-y'." },
    { stem: "RAIN", text: "It was too ____ to play outside, so we stayed at home.", answers: ["rainy"], explanation: "We need an adjective. Add '-y' to 'rain' to make 'rainy'." },
    { stem: "WIND", text: "It is very ____ today, so hold your umbrella carefully.", answers: ["windy"], explanation: "We need a weather adjective. Add '-y' to 'wind' to make 'windy'." },
    { stem: "CLOUD", text: "The sky was grey and ____ all morning.", answers: ["cloudy"], explanation: "We need an adjective. Add '-y' to 'cloud' to make 'cloudy'." },
    { stem: "SNOW", text: "On ____ days we love making snowmen in the garden.", answers: ["snowy"], explanation: "We need an adjective before 'days'. Add '-y' to 'snow'." },
    { stem: "FOG", text: "The morning was so ____ that we could not see the bridge.", answers: ["foggy"], explanation: "We need an adjective. 'Fog' becomes 'foggy' with double 'g' and '-y'." },
    { stem: "STORM", text: "The sea looks dangerous on ____ nights like this.", answers: ["stormy"], explanation: "We need an adjective before 'nights'. Add '-y' to 'storm'." },
    { stem: "LUCK", text: "I was very ____ because I found my keys under the sofa.", answers: ["lucky"], explanation: "We need an adjective after 'was'. Add '-y' to 'luck' to make 'lucky'." },
    { stem: "DIRT", text: "Wash your hands because they are ____ after playing football.", answers: ["dirty"], explanation: "We need an adjective. Add '-y' to 'dirt' to make 'dirty'." },
    { stem: "NOISE", text: "The classroom was too ____ so the teacher closed the door.", answers: ["noisy"], explanation: "We need an adjective. 'Noise' becomes 'noisy' with '-y'." },
    { stem: "SALT", text: "This soup is too ____ for me to eat.", answers: ["salty"], explanation: "We need an adjective. Add '-y' to 'salt' to make 'salty'." },
    { stem: "SAND", text: "We walked along the long ____ beach in the evening.", answers: ["sandy"], explanation: "We need an adjective before 'beach'. Add '-y' to 'sand'." },
    { stem: "FUN", text: "The clown at the party was really ____ and everybody laughed.", answers: ["funny"], explanation: "We need an adjective. 'Fun' becomes 'funny' with double 'n' and '-y'." },
    { stem: "SLEEP", text: "I felt very ____ after the long journey, so I went to bed early.", answers: ["sleepy"], explanation: "We need an adjective after 'felt'. Add '-y' to 'sleep'." },
    { stem: "THIRST", text: "After the tennis match we were all hot and ____.", answers: ["thirsty"], explanation: "We need an adjective. Add '-y' to 'thirst' to make 'thirsty'." },
    { stem: "HUNGER", text: "I am always ____ when I come home from school.", answers: ["hungry"], explanation: "The adjective from 'hunger' is 'hungry', meaning wanting food." },
    { stem: "HEALTH", text: "Eating fruit and vegetables keeps you strong and ____.", answers: ["healthy"], explanation: "We need an adjective. Add '-y' to 'health' to make 'healthy'." },
    { stem: "ICE", text: "Be careful on the road because it is ____ this morning.", answers: ["icy"], explanation: "We need an adjective. 'Ice' becomes 'icy', meaning covered with ice." },
    { stem: "ROCK", text: "The path up the mountain was steep and ____.", answers: ["rocky"], explanation: "We need an adjective. Add '-y' to 'rock' to make 'rocky'." },
    { stem: "MUD", text: "My boots got very ____ when we walked across the field.", answers: ["muddy"], explanation: "We need an adjective. 'Mud' becomes 'muddy' with double 'd' and '-y'." },
    { stem: "SMELL", text: "Please take out the rubbish because the kitchen is getting ____.", answers: ["smelly"], explanation: "We need an adjective. 'Smell' becomes 'smelly', meaning it smells bad." },
    { stem: "TASTE", text: "Grandma's pizza is the most ____ food I know.", answers: ["tasty"], explanation: "We need an adjective. 'Taste' becomes 'tasty', meaning delicious." },
    { stem: "MESS", text: "Your bedroom is so ____ that I cannot see the floor.", answers: ["messy"], explanation: "We need an adjective. 'Mess' becomes 'messy', meaning untidy." },
    { stem: "DUST", text: "The old books on the top shelf were very ____.", answers: ["dusty"], explanation: "We need an adjective. Add '-y' to 'dust' to make 'dusty'." },
    { stem: "STAR", text: "We watched the ____ sky from the top of the hill.", answers: ["starry"], explanation: "We need an adjective. 'Star' becomes 'starry' with double 'r' and '-y'." },
    { stem: "QUICK", text: "The waiter brought our drinks very ____.", answers: ["quickly"], explanation: "We need an adverb to describe 'brought'. Add '-ly' to 'quick'." },
    { stem: "SLOW", text: "Grandpa walks ____ because his legs hurt.", answers: ["slowly"], explanation: "We need an adverb to describe 'walks'. Add '-ly' to 'slow'." },
    { stem: "QUIET", text: "Please close the door ____ because the baby is sleeping.", answers: ["quietly"], explanation: "We need an adverb to describe how to close the door. Add '-ly'." },
    { stem: "CAREFUL", text: "You must carry the glasses ____ or they will break.", answers: ["carefully"], explanation: "We need an adverb. 'Careful' becomes 'carefully' with '-ly'." },
    { stem: "EASY", text: "She answered all the questions ____ because she had studied hard.", answers: ["easily"], explanation: "We need an adverb. 'Easy' becomes 'easily'; change '-y' to '-ily'." },
    { stem: "HAPPY", text: "The children played ____ in the park all afternoon.", answers: ["happily"], explanation: "We need an adverb. 'Happy' becomes 'happily'; change '-y' to '-ily'." },
    { stem: "LOUD", text: "Do not talk so ____ in the library, please.", answers: ["loudly"], explanation: "We need an adverb to describe 'talk'. Add '-ly' to 'loud'." },
    { stem: "SAFE", text: "The plane landed ____ after the long flight.", answers: ["safely"], explanation: "We need an adverb to describe 'landed'. Add '-ly' to 'safe'." },
    { stem: "BAD", text: "Our team played ____ and lost the match three-nil.", answers: ["badly"], explanation: "We need an adverb to describe 'played'. Add '-ly' to 'bad'." },
    { stem: "SAD", text: "She smiled ____ when she said goodbye to her friends.", answers: ["sadly"], explanation: "We need an adverb to describe 'smiled'. Add '-ly' to 'sad'." },
    { stem: "POLITE", text: "He always speaks ____ to older people.", answers: ["politely"], explanation: "We need an adverb to describe 'speaks'. Add '-ly' to 'polite'." },
    { stem: "ANGRY", text: "The man shouted ____ when the dog took his sandwich.", answers: ["angrily"], explanation: "We need an adverb. 'Angry' becomes 'angrily'; change '-y' to '-ily'." },
    { stem: "NICE", text: "If you ask ____, Mum might give you some ice cream.", answers: ["nicely"], explanation: "We need an adverb to describe 'ask'. Add '-ly' to 'nice'." },
    { stem: "SOFT", text: "The singer spoke ____ into the microphone before the song.", answers: ["softly"], explanation: "We need an adverb to describe 'spoke'. Add '-ly' to 'soft'." },
    { stem: "SUDDEN", text: "It ____ started to rain, so we ran into a shop.", answers: ["suddenly"], explanation: "We need an adverb before the verb. Add '-ly' to 'sudden'." },
    { stem: "USUAL", text: "We ____ have dinner at seven o'clock in the evening.", answers: ["usually"], explanation: "We need an adverb of frequency. Add '-ly' to 'usual'." },
    { stem: "FINAL", text: "After waiting an hour, the bus ____ arrived.", answers: ["finally"], explanation: "We need an adverb meaning 'in the end'. Add '-ly' to 'final'." },
    { stem: "CLEAR", text: "The teacher spoke slowly and ____ so everyone understood.", answers: ["clearly"], explanation: "We need an adverb to describe 'spoke'. Add '-ly' to 'clear'." },
    { stem: "BRAVE", text: "The firefighter ____ went into the burning house.", answers: ["bravely"], explanation: "We need an adverb to describe how he went in. Add '-ly'." },
    { stem: "GENTLE", text: "Hold the kitten ____ because it is very small.", answers: ["gently"], explanation: "We need an adverb. 'Gentle' becomes 'gently'; drop 'e' before adding '-ly' with 'le' endings." },
    { stem: "CHILD", text: "There were about thirty ____ playing in the school yard.", answers: ["children"], explanation: "We need a plural noun. The irregular plural of 'child' is 'children'." },
    { stem: "MAN", text: "Two ____ were painting the wall outside the bank.", answers: ["men"], explanation: "We need a plural noun. The irregular plural of 'man' is 'men'." },
    { stem: "WOMAN", text: "Three ____ were waiting at the bus stop in the rain.", answers: ["women"], explanation: "We need a plural noun. The irregular plural of 'woman' is 'women'." },
    { stem: "FOOT", text: "My ____ hurt after we walked around the city all day.", answers: ["feet"], explanation: "We need a plural noun. The irregular plural of 'foot' is 'feet'." },
    { stem: "TOOTH", text: "You should brush your ____ twice a day.", answers: ["teeth"], explanation: "We need a plural noun. The irregular plural of 'tooth' is 'teeth'." },
    { stem: "MOUSE", text: "Our cat caught two ____ in the garden last night.", answers: ["mice"], explanation: "We need a plural noun. The irregular plural of 'mouse' is 'mice'." },
    { stem: "PERSON", text: "More than a hundred ____ came to the concert in the park.", answers: ["people"], explanation: "We need a plural noun. The plural of 'person' is 'people'." },
    { stem: "BABY", text: "The two ____ slept while their mothers drank coffee.", answers: ["babies"], explanation: "We need a plural noun. Change '-y' to '-ies': 'babies'." },
    { stem: "CITY", text: "We visited three different ____ during our holiday in Spain.", answers: ["cities"], explanation: "We need a plural noun. Change '-y' to '-ies': 'cities'." },
    { stem: "PARTY", text: "I went to two birthday ____ last weekend.", answers: ["parties"], explanation: "We need a plural noun. Change '-y' to '-ies': 'parties'." },
    { stem: "FAMILY", text: "Many ____ bring a picnic to the beach in summer.", answers: ["families"], explanation: "We need a plural noun. Change '-y' to '-ies': 'families'." },
    { stem: "BOX", text: "We packed our books into six big ____ before we moved house.", answers: ["boxes"], explanation: "We need a plural noun. Words ending in '-x' add '-es': 'boxes'." },
    { stem: "WATCH", text: "The shop sells cheap ____ from many different countries.", answers: ["watches"], explanation: "We need a plural noun. Words ending in '-ch' add '-es': 'watches'." },
    { stem: "LEAF", text: "In autumn the ____ turn red and fall from the trees.", answers: ["leaves"], explanation: "We need a plural noun. Change '-f' to '-ves': 'leaves'." },
    { stem: "KNIFE", text: "Please put the ____ and forks on the table for dinner.", answers: ["knives"], explanation: "We need a plural noun. Change '-fe' to '-ves': 'knives'." },
    { stem: "SHELF", text: "The library has hundreds of books on its ____.", answers: ["shelves"], explanation: "We need a plural noun. Change '-f' to '-ves': 'shelves'." },
    { stem: "TOMATO", text: "Dad grows ____ in pots on our balcony.", answers: ["tomatoes"], explanation: "We need a plural noun. 'Tomato' adds '-es': 'tomatoes'." },
    { stem: "POTATO", text: "We had chicken with ____ and carrots for lunch.", answers: ["potatoes"], explanation: "We need a plural noun. 'Potato' adds '-es': 'potatoes'." },
    { stem: "BUS", text: "There are no ____ to the village on Sundays.", answers: ["buses"], explanation: "We need a plural noun. 'Bus' adds '-es': 'buses'." },
    { stem: "SANDWICH", text: "Mum made cheese ____ for our school trip.", answers: ["sandwiches"], explanation: "We need a plural noun. Words ending in '-ch' add '-es': 'sandwiches'." },
    { stem: "ONE", text: "This is the ____ time I have ever flown in a plane.", answers: ["first"], explanation: "We need an ordinal number. 'One' becomes 'first'." },
    { stem: "TWO", text: "Our flat is on the ____ floor, above the bakery.", answers: ["second"], explanation: "We need an ordinal number. 'Two' becomes 'second'." },
    { stem: "THREE", text: "My birthday is on the ____ of May.", answers: ["third"], explanation: "We need an ordinal number for a date. 'Three' becomes 'third'." },
    { stem: "FOUR", text: "She finished ____ in the swimming race, just behind her friend.", answers: ["fourth"], explanation: "We need an ordinal number. Add '-th' to 'four': 'fourth'." },
    { stem: "FIVE", text: "This is our ____ visit to the zoo this year.", answers: ["fifth"], explanation: "We need an ordinal number. 'Five' becomes 'fifth'." },
    { stem: "SIX", text: "The lift stopped at the ____ floor of the hotel.", answers: ["sixth"], explanation: "We need an ordinal number. Add '-th' to 'six': 'sixth'." },
    { stem: "SEVEN", text: "My little brother started school when he was in his ____ year.", answers: ["seventh"], explanation: "We need an ordinal number. Add '-th' to 'seven': 'seventh'." },
    { stem: "EIGHT", text: "Our team came ____ in the quiz, which was a bit sad.", answers: ["eighth"], explanation: "We need an ordinal number. 'Eight' becomes 'eighth'." },
    { stem: "NINE", text: "The runner in the ____ place still got a small prize.", answers: ["ninth"], explanation: "We need an ordinal number. 'Nine' becomes 'ninth'; drop the 'e'." },
    { stem: "TEN", text: "It is my parents' ____ wedding anniversary this June.", answers: ["tenth"], explanation: "We need an ordinal number. Add '-th' to 'ten': 'tenth'." }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  QUESTIONS.part3 = QUESTIONS.part3.concat(BANK);
})();
