/* KET Prep bank: reading multiple-choice (A2) — wave 12 */
(function () {
var BANK = [
  {
    id: "ket-rmc12-01",
    title: "The School Play",
    text: "Every February our school does a play. Last year it was about a family who move to a new town, and there were twenty-six students in it. I was not one of them. I was one of the six people who worked backstage, which means you are behind the curtain and the audience never sees you. I did the sound. There were forty-one sound cues in that play: doors, a telephone, rain, a car, and music at the beginning and the end. I sat at a small table at the side of the stage with a laptop and a list, and my job was to press one button at exactly the right moment. If you press it two seconds late, everybody notices. We practised for nine weeks, twice a week, and then every evening in the last week. The worst moment was on the Thursday performance, when an actor missed two lines and skipped straight to the part where the telephone rings. I had about one second to decide. I played the telephone, and it worked, and only three people in the whole hall knew that anything had happened. Our teacher, Miss Rowe, told me afterwards that this was the most useful thing I would learn all year. Two hundred and ten people came over three evenings. My family came on the Saturday. My little cousin asked me afterwards which one I was, and I said I was the rain and the telephone, and she did not believe me for the whole of the following week. This February I am doing the sound again, and there is a Year 8 student sitting next to me learning it, exactly as I sat next to somebody last year.",
    questions: [
      { q: "What was the writer's job?", options: ["Doing the sound.","Making the costumes.","Acting in the play.","Selling tickets."], answer: 0, explanation: "'I did the sound.'" },
      { q: "How many sound cues were there?", options: ["Six.","Forty-one.","Twenty-six.","Nine."], answer: 1, explanation: "'There were forty-one sound cues in that play'." },
      { q: "How long did they practise?", options: ["Every evening from February.","One week.","Nine weeks.","Two months exactly."], answer: 2, explanation: "'We practised for nine weeks'." },
      { q: "What went wrong on Thursday?", options: ["The laptop stopped working.", "The curtain would not open.", "An actor was ill.", "An actor missed two lines."], answer: 3, explanation: "'an actor missed two lines and skipped straight to the part where the telephone rings'." },
      { q: "How did the writer deal with it?", options: ["Played the telephone sound immediately.", "Waited for the teacher to help.", "Stopped the sound completely.", "Told the actor what to say."], answer: 0, explanation: "'I played the telephone, and it worked'." },
      { q: "What did the writer's cousin ask?", options: ["How the sound machine worked.", "Which character the writer played.", "Why the writer was not on stage.", "How many people came."], answer: 1, explanation: "'My little cousin asked me afterwards which one I was'." }
    ]
  },
  {
    id: "ket-rmc12-02",
    title: "My First Pair of Glasses",
    text: "I got glasses when I was twelve and I should have got them when I was nine. Nobody knew, including me. I sat near the back of the class and I could not read the board properly, but I did not know that other people could, because you do not know what you are not seeing. I copied from the person next to me, or I waited until the teacher walked past and asked her quietly. In Year 7 we had an eye test at school. A woman came with a machine and we went in one at a time. It took four minutes. She told me to read the letters and I read three lines and then said that the next line was empty. It was not empty. She was very kind about it. Two weeks later I went to a shop in town with my father and chose frames, which took an hour because I did not like any of them. When I put the finished glasses on, in the shop, I looked out of the window and could see the individual leaves on a tree on the other side of the road. I said something out loud, and my father laughed, and the woman in the shop said she sees that every week. School was easier immediately, but the thing I remember is the tree. I have worn glasses for six years now. I only think about them when I lose them, which is about twice a week.",
    questions: [
      { q: "When should the writer have got glasses?", options: ["In Year 7.","Six years ago.","At the age of nine.","At twelve."], answer: 2, explanation: "'I should have got them when I was nine'." },
      { q: "Why did nobody notice the problem?", options: ["The teachers never used the board.","The writer sat at the front.","The writer hid it deliberately.","The writer did not know anything was wrong."], answer: 3, explanation: "'you do not know what you are not seeing'." },
      { q: "How did the writer manage in class?", options: ["By copying and asking the teacher.","By asking to move seats.","By sitting nearer the front.","By using a friend's notes at home."], answer: 0, explanation: "'I copied from the person next to me, or I waited until the teacher walked past'." },
      { q: "What happened during the eye test?", options: ["The test took a long time.","The writer said a line of letters was empty.","The machine did not work.","The writer refused to read."], answer: 1, explanation: "'I read three lines and then said that the next line was empty'." },
      { q: "Why did choosing frames take an hour?", options: ["The father could not decide.","There were only two pairs.","The writer did not like any of them.","The shop was very busy."], answer: 2, explanation: "'it took an hour because I did not like any of them'." },
      { q: "What does the writer remember most?", options: ["The shop assistant.","Reading the board for the first time.","The test at school.","Seeing the leaves on a tree."], answer: 3, explanation: "'the thing I remember is the tree'." }
    ]
  },
  {
    id: "ket-rmc12-03",
    title: "Cooking Dinner for My Family",
    text: "In our house we each cook one evening a week. My mother started this two years ago when she went back to work full time. There are four of us: my parents, my brother who is seventeen, and me. My mother cooks on Monday and Thursday, my father on Tuesday and Friday, my brother on Wednesday and me on Saturday. Sunday is different, and usually means whatever is left in the fridge. When I started I could make two things: pasta with tomato sauce, and eggs. That was fine for about a month, and then my brother said, quite fairly, that he had eaten pasta seven Saturdays in a row. So I learned to make three more things. I found them on a website that shows you a photograph of every step, which helped a lot at the beginning. Rice is the one I still find difficult. It is either fine or it is a wet lump, and I cannot always tell why. There are two rules in our house. The person who cooks does not wash up. And nobody is allowed to say anything about the food except thank you, unless the cook asks, and then everybody must be honest. My brother asked once and we told him, and he has not made that soup again. I am better than I was. Last Saturday I made a chicken dish with potatoes that my father asked me to make again, which he has never done before, and I wrote the date in the front of my book.",
    questions: [
      { q: "Why did the family start this system?", options: ["The mother returned to full-time work.", "The children wanted to learn.", "It was cheaper.", "The father was ill."], answer: 0, explanation: "'My mother started this two years ago when she went back to work full time.'" },
      { q: "Which day does the writer cook?", options: ["Friday.","Saturday.","Sunday.","Wednesday."], answer: 1, explanation: "'my brother on Wednesday and me on Saturday'." },
      { q: "Why did the writer learn new dishes?", options: ["Their mother told them to.","The shop had no pasta.","Their brother complained about pasta.","The website suggested it."], answer: 2, explanation: "'he had eaten pasta seven Saturdays in a row'." },
      { q: "What does the writer still find hard?", options: ["Making sauce.", "Cooking eggs.", "Following the website.", "Cooking rice."], answer: 3, explanation: "'Rice is the one I still find difficult.'" },
      { q: "What is one of the family rules?", options: ["The cook does not wash up.", "Everybody must eat everything.", "Meals must cost under ten pounds.", "No cooking on Sundays."], answer: 0, explanation: "'The person who cooks does not wash up.'" },
      { q: "Why was last Saturday important?", options: ["The writer cooked for guests.", "The father asked for the dish again.", "The writer cooked without a recipe.", "The brother helped."], answer: 1, explanation: "'my father asked me to make again, which he has never done before'." }
    ]
  },
  {
    id: "ket-rmc12-04",
    title: "A Present That Was Wrong",
    text: "For my fourteenth birthday my grandmother gave me a jumper. It was dark green, it was two sizes too big, and it had a picture of a horse on the front. I do not ride horses. I have never ridden a horse. My grandmother is seventy-eight and she lives three hours away and we see her about five times a year. I opened the present in front of her, which is the difficult part, and I said thank you and that I liked it, which was not true. My mother saw my face and said nothing at the time. Later, in the kitchen, she told me something I have thought about since. She said that when my grandmother was young, a jumper was an expensive present, and that she had chosen the horse because when I was six I had a toy horse that I took everywhere and would not go to bed without. My grandmother remembered that and I did not. I wore the jumper twice while she was staying, and then it went into a drawer, and last winter it came out again because it is actually very warm and the house was cold. I have worn it a lot this year, mostly at home. My sister says it is the worst jumper she has ever seen. I have a photograph on my phone of me wearing it, which I sent to my grandmother in January. She has told four different people about it, including a woman at her bus stop whom she barely knows, and my mother says this is the best five minutes of work I have ever done.",
    questions: [
      { q: "What was wrong with the jumper?", options: ["It was the same as one she gave before.","It was the wrong colour and too small.","It was too big and had a horse on it.","It was damaged."], answer: 2, explanation: "'it was two sizes too big, and it had a picture of a horse on the front'." },
      { q: "What did the writer say when they opened it?", options: ["That they did not ride horses.","Nothing at all.","That it was too big.","That they liked it."], answer: 3, explanation: "'I said thank you and that I liked it'." },
      { q: "Why did the grandmother choose a horse?", options: ["The writer had a toy horse as a child.","She thought the writer rode horses.","It was the only design in the shop.","The writer's sister asked her to."], answer: 0, explanation: "'when I was six I had a toy horse that I took everywhere'." },
      { q: "What did the mother explain?", options: ["That the writer had been rude.","That a jumper used to be an expensive gift.","That the writer should return it.","That the grandmother was unwell."], answer: 1, explanation: "'when my grandmother was young, a jumper was an expensive present'." },
      { q: "Why did the writer wear it again last winter?", options: ["All their other clothes were dirty.","The grandmother was visiting.","The house was cold and it is warm.","Their sister asked them to."], answer: 2, explanation: "'it is actually very warm and the house was cold'." },
      { q: "What did the writer send in January?", options: ["A thank-you letter.","A different present.","The jumper back.","A photograph of themselves in the jumper."], answer: 3, explanation: "'I have a photograph on my phone of me wearing it, which I sent to my grandmother in January'." }
    ]
  },
  {
    id: "ket-rmc12-05",
    title: "My Grandmother's Radio",
    text: "There is a radio in my grandmother's kitchen that has been on, more or less, since 1998. It is silver and it stands on the shelf above the bread bin. It is on when she gets up at half past six and it is on when she goes to bed. She listens to one station and she has never changed it. When I stayed with her in the summer I found this very strange for about two days and then I stopped noticing it, which is I think exactly how she experiences it. It is not really about the programmes. She does not sit down to listen. The radio talks while she does other things, and sometimes she answers it, out loud, usually to disagree with somebody. Once I asked her why she does not have the television on instead, and she gave a very clear answer: because you have to look at a television, and she has things to do with her eyes. Last year the radio broke. It made a noise like paper and then stopped. My father bought her a new one, a small modern thing with a screen, and she used it for eleven days and then asked him to take it back. She said the buttons were too small and there were too many of them, and that she did not want to choose anything. In the end my uncle repaired the old one for the price of a part that cost four pounds. It is back on the shelf.",
    questions: [
      { q: "How long has the radio been in the kitchen?", options: ["Since 1998.", "For eleven days.", "Since last year.", "For four years."], answer: 0, explanation: "'has been on, more or less, since 1998'." },
      { q: "How many stations does the grandmother listen to?", options: ["Several, depending on the time.", "Only one.", "Two, morning and evening.", "She changes it every day."], answer: 1, explanation: "'She listens to one station and she has never changed it.'" },
      { q: "How does she use the radio?", options: ["She sits and listens carefully.", "She records programmes to hear later.", "It plays while she does other things.", "She only turns it on for the news."], answer: 2, explanation: "'The radio talks while she does other things'." },
      { q: "Why does she prefer radio to television?", options: ["It is cheaper.", "The television is broken.", "She cannot hear the television.", "You have to look at a television."], answer: 3, explanation: "'because you have to look at a television, and she has things to do with her eyes'." },
      { q: "What was wrong with the new radio?", options: ["Too many small buttons.", "The sound was poor.", "It was too large for the shelf.", "It did not get her station."], answer: 0, explanation: "'the buttons were too small and there were too many of them'." },
      { q: "What happened to the old radio?", options: ["It was thrown away.", "It was repaired cheaply.", "It is kept in a cupboard.", "It was given to the writer."], answer: 1, explanation: "'my uncle repaired the old one for the price of a part that cost four pounds'." }
    ]
  },
  {
    id: "ket-rmc12-06",
    title: "The Swimming Badge",
    text: "At our town pool you can take swimming tests and get badges. They start at five metres and go up to a mile, which is sixty-four lengths of that pool. I got the five-metre badge when I was six and my mother sewed it onto my swimming bag. By the time I was ten I had six badges and the bag was full. Then I stopped for three years. I do not remember deciding to stop. I got interested in other things, the lessons were on Saturday mornings, and I wanted to be somewhere else on Saturday mornings. Last September I went back, because a friend asked me to go with her, and I discovered two things. The first was that I could still swim, which surprised me. The second was that I was much slower and much more tired than I had been at ten. The badge I am working on now is the one for four hundred metres, which is sixteen lengths without stopping. When I started again in September I could do six. Now I can do fourteen. I get one more length about every two weeks, and my friend, who is better than me, says that this is the normal speed and that everybody wants it to be faster. The test is in March. If I pass, that badge goes on my school bag, not the swimming bag, and the swimming bag stays in the cupboard where it has been since I was ten. My mother has offered twice to sew it on for me and I have said that this time I will do it myself, which she thinks is funny and which I mean.",
    questions: [
      { q: "How many badges did the writer have by the age of ten?", options: ["Sixteen.","One.","Six.","Five."], answer: 2, explanation: "'By the time I was ten I had six badges'." },
      { q: "Why did the writer stop swimming?", options: ["The lessons became too expensive.","They were ill.","The pool closed.","They wanted to do other things on Saturdays."], answer: 3, explanation: "'I wanted to be somewhere else on Saturday mornings'." },
      { q: "Why did they start again?", options: ["A friend asked them to go.","Their mother made them.","They wanted to get fit.","A teacher suggested it."], answer: 0, explanation: "'because a friend asked me to go with her'." },
      { q: "What surprised the writer on returning?", options: ["They were faster than before.","They could still swim.","The pool had changed.","The lessons were free."], answer: 1, explanation: "'The first was that I could still swim, which surprised me.'" },
      { q: "How many lengths can they swim now?", options: ["Sixteen.","Sixty-four.","Fourteen.","Six."], answer: 2, explanation: "'Now I can do fourteen.'" },
      { q: "What does the friend say about progress?", options: ["Two weeks is too slow.","The test is too hard.","It will get faster soon.","This speed is normal."], answer: 3, explanation: "'this is the normal speed and that everybody wants it to be faster'." }
    ]
  },
  {
    id: "ket-rmc12-07",
    title: "The Tree in the Playground",
    text: "There is a very large tree in the middle of our school playground. It is a lime tree and the school says it is about a hundred and forty years old, which means it was there before the school buildings. In the summer it makes a big circle of shade, and on hot days that is the most popular place in the whole school. There are two rules about the tree. You cannot climb it, and you cannot pull the branches down. Both rules are sensible and both are broken about once a week. Three years ago the tree caused a problem. A large branch fell in a storm at four in the morning. Nobody was there and nothing was damaged except a bicycle rack. The school had to close for a day while a company came and checked the whole tree. Some parents said afterwards that the tree should be cut down because it was dangerous. Other parents said that it had been there for a hundred and forty years and had dropped one branch. The school asked a tree expert, who came for a morning and said the tree was healthy, that two branches needed to be removed, and that it should be checked every three years. That is what happened. Now there is a small sign under it with a photograph from 1912, which shows the school children standing in front of the same tree. The children in the photograph are wearing hats. The tree looks almost exactly the same.",
    questions: [
      { q: "How old is the tree?", options: ["About a hundred and forty years old.", "Older than the town.", "Planted in 1912.", "Three years old."], answer: 0, explanation: "'the school says it is about a hundred and forty years old'." },
      { q: "Why is the tree popular in summer?", options: ["Children can climb it.", "It gives shade.", "It has fruit.", "It is near the school gate."], answer: 1, explanation: "'it makes a big circle of shade'." },
      { q: "What happened three years ago?", options: ["The tree was cut down.", "A child was hurt.", "A branch fell during a storm.", "The school moved the bicycle rack."], answer: 2, explanation: "'A large branch fell in a storm at four in the morning.'" },
      { q: "What did some parents want?", options: ["A fence around the tree.", "The playground moved.", "More trees planted.", "The tree removed."], answer: 3, explanation: "'the tree should be cut down because it was dangerous'." },
      { q: "What did the expert recommend?", options: ["Removing two branches and regular checks.", "Cutting the tree down.", "Leaving it completely alone.", "Closing that part of the playground."], answer: 0, explanation: "'two branches needed to be removed, and that it should be checked every three years'." },
      { q: "What does the sign show?", options: ["The rules about climbing.", "A photograph from 1912.", "The age of the school.", "The name of the tree expert."], answer: 1, explanation: "'a small sign under it with a photograph from 1912'." }
    ]
  },
  {
    id: "ket-rmc12-08",
    title: "The Postbox at the End of the Road",
    text: "There is a red postbox at the end of our road, in the wall of a house. It has been there since 1936, which you can see because the year is not written on it but the letters of the king who was on the throne are. The post is collected at nine in the morning and at four in the afternoon on weekdays, and at eleven on Saturday. There is no collection on Sunday. Last year the postbox nearly disappeared. The house it is set into was sold, and the new owners wanted to take the wall down and build a wider entrance for two cars. They did not know that they could not touch the postbox, because a postbox belongs to the post office even when it is in somebody else's wall. There were letters in the local newspaper. One woman wrote that she had posted her wedding invitations in that box in 1974. In the end the new owners changed the plan and built the entrance on the other side, which cost them more money and which they were, by all accounts, quite reasonable about. My grandmother uses the box about once a week. She writes to two people, both of them older than she is, and she says that neither of them has any interest in a computer and that she does not either. I have posted three things in my life. Two were birthday cards and one was a form for a passport, and I remember being told to check it four times before it went in.",
    questions: [
      { q: "How can you tell the postbox is old?", options: ["It is a different colour.","A date is written on it.","It has the king's letters on it.","A sign next to it says so."], answer: 2, explanation: "'the letters of the king who was on the throne are'." },
      { q: "When is there no collection?", options: ["On Saturday.","In the afternoon.","At nine in the morning.","On Sunday."], answer: 3, explanation: "'There is no collection on Sunday.'" },
      { q: "What did the new owners want to do?", options: ["Take down the wall for a wider entrance.","Close the collection.","Paint the postbox.","Move it further along the road."], answer: 0, explanation: "'wanted to take the wall down and build a wider entrance for two cars'." },
      { q: "Why could they not remove the postbox?", options: ["It is protected by the council.","It belongs to the post office.","It is too heavy.","The neighbours refused."], answer: 1, explanation: "'a postbox belongs to the post office even when it is in somebody else's wall'." },
      { q: "What happened in the end?", options: ["The house was sold again.","The plan was refused by the council.","The entrance was built elsewhere.","The postbox was moved."], answer: 2, explanation: "'the new owners changed the plan and built the entrance on the other side'." },
      { q: "Why does the grandmother use the box?", options: ["It is nearer than the post office.","She sells things by post.","She has no telephone.","She writes to two older friends."], answer: 3, explanation: "'She writes to two people, both of them older than she is'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
