/* KET Prep bank: reading multiple-choice (A2) — wave 9 */
(function () {
var BANK = [
  {
    id: "ket-rmc9-01",
    title: "The New Shop on Our Street",
    text: "For six years the shop on the corner of our street was empty. The windows were white and there was a sign on the door that said TO LET. My mother told me that it was a bread shop when she was a girl, and after that a shop that sold shoes, and then nothing at all. In March a van arrived and two people began to paint the front. It is green now. The shop opened in May and it sells flowers, fruit and vegetables. The owner's name is Nadia and she is from our town. She worked in a big supermarket for eleven years and then decided to open her own place. The shop is small. There is room for about four customers inside, so when it is busy people wait on the pavement, and they talk to each other while they wait, which never happens in the supermarket. Nadia opens at seven in the morning because people want to buy things before work. She closes at six. On Sunday she does not open at all, and she says that is important because she has two children. My favourite thing is that she remembers what people buy. She knows my mother likes yellow tomatoes, and when she has them she keeps some for her. Some people say the shop is more expensive than the supermarket. That is true for some things and not for others. My mother says she buys her vegetables from Nadia and her washing powder from the supermarket, and that this is not complicated at all.",
    questions: [
      { q: "How long was the shop empty?", options: ["Six years.", "Eleven years.", "Since May.", "Since my mother was a girl."], answer: 0, explanation: "'For six years the shop on the corner of our street was empty.'" },
      { q: "What does the shop sell now?", options: ["Shoes.","Flowers and vegetables.","Washing powder.","Bread."], answer: 1, explanation: "'it sells flowers, fruit and vegetables'." },
      { q: "What did Nadia do before?", options: ["She was a teacher.","She had another shop.","She worked in a supermarket.","She painted houses."], answer: 2, explanation: "'She worked in a big supermarket for eleven years'." },
      { q: "Why do customers wait outside?", options: ["Nadia asks them to.","The shop opens late.","They are waiting for a delivery.","There is not much room inside."], answer: 3, explanation: "'There is room for about four customers inside'." },
      { q: "Why is the shop closed on Sundays?", options: ["Nadia wants time with her children.", "Nobody comes on Sundays.", "The market is open instead.", "Nadia works in the supermarket."], answer: 0, explanation: "'On Sunday she does not open at all, and she says that is important because she has two children.'" },
      { q: "What does the writer like best about the shop?", options: ["The low prices.","Nadia remembers what people buy.","The green paint.","The early opening time."], answer: 1, explanation: "'My favourite thing is that she remembers what people buy.'" }
    ]
  },
  {
    id: "ket-rmc9-02",
    title: "Grandad's Tomatoes",
    text: "My grandad grows tomatoes in a small greenhouse behind his house. He has done it every year since 1988. He does not grow anything else. There is a garden with grass and two apple trees, but the greenhouse is only for tomatoes, and he says that one thing done well is better than six things done badly. He starts in February. The seeds go into small pots on the kitchen window, where it is warm, and they stay there until April. Then they move into the greenhouse. He waters them every morning at seven and he talks to them, which my sister thinks is very funny and which my grandad says makes no difference to the plants and a lot of difference to him. The first tomatoes are ready at the end of June. There are always far too many. Last summer he picked more than thirty kilos, and there are only two people in that house. So he gives them away. He puts a box at the front gate with a sign that says HELP YOURSELF, and by the evening the box is empty. Our neighbour Mrs Choi makes soup with them and brings some back to him, which he says is the best part of the whole business. This year he is teaching me. I have four plants of my own in the greenhouse, in the corner near the door. Two of them are not doing well. Grandad says that is normal, that he lost half his plants in his first year, and that the important thing is to write down what I did.",
    questions: [
      { q: "What does Grandad grow in the greenhouse?", options: ["Flowers and tomatoes.","Apples.","Only tomatoes.","Vegetables of many kinds."], answer: 2, explanation: "'the greenhouse is only for tomatoes'." },
      { q: "Where do the seeds start?", options: ["At Mrs Choi's house.","In the greenhouse.","In the garden.","On the kitchen window."], answer: 3, explanation: "'The seeds go into small pots on the kitchen window'." },
      { q: "Why does Grandad talk to the plants?", options: ["It helps him, not the plants.", "It makes them grow faster.", "His sister told him to.", "To keep birds away."], answer: 0, explanation: "he says it 'makes no difference to the plants and a lot of difference to him'." },
      { q: "What does he do with the extra tomatoes?", options: ["He keeps them for the winter.","He leaves them at the gate for anybody.","He sells them at the market.","He makes soup."], answer: 1, explanation: "'He puts a box at the front gate with a sign that says HELP YOURSELF'." },
      { q: "What does Mrs Choi do?", options: ["She sells the tomatoes.","She grows her own.","She brings soup back to him.","She waters the plants."], answer: 2, explanation: "'Our neighbour Mrs Choi makes soup with them and brings some back to him'." },
      { q: "What does Grandad tell the writer about the two weak plants?", options: ["That the corner is the wrong place.","To throw them away.","To water them twice a day.","That losing plants is normal."], answer: 3, explanation: "'Grandad says that is normal, that he lost half his plants in his first year'." }
    ]
  },
  {
    id: "ket-rmc9-03",
    title: "Boots That Were Too Big",
    text: "When I was ten I wanted to play football for the school team. My friend Dom was already in the team and he told me the trials were on Thursday. The problem was my boots. I did not have any. My mother said that boots were expensive and that we would see if I got into the team first, which seemed the wrong way round to me but was probably sensible. On Wednesday evening my cousin Leo came round with a pair of boots in a plastic bag. They were black, they were only a year old, and they were two sizes too big. My mother put a thick sock inside each one at the toe. On Thursday it rained. I ran onto the field and after four minutes one boot came off completely. I put it back on. Ten minutes later it happened again. The teacher, Mr Kerr, watched me run after the ball with one boot in my hand and said nothing at all. I did not get into the team. Mr Kerr asked me to come back in September, and he told me one thing, quietly, at the end: get boots that fit. In August my mother bought me a pair in the right size. They were not new. She found them in a shop that sells second-hand sports things, and they cost eight pounds. I played in the school team for three years in those boots. Leo's old boots went back to Leo, who by then had grown into them himself.",
    questions: [
      { q: "How did the writer hear about the trials?", options: ["From his friend Dom.","From a sign at school.","From his cousin Leo.","From Mr Kerr."], answer: 0, explanation: "'My friend Dom was already in the team and he told me the trials were on Thursday.'" },
      { q: "Why did his mother not buy boots first?", options: ["Leo had already offered his.","She thought they were too expensive to buy before he was chosen.","The shops were closed.","She did not want him to play."], answer: 1, explanation: "'boots were expensive and… we would see if I got into the team first'." },
      { q: "What was wrong with Leo's boots?", options: ["They were old and broken.", "They were the wrong colour.", "They were too big.", "They were for a different sport."], answer: 2, explanation: "'they were two sizes too big'." },
      { q: "What happened during the trial?", options: ["The writer scored a goal.", "The game was stopped by rain.", "Dom was injured.", "A boot came off twice."], answer: 3, explanation: "one boot came off after four minutes and again ten minutes later." },
      { q: "What did Mr Kerr tell him at the end?", options: ["To get boots that fit.", "To practise every day.", "To join a different team.", "To play in a different position."], answer: 0, explanation: "'get boots that fit'." },
      { q: "Where did his new boots come from?", options: ["From a big sports shop.", "From a second-hand shop.", "From Leo again.", "From the school."], answer: 1, explanation: "'She found them in a shop that sells second-hand sports things'." }
    ]
  },
  {
    id: "ket-rmc9-04",
    title: "The Music Lesson I Nearly Missed",
    text: "I have a piano lesson every Tuesday at five o'clock. My teacher, Mrs Iyer, lives fifteen minutes away on foot. On the second Tuesday in October I came home from school, put my bag down, ate an apple and sat on the sofa. When I looked at the clock it said seven minutes to five. I had not practised at all that week, which was the real problem. I had a new piece, three pages long, and I had played it once, badly, on the Wednesday before. I ran. I arrived at four minutes past five with my coat still open and no book, because I had left the music on my bed. Mrs Iyer did not say anything about the time. She asked me to play the piece, and I told her the truth, which was that I did not have it and had not practised. She looked at me for a moment and then said something surprising: good, we will do something else today. She sat at the piano and played four notes and asked me to play them back without looking. I could. Then eight notes. Then a short tune I had never heard. We did that for the whole lesson. At the end she said that my ears were better than my fingers, and that this was useful information and she was glad we had found it out. The next week I practised for four days, and she made me play the piece with the book closed. It was much harder and it sounded much better.",
    questions: [
      { q: "How does the writer get to the lesson?", options: ["By bus.", "By car with a parent.", "On foot.", "By bicycle."], answer: 2, explanation: "'Mrs Iyer lives fifteen minutes away on foot.'" },
      { q: "What was the writer's real problem that week?", options: ["The piano was broken.","They had lost the music.","They were ill on Wednesday.","They had not practised."], answer: 3, explanation: "'I had not practised at all that week, which was the real problem.'" },
      { q: "Why did the writer arrive without the music?", options: ["It was left on the bed at home.","The teacher had not given it to them.","Mrs Iyer had it already.","It was left at school."], answer: 0, explanation: "'I had left the music on my bed'." },
      { q: "How did Mrs Iyer react?", options: ["She telephoned the writer's mother.","She changed the lesson to something else.","She was angry about the lateness.","She sent the writer home."], answer: 1, explanation: "'good, we will do something else today'." },
      { q: "What did they do in the lesson?", options: ["Practised the new piece slowly.","Listened to a recording.","Played notes back without looking.","Read a book about music."], answer: 2, explanation: "'She sat at the piano and played four notes and asked me to play them back without looking.'" },
      { q: "What did Mrs Iyer say about the writer?", options: ["That they must always bring the music.","That the piece was too difficult.","That they should change teachers.","That their ears were better than their fingers."], answer: 3, explanation: "'my ears were better than my fingers'." }
    ]
  },
  {
    id: "ket-rmc9-05",
    title: "Helping at the Village Fair",
    text: "Our village has a fair in the field behind the church on the first Saturday in July. It is more than seventy years old. Last year I helped for the first time, because I am now thirteen and thirteen is the youngest age you can be to have a job at the fair. There are lots of jobs. Some people put up tables at eight in the morning. Some sell tickets at the gate. Some make tea in the church hall, which is hot work and goes on all day. I wanted to help with the animals, but that job was already taken by two girls from my class who asked in March. I got the cake table. My job was to take the money and to say how much each cake cost, which was written on a small card in front of it. It sounds easy and it was not, because people wanted to talk. An old man asked me who had made the lemon cake and I did not know. After that I wrote the name of the baker on the back of every card, and by two o'clock I could answer any question about any cake on that table. We sold everything except one large chocolate cake, which was still there at four. My mother bought it for three pounds, half price, and we ate it for two days. The tea helpers finished at six o'clock and they were the last to go home. This year I have already asked for the animals. I asked in January, which is five months earlier than the two girls did, and the woman who organises the jobs wrote my name down straight away and told me that nobody had ever asked her that early before.",
    questions: [
      { q: "When does the fair happen?", options: ["The first Saturday in July.", "Every Saturday in summer.", "In the school holidays.", "On the first Sunday in June."], answer: 0, explanation: "'Our village has a fair in the field behind the church on the first Saturday in July.'" },
      { q: "Why could the writer help for the first time?", options: ["They moved to the village.", "They are now old enough.", "Their mother asked for them.", "There were not enough helpers."], answer: 1, explanation: "'thirteen is the youngest age you can be to have a job at the fair'." },
      { q: "Why did the writer not get the animal job?", options: ["It was only for adults.", "There were no animals last year.", "Two classmates asked earlier.", "The writer arrived late."], answer: 2, explanation: "'that job was already taken by two girls from my class who asked in March'." },
      { q: "What made the cake table difficult?", options: ["The prices were not written down.", "The table was in the sun.", "There was no change in the box.", "People asked questions."], answer: 3, explanation: "'it was not, because people wanted to talk'." },
      { q: "What did the writer do to solve the problem?", options: ["Wrote the baker's name on each card.", "Asked another helper to take over.", "Put all the cakes at one price.", "Moved the table into the hall."], answer: 0, explanation: "'I wrote the name of the baker on the back of every card'." },
      { q: "What happened to the chocolate cake?", options: ["Nobody wanted it and it was thrown away.","The writer's mother bought it cheaply.","It was sold first.","It was given to the church."], answer: 1, explanation: "'My mother bought it for three pounds, half price'." }
    ]
  },
  {
    id: "ket-rmc9-06",
    title: "My First Time on a Plane",
    text: "I was nineteen the first time I flew. That is late in my family: my younger brother was four. We went to see my aunt, who lives in Ireland, and the flight was only fifty minutes, which everybody told me was lucky for a first time. I was not frightened of flying. I was frightened of the airport. Nobody explains an airport to you. There are signs everywhere and they all use words that mean something slightly different from the word you know, and everybody around you is walking quickly and looking at their phone as if the whole thing is simple. I stood in the wrong queue for eleven minutes. A woman in a yellow jacket noticed and moved me, kindly, without making me feel stupid, and I have thought about her several times since. The plane itself was easy. I had a seat by the window. When we went up through the cloud there was a moment when everything below disappeared and the sun came in very bright, and the man next to me, who was about sixty and travelled every week, put down his newspaper and looked out of the window too. He said he still liked that part. We landed early. My aunt was waiting, and she said, before anything else, that I looked exactly like my mother did at that age. On the way back, six days later, I knew where to stand and which queue was mine, and the whole thing took about half the time it had taken on the Monday. Now I have flown eleven times, always to the same place. The airport is still the hard part and the window is still the good part.",
    questions: [
      { q: "How old was the writer on their first flight?", options: ["Four.", "Eleven.", "Nineteen.", "Sixty."], answer: 2, explanation: "'I was nineteen the first time I flew.'" },
      { q: "What was the writer afraid of?", options: ["Flying.","Meeting their aunt.","Being late.","The airport."], answer: 3, explanation: "'I was frightened of the airport.'" },
      { q: "What problem did the writer have?", options: ["They waited in the wrong queue.","They missed the plane.","Their bag was too heavy.","They lost their ticket."], answer: 0, explanation: "'I stood in the wrong queue for eleven minutes.'" },
      { q: "Who helped the writer?", options: ["Their brother.","A woman in a yellow jacket.","The man sitting next to them.","Their aunt."], answer: 1, explanation: "'A woman in a yellow jacket noticed and moved me'." },
      { q: "What did the man on the plane do?", options: ["He slept the whole way.","He read his newspaper.","He looked out of the window too.","He explained the journey."], answer: 2, explanation: "he 'put down his newspaper and looked out of the window too'." },
      { q: "What does the writer think now?", options: ["They prefer to travel by boat.","Short flights are the worst.","Flying is more difficult than they expected.","The airport is still the hard part."], answer: 3, explanation: "'The airport is still the hard part and the window is still the good part.'" }
    ]
  },
  {
    id: "ket-rmc9-07",
    title: "Learning to Play Chess",
    text: "My uncle taught me chess when I was eight, in one afternoon, and then beat me forty times in a row. I remember the number because I counted. He did not let me win, not once, and I asked him about it years later. He said that a game somebody has let you win teaches you nothing, and that he had waited for me to notice this, which took me about a month. After the first month I stopped losing so quickly. The thing that changed was not that I learned clever moves. It was that I started to look at what my uncle was doing before I moved my own piece, which sounds obvious and is the hardest habit in the game. My first win came in the November after my ninth birthday. It took two hours and my uncle thought about his moves for a long time near the end, which I did not understand then and understand now: he was making sure that I had really won it. At school there is a chess club on Wednesdays with about twenty members. I am not the best player there. The best is a girl in Year 8 called Ines who plays online against people in other countries and once beat a very strong adult in a competition in Manchester. I have played her four times and lost four times, and she does the same thing my uncle did: she never says well done unless I have actually done something well.",
    questions: [
      { q: "Who taught the writer to play?", options: ["Their uncle.","Ines.","Their father.","A teacher at school."], answer: 0, explanation: "'My uncle taught me chess when I was eight'." },
      { q: "Why did the uncle never let the writer win?", options: ["He did not think the writer was learning.","A game you are given teaches nothing.","He had promised the writer's parents.","He wanted to win himself."], answer: 1, explanation: "'a game somebody has let you win teaches you nothing'." },
      { q: "What changed after the first month?", options: ["The uncle played more slowly.","The writer learned clever moves.","The writer looked at the uncle's moves first.","They played shorter games."], answer: 2, explanation: "'I started to look at what my uncle was doing before I moved my own piece'." },
      { q: "Why did the uncle think for a long time in that game?", options: ["He was tired.", "He wanted to make the game longer.", "He was not paying attention.", "He was checking the writer had really won."], answer: 3, explanation: "'he was making sure that I had really won it'." },
      { q: "Who is the best player at the chess club?", options: ["A girl called Ines.", "The writer.", "The teacher who runs it.", "Nobody knows."], answer: 0, explanation: "'The best is a girl in Year 8 called Ines'." },
      { q: "What do Ines and the uncle have in common?", options: ["They both play online.", "They only praise real success.", "They both learned at eight.", "They play very fast."], answer: 1, explanation: "'she never says well done unless I have actually done something well'." }
    ]
  },
  {
    id: "ket-rmc9-08",
    title: "The Snow Day",
    text: "It snowed on a Wednesday night in January and by Thursday morning there was thirty centimetres in our street. That is a lot for our town. The radio said that the schools were closed, and my brother and I went outside at eight o'clock, before we had properly finished breakfast, and stayed out until it got dark at four. The street was quiet in a way I had never heard. No cars could move. Two of our neighbours came out with spades and cleared the pavement in front of their houses, then kept going and did the whole street, which took them most of the morning. My father went out and helped from about ten. In the afternoon everybody was outside. Children from four different streets came to the hill behind the church, and there were about fifty people there with sledges, plastic boxes and one old door, which was the fastest thing on the hill and belonged to a boy called Tom. Mrs Aziz from number 3, who is eighty-one, came out to watch and somebody brought her a chair from her own kitchen. In the evening my mother made soup and we ate it with the television off, all four of us, which almost never happens. The snow was gone by Saturday. I have thought since that the strange thing was not the snow. It was that everybody was outside at the same time, talking, and that this needed the town to stop completely before it could happen.",
    questions: [
      { q: "How much snow fell?", options: ["More than a metre.","The text does not say.","About thirty centimetres.","A few centimetres."], answer: 2, explanation: "'by Thursday morning there was thirty centimetres in our street'." },
      { q: "How did the children find out about school?", options: ["A message on the school website.","A neighbour told them.","A teacher telephoned.","From the radio."], answer: 3, explanation: "'The radio said that the schools were closed'." },
      { q: "What did the two neighbours do?", options: ["They cleared the whole street.","They brought sledges for the children.","They drove people to work.","They made soup for the street."], answer: 0, explanation: "they 'cleared the pavement in front of their houses, then kept going and did the whole street'." },
      { q: "What was the fastest thing on the hill?", options: ["A pair of skis.","An old door.","A metal sledge.","A plastic box."], answer: 1, explanation: "'one old door, which was the fastest thing on the hill'." },
      { q: "What did somebody do for Mrs Aziz?", options: ["Cleared her path.","Made her a hot drink.","Brought her a chair.","Took her home early."], answer: 2, explanation: "'somebody brought her a chair from her own kitchen'." },
      { q: "What does the writer find strange about the day?", options: ["That the schools closed at all.","That nobody could drive.","That the snow melted so quickly.","That everybody was outside together."], answer: 3, explanation: "'It was that everybody was outside at the same time, talking'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
