/* KET Prep bank: reading multiple-choice (A2) — wave 20 */
(function () {
var BANK = [
  {
    id: "ket-rmc20-01",
    title: "The Cake Stall",
    text: "Every Saturday morning there is a cake stall outside the church in our town. It is run by four women, all of them over seventy, and it has been there since 1994. They start at nine and they are usually finished by half past eleven, because everything is sold. Each woman bakes at home on the Friday. They do not decide together what to make and they never have, and the result is that there are always about eight kinds of cake and they are always different, which the customers like. The prices are low. A large slice costs one pound twenty and a whole small cake is six pounds, and they have not raised the prices since 2019 although everything they buy has become more expensive. When somebody asked about this last year, one of them said that they are not a business and that the money is not the point. The money goes to the church roof, which needs about forty thousand pounds and which the stall will never pay for. They know this. In thirty-one years they have raised about nineteen thousand pounds. My grandmother buys a lemon cake there almost every week and has done for years. She told me that when her husband died in 2011 those four women brought food to her house every day for a fortnight without being asked and without discussing it with each other, and that this is what the stall actually is. She has told me that story three times and she tells it the same way every time, which my mother says is how you know somebody means it.",
    questions: [
      { q: "How long has the stall existed?", options: ["Since 1994.", "Since 2011.", "For about ten years.", "Since 2019."], answer: 0, explanation: "'it has been there since 1994'." },
      { q: "Why is there a variety of cakes?", options: ["Customers order in advance.","Each woman bakes what she likes.","A shop supplies some of them.","They plan it carefully."], answer: 1, explanation: "'They do not decide together what to make'." },
      { q: "What is true about the prices?", options: ["They vary each week.","There is no fixed price.","They have not changed since 2019.","They rise every year."], answer: 2, explanation: "'they have not raised the prices since 2019'." },
      { q: "What did one of the women say about money?", options: ["The prices will rise soon.","The church should pay them.","They need more helpers.","They are not a business."], answer: 3, explanation: "'they are not a business and that the money is not the point'." },
      { q: "How much have they raised in total?", options: ["About nineteen thousand pounds.","Nobody has counted.","Forty thousand pounds.","Six thousand pounds."], answer: 0, explanation: "'In thirty-one years they have raised about nineteen thousand pounds.'" },
      { q: "What did the four women do in 2011?", options: ["Asked her to join them.","Brought food to the grandmother for two weeks.","Closed the stall for a month.","Raised money for her."], answer: 1, explanation: "'brought food to her house every day for a fortnight'." }
    ]
  },
  {
    id: "ket-rmc20-02",
    title: "The Coldest Morning",
    text: "The coldest morning I remember was in December two years ago. It was minus eleven degrees at seven o'clock, which is very unusual where we live, and the whole town was different for one day. The car would not start. My father tried three times and then stopped, because he said that trying again would only make it worse, and he telephoned his work and said he would be late. Every window in the house had ice on the inside, in a pattern like leaves, which I had never seen before and which my grandmother said was completely normal in the house she grew up in. School was open. About half the students came. The heating in our building was on but the corridors were cold and nobody took their coat off all day, including two teachers. In the afternoon somebody discovered that the water in the pipe to the outside tap had frozen and pushed the tap apart, which the caretaker had expected and had put a note about on the staff board in November, which nobody had read. What I remember most is the sound. Snow makes a place quiet and hard frost does something different: everything is louder and sharper, and you can hear a car door close four streets away. I stood outside for about ten minutes before school just listening, and I was extremely cold, and I would do it again. It has not been below minus five since, and every time the forecast says it might be, I check it twice.",
    questions: [
      { q: "How cold was it?", options: ["Colder than minus twenty.","The text does not say.","Minus eleven degrees.","Just below zero."], answer: 2, explanation: "'It was minus eleven degrees at seven o'clock'." },
      { q: "Why did the father stop trying the car?", options: ["The battery was flat.","He decided to walk.","He was late already.","Trying again would make it worse."], answer: 3, explanation: "'trying again would only make it worse'." },
      { q: "What was on the windows?", options: ["Ice on the inside.","Nothing unusual.","Snow outside.","Water running down."], answer: 0, explanation: "'Every window in the house had ice on the inside'." },
      { q: "What happened at school?", options: ["Lessons finished early.","About half the students came.","It was closed for the day.","Everybody stayed in one room."], answer: 1, explanation: "'About half the students came.'" },
      { q: "What broke?", options: ["A classroom window.","The school gate.","The outside tap.","The heating boiler."], answer: 2, explanation: "'the water in the pipe to the outside tap had frozen and pushed the tap apart'." },
      { q: "What does the writer remember most?", options: ["The ice patterns.","Missing the bus.","The cold in the classrooms.","How everything sounded."], answer: 3, explanation: "'What I remember most is the sound.'" }
    ]
  },
  {
    id: "ket-rmc20-03",
    title: "My First Interview",
    text: "I had my first job interview at sixteen, for Saturday work in a garden centre. I prepared for the wrong things. I read about the company for two hours, I learned the names of the managers, and I practised answering the question about where I want to be in five years, which nobody asked. The interview lasted eleven minutes and there were three questions. The first was whether I could work every Saturday from eight until four including in December. The second was what I would do if a customer asked me something I did not know. And the third was whether I had ever looked after a plant. I answered the first one easily. For the second one I said that I would say I did not know and find somebody who did, which is apparently the right answer and which I only said because it is what I would actually do. The third one caught me completely. I said no, honestly, and then said that my grandmother had a garden and that I had helped her but had never been responsible for anything alive. The woman interviewing me wrote something down and I was sure I had failed. I got the job. In my second week I asked her about that question and she said that she does not care whether people know about plants, because that can be taught in a fortnight, and that she asks it to see whether people say yes when the answer is no.",
    questions: [
      { q: "What job was the interview for?", options: ["Saturday work at a garden centre.", "Full-time work in a shop.", "Summer work on a farm.", "Evening work in a café."], answer: 0, explanation: "'for Saturday work in a garden centre'." },
      { q: "What did the writer prepare that was not needed?", options: ["Questions about pay.", "An answer about five years' time.", "A list of plants.", "References from school."], answer: 1, explanation: "'I practised answering the question about where I want to be in five years, which nobody asked'." },
      { q: "How long was the interview?", options: ["Two hours.","Three minutes.","Eleven minutes.","Half an hour."], answer: 2, explanation: "'The interview lasted eleven minutes'." },
      { q: "What was the writer's answer about not knowing something?", options: ["To look it up on a phone.","To guess sensibly.","To ask the customer to come back later.","To say so and find somebody who knows."], answer: 3, explanation: "'I would say I did not know and find somebody who did'." },
      { q: "How did the writer answer the plant question?", options: ["Honestly, saying no.", "By describing a garden they had.", "By avoiding the question.", "By saying yes."], answer: 0, explanation: "'I said no, honestly'." },
      { q: "Why does the manager ask that question?", options: ["To find people who know about plants.", "To see whether people admit what they do not know.", "To test their memory.", "Because gardening is essential."], answer: 1, explanation: "'she asks it to see whether people say yes when the answer is no'." }
    ]
  },
  {
    id: "ket-rmc20-04",
    title: "The Library Card",
    text: "I got my first library card when I was six and I still have the same number, which surprised me when I found out. The card itself has been replaced four times. The first two were paper, then plastic, and the one I have now is plastic with a small chip in it, and each time the number stayed the same. That number has followed me through four houses and two towns. Our library is open five days a week and closed on Wednesday and Sunday. You can borrow twelve items and keep them for three weeks, and you can renew them twice unless somebody else has reserved them. There are no fines for children, which changed in 2018 and which the librarian says has made no difference to how late books come back and a large difference to how many children come in. What I use most is not books. It is the reservation system: any book in the county, about a million of them, can be sent to our small building for free, and it takes between two days and three weeks. I have ordered ninety-one books that way. The librarian, Mrs Achebe, knows my name and knows roughly what I read, and last year she started leaving a note in the front of anything she thought I might like. She is right about half the time. The books she is wrong about are frequently more interesting than the ones she is right about, which I have not told her.",
    questions: [
      { q: "What has stayed the same since the writer was six?", options: ["The card itself.", "The library building.", "The membership number.", "The librarian."], answer: 2, explanation: "'I still have the same number'." },
      { q: "When is the library closed?", options: ["Only Sunday.","At weekends.","Two afternoons a week.","Wednesday and Sunday."], answer: 3, explanation: "'closed on Wednesday and Sunday'." },
      { q: "What changed in 2018?", options: ["Children no longer pay fines.","The loan period became longer.","Reservations became free.","Opening hours were reduced."], answer: 0, explanation: "'There are no fines for children, which changed in 2018'." },
      { q: "What effect did that change have?", options: ["The library lost money.","More children come in.","Books come back later.","Fewer books are borrowed."], answer: 1, explanation: "'a large difference to how many children come in'." },
      { q: "What does the writer use most?", options: ["The reading room.","The children's section.","The reservation system.","The computers."], answer: 2, explanation: "'It is the reservation system'." },
      { q: "What does Mrs Achebe do?", options: ["Chooses all his books for him.","Orders books from other countries.","Keeps a list of his favourites.","Leaves notes about books he might like."], answer: 3, explanation: "'she started leaving a note in the front of anything she thought I might like'." }
    ]
  },
  {
    id: "ket-rmc20-05",
    title: "The Photograph on the Stairs",
    text: "There is a photograph on the wall of our stairs that I walked past for eleven years without looking at. It is black and white, it is about the size of a book, and it shows four young men standing beside a lorry. Last year I stopped and looked at it properly for the first time, because my sister asked who they were and neither of us knew. My mother told us. The man on the left is my great-grandfather, who was twenty-two when it was taken in 1951. The other three worked with him. They delivered coal in our town for a company that closed in 1974, and the lorry in the picture, which looks old in the photograph, was already fifteen years old then. What my mother said next is the part I think about. Nobody knows the names of the other three men. My great-grandfather knew them, obviously, and worked with them for years, and he died in 1998, and nobody ever wrote anything on the back of the photograph. There is a whole box of photographs in the loft in the same condition. My sister and I have started doing something about it, in a small way. We take a photograph of the family with a phone about once a month and we write, in a note on the same phone, who is in it and where and when. It takes about a minute. My mother says this is the most sensible thing either of us has ever done and that she is not going to do it herself.",
    questions: [
      { q: "Why did the writer finally look at the photograph?", options: ["Their sister asked about it.","It was moved to another room.","Their mother told them to.","It fell off the wall."], answer: 0, explanation: "'because my sister asked who they were'." },
      { q: "Who is the man on the left?", options: ["Nobody knows.","The writer's great-grandfather.","The writer's grandfather.","A family friend."], answer: 1, explanation: "'The man on the left is my great-grandfather'." },
      { q: "What did the men do?", options: ["Worked on the railway.", "Repaired lorries.", "Delivered coal.", "Built houses."], answer: 2, explanation: "'They delivered coal in our town'." },
      { q: "What is the problem with the photograph?", options: ["It is damaged.", "The date is wrong.", "It was taken in another town.", "Three of the men are unidentified."], answer: 3, explanation: "'Nobody knows the names of the other three men.'" },
      { q: "Why is nothing known about them?", options: ["Nothing was written on the back.", "The family lost the records.", "The company closed.", "Nobody asked in time."], answer: 0, explanation: "'nobody ever wrote anything on the back of the photograph'." },
      { q: "What do the writer and sister do now?", options: ["Write to the coal company.","Label a family photograph each month.","Scan the whole box in the loft.","Ask relatives about old pictures."], answer: 1, explanation: "'we write, in a note on the same phone, who is in it and where and when'." }
    ]
  },
  {
    id: "ket-rmc20-06",
    title: "The Song Everybody Knows",
    text: "There is a song that everybody at my school knows and nobody can explain. It is not on the radio. It has about eleven words in it and a tune of four notes, and it is sung at the end of every match that our school football and netball teams play, win or lose, by whoever is watching. I asked eleven people where it came from. Nobody knew. The oldest answer I got was from a teacher who has been at the school for twenty-six years and who says it was already happening when she arrived in 1999, and that she was told at the time that it came from a group of students in the early nineties. That is all anybody has. It is not written down anywhere. It is not in any school document and no teacher has ever taught it, and every single student learns it by standing next to somebody who is singing it. It changes very slowly. The teacher says that the tune is the same as it was in 1999 and that two of the words are different, and that nobody decided to change them. I find this genuinely interesting. In a school of nine hundred people where everything else is written down, timetabled and checked, there is one thing that is passed from person to person by ear, that has no owner, and that has survived at least twenty-six years without anybody being responsible for it. I have written down the words and the four notes and put the paper in a drawer, which possibly ruins the whole thing, and I did it anyway.",
    questions: [
      { q: "When is the song sung?", options: ["On the last day of term.","In assemblies.","At the end of school matches.","Only when the team wins."], answer: 2, explanation: "'it is sung at the end of every match'." },
      { q: "Where did it come from?", options: ["A song book in the music room.","The radio.","A teacher taught it.","Nobody knows."], answer: 3, explanation: "'I asked eleven people where it came from. Nobody knew.'" },
      { q: "What is the oldest information?", options: ["A teacher who heard it in 1999.","A photograph from 1990.","A note in the school office.","A recording from 1999."], answer: 0, explanation: "'a teacher who… says it was already happening when she arrived in 1999'." },
      { q: "How do students learn it?", options: ["From a video online.","By standing next to somebody singing.","From a sheet given out in Year 7.","In music lessons."], answer: 1, explanation: "'every single student learns it by standing next to somebody who is singing it'." },
      { q: "How has it changed?", options: ["It has not changed at all.","The tune has changed completely.","Two words are different.","It has become much longer."], answer: 2, explanation: "'two of the words are different'." },
      { q: "Why does the writer find it interesting?", options: ["It is very old.","The teachers dislike it.","Only some students know it.","It has no owner and is not written down."], answer: 3, explanation: "'that is passed from person to person by ear, that has no owner'." }
    ]
  },
  {
    id: "ket-rmc20-07",
    title: "Walking to School in the Dark",
    text: "In December I leave the house at ten past eight and it is not properly light until about a quarter to nine, so for six weeks of the year I walk to school in the dark. It takes twenty-two minutes. The route is the same all year: down our road, along a footpath beside the park, across one main road at a crossing, and then two streets. In summer the footpath is the nice part. In December it is the part I do not like, because there are no lights on it at all and the park on one side is completely black. For two winters I walked the long way round instead, which adds seven minutes and goes past shops and houses. Then last year my father bought me a head torch, which I thought was ridiculous and wore anyway, and the footpath became completely fine, because the problem was never really the dark. It was not being able to see the ground. My mother's rule is that I send a message when I arrive, which takes four seconds and which she says is not about not trusting me but about her own head. I understand that better than I did. Three of us walk together now, which happened by accident because we kept meeting at the same corner at the same time, and we have never arranged it and we all arrive at that corner within about a minute of each other every day. If one of us is not there by twelve minutes past, the other two wait, which we also never agreed and which has happened four times.",
    questions: [
      { q: "How long does the walk take?", options: ["Twenty-two minutes.", "Seven minutes.", "Half an hour.", "Different every day."], answer: 0, explanation: "'It takes twenty-two minutes.'" },
      { q: "Which part does the writer dislike in December?", options: ["The two streets at the end.","The footpath by the park.","The start of the walk.","The main road."], answer: 1, explanation: "'In December it is the part I do not like'." },
      { q: "What did the writer do for two winters?", options: ["Left the house later.","Walked with a friend.","Went the long way round.","Took the bus."], answer: 2, explanation: "'For two winters I walked the long way round instead'." },
      { q: "What solved the problem?", options: ["New street lights.","A different route.","Walking with three people.","A head torch."], answer: 3, explanation: "'my father bought me a head torch'." },
      { q: "What was the real problem?", options: ["Not being able to see the ground.","The cold.","The time it took.","Being alone."], answer: 0, explanation: "'It was not being able to see the ground.'" },
      { q: "How did the group of three start?", options: ["The school suggested it.","By meeting at the same corner.","They are all neighbours.","The parents arranged it."], answer: 1, explanation: "'which happened by accident because we kept meeting at the same corner'." }
    ]
  },
  {
    id: "ket-rmc20-08",
    title: "The Ice Cream Van",
    text: "An ice cream van comes to our street between four and half past four on weekdays from April until September. It plays a tune that you can hear about two minutes before it arrives, which is the whole idea, because by the time it stops there are usually about ten children waiting. The man who drives it is called Frank and he has done this round for twenty-two years. He knows the roads where he stops and he also knows where not to stop: not outside the school at home time, which is a rule he made himself and which he says is because a queue of children next to a road full of cars is a bad idea, whatever the money would be. He sells eleven things and the most popular is the simplest one. His van is not new. It was made in 1998 and he repairs most of it himself, and he told me that the freezer is the part that must never fail and that he has two, one large and one small, so that a failure is a problem rather than a disaster. Last summer he did not come for three weeks. He had a knee operation. When he came back the first afternoon there were about thirty children in our street instead of ten, which he had not expected at all, and he told my mother later that he had to sit in the van for a minute before he opened the window. He is sixty-one and he says he will do five more summers, and my mother says he has been saying five more summers since about 2015.",
    questions: [
      { q: "When does the van come?", options: ["Only at weekends.","All year round.","Between four and half past four.","At lunchtime."], answer: 2, explanation: "'between four and half past four on weekdays'." },
      { q: "Why does it play a tune?", options: ["It is required by law.","To wake people up.","Frank enjoys it.","So children are ready when it arrives."], answer: 3, explanation: "'by the time it stops there are usually about ten children waiting'." },
      { q: "Where does Frank refuse to stop?", options: ["Outside the school at home time.", "In narrow streets.", "Near the park.", "Anywhere on a main road."], answer: 0, explanation: "'not outside the school at home time'." },
      { q: "Why does he have two freezers?", options: ["The van is old.","So a failure is not a disaster.","One is for storage at home.","He sells two kinds of product."], answer: 1, explanation: "'so that a failure is a problem rather than a disaster'." },
      { q: "Why was he away for three weeks?", options: ["He was on holiday.","The weather was bad.","He had an operation.","The van broke down."], answer: 2, explanation: "'He had a knee operation.'" },
      { q: "What happened when he returned?", options: ["Nobody noticed.","He sold nothing.","He changed his route.","Three times as many children came."], answer: 3, explanation: "'there were about thirty children in our street instead of ten'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
