/* KET Prep bank: reading multiple-choice (A2) — wave 8 */
(function () {
var BANK = [
  {
    id: "ket-rmc8-01",
    title: "The Toy Sale at Our School",
    text: "Last month our school had a toy sale. The idea came from Class 5. They wanted to buy new books for the school library, and their teacher, Mr Osei, said they could try. Every child brought old toys from home. My brother brought three cars and a box of building blocks. I brought a puzzle and two games. We put everything on tables in the school hall on Friday afternoon. Nothing cost more than two pounds. The most popular table was the one with the soft toys. There were more than fifty of them, and they were all sold in the first twenty minutes. The puzzles did not sell so well. Mr Osei said that people like to see a toy's face. My puzzle was still there at the end of the afternoon, so I took it home again. Parents came to help. Two mothers made cakes and sold them at the door for fifty pence each, and one father counted all the money. We made two hundred and eleven pounds, which was more than anybody expected. The library bought sixteen new books with it. They are on a special shelf now, and inside the front of each one there is a small label that says: Bought with money from the Toy Sale, June. My favourite is a book about volcanoes. I have read it twice. Class 5 want to have another sale next June. Mr Osei says yes, but this time he wants fewer puzzles and more soft toys.",
    questions: [
      { q: "Whose idea was the toy sale?", options: ["Class 5's.","The writer's brother's.","The parents'.","Mr Osei's."], answer: 0, explanation: "'The idea came from Class 5.'" },
      { q: "Why did the school have the sale?", options: ["To help another school.","To buy books for the library.","To buy new toys for the classroom.","To pay for a school trip."], answer: 1, explanation: "'They wanted to buy new books for the school library'." },
      { q: "Which toys sold fastest?", options: ["The cars.", "The building blocks.", "The soft toys.", "The puzzles."], answer: 2, explanation: "The soft toys 'were all sold in the first twenty minutes'." },
      { q: "What happened to the writer's puzzle?", options: ["A parent bought it.", "It was given to the library.", "Mr Osei kept it.", "The writer took it home."], answer: 3, explanation: "'My puzzle was still there at the end of the afternoon, so I took it home again.'" },
      { q: "How much money did the sale make?", options: ["£211.", "£50.", "£16.", "£2."], answer: 0, explanation: "'We made two hundred and eleven pounds'." },
      { q: "What does Mr Osei want next year?", options: ["A bigger hall.","More soft toys.","Higher prices.","More parents to help."], answer: 1, explanation: "'he wants fewer puzzles and more soft toys'." }
    ]
  },
  {
    id: "ket-rmc8-02",
    title: "Ali's Saturday Job",
    text: "Ali is sixteen and he works in a café on Saturdays. He starts at eight in the morning and finishes at two in the afternoon. The café is on the corner of the market square, so Saturday is the busiest day of the week. Ali does not make the coffee. He is learning, but the machine is difficult and his boss, Rina, says he needs more practice before he can use it when the café is full. So Ali takes the plates to the tables, clears them away, and washes them. He also cuts the bread for the sandwiches, and Rina says he does that better than anybody. The hardest part of the job is remembering which table asked for what. In the beginning Ali wrote everything down, but he often could not read his own writing later. Now he says the order out loud in his head twice before he walks away from the table. It works, but he is still slower than Rina, who never writes anything down at all. Ali gets forty pounds for the day and his lunch. He is saving for a guitar. He has one hundred and sixty pounds now and the guitar costs two hundred and twenty, so he needs to work two more Saturdays. Some of his friends think that six hours is a long time to work at the weekend. Ali does not agree. He says the morning goes very fast, that he likes talking to the customers who come every week, and that he sleeps very well on Saturday night.",
    questions: [
      { q: "When does Ali finish work?", options: ["At the end of the market.","At eight in the morning.","At two in the afternoon.","At six in the evening."], answer: 2, explanation: "'He starts at eight in the morning and finishes at two in the afternoon.'" },
      { q: "Why does Ali not make the coffee?", options: ["Rina does not have time to teach him.","He does not like coffee.","The café does not sell it.","He needs more practice first."], answer: 3, explanation: "Rina 'says he needs more practice before he can use it when the café is full'." },
      { q: "What is Ali especially good at?", options: ["Cutting the bread.", "Washing the plates.", "Using the machine.", "Counting the money."], answer: 0, explanation: "'he cuts the bread for the sandwiches, and Rina says he does that better than anybody'." },
      { q: "How does Ali remember the orders now?", options: ["He asks Rina to help him.","He says them to himself twice.","He takes a photograph of the table.","He writes them in a book."], answer: 1, explanation: "'Now he says the order out loud in his head twice'." },
      { q: "What is Ali saving his money for?", options: ["A bicycle.","A computer.","A guitar.","A holiday."], answer: 2, explanation: "'He is saving for a guitar.'" },
      { q: "What does Ali say about the job?", options: ["It is too long at the weekend.","He would like more money.","He wants to work on Sundays too.","The time passes quickly."], answer: 3, explanation: "'He says the morning goes very fast'." }
    ]
  },
  {
    id: "ket-rmc8-03",
    title: "A Tent in the Garden",
    text: "Every August my sister and I sleep in a tent in our garden for one night. It started four years ago, when we were nine and eleven. Our parents said we were too young to go camping in the mountains with our cousins, and we were angry about it for a whole day. Then Dad found an old tent in the garage and said we could put it up behind the apple tree. The first year was not a success. We forgot to bring a torch, we could not find the door of the tent in the dark, and my sister went inside the house at midnight because she was cold. I stayed outside, but I did not sleep much. Now we are better at it. We put the tent up in the afternoon while it is still light. We take two torches, warm socks, a bottle of water and something to eat at eleven o'clock, which is the best part. We do not take our phones, because that was Mum's one rule, and after the first year we agreed that she was right. The strange thing about a garden at night is the noise. In the day you hear cars and people. At night you hear the tree, and birds moving, and once, last year, a fox walking very slowly past the tent. We stayed completely quiet until it had gone. In the morning we go inside at about seven and have breakfast, and everybody asks us the same question, and every year we say the same thing: it was cold, and we will do it again.",
    questions: [
      { q: "How often do the sisters sleep in the tent?", options: ["One night each August.","Whenever the weather is warm.","Every weekend in summer.","Once a month."], answer: 0, explanation: "'Every August my sister and I sleep in a tent in our garden for one night.'" },
      { q: "Why did they start doing this?", options: ["They wanted to see the fox.","They could not go camping with their cousins.","Their parents bought them a tent.","Their house was being repaired."], answer: 1, explanation: "Their parents said they were too young to go camping in the mountains with their cousins." },
      { q: "What went wrong the first year?", options: ["The tent fell down.", "It rained all night.", "They had no torch.", "The apple tree was in the way."], answer: 2, explanation: "'We forgot to bring a torch'." },
      { q: "What is their mother's rule?", options: ["They must not eat in the tent.","They have to put the tent away.","They must come in before midnight.","They cannot take their phones."], answer: 3, explanation: "'We do not take our phones, because that was Mum's one rule'." },
      { q: "What did they see last year?", options: ["A fox going past the tent.","A bird in the apple tree.","A cat from next door.","Their father with a torch."], answer: 0, explanation: "'a fox walking very slowly past the tent'." },
      { q: "What do the sisters say every year?", options: ["That they slept very well.","That it was cold and they will do it again.","That they want a bigger tent.","That next time they will go to the mountains."], answer: 1, explanation: "'it was cold, and we will do it again'." }
    ]
  },
  {
    id: "ket-rmc8-04",
    title: "Waiting in the Rain",
    text: "The number 9 bus comes at ten past four. On Tuesday it did not come at all. About fifteen of us were waiting at the stop outside the sports centre, and it began to rain hard at a quarter past. There is a roof over the bus stop, but it is small, and only six people can stand under it. A woman with a baby was at the front, and an old man with two shopping bags stood behind her. The rest of us got wet. At half past four a man in a blue coat looked at his phone and said that the bus was cancelled and that the next one was at ten past five. Nobody was happy. Two students walked away towards the town. A woman telephoned somebody and asked them to come in a car. The old man said he would wait, because the walk to his house was too long for him. Then something good happened. The sports centre manager came out and said we could all wait inside. She opened the doors and we sat in the entrance hall, which was warm and dry, and she told us she would watch for the bus and tell us when it arrived. Somebody made tea for the old man. The bus came at seven minutes past five, three minutes early, and we all went out together. I have used that bus stop for two years and I have never spoken to anybody there. On Tuesday I talked to four people, and now the old man says hello to me every week.",
    questions: [
      { q: "What time should the bus have arrived?", options: ["At half past four.","At ten past five.","At ten past four.","At a quarter past four."], answer: 2, explanation: "'The number 9 bus comes at ten past four.'" },
      { q: "What was the problem with the bus stop?", options: ["There was nowhere to sit.","It was closed on Tuesdays.","It was in the wrong place.","The roof was too small for everybody."], answer: 3, explanation: "'There is a roof over the bus stop, but it is small, and only six people can stand under it.'" },
      { q: "How did the people find out about the cancellation?", options: ["A man read it on his phone.","The sports centre manager told them.","A sign at the stop.","The bus driver told them."], answer: 0, explanation: "'a man in a blue coat looked at his phone and said that the bus was cancelled'." },
      { q: "Why did the old man stay at the stop?", options: ["He had to buy more shopping.","It was too far for him to walk home.","He was waiting for a friend.","He did not believe the news."], answer: 1, explanation: "'the walk to his house was too long for him'." },
      { q: "What did the sports centre manager do?", options: ["She drove two students into town.","She put up a bigger roof.","She let everybody wait inside.","She telephoned the bus company."], answer: 2, explanation: "'she said we could all wait inside'." },
      { q: "What has changed for the writer since Tuesday?", options: ["They walk into town instead.","They arrive earlier for the bus.","They take a different bus.","They know somebody at the stop now."], answer: 3, explanation: "'now the old man says hello to me every week'." }
    ]
  },
  {
    id: "ket-rmc8-05",
    title: "The Cat Next Door",
    text: "We do not have a cat, but there is a cat in our kitchen almost every day. Her name is Pepper and she lives at number 14, two houses away. She is grey with a white nose and she is nine years old. Pepper arrives at about eight in the morning, when my father opens the back door. She walks in, sits on the third chair, and waits. She is not waiting for food. We do not give her any, because her owner, Mrs Bell, asked us not to. Pepper is waiting for the sun to come round to the window at the back of the kitchen, which happens at about half past nine in summer. Then she moves onto the floor by the window and sleeps there until lunchtime. My mother says Pepper thinks our kitchen is warmer than Mrs Bell's, and she is probably right, because Mrs Bell's kitchen faces the other way. At first we thought Mrs Bell would be unhappy about it. My father went to tell her, and she laughed and said Pepper had done the same thing at the old family who lived here before us. So now it is normal. Mrs Bell can see our garden from her window, and when she wants Pepper to come home she stands at her gate and shakes a small box of cat food. Pepper always hears it, even in her sleep. My little brother asked last week if we could have a cat of our own. My mother said no, and then she said something I thought was very fair: we already have one, four days a week, and somebody else pays for her food.",
    questions: [
      { q: "Where does Pepper live?", options: ["At number 14.","In the garden.","With Mrs Bell's family in another town.","In the writer's house."], answer: 0, explanation: "'she lives at number 14, two houses away'." },
      { q: "Why does Pepper come into the kitchen?", options: ["She is frightened of dogs.","She wants to sit in the sun.","Mrs Bell sends her there.","She is looking for food."], answer: 1, explanation: "'Pepper is waiting for the sun to come round to the window'." },
      { q: "Why do the family not feed Pepper?", options: ["The food is too expensive.","She only eats at night.","Her owner asked them not to.","She is not hungry."], answer: 2, explanation: "'her owner, Mrs Bell, asked us not to'." },
      { q: "How did Mrs Bell react when she was told?", options: ["She came to collect the cat.","She was upset.","She asked them to shut the door.","She said it had happened before."], answer: 3, explanation: "'she laughed and said Pepper had done the same thing at the old family'." },
      { q: "How does Mrs Bell call the cat home?", options: ["She shakes a box of cat food.","She opens her back door.","She telephones the writer's mother.","She calls Pepper's name loudly."], answer: 0, explanation: "'she stands at her gate and shakes a small box of cat food'." },
      { q: "What did the writer's mother say about getting a cat?", options: ["Pepper would not like it.","They already have one for part of the week.","They can have one next year.","The house is too small."], answer: 1, explanation: "'we already have one, four days a week, and somebody else pays for her food'." }
    ]
  },
  {
    id: "ket-rmc8-06",
    title: "Making a Kite",
    text: "In April our teacher, Miss Farrow, said that each group of four would make a kite. She gave us two thin sticks, some string, a large piece of light paper and some tape. That was all. We could not buy anything else. My group was me, Josef, Amina and Ben. Josef wanted to make a kite in the shape of a fish. Amina said that a fish would be heavy and would not fly, and that we should make a simple diamond shape. They talked about it for a whole lesson and we made nothing at all that day. In the end we made the diamond. Ben was good at cutting straight lines and Amina tied the string. My job was the tail, which is more important than it looks: a kite without a tail turns round and round and comes down. We used strips of paper and made it a metre long. On Friday we went to the sports field. It was a windy day, which was lucky. Three kites did not fly. One had no tail at all and one was much too heavy — it was Class 6's fish, and everybody had told them. Our kite went up on the second try and stayed up for eleven minutes. It went so high that the string was tight and my hands hurt. The winner was a kite made by two girls in the other class. It was smaller than everybody else's and they had used almost no tape, so it weighed very little. Miss Farrow said that was the whole lesson: light is better than beautiful.",
    questions: [
      { q: "What did the students get from the teacher?", options: ["Money to buy materials.", "A finished kite to copy.", "A few simple materials only.", "A book about kites."], answer: 2, explanation: "The teacher gave sticks, string, paper and tape, and 'That was all.'" },
      { q: "Why did the group make nothing on the first day?", options: ["Miss Farrow was away.","They lost the string.","It was raining.","They could not agree on the shape."], answer: 3, explanation: "Josef and Amina 'talked about it for a whole lesson'." },
      { q: "What was the writer's job?", options: ["Making the tail.","Cutting the paper.","Tying the string.","Drawing the shape."], answer: 0, explanation: "'My job was the tail'." },
      { q: "Why did one kite not fly?", options: ["It was the wrong colour.","It was too heavy.","The wind stopped.","The string broke."], answer: 1, explanation: "'one was much too heavy — it was Class 6's fish'." },
      { q: "How long did the writer's kite stay in the air?", options: ["It did not fly.","Two minutes.","Eleven minutes.","A whole afternoon."], answer: 2, explanation: "'Our kite went up on the second try and stayed up for eleven minutes.'" },
      { q: "Why did the winning kite fly best?", options: ["It was made of cloth.","It was the biggest.","It had the longest tail.","It was very light."], answer: 3, explanation: "'they had used almost no tape, so it weighed very little'." }
    ]
  },
  {
    id: "ket-rmc8-07",
    title: "The Day I Lost My Bag",
    text: "I lost my school bag on a Wednesday in March. I know the day because we had swimming, and swimming is always on Wednesday. I had my bag on the bus in the morning. I had it at school. After swimming I walked to the shop with two friends, bought an apple, and then went home. At six o'clock my mother asked me where my bag was and I could not answer. Inside it there were my books, my homework, my house key, and my grandmother's watch. The watch was the important thing. She gave it to me in February and it does not work, but she wore it for forty years. I did not tell my mother about the watch that evening. I telephoned the shop first. The man there looked but found nothing. Then my father drove me to the swimming pool. It was closed. I did not sleep very well. On Thursday morning we went to the pool at eight o'clock and a woman at the desk took us to a small room full of coats, shoes, water bottles and three umbrellas. My bag was on the floor at the back, with everything still inside it, including the watch. I was so happy that I could not say thank you properly. The woman said that most things are found, but that people often do not come and look. She said there were two bicycles in that room and they had been there for a year. Now I have a rule: before I leave anywhere, I count. Bag, coat, key. Three things. I have not lost anything since March.",
    questions: [
      { q: "How does the writer know which day it was?", options: ["Swimming is always on Wednesday.","It was written in the homework book.","From a photograph.","Their mother told them."], answer: 0, explanation: "'swimming is always on Wednesday'." },
      { q: "What worried the writer most?", options: ["The books.","Their grandmother's watch.","The homework.","The house key."], answer: 1, explanation: "'The watch was the important thing.'" },
      { q: "Where did the writer look first?", options: ["On the bus.","At school.","At the shop.","At the swimming pool."], answer: 2, explanation: "'I telephoned the shop first.'" },
      { q: "Why did they not find the bag on Wednesday evening?", options: ["Nobody had handed it in yet.","The bus company was closed.","Their father was at work.","The swimming pool was closed."], answer: 3, explanation: "'my father drove me to the swimming pool. It was closed.'" },
      { q: "What did the woman at the pool say?", options: ["Most lost things are found but not collected.", "Bags are never returned.", "They should come back next week.", "The room is emptied every month."], answer: 0, explanation: "'most things are found, but that people often do not come and look'." },
      { q: "What does the writer do now?", options: ["Leaves the watch at home.", "Counts three things before leaving.", "Uses a smaller bag.", "Goes swimming on a different day."], answer: 1, explanation: "'Bag, coat, key. Three things.'" }
    ]
  },
  {
    id: "ket-rmc8-08",
    title: "A Visit to the Fire Station",
    text: "Last term our class visited the fire station in our town. We walked there, because it is only ten minutes from school. A firefighter called Sam met us at the door. The first thing he showed us was not the fire engine. It was a small room with a row of chairs, a kettle and a television, and he said that firefighters spend a lot of time there, waiting. He told us that his team goes out about four times a day, and that only one of those four is usually a fire. The others are car accidents, people locked out of houses, water in a building, and animals in difficult places. Last month they got a cat out of a tree, which Sam said happens much less often than people think — about twice a year. Then we saw the engine. It carries one thousand eight hundred litres of water, which sounds like a lot and is used up in about seven minutes. That surprised everybody. Sam said that is why the first thing they do at a big fire is find a hydrant in the street to connect to. We each tried on a helmet. They are heavier than they look, and the whole set of clothes weighs more than twenty kilos with the air tank. Ravi tried to walk in the boots and could not lift his feet properly. At the end a bell rang and Sam said, quickly and politely, that we had to go outside. We stood on the pavement and the engine left with its lights on. Nobody in our class said a word until it had turned the corner.",
    questions: [
      { q: "How did the class travel to the fire station?", options: ["In a fire engine.","By car.","On foot.","By bus."], answer: 2, explanation: "'We walked there, because it is only ten minutes from school.'" },
      { q: "What did Sam show the class first?", options: ["The fire engine.","The helmets.","The hydrant in the street.","The room where firefighters wait."], answer: 3, explanation: "'It was a small room with a row of chairs, a kettle and a television'." },
      { q: "How many of the team's call-outs are fires?", options: ["About one in four.","About half.","Only one a month.","All of them."], answer: 0, explanation: "'his team goes out about four times a day, and that only one of those four is usually a fire'." },
      { q: "What surprised the class about the engine?", options: ["How fast it can drive.","How quickly the water runs out.","How many people it carries.","How much it cost."], answer: 1, explanation: "The water 'is used up in about seven minutes'." },
      { q: "What problem did Ravi have?", options: ["He dropped the hose.","The helmet was too small.","He could not walk in the boots.","He could not lift the air tank."], answer: 2, explanation: "'Ravi tried to walk in the boots and could not lift his feet properly.'" },
      { q: "Why did the visit end suddenly?", options: ["The class had to catch a bus.", "It started to rain.", "Sam was called to a meeting.", "A bell rang and the team had to go."], answer: 3, explanation: "'a bell rang and Sam said, quickly and politely, that we had to go outside'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
