/* KET Prep bank: reading multiple-choice (A2) — wave 17 */
(function () {
var BANK = [
  {
    id: "ket-rmc17-01",
    title: "The Table Tennis Table",
    text: "Our youth club has one table tennis table and it is the most popular thing in the building. The club is open on Tuesday and Friday evenings from six until nine, in a hall behind the library, and about forty people come. There is a sofa, a small kitchen, a box of board games and the table. Almost everybody wants the table. For two years there were arguments about it every single evening, and the person running the club, whose name is Dev, tried three different systems. The first was a list on the wall, which people wrote their names on and then ignored. The second was fifteen minutes each, timed by Dev, which meant Dev spent the whole evening looking at a clock and shouting. The third one works and it is very simple. If you lose a game, you leave the table. Whoever is next in the queue plays the winner. That is all. It means a good player can stay at the table for a long time, which sounds unfair and does not cause any complaints, because everybody can see exactly why that person is still there. The queue is a line of people standing along the wall, and there is no list and nothing written down. Dev says the important thing about a rule is not whether it is fair in every case. It is whether everybody in the room can understand it and see it working, which the first two systems were not and this one is.",
    questions: [
      { q: "When is the youth club open?", options: ["Tuesday and Friday evenings.", "Every evening.", "Only at weekends.", "From six until nine on Fridays."], answer: 0, explanation: "'open on Tuesday and Friday evenings from six until nine'." },
      { q: "What was the problem with the list on the wall?", options: ["It was always full.","People ignored it.","It was taken down.","People wrote the wrong names."], answer: 1, explanation: "'which people wrote their names on and then ignored'." },
      { q: "Why did the timed system fail?", options: ["Nobody had a watch.","The games ended too quickly.","Dev had to watch the clock all evening.","Fifteen minutes was too long."], answer: 2, explanation: "'Dev spent the whole evening looking at a clock and shouting'." },
      { q: "What is the rule now?", options: ["The table is booked in advance.","Each player gets one game a night.","Names go in a hat.","The loser leaves the table."], answer: 3, explanation: "'If you lose a game, you leave the table.'" },
      { q: "Why does nobody complain about good players?", options: ["Everybody can see why they are still there.","They give other people a turn.","They are asked to leave after an hour.","Most people prefer the board games."], answer: 0, explanation: "'because everybody can see exactly why that person is still there'." },
      { q: "What does Dev say makes a good rule?", options: ["That it is fair in every case.", "That everybody can understand and see it.", "That an adult enforces it.", "That it is written down."], answer: 1, explanation: "'whether everybody in the room can understand it and see it working'." }
    ]
  },
  {
    id: "ket-rmc17-02",
    title: "The Day I Was Ill at School",
    text: "I was sick in a geography lesson in March, which is the worst thing that has ever happened to me and which everybody has now forgotten except me. I had felt strange since break. I did not say anything, because I did not want to make a fuss and because I thought it would pass, and this was a mistake that I would not make again. At about half past eleven I put my hand up and asked to go out, and I did not get to the door. Mr Bianchi was very good about it. He did not say anything at all in front of the class. He asked two people to take their books and move, opened a window, sent me to the office with a girl called Priya, and then, I found out later, told the class one sentence about how anybody can be ill and then carried on with the lesson. At the office they telephoned my father, who came in twenty minutes. I went home and slept for four hours and was completely fine the next day. What I was worried about was going back. I was sure that everybody would say something. Three people did, all of them kindly: one asked if I was all right, one said the same thing had happened to her brother in Year 7, and one, who I did not know well, said that Mr Bianchi had cleaned the floor himself before the caretaker came, and that this was why nobody talked about it much.",
    questions: [
      { q: "When did the writer start feeling unwell?", options: ["The night before.","At half past eleven.","Since break.","During the lesson only."], answer: 2, explanation: "'I had felt strange since break.'" },
      { q: "Why did the writer say nothing?", options: ["They did not feel very ill.","The lesson was nearly over.","They were afraid of the teacher.","They did not want to make a fuss."], answer: 3, explanation: "'because I did not want to make a fuss'." },
      { q: "What did Mr Bianchi do first?", options: ["Moved two students and opened a window.","Sent the whole class out.","Called the office immediately.","Told the class what had happened."], answer: 0, explanation: "'He asked two people to take their books and move, opened a window'." },
      { q: "Who took the writer to the office?", options: ["Nobody; they went alone.","A student called Priya.","Mr Bianchi.","The caretaker."], answer: 1, explanation: "'sent me to the office with a girl called Priya'." },
      { q: "What was the writer most worried about?", options: ["Missing the geography test.", "What their father would say.", "Returning to school.", "Being ill again."], answer: 2, explanation: "'What I was worried about was going back.'" },
      { q: "What did the third student say?", options: ["That everybody was talking about it.","That the same thing had happened to them.","That the writer should have gone home earlier.","That the teacher had cleaned up himself."], answer: 3, explanation: "'Mr Bianchi had cleaned the floor himself before the caretaker came'." }
    ]
  },
  {
    id: "ket-rmc17-03",
    title: "My Father's Recipe Book",
    text: "My father has a notebook in the kitchen drawer with about sixty recipes in it. He did not buy it and he did not copy them from anywhere. Every recipe in that book is one he has cooked at least four times, and he only writes it down after the fourth time, when he knows what he actually does rather than what he thinks he does. That is his rule and he has kept it since 2009. The book is not tidy. There are crossings out, there are notes in the margins in three colours, and about half the pages have marks on them from cooking. Page 14 has a piece of paper stuck over the top of the original recipe, because he changed it completely in 2016 and did not want to lose what was underneath. Some entries are very short. His recipe for rice is four lines and one of those lines is: do not look at it. Others are long, with a paragraph at the end saying what can go wrong, which is the part I use most. He is teaching my sister and me from the book, one recipe at a time, and we are allowed to write in it once we have cooked something four times ourselves. I have written two: a soup and a tray of vegetables. My sister has written one. My father says that when the book is full he will not start another one, because sixty recipes is more than anybody needs and he has never in his life met a person who cooks more than about twelve.",
    questions: [
      { q: "Where do the recipes come from?", options: ["The father's own cooking.","The children's school.","A family member.","Books and websites."], answer: 0, explanation: "'Every recipe in that book is one he has cooked at least four times'." },
      { q: "When does he write a recipe down?", options: ["Once a year.","After cooking it four times.","The first time he cooks it.","Whenever it works well."], answer: 1, explanation: "'he only writes it down after the fourth time'." },
      { q: "Why is there paper stuck on page 14?", options: ["The page was damaged.", "He wrote it in the wrong place.", "He changed the recipe but kept the old one.", "Somebody else wrote there."], answer: 2, explanation: "'he changed it completely in 2016 and did not want to lose what was underneath'." },
      { q: "What does his rice recipe say?", options: ["Use exactly two cups of water.", "Cook it for twenty minutes.", "Wash it three times.", "Do not look at it."], answer: 3, explanation: "'one of those lines is: do not look at it'." },
      { q: "Which part does the writer use most?", options: ["The notes about what can go wrong.", "The short recipes.", "The list of ingredients.", "The margins."], answer: 0, explanation: "'saying what can go wrong, which is the part I use most'." },
      { q: "What will happen when the book is full?", options: ["He will type it up.","He will not start another.","He will give it to the children.","He will start a new one."], answer: 1, explanation: "'he will not start another one'." }
    ]
  },
  {
    id: "ket-rmc17-04",
    title: "The Bench Our Class Made",
    text: "Last year our class made a bench for the playground. It was not a school project at first. A tree had to be cut down in November because it was diseased, and the wood was going to be taken away, and our teacher Mr Vasquez asked whether we could keep some of it. The school said yes. So we had four large pieces of oak in the corner of the playground for three months while they dried, with a plastic sheet over them. In February a man called Jim, who is a carpenter and whose daughter is in Year 8, came in on four Saturday mornings. Fourteen of us worked with him. We did not do the difficult parts. He cut the joints and he made all the decisions, and we did the sanding, which took much longer than everybody expected: about eleven hours in total for a bench that seats four people. The bench went into the playground in April, near the wall where the tree had been. There is a small metal label on the back with the year and the words: from the oak that stood here. Two things surprised me. The first is that a bench is used constantly, all day, by different people, in a way that nothing else in that playground is. The second is that I now notice benches everywhere and look at how they are made, which I never did before and which I cannot stop doing. My mother says this happens with everything you have made once yourself, and that she has not been able to look at a curtain in the same way since 1998.",
    questions: [
      { q: "Where did the wood come from?", options: ["A shop in town.", "Jim the carpenter.", "A tree cut down at the school.", "Another school."], answer: 2, explanation: "'A tree had to be cut down in November because it was diseased'." },
      { q: "Why did the wood stay outside for three months?", options: ["Nobody had time to work on it.","The school had not agreed.","It was too heavy to move.","It had to dry."], answer: 3, explanation: "'for three months while they dried'." },
      { q: "Who is Jim?", options: ["A carpenter and a parent.","The caretaker.","A man from the council.","A teacher at the school."], answer: 0, explanation: "'a carpenter and whose daughter is in Year 8'." },
      { q: "What did the students do?", options: ["Chose the wood.","The sanding.","Cut the joints.","Designed the bench."], answer: 1, explanation: "'we did the sanding'." },
      { q: "What does the label say?", options: ["The date the tree was planted.","The names of the students.","The year and 'from the oak that stood here'.","The name of the carpenter."], answer: 2, explanation: "'the year and the words: from the oak that stood here'." },
      { q: "What does the writer notice now?", options: ["Which trees are diseased.","How long jobs take.","Who sits in the playground.","How benches are made."], answer: 3, explanation: "'I now notice benches everywhere and look at how they are made'." }
    ]
  },
  {
    id: "ket-rmc17-05",
    title: "The Cold Swimming Pool",
    text: "There is an outdoor swimming pool in the next town that is open from May to September. It is not heated. The water comes from a spring, it is about sixteen degrees in June and about eighteen in August, and people either love it or leave after four minutes. I have been going since I was ten. The pool was built in 1935 and it is twenty-five metres long with grass all round it and a small building with changing rooms that have not been changed since about 1970. It costs three pounds fifty. The first minute is genuinely unpleasant and everybody who swims there knows it. The trick, which an old man told me when I was eleven, is not to stand at the side thinking about it. You get in within ten seconds of arriving at the edge, you swim four lengths without stopping, and by the fourth length you are fine and you stay fine for about twenty minutes. If you stand and think, you do not get in at all. In the summer there are about sixty people there on a hot day and eleven of them are over seventy. The oldest swimmer is a woman called Iris who is ninety-one and swims twice a week and does not talk about it. The pool nearly closed in 2015 and was saved by a group of swimmers who now run it themselves. There are two paid staff and about thirty volunteers, and the volunteers do the tickets, the cleaning and the tea, and one of them tests the water every morning at seven and writes the temperature on a small blackboard by the gate so that everybody knows before they get changed.",
    questions: [
      { q: "How is the pool heated?", options: ["It is not heated.", "By the sun only.", "By a small boiler.", "Only in June."], answer: 0, explanation: "'It is not heated.'" },
      { q: "How cold is the water in June?", options: ["Eighteen degrees.", "About sixteen degrees.", "Below ten degrees.", "It varies by day."], answer: 1, explanation: "'about sixteen degrees in June'." },
      { q: "What is the advice about getting in?", options: ["Wait until the sun is out.", "Go in slowly.", "Get in immediately and swim.", "Swim at the shallow end first."], answer: 2, explanation: "'You get in within ten seconds of arriving at the edge'." },
      { q: "What happens if you stand and think?", options: ["You get colder.", "You swim more slowly.", "Other people complain.", "You do not get in at all."], answer: 3, explanation: "'If you stand and think, you do not get in at all.'" },
      { q: "Who is Iris?", options: ["A ninety-one-year-old swimmer.", "One of the paid staff.", "The person who saved the pool.", "The writer's grandmother."], answer: 0, explanation: "'a woman called Iris who is ninety-one'." },
      { q: "Who runs the pool now?", options: ["The town council.", "A group of swimmers.", "A private company.", "Two paid managers."], answer: 1, explanation: "'saved by a group of swimmers who now run it themselves'." }
    ]
  },
  {
    id: "ket-rmc17-06",
    title: "The New Boy",
    text: "A new boy came into our class in January. His name is Tobias and he had moved from another country in December. He spoke some English, enough to understand most lessons and not enough to join a conversation at speed, which is a very different thing. For three weeks he said almost nothing. I want to be honest about what our class did, which was mostly nothing. Nobody was unkind to him. Nobody sat next to him either, and at break he stood near a wall by himself, and we all noticed and all did nothing, because somebody else would probably do it. What changed it was football, which is the most ordinary answer possible and is what actually happened. On a Wednesday somebody was one player short at lunchtime and asked him, not out of kindness but because they needed eleven, and he turned out to be very good. He did not need any English to be good at football. By February he was talking, and by Easter he was talking a lot, and in May he corrected our teacher's pronunciation of a place name in his own country, in front of everybody, which everybody thought was funny including the teacher. Tobias told me in the summer that the first three weeks were the worst weeks of his life. I asked him what would have helped. He said: anybody saying one sentence to me on the first day. He did not say a whole conversation, or an invitation, or somebody sitting with him at lunch. One sentence. I have thought about that more than about anything else that happened at school that year, and there is a new girl in our class this term.",
    questions: [
      { q: "What was Tobias's problem with English?", options: ["He refused to speak it.","He could not read it.","He could not follow fast conversation.","He understood nothing."], answer: 2, explanation: "'not enough to join a conversation at speed'." },
      { q: "What did the class do at first?", options: ["Asked the teacher to move him.","Were unkind to him.","Helped him with the lessons.","Nothing at all."], answer: 3, explanation: "'Nobody sat next to him either'." },
      { q: "Why did nobody act?", options: ["They thought somebody else would.", "They did not notice.", "They were told not to.", "They did not like him."], answer: 0, explanation: "'because somebody else would probably do it'." },
      { q: "How did things change?", options: ["He improved his English quickly.","He was asked to play football.","The teacher moved his seat.","He joined a school club."], answer: 1, explanation: "'somebody was one player short at lunchtime and asked him'." },
      { q: "Why was he asked?", options: ["The teacher suggested it.","He asked to play.","The team needed another player.","Somebody felt sorry for him."], answer: 2, explanation: "'not out of kindness but because they needed eleven'." },
      { q: "What did Tobias say would have helped?", options: ["A teacher sitting with him.","Being put in a different class.","Extra English lessons.","One sentence from anybody on day one."], answer: 3, explanation: "'anybody saying one sentence to me on the first day'." }
    ]
  },
  {
    id: "ket-rmc17-07",
    title: "The Hole in the Road",
    text: "There was a hole in the road at the end of our street for five months. It started small, about the size of a hand, in November, and by February it was as wide as a car door and about fifteen centimetres deep. Every car that went over it made a noise, and at night you could hear which cars had noticed it and which had not. Three people reported it to the council. My mother did it in December using a form on a website, which asks you to say where the hole is, how big it is and whether you can send a photograph. Two neighbours did the same thing in January. Nothing happened for a long time. Then in March a man came in a small van, looked at it for about four minutes, painted a white square round it and drove away, and everybody in our street thought that this was the repair and complained about it. It was not the repair. It was the inspection, and the white square means that a repair has been ordered, which nobody knew because nobody had told us. The road was repaired in April by three men and a lorry in about forty minutes. Afterwards my mother telephoned the council to ask why it takes five months. The answer was honest: there are more holes than money, holes are repaired in order of how dangerous they are, and a hole at the end of a quiet street is at the bottom of that list until it becomes deep enough to damage a car.",
    questions: [
      { q: "How did the hole change?", options: ["It grew from hand-sized to very wide.","It was filled and reopened.","It moved along the road.","It stayed the same size."], answer: 0, explanation: "'It started small, about the size of a hand… by February it was as wide as a car door'." },
      { q: "How did the writer's mother report it?", options: ["In person at the council office.","Using a form on a website.","By telephone.","By letter."], answer: 1, explanation: "'using a form on a website'." },
      { q: "What did the man in the van do?", options: ["Measured it and left a sign.","Closed the road.","Painted a white square round it.","Filled it with material."], answer: 2, explanation: "'painted a white square round it and drove away'." },
      { q: "What did the white square mean?", options: ["The hole would not be repaired.","The hole was dangerous.","The road would be closed.","A repair had been ordered."], answer: 3, explanation: "'the white square means that a repair has been ordered'." },
      { q: "Why were people annoyed?", options: ["They thought the painting was the repair.","The repair was poor quality.","The road was closed too long.","The men worked too slowly."], answer: 0, explanation: "'everybody in our street thought that this was the repair and complained'." },
      { q: "Why did it take five months?", options: ["Nobody had reported it properly.","Repairs are ordered by how dangerous they are.","The council had lost the report.","The weather was too cold."], answer: 1, explanation: "'holes are repaired in order of how dangerous they are'." }
    ]
  },
  {
    id: "ket-rmc17-08",
    title: "Learning to Tie Knots",
    text: "My uncle keeps a small boat and last summer he taught me four knots. I thought this would take an afternoon. It took the whole holiday, which was eleven days, and I can now tie all four in the dark, which is the test he set and which sounds unnecessary until you understand that a knot on a boat is usually tied when something has gone wrong and it is raining. The four knots each do one job. One makes a loop that will not tighten, one joins two ropes together, one ties a rope to a post so that it can be untied afterwards even when it has been pulled hard, and one shortens a rope without cutting it. My uncle refused to teach me any others. He said that people who know twenty knots use three, and that people who know four and can do them without thinking are safer than people who know twenty and have to remember which is which. The way he taught me was strange and worked. For the first three days I tied each knot ten times a day while sitting at a table, with a piece of rope, doing nothing else. Only after that did we do anything on the boat. He also made me untie them, which is a real skill and is harder than tying, and he showed me one knot that is very easy to tie and almost impossible to untie afterwards, so that I would recognise it and never use it.",
    questions: [
      { q: "How long did it take to learn?", options: ["A whole summer.","An afternoon.","Eleven days.","Three days."], answer: 2, explanation: "'It took the whole holiday, which was eleven days'." },
      { q: "What was the uncle's test?", options: ["Tying them under water.","Tying them in ten seconds.","Teaching somebody else.","Tying the knots in the dark."], answer: 3, explanation: "'I can now tie all four in the dark, which is the test he set'." },
      { q: "Why does he teach only four?", options: ["People who know four and use them are safer.","The boat is small.","The others are too difficult.","There is not enough time."], answer: 0, explanation: "'people who know four and can do them without thinking are safer'." },
      { q: "What did the writer do for the first three days?", options: ["Read about knots.","Practised at a table, ten times a day.","Watched the uncle only.","Worked on the boat."], answer: 1, explanation: "'I tied each knot ten times a day while sitting at a table'." },
      { q: "What is harder than tying a knot?", options: ["Tying it quickly.","Tying it with wet rope.","Untying it.","Choosing the right one."], answer: 2, explanation: "'he also made me untie them, which is a real skill and is harder than tying'." },
      { q: "Why did he show one extra knot?", options: ["It is used for the sail.","It is the easiest to remember.","It is the most useful.","So the writer would avoid it."], answer: 3, explanation: "'so that I would recognise it and never use it'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
