/* KET Prep bank: reading multiple-choice (A2) — wave 13 */
(function () {
var BANK = [
  {
    id: "ket-rmc13-01",
    title: "My Dad's Van",
    text: "My father is an electrician and he has a white van. It is eleven years old and it has driven two hundred and sixty thousand kilometres, which is more than six times round the world. He has had it since 2019 and he bought it from another electrician who was retiring. The van is not clean and it is not tidy, but my father knows where everything is. There are metal boxes down one side with cable in them, a shelf of small plastic drawers with screws and connectors, and a large red toolbox that I cannot lift with one hand. Once, when I was about eleven, I moved two things while I was waiting for him, and he found them in four seconds and then explained, very calmly, why I must never do it again. He said that on a job he has about a minute to find a part, that the customer is watching, and that a van you cannot find things in is a van that loses you work. In the summer holidays I go with him sometimes. Most days are not interesting. He changes sockets, he puts in lights, he checks things and writes on a form. What I like is the talking. He speaks to every customer for a few minutes about something that is not electricity, and one old man last August talked to us for twenty minutes about a ship he worked on in 1969. My father says that half his customers come back because of the work and half because somebody listened to them.",
    questions: [
      { q: "How old is the van?", options: ["Eleven years old.", "Six years old.", "It was bought new in 2019.", "The text does not say."], answer: 0, explanation: "'It is eleven years old'." },
      { q: "Who did the father buy it from?", options: ["A garage in town.", "An electrician who was stopping work.", "A friend from school.", "A company that sells old vans."], answer: 1, explanation: "'he bought it from another electrician who was retiring'." },
      { q: "What happened when the writer moved two things?", options: ["The father did not notice.", "The father was angry and shouted.", "The father noticed at once and explained why not.", "They were lost for a week."], answer: 2, explanation: "'he found them in four seconds and then explained, very calmly, why I must never do it again'." },
      { q: "Why does the order in the van matter?", options: ["The van is inspected every year.", "There is very little space.", "Other people borrow the tools.", "He must find a part quickly while a customer watches."], answer: 3, explanation: "'on a job he has about a minute to find a part, that the customer is watching'." },
      { q: "What does the writer enjoy about going with him?", options: ["The conversations with customers.", "Learning about electricity.", "Driving the van.", "Being paid for the work."], answer: 0, explanation: "'What I like is the talking.'" },
      { q: "Why do customers come back, according to the father?", options: ["The prices are low.", "Half of them because somebody listened.", "He works at weekends.", "He is the only electrician in town."], answer: 1, explanation: "'half his customers come back because of the work and half because somebody listened to them'." }
    ]
  },
  {
    id: "ket-rmc13-02",
    title: "The Cinema in Our Town",
    text: "Our town has one cinema. It has two screens, it was built in 1938, and for eight years, between 2010 and 2018, it was closed. When I was small it was a building with wood over the windows and my mother used to say that she saw her first film there in 1987. In 2016 a group of about thirty people from the town decided to try to open it again. They were not rich. They collected money for two years, from a hundred and forty people, and got some more from a national fund that helps old buildings. The work took eleven months. New seats came from a cinema in another city that was closing, and they cost almost nothing, but taking them out and bringing them here cost a lot. The cinema opened again in November 2018. It shows one film in the evening on most days and two on Saturday, and on Wednesday afternoons there is a showing for older people with the lights not completely off and the sound a little lower. The tickets are five pounds, which is less than half what the big cinema in the city charges. Everybody who works there is a volunteer except the manager. My aunt sells the tickets on Thursdays. I did four Saturdays last year, taking the money for drinks, and I saw about ten minutes of each film through the door. The cinema is now full about three times a month, which the manager says is enough.",
    questions: [
      { q: "How long was the cinema closed?", options: ["Two years.","Since 1987.","Eight years.","Eleven months."], answer: 2, explanation: "'between 2010 and 2018, it was closed'." },
      { q: "Where did the money come from?", options: ["The cinema in the city.","The town council alone.","A single rich family.","Local people and a national fund."], answer: 3, explanation: "'from a hundred and forty people, and got some more from a national fund'." },
      { q: "What was expensive about the seats?", options: ["Moving them from the other city.","Buying them.","Repairing them.","Fitting new covers."], answer: 0, explanation: "'taking them out and bringing them here cost a lot'." },
      { q: "What is special about Wednesday afternoons?", options: ["Children can come alone.","The lights stay partly on and the sound is lower.","The tickets are free.","Two films are shown."], answer: 1, explanation: "'a showing for older people with the lights not completely off and the sound a little lower'." },
      { q: "Who works at the cinema?", options: ["The people who lent the money.","Paid staff only.","Volunteers, except the manager.","Students from the school."], answer: 2, explanation: "'Everybody who works there is a volunteer except the manager.'" },
      { q: "What did the writer do there?", options: ["Chose which films to show.","Sold tickets on Thursdays.","Cleaned after each showing.","Sold drinks on four Saturdays."], answer: 3, explanation: "'I did four Saturdays last year, taking the money for drinks'." }
    ]
  },
  {
    id: "ket-rmc13-03",
    title: "Feeding the Birds in Winter",
    text: "We started feeding the birds in our garden four winters ago. My mother bought one feeder and put it on the apple tree, about two metres from the kitchen window. For six days nothing happened at all. She was ready to give up, and then on the seventh day two small birds arrived, and after that there were birds every day. We learned some things quickly. The first is that once you start in the cold months you should not stop, because the birds come to depend on the food and use energy flying to a feeder that is empty. The second is that a feeder must be cleaned. If you do not wash it every two weeks, illness spreads between the birds, and we did not know that in the first winter. The third is that the cat next door will sit under the tree if you let her, so the feeder is now on a pole in the middle of the grass with nothing near it. We put out different things. Small seeds bring the small birds. Nuts bring bigger ones, and one that comes twice a day is a green woodpecker, which my grandfather says he never saw in a garden when he was young. We do not feed bread, because we read that it fills the birds up and gives them almost nothing. In February we count for one hour and send the numbers to a national survey. Last year we counted eleven species. The year before it was nine.",
    questions: [
      { q: "What happened in the first week?", options: ["No birds came.", "Many birds came at once.", "The feeder was damaged.", "A cat took the food."], answer: 0, explanation: "'For six days nothing happened at all.'" },
      { q: "Why should you not stop feeding in winter?", options: ["The feeder gets dirty.", "The birds rely on the food.", "Other animals come instead.", "The food goes bad."], answer: 1, explanation: "'the birds come to depend on the food'." },
      { q: "What must be done every two weeks?", options: ["Move the feeder.", "Change the type of seed.", "Clean the feeder.", "Count the birds."], answer: 2, explanation: "'If you do not wash it every two weeks, illness spreads between the birds'." },
      { q: "Why is the feeder now on a pole?", options: ["The tree was cut down.", "It is easier to fill.", "The wind blew it down.", "Because of the neighbour's cat."], answer: 3, explanation: "'the cat next door will sit under the tree if you let her'." },
      { q: "Why do they not put out bread?", options: ["It has almost no food value for birds.", "It attracts too many birds.", "It makes the garden dirty.", "The survey does not allow it."], answer: 0, explanation: "'it fills the birds up and gives them almost nothing'." },
      { q: "What do they do in February?", options: ["Stop feeding until spring.", "Count birds for an hour for a survey.", "Buy a second feeder.", "Move the feeder to the front garden."], answer: 1, explanation: "'In February we count for one hour and send the numbers to a national survey.'" }
    ]
  },
  {
    id: "ket-rmc13-04",
    title: "The Lost Key",
    text: "On a Friday in October I came home from school at half past four and could not get into the house. My key was not in my bag. It was not in any pocket. I emptied the whole bag onto the step and it was not there. My parents both work until six and my brother had football until seven, so there was nobody to let me in. I did four things, in this order, and I think three of them were sensible. First I looked through the window into the kitchen, which told me nothing except that the key was not on the table. Then I walked back to school, looking at the pavement the whole way, which took twenty-five minutes and found nothing. Then I went to the school office, where a woman I did not know checked the lost property and looked in a drawer of keys, and there were eleven keys in that drawer and none of them was mine. The fourth thing was the useful one. I remembered that our neighbour Mr Adeyemi has a key for emergencies, which my mother arranged years ago and which I had completely forgotten. He was at home. I was inside by twenty past five with a cup of tea. The key turned up on Sunday. It was in the pocket of my coat, in the lining, because there was a hole in the pocket that I did not know about. My mother mended the pocket and cut me a second key, which now lives in my pencil case.",
    questions: [
      { q: "Why could nobody let the writer in?", options: ["The neighbours were out.","The door was broken.","The parents were at work and the brother at football.","The family were on holiday."], answer: 2, explanation: "'My parents both work until six and my brother had football until seven'." },
      { q: "What did the writer do first?", options: ["Telephoned their mother.","Went to Mr Adeyemi.","Went back to school.","Looked through the kitchen window."], answer: 3, explanation: "'First I looked through the window into the kitchen'." },
      { q: "What did the school office have?", options: ["A drawer with eleven keys in it.","A note about the key.","A telephone for the writer to use.","The writer's key."], answer: 0, explanation: "'there were eleven keys in that drawer and none of them was mine'." },
      { q: "How did the writer get in?", options: ["A locksmith came.","A neighbour had a spare key.","Their brother came home early.","Through an open window."], answer: 1, explanation: "'our neighbour Mr Adeyemi has a key for emergencies'." },
      { q: "Where was the key?", options: ["In the writer's bag after all.","At school.","In the lining of a coat.","On the kitchen table."], answer: 2, explanation: "'It was in the pocket of my coat, in the lining'." },
      { q: "What happened afterwards?", options: ["The locks were changed.","The coat was thrown away.","The neighbour kept the key.","The writer was given a second key."], answer: 3, explanation: "'cut me a second key, which now lives in my pencil case'." }
    ]
  },
  {
    id: "ket-rmc13-05",
    title: "The Trip That Was Cancelled",
    text: "Our class was going to Paris in April. We had been planning it since September. Everybody paid the money in four parts, we had a meeting with our parents in January, we chose our rooms, and two students who had never been out of the country got passports for the first time. Then in March the trip was cancelled. The company that organised it had a problem with the hotel, and there was no other hotel with room for thirty-two people at that price at that time of year. Our teacher, Mr Novak, told us on a Tuesday morning. He did not say much and he looked terrible. Everybody got their money back, which took six weeks and which some parents had to telephone about twice. Two people cried. I was not one of them, but I was much more disappointed than I expected to be, and it took me about a fortnight to be normal about it. In May Mr Novak did something else. He organised three days in a city in our own country: two nights, a youth hostel, a museum, a river trip and a long walk. It cost about a third of the Paris price. Twenty-nine of us went. It was not Paris and everybody knew it was not Paris, and it was, honestly, a very good three days. Two of the students on that trip were the ones who had just got their first passport, and neither of them needed it, and both of them said on the last evening that they were going to use it in the summer anyway. Mr Novak is taking a different class to Paris next April, with a different company, and eleven of us have asked him whether we can go too.",
    questions: [
      { q: "When had the class started planning the trip?", options: ["In September.", "In January.", "In March.", "In April."], answer: 0, explanation: "'We had been planning it since September.'" },
      { q: "Why was the trip cancelled?", options: ["Not enough students paid.", "A problem with the hotel.", "The teacher became ill.", "The flights were too expensive."], answer: 1, explanation: "'The company that organised it had a problem with the hotel'." },
      { q: "What happened with the money?", options: ["It was used for the second trip.", "Half of it was lost.", "Everybody got it back after six weeks.", "The school paid it back at once."], answer: 2, explanation: "'Everybody got their money back, which took six weeks'." },
      { q: "How did the writer feel?", options: ["Not very disappointed.", "Angry with Mr Novak.", "Relieved about the money.", "More disappointed than expected."], answer: 3, explanation: "'I was much more disappointed than I expected to be'." },
      { q: "What did Mr Novak arrange instead?", options: ["Three days in their own country.", "A trip to Paris in the summer.", "A day out at a museum.", "Nothing at all."], answer: 0, explanation: "'He organised three days in a city in our own country'." },
      { q: "What does the writer say about the second trip?", options: ["It was better than Paris would have been.", "It was genuinely enjoyable.", "Very few students went.", "It cost the same as Paris."], answer: 1, explanation: "'it was, honestly, a very good three days'." }
    ]
  },
  {
    id: "ket-rmc13-06",
    title: "The Old Bike I Fixed",
    text: "Somebody put a bicycle out with the rubbish at the end of our road in February. It was there for two days. On the third day I asked at the house and a woman said I could take it, and I pushed it home, because both tyres were flat and the chain had come off. It was a good bicycle once. My uncle, who repairs bikes as a hobby, looked at it and told me the frame was fine and that everything else was either cheap to fix or not important. That is how I spent most of March. I put on two new inner tubes, which cost twelve pounds and which I did wrong twice before I did it right. I cleaned the chain in a bowl of hot water and put oil on it. My uncle showed me how to adjust the brakes, which is the one part I would not do alone, because brakes matter more than anything else on a bicycle. The gears do not all work. There are eighteen and I can use eleven of them, and my uncle says the rest need a part that costs more than the whole bike is worth. I have ridden it every day since April. It is heavier than my friends' bikes and slower up hills. The best thing about it is not the bicycle. It is that when something goes wrong now, I look at it myself first, and about half the time I can put it right with the tools in a small bag under the seat.",
    questions: [
      { q: "Where did the bicycle come from?", options: ["It was bought second-hand.","It was found in a park.","It was put out with the rubbish.","The writer's uncle gave it to them."], answer: 2, explanation: "'Somebody put a bicycle out with the rubbish'." },
      { q: "What did the uncle say about it?", options: ["It needed a new chain.","It was too big for the writer.","It was not worth repairing.","The frame was good."], answer: 3, explanation: "'the frame was fine'." },
      { q: "What went wrong twice?", options: ["Fitting the inner tubes.","Fixing the gears.","Cleaning the chain.","Adjusting the brakes."], answer: 0, explanation: "'which cost twelve pounds and which I did wrong twice'." },
      { q: "Why did the uncle help with the brakes?", options: ["The parts were expensive.","Brakes are the most important part.","The writer had no tools.","It was too difficult to explain."], answer: 1, explanation: "'brakes matter more than anything else on a bicycle'." },
      { q: "What is still not right?", options: ["The seat.","The wheels.","Some of the gears.","The tyres."], answer: 2, explanation: "'There are eighteen and I can use eleven of them'." },
      { q: "What does the writer value most?", options: ["That it is faster than their friends' bikes.","That the uncle taught them to ride.","That the bicycle was free.","That they can now repair things themselves."], answer: 3, explanation: "'when something goes wrong now, I look at it myself first'." }
    ]
  },
  {
    id: "ket-rmc13-07",
    title: "A Letter to the Council",
    text: "There is a crossing near our school and for two years it did not work properly. The lights changed, but the sound that tells you it is safe to cross had stopped working, and the little box under the button that turns round did not turn. Most of us did not notice, because we look at the lights. A woman called Mrs Halim noticed, because she is blind and she uses that crossing every morning to get to the bus. She told the school and the school told us. In our citizenship lesson we wrote to the council. Twenty-eight students wrote separate letters, which our teacher said was better than one letter from a class, and we sent them in the same envelope. Nothing happened for five weeks. Then a man from the council came to the school and told us three things. First, that they had checked and we were right. Second, that the repair was already on a list but that the list is long and is ordered by how many people complain. And third, that our letters had moved it to the top of that list. The crossing was repaired in June. Mrs Halim came into an assembly in July and thanked us, and said one thing that I have not forgotten: that she had reported it herself four times in two years, and that the difference was not what was said but how many people said it. Our teacher has kept one of the letters, from a boy in our class who wrote four lines and spelled the word crossing wrong twice, and she says it is the best piece of work anybody in that room produced all year.",
    questions: [
      { q: "What was wrong with the crossing?", options: ["The sound and the turning box did not work.","The road markings had faded.","The button was broken off.","The lights did not change."], answer: 0, explanation: "The sound 'had stopped working, and the little box under the button… did not turn'." },
      { q: "Why did most people not notice?", options: ["The problem happened only at night.","They watch the lights instead.","It was repaired quickly before.","They used a different crossing."], answer: 1, explanation: "'because we look at the lights'." },
      { q: "How many students wrote?", options: ["Four.","The whole school.","Twenty-eight.","One, on behalf of the class."], answer: 2, explanation: "'Twenty-eight students wrote separate letters'." },
      { q: "Why did the teacher want separate letters?", options: ["It was quicker.", "The council asked for them.", "Each student had a different point.", "It works better than one class letter."], answer: 3, explanation: "'our teacher said was better than one letter from a class'." },
      { q: "How does the council order its repair list?", options: ["By how many people complain.", "By the age of the equipment.", "By cost.", "By the date it was reported."], answer: 0, explanation: "'the list is long and is ordered by how many people complain'." },
      { q: "What did Mrs Halim say?", options: ["That the council had ignored the school.","That the number of voices made the difference.","That the repair was not good enough.","That she had never reported it."], answer: 1, explanation: "'the difference was not what was said but how many people said it'." }
    ]
  },
  {
    id: "ket-rmc13-08",
    title: "Our New Neighbours",
    text: "The house next to ours was empty for seven months and then in September a family moved in. There are four of them: two parents, a boy of about six and a girl who is my age, fifteen. They came from another town about ninety kilometres away. For the first two weeks nobody in our family spoke to them, and I think nobody in the street did, which sounds unfriendly and is not exactly that. Everybody was waiting for somebody else. My mother said afterwards that she had thought about knocking three times and had not, because she could not decide what to say. What ended it was rain. There was a storm on a Saturday in October and their washing was on the line, and they were out. My mother took it in, and then had to knock on the door in the evening holding a basket of somebody else's clothes, which is a strange first meeting and is much easier than knocking with nothing in your hands. Now it is completely normal. The girl, whose name is Yara, walks to school with me most days. Her brother comes into our garden to see our rabbit. Her father cut our hedge in November when he was cutting his own, without asking, which my father says he would never have dared to do himself. Yara told me in January that they were worried before they moved, because they had heard that people in this town do not talk to anybody. She said it took a storm and a basket of wet washing to prove that this was not true, and that she has told the story to her cousins twice. My mother now knocks on that door about once a week, usually about nothing at all, which four months ago she could not make herself do once.",
    questions: [
      { q: "How long was the house empty?", options: ["Since September.","A year.","Seven months.","Two weeks."], answer: 2, explanation: "'The house next to ours was empty for seven months'." },
      { q: "Why did nobody speak to the new family at first?", options: ["The family were never at home.","There was a disagreement about the hedge.","They were unfriendly.","Everybody was waiting for somebody else."], answer: 3, explanation: "'Everybody was waiting for somebody else.'" },
      { q: "What stopped the writer's mother knocking earlier?", options: ["She did not know what to say.", "She was too busy.", "She had never met them.", "Her husband told her not to."], answer: 0, explanation: "'she could not decide what to say'." },
      { q: "What finally brought them together?", options: ["The children meeting at school.","Rain and washing on the line.","A problem with the hedge.","A party in the street."], answer: 1, explanation: "'their washing was on the line, and they were out'." },
      { q: "What did Yara's father do in November?", options: ["Repaired the fence.","Helped with the rabbit.","Cut the writer's hedge.","Invited the family for dinner."], answer: 2, explanation: "'Her father cut our hedge in November'." },
      { q: "What had the family heard before moving?", options: ["That the house was in poor condition.","That the school was very strict.","That the street was noisy.","That local people do not talk to anybody."], answer: 3, explanation: "'they had heard that people in this town do not talk to anybody'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
