/* KET Prep bank: reading multiple-choice (A2) — wave 15 */
(function () {
var BANK = [
  {
    id: "ket-rmc15-01",
    title: "The Sports Day I Did Not Want",
    text: "I am not good at sport. I am slow, I cannot catch, and in primary school I was always one of the last two people chosen for any team, which everybody says does not matter and which matters quite a lot when you are nine. So sports day was the worst day of the year for me, every year, from the age of six to the age of thirteen. Then in Year 9 our school changed it. Instead of races where four people run and everybody else watches, the whole year group was divided into eight teams of about thirty, and every person had to do three activities out of a list of twelve. Some were running. Some were not: there was one where you build a tower out of sticks, one where you carry water across a field in a cup with a hole in it, and one where the whole team has to get everybody over a rope. Points went to the team, not to the person. I did the tower, the water and a relay in which I was the third runner and was slower than the other three teams by a long way. Nobody said anything about it, because two minutes later my team was building a tower and I turned out to be good at that. We came fourth out of eight. What I remember is that for the first time in eight years I was tired at the end of sports day rather than embarrassed, and that I did not once wish I was somewhere else.",
    questions: [
      { q: "How did the writer feel about sports day before Year 9?", options: ["It was the worst day of the year.", "It was boring but not upsetting.", "They enjoyed watching others.", "They usually did not attend."], answer: 0, explanation: "'sports day was the worst day of the year for me, every year'." },
      { q: "What changed in Year 9?", options: ["The school stopped having sports day.", "Everybody took part in team activities.", "Only good athletes took part.", "It moved to the summer."], answer: 1, explanation: "'the whole year group was divided into eight teams'." },
      { q: "How many activities did each person do?", options: ["One.", "Twelve.", "Three.", "As many as they wanted."], answer: 2, explanation: "'every person had to do three activities out of a list of twelve'." },
      { q: "Who got the points?", options: ["The fastest runner.", "The team captain.", "Each individual.", "The team."], answer: 3, explanation: "'Points went to the team, not to the person.'" },
      { q: "What was the writer good at?", options: ["Building the tower.", "The relay.", "Carrying the water.", "Nothing at all."], answer: 0, explanation: "'my team was building a tower and I turned out to be good at that'." },
      { q: "How did the writer feel at the end?", options: ["Embarrassed as usual.", "Tired rather than embarrassed.", "Disappointed with fourth place.", "Angry about the relay."], answer: 1, explanation: "'I was tired at the end of sports day rather than embarrassed'." }
    ]
  },
  {
    id: "ket-rmc15-02",
    title: "The Coat That Was Too Small",
    text: "In October my mother said that my winter coat was too small. I said it was fine. It was not fine: the sleeves finished about three centimetres above my wrists and I could not do it up over a jumper. I had grown eleven centimetres in a year and I had not really noticed, because you do not see yourself change. The problem was that the coat was two years old and had cost a lot of money, and my mother had said at the time that it would last three winters. She was annoyed, not with me, and I understood that. We went to two shops in town. Everything I liked was expensive and everything that was not expensive was thin. In the second shop a woman who worked there heard my mother talking about the price and said something useful: that the shop takes coats back in March, cleans them and sells them again in October at half price, and that if we came back on the first Saturday of that month there would be about forty of them. We waited. On the first Saturday in November we went back at nine in the morning and there were about thirty coats on two rails at the back of the shop. Mine cost thirty-four pounds instead of eighty-five. It is dark blue and it is a size too big, deliberately, and it has a small mark on one pocket that you cannot see unless somebody tells you about it. It is the warmest thing I have ever owned.",
    questions: [
      { q: "How did the writer know the coat was too small?", options: ["A friend told them.", "It was two years old.", "The sleeves were short and it would not do up.", "It was damaged."], answer: 2, explanation: "'the sleeves finished about three centimetres above my wrists'." },
      { q: "Why had the writer not noticed?", options: ["The coat had stretched.","They had a second coat.","They did not wear it often.","You do not see yourself change."], answer: 3, explanation: "'because you do not see yourself change'." },
      { q: "Why was the mother annoyed?", options: ["The coat was expected to last three winters.", "The writer had damaged the coat.", "The shops were closed.", "The writer refused to try coats on."], answer: 0, explanation: "'my mother had said at the time that it would last three winters'." },
      { q: "What did the shop assistant explain?", options: ["That they could order a bigger size.","That returned coats are resold cheaply in October.","That a sale starts in December.","That thin coats are warmer than they look."], answer: 1, explanation: "'the shop takes coats back in March, cleans them and sells them again in October at half price'." },
      { q: "How much did the coat cost?", options: ["Half of thirty pounds.","Nothing, it was a gift.","Thirty-four pounds.","Eighty-five pounds."], answer: 2, explanation: "'Mine cost thirty-four pounds instead of eighty-five.'" },
      { q: "Why is the coat a size too big?", options: ["The writer measured wrongly.","The mother preferred it.","It was the only size left.","It was chosen that way on purpose."], answer: 3, explanation: "'it is a size too big, deliberately'." }
    ]
  },
  {
    id: "ket-rmc15-03",
    title: "My First Time in Hospital",
    text: "I broke my arm in February. I fell off a wall that I should not have been on, in the park, at about four in the afternoon, and my friend Dara ran to get an adult while I sat on the grass and did not move. I was thirteen. The ambulance came in about twenty minutes and the two people in it were extremely calm, which made me calm, and one of them explained everything before he did it: I am going to hold your arm here, this will hurt for two seconds, tell me if you feel sick. At the hospital I waited for an hour and forty minutes, which felt much longer, and then had an X-ray. The X-ray took four minutes and did not hurt at all. A doctor showed me the picture on a screen and pointed at the break with a pen, and it was strange to look at a photograph of the inside of my own arm. I had a plaster cast for six weeks. Things I could not do: swim, carry anything heavy, write properly, or wash my own hair. Things I did not expect: how much it itched, and how heavy the cast was at night. Thirty-one people wrote on it, including my grandmother, who wrote something in a language I cannot read and would not tell me what it said. When they cut the cast off with a small saw I was frightened for about ten seconds and then it was over, and my arm underneath was thin and pale and completely fine.",
    questions: [
      { q: "How did the writer break their arm?", options: ["Falling off a wall.","In a car.","At school.","Playing football."], answer: 0, explanation: "'I fell off a wall that I should not have been on'." },
      { q: "What did the ambulance staff do?", options: ["Telephoned the writer's parents first.","Explained everything before doing it.","Asked Dara what had happened.","Took the writer straight to the X-ray room."], answer: 1, explanation: "'one of them explained everything before he did it'." },
      { q: "How long did the writer wait at the hospital?", options: ["Twenty minutes.","Six weeks.","About an hour and forty minutes.","Four minutes."], answer: 2, explanation: "'I waited for an hour and forty minutes'." },
      { q: "What did the writer find strange?", options: ["That the X-ray hurt.","That nobody explained the X-ray.","How quickly the doctor worked.","Seeing inside their own arm."], answer: 3, explanation: "'it was strange to look at a photograph of the inside of my own arm'." },
      { q: "What did the writer not expect?", options: ["How much it would itch.","How long they would wait.","That they could not swim.","That the cast would be white."], answer: 0, explanation: "'how much it itched, and how heavy the cast was at night'." },
      { q: "What did the grandmother do?", options: ["Refused to sign the cast.","Wrote something the writer could not read.","Visited every day.","Signed her name in English."], answer: 1, explanation: "'who wrote something in a language I cannot read'." }
    ]
  },
  {
    id: "ket-rmc15-04",
    title: "Learning to Take Photographs",
    text: "My aunt gave me an old camera two years ago. It is not digital. You put a film in it, you get thirty-six photographs, and you cannot see any of them until the film is finished and developed, which costs about eleven pounds and takes a week. I thought this would be annoying. It is the whole point. With a phone I take about four hundred photographs a month and look at almost none of them. With this camera I have thirty-six, so I think before each one, and I have got much better because of that rather than because anybody taught me anything. My aunt did tell me three things at the beginning. Stand still. Take the photograph of the person, not of the place with the person in it. And if you are not sure, get closer. The third one is the hardest and is the one that has improved my pictures most. My first film was terrible. Eleven photographs were too dark, four had my own finger in the corner, and one, by accident, is the best photograph I have ever taken: my brother at a bus stop, not looking at the camera, in the rain. My tenth film was much better and about half of it was fine. I have a box now with about two hundred prints in it, sorted by the month they were taken, with the date written on the back of each one in pencil. It is the only thing I own that will still exist in fifty years if nobody throws it away, and my aunt says that is exactly why she gave me the camera and not a better phone.",
    questions: [
      { q: "What kind of camera is it?", options: ["A very expensive new one.","A modern digital one.","A camera that uses film.","A camera on a phone."], answer: 2, explanation: "'It is not digital. You put a film in it'." },
      { q: "Why does the writer think carefully about each photo?", options: ["The camera is slow.","Their aunt checks them.","Film is difficult to load.","There are only thirty-six."], answer: 3, explanation: "'With this camera I have thirty-six, so I think before each one'." },
      { q: "Which piece of advice helped most?", options: ["Get closer if unsure.","Stand still.","Photograph the person, not the place.","Use the camera every day."], answer: 0, explanation: "'The third one is the hardest and is the one that has improved my pictures most.'" },
      { q: "What was wrong with the first film?", options: ["Nothing came out at all.","Most pictures were too dark or spoiled.","The film was damaged in the post.","The camera was broken."], answer: 1, explanation: "'Eleven photographs were too dark, four had my own finger in the corner'." },
      { q: "What is the best photograph the writer has taken?", options: ["One of their aunt.", "One taken on the tenth film.", "An accidental one of their brother.", "One taken with a phone."], answer: 2, explanation: "'one, by accident, is the best photograph I have ever taken'." },
      { q: "Why does the writer value the box of prints?", options: ["It cost a lot of money.","It contains four hundred pictures.","Their aunt made it.","It could still exist in fifty years."], answer: 3, explanation: "'it is the only thing I own that will still exist in fifty years'." }
    ]
  },
  {
    id: "ket-rmc15-05",
    title: "The Money Box",
    text: "When I was eight my grandfather gave me a metal money box shaped like a post box. It has a slot at the top and no key, and the only way to open it is to turn it upside down and shake coins out through the slot, one at a time, which takes a very long time. He did that on purpose. He told me that a money box you can open easily is not a money box, it is a pocket. For about three years I put money in it: birthday money, coins I found, and what was left of my pocket money at the end of a week, which was usually nothing. I opened it twice in that time and both times it took about forty minutes and I put most of it back. When I was eleven I decided I wanted a bicycle and my parents said they would pay half. I spent an evening on the floor of my bedroom shaking that money box, with the television off, and I counted eighty-six pounds and forty pence, most of it in ten and twenty pence coins. It was more than I expected by about thirty pounds. I bought the bicycle with my half. I am eighteen now and the money box is still on the shelf and there is money in it, although I do not put much in these days. My grandfather died three years ago. The box is the only thing of his that I have, and it is heavy, and I have not shaken it since.",
    questions: [
      { q: "Why is the money box hard to open?", options: ["You must shake coins out one at a time.","It can only be opened by an adult.","It has a lock and no key.","It is glued shut."], answer: 0, explanation: "'the only way to open it is to turn it upside down and shake coins out'." },
      { q: "Why did the grandfather choose that kind?", options: ["It was a family tradition.","An easy money box is just a pocket.","It was the cheapest.","It looked like a post box."], answer: 1, explanation: "'a money box you can open easily is not a money box, it is a pocket'." },
      { q: "What did the writer put in it?", options: ["Notes rather than coins.","Money from a job.","Birthday money, found coins and leftover pocket money.","Only birthday money."], answer: 2, explanation: "'birthday money, coins I found, and what was left of my pocket money'." },
      { q: "How much was in it at eleven?", options: ["Thirty pounds.","Half the price of a bicycle.","Forty pounds.","Just over eighty-six pounds."], answer: 3, explanation: "'I counted eighty-six pounds and forty pence'." },
      { q: "How did the amount compare with expectations?", options: ["About thirty pounds more than expected.","Exactly what was expected.","The writer had no idea.","It was less than expected."], answer: 0, explanation: "'It was more than I expected by about thirty pounds.'" },
      { q: "Why has the writer not opened it recently?", options: ["They have no need for money.","It is the only thing they have of their grandfather.","It is empty.","It has been lost."], answer: 1, explanation: "'The box is the only thing of his that I have… I have not shaken it since.'" }
    ]
  },
  {
    id: "ket-rmc15-06",
    title: "The Model Aeroplane",
    text: "My father and I built a model aeroplane over one winter. It came in a box with about two hundred pieces of wood, a plan, and no instructions except the plan itself, which was a large sheet of paper printed with the shape of every part at its real size. You put the paper flat on a board, cover it with plastic, and build the wing directly on top of the drawing, which is a very old way of doing it and is much easier to understand than a book of instructions. We worked on Sunday afternoons from November to March. The wing took nine weeks. It is made of about forty small pieces of wood glued together, and if one of them is one millimetre out of place, the wing is not straight, and a wing that is not straight makes an aeroplane that turns to one side and cannot be corrected. We built it twice. The first one broke when I picked it up wrongly in January and I was very upset, and my father was extremely calm and said that we now knew how to do it and it would take five weeks rather than nine. It took four. The aeroplane flew for the first time in April, from a field behind the sports centre, and stayed up for one minute and forty seconds. My father did not fly it. He gave me the controls and stood behind me and said nothing at all until it was on the ground.",
    questions: [
      { q: "What came in the box?", options: ["Two hundred metal pieces.","A finished wing.","Wood, a plan and no written instructions.","Instructions in four languages."], answer: 2, explanation: "'about two hundred pieces of wood, a plan, and no instructions except the plan itself'." },
      { q: "How is the wing built?", options: ["Inside a special frame.","From the middle outwards.","By machine.","Directly on top of the drawing."], answer: 3, explanation: "'build the wing directly on top of the drawing'." },
      { q: "Why must the pieces be exact?", options: ["A crooked wing cannot be corrected in flight.","The plan will not fit.","The glue does not hold otherwise.","Otherwise the wing is too heavy."], answer: 0, explanation: "'a wing that is not straight makes an aeroplane that turns to one side'." },
      { q: "What happened in January?", options: ["The father stopped helping.","The first wing was broken.","The plan was lost.","They ran out of wood."], answer: 1, explanation: "'The first one broke when I picked it up wrongly in January'." },
      { q: "How long did the second wing take?", options: ["Five weeks.","One winter.","Four weeks.","Nine weeks."], answer: 2, explanation: "'It took four.'" },
      { q: "What did the father do on the first flight?", options: ["Flew it himself.","Filmed it.","Stayed at home.","Let the writer fly it."], answer: 3, explanation: "'He gave me the controls and stood behind me'." }
    ]
  },
  {
    id: "ket-rmc15-07",
    title: "The Journey to My Grandmother's",
    text: "My grandmother lives two hundred and forty kilometres away and we go four times a year. The journey takes about three and a half hours by car and about five by train, and we have done both. By car it is cheaper for four people and my father does all the driving, which he says he does not mind and which I think he does mind by the last hour. By train it costs a lot more, but nobody has to concentrate, and we play cards on the table between the seats, and there is a fifteen-minute change at a big station where we always buy the same terrible sandwiches. Two years ago we started going by train more often, for a reason that is not about the journey at all: my grandmother is eighty-four and my father wants to arrive able to talk to her rather than tired. The last hour of the train journey is the best part. The line runs beside a river and then through a tunnel and then, straight after the tunnel, there is a view of the whole valley with her town at the bottom of it. My sister and I have watched for that tunnel since we were small. We stayed for five days at Easter. My grandmother cooked twice, we cooked twice, and one evening we ate food we bought at the shop on the corner because everybody was tired and nobody minded. On the way home my father slept on the train, which he could not have done in a car.",
    questions: [
      { q: "How far away does the grandmother live?", options: ["240 kilometres.", "Three and a half hours by train.", "Five hours by car.", "In the next town."], answer: 0, explanation: "'My grandmother lives two hundred and forty kilometres away'." },
      { q: "What is an advantage of the car?", options: ["It is faster than the train.", "It is cheaper for four people.", "Nobody has to concentrate.", "There is a place to play cards."], answer: 1, explanation: "'By car it is cheaper for four people'." },
      { q: "Why did the family start using the train more?", options: ["The car broke down.", "Train tickets became cheaper.", "So the father arrives less tired.", "The road was closed."], answer: 2, explanation: "'my father wants to arrive able to talk to her rather than tired'." },
      { q: "What do they always buy at the change?", options: ["Newspapers.", "Tickets for the next journey.", "Presents for the grandmother.", "The same poor sandwiches."], answer: 3, explanation: "'we always buy the same terrible sandwiches'." },
      { q: "What do the children watch for?", options: ["The tunnel before the valley view.", "The river bridge.", "The name of the station.", "The end of the line."], answer: 0, explanation: "'My sister and I have watched for that tunnel since we were small.'" },
      { q: "What happened on the way home?", options: ["They travelled by car instead.","The father slept.","They missed the connection.","They played cards for five hours."], answer: 1, explanation: "'my father slept on the train, which he could not have done in a car'." }
    ]
  },
  {
    id: "ket-rmc15-08",
    title: "The Clock That Was Always Wrong",
    text: "There is a clock on the tower of the church in our village and for eleven years it was four minutes slow. Everybody knew. If you asked anybody in the village what time it was and they looked at the church, they took the answer and added four minutes without thinking about it. Visitors did not know, which caused a small number of problems, mostly for people waiting for the bus at the stop opposite. The clock is from 1897 and it is wound by hand once a week. A man called Mr Ferris did that job for thirty-one years, climbing sixty-eight steps every Sunday, and he retired in 2021 at the age of eighty. He had known about the four minutes for a long time and had decided not to do anything about it, because correcting it meant taking a part out and sending it away, and the clock would then be silent for perhaps two months, and he did not want to be the person who stopped the church clock. When he retired, two younger people took over the winding, sharing it. In 2023 they had the clock repaired properly. It cost nine thousand pounds, which came from a fund for old buildings and from the village, and the clock was silent from January to April. It has been right ever since. My father says he still adds four minutes and then takes them off again, every single time, and that he expects to do this for the rest of his life.",
    questions: [
      { q: "How wrong was the clock?", options: ["An hour out in winter.","It had stopped completely.","Four minutes slow.","Four minutes fast."], answer: 2, explanation: "'for eleven years it was four minutes slow'." },
      { q: "Who had problems because of it?", options: ["The church.","Nobody at all.","The people who wound it.","Visitors, especially at the bus stop."], answer: 3, explanation: "'Visitors did not know, which caused a small number of problems'." },
      { q: "How is the clock wound?", options: ["By hand, once a week.","It winds itself.","By electricity.","Once a month by a company."], answer: 0, explanation: "'it is wound by hand once a week'." },
      { q: "Why did Mr Ferris not have it corrected?", options: ["Nobody would pay for it.","The clock would have been silent for weeks.","It was too expensive.","He did not believe it was wrong."], answer: 1, explanation: "'the clock would then be silent for perhaps two months'." },
      { q: "Where did the repair money come from?", options: ["Mr Ferris.","The bus company.","A fund for old buildings and the village.","The council alone."], answer: 2, explanation: "'which came from a fund for old buildings and from the village'." },
      { q: "What does the writer's father still do?", options: ["Refuses to look at the clock.","Winds the clock on Sundays.","Checks the time on his phone instead.","Adds four minutes and takes them off again."], answer: 3, explanation: "'he still adds four minutes and then takes them off again, every single time'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
