/* KET Prep bank: reading multiple-choice (A2) — wave 14 */
(function () {
var BANK = [
  {
    id: "ket-rmc14-01",
    title: "The Fish and Chip Shop",
    text: "There is a fish and chip shop on the corner of Bridge Street that has been open since 1961. The same family has had it the whole time. The woman who runs it now is called Sandra and her grandfather opened it, and there is a black and white photograph on the wall of him standing outside on the first day in a white coat. The shop opens at five o'clock in the afternoon and closes at nine, and it does not open at lunchtime and never has. On Friday there is a queue outside from about half past five. It goes past the next two shops and people wait for twenty minutes, sometimes in the rain, and nobody seems to mind. Sandra says Friday is more than half of the week's business. The shop has changed very little. The counter is the same. The prices are on a board with letters that are put up by hand, and Sandra changes them about twice a year, which she does not enjoy. Two things have changed. There is a card machine now, which arrived in 2019 and which her father said would never be needed. And the shop now sells one thing that is not fried at all: a box of salad, which sells about four a night and which Sandra keeps because her daughter asked her to. Last year a company offered to buy the shop. Sandra said no. She told the local newspaper that she is fifty-eight, that she will do it for another ten years, and that after that it depends on whether anybody in the family wants it.",
    questions: [
      { q: "Who opened the shop?", options: ["Sandra's grandfather.", "Sandra's father.", "Sandra herself.", "A company."], answer: 0, explanation: "'her grandfather opened it'." },
      { q: "When is the shop open?", options: ["From lunchtime until nine.", "From five until nine in the evening.", "All day on Friday only.", "From five in the morning."], answer: 1, explanation: "'The shop opens at five o'clock in the afternoon and closes at nine'." },
      { q: "What is special about Friday?", options: ["The prices are lower.", "The shop opens earlier.", "It is more than half the week's business.", "Sandra's family help her."], answer: 2, explanation: "'Sandra says Friday is more than half of the week's business.'" },
      { q: "How are the prices displayed?", options: ["On a screen.", "On paper in the window.", "They are not displayed.", "On a board with letters put up by hand."], answer: 3, explanation: "'The prices are on a board with letters that are put up by hand'." },
      { q: "Why does the shop sell salad?", options: ["Sandra's daughter asked for it.", "It sells very well.", "A customer complained.", "The council required it."], answer: 0, explanation: "'which Sandra keeps because her daughter asked her to'." },
      { q: "What did Sandra do last year?", options: ["She sold the shop.", "She refused an offer to buy it.", "She opened at lunchtime.", "She retired."], answer: 1, explanation: "'a company offered to buy the shop. Sandra said no.'" }
    ]
  },
  {
    id: "ket-rmc14-02",
    title: "My Newspaper Round",
    text: "I deliver newspapers six mornings a week. I start at ten to seven and I finish at about twenty past, and I do fifty-one houses on three streets. I get twenty-two pounds a week. I have been doing it for fourteen months. Getting up is the hardest part and it is hardest in November, when it is dark at seven and cold and often wet. In June it is light and warm and the whole thing is almost pleasant. The bag is heavy on Thursday and Saturday because the papers have extra parts inside them, and on those days I do the heavy street first, which I worked out after about two months. There are things about this job that nobody tells you. Number 14 has a dog that pushes the paper back out of the letterbox and I have learned to fold it and push it hard so that it falls inside. Number 31 has a very stiff letterbox with a metal edge and I cut my finger on it in my first week, so now I use the side of my hand. Three houses want the paper left in a plastic box by the door instead. Two of my customers are always awake and one of them, an old man at number 8, opens the door and says good morning every single day. I have thought about stopping twice, both times in winter. What has kept me going is the money, which goes into an account I do not touch, and the fact that by half past seven, when other people are getting up, my day already has something finished in it.",
    questions: [
      { q: "How long does the round take?", options: ["Ten minutes.","It varies by day.","About half an hour.","Two hours."], answer: 2, explanation: "'I start at ten to seven and I finish at about twenty past'." },
      { q: "Why is the bag heavier on some days?", options: ["The writer carries two bags.","The papers are wet.","More houses order papers.","The papers have extra parts inside."], answer: 3, explanation: "'the papers have extra parts inside them'." },
      { q: "What did the writer work out after two months?", options: ["To do the heavy street first.","To start ten minutes earlier.","A shorter route.","How to fold the papers."], answer: 0, explanation: "'on those days I do the heavy street first'." },
      { q: "What is the problem at number 31?", options: ["The customer complains.","The letterbox is stiff and sharp.","A dog pushes the paper out.","The gate is locked."], answer: 1, explanation: "'a very stiff letterbox with a metal edge'." },
      { q: "What does the man at number 8 do?", options: ["Takes the paper from the box.","Complains about the time.","Says good morning every day.","Leaves money for the writer."], answer: 2, explanation: "'opens the door and says good morning every single day'." },
      { q: "Why has the writer continued?", options: ["Their parents insist.","They want to meet the customers.","The work is easy in winter.","The money and the finished feeling."], answer: 3, explanation: "'What has kept me going is the money… and the fact that by half past seven… my day already has something finished in it.'" }
    ]
  },
  {
    id: "ket-rmc14-03",
    title: "The Charity Run",
    text: "In May our school had a charity run round the sports field. Every student in Years 7 to 11 took part, which is about six hundred people, and it happened over one afternoon in groups of a hundred. The distance was two and a half kilometres, which is six times round the field. Students asked their families to give money, either a fixed amount or an amount for each lap. The money went to a hospital in our town that treats children, and the school had chosen it because a student in Year 9 spent three months there in the year before. That student, whose name is Leo, started the run with a whistle. Not everybody ran. The rule was that you had to complete the distance, and walking was fine, and about a third of the school walked most of it. Two teachers ran with the slowest group and finished last, deliberately, so that nobody was at the back on their own. It rained for the third group, which was mine, and the field was heavy afterwards. The total was four thousand and eighty pounds. The hospital sent two nurses to an assembly in June to say thank you, and one of them explained exactly what the money would buy, which the head teacher said afterwards was the most important part of the whole thing. It bought equipment for a room where children wait, so that waiting is less frightening. Leo, who is in Year 10 now, has already asked whether we can do it again next May.",
    questions: [
      { q: "How far was the run?", options: ["Two and a half kilometres.", "Six kilometres.", "One lap of the field.", "It was different for each year."], answer: 0, explanation: "'The distance was two and a half kilometres'." },
      { q: "Why was that hospital chosen?", options: ["It is the nearest to the school.", "A student had been treated there.", "The head teacher works there.", "It asked the school for help."], answer: 1, explanation: "'a student in Year 9 spent three months there in the year before'." },
      { q: "What was the rule?", options: ["Everybody had to run the whole way.", "Only Years 10 and 11 had to take part.", "You had to complete it, and walking was allowed.", "You had to raise at least ten pounds."], answer: 2, explanation: "'you had to complete the distance, and walking was fine'." },
      { q: "Why did two teachers finish last?", options: ["They started late.", "They were injured.", "They were counting the students.", "So that nobody was alone at the back."], answer: 3, explanation: "'so that nobody was at the back on their own'." },
      { q: "How much money was raised?", options: ["£4,080.", "£600.", "£1,000.", "The text does not say."], answer: 0, explanation: "'The total was four thousand and eighty pounds.'" },
      { q: "What did the head teacher think was most important?", options: ["The nurses' visit.","Explaining what the money would buy.","The amount raised.","That everybody took part."], answer: 1, explanation: "'one of them explained exactly what the money would buy, which the head teacher said afterwards was the most important part'." }
    ]
  },
  {
    id: "ket-rmc14-04",
    title: "The Day the Water Went Off",
    text: "On a Tuesday in July the water went off in our street at nine in the morning and did not come back until seven in the evening. A pipe had broken under the main road, and the water company put a sign up and started digging at eight. Nobody in our house had thought about water before that day. You do not think about it. You turn the tap and it is there, and when it is not there you discover, in the first hour, how many things you do that need it. We could not wash anything. We could not fill the kettle. We could not flush the toilet, which is the thing everybody discovers at about half past nine. My mother filled the kettle and two large bottles at eight, because a neighbour telephoned to warn her, and that was the difference between a difficult day and a very difficult day. At eleven the water company brought bottles of water and put them at the end of the street on a small trailer. Six bottles per house. My brother and I carried ours home, and they were heavier than we expected, and we made two trips. In the afternoon I went to my friend's house in the next street, where everything was completely normal, and it felt strange. The water came back at seven. It was brown for about ten minutes, which we had been told to expect, and then it was clear. I filled a glass and drank it and thought about it properly for the first time in my life.",
    questions: [
      { q: "How long was the water off?", options: ["The whole day and night.","Until the following morning.","About ten hours.","Two hours."], answer: 2, explanation: "The water went off at nine and returned at seven in the evening." },
      { q: "What caused the problem?", options: ["Very hot weather.","A fire in the street.","Work at the water company.","A broken pipe under the main road."], answer: 3, explanation: "'A pipe had broken under the main road'." },
      { q: "Why did the family have some water ready?", options: ["A neighbour telephoned to warn them.","The mother heard the digging.","They always keep bottles.","The company sent a message."], answer: 0, explanation: "'a neighbour telephoned to warn her'." },
      { q: "How was water supplied to the street?", options: ["People collected it from the school.","Bottles on a trailer, six per house.","A tap at the end of the road.","The company delivered to each door."], answer: 1, explanation: "'Six bottles per house.'" },
      { q: "What did the writer find strange?", options: ["That nobody complained.","That the work took so long.","That the next street was normal.","That the water was brown."], answer: 2, explanation: "'where everything was completely normal, and it felt strange'." },
      { q: "What had they been warned about?", options: ["That the bill would be higher.","That the road would stay closed.","A second day without water.","That the water would look brown at first."], answer: 3, explanation: "'It was brown for about ten minutes, which we had been told to expect'." }
    ]
  },
  {
    id: "ket-rmc14-05",
    title: "The Book I Read Three Times",
    text: "I do not read very much. I read what we have to read for school and I finish about half of it, and I have never been the kind of person who has a book in a bag. Then last year my cousin gave me a book for my birthday. It is about a boy who works on a fishing boat with his uncle, and it is not a long book, and I read it in four days, which for me is extremely fast. Then in August I read it again. That was strange, because I already knew what happened, and I noticed things I had not noticed the first time: that the uncle almost never says anything directly, and that the weather in the story is always doing what the boy is feeling. I read it a third time in the winter, and by then I could open it anywhere and know where I was. My English teacher asked me in January what I was reading and I told her, and I expected her to say that I should read something else. She did not. She said that reading one book three times is worth more than reading three books once, and she asked me to say something about it to the class, which I did not want to do and did. I have read four other books since then and none of them has done the same thing. My cousin says that is normal and that she has one book like that too, and that she reads it every couple of years and always in the same chair.",
    questions: [
      { q: "How much did the writer read before?", options: ["Very little.", "A book every week.", "Only newspapers.", "Everything set at school."], answer: 0, explanation: "'I do not read very much.'" },
      { q: "Where did the book come from?", options: ["The school library.", "A present from a cousin.", "A shop in town.", "The English teacher."], answer: 1, explanation: "'my cousin gave me a book for my birthday'." },
      { q: "What did the writer notice the second time?", options: ["The ending was different from what they remembered.", "It was shorter than they thought.", "The uncle rarely says anything directly.", "There were mistakes in the text."], answer: 2, explanation: "'the uncle almost never says anything directly'." },
      { q: "What did the writer expect the teacher to say?", options: ["That the book was too easy.", "That they should write about it.", "That she had read it too.", "That they should read something different."], answer: 3, explanation: "'I expected her to say that I should read something else'." },
      { q: "What did the teacher actually say?", options: ["Rereading one book is worth more than reading three once.", "The book was a good choice for the class.", "They should try the author's other books.", "Reading three times is unusual."], answer: 0, explanation: "'reading one book three times is worth more than reading three books once'." },
      { q: "What does the cousin say?", options: ["The writer should keep the book safe.", "She has a book like that as well.", "She has never read it herself.", "The writer will grow out of it."], answer: 1, explanation: "'she has one book like that too'." }
    ]
  },
  {
    id: "ket-rmc14-06",
    title: "The Wasps' Nest",
    text: "In July we found a wasps' nest in the roof of our shed. My brother found it, because he opened the shed door and about six wasps came out at once and one of them stung him on the arm. He is not allergic, which we already knew, and it hurt for an hour and was fine the next day. We did not go into the shed for four days. My father looked at it from outside with a torch and said the nest was about the size of a football and was attached to a beam near the roof. He wanted to deal with it himself. My mother telephoned the council instead, which was the right decision, and a man came on the Friday. He arrived at eight in the evening, because wasps are all inside the nest at that time and are much slower. He wore a suit and a hood and he was there for about fifteen minutes. He told us three things while he was putting his equipment away. The first is that a wasps' nest is only used for one year and is never used again, so if you find an old one in the winter it is empty. The second is that wasps eat a very large number of insects that damage garden plants, so they are not useless. And the third is that the one thing you must never do is hit a nest or throw water at it, which is exactly what my father had suggested on the Tuesday.",
    questions: [
      { q: "How was the nest discovered?", options: ["A neighbour told them.","The father saw it with a torch.","The brother was stung.","The council found it."], answer: 2, explanation: "'he opened the shed door and about six wasps came out at once and one of them stung him'." },
      { q: "How big was the nest?", options: ["Very small.","It filled the roof.","Nobody could see it.","About the size of a football."], answer: 3, explanation: "'the nest was about the size of a football'." },
      { q: "Why did the man come in the evening?", options: ["The wasps are inside and slower.","The family were out earlier.","He was busy in the day.","It was cooler then."], answer: 0, explanation: "'wasps are all inside the nest at that time and are much slower'." },
      { q: "What is true about a wasps' nest?", options: ["It grows every year.","It is used for only one year.","It lasts for many years.","It is used in winter."], answer: 1, explanation: "'a wasps' nest is only used for one year and is never used again'." },
      { q: "Why did the man say wasps are useful?", options: ["They keep other animals away.","They pollinate flowers.","They eat insects that damage plants.","They make honey."], answer: 2, explanation: "'wasps eat a very large number of insects that damage garden plants'." },
      { q: "What must you never do?", options: ["Use a torch near it.","Telephone the council.","Close the shed door.","Hit the nest or throw water at it."], answer: 3, explanation: "'the one thing you must never do is hit a nest or throw water at it'." }
    ]
  },
  {
    id: "ket-rmc14-07",
    title: "The Bus Pass",
    text: "When I started at my new school I had to take two buses. The journey is about fifty minutes each way and it costs three pounds forty a day, which is seventeen pounds a week and which my parents could not easily pay. In September my mother found out about a card that the council gives to students who live more than three miles from their school. We live three point four miles away, measured by the shortest road, which the council checks on a computer. She applied in the first week of September and the card came in the middle of October, so we paid for six weeks and then stopped paying. The card is blue and has my photograph on it and I have to show it to both drivers. It is free until I am nineteen as long as I am still at school. There are rules. It only works between seven in the morning and seven in the evening, and only on school days, so it is no use at the weekend or in the holidays. Once I left it at home. The driver of the first bus let me on and said nothing, and I have thought since that he did not have to. The driver of the second bus did not, and I walked the last two miles and was late, and the school office telephoned my mother, and I have never left it at home again. My friend Ade lives two point eight miles from school and does not get one. He walks. He says the line has to be somewhere and that he would rather it was not where it is.",
    questions: [
      { q: "Why did the writer need help with the fare?", options: ["The cost was difficult for the family.","There was no direct bus.","The school asked them to apply.","The buses were often late."], answer: 0, explanation: "'which my parents could not easily pay'." },
      { q: "Who can get the card?", options: ["Anybody under nineteen.","Students who live over three miles away.","All students at the school.","Students whose parents apply in September."], answer: 1, explanation: "'students who live more than three miles from their school'." },
      { q: "How long did the family pay fares?", options: ["Until Christmas.", "Two weeks.", "Six weeks.", "They never paid."], answer: 2, explanation: "'we paid for six weeks and then stopped paying'." },
      { q: "When can the card not be used?", options: ["Before nine in the morning.", "On the second bus.", "When the writer has no photograph.", "At weekends and in the holidays."], answer: 3, explanation: "'only on school days, so it is no use at the weekend or in the holidays'." },
      { q: "What happened when the writer forgot the card?", options: ["They walked part of the way and were late.","They paid the fare in cash.","The school gave them a temporary card.","Both drivers refused."], answer: 0, explanation: "'I walked the last two miles and was late'." },
      { q: "What does Ade say about the rule?", options: ["He will apply again next year.","The line has to be somewhere.","It is unfair and should be changed.","He does not want a card."], answer: 1, explanation: "'He says the line has to be somewhere'." }
    ]
  },
  {
    id: "ket-rmc14-08",
    title: "Our Class Assembly",
    text: "Every class in our school does one assembly a year in front of the whole of Years 7 to 9, which is about four hundred people. Ours was in March and it was about water: how much we use, where it comes from, and what happens to it afterwards. Our teacher gave us three weeks and then did something unusual, which was almost nothing. She told us the subject, told us it must last twelve minutes, and said that she would watch it once, four days before, and give us one piece of advice. Everything else was ours. That was harder than being told what to do. For the first week we argued. Six people wanted to make a film, four wanted to do a play, and three people said nothing at all, which I now think was the real problem rather than the arguing. In the end we did both: a short film of a tap running for one minute at the start, which was more uncomfortable to watch than we expected, and then a play about a town with no water. When our teacher watched it, her one piece of advice was to cut the play from nine minutes to six. We did not want to. We did it, and she was right, because the last three minutes were the part where two people repeated things. On the day it went well. The best moment was the tap. Four hundred people watched water running into a sink for sixty seconds and by the end of it the hall was completely silent.",
    questions: [
      { q: "Who watches the assembly?", options: ["Only Year 7.","Parents and teachers.","About four hundred students.","The whole school."], answer: 2, explanation: "'in front of the whole of Years 7 to 9, which is about four hundred people'." },
      { q: "What did the teacher do?", options: ["She wrote the play herself.","She chose who would speak.","She watched every rehearsal.","She gave them the subject and left them to it."], answer: 3, explanation: "'She told us the subject, told us it must last twelve minutes'." },
      { q: "What does the writer now think was the real problem?", options: ["Three people said nothing.","Nobody could agree on a film.","The subject was too difficult.","There was not enough time."], answer: 0, explanation: "'three people said nothing at all, which I now think was the real problem'." },
      { q: "What was the teacher's advice?", options: ["To use fewer people.","To make the play three minutes shorter.","To add music.","To speak more loudly."], answer: 1, explanation: "'to cut the play from nine minutes to six'." },
      { q: "Why was she right?", options: ["The audience could not hear.","The play had too many characters.","The last part repeated things.","The film was too long."], answer: 2, explanation: "'the last three minutes were the part where two people repeated things'." },
      { q: "What was the best moment?", options: ["The teacher's introduction.","The applause.","The end of the play.","The film of the running tap."], answer: 3, explanation: "'The best moment was the tap.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
