/* KET Prep bank: reading multiple-choice (A2) — wave 18 */
(function () {
var BANK = [
  {
    id: "ket-rmc18-01",
    title: "The School Bus Driver",
    text: "Our school bus driver is called Mr Okonkwo and he has driven that route for nineteen years. There are fifty-two students on the bus and he knows every name. He also knows which stop each person gets off at, which sounds simple and is not, because there are eleven stops and people change. If somebody is not at their stop in the morning he waits about forty seconds and then goes, and if the same person is missing for three days he asks somebody on the bus whether they are all right. The rules on the bus are his rules and there are three. Everybody sits down before the bus moves. Nothing is eaten on the bus. And the seats at the front are for the youngest students, which he decided years ago and which nobody argues about. He is not strict in any other way. There is a lot of noise, especially in the afternoon, and he does not mind it at all. Two years ago the bus company wanted to change the route and take out two stops to save eight minutes. Mr Okonkwo went to a meeting and said that one of those stops was used by four students who would otherwise have to walk on a road with no pavement. The stops stayed. On the last day of the summer term everybody claps when he stops the bus, which he pretends to find embarrassing, and last July somebody gave him a card that fifty of us had signed.",
    questions: [
      { q: "How long has he driven the route?", options: ["Nineteen years.", "Eleven years.", "Two years.", "Since the school opened."], answer: 0, explanation: "'he has driven that route for nineteen years'." },
      { q: "What does he do if somebody is missing for three days?", options: ["Reports it to the school office.", "Asks somebody if they are all right.", "Waits longer at the stop.", "Telephones their parents."], answer: 1, explanation: "'he asks somebody on the bus whether they are all right'." },
      { q: "Which is one of his rules?", options: ["No talking after eight o'clock.", "Bags must go under the seat.", "Nothing is eaten on the bus.", "Everybody must sit in the same seat."], answer: 2, explanation: "'Nothing is eaten on the bus.'" },
      { q: "Who sits at the front?", options: ["Students who feel ill.", "Anybody who arrives first.", "Students in the oldest year.", "The youngest students."], answer: 3, explanation: "'the seats at the front are for the youngest students'." },
      { q: "Why did the company want to change the route?", options: ["To save eight minutes.", "Because of roadworks.", "Because the bus was too full.", "To add two new stops."], answer: 0, explanation: "'take out two stops to save eight minutes'." },
      { q: "Why did the stops stay?", options: ["The parents complained.", "He explained that students would walk on a dangerous road.", "The school paid extra.", "The company changed its mind about the time."], answer: 1, explanation: "'four students who would otherwise have to walk on a road with no pavement'." }
    ]
  },
  {
    id: "ket-rmc18-02",
    title: "The Art Competition",
    text: "Our town library has an art competition every year for people under sixteen. There is one subject, which is announced in January, and last year it was Water. You can use any materials and the picture must be smaller than a certain size, and you take it to the library by the end of March. About a hundred and forty pictures were entered last year. I entered for the first time. I am not the best artist in my class, and my picture was a drawing of the inside of our kitchen sink with the tap running, done in pencil, which took me about six hours over three weekends. I did not win. A girl of eleven won with a painting of the sea in a storm, which was genuinely very good, and I stood in front of it for a while and could see exactly why it had won. What surprised me is that all hundred and forty pictures were put up. They were on the walls of the library for the whole of April, in three rooms, with a small card next to each one with the name and age of the artist. There was no order and no separate place for the winners except one shelf near the door. My grandmother went twice. She told me that she had looked at all of them and that a picture by a boy of seven, of a puddle, had made her laugh out loud in a library, which she said was the first time that had happened to her.",
    questions: [
      { q: "When is the subject announced?", options: ["In April.","It is different every month.","In January.","At the end of March."], answer: 2, explanation: "'There is one subject, which is announced in January'." },
      { q: "What did the writer draw?", options: ["A river in their town.","The sea in a storm.","A puddle.","A kitchen sink with the tap running."], answer: 3, explanation: "'a drawing of the inside of our kitchen sink with the tap running'." },
      { q: "Who won?", options: ["A girl of eleven.","A boy of seven.","The writer.","Nobody won last year."], answer: 0, explanation: "'A girl of eleven won with a painting of the sea in a storm'." },
      { q: "What surprised the writer?", options: ["Only ten pictures were shown.","Every picture was displayed.","The library was very busy.","The prize was money."], answer: 1, explanation: "'all hundred and forty pictures were put up'." },
      { q: "How long were the pictures on the walls?", options: ["Three days.","One weekend.","The whole of April.","Until the end of March."], answer: 2, explanation: "'They were on the walls of the library for the whole of April'." },
      { q: "What did the grandmother say?", options: ["She would enter next year.","The winner should have been different.","There were too many pictures.","A picture of a puddle made her laugh."], answer: 3, explanation: "'a picture by a boy of seven, of a puddle, had made her laugh out loud'." }
    ]
  },
  {
    id: "ket-rmc18-03",
    title: "The Litter Pick",
    text: "On the first Sunday of every month about twenty people meet at the bridge in our village at ten o'clock and pick up litter for two hours. I have been going since March with my father. The council gives the group the equipment: grabbers, gloves, bags and yellow jackets, which you must wear because some of the work is beside a road. We work in pairs and each pair takes a section, and there is a map on a clipboard with the sections marked so that nobody does the same stretch twice. In two hours twenty people usually collect between thirty and forty bags. The council collects the bags on the Monday. What we find is not what most people imagine. There is very little that has been dropped in the village itself. Almost all of it comes from two places: the road, where it is thrown from cars, and the river, which brings things down from the town and leaves them in the trees on the bank when the water goes down. In July we found a road sign in the river, a chair, and eleven tyres, which took two people and a rope. The group started in 2019 with four people. One of them told me that the most useful thing about it is not the litter. It is that a place that looks looked after gets less litter dropped in it, and that this effect is much larger than anybody expects. She said the stretch by the bridge used to fill up again within a week and now takes about a month, and that nothing has changed there except that somebody comes.",
    questions: [
      { q: "How often does the group meet?", options: ["Once a month.","Twice a month.","Every day in summer.","Every Sunday."], answer: 0, explanation: "'On the first Sunday of every month'." },
      { q: "Who provides the equipment?", options: ["A local shop.","The council.","The village school.","The volunteers themselves."], answer: 1, explanation: "'The council gives the group the equipment'." },
      { q: "Why is there a map?", options: ["To show where the bins are.", "To find the river bank.", "So that no stretch is done twice.", "To record what is found."], answer: 2, explanation: "'so that nobody does the same stretch twice'." },
      { q: "Where does most of the litter come from?", options: ["Local houses.", "The village shop.", "Visitors in summer.", "The road and the river."], answer: 3, explanation: "'Almost all of it comes from two places: the road… and the river'." },
      { q: "What did they find in July?", options: ["A road sign, a chair and eleven tyres.", "Forty bags of household rubbish.", "A bicycle.", "Nothing unusual."], answer: 0, explanation: "'we found a road sign in the river, a chair, and eleven tyres'." },
      { q: "What is the most useful effect, according to a founder?", options: ["The bags collected each month.", "A tidy place attracts less litter.", "The council pays attention.", "More people join each year."], answer: 1, explanation: "'a place that looks looked after gets less litter dropped in it'." }
    ]
  },
  {
    id: "ket-rmc18-04",
    title: "The Talent Show",
    text: "Our school has a talent show in December. Anybody can enter and about thirty acts try, and eighteen are chosen after an afternoon of auditions in November. Last year my friend Nils and I entered as a pair. We are not musicians and we cannot dance. What we did was a short piece where he made a paper aeroplane on stage while I explained, in a very serious voice, exactly what he was doing wrong, and then it flew the whole length of the hall. It took us nine hours to prepare something that lasts two minutes and twenty seconds, and most of that time was spent throwing paper aeroplanes in his garage to find a design that flies straight every single time. We did not win. The winner was a girl in Year 11 who sang without any music at all and who stopped the whole hall completely, and I have thought since that the reason it worked was that everything else, including ours, had something else in it, and hers had nothing except her voice. The show raised four hundred pounds for a charity that our student council chooses each year. My favourite part was not the show. It was the auditions, which anybody could watch. Twelve acts that did not get in did things in front of about forty people, in an ordinary classroom, with the lights on and no music and nowhere to stand, which is much harder than a stage. Two of those twelve are entering again this year and one of them has asked me to help.",
    questions: [
      { q: "How many acts are chosen?", options: ["Anybody who enters.","Thirty.","Eighteen.","Twelve."], answer: 2, explanation: "'eighteen are chosen after an afternoon of auditions'." },
      { q: "What did the writer and Nils do?", options: ["Told jokes.","Sang a song.","Danced.","Made a paper aeroplane on stage."], answer: 3, explanation: "'he made a paper aeroplane on stage while I explained'." },
      { q: "How long did their act last?", options: ["Nine hours to prepare and about two minutes on stage.", "Ten minutes.", "Twenty seconds.", "The whole first half."], answer: 0, explanation: "'nine hours to prepare something that lasts two minutes and twenty seconds'." },
      { q: "Why did the winner's act work, in the writer's view?", options: ["She had won before.","There was nothing in it except her voice.","She practised the longest.","The audience knew the song."], answer: 1, explanation: "'hers had nothing except her voice'." },
      { q: "What happens to the money?", options: ["It is shared between the winners.","It buys equipment for the music room.","It goes to a charity the students choose.","It pays for the school hall."], answer: 2, explanation: "'raised four hundred pounds for a charity that our student council chooses'." },
      { q: "What did the writer like best?", options: ["Winning a prize.","The lights and the stage.","The final performance.","The auditions."], answer: 3, explanation: "'It was the auditions'." }
    ]
  },
  {
    id: "ket-rmc18-05",
    title: "My Mother's Night Shifts",
    text: "My mother is a nurse and she works nights, which means twelve and a half hours from half past seven in the evening until eight the next morning. She does three nights, then has four days off, then does three more. She has done this for eleven years. Our house has a rule that everybody understands and that visitors find strange: between about ten in the morning and four in the afternoon on the days after a night shift, we are quiet. Not silent, because she says a completely silent house is impossible and she can sleep through ordinary noise. What she cannot sleep through is the washing machine, the front door and anybody calling her name. I do not remember when I learned this. I have never known anything else. The difficult part is not the quiet, which is easy. It is that on the days she works, I see her for about twenty minutes in the evening before she goes, and on the days she sleeps, I see her at about half past four when I get home from school. So for six days out of seven the amount of time we spend together is small, and then on her long weekend it is the opposite: she is there for four days and we do things. My father, who works ordinary hours, told me once that this is why we cook together so much, because that is the thing my mother chose to do with the four days rather than sleep more.",
    questions: [
      { q: "How long is one shift?", options: ["Twelve and a half hours.", "Eight hours.", "A whole day.", "Three nights."], answer: 0, explanation: "'twelve and a half hours from half past seven in the evening until eight the next morning'." },
      { q: "What is the household rule?", options: ["Nobody may come to the house.", "Everybody is quiet in the middle of the day.", "The television must stay off.", "The children must stay upstairs."], answer: 1, explanation: "'between about ten in the morning and four in the afternoon… we are quiet'." },
      { q: "What can she sleep through?", options: ["Her name being called.","The washing machine.","Ordinary noise.","The front door."], answer: 2, explanation: "'she can sleep through ordinary noise'." },
      { q: "What does the writer find hardest?", options: ["Cooking every day.","The quiet.","Doing the housework.","Seeing so little of their mother."], answer: 3, explanation: "'for six days out of seven the amount of time we spend together is small'." },
      { q: "What happens on the four days off?", options: ["The family does things together.","The writer stays with grandparents.","She sleeps most of the time.","She works a different job."], answer: 0, explanation: "'she is there for four days and we do things'." },
      { q: "Why does the family cook together?", options: ["The father suggested it.","The mother chose to spend her days off that way.","Nobody else can cook.","It is cheaper."], answer: 1, explanation: "'that is the thing my mother chose to do with the four days'." }
    ]
  },
  {
    id: "ket-rmc18-06",
    title: "The Guitar Lesson",
    text: "I had guitar lessons for two years and then stopped, and I want to explain why, because it is not the reason people assume. My teacher was good. He was patient, he never told me off for not practising, and he could play anything. The problem was that I wanted to play three songs and he wanted me to learn to read music. Both of those are reasonable. He said that if I learned to read, I could play anything I ever wanted for the rest of my life. I said that I would like to play one of the three songs by Christmas. In two years I did learn to read music slowly, and I could play about half of one of the songs, and I stopped in the March after my fifteenth birthday. Then something happened that I did not expect. I did not touch the guitar for eight months, and in the November I picked it up and taught myself one of the three songs from a video in about a fortnight. It is not perfect. I play it wrongly in one place, which my teacher would notice in four seconds. I have played it perhaps two hundred times since. I have thought about this a great deal and I do not think anybody was wrong. He was teaching me to be a musician and I wanted to play a song. If I had told him that clearly at the beginning, in those words, I think he would have taught me the song first.",
    questions: [
      { q: "What was the teacher like?", options: ["Not very skilled.","Impatient and strict.","Good and patient.","Often late."], answer: 2, explanation: "'He was patient, he never told me off'." },
      { q: "What was the disagreement about?", options: ["Which guitar to buy.","The price of lessons.","How often to practise.","Songs versus reading music."], answer: 3, explanation: "'I wanted to play three songs and he wanted me to learn to read music'." },
      { q: "What did the teacher argue?", options: ["Reading music lets you play anything later.","Songs are too difficult at first.","Reading music is quicker to learn.","The writer had no talent."], answer: 0, explanation: "'if I learned to read, I could play anything I ever wanted'." },
      { q: "What happened after eight months?", options: ["The writer joined a band.","The writer learned a song from a video.","The writer went back to lessons.","The guitar was sold."], answer: 1, explanation: "'in the November I picked it up and taught myself one of the three songs'." },
      { q: "What is true about the writer's playing?", options: ["They only play from music.","It is perfect now.","There is a mistake in it.","They cannot remember the song."], answer: 2, explanation: "'I play it wrongly in one place'." },
      { q: "What does the writer conclude?", options: ["The teacher was wrong.","They should have practised more.","Lessons are a waste of money.","Neither person was wrong."], answer: 3, explanation: "'I do not think anybody was wrong'." }
    ]
  },
  {
    id: "ket-rmc18-07",
    title: "The First Day of the Holidays",
    text: "The first day of the summer holidays is always a disappointment and I have finally worked out why. In the last week of term everybody talks about it. Six weeks, no school, and a list of things you are going to do. I always have a list. Last year it had eleven things on it, including learn to cook three meals, read four books, tidy my room properly and go swimming twice a week. Then the first day arrives and you wake up at half past nine and there is nothing at all that has to happen, and by eleven o'clock you have done nothing, and by four o'clock you feel strange and slightly flat. It is not that the holiday is bad. It is that six weeks of nothing planned is too much space, and a person who has been told where to be every forty minutes for eleven weeks does not know what to do with it immediately. What works, and what I did last year for the first time, is to put three fixed things in the week. I had swimming on Tuesday mornings, a job at the garden centre on Thursday and Friday, and my grandmother on Sunday. Everything else was free, and the free time was much better because it had edges. I did seven of the eleven things on the list, which is the most I have ever done, and the four I did not do were the four that were on the list because I thought I should want them.",
    questions: [
      { q: "How does the writer feel on the first day?", options: ["Flat and strange.","Tired from the last week of term.","Worried about the list.","Excited."], answer: 0, explanation: "'by four o'clock you feel strange and slightly flat'." },
      { q: "What is the reason for this?", options: ["There is too much homework.","Six weeks with nothing planned is too much space.","The weather is usually bad.","Friends are away."], answer: 1, explanation: "'six weeks of nothing planned is too much space'." },
      { q: "How many things were on last year's list?", options: ["Four.", "Three.", "Eleven.", "Seven."], answer: 2, explanation: "'it had eleven things on it'." },
      { q: "What did the writer try last year?", options: ["Making a longer list.", "Going away for the whole summer.", "Doing nothing on purpose.", "Fixing three things each week."], answer: 3, explanation: "'to put three fixed things in the week'." },
      { q: "Why was the free time better?", options: ["It had edges.", "There was less of it.", "Friends were free too.", "The writer had more money."], answer: 0, explanation: "'the free time was much better because it had edges'." },
      { q: "Why were four things not done?", options: ["They were too expensive.","They were things the writer thought they should want.","The weather prevented them.","There was no time."], answer: 1, explanation: "'the four that were on the list because I thought I should want them'." }
    ]
  },
  {
    id: "ket-rmc18-08",
    title: "My Grandmother's Tool Box",
    text: "My grandmother has a wooden tool box that she keeps under the stairs. It is not large and it is not full. There are eleven things in it and she has told me that this is on purpose, and that she has thrown away or given away everything she does not use. Inside there is a hammer, two screwdrivers, a small saw, pliers, a tape measure, a spirit level, a tin of assorted screws, a roll of tape, a pencil and a pair of scissors. That is all. She has done every small repair in her house herself since 1979, when her husband died and she decided, in her own words, that she was not going to wait for anybody. She has put up about forty shelves. She has mended chairs, changed the washer in every tap in the house twice, and once repaired a door that would not close by taking it off, planing four millimetres from one edge and putting it back, which took her a whole Saturday and which she describes as the most satisfying day of that year. She taught me to use the spirit level when I was seven and the saw when I was eleven. Her rule about the saw is that you never hurry a cut and that a saw does the work if you let it. Last year she told me that the box is coming to me. She also said, in the same sentence, that if I ever put more than fifteen things in it I will have misunderstood the whole point.",
    questions: [
      { q: "What is unusual about the tool box?", options: ["It is kept in the garden.","It is very old.","It contains only eleven things.","It is too heavy to move."], answer: 2, explanation: "'There are eleven things in it and she has told me that this is on purpose'." },
      { q: "When did she start doing repairs herself?", options: ["When she was seven.","Last year.","After she retired.","In 1979."], answer: 3, explanation: "'since 1979, when her husband died'." },
      { q: "What did she do with the door?", options: ["Took it off and planed one edge.","Changed the handle.","Replaced it completely.","Called a carpenter."], answer: 0, explanation: "'taking it off, planing four millimetres from one edge and putting it back'." },
      { q: "What did she teach the writer at eleven?", options: ["To put up shelves.","To use the saw.","To use the spirit level.","To change a tap washer."], answer: 1, explanation: "'the saw when I was eleven'." },
      { q: "What is her rule about sawing?", options: ["Use both hands.","Cut on the line, not next to it.","Never hurry the cut.","Always measure twice."], answer: 2, explanation: "'you never hurry a cut and that a saw does the work if you let it'." },
      { q: "What did she say about the future of the box?", options: ["She will buy a bigger one.","It will be sold.","It will go to a museum.","The writer will inherit it."], answer: 3, explanation: "'she told me that the box is coming to me'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
