/* KET Prep bank: reading multiple-choice (wave 6) */
(function () {
var BANK = [
  {
    id: "ket-rmc6-01",
    title: "Grandpa's Bicycle Shop",
    text: "My grandpa has a small bicycle shop near the park. It is not a new shop — it was my great-grandfather's shop first, so it is more than sixty years old. Grandpa opens the shop every morning at nine o'clock, but not on Mondays. That is his day for fishing at the lake. I love visiting the shop after school on Fridays. It smells of oil and rubber, and there are bicycles everywhere: red ones, blue ones, big ones for adults and small ones for children. My favourite is an old green bicycle that hangs on the wall. Grandpa says it is not for sale because it was his first bicycle, a present from his father when he was ten. Grandpa does not only sell bicycles. Most people come because their bicycles are broken. Grandpa can repair almost anything — broken lights, flat tyres, old brakes. He works slowly and carefully, and he always talks to the customers about their families while he works. Mum says half of the town has sat on the little red chairs in his shop, drinking tea and waiting. Last month, Grandpa started teaching me how to repair a flat tyre. It was difficult at first, and I got oil on my school shirt, so now I keep an old T-shirt at the shop. Yesterday I repaired a tyre all by myself for the first time. The customer was our maths teacher, Mr Reed! He gave me one pound and said, 'Great job, young man.' I put the coin in a little box under the counter. When I am older, I want to work in the shop with Grandpa every summer.",
    questions: [
      { q: "Why is the shop closed on Mondays?", options: ["Grandpa goes fishing.", "It is too old.", "Nobody comes on Mondays.", "Grandpa cleans the shop."], answer: 0, explanation: "Monday 'is his day for fishing at the lake'." },
      { q: "Why is the green bicycle not for sale?", options: ["It is broken.", "It was Grandpa's first bicycle.", "It is too old to ride.", "It belongs to the writer."], answer: 1, explanation: "Grandpa says it was 'his first bicycle, a present from his father when he was ten'." },
      { q: "Why do most people come to the shop?", options: ["To buy new bicycles.", "To drink tea with Grandpa.", "To get their bicycles repaired.", "To talk about fishing."], answer: 2, explanation: "'Most people come because their bicycles are broken.'" },
      { q: "Why does the writer keep an old T-shirt at the shop?", options: ["The shop is cold.", "Grandpa asked for it.", "It was a present from Mr Reed.", "To keep the school shirt clean from oil."], answer: 3, explanation: "The writer got oil on a school shirt, 'so now I keep an old T-shirt at the shop'." },
      { q: "What happened yesterday?", options: ["The writer repaired a tyre alone for the first time.", "Grandpa taught the writer about brakes.", "Mr Reed bought a new bicycle.", "The writer lost a pound coin."], answer: 0, explanation: "'Yesterday I repaired a tyre all by myself for the first time.'" },
      { q: "What does the writer want to do in the future?", options: ["Open a new shop in the park.", "Become a maths teacher.", "Work in the shop with Grandpa in summer.", "Buy the green bicycle."], answer: 2, explanation: "'When I am older, I want to work in the shop with Grandpa every summer.'" }
    ]
  },
  {
    id: "ket-rmc6-02",
    title: "A Morning at the Animal Home",
    text: "Last Saturday, our class visited the animal home on River Road. It is a place for cats and dogs that do not have families. Our teacher, Miss Lane, told us to arrive at nine o'clock, but I was so excited that I arrived at half past eight, before everyone else. A worker called Tom showed us around. First we saw the dogs. Tom said there were twenty-three dogs living there. The oldest dog is called Biscuit. He is twelve years old and has lived at the home for two years, longer than any other animal there. Tom said most people want young dogs, so nobody chooses Biscuit. I felt sad about that. He looked very friendly, with big brown eyes. Then we visited the cat rooms. The cats do not live in cages; they live in three big rooms with beds, toys and things to climb. A small black cat came and sat on my shoes. Tom laughed and said, 'She likes you! Her name is Pepper.' We learned that the animal home needs a lot of help. The workers wash the animals, clean the rooms and take the dogs for walks twice a day. Tom said the home always needs old towels and blankets, so our class decided to collect some at school and bring them next month. On the bus home, I could not stop thinking about Biscuit. I told Mum and Dad about him at dinner. On Sunday, we all went back to the animal home together — and now Biscuit sleeps in a basket in our kitchen!",
    questions: [
      { q: "Why did the writer arrive at half past eight?", options: ["The bus came early.", "The writer was very excited.", "Miss Lane changed the time.", "The home opens at eight."], answer: 1, explanation: "'I was so excited that I arrived at half past eight, before everyone else.'" },
      { q: "Why has nobody chosen Biscuit?", options: ["He is not friendly.", "He is ill.", "Most people want young dogs.", "He bites visitors."], answer: 2, explanation: "Tom said 'most people want young dogs, so nobody chooses Biscuit'." },
      { q: "Where do the cats live?", options: ["In three big rooms.", "In small cages.", "In the workers' office.", "In the garden."], answer: 0, explanation: "'The cats do not live in cages; they live in three big rooms.'" },
      { q: "How did the writer meet Pepper?", options: ["Tom put her in the writer's arms.", "She was sleeping in a basket.", "She was walking with the dogs.", "She came and sat on the writer's shoes."], answer: 3, explanation: "'A small black cat came and sat on my shoes... Her name is Pepper.'" },
      { q: "What will the class do next month?", options: ["Wash the dogs.", "Bring old towels and blankets.", "Clean the cat rooms.", "Take photos of the animals."], answer: 1, explanation: "The home needs old towels and blankets, 'so our class decided to collect some at school and bring them next month'." },
      { q: "What happened on Sunday?", options: ["The writer's family gave Biscuit a home.", "The class visited again.", "Biscuit found a new dog friend.", "Pepper came to live with the writer."], answer: 0, explanation: "The family went back together 'and now Biscuit sleeps in a basket in our kitchen'." }
    ]
  },
  {
    id: "ket-rmc6-03",
    title: "The Sandwich Project",
    text: "Every year, our school has a cooking week, and this year the theme was sandwiches. On Monday, our teacher put us into teams of four and gave every team the same job: invent a new sandwich, make it on Friday, and sell it at the school food fair on Saturday morning. The money from the fair helps pay for our school garden. My team had a problem at the start. Marco wanted a hot chicken sandwich, but Lily does not eat meat, and Ben wanted something sweet, like banana and chocolate. We talked for a long time and nearly had an argument. Then Lily had a clever idea: why not make two small sandwiches and sell them together as one 'Two Friends' box? One sandwich would be egg and salad, and the other would be banana with honey. Everyone liked her plan. On Friday afternoon, we made forty boxes in the school kitchen. I cut the bread, Marco cooked the eggs, Lily washed the salad and Ben did the bananas. It took us three hours, and the kitchen was a mess, but Miss Carter said our boxes looked wonderful. At the fair on Saturday, our table was next to Team Pizza Toast, and at first everyone went to them. Then Ben stood on a chair and shouted, 'Two sandwiches for the price of one!' After that, we had a long queue, and by eleven o'clock we had nothing left to sell. Our team made thirty-two pounds — more than any other team. The head teacher said the money will buy new seeds and a small apple tree for the garden.",
    questions: [
      { q: "Why does the school sell food at the fair?", options: ["To pay for the school garden.", "To buy books for the library.", "To help the school kitchen.", "To pay for a class trip."], answer: 0, explanation: "'The money from the fair helps pay for our school garden.'" },
      { q: "Why was there a problem in the team at the start?", options: ["Nobody could cook.", "The team members wanted different sandwiches.", "Marco and Ben were not friends.", "The kitchen was closed."], answer: 1, explanation: "Marco wanted chicken, Lily doesn't eat meat, and Ben wanted something sweet — 'we nearly had an argument'." },
      { q: "What was Lily's idea?", options: ["To make a hot chicken sandwich.", "To ask Miss Carter for help.", "To sell two small sandwiches together in one box.", "To make pizza toast instead."], answer: 2, explanation: "Her idea was 'two small sandwiches... sold together as one Two Friends box'." },
      { q: "What was Ben's job on Friday?", options: ["Cutting the bread.", "Cooking the eggs.", "Washing the salad.", "Preparing the bananas."], answer: 3, explanation: "'I cut the bread, Marco cooked the eggs, Lily washed the salad and Ben did the bananas.'" },
      { q: "How did the team get a long queue at the fair?", options: ["Ben shouted about their special offer.", "Miss Carter sent people to them.", "Team Pizza Toast finished early.", "They gave free boxes to teachers."], answer: 0, explanation: "Ben stood on a chair and shouted 'Two sandwiches for the price of one!' — after that there was a long queue." },
      { q: "What will the school buy with the money?", options: ["A new kitchen table.", "Seeds and a small apple tree.", "Forty sandwich boxes.", "Chairs for the fair."], answer: 1, explanation: "The head teacher said the money 'will buy new seeds and a small apple tree for the garden'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
