/* KET Prep extra bank: speaking */
(function () {
  var BANK = [
    { question: "Tell me about your family.", bullets: ["who is in your family", "what they do", "what you do together"] },
    { question: "Talk about your best friend.", bullets: ["what their name is", "how you met", "why you like them"] },
    { question: "Tell me about your favourite season.", bullets: ["which season it is", "what the weather is like", "what you do in that season"] },
    { question: "Talk about your school.", bullets: ["how big it is", "your favourite subject", "your teachers"] },
    { question: "Tell me about a pet you have or want.", bullets: ["what animal it is", "its name", "how you look after it"] },
    { question: "Talk about going shopping.", bullets: ["where you go", "who you go with", "what you like to buy"] },
    { question: "Tell me about your breakfast.", bullets: ["what you eat and drink", "what time you have it", "who makes it"] },
    { question: "Talk about a sport you like.", bullets: ["what the sport is", "where you play or watch it", "why you like it"] },
    { question: "Tell me about your bedroom.", bullets: ["what is in it", "your favourite thing there", "if you share it"] },
    { question: "Talk about your favourite film.", bullets: ["what it is called", "what happens in it", "why you like it"] },
    { question: "Tell me about music you like.", bullets: ["what kind of music", "when you listen to it", "your favourite singer or band"] },
    { question: "Talk about your town or city.", bullets: ["where it is", "what you can do there", "your favourite place"] },
    { question: "Tell me about your last holiday.", bullets: ["where you went", "who you went with", "what you did there"] },
    { question: "Talk about your favourite day of the week.", bullets: ["which day it is", "what you do on that day", "why you like it"] },
    { question: "Tell me about the clothes you like to wear.", bullets: ["your favourite clothes", "your favourite colour", "where you buy clothes"] },
    { question: "Talk about how you come to school.", bullets: ["how you travel", "how long it takes", "who you travel with"] },
    { question: "Tell me about a book you read.", bullets: ["what it was about", "where you got it", "if you liked it"] },
    { question: "Talk about your favourite room at home.", bullets: ["which room it is", "what is in it", "what you do there"] },
    { question: "Tell me about birthdays in your family.", bullets: ["how you celebrate", "what food you have", "presents you give"] },
    { question: "Talk about a game you play with friends.", bullets: ["what the game is", "how you play it", "who usually wins"] },
    { question: "Tell me about your morning routine.", bullets: ["what time you get up", "what you do first", "how you feel in the morning"] },
    { question: "Talk about the weather today.", bullets: ["what it is like", "what you wear in this weather", "if you like it"] },
    { question: "Tell me about a place you want to visit.", bullets: ["where it is", "why you want to go", "who you want to go with"] },
    { question: "Talk about helping at home.", bullets: ["what jobs you do", "how often you do them", "which job you don't like"] },
    { question: "Tell me about your favourite fruit.", bullets: ["what it is", "when you eat it", "why you like it"] },
    { question: "Talk about watching TV.", bullets: ["your favourite programme", "when you watch", "who you watch with"] },
    { question: "Tell me about your grandparents.", bullets: ["where they live", "how often you see them", "what you do together"] },
    { question: "Talk about a party you went to.", bullets: ["whose party it was", "what you did there", "what you ate"] },
    { question: "Tell me about learning English.", bullets: ["when you started", "what is easy for you", "what is difficult"] },
    { question: "Talk about your favourite drink.", bullets: ["what it is", "when you drink it", "if it is good for you"] },
    { question: "Tell me about a day at the beach or a park.", bullets: ["where you went", "what you did", "what the weather was like"] },
    { question: "Talk about your neighbours.", bullets: ["who lives near you", "if you talk to them", "if they are friendly"] },
    { question: "Tell me about your favourite animal.", bullets: ["what animal it is", "where it lives", "why you like it"] },
    { question: "Talk about using a phone or computer.", bullets: ["what you use it for", "how often you use it", "your favourite app or game"] },
    { question: "Tell me about your dinner yesterday.", bullets: ["what you ate", "who cooked it", "if you liked it"] },
    { question: "Talk about a present you gave to someone.", bullets: ["what it was", "who you gave it to", "why you chose it"] },
    { question: "Tell me about walking or cycling.", bullets: ["which one you prefer", "where you go", "why it is good for you"] },
    { question: "Talk about your English class.", bullets: ["how many students there are", "what you do in class", "your teacher"] },
    { question: "Tell me about winter where you live.", bullets: ["what the weather is like", "what clothes you wear", "what you do for fun"] },
    { question: "Talk about a market or supermarket you know.", bullets: ["where it is", "what they sell", "how often you go"] },
    { question: "Tell me about your favourite sweet or cake.", bullets: ["what it is", "when you eat it", "who makes or buys it"] },
    { question: "Talk about doing homework.", bullets: ["where you do it", "when you do it", "who helps you"] },
    { question: "Tell me about a trip by train or bus.", bullets: ["where you went", "how long it took", "what you saw"] },
    { question: "Talk about your favourite teacher.", bullets: ["what they teach", "why you like them", "something funny they do"] },
    { question: "Tell me about games you played when you were small.", bullets: ["what you played", "who you played with", "your favourite toy"] },
    { question: "Talk about a job you would like to do.", bullets: ["what the job is", "why you like it", "what you need to learn"] },
    { question: "Tell me about your favourite photo.", bullets: ["who or what is in it", "where you took it", "why you like it"] },
    { question: "Talk about going to the cinema.", bullets: ["how often you go", "who you go with", "what snacks you buy"] }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  SPEAKING = SPEAKING.concat(BANK);
})();
