/* KET Prep extra bank: vocab wave 1 — numbers, time, dates, family, colours, people */
(function () {
  var BANK = [
    /* ---------- Numbers ---------- */
    { front: "one", pos: "n.", def: "the number 1", example: "I have one brother and two sisters.", zh: "一" },
    { front: "two", pos: "n.", def: "the number 2", example: "There are two cats in the garden.", zh: "二" },
    { front: "three", pos: "n.", def: "the number 3", example: "The lesson starts at three o'clock.", zh: "三" },
    { front: "four", pos: "n.", def: "the number 4", example: "We need four chairs for the table.", zh: "四" },
    { front: "five", pos: "n.", def: "the number 5", example: "My little sister is five years old.", zh: "五" },
    { front: "six", pos: "n.", def: "the number 6", example: "The shop closes at six in the evening.", zh: "六" },
    { front: "seven", pos: "n.", def: "the number 7", example: "There are seven days in a week.", zh: "七" },
    { front: "eight", pos: "n.", def: "the number 8", example: "School begins at eight in the morning.", zh: "八" },
    { front: "nine", pos: "n.", def: "the number 9", example: "The film starts at nine tonight.", zh: "九" },
    { front: "ten", pos: "n.", def: "the number 10", example: "Can you count from one to ten?", zh: "十" },
    { front: "eleven", pos: "n.", def: "the number 11", example: "There are eleven players in a football team.", zh: "十一" },
    { front: "twelve", pos: "n.", def: "the number 12", example: "There are twelve months in a year.", zh: "十二" },
    { front: "thirteen", pos: "n.", def: "the number 13", example: "My cousin is thirteen years old.", zh: "十三" },
    { front: "fourteen", pos: "n.", def: "the number 14", example: "The bus leaves at fourteen minutes past two.", zh: "十四" },
    { front: "fifteen", pos: "n.", def: "the number 15", example: "The break is fifteen minutes long.", zh: "十五" },
    { front: "sixteen", pos: "n.", def: "the number 16", example: "You can ride this bike when you are sixteen.", zh: "十六" },
    { front: "seventeen", pos: "n.", def: "the number 17", example: "There are seventeen students in my class.", zh: "十七" },
    { front: "eighteen", pos: "n.", def: "the number 18", example: "My brother is eighteen and goes to university.", zh: "十八" },
    { front: "nineteen", pos: "n.", def: "the number 19", example: "The hotel room number is nineteen.", zh: "十九" },
    { front: "twenty", pos: "n.", def: "the number 20", example: "The book costs twenty pounds.", zh: "二十" },
    { front: "thirty", pos: "n.", def: "the number 30", example: "My aunt is thirty years old.", zh: "三十" },
    { front: "forty", pos: "n.", def: "the number 40", example: "The journey takes forty minutes.", zh: "四十" },
    { front: "fifty", pos: "n.", def: "the number 50", example: "There are fifty people at the party.", zh: "五十" },
    { front: "sixty", pos: "n.", def: "the number 60", example: "There are sixty seconds in a minute.", zh: "六十" },
    { front: "seventy", pos: "n.", def: "the number 70", example: "My grandfather is seventy years old.", zh: "七十" },
    { front: "eighty", pos: "n.", def: "the number 80", example: "The train travels at eighty kilometres an hour.", zh: "八十" },
    { front: "ninety", pos: "n.", def: "the number 90", example: "A football match lasts ninety minutes.", zh: "九十" },
    { front: "hundred", pos: "n.", def: "the number 100", example: "There are a hundred students in our school hall.", zh: "一百" },
    { front: "thousand", pos: "n.", def: "the number 1,000", example: "The car costs five thousand pounds.", zh: "一千" },
    { front: "million", pos: "n.", def: "the number 1,000,000", example: "More than a million people live in this city.", zh: "一百萬" },
    { front: "first", pos: "adj.", def: "coming before all others; number one in order", example: "This is my first day at the new school.", zh: "第一的" },
    { front: "second", pos: "adj.", def: "coming after the first; number two in order", example: "Our flat is on the second floor.", zh: "第二的" },
    { front: "third", pos: "adj.", def: "coming after the second; number three in order", example: "This is the third time I have seen this film.", zh: "第三的" },
    { front: "fourth", pos: "adj.", def: "coming after the third; number four in order", example: "My birthday is on the fourth of May.", zh: "第四的" },
    { front: "fifth", pos: "adj.", def: "coming after the fourth; number five in order", example: "Our classroom is on the fifth floor.", zh: "第五的" },
    { front: "sixth", pos: "adj.", def: "coming after the fifth; number six in order", example: "He finished sixth in the race.", zh: "第六的" },
    { front: "seventh", pos: "adj.", def: "coming after the sixth; number seven in order", example: "July is the seventh month of the year.", zh: "第七的" },
    { front: "eighth", pos: "adj.", def: "coming after the seventh; number eight in order", example: "Her office is on the eighth floor.", zh: "第八的" },
    { front: "ninth", pos: "adj.", def: "coming after the eighth; number nine in order", example: "The meeting is on the ninth of June.", zh: "第九的" },
    { front: "tenth", pos: "adj.", def: "coming after the ninth; number ten in order", example: "It is my parents' tenth wedding anniversary.", zh: "第十的" },
    { front: "twentieth", pos: "adj.", def: "coming after the nineteenth; number twenty in order", example: "The exam is on the twentieth of March.", zh: "第二十的" },
    { front: "zero", pos: "n.", def: "the number 0", example: "The temperature is zero degrees today.", zh: "零" },
    { front: "half", pos: "n.", def: "one of two equal parts of something", example: "I ate half of the pizza.", zh: "一半" },
    { front: "quarter", pos: "n.", def: "one of four equal parts of something", example: "It is a quarter past seven.", zh: "四分之一；一刻鐘" },
    { front: "double", pos: "adj.", def: "twice as much or made for two people", example: "We booked a double room at the hotel.", zh: "雙倍的；雙人的" },
    { front: "pair", pos: "n.", def: "two things that go together", example: "I bought a new pair of shoes.", zh: "一雙、一對" },
    { front: "dozen", pos: "n.", def: "a group of twelve", example: "Mum bought a dozen eggs at the market.", zh: "一打（十二個）" },
    { front: "number", pos: "n.", def: "a word or sign like 1, 2 or 3", example: "What is your phone number?", zh: "號碼、數字" },
    { front: "count", pos: "v.", def: "to say numbers in order or find how many there are", example: "The teacher counted the children on the bus.", zh: "數、計算" },
    { front: "add", pos: "v.", def: "to put numbers or things together", example: "If you add two and three, you get five.", zh: "加、添加" },
    { front: "plus", pos: "prep.", def: "and; added to", example: "Two plus two is four.", zh: "加上" },
    { front: "minus", pos: "prep.", def: "taken away from; below zero", example: "Ten minus four is six.", zh: "減去；零下" },
    { front: "total", pos: "n.", def: "the number you get when you add everything together", example: "The total for the meal was thirty pounds.", zh: "總數、總計" },
    { front: "once", pos: "adv.", def: "one time", example: "I visit my grandparents once a week.", zh: "一次" },
    { front: "twice", pos: "adv.", def: "two times", example: "I brush my teeth twice a day.", zh: "兩次" },
    /* ---------- Days & time of day ---------- */
    { front: "Monday", pos: "n.", def: "the first day of the working week", example: "I have a maths lesson on Monday.", zh: "星期一" },
    { front: "Tuesday", pos: "n.", def: "the day after Monday", example: "We play tennis every Tuesday.", zh: "星期二" },
    { front: "Wednesday", pos: "n.", def: "the day after Tuesday", example: "The library is closed on Wednesday.", zh: "星期三" },
    { front: "Thursday", pos: "n.", def: "the day after Wednesday", example: "My guitar class is on Thursday evening.", zh: "星期四" },
    { front: "Friday", pos: "n.", def: "the day after Thursday", example: "We are going to the cinema on Friday.", zh: "星期五" },
    { front: "Saturday", pos: "n.", def: "the day after Friday", example: "I play football with my friends on Saturday.", zh: "星期六" },
    { front: "Sunday", pos: "n.", def: "the day after Saturday", example: "We have lunch at my grandmother's house on Sunday.", zh: "星期日" },
    { front: "today", pos: "adv.", def: "on this day", example: "It is very hot today.", zh: "今天" },
    { front: "tomorrow", pos: "adv.", def: "on the day after today", example: "See you tomorrow at school!", zh: "明天" },
    { front: "yesterday", pos: "adv.", def: "on the day before today", example: "I saw Anna at the park yesterday.", zh: "昨天" },
    { front: "day", pos: "n.", def: "a period of twenty-four hours", example: "We spent the day at the beach.", zh: "一天、白天" },
    { front: "week", pos: "n.", def: "a period of seven days", example: "I go swimming three times a week.", zh: "星期、週" },
    { front: "month", pos: "n.", def: "one of the twelve parts of a year", example: "We are moving house next month.", zh: "月份" },
    { front: "year", pos: "n.", def: "a period of twelve months", example: "My family goes on holiday every year.", zh: "年" },
    { front: "weekday", pos: "n.", def: "any day from Monday to Friday", example: "The museum is quieter on weekdays.", zh: "平日、工作日" },
    { front: "date", pos: "n.", def: "the day, month and year", example: "What is the date today?", zh: "日期" },
    { front: "calendar", pos: "n.", def: "a list of the days and months of the year", example: "I wrote your birthday on my calendar.", zh: "日曆" },
    { front: "diary", pos: "n.", def: "a book where you write what you do each day", example: "She writes in her diary every night.", zh: "日記；記事本" },
    { front: "morning", pos: "n.", def: "the early part of the day, before midday", example: "I drink a glass of milk every morning.", zh: "早上" },
    { front: "afternoon", pos: "n.", def: "the part of the day between midday and evening", example: "We have two lessons in the afternoon.", zh: "下午" },
    { front: "evening", pos: "n.", def: "the part of the day between afternoon and night", example: "My father watches TV in the evening.", zh: "傍晚、晚上" },
    { front: "night", pos: "n.", def: "the time when it is dark and people sleep", example: "The baby slept well last night.", zh: "夜晚" },
    { front: "midnight", pos: "n.", def: "twelve o'clock at night", example: "We stayed up until midnight on New Year's Eve.", zh: "午夜" },
    { front: "midday", pos: "n.", def: "twelve o'clock in the middle of the day", example: "We stopped for lunch at midday.", zh: "中午" },
    { front: "noon", pos: "n.", def: "twelve o'clock in the day", example: "The meeting finishes at noon.", zh: "正午" },
    { front: "tonight", pos: "adv.", def: "on this night, the night of today", example: "There is a good film on TV tonight.", zh: "今晚" },
    { front: "sunrise", pos: "n.", def: "the time in the morning when the sun appears", example: "We got up early to watch the sunrise.", zh: "日出" },
    { front: "sunset", pos: "n.", def: "the time in the evening when the sun goes down", example: "The sky was orange at sunset.", zh: "日落" },
    { front: "o'clock", pos: "adv.", def: "used after a number to say the time", example: "The lesson starts at nine o'clock.", zh: "……點鐘" },
    { front: "hour", pos: "n.", def: "a period of sixty minutes", example: "The film is about two hours long.", zh: "小時" },
    { front: "minute", pos: "n.", def: "a period of sixty seconds; a short time", example: "The bus leaves in five minutes.", zh: "分鐘" },
    { front: "moment", pos: "n.", def: "a very short time", example: "Wait a moment, please.", zh: "片刻、瞬間" },
    { front: "clock", pos: "n.", def: "a thing on a wall or table that shows the time", example: "The clock on the wall says half past three.", zh: "時鐘" },
    { front: "watch", pos: "n.", def: "a small clock that you wear on your arm", example: "Dad gave me a new watch for my birthday.", zh: "手錶" },
    { front: "alarm clock", pos: "n.", def: "a clock that makes a noise to wake you up", example: "My alarm clock rings at half past six.", zh: "鬧鐘" },
    { front: "time", pos: "n.", def: "what we measure in minutes, hours, days and years", example: "What time is it now?", zh: "時間" },
    /* ---------- Months & seasons ---------- */
    { front: "January", pos: "n.", def: "the first month of the year", example: "It often snows here in January.", zh: "一月" },
    { front: "February", pos: "n.", def: "the second month of the year", example: "February is the shortest month.", zh: "二月" },
    { front: "March", pos: "n.", def: "the third month of the year", example: "The new school term starts in March.", zh: "三月" },
    { front: "April", pos: "n.", def: "the fourth month of the year", example: "It rains a lot in April.", zh: "四月" },
    { front: "May", pos: "n.", def: "the fifth month of the year", example: "The garden is full of flowers in May.", zh: "五月" },
    { front: "June", pos: "n.", def: "the sixth month of the year", example: "Our exams finish in June.", zh: "六月" },
    { front: "July", pos: "n.", def: "the seventh month of the year", example: "We always go to the beach in July.", zh: "七月" },
    { front: "August", pos: "n.", def: "the eighth month of the year", example: "There is no school in August.", zh: "八月" },
    { front: "September", pos: "n.", def: "the ninth month of the year", example: "School starts again in September.", zh: "九月" },
    { front: "October", pos: "n.", def: "the tenth month of the year", example: "The leaves turn brown in October.", zh: "十月" },
    { front: "November", pos: "n.", def: "the eleventh month of the year", example: "It gets cold and dark in November.", zh: "十一月" },
    { front: "December", pos: "n.", def: "the last month of the year", example: "We decorate the house in December.", zh: "十二月" },
    { front: "spring", pos: "n.", def: "the season after winter when plants start to grow", example: "The trees turn green in spring.", zh: "春天" },
    { front: "summer", pos: "n.", def: "the hottest season of the year", example: "We swim in the sea every summer.", zh: "夏天" },
    { front: "autumn", pos: "n.", def: "the season between summer and winter", example: "The leaves fall from the trees in autumn.", zh: "秋天" },
    { front: "winter", pos: "n.", def: "the coldest season of the year", example: "We wear warm coats in winter.", zh: "冬天" },
    /* ---------- Celebrations & special days ---------- */
    { front: "season", pos: "n.", def: "one of the four parts of the year", example: "Which season do you like best?", zh: "季節" },
    { front: "holiday", pos: "n.", def: "a time when you do not work or study, often away from home", example: "We went to Spain on holiday last summer.", zh: "假期" },
    { front: "birthday", pos: "n.", def: "the day each year when you celebrate being born", example: "My birthday is in October.", zh: "生日" },
    { front: "party", pos: "n.", def: "a time when people meet to eat, dance and have fun", example: "Are you coming to my birthday party?", zh: "派對" },
    { front: "present", pos: "n.", def: "a thing you give to someone on a special day", example: "I got lots of presents for my birthday.", zh: "禮物" },
    { front: "gift", pos: "n.", def: "something you give to another person; a present", example: "This watch was a gift from my uncle.", zh: "禮物、贈品" },
    { front: "celebrate", pos: "v.", def: "to do something fun on a special day", example: "We celebrated my mum's birthday at a restaurant.", zh: "慶祝" },
    { front: "festival", pos: "n.", def: "a special time when people celebrate something", example: "There is a music festival in the park this summer.", zh: "節慶、慶典" },
    { front: "Christmas", pos: "n.", def: "the holiday on 25 December", example: "We give presents to each other at Christmas.", zh: "聖誕節" },
    { front: "Easter", pos: "n.", def: "a holiday in spring when people eat chocolate eggs", example: "The children looked for chocolate eggs at Easter.", zh: "復活節" },
    { front: "New Year", pos: "n.", def: "the time when a new year begins", example: "We watched fireworks at New Year.", zh: "新年" },
    { front: "wedding", pos: "n.", def: "the day when two people get married", example: "My aunt's wedding was in a beautiful garden.", zh: "婚禮" },
    { front: "anniversary", pos: "n.", def: "a day that is exactly one or more years after a special event", example: "It is my parents' wedding anniversary today.", zh: "週年紀念日" },
    { front: "invitation", pos: "n.", def: "a card or message asking you to come to something", example: "I got an invitation to Tom's party.", zh: "邀請函、邀請" },
    { front: "invite", pos: "v.", def: "to ask someone to come to a party or event", example: "She invited all her friends to the picnic.", zh: "邀請" },
    { front: "guest", pos: "n.", def: "a person who is invited to a place or party", example: "There were fifty guests at the wedding.", zh: "客人、賓客" },
    { front: "candle", pos: "n.", def: "a stick of wax that gives light when it burns", example: "There were ten candles on the birthday cake.", zh: "蠟燭" },
    { front: "balloon", pos: "n.", def: "a small coloured bag filled with air, used at parties", example: "We put balloons on the door for the party.", zh: "氣球" },
    { front: "card", pos: "n.", def: "a folded piece of paper with a picture and a message", example: "I sent my grandmother a birthday card.", zh: "卡片" },
    { front: "surprise", pos: "n.", def: "something you do not expect", example: "The party was a big surprise for my dad.", zh: "驚喜" },
    /* ---------- Time adverbs & expressions ---------- */
    { front: "early", pos: "adj.", def: "before the usual time", example: "I got up early to catch the train.", zh: "早的、提早的" },
    { front: "late", pos: "adj.", def: "after the usual or correct time", example: "Sorry I am late — the bus did not come.", zh: "遲的、晚的" },
    { front: "soon", pos: "adv.", def: "in a short time from now", example: "Hurry up — the film starts soon.", zh: "很快、不久" },
    { front: "now", pos: "adv.", def: "at this moment", example: "I am doing my homework now.", zh: "現在" },
    { front: "then", pos: "adv.", def: "at that time; after that", example: "We had dinner and then watched a film.", zh: "那時；然後" },
    { front: "later", pos: "adv.", def: "after the present time or the time you are talking about", example: "I will call you later this evening.", zh: "稍後、後來" },
    { front: "ago", pos: "adv.", def: "before now; in the past", example: "We moved to this town two years ago.", zh: "……以前" },
    { front: "always", pos: "adv.", def: "every time; at all times", example: "She always walks to school with her friend.", zh: "總是" },
    { front: "usually", pos: "adv.", def: "most of the time", example: "I usually have cereal for breakfast.", zh: "通常" },
    { front: "often", pos: "adv.", def: "many times", example: "We often go to the cinema at the weekend.", zh: "經常" },
    { front: "sometimes", pos: "adv.", def: "at some times but not always", example: "Sometimes I ride my bike to school.", zh: "有時" },
    { front: "never", pos: "adv.", def: "not at any time", example: "He never eats fish.", zh: "從不" },
    { front: "again", pos: "adv.", def: "one more time", example: "Can you say that again, please?", zh: "再一次" },
    { front: "already", pos: "adv.", def: "before now or before this time", example: "I have already finished my homework.", zh: "已經" },
    { front: "yet", pos: "adv.", def: "until now; used in questions and negative sentences", example: "Have you seen the new film yet?", zh: "還（沒）、尚未" },
    { front: "still", pos: "adv.", def: "continuing until now", example: "It is ten o'clock and he is still in bed.", zh: "仍然" },
    { front: "next", pos: "adj.", def: "coming after this one", example: "We are going to Italy next summer.", zh: "下一個的" },
    { front: "last", pos: "adj.", def: "the one before this one; final", example: "I saw her last Friday.", zh: "上一個的；最後的" },
    { front: "before", pos: "prep.", def: "earlier than something", example: "Wash your hands before dinner.", zh: "在……之前" },
    { front: "after", pos: "prep.", def: "later than something", example: "We played games after school.", zh: "在……之後" },
    { front: "during", pos: "prep.", def: "through the time of something", example: "Please do not talk during the lesson.", zh: "在……期間" },
    { front: "until", pos: "prep.", def: "up to a time", example: "The shop is open until nine o'clock.", zh: "直到" },
    { front: "forever", pos: "adv.", def: "for all time; always", example: "I will remember this holiday forever.", zh: "永遠" },
    { front: "suddenly", pos: "adv.", def: "quickly, when you do not expect it", example: "Suddenly, it started to rain.", zh: "突然地" },
    { front: "finally", pos: "adv.", def: "after a long time; in the end", example: "After two hours, the bus finally arrived.", zh: "終於、最後" },
    { front: "at first", pos: "phrase", def: "at the beginning", example: "At first I did not like the new school, but now I love it.", zh: "起初" },
    { front: "at last", pos: "phrase", def: "in the end, after waiting a long time", example: "At last the holidays are here!", zh: "終於" },
    { front: "on time", pos: "phrase", def: "not late; at the correct time", example: "The train arrived on time.", zh: "準時" },
    { front: "in time", pos: "phrase", def: "early enough; not too late", example: "We got to the station just in time for the train.", zh: "及時" },
    { front: "at the moment", pos: "phrase", def: "now", example: "I am busy at the moment — can I call you back?", zh: "目前、此刻" },
    { front: "straight away", pos: "phrase", def: "immediately; now, without waiting", example: "When I heard the news, I phoned her straight away.", zh: "立刻、馬上" },
    { front: "at night", pos: "phrase", def: "during the night", example: "You can see the stars at night.", zh: "在夜晚" },
    /* ---------- Family & people ---------- */
    { front: "mother", pos: "n.", def: "a woman who has a child", example: "My mother works in a hospital.", zh: "母親" },
    { front: "father", pos: "n.", def: "a man who has a child", example: "My father drives me to school every day.", zh: "父親" },
    { front: "mum", pos: "n.", def: "an informal word for mother", example: "Mum, can I have a sandwich, please?", zh: "媽媽" },
    { front: "dad", pos: "n.", def: "an informal word for father", example: "My dad is teaching me to swim.", zh: "爸爸" },
    { front: "parent", pos: "n.", def: "a mother or father", example: "My parents both work in the city.", zh: "父母（之一）" },
    { front: "brother", pos: "n.", def: "a boy or man who has the same parents as you", example: "My brother is two years older than me.", zh: "兄弟" },
    { front: "sister", pos: "n.", def: "a girl or woman who has the same parents as you", example: "My sister and I share a bedroom.", zh: "姊妹" },
    { front: "son", pos: "n.", def: "someone's male child", example: "Their son is studying at university.", zh: "兒子" },
    { front: "daughter", pos: "n.", def: "someone's female child", example: "Mrs Lee has two daughters and one son.", zh: "女兒" },
    { front: "child", pos: "n.", def: "a young boy or girl", example: "Every child in the class got a book.", zh: "小孩" },
    { front: "baby", pos: "n.", def: "a very young child", example: "The baby is sleeping in her bed.", zh: "嬰兒" },
    { front: "grandmother", pos: "n.", def: "the mother of your mother or father", example: "My grandmother makes wonderful soup.", zh: "祖母、外婆" },
    { front: "grandfather", pos: "n.", def: "the father of your mother or father", example: "My grandfather tells us stories about the past.", zh: "祖父、外公" },
    { front: "grandma", pos: "n.", def: "an informal word for grandmother", example: "We visit Grandma every Sunday.", zh: "奶奶、外婆（口語）" },
    { front: "grandpa", pos: "n.", def: "an informal word for grandfather", example: "Grandpa taught me how to fish.", zh: "爺爺、外公（口語）" },
    { front: "grandparent", pos: "n.", def: "the mother or father of your parent", example: "My grandparents live by the sea.", zh: "祖父母（之一）" },
    { front: "grandson", pos: "n.", def: "the son of your child", example: "Their grandson visits them every holiday.", zh: "孫子、外孫" },
    { front: "granddaughter", pos: "n.", def: "the daughter of your child", example: "She often plays cards with her granddaughter.", zh: "孫女、外孫女" },
    { front: "grandchild", pos: "n.", def: "the child of your son or daughter", example: "My grandparents have six grandchildren.", zh: "孫子女、外孫子女" },
    { front: "uncle", pos: "n.", def: "the brother of your mother or father", example: "My uncle took us to the zoo.", zh: "叔伯、舅舅、姑丈、姨丈" },
    { front: "aunt", pos: "n.", def: "the sister of your mother or father", example: "My aunt lives in Canada.", zh: "姑姑、阿姨、嬸嬸、舅媽" },
    { front: "cousin", pos: "n.", def: "the child of your uncle or aunt", example: "I play video games with my cousin at the weekend.", zh: "堂／表兄弟姊妹" },
    { front: "nephew", pos: "n.", def: "the son of your brother or sister", example: "She bought a toy car for her nephew.", zh: "姪子、外甥" },
    { front: "niece", pos: "n.", def: "the daughter of your brother or sister", example: "My niece is learning to read.", zh: "姪女、外甥女" },
    { front: "husband", pos: "n.", def: "the man that a person is married to", example: "Her husband cooks dinner every evening.", zh: "丈夫" },
    { front: "wife", pos: "n.", def: "the woman that a person is married to", example: "Mr Brown and his wife live next door.", zh: "妻子" },
    { front: "married", pos: "adj.", def: "having a husband or wife", example: "My sister is married and has a baby.", zh: "已婚的" },
    { front: "single", pos: "adj.", def: "not married; only one", example: "My uncle is still single.", zh: "單身的；單一的" },
    { front: "family", pos: "n.", def: "a group of people such as parents and children", example: "There are five people in my family.", zh: "家庭、家人" },
    { front: "surname", pos: "n.", def: "your family name", example: "Her first name is Emma and her surname is Clark.", zh: "姓氏" },
    { front: "first name", pos: "n.", def: "the name your parents chose for you", example: "Write your first name at the top of the page.", zh: "名字" },
    { front: "name", pos: "n.", def: "the word people call you by", example: "What is your name?", zh: "名字、名稱" },
    { front: "friend", pos: "n.", def: "a person you like and know well", example: "I went shopping with my friends.", zh: "朋友" },
    { front: "best friend", pos: "n.", def: "the friend you like the most", example: "My best friend and I do everything together.", zh: "最好的朋友" },
    { front: "neighbour", pos: "n.", def: "a person who lives near you", example: "Our neighbours have a friendly dog.", zh: "鄰居" },
    { front: "person", pos: "n.", def: "one man, woman or child", example: "She is a very kind person.", zh: "人" },
    { front: "people", pos: "n.", def: "more than one person", example: "There were a lot of people at the concert.", zh: "人們" },
    { front: "man", pos: "n.", def: "an adult male person", example: "The man in the blue coat is my teacher.", zh: "男人" },
    { front: "woman", pos: "n.", def: "an adult female person", example: "That woman is my mother's friend.", zh: "女人" },
    { front: "boy", pos: "n.", def: "a male child", example: "The boys are playing football in the park.", zh: "男孩" },
    { front: "girl", pos: "n.", def: "a female child", example: "The girl in the red dress is my cousin.", zh: "女孩" },
    { front: "adult", pos: "n.", def: "a person who is fully grown", example: "Tickets cost ten pounds for adults.", zh: "成人" },
    { front: "teenager", pos: "n.", def: "a person between thirteen and nineteen years old", example: "Many teenagers enjoy playing computer games.", zh: "青少年" },
    { front: "twin", pos: "n.", def: "one of two children born at the same time to the same mother", example: "My twin brother looks exactly like me.", zh: "雙胞胎之一" },
    { front: "couple", pos: "n.", def: "two people who are together; two things", example: "A young couple moved into the house next door.", zh: "一對（夫妻／情侶）；幾個" },
    { front: "kid", pos: "n.", def: "an informal word for a child", example: "The kids are playing in the garden.", zh: "小孩（口語）" },
    { front: "relative", pos: "n.", def: "a person in your family", example: "All our relatives came to the wedding.", zh: "親戚" },
    { front: "age", pos: "n.", def: "how old someone or something is", example: "Children of all ages can join the club.", zh: "年齡" },
    { front: "be born", pos: "phrase", def: "to start life", example: "I was born in 2012.", zh: "出生" },
    { front: "grow up", pos: "phr. v.", def: "to change from a child into an adult", example: "She grew up in a small village.", zh: "長大" },
    { front: "get married", pos: "phrase", def: "to become husband and wife", example: "My aunt got married last June.", zh: "結婚" },
    { front: "penfriend", pos: "n.", def: "a friend you write letters or emails to but have not met", example: "My penfriend lives in Japan.", zh: "筆友" },
    /* ---------- Colours ---------- */
    { front: "red", pos: "adj.", def: "the colour of blood or a tomato", example: "She is wearing a red jacket.", zh: "紅色的" },
    { front: "blue", pos: "adj.", def: "the colour of the sky on a sunny day", example: "The sea looks very blue today.", zh: "藍色的" },
    { front: "green", pos: "adj.", def: "the colour of grass", example: "My school bag is green.", zh: "綠色的" },
    { front: "yellow", pos: "adj.", def: "the colour of the sun or a banana", example: "The taxi is yellow.", zh: "黃色的" },
    { front: "black", pos: "adj.", def: "the colour of the sky at night", example: "Dad wears black shoes to work.", zh: "黑色的" },
    { front: "white", pos: "adj.", def: "the colour of snow or milk", example: "The walls in my room are white.", zh: "白色的" },
    { front: "brown", pos: "adj.", def: "the colour of chocolate or wood", example: "She has long brown hair.", zh: "棕色的" },
    { front: "orange", pos: "adj.", def: "the colour between red and yellow", example: "The sky was orange in the evening.", zh: "橘色的" },
    { front: "pink", pos: "adj.", def: "a light red colour", example: "My little sister loves her pink dress.", zh: "粉紅色的" },
    { front: "purple", pos: "adj.", def: "a colour made from red and blue", example: "There are purple flowers in the garden.", zh: "紫色的" },
    { front: "grey", pos: "adj.", def: "the colour between black and white", example: "The sky is grey and it might rain.", zh: "灰色的" },
    { front: "gold", pos: "adj.", def: "the colour of the metal used in rings and coins", example: "She won a gold medal in the race.", zh: "金色的" },
    { front: "silver", pos: "adj.", def: "the colour of a shiny grey metal", example: "He wears a silver watch.", zh: "銀色的" },
    { front: "dark", pos: "adj.", def: "with little or no light; closer to black", example: "Her coat is dark blue.", zh: "暗的、深色的" },
    { front: "light", pos: "adj.", def: "pale in colour; not dark", example: "He painted his room light green.", zh: "淺色的；明亮的" },
    { front: "colour", pos: "n.", def: "red, blue, green and so on", example: "What is your favourite colour?", zh: "顏色" },
    /* ---------- Appearance ---------- */
    { front: "tall", pos: "adj.", def: "higher than most people or things", example: "My brother is very tall — nearly two metres!", zh: "高的" },
    { front: "short", pos: "adj.", def: "not tall; not long", example: "She is too short to reach the top shelf.", zh: "矮的、短的" },
    { front: "thin", pos: "adj.", def: "not fat; with little fat on the body", example: "The cat is very thin — we should feed it more.", zh: "瘦的、薄的" },
    { front: "slim", pos: "adj.", def: "thin in an attractive way", example: "My aunt stays slim because she runs every day.", zh: "苗條的" },
    { front: "fat", pos: "adj.", def: "with too much weight on the body", example: "Our dog is getting fat because he eats too much.", zh: "胖的" },
    { front: "pretty", pos: "adj.", def: "nice to look at; attractive", example: "What a pretty dress you are wearing!", zh: "漂亮的" },
    { front: "beautiful", pos: "adj.", def: "very nice to look at", example: "The view from the mountain is beautiful.", zh: "美麗的" },
    { front: "handsome", pos: "adj.", def: "nice to look at (usually for a man)", example: "The actor in that film is very handsome.", zh: "英俊的" },
    { front: "ugly", pos: "adj.", def: "not nice to look at", example: "I think that building is really ugly.", zh: "醜的" },
    { front: "young", pos: "adj.", def: "not old; having lived a short time", example: "She looks very young for her age.", zh: "年輕的" },
    { front: "old", pos: "adj.", def: "having lived a long time; not new", example: "My grandfather is old, but he is very strong.", zh: "老的、舊的" },
    { front: "good-looking", pos: "adj.", def: "attractive; nice to look at", example: "Her brother is tall and good-looking.", zh: "好看的" },
    { front: "elderly", pos: "adj.", def: "a polite word for old (about people)", example: "An elderly man sat down next to me on the bus.", zh: "年長的" },
    { front: "strong", pos: "adj.", def: "having a powerful body; not weak", example: "You need to be strong to carry these boxes.", zh: "強壯的" },
    { front: "cute", pos: "adj.", def: "pretty and lovely, like a baby or small animal", example: "Look at that cute little puppy!", zh: "可愛的" },
    { front: "lovely", pos: "adj.", def: "very nice or beautiful", example: "Thank you for a lovely evening.", zh: "極好的、可愛的" },
    { front: "hair", pos: "n.", def: "what grows on your head", example: "She has long black hair.", zh: "頭髮" },
    { front: "beard", pos: "n.", def: "hair that grows on a man's chin", example: "My uncle has a long grey beard.", zh: "鬍鬚" },
    { front: "moustache", pos: "n.", def: "hair that grows above a man's mouth", example: "The teacher with the moustache teaches history.", zh: "小鬍子" },
    { front: "blond", pos: "adj.", def: "with light yellow hair", example: "Both children have blond hair like their mother.", zh: "金髮的" },
    { front: "curly", pos: "adj.", def: "with many curls; not straight (hair)", example: "The baby has lovely curly hair.", zh: "捲的" },
    { front: "straight", pos: "adj.", def: "not curly; without bends", example: "Her hair is long and straight.", zh: "直的" },
    { front: "bald", pos: "adj.", def: "with no hair on the head", example: "My dad is going bald.", zh: "禿頭的" },
    { front: "glasses", pos: "n.", def: "two pieces of glass you wear to see better", example: "I wear glasses for reading.", zh: "眼鏡" },
    /* ---------- Personality ---------- */
    { front: "kind", pos: "adj.", def: "friendly and good to other people", example: "It was kind of you to help me.", zh: "仁慈的、體貼的" },
    { front: "friendly", pos: "adj.", def: "behaving in a kind and pleasant way", example: "Everyone in the village is very friendly.", zh: "友善的" },
    { front: "funny", pos: "adj.", def: "making you laugh", example: "He told us a very funny story.", zh: "好笑的" },
    { front: "clever", pos: "adj.", def: "able to learn and understand quickly", example: "She is clever and always gets good marks.", zh: "聰明的" },
    { front: "lazy", pos: "adj.", def: "not wanting to work or do anything", example: "Don't be lazy — help me clean the kitchen.", zh: "懶惰的" },
    { front: "polite", pos: "adj.", def: "speaking and behaving in a nice way to people", example: "It is polite to say thank you.", zh: "有禮貌的" },
    { front: "quiet", pos: "adj.", def: "not making much noise; not talking much", example: "Please be quiet in the library.", zh: "安靜的" },
    { front: "shy", pos: "adj.", def: "nervous about talking to people you do not know", example: "He is too shy to speak in class.", zh: "害羞的" },
    { front: "busy", pos: "adj.", def: "having a lot of things to do", example: "Mum is busy cooking dinner.", zh: "忙碌的" },
    { front: "careful", pos: "adj.", def: "thinking about what you do so nothing bad happens", example: "Be careful when you cross the road.", zh: "小心的" },
    { front: "famous", pos: "adj.", def: "known by many people", example: "Paris is famous for the Eiffel Tower.", zh: "有名的" },
    { front: "favourite", pos: "adj.", def: "liked more than all the others", example: "Blue is my favourite colour.", zh: "最喜愛的" },
    /* ---------- Pronoun words & quantifiers ---------- */
    { front: "everyone", pos: "n.", def: "all the people", example: "Everyone in the class passed the test.", zh: "每個人" },
    { front: "everybody", pos: "n.", def: "all the people; everyone", example: "Everybody enjoyed the party.", zh: "每個人、大家" },
    { front: "someone", pos: "n.", def: "a person, but you do not say who", example: "Someone left a bag on the bus.", zh: "某人" },
    { front: "somebody", pos: "n.", def: "a person; someone", example: "Somebody is knocking at the door.", zh: "某人" },
    { front: "anyone", pos: "n.", def: "any person; used in questions and negatives", example: "Does anyone know the answer?", zh: "任何人" },
    { front: "anybody", pos: "n.", def: "any person; anyone", example: "I did not see anybody in the garden.", zh: "任何人" },
    { front: "no one", pos: "n.", def: "not any person", example: "No one came to the meeting.", zh: "沒有人" },
    { front: "nobody", pos: "n.", def: "not any person; no one", example: "Nobody knows where the keys are.", zh: "沒有人" },
    { front: "everything", pos: "n.", def: "all the things", example: "Everything in this shop is cheap today.", zh: "每件事、一切" },
    { front: "something", pos: "n.", def: "a thing, but you do not say what", example: "There is something in my shoe.", zh: "某物、某事" },
    { front: "anything", pos: "n.", def: "any thing; used in questions and negatives", example: "Is there anything to eat?", zh: "任何東西" },
    { front: "nothing", pos: "n.", def: "not any thing", example: "There is nothing in the fridge.", zh: "什麼都沒有" },
    { front: "everywhere", pos: "adv.", def: "in all places", example: "I looked everywhere for my phone.", zh: "到處" },
    { front: "somewhere", pos: "adv.", def: "in a place, but you do not say where", example: "I left my umbrella somewhere at school.", zh: "某處" },
    { front: "anywhere", pos: "adv.", def: "in any place", example: "We can sit anywhere we like.", zh: "任何地方" },
    { front: "nowhere", pos: "adv.", def: "not in any place", example: "There was nowhere to park the car.", zh: "無處" },
    { front: "both", pos: "det.", def: "the two together", example: "Both my brothers play the guitar.", zh: "兩者都" },
    { front: "all", pos: "det.", def: "every one of; the whole of", example: "All the students went on the trip.", zh: "全部" },
    { front: "some", pos: "det.", def: "an amount or number of something", example: "Would you like some tea?", zh: "一些" },
    { front: "any", pos: "det.", def: "some; used in questions and negatives", example: "We do not have any milk left.", zh: "任何、一些" },
    { front: "many", pos: "det.", def: "a large number of", example: "There are many books in the library.", zh: "許多（可數）" },
    { front: "much", pos: "det.", def: "a large amount of", example: "I do not have much time before the bus comes.", zh: "許多（不可數）" },
    { front: "a few", pos: "phrase", def: "a small number of", example: "I invited a few friends for dinner.", zh: "一些、幾個" },
    { front: "a little", pos: "phrase", def: "a small amount of", example: "Can I have a little sugar in my coffee?", zh: "一點" },
    { front: "a lot of", pos: "phrase", def: "a large number or amount of", example: "There were a lot of people at the match.", zh: "很多" },
    { front: "lots of", pos: "phrase", def: "a large number or amount of; a lot of", example: "We took lots of photos on holiday.", zh: "很多" },
    { front: "enough", pos: "det.", def: "as much or as many as you need", example: "Do we have enough chairs for everyone?", zh: "足夠的" },
    { front: "other", pos: "det.", def: "different from this one; more of the same kind", example: "The other students are still in the classroom.", zh: "其他的" },
    { front: "another", pos: "det.", def: "one more; a different one", example: "Would you like another piece of cake?", zh: "另一個" },
    { front: "same", pos: "adj.", def: "not different; exactly like something else", example: "We go to the same school.", zh: "相同的" },
    { front: "different", pos: "adj.", def: "not the same", example: "My sister and I like different music.", zh: "不同的" },
    { front: "each", pos: "det.", def: "every one, thought of separately", example: "Each student has a desk.", zh: "每個" },
    { front: "every", pos: "det.", def: "all the people or things in a group", example: "I go swimming every Saturday.", zh: "每一" },
    { front: "few", pos: "det.", def: "not many", example: "Few people know about this little café.", zh: "很少的" },
    { front: "several", pos: "det.", def: "more than two but not very many", example: "I have read this book several times.", zh: "數個、幾個" },
    { front: "most", pos: "det.", def: "nearly all; the largest number of", example: "Most children in my class like sport.", zh: "大多數" },
    { front: "none", pos: "pron.", def: "not one; not any", example: "None of the shops were open.", zh: "一個也沒有" },
    { front: "only", pos: "adv.", def: "no more than; just", example: "The ticket costs only two pounds.", zh: "只有、僅僅" },
    { front: "together", pos: "adv.", def: "with each other", example: "We did the project together.", zh: "一起" },
    { front: "alone", pos: "adv.", def: "without other people", example: "She likes to read alone in her room.", zh: "獨自" },
    { front: "group", pos: "n.", def: "a number of people or things that are together", example: "A group of tourists stood outside the museum.", zh: "團體、群" },
    { front: "member", pos: "n.", def: "a person who belongs to a group or club", example: "He is a member of the school football club.", zh: "成員" },
    { front: "part", pos: "n.", def: "one piece of something bigger", example: "This is my favourite part of the film.", zh: "部分" },
    { front: "whole", pos: "adj.", def: "all of something; complete", example: "We spent the whole day at the beach.", zh: "整個的" },
    { front: "piece", pos: "n.", def: "one part of something", example: "Would you like a piece of cake?", zh: "一塊、一片" },
    { front: "bit", pos: "n.", def: "a small piece or amount", example: "I am a bit tired after the long walk.", zh: "一點、少量" },
    { front: "thing", pos: "n.", def: "an object; something that happens or that you talk about", example: "Put your things in your bag.", zh: "東西、事情" },
    { front: "stuff", pos: "n.", def: "an informal word for things", example: "There is a lot of stuff on your desk.", zh: "東西（口語）" },
    { front: "own", pos: "adj.", def: "belonging to you and no one else", example: "I have my own bedroom now.", zh: "自己的" },
    { front: "else", pos: "adv.", def: "other; different; more", example: "Would you like anything else?", zh: "其他、另外" },
    { front: "either", pos: "adv.", def: "also (used in negative sentences); one of two", example: "I can't swim, and my brother can't either.", zh: "也（不）；兩者之一" },
    { front: "each other", pos: "phrase", def: "used to say that two people do the same thing to the other", example: "The twins often help each other with homework.", zh: "互相" },
    /* ---------- Titles & people ---------- */
    { front: "Mr", pos: "n.", def: "a title for a man, used before his surname", example: "Mr Smith is our English teacher.", zh: "先生" },
    { front: "Mrs", pos: "n.", def: "a title for a married woman, used before her surname", example: "Mrs Jones lives next door to us.", zh: "太太、夫人" },
    { front: "Miss", pos: "n.", def: "a title for a woman who is not married", example: "Miss Green teaches us music.", zh: "小姐" },
    { front: "Ms", pos: "n.", def: "a title for a woman, married or not married", example: "Please give this form to Ms Taylor.", zh: "女士" },
    { front: "sir", pos: "n.", def: "a polite word for speaking to a man", example: "Excuse me, sir, you dropped your wallet.", zh: "先生（尊稱）" },
    { front: "madam", pos: "n.", def: "a polite word for speaking to a woman", example: "Good morning, madam. Can I help you?", zh: "女士（尊稱）" },
    { front: "gentleman", pos: "n.", def: "a polite word for a man", example: "A kind gentleman showed us the way.", zh: "紳士、男士" },
    { front: "lady", pos: "n.", def: "a polite word for a woman", example: "The lady at the desk gave me a map.", zh: "女士、淑女" },
    { front: "king", pos: "n.", def: "the most important man in a country's royal family", example: "The king lives in a big palace.", zh: "國王" },
    { front: "queen", pos: "n.", def: "the most important woman in a country's royal family", example: "The queen waved to the people.", zh: "女王、王后" },
    { front: "prince", pos: "n.", def: "the son of a king or queen", example: "The prince visited our city last week.", zh: "王子" },
    { front: "princess", pos: "n.", def: "the daughter of a king or queen", example: "The story is about a princess and a dragon.", zh: "公主" },
    { front: "stranger", pos: "n.", def: "a person you do not know", example: "Do not open the door to strangers.", zh: "陌生人" },
    { front: "visitor", pos: "n.", def: "a person who comes to see a place or person", example: "The museum gets thousands of visitors every year.", zh: "訪客、遊客" },
    { front: "owner", pos: "n.", def: "the person that something belongs to", example: "Who is the owner of this bicycle?", zh: "擁有者、主人" },
    { front: "winner", pos: "n.", def: "the person who wins", example: "The winner of the race got a gold cup.", zh: "獲勝者" },
    { front: "classmate", pos: "n.", def: "a person in the same class as you at school", example: "I did the project with two of my classmates.", zh: "同班同學" },
    { front: "flatmate", pos: "n.", def: "a person who shares a flat with you", example: "My sister and her flatmate cook dinner together.", zh: "室友" },
    /* ---------- Life & contact details ---------- */
    { front: "life", pos: "n.", def: "the time between being born and dying; the way you live", example: "She had a long and happy life.", zh: "生命、生活" },
    { front: "die", pos: "v.", def: "to stop living", example: "My grandfather died when I was six.", zh: "死亡" },
    { front: "dead", pos: "adj.", def: "not living any more", example: "The plant is dead because nobody watered it.", zh: "死的" },
    { front: "alive", pos: "adj.", def: "living; not dead", example: "The fish is still alive — put it back in the water.", zh: "活著的" },
    { front: "date of birth", pos: "n.", def: "the day, month and year when you were born", example: "Write your date of birth on the form.", zh: "出生日期" },
    { front: "address", pos: "n.", def: "the number, street and town where you live", example: "What is your home address?", zh: "地址" },
    { front: "phone number", pos: "n.", def: "the numbers you use to call someone", example: "Can I have your phone number, please?", zh: "電話號碼" },
    { front: "postcode", pos: "n.", def: "the letters and numbers at the end of an address", example: "Don't forget to write the postcode on the letter.", zh: "郵遞區號" },
    /* ---------- Description adjectives ---------- */
    { front: "nice", pos: "adj.", def: "pleasant; kind", example: "We had a nice time at the park.", zh: "好的、愉快的" },
    { front: "great", pos: "adj.", def: "very good; very big", example: "That is a great idea!", zh: "很棒的" },
    { front: "wonderful", pos: "adj.", def: "very good; excellent", example: "The weather was wonderful all week.", zh: "極好的" },
    { front: "brilliant", pos: "adj.", def: "very good; very clever", example: "The concert last night was brilliant.", zh: "傑出的、很棒的" },
    { front: "amazing", pos: "adj.", def: "very surprising and very good", example: "The view from the top was amazing.", zh: "令人驚嘆的" },
    { front: "special", pos: "adj.", def: "different from normal; important", example: "We cook a special dinner on New Year's Eve.", zh: "特別的" },
    { front: "important", pos: "adj.", def: "mattering a lot", example: "It is important to drink enough water.", zh: "重要的" },
    { front: "interesting", pos: "adj.", def: "keeping your attention; not boring", example: "This book about space is very interesting.", zh: "有趣的" },
    { front: "boring", pos: "adj.", def: "not interesting", example: "The film was so boring that I fell asleep.", zh: "無聊的" },
    { front: "difficult", pos: "adj.", def: "not easy; hard to do", example: "The last question in the test was difficult.", zh: "困難的" },
    { front: "easy", pos: "adj.", def: "not difficult", example: "The homework was easy — I finished in ten minutes.", zh: "容易的" },
    { front: "new", pos: "adj.", def: "made or bought a short time ago; not old", example: "I got a new phone for my birthday.", zh: "新的" },
    { front: "real", pos: "adj.", def: "true; not false or imagined", example: "Is that a real diamond?", zh: "真的" },
    { front: "sure", pos: "adj.", def: "knowing that something is true", example: "Are you sure the shop is open today?", zh: "確定的" },
    { front: "true", pos: "adj.", def: "correct; real", example: "Is it true that you are moving to London?", zh: "真實的" },
    { front: "wrong", pos: "adj.", def: "not correct; not right", example: "Sorry, you have the wrong number.", zh: "錯誤的" },
    { front: "right", pos: "adj.", def: "correct; good", example: "All my answers were right.", zh: "正確的；右邊的" },
    { front: "free", pos: "adj.", def: "costing nothing; not busy", example: "Children under five travel free on the bus.", zh: "免費的；有空的" },
    { front: "ready", pos: "adj.", def: "prepared and able to do something", example: "Dinner is ready — come and sit down.", zh: "準備好的" },
    { front: "safe", pos: "adj.", def: "not in danger; not dangerous", example: "Wear a helmet to keep your head safe.", zh: "安全的" },
    { front: "dangerous", pos: "adj.", def: "able to hurt you; not safe", example: "It is dangerous to swim here.", zh: "危險的" },
    { front: "strange", pos: "adj.", def: "unusual or surprising", example: "I heard a strange noise in the night.", zh: "奇怪的" },
    { front: "terrible", pos: "adj.", def: "very bad", example: "The traffic was terrible this morning.", zh: "糟糕的" },
    { front: "horrible", pos: "adj.", def: "very bad or unpleasant", example: "The medicine has a horrible taste.", zh: "可怕的、討厭的" },
    { front: "awful", pos: "adj.", def: "very bad", example: "The weather was awful, so we stayed at home.", zh: "很糟的" },
    { front: "perfect", pos: "adj.", def: "so good that it cannot be better", example: "It was a perfect day for a picnic.", zh: "完美的" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
