/* KET Prep extra bank: vocab wave 6 — common verbs, modals, phrasal verbs, question words, adverbs & everyday phrases */
(function () {
  var BANK = [
    /* ---------- Common verbs ---------- */
    { front: "know", pos: "v.", def: "to have information in your head", example: "Do you know the answer to this question?", zh: "知道、認識" },
    { front: "think", pos: "v.", def: "to use your mind; to believe something", example: "I think it will rain tomorrow.", zh: "想、認為" },
    { front: "want", pos: "v.", def: "to feel that you would like something", example: "I want a glass of water, please.", zh: "想要" },
    { front: "like", pos: "v.", def: "to enjoy something or think it is nice", example: "She likes chocolate ice cream.", zh: "喜歡" },
    { front: "love", pos: "v.", def: "to like someone or something very much", example: "I love my family very much.", zh: "愛、熱愛" },
    { front: "hate", pos: "v.", def: "to not like something at all", example: "He hates getting up early.", zh: "討厭" },
    { front: "enjoy", pos: "v.", def: "to get pleasure from something", example: "We enjoyed the film last night.", zh: "享受、喜愛" },
    { front: "need", pos: "v.", def: "to have to have something", example: "Plants need water and sunlight.", zh: "需要" },
    { front: "help", pos: "v.", def: "to do something useful for someone", example: "Can you help me carry these bags?", zh: "幫助" },
    { front: "give", pos: "v.", def: "to let someone have something", example: "She gave me a present for my birthday.", zh: "給" },
    { front: "take", pos: "v.", def: "to move something with you; to get something", example: "Take an umbrella — it might rain.", zh: "拿、帶" },
    { front: "get", pos: "v.", def: "to receive or buy something; to become", example: "I got a new phone for my birthday.", zh: "得到、變得" },
    { front: "go", pos: "v.", def: "to move from one place to another", example: "We go to school by bus.", zh: "去" },
    { front: "come", pos: "v.", def: "to move towards the person speaking", example: "Come to my house after school.", zh: "來" },
    { front: "see", pos: "v.", def: "to notice something with your eyes", example: "Can you see that bird in the tree?", zh: "看見" },
    { front: "look", pos: "v.", def: "to turn your eyes towards something", example: "Look! There's a rainbow in the sky.", zh: "看" },
    { front: "hear", pos: "v.", def: "to notice sounds with your ears", example: "I can hear music from the next room.", zh: "聽見" },
    { front: "find", pos: "v.", def: "to see something after looking for it", example: "I can't find my keys anywhere.", zh: "找到" },
    { front: "make", pos: "v.", def: "to create or produce something", example: "Mum is making a cake for the party.", zh: "做、製作" },
    { front: "do", pos: "v.", def: "to work at an activity or job", example: "I do my homework after dinner.", zh: "做" },
    { front: "put", pos: "v.", def: "to move something to a place", example: "Put the books on the shelf, please.", zh: "放" },
    { front: "bring", pos: "v.", def: "to carry something to the place you are going", example: "Bring your swimming things tomorrow.", zh: "帶來" },
    { front: "send", pos: "v.", def: "to make something go to another place", example: "I sent a birthday card to my aunt.", zh: "寄、傳送" },
    { front: "meet", pos: "v.", def: "to see and talk to someone", example: "Let's meet at the station at six.", zh: "見面、遇見" },
    { front: "use", pos: "v.", def: "to do something with a thing", example: "Can I use your pen for a minute?", zh: "使用" },
    { front: "try", pos: "v.", def: "to make an effort to do something", example: "Try to finish your homework before dinner.", zh: "嘗試" },
    { front: "start", pos: "v.", def: "to begin doing something", example: "The film starts at eight o'clock.", zh: "開始" },
    { front: "begin", pos: "v.", def: "to start", example: "The lesson begins at nine.", zh: "開始" },
    { front: "finish", pos: "v.", def: "to come to the end of something", example: "I finished my book last night.", zh: "完成、結束" },
    { front: "hold", pos: "v.", def: "to have something in your hands", example: "Can you hold my bag for a moment?", zh: "拿著、握住" },
    { front: "keep", pos: "v.", def: "to have something and not give it away; to stay the same", example: "You can keep the book — I have another one.", zh: "保留、保持" },
    { front: "stand", pos: "v.", def: "to be on your feet, not sitting", example: "We had to stand on the crowded bus.", zh: "站立" },
    { front: "sit", pos: "v.", def: "to rest on a chair or the floor", example: "Come and sit next to me.", zh: "坐" },
    { front: "turn", pos: "v.", def: "to move round; to change direction", example: "Turn the key to open the door.", zh: "轉動、轉向" },
    { front: "choose", pos: "v.", def: "to decide which one you want", example: "You can choose any cake you like.", zh: "選擇" },
    { front: "decide", pos: "v.", def: "to think about something and choose what to do", example: "We decided to go to the beach.", zh: "決定" },
    { front: "believe", pos: "v.", def: "to think that something is true", example: "I don't believe his story about the shark.", zh: "相信" },
    { front: "guess", pos: "v.", def: "to give an answer when you are not sure", example: "Guess how old my grandad is!", zh: "猜" },
    { front: "become", pos: "v.", def: "to change into something", example: "She wants to become a doctor.", zh: "成為、變成" },
    { front: "happen", pos: "v.", def: "to take place", example: "What happened at school today?", zh: "發生" },
    { front: "seem", pos: "v.", def: "to look or feel like something is true", example: "You seem tired today. Are you OK?", zh: "似乎、看起來" },
    { front: "sound", pos: "v.", def: "to seem a certain way when you hear about it", example: "A trip to the beach? That sounds great!", zh: "聽起來" },
    { front: "let", pos: "v.", def: "to allow someone to do something", example: "Mum let me stay up late on Friday.", zh: "讓、允許" },
    { front: "thank", pos: "v.", def: "to tell someone you are happy about their help", example: "Don't forget to thank your teacher.", zh: "感謝" },
    { front: "welcome", pos: "v.", def: "to greet someone in a friendly way when they arrive", example: "The teacher welcomed the new student.", zh: "歡迎" },
    { front: "cook", pos: "v.", def: "to make food hot and ready to eat", example: "Dad is cooking dinner tonight.", zh: "煮、烹飪" },
    { front: "marry", pos: "v.", def: "to become someone's husband or wife", example: "My uncle married his best friend from school.", zh: "結婚" },
    { front: "reply", pos: "v.", def: "to answer someone", example: "She didn't reply to my message.", zh: "回覆" },
    { front: "improve", pos: "v.", def: "to become better or make something better", example: "Your English is improving every week!", zh: "進步、改善" },
    { front: "revise", pos: "v.", def: "to study something again before a test", example: "I need to revise for the maths exam.", zh: "複習" },
    { front: "prefer", pos: "v.", def: "to like one thing more than another", example: "I prefer tea to coffee.", zh: "比較喜歡" },
    { front: "mind", pos: "v.", def: "to feel unhappy about something", example: "Do you mind if I open the window?", zh: "介意" },
    { front: "matter", pos: "v.", def: "to be important", example: "It doesn't matter if we're a little late.", zh: "要緊、重要" },
    { front: "waste", pos: "v.", def: "to use something in a bad way", example: "Don't waste water — turn off the tap.", zh: "浪費" },
    { front: "plan", pos: "v.", def: "to think about and decide what you will do", example: "We are planning a surprise party for Dad.", zh: "計劃" },
    { front: "exchange", pos: "v.", def: "to give something and get something back", example: "Can I exchange this shirt for a bigger one?", zh: "交換、更換" },
    { front: "complain", pos: "v.", def: "to say that you are not happy about something", example: "He complained that the soup was cold.", zh: "抱怨" },
    { front: "introduce", pos: "v.", def: "to tell someone another person's name for the first time", example: "Let me introduce you to my cousin.", zh: "介紹" },
    { front: "greet", pos: "v.", def: "to say hello to someone", example: "The teacher greeted us at the classroom door.", zh: "打招呼、問候" },
    { front: "disagree", pos: "v.", def: "to have a different opinion", example: "I disagree — I think blue is nicer than green.", zh: "不同意" },
    { front: "accept", pos: "v.", def: "to say yes to something", example: "She accepted the invitation to the party.", zh: "接受" },
    { front: "refuse", pos: "v.", def: "to say no to something", example: "He refused to eat his vegetables.", zh: "拒絕" },
    { front: "belong", pos: "v.", def: "to be someone's; to be a member of a group", example: "This pencil case belongs to Anna.", zh: "屬於" },
    { front: "compare", pos: "v.", def: "to look at two things to see how they are different", example: "Compare the prices before you buy.", zh: "比較" },
    { front: "continue", pos: "v.", def: "to keep doing something", example: "We continued walking until it got dark.", zh: "繼續" },
    { front: "imagine", pos: "v.", def: "to make a picture of something in your mind", example: "Imagine you are on a beautiful beach.", zh: "想像" },
    { front: "notice", pos: "v.", def: "to see or hear something", example: "Did you notice her new haircut?", zh: "注意到" },
    { front: "offer", pos: "v.", def: "to say you will give or do something for someone", example: "He offered to carry my heavy bag.", zh: "主動提供" },
    { front: "receive", pos: "v.", def: "to get something that someone sends or gives you", example: "I received a letter from my pen friend.", zh: "收到" },
    { front: "record", pos: "v.", def: "to keep sound or pictures on a phone or computer", example: "She recorded a video of her cat.", zh: "錄製" },
    { front: "hide", pos: "v.", def: "to go or put something where nobody can see", example: "The dog hid under the bed during the storm.", zh: "躲藏、隱藏" },
    { front: "stick", pos: "v.", def: "to join something to something with glue", example: "Stick the photo on the first page.", zh: "黏貼" },
    { front: "care", pos: "v.", def: "to think that something is important", example: "She really cares about her friends.", zh: "在乎、關心" },
    { front: "complete", pos: "v.", def: "to finish something", example: "Complete the exercise on page ten.", zh: "完成" },
    { front: "cover", pos: "v.", def: "to put something over something else", example: "Cover the food so the flies can't get it.", zh: "覆蓋" },
    { front: "enter", pos: "v.", def: "to go into a place; to join a competition", example: "Please knock before you enter the room.", zh: "進入、參加" },
    { front: "fill", pos: "v.", def: "to make something full", example: "Fill the bottle with water.", zh: "裝滿、填滿" },
    { front: "mend", pos: "v.", def: "to fix something that is broken", example: "Grandpa mended my broken toy car.", zh: "修理" },
    { front: "reach", pos: "v.", def: "to arrive at a place; to touch something far away", example: "I can't reach the top shelf.", zh: "到達、伸手觸到" },
    { front: "chase", pos: "v.", def: "to run after someone or something", example: "The dog chased the cat up a tree.", zh: "追趕" },
    { front: "fetch", pos: "v.", def: "to go and get something and bring it back", example: "Can you fetch my glasses from the kitchen?", zh: "去拿來" },
    { front: "lie", pos: "v.", def: "to put your body flat; to say something that is not true", example: "He lay on the grass and looked at the clouds.", zh: "躺；說謊" },
    { front: "lead", pos: "v.", def: "to go in front and show the way", example: "The guide led us through the old town.", zh: "帶領" },
    { front: "turn round", pos: "phr. v.", def: "to move so you face the other way", example: "Turn round and look at the camera.", zh: "轉身" },
    { front: "invite someone", pos: "phrase", def: "to ask someone to come to a party or event", example: "She invited everyone in the class to her party.", zh: "邀請某人" },
    { front: "save money", pos: "phrase", def: "to keep money to use later", example: "He is saving money for a new bike.", zh: "存錢" },
    { front: "spend time", pos: "phrase", def: "to use time doing something", example: "I spend a lot of time playing with my dog.", zh: "花時間" },
    /* ---------- Modals & verb structures ---------- */
    { front: "must", pos: "v.", def: "used to say something is very important to do", example: "You must wear a seat belt in the car.", zh: "必須" },
    { front: "should", pos: "v.", def: "used to say something is a good idea", example: "You should go to bed earlier.", zh: "應該" },
    { front: "could", pos: "v.", def: "was able to; used to ask politely", example: "Could you open the window, please?", zh: "能、可以（過去式／客氣）" },
    { front: "might", pos: "v.", def: "used to say something is possible", example: "It might rain later, so take a coat.", zh: "可能" },
    { front: "shall", pos: "v.", def: "used to make offers and suggestions with I and we", example: "Shall we go to the park?", zh: "（提議）要不要" },
    { front: "will", pos: "v.", def: "used to talk about the future", example: "I will call you tonight.", zh: "將會" },
    { front: "would", pos: "v.", def: "used to ask politely and talk about imagined things", example: "Would you like some tea?", zh: "（客氣、假設）會" },
    { front: "have to", pos: "phrase", def: "to need to do something", example: "I have to finish my homework before I play.", zh: "必須" },
    { front: "be able to", pos: "phrase", def: "to can do something", example: "She was able to swim when she was four.", zh: "能夠" },
    { front: "need to", pos: "phrase", def: "used to say something is necessary", example: "You need to drink more water in summer.", zh: "需要" },
    { front: "used to", pos: "phrase", def: "about something that happened often in the past", example: "We used to live in a small village.", zh: "過去常常" },
    { front: "had better", pos: "phrase", def: "used to say what someone should do", example: "You had better take an umbrella.", zh: "最好" },
    { front: "would like", pos: "phrase", def: "a polite way to say want", example: "I would like a cheese sandwich, please.", zh: "想要（客氣）" },
    { front: "would rather", pos: "phrase", def: "to prefer to do something", example: "I would rather stay at home tonight.", zh: "寧願" },
    /* ---------- Phrasal verbs ---------- */
    { front: "look for", pos: "phr. v.", def: "to try to find something", example: "I'm looking for my other shoe.", zh: "尋找" },
    { front: "look at", pos: "phr. v.", def: "to turn your eyes to something", example: "Look at this funny picture!", zh: "看著" },
    { front: "look forward to", pos: "phr. v.", def: "to feel happy about something that will happen", example: "I'm looking forward to the summer holidays.", zh: "期待" },
    { front: "find out", pos: "phr. v.", def: "to learn new information", example: "Let's find out what time the film starts.", zh: "查明、得知" },
    { front: "go out", pos: "phr. v.", def: "to leave your house to do something fun", example: "We went out for pizza on Friday.", zh: "外出" },
    { front: "come from", pos: "phr. v.", def: "to be born in or be from a place", example: "She comes from Taiwan.", zh: "來自" },
    { front: "put down", pos: "phr. v.", def: "to place something on a table or the floor", example: "Put down that heavy box and have a rest.", zh: "放下" },
    { front: "take away", pos: "phr. v.", def: "to remove something; food you carry home to eat", example: "The waiter took away the empty plates.", zh: "拿走、外帶" },
    { front: "give back", pos: "phr. v.", def: "to return something to its owner", example: "Please give back my ruler when you finish.", zh: "歸還" },
    { front: "bring back", pos: "phr. v.", def: "to return with something", example: "Can you bring back some milk from the shop?", zh: "帶回來" },
    { front: "come over", pos: "phr. v.", def: "to visit someone at their house", example: "Why don't you come over after school?", zh: "過來（拜訪）" },
    { front: "go away", pos: "phr. v.", def: "to leave a place or person", example: "The rain won't go away today.", zh: "離開、走開" },
    { front: "run away", pos: "phr. v.", def: "to leave a place quickly by running", example: "The cat ran away when the dog barked.", zh: "跑走、逃走" },
    { front: "throw away", pos: "phr. v.", def: "to put something in the rubbish", example: "Don't throw away those old magazines — I want them.", zh: "丟掉" },
    { front: "write down", pos: "phr. v.", def: "to write something on paper so you remember it", example: "Write down my phone number.", zh: "寫下" },
    { front: "look up", pos: "phr. v.", def: "to find information in a book or online", example: "Look up the word in your dictionary.", zh: "查詢" },
    { front: "get in", pos: "phr. v.", def: "to enter a car or a place", example: "Get in the car — we're leaving now!", zh: "進入、上（車）" },
    { front: "get out", pos: "phr. v.", def: "to leave a car or a place", example: "We got out of the taxi at the hotel.", zh: "出去、下（車）" },
    { front: "go up", pos: "phr. v.", def: "to move to a higher place; to become more", example: "The lift is going up to the fifth floor.", zh: "上升、上漲" },
    { front: "go down", pos: "phr. v.", def: "to move to a lower place; to become less", example: "Go down the stairs and turn left.", zh: "下降、下去" },
    { front: "stay up", pos: "phr. v.", def: "to not go to bed", example: "We stayed up late to watch the stars.", zh: "熬夜" },
    { front: "get together", pos: "phr. v.", def: "to meet with friends or family", example: "Our family gets together every Chinese New Year.", zh: "聚會、相聚" },
    { front: "cheer up", pos: "phr. v.", def: "to become happier or make someone happier", example: "I bought her flowers to cheer her up.", zh: "振作、使開心" },
    { front: "calm down", pos: "phr. v.", def: "to become quiet and less worried or angry", example: "Calm down and tell me what happened.", zh: "冷靜下來" },
    { front: "slow down", pos: "phr. v.", def: "to go less fast", example: "Slow down! You're walking too fast for me.", zh: "放慢速度" },
    { front: "speed up", pos: "phr. v.", def: "to go faster", example: "The train speeded up after it left the station.", zh: "加速" },
    { front: "hold on", pos: "phr. v.", def: "to wait for a short time", example: "Hold on a minute — I'm nearly ready.", zh: "稍等" },
    { front: "hang on", pos: "phr. v.", def: "to wait a moment", example: "Hang on, I'll just get my coat.", zh: "等一下" },
    { front: "move away", pos: "phr. v.", def: "to go to live in a different place", example: "My best friend moved away last year.", zh: "搬走" },
    { front: "look out", pos: "phr. v.", def: "used to warn someone of danger", example: "Look out! There's a car coming!", zh: "小心、當心" },
    /* ---------- Verb + preposition ---------- */
    { front: "think about", pos: "phrase", def: "to have something in your mind", example: "I'm thinking about what to buy Mum.", zh: "考慮、想著" },
    { front: "talk about", pos: "phrase", def: "to speak about a subject", example: "We talked about our favourite films.", zh: "談論" },
    { front: "dream about", pos: "phrase", def: "to see something in your sleep; to hope for something", example: "She dreams about becoming a pilot.", zh: "夢見、夢想" },
    { front: "hear about", pos: "phrase", def: "to get news about something", example: "Did you hear about the new sports centre?", zh: "聽說" },
    { front: "know about", pos: "phrase", def: "to have information about something", example: "He knows a lot about dinosaurs.", zh: "了解、知道關於" },
    { front: "learn about", pos: "phrase", def: "to get knowledge about a subject", example: "We learnt about the moon in science class.", zh: "學習關於" },
    { front: "ask for", pos: "phrase", def: "to say that you want something", example: "She asked for a glass of orange juice.", zh: "要求、請求" },
    { front: "wait for", pos: "phrase", def: "to stay until someone or something comes", example: "We waited for the bus for twenty minutes.", zh: "等候" },
    { front: "pay for", pos: "phrase", def: "to give money for something", example: "Dad paid for our cinema tickets.", zh: "付錢買" },
    { front: "look like", pos: "phrase", def: "to have the same appearance as", example: "She looks like her mother.", zh: "看起來像" },
    { front: "sound like", pos: "phrase", def: "to seem a certain way when you hear it", example: "That sounds like a great plan!", zh: "聽起來像" },
    { front: "feel like", pos: "phrase", def: "to want something", example: "I feel like eating ice cream.", zh: "想要（做某事）" },
    /* ---------- Question words ---------- */
    { front: "who", pos: "phrase", def: "used to ask about a person", example: "Who is that boy next to Maria?", zh: "誰" },
    { front: "what", pos: "phrase", def: "used to ask about a thing", example: "What is your favourite colour?", zh: "什麼" },
    { front: "where", pos: "phrase", def: "used to ask about a place", example: "Where do you live?", zh: "哪裡" },
    { front: "when", pos: "phrase", def: "used to ask about a time", example: "When does the film start?", zh: "何時" },
    { front: "why", pos: "phrase", def: "used to ask about a reason", example: "Why are you laughing?", zh: "為什麼" },
    { front: "how", pos: "phrase", def: "used to ask about the way something happens", example: "How do you spell your name?", zh: "如何" },
    { front: "which", pos: "phrase", def: "used to ask about one from a group", example: "Which cake would you like — chocolate or lemon?", zh: "哪一個" },
    { front: "whose", pos: "phrase", def: "used to ask who something belongs to", example: "Whose jacket is this on the chair?", zh: "誰的" },
    { front: "how much", pos: "phrase", def: "used to ask about price or amount", example: "How much is this T-shirt?", zh: "多少（錢、量）" },
    { front: "how many", pos: "phrase", def: "used to ask about a number of things", example: "How many brothers do you have?", zh: "多少（個數）" },
    { front: "how often", pos: "phrase", def: "used to ask about how many times", example: "How often do you play tennis?", zh: "多常、多久一次" },
    { front: "how old", pos: "phrase", def: "used to ask about age", example: "How old is your little sister?", zh: "幾歲" },
    { front: "how long", pos: "phrase", def: "used to ask about time or length", example: "How long does the journey take?", zh: "多久、多長" },
    /* ---------- Conjunctions & connectors ---------- */
    { front: "because", pos: "phrase", def: "used to give a reason", example: "I stayed at home because I was ill.", zh: "因為" },
    { front: "but", pos: "phrase", def: "used to join two different ideas", example: "I like tea, but I don't like coffee.", zh: "但是" },
    { front: "or", pos: "phrase", def: "used to give a choice", example: "Would you like juice or water?", zh: "或者" },
    { front: "if", pos: "phrase", def: "used to talk about something that may happen", example: "If it rains, we'll stay inside.", zh: "如果" },
    { front: "while", pos: "phrase", def: "during the time that something happens", example: "Dad cooked dinner while I did my homework.", zh: "當…的時候" },
    { front: "than", pos: "phrase", def: "used to compare two things", example: "My brother is taller than me.", zh: "比" },
    { front: "and", pos: "phrase", def: "used to join words or ideas together", example: "I bought apples and bananas.", zh: "和、而且" },
    { front: "so that", pos: "phrase", def: "used to say why someone does something", example: "Speak slowly so that everyone can understand.", zh: "以便" },
    { front: "because of", pos: "phrase", def: "used before a noun to give a reason", example: "The match was cancelled because of the rain.", zh: "由於" },
    { front: "since", pos: "phrase", def: "from a time in the past until now", example: "We have lived here since 2020.", zh: "自從" },
    /* ---------- Adverbs ---------- */
    { front: "very", pos: "adv.", def: "used to make an adjective stronger", example: "This soup is very hot.", zh: "非常" },
    { front: "really", pos: "adv.", def: "very; used to make something stronger", example: "I really love this song.", zh: "真的、非常" },
    { front: "quite", pos: "adv.", def: "a little but not very", example: "The test was quite easy.", zh: "相當、蠻" },
    { front: "so", pos: "adv.", def: "very; used to make something stronger", example: "I'm so happy to see you!", zh: "如此、非常" },
    { front: "almost", pos: "adv.", def: "nearly but not completely", example: "It's almost time for lunch.", zh: "幾乎" },
    { front: "nearly", pos: "adv.", def: "almost", example: "I'm nearly ten — my birthday is next week.", zh: "將近、幾乎" },
    { front: "just", pos: "adv.", def: "a very short time ago; only", example: "I've just finished my homework.", zh: "剛剛、只是" },
    { front: "even", pos: "adv.", def: "used to show something is surprising", example: "It was cold in June — it even snowed!", zh: "甚至" },
    { front: "also", pos: "adv.", def: "too; as well", example: "She plays the piano and also sings.", zh: "也" },
    { front: "too", pos: "adv.", def: "also; more than you want", example: "I like ice cream too.", zh: "也；太" },
    { front: "carefully", pos: "adv.", def: "with care and attention", example: "Read the questions carefully before you answer.", zh: "小心地、仔細地" },
    { front: "quietly", pos: "adv.", def: "without much noise", example: "Please close the door quietly.", zh: "安靜地" },
    { front: "loudly", pos: "adv.", def: "with a lot of noise", example: "Don't talk so loudly in the library.", zh: "大聲地" },
    { front: "easily", pos: "adv.", def: "without any problems", example: "She won the race easily.", zh: "輕易地" },
    { front: "badly", pos: "adv.", def: "not well", example: "He played badly and lost the game.", zh: "糟糕地" },
    { front: "luckily", pos: "adv.", def: "used to say something good happened", example: "Luckily, the rain stopped before the picnic.", zh: "幸運地" },
    { front: "fortunately", pos: "adv.", def: "luckily", example: "Fortunately, nobody was hurt in the accident.", zh: "幸好" },
    { front: "especially", pos: "adv.", def: "more than usual; more than others", example: "I love fruit, especially mangoes.", zh: "尤其" },
    { front: "perhaps", pos: "adv.", def: "maybe; possibly", example: "Perhaps we can go swimming tomorrow.", zh: "也許" },
    { front: "maybe", pos: "adv.", def: "possibly; perhaps", example: "Maybe he's late because of the traffic.", zh: "可能、也許" },
    { front: "actually", pos: "adv.", def: "really; used to say what is true", example: "Actually, I've never been to Japan.", zh: "其實、事實上" },
    { front: "probably", pos: "adv.", def: "very likely to be true", example: "It will probably rain this afternoon.", zh: "很可能" },
    { front: "certainly", pos: "adv.", def: "surely; without doubt", example: "\"Can you help me?\" \"Certainly!\"", zh: "當然、必定" },
    { front: "rarely", pos: "adv.", def: "not often", example: "We rarely eat out on weekdays.", zh: "很少" },
    { front: "instead", pos: "adv.", def: "in the place of something else", example: "There was no juice, so I drank water instead.", zh: "反而、改為" },
    { front: "as well", pos: "phrase", def: "also; too", example: "Can my friend come to the party as well?", zh: "也" },
    { front: "at least", pos: "phrase", def: "not less than; the smallest amount", example: "Drink at least two glasses of water a day.", zh: "至少" },
    { front: "anyway", pos: "adv.", def: "used to change the subject or add something", example: "It was raining, but we went out anyway.", zh: "反正、無論如何" },
    /* ---------- Place & direction words ---------- */
    { front: "here", pos: "adv.", def: "in this place", example: "Come here and look at this!", zh: "這裡" },
    { front: "there", pos: "adv.", def: "in that place", example: "Put the box over there, please.", zh: "那裡" },
    { front: "away", pos: "adv.", def: "not here; to another place", example: "My parents are away this weekend.", zh: "不在、離開" },
    { front: "over there", pos: "phrase", def: "in that place, not near here", example: "The toilets are over there, next to the café.", zh: "在那邊" },
    { front: "close to", pos: "phrase", def: "near", example: "Our school is close to the park.", zh: "靠近" },
    { front: "somewhere else", pos: "phrase", def: "in a different place", example: "This café is full — let's go somewhere else.", zh: "別的地方" },
    { front: "this way", pos: "phrase", def: "in this direction", example: "Come this way, please. The exit is here.", zh: "這邊、往這走" },
    { front: "go straight on", pos: "phrase", def: "to continue in the same direction", example: "Go straight on and the bank is on your right.", zh: "直走" },
    { front: "go home", pos: "phrase", def: "to return to your house", example: "It's late — I have to go home now.", zh: "回家" },
    { front: "come here", pos: "phrase", def: "to move to this place", example: "Come here and help me with this box.", zh: "過來" },
    { front: "get home", pos: "phrase", def: "to arrive at your house", example: "What time did you get home last night?", zh: "到家" },
    { front: "leave home", pos: "phrase", def: "to go out of your house", example: "I leave home at half past seven every morning.", zh: "出門" },
    /* ---------- Greetings & politeness ---------- */
    { front: "hello", pos: "phrase", def: "a word you say when you meet someone", example: "Hello! How are you today?", zh: "你好" },
    { front: "hi", pos: "phrase", def: "an informal way to say hello", example: "Hi, Tom! Nice to see you.", zh: "嗨" },
    { front: "goodbye", pos: "phrase", def: "a word you say when you leave someone", example: "Goodbye! See you on Monday.", zh: "再見" },
    { front: "good morning", pos: "phrase", def: "a greeting used before midday", example: "Good morning, class! Please sit down.", zh: "早安" },
    { front: "good afternoon", pos: "phrase", def: "a greeting used after midday", example: "Good afternoon! Do you have an appointment?", zh: "午安" },
    { front: "good evening", pos: "phrase", def: "a greeting used in the evening", example: "Good evening! Welcome to our restaurant.", zh: "晚安（見面時）" },
    { front: "good night", pos: "phrase", def: "what you say before someone goes to bed", example: "Good night! Sleep well.", zh: "晚安（道別／睡前）" },
    { front: "please", pos: "phrase", def: "a polite word used when you ask for something", example: "Can I have some water, please?", zh: "請" },
    { front: "thank you", pos: "phrase", def: "words you say when someone helps or gives you something", example: "Thank you for the lovely present!", zh: "謝謝你" },
    { front: "thanks", pos: "phrase", def: "an informal way to say thank you", example: "Thanks for your help!", zh: "謝啦" },
    { front: "sorry", pos: "phrase", def: "a word you say when you do something wrong", example: "Sorry I'm late — the bus didn't come.", zh: "對不起" },
    { front: "pardon", pos: "phrase", def: "used to ask someone to say something again", example: "Pardon? Could you say that again, please?", zh: "抱歉，請再說一次" },
    { front: "see you soon", pos: "phrase", def: "a friendly way to say goodbye", example: "Bye, Grandma! See you soon!", zh: "很快再見" },
    { front: "see you later", pos: "phrase", def: "goodbye for now", example: "I'm going to the shop. See you later!", zh: "待會見" },
    { front: "take care", pos: "phrase", def: "a friendly way to say goodbye; be careful", example: "Take care! Have a safe journey.", zh: "保重" },
    { front: "happy birthday", pos: "phrase", def: "what you say to someone on their birthday", example: "Happy birthday! Here's a little present for you.", zh: "生日快樂" },
    { front: "congratulations", pos: "phrase", def: "what you say when something good happens to someone", example: "Congratulations! You won first prize!", zh: "恭喜" },
    { front: "excuse me", pos: "phrase", def: "used to get someone's attention politely", example: "Excuse me, where is the train station?", zh: "不好意思、打擾一下" },
    { front: "of course", pos: "phrase", def: "yes, certainly", example: "\"Can I borrow your pen?\" \"Of course!\"", zh: "當然" },
    { front: "never mind", pos: "phrase", def: "used to say something is not a problem", example: "\"I forgot the tickets.\" \"Never mind, we can print them.\"", zh: "沒關係" },
    { front: "no problem", pos: "phrase", def: "used to say something is easy or OK", example: "\"Thanks for driving me.\" \"No problem!\"", zh: "沒問題" },
    { front: "you are welcome", pos: "phrase", def: "a polite answer when someone thanks you", example: "\"Thank you so much!\" \"You're welcome.\"", zh: "不客氣" },
    { front: "good luck", pos: "phrase", def: "what you say to wish someone success", example: "Good luck in your exam tomorrow!", zh: "祝好運" },
    { front: "well done", pos: "phrase", def: "what you say when someone does something well", example: "Well done! You got full marks!", zh: "做得好" },
    /* ---------- Everyday interaction phrases ---------- */
    { front: "hurry up", pos: "phrase", def: "used to tell someone to be quick", example: "Hurry up! The bus is coming!", zh: "快一點" },
    { front: "watch out", pos: "phrase", def: "used to warn someone about danger", example: "Watch out! The floor is wet.", zh: "小心" },
    { front: "be careful", pos: "phrase", def: "used to tell someone to take care", example: "Be careful with those scissors.", zh: "小心點" },
    { front: "come on", pos: "phrase", def: "used to tell someone to hurry or try harder", example: "Come on! We're going to be late.", zh: "快點、加油" },
    { front: "by the way", pos: "phrase", def: "used to add something new to a conversation", example: "By the way, did you feed the cat?", zh: "順帶一提" },
    { front: "for example", pos: "phrase", def: "used to give an example", example: "I like fruit — for example, apples and grapes.", zh: "例如" },
    { front: "such as", pos: "phrase", def: "like; for example", example: "She enjoys sports such as tennis and swimming.", zh: "例如、像是" },
    { front: "in fact", pos: "phrase", def: "used to say what is really true", example: "It looks hard, but in fact it's easy.", zh: "事實上" },
    { front: "in the end", pos: "phrase", def: "finally, after everything", example: "In the end, we decided to stay at home.", zh: "最後" },
    { front: "at all", pos: "phrase", def: "used to make a negative stronger", example: "I don't like spiders at all.", zh: "一點也（不）" },
    { front: "a lot", pos: "phrase", def: "very much; a large amount", example: "Thanks a lot for your help!", zh: "很多、非常" },
    { front: "how about", pos: "phrase", def: "used to make a suggestion", example: "How about going to the cinema tonight?", zh: "…如何？" },
    { front: "what about", pos: "phrase", def: "used to suggest something or ask about it", example: "What about a picnic in the park?", zh: "…怎麼樣？" },
    { front: "I would love to", pos: "phrase", def: "a friendly way to say yes to an invitation", example: "\"Do you want to come?\" \"I'd love to!\"", zh: "我很樂意" },
    { front: "good idea", pos: "phrase", def: "used to agree with a plan", example: "\"Let's take a taxi.\" \"Good idea!\"", zh: "好主意" },
    { front: "no idea", pos: "phrase", def: "used to say you do not know", example: "\"Where's Tom?\" \"No idea — I haven't seen him.\"", zh: "不知道" },
    { front: "let me see", pos: "phrase", def: "used when you need time to think", example: "Let me see... I think the bus leaves at ten.", zh: "讓我想想" },
    { front: "I think so", pos: "phrase", def: "used to say yes when you are not completely sure", example: "\"Is the shop open?\" \"I think so.\"", zh: "我想是的" },
    { front: "I hope so", pos: "phrase", def: "used to say you want something to be true", example: "\"Will it be sunny?\" \"I hope so!\"", zh: "希望如此" },
    { front: "me too", pos: "phrase", def: "used to say the same is true for you", example: "\"I love pizza.\" \"Me too!\"", zh: "我也是" },
    { front: "not at all", pos: "phrase", def: "a polite answer to thank you; not in any way", example: "\"Thanks for waiting.\" \"Not at all.\"", zh: "不客氣、一點也不" },
    { front: "that is right", pos: "phrase", def: "used to say something is correct", example: "\"You're from Taipei?\" \"That's right.\"", zh: "沒錯" },
    { front: "anything else", pos: "phrase", def: "used to ask if someone wants more", example: "\"Anything else?\" \"No, thanks. That's all.\"", zh: "還需要別的嗎" },
    { front: "here you are", pos: "phrase", def: "what you say when you give something to someone", example: "\"Can I see the menu?\" \"Here you are.\"", zh: "給你" },
    { front: "just a minute", pos: "phrase", def: "used to ask someone to wait a short time", example: "Just a minute — I'm putting on my shoes.", zh: "等一下" },
    { front: "wait a moment", pos: "phrase", def: "used to ask someone to wait briefly", example: "Wait a moment, please. I'll check for you.", zh: "請稍候" },
    { front: "one moment", pos: "phrase", def: "a short time; please wait", example: "One moment, please. The manager is coming.", zh: "稍等片刻" },
    { front: "go ahead", pos: "phrase", def: "used to give someone permission", example: "\"Can I use your phone?\" \"Sure, go ahead.\"", zh: "請便、去吧" },
    { front: "after you", pos: "phrase", def: "a polite way to let someone go first", example: "He opened the door and said, \"After you.\"", zh: "您先請" },
    { front: "what a pity", pos: "phrase", def: "used to say you are sad about something", example: "You can't come? What a pity!", zh: "真可惜" },
    { front: "have a nice day", pos: "phrase", def: "a friendly goodbye wish", example: "Thanks for shopping with us. Have a nice day!", zh: "祝你有美好的一天" },
    { front: "wow", pos: "phrase", def: "used when you are surprised or think something is great", example: "Wow! Your new bike is amazing!", zh: "哇" },
    { front: "OK", pos: "phrase", def: "yes; all right", example: "\"Let's meet at six.\" \"OK, see you then.\"", zh: "好的" },
    { front: "all right", pos: "phrase", def: "OK; good enough", example: "\"Is your room all right?\" \"Yes, it's lovely.\"", zh: "好、還可以" },
    /* ---------- Time phrases ---------- */
    { front: "right now", pos: "phrase", def: "at this moment", example: "I'm busy right now — can I call you later?", zh: "現在、此刻" },
    { front: "after that", pos: "phrase", def: "next; following that", example: "We had lunch, and after that we went shopping.", zh: "在那之後" },
    { front: "one day", pos: "phrase", def: "at some time in the future or past", example: "One day I want to visit London.", zh: "有一天" },
    { front: "during the week", pos: "phrase", def: "on weekdays, from Monday to Friday", example: "I don't watch much TV during the week.", zh: "在平日" },
    { front: "all day", pos: "phrase", def: "for the whole day", example: "It rained all day on Saturday.", zh: "一整天" },
    { front: "all night", pos: "phrase", def: "for the whole night", example: "The baby cried all night.", zh: "整晚" },
    { front: "every day", pos: "phrase", def: "each day", example: "She practises the piano every day.", zh: "每天" },
    { front: "once a week", pos: "phrase", def: "one time each week", example: "We have art class once a week.", zh: "每週一次" },
    { front: "in the morning", pos: "phrase", def: "during the early part of the day", example: "I do my exercises in the morning.", zh: "在早上" },
    { front: "in the afternoon", pos: "phrase", def: "between midday and evening", example: "We play football in the afternoon.", zh: "在下午" },
    { front: "in the evening", pos: "phrase", def: "between afternoon and night", example: "Dad reads the newspaper in the evening.", zh: "在傍晚、晚上" },
    { front: "last night", pos: "phrase", def: "the night before today", example: "I slept really well last night.", zh: "昨晚" },
    { front: "next week", pos: "phrase", def: "the week after this one", example: "We're going on holiday next week.", zh: "下週" },
    { front: "last week", pos: "phrase", def: "the week before this one", example: "Last week we had two tests.", zh: "上週" },
    { front: "this morning", pos: "phrase", def: "the morning of today", example: "I got up late this morning.", zh: "今天早上" },
    { front: "at once", pos: "phrase", def: "immediately; now", example: "Come here at once, please!", zh: "立刻" },
    { front: "in the future", pos: "phrase", def: "at a time that has not come yet", example: "In the future, cars might fly.", zh: "在未來" },
    { front: "in the past", pos: "phrase", def: "at a time before now", example: "In the past, people wrote letters, not emails.", zh: "在過去" },
    { front: "these days", pos: "phrase", def: "now, at the present time", example: "Everyone uses smartphones these days.", zh: "現今、這年頭" },
    { front: "nowadays", pos: "adv.", def: "at the present time", example: "Nowadays many people work from home.", zh: "如今" },
    { front: "the day after tomorrow", pos: "phrase", def: "two days from today", example: "My exam is the day after tomorrow.", zh: "後天" },
    { front: "from now on", pos: "phrase", def: "starting now and continuing", example: "From now on, I'll do my homework first.", zh: "從現在起" },
    { front: "so far", pos: "phrase", def: "until now", example: "So far, the holiday has been wonderful.", zh: "到目前為止" },
    { front: "once more", pos: "phrase", def: "one more time; again", example: "Let's sing the song once more.", zh: "再一次" },
    { front: "as soon as", pos: "phrase", def: "at the moment that something happens", example: "Call me as soon as you arrive.", zh: "一…就…" },
    { front: "as usual", pos: "phrase", def: "in the same way as always", example: "As usual, he was the first to arrive.", zh: "一如往常" },
    { front: "at the same time", pos: "phrase", def: "together; not one after the other", example: "We both answered at the same time.", zh: "同時" },
    { front: "for a long time", pos: "phrase", def: "for many hours, days or years", example: "I haven't seen her for a long time.", zh: "很長一段時間" },
    { front: "a long time ago", pos: "phrase", def: "many years in the past", example: "A long time ago, there was no internet.", zh: "很久以前" },
    { front: "all the time", pos: "phrase", def: "very often; always", example: "My little brother asks questions all the time.", zh: "一直、總是" },
    { front: "most of the time", pos: "phrase", def: "usually; nearly always", example: "Most of the time I walk to school.", zh: "大部分時間" },
    { front: "in a hurry", pos: "phrase", def: "needing to do something quickly", example: "Sorry, I can't talk — I'm in a hurry.", zh: "匆忙" },
    /* ---------- Common nouns ---------- */
    { front: "idea", pos: "n.", def: "a thought or plan in your mind", example: "I have a great idea for the school party.", zh: "主意、想法" },
    { front: "problem", pos: "n.", def: "something difficult that needs an answer", example: "There's a problem with my computer.", zh: "問題" },
    { front: "reason", pos: "n.", def: "why something happens", example: "What was the reason for the delay?", zh: "原因" },
    { front: "example", pos: "n.", def: "one thing that shows what others are like", example: "Can you give me an example of a healthy snack?", zh: "例子" },
    { front: "fun", pos: "n.", def: "enjoyment; a good time", example: "We had a lot of fun at the beach.", zh: "樂趣" },
    { front: "luck", pos: "n.", def: "good or bad things that happen by chance", example: "With a bit of luck, we'll win the match.", zh: "運氣" },
    { front: "sort", pos: "n.", def: "a type or kind", example: "What sort of music do you like?", zh: "種類" },
    { front: "information", pos: "n.", def: "facts about something", example: "The website has information about the museum.", zh: "資訊" },
    { front: "beginning", pos: "n.", def: "the first part of something", example: "The beginning of the film was a bit slow.", zh: "開始、開頭" },
    { front: "end", pos: "n.", def: "the last part of something", example: "There is a big surprise at the end of the story.", zh: "結尾、末端" },
    { front: "middle", pos: "n.", def: "the centre; not the beginning or end", example: "He woke up in the middle of the night.", zh: "中間" },
    { front: "bottom", pos: "n.", def: "the lowest part of something", example: "Write your name at the bottom of the page.", zh: "底部" },
    { front: "side", pos: "n.", def: "the left or right part; an edge", example: "In Britain, cars drive on the left side of the road.", zh: "側邊、邊" },
    { front: "hard work", pos: "n.", def: "work that needs a lot of effort", example: "Learning a language is hard work, but fun.", zh: "辛苦的工作" },
    /* ---------- Adjectives ---------- */
    { front: "false", pos: "adj.", def: "not true", example: "Is this sentence true or false?", zh: "錯誤的、假的" },
    { front: "possible", pos: "adj.", def: "able to happen or be done", example: "Is it possible to change my ticket?", zh: "可能的" },
    { front: "impossible", pos: "adj.", def: "not able to happen", example: "It's impossible to finish this today.", zh: "不可能的" },
    { front: "loud", pos: "adj.", def: "making a lot of noise", example: "The music is too loud — please turn it down.", zh: "大聲的" },
    { front: "silent", pos: "adj.", def: "completely quiet, with no sound", example: "The classroom was silent during the test.", zh: "寂靜的" },
    { front: "extra", pos: "adj.", def: "more than usual", example: "Can I have an extra blanket, please?", zh: "額外的" },
    { front: "normal", pos: "adj.", def: "usual; not different or special", example: "It's normal to feel nervous before a test.", zh: "正常的、一般的" },
    { front: "main", pos: "adj.", def: "the most important", example: "The main street is full of shops.", zh: "主要的" },
    /* ---------- Quantity & degree phrases ---------- */
    { front: "a bit", pos: "phrase", def: "a little", example: "I'm a bit tired after the long walk.", zh: "有一點" },
    { front: "enough time", pos: "phrase", def: "as much time as you need", example: "We have enough time for a coffee before the train.", zh: "足夠的時間" },
    { front: "plenty of", pos: "phrase", def: "a lot of; more than enough", example: "Don't hurry — we have plenty of time.", zh: "很多、充足的" },
    { front: "little by little", pos: "phrase", def: "slowly, in small steps", example: "Little by little, her English got better.", zh: "一點一點地" },
    { front: "for fun", pos: "phrase", def: "for enjoyment, not for a serious reason", example: "He learns magic tricks just for fun.", zh: "為了好玩" },
    { front: "for free", pos: "phrase", def: "without paying money", example: "Children under five can enter for free.", zh: "免費" },
    /* ---------- Activity & daily-life phrases ---------- */
    { front: "go to sleep", pos: "phrase", def: "to start sleeping", example: "I usually go to sleep at ten o'clock.", zh: "入睡" },
    { front: "have a party", pos: "phrase", def: "to invite people to eat, drink and have fun", example: "We're having a party for Dad's fiftieth birthday.", zh: "辦派對" },
    { front: "have a look", pos: "phrase", def: "to look at something quickly", example: "Have a look at my new photos.", zh: "看一下" },
    { front: "have a go", pos: "phrase", def: "to try something", example: "This game is easy — have a go!", zh: "試試看" },
    { front: "make friends", pos: "phrase", def: "to get to know people and become friends", example: "She made friends quickly at her new school.", zh: "交朋友" },
    { front: "make sure", pos: "phrase", def: "to check that something is done or true", example: "Make sure you lock the door when you leave.", zh: "確保、確認" },
    { front: "take a break", pos: "phrase", def: "to stop working for a short rest", example: "Let's take a break and have some tea.", zh: "休息一下" },
    { front: "take your time", pos: "phrase", def: "to do something slowly without hurrying", example: "Take your time — the test isn't until eleven.", zh: "慢慢來" },
    { front: "take a seat", pos: "phrase", def: "to sit down", example: "Please take a seat — the doctor will see you soon.", zh: "請坐" },
    { front: "have a seat", pos: "phrase", def: "a polite way to ask someone to sit down", example: "Come in and have a seat.", zh: "請坐下" },
    { front: "make a phone call", pos: "phrase", def: "to call someone on the phone", example: "Excuse me, I need to make a phone call.", zh: "打電話" },
    { front: "make a noise", pos: "phrase", def: "to be loud", example: "Don't make a noise — the baby is sleeping.", zh: "發出聲響、吵鬧" },
    { front: "make money", pos: "phrase", def: "to get money by working or selling", example: "He makes money by selling his drawings online.", zh: "賺錢" },
    { front: "do the shopping", pos: "phrase", def: "to buy food and things for the house", example: "Mum does the shopping on Saturday mornings.", zh: "採買日用品" },
    { front: "take a walk", pos: "phrase", def: "to go for a short walk", example: "Let's take a walk along the river.", zh: "散步" },
    { front: "have a drink", pos: "phrase", def: "to drink something", example: "Sit down and have a drink of juice.", zh: "喝點東西" },
    { front: "go for a run", pos: "phrase", def: "to run outside for exercise", example: "She goes for a run every morning before work.", zh: "去跑步" },
    { front: "go sightseeing", pos: "phrase", def: "to visit interesting places as a tourist", example: "We went sightseeing in the old city.", zh: "觀光" },
    { front: "take photos", pos: "phrase", def: "to use a camera to make pictures", example: "Tourists were taking photos of the temple.", zh: "拍照" },
    { front: "have a picnic", pos: "phrase", def: "to eat a meal outside in a park or field", example: "We had a picnic by the lake on Sunday.", zh: "野餐" },
    { front: "play outside", pos: "phrase", def: "to play games out of the house", example: "The children played outside until it got dark.", zh: "在外面玩" },
    { front: "stay at home", pos: "phrase", def: "to not go out", example: "I stayed at home because I had a cold.", zh: "待在家" },
    { front: "watch a film", pos: "phrase", def: "to look at a film at home or at the cinema", example: "Let's watch a film after dinner.", zh: "看電影" },
    { front: "read a book", pos: "phrase", def: "to look at and understand the words in a book", example: "I read a book on the train every day.", zh: "看書" },
    { front: "listen to the radio", pos: "phrase", def: "to hear music or news on the radio", example: "Grandpa listens to the radio at breakfast.", zh: "聽廣播" },
    { front: "meet friends", pos: "phrase", def: "to spend time with your friends", example: "I meet friends in town on Saturdays.", zh: "和朋友見面" },
    { front: "visit relatives", pos: "phrase", def: "to go and see people in your family", example: "We visit relatives during Chinese New Year.", zh: "探親" },
    { front: "do nothing", pos: "phrase", def: "to relax without any activity", example: "On Sunday I just want to do nothing.", zh: "什麼都不做" },
    { front: "spare time", pos: "n.", def: "time when you are not working or studying", example: "What do you do in your spare time?", zh: "空閒時間" },
    { front: "on holiday", pos: "phrase", def: "away from home for a rest or fun", example: "They are on holiday in Spain this week.", zh: "度假中" },
    { front: "at home", pos: "phrase", def: "in your house", example: "Is your mum at home now?", zh: "在家" },
    { front: "get ready", pos: "phrase", def: "to prepare yourself", example: "Hurry and get ready for school!", zh: "準備好" },
    { front: "on your own", pos: "phrase", def: "alone; without help", example: "Did you make this cake on your own?", zh: "獨自、靠自己" },
    { front: "by yourself", pos: "phrase", def: "alone; without other people", example: "Do you like travelling by yourself?", zh: "獨自一人" },
    { front: "one another", pos: "phrase", def: "each other", example: "Good friends help one another.", zh: "彼此" },
    { front: "give a hand", pos: "phrase", def: "to help someone", example: "Can you give me a hand with these boxes?", zh: "幫忙" },
    { front: "lend a hand", pos: "phrase", def: "to help someone with something", example: "Everyone lent a hand to clean the beach.", zh: "幫一把" },
    { front: "shake your head", pos: "phrase", def: "to move your head from side to side to say no", example: "She shook her head when I asked if she was cold.", zh: "搖頭" },
    { front: "raise your hand", pos: "phrase", def: "to put your hand up to answer or ask", example: "Raise your hand if you know the answer.", zh: "舉手" },
    { front: "open the door", pos: "phrase", def: "to move a door so people can go through", example: "Could you open the door for me, please?", zh: "開門" },
    { front: "close the window", pos: "phrase", def: "to shut a window", example: "Close the window — it's getting cold.", zh: "關窗" },
    { front: "turn around", pos: "phrase", def: "to move your body to face the other way", example: "Turn around and let me see your new dress.", zh: "轉過身" },
    { front: "have a good time", pos: "phrase", def: "to enjoy yourself", example: "Did you have a good time at the concert?", zh: "玩得愉快" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
