/* KET Prep extra bank: vocab wave 2 — house, furniture, food & drink */
(function () {
  var BANK = [
    /* ---------- House & rooms ---------- */
    { front: "house", pos: "n.", def: "a building where people live", example: "They live in a small house near the park.", zh: "房子" },
    { front: "home", pos: "n.", def: "the place where you live", example: "I usually get home at four o'clock.", zh: "家" },
    { front: "flat", pos: "n.", def: "a set of rooms to live in, inside a bigger building", example: "We live in a flat on the third floor.", zh: "公寓" },
    { front: "apartment", pos: "n.", def: "a flat; rooms to live in inside a building", example: "Their apartment has a great view of the river.", zh: "公寓" },
    { front: "building", pos: "n.", def: "a house, school, shop or other place with walls and a roof", example: "That tall building is a hotel.", zh: "建築物" },
    { front: "floor", pos: "n.", def: "the part of a room you walk on; a level of a building", example: "Don't leave your clothes on the floor.", zh: "地板；樓層" },
    { front: "wall", pos: "n.", def: "one of the sides of a room or building", example: "There is a big map on the classroom wall.", zh: "牆壁" },
    { front: "ceiling", pos: "n.", def: "the top part of a room, above your head", example: "The lamp hangs from the ceiling.", zh: "天花板" },
    { front: "roof", pos: "n.", def: "the top part of a building, outside", example: "There is a cat sitting on the roof.", zh: "屋頂" },
    { front: "window", pos: "n.", def: "an opening with glass in a wall", example: "Please open the window — it is hot in here.", zh: "窗戶" },
    { front: "door", pos: "n.", def: "the thing you open to go into a room or building", example: "Someone is knocking at the door.", zh: "門" },
    { front: "stairs", pos: "n.", def: "steps that go from one floor to another", example: "Be careful when you walk down the stairs.", zh: "樓梯" },
    { front: "upstairs", pos: "adv.", def: "on or to a higher floor", example: "My bedroom is upstairs.", zh: "在樓上" },
    { front: "downstairs", pos: "adv.", def: "on or to a lower floor", example: "The kitchen is downstairs.", zh: "在樓下" },
    { front: "garden", pos: "n.", def: "a piece of land next to a house with grass and flowers", example: "The children are playing in the garden.", zh: "花園、庭院" },
    { front: "garage", pos: "n.", def: "a place next to a house where you keep a car", example: "Dad put the car in the garage.", zh: "車庫" },
    { front: "gate", pos: "n.", def: "a door in a fence or wall outside", example: "Please close the gate so the dog cannot get out.", zh: "大門、柵欄門" },
    { front: "balcony", pos: "n.", def: "a small place outside an upstairs window where you can stand or sit", example: "We had coffee on the balcony.", zh: "陽台" },
    { front: "lift", pos: "n.", def: "a machine that carries people up and down in a building", example: "Take the lift to the fifth floor.", zh: "電梯" },
    { front: "key", pos: "n.", def: "a small metal thing that opens a lock", example: "I cannot find my house keys.", zh: "鑰匙" },
    { front: "room", pos: "n.", def: "a part of a building with its own walls and door", example: "This hotel room is big and clean.", zh: "房間" },
    { front: "bedroom", pos: "n.", def: "the room where you sleep", example: "My bedroom is next to the bathroom.", zh: "臥室" },
    { front: "bathroom", pos: "n.", def: "the room where you wash", example: "There is a shower in the bathroom.", zh: "浴室" },
    { front: "kitchen", pos: "n.", def: "the room where you cook food", example: "Mum is making soup in the kitchen.", zh: "廚房" },
    { front: "living room", pos: "n.", def: "the room where the family sits and relaxes", example: "We watch TV in the living room.", zh: "客廳" },
    { front: "dining room", pos: "n.", def: "the room where you eat meals", example: "We have dinner in the dining room.", zh: "餐廳（家中）" },
    { front: "toilet", pos: "n.", def: "the thing or room you use when you need the bathroom", example: "Excuse me, where is the toilet?", zh: "廁所、馬桶" },
    { front: "hall", pos: "n.", def: "the room just inside the front door; a big room for events", example: "Leave your shoes in the hall, please.", zh: "門廳；大廳" },
    { front: "basement", pos: "n.", def: "the part of a building under the ground", example: "We keep old boxes in the basement.", zh: "地下室" },
    { front: "ground floor", pos: "n.", def: "the floor of a building at street level", example: "The café is on the ground floor of the hotel.", zh: "一樓" },
    /* ---------- Furniture ---------- */
    { front: "furniture", pos: "n.", def: "things like beds, tables and chairs", example: "They bought new furniture for the living room.", zh: "家具" },
    { front: "bed", pos: "n.", def: "the thing you sleep on", example: "I go to bed at ten o'clock.", zh: "床" },
    { front: "chair", pos: "n.", def: "a seat for one person", example: "Please sit on this chair.", zh: "椅子" },
    { front: "table", pos: "n.", def: "a piece of furniture with a flat top and legs", example: "Put the plates on the table.", zh: "桌子" },
    { front: "desk", pos: "n.", def: "a table where you write or work", example: "I do my homework at my desk.", zh: "書桌" },
    { front: "sofa", pos: "n.", def: "a long soft seat for two or more people", example: "The cat is sleeping on the sofa.", zh: "沙發" },
    { front: "armchair", pos: "n.", def: "a big comfortable chair with parts for your arms", example: "Grandpa reads the newspaper in his armchair.", zh: "扶手椅" },
    { front: "cupboard", pos: "n.", def: "a piece of furniture with doors for keeping things in", example: "The cups are in the kitchen cupboard.", zh: "櫥櫃" },
    { front: "wardrobe", pos: "n.", def: "a tall cupboard where you keep your clothes", example: "Hang your coat in the wardrobe.", zh: "衣櫃" },
    { front: "bookcase", pos: "n.", def: "a piece of furniture with shelves for books", example: "The bookcase in my room is full.", zh: "書櫃" },
    { front: "shelf", pos: "n.", def: "a flat board on a wall or in a cupboard for putting things on", example: "Put the dictionary back on the shelf.", zh: "架子、層板" },
    { front: "drawer", pos: "n.", def: "a box-shaped part of a desk or cupboard that you pull out", example: "The scissors are in the top drawer.", zh: "抽屜" },
    { front: "mirror", pos: "n.", def: "a piece of special glass where you can see yourself", example: "She looked at herself in the mirror.", zh: "鏡子" },
    { front: "lamp", pos: "n.", def: "a light that stands on a table or the floor", example: "I turned on the lamp to read my book.", zh: "檯燈、燈" },
    { front: "curtain", pos: "n.", def: "cloth that hangs in front of a window", example: "Please close the curtains — it is getting dark.", zh: "窗簾" },
    { front: "carpet", pos: "n.", def: "a soft cover for the floor", example: "There is a thick red carpet in the bedroom.", zh: "地毯" },
    { front: "blanket", pos: "n.", def: "a warm cover for a bed", example: "It was cold, so I put another blanket on the bed.", zh: "毯子" },
    { front: "pillow", pos: "n.", def: "the soft thing you put your head on in bed", example: "This pillow is very soft.", zh: "枕頭" },
    { front: "sheet", pos: "n.", def: "a thin piece of cloth you sleep on; a piece of paper", example: "Mum changes the sheets every week.", zh: "床單；一張（紙）" },
    { front: "towel", pos: "n.", def: "a piece of cloth for drying yourself", example: "Take a towel when you go swimming.", zh: "毛巾" },
    { front: "picture", pos: "n.", def: "a drawing, painting or photo", example: "There are pictures of my family on the wall.", zh: "圖畫、照片" },
    { front: "painting", pos: "n.", def: "a picture made with paint", example: "This painting is two hundred years old.", zh: "畫作" },
    { front: "poster", pos: "n.", def: "a big picture or notice that you put on a wall", example: "He has a poster of his favourite band in his room.", zh: "海報" },
    { front: "vase", pos: "n.", def: "a container for flowers", example: "She put the roses in a blue vase.", zh: "花瓶" },
    { front: "plant", pos: "n.", def: "a living thing that grows in the ground, like a flower or tree", example: "Don't forget to water the plants.", zh: "植物" },
    /* ---------- Kitchen & household appliances ---------- */
    { front: "fridge", pos: "n.", def: "a machine that keeps food and drink cold", example: "Put the milk back in the fridge.", zh: "冰箱" },
    { front: "freezer", pos: "n.", def: "a machine that keeps food very cold and frozen", example: "There is some ice cream in the freezer.", zh: "冷凍庫" },
    { front: "cooker", pos: "n.", def: "a machine in the kitchen for cooking food", example: "The soup is on the cooker.", zh: "爐具" },
    { front: "oven", pos: "n.", def: "the part of a cooker where you bake food inside", example: "The cake is in the oven.", zh: "烤箱" },
    { front: "microwave", pos: "n.", def: "a machine that heats food very quickly", example: "You can warm the rice in the microwave.", zh: "微波爐" },
    { front: "washing machine", pos: "n.", def: "a machine that washes clothes", example: "Put your dirty clothes in the washing machine.", zh: "洗衣機" },
    { front: "dishwasher", pos: "n.", def: "a machine that washes plates and cups", example: "Please put the plates in the dishwasher.", zh: "洗碗機" },
    { front: "sink", pos: "n.", def: "the place in a kitchen or bathroom where you wash things", example: "The dirty dishes are in the sink.", zh: "水槽" },
    { front: "tap", pos: "n.", def: "the thing you turn to get water", example: "Turn off the tap when you brush your teeth.", zh: "水龍頭" },
    { front: "shower", pos: "n.", def: "the thing that sprays water so you can wash your body", example: "I have a shower every morning.", zh: "淋浴" },
    { front: "bath", pos: "n.", def: "a large container that you sit in to wash your body", example: "The baby loves playing in the bath.", zh: "浴缸；洗澡" },
    { front: "heater", pos: "n.", def: "a machine that makes a room warm", example: "Turn on the heater — it is cold in here.", zh: "暖氣機" },
    /* ---------- Bathroom things ---------- */
    { front: "toothbrush", pos: "n.", def: "a small brush for cleaning your teeth", example: "I need a new toothbrush.", zh: "牙刷" },
    { front: "toothpaste", pos: "n.", def: "the soft substance you put on a toothbrush", example: "We are out of toothpaste.", zh: "牙膏" },
    { front: "soap", pos: "n.", def: "the thing you use with water to wash your hands and body", example: "Wash your hands with soap before dinner.", zh: "肥皂" },
    { front: "shampoo", pos: "n.", def: "liquid soap for washing your hair", example: "This shampoo smells like apples.", zh: "洗髮精" },
    { front: "brush", pos: "n.", def: "a thing with hairs on it for cleaning or tidying", example: "Use a brush to clean your shoes.", zh: "刷子" },
    { front: "comb", pos: "n.", def: "a flat thing with teeth for making your hair tidy", example: "She keeps a comb in her bag.", zh: "梳子" },
    { front: "tissue", pos: "n.", def: "a soft thin paper for your nose", example: "Can I have a tissue, please?", zh: "面紙" },
    { front: "toilet paper", pos: "n.", def: "soft paper used in the toilet", example: "We need to buy more toilet paper.", zh: "衛生紙" },
    /* ---------- Containers & tableware ---------- */
    { front: "bin", pos: "n.", def: "a container for rubbish", example: "Put the empty bottle in the bin.", zh: "垃圾桶" },
    { front: "rubbish", pos: "n.", def: "things you throw away", example: "Dad takes out the rubbish every evening.", zh: "垃圾" },
    { front: "box", pos: "n.", def: "a container with straight sides, often made of card or wood", example: "The old toys are in a box under my bed.", zh: "盒子、箱子" },
    { front: "bottle", pos: "n.", def: "a tall glass or plastic container for liquids", example: "I always carry a bottle of water.", zh: "瓶子" },
    { front: "glass", pos: "n.", def: "a container you drink from; the hard clear material in windows", example: "Could I have a glass of juice?", zh: "玻璃杯；玻璃" },
    { front: "cup", pos: "n.", def: "a small container with a handle for hot drinks", example: "Would you like a cup of tea?", zh: "杯子" },
    { front: "mug", pos: "n.", def: "a big cup with straight sides", example: "He drinks coffee from his favourite mug.", zh: "馬克杯" },
    { front: "plate", pos: "n.", def: "a flat dish you put food on", example: "Put the sandwiches on a plate.", zh: "盤子" },
    { front: "bowl", pos: "n.", def: "a deep round dish for soup or cereal", example: "I had a bowl of rice for lunch.", zh: "碗" },
    { front: "dish", pos: "n.", def: "a container for food; a type of cooked food", example: "This chicken dish is delicious.", zh: "盤、碟；菜餚" },
    { front: "knife", pos: "n.", def: "a tool with a sharp edge for cutting", example: "Use a knife to cut the bread.", zh: "刀子" },
    { front: "fork", pos: "n.", def: "a tool with points for picking up food", example: "We eat pasta with a fork.", zh: "叉子" },
    { front: "spoon", pos: "n.", def: "a tool with a round end for eating soup or mixing", example: "You need a spoon for the soup.", zh: "湯匙" },
    { front: "chopsticks", pos: "n.", def: "two thin sticks used for eating food", example: "Can you eat noodles with chopsticks?", zh: "筷子" },
    { front: "napkin", pos: "n.", def: "a piece of cloth or paper for cleaning your mouth at meals", example: "The waiter gave everyone a napkin.", zh: "餐巾" },
    { front: "pan", pos: "n.", def: "a metal container for cooking food on a cooker", example: "Heat some oil in a pan.", zh: "平底鍋" },
    { front: "pot", pos: "n.", def: "a deep round container for cooking or keeping things", example: "There is a big pot of soup on the cooker.", zh: "鍋子、罐" },
    { front: "kettle", pos: "n.", def: "a container for boiling water", example: "Put the kettle on and we'll have some tea.", zh: "熱水壺" },
    { front: "teapot", pos: "n.", def: "a container for making and pouring tea", example: "Grandma's teapot is shaped like a house.", zh: "茶壺" },
    { front: "tray", pos: "n.", def: "a flat thing for carrying food and drinks", example: "She carried the drinks on a tray.", zh: "托盤" },
    /* ---------- Housework ---------- */
    { front: "clean", pos: "v.", def: "to take away dirt from something", example: "I clean my room every Saturday.", zh: "清潔、打掃" },
    { front: "wash", pos: "v.", def: "to make something clean with water", example: "Please wash the dishes after dinner.", zh: "洗" },
    { front: "tidy", pos: "v.", def: "to put things in the right place", example: "Tidy your desk before you go out.", zh: "整理" },
    { front: "iron", pos: "v.", def: "to make clothes flat and smooth with a hot tool", example: "Dad irons his shirts on Sunday evening.", zh: "熨燙" },
    { front: "sweep", pos: "v.", def: "to clean the floor with a brush", example: "I swept the kitchen floor after lunch.", zh: "掃地" },
    { front: "repair", pos: "v.", def: "to make something broken work again", example: "A man came to repair the washing machine.", zh: "修理" },
    { front: "fix", pos: "v.", def: "to repair something", example: "Can you fix my bike, please?", zh: "修理" },
    { front: "hang", pos: "v.", def: "to put something on a hook or line", example: "Hang your jacket behind the door.", zh: "掛" },
    { front: "lock", pos: "v.", def: "to close something with a key", example: "Don't forget to lock the door when you leave.", zh: "鎖上" },
    { front: "housework", pos: "n.", def: "the work of cleaning and tidying a house", example: "We all help with the housework at the weekend.", zh: "家事" },
    { front: "cushion", pos: "n.", def: "a soft bag you put on a chair or sofa", example: "There are four blue cushions on the sofa.", zh: "抱枕、坐墊" },
    { front: "fence", pos: "n.", def: "a wall made of wood or metal around a garden or field", example: "The dog jumped over the fence.", zh: "圍籬" },
    /* ---------- Fruit ---------- */
    { front: "fruit", pos: "n.", def: "food like apples and bananas that grows on plants", example: "Eat more fruit — it is good for you.", zh: "水果" },
    { front: "apple", pos: "n.", def: "a round fruit that is red or green", example: "I eat an apple every day at school.", zh: "蘋果" },
    { front: "banana", pos: "n.", def: "a long yellow fruit", example: "The monkey is eating a banana.", zh: "香蕉" },
    { front: "grape", pos: "n.", def: "a small green or purple fruit that grows in groups", example: "We bought a bag of grapes at the market.", zh: "葡萄" },
    { front: "lemon", pos: "n.", def: "a yellow fruit with a sour taste", example: "I like lemon in my tea.", zh: "檸檬" },
    { front: "mango", pos: "n.", def: "a sweet yellow-orange fruit from hot countries", example: "This mango juice is really sweet.", zh: "芒果" },
    { front: "melon", pos: "n.", def: "a big round fruit with sweet juicy inside", example: "We had melon for dessert.", zh: "甜瓜、哈密瓜" },
    { front: "watermelon", pos: "n.", def: "a very big green fruit that is red inside", example: "Watermelon is perfect on a hot day.", zh: "西瓜" },
    { front: "pear", pos: "n.", def: "a green or yellow fruit that is round at the bottom", example: "Would you like a pear or an apple?", zh: "梨子" },
    { front: "pineapple", pos: "n.", def: "a big fruit with hard skin and sweet yellow inside", example: "Do you like pineapple on pizza?", zh: "鳳梨" },
    { front: "strawberry", pos: "n.", def: "a small soft red fruit", example: "We picked strawberries at the farm.", zh: "草莓" },
    { front: "cherry", pos: "n.", def: "a small round red fruit with a stone inside", example: "There is a cherry on top of the cake.", zh: "櫻桃" },
    { front: "peach", pos: "n.", def: "a soft round fruit with orange-pink skin", example: "These peaches are soft and sweet.", zh: "桃子" },
    { front: "coconut", pos: "n.", def: "a large brown fruit with white inside and liquid in the middle", example: "The cake is made with coconut.", zh: "椰子" },
    /* ---------- Vegetables ---------- */
    { front: "vegetable", pos: "n.", def: "a plant you eat, like a carrot or potato", example: "You should eat vegetables every day.", zh: "蔬菜" },
    { front: "potato", pos: "n.", def: "a round white vegetable that grows under the ground", example: "We had chicken and potatoes for dinner.", zh: "馬鈴薯" },
    { front: "tomato", pos: "n.", def: "a soft round red vegetable used in salads", example: "Can you cut the tomatoes for the salad?", zh: "番茄" },
    { front: "carrot", pos: "n.", def: "a long orange vegetable", example: "Rabbits love eating carrots.", zh: "紅蘿蔔" },
    { front: "onion", pos: "n.", def: "a round vegetable with a strong smell that can make you cry", example: "Mum is cutting an onion for the soup.", zh: "洋蔥" },
    { front: "garlic", pos: "n.", def: "a small white vegetable with a very strong taste", example: "This pasta has a lot of garlic in it.", zh: "大蒜" },
    { front: "pepper", pos: "n.", def: "a red, green or yellow vegetable; a hot-tasting powder", example: "She put red peppers in the salad.", zh: "甜椒；胡椒" },
    { front: "mushroom", pos: "n.", def: "a small white or brown food with a round top", example: "I would like a mushroom pizza, please.", zh: "蘑菇" },
    { front: "salad", pos: "n.", def: "a cold dish of vegetables like lettuce and tomato", example: "I had a chicken salad for lunch.", zh: "沙拉" },
    { front: "beans", pos: "n.", def: "small seeds from a plant that you cook and eat", example: "We had beans on toast for breakfast.", zh: "豆子" },
    { front: "peas", pos: "n.", def: "small round green seeds that you eat as a vegetable", example: "There are peas and carrots with the fish.", zh: "豌豆" },
    { front: "cabbage", pos: "n.", def: "a large round vegetable with green leaves", example: "Grandma cooks cabbage with dinner.", zh: "高麗菜、甘藍" },
    { front: "lettuce", pos: "n.", def: "a vegetable with big green leaves used in salads", example: "Put some lettuce in the sandwich.", zh: "萵苣、生菜" },
    { front: "cucumber", pos: "n.", def: "a long green vegetable eaten cold in salads", example: "I like cucumber sandwiches.", zh: "小黃瓜" },
    /* ---------- Everyday foods ---------- */
    { front: "bread", pos: "n.", def: "a basic food made from flour and baked", example: "We buy fresh bread every morning.", zh: "麵包" },
    { front: "rice", pos: "n.", def: "small white or brown grains that you cook and eat", example: "We eat rice with almost every meal.", zh: "米飯" },
    { front: "pasta", pos: "n.", def: "an Italian food made from flour, like spaghetti", example: "My favourite food is pasta with cheese.", zh: "義大利麵食" },
    { front: "noodles", pos: "n.", def: "long thin pieces of food made from flour", example: "We had chicken noodles for lunch.", zh: "麵條" },
    { front: "egg", pos: "n.", def: "a round food that comes from a chicken", example: "I had a boiled egg for breakfast.", zh: "蛋" },
    { front: "cheese", pos: "n.", def: "a yellow or white food made from milk", example: "Would you like cheese on your burger?", zh: "起司" },
    { front: "butter", pos: "n.", def: "a soft yellow food made from milk that you put on bread", example: "Put some butter on the toast.", zh: "奶油" },
    { front: "milk", pos: "n.", def: "the white drink that comes from cows", example: "I drink a glass of milk before bed.", zh: "牛奶" },
    { front: "yogurt", pos: "n.", def: "a thick soft food made from milk", example: "She has yogurt and fruit for breakfast.", zh: "優格" },
    { front: "flour", pos: "n.", def: "the white powder used for making bread and cakes", example: "We need flour and eggs to make the cake.", zh: "麵粉" },
    { front: "sugar", pos: "n.", def: "the sweet white food you put in tea or cakes", example: "Do you take sugar in your coffee?", zh: "糖" },
    { front: "salt", pos: "n.", def: "the white powder you put on food to give it taste", example: "This soup needs a little more salt.", zh: "鹽" },
    { front: "oil", pos: "n.", def: "the liquid used for cooking food", example: "Fry the onions in a little oil.", zh: "油" },
    { front: "honey", pos: "n.", def: "the sweet food made by bees", example: "I like honey on my bread.", zh: "蜂蜜" },
    { front: "jam", pos: "n.", def: "a sweet food made from fruit, put on bread", example: "We made strawberry jam last summer.", zh: "果醬" },
    { front: "cereal", pos: "n.", def: "a breakfast food eaten with milk", example: "The children have cereal every morning.", zh: "麥片、穀片" },
    { front: "toast", pos: "n.", def: "bread that is cooked until it is brown", example: "I had toast and jam for breakfast.", zh: "吐司" },
    { front: "sandwich", pos: "n.", def: "two pieces of bread with food between them", example: "I made a cheese sandwich for lunch.", zh: "三明治" },
    { front: "burger", pos: "n.", def: "cooked meat in a round piece of bread", example: "He ordered a burger and chips.", zh: "漢堡" },
    { front: "pizza", pos: "n.", def: "a flat round bread with cheese and other food on top", example: "Let's order a pizza tonight.", zh: "披薩" },
    { front: "chips", pos: "n.", def: "long thin pieces of fried potato", example: "Fish and chips is a famous British meal.", zh: "薯條" },
    { front: "soup", pos: "n.", def: "a hot liquid food, often with vegetables", example: "Hot soup is lovely on a cold day.", zh: "湯" },
    { front: "steak", pos: "n.", def: "a thick flat piece of meat", example: "Dad cooked steak on the barbecue.", zh: "牛排" },
    { front: "chicken", pos: "n.", def: "a farm bird; the meat from this bird", example: "We had roast chicken for Sunday lunch.", zh: "雞；雞肉" },
    /* ---------- Meat & fish ---------- */
    { front: "meat", pos: "n.", def: "food that comes from animals", example: "My cousin does not eat meat.", zh: "肉" },
    { front: "beef", pos: "n.", def: "meat from a cow", example: "This beef noodle soup is delicious.", zh: "牛肉" },
    { front: "pork", pos: "n.", def: "meat from a pig", example: "We are having pork and rice tonight.", zh: "豬肉" },
    { front: "lamb", pos: "n.", def: "meat from a young sheep; a young sheep", example: "The restaurant is famous for its lamb.", zh: "羊肉；小羊" },
    { front: "sausage", pos: "n.", def: "meat in a long thin shape", example: "We cooked sausages on the barbecue.", zh: "香腸" },
    { front: "ham", pos: "n.", def: "meat from a pig, often eaten cold in sandwiches", example: "I'd like a ham and cheese sandwich.", zh: "火腿" },
    { front: "bacon", pos: "n.", def: "thin pieces of pig meat, often eaten at breakfast", example: "The hotel breakfast has eggs and bacon.", zh: "培根" },
    { front: "fish", pos: "n.", def: "an animal that lives in water; its meat as food", example: "We caught three fish in the river.", zh: "魚；魚肉" },
    { front: "seafood", pos: "n.", def: "food from the sea, like fish and prawns", example: "This restaurant by the beach serves great seafood.", zh: "海鮮" },
    { front: "prawn", pos: "n.", def: "a small pink sea animal that people eat", example: "She ordered rice with prawns.", zh: "蝦" },
    /* ---------- Desserts & snacks ---------- */
    { front: "cake", pos: "n.", def: "a sweet food made from flour, eggs and sugar", example: "Mum made a chocolate cake for my birthday.", zh: "蛋糕" },
    { front: "biscuit", pos: "n.", def: "a small flat dry cake that is sweet", example: "Would you like a biscuit with your tea?", zh: "餅乾" },
    { front: "cookie", pos: "n.", def: "a sweet biscuit", example: "Grandma baked chocolate cookies for us.", zh: "曲奇餅乾" },
    { front: "chocolate", pos: "n.", def: "a sweet brown food made from cocoa", example: "He gave me a box of chocolates.", zh: "巧克力" },
    { front: "sweets", pos: "n.", def: "small sugary things that children like to eat", example: "Too many sweets are bad for your teeth.", zh: "糖果" },
    { front: "ice cream", pos: "n.", def: "a very cold sweet food made from milk", example: "We bought ice cream at the beach.", zh: "冰淇淋" },
    { front: "pie", pos: "n.", def: "fruit or meat baked inside pastry", example: "Grandma's apple pie is the best.", zh: "派" },
    { front: "dessert", pos: "n.", def: "sweet food eaten at the end of a meal", example: "What would you like for dessert?", zh: "甜點" },
    { front: "snack", pos: "n.", def: "a small amount of food eaten between meals", example: "I had a snack after school.", zh: "點心、零食" },
    { front: "crisps", pos: "n.", def: "very thin fried pieces of potato in a bag", example: "He bought a packet of crisps at the shop.", zh: "洋芋片" },
    { front: "popcorn", pos: "n.", def: "small white pieces of cooked corn eaten as a snack", example: "We always eat popcorn at the cinema.", zh: "爆米花" },
    { front: "nut", pos: "n.", def: "a dry fruit with a hard shell, like a peanut", example: "This cake has nuts in it.", zh: "堅果" },
    /* ---------- Drinks ---------- */
    { front: "drink", pos: "n.", def: "a liquid that you put in your mouth, like water or juice", example: "Would you like a hot or a cold drink?", zh: "飲料" },
    { front: "water", pos: "n.", def: "the clear liquid that we drink", example: "Can I have a glass of water, please?", zh: "水" },
    { front: "juice", pos: "n.", def: "the liquid from fruit that you drink", example: "I drink apple juice at breakfast.", zh: "果汁" },
    { front: "tea", pos: "n.", def: "a hot brown drink made with leaves", example: "My grandmother drinks tea every afternoon.", zh: "茶" },
    { front: "coffee", pos: "n.", def: "a hot dark drink that wakes people up", example: "Dad cannot start the day without coffee.", zh: "咖啡" },
    { front: "lemonade", pos: "n.", def: "a sweet drink made with lemons", example: "We drank cold lemonade in the garden.", zh: "檸檬汽水" },
    { front: "cola", pos: "n.", def: "a sweet brown drink with bubbles", example: "A burger and a cola, please.", zh: "可樂" },
    { front: "milkshake", pos: "n.", def: "a cold drink made from milk and fruit or chocolate", example: "She ordered a strawberry milkshake.", zh: "奶昔" },
    { front: "mineral water", pos: "n.", def: "water from under the ground that you buy in bottles", example: "Two bottles of mineral water, please.", zh: "礦泉水" },
    { front: "hot chocolate", pos: "n.", def: "a hot sweet drink made with chocolate and milk", example: "I love hot chocolate in winter.", zh: "熱可可" },
    { front: "soft drink", pos: "n.", def: "a cold sweet drink with no alcohol", example: "Soft drinks are half price at the cinema today.", zh: "汽水、無酒精飲料" },
    { front: "ice", pos: "n.", def: "frozen water", example: "Would you like ice in your drink?", zh: "冰塊" },
    /* ---------- Meals & eating out ---------- */
    { front: "meal", pos: "n.", def: "the food you eat at one time, like lunch or dinner", example: "Breakfast is my favourite meal of the day.", zh: "一餐" },
    { front: "breakfast", pos: "n.", def: "the first meal of the day, eaten in the morning", example: "I have breakfast at seven o'clock.", zh: "早餐" },
    { front: "lunch", pos: "n.", def: "the meal you eat in the middle of the day", example: "We have lunch at school at twelve.", zh: "午餐" },
    { front: "dinner", pos: "n.", def: "the main meal, usually eaten in the evening", example: "We have dinner together every evening.", zh: "晚餐" },
    { front: "supper", pos: "n.", def: "a small meal eaten in the evening", example: "We had a light supper before bed.", zh: "晚飯、宵夜" },
    { front: "picnic", pos: "n.", def: "a meal you eat outside, for example in a park", example: "We had a picnic by the lake.", zh: "野餐" },
    { front: "barbecue", pos: "n.", def: "a meal cooked outside over fire", example: "Our neighbours invited us to a barbecue.", zh: "烤肉、燒烤" },
    { front: "takeaway", pos: "n.", def: "a meal you buy in a shop and eat at home", example: "Let's get a takeaway tonight — I'm too tired to cook.", zh: "外帶餐點" },
    { front: "menu", pos: "n.", def: "the list of food you can order in a restaurant", example: "The waiter brought us the menu.", zh: "菜單" },
    { front: "bill", pos: "n.", def: "the piece of paper that shows how much you must pay", example: "Can we have the bill, please?", zh: "帳單" },
    { front: "waiter", pos: "n.", def: "a man who brings food in a restaurant", example: "The waiter took our order.", zh: "男服務生" },
    { front: "waitress", pos: "n.", def: "a woman who brings food in a restaurant", example: "The waitress brought our drinks quickly.", zh: "女服務生" },
    { front: "order", pos: "v.", def: "to ask for food or drink in a restaurant", example: "Are you ready to order?", zh: "點餐、訂購" },
    { front: "serve", pos: "v.", def: "to bring food or drink to someone", example: "Breakfast is served from seven to ten.", zh: "供應、上菜" },
    { front: "fast food", pos: "n.", def: "food like burgers that is made and served quickly", example: "We should not eat fast food every day.", zh: "速食" },
    { front: "main course", pos: "n.", def: "the biggest part of a meal", example: "For my main course, I'll have the fish.", zh: "主菜" },
    { front: "tip", pos: "n.", def: "extra money you give to a waiter; helpful advice", example: "Dad left a tip for the waiter.", zh: "小費；訣竅" },
    { front: "jar", pos: "n.", def: "a glass container for food like jam", example: "There is a jar of honey on the shelf.", zh: "玻璃罐" },
    /* ---------- Taste & food adjectives ---------- */
    { front: "delicious", pos: "adj.", def: "tasting very good", example: "This cake is delicious — can I have more?", zh: "美味的" },
    { front: "tasty", pos: "adj.", def: "having a good taste", example: "Mum's soup is always tasty.", zh: "好吃的" },
    { front: "sweet", pos: "adj.", def: "tasting of sugar", example: "This tea is too sweet for me.", zh: "甜的" },
    { front: "sour", pos: "adj.", def: "with a sharp taste like a lemon", example: "The apple was green and sour.", zh: "酸的" },
    { front: "salty", pos: "adj.", def: "tasting of salt", example: "Sea water is very salty.", zh: "鹹的" },
    { front: "spicy", pos: "adj.", def: "with a strong hot taste", example: "I love spicy chicken curry.", zh: "辣的" },
    { front: "bitter", pos: "adj.", def: "with a strong taste that is not sweet, like black coffee", example: "This coffee is too bitter without sugar.", zh: "苦的" },
    { front: "fresh", pos: "adj.", def: "made or picked a short time ago; not old", example: "The bread from that shop is always fresh.", zh: "新鮮的" },
    { front: "fried", pos: "adj.", def: "cooked in hot oil", example: "I had fried rice for lunch.", zh: "油炸的、炒的" },
    { front: "boiled", pos: "adj.", def: "cooked in very hot water", example: "She had a boiled egg for breakfast.", zh: "水煮的" },
    { front: "roast", pos: "adj.", def: "cooked in an oven or over fire", example: "We eat roast beef on Sundays.", zh: "烘烤的" },
    { front: "frozen", pos: "adj.", def: "kept very cold and hard like ice", example: "We bought some frozen vegetables.", zh: "冷凍的" },
    { front: "thirsty", pos: "adj.", def: "needing to drink something", example: "After the race I was really thirsty.", zh: "口渴的" },
    { front: "full", pos: "adj.", def: "not able to eat more; with no empty space", example: "No dessert for me — I'm full.", zh: "吃飽的；滿的" },
    /* ---------- Cooking & eating verbs ---------- */
    { front: "eat", pos: "v.", def: "to put food in your mouth and swallow it", example: "We usually eat dinner at seven.", zh: "吃" },
    { front: "taste", pos: "v.", def: "to have a flavour; to try a little food", example: "This soup tastes wonderful.", zh: "嚐起來；品嚐" },
    { front: "smell", pos: "v.", def: "to notice something with your nose; to have a smell", example: "The kitchen smells of fresh bread.", zh: "聞起來；聞" },
    { front: "bake", pos: "v.", def: "to cook food like bread or cakes in an oven", example: "We baked biscuits this afternoon.", zh: "烘焙" },
    { front: "boil", pos: "v.", def: "to cook in very hot water; to become very hot (liquid)", example: "Boil the eggs for five minutes.", zh: "煮沸、水煮" },
    { front: "fry", pos: "v.", def: "to cook food in hot oil", example: "Fry the onions until they are soft.", zh: "煎、炸、炒" },
    { front: "mix", pos: "v.", def: "to put different things together", example: "Mix the eggs with the sugar.", zh: "混合" },
    { front: "slice", pos: "v.", def: "to cut something into thin flat pieces", example: "Slice the bread for the sandwiches.", zh: "切片" },
    { front: "pour", pos: "v.", def: "to make a liquid go out of a container", example: "She poured milk into the glass.", zh: "倒（液體）" },
    { front: "bite", pos: "v.", def: "to cut something with your teeth", example: "He bit into the apple.", zh: "咬" },
    { front: "chew", pos: "v.", def: "to break food into small pieces with your teeth", example: "Chew your food slowly.", zh: "咀嚼" },
    { front: "swallow", pos: "v.", def: "to make food or drink go down your throat", example: "The pill was hard to swallow.", zh: "吞嚥" },
    { front: "prepare", pos: "v.", def: "to make something ready", example: "Mum is preparing lunch in the kitchen.", zh: "準備" },
    { front: "feed", pos: "v.", def: "to give food to a person or animal", example: "I feed the cat twice a day.", zh: "餵食" },
    { front: "grill", pos: "v.", def: "to cook food under or over strong heat", example: "Dad grilled some fish for dinner.", zh: "燒烤" },
    { front: "heat", pos: "v.", def: "to make something warm or hot", example: "Heat the milk but do not boil it.", zh: "加熱" },
    /* ---------- Amounts & food words ---------- */
    { front: "recipe", pos: "n.", def: "instructions that tell you how to cook something", example: "This is my grandmother's recipe for apple cake.", zh: "食譜" },
    { front: "kilo", pos: "n.", def: "a measure of weight; 1,000 grams", example: "I bought a kilo of apples.", zh: "公斤" },
    { front: "gram", pos: "n.", def: "a small measure of weight", example: "The recipe needs 200 grams of flour.", zh: "公克" },
    { front: "litre", pos: "n.", def: "a measure for liquids", example: "We need two litres of milk.", zh: "公升" },
    { front: "packet", pos: "n.", def: "a small paper or plastic container for food", example: "He opened a packet of biscuits.", zh: "小包、一包" },
    { front: "tin", pos: "n.", def: "a metal container for food", example: "There is a tin of tomatoes in the cupboard.", zh: "罐頭" },
    { front: "can", pos: "n.", def: "a metal container for food or drink", example: "She bought a can of lemonade.", zh: "罐、易開罐" },
    { front: "loaf", pos: "n.", def: "bread baked in one large piece", example: "Please buy a loaf of bread on your way home.", zh: "一條（麵包）" },
    { front: "flavour", pos: "n.", def: "the taste of food or drink", example: "Which flavour of ice cream do you want?", zh: "口味、風味" },
    { front: "ingredient", pos: "n.", def: "one of the foods you use to make a dish", example: "The main ingredients are eggs, milk and flour.", zh: "食材、原料" },
    /* ---------- Around the house ---------- */
    { front: "bell", pos: "n.", def: "a metal thing that makes a ringing sound", example: "The school bell rings at nine o'clock.", zh: "鈴、鐘" },
    { front: "doorbell", pos: "n.", def: "the bell at the door that visitors ring", example: "Someone is ringing the doorbell.", zh: "門鈴" },
    { front: "chimney", pos: "n.", def: "the part of a house that smoke goes up through", example: "Smoke was coming out of the chimney.", zh: "煙囪" },
    { front: "entrance", pos: "n.", def: "the door or way into a place", example: "I will meet you at the main entrance.", zh: "入口" },
    { front: "exit", pos: "n.", def: "the door or way out of a place", example: "The exit is at the back of the cinema.", zh: "出口" },
    { front: "ladder", pos: "n.", def: "a thing you climb to reach high places", example: "Dad used a ladder to clean the windows.", zh: "梯子" },
    { front: "torch", pos: "n.", def: "a small electric light you carry in your hand", example: "Take a torch — it is dark outside.", zh: "手電筒" },
    { front: "matches", pos: "n.", def: "small wooden sticks used to make fire", example: "Keep matches away from children.", zh: "火柴" },
    { front: "scissors", pos: "n.", def: "a tool with two blades for cutting paper or cloth", example: "Use scissors to cut out the picture.", zh: "剪刀" },
    { front: "string", pos: "n.", def: "thin rope for tying things", example: "Tie the box with a piece of string.", zh: "細繩" },
    { front: "rope", pos: "n.", def: "very thick strong string", example: "The boat is tied to the tree with a rope.", zh: "繩索" },
    { front: "bucket", pos: "n.", def: "an open container with a handle for carrying water", example: "The children filled their buckets with sand.", zh: "水桶" },
    /* ---------- House adjectives ---------- */
    { front: "comfortable", pos: "adj.", def: "nice to sit, lie or be in", example: "This armchair is really comfortable.", zh: "舒適的" },
    { front: "modern", pos: "adj.", def: "new in style; of the present time", example: "They live in a modern flat in the city.", zh: "現代的" },
    { front: "cosy", pos: "adj.", def: "warm, comfortable and nice to be in", example: "The living room is small but cosy.", zh: "溫馨舒適的" },
    { front: "empty", pos: "adj.", def: "with nothing or no one inside", example: "The fridge is empty — we need to go shopping.", zh: "空的" },
    { front: "noisy", pos: "adj.", def: "making a lot of noise", example: "Our street is very noisy in the morning.", zh: "吵鬧的" },
    { front: "large", pos: "adj.", def: "big", example: "They have a large garden behind the house.", zh: "大的" },
    { front: "huge", pos: "adj.", def: "very big", example: "There is a huge tree in front of our house.", zh: "巨大的" },
    { front: "tiny", pos: "adj.", def: "very small", example: "The kitchen in our flat is tiny.", zh: "極小的" },
    { front: "narrow", pos: "adj.", def: "not wide", example: "The stairs are too narrow for this big sofa.", zh: "窄的" },
    { front: "wide", pos: "adj.", def: "measuring a long way from side to side", example: "The new road is very wide.", zh: "寬的" },
    { front: "low", pos: "adj.", def: "not high; near the ground", example: "The ceiling in the old house is quite low.", zh: "低的" },
    { front: "high", pos: "adj.", def: "a long way above the ground", example: "The shelf is too high for me to reach.", zh: "高的" },
    /* ---------- Position words ---------- */
    { front: "in", pos: "prep.", def: "inside something", example: "The keys are in my bag.", zh: "在……裡面" },
    { front: "on", pos: "prep.", def: "touching the top or surface of something", example: "Your book is on the table.", zh: "在……上面" },
    { front: "under", pos: "prep.", def: "below something", example: "The cat is sleeping under the chair.", zh: "在……下面" },
    { front: "behind", pos: "prep.", def: "at the back of something", example: "The garden is behind the house.", zh: "在……後面" },
    { front: "next to", pos: "prep.", def: "at the side of something", example: "The bank is next to the supermarket.", zh: "在……旁邊" },
    { front: "between", pos: "prep.", def: "in the space in the middle of two things", example: "My house is between the school and the park.", zh: "在……之間" },
    { front: "in front of", pos: "prep.", def: "before something; facing something", example: "There is a bus stop in front of the cinema.", zh: "在……前面" },
    { front: "above", pos: "prep.", def: "higher than something", example: "There is a mirror above the sink.", zh: "在……上方" },
    { front: "below", pos: "prep.", def: "lower than something", example: "Our flat is below theirs.", zh: "在……下方" },
    { front: "near", pos: "prep.", def: "close to something", example: "We live near the station.", zh: "在……附近" },
    { front: "opposite", pos: "prep.", def: "on the other side, facing something", example: "The chemist is opposite the post office.", zh: "在……對面" },
    { front: "inside", pos: "adv.", def: "in a building or container", example: "It is raining — let's go inside.", zh: "在裡面" },
    { front: "outside", pos: "adv.", def: "not in a building", example: "The children are playing outside.", zh: "在外面" },
    { front: "around", pos: "prep.", def: "on all sides of something; to different parts of a place", example: "There is a fence around the garden.", zh: "環繞、在……四周" },
    { front: "through", pos: "prep.", def: "from one side of something to the other", example: "The cat came in through the window.", zh: "穿過" },
    { front: "across", pos: "prep.", def: "from one side to the other side of something", example: "We walked across the bridge.", zh: "橫越" },
    { front: "over", pos: "prep.", def: "above something; from one side to the other", example: "The plane flew over our house.", zh: "在……上方；越過" },
    { front: "up", pos: "adv.", def: "towards a higher place", example: "We walked up the hill to the castle.", zh: "向上" },
    { front: "down", pos: "adv.", def: "towards a lower place", example: "The ball rolled down the stairs.", zh: "向下" },
    { front: "off", pos: "prep.", def: "away from something; down from something", example: "The cup fell off the table.", zh: "離開、從……掉下" },
    /* ---------- Materials & objects ---------- */
    { front: "paper", pos: "n.", def: "the thin material you write on", example: "Take a piece of paper and write your name.", zh: "紙" },
    { front: "plastic", pos: "n.", def: "a light man-made material", example: "The toys are made of plastic.", zh: "塑膠" },
    { front: "wood", pos: "n.", def: "the hard material that comes from trees", example: "This table is made of wood.", zh: "木頭" },
    { front: "metal", pos: "n.", def: "a hard material like iron or gold", example: "The gate is made of metal.", zh: "金屬" },
    { front: "material", pos: "n.", def: "what something is made of; cloth", example: "What material is your bag made of?", zh: "材料；布料" },
    { front: "umbrella", pos: "n.", def: "a thing you hold over your head when it rains", example: "Take an umbrella — it looks like rain.", zh: "雨傘" },
    { front: "mat", pos: "n.", def: "a small piece of thick material on the floor", example: "Wipe your shoes on the mat, please.", zh: "墊子" },
    { front: "basket", pos: "n.", def: "a container made of thin sticks or plastic for carrying things", example: "She put the fruit in a basket.", zh: "籃子" },
    { front: "toy", pos: "n.", def: "a thing for children to play with", example: "The floor was covered with the baby's toys.", zh: "玩具" },
    { front: "doll", pos: "n.", def: "a toy that looks like a small person", example: "My little sister sleeps with her doll.", zh: "洋娃娃" },
    { front: "teddy bear", pos: "n.", def: "a soft toy bear", example: "He has had that teddy bear since he was two.", zh: "泰迪熊" },
    { front: "brick", pos: "n.", def: "a hard block used for building walls", example: "The house is built of red bricks.", zh: "磚塊" },
    { front: "stone", pos: "n.", def: "a small piece of rock; the hard material rock is made of", example: "The old bridge is made of stone.", zh: "石頭" },
    { front: "teaspoon", pos: "n.", def: "a small spoon for putting sugar in drinks", example: "Add two teaspoons of sugar.", zh: "茶匙" },
    { front: "saucepan", pos: "n.", def: "a deep metal pan with a handle for cooking", example: "Heat the soup in a saucepan.", zh: "深鍋、湯鍋" },
    { front: "jug", pos: "n.", def: "a container with a handle for pouring liquids", example: "There is a jug of water on the table.", zh: "水壺、壺" },
    { front: "lid", pos: "n.", def: "the top part that closes a box, pot or jar", example: "Put the lid back on the jam jar.", zh: "蓋子" },
    { front: "tablecloth", pos: "n.", def: "a large cloth you put over a table", example: "Mum put a clean tablecloth on the table.", zh: "桌巾" },
    { front: "cloth", pos: "n.", def: "material for making clothes; a piece of material for cleaning", example: "Wipe the table with a wet cloth.", zh: "布" },
    { front: "sponge", pos: "n.", def: "a soft thing full of holes used for washing", example: "Clean the bath with a sponge.", zh: "海綿" },
    /* ---------- Living at home: verbs ---------- */
    { front: "live", pos: "v.", def: "to have your home in a place", example: "We live in a small town near the sea.", zh: "居住" },
    { front: "rent", pos: "v.", def: "to pay money to use a house or room", example: "They rent a flat in the city centre.", zh: "租" },
    { front: "build", pos: "v.", def: "to make a building or other thing", example: "They are building new houses near the school.", zh: "建造" },
    { front: "paint", pos: "v.", def: "to put colour on a wall or make a picture with paint", example: "We painted my bedroom blue.", zh: "油漆、繪畫" },
    { front: "decorate", pos: "v.", def: "to make a room or place look nice", example: "We decorated the house for the party.", zh: "裝飾" },
    { front: "knock", pos: "v.", def: "to hit a door with your hand to make a noise", example: "Please knock before you come in.", zh: "敲" },
    { front: "press", pos: "v.", def: "to push something with your finger", example: "Press the button to ring the doorbell.", zh: "按、壓" },
    { front: "open", pos: "v.", def: "to move something so it is not closed", example: "Can you open the window, please?", zh: "打開" },
    { front: "close", pos: "v.", def: "to shut something", example: "Please close the door — it is cold.", zh: "關閉" },
    { front: "shut", pos: "v.", def: "to close something", example: "Shut the gate so the dog stays in.", zh: "關上" },
    { front: "turn on", pos: "phr. v.", def: "to make a light or machine start working", example: "Turn on the light — I can't see anything.", zh: "打開（電器）" },
    { front: "turn off", pos: "phr. v.", def: "to make a light or machine stop working", example: "Turn off the TV and do your homework.", zh: "關掉（電器）" },
    { front: "switch on", pos: "phr. v.", def: "to turn on a light or machine", example: "She switched on the computer.", zh: "開啟（電器）" },
    { front: "switch off", pos: "phr. v.", def: "to turn off a light or machine", example: "Switch off the lights when you leave.", zh: "關閉（電器）" },
    { front: "move house", pos: "phrase", def: "to go and live in a different house", example: "We are moving house next month.", zh: "搬家" },
    { front: "put away", pos: "phr. v.", def: "to put something in the place where it is kept", example: "Put your toys away before dinner.", zh: "收好、放回原位" },
    /* ---------- Daily routine ---------- */
    { front: "wake up", pos: "phr. v.", def: "to stop sleeping", example: "I wake up at seven every morning.", zh: "醒來" },
    { front: "go to bed", pos: "phrase", def: "to get into bed to sleep", example: "On school days I go to bed at ten.", zh: "上床睡覺" },
    { front: "get dressed", pos: "phrase", def: "to put your clothes on", example: "Get dressed quickly — we are late!", zh: "穿衣服" },
    { front: "have a shower", pos: "phrase", def: "to wash your body under a shower", example: "I have a shower after football practice.", zh: "淋浴" },
    { front: "have breakfast", pos: "phrase", def: "to eat the morning meal", example: "We have breakfast together at half past seven.", zh: "吃早餐" },
    { front: "brush your teeth", pos: "phrase", def: "to clean your teeth with a toothbrush", example: "Brush your teeth before you go to bed.", zh: "刷牙" },
    { front: "fall asleep", pos: "phrase", def: "to start sleeping", example: "The baby fell asleep in the car.", zh: "入睡" },
    { front: "sleep", pos: "v.", def: "to rest with your eyes closed, as you do at night", example: "I slept for nine hours last night.", zh: "睡覺" },
    { front: "dream", pos: "v.", def: "to see pictures in your mind while you sleep", example: "I dreamt about flying last night.", zh: "做夢" },
    { front: "rest", pos: "v.", def: "to relax and do nothing after working", example: "Sit down and rest for a few minutes.", zh: "休息" },
    /* ---------- Sleep words ---------- */
    { front: "asleep", pos: "adj.", def: "sleeping", example: "Be quiet — the baby is asleep.", zh: "睡著的" },
    { front: "awake", pos: "adj.", def: "not sleeping", example: "I was still awake at midnight.", zh: "醒著的" },
    { front: "nap", pos: "n.", def: "a short sleep in the day", example: "Grandpa has a nap after lunch.", zh: "小睡、午睡" },
    { front: "bedtime", pos: "n.", def: "the time when you go to bed", example: "Eight o'clock is my little brother's bedtime.", zh: "就寢時間" },
    { front: "noise", pos: "n.", def: "a sound, often loud and not nice", example: "What is that strange noise upstairs?", zh: "噪音、聲響" },
    /* ---------- Home & meal phrases ---------- */
    { front: "lay the table", pos: "phrase", def: "to put plates, knives and forks on the table before a meal", example: "Can you lay the table for dinner, please?", zh: "擺餐具" },
    { front: "wash up", pos: "phr. v.", def: "to clean the plates and cups after a meal", example: "I'll cook if you wash up.", zh: "洗碗" },
    { front: "make the bed", pos: "phrase", def: "to tidy the sheets and covers on a bed", example: "I make my bed every morning.", zh: "鋪床" },
    { front: "help yourself", pos: "phrase", def: "used to tell someone to take what they want", example: "Help yourself to some cake.", zh: "請自行取用" },
    { front: "come in", pos: "phr. v.", def: "to enter a room or building", example: "Come in and sit down.", zh: "進來" },
    { front: "sit down", pos: "phr. v.", def: "to move from standing to sitting", example: "Please sit down — the lesson is starting.", zh: "坐下" },
    { front: "stand up", pos: "phr. v.", def: "to move from sitting to standing", example: "Everyone stood up when the teacher came in.", zh: "站起來" },
    /* ---------- More foods ---------- */
    { front: "curry", pos: "n.", def: "a dish cooked with spices, often eaten with rice", example: "We had chicken curry and rice for dinner.", zh: "咖哩" },
    { front: "sushi", pos: "n.", def: "a Japanese food made with rice and fish", example: "We ate sushi at a Japanese restaurant.", zh: "壽司" },
    { front: "omelette", pos: "n.", def: "eggs mixed together and fried", example: "Dad made a cheese omelette for breakfast.", zh: "煎蛋捲、歐姆蛋" },
    { front: "pancake", pos: "n.", def: "a thin flat cake cooked in a pan", example: "We had pancakes with honey on Sunday morning.", zh: "煎餅、鬆餅" },
    { front: "doughnut", pos: "n.", def: "a small round sweet cake cooked in oil", example: "He bought a bag of doughnuts for the class.", zh: "甜甜圈" },
    { front: "bun", pos: "n.", def: "a small round piece of bread or sweet cake", example: "The burger comes in a soft bun.", zh: "小圓麵包" },
    { front: "roll", pos: "n.", def: "a small round piece of bread for one person", example: "I had a cheese roll for lunch.", zh: "餐包、麵包捲" },
    { front: "cream", pos: "n.", def: "the thick part of milk, often eaten with desserts", example: "Would you like cream with your strawberries?", zh: "鮮奶油" },
    { front: "chilli", pos: "n.", def: "a small red or green vegetable with a very hot taste", example: "Be careful — there is a lot of chilli in this dish.", zh: "辣椒" },
    { front: "corn", pos: "n.", def: "a plant with yellow seeds that people eat", example: "We grilled some corn at the barbecue.", zh: "玉米" },
    { front: "ketchup", pos: "n.", def: "a cold red sauce made from tomatoes", example: "He puts ketchup on his chips.", zh: "番茄醬" },
    { front: "sauce", pos: "n.", def: "a thick liquid that you eat with food", example: "The pasta comes with tomato sauce.", zh: "醬汁" },
    { front: "cheeseburger", pos: "n.", def: "a burger with cheese in it", example: "A cheeseburger and a lemonade, please.", zh: "起司漢堡" },
    { front: "hot dog", pos: "n.", def: "a hot sausage in a long piece of bread", example: "We bought hot dogs at the football match.", zh: "熱狗" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
