/* KET Prep extra bank: vocab wave 3 — school, jobs, shopping & clothes */
(function () {
  var BANK = [
    /* ---------- School & subjects ---------- */
    { front: "school", pos: "n.", def: "the place where children go to learn", example: "Our school starts at half past eight.", zh: "學校" },
    { front: "classroom", pos: "n.", def: "the room where students have lessons", example: "The classroom is on the second floor.", zh: "教室" },
    { front: "lesson", pos: "n.", def: "a time when you learn something with a teacher", example: "We have an English lesson every day.", zh: "課、一堂課" },
    { front: "class", pos: "n.", def: "a group of students who learn together", example: "There are twenty students in my class.", zh: "班級" },
    { front: "subject", pos: "n.", def: "something you study at school, like maths or art", example: "My favourite subject is science.", zh: "科目" },
    { front: "maths", pos: "n.", def: "the study of numbers", example: "We learnt about triangles in maths today.", zh: "數學" },
    { front: "science", pos: "n.", def: "the study of the natural world", example: "We did an experiment in the science lesson.", zh: "科學、自然" },
    { front: "history", pos: "n.", def: "the study of things that happened in the past", example: "In history we are learning about ancient Egypt.", zh: "歷史" },
    { front: "geography", pos: "n.", def: "the study of countries, mountains, rivers and weather", example: "We drew maps in geography.", zh: "地理" },
    { front: "art", pos: "n.", def: "the subject where you draw and paint", example: "I painted a picture of my dog in art.", zh: "美術、藝術" },
    { front: "music", pos: "n.", def: "the sounds made by singing or instruments", example: "We listen to music in the car.", zh: "音樂" },
    { front: "English", pos: "n.", def: "the language spoken in Britain, the USA and other countries", example: "She speaks English very well.", zh: "英語" },
    { front: "language", pos: "n.", def: "the words people use to speak and write", example: "How many languages can you speak?", zh: "語言" },
    { front: "PE", pos: "n.", def: "the school subject where you do sport and exercise", example: "We played basketball in PE today.", zh: "體育課" },
    { front: "timetable", pos: "n.", def: "a list that shows when lessons or buses happen", example: "Look at the timetable to see when maths starts.", zh: "課表、時刻表" },
    { front: "homework", pos: "n.", def: "school work that you do at home", example: "I have a lot of homework tonight.", zh: "回家作業" },
    { front: "exam", pos: "n.", def: "an important test of what you know", example: "We have an English exam next week.", zh: "考試" },
    { front: "test", pos: "n.", def: "questions to see how much you know", example: "I got ten out of ten in the spelling test.", zh: "測驗" },
    { front: "mark", pos: "n.", def: "a number or letter that shows how good your work is", example: "She got a good mark in the maths test.", zh: "分數" },
    { front: "grade", pos: "n.", def: "a mark for school work; a level in school", example: "He got the top grade in the exam.", zh: "成績、年級" },
    { front: "university", pos: "n.", def: "the place where people study after school", example: "My sister studies medicine at university.", zh: "大學" },
    { front: "college", pos: "n.", def: "a place where people study after leaving school", example: "He is studying cooking at college.", zh: "學院、大專" },
    { front: "library", pos: "n.", def: "a place where you can read and borrow books", example: "I took two books back to the library.", zh: "圖書館" },
    { front: "playground", pos: "n.", def: "an outside place where children play", example: "The children are in the playground at break time.", zh: "操場、遊樂場" },
    { front: "uniform", pos: "n.", def: "special clothes that everyone in a school or job wears", example: "Our school uniform is a white shirt and grey trousers.", zh: "制服" },
    { front: "student", pos: "n.", def: "a person who is learning at school or university", example: "The students are doing a science project.", zh: "學生" },
    { front: "pupil", pos: "n.", def: "a child who is learning at school", example: "There are six hundred pupils at our school.", zh: "（中小學）學生" },
    { front: "teacher", pos: "n.", def: "a person whose job is to help people learn", example: "Our teacher explains things very clearly.", zh: "老師" },
    { front: "headteacher", pos: "n.", def: "the teacher who leads a school", example: "The headteacher spoke to all the parents.", zh: "校長" },
    { front: "term", pos: "n.", def: "one of the periods of the school year", example: "The new term starts in September.", zh: "學期" },
    /* ---------- Classroom objects ---------- */
    { front: "pen", pos: "n.", def: "a thing you write with, using ink", example: "Can I borrow a pen, please?", zh: "原子筆" },
    { front: "pencil", pos: "n.", def: "a thing you write or draw with, made of wood", example: "Draw the picture with a pencil first.", zh: "鉛筆" },
    { front: "pencil case", pos: "n.", def: "a small bag for pens and pencils", example: "My pencil case is full of coloured pens.", zh: "鉛筆盒" },
    { front: "rubber", pos: "n.", def: "a small thing that takes away pencil marks", example: "Use a rubber if you make a mistake.", zh: "橡皮擦" },
    { front: "ruler", pos: "n.", def: "a long flat thing for drawing straight lines", example: "Use a ruler to draw the line.", zh: "尺" },
    { front: "book", pos: "n.", def: "pages with words that you read, joined together", example: "I am reading a book about dinosaurs.", zh: "書" },
    { front: "notebook", pos: "n.", def: "a book with empty pages for writing in", example: "Write the new words in your notebook.", zh: "筆記本" },
    { front: "textbook", pos: "n.", def: "a book that you study from at school", example: "Open your textbooks at page forty.", zh: "課本" },
    { front: "dictionary", pos: "n.", def: "a book that tells you what words mean", example: "Look up the word in your dictionary.", zh: "字典" },
    { front: "page", pos: "n.", def: "one side of a piece of paper in a book", example: "Turn to page twenty-five.", zh: "頁" },
    { front: "bag", pos: "n.", def: "a thing you carry your books and other things in", example: "My school bag is really heavy today.", zh: "袋子、書包" },
    { front: "backpack", pos: "n.", def: "a bag that you carry on your back", example: "He put his lunch in his backpack.", zh: "後背包" },
    { front: "board", pos: "n.", def: "the flat surface a teacher writes on", example: "The teacher wrote the date on the board.", zh: "黑板、白板" },
    { front: "glue", pos: "n.", def: "a sticky thing used to join paper or other things", example: "Stick the picture in with glue.", zh: "膠水" },
    { front: "crayon", pos: "n.", def: "a coloured pencil made of wax", example: "The little children drew with crayons.", zh: "蠟筆" },
    { front: "calculator", pos: "n.", def: "a small machine that does maths for you", example: "You can use a calculator in this test.", zh: "計算機" },
    { front: "folder", pos: "n.", def: "a cover for keeping papers in", example: "Keep your worksheets in a folder.", zh: "資料夾" },
    { front: "mistake", pos: "n.", def: "something that is wrong", example: "I made two mistakes in the test.", zh: "錯誤" },
    { front: "question", pos: "n.", def: "words that ask something", example: "The last question was very difficult.", zh: "問題" },
    { front: "project", pos: "n.", def: "a big piece of school work that takes a long time", example: "We are doing a project about rivers.", zh: "專題、報告" },
    { front: "story", pos: "n.", def: "words that tell you about things that happened", example: "Grandpa told us a story about his childhood.", zh: "故事" },
    { front: "word", pos: "n.", def: "a group of letters with a meaning", example: "What does this word mean?", zh: "字、單字" },
    { front: "sentence", pos: "n.", def: "a group of words that begins with a capital letter and ends with a full stop", example: "Write three sentences about your family.", zh: "句子" },
    { front: "alphabet", pos: "n.", def: "all the letters from A to Z", example: "There are twenty-six letters in the English alphabet.", zh: "字母表" },
    { front: "note", pos: "n.", def: "a short piece of writing to help you remember", example: "I made notes during the lesson.", zh: "筆記、便條" },
    /* ---------- School verbs ---------- */
    { front: "learn", pos: "v.", def: "to get new knowledge or a new skill", example: "I am learning to play the piano.", zh: "學習" },
    { front: "teach", pos: "v.", def: "to help someone learn something", example: "Mr Brown teaches us geography.", zh: "教" },
    { front: "study", pos: "v.", def: "to spend time learning something", example: "She is studying for her English exam.", zh: "讀書、研讀" },
    { front: "read", pos: "v.", def: "to look at words and understand them", example: "I read a chapter of my book every night.", zh: "閱讀" },
    { front: "write", pos: "v.", def: "to make letters and words on paper or a screen", example: "Write your name at the top of the page.", zh: "寫" },
    { front: "spell", pos: "v.", def: "to say or write the letters of a word in order", example: "How do you spell your surname?", zh: "拼寫" },
    { front: "draw", pos: "v.", def: "to make a picture with a pen or pencil", example: "She drew a picture of her house.", zh: "畫" },
    { front: "listen", pos: "v.", def: "to try to hear something", example: "Listen to the teacher carefully.", zh: "聽" },
    { front: "repeat", pos: "v.", def: "to say or do something again", example: "Could you repeat the question, please?", zh: "重複" },
    { front: "ask", pos: "v.", def: "to say a question to someone", example: "Put up your hand if you want to ask a question.", zh: "問" },
    { front: "answer", pos: "v.", def: "to say or write something back when someone asks", example: "Nobody could answer the last question.", zh: "回答" },
    { front: "explain", pos: "v.", def: "to make something easy to understand", example: "The teacher explained the new grammar.", zh: "解釋" },
    { front: "understand", pos: "v.", def: "to know what something means", example: "I don't understand this word.", zh: "了解、懂" },
    { front: "remember", pos: "v.", def: "to keep something in your mind and not forget it", example: "Do you remember our first teacher?", zh: "記得" },
    { front: "forget", pos: "v.", def: "to not remember something", example: "Don't forget to bring your homework tomorrow.", zh: "忘記" },
    { front: "practise", pos: "v.", def: "to do something many times to get better at it", example: "You should practise the piano every day.", zh: "練習" },
    { front: "check", pos: "v.", def: "to look at something to see if it is correct", example: "Check your answers before you hand in the test.", zh: "檢查" },
    { front: "correct", pos: "v.", def: "to make mistakes right", example: "The teacher corrected our homework.", zh: "訂正、批改" },
    { front: "copy", pos: "v.", def: "to write or do the same thing as something else", example: "Copy the words from the board.", zh: "抄寫、複製" },
    { front: "pass", pos: "v.", def: "to be successful in a test; to give something to someone", example: "She passed all her exams.", zh: "通過（考試）；傳遞" },
    { front: "fail", pos: "v.", def: "to not pass a test", example: "He failed his driving test the first time.", zh: "不及格、失敗" },
    { front: "describe", pos: "v.", def: "to say what someone or something is like", example: "Describe your best friend in five sentences.", zh: "描述" },
    { front: "take an exam", pos: "phrase", def: "to do an important test", example: "I am taking my piano exam in June.", zh: "參加考試" },
    { front: "do your homework", pos: "phrase", def: "to do the school work your teacher gives you for home", example: "You can watch TV after you do your homework.", zh: "做作業" },
    { front: "put up your hand", pos: "phrase", def: "to lift your hand to answer or ask in class", example: "Put up your hand if you know the answer.", zh: "舉手" },
    { front: "break time", pos: "n.", def: "the short free time between lessons", example: "We play in the playground at break time.", zh: "下課時間" },
    /* ---------- School life ---------- */
    { front: "break", pos: "n.", def: "a short time when you stop working", example: "Let's have a break and drink some water.", zh: "休息時間" },
    { front: "club", pos: "n.", def: "a group of people who meet to do something they like", example: "I joined the school chess club.", zh: "社團、俱樂部" },
    { front: "level", pos: "n.", def: "how good or high something is", example: "This book is perfect for my English level.", zh: "程度、等級" },
    { front: "course", pos: "n.", def: "a set of lessons about a subject", example: "My mum is doing a computer course.", zh: "課程" },
    { front: "prize", pos: "n.", def: "something you win in a game or competition", example: "The first prize is a new bicycle.", zh: "獎品" },
    { front: "competition", pos: "n.", def: "a game or test that people try to win", example: "She won the school photography competition.", zh: "比賽、競賽" },
    { front: "absent", pos: "adj.", def: "not at school or work", example: "Two students were absent today because they were ill.", zh: "缺席的" },
    { front: "hard-working", pos: "adj.", def: "working a lot and trying hard", example: "She is the most hard-working student in the class.", zh: "勤奮的" },
    { front: "strict", pos: "adj.", def: "making people follow rules", example: "Our maths teacher is quite strict.", zh: "嚴格的" },
    { front: "primary school", pos: "n.", def: "a school for children between about five and eleven", example: "My little brother is still at primary school.", zh: "小學" },
    /* ---------- Jobs ---------- */
    { front: "job", pos: "n.", def: "the work a person does for money", example: "My uncle has a job in a bank.", zh: "工作、職業" },
    { front: "work", pos: "v.", def: "to do a job", example: "My mother works in a hospital.", zh: "工作" },
    { front: "doctor", pos: "n.", def: "a person whose job is to help ill people", example: "You should see a doctor about that cough.", zh: "醫生" },
    { front: "nurse", pos: "n.", def: "a person who looks after ill people in a hospital", example: "The nurse took my temperature.", zh: "護理師" },
    { front: "dentist", pos: "n.", def: "a person whose job is to look after teeth", example: "I go to the dentist twice a year.", zh: "牙醫" },
    { front: "engineer", pos: "n.", def: "a person who designs or repairs machines, roads or bridges", example: "My dad is an engineer at a car company.", zh: "工程師" },
    { front: "farmer", pos: "n.", def: "a person who keeps animals or grows food on a farm", example: "The farmer gets up very early to milk the cows.", zh: "農夫" },
    { front: "driver", pos: "n.", def: "a person who drives a car, bus or taxi", example: "The bus driver said good morning to everyone.", zh: "司機" },
    { front: "pilot", pos: "n.", def: "a person who flies a plane", example: "The pilot told us about the weather in London.", zh: "飛行員" },
    { front: "police officer", pos: "n.", def: "a person whose job is to make people follow the law", example: "A police officer helped us find the way.", zh: "警察" },
    { front: "firefighter", pos: "n.", def: "a person whose job is to stop fires", example: "The firefighters arrived very quickly.", zh: "消防員" },
    { front: "chef", pos: "n.", def: "a person who cooks food in a restaurant", example: "The chef made a special dessert for us.", zh: "主廚" },
    { front: "actor", pos: "n.", def: "a person who acts in films or plays", example: "Who is your favourite actor?", zh: "演員" },
    { front: "actress", pos: "n.", def: "a woman who acts in films or plays", example: "The actress answered questions about her new film.", zh: "女演員" },
    { front: "singer", pos: "n.", def: "a person who sings", example: "The singer has a beautiful voice.", zh: "歌手" },
    { front: "dancer", pos: "n.", def: "a person who dances", example: "She wants to be a dancer when she grows up.", zh: "舞者" },
    { front: "artist", pos: "n.", def: "a person who paints or draws pictures", example: "The artist painted a picture of the old bridge.", zh: "藝術家、畫家" },
    { front: "photographer", pos: "n.", def: "a person who takes photos as a job", example: "A photographer took pictures at the wedding.", zh: "攝影師" },
    { front: "journalist", pos: "n.", def: "a person who writes news for newspapers or websites", example: "The journalist asked the singer some questions.", zh: "記者" },
    { front: "secretary", pos: "n.", def: "a person who writes letters and answers the phone in an office", example: "The secretary told me the manager was busy.", zh: "秘書" },
    { front: "receptionist", pos: "n.", def: "a person who welcomes people at a hotel or office", example: "The receptionist gave us our room key.", zh: "接待員、櫃檯人員" },
    { front: "shop assistant", pos: "n.", def: "a person who helps customers in a shop", example: "The shop assistant found my size for me.", zh: "店員" },
    { front: "manager", pos: "n.", def: "the person who leads a shop, team or company", example: "Can I speak to the manager, please?", zh: "經理" },
    { front: "boss", pos: "n.", def: "the person you work for", example: "Her boss said she could leave early today.", zh: "老闆、上司" },
    { front: "businessman", pos: "n.", def: "a man who works in business", example: "The businessman travels to other countries a lot.", zh: "商人（男）" },
    { front: "businesswoman", pos: "n.", def: "a woman who works in business", example: "The businesswoman opened her third shop this year.", zh: "商人（女）" },
    { front: "cleaner", pos: "n.", def: "a person whose job is to clean offices or houses", example: "The cleaners come to the school in the evening.", zh: "清潔人員" },
    { front: "mechanic", pos: "n.", def: "a person who repairs cars and machines", example: "The mechanic fixed our car in one day.", zh: "技工、修車師傅" },
    { front: "painter", pos: "n.", def: "a person who paints pictures or walls", example: "The painter is painting our kitchen this week.", zh: "畫家；油漆工" },
    { front: "builder", pos: "n.", def: "a person who makes houses and buildings", example: "The builders are working on the new school.", zh: "建築工人" },
    { front: "postman", pos: "n.", def: "a person who brings letters to your house", example: "The postman comes at about nine o'clock.", zh: "郵差" },
    { front: "hairdresser", pos: "n.", def: "a person who cuts and styles hair", example: "The hairdresser cut my hair too short.", zh: "美髮師" },
    { front: "footballer", pos: "n.", def: "a person who plays football, often as a job", example: "He wants to be a famous footballer.", zh: "足球員" },
    { front: "guide", pos: "n.", def: "a person who shows visitors around a place", example: "The guide told us about the castle's history.", zh: "導遊、嚮導" },
    { front: "taxi driver", pos: "n.", def: "a person who drives a taxi", example: "The taxi driver knew a quicker way to the airport.", zh: "計程車司機" },
    { front: "scientist", pos: "n.", def: "a person who studies science", example: "Scientists are learning more about the sea.", zh: "科學家" },
    { front: "musician", pos: "n.", def: "a person who plays music", example: "The musicians played in the town square.", zh: "音樂家" },
    { front: "writer", pos: "n.", def: "a person who writes books or stories", example: "My favourite writer has a new book out.", zh: "作家" },
    { front: "worker", pos: "n.", def: "a person who works", example: "The factory workers start at six in the morning.", zh: "工人、員工" },
    { front: "librarian", pos: "n.", def: "a person who works in a library", example: "The librarian helped me find a book about space.", zh: "圖書館員" },
    /* ---------- Work words ---------- */
    { front: "office", pos: "n.", def: "a room or building where people work at desks", example: "My mum's office is in the city centre.", zh: "辦公室" },
    { front: "factory", pos: "n.", def: "a building where things are made by machines", example: "This factory makes bicycles.", zh: "工廠" },
    { front: "company", pos: "n.", def: "a business that sells things or services", example: "She works for a computer company.", zh: "公司" },
    { front: "business", pos: "n.", def: "buying and selling things; a company", example: "My aunt runs her own business.", zh: "生意、事業" },
    { front: "meeting", pos: "n.", def: "a time when people come together to talk about something", example: "Dad has a meeting at nine tomorrow.", zh: "會議" },
    { front: "staff", pos: "n.", def: "all the people who work in a place", example: "The hotel staff were very friendly.", zh: "員工、職員" },
    { front: "earn", pos: "v.", def: "to get money for work you do", example: "She earns extra money by walking dogs.", zh: "賺（錢）" },
    { front: "part-time", pos: "adj.", def: "working only some hours of the week", example: "He has a part-time job at the weekend.", zh: "兼職的" },
    { front: "full-time", pos: "adj.", def: "working all the normal hours of the week", example: "After college she got a full-time job.", zh: "全職的" },
    { front: "day off", pos: "n.", def: "a day when you do not have to work", example: "Monday is my dad's day off.", zh: "休假日" },
    { front: "at work", pos: "phrase", def: "at the place where you work; working", example: "Mum is still at work — she will be home at six.", zh: "在上班、在工作" },
    { front: "hard", pos: "adv.", def: "with a lot of effort", example: "She works hard at school.", zh: "努力地" },
    /* ---------- Shopping & money ---------- */
    { front: "shop", pos: "n.", def: "a place where you buy things", example: "The shop on the corner sells sweets and newspapers.", zh: "商店" },
    { front: "shopping", pos: "n.", def: "buying things from shops", example: "We do our shopping on Saturday morning.", zh: "購物" },
    { front: "supermarket", pos: "n.", def: "a big shop that sells food and things for the house", example: "We buy our food at the supermarket.", zh: "超級市場" },
    { front: "market", pos: "n.", def: "a place with many small shops or tables, often outside", example: "The fruit at the market is cheaper than in the shop.", zh: "市場" },
    { front: "department store", pos: "n.", def: "a big shop that sells many different things", example: "We bought a lamp at the department store.", zh: "百貨公司" },
    { front: "shopping centre", pos: "n.", def: "a big building with many shops inside", example: "There is a new shopping centre near the station.", zh: "購物中心" },
    { front: "customer", pos: "n.", def: "a person who buys something from a shop", example: "The shop was full of customers before Christmas.", zh: "顧客" },
    { front: "price", pos: "n.", def: "the money you must pay for something", example: "What is the price of this jacket?", zh: "價格" },
    { front: "money", pos: "n.", def: "the coins and paper notes you use to buy things", example: "I am saving money for a new bike.", zh: "錢" },
    { front: "cash", pos: "n.", def: "money in coins and notes", example: "Are you paying by card or in cash?", zh: "現金" },
    { front: "coin", pos: "n.", def: "a piece of metal money", example: "He found an old coin in the garden.", zh: "硬幣" },
    { front: "banknote", pos: "n.", def: "a piece of paper money", example: "She paid with a twenty-pound banknote.", zh: "紙鈔" },
    { front: "credit card", pos: "n.", def: "a plastic card you use to pay for things", example: "Can I pay by credit card?", zh: "信用卡" },
    { front: "pound", pos: "n.", def: "the money used in Britain", example: "The magazine costs three pounds.", zh: "英鎊" },
    { front: "euro", pos: "n.", def: "the money used in many European countries", example: "The ice cream cost two euros.", zh: "歐元" },
    { front: "dollar", pos: "n.", def: "the money used in the USA and some other countries", example: "The T-shirt cost ten dollars.", zh: "美元" },
    { front: "penny", pos: "n.", def: "a small British coin; 100 pennies make a pound", example: "The sweets cost fifty pence — I paid with a penny short!", zh: "便士" },
    { front: "pay", pos: "v.", def: "to give money for something", example: "I'll pay for the drinks.", zh: "付錢" },
    { front: "buy", pos: "v.", def: "to get something by giving money", example: "We bought some bread and milk.", zh: "買" },
    { front: "sell", pos: "v.", def: "to give something to someone for money", example: "That shop sells lovely cakes.", zh: "賣" },
    { front: "spend", pos: "v.", def: "to use money to buy things; to use time", example: "She spent all her pocket money on stickers.", zh: "花費" },
    { front: "cost", pos: "v.", def: "to have a price of", example: "How much does this bag cost?", zh: "價錢為、花費" },
    { front: "change", pos: "n.", def: "the money you get back when you pay too much", example: "The assistant gave me two pounds change.", zh: "找零" },
    { front: "receipt", pos: "n.", def: "a piece of paper that shows what you paid", example: "Keep the receipt in case the radio doesn't work.", zh: "收據" },
    { front: "wallet", pos: "n.", def: "a small flat case for money and cards", example: "He took a ten-pound note out of his wallet.", zh: "皮夾" },
    { front: "purse", pos: "n.", def: "a small bag for money, used especially by women", example: "Her purse is full of coins.", zh: "錢包" },
    { front: "pocket money", pos: "n.", def: "money that parents give children each week", example: "I get five pounds pocket money a week.", zh: "零用錢" },
    { front: "sale", pos: "n.", def: "a time when a shop sells things at lower prices", example: "I bought these boots in the January sale.", zh: "特賣、拍賣" },
    { front: "expensive", pos: "adj.", def: "costing a lot of money", example: "That restaurant is too expensive for us.", zh: "昂貴的" },
    { front: "queue", pos: "n.", def: "a line of people waiting for something", example: "There was a long queue at the supermarket.", zh: "排隊隊伍" },
    { front: "trolley", pos: "n.", def: "a big basket on wheels for shopping", example: "Dad pushed the trolley around the supermarket.", zh: "購物推車" },
    { front: "size", pos: "n.", def: "how big or small something is", example: "Do you have these shoes in size six?", zh: "尺寸" },
    { front: "try on", pos: "phr. v.", def: "to put on clothes to see if they fit", example: "Can I try on this jacket, please?", zh: "試穿" },
    { front: "save", pos: "v.", def: "to keep money to use later; to help someone out of danger", example: "I am saving for a new computer game.", zh: "儲蓄；拯救" },
    { front: "shopping list", pos: "n.", def: "a list of things you want to buy", example: "Milk is at the top of the shopping list.", zh: "購物清單" },
    { front: "for sale", pos: "phrase", def: "able to be bought", example: "The house next door is for sale.", zh: "出售中" },
    { front: "special offer", pos: "n.", def: "a lower price for a short time", example: "These apples are on special offer this week.", zh: "特價、優惠" },
    { front: "closed", pos: "adj.", def: "not open", example: "The bank is closed on Sundays.", zh: "關閉的、不營業的" },
    { front: "go shopping", pos: "phrase", def: "to visit shops to buy things", example: "Let's go shopping on Saturday.", zh: "去購物" },
    /* ---------- Clothes ---------- */
    { front: "clothes", pos: "n.", def: "things like shirts and trousers that you wear", example: "She packed some warm clothes for the trip.", zh: "衣服" },
    { front: "dress", pos: "n.", def: "a piece of clothing for a woman or girl that covers the body and legs", example: "She wore a beautiful red dress to the party.", zh: "洋裝、連身裙" },
    { front: "skirt", pos: "n.", def: "a piece of clothing for a woman or girl that hangs from the waist", example: "Our school uniform has a grey skirt.", zh: "裙子" },
    { front: "shirt", pos: "n.", def: "a piece of clothing with buttons for the top part of the body", example: "Dad wears a white shirt to work.", zh: "襯衫" },
    { front: "T-shirt", pos: "n.", def: "a soft shirt with short sleeves and no buttons", example: "He was wearing jeans and a blue T-shirt.", zh: "T恤" },
    { front: "trousers", pos: "n.", def: "clothing that covers your legs, with a part for each leg", example: "These trousers are too long for me.", zh: "長褲" },
    { front: "jeans", pos: "n.", def: "trousers made of strong blue cotton", example: "She usually wears jeans at the weekend.", zh: "牛仔褲" },
    { front: "shorts", pos: "n.", def: "short trousers that end above the knees", example: "The children wore shorts because it was hot.", zh: "短褲" },
    { front: "jacket", pos: "n.", def: "a short coat", example: "Take a jacket — it may be cold later.", zh: "夾克、外套" },
    { front: "coat", pos: "n.", def: "warm clothing you wear outside over other clothes", example: "Put on your coat — it's snowing.", zh: "大衣" },
    { front: "sweater", pos: "n.", def: "a warm piece of clothing for the top of your body", example: "Grandma knitted me a sweater.", zh: "毛衣" },
    { front: "jumper", pos: "n.", def: "a warm piece of clothing that you pull over your head", example: "He wore a thick jumper under his coat.", zh: "套頭毛衣" },
    { front: "suit", pos: "n.", def: "a jacket and trousers or skirt made of the same material", example: "Dad wears a suit for important meetings.", zh: "西裝、套裝" },
    { front: "tie", pos: "n.", def: "a long thin piece of cloth worn around the neck with a shirt", example: "Our school tie is blue and yellow.", zh: "領帶" },
    { front: "belt", pos: "n.", def: "a band you wear around your waist", example: "He needs a belt for these trousers.", zh: "皮帶、腰帶" },
    { front: "sock", pos: "n.", def: "a soft thing you wear on your foot inside your shoe", example: "I can only find one blue sock.", zh: "襪子" },
    { front: "shoe", pos: "n.", def: "a thing you wear on your foot outside", example: "Take off your shoes at the door, please.", zh: "鞋子" },
    { front: "boot", pos: "n.", def: "a shoe that covers your foot and part of your leg", example: "You need boots for walking in the mountains.", zh: "靴子" },
    { front: "trainers", pos: "n.", def: "soft sports shoes", example: "I wear trainers for PE.", zh: "運動鞋" },
    { front: "sandal", pos: "n.", def: "an open shoe for warm weather", example: "She bought new sandals for the summer.", zh: "涼鞋" },
    { front: "slipper", pos: "n.", def: "a soft shoe you wear at home", example: "Grandpa always wears his old slippers.", zh: "拖鞋" },
    { front: "hat", pos: "n.", def: "a thing you wear on your head", example: "Wear a hat in the sun.", zh: "帽子" },
    { front: "cap", pos: "n.", def: "a soft hat with a flat part at the front", example: "He never takes off his baseball cap.", zh: "鴨舌帽" },
    { front: "scarf", pos: "n.", def: "a long piece of cloth you wear around your neck", example: "She wore a warm scarf in the snow.", zh: "圍巾" },
    { front: "gloves", pos: "n.", def: "things you wear on your hands to keep them warm", example: "I lost one of my gloves on the bus.", zh: "手套" },
    { front: "pyjamas", pos: "n.", def: "soft clothes you wear in bed", example: "The children put on their pyjamas at eight.", zh: "睡衣" },
    { front: "swimsuit", pos: "n.", def: "clothing you wear for swimming", example: "Don't forget your swimsuit for the pool.", zh: "泳衣" },
    { front: "raincoat", pos: "n.", def: "a coat that keeps you dry in the rain", example: "Take your raincoat — it's going to rain.", zh: "雨衣" },
    { front: "blouse", pos: "n.", def: "a shirt for a woman or girl", example: "She wore a white blouse and a black skirt.", zh: "女用襯衫" },
    /* ---------- Accessories ---------- */
    { front: "pocket", pos: "n.", def: "a small bag sewn into clothes for keeping things in", example: "He put the coins in his pocket.", zh: "口袋" },
    { front: "button", pos: "n.", def: "a small round thing that closes clothes", example: "A button came off my shirt.", zh: "鈕扣" },
    { front: "zip", pos: "n.", def: "a long metal or plastic thing that opens and closes clothes or bags", example: "The zip on my jacket is broken.", zh: "拉鍊" },
    { front: "ring", pos: "n.", def: "a round piece of jewellery you wear on your finger", example: "She wears a small gold ring.", zh: "戒指" },
    { front: "necklace", pos: "n.", def: "jewellery that you wear around your neck", example: "Mum got a silver necklace for her birthday.", zh: "項鍊" },
    { front: "earrings", pos: "n.", def: "jewellery that you wear on your ears", example: "She was wearing long silver earrings.", zh: "耳環" },
    { front: "bracelet", pos: "n.", def: "jewellery that you wear around your arm", example: "My friend made me a bracelet.", zh: "手鍊" },
    { front: "jewellery", pos: "n.", def: "pretty things like rings and necklaces that you wear", example: "She keeps her jewellery in a little box.", zh: "珠寶、首飾" },
    { front: "handbag", pos: "n.", def: "a small bag that a woman carries", example: "Her phone is in her handbag.", zh: "手提包" },
    { front: "sunglasses", pos: "n.", def: "dark glasses that you wear in the sun", example: "I left my sunglasses at the beach.", zh: "太陽眼鏡" },
    { front: "sleeve", pos: "n.", def: "the part of clothing that covers your arm", example: "He rolled up his sleeves to wash the car.", zh: "袖子" },
    { front: "collar", pos: "n.", def: "the part of a shirt or coat around the neck", example: "His shirt collar was too tight.", zh: "衣領" },
    { front: "label", pos: "n.", def: "a small piece of paper or cloth that gives information about a thing", example: "The label says you can wash it at thirty degrees.", zh: "標籤" },
    { front: "fashion", pos: "n.", def: "the style of clothes that people like at one time", example: "My sister loves reading about fashion.", zh: "時尚、流行" },
    { front: "costume", pos: "n.", def: "special clothes you wear to look like someone else", example: "He wore a pirate costume to the party.", zh: "戲服、裝扮服" },
    { front: "top", pos: "n.", def: "a piece of clothing for the upper body; the highest part", example: "She bought a pink top to go with her jeans.", zh: "上衣；頂部" },
    /* ---------- Wearing clothes ---------- */
    { front: "wear", pos: "v.", def: "to have clothes on your body", example: "She is wearing a green dress today.", zh: "穿、戴" },
    { front: "put on", pos: "phr. v.", def: "to place clothes on your body", example: "Put on your coat before you go out.", zh: "穿上" },
    { front: "take off", pos: "phr. v.", def: "to remove clothes; (of a plane) to leave the ground", example: "Take off your wet shoes.", zh: "脫下；起飛" },
    { front: "fit", pos: "v.", def: "to be the right size for someone", example: "These jeans don't fit me any more.", zh: "合身" },
    { front: "dress up", pos: "phr. v.", def: "to put on special or smart clothes", example: "The children dressed up as animals for the show.", zh: "盛裝打扮、變裝" },
    { front: "get changed", pos: "phrase", def: "to take off your clothes and put on different ones", example: "I'll get changed before dinner.", zh: "換衣服" },
    { front: "dirty", pos: "adj.", def: "not clean", example: "Put your dirty clothes in the washing machine.", zh: "髒的" },
    { front: "smart", pos: "adj.", def: "clean and tidy in style; clever", example: "You look very smart in that suit.", zh: "體面的；聰明的" },
    { front: "casual", pos: "adj.", def: "comfortable and not formal (clothes)", example: "We can wear casual clothes on Fridays.", zh: "休閒的" },
    { front: "tight", pos: "adj.", def: "fitting very closely to your body", example: "These shoes are too tight.", zh: "緊的" },
    { front: "loose", pos: "adj.", def: "not fitting closely; not tight", example: "He likes wearing loose T-shirts.", zh: "寬鬆的" },
    { front: "long", pos: "adj.", def: "measuring a lot from one end to the other", example: "She wore a long black coat.", zh: "長的" },
    { front: "in fashion", pos: "phrase", def: "popular to wear at the moment", example: "Are these boots still in fashion?", zh: "流行中" },
    /* ---------- Materials for clothes ---------- */
    { front: "cotton", pos: "n.", def: "a light natural material for clothes", example: "This T-shirt is made of cotton.", zh: "棉" },
    { front: "wool", pos: "n.", def: "the warm material that comes from sheep", example: "The scarf is made of soft wool.", zh: "羊毛" },
    { front: "leather", pos: "n.", def: "material made from animal skin", example: "He bought a leather jacket.", zh: "皮革" },
    { front: "silk", pos: "n.", def: "a soft shiny natural material", example: "The queen wore a silk dress.", zh: "絲綢" },
    /* ---------- Work & shopping extras ---------- */
    { front: "get a job", pos: "phrase", def: "to start working for a company for money", example: "My brother got a job in a bookshop.", zh: "找到工作" },
    { front: "lend", pos: "v.", def: "to give something to someone for a short time", example: "Can you lend me your ruler?", zh: "借出" },
    { front: "drama", pos: "n.", def: "the school subject where you act; a serious play", example: "We are doing a play in drama this term.", zh: "戲劇" },
    { front: "IT", pos: "n.", def: "the school subject about computers", example: "We learnt how to make a website in IT.", zh: "資訊科技" },
    { front: "sharpener", pos: "n.", def: "a small tool for making a pencil sharp", example: "My pencil broke — can I use your sharpener?", zh: "削鉛筆器" },
    { front: "chalk", pos: "n.", def: "a soft white stick for writing on a board", example: "The teacher drew a circle with chalk.", zh: "粉筆" },
    { front: "changing room", pos: "n.", def: "a room where you try on clothes or change for sport", example: "The changing rooms are next to the shoe department.", zh: "更衣室、試衣間" },
    { front: "shop window", pos: "n.", def: "the big glass at the front of a shop", example: "I saw a lovely dress in the shop window.", zh: "商店櫥窗" },
    { front: "cash machine", pos: "n.", def: "a machine in the street that gives you money from your bank", example: "Dad got some money from the cash machine.", zh: "提款機" },
    { front: "till", pos: "n.", def: "the machine in a shop where you pay", example: "Please pay at the till by the door.", zh: "收銀機、收銀台" },
    { front: "second-hand", pos: "adj.", def: "not new; used by someone else before", example: "He bought a second-hand bike for thirty pounds.", zh: "二手的" },
    { front: "brand new", pos: "phrase", def: "completely new", example: "Look at my brand new trainers!", zh: "全新的" },
    { front: "wrap", pos: "v.", def: "to cover something in paper", example: "I wrapped the present in red paper.", zh: "包裝" },
    { front: "plastic bag", pos: "n.", def: "a bag made of plastic for carrying shopping", example: "We take our own bags instead of buying plastic bags.", zh: "塑膠袋" },
    { front: "list", pos: "n.", def: "words or names written one under another", example: "Her name is first on the list.", zh: "清單、名單" },
    { front: "assistant", pos: "n.", def: "a person who helps someone in their job", example: "The assistant helped me find the right book.", zh: "助理、店員" },
    { front: "interview", pos: "n.", def: "a meeting where someone asks you questions, for a job or a newspaper", example: "She has a job interview on Monday.", zh: "面試、訪談" },
    { front: "form", pos: "n.", def: "a paper with spaces where you write information", example: "Please write your name and address on the form.", zh: "表格" },
    { front: "fill in", pos: "phr. v.", def: "to write information in the spaces on a form", example: "Fill in this form with your details.", zh: "填寫" },
    /* ---------- More jobs ---------- */
    { front: "soldier", pos: "n.", def: "a person in an army", example: "The soldiers marched through the town.", zh: "軍人、士兵" },
    { front: "sailor", pos: "n.", def: "a person who works on a ship", example: "The sailors were happy to see land.", zh: "水手" },
    { front: "film star", pos: "n.", def: "a famous film actor", example: "She dreams of becoming a film star.", zh: "電影明星" },
    { front: "pop star", pos: "n.", def: "a famous pop singer", example: "The pop star sang his new song on TV.", zh: "流行歌手明星" },
    { front: "vet", pos: "n.", def: "a doctor for animals", example: "We took our cat to the vet.", zh: "獸醫" },
    { front: "fisherman", pos: "n.", def: "a person who catches fish", example: "The fishermen go out to sea very early.", zh: "漁夫" },
    /* ---------- More clothes ---------- */
    { front: "tracksuit", pos: "n.", def: "loose warm clothes for doing sport", example: "He wears a tracksuit for football training.", zh: "運動服" },
    { front: "tights", pos: "n.", def: "thin clothing that covers the legs and feet", example: "She wore black tights with her skirt.", zh: "褲襪" },
    { front: "swimming trunks", pos: "n.", def: "shorts that boys and men wear for swimming", example: "He forgot his swimming trunks.", zh: "男用泳褲" },
    { front: "dressing gown", pos: "n.", def: "a long loose piece of clothing worn over pyjamas", example: "She came downstairs in her dressing gown.", zh: "睡袍" },
    /* ---------- Work verbs ---------- */
    { front: "type", pos: "v.", def: "to write with a keyboard", example: "She can type very fast.", zh: "打字" },
    { front: "deliver", pos: "v.", def: "to take letters or things to a place", example: "The postman delivers letters every morning.", zh: "遞送" },
    /* ---------- Countries & nationalities ---------- */
    { front: "country", pos: "n.", def: "an area of land with its own government, like France or Japan", example: "Which country would you like to visit?", zh: "國家" },
    { front: "nationality", pos: "n.", def: "belonging to a country", example: "What nationality are you?", zh: "國籍" },
    { front: "foreign", pos: "adj.", def: "from another country", example: "She loves learning foreign languages.", zh: "外國的" },
    { front: "international", pos: "adj.", def: "between different countries", example: "It is an international school with students from many countries.", zh: "國際的" },
    { front: "flag", pos: "n.", def: "a piece of cloth with a country's colours on it", example: "The French flag is blue, white and red.", zh: "旗幟、國旗" },
    { front: "American", pos: "adj.", def: "from the USA", example: "We watched an American film last night.", zh: "美國的" },
    { front: "British", pos: "adj.", def: "from Britain", example: "The British flag is red, white and blue.", zh: "英國的" },
    { front: "Chinese", pos: "adj.", def: "from China", example: "We had Chinese food for dinner.", zh: "中國的、中文的" },
    { front: "Japanese", pos: "adj.", def: "from Japan", example: "She is learning Japanese cooking.", zh: "日本的、日語的" },
    { front: "Korean", pos: "adj.", def: "from Korea", example: "My friend loves Korean music.", zh: "韓國的、韓語的" },
    { front: "French", pos: "adj.", def: "from France", example: "We learn French at school.", zh: "法國的、法語的" },
    { front: "German", pos: "adj.", def: "from Germany", example: "He drives a German car.", zh: "德國的、德語的" },
    { front: "Spanish", pos: "adj.", def: "from Spain", example: "She sings beautiful Spanish songs.", zh: "西班牙的、西語的" },
    { front: "Italian", pos: "adj.", def: "from Italy", example: "Pizza is a famous Italian food.", zh: "義大利的" },
    { front: "Mexican", pos: "adj.", def: "from Mexico", example: "We tried Mexican food at the new restaurant.", zh: "墨西哥的" },
    { front: "Brazilian", pos: "adj.", def: "from Brazil", example: "The Brazilian team played very well.", zh: "巴西的" },
    { front: "Indian", pos: "adj.", def: "from India", example: "My favourite meal is Indian curry.", zh: "印度的" },
    { front: "Turkish", pos: "adj.", def: "from Turkey", example: "We stayed in a Turkish hotel by the sea.", zh: "土耳其的" },
    { front: "Greek", pos: "adj.", def: "from Greece", example: "We visited some old Greek buildings.", zh: "希臘的" },
    { front: "Polish", pos: "adj.", def: "from Poland", example: "Our Polish neighbours are very friendly.", zh: "波蘭的" },
    { front: "Russian", pos: "adj.", def: "from Russia", example: "She read a famous Russian story.", zh: "俄羅斯的" },
    { front: "Egyptian", pos: "adj.", def: "from Egypt", example: "We saw Egyptian art at the museum.", zh: "埃及的" },
    { front: "Australian", pos: "adj.", def: "from Australia", example: "An Australian student joined our class.", zh: "澳洲的" },
    { front: "Canadian", pos: "adj.", def: "from Canada", example: "My Canadian penfriend sent me a photo of the snow.", zh: "加拿大的" },
    { front: "Irish", pos: "adj.", def: "from Ireland", example: "We listened to Irish music at the festival.", zh: "愛爾蘭的" },
    { front: "Scottish", pos: "adj.", def: "from Scotland", example: "My teacher is Scottish.", zh: "蘇格蘭的" },
    { front: "Welsh", pos: "adj.", def: "from Wales", example: "Some Welsh people speak two languages.", zh: "威爾斯的" },
    { front: "Swiss", pos: "adj.", def: "from Switzerland", example: "Swiss chocolate is famous everywhere.", zh: "瑞士的" },
    { front: "Dutch", pos: "adj.", def: "from the Netherlands", example: "The Dutch team wore orange shirts.", zh: "荷蘭的" },
    { front: "Portuguese", pos: "adj.", def: "from Portugal", example: "People speak Portuguese in Brazil too.", zh: "葡萄牙的、葡語的" },
    /* ---------- Countries ---------- */
    { front: "Britain", pos: "n.", def: "the country of England, Scotland and Wales", example: "My cousin studies in Britain.", zh: "英國、不列顛" },
    { front: "England", pos: "n.", def: "the largest country in Britain", example: "London is the capital of England.", zh: "英格蘭" },
    { front: "France", pos: "n.", def: "a country in Europe; its capital is Paris", example: "We went camping in France last summer.", zh: "法國" },
    { front: "Germany", pos: "n.", def: "a country in the middle of Europe", example: "My uncle works in Germany.", zh: "德國" },
    { front: "Spain", pos: "n.", def: "a country in the south of Europe", example: "It is usually hot and sunny in Spain.", zh: "西班牙" },
    { front: "Italy", pos: "n.", def: "a country in Europe famous for pizza and pasta", example: "We visited Rome when we were in Italy.", zh: "義大利" },
    { front: "China", pos: "n.", def: "a very large country in Asia", example: "The Great Wall is in China.", zh: "中國" },
    { front: "Japan", pos: "n.", def: "an island country in Asia", example: "My penfriend lives in Japan.", zh: "日本" },
    { front: "the USA", pos: "n.", def: "the United States of America", example: "New York is a famous city in the USA.", zh: "美國" },
    { front: "India", pos: "n.", def: "a very large country in Asia", example: "My grandmother was born in India.", zh: "印度" },
    { front: "Turkey", pos: "n.", def: "a country between Europe and Asia", example: "We flew to Turkey for our holiday.", zh: "土耳其" },
    { front: "Greece", pos: "n.", def: "a country in the south of Europe with many islands", example: "Greece has beautiful beaches.", zh: "希臘" },
    { front: "Poland", pos: "n.", def: "a country in the middle of Europe", example: "Warsaw is the capital of Poland.", zh: "波蘭" },
    { front: "Russia", pos: "n.", def: "the largest country in the world", example: "Winters in Russia are very cold.", zh: "俄羅斯" },
    { front: "Egypt", pos: "n.", def: "a country in Africa famous for the pyramids", example: "We saw the pyramids in Egypt.", zh: "埃及" },
    { front: "Australia", pos: "n.", def: "a large island country south of Asia", example: "Kangaroos live in Australia.", zh: "澳洲" },
    { front: "Canada", pos: "n.", def: "a large country north of the USA", example: "My aunt moved to Canada ten years ago.", zh: "加拿大" },
    { front: "Ireland", pos: "n.", def: "an island country west of Britain", example: "The fields in Ireland are very green.", zh: "愛爾蘭" },
    { front: "Scotland", pos: "n.", def: "the country in the north of Britain", example: "There are beautiful mountains in Scotland.", zh: "蘇格蘭" },
    { front: "Wales", pos: "n.", def: "a country in the west of Britain", example: "We walked in the hills of Wales.", zh: "威爾斯" },
    { front: "Brazil", pos: "n.", def: "the largest country in South America", example: "Football is very popular in Brazil.", zh: "巴西" },
    { front: "Taiwan", pos: "n.", def: "an island in Asia famous for its night markets", example: "My family comes from Taiwan.", zh: "台灣" },
    { front: "Mexico", pos: "n.", def: "a country south of the USA", example: "Mexico has a lot of interesting history.", zh: "墨西哥" },
    { front: "Portugal", pos: "n.", def: "a country in the west of Europe, next to Spain", example: "Lisbon is the capital of Portugal.", zh: "葡萄牙" },
    { front: "Switzerland", pos: "n.", def: "a small country in Europe famous for mountains", example: "We went skiing in Switzerland.", zh: "瑞士" },
    { front: "Europe", pos: "n.", def: "the continent with countries like France, Spain and Germany", example: "They travelled around Europe by train.", zh: "歐洲" },
    { front: "world", pos: "n.", def: "the Earth and everything on it", example: "The Amazon is the biggest river in the world.", zh: "世界" },
    /* ---------- Communication & language ---------- */
    { front: "speak", pos: "v.", def: "to say words; to know a language", example: "Do you speak English?", zh: "說（語言）、講話" },
    { front: "say", pos: "v.", def: "to speak words", example: "What did the teacher say?", zh: "說" },
    { front: "tell", pos: "v.", def: "to give information to someone by speaking", example: "Tell me about your holiday.", zh: "告訴" },
    { front: "talk", pos: "v.", def: "to speak with someone", example: "We talked about the film for hours.", zh: "談話" },
    { front: "call", pos: "v.", def: "to phone someone; to give a name to someone", example: "I'll call you when I get home.", zh: "打電話；稱呼" },
    { front: "chat", pos: "v.", def: "to talk in a friendly way", example: "We chatted about music on the way home.", zh: "聊天" },
    { front: "shout", pos: "v.", def: "to speak very loudly", example: "Don't shout — I can hear you.", zh: "大喊" },
    { front: "conversation", pos: "n.", def: "a talk between people", example: "We had a long conversation about football.", zh: "對話、交談" },
    { front: "voice", pos: "n.", def: "the sound you make when you speak or sing", example: "The singer has a lovely voice.", zh: "聲音、嗓音" },
    { front: "joke", pos: "n.", def: "something you say to make people laugh", example: "He told a funny joke at dinner.", zh: "笑話" },
    { front: "secret", pos: "n.", def: "something you do not tell other people", example: "Can you keep a secret?", zh: "秘密" },
    { front: "promise", pos: "v.", def: "to say that you will really do something", example: "I promise I will write to you every week.", zh: "承諾、保證" },
    { front: "agree", pos: "v.", def: "to have the same idea as someone", example: "I agree with you — the film was great.", zh: "同意" },
    { front: "mean", pos: "v.", def: "to have a meaning; to want to say", example: "What does this word mean?", zh: "意思是" },
    { front: "translate", pos: "v.", def: "to change words from one language to another", example: "Can you translate this sentence into English?", zh: "翻譯" },
    { front: "grammar", pos: "n.", def: "the rules of a language", example: "English grammar is not too difficult.", zh: "文法" },
    { front: "meaning", pos: "n.", def: "what a word or sentence tells you", example: "Look up the meaning of the word in a dictionary.", zh: "意思、意義" },
    { front: "pronounce", pos: "v.", def: "to make the sound of a word", example: "How do you pronounce this name?", zh: "發音" },
    /* ---------- Adjectives for things ---------- */
    { front: "useful", pos: "adj.", def: "helping you to do something", example: "A dictionary is useful when you learn a language.", zh: "有用的" },
    { front: "broken", pos: "adj.", def: "not working; in pieces", example: "My watch is broken.", zh: "壞掉的" },
    { front: "heavy", pos: "adj.", def: "weighing a lot; hard to carry", example: "This suitcase is too heavy for me.", zh: "重的" },
    { front: "soft", pos: "adj.", def: "not hard; nice to touch", example: "The kitten's fur is very soft.", zh: "柔軟的" },
    { front: "round", pos: "adj.", def: "shaped like a circle or ball", example: "We sat at a round table.", zh: "圓的" },
    { front: "square", pos: "adj.", def: "with four equal sides", example: "The present came in a square box.", zh: "正方形的" },
    { front: "thick", pos: "adj.", def: "not thin; measuring a lot from one side to the other", example: "She wore a thick coat in the snow.", zh: "厚的" },
    { front: "sharp", pos: "adj.", def: "able to cut things easily", example: "Be careful — that knife is very sharp.", zh: "鋒利的" },
    { front: "shiny", pos: "adj.", def: "bright, like light on glass or metal", example: "He cleaned his shoes until they were shiny.", zh: "閃亮的" },
    /* ---------- School phrases ---------- */
    { front: "at school", pos: "phrase", def: "in the school building; being a student there", example: "My little brother is still at school.", zh: "在學校" },
    { front: "after school", pos: "phrase", def: "when lessons have finished for the day", example: "We play basketball after school on Tuesdays.", zh: "放學後" },
    { front: "go to school", pos: "phrase", def: "to attend school as a student", example: "I go to school by bus.", zh: "上學" },
    { front: "leave school", pos: "phrase", def: "to finish your time as a school student", example: "My sister left school last year and now works in a shop.", zh: "畢業、離校" },
    { front: "get good marks", pos: "phrase", def: "to do well in school work or tests", example: "She studies hard and always gets good marks.", zh: "取得好成績" },
    { front: "make a mistake", pos: "phrase", def: "to do something wrong", example: "Don't worry if you make a mistake.", zh: "犯錯" },
    { front: "ask a question", pos: "phrase", def: "to say a question to someone", example: "You can ask a question at the end of the lesson.", zh: "提問" },
    { front: "do well", pos: "phrase", def: "to be successful", example: "She did well in her piano exam.", zh: "表現好" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
