/* CPE Prep bank: Reading True/False/Not Given (C2) — wave 7 */
(function () {
var TFNG = ["True", "False", "Not Given"];
var BANK = [
  {
    id: "cpe-rtfng7-01",
    title: "A Cure That Kept Being Forgotten",
    text: "Scurvy killed more sailors on long voyages than storms, wrecks and hostile action combined, and its cure was discovered, forgotten and rediscovered several times before it was reliably applied.\nThe disease results from a deficiency of a compound that most mammals synthesise and that humans cannot, so that a diet lacking fresh plant material produces symptoms within a few months: bleeding gums, wounds that reopen, and eventually collapse. On voyages of the sixteenth and seventeenth centuries the loss of half a crew was not exceptional.\nRemedies based on fresh vegetables or citrus were recorded repeatedly by individual commanders, and each such record was followed by a period during which the knowledge did not travel. A controlled comparison conducted on a naval vessel in the seventeen-forties tested several proposed treatments on sailors with the disease and found that those given citrus recovered while the others did not. The experiment is now cited as an early example of a clinical trial and had very little immediate effect on practice.\nThe reasons for that delay are instructive. The prevailing theory of disease attributed scurvy to bad air or to the effects of salt provisions rather than to an absence of anything, and a remedy that fitted no accepted mechanism was easily doubted. Citrus was also expensive to carry, and administrators comparing proposed provisions had no framework in which a preventive measure could be valued against the cost of the fruit.\nWhen supply was eventually adopted on a fleet-wide basis, the effect was dramatic and was itself later undermined. A change in the source of the fruit, and the practice of boiling the juice for storage, reduced the potency of the ration considerably, and expeditions provisioned in this way suffered from the disease while carrying what everybody believed to be a preventive. Polar expeditions of the early twentieth century encountered scurvy for exactly this reason and produced explanations involving tainted food.\nThe compound responsible was identified in the nineteen-thirties, and the confusion ended at that point.",
    questions: [
      { q: "Scurvy caused more deaths at sea than storms and shipwrecks together.", options: TFNG, answer: 0, explanation: "True - it 'killed more sailors on long voyages than storms, wrecks and hostile action combined'." },
      { q: "Humans are able to synthesise the compound whose absence causes scurvy.", options: TFNG, answer: 1, explanation: "False - it is a compound 'that most mammals synthesise and that humans cannot'." },
      { q: "The trial of the seventeen-forties changed naval practice immediately.", options: TFNG, answer: 1, explanation: "False - it 'had very little immediate effect on practice'." },
      { q: "The prevailing theory of disease made the citrus remedy easy to doubt.", options: TFNG, answer: 0, explanation: "True - a remedy fitting no accepted mechanism was easily doubted." },
      { q: "The officer who conducted the trial was promoted as a result of it.", options: TFNG, answer: 2, explanation: "Not Given - the text describes the trial but says nothing about its author's career." },
      { q: "Boiling the juice reduced the effectiveness of the ration.", options: TFNG, answer: 0, explanation: "True - boiling for storage 'reduced the potency of the ration considerably'." },
      { q: "Polar expeditions of the early twentieth century avoided scurvy entirely.", options: TFNG, answer: 1, explanation: "False - they 'encountered scurvy for exactly this reason'." },
      { q: "The compound responsible was identified in the nineteen-thirties.", options: TFNG, answer: 0, explanation: "True - stated directly in the final paragraph." },
    ]
  },
  {
    id: "cpe-rtfng7-02",
    title: "Making Threads Agree",
    text: "A screw thread is a simple thing to make and a difficult thing to standardise, and the history of the standard illustrates how much of industrial capability consists of agreement rather than invention.\nBefore standardisation, threads were cut by individual workshops to their own dimensions, so that a bolt and a nut were a matched pair and were frequently marked to keep them together. A machine repaired away from its maker required threads to be cut to fit, and the practical consequence was that spare parts in the modern sense did not exist for threaded fastenings.\nThe proposal that changed this was made in the middle of the nineteenth century and specified not merely a set of diameters but the angle of the thread form and the relationship between diameter and pitch. Because the specification described a family rather than a list, a manufacturer could produce a size not previously made and be confident that it would mate with anybody else's example of the same size.\nAdoption was uneven and was driven by the industries that suffered most from incompatibility. Railway companies, whose rolling stock was repaired at many locations, had an obvious interest, and their adoption exerted pressure on their suppliers, which is the ordinary mechanism by which such standards spread.\nA competing system with a different thread angle was developed later and became established in another country, and the coexistence of two standards produced difficulties whose scale became apparent during the wars of the twentieth century, when equipment manufactured in one place had to be maintained in another. Committees were convened, an agreement was reached on a unified form for the nations concerned, and a substantial quantity of existing tooling was thereby rendered obsolete.\nThe subsequent adoption of metric threads in most of the world did not eliminate the earlier systems, which persist in specific industries and in the maintenance of older equipment. A workshop today may hold taps and dies for several incompatible families, which is the physical residue of a sequence of decisions each of which was reasonable when taken.",
    questions: [
      { q: "Before standardisation a bolt and nut were often kept together as a pair.", options: TFNG, answer: 0, explanation: "True - they 'were frequently marked to keep them together'." },
      { q: "The nineteenth-century proposal specified only a list of diameters.", options: TFNG, answer: 1, explanation: "False - it specified 'not merely a set of diameters but the angle of the thread form' and the pitch relationship." },
      { q: "Railway companies had a particular interest in standardised threads.", options: TFNG, answer: 0, explanation: "True - their rolling stock was repaired at many locations." },
      { q: "The competing system used a different thread angle.", options: TFNG, answer: 0, explanation: "True - 'A competing system with a different thread angle'." },
      { q: "The unified standard was agreed before the wars of the twentieth century.", options: TFNG, answer: 1, explanation: "False - the difficulties became apparent during those wars, after which committees were convened." },
      { q: "The unification agreement made some existing tooling obsolete.", options: TFNG, answer: 0, explanation: "True - 'a substantial quantity of existing tooling was thereby rendered obsolete'." },
      { q: "Manufacturers were compensated for the tooling they had to replace.", options: TFNG, answer: 2, explanation: "Not Given - the text notes obsolescence but says nothing about compensation." },
      { q: "Metric adoption eliminated the earlier thread systems.", options: TFNG, answer: 1, explanation: "False - it 'did not eliminate the earlier systems, which persist'." },
    ]
  },
  {
    id: "cpe-rtfng7-03",
    title: "The Bird That Follows the Summer",
    text: "The Arctic tern undertakes the longest regular migration known in any animal, breeding in the high northern latitudes and spending the northern winter in the seas around Antarctica.\nThe scale of the journey was suspected from ringing recoveries long before it could be measured, since a bird ringed at a northern colony and recovered in the southern ocean establishes the endpoints and nothing about the route. The problem was resolved by miniature recording devices light enough to be carried without impeding flight, which log ambient light and from which position can be estimated by the timing of sunrise and sunset.\nThe tracks obtained were longer than expected. Individual birds were found to travel distances well in excess of the straight-line separation of the two regions, because the routes followed prevailing wind systems rather than the shortest path, and several birds crossed from one side of an ocean to the other in a way that no direct route would require. A bird of this species that lives for twenty years accumulates a total flight distance comparable with several journeys to the moon and back.\nThe tracking also revealed a period of some weeks in the north Atlantic during the southward journey, in an area of high biological productivity, which had not been suspected and is presumed to be a period of feeding before the longer crossing.\nWhat the birds gain from the arrangement is daylight. By following the summer of each hemisphere, an Arctic tern experiences more hours of daylight in a year than any other animal, and the feeding opportunity that daylight represents is the usual explanation for a migration whose energetic cost is otherwise difficult to justify.\nThe species breeds in colonies on open ground and is aggressive in defence of a nest, attacking intruders of any size that approach it. The dependence on productive polar seas at both ends makes the population sensitive to changes in the distribution of the small fish and crustaceans on which it feeds.",
    questions: [
      { q: "Ringing recoveries revealed the route taken by the birds.", options: TFNG, answer: 1, explanation: "False - a recovery 'establishes the endpoints and nothing about the route'." },
      { q: "The tracking devices estimate position from the timing of sunrise and sunset.", options: TFNG, answer: 0, explanation: "True - they log ambient light and position is estimated from that timing." },
      { q: "The routes followed were longer than the straight-line distance.", options: TFNG, answer: 0, explanation: "True - distances were 'well in excess of the straight-line separation'." },
      { q: "The birds follow prevailing wind systems rather than the shortest path.", options: TFNG, answer: 0, explanation: "True - stated directly in the text." },
      { q: "A stopover in the north Atlantic had been predicted before tracking.", options: TFNG, answer: 1, explanation: "False - it 'had not been suspected'." },
      { q: "The species experiences more daylight annually than any other animal.", options: TFNG, answer: 0, explanation: "True - 'an Arctic tern experiences more hours of daylight in a year than any other animal'." },
      { q: "Young birds make the first migration in the company of adults.", options: TFNG, answer: 2, explanation: "Not Given - the text does not describe how young birds migrate." },
      { q: "The species nests in trees.", options: TFNG, answer: 1, explanation: "False - it 'breeds in colonies on open ground'." },
    ]
  },
  {
    id: "cpe-rtfng7-04",
    title: "Reading a Lost Script",
    text: "The decipherment of Egyptian hieroglyphs took two decades and rested on a stone bearing the same decree in three scripts, discovered by a French expedition in 1799 and subsequently transferred to British possession.\nThe decree itself is administrative rather than remarkable in content. Its value lay in the arrangement: a text in hieroglyphs, a version in a cursive Egyptian script, and a version in Greek, which scholars could read. A comparison therefore offered a route into a writing system that had not been read for more than a thousand years.\nProgress was slower than the availability of such a text might suggest, because the prevailing assumption was wrong. Hieroglyphs were understood to be symbolic, each sign standing for an idea rather than a sound, and generations of scholars had produced elaborate interpretations on that basis. The system in fact combines signs representing sounds with signs representing meaning, and until that mixture was accepted no consistent reading was possible.\nThe first substantial advance came from the observation that certain groups of signs were enclosed in an oval loop and that these corresponded to royal names in the Greek text. A name written in a foreign language must be spelt phonetically, and the enclosed groups therefore supplied sound values for individual signs, which could then be tested elsewhere.\nThe scholar who completed the work extended those values beyond the foreign names to native Egyptian words, which required abandoning the assumption that phonetic writing was reserved for foreign terms. His knowledge of Coptic, a later stage of the Egyptian language written in a Greek-derived alphabet, allowed him to check proposed readings against a language that had survived.\nThe stone remains among the most visited objects in the museum that holds it, and its ownership has been the subject of formal requests for return.",
    questions: [
      { q: "The stone carries the same decree in three scripts.", options: TFNG, answer: 0, explanation: "True - hieroglyphs, a cursive Egyptian script and Greek." },
      { q: "The content of the decree is of exceptional historical interest.", options: TFNG, answer: 1, explanation: "False - it is 'administrative rather than remarkable in content'." },
      { q: "Scholars long assumed that each hieroglyph stood for an idea.", options: TFNG, answer: 0, explanation: "True - they were 'understood to be symbolic, each sign standing for an idea'." },
      { q: "The enclosed groups of signs corresponded to royal names.", options: TFNG, answer: 0, explanation: "True - they 'corresponded to royal names in the Greek text'." },
      { q: "Phonetic writing in Egyptian was used only for foreign words.", options: TFNG, answer: 1, explanation: "False - the decipherer extended phonetic values to native Egyptian words." },
      { q: "Knowledge of Coptic allowed proposed readings to be tested.", options: TFNG, answer: 0, explanation: "True - Coptic 'allowed him to check proposed readings against a language that had survived'." },
      { q: "The decipherer visited Egypt before completing his work.", options: TFNG, answer: 2, explanation: "Not Given - the text says nothing about his travels." },
      { q: "The return of the stone has been formally requested.", options: TFNG, answer: 0, explanation: "True - 'its ownership has been the subject of formal requests for return'." },
    ]
  },
  {
    id: "cpe-rtfng7-05",
    title: "Knowing Where You Are",
    text: "Determining latitude at sea has never been difficult, since the height of the sun at noon or of a known star gives it directly. Longitude is a different problem: it is equivalent to knowing the difference between local time, which can be observed, and the time at a reference place, which cannot be observed and must be carried.\nThe practical consequence was that ships knew how far north or south they were and could only estimate how far east or west, by recording their speed and heading and accumulating the result. Errors in that estimate accumulated over weeks and produced wrecks on coasts that navigators believed to be a considerable distance away.\nTwo solutions were pursued through the eighteenth century. One used the moon, whose position against the stars changes rapidly enough to serve as a clock, requiring accurate tables, careful observation and a calculation that occupied several hours. The other required a timepiece that would keep the reference time through months at sea, despite motion, temperature change and variation in humidity, none of which any clock of the period could tolerate.\nThe timepieces eventually produced by a self-taught clockmaker met the requirement, and the trials of his instruments established that a mechanical solution was possible. The lunar method was nonetheless used alongside chronometers for decades afterwards, because a chronometer was expensive, because a single one could not be checked against anything, and because the tables and the technique were already in place.\nThe eventual arrangement combined the two: ships carried several chronometers and compared them, and observations of the moon or of the sun were used to check for drift. Longitude was finally fixed to a reference meridian by international agreement in the late nineteenth century, an arrangement that required the acceptance of one nation's observatory as the origin and was adopted for practical rather than principled reasons.",
    questions: [
      { q: "Latitude can be obtained from the height of the sun at noon.", options: TFNG, answer: 0, explanation: "True - the height of the sun at noon or of a known star gives it directly." },
      { q: "Longitude requires knowing the time at a reference place.", options: TFNG, answer: 0, explanation: "True - it is equivalent to knowing the difference between local time and reference time." },
      { q: "Estimates of east-west position became more accurate over a long voyage.", options: TFNG, answer: 1, explanation: "False - errors 'accumulated over weeks'." },
      { q: "The lunar method required calculations lasting several hours.", options: TFNG, answer: 0, explanation: "True - 'a calculation that occupied several hours'." },
      { q: "The clockmaker had been formally trained in his craft.", options: TFNG, answer: 2, explanation: "Not Given - he is described as self-taught, but no detail about formal training is stated beyond that." },
      { q: "Chronometers replaced the lunar method immediately.", options: TFNG, answer: 1, explanation: "False - the lunar method 'was nonetheless used alongside chronometers for decades'." },
      { q: "Ships eventually carried more than one chronometer.", options: TFNG, answer: 0, explanation: "True - 'ships carried several chronometers and compared them'." },
      { q: "The reference meridian was agreed on principled rather than practical grounds.", options: TFNG, answer: 1, explanation: "False - it 'was adopted for practical rather than principled reasons'." },
    ]
  },
  {
    id: "cpe-rtfng7-06",
    title: "The Canal and the Mosquito",
    text: "The first attempt to cut a canal across the isthmus of Panama was abandoned after several years, having consumed an enormous sum and a still more remarkable number of lives. The engineering difficulties were substantial and were not the principal reason for the failure.\nThe two diseases responsible were yellow fever and malaria, and the medical understanding of the period attributed both to the atmosphere of low, wet ground. Hospitals were built on the assumption that contaminated air caused the illness, and in several cases the legs of beds were placed in bowls of water to keep insects from climbing them, which produced breeding sites for mosquitoes in the wards themselves.\nThe transmission of yellow fever by a mosquito was demonstrated experimentally at the end of the nineteenth century by a commission working in Cuba, using human volunteers under conditions that would not now be permitted. The demonstration was decisive, and it converted a disease of unknown cause into a problem of controlling a specific insect with identifiable breeding habits.\nWhen work resumed under a second administration, a sanitary campaign preceded and accompanied the excavation. Standing water was drained or oiled, buildings were screened, water containers were covered, and infected people were isolated behind netting so that mosquitoes could not acquire the infection from them. Yellow fever was eliminated from the zone within about two years; malaria, whose vector breeds in a wider range of sites, was reduced substantially but not removed.\nThe campaign was opposed within the project on grounds of cost, and the officer directing it had to argue repeatedly that expenditure on drainage was expenditure on excavation. The eventual completion of the canal is attributed in most accounts to engineering decisions, chiefly the choice of a lock canal over a sea-level cut. The sanitary work is a less visible part of the explanation and was the condition on which the rest depended, since no workforce could have been assembled and retained under the conditions of the first attempt.",
    questions: [
      { q: "The first attempt failed principally because of engineering difficulties.", options: TFNG, answer: 1, explanation: "False - the engineering difficulties 'were not the principal reason for the failure'." },
      { q: "Bowls of water under hospital beds created mosquito breeding sites.", options: TFNG, answer: 0, explanation: "True - they 'produced breeding sites for mosquitoes in the wards themselves'." },
      { q: "The mosquito transmission of yellow fever was demonstrated using human volunteers.", options: TFNG, answer: 0, explanation: "True - the commission worked 'using human volunteers'." },
      { q: "The volunteers were paid for their participation.", options: TFNG, answer: 2, explanation: "Not Given - the text mentions volunteers and conditions but says nothing about payment." },
      { q: "Yellow fever was eliminated from the canal zone within about two years.", options: TFNG, answer: 0, explanation: "True - stated directly in the text." },
      { q: "Malaria was also eliminated completely.", options: TFNG, answer: 1, explanation: "False - it 'was reduced substantially but not removed'." },
      { q: "The sanitary campaign was resisted within the project on cost grounds.", options: TFNG, answer: 0, explanation: "True - 'The campaign was opposed within the project on grounds of cost'." },
      { q: "Most accounts of the canal's completion emphasise the sanitary work.", options: TFNG, answer: 1, explanation: "False - completion 'is attributed in most accounts to engineering decisions', with the sanitary work less visible." },
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
