/* CPE Prep bank: Reading multiple choice (C2) — wave 8 */
(function () {
var BANK = [
  {
    id: "cpe-rmc8-01",
    title: "The Vice of Coherence",
    text: "There is a peculiar pleasure in an explanation that accounts for everything, and it is a pleasure that ought to arouse suspicion rather more often than it does. The satisfaction is aesthetic before it is intellectual: a story in which each element bears on every other, in which nothing is left over and no detail is merely there, produces in the reader a sensation of understanding that is largely independent of whether the story is true.\nThe difficulty is that the world is under no obligation to be coherent, and the sources from which any account is built are systematically biased towards the material that survives. A historian working from documents has the documents that were kept; a clinician reconstructing a course of illness has the symptoms the patient thought worth mentioning; an investigator has the evidence that was not destroyed, and each of these produces a residue from which a tidy account can be assembled precisely because the untidy parts are missing.\nWhat follows is not that coherent accounts are false. It is that coherence is not evidence, and that the confidence it produces is unearned. A narrative that leaves several elements unexplained is, other things being equal, more likely to be tracking something real than one in which everything fits, since reality routinely produces coincidences, dead ends and details that do not signify.\nThe professional consequences are visible in every field that reconstructs events after the fact. Investigators of accidents are trained, with some difficulty, to resist the account that emerges in the first four hours; historians are taught to distrust the source that answers all their questions; and the better sort of biographer is recognisable by a willingness to say that a period is obscure and to leave it so, rather than to supply the plausible material that would close the gap.\nThe recommendation, if there is one, is uncomfortable in proportion to its usefulness. When an explanation arrives that accounts for everything, the appropriate response is to ask what has been left out in order to allow it to do so, and the answer is generally available to anybody who wants it, which is a smaller population than one might suppose.",
    questions: [
      { q: "What does the writer say about the pleasure of a complete explanation?", options: ["It is aesthetic and should prompt suspicion","It indicates careful reasoning","It is rarely experienced","It is primarily intellectual"], answer: 0, explanation: "'The satisfaction is aesthetic before it is intellectual'." },
      { q: "Why do sources tend to produce tidy accounts?", options: ["Because they are edited deliberately", "Because untidy material has not survived", "Because they are written by professionals", "Because coherence is required by convention"], answer: 1, explanation: "'a tidy account can be assembled precisely because the untidy parts are missing'." },
      { q: "What is the writer's claim about coherence?", options: ["It is impossible to achieve","It proves an account is false","It is not evidence and produces unearned confidence","It is the strongest available evidence"], answer: 2, explanation: "'coherence is not evidence, and that the confidence it produces is unearned'." },
      { q: "Why may an account with loose ends be preferable?", options: ["It requires fewer sources","It is more persuasive","It is easier to write","Reality produces details that do not signify"], answer: 3, explanation: "'reality routinely produces coincidences, dead ends and details that do not signify'." },
      { q: "How does the writer characterise a good biographer?", options: ["By willingness to leave a period obscure","By the range of sources used","By narrative skill","By the completeness of the account"], answer: 0, explanation: "'a willingness to say that a period is obscure and to leave it so'." },
      { q: "What does the final sentence imply?", options: ["The answer is usually unobtainable", "Few people want to know what was omitted", "Most people ask the right question", "The recommendation is easy to follow"], answer: 1, explanation: "'which is a smaller population than one might suppose'." }
    ]
  },
  {
    id: "cpe-rmc8-02",
    title: "What the Inventory Cannot Hold",
    text: "Heritage protection developed as a practice of listing things, and the apparatus that surrounds it — designation, curtilage, consent — presupposes an object with an edge. Applied to a building or a painting the assumption is unproblematic. Applied to a practice, a craft or a form of knowledge that exists only in its performance, it produces a category error that a substantial international effort has spent two decades attempting to manage.\nThe difficulty is not administrative. A practice that is inscribed on a list acquires attention, funding and visitors, and each of those alters it; the version that is protected becomes, within a generation, the version that is performed for the people who came because it was protected. This is not a failure of implementation and it is not avoidable by better guidance, since the mechanism is the protection itself.\nThe alternative positions are both unattractive. To decline to intervene is to leave a practice to a set of economic pressures under which it will generally disappear, and the disappearance is not a neutral outcome that anybody chose. To intervene is to fix, in a description, something that was continuously changing, and to establish an authoritative version at a particular moment, which is precisely what a living practice does not have.\nThe more sophisticated schemes attempt to address this by inscribing the community rather than the practice, and by making the community the arbiter of what constitutes a legitimate development. This is a genuine improvement and it relocates rather than resolves the problem, since a community is not a body with a single view, and the question of which members speak for it is answered, in practice, by whoever is available and willing to be consulted.\nWhat may be said in defence of the whole enterprise is that its alternative was not preservation but silence. A practice that vanishes without documentation vanishes entirely, and an imperfect record made by people who altered what they recorded is, on any reasonable comparison, preferable. That is a modest claim and it is the one the evidence supports, and it is considerably less than the claims that appear in the literature of the field.",
    questions: [
      { q: "What does the writer identify as the founding assumption of heritage protection?", options: ["That practices are unchanging","That objects can be valued in money","That the thing protected has an edge","That communities want protection"], answer: 2, explanation: "'presupposes an object with an edge'." },
      { q: "Why does protection alter a practice?", options: ["Because performers resist it","Because listing is inaccurate","Because guidance is poorly written","Because attention and funding change it"], answer: 3, explanation: "'attention, funding and visitors, and each of those alters it'." },
      { q: "What does the writer say about declining to intervene?", options: ["It generally leads to disappearance","It preserves authenticity","It is administratively simpler","It is the neutral choice"], answer: 0, explanation: "'under which it will generally disappear'." },
      { q: "How does the writer assess community-based schemes?", options: ["As unworkable in principle","As a genuine improvement that relocates the problem","As entirely successful","As no different from earlier schemes"], answer: 1, explanation: "'a genuine improvement and it relocates rather than resolves the problem'." },
      { q: "Who effectively speaks for a community in practice?", options: ["External assessors","Elected representatives","Whoever is available and willing","The oldest practitioners"], answer: 2, explanation: "'by whoever is available and willing to be consulted'." },
      { q: "What defence of the enterprise does the writer accept?", options: ["That it is popular with communities","That it generates income","That it preserves practices unchanged","That the alternative was silence"], answer: 3, explanation: "'its alternative was not preservation but silence'." }
    ]
  },
  {
    id: "cpe-rmc8-03",
    title: "In Praise of the Temporary",
    text: "A structure erected for a season, a scheme funded for eighteen months, an appointment described as interim: these are treated, by the institutions that create them, as inferior versions of the permanent thing they could not afford. The assumption deserves examination, since the temporary arrangement possesses properties that the permanent one cannot have and that are, on inspection, frequently the source of whatever success it achieves.\nThe first is that it can be wrong. A permanent installation is a claim about the future that its authors are required to defend, and the defence begins at the moment of opening and continues for as long as anybody involved remains in post. A temporary one is a proposition, and a proposition that fails is information rather than embarrassment, which permits a category of attempt that no permanent budget would authorise.\nThe second is that it attracts a different kind of participant. The people who will give a year to something they expect to end are not, in general, the people who would give a career to it, and the difference is not one of seriousness. What a defined ending removes is the requirement to commit indefinitely, and a substantial population of capable people is available on those terms and on no other.\nThe third property is more paradoxical. Temporary arrangements are frequently better maintained than permanent ones, because a thing that is known to be ending is inspected, and a thing assumed to be permanent is inherited by a series of people who assume that somebody previously established that it worked.\nNone of this constitutes an argument for provisionality as a general policy, which would be its own kind of foolishness: certain functions require an institution that will still exist in forty years, and an organisation composed entirely of pilots is one that has decided nothing. The argument is narrower and, correspondingly, more likely to be useful. Before a proposal is made permanent, it is worth asking which of its virtues depend on its not being so, and the question is almost never asked, since the natural ambition of everybody involved is to secure exactly the status that will remove them.",
    questions: [
      { q: "How do institutions generally regard temporary arrangements?", options: ["As inferior versions of permanent ones","As the preferred option","As administratively convenient","As experiments worth repeating"], answer: 0, explanation: "'inferior versions of the permanent thing they could not afford'." },
      { q: "What is the first advantage the writer identifies?", options: ["Lower cost", "The capacity to be wrong", "Speed of delivery", "Public enthusiasm"], answer: 1, explanation: "'The first is that it can be wrong.'" },
      { q: "What does a defined ending remove for participants?", options: ["Accountability","The need for expertise","The requirement to commit indefinitely","Financial risk"], answer: 2, explanation: "'the requirement to commit indefinitely'." },
      { q: "Why may temporary things be better maintained?", options: ["They have larger budgets","They are less used","They are newer","Because a known ending prompts inspection"], answer: 3, explanation: "'a thing that is known to be ending is inspected'." },
      { q: "What does the writer say about organisations composed only of pilots?", options: ["They have decided nothing","They attract the best staff","They are the future","They are efficient"], answer: 0, explanation: "'an organisation composed entirely of pilots is one that has decided nothing'." },
      { q: "Why is the writer's key question rarely asked?", options: ["It is difficult to answer", "Everybody involved wants permanence", "It is prohibited by funders", "It has been answered already"], answer: 1, explanation: "'the natural ambition of everybody involved is to secure exactly the status that will remove them'." }
    ]
  },
  {
    id: "cpe-rmc8-04",
    title: "Being Wrong Where People Can See",
    text: "The correction of a published error is among the least ceremonious acts available to a professional and among the most consequential for the field in which it occurs, and the disproportion between those two facts explains a good deal about why the correction is so frequently deferred.\nConsider what is actually required. The author must establish that the error is real, which generally means conducting the work again in circumstances that will produce an unwelcome answer; must determine its extent, which is rarely confined to the sentence in which it appears; and must then produce a document whose only function is to reduce the standing of its own author. No institutional mechanism assists with any of these, and several impede them.\nThe response of a field to such a document is the variable that determines whether it will receive another. Where a correction is treated as evidence of unreliability, the rational course for anybody who discovers an error in their own work is silence, and the resulting literature is one in which the errors are those that nobody was willing to identify. Where a correction is received as ordinary professional conduct, the volume of them rises and the field acquires, at some cost to its dignity, a considerably more accurate account of itself.\nThe empirical position is discouraging. Studies of retraction and correction consistently find that the citation of a corrected work continues at a substantial rate afterwards, frequently without any reference to the correction, and that a proportion of the citations reproduce the erroneous claim. The mechanism is not dishonesty; it is that a reader encounters a paper through a reference in another paper and has no occasion to check its subsequent history.\nThere is a modest structural remedy that has been available for two decades and that a minority of publishers apply: linking every version of a document to its corrections so that no route to the original omits them. Where this has been implemented the propagation falls markedly. That it has not been implemented universally is not a technical matter and is not, on any reading, a defensible one, and the explanation lies in the ordinary reluctance of any institution to make its own errors easier to find.",
    questions: [
      { q: "What explains why corrections are deferred?", options: ["Legal restrictions","The difficulty of writing them","The disproportion between their cost and their ceremony","A lack of interest in accuracy"], answer: 2, explanation: "'the disproportion between those two facts explains a good deal'." },
      { q: "What must an author usually do to establish an error?", options: ["Withdraw the paper","Wait for a reviewer","Consult colleagues informally","Repeat the work expecting an unwelcome answer"], answer: 3, explanation: "'conducting the work again in circumstances that will produce an unwelcome answer'." },
      { q: "What happens where corrections are treated as unreliability?", options: ["Silence becomes the rational course","Standards improve","More corrections are published","Errors are identified faster"], answer: 0, explanation: "'the rational course... is silence'." },
      { q: "What do studies of corrected work find?", options: ["Citation stops immediately", "Citation continues, often without reference to the correction", "Corrections are always noticed", "Errors are rarely repeated"], answer: 1, explanation: "'continues at a substantial rate afterwards, frequently without any reference to the correction'." },
      { q: "Why do readers miss corrections?", options: ["They lack access","They are dishonest","They encounter the work through another paper's reference","Corrections are hidden deliberately"], answer: 2, explanation: "'a reader encounters a paper through a reference in another paper'." },
      { q: "How does the writer explain the failure to adopt linking?", options: ["Publishers cannot afford it","Authors object to it","It is technically difficult","Institutions are reluctant to expose their errors"], answer: 3, explanation: "'the ordinary reluctance of any institution to make its own errors easier to find'." }
    ]
  },
  {
    id: "cpe-rmc8-05",
    title: "The Uses of Anachronism",
    text: "To describe a fifteenth-century arrangement as a corporation, or a medieval dispute as a case of intellectual property, is to commit the offence for which historians reprove their students most reliably. The reproof is justified and it conceals a difficulty, which is that the alternative — describing the past exclusively in its own vocabulary — produces an account that is unintelligible to anybody who does not already possess it.\nThe defensible position, which most working historians occupy without articulating it, is that anachronism is a tool with a specific and limited application. A modern term may be used to indicate a resemblance, provided the resemblance is the thing being asserted and the differences are then stated. What is illegitimate is the use of a modern term to import, silently, the assumptions that attach to it: to call an institution a corporation and thereby to attribute to it a separate legal personality, limited liability and a shareholder interest that its members would not have recognised.\nThe more insidious version operates at the level of the question rather than the vocabulary. To ask of a fourteenth-century community what its rate of literacy was is to ask a question formed by a modern conception of reading as an individual and silent activity, applied to a society in which a text was frequently encountered in performance and in which the relevant distinction was not between those who could read and those who could not.\nThe corresponding danger, which the discipline discusses considerably less, is the reverse error. An insistence that the past is wholly foreign, that its categories are incommensurable with ours, is itself a position with consequences: it renders the past useless for any purpose except contemplation, and it is frequently deployed to prevent an inconvenient comparison rather than to prevent an inaccurate one.\nThe practical test proposed by the more careful practitioners is neither elegant nor difficult. Any modern term applied to an earlier period should be accompanied by a statement of what it is doing there, and a reader who cannot determine from the text whether a resemblance is being asserted or assumed is entitled to conclude that the author has not determined it either.",
    questions: [
      { q: "What difficulty does the standard reproof conceal?", options: ["That the alternative produces an unintelligible account","That students rarely commit the error","That vocabulary changes constantly","That anachronism is unavoidable in translation"], answer: 0, explanation: "'produces an account that is unintelligible to anybody who does not already possess it'." },
      { q: "When may a modern term legitimately be used?", options: ["Never","When it indicates a resemblance that is then qualified","When no earlier term exists","When the audience is general"], answer: 1, explanation: "'provided the resemblance is the thing being asserted and the differences are then stated'." },
      { q: "What makes the use of a modern term illegitimate?", options: ["Its origin in another discipline","Its unfamiliarity","The silent importing of modern assumptions","Its precision"], answer: 2, explanation: "'to import, silently, the assumptions that attach to it'." },
      { q: "Why is the literacy question problematic?", options: ["It is politically sensitive","It has already been answered","The data are unavailable","It applies a modern conception of reading"], answer: 3, explanation: "'a question formed by a modern conception of reading'." },
      { q: "What is the reverse error the writer identifies?", options: ["Insisting the past is wholly foreign","Excessive quotation","Neglect of primary sources","Over-reliance on statistics"], answer: 0, explanation: "'An insistence that the past is wholly foreign'." },
      { q: "What test do careful practitioners propose?", options: ["Avoiding modern terms entirely", "Stating what a modern term is doing there", "Consulting a specialist", "Using footnotes for all terms"], answer: 1, explanation: "'accompanied by a statement of what it is doing there'." }
    ]
  },
  {
    id: "cpe-rmc8-06",
    title: "Against the Legacy Project",
    text: "It is customary, on the departure of anybody who has held a position of consequence, to speak of a legacy, and the word does a great deal of concealed work. It suggests an estate, a thing bequeathed and received, when what is generally meant is a set of arrangements that will now be maintained, altered or abandoned by people who did not make them and who owe the departing figure nothing whatever.\nThe consequences of the metaphor are not merely rhetorical. An office-holder who conceives of their tenure as producing a legacy is under a specific temptation, which is to prefer the intervention that is visible and attributable to the one that is effective. A building bears a name; a reformed process does not, and neither does a decision not to proceed with something, which is frequently the most valuable act available and is by construction invisible.\nThe temptation is aggravated by the length of a modern tenure. Where an appointment runs for four or five years, the interventions whose benefits accrue within that period are a small subset of those worth making, and a post-holder attending to their own record will select from that subset. Anything whose returns arrive in year eleven is undertaken, if at all, by somebody who has decided not to care about the question this essay is about.\nThere is a further difficulty concerning what successors inherit. An arrangement created as a monument is harder to alter than one created as a solution, because altering it is read as a judgement on a person rather than as a response to circumstances. A departing figure who genuinely wishes to be useful will therefore do the opposite of what the language of legacy suggests: they will document the reasoning rather than the achievement, and they will make it as easy as possible for a successor to undo their work.\nThat is a considerable thing to ask of anybody, and it is asked, in practice, of nobody. The institutions that hold farewell events and commission portraits are the same institutions that will complain, a decade later, that they cannot modify an arrangement because of what it is called and who is still alive.",
    questions: [
      { q: "What does the word legacy conceal, according to the writer?", options: ["The role of institutions","The cost of an appointment","That successors owe the departing figure nothing","The length of a tenure"], answer: 2, explanation: "'people who did not make them and who owe the departing figure nothing whatever'." },
      { q: "What temptation does the metaphor create?", options: ["To stay in post too long","To avoid difficult decisions","To delegate excessively","To prefer visible interventions over effective ones"], answer: 3, explanation: "'to prefer the intervention that is visible and attributable to the one that is effective'." },
      { q: "Which act is described as valuable but invisible?", options: ["Deciding not to proceed with something","Recruiting a successor","Publishing a strategy","Commissioning a building"], answer: 0, explanation: "'a decision not to proceed with something'." },
      { q: "How does the length of tenure aggravate the problem?", options: ["It reduces available funding", "Only short-return interventions are selected", "It prevents documentation", "It shortens consultation"], answer: 1, explanation: "'a post-holder attending to their own record will select from that subset'." },
      { q: "Why is a monument harder to alter?", options: ["It is technically complex","It costs more","Altering it reads as a judgement on a person","It is legally protected"], answer: 2, explanation: "'altering it is read as a judgement on a person'." },
      { q: "What does the writer say a genuinely useful figure would do?", options: ["Refuse a farewell event","Publish their achievements","Extend their tenure","Make it easy for a successor to undo their work"], answer: 3, explanation: "'make it as easy as possible for a successor to undo their work'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
