/* CPE Prep bank: Reading multiple choice (C2) — wave 13 */
(function () {
var BANK = [
  {
    id: "cpe-rmc13-01",
    title: "The Interview as an Instrument",
    text: "Few practices have been examined as thoroughly, and abandoned as reluctantly, as the unstructured selection interview. The findings have been stable for several decades: a conversation of the customary kind predicts subsequent performance at a level barely distinguishable from chance, and does so while consuming a great deal of senior time and generating conviction in everybody involved.\nThe conviction is the interesting part. Interviewers emerge with a strong sense of having formed an accurate impression, and the strength of that sense is unrelated to its accuracy, which is a combination that makes the practice unusually resistant to evidence. A person told that their judgement in such settings is worthless will accept the finding in general and exempt their own case, on the grounds of an experience that consists entirely of impressions never checked against outcomes.\nThe mechanism has been identified with reasonable confidence. An unstructured conversation permits the interviewer to pursue whatever seems interesting, which means the questions differ between candidates and the comparison is therefore between impressions rather than between answers. It also rewards fluency, composure and similarity to the interviewer, none of which is predictive of much, and all of which are conspicuous within the first minutes and colour everything afterwards.\nWhat does work is known and is used less often than its record deserves. A structured interview with the same questions in the same order, scored against defined criteria immediately after each answer, performs substantially better; a work sample performs better still, for the unsurprising reason that watching somebody do the task is more informative than discussing it. Neither is expensive, and both are resisted, because they feel mechanical and they remove the pleasure of the encounter.\nThe honest position for an organisation is therefore uncomfortable. If the conversation is retained, it should be retained on the stated ground that it serves purposes other than prediction, which it does: candidates form impressions too, and a process without human contact loses people who had other options. What cannot be defended is retaining it while believing that it works, since that belief is the one thing the evidence has ruled out.",
    questions: [
      { q: "What do the findings on unstructured interviews show?", options: ["Prediction barely distinguishable from chance","They are improving","They favour experienced interviewers","They predict performance well"], answer: 0, explanation: "'predicts subsequent performance at a level barely distinguishable from chance'." },
      { q: "Why is the practice resistant to evidence?", options: ["Alternatives are costly","Confidence is unrelated to accuracy","The evidence is disputed","It is legally required"], answer: 1, explanation: "'the strength of that sense is unrelated to its accuracy'." },
      { q: "How do interviewers treat the general finding?", options: ["They change their practice","They reject it","They accept it and exempt themselves","They demand replication"], answer: 2, explanation: "'will accept the finding in general and exempt their own case'." },
      { q: "What is the problem with differing questions?", options: ["Interviews run long","Records are incomplete","Candidates are confused","Comparison is between impressions rather than answers"], answer: 3, explanation: "'the comparison is therefore between impressions rather than between answers'." },
      { q: "Why does a work sample perform best?", options: ["Watching somebody do the task is more informative","It takes less time","Candidates prefer it","It is cheaper"], answer: 0, explanation: "'watching somebody do the task is more informative than discussing it'." },
      { q: "What position does the writer say cannot be defended?", options: ["Keeping the conversation for other purposes", "Keeping it while believing it works", "Abolishing interviews", "Using work samples"], answer: 1, explanation: "'retaining it while believing that it works'." }
    ]
  },
  {
    id: "cpe-rmc13-02",
    title: "The Quiet Change of Mind",
    text: "Public changes of position are rare, are treated as newsworthy when they occur, and are for that reason a poor guide to how opinion actually moves. What happens far more often is a private revision that is never announced, in which a person comes to hold a different view and allows the fact to emerge gradually, and the absence of an announcement is not cowardice so much as an accurate reading of what an announcement would cost.\nThe cost is levied in a specific currency. A person who states that they were wrong invites the inference that their present judgement is equally unreliable, and the inference is drawn by people who have never revised anything and whose consistency is therefore unblemished. The incentive facing anybody who has changed their mind is to do so silently, and the incentive is strongest precisely where the stakes are highest and the revision would be most useful to others.\nThis produces a distortion in what the public record contains. Positions appear more stable than they are, disagreements appear more entrenched, and the useful information — the argument or the evidence that actually moved somebody — is lost, since it was never recorded. A person who has changed their mind possesses something valuable, which is a demonstration that the change is possible and an account of what produced it, and the value is destroyed by the silence that self-interest recommends.\nThere are contexts in which the announcement is obligatory rather than admirable. Anybody who has argued a position publicly and persuaded others has incurred a debt to those people, and the debt is not discharged by quietly holding something else; a reader who was convinced by an argument is entitled to know that its author no longer finds it convincing.\nWhat would improve matters is not more courage, which is difficult to arrange, but a change in how revision is received. An audience that treats a stated change of view as evidence of attention rather than of unreliability will receive more of them, and will be better informed. This is within the gift of readers rather than of writers, which is an unusual position for a problem of intellectual honesty to be in.",
    questions: [
      { q: "Why are public changes of position a poor guide?", options: ["They occur too late","They are dishonest","Most revision happens privately","They are exaggerated"], answer: 2, explanation: "'a private revision that is never announced'." },
      { q: "What inference does admitting error invite?", options: ["That they were misled","That they lack expertise","That the person is honest","That present judgement is equally unreliable"], answer: 3, explanation: "'invites the inference that their present judgement is equally unreliable'." },
      { q: "Who draws that inference?", options: ["People who have never revised anything","Former allies","Editors","Experts"], answer: 0, explanation: "'drawn by people who have never revised anything'." },
      { q: "What is lost from the public record?", options: ["The original argument", "What actually moved somebody", "The date of the change", "The names involved"], answer: 1, explanation: "'the argument or the evidence that actually moved somebody'." },
      { q: "When is announcement obligatory?", options: ["When the stakes are low","Always","When one has persuaded others publicly","When asked directly"], answer: 2, explanation: "'has argued a position publicly and persuaded others has incurred a debt'." },
      { q: "What does the writer say would improve matters?", options: ["Stricter editing","Fewer public arguments","Greater courage","A change in how revision is received"], answer: 3, explanation: "'not more courage, which is difficult to arrange, but a change in how revision is received'." }
    ]
  },
  {
    id: "cpe-rmc13-03",
    title: "Outside the Frame",
    text: "A photograph is received as a record of what was there and is more accurately described as a record of a decision about where to stand, and the two differ in ways that no amount of technical fidelity reduces. Everything within the frame is true; what the image cannot convey is the relation of that content to everything the photographer chose to exclude.\nThe classic demonstrations are not tricks. A gathering photographed from the front, tightly framed, is indistinguishable from one ten times its size; the same gathering photographed from behind, with the empty space included, is indistinguishable from a failure. Neither image has been altered and the two support opposite conclusions, and a viewer possesses no means of determining which they are looking at.\nA second exclusion is temporal. A photograph records an instant that was selected from a continuous sequence, and human faces pass through configurations that misrepresent what the person was doing throughout: the frame in which a speaker appears enraged may be a twenty-fourth of a second within an otherwise unremarkable sentence. The still image is not a summary of the interval; it is a sample from it, chosen by somebody who was looking for something.\nThe third and least examined exclusion concerns the photographer's presence. People behave differently when a camera is visible, and the behaviour recorded is behaviour in the presence of recording, which is a different phenomenon from the one the image appears to document. The exception is the concealed camera, which purchases authenticity at a price that is generally judged too high.\nNone of this argues for distrusting photographs, which would discard the most useful documentary instrument available. It argues for a specific question, asked routinely and almost never asked: what is immediately outside this frame, and who decided that it should be? An image that cannot be interrogated in this way is not evidence about an event; it is evidence about the intentions of the person who produced it, which is worth knowing and is not what it is being offered as.",
    questions: [
      { q: "What does the writer say a photograph actually records?", options: ["A decision about where to stand","The photographer's skill","The available light","What was there"], answer: 0, explanation: "'a record of a decision about where to stand'." },
      { q: "What can the image not convey?", options: ["Colour accurately", "The relation to what was excluded", "The time of day", "The location"], answer: 1, explanation: "'the relation of that content to everything the photographer chose to exclude'." },
      { q: "What does the gathering example show?", options: ["That angles distort colour","That editing is common","That unaltered images support opposite conclusions","That crowds are hard to count"], answer: 2, explanation: "'Neither image has been altered and the two support opposite conclusions'." },
      { q: "What is a still image in relation to an interval?", options: ["An average","A reconstruction","A summary","A sample chosen by somebody looking for something"], answer: 3, explanation: "'it is a sample from it, chosen by somebody who was looking for something'." },
      { q: "What does a visible camera record?", options: ["Behaviour in the presence of recording","Staged events","Nothing reliable","Ordinary behaviour"], answer: 0, explanation: "'the behaviour recorded is behaviour in the presence of recording'." },
      { q: "What question does the writer recommend?", options: ["Who owns the image", "What is outside the frame and who decided", "When it was taken", "Whether it was edited"], answer: 1, explanation: "'what is immediately outside this frame, and who decided that it should be?'" }
    ]
  },
  {
    id: "cpe-rmc13-04",
    title: "The Line Has to Go Somewhere",
    text: "Any rule that distinguishes between cases must place a boundary, and the boundary will fall between two cases that differ imperceptibly. This is not a defect in particular rules; it is a property of the operation of ruling, and the arguments that proceed by pointing at the pair on either side of a line are arguments against having lines at all, which is a position their authors do not hold.\nThe familiar move is to observe that a person one day below a threshold is indistinguishable from one a day above it and to conclude that the threshold is arbitrary. The conclusion does not follow. A threshold may be arbitrary in its precise location and entirely non-arbitrary in its existence, and the two properties are routinely conflated by people who would be unwilling to accept the alternative, which is discretionary assessment of every case by an official.\nThat alternative deserves attention, since it is what is being proposed whenever a bright line is criticised. Case-by-case judgement is more accurate at the margin and considerably worse in every other respect: it is slower, more expensive, unpredictable in advance, impossible to appeal against on any principled ground, and it distributes outcomes according to the applicant's ability to present themselves, which correlates with advantages the rule was frequently designed to offset.\nThere are, nonetheless, real questions about how a line should be drawn. It should fall where the distribution is sparse rather than where it is dense, so that the number of cases sitting adjacent to it is minimised. It should be accompanied by a stated rationale, so that a subsequent challenge can address the reasoning. And it should be reviewed on a schedule, since a boundary set against conditions that have changed becomes arbitrary in the second sense as well as the first.\nWhat should not be conceded is the demand that a rule justify its exact position against the case just outside it. That case will always exist, its existence carries no information about whether the rule is sound, and a system that accepts the demand will find itself with no rules at all and a great deal of discretion, which is what those making the demand were usually seeking.",
    questions: [
      { q: "What does the writer say about boundaries falling between similar cases?", options: ["It applies only to legal rules","It is a defect of poor rules","It is a property of ruling itself","It can be avoided by care"], answer: 2, explanation: "'it is a property of the operation of ruling'." },
      { q: "What two properties are conflated?", options: ["Cost and accuracy","Law and custom","Fairness and speed","Arbitrary location and arbitrary existence"], answer: 3, explanation: "'arbitrary in its precise location and entirely non-arbitrary in its existence'." },
      { q: "What is the implied alternative to bright lines?", options: ["Discretionary assessment by an official", "Random allocation", "No decisions at all", "Automated scoring"], answer: 0, explanation: "'discretionary assessment of every case by an official'." },
      { q: "What does case-by-case judgement correlate with?", options: ["Need", "The applicant's ability to present themselves", "Length of application", "Geographic location"], answer: 1, explanation: "'according to the applicant's ability to present themselves'." },
      { q: "Where should a line fall?", options: ["At the median","Where precedent suggests","Where the distribution is sparse","At a round number"], answer: 2, explanation: "'It should fall where the distribution is sparse'." },
      { q: "What does the writer say a system accepting the demand ends with?", options: ["Simpler rules","More appeals","Fairer outcomes","No rules and a great deal of discretion"], answer: 3, explanation: "'will find itself with no rules at all and a great deal of discretion'." }
    ]
  },
  {
    id: "cpe-rmc13-05",
    title: "Why We Count in Tens",
    text: "Commemoration clusters at intervals that have no relation to anything except the arithmetic of the decimal system, and the clustering has effects on public memory that are worth examining precisely because nobody chose them.\nThe mechanism is straightforward. A fiftieth anniversary secures attention that a forty-seventh cannot, and the attention brings resources: the archive is opened, the survivors are interviewed, the accounts are collected while collection remains possible. Events that fall at convenient intervals are therefore documented, and events falling awkwardly receive their attention when they are already beyond the reach of testimony.\nThe second effect concerns generational timing. A fiftieth anniversary arrives when those who were present as adults are in their seventies, which is the last moment at which a substantial body of first-hand recollection can be gathered, and the coincidence is fortunate rather than designed. A seventy-fifth arrives when the participants are gone and the commemoration is conducted by people who have inherited an account, and the character of the occasion changes accordingly: it becomes a statement about the present rather than an inquiry into the past.\nThe third effect is a distortion in what is remembered at all. Commemoration requires a date, and processes do not have dates. A war has an armistice; the decline of an industry does not, and it is therefore commemorated nowhere despite having altered more lives more permanently. Public memory accordingly consists disproportionately of events that happened on a day, which is a category that correlates with the political and the military and against the economic and the gradual.\nThe corrective available to anybody arranging such an occasion is modest and it is not nothing. An anniversary can be used to collect rather than to conclude: to record the recollections that remain, to open the material that has not been examined, and to state plainly what is still unknown. An occasion organised in that spirit leaves something behind other than a photograph of the ceremony, which is what most of them leave.",
    questions: [
      { q: "What determines commemoration intervals?", options: ["The arithmetic of the decimal system","Political convenience","Archive availability","Historical significance"], answer: 0, explanation: "'no relation to anything except the arithmetic of the decimal system'." },
      { q: "What does attention bring?", options: ["Controversy", "Resources for documentation", "Tourism", "Legislation"], answer: 1, explanation: "'the attention brings resources'." },
      { q: "Why is the fiftieth anniversary fortunate?", options: ["It attracts the most visitors","It follows a natural cycle","It coincides with the last first-hand recollection","It is easiest to fund"], answer: 2, explanation: "'the last moment at which a substantial body of first-hand recollection can be gathered'." },
      { q: "How does a seventy-fifth anniversary differ?", options: ["It is more accurate","It is privately organised","It is better attended","It becomes a statement about the present"], answer: 3, explanation: "'it becomes a statement about the present rather than an inquiry into the past'." },
      { q: "Why is the decline of an industry not commemorated?", options: ["Processes do not have dates","Records are lost","Survivors decline to speak","It is not important"], answer: 0, explanation: "'Commemoration requires a date, and processes do not have dates.'" },
      { q: "What does the writer recommend for such occasions?", options: ["Standardising the format","Using them to collect rather than conclude","Reducing their frequency","Making them private"], answer: 1, explanation: "'An anniversary can be used to collect rather than to conclude'." }
    ]
  },
  {
    id: "cpe-rmc13-06",
    title: "Simplification Is Not Explanation",
    text: "The instruction to explain a technical matter simply is issued constantly and is understood by almost everybody to mean the same thing as saying less, which is a misunderstanding with consequences that fall on the audience rather than on the speaker.\nAn explanation succeeds when a listener can subsequently do something they could not do before: predict an outcome, recognise a case, ask a question that bears on the matter. A simplification that removes the mechanism produces none of these. It produces a sentence the listener can repeat, and repetition is mistaken for understanding by both parties, since the listener now possesses a form of words and the speaker has heard it used correctly.\nThe distinction is visible in what happens next. A person who has received an explanation will apply it to a case that was not mentioned and will get somewhere; a person who has received a simplification will apply it to such a case and will produce nonsense, having no way of knowing that the case falls outside the range of what they were told. The failure is invisible until it matters, and it is then attributed to the listener.\nWhat genuine simplification requires is harder than reduction and is a different operation altogether. It involves identifying which element of a mechanism does the essential work, constructing an analogy that preserves that element and distorts only what is peripheral, and — the step that is almost always omitted — saying where the analogy breaks down. That last sentence costs ten seconds and converts a misleading picture into a usable one, since a listener who knows the limits of a model can tell when they have reached them.\nThe deeper obstacle is that this cannot be done by somebody who does not thoroughly understand the material, because deciding what is peripheral is the whole difficulty and requires knowing what everything is for. The common arrangement, in which the explaining is delegated to communication staff working from a summary, therefore produces simplifications of the useless kind reliably, and the reliability is structural rather than a reflection on anybody's competence.",
    questions: [
      { q: "How is the instruction to explain simply usually understood?", options: ["As avoiding jargon","As using analogies","As saying less","As speaking slowly"], answer: 2, explanation: "'the same thing as saying less'." },
      { q: "When does an explanation succeed?", options: ["When the listener agrees","When it is short","When it is remembered","When the listener can do something new"], answer: 3, explanation: "'a listener can subsequently do something they could not do before'." },
      { q: "What does a mechanism-free simplification produce?", options: ["A sentence the listener can repeat","Confusion","Further questions","Partial understanding"], answer: 0, explanation: "'It produces a sentence the listener can repeat'." },
      { q: "What happens with an unmentioned case?", options: ["The speaker is blamed","The listener produces nonsense unknowingly","The listener asks for help","The explanation transfers well"], answer: 1, explanation: "'will produce nonsense, having no way of knowing that the case falls outside the range'." },
      { q: "Which step is almost always omitted?", options: ["Giving examples","Choosing an analogy","Saying where the analogy breaks down","Defining terms"], answer: 2, explanation: "'saying where the analogy breaks down'." },
      { q: "Why does delegating explanation fail structurally?", options: ["Summaries are inaccurate","Audiences are inattentive","Communication staff lack time","Deciding what is peripheral requires deep understanding"], answer: 3, explanation: "'deciding what is peripheral is the whole difficulty and requires knowing what everything is for'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
