/* CPE Prep bank: Reading multiple choice (C2) — wave 25 */
(function () {
var BANK = [
  {
    id: "cpe-rmc25-01",
    title: "The Number That Was Mentioned First",
    text: "The first figure introduced into a negotiation exerts an influence on the settlement that neither party intends and that both would deny, and the effect has been demonstrated under conditions that exclude every explanation except the one that is uncomfortable.\nThe most striking demonstrations use figures that carry no information at all. Participants told to consider an arbitrary number, produced by a visibly random process and known by everybody present to be irrelevant, subsequently produce estimates that are pulled towards it. The effect survives warnings, survives financial incentives for accuracy, and survives among experts estimating quantities in their own field, which excludes the explanation that it is a failure of the inexperienced.\nThe mechanism appears to be that an estimate is produced by adjustment from a starting point, and the adjustment stops when a value becomes plausible rather than when it becomes correct. Since the region of plausibility is wide, the stopping point depends on where the adjustment began, and a starting point supplied by somebody else therefore determines a great deal about where it ends.\nThe practical consequences in negotiation are direct and are known to those who negotiate professionally. Making the first offer confers an advantage where one has any reasonable information about value, which is contrary to the common advice to let the other party speak first; and the counter to a first offer is not a counter-offer, which anchors on the same figure by responding to it, but the introduction of an independent basis for valuation before any number is discussed.\nWhat is worth extracting from this is a general point about how estimates should be assembled. A judgement formed after exposure to somebody's figure is not independent of that figure, whatever the person forming it believes, and the only reliable defence is procedural: produce one's own estimate, in writing, before hearing theirs. This is the same remedy that applies to second opinions, to group forecasts and to interview panels, and its recurrence suggests that the underlying problem is not a set of separate biases but a single fact about how judgement works.",
    questions: [
      { q: "What excludes alternative explanations?", options: ["The use of visibly random, irrelevant figures","Long time frames","Expert participants only","Large sample sizes"], answer: 0, explanation: "'produced by a visibly random process and known by everybody present to be irrelevant'." },
      { q: "What does the effect's survival among experts show?", options: ["Training helps","It is not a failure of the inexperienced","It is small","It affects only estimates"], answer: 1, explanation: "'excludes the explanation that it is a failure of the inexperienced'." },
      { q: "When does adjustment stop?", options: ["When the other party agrees","When a value becomes correct","When a value becomes plausible","After a fixed time"], answer: 2, explanation: "'the adjustment stops when a value becomes plausible rather than when it becomes correct'." },
      { q: "What does the writer say about making the first offer?", options: ["It should be avoided","It has no effect","It is unprofessional","It confers an advantage with reasonable information"], answer: 3, explanation: "'Making the first offer confers an advantage where one has any reasonable information'." },
      { q: "What is the correct counter to a first offer?", options: ["An independent basis for valuation","Silence","A walkout","A counter-offer"], answer: 0, explanation: "'the introduction of an independent basis for valuation before any number is discussed'." },
      { q: "What does the recurrence of the remedy suggest?", options: ["Separate biases", "A single fact about how judgement works", "Poor training", "Cultural variation"], answer: 1, explanation: "'a single fact about how judgement works'." }
    ]
  },
  {
    id: "cpe-rmc25-02",
    title: "The Light in the Room",
    text: "Lighting is the element of an interior that is noticed least and determines most, and the disproportion is a consequence of the fact that it is perceived as a property of the objects it falls on rather than as an intervention in its own right.\nThe technical variables are few and their effects are large. The colour of a light source determines whether surfaces appear as they would in daylight or are shifted towards a warmth or coldness that the occupant attributes to the paint; the direction determines whether faces are legible or are divided into bright and shadowed regions that make expression difficult to read; and the ratio between the brightest and darkest parts of a room determines whether it is experienced as a single space or as a series of places. None of these is difficult to control and all of them are routinely left to whatever fitting was cheapest.\nThe overhead source that is standard in most institutional interiors is the arrangement that performs worst on all three. It produces uniform illumination, which removes the variation by which a space is understood; it lights from above, which is the direction under which human faces are hardest to read; and it renders colour indifferently. It is chosen because it is cheap to install, easy to maintain and produces a number on a plan that satisfies a standard expressed in illumination per square metre, which is the wrong quantity.\nThe alternative is not a matter of expenditure so much as of distribution. Several smaller sources at the height at which people sit, producing pools rather than a plane, generate the variation that permits a room to be occupied differently at different times, and the total energy consumed is generally lower. The obstacle is that the standard against which the installation will be assessed cannot represent the difference.\nWhat this illustrates is a general problem with regulation by measurable proxy. A standard requiring a quantity of light per unit area is enforceable, auditable and indifferent to everything that determines whether a room works, and it will be met by the cheapest arrangement that satisfies it. The result is a building stock lit to a standard that nobody defends on its merits and that is nevertheless what the rules require.",
    questions: [
      { q: "Why is lighting noticed least?", options: ["It is technical","It is invisible","It is perceived as a property of the objects it falls on","It is standardised"], answer: 2, explanation: "'perceived as a property of the objects it falls on'." },
      { q: "What does the direction of light determine?", options: ["Energy use","Room size perception","Colour rendering","Whether faces are legible"], answer: 3, explanation: "'the direction determines whether faces are legible'." },
      { q: "What does the brightness ratio determine?", options: ["Whether a room is one space or several places", "Colour accuracy", "Maintenance cost", "Glare"], answer: 0, explanation: "'whether it is experienced as a single space or as a series of places'." },
      { q: "Why is the overhead source chosen?", options: ["It performs best", "It is cheap and satisfies a standard", "It is preferred by occupants", "It renders colour well"], answer: 1, explanation: "'chosen because it is cheap to install, easy to maintain'." },
      { q: "What does the alternative require?", options: ["Higher energy use","Greater expenditure","Different distribution","New technology"], answer: 2, explanation: "'not a matter of expenditure so much as of distribution'." },
      { q: "What general problem does this illustrate?", options: ["Poor training","Rising costs","Technological change","Regulation by measurable proxy"], answer: 3, explanation: "'a general problem with regulation by measurable proxy'." }
    ]
  },
  {
    id: "cpe-rmc25-03",
    title: "The Paper That Covered the Council",
    text: "The disappearance of local newspapers is discussed as a commercial event and its consequences are civic, and the research that has accumulated in the last decade allows the consequences to be stated with some precision rather than asserted.\nThe function that has been lost is not principally the reporting of what happened. It is the routine presence of somebody in the room: a reporter attending a council meeting, a planning hearing, a magistrates' court, most of which produce nothing worth printing on most days. The value of that presence lay in its being expected, since the knowledge that a proceeding may be reported alters what occurs in it, and the alteration does not require that anything be printed.\nThe measurable consequences follow from the removal of that expectation. Studies comparing places that lost a local paper with comparable places that did not have found increased borrowing costs for municipalities, attributable to reduced scrutiny of their finances; lower turnout in local elections; and a reduction in the number of candidates standing, since a contest that nobody reports is one in which a challenger cannot become known. Each of these is a cost borne by everybody in the area, including those who never read the paper.\nThe replacement that was expected has not materialised in the form anticipated. Social platforms distribute information about a locality efficiently and produce very little of it, since the production required somebody paid to attend proceedings that are usually dull, and that role has no equivalent in a system where distribution is free and attendance is not.\nThe experiments that show promise are unromantic. Public or philanthropic funding of reporters attached to specified public bodies, with output made freely available to any outlet, separates the production of the record from the business of selling it, and the early evaluations are encouraging. What they cannot restore is the bundle: a publication that people read for the sport and the notices, and which financed the coverage of the council as a by-product, was a mechanism nobody designed and nobody has replaced.",
    questions: [
      { q: "What function has principally been lost?", options: ["The routine presence of somebody in the room","Advertising","Editorial comment","Reporting what happened"], answer: 0, explanation: "'the routine presence of somebody in the room'." },
      { q: "Why did that presence have value?", options: ["It produced good copy", "Being expected altered what occurred", "It employed people", "It informed readers"], answer: 1, explanation: "'the knowledge that a proceeding may be reported alters what occurs in it'." },
      { q: "What did studies find about municipal finances?", options: ["Improved accounting","No change","Increased borrowing costs","Lower spending"], answer: 2, explanation: "'increased borrowing costs for municipalities'." },
      { q: "Why do fewer candidates stand?", options: ["Rules have changed","Interest has declined","Costs have risen","A challenger cannot become known"], answer: 3, explanation: "'a challenger cannot become known'." },
      { q: "Why have platforms not replaced the function?", options: ["They distribute but produce little", "They are unpopular", "They are expensive", "They exclude local content"], answer: 0, explanation: "'distribute information about a locality efficiently and produce very little of it'." },
      { q: "What cannot be restored?", options: ["Advertising revenue","The bundle that financed council coverage","Printing technology","Reader trust"], answer: 1, explanation: "'What they cannot restore is the bundle'." }
    ]
  },
  {
    id: "cpe-rmc25-04",
    title: "Putting the Bends Back",
    text: "Rivers that were straightened at considerable expense are now being restored to a meandering course at considerable expense, and the sequence is instructive about how a problem is defined and what is excluded when it is.\nThe original works were competent solutions to the problem as posed. A river confined to a straight, deepened channel moves water off agricultural land quickly, and the land becomes workable; the engineering achieved exactly this and was correctly regarded as a success by the people who commissioned it. What the definition omitted was that water removed quickly from one place arrives quickly somewhere else, and the somewhere else was downstream and was frequently a town.\nThe hydrological account is not complicated. A meander lengthens the course, slows the flow and permits water to spill into adjacent ground during high flows, where it is stored and released slowly; the vegetation and the irregular bed add resistance that has the same effect. Straightening removes all of this, converting a system that attenuated a flood peak into one that transmits it, and the transmission is efficient in proportion to the quality of the engineering.\nThe restoration works now being undertaken reintroduce the features that were removed, and their justification is a flood defence for settlements downstream, purchased by accepting inundation of land upstream. This is a transfer between parties, and where it has been managed well the upstream landholder is compensated for storing water, which converts an imposition into a service that is paid for. Where it has not been, the schemes are resisted and the resistance is reasonable.\nWhat the episode illustrates is not that the original engineers were mistaken about hydrology, which they were not. They were answering the question they were asked, within the boundary they were given, and the boundary excluded everybody downstream. The instructive point is that a boundary drawn around a problem is a decision about whose interests are counted, and that it is generally made implicitly, by whoever is paying, at a stage before anybody notices that a decision is being taken.",
    questions: [
      { q: "How does the writer describe the original works?", options: ["Experimental","Incompetent","Competent solutions to the problem as posed","Unnecessary"], answer: 2, explanation: "'competent solutions to the problem as posed'." },
      { q: "What did the definition omit?", options: ["Soil quality","Wildlife","The cost","That water arrives quickly somewhere else"], answer: 3, explanation: "'water removed quickly from one place arrives quickly somewhere else'." },
      { q: "What does a meander do?", options: ["Slows the flow and permits spill into adjacent ground", "Increases erosion", "Deepens the channel", "Reduces storage"], answer: 0, explanation: "'A meander lengthens the course, slows the flow'." },
      { q: "What does straightening convert the system into?", options: ["One that silts up","One that transmits a flood peak","One that stores water","One that dries out"], answer: 1, explanation: "'converting a system that attenuated a flood peak into one that transmits it'." },
      { q: "What makes restoration schemes acceptable?", options: ["Legal compulsion","Public consultation","Compensating the upstream landholder","Lower cost"], answer: 2, explanation: "'the upstream landholder is compensated for storing water'." },
      { q: "What is the instructive point?", options: ["Engineers were mistaken","Restoration is cheaper","Agriculture should be reduced","A boundary decides whose interests are counted"], answer: 3, explanation: "'a boundary drawn around a problem is a decision about whose interests are counted'." }
    ]
  },
  {
    id: "cpe-rmc25-05",
    title: "The Charity That Counts",
    text: "The demand that charitable organisations demonstrate their effectiveness is entirely reasonable and has produced a set of consequences that its proponents did not intend, which is the ordinary fate of reasonable demands applied through a measurement.\nThe difficulty is that effectiveness is easy to demonstrate for some interventions and impossible for others, and the difference does not correspond to how much good is done. An organisation distributing a specific item to a defined population can report a number that is genuine and comparable; one working to change a legal framework, or to sustain a community over decades, cannot report anything of the kind, and the absence of a figure is read by funders as an absence of effect.\nThe resulting shift in what gets funded is documented and predictable. Resources move towards interventions whose results appear within a reporting period, are attributable to the organisation reporting them, and can be counted per unit of expenditure. This is a defensible category of work and it is not the whole of what is required, and the categories it displaces — prevention, advocacy, the maintenance of institutions that respond when something goes wrong — share the property of being invisible in the metric.\nA second effect operates on the organisations themselves. The proportion of expenditure devoted to overheads is reported and compared, and is treated by donors as a measure of efficiency, with the consequence that organisations minimise the expenditure that appears under that heading. What appears under that heading is evaluation, training, financial control and the retention of experienced staff, and an organisation that has reduced them has improved its ratio and damaged its capacity to do anything.\nWhat would improve matters is a change in what is asked for rather than an abandonment of accountability. A funder asking what an organisation has learnt, what it stopped doing as a result, and what it would do differently with a larger grant obtains information that no ratio contains, and obtains it from organisations that cannot produce a number. That such questions are asked rarely reflects the cost of reading answers to them, which is borne by the funder, against the cost of producing a comparable figure, which is not.",
    questions: [
      { q: "What does effectiveness measurement fail to track?", options: ["How much good is done", "Expenditure", "Staff numbers", "Donor numbers"], answer: 0, explanation: "'the difference does not correspond to how much good is done'." },
      { q: "How do funders read the absence of a figure?", options: ["As a warning sign","As an absence of effect","As poor reporting","As long-term work"], answer: 1, explanation: "'the absence of a figure is read by funders as an absence of effect'." },
      { q: "Which work is displaced?", options: ["Emergency response","Fundraising","Prevention and advocacy","Direct distribution"], answer: 2, explanation: "'prevention, advocacy, the maintenance of institutions'." },
      { q: "What appears under the overheads heading?", options: ["Programme delivery","Grants made","Marketing only","Evaluation, training and financial control"], answer: 3, explanation: "'evaluation, training, financial control and the retention of experienced staff'." },
      { q: "What does minimising overheads achieve?", options: ["Improved ratio, damaged capacity", "Genuine efficiency", "Higher donations", "Better outcomes"], answer: 0, explanation: "'improved its ratio and damaged its capacity to do anything'." },
      { q: "Why are better questions asked rarely?", options: ["Organisations refuse them","The cost of reading answers falls on the funder","They are impolite","They are unreliable"], answer: 1, explanation: "'reflects the cost of reading answers to them, which is borne by the funder'." }
    ]
  },
  {
    id: "cpe-rmc25-06",
    title: "Watching Somebody Else Do It",
    text: "The availability of recorded demonstrations has made it possible to observe almost any manual skill being performed by somebody competent, and the effect on the acquisition of such skills is smaller than the availability would suggest, for reasons that are worth setting out.\nWatching supplies the shape of an operation and not the information that governs it. A person joining two pieces of material observes the sequence, the tool and the approximate speed, and does not observe the resistance under the hand, the point at which the material begins to yield, or the difference between a sound that indicates progress and one that indicates damage. These are the variables by which the operation is actually controlled, they are unavailable through a screen, and their absence is not apparent to the watcher, who has seen everything there was to see.\nThe resulting confidence is the characteristic failure. A person who has watched an operation performed several times can describe it accurately and believes themselves prepared, and the belief survives until the first attempt, at which point they discover that the description was of a different thing. This is not an argument against watching, which conveys a great deal that would otherwise require somebody's presence; it is an argument against the assumption that watching is a substitute for the feedback that produces control.\nWhat recorded demonstrations do supply, and supply better than any instructor, is the answer to a narrow question at the moment it arises. A person part-way through a task who needs to see one specific operation performed once is served extremely well, and this is a real change: the alternative was to abandon the task or to proceed wrongly.\nThe arrangement that appears to work is therefore hybrid and is not what either enthusiasts or traditionalists propose. Recorded material for the sequence and the specific question; a person present, at intervals, to correct what cannot be self-diagnosed; and the acceptance that the second is not eliminable, because the errors that matter are the ones the learner cannot perceive, and a learner who could perceive them would not need correcting.",
    questions: [
      { q: "What does watching supply?", options: ["Muscle memory","Complete competence","The shape of an operation","The governing information"], answer: 2, explanation: "'Watching supplies the shape of an operation and not the information that governs it.'" },
      { q: "Which variables are unavailable through a screen?", options: ["Speed","Materials used","Sequence and tool","Resistance, yield point and sound"], answer: 3, explanation: "'the resistance under the hand, the point at which the material begins to yield'." },
      { q: "Why is their absence unnoticed?", options: ["The watcher has seen everything there was to see", "The video is edited", "Instructions are poor", "Attention lapses"], answer: 0, explanation: "'who has seen everything there was to see'." },
      { q: "What is the characteristic failure?", options: ["Wrong tools","Resulting confidence","Lack of interest","Poor memory"], answer: 1, explanation: "'The resulting confidence is the characteristic failure.'" },
      { q: "What do recordings supply better than an instructor?", options: ["Encouragement","Assessment","An answer to a narrow question when it arises","Correction of errors"], answer: 2, explanation: "'the answer to a narrow question at the moment it arises'." },
      { q: "Why is a person present not eliminable?", options: ["Regulations require supervision","Videos are incomplete","Learners lack motivation","The errors that matter cannot be perceived by the learner"], answer: 3, explanation: "'the errors that matter are the ones the learner cannot perceive'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
