/* CPE Prep bank: Reading multiple choice (C2) — wave 20 */
(function () {
var BANK = [
  {
    id: "cpe-rmc20-01",
    title: "The Person Who Does Not Exist",
    text: "An average is a statement about a set and is habitually received as a statement about a member of it, and the substitution is responsible for a class of error that ranges from the merely amusing to the genuinely expensive.\nThe design failure is the standard illustration. A workstation built to the dimensions of the average operator fits nobody, because the average of a set of measurements is not itself a member of the set: a person of average height is unlikely to have average arm length, and the proportion of any population falling near the mean on several dimensions simultaneously approaches zero as the number of dimensions rises. The response that has been adopted in the fields that learned this lesson is adjustability, which is a design for a range rather than for a point.\nA second failure concerns distributions that are not symmetrical. Where a few very large values are present, the mean describes no part of the population: it exceeds what most members have, is below what a few have, and is reported as though it were typical. The median answers a different and usually more relevant question, and the choice between them is presented as technical while functioning as editorial.\nThe third and most treacherous case arises when a set is composed of groups that behave differently. An average taken across such a set can move in the opposite direction to the average within every group of which it is composed, which sounds impossible and is arithmetically routine, and the resulting figure supports a conclusion that is false of every subgroup examined separately.\nWhat this recommends is not distrust of averages, which are indispensable, but a habit of asking what has been averaged over. A single number describing a heterogeneous population has concealed the heterogeneity, and the concealment is the point of the operation; the question is whether what was concealed was noise, which is what the operation is for, or the structure of the thing being described, which is what it destroys. Nothing in the number itself indicates which, and the person reporting it has frequently not asked.",
    questions: [
      { q: "What is an average habitually received as?", options: ["A statement about a member of it","A prediction","An estimate","A statement about a set"], answer: 0, explanation: "'received as a statement about a member of it'." },
      { q: "Why does a workstation built to average dimensions fit nobody?", options: ["Measurements are inaccurate", "The average is not itself a member of the set", "Adjustment is impossible", "Populations vary regionally"], answer: 1, explanation: "'the average of a set of measurements is not itself a member of the set'." },
      { q: "What did fields that learned this adopt?", options: ["Larger dimensions","Individual fitting","Adjustability","Standardisation"], answer: 2, explanation: "'The response that has been adopted... is adjustability'." },
      { q: "What happens with asymmetrical distributions?", options: ["The median fails","Both measures agree","Reporting becomes impossible","The mean describes no part of the population"], answer: 3, explanation: "'the mean describes no part of the population'." },
      { q: "How does the writer describe choosing between mean and median?", options: ["Presented as technical while functioning as editorial","Legally determined","Unimportant","Purely technical"], answer: 0, explanation: "'presented as technical while functioning as editorial'." },
      { q: "What question does the writer recommend?", options: ["Who produced the number", "What has been averaged over", "How large the sample was", "When it was measured"], answer: 1, explanation: "'a habit of asking what has been averaged over'." }
    ]
  },
  {
    id: "cpe-rmc20-02",
    title: "What the Uniform Is Doing",
    text: "A uniform is described as a means of identification and performs several other functions that are less often stated and are the reason the practice survives in settings where identification could be achieved by a badge.\nThe first is the transfer of authority from the person to the role. A uniformed individual issuing an instruction is obeyed by people who have made no assessment of them, and the obedience is owed to what they represent rather than to anything about them; this is efficient in circumstances where instructions must be followed immediately, and is the reason for the practice in emergency services. It is also the source of the well-documented finding that a uniform secures compliance with instructions that have no legitimate basis, from people who would have refused the same request from the same person in ordinary clothing.\nThe second function operates on the wearer. Putting on a uniform is a boundary, and the act of crossing it marks a transition into a role with defined obligations; those who work in such settings describe the effect consistently, and the removal at the end of a shift is reported as being as significant as the putting on. What this suggests is that a uniform is partly a device for making a role something one enters and leaves rather than something one is, which is protective in work that would otherwise be difficult to put down.\nThe third is the suppression of information the setting does not want visible. Uniform dress removes the signals of income, taste and background that ordinary clothing carries continuously, and its adoption in schools is usually defended on exactly this ground. The evidence that it achieves the intended effect is weaker than its advocates suppose, since the signals reappear in whatever variation remains available, but the intention is coherent and the mechanism is real where the uniform is genuinely uniform.\nWhat is worth noticing is that these functions can conflict. A uniform that confers authority on the wearer also removes their individuality from those they deal with, and the same garment that protects a worker by defining a role prevents the person on the other side of the counter from addressing anybody in particular. Institutions choose the uniform for the first set of reasons and encounter the second set as complaints they have difficulty attributing.",
    questions: [
      { q: "What is the first unstated function?", options: ["Protection","Identification","Transfer of authority from person to role","Cost saving"], answer: 2, explanation: "'the transfer of authority from the person to the role'." },
      { q: "What does the documented finding show?", options: ["Uniforms are ignored","Uniforms reduce errors","Uniforms improve safety","Uniforms secure compliance with illegitimate instructions"], answer: 3, explanation: "'a uniform secures compliance with instructions that have no legitimate basis'." },
      { q: "How does a uniform affect the wearer?", options: ["It marks a transition into a role", "It reduces fatigue", "It improves posture", "It has no effect"], answer: 0, explanation: "'the act of crossing it marks a transition into a role'." },
      { q: "Why is this protective?", options: ["It prevents injury", "It makes a role something one enters and leaves", "It hides identity", "It ensures fair treatment"], answer: 1, explanation: "'a device for making a role something one enters and leaves rather than something one is'." },
      { q: "What does the writer say about the school evidence?", options: ["It is contested by teachers","It is conclusive","It is weaker than advocates suppose","It is unavailable"], answer: 2, explanation: "'weaker than its advocates suppose'." },
      { q: "How do the functions conflict?", options: ["Costs exceed benefits","Comfort is reduced","Identification fails","Authority removes individuality"], answer: 3, explanation: "'also removes their individuality from those they deal with'." }
    ]
  },
  {
    id: "cpe-rmc20-03",
    title: "What an Auction Reveals",
    text: "An auction is a device for discovering a price where no price exists, and its design determines the answer it produces, which is an uncomfortable property for a mechanism widely regarded as neutral.\nThe familiar ascending auction, in which bidding continues until one participant remains, produces a price a little above the second-highest valuation rather than the highest. The winner therefore pays less than they were willing to pay, and the amount by which they underpay is determined by their rivals rather than by themselves. This is a well-understood feature and not a defect, but it establishes that the outcome depends on the shape of the competition and not only on what the item is worth to the person who obtains it.\nThe sealed-bid arrangement produces a different result and different behaviour. A bidder unable to observe the others must submit a figure below their true valuation, since bidding it exactly guarantees no gain, and the size of the reduction depends on their guess about the competition. The price obtained is accordingly a function of how well the participants estimated each other, which is information about the bidders rather than about the object.\nThe phenomenon that most damages the assumption of neutrality is the tendency of winners in common-value auctions — those in which the item is worth roughly the same to everybody but its value is uncertain — to overpay systematically. The winner is by definition the participant whose estimate was highest, and the highest estimate in a set of estimates around a true value is above it. Winning is therefore evidence of having been too optimistic, and experienced bidders in such markets reduce their bids to account for a fact that the bidding itself supplies.\nThe practical lesson extends beyond auction rooms to every situation in which something is allocated by competitive offer, including tenders and recruitment. The party that wins a competitive process has, in a specific and calculable sense, made the most optimistic assessment of what they were acquiring, and a purchaser who has not asked why their offer was the highest has not finished evaluating the transaction.",
    questions: [
      { q: "What price does an ascending auction produce?", options: ["A little above the second-highest valuation","An average of bids","The reserve price","The highest valuation"], answer: 0, explanation: "'a price a little above the second-highest valuation'." },
      { q: "What determines the winner's saving?", options: ["Their own valuation", "Their rivals", "The auctioneer", "The reserve"], answer: 1, explanation: "'determined by their rivals rather than by themselves'." },
      { q: "Why must a sealed bidder bid below their valuation?", options: ["To save money","Rules require it","Bidding it exactly guarantees no gain","To avoid detection"], answer: 2, explanation: "'bidding it exactly guarantees no gain'." },
      { q: "What does the sealed-bid price reflect?", options: ["The seller's reserve","Market conditions","The object's worth","How well participants estimated each other"], answer: 3, explanation: "'a function of how well the participants estimated each other'." },
      { q: "Why do common-value winners overpay?", options: ["The highest estimate is above the true value","They lack information","Auctions are rigged","They bid emotionally"], answer: 0, explanation: "'the highest estimate in a set of estimates around a true value is above it'." },
      { q: "What should a winning purchaser ask?", options: ["How to reduce costs","Why their offer was the highest","Who the other bidders were","Whether to resell"], answer: 1, explanation: "'has not asked why their offer was the highest'." }
    ]
  },
  {
    id: "cpe-rmc20-04",
    title: "The Handover",
    text: "The transfer of responsibility between shifts is the point at which more information is lost than at any other moment in continuous operations, and it has been studied intensively in the settings where the loss is most expensive.\nThe difficulty is not that the outgoing party fails to describe the situation. It is that a description is a summary of a mental model built over hours, and the model contains a great deal that the person holding it does not know they are using: the patient who seemed unusually anxious, the reading that was normal but had moved, the fact that a colleague was uncertain about something and did not say so. None of this appears in a structured handover because none of it has crossed the threshold at which it would be reported.\nThe formats that improve matters do so by forcing articulation rather than by adding content. A requirement to state what one is worried about, as distinct from what has happened, produces information that no factual summary elicits; a requirement to state what one would do next if one were staying converts a report into a judgement, and the judgement is what the incoming party actually needs. Both take under a minute and neither is natural.\nThe second common failure is the interruption. A handover conducted while both parties are attending to other demands loses items in a way that is invisible to both, since neither can subsequently identify what was not said. The protected handover — a defined period, in a defined place, without other traffic — is a straightforward measure whose adoption is resisted on the ground that the time is not available, in settings that then spend considerably more time reconstructing what was missed.\nWhat is least often addressed is the asymmetry of confidence. The incoming party receives a coherent account and treats it as complete, since it arrives without the hesitations that accompanied its construction, and they proceed on a model they did not build and whose weak points they cannot see. The countermeasure is a habit rather than a procedure: an explicit statement of what remains uncertain, offered by the outgoing party and asked for by the incoming one, which two people who trust each other will find easier than two who do not.",
    questions: [
      { q: "What is the central difficulty in handover?", options: ["Language differences","Poor description","The mental model contains unreported elements","Lack of time"], answer: 2, explanation: "'the model contains a great deal that the person holding it does not know they are using'." },
      { q: "How do better formats help?", options: ["By shortening the handover","By using checklists","By adding content","By forcing articulation"], answer: 3, explanation: "'by forcing articulation rather than by adding content'." },
      { q: "What does stating what one would do next produce?", options: ["A judgement", "A record", "A summary", "A plan"], answer: 0, explanation: "'converts a report into a judgement'." },
      { q: "Why are interrupted handovers dangerous?", options: ["They take longer", "Neither party can identify what was not said", "They are informal", "They are unrecorded"], answer: 1, explanation: "'neither can subsequently identify what was not said'." },
      { q: "On what ground is the protected handover resisted?", options: ["That it is expensive","That staff dislike it","That the time is not available","That it is unnecessary"], answer: 2, explanation: "'resisted on the ground that the time is not available'." },
      { q: "Why does the incoming party overestimate completeness?", options: ["They do not listen","Records are absent","They are inexperienced","The account arrives without its hesitations"], answer: 3, explanation: "'it arrives without the hesitations that accompanied its construction'." }
    ]
  },
  {
    id: "cpe-rmc20-05",
    title: "A Stage of Life That Had to Be Invented",
    text: "The categories into which a life is divided appear natural to those living inside them and are, on inspection, arrangements of relatively recent construction, produced by specific conditions and capable of dissolving when the conditions change.\nThe interval between childhood and adult responsibility is the clearest case. For most of recorded history no such interval existed for most people: a person too young for full work was a child, and a person capable of it was treated substantially as an adult, and the transition was marked rather than extended. What produced the modern arrangement was a combination of compulsory schooling to a later age, the removal of the young from the labour market, and a period of prosperity in which those excluded from work nevertheless possessed money to spend.\nThe last of these is the least discussed and did most of the work. A group with disposable income and no domestic obligations was identified as a market, and the identification produced the apparatus by which the category became visible to itself: music, clothing and publications addressed specifically to it. A stage of life that had been a gap became a stage with contents, and the contents were substantially commercial in origin, which is not an argument that the stage is unreal.\nThe same analysis applies at the other end. The retirement that is treated as a natural conclusion to a working life is an administrative creation of the last century and a half, dependent on pension arrangements that assumed a particular relation between working years and remaining ones. Where that relation has altered, the category has begun to lose definition, and the confusion now attending it is not a failure of individual planning but the dissolution of a construction whose conditions have gone.\nWhat this suggests is a certain caution about arguments that appeal to the natural shape of a life, since the shape being appealed to is generally the one that obtained during the arguer's own formation. The categories are real in the only sense that matters — they organise institutions, expectations and self-understanding — and they are not thereby permanent, and a person who assumes otherwise is planning for a world that is already changing under them.",
    questions: [
      { q: "How does the writer describe life-stage categories?", options: ["Arrangements of relatively recent construction","Universal","Biologically determined","Natural"], answer: 0, explanation: "'arrangements of relatively recent construction'." },
      { q: "How was the transition historically handled?", options: ["Legally defined","Marked rather than extended","Gradual","Formally schooled"], answer: 1, explanation: "'the transition was marked rather than extended'." },
      { q: "Which factor did most of the work?", options: ["Family structure","Compulsory schooling","Disposable income among the young","Labour law"], answer: 2, explanation: "'The last of these is the least discussed and did most of the work.'" },
      { q: "What did commercial identification produce?", options: ["Higher wages","Longer schooling","Legal recognition","The apparatus by which the category became visible to itself"], answer: 3, explanation: "'the apparatus by which the category became visible to itself'." },
      { q: "What is happening to retirement as a category?", options: ["It is losing definition","It is being legislated","It is unchanged","It is expanding"], answer: 0, explanation: "'the category has begun to lose definition'." },
      { q: "What caution does the writer recommend?", options: ["About schooling policy","About appeals to the natural shape of a life","About commercial influence","About early retirement"], answer: 1, explanation: "'a certain caution about arguments that appeal to the natural shape of a life'." }
    ]
  },
  {
    id: "cpe-rmc20-06",
    title: "The City at Walking Pace",
    text: "A city encountered on foot and the same city encountered at speed are different objects, and the difference is not a matter of degree. What alters is the unit of attention: a driver perceives a route composed of junctions and a walker perceives a sequence of surfaces, thresholds and small events, and almost nothing that constitutes the second is visible from within the first.\nThe design consequence is that streets planned by people who arrive by car are planned for a perception that excludes most of what makes a street work. The distance at which a shopfront becomes interesting, the width at which a pavement stops being a corridor and starts being a place, the effect of a doorway recessed by half a metre: these operate at a scale that is invisible above a certain speed and are precisely the variables that determine whether anybody chooses to walk. A street can satisfy every standard in the manual and be unusable in the only sense that matters.\nThe economic argument has been made repeatedly and is now reasonably well evidenced. Streets that are pleasant to walk along sustain more small businesses per unit of frontage than streets that are not, because a walker passes a shop at a speed permitting a decision and a driver does not; and the retail that survives on a fast road is the retail that people drive to deliberately, which is a smaller and less diverse set. The effect is measurable and is regularly outweighed in decisions by the ease of measuring traffic flow.\nThere is a further consideration that resists quantification and may be the more important. Walking is the only mode in which encounter is possible: a person on foot can stop, can be spoken to, can change their mind about where they are going. A city in which most journeys occur inside vehicles is one in which most of its inhabitants pass one another without the possibility of contact, and whatever a city is for, it is not obviously that.\nThe interventions that work are known and are modest in cost relative to their effect. Narrower carriageways, wider pavements, frequent crossings placed where people actually want to cross rather than where they are convenient to install: none of these requires new technology, and their absence in any particular street is a record of whose convenience was being consulted.",
    questions: [
      { q: "What alters between walking and driving?", options: ["The time taken","The route chosen","The unit of attention","The distance travelled"], answer: 2, explanation: "'What alters is the unit of attention'." },
      { q: "What is the problem with streets planned by drivers?", options: ["They cost more","They are poorly surfaced","They are too narrow","They are planned for a perception excluding what makes streets work"], answer: 3, explanation: "'planned for a perception that excludes most of what makes a street work'." },
      { q: "Why do walkable streets sustain more small businesses?", options: ["A walker passes at a speed permitting a decision","There is more parking","They are better lit","Rents are lower"], answer: 0, explanation: "'a walker passes a shop at a speed permitting a decision'." },
      { q: "Why is the effect outweighed in decisions?", options: ["It is disputed", "Traffic flow is easier to measure", "Businesses object", "Costs are high"], answer: 1, explanation: "'regularly outweighed in decisions by the ease of measuring traffic flow'." },
      { q: "What is unique to walking?", options: ["Health benefit","Speed","The possibility of encounter","Low cost"], answer: 2, explanation: "'Walking is the only mode in which encounter is possible'." },
      { q: "What does the absence of such interventions record?", options: ["Technical difficulty","Legal constraints","Budget limits","Whose convenience was consulted"], answer: 3, explanation: "'a record of whose convenience was being consulted'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
