/* CPE Prep bank: Reading multiple choice (C2) — wave 14 */
(function () {
var BANK = [
  {
    id: "cpe-rmc14-01",
    title: "Asking Somebody Else",
    text: "The second opinion is understood as a safeguard against error and is, in the form it usually takes, considerably less than that. Its value depends on a condition that is rarely satisfied and almost never checked, which is that the second judgement be independent of the first.\nIndependence is destroyed by the ordinary courtesies of consultation. A colleague approached with a case is generally told what the first assessment was, on the reasonable ground that withholding it would be strange, and having been told, they are no longer capable of producing an independent judgement; they are capable of producing an assessment of the first one, which is a different and much weaker instrument. The agreement that results is then reported as confirmation, and it confirms only that the second person could not see an obvious error.\nThe arithmetic is worth stating because it is counter-intuitive. Two judgements that are genuinely independent and individually unreliable are jointly far more reliable than either, and the improvement is substantial. Two judgements of which the second was formed in the knowledge of the first are barely more reliable than one, and the impression of corroboration they create makes the resulting decision harder to overturn than a single judgement would have been. The consultation has therefore made matters worse.\nThe remedies are procedurally simple and socially awkward, which is the usual configuration. The second assessor should receive the material and not the conclusion; both assessments should be recorded before either party sees the other; and disagreement should be treated as the informative outcome it is rather than as a problem requiring reconciliation. The last point is the one that fails in practice, since a recorded disagreement is uncomfortable and the natural response is a discussion that produces a shared position, which discards the information the exercise was conducted to obtain.\nWhere genuine independence cannot be arranged, the honest course is to describe what has been obtained as a review rather than as a second opinion. A review has value; it detects errors that are visible once pointed at. It does not do what independence does, and describing it as though it did produces a confidence that nothing in the procedure justifies.",
    questions: [
      { q: "What condition does the value of a second opinion depend on?", options: ["Independence from the first judgement","Speed of response","Written records","Seniority of the assessor"], answer: 0, explanation: "'that the second judgement be independent of the first'." },
      { q: "What destroys independence?", options: ["Lack of time", "The ordinary courtesies of consultation", "Poor documentation", "Conflicting interests"], answer: 1, explanation: "'Independence is destroyed by the ordinary courtesies of consultation.'" },
      { q: "What does the resulting agreement actually confirm?", options: ["That the case is simple","That the diagnosis is correct","That no obvious error was visible","That both are experienced"], answer: 2, explanation: "'it confirms only that the second person could not see an obvious error'." },
      { q: "Why is a dependent second judgement worse than none?", options: ["It costs money","It delays treatment","It wastes time","It creates corroboration that resists overturning"], answer: 3, explanation: "'makes the resulting decision harder to overturn than a single judgement would have been'." },
      { q: "How should disagreement be treated?", options: ["As an informative outcome", "As a problem to reconcile", "As a procedural failure", "As grounds for a third opinion"], answer: 0, explanation: "'treated as the informative outcome it is'." },
      { q: "What should a non-independent assessment be called?", options: ["A second opinion", "A review", "An audit", "A confirmation"], answer: 1, explanation: "'describe what has been obtained as a review rather than as a second opinion'." }
    ]
  },
  {
    id: "cpe-rmc14-02",
    title: "The Committees Nobody Watches",
    text: "A standards body is among the least observed and most consequential institutions in any technical field. Its decisions determine what will interoperate with what, and therefore which products can exist, and they are taken in meetings that no journalist attends and whose minutes are read by nobody outside the industry concerned.\nThe work itself is unglamorous to a degree that is difficult to convey. A specification is argued over clause by clause for years, and the arguments concern edge cases, tolerances and the precise meaning of words such as should and shall, which carry entirely different obligations and are the subject of more dispute than any substantive question. This is not pedantry; the difference between a recommendation and a requirement determines what a purchaser can insist upon.\nThe political dimension is present and is not hidden. Participation is expensive, requiring staff who can attend meetings for years, and expense selects for large organisations with an interest in the outcome. A standard that can be met by an existing product favours its manufacturer; one that requires a capability held under patent favours whoever holds it. The resulting documents are compromises between commercial interests, and their technical merits are real but are not the only forces acting.\nWhat prevents capture, where it is prevented, is the requirement for adoption. A standard that serves one participant too obviously is not implemented by the others, and an unimplemented standard is worthless to everybody including its author, which imposes a discipline that no rule could impose. The system works, to the extent it does, because the parties need one another.\nThe consequence for the public is a category of decision that is genuinely important, genuinely open in the sense that anybody may participate, and effectively closed because participation costs more than any unaffiliated party can bear. Proposals to fund independent participation appear periodically and are not adopted, and the reason offered is cost, which in this instance is a small fraction of what the resulting decisions are worth.",
    questions: [
      { q: "What do standards bodies determine?", options: ["Research funding","Prices","What will interoperate with what","Employment levels"], answer: 2, explanation: "'Its decisions determine what will interoperate with what'." },
      { q: "What causes the most dispute?", options: ["Meeting schedules","Membership fees","Substantive questions","The meaning of words like should and shall"], answer: 3, explanation: "'the precise meaning of words such as should and shall'." },
      { q: "Why does that distinction matter?", options: ["It determines what a purchaser can insist upon","It affects translation","It sets deadlines","It affects document length"], answer: 0, explanation: "'the difference between a recommendation and a requirement determines what a purchaser can insist upon'." },
      { q: "What does the expense of participation select for?", options: ["Technical expertise", "Large organisations with an interest", "Academic institutions", "Government bodies"], answer: 1, explanation: "'expense selects for large organisations with an interest in the outcome'." },
      { q: "What prevents capture?", options: ["Rotating chairs","Legal oversight","The requirement for adoption","Public scrutiny"], answer: 2, explanation: "'What prevents capture, where it is prevented, is the requirement for adoption.'" },
      { q: "Why is the process effectively closed?", options: ["Meetings are secret","Documents are confidential","Membership is restricted","Participation costs more than unaffiliated parties can bear"], answer: 3, explanation: "'participation costs more than any unaffiliated party can bear'." }
    ]
  },
  {
    id: "cpe-rmc14-03",
    title: "The Hand That Remembers",
    text: "The persistence of handwriting in an age of keyboards is usually explained by sentiment, and there is a body of evidence suggesting that the explanation is incomplete. Where the two methods have been compared for the purpose of retaining material, the slower one performs better, and the mechanism identified is instructive.\nA competent typist can record speech at close to the rate it is produced, and the capacity permits transcription without comprehension: the words pass from ear to hand with no requirement that they be understood. Writing by hand is too slow for this, and the constraint forces a selection. The writer must decide what matters, compress it, and render it in their own formulation, and those operations constitute the processing that produces retention. The advantage does not come from the pen; it comes from the inability to keep up.\nThis is supported by the observation that the effect disappears where typists are instructed to summarise rather than transcribe. What is being measured is not a property of the instrument but of what the instrument permits, which is why the practical recommendation concerns the practice rather than the tool.\nA second and less examined difference concerns spatial memory. A handwritten page has a topography — this was in the upper left, that was underlined heavily, this was written when the pen was running out — and recollection appears to make use of it. A scrolling document is uniform, has no fixed positions, and offers nothing for this faculty to attach to. Whether the effect is substantial is not settled; that it exists is reasonably clear.\nThe conclusion is not that handwriting should be restored generally, which would be an expensive way of obtaining a modest benefit for material that is mostly not worth retaining. It is that the choice of instrument silently determines the cognitive operation performed, and that anybody recording something they intend to remember should choose the method that prevents them from doing so mechanically, which for most people and most purposes remains the slower one.",
    questions: [
      { q: "What does the evidence suggest about handwriting?", options: ["The slower method aids retention","It is preferred by students","It reduces errors","It is faster"], answer: 0, explanation: "'the slower one performs better'." },
      { q: "What does typing speed permit?", options: ["Better organisation", "Transcription without comprehension", "Longer notes", "Easier revision"], answer: 1, explanation: "'the capacity permits transcription without comprehension'." },
      { q: "Where does the advantage come from?", options: ["Reduced distraction","The pen itself","The inability to keep up","Better posture"], answer: 2, explanation: "'it comes from the inability to keep up'." },
      { q: "What happens when typists are told to summarise?", options: ["The effect doubles","Retention worsens","Speed falls","The effect disappears"], answer: 3, explanation: "'the effect disappears where typists are instructed to summarise'." },
      { q: "What does a handwritten page offer that a document does not?", options: ["A topography for spatial memory","Permanence","Searchability","Legibility"], answer: 0, explanation: "'A handwritten page has a topography'." },
      { q: "What is the writer's conclusion?", options: ["Handwriting should be restored generally", "The instrument determines the cognitive operation", "Typing should be discouraged", "Notes are rarely useful"], answer: 1, explanation: "'the choice of instrument silently determines the cognitive operation performed'." }
    ]
  },
  {
    id: "cpe-rmc14-04",
    title: "In Defence of Spare Capacity",
    text: "A system operating at full utilisation is generally described as efficient, and the description is accurate about the ratio it measures and silent about everything the ratio omits. What full utilisation guarantees is that any disturbance whatever will propagate, since there is no capacity anywhere with which to absorb it.\nThe mathematics of queueing makes the point without any need for judgement. As utilisation approaches its ceiling, waiting times rise not proportionately but towards infinity, and the region in which a system is most efficient by the usual measure is the region in which it is least tolerant of variation. A road at capacity carries the maximum number of vehicles and stops entirely when one of them brakes; the same road at eighty per cent carries slightly fewer and continues to function.\nThe organisational version is familiar and is rarely named. Staff scheduled at full occupancy cannot cover absence, cannot train anybody, and cannot investigate the anomaly that would have prevented next month's failure, since all of those activities require time that the schedule has allocated. The capabilities lost are precisely the ones whose absence is invisible until the moment it is not.\nWhat makes the error persistent is that slack is measurable and its benefits are not. An accounting system records idle capacity as a cost, accurately, and records the failures that did not occur as nothing, also accurately, and a manager comparing the two figures reaches the conclusion the figures support. The elimination of slack is therefore not a mistake in reasoning; it is a correct inference from an incomplete measurement, which is a much harder thing to correct.\nThe practical response is to protect capacity by naming it, since anything unnamed will be reallocated. Time designated for maintenance, for training or for investigation survives budget scrutiny in a way that unallocated availability does not, and the designation is a fiction only in the sense that all such categories are. What matters is that the capacity exists when the disturbance arrives, and disturbances arrive.",
    questions: [
      { q: "What does full utilisation guarantee?", options: ["Predictable service","Maximum output","That any disturbance will propagate","Lower costs"], answer: 2, explanation: "'any disturbance whatever will propagate'." },
      { q: "What happens to waiting times near the ceiling?", options: ["They stabilise","They fall","They rise proportionately","They rise towards infinity"], answer: 3, explanation: "'waiting times rise not proportionately but towards infinity'." },
      { q: "What does the road example illustrate?", options: ["That maximum throughput coincides with fragility","That drivers cause congestion","That eighty per cent is optimal legally","That capacity should be expanded"], answer: 0, explanation: "'stops entirely when one of them brakes'." },
      { q: "Which capabilities are lost at full occupancy?", options: ["Customer contact","Those whose absence is invisible until it matters","Only training","Routine reporting"], answer: 1, explanation: "'the ones whose absence is invisible until the moment it is not'." },
      { q: "Why is the error persistent?", options: ["Staff prefer full schedules","Managers are careless","It is a correct inference from incomplete measurement","Accounting rules forbid slack"], answer: 2, explanation: "'it is a correct inference from an incomplete measurement'." },
      { q: "How does the writer suggest protecting capacity?", options: ["By hiding it","By automating it","By outsourcing it","By naming it"], answer: 3, explanation: "'to protect capacity by naming it'." }
    ]
  },
  {
    id: "cpe-rmc14-05",
    title: "How Many Species Are There?",
    text: "The number of recognised species in a well-studied group can rise substantially without a single new organism being discovered, and the rise reflects a change in the criteria applied rather than in the world. This is not a scandal; it is a consequence of the fact that the species concept has never been settled and probably cannot be.\nThe difficulty is genuine rather than semantic. The criterion most often taught, which concerns the capacity to interbreed, is inapplicable to organisms that do not reproduce sexually, is untestable for those known only from fossils, and produces indeterminate results wherever populations interbreed occasionally and successfully. Every alternative criterion — morphological, ecological, genetic — draws its boundaries in a different place, and no procedure exists for adjudicating between them, because the disagreement is not about facts.\nThe practical consequences are considerable, since species are the units in which conservation is conducted. A population recognised as a distinct species attracts protection that the same population, classified as a subspecies, does not, and the classification may turn on which criterion a committee found persuasive. Conservationists are accordingly aware that taxonomic decisions have effects, and the awareness introduces a pressure that taxonomy is not equipped to resist.\nThe genetic methods that were expected to settle matters have instead multiplied the difficulty. Sequencing reveals distinctions invisible to earlier workers, and populations long treated as one are found to comprise several lineages that have not exchanged genes for a very long time. Whether these constitute species is precisely the question the data cannot answer, since the data show degrees of difference and the question demands a boundary.\nWhat follows is not that the counts are meaningless but that a count is a statement about criteria as much as about organisms, and that a comparison of two counts made under different criteria is not a measurement of change. The honest presentation states the criterion, and the honest reader looks for it, and neither is common in the reporting of these figures.",
    questions: [
      { q: "What causes species counts to rise without new discoveries?", options: ["A change in the criteria applied","Population growth","Improved funding","Better equipment"], answer: 0, explanation: "'a change in the criteria applied rather than in the world'." },
      { q: "What is wrong with the interbreeding criterion?", options: ["It is too strict", "It is inapplicable to several categories of organism", "It requires genetic data", "It is outdated legally"], answer: 1, explanation: "'is inapplicable to organisms that do not reproduce sexually'." },
      { q: "Why can criteria not be adjudicated between?", options: ["Committees are divided","Funding is limited","The disagreement is not about facts","Data are unavailable"], answer: 2, explanation: "'the disagreement is not about facts'." },
      { q: "Why do classifications matter practically?", options: ["They affect naming rights","They set trade rules","They determine research funding","Species attract protection that subspecies do not"], answer: 3, explanation: "'attracts protection that the same population, classified as a subspecies, does not'." },
      { q: "What did genetic methods do?", options: ["Multiplied the difficulty","Reduced species counts","Replaced morphology","Settled the question"], answer: 0, explanation: "'have instead multiplied the difficulty'." },
      { q: "Why can the data not answer the question?", options: ["They are incomplete", "They show degrees while the question demands a boundary", "They are contested", "They are expensive to obtain"], answer: 1, explanation: "'the data show degrees of difference and the question demands a boundary'." }
    ]
  },
  {
    id: "cpe-rmc14-06",
    title: "The Uses of a Fixed Date",
    text: "A deadline is experienced as an imposition and functions as a resource, and the discrepancy between the experience and the function accounts for most of the confusion surrounding the subject.\nWhat a fixed date supplies is a means of ending deliberation. Work of any complexity admits of indefinite improvement, and the judgement that something is finished cannot be derived from the work itself, since a further revision is always available and will always be an improvement of some kind. Without an external stop, the decision to conclude must be taken on grounds that feel arbitrary, and the discomfort of taking it is why so much work is not concluded but abandoned.\nThe familiar objection, that a deadline produces work of lower quality than would otherwise have been achieved, rests on a comparison with an outcome that generally does not occur. The alternative to the deadline is not the same work completed more carefully; it is the work completed at an unknown later date or not at all, and the comparison that matters is with that.\nDeadlines nevertheless fail in a characteristic way, which is worth stating precisely. A date set by somebody who will not do the work, without reference to what the work requires, communicates nothing except that a date was wanted, and the people subject to it learn quickly that the number is unrelated to the task. Once that is understood, deadlines cease to function as stops at all and become an idiom, and their subsequent violation is unremarkable to everybody.\nThe useful distinction is therefore between a deadline that is a genuine constraint and one that is an expression of preference, and organisations that maintain both without distinguishing them lose the benefit of the first. A date beyond which something is worthless should be stated as such and defended; a date that would be convenient should be described as convenient. The second kind is not illegitimate, and the damage arises entirely from presenting it as the first.",
    questions: [
      { q: "What does a fixed date supply?", options: ["A quality standard","Motivation","A means of ending deliberation","Accountability"], answer: 2, explanation: "'What a fixed date supplies is a means of ending deliberation.'" },
      { q: "Why can completion not be judged from the work?", options: ["Reviewers disagree","Requirements change","Standards vary","A further improvement is always available"], answer: 3, explanation: "'a further revision is always available'." },
      { q: "What does the writer say happens without an external stop?", options: ["Work is abandoned rather than concluded","Deadlines are invented","Costs rise","Work improves"], answer: 0, explanation: "'so much work is not concluded but abandoned'." },
      { q: "What is wrong with the quality objection?", options: ["It applies only to creative work","It compares with an outcome that does not occur","It is empirically untested","It ignores costs"], answer: 1, explanation: "'rests on a comparison with an outcome that generally does not occur'." },
      { q: "How do deadlines characteristically fail?", options: ["They are secret","They are too short","They are set without reference to the work","They are unenforced"], answer: 2, explanation: "'without reference to what the work requires'." },
      { q: "Where does the damage arise?", options: ["From missed dates","From long projects","From preference dates existing","From presenting a preference as a constraint"], answer: 3, explanation: "'the damage arises entirely from presenting it as the first'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
