/* CPE Prep bank: Reading multiple choice (C2) — wave 24 */
(function () {
var BANK = [
  {
    id: "cpe-rmc24-01",
    title: "What an Apology Has to Contain",
    text: "The public apology has become a standard instrument and is issued in a form that reliably fails, and the failure is sufficiently consistent to be described as a genre rather than as a series of individual misjudgements.\nWhat is issued usually contains an expression of regret about the effect and no acknowledgement of the act. The formulation that regret is felt if anyone was offended locates the injury in the sensitivity of the recipient, transfers the description of what happened out of the speaker's control, and commits to nothing. Audiences identify this immediately and respond to it as an aggravation, which it is: an apology that denies the act while performing contrition asks its recipient to accept a falsehood as a courtesy.\nThe components that research consistently identifies are unwelcome for reasons that are obvious once stated. An effective apology names the act specifically, which creates a record; accepts responsibility without conditions, which forecloses a defence; states what will be done differently, which can be checked; and offers no explanation of circumstances, since an explanation is heard as an excuse regardless of its accuracy. Each element increases exposure, and the standard apology is constructed by people whose task is to reduce exposure.\nThe institutional obstacle is more specific than reluctance. Legal advice in many jurisdictions has historically treated an apology as an admission, and the drafting reflects that advice, with the result that the document is addressed to a future court rather than to the injured party. Several jurisdictions have legislated to prevent apologies being used as evidence, and where this has been done the frequency of genuine apologies has risen and the volume of litigation has fallen, which is the outcome the original caution was intended to secure.\nThe individual case follows the same structure and is not made easier by understanding it. An apology that satisfies the conditions is uncomfortable to deliver, offers nothing in return, and may not be accepted, which is the recipient's right and is frequently forgotten by those who apologise in the expectation of a settlement. What distinguishes the apology that works is that it is offered without one.",
    questions: [
      { q: "What does the standard apology express?", options: ["Regret about the effect without acknowledging the act", "Full responsibility", "A plan for change", "An explanation"], answer: 0, explanation: "'an expression of regret about the effect and no acknowledgement of the act'." },
      { q: "Where does the usual formulation locate the injury?", options: ["In the act", "In the sensitivity of the recipient", "In circumstances", "In misunderstanding"], answer: 1, explanation: "'locates the injury in the sensitivity of the recipient'." },
      { q: "Why should an apology offer no explanation?", options: ["It is unnecessary","It takes too long","An explanation is heard as an excuse","It is legally risky"], answer: 2, explanation: "'an explanation is heard as an excuse regardless of its accuracy'." },
      { q: "Why do institutions produce weak apologies?", options: ["They are indifferent","They are advised by committees","They lack skill","Their drafters' task is to reduce exposure"], answer: 3, explanation: "'constructed by people whose task is to reduce exposure'." },
      { q: "What has legislation achieved?", options: ["More genuine apologies and less litigation", "Fewer apologies", "Higher settlements", "No measurable change"], answer: 0, explanation: "'the frequency of genuine apologies has risen and the volume of litigation has fallen'." },
      { q: "What distinguishes an apology that works?", options: ["It is legally approved","It is offered without expectation of a settlement","It is public","It is brief"], answer: 1, explanation: "'it is offered without one'." }
    ]
  },
  {
    id: "cpe-rmc24-02",
    title: "The Material Nobody Has Used Yet",
    text: "The conservatism of structural engineering with respect to new materials is regularly criticised as an obstacle to innovation, and the criticism generally proceeds without an account of what the conservatism is for.\nThe governing consideration is that the properties which matter for a structure are those it exhibits after several decades of loading, weather and neglect, and no laboratory programme produces that information. Accelerated testing produces an estimate, and the estimate rests on an assumption that the mechanisms of deterioration are the same at speed as at leisure, which has been false often enough to have generated a literature of its own. The only reliable source of data about fifty-year behaviour is a structure that has stood for fifty years.\nThe asymmetry of consequences reinforces this. A material that performs as expected produces a building that is unremarkable; one that does not may produce a failure that is fatal, expensive and attributable, and the attribution reaches the individual who specified it. A profession in which the reward for innovation is invisible and the penalty is personal will innovate slowly, and the slowness is a rational response to the incentive structure rather than a cultural defect.\nThere is nevertheless a genuine cost, and it falls in an area that the profession discusses less readily. A material that would perform well is excluded for the same period as one that would not, and the exclusion applies most strongly to materials whose advantages are environmental rather than structural, since these do not solve a problem the engineer is accountable for. The incentives that produce appropriate caution about safety produce inappropriate caution about everything else.\nThe arrangements that have worked in practice are those that separate the two. A programme of monitored demonstration structures, built with public support and instrumented so that their behaviour is recorded, produces long-term data without requiring any individual to accept the risk personally; and a regulatory route in which a novel material may be used with an enhanced factor of safety permits accumulation of experience at a known cost. Both exist, both work and both are funded at a level that suggests the sector has not decided whether it wants the problem solved.",
    questions: [
      { q: "Which properties matter for a structure?", options: ["Manufacturing consistency","Laboratory results","Those after decades of loading and weather","Initial strength"], answer: 2, explanation: "'those it exhibits after several decades of loading, weather and neglect'." },
      { q: "What assumption does accelerated testing rest on?", options: ["That loads are constant","That materials are uniform","That climate is stable","That deterioration mechanisms are the same at speed"], answer: 3, explanation: "'the mechanisms of deterioration are the same at speed as at leisure'." },
      { q: "What is the only reliable source of long-term data?", options: ["A structure that has stood for fifty years","Manufacturer testing","Regulatory records","Simulation"], answer: 0, explanation: "'a structure that has stood for fifty years'." },
      { q: "How does the writer describe the profession's slowness?", options: ["A cultural defect", "A rational response to incentives", "A regulatory artefact", "A training failure"], answer: 1, explanation: "'a rational response to the incentive structure rather than a cultural defect'." },
      { q: "Which materials suffer most from exclusion?", options: ["Imported materials","Traditional materials","Those with environmental advantages","Cheaper materials"], answer: 2, explanation: "'materials whose advantages are environmental rather than structural'." },
      { q: "What do demonstration structures achieve?", options: ["Lower costs","Faster approval","Public support","Long-term data without personal risk"], answer: 3, explanation: "'produces long-term data without requiring any individual to accept the risk personally'." }
    ]
  },
  {
    id: "cpe-rmc24-03",
    title: "The Garden as a Statement",
    text: "A garden is among the most legible documents a period produces about itself, and it is legible precisely because nobody making one believes they are producing a document.\nWhat a garden encodes is a position on the relation between people and the rest of the world. The formal garden, in which planting is subordinated to geometry and growth is corrected continuously towards a plan, asserts that nature is material for arrangement and that the arrangement is the achievement. The landscape garden that displaced it in some countries asserts something else — that the desirable condition is an apparently unmanaged one — while requiring enormous intervention to produce an appearance of having had none, which is a claim about concealment rather than about restraint.\nThe reversal is instructive because both styles were maintained by the same class of owner within a century of each other, and the shift was not driven by any change in what plants do. It followed a change in what a landowner wished to be understood as: no longer a person who imposed order, but a person whose holdings were naturally harmonious, which was a considerably more useful thing to appear to be at the moment the change occurred.\nThe contemporary versions carry equivalent freight and are not usually recognised as doing so. A garden planted for pollinators, one kept as a lawn, one paved for parking and one left deliberately unmanaged are four positions on the same set of questions, and each is read fluently by neighbours who would be unable to state the code they are using. The vocabulary of horticultural argument — tidy, wild, low-maintenance, appropriate — carries the judgements.\nWhat makes the garden a better document than the buildings around it is that it must be continuously renewed. A house records the intentions of the moment it was built; a garden that has not been maintained for two seasons announces the withdrawal of intention, and one maintained for fifty years records every year of the fifty. It is the only structure that cannot be abandoned quietly, which is why the state of a garden is read, universally and accurately, as information about its owner.",
    questions: [
      { q: "Why is a garden legible?", options: ["Nobody making one believes they are producing a document","It is publicly visible","It is well recorded","It is carefully designed"], answer: 0, explanation: "'nobody making one believes they are producing a document'." },
      { q: "What does the formal garden assert?", options: ["That gardens are private","That nature is material for arrangement","That growth should be uncontrolled","That geometry is natural"], answer: 1, explanation: "'nature is material for arrangement'." },
      { q: "What is the landscape garden's claim about?", options: ["Tradition","Restraint","Concealment","Economy"], answer: 2, explanation: "'a claim about concealment rather than about restraint'." },
      { q: "What drove the shift between styles?", options: ["Climate","Cost","Plant availability","A change in what a landowner wished to appear to be"], answer: 3, explanation: "'a change in what a landowner wished to be understood as'." },
      { q: "How do neighbours read contemporary gardens?", options: ["Fluently, without stating the code", "By consulting guides", "Inaccurately", "Not at all"], answer: 0, explanation: "'read fluently by neighbours who would be unable to state the code'." },
      { q: "Why is a garden a better document than a building?", options: ["It is older", "It must be continuously renewed", "It is cheaper", "It is more visible"], answer: 1, explanation: "'it must be continuously renewed'." }
    ]
  },
  {
    id: "cpe-rmc24-04",
    title: "The Numbers Come to the Stadium",
    text: "The statistical analysis of sport has produced results that its opponents disputed and that have been vindicated, and the vindication has been followed by a set of consequences that its advocates did not anticipate and have been slow to discuss.\nThe original insight was narrow and correct. Certain widely used measures of performance were poor predictors of what teams were trying to achieve, better measures existed in data already collected, and clubs applying them could acquire useful players at prices set by a market using the worse measures. The advantage was real and was necessarily temporary: once the better measures were generally adopted, the prices adjusted, and what had been an edge became a cost of entry.\nThe second-order effects are where the interest now lies. A measure that determines selection determines training, and training determines what the sport looks like. Where analysis established that a particular action was more valuable than the alternatives, teams did more of it, and they converged: the variety of approaches that had characterised the game narrowed towards the strategy the numbers endorsed, and the endorsement was correct on its own terms while producing a competition that spectators describe as more uniform.\nThe governing bodies have responded by altering rules to restore variety, which is an odd position: a sport adjusting its constitution to prevent its participants from playing optimally, in order to preserve a quality that optimisation destroys. The adjustment is defensible — the entertainment is the product — but it makes explicit something usually left unstated, which is that a sport is not a contest to determine the best team by any available means but an artificial arrangement maintained for the interest of watching it.\nWhat remains unresolved is the position of the qualities that are not measured. Analysis captures what happens on the field and captures nothing about what a player contributes to the people around them, and the absence is treated in practice as a zero rather than as an unknown. The clubs that appear to do best are those combining the measurements with a judgement about the unmeasured, which is an unsatisfying conclusion for both parties to the original argument.",
    questions: [
      { q: "Why was the original advantage temporary?", options: ["Data became unavailable","The measures were wrong","Prices adjusted once measures were adopted","Rules changed"], answer: 2, explanation: "'the prices adjusted, and what had been an edge became a cost of entry'." },
      { q: "What happened as teams applied the analysis?", options: ["They diversified","They declined","They ignored it","They converged"], answer: 3, explanation: "'they converged'." },
      { q: "How do spectators describe the result?", options: ["More uniform","Faster","Less skilful","More exciting"], answer: 0, explanation: "'a competition that spectators describe as more uniform'." },
      { q: "How does the writer characterise rule changes?", options: ["As unnecessary","As preventing optimal play to preserve a quality","As restoring fairness","As commercially motivated only"], answer: 1, explanation: "'to prevent its participants from playing optimally'." },
      { q: "What do rule changes make explicit?", options: ["That teams cheat","That fans are conservative","That a sport is an artificial arrangement maintained for watching","That analysis is flawed"], answer: 2, explanation: "'an artificial arrangement maintained for the interest of watching it'." },
      { q: "How are unmeasured qualities treated in practice?", options: ["As decisive","As unmeasurable","As secondary","As a zero rather than an unknown"], answer: 3, explanation: "'treated in practice as a zero rather than as an unknown'." }
    ]
  },
  {
    id: "cpe-rmc24-05",
    title: "The Testimony of Those Who Were There",
    text: "Oral history occupies an uncertain position between evidence and literature, and the uncertainty is usually addressed by defending it against the charge that memory is unreliable, which is the wrong defence because the charge is true.\nMemory for events is reconstructive rather than reproductive. A recollection is assembled at the moment of recall from fragments, general knowledge and the requirements of the present narrative, and the assembly incorporates material acquired since, including material from other people's accounts and from published versions of the same events. The confidence with which a memory is held is not related to its accuracy. Detailed, vivid recollections of significant public events have been shown repeatedly to be wrong in specifics their holders would have sworn to.\nWhat follows is not that testimony is worthless but that its evidential value lies elsewhere than in the details. An account establishes what it was like to be in a position, what was known and believed at the time, what the alternatives appeared to be to somebody who could not see the outcome: none of this is available in a document, and all of it is what a later reader most lacks. The reconstructive character of memory does not damage this, since a person's sense of what a period felt like is not a factual claim being misremembered.\nThe methodological consequences are specific. An interviewer should not seek to establish dates and sequences, which the archive does better; should ask about the ordinary rather than the notable, since ordinary practice is precisely what documents omit and what memory holds reliably; and should record the account without correcting it against the record, since a divergence between testimony and document is itself information about how an event was understood.\nThe final consideration is one of timing and is not negotiable. Testimony can be collected only while the people who hold it are alive, and the decision not to collect it is taken by default, by institutions attending to more pressing matters, and is discovered to have been a decision only when it can no longer be reversed. Every generation records the period it can still reach and regrets what the previous one did not.",
    questions: [
      { q: "Why is defending memory's reliability the wrong defence?", options: ["The charge is true", "It is irrelevant", "It is unpopular", "It cannot be tested"], answer: 0, explanation: "'the charge is true'." },
      { q: "How is a recollection produced?", options: ["Retrieved intact", "Assembled at the moment of recall", "Recorded at the time", "Verified against records"], answer: 1, explanation: "'assembled at the moment of recall from fragments'." },
      { q: "What is confidence unrelated to?", options: ["Age","Repetition","Accuracy","Detail"], answer: 2, explanation: "'The confidence with which a memory is held is not related to its accuracy'." },
      { q: "Where does testimony's value lie?", options: ["In factual detail","In corroboration","In dates and sequences","In what it was like to be in a position"], answer: 3, explanation: "'what it was like to be in a position'." },
      { q: "What should an interviewer ask about?", options: ["The ordinary","Dates","Public events","The notable"], answer: 0, explanation: "'should ask about the ordinary rather than the notable'." },
      { q: "How is the decision not to collect taken?", options: ["Deliberately", "By default", "By committee", "By funders"], answer: 1, explanation: "'is taken by default'." }
    ]
  },
  {
    id: "cpe-rmc24-06",
    title: "Working in the Other Language",
    text: "A meeting conducted in a language that some participants speak natively and others do not is described as a meeting in a common language, and the description conceals an asymmetry that determines a great deal about what is decided in it.\nThe cost falls unevenly and is largely invisible to those not paying it. Operating in a second language consumes capacity that is then unavailable for the substance of the discussion: a participant who is composing a sentence is not simultaneously evaluating the proposal, and the delay of a second or two before contributing is sufficient, in a fast exchange, to ensure that the moment has passed. The result is a discussion in which the native speakers appear more engaged and the others appear to have fewer views, and the appearance is a product of the medium.\nThe subtler effect concerns register. Persuasion in any language depends on resources that are acquired late — the qualification that softens without conceding, the idiom that signals membership, the joke that establishes that one is at ease — and a person deprived of these is not merely slower but is heard differently. Their contributions arrive as blunter than intended, and the bluntness is attributed to their character or their culture rather than to the vocabulary available to them under pressure.\nWhat native speakers do about this is generally the wrong thing. Speaking loudly, simplifying vocabulary to the point of condescension and completing other people's sentences are the observed responses, and all three make matters worse. The measures that help are less intuitive: speaking more slowly rather than more simply, avoiding idiom and humour that depends on it, pausing after questions for longer than feels natural, and circulating material in writing beforehand so that comprehension does not have to occur in real time.\nThe structural remedy is to distribute the burden. Meetings in which the working language rotates, or in which contributions may be made in writing during the discussion, change who bears the cost and produce a noticeable difference in whose views are recorded. That such arrangements are rare, in organisations that describe themselves as international, indicates whose convenience is being treated as the default.",
    questions: [
      { q: "What does operating in a second language consume?", options: ["Preparation","Time only","Capacity unavailable for the substance","Confidence"], answer: 2, explanation: "'consumes capacity that is then unavailable for the substance'." },
      { q: "What does the delay before contributing ensure?", options: ["More attention","Fewer interruptions","Better answers","That the moment has passed"], answer: 3, explanation: "'sufficient, in a fast exchange, to ensure that the moment has passed'." },
      { q: "Which resources are acquired late?", options: ["Qualification, idiom and humour","Grammar","Pronunciation","Basic vocabulary"], answer: 0, explanation: "'the qualification that softens without conceding, the idiom that signals membership'." },
      { q: "To what is apparent bluntness attributed?", options: ["Available vocabulary", "Character or culture", "Fatigue", "Disagreement"], answer: 1, explanation: "'attributed to their character or their culture'." },
      { q: "Which response actually helps?", options: ["Simplifying vocabulary","Completing sentences","Speaking more slowly rather than more simply","Speaking loudly"], answer: 2, explanation: "'speaking more slowly rather than more simply'." },
      { q: "What does the rarity of structural remedies indicate?", options: ["Their ineffectiveness","Legal obstacles","Their cost","Whose convenience is the default"], answer: 3, explanation: "'indicates whose convenience is being treated as the default'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
