/* CPE Prep bank: Reading multiple choice (C2) — wave 19 */
(function () {
var BANK = [
  {
    id: "cpe-rmc19-01",
    title: "Every Map Is Wrong",
    text: "A map of the world on a flat sheet is necessarily inaccurate, and the inaccuracy is not a limitation of technique but a mathematical certainty: a curved surface cannot be represented on a plane without distorting area, shape, distance or direction, and every projection is a decision about which of these to sacrifice.\nThe decision is usually presented as technical and is invariably consequential. A projection preserving direction, which is what a navigator requires, distorts area increasingly towards the poles, with the result that regions in high latitudes appear far larger than they are relative to those near the equator. The distortion is a straightforward consequence of the mathematics and is not a statement about anything, but a map is a picture, and a picture that shows one continent as larger than another is understood as a claim about size.\nThe response of designing projections that preserve area has produced maps that are accurate in that respect and that distort shape severely, and the resulting outlines are unfamiliar enough that the maps are read as making a point rather than as showing the world. This is an interesting failure: the more accurate representation is received as the more ideological one, because familiarity is doing work that accuracy cannot displace.\nWhat is rarely stated in the argument is that there is no correct answer available. A projection preserving area cannot preserve shape; one preserving both cannot exist; and the choice must be made according to the use, so that a map for navigation, a map for comparing land areas and a map for showing a single country properly are three different objects that happen to share a name.\nThe practical conclusion for a reader is to treat the projection as part of the information rather than as the medium carrying it, and to notice that most world maps encountered in ordinary life were selected by a designer choosing a familiar outline rather than by anybody considering what the map would be used for. The globe remains the only representation that distorts nothing, and its inconvenience is the reason that a distorted image is what almost everybody carries in their head.",
    questions: [
      { q: "Why is a flat world map necessarily inaccurate?", options: ["A curved surface cannot be represented on a plane undistorted","Data are incomplete","Scales vary","Printing limits"], answer: 0, explanation: "'a curved surface cannot be represented on a plane without distorting'." },
      { q: "What does a direction-preserving projection distort?", options: ["Distance only","Area, increasingly towards the poles","Direction","Coastlines"], answer: 1, explanation: "'distorts area increasingly towards the poles'." },
      { q: "Why is the distortion read as a claim?", options: ["It is exaggerated","It is labelled","A map is a picture","It is deliberate"], answer: 2, explanation: "'a map is a picture, and a picture that shows one continent as larger'." },
      { q: "How are equal-area maps received?", options: ["As navigational tools","As decorative","As more accurate","As making a point"], answer: 3, explanation: "'the maps are read as making a point rather than as showing the world'." },
      { q: "What does the writer call an interesting failure?", options: ["That accuracy is read as ideology", "That projections are complex", "That globes are rare", "That designers disagree"], answer: 0, explanation: "'the more accurate representation is received as the more ideological one'." },
      { q: "How were most everyday world maps selected?", options: ["By purpose", "By a designer choosing a familiar outline", "By cartographic authorities", "By accuracy"], answer: 1, explanation: "'selected by a designer choosing a familiar outline'." }
    ]
  },
  {
    id: "cpe-rmc19-02",
    title: "Who Comes Next",
    text: "Succession is the problem that every organisation solves badly, and the consistency of the failure across sectors, sizes and centuries suggests that the causes are structural rather than particular.\nThe first is that the incumbent is required to organise it. A person is asked to identify their own replacement, to prepare that person, and to hand over at a moment they will select, and the task requires them to contemplate their own irrelevance while performing a role that depends on their being indispensable. The tendency to defer is not a character flaw; it is what the structure produces.\nThe second is that a designated successor is damaged by the designation. Announced too early, they become a rival to the incumbent and a target for everybody whose position would be improved by a different outcome, and their subsequent performance is assessed by an audience with an interest in the assessment. Announced too late, they take office without preparation. There is no interval that avoids both, and organisations oscillate between the errors rather than solving them.\nThe third and least tractable is that the qualities that make a successor visible are not the qualities the position requires. Visibility rewards those who work near the centre, on matters the incumbent notices; the position frequently requires somebody who has run something difficult at a distance, and such people are unknown to the body making the choice. The result is a preference for continuity that is often mistaken for a judgement about competence.\nWhat improves matters is unglamorous and is undertaken by a minority. Multiple candidates developed in parallel, without designation, spread the preparation and avoid the rivalry; a written statement of what the role will require in five years rather than what it requires now shifts the criteria away from resemblance to the incumbent; and a fixed date, set in advance and not by the person departing, removes the decision from the one party structurally incapable of taking it. None of these is difficult, and their rarity indicates that the difficulty was never technical.",
    questions: [
      { q: "What does the consistency of failure suggest?", options: ["Insufficient planning","Poor leadership","Structural causes","Bad luck"], answer: 2, explanation: "'the causes are structural rather than particular'." },
      { q: "What does the incumbent's task require?", options: ["External advice","Board approval","A formal process","Contemplating their own irrelevance"], answer: 3, explanation: "'requires them to contemplate their own irrelevance'." },
      { q: "What happens to an early-designated successor?", options: ["They become a rival and a target","They are trained better","They leave","They gain authority"], answer: 0, explanation: "'they become a rival to the incumbent and a target'." },
      { q: "What do organisations do about the timing problem?", options: ["Solve it", "Oscillate between the errors", "Avoid designation", "Use external candidates"], answer: 1, explanation: "'organisations oscillate between the errors rather than solving them'." },
      { q: "What does visibility reward?", options: ["Technical skill","Running something difficult at a distance","Working near the centre","Long service"], answer: 2, explanation: "'Visibility rewards those who work near the centre'." },
      { q: "Why does a fixed date help?", options: ["It saves time","It reassures staff","It is legally required","It removes the decision from the incumbent"], answer: 3, explanation: "'removes the decision from the one party structurally incapable of taking it'." }
    ]
  },
  {
    id: "cpe-rmc19-03",
    title: "The Record in the Rock",
    text: "The fossil record is the primary evidence for the history of life and is, considered as a sample, one of the worst that any science is obliged to work with. Understanding what it omits is more important than understanding what it contains, since almost every dispute in the field turns on the difference.\nPreservation requires a specific and uncommon sequence: rapid burial in sediment, absence of scavenging, chemical conditions that permit mineralisation, and subsequent survival of the enclosing rock through hundreds of millions of years of uplift, erosion and metamorphism. Each stage removes the great majority of candidates, and the stages compound. What survives is not a random sample of what lived; it is a sample of what died in the right circumstances.\nThe biases are therefore systematic and are known in outline. Hard tissues preserve and soft ones rarely do, so that whole groups without shells or bones are effectively invisible. Aquatic environments accumulate sediment and terrestrial ones erode, so that marine organisms are over-represented by a very large factor. Abundant and widespread species are recorded and rare or localised ones are not, which means that precisely the populations most interesting to a student of extinction are the least likely to appear.\nA further difficulty concerns time. A rock formation may represent a few thousand years or a few million, and the difference is not always determinable, so that two fossils found in adjacent layers may have lived within a generation of each other or many thousands of generations apart. Sequences that appear gradual and sequences that appear abrupt may both be artefacts of how much time each layer contains.\nNone of this justifies the conclusion that the record is uninformative, which is a misreading favoured by those who dislike its implications. A biased sample supports inference provided the biases are characterised, and much of the technical work of the field consists of exactly that characterisation. What it does not support is the confident narrative of a sequence of forms leading to a present outcome, which is a story the gaps permit rather than one the evidence requires.",
    questions: [
      { q: "How does the writer describe the fossil record as a sample?", options: ["One of the worst any science works with","Adequate","Improving","Representative"], answer: 0, explanation: "'one of the worst that any science is obliged to work with'." },
      { q: "What is the record a sample of?", options: ["What lived", "What died in the right circumstances", "What was abundant", "What was recently discovered"], answer: 1, explanation: "'it is a sample of what died in the right circumstances'." },
      { q: "Why are marine organisms over-represented?", options: ["They are easier to find","They are more numerous","Aquatic environments accumulate sediment","They have harder shells"], answer: 2, explanation: "'Aquatic environments accumulate sediment and terrestrial ones erode'." },
      { q: "Which populations are least likely to appear?", options: ["Marine ones","Recent ones","Abundant ones","Rare or localised ones"], answer: 3, explanation: "'Abundant and widespread species are recorded and rare or localised ones are not'." },
      { q: "What difficulty concerns time?", options: ["A layer may represent thousands or millions of years","Fossils move between layers","Layers are always thin","Dating methods are unreliable"], answer: 0, explanation: "'may represent a few thousand years or a few million'." },
      { q: "What does the record not support?", options: ["Any inference", "A confident narrative leading to the present", "Extinction studies", "Comparative anatomy"], answer: 1, explanation: "'the confident narrative of a sequence of forms leading to a present outcome'." }
    ]
  },
  {
    id: "cpe-rmc19-04",
    title: "The Instrument Writes the Music",
    text: "The history of composition is conventionally written as a history of ideas and is at least as much a history of hardware, since what a composer writes is bounded by what the available instruments can do, and the boundaries move when the instruments change.\nThe clearest cases are those in which a mechanical development is followed immediately by a change in the music. The addition of valves to brass instruments made a full chromatic scale available to players who had previously been restricted to a set of notes determined by the harmonic series, and the writing for those instruments changed within a generation from fanfare-like figures to melodic lines. Nothing about the musical imagination had altered; a constraint had been removed, and composers immediately wrote what had previously been impossible.\nThe relationship also runs in the other direction, though it is slower and less often noticed. Instruments are modified in response to demands the existing versions cannot meet: the piano acquired a heavier frame and greater tension because composers and players wanted a volume that the earlier instrument could not produce without breaking, and the resulting instrument then made a different kind of writing possible in its turn. Each change to the hardware and each change to the repertoire is a response to the other, and neither is the origin.\nWhat this suggests about the persistent question of technical limitation is that the question is badly posed. A constraint does not merely prevent; it directs. The music written for instruments incapable of certain things is not a reduced version of the music that would have been written without the restriction, since the restriction shaped what was attempted, and much of what is admired in earlier repertoire consists of solutions to problems that no longer exist.\nThe corollary for the present is uncomfortable for anybody who believes that expanded capability is straightforwardly an improvement. An instrument capable of anything supplies no direction whatever, and the difficulty reported by composers working with unrestricted electronic resources is not a failure of imagination but the absence of the resistance against which musical decisions were historically made.",
    questions: [
      { q: "How is the history of composition conventionally written?", options: ["As a history of performance","As a history of hardware","As a history of ideas","As a history of patronage"], answer: 2, explanation: "'conventionally written as a history of ideas'." },
      { q: "What did valves make available?", options: ["Longer instruments","Easier fingering","Greater volume","A full chromatic scale"], answer: 3, explanation: "'made a full chromatic scale available'." },
      { q: "What changed when the constraint was removed?", options: ["The writing, from fanfares to melodic lines","The instruments' popularity","Performance practice only","The musical imagination"], answer: 0, explanation: "'changed within a generation from fanfare-like figures to melodic lines'." },
      { q: "Why did the piano acquire a heavier frame?", options: ["To last longer", "Because greater volume was wanted", "For transport", "To reduce cost"], answer: 1, explanation: "'because composers and players wanted a volume that the earlier instrument could not produce'." },
      { q: "What does the writer say a constraint does?", options: ["Delays innovation","Merely prevents","Directs as well as prevents","Reduces quality"], answer: 2, explanation: "'A constraint does not merely prevent; it directs.'" },
      { q: "What difficulty do composers with unlimited resources report?", options: ["Lack of funding","Poor sound quality","Technical complexity","The absence of resistance"], answer: 3, explanation: "'the absence of the resistance against which musical decisions were historically made'." }
    ]
  },
  {
    id: "cpe-rmc19-05",
    title: "The Obligation in a Small Gift",
    text: "The experimental literature on reciprocity is among the most reliable in social psychology and among the least comfortable, since what it establishes is that a small unsolicited benefit produces a disproportionate obligation in the recipient, and that the recipient is generally unaware of the mechanism operating on them.\nThe effect does not require that the gift be wanted, valuable, or accepted willingly. An item pressed on somebody who did not ask for it produces a measurable increase in the likelihood of subsequent compliance, and attempts to disclaim the obligation verbally do not remove it. What appears to be operating is a rule of exchange so deeply established that it functions below the level at which a person could decide not to apply it.\nThe asymmetry between what is given and what is returned is the commercially interesting part. The return is calibrated not to the value of the initial benefit but to the discomfort of remaining in debt, and that discomfort is largely independent of magnitude, so that a trivial gift can secure a substantial concession. This is why the technique is used by parties whose interest in the recipient is exhausted by the transaction.\nThe professional contexts in which this matters are those in which a judgement is supposed to be independent. The recipient of hospitality from a party with an interest in their decision will report, sincerely, that it has no influence, and the sincerity is not in doubt: the mechanism operates without producing any experience that could be reported. This is why declarations of interest, while useful, do not solve the problem, and why prohibition is the only measure that has been shown to work.\nThe difficulty in ordinary life is that reciprocity is also the foundation of cooperation, and a person who has trained themselves to refuse every unreciprocated benefit has purchased their independence at the cost of the relationships that such exchanges create. The available distinction is not between accepting and refusing but between exchanges with somebody one will deal with repeatedly and exchanges with somebody who will not be seen again, since the first is how trust is built and the second is where the technique lives.",
    questions: [
      { q: "What does a small unsolicited benefit produce?", options: ["A disproportionate obligation","Suspicion","Indifference","Gratitude"], answer: 0, explanation: "'produces a disproportionate obligation in the recipient'." },
      { q: "What does the effect not require?", options: ["Repeated contact","That the gift be wanted","Physical contact","A written record"], answer: 1, explanation: "'does not require that the gift be wanted, valuable, or accepted willingly'." },
      { q: "What is the return calibrated to?", options: ["Future benefit","The gift's value","The discomfort of remaining in debt","Social status"], answer: 2, explanation: "'calibrated not to the value of the initial benefit but to the discomfort of remaining in debt'." },
      { q: "Why are sincere denials of influence unreliable?", options: ["Memory fails","Denials are coerced","People lie","The mechanism produces no reportable experience"], answer: 3, explanation: "'the mechanism operates without producing any experience that could be reported'." },
      { q: "Which measure has been shown to work?", options: ["Prohibition","Training","Disclosure to the public","Declarations of interest"], answer: 0, explanation: "'prohibition is the only measure that has been shown to work'." },
      { q: "What distinction does the writer propose?", options: ["Between large and small gifts", "Between repeated and one-off dealings", "Between money and goods", "Between public and private settings"], answer: 1, explanation: "'exchanges with somebody one will deal with repeatedly and exchanges with somebody who will not be seen again'." }
    ]
  },
  {
    id: "cpe-rmc19-06",
    title: "The Second Reading",
    text: "A book read twice is two different books, and the difference is not principally a matter of noticing more, which is how it is usually described. What alters is the operation being performed, and the alteration is large enough that the two readings are not comparable experiences.\nA first reading is dominated by the question of what happens, and the question consumes attention in a way that is not available for anything else. Everything encountered is provisional, since its significance depends on material not yet read, and a reader is therefore holding a great deal in suspension and disposing of most of it. This is why a first reading is exhausting and why it retains so little: the mind is engaged in a sorting operation rather than in taking anything in.\nOn a second reading the question is settled, and the attention it consumed is released. What was suspense becomes structure: a reader who knows how a thing ends can see the preparation, can observe which effects were set up and how far in advance, and can attend to the writing itself, which on a first reading is largely transparent. The experience is less urgent and considerably more informative, and it is the reading in which almost everything that is said about a book is actually noticed.\nA third factor is the reader rather than the text. An interval of years produces a person with different concerns, and a book returned to after such an interval yields material that was present and unavailable: passages that were skimmed as background become the centre, and the earlier response is retrievable only as a memory of having felt something the present reader does not feel. The book has functioned as an instrument for measuring the change.\nWhat follows is a practical position that most readers do not adopt, which is that the number of books read is a poor measure of anything. A person who has read forty books once has performed forty sorting operations; a person who has read ten books four times has done something else entirely, and the second is what the word reading has generally been taken to mean by those whose opinions on the subject are worth having.",
    questions: [
      { q: "What alters on a second reading?", options: ["The pace","The text","The operation being performed","The reader's memory"], answer: 2, explanation: "'What alters is the operation being performed'." },
      { q: "Why does a first reading retain little?", options: ["The material is unfamiliar","Attention wanders","It is too fast","The mind is engaged in a sorting operation"], answer: 3, explanation: "'the mind is engaged in a sorting operation rather than in taking anything in'." },
      { q: "What does suspense become?", options: ["Structure","Familiarity","Detail","Boredom"], answer: 0, explanation: "'What was suspense becomes structure'." },
      { q: "What is largely transparent on a first reading?", options: ["The plot", "The writing itself", "The characters", "The setting"], answer: 1, explanation: "'the writing itself, which on a first reading is largely transparent'." },
      { q: "What does an interval of years produce?", options: ["A shorter reading","A forgotten book","A person with different concerns","Better memory"], answer: 2, explanation: "'An interval of years produces a person with different concerns'." },
      { q: "What does the writer say about the number of books read?", options: ["It indicates diligence","It should be recorded","It predicts understanding","It is a poor measure"], answer: 3, explanation: "'the number of books read is a poor measure of anything'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
