/* CPE Prep bank: Reading multiple choice (C2) — wave 9 */
(function () {
var BANK = [
  {
    id: "cpe-rmc9-01",
    title: "The Authority of the Footnote",
    text: "The footnote performs two functions that are ordinarily conflated and that pull in opposite directions. The first is evidential: it discloses the basis of a claim so that a reader may check it. The second is rhetorical: it signals that a claim has a basis, and it performs that signalling function whether or not anybody looks.\nThe second function is the one that operates. Studies of citation practice consistently find that a substantial proportion of references are inaccurate in ways that indicate the cited work was not consulted directly, and that errors propagate through chains of citation in which each author has taken the reference from the previous one. The mechanism is not fraud; it is that the cost of verifying a reference is real and the probability of detection is negligible.\nA further difficulty attends the apparatus of scholarly form. A page carrying forty references appears more thoroughly grounded than one carrying four, and the appearance is available at low cost to anybody who wishes to produce it. Where an audience assesses rigour by the density of the apparatus, the apparatus expands, and its expansion is uncorrelated with anything a reader would call reliability.\nWhat the footnote does achieve, and what nothing else achieves, is the possibility of dissent. A claim without a source cannot be checked and can only be believed or disbelieved; a claim with one can be pursued, and the existence of that route constrains what an author is prepared to assert, quite independently of whether anybody follows it. This is a considerable achievement and it does not require that references be accurate, which is fortunate.\nThe recommendation that follows is unglamorous. A reader wishing to assess a work should check three references at random, which takes about twenty minutes and produces information that no amount of reading the text can produce, and a reader who declines to do so should treat the apparatus as a claim about the author's practice rather than as evidence about the world.",
    questions: [
      { q: "What two functions does the footnote perform?", options: ["Evidential and rhetorical", "Legal and academic", "Historical and stylistic", "Explanatory and decorative"], answer: 0, explanation: "'The first is evidential... The second is rhetorical'." },
      { q: "Which function does the writer say actually operates?", options: ["The evidential one", "The rhetorical one", "Neither", "Both equally"], answer: 1, explanation: "'The second function is the one that operates.'" },
      { q: "How does the writer explain citation errors?", options: ["As translation problems","As fraud","As the result of low verification incentives","As editorial failures"], answer: 2, explanation: "'the cost of verifying a reference is real and the probability of detection is negligible'." },
      { q: "What happens where rigour is judged by apparatus density?", options: ["Citations become more accurate","Authors cite less","Standards improve","The apparatus expands without gaining reliability"], answer: 3, explanation: "'its expansion is uncorrelated with anything a reader would call reliability'." },
      { q: "What unique achievement does the footnote have?", options: ["It makes dissent possible", "It shortens texts", "It improves style", "It ensures accuracy"], answer: 0, explanation: "'what nothing else achieves, is the possibility of dissent'." },
      { q: "What does the writer recommend to readers?", options: ["Ignoring references", "Checking three references at random", "Reading only reviewed work", "Counting citations"], answer: 1, explanation: "'should check three references at random'." }
    ]
  },
  {
    id: "cpe-rmc9-02",
    title: "The Discipline of Having No View",
    text: "There is a social cost attached to the statement that one has not formed a view, and it is levied most heavily on those from whom a view is expected. The cost is real and it is worth paying, because the alternative is a population of positions arrived at without any process that would justify them and held with a firmness that increases with the frequency of their expression.\nThe mechanism by which an unexamined view hardens is reasonably well documented. A position stated aloud acquires an owner; the owner is subsequently exposed to information bearing on it and processes that information as evidence about whether they were right rather than as evidence about the question. What began as a remark becomes a commitment, and the commitment is defended with an energy that its original basis could not possibly warrant.\nThe corresponding difficulty is that a refusal to form a view may be a refusal to think, and the two are indistinguishable from outside. A person who declines to take a position on a matter they have not examined is exercising a virtue; a person who declines because taking one would be costly is exercising something else, and both produce the same sentence. This is why the useful formulation includes what would be required: what one would need to know, from whom, and by when.\nThere is also a question of role. An individual is entitled to have no view about most things; a person occupying an office is frequently not, since a decision must be taken and the absence of a view is a decision to leave matters as they are, which is a position with consequences and not an abstention from having one.\nWhat may be defended, then, is narrower than a general scepticism and considerably more difficult to practise. It is the maintenance of a distinction, in one's own mind and in what one says, between the things one has examined and the things about which one has merely acquired an impression, and the observation that the second category is, for everybody, very much the larger.",
    questions: [
      { q: "Why is the social cost of having no view worth paying?", options: ["It is expected professionally","It saves time","The alternative is unjustified positions held firmly","It avoids conflict"], answer: 2, explanation: "'a population of positions arrived at without any process that would justify them'." },
      { q: "How does an unexamined view harden?", options: ["Through public debate","Because it is written down","Through repetition alone","Because new information is processed as evidence about being right"], answer: 3, explanation: "'as evidence about whether they were right rather than as evidence about the question'." },
      { q: "What difficulty attends refusing to form a view?", options: ["It is indistinguishable from refusing to think","It requires expertise","It is rarely accepted","It is always dishonest"], answer: 0, explanation: "'the two are indistinguishable from outside'." },
      { q: "What does the useful formulation include?", options: ["An apology", "What would be required to reach a view", "A provisional position", "A refusal to discuss"], answer: 1, explanation: "'what one would need to know, from whom, and by when'." },
      { q: "Why may an office-holder not abstain?", options: ["Because they are better informed","Because rules forbid it","Because inaction is itself a position","Because colleagues object"], answer: 2, explanation: "'the absence of a view is a decision to leave matters as they are'." },
      { q: "What does the writer ultimately defend?", options: ["Silence in public","Deference to experts","General scepticism","Distinguishing examined views from impressions"], answer: 3, explanation: "'the maintenance of a distinction... between the things one has examined and the things about which one has merely acquired an impression'." }
    ]
  },
  {
    id: "cpe-rmc9-03",
    title: "The Reader Over the Shoulder",
    text: "Every piece of writing is addressed to somebody, and the identity of that person determines a great deal more than tone. It determines what may be assumed, what must be explained, what will be read as an insult and what will be read as a courtesy, and a writer who has not settled the question has settled it anyway, generally in favour of somebody rather like themselves.\nThe consequences are most visible where a document is intended to reach a mixed audience. A report written for a specialist and circulated to a committee is not a report that the committee will misunderstand; it is one they will not read, and the failure will be attributed to their inattention. The same document rewritten for the committee will be regarded by the specialists as having omitted everything of interest, which is also true. The instinct to compromise produces a document addressed to a person who does not exist and useful to nobody.\nThe alternative, which is more work and considerably more effective, is to write two documents and to say so. A four-page account for the decision-makers and a technical annexe for those who will interrogate it are not a duplication; they are two texts with different purposes, and the transparency of the arrangement removes the suspicion that attaches to any summary presented alone.\nThere is a subtler effect on the writer. An imagined reader operates as a constraint during composition, and the quality of the constraint depends on who is imagined. A writer whose internal audience consists of colleagues will produce work that satisfies colleagues; one who imagines an intelligent reader from outside the field will produce something that has been forced to justify its assumptions, and the second is frequently better on criteria the field itself would accept.\nThe practical recommendation is to name the reader, on paper, before writing anything, and to be specific to the point of absurdity: not a general audience but a particular person with a particular reason for reading. Writers who do this report that a substantial proportion of what they had intended to include falls away at that moment, which is the exercise doing exactly what it exists to do.",
    questions: [
      { q: "What happens if a writer does not settle who they address?", options: ["It is settled by default in favour of somebody like themselves","The tone becomes neutral","Editors decide","The document fails entirely"], answer: 0, explanation: "'generally in favour of somebody rather like themselves'." },
      { q: "What does a specialist report circulated to a committee produce?", options: ["Misunderstanding", "Non-reading blamed on the committee", "Useful debate", "Requests for clarification"], answer: 1, explanation: "'it is one they will not read, and the failure will be attributed to their inattention'." },
      { q: "What does the instinct to compromise produce?", options: ["Two versions","A balanced document","A document addressed to a person who does not exist","A shorter text"], answer: 2, explanation: "'a document addressed to a person who does not exist and useful to nobody'." },
      { q: "Why is the two-document approach not duplication?", options: ["Because one is discarded","Because they share content","Because it is shorter overall","Because the texts have different purposes"], answer: 3, explanation: "'they are two texts with different purposes'." },
      { q: "How does the imagined reader affect the writer?", options: ["It operates as a constraint during composition", "It slows the work", "It has no measurable effect", "It determines length only"], answer: 0, explanation: "'An imagined reader operates as a constraint during composition'." },
      { q: "What do writers report after naming a specific reader?", options: ["They write faster", "Much of the intended content falls away", "They need more sources", "The tone becomes formal"], answer: 1, explanation: "'a substantial proportion of what they had intended to include falls away'." }
    ]
  },
  {
    id: "cpe-rmc9-04",
    title: "Prediction as a Literary Form",
    text: "Published predictions are read as attempts to describe the future and are more usefully read as documents about the present, since they are constrained by what an audience at the moment of writing is prepared to find plausible, and the constraint operates far more powerfully than any consideration about what is likely.\nThe evidence for this is straightforward. Predictions from any period cluster around the extrapolation of whatever was then novel, and they are almost uniformly silent about the developments that turned out to matter, for the reason that those developments did not yet have a vocabulary. A forecast is composed of available concepts, and the things that reorganise a field are precisely those for which no concept exists at the moment of forecasting.\nA second regularity concerns the direction of error. Technological change is habitually overestimated in the short run and underestimated in the long, and the mechanism appears to be that the first is a question about engineering, which enthusiasts can assess, and the second is a question about adoption, which depends on institutions, regulation and habit and which nobody finds interesting to model.\nThe genre has an accountability problem that is structural rather than moral. A prediction is issued at a moment when its subject is interesting, and it comes due at a moment when it is not, and the audience that received it has dispersed. Attempts to correct this by scoring forecasters have produced the finding, now well replicated, that most published forecasters perform no better than chance and that the small number who do better are distinguished by a characteristic style: frequent small revisions, explicit probabilities and a marked reluctance to produce the confident narrative that secures an audience.\nThe conclusion is inconvenient to everybody involved. The forecasts most likely to be accurate are those least likely to be read, and the ones that circulate are selected for the qualities that make them wrong. A reader is therefore best advised to treat any confident account of the coming decade as a description of what its author's contemporaries currently believe, which is a genuinely valuable thing to know and is not what the document claims to offer.",
    questions: [
      { q: "How does the writer suggest predictions should be read?", options: ["As policy proposals","As descriptions of the future","As documents about the present","As fiction"], answer: 2, explanation: "'more usefully read as documents about the present'." },
      { q: "Why are important developments absent from forecasts?", options: ["They are classified","They seem implausible","They are deliberately excluded","They lack a vocabulary at the time"], answer: 3, explanation: "'those developments did not yet have a vocabulary'." },
      { q: "What is the habitual direction of error?", options: ["Overestimating short run, underestimating long run","Underestimating both","Errors are random","Overestimating both short and long run"], answer: 0, explanation: "'overestimated in the short run and underestimated in the long'." },
      { q: "Why is long-run change underestimated?", options: ["Engineering is unpredictable", "Adoption depends on factors nobody enjoys modelling", "Data are unavailable", "Forecasters are cautious"], answer: 1, explanation: "'depends on institutions, regulation and habit and which nobody finds interesting to model'." },
      { q: "What distinguishes the better forecasters?", options: ["Institutional support","Confident narratives","Frequent revisions and explicit probabilities","Longer time horizons"], answer: 2, explanation: "'frequent small revisions, explicit probabilities'." },
      { q: "What is the inconvenient conclusion?", options: ["All forecasting should stop","Forecasters are dishonest","Accuracy is improving","Accurate forecasts are least likely to be read"], answer: 3, explanation: "'The forecasts most likely to be accurate are those least likely to be read'." }
    ]
  },
  {
    id: "cpe-rmc9-05",
    title: "What a Single Case Can Show",
    text: "The case study occupies an uncomfortable position in the hierarchy of evidence, admired by practitioners and distrusted by methodologists, and the disagreement is generally conducted as though a single question were at issue when in fact there are several.\nOn the question of frequency, the distrust is entirely warranted. A case cannot establish how common anything is, and a literature composed of cases will systematically over-represent the unusual, since a case is written because it was worth writing about. Any inference of the form this happens often, drawn from a series of cases, is invalid regardless of how many cases there are.\nOn the question of possibility, the position reverses completely. A single well-documented case establishes that something can occur, which no statistical study can do and which is frequently the finding that matters. An account of one patient, one organisation or one failure is sufficient to refute a general claim, and the history of every applied field contains examples of a confident generalisation dismantled by a single instance that could not be explained away.\nOn the question of mechanism, the case is the only instrument available. Statistical association establishes that two things vary together and is silent about the route between them, and the route is what an intervention must act upon. A detailed reconstruction of a single sequence, in which each step is observed rather than inferred, produces a candidate mechanism that can subsequently be tested at scale, and the order of those operations is the reverse of what most research training implies.\nThe methodological rules that follow are not difficult and are inconsistently applied. A case should state why this case was selected, since selection is where the bias enters; it should include the material that does not fit, since a case in which everything supports the conclusion has been curated; and it should state explicitly which of the three questions it is answering. A case study that fails to do the last is not necessarily wrong and is certain to be misread, generally by readers who take a claim about possibility for a claim about frequency, which is the commonest error in the interpretation of evidence of any kind.",
    questions: [
      { q: "What does the writer say about disagreement over case studies?", options: ["Several questions are being conflated","It has been resolved","It is about presentation","It concerns one question"], answer: 0, explanation: "'as though a single question were at issue when in fact there are several'." },
      { q: "Why are cases unreliable about frequency?", options: ["They are poorly documented", "Cases are written because they were unusual", "There are too few of them", "They are anonymised"], answer: 1, explanation: "'a case is written because it was worth writing about'." },
      { q: "What can a single case establish?", options: ["The average outcome","How common something is","That something can occur","The strength of an association"], answer: 2, explanation: "'establishes that something can occur'." },
      { q: "Why is a case the only instrument for mechanism?", options: ["Cases are cheaper","Statistics are unreliable","Mechanisms cannot be tested","Statistical association is silent about the route"], answer: 3, explanation: "'Statistical association establishes that two things vary together and is silent about the route'." },
      { q: "What should a case state about its own selection?", options: ["Why this case was chosen","How long it took","Which journal rejected it","Who funded it"], answer: 0, explanation: "'A case should state why this case was selected'." },
      { q: "What is the commonest error in interpreting evidence?", options: ["Excessive scepticism","Confusing possibility with frequency","Ignoring statistics","Over-reliance on mechanism"], answer: 1, explanation: "'take a claim about possibility for a claim about frequency'." }
    ]
  },
  {
    id: "cpe-rmc9-06",
    title: "Mistakes Were Made",
    text: "The passive voice has acquired a reputation it does not entirely deserve, and the reputation obscures the distinction that actually matters, which is not between passive and active constructions but between sentences that identify an agent and sentences that do not.\nThe grammatical point is straightforward. A passive construction may name its agent perfectly well, and an active one may conceal it as effectively as any passive: an institution that reports that a review has determined something has produced an active sentence in which the acting party is an abstraction. The stylistic advice that circulates in every handbook addresses a form and not the property the form is being blamed for.\nWhere the passive is genuinely doing concealing work, it is worth asking what would have to be written in order to name the agent, since the answer is frequently the reason for the construction. A sentence stating that an error occurred can be rewritten to identify the person who made it, and the rewriting requires a decision that somebody has declined to take. The construction is therefore evidence about an organisation rather than about a writer.\nThere are, equally, contexts in which the agent is genuinely uninteresting and the passive is the correct choice. A description of a process in which the identity of the operator is irrelevant is not improved by inventing an actor, and the insistence that every sentence carry a subject who did something produces prose that is falsely specific, which is a worse fault than being vague about something that does not matter.\nThe useful test is not grammatical at all. For every sentence in which responsibility is at issue, one asks whether a reader could establish, from the text, who would have to have acted differently for the outcome to have been avoided. Where the answer is no, the sentence has failed, whatever its construction; where it is yes, the sentence has succeeded, and it is a matter of indifference which voice was used to achieve it.",
    questions: [
      { q: "What distinction does the writer regard as important?", options: ["Between long and short sentences","Between passive and active","Between naming and not naming an agent","Between formal and informal style"], answer: 2, explanation: "'between sentences that identify an agent and sentences that do not'." },
      { q: "What example is given of active concealment?", options: ["An error occurred","A decision was taken","The process was completed","A review has determined something"], answer: 3, explanation: "'a review has determined something has produced an active sentence in which the acting party is an abstraction'." },
      { q: "What does the writer say about handbook advice?", options: ["It addresses form rather than the real property", "It is entirely correct", "It is too complicated", "It is rarely followed"], answer: 0, explanation: "'addresses a form and not the property the form is being blamed for'." },
      { q: "Why is a concealing construction evidence about an organisation?", options: ["Because writers are anonymous", "Because naming the agent requires a declined decision", "Because style guides are institutional", "Because passives are mandated"], answer: 1, explanation: "'the rewriting requires a decision that somebody has declined to take'." },
      { q: "When is the passive the correct choice?", options: ["When the writer is unsure","Never","When the agent is uninteresting","In all technical writing"], answer: 2, explanation: "'the agent is genuinely uninteresting and the passive is the correct choice'." },
      { q: "What is the writer's proposed test?", options: ["Whether the sentence is short","Whether an editor approves","Whether the voice is active","Whether a reader can identify who should have acted differently"], answer: 3, explanation: "'whether a reader could establish, from the text, who would have to have acted differently'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
