/* CPE Prep bank: Reading multiple choice (C2) — wave 17 */
(function () {
var BANK = [
  {
    id: "cpe-rmc17-01",
    title: "When Every Town Kept Its Own Hour",
    text: "Standard time is a recent arrangement and was resisted at the time on grounds that are more interesting than the eventual outcome suggests. Before it, each place kept the hour indicated by the sun over it, which meant that noon in one town differed by several minutes from noon in the next, and the arrangement caused nobody any difficulty for as long as nobody moved faster than a horse.\nThe railway created the difficulty and did so in a form that could not be evaded. A timetable must state a time, and a time meant something different at every station on the line, so that a schedule was either unintelligible or dangerous, since two trains proceeding on inconsistent reckonings occupy the same track. The companies accordingly adopted a single time of their own, and the public was presented with a fact rather than a proposal.\nThe objection raised was not sentimental. Local time was true in a sense that the imposed time was not: the sun genuinely was overhead at local noon, and the new arrangement required a town to declare that noon occurred at a moment when the evidence of the sky said otherwise. What was being asked was that a community accept a convention in place of an observation, and the request was understood, correctly, as a transfer of authority from the place to the network.\nThe resistance took the form that such resistance usually takes, which is neither refusal nor acceptance but duplication. Public clocks in a number of towns carried two minute hands for years, and the practice persisted until the generation that regarded local time as the real one had been replaced by one that had never used it.\nWhat the episode illustrates is not that the objectors were wrong. They were right about what was happening and wrong only about whether it could be prevented, and the pattern recurs whenever a network requires uniformity from places that had previously determined their own arrangements. The subsequent invisibility of the change is the most striking part: a person consulting a timetable today is participating in a settlement whose terms were contested and whose losing side has left almost no trace.",
    questions: [
      { q: "Why did local time cause no difficulty originally?", options: ["Nobody moved faster than a horse","Towns were isolated","Time was not measured precisely","Clocks were rare"], answer: 0, explanation: "'for as long as nobody moved faster than a horse'." },
      { q: "What problem did the railway create?", options: ["Overcrowding", "A timetable time meant something different at every station", "Clock inaccuracy", "Excessive speed"], answer: 1, explanation: "'a time meant something different at every station on the line'." },
      { q: "How was the public treated in the change?", options: ["Compensated","Consulted formally","Presented with a fact rather than a proposal","Given a vote"], answer: 2, explanation: "'the public was presented with a fact rather than a proposal'." },
      { q: "What was the basis of the objection?", options: ["Religious grounds","Inconvenience","Cost","That a convention was replacing an observation"], answer: 3, explanation: "'accept a convention in place of an observation'." },
      { q: "What form did the resistance take?", options: ["Duplication, with two minute hands","Legal challenge","Petitions","Refusal"], answer: 0, explanation: "'Public clocks in a number of towns carried two minute hands for years'." },
      { q: "What does the writer find most striking?", options: ["The speed of adoption", "The invisibility of the change afterwards", "The strength of resistance", "The railway's power"], answer: 1, explanation: "'The subsequent invisibility of the change is the most striking part'." }
    ]
  },
  {
    id: "cpe-rmc17-02",
    title: "The Recipe Does Not Say",
    text: "A recipe presents itself as a set of instructions sufficient to produce a result and is in fact a compressed record of a process, most of which it does not describe, and the gap between the two accounts for a great deal of unexplained failure in domestic kitchens.\nThe omissions are systematic rather than careless. A recipe states quantities, which are easy to write, and is largely silent about the sensory information by which a cook actually navigates: how the mixture should look when it has been worked enough, what the sound of the pan indicates, when the resistance under a knife means what it means. These are the operative variables and they resist description, so what is written down is the residue that survives writing.\nTime and temperature are given and are the least reliable part. An instruction to cook for twenty minutes assumes an oven that is at the stated temperature, which few are, and a dish of a particular dimension, which is rarely specified, and an ingredient at a particular starting temperature, which is never mentioned. The experienced cook treats such figures as an order of magnitude and consults the food, and the recipe does not say that this is what should be done, since the author has forgotten that they are doing it.\nThe historical recipe makes the problem visible by exaggerating it. Instructions from earlier centuries assume a knowledge base that no longer exists — a moderate oven, a piece of butter the size of a walnut, cook until done — and are unusable not because they are vague but because they were addressed to somebody who had been taught. Modern recipes differ in degree and not in kind, and a reader who has failed with one has usually failed at something the text did not mention.\nThe practical inference is that a recipe should be read as a route rather than as a specification, and that the useful additions to any published version are the ones the cook writes on it afterwards: what went wrong, at what stage, and what the material looked like at the moment it went wrong. A recipe annotated over five attempts is a different and much better document, and it is one that cannot be bought.",
    questions: [
      { q: "What is a recipe actually?", options: ["A list of quantities","A complete set of instructions","A compressed record of a process","A historical document"], answer: 2, explanation: "'a compressed record of a process'." },
      { q: "Why are the omissions systematic?", options: ["Space is limited","Publishers cut text","Authors are careless","Sensory information resists description"], answer: 3, explanation: "'These are the operative variables and they resist description'." },
      { q: "What is unreliable about time and temperature?", options: ["They assume unstated conditions", "They are usually wrong", "They vary by region", "They are optional"], answer: 0, explanation: "'assumes an oven that is at the stated temperature, which few are'." },
      { q: "How does the experienced cook treat such figures?", options: ["As precise", "As an order of magnitude", "As irrelevant", "As legally binding"], answer: 1, explanation: "'treats such figures as an order of magnitude and consults the food'." },
      { q: "Why are historical recipes unusable?", options: ["They are incomplete","They are vague","They were addressed to somebody who had been taught","They use old measures"], answer: 2, explanation: "'they were addressed to somebody who had been taught'." },
      { q: "What makes an annotated recipe valuable?", options: ["It is shorter","It is illustrated","It is tested","It records what went wrong and when"], answer: 3, explanation: "'what went wrong, at what stage, and what the material looked like'." }
    ]
  },
  {
    id: "cpe-rmc17-03",
    title: "The Machine That Marks the Essay",
    text: "Automated essay scoring achieves agreement with human markers at rates comparable to the agreement between two human markers, and this fact is presented as validation by its advocates and as an indictment of human marking by its critics, and both readings are available because the underlying question has not been settled.\nWhat the systems do is reasonably well understood. They identify features that correlate with the scores human markers award — sentence length and variation, vocabulary range, the density of certain connective expressions, structural markers of organisation — and combine them. They do not, in any sense that would satisfy a philosopher or a teacher, read. The correlation is nevertheless high, because the features are genuinely associated with the qualities markers respond to.\nThe difficulty is exposed by adversarial testing. Essays constructed to exhibit the measured features while being semantically empty receive high scores, and essays making an unusual argument in plain language receive low ones. Neither result is a defect in the system's own terms, since the system is doing what it was built to do, and both indicate that the measured features are proxies whose relationship to the thing of interest holds only for texts produced without knowledge of the measurement.\nThis is the general problem with any proxy that becomes a target, and its consequences here are educational rather than technical. A student who knows what is being measured can be taught to produce it, and the teaching is efficient and unedifying, and the resulting writing is worse by every criterion except the one being applied. The system has then not merely failed to measure writing; it has changed what is being written.\nThe defensible use is therefore narrow and is not the one being marketed. As a second marker flagging discrepancies for human attention, such a system adds information at low cost and cannot be gamed by a student who does not know which script will be flagged. As the sole determinant of a score that matters, it converts an assessment of writing into an assessment of conformity to a measurable pattern, and does so while reporting agreement statistics that remain entirely accurate.",
    questions: [
      { q: "What do automated systems actually identify?", options: ["Features correlating with human scores","Factual accuracy","Originality","Meaning"], answer: 0, explanation: "'They identify features that correlate with the scores human markers award'." },
      { q: "Why is the correlation high?", options: ["The systems read", "The features are genuinely associated with qualities markers respond to", "Markers are inconsistent", "Essays are formulaic"], answer: 1, explanation: "'the features are genuinely associated with the qualities markers respond to'." },
      { q: "What does adversarial testing show?", options: ["Markers disagree","Scores are random","Empty essays score highly","Systems fail entirely"], answer: 2, explanation: "'Essays constructed to exhibit the measured features while being semantically empty receive high scores'." },
      { q: "When does the proxy relationship hold?", options: ["Only for long essays","For trained writers","Always","For texts produced without knowledge of the measurement"], answer: 3, explanation: "'holds only for texts produced without knowledge of the measurement'." },
      { q: "What is the educational consequence?", options: ["Writing becomes worse by every criterion but the applied one","Faster feedback","More practice","Improved standards"], answer: 0, explanation: "'the resulting writing is worse by every criterion except the one being applied'." },
      { q: "What is the defensible use?", options: ["Sole determinant of scores", "A second marker flagging discrepancies", "Replacing teachers", "Ranking schools"], answer: 1, explanation: "'As a second marker flagging discrepancies for human attention'." }
    ]
  },
  {
    id: "cpe-rmc17-04",
    title: "Finding the Way Out",
    text: "The design of signage in large public buildings is judged by a criterion that sounds obvious and is routinely violated, which is that a person should be able to reach their destination while thinking about something else.\nThe underlying observation is that wayfinding is not primarily a matter of reading. A person moving through a building forms a rough model of its layout and navigates by that model, consulting signs only when the model fails; and a building whose structure is legible — where the main route is wider, where daylight indicates the exterior, where the circulation follows an apprehensible geometry — requires very little signage. A building whose structure is illegible cannot be repaired by signs, and the quantity of signage in a space is therefore a reasonably good measure of how badly it was planned.\nThe second principle concerns the decision point. Information is required at the moment a choice is presented and is useless elsewhere, which sounds trivial and is contradicted by the common practice of placing a comprehensive directory at the entrance, where a visitor cannot yet use it, and nothing at the junction three floors up where the actual choice occurs. What is needed at each point is not the full map but the answer to the question being asked there.\nA third and less obvious principle concerns confirmation. A person who has turned correctly needs to be told so, and the absence of confirmation produces the characteristic behaviour of stopping, retracing and re-reading, which is expensive in circulation terms and is experienced as the visitor's own failure. Signs placed only at junctions produce this; signs that also appear mid-route do not.\nWhat unites these is that the design must be assessed by observing people rather than by consulting the drawing, since the drawing is comprehensible to somebody who has seen it and the building is encountered by somebody who has not. The test is cheap: a person unfamiliar with the building is asked to reach a location and is watched. Where they stop is where the design has failed, and the information cannot be obtained in any other way.",
    questions: [
      { q: "What is the criterion for good signage?", options: ["Consistent typography","Sign visibility","Reaching a destination while thinking about something else","Minimal text"], answer: 2, explanation: "'able to reach their destination while thinking about something else'." },
      { q: "How do people primarily navigate?", options: ["By asking staff","By following others","By reading signs","By a rough model of the layout"], answer: 3, explanation: "'forms a rough model of its layout and navigates by that model'." },
      { q: "What does the quantity of signage measure?", options: ["How badly the building was planned","Budget","Visitor numbers","Building size"], answer: 0, explanation: "'a reasonably good measure of how badly it was planned'." },
      { q: "What is wrong with entrance directories?", options: ["They are too small", "A visitor cannot yet use the information", "They are expensive", "They date quickly"], answer: 1, explanation: "'where a visitor cannot yet use it'." },
      { q: "What does the absence of confirmation produce?", options: ["Requests for help","Complaints","Stopping, retracing and re-reading","Faster movement"], answer: 2, explanation: "'the characteristic behaviour of stopping, retracing and re-reading'." },
      { q: "How should the design be assessed?", options: ["By expert review","By counting signs","By consulting the drawing","By observing unfamiliar visitors"], answer: 3, explanation: "'a person unfamiliar with the building is asked to reach a location and is watched'." }
    ]
  },
  {
    id: "cpe-rmc17-05",
    title: "Counting What Cannot Be Counted",
    text: "Estimates of bird populations are produced annually, are reported as though they were counts, and rest on a body of statistical reasoning that the reporting almost never conveys. Nobody counts birds; what is counted is detections, and the relation between the two is where the work lies.\nThe fundamental difficulty is that detection is imperfect and unevenly so. A bird that sings is detected; the same species, silent outside its breeding season, is not. A species of open ground is detected at a distance; one of dense cover is detected when it is a few metres away. A count conducted by an experienced observer differs systematically from one conducted by a beginner, and both differ according to wind, hour and the observer's hearing, which declines with age in a manner that affects high-frequency species disproportionately.\nThe methods that address this estimate detection probability rather than assuming it. Repeated visits to the same site, distance sampling, and designs in which two observers record independently all permit the fraction missed to be estimated and the count corrected. The corrections are substantial, are larger for some species than for others, and are what turns a set of observations into an estimate that can be compared with another year's.\nThe volunteer basis of most such schemes is a strength and a complication. It supplies coverage no professional body could fund, and it introduces variation in skill that must be modelled rather than wished away; schemes that have run for decades have accumulated enough repeat observations to characterise individual observers, which is an unusual and valuable form of data.\nWhat the public discussion generally loses is that the trend is far more reliable than the level. The absolute number of a species is uncertain within wide bounds; the direction and rate of its change are known with much greater confidence, because the biases that afflict the estimate are largely constant across years and cancel in the comparison. A report stating that a population has fallen by half is on firm ground; the same report stating how many remain is offering a figure whose uncertainty it has not mentioned.",
    questions: [
      { q: "What is actually counted?", options: ["Detections","Nests","Territories","Birds"], answer: 0, explanation: "'what is counted is detections'." },
      { q: "How does habitat affect detection?", options: ["Habitat is irrelevant","Open-ground species are detected at a distance","Detection is unaffected","Dense cover improves detection"], answer: 1, explanation: "'A species of open ground is detected at a distance'." },
      { q: "Which observers are affected by declining hearing?", options: ["Professionals only","Beginners","Those recording high-frequency species","Volunteers only"], answer: 2, explanation: "'declines with age in a manner that affects high-frequency species disproportionately'." },
      { q: "What do the better methods do?", options: ["Increase visit numbers","Use recordings","Exclude beginners","Estimate detection probability"], answer: 3, explanation: "'estimate detection probability rather than assuming it'." },
      { q: "How is volunteer variation handled?", options: ["It must be modelled","Volunteers are trained identically","Data are discarded","It is ignored"], answer: 0, explanation: "'introduces variation in skill that must be modelled rather than wished away'." },
      { q: "Why is the trend more reliable than the level?", options: ["Trends are simpler", "Biases are largely constant and cancel", "Levels are not measured", "Trends use more data"], answer: 1, explanation: "'the biases that afflict the estimate are largely constant across years and cancel'." }
    ]
  },
  {
    id: "cpe-rmc17-06",
    title: "Drawing What Is No Longer There",
    text: "The reconstruction drawing is the most widely reproduced product of archaeology and the least examined. It shows a settlement as it appeared, populated and roofed and in use, and it is the image that lodges in the memory of anybody who visits a site where nothing above knee height survives.\nThe drawing is an argument presented in a form that does not permit disagreement. A text advancing the same claims would use qualifications — the roof was probably thatched, the enclosure may have been for stock — and each qualification would be visible as a claim that could be contested. A drawing cannot qualify. It must show a roof of some material at some pitch, and the viewer receives the illustrator's judgement as description, having no means of distinguishing the parts founded on excavated evidence from the parts required by the necessity of drawing something.\nThe difficulty is compounded by the distribution of the evidence. Post holes survive and textiles do not; hearths survive and the arrangement of people around them does not. The elements of the drawing that carry the most meaning for a viewer are precisely those for which the evidence is weakest, and the illustrator is obliged to invent them or to produce an image of an empty structure that nobody would reproduce.\nThe response that has emerged in the better practice is not to abandon the genre but to make its status legible. Multiple alternative reconstructions of the same structure, presented together, convey the range of what the evidence permits; drawings that render conjectural elements in a different weight distinguish the excavated from the supposed; and a caption stating what is known and what is proposed does most of the work at almost no cost.\nThese devices are used unevenly, and the reason is not obscure. A single confident image is more useful for the purposes of funding, publication and public interest than an honest presentation of uncertainty, and the institutions producing such drawings are subject to those purposes. The result is that the most widely circulated products of the discipline are the ones that least resemble what it actually knows.",
    questions: [
      { q: "Why is a drawing different from a text?", options: ["It reaches fewer people","It is more accurate","It cannot qualify its claims","It is cheaper"], answer: 2, explanation: "'A drawing cannot qualify.'" },
      { q: "What can the viewer not distinguish?", options: ["Old from new drawings","Materials","Scale from perspective","Evidence-based parts from necessary invention"], answer: 3, explanation: "'no means of distinguishing the parts founded on excavated evidence'." },
      { q: "What is true of the most meaningful elements?", options: ["The evidence for them is weakest","They are omitted","They are standardised","They are best evidenced"], answer: 0, explanation: "'precisely those for which the evidence is weakest'." },
      { q: "What does better practice do?", options: ["Abandon the genre", "Make the drawing's status legible", "Use photographs", "Reduce detail"], answer: 1, explanation: "'not to abandon the genre but to make its status legible'." },
      { q: "Which device does most work at least cost?", options: ["Three-dimensional models","Multiple reconstructions","A caption stating what is known and proposed","Different line weights"], answer: 2, explanation: "'a caption stating what is known and what is proposed does most of the work at almost no cost'." },
      { q: "Why are these devices used unevenly?", options: ["They are unpopular with illustrators","They are technically difficult","They are expensive","A confident image serves funding and publicity better"], answer: 3, explanation: "'more useful for the purposes of funding, publication and public interest'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
