/* CPE Prep bank: Reading True/False/Not Given (C2) — wave 8 */
(function () {
var TFNG = ["True", "False", "Not Given"];
var BANK = [
  {
    id: "cpe-rtfng8-01",
    title: "Holding Back the Lagoon",
    text: "Venice occupies a lagoon that has been managed continuously for more than a thousand years, and almost every feature of the water around the city is the result of an engineering decision taken at some point in that period.\nThe lagoon is a shallow body of water separated from the sea by a chain of barrier islands and connected to it by a small number of inlets. Left alone, such a system fills with sediment carried by rivers and becomes marsh, and the Venetian response over several centuries was to divert the rivers away from the lagoon entirely, in works of considerable scale that preserved the water body at the cost of altering the coastline elsewhere.\nThe city sits on a substrate of compressible sediment, and it has been sinking relative to the sea for as long as it has existed. The rate increased substantially in the twentieth century when industrial extraction of groundwater from beneath the lagoon accelerated the compaction; the extraction was stopped when the effect was recognised, and the subsidence slowed but did not reverse.\nFlooding occurs when a high tide coincides with a strong wind from the south-east, which drives water up the Adriatic and holds it against the coast, and with low atmospheric pressure, which raises sea level directly. The frequency of such events has risen sharply over the past century, and both subsidence and rising sea level contribute to the trend.\nThe engineering response is a system of barriers at the inlets that can be raised to close the lagoon during an event and lowered to lie on the sea bed at other times, so that the exchange of water on which the lagoon's ecology depends is not permanently interrupted. Construction took far longer and cost far more than the original estimates, and the barriers have now been raised on many occasions and have prevented flooding when raised.\nThe unresolved question concerns frequency of use. Each closure interrupts the tidal exchange, and a system operated increasingly often as sea level rises will alter conditions inside the lagoon in ways that are the subject of continuing study.",
    questions: [
      { q: "The lagoon connects to the sea through a small number of inlets.", options: TFNG, answer: 0, explanation: "True - stated directly in the second paragraph." },
      { q: "Rivers were diverted away from the lagoon.", options: TFNG, answer: 0, explanation: "True - 'the Venetian response... was to divert the rivers away from the lagoon entirely'." },
      { q: "Groundwater extraction reversed the subsidence.", options: TFNG, answer: 1, explanation: "False - extraction accelerated compaction; stopping it slowed subsidence but did not reverse it." },
      { q: "Flooding requires the coincidence of tide, wind and pressure conditions.", options: TFNG, answer: 0, explanation: "True - a high tide with a south-easterly wind and low pressure." },
      { q: "The frequency of flooding events has increased over the past century.", options: TFNG, answer: 0, explanation: "True - 'The frequency of such events has risen sharply'." },
      { q: "The barriers remain raised permanently once installed.", options: TFNG, answer: 1, explanation: "False - they are 'lowered to lie on the sea bed at other times'." },
      { q: "The barriers were completed within the original budget.", options: TFNG, answer: 1, explanation: "False - construction 'cost far more than the original estimates'." },
      { q: "Residents were consulted before the barrier scheme was approved.", options: TFNG, answer: 2, explanation: "Not Given - the text describes the scheme but says nothing about consultation." },
    ]
  },
  {
    id: "cpe-rtfng8-02",
    title: "A Measure Taken From the Earth",
    text: "The metric system was devised in the late eighteenth century with the explicit aim of producing units that did not depend on the authority of any ruler or the dimensions of any body, and the choices made reflect that aim more than they reflect convenience.\nThe metre was defined as one ten-millionth of the distance from the equator to the pole along a meridian, which required that distance to be measured. Two surveyors were dispatched to measure an arc between Dunkirk and Barcelona, a task that occupied them for several years and was conducted across a country in political upheaval, with both men detained at various points by authorities suspicious of anybody making measurements from high ground.\nThe resulting value contained an error, which was discovered later and which arises from an assumption about the shape of the earth rather than from carelessness in the survey. Because the definition had by then been embodied in a physical bar, the metre continued as that length: an artefact whose relationship to the planet was slightly different from the one intended.\nThe other units were derived from the metre by construction. The unit of mass was defined as the mass of a specified volume of water at a particular temperature, which tied it to the length unit, and the units of area and volume followed from powers of the length.\nAdoption was neither immediate nor universal. The system was abandoned domestically for a period and reintroduced, and its spread elsewhere occurred over more than a century, driven by trade, by scientific practice and in several cases by administrative reform following a change of government.\nThe definitions have since been rebuilt on physical constants. The metre is now defined by fixing the speed of light and the second is defined by a property of an atom, so that a laboratory anywhere can realise the units without reference to any object. The last artefact standard, a cylinder held under controlled conditions, was replaced in this way in 2019, which completed a programme begun with the intention of a system founded on nature.",
    questions: [
      { q: "The metric system was designed to avoid depending on any ruler's authority.", options: TFNG, answer: 0, explanation: "True - stated as the explicit aim in the opening paragraph." },
      { q: "The survey between Dunkirk and Barcelona was completed within a year.", options: TFNG, answer: 1, explanation: "False - it 'occupied them for several years'." },
      { q: "The surveyors were detained during their work.", options: TFNG, answer: 0, explanation: "True - 'both men detained at various points by authorities'." },
      { q: "The error in the metre's value arose from careless measurement.", options: TFNG, answer: 1, explanation: "False - it arises 'from an assumption about the shape of the earth rather than from carelessness'." },
      { q: "The unit of mass was tied to the unit of length.", options: TFNG, answer: 0, explanation: "True - defined as the mass of a specified volume of water." },
      { q: "The system was abandoned domestically for a period.", options: TFNG, answer: 0, explanation: "True - 'The system was abandoned domestically for a period and reintroduced'." },
      { q: "Most countries adopted the system within twenty years of its creation.", options: TFNG, answer: 1, explanation: "False - its spread 'occurred over more than a century'." },
      { q: "The replacement of the last artefact standard was opposed by several national laboratories.", options: TFNG, answer: 2, explanation: "Not Given - the text records the replacement but says nothing about opposition." },
    ]
  },
  {
    id: "cpe-rtfng8-03",
    title: "The Insect That Was a State Secret",
    text: "Silk is produced by the larva of a moth that has been bred in captivity for so long that it no longer exists in the wild: the adult cannot fly and the larva cannot feed itself without human attention, which makes it among the most thoroughly domesticated of all animals.\nThe production sequence is exacting. Larvae are fed continuously on the leaves of a particular tree, in conditions of controlled temperature and humidity, until they spin a cocoon of a single continuous filament that may be nearly a kilometre in length. To recover that filament unbroken, the cocoon must be treated before the adult emerges, since an emerging moth cuts through the wall and severs the thread. The cocoons are then softened in hot water and the filaments from several are reeled together, since a single one is too fine to use alone.\nThe technique was maintained as a monopoly for a very long period. Trade in finished silk extended across Asia and into the Mediterranean world for centuries before the method of production was known outside the region of origin, and export of the eggs or of the moths was prohibited on severe penalties.\nThe transfer eventually occurred, and the accounts of it are of uncertain reliability. One well-known story describes monks carrying eggs concealed in hollow staves to the eastern Mediterranean; whether or not the details are accurate, sericulture was established there by the sixth century and subsequently spread westwards across southern Europe.\nThe industry was vulnerable in a way that other textile production was not. An epidemic disease of the larvae devastated European sericulture in the nineteenth century, and the investigation into it established that the infection was transmitted from parent to offspring and could be eliminated by examining moths and destroying the eggs of any that were infected. That method saved the industry in the short term; the longer-term decline followed the arrival of manufactured fibres and of cheaper production elsewhere.",
    questions: [
      { q: "The silk moth can no longer survive without human care.", options: TFNG, answer: 0, explanation: "True - the adult cannot fly and the larva cannot feed itself without attention." },
      { q: "The cocoon is made from a single continuous filament.", options: TFNG, answer: 0, explanation: "True - 'a single continuous filament that may be nearly a kilometre in length'." },
      { q: "Cocoons are processed after the adult moth emerges.", options: TFNG, answer: 1, explanation: "False - they must be treated before emergence, since an emerging moth severs the thread." },
      { q: "A single filament is strong enough to be used on its own.", options: TFNG, answer: 1, explanation: "False - 'a single one is too fine to use alone'." },
      { q: "Finished silk was traded long before the production method was known abroad.", options: TFNG, answer: 0, explanation: "True - trade extended for centuries before the method was known outside the region of origin." },
      { q: "The story of monks carrying eggs in staves is fully corroborated.", options: TFNG, answer: 1, explanation: "False - the accounts are 'of uncertain reliability'." },
      { q: "The nineteenth-century disease was transmitted from parent to offspring.", options: TFNG, answer: 0, explanation: "True - the investigation established that transmission route." },
      { q: "The disease originated in imported stock from Asia.", options: TFNG, answer: 2, explanation: "Not Given - the text describes the epidemic and its remedy but not its origin." },
    ]
  },
  {
    id: "cpe-rtfng8-04",
    title: "Rebuilding After the Earthquake",
    text: "The earthquake that struck Lisbon in 1755 was followed by a tsunami and by fires that burned for several days, and the combination destroyed a large part of the city. The response is remembered less for the scale of the destruction than for what the administration did next.\nWithin weeks a survey of the damage was under way and a set of questions was circulated to parishes throughout the country, asking how long the shaking lasted, in which direction it appeared to travel, whether wells rose or fell, and how animals behaved beforehand. The answers, preserved in the archives, constitute one of the earliest attempts to gather systematic data about an earthquake across a wide area, and they allow modern researchers to estimate the intensity of the shaking at many locations.\nThe rebuilding was directed rather than left to owners. A new street plan was imposed on the destroyed district, with wider streets on a grid, standardised building heights and a uniform facade, and the resulting quarter was constructed to a single design in a period of a few decades.\nThe most consequential feature was structural. Buildings were required to incorporate a timber frame within the masonry, designed so that the wooden lattice would hold the structure together if the masonry cracked, and models of this arrangement were tested by having troops march around them to simulate ground motion. It is among the earliest examples of a building code adopted explicitly to resist earthquakes.\nThe intellectual consequences extended beyond construction. The disaster occurred on a religious holiday, destroyed churches while leaving other districts standing, and prompted an extended argument among European writers about whether such an event could be reconciled with a benevolent order. That argument is generally described as a turning point in the treatment of natural disaster as a subject for investigation rather than interpretation.",
    questions: [
      { q: "The destruction was caused by the earthquake alone.", options: TFNG, answer: 1, explanation: "False - a tsunami and fires followed and the combination destroyed much of the city." },
      { q: "A questionnaire was circulated to parishes around the country.", options: TFNG, answer: 0, explanation: "True - a set of questions was circulated asking about the shaking and its effects." },
      { q: "The responses allow modern estimation of shaking intensity.", options: TFNG, answer: 0, explanation: "True - they 'allow modern researchers to estimate the intensity of the shaking'." },
      { q: "Owners were left to rebuild as they wished.", options: TFNG, answer: 1, explanation: "False - 'The rebuilding was directed rather than left to owners.'" },
      { q: "Buildings were required to include a timber frame within the masonry.", options: TFNG, answer: 0, explanation: "True - stated directly in the text." },
      { q: "Models were tested using marching troops.", options: TFNG, answer: 0, explanation: "True - troops marched around them to simulate ground motion." },
      { q: "The new district was completed within five years.", options: TFNG, answer: 1, explanation: "False - it was constructed 'in a period of a few decades'." },
      { q: "The rebuilding was financed by a special tax on colonial trade.", options: TFNG, answer: 2, explanation: "Not Given - the text does not describe how the work was financed." },
    ]
  },
  {
    id: "cpe-rtfng8-05",
    title: "Life Without Sunlight",
    text: "In 1977 a research submersible examining a volcanic ridge in the eastern Pacific encountered warm water issuing from the sea floor and, around it, an assemblage of animals that nobody had predicted and that included species unknown to science.\nThe expedition was designed to study geology rather than biology, and no biologist was aboard. Specimens were preserved in whatever was available, and the accounts of the discovery record a certain improvisation, since the equipment carried was intended for rock samples.\nThe significance of the find became clear when the source of energy was identified. The animals at these vents do not depend on sunlight, even indirectly. Bacteria in the water and within the tissues of some of the animals oxidise chemicals dissolved in the vent fluid, chiefly hydrogen sulphide, and use the energy released to build organic material, which supports everything else in the community.\nSome of the animals concerned have no digestive system at all. A large tube worm found at these sites absorbs dissolved compounds through a plume of tissue and passes them to bacteria housed within its own body, which supply it in return; the worm is, in effect, an arrangement for keeping the bacteria supplied with what they need.\nThe vents themselves are short-lived on geological timescales. A given site may be active for a few decades and then cease, which raises the question of how the animals reach new sites, and the current understanding involves larvae carried in ocean currents, with settlement depending on chance encounter.\nThe discovery altered several fields at once. It extended the range of conditions in which life is known to persist, it supplied a plausible model for how life might exist elsewhere in the solar system beneath ice, and it introduced a commercial question, since the mineral deposits formed by these systems are of a grade that has attracted the attention of mining interests.",
    questions: [
      { q: "A biologist was present on the expedition that made the discovery.", options: TFNG, answer: 1, explanation: "False - 'no biologist was aboard'." },
      { q: "The expedition was originally designed to study geology.", options: TFNG, answer: 0, explanation: "True - stated directly in the second paragraph." },
      { q: "The vent communities depend indirectly on sunlight.", options: TFNG, answer: 1, explanation: "False - they 'do not depend on sunlight, even indirectly'." },
      { q: "Bacteria at the vents use hydrogen sulphide as an energy source.", options: TFNG, answer: 0, explanation: "True - they oxidise chemicals dissolved in the vent fluid, chiefly hydrogen sulphide." },
      { q: "The large tube worm lacks a digestive system.", options: TFNG, answer: 0, explanation: "True - some animals have no digestive system, and the worm relies on internal bacteria." },
      { q: "Vent sites remain active for many thousands of years.", options: TFNG, answer: 1, explanation: "False - a site 'may be active for a few decades and then cease'." },
      { q: "Larvae are thought to reach new sites by ocean currents.", options: TFNG, answer: 0, explanation: "True - the current understanding involves larvae carried in ocean currents." },
      { q: "Mining of vent deposits has already begun commercially.", options: TFNG, answer: 2, explanation: "Not Given - the text says the deposits have attracted attention, not that mining has started." },
    ]
  },
  {
    id: "cpe-rtfng8-06",
    title: "Meat That Could Cross an Ocean",
    text: "Until the late nineteenth century, meat was consumed within a short distance of where the animal was killed, or was preserved by salting, drying or smoking, all of which alter it substantially. The change that ended this was mechanical refrigeration, and its commercial consequences were felt on the other side of the world from where the meat was eaten.\nThe principle had been demonstrated decades earlier: a compressed gas, allowed to expand, cools, and a machine can move heat from a cold space to a warmer one. Making the principle into a plant that would operate unattended for six weeks on a moving ship was a different problem, and the early attempts failed for reasons that were mechanical rather than thermodynamic.\nThe first successful long-distance cargoes were carried in the eighteen-seventies and eighteen-eighties, from South America and from Australasia to Europe. The economic effect was immediate. Land in the exporting countries that had been used for wool or tallow acquired a new value, breeds were changed to suit a distant market, and the price of meat in the importing countries fell.\nThe consequences for producers nearer the consuming markets were severe, and the arrival of frozen imports coincided with a prolonged agricultural depression in parts of Europe, to which it contributed. Whether it was the principal cause is disputed, since cheap grain arriving by rail and steamship from other continents was affecting the same farmers at the same time.\nThe technology also altered what was eaten rather than merely where it came from. A trade in frozen carcasses rewards the cuts that travel well and standardises what is available, and the meat that arrived was leaner and younger than what local production had supplied. Refrigeration subsequently moved into the retail and domestic spheres, where its effects on shopping frequency, household organisation and the composition of diets were larger still, and are rarely attributed to a machine.",
    questions: [
      { q: "Before refrigeration, meat was preserved by methods that changed it substantially.", options: TFNG, answer: 0, explanation: "True - salting, drying and smoking 'alter it substantially'." },
      { q: "The cooling principle was discovered at the same time as the first shipments.", options: TFNG, answer: 1, explanation: "False - the principle 'had been demonstrated decades earlier'." },
      { q: "Early attempts at shipboard refrigeration failed for mechanical reasons.", options: TFNG, answer: 0, explanation: "True - the failures were 'mechanical rather than thermodynamic'." },
      { q: "Land use in exporting countries changed as a result of the trade.", options: TFNG, answer: 0, explanation: "True - land used for wool or tallow acquired a new value." },
      { q: "Frozen imports were the undisputed principal cause of the agricultural depression.", options: TFNG, answer: 1, explanation: "False - whether it was the principal cause 'is disputed'." },
      { q: "Cheap imported grain was affecting European farmers in the same period.", options: TFNG, answer: 0, explanation: "True - cheap grain 'was affecting the same farmers at the same time'." },
      { q: "The imported meat was leaner than locally produced meat.", options: TFNG, answer: 0, explanation: "True - it 'was leaner and younger than what local production had supplied'." },
      { q: "Domestic refrigerators were widely owned before the First World War.", options: TFNG, answer: 2, explanation: "Not Given - the text says refrigeration later moved into domestic use but gives no dates." },
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
