/* CPE Prep bank: Reading multiple choice (C2) — wave 11 */
(function () {
var BANK = [
  {
    id: "cpe-rmc11-01",
    title: "The Price of Being Reachable",
    text: "The obligation to be reachable is discussed almost exclusively in terms of hours, and the accounting in hours understates it substantially. The relevant quantity is not the time spent responding but the effect of the expectation on the time that remains, and the effect is disproportionate for reasons that have to do with the structure of demanding work rather than with anybody's tolerance for interruption.\nWork that requires holding several elements in mind simultaneously has a cost of entry. The state is reached gradually, is lost instantly, and cannot be resumed from where it was abandoned; what follows an interruption is not the continuation of the previous thought but a reconstruction of it, and the reconstruction takes time that does not appear in any record. An hour containing two interruptions is therefore not fifty minutes of work.\nThe second and less obvious effect operates in the absence of any interruption at all. A person who might be contacted behaves differently from one who will not be, choosing tasks that tolerate suspension and avoiding those that do not, and the avoidance is rarely conscious. Over a period the composition of the work changes: the tractable and interruptible expands and the demanding contracts, and nobody has decided this.\nWhat makes the problem difficult is that availability is genuinely valuable. An organisation in which nobody can be reached is one in which decisions wait, errors persist and the people who need an answer improvise, and the costs of that are also real and are more visible than the costs described above, which is why they win.\nThe arrangements that work are structural rather than personal, because a norm defended by individuals is defended unevenly and the people least able to defend it are those with least standing. Published windows during which a person is not available, an explicit and short list of what constitutes an emergency, and a shared understanding that a message is not a summons: none of these is difficult to state, and all of them fail unless somebody senior is seen to observe them, which is the whole of the implementation problem.",
    questions: [
      { q: "What does accounting in hours understate?", options: ["The effect of the expectation on remaining time","The cost of technology","The volume of work","The number of messages"], answer: 0, explanation: "'the effect of the expectation on the time that remains'." },
      { q: "Why is an interrupted state costly to resume?", options: ["It depends on written notes","It requires reconstruction rather than continuation","It cannot be recovered at all","It requires a colleague's help"], answer: 1, explanation: "'not the continuation of the previous thought but a reconstruction of it'." },
      { q: "What is the second, less obvious effect?", options: ["Increased delegation","Reduced message volume","Task selection shifts towards interruptible work","Longer working hours"], answer: 2, explanation: "'choosing tasks that tolerate suspension and avoiding those that do not'." },
      { q: "Why do the costs of unavailability tend to win?", options: ["They are measured formally","They affect senior staff","They are larger","They are more visible"], answer: 3, explanation: "'are more visible than the costs described above, which is why they win'." },
      { q: "Why must arrangements be structural?", options: ["Individual norms are defended unevenly", "Rules are legally required", "Technology enforces them", "Managers prefer them"], answer: 0, explanation: "'a norm defended by individuals is defended unevenly'." },
      { q: "What does implementation ultimately depend on?", options: ["Software settings", "Someone senior being seen to observe the norms", "Written policy", "Team size"], answer: 1, explanation: "'all of them fail unless somebody senior is seen to observe them'." }
    ]
  },
  {
    id: "cpe-rmc11-02",
    title: "Rules Nobody Can Actually Follow",
    text: "Every complex operation accumulates a body of written procedure that cannot be complied with in full, and the accumulation is not the result of carelessness. Each provision was added in response to something that went wrong, was reasonable at the moment of its addition, and was never assessed against the total burden of the provisions already present, because no mechanism exists for conducting that assessment and nobody is responsible for it.\nThe consequence is a documented standard that exceeds the available time, and a workforce that has developed, informally, a hierarchy of which provisions are observed and which are not. This hierarchy is generally sound: it reflects accumulated judgement about which steps prevent harm, and operations run on it rather than on the written version. It is also entirely undocumented, is transmitted by demonstration, and disappears when experienced staff leave.\nThe arrangement is stable until something goes wrong, at which point the written standard becomes the measure. An investigation establishes that a procedure was not followed, which is true, and the finding is recorded as the cause, which it generally is not, since the procedure in question was not being followed by anybody at any time and the operation had run for years without incident. The remedy issued is a further provision, and the burden increases.\nWhat makes this difficult to correct is that the correction requires somebody to state, in writing, that a rule may be disregarded, and no individual is willing to sign that. The asymmetry is complete: a person who removes a provision and is subsequently associated with a failure has ended their career, and one who adds a provision that consumes time indefinitely bears no cost that can be traced to them.\nThe organisations that have addressed this have done so by requiring that provisions expire unless renewed, and by conducting the periodic exercise of timing the full documented procedure against the shift in which it must be performed. Where the first number exceeds the second, something is untrue, and the value of the exercise is that it forces the untruth to be located and named rather than absorbed silently by the people doing the work.",
    questions: [
      { q: "Why does procedure accumulate?", options: ["Because staff request it","Through carelessness","Each provision answers a past failure without total assessment","Because regulators demand it"], answer: 2, explanation: "'was never assessed against the total burden of the provisions already present'." },
      { q: "What does the informal hierarchy reflect?", options: ["Management instruction","Legal advice","Personal preference","Accumulated judgement about which steps prevent harm"], answer: 3, explanation: "'it reflects accumulated judgement about which steps prevent harm'." },
      { q: "What is the weakness of that hierarchy?", options: ["It is undocumented and lost when staff leave", "It is unsafe", "It is too rigid", "It is written down incorrectly"], answer: 0, explanation: "'is transmitted by demonstration, and disappears when experienced staff leave'." },
      { q: "What happens after an incident?", options: ["The procedure is simplified", "A further provision is added", "The hierarchy is documented", "Staff are retrained"], answer: 1, explanation: "'The remedy issued is a further provision, and the burden increases.'" },
      { q: "What asymmetry prevents correction?", options: ["Regulations forbid removal","Records are incomplete","Removing a rule is career-ending; adding one is costless","Junior staff cannot propose changes"], answer: 2, explanation: "'has ended their career, and one who adds a provision that consumes time indefinitely bears no cost'." },
      { q: "What exercise do successful organisations conduct?", options: ["External audits","Rewriting all manuals","Annual staff surveys","Timing the full procedure against the available shift"], answer: 3, explanation: "'timing the full documented procedure against the shift in which it must be performed'." }
    ]
  },
  {
    id: "cpe-rmc11-03",
    title: "How to Read a Building",
    text: "A building is a record of the decisions taken during its construction and of every decision taken since, and it is legible to anybody prepared to look at it as a document rather than as a backdrop. What is recorded is not principally aesthetic intention, which is the aspect most often discussed, but the distribution of resources, authority and expectation at the moment the structure was raised.\nThe simplest reading concerns effort. Materials are not distributed evenly across a structure: the expensive treatment appears where it will be seen by those whose opinion mattered, and the plain treatment appears elsewhere, and the boundary between them marks the edge of the intended audience. A façade of dressed stone with brick flanks does not indicate a shortage of stone; it indicates a judgement about who would be looking and from where.\nThe second reading concerns circulation, which encodes assumptions about who was expected to encounter whom. Separate stairs, service corridors and entrances of different grandeur are the physical form of a social arrangement, and they persist long after the arrangement has gone, which is why so many institutions operate in buildings whose logic contradicts their stated intentions and why the contradiction is felt without being articulated.\nThe third and most informative reading concerns alteration. A blocked opening, a floor inserted into a room of double height, a staircase that arrives at a wall: each is a moment at which a requirement overrode the original design, and the crudeness of the alteration is a fair measure of the urgency. Buildings that have been continuously useful are heavily altered, and buildings preserved in their original state have generally survived because nobody needed them.\nWhat this offers is not expertise but a habit of attention, and the habit is worth acquiring for a reason beyond curiosity: a person who can read a building is harder to persuade by one. Architecture makes claims about permanence, authority and inevitability, and those claims are considerably less impressive to somebody who can see where the money ran out.",
    questions: [
      { q: "What does a building principally record?", options: ["The distribution of resources, authority and expectation","The architect's reputation","Local building codes","Aesthetic intention"], answer: 0, explanation: "'the distribution of resources, authority and expectation'." },
      { q: "What does a stone façade with brick flanks indicate?", options: ["A shortage of stone", "A judgement about who would be looking", "Poor construction", "A later alteration"], answer: 1, explanation: "'it indicates a judgement about who would be looking and from where'." },
      { q: "What does circulation encode?", options: ["Heating requirements","Fire safety rules","Assumptions about who would encounter whom","Structural loads"], answer: 2, explanation: "'encodes assumptions about who was expected to encounter whom'." },
      { q: "Why do institutions feel contradictions in their buildings?", options: ["The buildings are too old","Maintenance is poor","Staff are unfamiliar with them","The logic persists after the arrangement has gone"], answer: 3, explanation: "'they persist long after the arrangement has gone'." },
      { q: "What does the crudeness of an alteration measure?", options: ["The urgency of the requirement","The skill of the builder","The age of the building","The cost"], answer: 0, explanation: "'the crudeness of the alteration is a fair measure of the urgency'." },
      { q: "Why are unaltered buildings often preserved?", options: ["They were well built", "Nobody needed them", "They were protected by law", "They were expensive"], answer: 1, explanation: "'have generally survived because nobody needed them'." }
    ]
  },
  {
    id: "cpe-rmc11-04",
    title: "What a Review Is Actually For",
    text: "The review is discussed as though its function were to advise a reader whether to acquire something, and the discussion has never accounted for the observable fact that a great many reviews are read after the decision, or about works the reader has no intention of encountering, or of works that cannot be acquired at all.\nA more accurate description is that a review supplies a vocabulary. A reader who has encountered a work possesses a set of impressions that are not yet articulated, and the review offers terms in which they might be, and the pleasure of agreement or disagreement is the pleasure of finding one's own response either confirmed or usefully opposed. This is a service and it is not the advisory one.\nA second function is the placement of a work within a field. A review that establishes what a thing resembles, what it departs from and what it is attempting communicates something a reader cannot obtain from the work in isolation, and this is why reviews of works one will never encounter remain worth reading: they are, in effect, brief essays on a field, using a new arrival as their occasion.\nThe advisory function, where it survives, has been substantially displaced by aggregate ratings, and the displacement is instructive. An aggregate answers the question of whether most people liked something, which is a different and less useful question than whether this reader will, and the second cannot be answered by any number but can sometimes be answered by a reviewer whose responses one has learnt to calibrate. The value of a critic, on this account, lies in consistency rather than authority: a reviewer who is reliably wrong for a particular reader is more useful than one who is unpredictably right.\nWhat follows is that the standard complaint about reviews — that they contain too much of the reviewer — misidentifies the product. A review purged of its author would be a description, and descriptions are already available from those who wish to sell the thing. The reviewer's presence is not an intrusion upon the information; in the account offered here it is the information.",
    questions: [
      { q: "What fact does the advisory account fail to explain?", options: ["That reviewers disagree","That reviews are unpaid","That reviews are often read after the decision","That reviews are long"], answer: 2, explanation: "'a great many reviews are read after the decision'." },
      { q: "What does the writer say a review supplies?", options: ["A summary","A recommendation","A rating","A vocabulary"], answer: 3, explanation: "'a review supplies a vocabulary'." },
      { q: "Why are reviews of unencountered works worth reading?", options: ["They are brief essays on a field","They are entertaining","They are shorter","They save money"], answer: 0, explanation: "'they are, in effect, brief essays on a field'." },
      { q: "What is wrong with aggregate ratings?", options: ["They are inaccurate", "They answer whether most people liked something", "They are manipulated", "They are outdated"], answer: 1, explanation: "'An aggregate answers the question of whether most people liked something'." },
      { q: "Where does a critic's value lie?", options: ["In independence","In authority","In consistency","In expertise"], answer: 2, explanation: "'lies in consistency rather than authority'." },
      { q: "How does the writer answer the standard complaint?", options: ["Reviews should be shorter","Reviewers should be anonymous","Descriptions are preferable","The reviewer's presence is the information"], answer: 3, explanation: "'it is the information'." }
    ]
  },
  {
    id: "cpe-rmc11-05",
    title: "Where the Checklist Stops Working",
    text: "The checklist has been among the most successful interventions of recent decades in fields where error is costly, and its success has produced the customary consequence, which is adoption in circumstances that do not resemble the ones in which it was demonstrated.\nThe conditions under which a checklist works are specific and are stated clearly in the original literature. The task must be one whose steps are known in advance, whose omissions are consequential, and whose performance is routine enough that attention lapses. A checklist addresses forgetting; it does not address not knowing, and the two failures look similar from outside and are entirely different.\nWhere the conditions do not hold, the instrument does harm rather than nothing, which is the point most often missed. A checklist applied to a task requiring judgement converts an open question into a closed one, and the person completing it has performed a defensible act rather than a considered one. Worse, the completed document becomes the record: it establishes that the steps were taken, and it is silent on whether the situation was one the steps were designed for.\nThe secondary failure is dilution. A list containing the three items that matter is read; a list containing forty items, added over time by people protecting themselves, is completed rather than read, and completion becomes a motor task performed while thinking about something else. The instrument then measures compliance and nothing else, and it does so while carrying the reputation earned by the version that worked.\nThe practical corollaries are unwelcome in institutions, since they involve subtraction. A checklist should be short enough to be read; it should be tested by observing whether people actually use it rather than by asking them; and it should contain a provision, actually used, for recording that a step was consciously omitted and why. That last item is the one that distinguishes an instrument for supporting judgement from an instrument for replacing it, and it is the item that is almost always removed.",
    questions: [
      { q: "What consequence has the checklist's success produced?", options: ["Adoption in unsuitable circumstances", "Widespread rejection", "Regulatory bans", "Higher costs"], answer: 0, explanation: "'adoption in circumstances that do not resemble the ones in which it was demonstrated'." },
      { q: "What failure does a checklist address?", options: ["Not knowing", "Forgetting", "Inexperience", "Fatigue"], answer: 1, explanation: "'A checklist addresses forgetting; it does not address not knowing'." },
      { q: "What happens when a checklist is applied to a judgement task?", options: ["It improves accuracy","It has no effect","It converts an open question into a closed one","It slows the work"], answer: 2, explanation: "'converts an open question into a closed one'." },
      { q: "Why is the completed document a problem?", options: ["It is rarely kept","It is hard to read","It is confidential","It is silent on whether the situation fitted the steps"], answer: 3, explanation: "'it is silent on whether the situation was one the steps were designed for'." },
      { q: "What causes dilution?", options: ["Items added over time by people protecting themselves","Digital formats","Staff turnover","Poor training"], answer: 0, explanation: "'added over time by people protecting themselves'." },
      { q: "Which provision is almost always removed?", options: ["The date field", "Recording a consciously omitted step and why", "The signature line", "The item count"], answer: 1, explanation: "'for recording that a step was consciously omitted and why'." }
    ]
  },
  {
    id: "cpe-rmc11-06",
    title: "The Absent Party",
    text: "Most decisions of consequence are taken in the absence of somebody they will affect, and the absence is rarely deliberate. It arises because the affected party is numerous, or unorganised, or not yet identifiable, or has no standing to be present, and because the meeting has to end. The question is what a body can reasonably do about a difficulty that cannot be removed.\nThe response that is usually adopted is representation: somebody in the room undertakes to speak for those outside it. This is better than nothing and its limits are well understood by anybody who has attempted it. A representative reports what they believe the absent party would say, and the belief is formed from their own model of that party, which is generally a model of a reasonable person resembling themselves. The objections that are voiced are therefore the anticipatable ones, and the anticipatable objections are precisely the ones that would have been addressed anyway.\nA more effective device is procedural rather than personal, and consists in requiring that a proposal state what it assumes about the absent party and that the assumption be recorded as a claim capable of being false. A proposal resting on the assumption that users will read a notice is a different document from one resting on the assumption that they will not, and the second is rarely written because the first has never been stated aloud.\nThe strongest available device is delay of a particular kind: circulating a decision in draft to somebody who will be affected and who has no reason to be polite, and doing so early enough that the response can alter the outcome rather than merely be noted. The cost is a few days and the objection is always that there is no time, which is true in a sense that deserves examination, since the same bodies will subsequently spend months on remediation that the few days would have prevented.\nNone of this makes the absent party present. What it does is make their absence visible in the record, and a decision that records what it assumed about the people it would affect is one that can be revisited when the assumption turns out to have been wrong, which is a lower standard than fairness and is achievable.",
    questions: [
      { q: "Why is the absent party usually absent?", options: ["Meetings are secret","Deliberate exclusion","They are numerous, unorganised or without standing","They decline to attend"], answer: 2, explanation: "'because the affected party is numerous, or unorganised, or not yet identifiable, or has no standing'." },
      { q: "What limits representation?", options: ["It takes too long","It is legally restricted","Representatives are unqualified","The model used resembles the representative"], answer: 3, explanation: "'a model of a reasonable person resembling themselves'." },
      { q: "Why are voiced objections of limited use?", options: ["They are the ones that would have been addressed anyway","They arrive too late","They are too numerous","They are ignored"], answer: 0, explanation: "'the anticipatable objections are precisely the ones that would have been addressed anyway'." },
      { q: "What does the procedural device require?", options: ["An extra meeting", "Stating assumptions about the absent party as falsifiable claims", "A vote", "Legal review"], answer: 1, explanation: "'the assumption be recorded as a claim capable of being false'." },
      { q: "What makes the strongest device work?", options: ["Appointing more representatives","Extending the meeting","Circulating early to somebody with no reason to be polite","Publishing the decision"], answer: 2, explanation: "'somebody who will be affected and who has no reason to be polite'." },
      { q: "What does the writer claim these devices achieve?", options: ["Full participation","Faster decisions","Fairness","Making the absence visible in the record"], answer: 3, explanation: "'make their absence visible in the record'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
