/* CPE Prep bank: Reading multiple choice (C2) — wave 10 */
(function () {
var BANK = [
  {
    id: "cpe-rmc10-01",
    title: "The Composite Example",
    text: "A writer who wishes to illustrate a pattern faces an awkward choice. The individual case that exhibits every feature of the pattern generally does not exist, and the cases that do exist each exhibit some of them, which produces either a paragraph of qualifications or a composite: an example assembled from several instances and presented as one.\nThe practice is defended on grounds of clarity and of protection, and both defences have force. A composite conveys the shape of a phenomenon more economically than four partial cases, and it removes the possibility that an individual will be identified from a description that was intended to illustrate rather than to expose.\nThe objection is not that the composite is untrue but that its truth is of a different kind, and that the reader is not told which kind they are receiving. A described case carries an implicit claim that the events occurred in the relation described, and a composite carries no such claim; it asserts that this configuration is representative, which is a considerably stronger claim about the world and a considerably weaker one about any particular person.\nThe consequences appear when a composite is treated as evidence, which it will be. A reader encountering a vivid case in a professional text will recall it as an instance, will cite it as an instance, and will reason from it as though such a person existed. Where the composite was assembled to illustrate a well-established pattern this may be harmless; where it was assembled to illustrate a pattern the author believed in, it functions as fabricated corroboration for a proposition that has not been demonstrated.\nThe remedy is a sentence and it is omitted with remarkable consistency. Stating that a case is composite, and describing briefly what it was assembled from, permits a reader to give it the weight it deserves, which is not nothing and is not the weight of a documented instance. Its omission is rarely dishonest and is almost always convenient, which is a combination that ought to make anybody uneasy.",
    questions: [
      { q: "Why do writers use composite examples?", options: ["Because individual cases showing every feature rarely exist", "To reduce the length of a text", "Because editors require them", "To avoid research"], answer: 0, explanation: "'The individual case that exhibits every feature of the pattern generally does not exist'." },
      { q: "What defences does the writer acknowledge?", options: ["Legal requirement","Clarity and protection of identity","Cost and speed","Tradition and convention"], answer: 1, explanation: "'defended on grounds of clarity and of protection'." },
      { q: "What is the writer's objection?", options: ["That they are unpopular","That composites are untrue","That their kind of truth is not disclosed","That they are difficult to construct"], answer: 2, explanation: "'the reader is not told which kind they are receiving'." },
      { q: "What claim does a composite actually make?", options: ["That the person consented","That the source is reliable","That events occurred as described","That the configuration is representative"], answer: 3, explanation: "'it asserts that this configuration is representative'." },
      { q: "When does the practice become most damaging?", options: ["When it corroborates an undemonstrated proposition","When it is very detailed","When it is short","When it illustrates an established pattern"], answer: 0, explanation: "'fabricated corroboration for a proposition that has not been demonstrated'." },
      { q: "How does the writer characterise the omission of disclosure?", options: ["As usually dishonest", "As rarely dishonest and almost always convenient", "As legally actionable", "As unavoidable"], answer: 1, explanation: "'rarely dishonest and is almost always convenient'." }
    ]
  },
  {
    id: "cpe-rmc10-02",
    title: "On Quoting Somebody",
    text: "A quotation appears to be the most transparent of devices: the words are the speaker's own, and the writer has merely conveyed them. In practice a quotation is the product of at least four decisions, none of which is visible in the result, and each of which can alter what a reader takes the speaker to have meant.\nThe first is selection. A speaker produces a quantity of material and a quotation is a fragment of it, and the fragment has been chosen by somebody with a purpose. This is unavoidable and it is not neutral, and the honest practice is to indicate what the surrounding material was about rather than to present a sentence as though it had been the speaker's whole contribution.\nThe second is the boundary. A sentence beginning after a qualification has been made says something different from the sentence including it, and the ellipsis conventionally marks removal within a quotation and does not mark what was removed from either end. A reader has no means of detecting a quotation that begins one clause too late.\nThe third is context of occasion. A remark made in a discussion, in response to a question, at the end of a long day, is not a considered position, and its presentation in a text confers a formality it did not have. Speakers who complain of being misquoted have frequently been quoted accurately and framed as having made a statement when they were thinking aloud, which is a distinction that the printed form cannot easily preserve.\nThe fourth concerns tone, which written quotation cannot carry at all. Irony, hesitation, the raised eyebrow that indicated that a sentence was being offered for consideration rather than asserted: none of it survives, and the same words appear on the page as a flat declaration.\nWhat follows is not that quotation is illegitimate but that the appearance of transparency is misleading, and that a writer who has quoted somebody has made four decisions on that person's behalf. The corresponding obligation is modest: to show the quotation to the speaker where circumstances permit, and to accept that a person who says they did not mean that is reporting something the transcript cannot contain.",
    questions: [
      { q: "How many decisions does the writer say a quotation involves?", options: ["Six","Two","At least four","One"], answer: 2, explanation: "'the product of at least four decisions'." },
      { q: "What is the honest practice regarding selection?", options: ["Avoiding quotation","Using indirect speech","Quoting at greater length","Indicating what the surrounding material was about"], answer: 3, explanation: "'to indicate what the surrounding material was about'." },
      { q: "What can a reader not detect?", options: ["A quotation beginning one clause too late", "An inaccurate transcription", "A missing source", "An altered word"], answer: 0, explanation: "'A reader has no means of detecting a quotation that begins one clause too late.'" },
      { q: "Why do speakers complain of misquotation?", options: ["Words are usually changed", "Thinking aloud is framed as a statement", "Sources are not credited", "Quotations are too long"], answer: 1, explanation: "'framed as having made a statement when they were thinking aloud'." },
      { q: "What does written quotation fail to carry?", options: ["Length","Vocabulary","Tone","Grammar"], answer: 2, explanation: "'The fourth concerns tone, which written quotation cannot carry at all.'" },
      { q: "What obligation does the writer propose?", options: ["Recording all conversations","Publishing full transcripts","Avoiding direct speech","Showing the quotation to the speaker where possible"], answer: 3, explanation: "'to show the quotation to the speaker where circumstances permit'." }
    ]
  },
  {
    id: "cpe-rmc10-03",
    title: "The Argument From What Was Done Before",
    text: "Reasoning from precedent is treated with suspicion outside the legal systems that formalise it, and the suspicion is misplaced in a specific way. The objection usually offered — that a thing having been done before is no argument for doing it again — is correct as stated and misses what the practice is for.\nA precedent does not establish that a course is right. It establishes that a course was taken, by people facing a comparable situation, who had reasons that were adequate at the time and that are recoverable. This is information, and it is information of a kind that is otherwise extremely expensive to obtain, since the alternative is to reason from first principles about a situation whose relevant features one has not yet identified.\nThe value depends entirely on the recoverability of the reasoning. A precedent recorded as an outcome — this was permitted, that was refused — is close to useless and is what most institutional records contain, since the decision was minuted and the deliberation was not. A precedent recorded with its reasoning permits the essential operation, which is to determine whether the reasons that applied then apply now, and to depart from the precedent where they do not.\nThis is why the objection to precedent is frequently an objection to bad record-keeping. An organisation whose files show what was decided and not why is one in which every decision must either be repeated blindly or made from nothing, and both of those are more expensive than the alternative and produce worse outcomes.\nThere remains a genuine danger, which is that a precedent acquires authority in proportion to its age rather than to its reasoning, and that a practice established for reasons that have entirely lapsed continues because nobody can now identify what they were. The corrective is not to abandon precedent but to require, of any invocation of one, a statement of the reasons it rested on, with the consequence that a precedent whose reasons cannot be produced ceases to be an argument and becomes what it always was, which is a description of what somebody once did.",
    questions: [
      { q: "What does the writer say the usual objection misses?", options: ["What the practice is for","The age of precedents","The cost of records","The legal context"], answer: 0, explanation: "'misses what the practice is for'." },
      { q: "What does a precedent establish?", options: ["That a course is right", "That a course was taken for recoverable reasons", "That circumstances are identical", "That an outcome was successful"], answer: 1, explanation: "'It establishes that a course was taken... who had reasons that were adequate at the time'." },
      { q: "What determines a precedent's value?", options: ["How often it is cited","Its age","Whether the reasoning is recoverable","Who made the decision"], answer: 2, explanation: "'The value depends entirely on the recoverability of the reasoning.'" },
      { q: "What do most institutional records contain?", options: ["Full deliberations","Nothing at all","Reasoning without outcomes","Outcomes without reasoning"], answer: 3, explanation: "'the decision was minuted and the deliberation was not'." },
      { q: "How does the writer reframe the objection to precedent?", options: ["As an objection to poor record-keeping", "As a legal argument", "As a matter of style", "As unavoidable"], answer: 0, explanation: "'the objection to precedent is frequently an objection to bad record-keeping'." },
      { q: "What corrective does the writer propose?", options: ["Abandoning precedent", "Requiring the reasons to be stated", "Limiting precedents by age", "Recording all meetings"], answer: 1, explanation: "'to require, of any invocation of one, a statement of the reasons it rested on'." }
    ]
  },
  {
    id: "cpe-rmc10-04",
    title: "The Books One Has Not Read",
    text: "A private library is conventionally understood as a record of what its owner has read, and the understanding produces the mild embarrassment that attends the unread volume. The embarrassment is misplaced, and the misplacement rests on a mistake about what a collection of books is doing.\nA library is an instrument rather than a monument, and its unread portion is the part that is doing the work. A book that has been read has been absorbed, its contents are, to whatever degree, already available, and the volume itself functions largely as an aide-memoire. A book that has not been read is a resource whose contents remain unknown and which is therefore available to answer a question its owner has not yet formulated.\nThe practical version of this is familiar to anybody who works with texts. The useful library is not the one containing what one has needed but the one containing what one will need, and the second cannot be assembled at the moment of need because the moment of need is characterised by not knowing what would help. A collection acquired according to a rule of vague interest, over decades, produces a hit rate that no targeted acquisition can match.\nThe objection, that one might simply consult a public collection, understates a difference that is difficult to convey to somebody who has not experienced it. What a private shelf provides is not access to a text but proximity to it: the spine encountered while looking for something else, the association formed between two books that happen to stand together, the recollection that something bearing on a problem was acquired four years ago for another reason.\nNone of this argues against reading, which would be perverse, and none of it excuses the acquisition of books as furniture, which is a different practice with a different purpose. It argues that the ratio of read to unread in a working collection is not a measure of diligence, and that a library in which everything has been read is one that has been assembled to describe its owner rather than to be used by them.",
    questions: [
      { q: "What mistake does the writer identify?", options: ["About library organisation","About the cost of books","About what a collection is doing","About reading speed"], answer: 2, explanation: "'a mistake about what a collection of books is doing'." },
      { q: "Which part of a library does the work?", options: ["The reference section","The most recent acquisitions","The read portion","The unread portion"], answer: 3, explanation: "'its unread portion is the part that is doing the work'." },
      { q: "Why can a useful library not be assembled at the moment of need?", options: ["The moment of need involves not knowing what would help","It is too expensive","Delivery takes too long","Books are unavailable"], answer: 0, explanation: "'characterised by not knowing what would help'." },
      { q: "What does a private shelf provide that a public collection does not?", options: ["Better editions", "Proximity rather than access", "Lower cost", "Longer loans"], answer: 1, explanation: "'not access to a text but proximity to it'." },
      { q: "Which practice does the writer explicitly exclude?", options: ["Reading several at once","Buying second-hand","Acquiring books as furniture","Lending books"], answer: 2, explanation: "'none of it excuses the acquisition of books as furniture'." },
      { q: "What does a wholly read library indicate?", options: ["Careful curation","Limited means","Diligence","That it was assembled to describe its owner"], answer: 3, explanation: "'assembled to describe its owner rather than to be used by them'." }
    ]
  },
  {
    id: "cpe-rmc10-05",
    title: "Where Difficulty Resides",
    text: "It is a commonplace of criticism that a text is difficult, and the formulation locates a property in an object where what exists is a relation between an object and a reader. The distinction is not pedantic, since the two accounts recommend entirely different responses.\nSome difficulty is a function of what a reader does not yet possess: a vocabulary, a body of reference, a familiarity with a form. This kind is dissolved by acquisition and is properly described as difficulty for this reader, and a text that is difficult in this way for almost everybody is one whose prerequisites are unusually extensive rather than one that is intrinsically hard.\nA second kind arises from the author's failure to make available what a reader would need, which is a defect in the text and is frequently defended as profundity. The distinguishing test is whether the difficulty, once penetrated, discloses something that could not have been said more plainly. Where the answer is no, the reader has been detained rather than instructed, and a critical vocabulary that cannot make this distinction is of no use to anybody.\nA third kind is deliberate and is the interesting case. A text may be constructed so that its meaning is available only to a reader who has performed certain operations, and the performance is the point: the argument is not conveyed but enacted, and a paraphrase would destroy what the reader was intended to undergo. Poetry works in this way routinely, and so does a certain kind of philosophical writing, and so do jokes.\nThe critical error that follows from failing to separate these is to praise or condemn all three together. A reader encountering the second kind and treating it as the third acquires a reverence for obscurity; a reader encountering the third and treating it as the second demands a summary and is given one, and receives, in exchange for their difficulty, something that is no longer the work. Both errors are common, and the second is committed most reliably by people acting in the interests of accessibility, which is the reason it is difficult to name without appearing to object to accessibility itself.",
    questions: [
      { q: "What does the writer say the usual formulation gets wrong?", options: ["It locates a relation as a property", "It exaggerates the problem", "It ignores authors", "It applies only to poetry"], answer: 0, explanation: "'locates a property in an object where what exists is a relation'." },
      { q: "How is the first kind of difficulty dissolved?", options: ["By paraphrase", "By acquisition on the reader's part", "By editing", "By repetition"], answer: 1, explanation: "'This kind is dissolved by acquisition'." },
      { q: "What test distinguishes the second kind?", options: ["Whether it is long","Whether it is translated","Whether it could have been said more plainly","Whether the author is famous"], answer: 2, explanation: "'discloses something that could not have been said more plainly'." },
      { q: "What characterises the third kind?", options: ["It is accidental","It results from bad editing","It affects only specialists","The meaning is enacted rather than conveyed"], answer: 3, explanation: "'the argument is not conveyed but enacted'." },
      { q: "What happens when the second kind is mistaken for the third?", options: ["A reverence for obscurity", "A demand for summaries", "Improved standards", "Loss of readers"], answer: 0, explanation: "'acquires a reverence for obscurity'." },
      { q: "Who most reliably commits the opposite error?", options: ["Academic critics", "People acting for accessibility", "Publishers", "Translators"], answer: 1, explanation: "'committed most reliably by people acting in the interests of accessibility'." }
    ]
  },
  {
    id: "cpe-rmc10-06",
    title: "The Body That Has Nothing Left to Do",
    text: "An institution created for a purpose that has been achieved is in an unusual position, and the position is one for which no established procedure exists. Dissolution is available in principle and is undertaken so rarely that the cases are remembered by name, and the reasons are not principally to do with the self-interest of the people employed, although that is the explanation most frequently offered.\nThe first difficulty is evidential. Establishing that a purpose has been achieved requires a measure, a threshold and somebody willing to declare it met, and the same organisation that would be dissolved is generally the one holding the relevant data and the expertise to interpret it. This is not a conflict that can be managed by good intentions, and it is rarely acknowledged as a conflict at all.\nThe second is that purposes are elastic. An organisation whose original object has been secured discovers, without any dishonesty, that the object was really a broader one of which the original was an instance, and that the broader version remains outstanding. Every strategic review conducted by such a body produces this finding, which is not evidence of bad faith but of what happens when a group of capable people is asked whether their work matters.\nThe third and least discussed is that dissolution destroys a capability that may be needed again. An organisation is not only a mandate; it is a set of relationships, a body of practice and a group of people who know how a thing is done, and reconstituting it after a decade costs considerably more than maintaining it and produces something worse. The case for retention on these grounds is real and is almost never the case that is actually made.\nThe institutional response that has some record of success is neither dissolution nor indefinite continuation but explicit sunsetting: a mandate that expires on a date, requiring positive renewal by somebody other than the body itself. It shifts the burden, which is the whole of the mechanism, and it is resisted for precisely that reason by every organisation to which it has ever been proposed.",
    questions: [
      { q: "What explanation for rare dissolution does the writer set aside?", options: ["Cost","Legal obstacles","The self-interest of employees","Public opposition"], answer: 2, explanation: "'although that is the explanation most frequently offered'." },
      { q: "What is the first difficulty?", options: ["Finding new employment","Disposing of assets","Informing the public","Establishing that the purpose has been achieved"], answer: 3, explanation: "'The first difficulty is evidential.'" },
      { q: "Why is that difficulty hard to manage?", options: ["The body facing dissolution holds the data","Measures are unavailable","Thresholds change","The data are secret"], answer: 0, explanation: "'the same organisation that would be dissolved is generally the one holding the relevant data'." },
      { q: "What does the writer say about purposes becoming broader?", options: ["It indicates bad faith", "It is what happens when capable people assess their own work", "It is legally required", "It is rare"], answer: 1, explanation: "'not evidence of bad faith but of what happens when a group of capable people is asked whether their work matters'." },
      { q: "What is the third and least discussed difficulty?", options: ["Redundancy costs","Archive disposal","Loss of a capability that may be needed again","Political embarrassment"], answer: 2, explanation: "'dissolution destroys a capability that may be needed again'." },
      { q: "Why is sunsetting resisted?", options: ["It is legally complex","It reduces public confidence","It is expensive","It shifts the burden of justification"], answer: 3, explanation: "'It shifts the burden, which is the whole of the mechanism, and it is resisted for precisely that reason'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
