/* CPE Prep bank: Reading multiple choice (C2) — wave 21 */
(function () {
var BANK = [
  {
    id: "cpe-rmc21-01",
    title: "The Forgery That Nobody Could Fault",
    text: "A forgery detected by technical means is a straightforward matter; a forgery that survives every technical test and is detected only when its maker confesses raises a question that the art world has never answered satisfactorily, which is what precisely was wrong with it while it hung unrecognised.\nThe conventional answer, that the object was a lie about its origin, is correct and does not dispose of the difficulty. If the pleasure taken in an object derives from its properties, and its properties are unaltered by the discovery, then the collapse in its value on exposure requires explanation in terms of something other than the object. The explanation generally offered is that a work is a record of a particular person's activity at a particular moment, and that this is part of what is being valued; on this account the forgery was always a different thing, and the viewers were mistaken about which thing they were looking at rather than about its qualities.\nThe account is defensible and has an implication its proponents rarely acknowledge. If the value lies substantially in the history rather than in the appearance, then the expertise that assesses appearance is doing less work than its practitioners claim, and the record supports this: forgeries have repeatedly passed the judgement of leading specialists and have been exposed by documents, chemistry or confession. The eye that was supposed to know has a poor record when tested against cases where the answer was subsequently established.\nThe most interesting cases are those in which a forger produced work that was preferred to the originals. Such a person has demonstrated something uncomfortable: that they could satisfy the market's stated criteria more effectively than the artist whose name they borrowed, and that what prevented recognition was not their ability but their lack of a biography that would make the work matter.\nWhat this suggests is not that authenticity is a delusion but that it is a different value from aesthetic merit, and that the two are habitually reported as one. A viewer who knows which of the two is producing their response is in a better position than the institutions, which have an interest in the belief that the eye alone is sufficient and a record that does not support it.",
    questions: [
      { q: "What question does an undetected forgery raise?", options: ["What was wrong with it while unrecognised","Who bought it","How to detect others","How it was made"], answer: 0, explanation: "'what precisely was wrong with it while it hung unrecognised'." },
      { q: "What does the conventional answer fail to dispose of?", options: ["The legal issue", "Why value collapses when properties are unaltered", "The maker's motive", "The detection method"], answer: 1, explanation: "'the collapse in its value on exposure requires explanation in terms of something other than the object'." },
      { q: "What does the historical account claim a work is?", options: ["A visual object only","A collaborative product","A record of a person's activity at a moment","A market commodity"], answer: 2, explanation: "'a work is a record of a particular person's activity at a particular moment'." },
      { q: "What does the record show about specialists?", options: ["They rely on chemistry","They rarely disagree","They detect forgeries reliably","Forgeries have repeatedly passed their judgement"], answer: 3, explanation: "'forgeries have repeatedly passed the judgement of leading specialists'." },
      { q: "What did the preferred forgeries demonstrate?", options: ["That the forger lacked a biography, not ability","That taste is stable","That originals are overvalued","Superior materials"], answer: 0, explanation: "'not their ability but their lack of a biography that would make the work matter'." },
      { q: "What is the writer's conclusion?", options: ["Authenticity is a delusion", "Authenticity and merit are different values reported as one", "Expertise is worthless", "Forgery should be permitted"], answer: 1, explanation: "'it is a different value from aesthetic merit, and that the two are habitually reported as one'." }
    ]
  },
  {
    id: "cpe-rmc21-02",
    title: "The Sound You Stopped Hearing",
    text: "Chronic noise exposure is among the better-evidenced environmental health risks and among the least regulated, and the discrepancy is explained largely by a property of the exposure itself: it is one of the few harms that the person suffering it stops noticing.\nHabituation is the mechanism and is easily mistaken for adaptation. A resident beside a busy road reports, accurately, that they no longer hear the traffic, and the report is taken by everybody including the resident to mean that the noise has ceased to affect them. The physiological measurements do not agree. Sleep studies record arousals in response to individual vehicle passes that the sleeper has no memory of, and the accumulated effect on cardiovascular measures is present in populations that consistently describe themselves as untroubled.\nThe consequence for policy is a systematic failure of the complaint-based mechanisms by which such matters are usually addressed. Complaints arrive from those recently exposed, and they diminish over the following year as habituation proceeds, and the diminution is read by the responsible body as evidence that the problem has resolved. The reverse inference would be more accurate: a population that has stopped complaining is a population that has stopped perceiving an exposure that continues.\nThe distributional aspect is stark and predictable. Quiet is expensive, being a function of distance from infrastructure, of the cost of construction that excludes sound, and of the ability to choose where one lives. The exposure therefore falls where the resources to avoid it are least, and it does so continuously and over decades, which is the relevant period for the effects that have been demonstrated.\nWhat would improve matters is chiefly a change in what is measured. Standards expressed as an average over a period conceal the pattern that matters, since the health effects appear to be driven by individual events rather than by aggregate energy, and a night of forty separate disturbances can satisfy a limit that a continuous sound of the same total would breach. Measurement that counts events rather than averaging them is technically straightforward, produces uncomfortable numbers, and has been adopted in very few places.",
    questions: [
      { q: "Why is noise poorly regulated?", options: ["Evidence is weak","It is hard to measure","Sufferers stop noticing it","It is inexpensive"], answer: 2, explanation: "'the person suffering it stops noticing'." },
      { q: "What do sleep studies record?", options: ["Improved sleep","No measurable effect","Complete adaptation","Arousals the sleeper does not remember"], answer: 3, explanation: "'arousals in response to individual vehicle passes that the sleeper has no memory of'." },
      { q: "How are diminishing complaints interpreted?", options: ["As evidence the problem has resolved", "As habituation", "As under-reporting", "As administrative failure"], answer: 0, explanation: "'read by the responsible body as evidence that the problem has resolved'." },
      { q: "What would the accurate inference be?", options: ["Measurement failed","The population has stopped perceiving a continuing exposure","The noise has fallen","Residents have moved"], answer: 1, explanation: "'a population that has stopped complaining is a population that has stopped perceiving'." },
      { q: "Why is exposure unequally distributed?", options: ["Traffic patterns differ","Construction standards are uniform","Quiet is expensive","Regulations vary"], answer: 2, explanation: "'Quiet is expensive'." },
      { q: "What change in measurement is proposed?", options: ["Continuous monitoring","Resident surveys","Longer averaging periods","Counting events rather than averaging"], answer: 3, explanation: "'Measurement that counts events rather than averaging them'." }
    ]
  },
  {
    id: "cpe-rmc21-03",
    title: "When a Crowd Is Right",
    text: "The finding that the average of many independent estimates is more accurate than most of the individual estimates composing it is genuine, is reproducible, and is routinely invoked in circumstances where the conditions producing it are absent.\nThe mechanism is arithmetical rather than mystical. Individual errors are partly random, random errors of opposite sign cancel when averaged, and what remains is the shared signal plus whatever error is common to all the estimators. The improvement is therefore a function of how much of the error is independent, and where the errors are correlated the averaging removes nothing at all.\nThis identifies the condition under which the effect disappears, which is precisely the condition that most real groups satisfy. Estimates formed by people who have consulted one another, or who have read the same source, or who are aware of an early figure proposed by somebody confident, are not independent, and their average is not more reliable than the common view they have converged on. A group that has discussed a question before estimating has destroyed the property that would have made its average worth having.\nThe practical procedures that preserve independence are simple and feel wasteful. Estimates written down before any discussion; a prohibition on stating a figure aloud until all are recorded; and, where possible, a deliberate variation in the material each estimator is given, so that their errors are less likely to share a source. Groups that adopt these report the same discomfort, which is that the exercise appears to ignore the informational advantage of discussion.\nThe resolution is that the two operations are for different things and should be sequenced rather than merged. Independent estimation first, to obtain the benefit of cancellation; discussion afterwards, to surface the reasoning behind outliers, which is where the information that no average contains is usually located. A group that discusses first has one number and no way of knowing how much of it was arrived at by everybody agreeing with the first person who spoke.",
    questions: [
      { q: "What makes the averaging effect work?", options: ["Random errors of opposite sign cancelling","Expert participation","Large group size","Collective intelligence"], answer: 0, explanation: "'random errors of opposite sign cancel when averaged'." },
      { q: "When does averaging remove nothing?", options: ["When experts differ","When errors are correlated","When groups are small","When estimates vary widely"], answer: 1, explanation: "'where the errors are correlated the averaging removes nothing at all'." },
      { q: "What does prior discussion destroy?", options: ["The record","Group cohesion","The property that made the average worth having","Individual confidence"], answer: 2, explanation: "'has destroyed the property that would have made its average worth having'." },
      { q: "Which procedure preserves independence?", options: ["Appointing a chair","Averaging repeatedly","Excluding novices","Recording estimates before discussion"], answer: 3, explanation: "'Estimates written down before any discussion'." },
      { q: "What discomfort do groups report?", options: ["That it appears to ignore discussion's advantage","That it is unfair","That it is inaccurate","That it takes too long"], answer: 0, explanation: "'the exercise appears to ignore the informational advantage of discussion'." },
      { q: "What is discussion afterwards for?", options: ["Reaching consensus", "Surfacing the reasoning behind outliers", "Confirming the average", "Assigning responsibility"], answer: 1, explanation: "'to surface the reasoning behind outliers'." }
    ]
  },
  {
    id: "cpe-rmc21-04",
    title: "The Calendar That Species Keep",
    text: "The timing of biological events — the opening of a leaf, the arrival of a migrant, the emergence of an insect — is recorded in datasets that in some cases extend across centuries, and these records have turned out to constitute one of the more sensitive instruments available for detecting environmental change.\nThe value of the records was not anticipated by those who made them. They were compiled by people with an interest in a garden, an estate or a particular species, for reasons that were personal, and the resulting series are irregular, unevenly documented and vulnerable to changes in who was doing the observing. That they are usable at all is a consequence of the size of the signal they contain: the shifts being detected are large relative to the noise introduced by amateur inconsistency.\nWhat the records show is a general advance in spring events, and, more importantly, an advance that is not uniform across species. Organisms take their cues from different variables — some from temperature, some from day length, some from soil conditions — and day length does not change, with the result that species responding to it advance not at all while those responding to temperature advance substantially.\nThe consequence is the decoupling of relationships that depend on timing. A migrant arriving on a schedule set by day length in a distant wintering area may reach a breeding site at which the insect emergence its young require has already passed its peak, and neither party has done anything unusual: each has responded correctly to its own cue. The failure is a failure of coincidence, and the population effects can be severe while every individual behaves exactly as it always has.\nThis is what makes phenological records more informative than temperature series alone. A temperature record establishes that conditions changed; a phenological record establishes what the change did to a system of relationships, and it does so with a resolution that no model of an ecosystem currently approaches. The instruments were assembled by people recording the date on which a particular tree came into leaf, which is a reminder that the value of a long series is rarely visible to whoever begins it.",
    questions: [
      { q: "Why are the records usable despite their irregularity?", options: ["They are short","They were professionally made","The signal is large relative to the noise","They were standardised later"], answer: 2, explanation: "'the shifts being detected are large relative to the noise'." },
      { q: "What do the records show?", options: ["No change","Delayed events","Uniform advance","An advance that is not uniform across species"], answer: 3, explanation: "'an advance that is not uniform across species'." },
      { q: "Why do some species not advance?", options: ["They respond to day length, which does not change", "They are less sensitive", "They live underground", "They migrate"], answer: 0, explanation: "'day length does not change'." },
      { q: "What is the consequence?", options: ["Increased competition","Decoupling of timing-dependent relationships","Population growth","Range expansion"], answer: 1, explanation: "'the decoupling of relationships that depend on timing'." },
      { q: "How does the writer characterise the failure?", options: ["A genetic problem","A measurement artefact","A failure of coincidence","A behavioural error"], answer: 2, explanation: "'The failure is a failure of coincidence'." },
      { q: "Why are phenological records more informative than temperature series?", options: ["They are more precise","They are professionally maintained","They are longer","They show what change did to relationships"], answer: 3, explanation: "'establishes what the change did to a system of relationships'." }
    ]
  },
  {
    id: "cpe-rmc21-05",
    title: "How Long a Skill Lasts",
    text: "The claim that skills now expire faster than they once did is repeated so often in discussions of work that its evidential basis is rarely examined, and the examination is worth conducting because the claim is true of some skills, false of others, and misleading as a general proposition.\nThe distinction that does the work is between skills whose content is a body of specific procedures and skills that consist of a capacity to acquire procedures. The first genuinely expire, and always have: a person trained on a particular system possesses knowledge that becomes worthless when the system is replaced, and the rate of replacement has increased. The second do not expire at all, and their possessors move between systems at a cost that is real but bounded.\nThe policy conclusion usually drawn — that education should concentrate on the second and neglect the first — does not follow and is contradicted by what is known about how expertise develops. The capacity to acquire procedures is not a general faculty that can be trained in the abstract; it is built by acquiring a substantial number of specific procedures in a domain and coming to see what they have in common, and a curriculum that skips the specifics produces neither the specific competence nor the general one.\nA further complication concerns what is actually lost when a technology changes. The surface of a practice is replaced and the underlying structure is frequently not: a person who understood why a system was arranged as it was will recognise the same considerations in its successor, and one who learnt the sequence of operations will not. The distinction is invisible in any record of qualifications, which is why the estimates of skill obsolescence that circulate are estimates of the surface.\nWhat the evidence supports is therefore an unfashionable position. Deep training in a specific domain remains the route to the transferable capacity, the transferable capacity cannot be taught directly, and the periodic announcements that a particular body of knowledge has been rendered obsolete are usually announcements about a surface, made by people who have not asked what the practitioners actually knew.",
    questions: [
      { q: "What distinction does the writer draw?", options: ["Between specific procedures and the capacity to acquire them","Between manual and mental work","Between formal and informal training","Between old and new skills"], answer: 0, explanation: "'between skills whose content is a body of specific procedures and skills that consist of a capacity to acquire procedures'." },
      { q: "What does the writer say about the second kind?", options: ["They expire slowly", "They do not expire at all", "They cannot be measured", "They are rare"], answer: 1, explanation: "'The second do not expire at all'." },
      { q: "Why does the usual policy conclusion fail?", options: ["Students prefer specifics","It costs too much","The general capacity cannot be trained in the abstract","Teachers resist it"], answer: 2, explanation: "'it is not a general faculty that can be trained in the abstract'." },
      { q: "What does a curriculum skipping specifics produce?", options: ["General competence only","Faster learning","Broader knowledge","Neither the specific nor the general competence"], answer: 3, explanation: "'produces neither the specific competence nor the general one'." },
      { q: "Who recognises considerations in a successor system?", options: ["Somebody who understood why it was arranged as it was","Any trained person","Nobody","Somebody who learnt the sequence of operations"], answer: 0, explanation: "'a person who understood why a system was arranged as it was'." },
      { q: "What are obsolescence announcements usually about?", options: ["Training costs","A surface","Deep structure","Employment trends"], answer: 1, explanation: "'usually announcements about a surface'." }
    ]
  },
  {
    id: "cpe-rmc21-06",
    title: "Nobody Heeds the Warning",
    text: "The failure of warnings is generally attributed to the people who disregard them, and the attribution survives despite a research literature that locates the causes almost entirely in the design of the warning and the situation in which it arrives.\nThe first cause is habituation, and it is produced by the warnings themselves. A signal that fires frequently without a consequential event teaches its audience that it does not require action, and the teaching is efficient: within weeks, response times lengthen and then disappear. Systems that warn conservatively, in order to be safe, therefore convert themselves into systems that do not warn at all, and the conversion is caused by the caution.\nThe second is that a warning must compete with an activity already in progress. A person receiving one is doing something, and the warning asks them to stop, which has costs that are immediate and certain, in exchange for avoiding a harm that is delayed and probabilistic. The calculation is not irrational, and the behaviour it produces is frequently described as complacency by people who were not performing the task.\nThe third and most consequential is that warnings are usually about the wrong stage. An alert that fires when a condition has become dangerous arrives when the options have narrowed and the operator is committed; the useful moment is earlier, when the situation is merely unusual and departing from the plan is still cheap. Systems that indicate deviation rather than danger are more useful and are harder to design, because the criterion for deviation must be established for each situation and the criterion for danger can be set once.\nWhat is known about effective warnings is unglamorous. They must be rare, must specify the action required rather than the condition detected, and must arrive with enough time for the action to be taken and no more. A warning that fails any of these has not merely been ineffective; it has contributed to the habituation that will degrade the next one, which is why adding a warning to a system in response to an incident is as likely to reduce safety as to increase it.",
    questions: [
      { q: "Where does the research locate the causes?", options: ["In regulation","In the people who disregard warnings","In the design and the situation","In training"], answer: 2, explanation: "'locates the causes almost entirely in the design of the warning and the situation'." },
      { q: "What produces habituation?", options: ["Operator fatigue","Poor training","Equipment failure","The warnings themselves"], answer: 3, explanation: "'it is produced by the warnings themselves'." },
      { q: "What happens to conservative warning systems?", options: ["They convert into systems that do not warn","They are removed","They improve response","They become safer"], answer: 0, explanation: "'convert themselves into systems that do not warn at all'." },
      { q: "How does the writer describe apparent complacency?", options: ["As irrational", "As a rational calculation", "As inexperience", "As distraction"], answer: 1, explanation: "'The calculation is not irrational'." },
      { q: "When is the useful moment to warn?", options: ["At the start of a shift","When danger is present","When the situation is merely unusual","After the event"], answer: 2, explanation: "'when the situation is merely unusual and departing from the plan is still cheap'." },
      { q: "What should a warning specify?", options: ["The probability of harm","The responsible party","The condition detected","The action required"], answer: 3, explanation: "'must specify the action required rather than the condition detected'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
