/* CPE Prep bank: Reading True/False/Not Given (C2) — wave 6 */
(function () {
var TFNG = ["True", "False", "Not Given"];
var BANK = [
  {
    id: "cpe-rtfng6-01",
    title: "The Corroded Machine from the Sea",
    text: "In 1901 sponge divers sheltering from a storm off the small Greek island of Antikythera investigated a wreck lying in some fifty metres of water. Among the bronze and marble statuary they raised over the following months was a shapeless lump of corroded metal, which was set aside and attracted no particular attention until, some time after its recovery, it split apart in the museum and revealed the unmistakable outlines of toothed gearwheels.\nThe object that emerged has since been dated to the second or first century before the present era, and it is unlike anything else surviving from antiquity. Its surviving fragments contain more than thirty interlocking bronze gears, cut by hand, arranged in trains that drive pointers across dials on the front and back faces. Nothing of comparable mechanical complexity is known from the following fourteen centuries, which is the fact that made the object so difficult for scholars to accept when it was first described.\nThe purpose of the machine was established gradually and by indirect means. Because the fragments are heavily corroded and cannot be dismantled, the internal arrangement had to be inferred, first from surface examination and later from radiography. Imaging conducted in recent decades resolved gear teeth that could not be seen at all, and also revealed inscriptions on plates within the mechanism that function as a set of instructions describing what the dials show.\nThose readings established that the device modelled the movements of the sun and moon against the zodiac, tracked the phase of the moon, and predicted eclipses using a cycle of lunar months known to Babylonian astronomy. A subsidiary dial recorded a four-year cycle associated with athletic festivals. One train of gears incorporates an ingenious arrangement in which a pin moves within a slot, producing a varying rate that reproduces the moon's uneven motion across the sky.\nWho built it is not known. The inscriptions are in Greek, the astronomical scheme is Babylonian in origin, and the workmanship indicates a tradition rather than an individual experiment, since a first attempt at such a mechanism would not look like this. What the object establishes beyond argument is that the ancient world possessed geared calculating devices, and that almost the entire record of that capability has been lost.",
    questions: [
      { q: "The divers were looking for the wreck when they took shelter from the storm.", options: TFNG, answer: 1, explanation: "False - they were sponge divers sheltering from a storm who then investigated the wreck." },
      { q: "The corroded lump was recognised as significant immediately upon recovery.", options: TFNG, answer: 1, explanation: "False - it 'was set aside and attracted no particular attention' until it split apart later in the museum." },
      { q: "The mechanism contains more than thirty surviving gearwheels.", options: TFNG, answer: 0, explanation: "True - 'more than thirty interlocking bronze gears'." },
      { q: "The fragments were taken apart so that the gear trains could be examined.", options: TFNG, answer: 1, explanation: "False - the fragments 'cannot be dismantled' and the arrangement had to be inferred." },
      { q: "Radiography revealed inscriptions functioning as instructions.", options: TFNG, answer: 0, explanation: "True - imaging 'revealed inscriptions on plates within the mechanism that function as a set of instructions'." },
      { q: "The eclipse prediction used a cycle derived from Babylonian astronomy.", options: TFNG, answer: 0, explanation: "True - 'using a cycle of lunar months known to Babylonian astronomy'." },
      { q: "The device was more accurate than any instrument built before the seventeenth century.", options: TFNG, answer: 2, explanation: "Not Given - the text says nothing of comparable complexity survives from the following fourteen centuries, but makes no claim about accuracy." },
      { q: "The identity of the maker has been established from the inscriptions.", options: TFNG, answer: 1, explanation: "False - 'Who built it is not known.'" },
    ]
  },
  {
    id: "cpe-rtfng6-02",
    title: "When the Horse Was Taken In",
    text: "The domestication of the horse is among the more consequential events in human history and among the hardest to date, because the animal was hunted for a very long period before it was kept, and the bones of a hunted horse and a herded one are not easily distinguished.\nThe evidence that has proved most useful is therefore indirect. One approach examines the wear on teeth: an animal that has carried a bit develops characteristic damage on particular teeth, and this damage has been identified on horse remains from sites in the steppe dating to around three thousand five hundred years before the present era. Another examines the proportions of animals in a settlement's refuse, on the reasoning that a herded population contains a different distribution of ages and sexes from a hunted one.\nA third line of evidence comes from residues absorbed into pottery. Fragments from certain steppe settlements have yielded traces of a fat whose composition is characteristic of mare's milk, which establishes that horses were being milked rather than merely eaten, and milking requires an animal that tolerates close handling.\nGenetic work has complicated the picture rather than settling it. Analysis of ancient and modern genomes indicates that the population from which almost all modern domestic horses descend expanded very rapidly across a wide area rather later than the earliest evidence for handling, which suggests that horses may have been kept in several places before one particular lineage spread and replaced the others. The reasons for that replacement are not established, though the timing coincides with changes in how horses were used.\nWhat the horse made possible is easier to describe than when it happened. Riding altered the distance a person could travel in a day by a factor of several, transformed the management of other livestock, and eventually changed the conduct of war, although the chariot preceded effective cavalry by a considerable period. The animal also spread languages, technologies and diseases, which is why the question of its domestication attracts attention far outside the study of animals.",
    questions: [
      { q: "Horses were hunted before they were kept.", options: TFNG, answer: 0, explanation: "True - 'the animal was hunted for a very long period before it was kept'." },
      { q: "The bones of hunted and herded horses can be readily told apart.", options: TFNG, answer: 1, explanation: "False - they 'are not easily distinguished'." },
      { q: "Wear caused by a bit has been identified on steppe horse remains.", options: TFNG, answer: 0, explanation: "True - characteristic damage identified on remains from steppe sites." },
      { q: "Residues in pottery indicate that horses were milked.", options: TFNG, answer: 0, explanation: "True - traces of a fat characteristic of mare's milk." },
      { q: "Mare's milk was the principal food of the settlements concerned.", options: TFNG, answer: 2, explanation: "Not Given - the text says milk residues were found but says nothing about its share of the diet." },
      { q: "Genetic evidence has resolved the question of where domestication occurred.", options: TFNG, answer: 1, explanation: "False - genetic work 'has complicated the picture rather than settling it'." },
      { q: "The reasons for the rapid spread of one horse lineage are known.", options: TFNG, answer: 1, explanation: "False - 'The reasons for that replacement are not established'." },
      { q: "Effective cavalry appeared before the chariot.", options: TFNG, answer: 1, explanation: "False - 'the chariot preceded effective cavalry by a considerable period'." },
    ]
  },
  {
    id: "cpe-rtfng6-03",
    title: "The Journey of Paper",
    text: "Paper was made in China at least two thousand years ago from macerated plant fibre suspended in water and drained on a screen, and the technique reached Europe by a route whose intermediate stages are reasonably well documented.\nThe first substantial transmission westwards is generally associated with the eighth century, when the technique became established in the cities of Central Asia and subsequently in Baghdad, where a paper industry of considerable scale developed. From there manufacture spread across North Africa and into the Iberian peninsula, and mills were operating in what is now Spain by the eleventh century. Italy followed, and by the fourteenth century Italian mills were exporting paper across the continent in quantities that undercut every local alternative.\nWhat made this possible was not merely the knowledge of how to form a sheet. European mills used water power to drive stamping hammers that reduced rags to pulp, adopted a gelatine size that suited the inks then in use, and developed a wire mould that left a pattern in the sheet by which a maker could be identified. Rags, principally of linen, were the raw material, and their supply became the industry's binding constraint: the growth of printing in the following centuries produced a demand that the available quantity of worn cloth could not satisfy.\nThe substitution that eventually resolved the shortage was wood, pulped mechanically and later chemically, and it arrived in the nineteenth century. Paper made in this way is cheaper by a wide margin and considerably less durable, since the mechanical process leaves in place a substance that yellows and embrittles the sheet under light. Books printed on rag paper four hundred years ago are frequently in better condition than books printed on wood pulp a century ago, which is a fact that librarians have had to accommodate in every decision about storage.\nParchment did not disappear when paper arrived. It continued in use for documents intended to last, and the choice between the two materials was for a long period a statement about how permanent a text was expected to be.",
    questions: [
      { q: "Paper-making reached Baghdad before it reached the Iberian peninsula.", options: TFNG, answer: 0, explanation: "True - the technique became established in Baghdad in the eighth century, and mills were operating in Spain by the eleventh." },
      { q: "Italian mills exported paper widely by the fourteenth century.", options: TFNG, answer: 0, explanation: "True - 'Italian mills were exporting paper across the continent'." },
      { q: "European mills used animal power to drive their stamping hammers.", options: TFNG, answer: 1, explanation: "False - they 'used water power to drive stamping hammers'." },
      { q: "The wire mould allowed a sheet's maker to be identified.", options: TFNG, answer: 0, explanation: "True - it 'left a pattern in the sheet by which a maker could be identified'." },
      { q: "The supply of rags limited the growth of the industry.", options: TFNG, answer: 0, explanation: "True - 'their supply became the industry's binding constraint'." },
      { q: "Rag collection was organised by guilds in most European cities.", options: TFNG, answer: 2, explanation: "Not Given - the text describes rags as the raw material but says nothing about how collection was organised." },
      { q: "Wood pulp paper is more durable than rag paper.", options: TFNG, answer: 1, explanation: "False - it is 'considerably less durable'." },
      { q: "Parchment ceased to be used once paper became available.", options: TFNG, answer: 1, explanation: "False - 'Parchment did not disappear when paper arrived.'" },
    ]
  },
  {
    id: "cpe-rtfng6-04",
    title: "The Year Without a Summer",
    text: "In April 1815 a volcano on the island of Sumbawa produced an eruption whose scale has not been matched in the period of instrumental record. The mountain lost a substantial part of its height, the explosive column reached the stratosphere, and the immediate effects in the surrounding region were catastrophic, with the loss of life from the eruption itself and from the destruction of crops over a wide area.\nThe global consequences followed from the material injected into the upper atmosphere. Sulphur compounds carried above the level at which rain removes them formed a persistent haze of fine droplets that reflected part of the incoming sunlight, and the resulting cooling was distributed around the planet by the circulation of the stratosphere over the following months.\nThe following year is remembered in Europe and North America as a season of persistent cold and rain. Frosts were recorded in New England in each of the summer months, harvests failed across much of northern Europe, and the price of grain rose to levels that produced unrest in several countries. Contemporary accounts describe a sun that could be looked at directly and sunsets of unusual colour, both consistent with a stratospheric veil.\nThe attribution of that weather to the eruption was not made at the time. The connection between distant volcanic activity and regional climate was proposed in the nineteenth century and established firmly only in the twentieth, when ice cores from Greenland and Antarctica were found to contain a layer of volcanic sulphate at the appropriate depth in both hemispheres, which indicates an eruption in the tropics whose plume was distributed globally.\nThe episode is now used as a reference case in the study of how the atmosphere responds to a sudden injection of reflective particles, and the estimates it supplies are cited in discussions of deliberate intervention in the climate. What it also demonstrates is the vulnerability of an agricultural system with little stored surplus to a single poor season, since the deaths that followed in Europe were caused not by the eruption but by the failure of a harvest.",
    questions: [
      { q: "The eruption reduced the height of the mountain.", options: TFNG, answer: 0, explanation: "True - 'The mountain lost a substantial part of its height'." },
      { q: "Sulphur compounds reached a level above that at which rain removes them.", options: TFNG, answer: 0, explanation: "True - they were 'carried above the level at which rain removes them'." },
      { q: "Frosts were recorded in New England during the summer months of the following year.", options: TFNG, answer: 0, explanation: "True - 'Frosts were recorded in New England in each of the summer months'." },
      { q: "The link between the eruption and the weather was recognised by contemporaries.", options: TFNG, answer: 1, explanation: "False - 'The attribution of that weather to the eruption was not made at the time.'" },
      { q: "Ice cores from both hemispheres contain a sulphate layer of the relevant date.", options: TFNG, answer: 0, explanation: "True - cores from Greenland and Antarctica contain such a layer." },
      { q: "The eruption was the largest in the last ten thousand years.", options: TFNG, answer: 2, explanation: "Not Given - the text says its scale is unmatched in the instrumental record, which is a much shorter period." },
      { q: "European deaths in the following year were caused directly by the eruption.", options: TFNG, answer: 1, explanation: "False - they 'were caused not by the eruption but by the failure of a harvest'." },
      { q: "The episode informs current discussion of intervening in the climate.", options: TFNG, answer: 0, explanation: "True - its estimates 'are cited in discussions of deliberate intervention in the climate'." },
    ]
  },
  {
    id: "cpe-rtfng6-05",
    title: "Measuring a Subcontinent",
    text: "The survey that measured the Indian subcontinent occupied most of the nineteenth century and was, in its methods, an exercise in geometry conducted across a landscape rather than a matter of exploration.\nThe procedure depended on triangulation. A base line of a few miles was measured directly, with extraordinary care, using chains or bars whose expansion with temperature had to be accounted for; every other distance in the network was then calculated from angles observed between fixed points rather than measured on the ground. Because errors accumulate along a chain of triangles, the network was arranged as a series of arcs, and base lines were measured again at intervals so that the calculated distance could be compared with a direct one.\nThe instruments were large and difficult to move. The principal theodolites weighed several hundred kilograms, required teams of men and animals to transport, and were raised onto towers built where no natural high point existed, since the observation of one station from another requires an unobstructed line. In forested or level country the construction of these towers accounted for a substantial share of the work.\nThe human cost was severe and is recorded unevenly. Malaria and other fevers killed surveyors and labourers in large numbers, particularly in the lower valleys, and the survey's own accounts note seasons in which parties were reduced by illness to a fraction of their strength.\nThe most widely known result of the enterprise was the calculation, from observations taken more than a hundred miles away, of the height of the mountain subsequently given the name of a former surveyor general. The computation required corrections for the curvature of the earth, for the refraction of light through the atmosphere and for the deflection of the plumb line by the gravitational attraction of the mountains themselves, and the figure obtained differs from the modern value by a small margin.\nThe survey's data underpinned mapping, administration and revenue collection, and its arcs were used in the nineteenth-century determination of the shape of the earth. The geodetic results were, in that sense, a by-product of an undertaking whose purposes were administrative.",
    questions: [
      { q: "Most distances in the survey were measured directly on the ground.", options: TFNG, answer: 1, explanation: "False - every other distance was 'calculated from angles observed between fixed points rather than measured on the ground'." },
      { q: "Base lines were re-measured at intervals as a check.", options: TFNG, answer: 0, explanation: "True - so that the calculated distance could be compared with a direct one." },
      { q: "The principal theodolites could be carried by one person.", options: TFNG, answer: 1, explanation: "False - they 'weighed several hundred kilograms' and required teams of men and animals." },
      { q: "Towers were built where no natural high point existed.", options: TFNG, answer: 0, explanation: "True - stated directly in the text." },
      { q: "Disease caused substantial losses among survey parties.", options: TFNG, answer: 0, explanation: "True - fevers 'killed surveyors and labourers in large numbers'." },
      { q: "The survey employed more labourers than any other project of its time.", options: TFNG, answer: 2, explanation: "Not Given - the text describes large parties but makes no comparison with other projects." },
      { q: "The mountain's height was calculated from observations made at a distance.", options: TFNG, answer: 0, explanation: "True - from observations taken more than a hundred miles away." },
      { q: "The determination of the earth's shape was the survey's principal purpose.", options: TFNG, answer: 1, explanation: "False - the geodetic results were 'a by-product of an undertaking whose purposes were administrative'." },
    ]
  },
  {
    id: "cpe-rtfng6-06",
    title: "A Lamp That Would Not Ignite the Air",
    text: "The mining disasters of the early nineteenth century in the coalfields of northern England prompted an unusual arrangement: a society formed by local landowners and clergy commissioned scientific investigation into the explosions of flammable gas that were killing miners in large numbers.\nThe problem was straightforward to state and not to solve. The gas encountered underground, chiefly methane, forms an explosive mixture with air across a range of concentrations, and the candles by which men worked provided a source of ignition. Any lamp that produced light by combustion carried a flame, and the flame was precisely the difficulty.\nThe solution that emerged rested on an observation about how flame propagates. A flame will not pass through a fine metal gauze, because the metal conducts heat away from the burning gas rapidly enough to cool it below the temperature at which combustion continues. A lamp whose flame is enclosed within such a gauze can therefore burn in an atmosphere containing flammable gas: the gas passes through the mesh and burns inside the lamp without igniting the surrounding air.\nThe device had a second and unintended benefit that miners came to value. The behaviour of the flame within the gauze indicates the composition of the air around it: an elongated blue cap on the flame signals the presence of methane, and its height gives a rough measure of concentration, while a flame that dims or goes out indicates a shortage of oxygen. The lamp thus became an instrument as well as a light source.\nIts introduction did not reduce fatalities as much as had been hoped, and the reason has been debated since. The lamp permitted work in seams that had previously been considered too dangerous to enter at all, and the resulting extension of mining into gassier workings offset a substantial part of the safety gain. The lamp also failed where a current of air was strong enough to drive flame through the gauze, a limitation that was recognised and led to later designs incorporating shields.\nWhether the credit for the invention belongs to one man was disputed at the time, since two designs appeared within a short period, and the dispute was pursued with some vigour by the supporters of each.",
    questions: [
      { q: "The investigation was commissioned by a society of landowners and clergy.", options: TFNG, answer: 0, explanation: "True - 'a society formed by local landowners and clergy commissioned scientific investigation'." },
      { q: "Methane forms an explosive mixture with air only at a single concentration.", options: TFNG, answer: 1, explanation: "False - it does so 'across a range of concentrations'." },
      { q: "A flame cannot pass through fine metal gauze because the metal conducts heat away.", options: TFNG, answer: 0, explanation: "True - the metal cools the burning gas below the temperature at which combustion continues." },
      { q: "The lamp could indicate the presence of methane by the appearance of its flame.", options: TFNG, answer: 0, explanation: "True - 'an elongated blue cap on the flame signals the presence of methane'." },
      { q: "Miners were given formal training in reading the flame.", options: TFNG, answer: 2, explanation: "Not Given - the text says miners valued the indication but says nothing about training." },
      { q: "Fatalities fell as much as had been expected after the lamp was introduced.", options: TFNG, answer: 1, explanation: "False - 'Its introduction did not reduce fatalities as much as had been hoped'." },
      { q: "The lamp could fail in a strong current of air.", options: TFNG, answer: 0, explanation: "True - it failed 'where a current of air was strong enough to drive flame through the gauze'." },
      { q: "Credit for the invention was undisputed at the time.", options: TFNG, answer: 1, explanation: "False - it 'was disputed at the time, since two designs appeared within a short period'." },
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
