/* CPE Prep bank: reading multiple-choice (wave 5) */
(function () {
var BANK = [
  {
    id: "cpe-rmc5-01",
    title: "On Losing One's Sense of Direction",
    text: "I come from a family of navigators. My grandfather could emerge from an unfamiliar underground station and, after a pause so brief it seemed merely a courtesy to the universe, set off unerringly north; my mother reads cities the way other people read menus. It was therefore a source of mild dynastic shame that I, their descendant, could get lost in a hotel corridor. For years I treated this as an immutable fact about myself, one of those traits, like an inability to whistle, that one carries apologetically through life. It was only when the satnav era arrived — and I noticed my proudly compass-brained relatives beginning to fumble — that I started to suspect the story was less about inheritance than about practice. The research on this point is quietly unsettling. Spatial ability, it turns out, behaves less like eye colour and more like a language: the capacity is universal, but fluency depends on use. Navigation researchers speak of a feedback loop in which small early failures breed avoidance, avoidance prevents the formation of cognitive maps, and the absent maps then confirm the original self-diagnosis. Meanwhile, populations who navigate constantly — taxi drivers famously, but also hunters, sailors, and children who roam unsupervised — show measurably enhanced abilities, and in some cases enlarged hippocampi to match. What the turn-by-turn voice in our pockets has done is enrol nearly all of us in the avoidance arm of the experiment. We arrive, but we do not know how we arrived; the journey happens to us. I spent last autumn conducting a private rebellion: phone in pocket, wrong turns permitted, a rule that I could consult the map only after committing to a guess. The early results were farcical — one 'shortcut' in Lisbon added ninety minutes and a hill I still resent. But something did change. Districts began to join up. The city stopped being a string of destinations and became, for the first time in my adult life, a shape. I remain, let me be clear, a mediocre navigator. My grandfather would find my progress amusing. But mediocrity, for those of us who believed ourselves hopeless, is a kind of triumph; and I have come to think the direction sense my family boasted of was never a gift at all, merely the sediment of ten thousand unassisted journeys.",
    questions: [
      { q: "The writer mentions the 'pause so brief it seemed merely a courtesy to the universe' to suggest that", options: ["her grandfather's orientation was almost instantaneous", "her grandfather doubted his own judgement", "underground stations confused her whole family", "politeness mattered greatly to her grandfather"], answer: 0, explanation: "The pause was barely a pause at all — his sense of direction operated 'unerringly' and near-instantly." },
      { q: "What first led the writer to question her self-diagnosis?", options: ["Reading research on taxi drivers", "A conversation with her mother", "Learning to whistle in adulthood", "Seeing skilled relatives decline once they used satnav"], answer: 3, explanation: "When 'my proudly compass-brained relatives beginning to fumble' in the satnav era, she suspected practice, not inheritance." },
      { q: "The comparison between spatial ability and language implies that", options: ["both are fixed at birth", "navigation requires verbal skill", "everyone has the capacity but skill depends on use", "some languages aid navigation more than others"], answer: 2, explanation: "'The capacity is universal, but fluency depends on use.'" },
      { q: "According to the research described, what sustains poor navigation?", options: ["A cycle of avoidance preventing cognitive maps from forming", "Inherited differences in the hippocampus", "The stress of early failures in adulthood", "Living in cities with confusing layouts"], answer: 0, explanation: "Small failures breed avoidance, avoidance prevents cognitive maps, and the absence 'confirms the original self-diagnosis'." },
      { q: "What does the writer mean by 'the journey happens to us'?", options: ["Modern travel has become dangerously fast", "Navigation devices make travel passive", "Journeys are now shorter than before", "We remember journeys more vividly now"], answer: 1, explanation: "With turn-by-turn guidance 'we arrive, but we do not know how we arrived' — the traveller is passive." },
      { q: "How does the writer finally interpret her family's talent?", options: ["As a genetic gift she failed to inherit", "As an exaggeration none of them possessed", "As a skill her rebellion has now surpassed", "As the accumulated result of vast unassisted practice"], answer: 3, explanation: "She concludes it 'was never a gift at all, merely the sediment of ten thousand unassisted journeys'." }
    ]
  },
  {
    id: "cpe-rmc5-02",
    title: "The Tyranny of the Definitive Edition",
    text: "Somewhere in most readers' minds lurks a quiet assumption: that behind the paperback in our hands stands a single, stable text — the novel as the author finally intended it — and that the scholarly apparatus of publishing exists to deliver that text to us undamaged. It is an assumption editors themselves did much to encourage during the twentieth century, when the phrase 'definitive edition' became both a scholarly ideal and a marketing device. The trouble is that the closer one looks at how books actually come into being, the more the single authoritative text dissolves. Novels exist as manuscripts overwritten by second thoughts, typescripts amended by nervous publishers, first editions corrected in later printings, and revised versions produced decades on by authors who had, in every sense, changed their minds. Which of these is the novel? The question is not pedantic. Henry James rewrote his early works so thoroughly for the New York Edition that admirers of the originals regard the revisions as acts of vandalism committed by an older writer upon a younger one; readers of Wordsworth must choose between a Prelude of 1805 and one of 1850 that differ profoundly in temperament. The editor's traditional answer — final authorial intention — sounds decisive but merely relocates the difficulty. Intention when? Under whose influence? An author bullied by a publisher into cutting a chapter has intentions, too, and so does one restoring it forty years later with failing memory of the original impulse. Some modern editors have accordingly abandoned the search for a single text altogether, producing parallel versions or genetic editions that display the work as a process, its layers visible like strata in rock. Purists object that no one reads a novel this way, and they are largely right; the common reader wants a book, not an archaeological site. Yet there is something salutary in the reminder that the object we treat as fixed was once fluid, contested, and plural. A definitive edition is not a discovery but a decision — a perfectly respectable thing for an editor to make, provided neither editor nor reader mistakes it for the recovery of something that never singly existed.",
    questions: [
      { q: "What assumption does the writer say most readers hold?", options: ["That a single stable text lies behind each published book", "That paperbacks are less reliable than hardbacks", "That editors damage texts in transmission", "That authors dislike scholarly editions"], answer: 0, explanation: "Readers assume 'a single, stable text — the novel as the author finally intended it' — stands behind their copy." },
      { q: "Why does the writer list manuscripts, typescripts and revised versions?", options: ["To praise the thoroughness of modern publishing", "To show the many states in which a novel exists", "To explain why first editions are valuable", "To criticise careless authors"], answer: 1, explanation: "The list shows the authoritative single text 'dissolves' into many differing states." },
      { q: "The example of Henry James illustrates", options: ["an author whose revisions some readers reject", "a publisher interfering with a manuscript", "the difficulty of dating early works", "an editor restoring a censored chapter"], answer: 0, explanation: "Admirers of the originals regard James's revisions 'as acts of vandalism' by his older self." },
      { q: "What is the writer's objection to 'final authorial intention'?", options: ["Authors rarely record their intentions", "It ignores the publisher's legal rights", "It merely shifts the problem rather than solving it", "It applies only to poetry"], answer: 2, explanation: "The answer 'sounds decisive but merely relocates the difficulty. Intention when? Under whose influence?'" },
      { q: "How does the writer regard genetic editions?", options: ["As the only honest way to publish", "As commercially superior to paperbacks", "As unreadable and therefore worthless", "As instructive though not how most people read"], answer: 3, explanation: "Purists 'are largely right' that no one reads this way, yet the reminder of fluidity is 'salutary'." },
      { q: "What final view does the writer take of definitive editions?", options: ["They are legitimate decisions, not recoveries of a single original", "They should be abandoned in favour of archaeology", "They recover the author's one true text", "They are purely marketing inventions"], answer: 0, explanation: "'A definitive edition is not a discovery but a decision' — respectable, so long as no one mistakes it for recovery." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
