/* CPE Prep extra bank: vocab wave 6 */
(function () {
  var BANK = [
    { front: "adumbrate", pos: "v.", def: "to outline or foreshadow something faintly", example: "The opening chapter adumbrates the tragedy to come.", zh: "略述；預示" },
    { front: "antediluvian", pos: "adj.", def: "ridiculously old-fashioned", example: "The office still runs on an antediluvian filing system.", zh: "老掉牙的" },
    { front: "asperity", pos: "n.", def: "harshness of tone or manner", example: "\"You are late again,\" she said with some asperity.", zh: "(語氣)嚴厲；刻薄" },
    { front: "august", pos: "adj.", def: "inspiring respect and admiration; dignified", example: "He addressed the august assembly of Nobel laureates.", zh: "威嚴的；令人敬畏的" },
    { front: "badinage", pos: "n.", def: "light-hearted teasing conversation", example: "The interview dissolved into friendly badinage.", zh: "打趣；玩笑話" },
    { front: "bathos", pos: "n.", def: "a sudden ludicrous descent from the serious to the trivial", example: "The solemn eulogy sank into bathos when his phone rang.", zh: "突降法；由莊重跌入可笑" },
    { front: "bifurcate", pos: "v.", def: "to divide into two branches", example: "The river bifurcates just below the old mill.", zh: "分岔為二" },
    { front: "blandishment", pos: "n.", def: "flattering words used to persuade someone", example: "She resisted the blandishments of the recruiters.", zh: "甜言蜜語；奉承" },
    { front: "bowdlerise", pos: "v.", def: "to remove parts of a text considered offensive", example: "Victorian editors bowdlerised Shakespeare for family reading.", zh: "刪改(文本)；淨化" },
    { front: "brackish", pos: "adj.", def: "slightly salty, as in river mouths", example: "Few fish tolerate the lagoon's brackish water.", zh: "半鹹的(水)" },
    { front: "calumny", pos: "n.", def: "the making of false and damaging statements about someone", example: "He sued the magazine for calumny.", zh: "誹謗" },
    { front: "captious", pos: "adj.", def: "fond of finding faults in trivial matters", example: "A captious reviewer counted every misplaced comma.", zh: "吹毛求疵的" },
    { front: "cavil", pos: "v.", def: "to make petty objections", example: "It seems ungrateful to cavil at so generous an offer.", zh: "挑剔；找碴" },
    { front: "contumacious", pos: "adj.", def: "stubbornly disobedient to authority", example: "The contumacious witness was jailed for contempt.", zh: "藐視權威的；抗命的" },
    { front: "corpulent", pos: "adj.", def: "fat, in a formal or literary register", example: "A corpulent gentleman occupied two seats.", zh: "肥胖的" },
    { front: "coruscating", pos: "adj.", def: "flashing with brilliance, often of wit or criticism", example: "Her coruscating review demolished the play in six paragraphs.", zh: "才氣煥發的；犀利奪目的" },
    { front: "crepuscular", pos: "adj.", def: "relating to twilight; active at dusk", example: "Bats are crepuscular hunters.", zh: "黃昏的；晨昏活動的" },
    { front: "cupidity", pos: "n.", def: "greed for money or possessions", example: "The scheme preyed on the cupidity of small investors.", zh: "貪婪" },
    { front: "decorous", pos: "adj.", def: "polite and suitable for the occasion", example: "The mourners maintained a decorous silence.", zh: "得體端莊的" },
    { front: "denouement", pos: "n.", def: "the final part of a story where everything is resolved", example: "The denouement reunites the twins after forty years.", zh: "結局；收場" },
    { front: "deracinate", pos: "v.", def: "to uproot someone from their native environment", example: "War deracinated an entire generation of villagers.", zh: "連根拔起；使離鄉背井" },
    { front: "diaphanous", pos: "adj.", def: "so delicate and thin as to be almost transparent", example: "She wore a diaphanous silk scarf.", zh: "輕薄透明的" },
    { front: "discomfit", pos: "v.", def: "to make someone feel uneasy or embarrassed", example: "The blunt question visibly discomfited the minister.", zh: "使窘迫" },
    { front: "dissolute", pos: "adj.", def: "living an immoral, self-indulgent life", example: "The heir squandered the estate in dissolute living.", zh: "放蕩的" },
    { front: "doughty", pos: "adj.", def: "brave and determined, in an old-fashioned register", example: "A doughty band of volunteers kept the library open.", zh: "剛毅勇敢的" },
    { front: "elegiac", pos: "adj.", def: "expressing sorrow, often for something past", example: "The memoir closes on an elegiac note.", zh: "哀婉的；輓歌式的" },
    { front: "emollient", pos: "adj.", def: "attempting to soothe and avoid confrontation", example: "His emollient reply defused the shareholders' anger.", zh: "安撫性的" },
    { front: "encomium", pos: "n.", def: "a formal speech or text of high praise", example: "The retiring professor received encomium after encomium.", zh: "頌詞" },
    { front: "ephemera", pos: "n.", def: "things enjoyed or used for only a short time", example: "The archive collects posters, tickets and other ephemera.", zh: "曇花一現之物；短命收藏品" },
    { front: "ersatz", pos: "adj.", def: "being an inferior artificial substitute", example: "The café served ersatz coffee made from chicory.", zh: "代用的；假冒的" },
    { front: "evanescent", pos: "adj.", def: "quickly fading from sight or memory", example: "Fame in the app era is peculiarly evanescent.", zh: "轉瞬即逝的" },
    { front: "exigency", pos: "n.", def: "an urgent need or demand of a situation", example: "The exigencies of war reshaped the whole economy.", zh: "迫切需要；緊急狀況" },
    { front: "expiate", pos: "v.", def: "to make amends for wrongdoing", example: "He spent his last years trying to expiate his betrayal.", zh: "贖罪" },
    { front: "expurgate", pos: "v.", def: "to remove objectionable material from a text", example: "The diaries were heavily expurgated before publication.", zh: "刪除(不當內容)" },
    { front: "extemporise", pos: "v.", def: "to speak or perform without preparation", example: "The pianist extemporised on a theme from the audience.", zh: "即興發揮" },
    { front: "fecund", pos: "adj.", def: "highly fertile or creatively productive", example: "It was the most fecund decade of her songwriting.", zh: "多產的；富饒的" },
    { front: "florid", pos: "adj.", def: "excessively ornate; also reddish in complexion", example: "His florid prose buries the plot in adjectives.", zh: "華麗浮誇的；紅潤的" },
    { front: "fulminate", pos: "v.", def: "to protest loudly and bitterly", example: "The columnist fulminated against the new tax.", zh: "猛烈抨擊" },
    { front: "fulsome", pos: "adj.", def: "excessively flattering, so as to seem insincere", example: "The fulsome introduction embarrassed the guest speaker.", zh: "過分恭維的" },
    { front: "hagiography", pos: "n.", def: "a biography that praises its subject uncritically", example: "The authorised life of the tycoon is pure hagiography.", zh: "美化式傳記；聖徒傳" },
    { front: "hidebound", pos: "adj.", def: "unwilling to change because of tradition", example: "The hidebound committee rejected every innovation.", zh: "墨守成規的" },
    { front: "imbroglio", pos: "n.", def: "a confused and embarrassing situation", example: "The visa imbroglio stranded the whole orchestra abroad.", zh: "混亂難堪的局面" },
    { front: "importune", pos: "v.", def: "to pester someone with persistent requests", example: "Fans importuned the star for selfies at every corner.", zh: "糾纏請求" },
    { front: "inure", pos: "v.", def: "to make someone used to something unpleasant", example: "Years on the wards inured her to the sight of blood.", zh: "使習以為常" },
    { front: "inveigle", pos: "v.", def: "to persuade someone by trickery or flattery", example: "He inveigled his way into the private reception.", zh: "誘騙；巧言哄騙" },
    { front: "jejune", pos: "adj.", def: "naive and simplistic; lacking substance", example: "The essay's jejune conclusions ignored decades of research.", zh: "幼稚空洞的" },
    { front: "jingoism", pos: "n.", def: "aggressive, boastful patriotism", example: "The tabloids whipped up jingoism before the match.", zh: "沙文主義；好戰愛國主義" },
    { front: "lachrymose", pos: "adj.", def: "tearful; tending to cause tears", example: "The film's lachrymose finale felt manipulative.", zh: "催淚的；愛哭的" },
    { front: "lambaste", pos: "v.", def: "to criticise someone very harshly", example: "The report lambastes the ministry for waste.", zh: "痛批" },
    { front: "languid", pos: "adj.", def: "slow, relaxed and lacking energy", example: "They spent a languid afternoon on the veranda.", zh: "慵懶的" },
    { front: "libertine", pos: "n.", def: "a person who lives without moral restraint", example: "The poet cultivated his reputation as a libertine.", zh: "放蕩不羈者" },
    { front: "limpid", pos: "adj.", def: "perfectly clear, of water, eyes or style", example: "She writes limpid prose that any reader can follow.", zh: "清澈的；明晰的" },
    { front: "meretricious", pos: "adj.", def: "superficially attractive but without real value", example: "The lobby's meretricious glitter fooled nobody.", zh: "華而不實的" },
    { front: "mordant", pos: "adj.", def: "sharply sarcastic in a critical way", example: "Her mordant wit enlivened the dullest meetings.", zh: "辛辣諷刺的" },
    { front: "noisome", pos: "adj.", def: "extremely unpleasant, especially in smell", example: "A noisome vapour rose from the blocked drain.", zh: "惡臭的；令人作嘔的" },
    { front: "ostensible", pos: "adj.", def: "stated as a reason but perhaps not true", example: "The ostensible purpose of his visit was research.", zh: "表面上的" },
    { front: "panegyric", pos: "n.", def: "a public speech of enthusiastic praise", example: "The funeral panegyric lasted nearly an hour.", zh: "頌揚演說" },
    { front: "parlous", pos: "adj.", def: "dangerously uncertain, of a situation", example: "The theatre's finances are in a parlous state.", zh: "岌岌可危的" },
    { front: "pastiche", pos: "n.", def: "a work imitating the style of another artist or period", example: "The hotel is a cheerful pastiche of Venetian Gothic.", zh: "模仿拼湊之作" },
    { front: "pellucid", pos: "adj.", def: "transparently clear in appearance or meaning", example: "His pellucid explanations made calculus seem easy.", zh: "清澈透明的；極明晰的" },
    { front: "penurious", pos: "adj.", def: "extremely poor; unwilling to spend", example: "The artist's penurious final years were spent in one room.", zh: "赤貧的；吝嗇的" },
    { front: "picayune", pos: "adj.", def: "petty and of little importance", example: "The audit obsessed over picayune expense claims.", zh: "微不足道的" },
    { front: "probity", pos: "n.", def: "complete honesty and integrity", example: "Judges must be of unquestioned probity.", zh: "正直" },
    { front: "prolix", pos: "adj.", def: "using far too many words", example: "The prolix contract runs to four hundred pages.", zh: "冗長囉嗦的" },
    { front: "raconteur", pos: "n.", def: "a person skilled at telling entertaining stories", example: "A born raconteur, he held the table spellbound.", zh: "說故事高手" },
    { front: "rebarbative", pos: "adj.", def: "unattractive and off-putting", example: "The manual is written in rebarbative legal jargon.", zh: "令人反感的" },
    { front: "refulgent", pos: "adj.", def: "shining very brightly, in literary register", example: "The temple's refulgent dome dazzled pilgrims.", zh: "光輝燦爛的" },
    { front: "rubicund", pos: "adj.", def: "having a healthy reddish face", example: "A rubicund farmer waved from the gate.", zh: "紅光滿面的" },
    { front: "solipsism", pos: "n.", def: "the view that only one's own mind is certain to exist; extreme self-centredness", example: "Social media is often accused of breeding solipsism.", zh: "唯我論；極度自我中心" },
    { front: "splenetic", pos: "adj.", def: "bad-tempered and spiteful", example: "The critic's splenetic column spared no one.", zh: "暴躁易怒的" },
    { front: "stoical", pos: "adj.", def: "enduring hardship without complaint", example: "She remained stoical throughout the long treatment.", zh: "堅忍的" },
    { front: "stygian", pos: "adj.", def: "extremely dark, as of the underworld", example: "The power cut plunged the tunnels into stygian gloom.", zh: "漆黑如冥河的" },
    { front: "sybarite", pos: "n.", def: "a person devoted to luxury and pleasure", example: "The spa caters to sybarites with heated marble floors.", zh: "享樂主義者" },
    { front: "torpid", pos: "adj.", def: "mentally or physically inactive; sluggish", example: "The heat left the whole town torpid by noon.", zh: "呆滯遲鈍的" },
    { front: "verdant", pos: "adj.", def: "green with lush vegetation", example: "The abbey sits amid verdant water meadows.", zh: "翠綠的" },
    { front: "vicissitude", pos: "n.", def: "an unpredictable change of fortune", example: "The diary records the vicissitudes of a merchant family.", zh: "人世滄桑；變遷" },
    { front: "vitriolic", pos: "adj.", def: "full of bitter, corrosive criticism", example: "The debate descended into vitriolic personal attacks.", zh: "尖酸刻薄的" },
    { front: "vociferous", pos: "adj.", def: "expressing opinions loudly and insistently", example: "Vociferous objectors packed the planning meeting.", zh: "大聲疾呼的" },
    { front: "voluble", pos: "adj.", def: "talking fluently and at length", example: "Our voluble guide barely paused for breath.", zh: "滔滔不絕的" },
    { front: "welter", pos: "n.", def: "a large confused mass of things", example: "The ruling is buried in a welter of footnotes.", zh: "雜亂的一大堆" },
    { front: "winsome", pos: "adj.", def: "attractive in a fresh, innocent way", example: "Her winsome smile disarmed the sternest examiner.", zh: "惹人喜愛的" },
    { front: "zealot", pos: "n.", def: "a person with extreme, uncompromising beliefs", example: "Even fitness zealots take a rest day.", zh: "狂熱份子" }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
