/* CAE Prep extra bank: listening week 5 */
(function () {
var BANK = [
  { id: "cae-lis5-01", title: "Lecture Extract: The Psychology of Queuing", kind: "monologue",
    script: "Today I want to spend a few minutes on something so ordinary that we rarely think about it analytically: the queue. Waiting in line feels like dead time, but for psychologists and operations researchers it's a remarkably rich subject, because how long a wait feels bears surprisingly little relation to how long it actually is. The pioneering observation here came not from a laboratory but from an airport. Passengers at a major terminal complained persistently about waiting at baggage reclaim. Management's first response was conventional: they hired more handlers, and the average wait dropped to eight minutes. The complaints barely moved. What eventually solved the problem cost far less: the arrival gates were reassigned so that passengers had to walk six minutes to reach the carousel. Total time to bags was unchanged, but occupied time had replaced idle time — and the complaints all but vanished. The lesson, that occupied time feels shorter than unoccupied time, now shapes environments you move through every day: mirrors beside lifts, progress bars on screens, menus handed out while you stand outside a restaurant. A second principle matters just as much: uncertainty amplifies the discomfort of waiting far more than duration does. Studies consistently find that people wait more calmly for twenty minutes with an accurate estimate than for ten minutes with no information, which is why the countdown display at a bus stop does more for passenger satisfaction than a modest increase in service frequency would. And a third finding, perhaps the most consequential for anyone designing a service: perceived fairness dominates almost everything else. A single serpentine queue feeding multiple counters is often no faster on average than separate lines, but it eliminates the special misery of watching a later arrival get served first — and that, more than speed itself, is what people remember afterwards.",
    questions: [
      { q: "Why does the speaker consider queuing a rich subject for study?", options: ["Perceived waiting time differs greatly from actual time.", "Queues are becoming longer worldwide.", "Airports refuse to share their data.", "Laboratory research on it is impossible."], answer: 0, explanation: "How long a wait feels 'bears surprisingly little relation to how long it actually is'." },
      { q: "What finally reduced complaints at the airport?", options: ["Hiring additional baggage handlers.", "Making passengers walk further to the carousel.", "Cutting the average wait to eight minutes.", "Compensating passengers for delays."], answer: 1, explanation: "Reassigning gates meant a six-minute walk: occupied time replaced idle time and 'the complaints all but vanished'." },
      { q: "What do mirrors beside lifts and progress bars have in common?", options: ["They shorten actual waiting time.", "They were invented at airports.", "They keep waiting people occupied.", "They measure customer satisfaction."], answer: 2, explanation: "Both apply the lesson that 'occupied time feels shorter than unoccupied time'." },
      { q: "According to the speaker, why do bus stop countdowns work so well?", options: ["They persuade passengers buses are frequent.", "They make buses arrive on schedule.", "They entertain waiting passengers.", "They remove uncertainty from the wait."], answer: 3, explanation: "Uncertainty amplifies discomfort: accurate information calms waiting more than shorter waits without information." },
      { q: "What is the main advantage of a single serpentine queue?", options: ["It prevents later arrivals being served first.", "It is always faster than separate lines.", "It needs fewer counters.", "It shortens the average wait considerably."], answer: 0, explanation: "It is often no faster, 'but it eliminates the special misery of watching a later arrival get served first'." }
    ] },
  { id: "cae-lis5-02", title: "Interview: A Career in Simultaneous Interpreting", kind: "dialogue",
    script: "Presenter: My guest today is Tomas, who has worked for over a decade as a simultaneous interpreter at international conferences. Tomas, people often say interpreting is just very good bilingualism. How wrong are they?\nTomas: Substantially wrong, though I understand the assumption. Knowing two languages is the entry ticket, not the skill itself. What we're actually trained to do is listen, analyse, and speak at the same time, with a lag of a few seconds. That divided attention is profoundly unnatural — new trainees can usually either listen or speak, and the first months are about building the ability to do both without one channel collapsing.\nPresenter: Is that why interpreters work in pairs?\nTomas: Partly, yes. The cognitive load is such that quality measurably degrades after about half an hour, whether you feel tired or not — and crucially, you usually don't. So we swap every twenty to thirty minutes. The resting partner isn't resting, though: they're noting numbers, names, and terminology for whoever is live. Numbers are treacherous, by the way. They carry no context. If I miss a verb I can often reconstruct it from meaning; if I miss 'forty-seven billion', there's nothing to reconstruct it from.\nPresenter: What preparation happens before a conference?\nTomas: Far more than delegates imagine. For a technical meeting I might spend three days building a glossary — not just vocabulary, but who the speakers are, what positions their organisations took last time, which acronyms they use. The interpreting itself is the visible tenth of the iceberg.\nPresenter: And what about humour? Jokes must be a nightmare.\nTomas: Wordplay is genuinely untranslatable in real time. The honest options are to briefly explain the joke, or — and every interpreter has done this — to say: 'The speaker has made a joke; it would be appreciated if you laughed now.' Delegates always laugh, which, if you think about it, means the joke worked after all.\nPresenter: A diplomatic solution. Tomas, thank you.",
    questions: [
      { q: "According to Tomas, what is the core trained skill of interpreting?", options: ["Speaking two languages perfectly.", "Listening, analysing and speaking simultaneously.", "Memorising long speeches.", "Speaking faster than the presenter."], answer: 1, explanation: "Bilingualism is 'the entry ticket'; the skill is doing all three at once with a short lag." },
      { q: "Why do interpreters swap every twenty to thirty minutes?", options: ["Quality drops even when they feel fine.", "Conference rules require it.", "They begin to feel exhausted.", "Each interpreter covers different languages."], answer: 0, explanation: "Quality 'measurably degrades after about half an hour, whether you feel tired or not — and crucially, you usually don't'." },
      { q: "Why does Tomas describe numbers as 'treacherous'?", options: ["Speakers often misread them.", "They differ between languages.", "They cannot be reconstructed from context.", "Delegates rarely need them."], answer: 2, explanation: "A missed verb can be rebuilt from meaning, but a missed number carries 'no context' to rebuild from." },
      { q: "What does Tomas's iceberg comparison refer to?", options: ["The size of conference venues.", "The difficulty of technical vocabulary.", "The number of interpreters at a conference.", "The unseen preparation behind the visible work."], answer: 3, explanation: "Days of glossary-building and research mean the interpreting itself 'is the visible tenth of the iceberg'." },
      { q: "What does Tomas suggest about his 'please laugh now' solution?", options: ["It paradoxically achieves the joke's purpose.", "It always offends the speaker.", "It is forbidden in formal settings.", "It only works for wordplay."], answer: 0, explanation: "Delegates always laugh — 'which, if you think about it, means the joke worked after all'." }
    ] }
,
  {
    id: "cae-lis5-03",
    title: "Interview with a Foley Artist",
    kind: "dialogue",
    script: "Host: My guest today is Dana Whitfield, who has spent twenty years as a Foley artist, creating everyday sounds for films. Dana, most people have never even heard your job title.\nDana: And yet they've heard my work — that's the irony. When an actor walks across a room, the footsteps you hear in the cinema were almost certainly performed by someone like me, months later, in a studio full of junk.\nHost: Junk?\nDana: Lovingly curated junk! Gravel trays, forty pairs of shoes, half a car door. The professional secret is that the real object rarely sounds convincing. A punch recorded from an actual punch sounds thin, almost polite. We get something far more believable by thumping a cabbage wrapped in a wet towel.\nHost: Why not simply use sound libraries? Surely every footstep imaginable has been recorded by now.\nDana: Libraries are fine for background — traffic, birdsong. But footsteps carry character. A nervous person walks differently from a confident one, and the audience hears that, even if they couldn't tell you why. Performance is the part software can't fake: I watch the screen and act the scene with my feet.\nHost: Is the craft under threat from AI-generated sound?\nDana: The tools are improving, and for cheap productions they may soon be good enough. What reassures me is that directors keep coming back after trying them. They tell me the generated tracks are technically clean but emotionally flat — everything is correct and nothing is alive. My job was never really about making noises. It's about making an audience believe a world exists.",
    questions: [
      { q: "What does Dana identify as the irony of her profession?",
        options: ["Her studio is full of objects nobody wants", "Audiences have heard her work without knowing her job exists", "Actors receive credit for sounds she never made", "Films no longer need performed sound at all"],
        answer: 1,
        explanation: "'They've heard my work — that's the irony': her job title is unknown, her sounds are everywhere." },
      { q: "Why does she record a cabbage in a wet towel rather than a real punch?",
        options: ["Cabbages are cheaper than stunt actors", "Real punches would injure the performers", "Wet towels are easier to keep in a studio", "A real punch sounds thin and unconvincing"],
        answer: 3,
        explanation: "'A punch recorded from an actual punch sounds thin, almost polite' — the substitute is 'far more believable'." },
      { q: "According to Dana, why can't sound libraries replace performed footsteps?",
        options: ["Libraries are too expensive for most studios", "Library recordings are technically poor", "Footsteps convey character that audiences can sense", "Libraries contain too few types of shoes"],
        answer: 2,
        explanation: "'Footsteps carry character' — audiences hear the difference between a nervous and a confident walk." },
      { q: "What reassures Dana about AI-generated sound?",
        options: ["Directors return to her after finding AI tracks emotionally flat", "AI tools have stopped improving in recent years", "Cheap productions cannot afford the software", "Audiences boycott films with generated sound"],
        answer: 0,
        explanation: "Directors 'keep coming back', saying generated tracks are 'technically clean but emotionally flat'." },
      { q: "How does Dana define the real purpose of her job?",
        options: ["Collecting rare objects for film studios", "Recording noises as accurately as possible", "Teaching actors to walk more convincingly", "Making an audience believe a world exists"],
        answer: 3,
        explanation: "'My job was never really about making noises. It's about making an audience believe a world exists.'" }
    ]
  }
,
  { id: "cae-lis5-04", title: "Lecture Extract: Why Cities Sound the Way They Do", kind: "monologue",
    script: "Good afternoon. I'd like to begin with a confession: I am about to try to convince you that the sound of your city deserves the same careful attention that architects lavish on its appearance — and that for most of the twentieth century, we got this profoundly wrong. Urban sound planning, where it existed at all, was purely defensive. The discipline concerned itself with noise abatement: decibel limits, insulation standards, barriers along motorways. Sound was treated exclusively as a pollutant — something to be reduced, deflected or, ideally, eliminated. What this framework entirely failed to grasp is that a city stripped of sound is not a pleasant city; it is a dead one. Consider what researchers call the acoustic signature of a place. The Rambla in Barcelona does not sound like a Tokyo shopping street, which in turn sounds nothing like a Cairo market, and these differences are not accidental. They emerge from building materials, street width, commercial culture, even climate — open windows transmit domestic life to the street in ways that sealed facades never can. When planners flatten these signatures, replacing them with the uniform hum of traffic and air conditioning, something culturally significant is lost, though it rarely appears in any environmental impact assessment. The more progressive approach, sometimes called soundscape design, asks not 'how do we make cities quieter?' but 'what do we want to hear?' A celebrated example is a square in Sheffield where designers deliberately channelled water over textured steel precisely so that its sound would mask the adjacent dual carriageway — not silence, but strategic replacement. Fountains, importantly, are democratic: unlike a concert hall, nobody is charged admission to listen. My research group recently completed a three-year study asking residents in four European cities to keep sound diaries. The findings surprised us. The sounds people treasured most were rarely spectacular — not cathedral bells or famous fountains, but what one participant memorably called the small proofs of life: a neighbour practising the piano, the shutter of the bakery rising at dawn, children in an unseen playground. Which suggests, I think, a rather humbling conclusion for my profession: the best urban soundscapes are not designed at all. They are simply permitted — by planning decisions that keep bakeries, pianos and playgrounds within earshot of daily life.",
    questions: [
      { q: "What criticism does the speaker make of twentieth-century sound planning?", options: ["It treated sound purely as a pollutant to be reduced.", "It spent too much money on insulation.", "It ignored decibel limits entirely.", "It prioritised sound over visual design."], answer: 0, explanation: "The discipline was 'purely defensive', treating sound 'exclusively as a pollutant' to be reduced or eliminated." },
      { q: "What point is made about acoustic signatures?", options: ["They are strongest in Mediterranean cities.", "They arise from materials, street design, culture and climate.", "They are deliberately created by planners.", "They appear in most impact assessments."], answer: 1, explanation: "Differences between cities 'emerge from building materials, street width, commercial culture, even climate'." },
      { q: "Why is the Sheffield square mentioned?", options: ["It is the quietest square in Europe.", "Its concert hall charges no admission.", "Water sound was deliberately used to mask traffic noise.", "It failed to reduce noise as planned."], answer: 2, explanation: "Designers channelled water over textured steel 'precisely so that its sound would mask the adjacent dual carriageway'." },
      { q: "What surprised the researchers about the sound diaries?", options: ["Residents wanted more spectacular sounds.", "Most participants abandoned the study.", "Cathedral bells were the most treasured sound.", "People most valued modest everyday sounds."], answer: 3, explanation: "The treasured sounds 'were rarely spectacular' — a piano, a bakery shutter, unseen children playing." },
      { q: "What 'humbling conclusion' does the speaker draw?", options: ["The best soundscapes are permitted rather than designed.", "His profession should design more fountains.", "Residents should not be consulted on sound.", "Cities can never be made pleasant."], answer: 0, explanation: "The best soundscapes 'are not designed at all. They are simply permitted' by everyday planning decisions." }
    ] },
  { id: "cae-lis5-05", title: "Interview: Restoring Silent Films for Modern Audiences", kind: "dialogue",
    script: "Interviewer: My guest today is film restorer Elena Marchetti, whose team recently completed a four-year restoration of a 1922 silent epic that many historians had written off as lost for ever. Elena, where does a project like this actually begin?\nElena: With detective work, not technology — that's what surprises people. The film existed in fragments scattered across five countries. A reel in a Prague archive, another mislabelled in a private collection in Argentina, forty minutes in a Dutch museum's cold storage. The Argentine reel was catalogued under a completely different title, and it was only found because a doctoral student noticed that the description of a shipwreck scene matched nothing else from that year.\nInterviewer: And the fragments presumably don't match each other.\nElena: Precisely. Different copies were cut differently for different markets — censors in one country removed scenes that another considered harmless. Beyond that, each print has aged in its own way. So before touching a single frame we spent eight months simply establishing what the film originally was — using the director's shooting notes, studio correspondence, even reviews in provincial newspapers that described scenes no surviving print contains. We know a garden sequence existed because three separate critics complained it was too long. It remains lost, so we represent it with production photographs and an explanatory title card.\nInterviewer: Some purists object to that approach, I gather.\nElena: They do, and I understand the discomfort. Our rule is transparency: everything we reconstruct or infer is documented, and the difference is visible to anyone who wants to see it. What I resist is the fantasy of neutrality — the idea that there is some untouched original we could simply reveal. Every surviving print is already an interpretation, cut by distributors and censors we'll never identify. Restoration is choosing between interpretations, and pretending otherwise is the only truly dishonest option.\nInterviewer: The premiere used live music, as in 1922. Whose decision was that?\nElena: Mine, and it was non-negotiable! The original score survived in the composer's family archive, annotated in his own hand. Hearing it performed by a full orchestra, synchronised to the restored image, the audience wasn't watching a historical artefact; they were watching a film. An elderly woman told me afterwards it was the first time she'd understood why her grandmother spoke about cinema as though it were magic. Four years of work justified in a single sentence.",
    questions: [
      { q: "How was the mislabelled Argentine reel identified?", options: ["A student matched a scene description to no other film of that year.", "The archive relabelled its whole collection.", "Elena's team travelled to Argentina to search.", "The composer's family recognised it."], answer: 0, explanation: "A doctoral student noticed the shipwreck scene description 'matched nothing else from that year'." },
      { q: "Why did the team spend eight months before touching any film?", options: ["The fragments needed to defrost slowly.", "They were establishing what the film originally was.", "They were negotiating with five governments.", "They had to raise funding first."], answer: 1, explanation: "They used shooting notes, correspondence and reviews to establish the original form before restoration began." },
      { q: "How is the lost garden sequence handled in the restoration?", options: ["It was refilmed with modern actors.", "It is simply omitted without comment.", "It is represented by photographs and an explanatory card.", "It was reconstructed from a censor's copy."], answer: 2, explanation: "The sequence 'remains lost, so we represent it with production photographs and an explanatory title card'." },
      { q: "What is Elena's response to purist critics?", options: ["She admits her method is dishonest.", "She says censors should have been consulted.", "She no longer documents her changes.", "She argues no neutral untouched original exists."], answer: 3, explanation: "She resists 'the fantasy of neutrality': every surviving print is already an interpretation." },
      { q: "Why does Elena consider the premiere a success?", options: ["An audience member finally understood cinema's old magic.", "The orchestra performed without errors.", "Four newspapers praised the restoration.", "The composer's family attended."], answer: 0, explanation: "The elderly woman's remark about her grandmother made 'four years of work justified in a single sentence'." }
    ] },
  { id: "cae-lis5-06", title: "Talk: The Hidden Economics of Secondhand Bookshops", kind: "monologue",
    script: "People assume I run a secondhand bookshop out of romantic stubbornness, and they're about half right. What they miss is that the survivors in this trade — and there are more of us than the obituaries for the high street suggest — operate on an economic logic that would look familiar to any hedge fund manager, just with smaller numbers and more dust. Let me explain what actually pays my rent. It is emphatically not the fiction shelves. Paperback novels are, commercially speaking, wallpaper: they draw people in, they make the shop look like a shop, but their margins barely cover the shelf space. A two-pound paperback that took thirty seconds to price has to be sold four hundred times to pay one month's rent. What pays the rent is the stock most visitors walk straight past: technical manuals for obsolete machinery, regimental histories, Victorian guides to beekeeping. Specialist stock finds specialist buyers, and specialist buyers do not haggle. An engineer restoring a 1930s printing press will pay ninety pounds for the maintenance manual without blinking, because I am, quite literally, the only place on earth that has it. The internet was supposed to kill this business, and it did kill the lazy version of it. What it actually did to the rest of us was more interesting: it repriced everything with brutal honesty. Books I'd been optimistically pricing at twenty pounds turned out to be worth two; books gathering dust at two pounds turned out to be worth two hundred. The dealers who suffered were the ones whose expertise was, shall we say, performative. The other thing no one warns you about is that buying is harder than selling. Anyone can sell a rare book; the skill is recognising one in a cardboard box of house-clearance junk that smells of cats. I once found a first edition, inscribed by the author, in a box I'd bought mainly for the box. That single volume paid for my daughter's first year at university. The seller had priced the whole box at five pounds, and before you judge me — I went back and gave him a great deal more. Partly conscience, mainly reputation: in a trade this small, the story of the dealer who cheated a widow travels faster than any advertisement, and it never, ever stops travelling.",
    questions: [
      { q: "What does the speaker say about paperback fiction?", options: ["It attracts customers but earns almost nothing.", "It is the core of his profits.", "He refuses to stock it.", "It sells best online."], answer: 0, explanation: "Fiction is 'commercially speaking, wallpaper' — it draws people in but margins barely cover shelf space." },
      { q: "Why do specialist books pay the rent?", options: ["They cost nothing to acquire.", "Specialist buyers pay high prices without haggling.", "They sell in very large quantities.", "Libraries buy them in bulk."], answer: 1, explanation: "'Specialist stock finds specialist buyers, and specialist buyers do not haggle' — like the engineer paying ninety pounds." },
      { q: "What effect did the internet have on the trade?", options: ["It doubled the value of all old books.", "It killed every secondhand bookshop.", "It exposed which dealers had genuine expertise.", "It made buying easier than selling."], answer: 2, explanation: "The internet 'repriced everything with brutal honesty', ruining dealers whose expertise was 'performative'." },
      { q: "What does the story of the five-pound box illustrate?", options: ["Sellers always know what they own.", "First editions are usually worthless.", "House clearances should be avoided.", "The real skill of the trade is recognising value when buying."], answer: 3, explanation: "'Buying is harder than selling' — the skill is spotting a rare book among junk." },
      { q: "Why did the speaker return to pay the seller more?", options: ["Mainly because reputation is everything in a small trade.", "The seller demanded the book back.", "A court ordered him to do so.", "His daughter insisted on it."], answer: 0, explanation: "'Partly conscience, mainly reputation' — the story of a cheating dealer 'never, ever stops travelling'." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
