/* CAE Prep extra bank: listening week 5 */
(function () {
var BANK = [
  { id: "cae-lis5-01", title: "Lecture Extract: The Psychology of Queuing", kind: "monologue",
    script: "Today I want to spend a few minutes on something so ordinary that we rarely think about it analytically: the queue. Waiting in line feels like dead time, but for psychologists and operations researchers it's a remarkably rich subject, because how long a wait feels bears surprisingly little relation to how long it actually is. The pioneering observation here came not from a laboratory but from an airport. Passengers at a major terminal complained persistently about waiting at baggage reclaim. Management's first response was conventional: they hired more handlers, and the average wait dropped to eight minutes. The complaints barely moved. What eventually solved the problem cost far less: the arrival gates were reassigned so that passengers had to walk six minutes to reach the carousel. Total time to bags was unchanged, but occupied time had replaced idle time — and the complaints all but vanished. The lesson, that occupied time feels shorter than unoccupied time, now shapes environments you move through every day: mirrors beside lifts, progress bars on screens, menus handed out while you stand outside a restaurant. A second principle matters just as much: uncertainty amplifies the discomfort of waiting far more than duration does. Studies consistently find that people wait more calmly for twenty minutes with an accurate estimate than for ten minutes with no information, which is why the countdown display at a bus stop does more for passenger satisfaction than a modest increase in service frequency would. And a third finding, perhaps the most consequential for anyone designing a service: perceived fairness dominates almost everything else. A single serpentine queue feeding multiple counters is often no faster on average than separate lines, but it eliminates the special misery of watching a later arrival get served first — and that, more than speed itself, is what people remember afterwards.",
    questions: [
      { q: "Why does the speaker consider queuing a rich subject for study?", options: ["Perceived waiting time differs greatly from actual time.", "Queues are becoming longer worldwide.", "Airports refuse to share their data.", "Laboratory research on it is impossible."], answer: 0, explanation: "How long a wait feels 'bears surprisingly little relation to how long it actually is'." },
      { q: "What finally reduced complaints at the airport?", options: ["Hiring additional baggage handlers.", "Making passengers walk further to the carousel.", "Cutting the average wait to eight minutes.", "Compensating passengers for delays."], answer: 1, explanation: "Reassigning gates meant a six-minute walk: occupied time replaced idle time and 'the complaints all but vanished'." },
      { q: "What do mirrors beside lifts and progress bars have in common?", options: ["They shorten actual waiting time.", "They were invented at airports.", "They keep waiting people occupied.", "They measure customer satisfaction."], answer: 2, explanation: "Both apply the lesson that 'occupied time feels shorter than unoccupied time'." },
      { q: "According to the speaker, why do bus stop countdowns work so well?", options: ["They persuade passengers buses are frequent.", "They make buses arrive on schedule.", "They entertain waiting passengers.", "They remove uncertainty from the wait."], answer: 3, explanation: "Uncertainty amplifies discomfort: accurate information calms waiting more than shorter waits without information." },
      { q: "What is the main advantage of a single serpentine queue?", options: ["It prevents later arrivals being served first.", "It is always faster than separate lines.", "It needs fewer counters.", "It shortens the average wait considerably."], answer: 0, explanation: "It is often no faster, 'but it eliminates the special misery of watching a later arrival get served first'." }
    ] },
  { id: "cae-lis5-02", title: "Interview: A Career in Simultaneous Interpreting", kind: "dialogue",
    script: "Presenter: My guest today is Tomas, who has worked for over a decade as a simultaneous interpreter at international conferences. Tomas, people often say interpreting is just very good bilingualism. How wrong are they?\nTomas: Substantially wrong, though I understand the assumption. Knowing two languages is the entry ticket, not the skill itself. What we're actually trained to do is listen, analyse, and speak at the same time, with a lag of a few seconds. That divided attention is profoundly unnatural — new trainees can usually either listen or speak, and the first months are about building the ability to do both without one channel collapsing.\nPresenter: Is that why interpreters work in pairs?\nTomas: Partly, yes. The cognitive load is such that quality measurably degrades after about half an hour, whether you feel tired or not — and crucially, you usually don't. So we swap every twenty to thirty minutes. The resting partner isn't resting, though: they're noting numbers, names, and terminology for whoever is live. Numbers are treacherous, by the way. They carry no context. If I miss a verb I can often reconstruct it from meaning; if I miss 'forty-seven billion', there's nothing to reconstruct it from.\nPresenter: What preparation happens before a conference?\nTomas: Far more than delegates imagine. For a technical meeting I might spend three days building a glossary — not just vocabulary, but who the speakers are, what positions their organisations took last time, which acronyms they use. The interpreting itself is the visible tenth of the iceberg.\nPresenter: And what about humour? Jokes must be a nightmare.\nTomas: Wordplay is genuinely untranslatable in real time. The honest options are to briefly explain the joke, or — and every interpreter has done this — to say: 'The speaker has made a joke; it would be appreciated if you laughed now.' Delegates always laugh, which, if you think about it, means the joke worked after all.\nPresenter: A diplomatic solution. Tomas, thank you.",
    questions: [
      { q: "According to Tomas, what is the core trained skill of interpreting?", options: ["Speaking two languages perfectly.", "Listening, analysing and speaking simultaneously.", "Memorising long speeches.", "Speaking faster than the presenter."], answer: 1, explanation: "Bilingualism is 'the entry ticket'; the skill is doing all three at once with a short lag." },
      { q: "Why do interpreters swap every twenty to thirty minutes?", options: ["Quality drops even when they feel fine.", "Conference rules require it.", "They begin to feel exhausted.", "Each interpreter covers different languages."], answer: 0, explanation: "Quality 'measurably degrades after about half an hour, whether you feel tired or not — and crucially, you usually don't'." },
      { q: "Why does Tomas describe numbers as 'treacherous'?", options: ["Speakers often misread them.", "They differ between languages.", "They cannot be reconstructed from context.", "Delegates rarely need them."], answer: 2, explanation: "A missed verb can be rebuilt from meaning, but a missed number carries 'no context' to rebuild from." },
      { q: "What does Tomas's iceberg comparison refer to?", options: ["The size of conference venues.", "The difficulty of technical vocabulary.", "The number of interpreters at a conference.", "The unseen preparation behind the visible work."], answer: 3, explanation: "Days of glossary-building and research mean the interpreting itself 'is the visible tenth of the iceberg'." },
      { q: "What does Tomas suggest about his 'please laugh now' solution?", options: ["It paradoxically achieves the joke's purpose.", "It always offends the speaker.", "It is forbidden in formal settings.", "It only works for wordplay."], answer: 0, explanation: "Delegates always laugh — 'which, if you think about it, means the joke worked after all'." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
