/* CAE Prep bank: Reading multiple choice (C1) — wave 8 */
(function () {
var BANK = [
  {
    id: "cae-rmc8-01",
    title: "The Tyranny of the Better Option",
    text: "There is a well-documented finding in consumer research that a display of six jams sells more than a display of twenty-four. The result has been repeated, disputed, qualified and repeated again, and the argument about its reliability has rather obscured the more interesting question, which is not whether choice reduces sales but what abundant choice does to the chooser afterwards.\nPsychologists distinguish between two approaches to any decision. The satisficer identifies a threshold of acceptability and takes the first option that clears it. The maximiser searches for the best available option and stops only when convinced that nothing better exists. In a world of limited options the difference is slight. In a world where a modest purchase can be compared against four hundred alternatives, the maximiser's method becomes not merely time-consuming but self-defeating, because the standard of comparison expands as fast as the search.\nWhat the research suggests, consistently, is that maximisers achieve better outcomes and feel worse about them. They secure higher starting salaries and report lower satisfaction with their jobs; they buy better equipment and spend longer wondering whether they should have bought something else. The mechanism is not mysterious. A decision made after exhaustive comparison carries with it a detailed knowledge of the alternatives that were rejected, and every subsequent disappointment can be measured against a specific unchosen possibility.\nThe conventional response is to advise people to lower their standards, which is both patronising and impractical. A more useful reading is that the cost of the search should be counted as part of the price. Four hours spent comparing insurance policies to save eleven pounds is not thrift; it is unpaid work, undertaken voluntarily, at a rate of remuneration nobody would accept from an employer.\nThe more difficult implication concerns the design of the systems that present us with choices. Where an institution offers a hundred options in a domain that most people encounter once or twice in a lifetime, it has not created freedom; it has transferred a burden of research from an organisation that could do it once to individuals who must each do it separately and badly. The proliferation of options is frequently defended in the language of empowerment. It might more honestly be described as a redistribution of labour, and the beneficiaries are not, on the whole, the people doing the choosing.",
    questions: [
      { q: "What does the writer say about the jam experiment?", options: ["The argument about it has distracted from a better question","It applies only to food purchases","It was never properly repeated","Its findings have been conclusively disproved"], answer: 0, explanation: "'The result has been repeated, disputed, qualified and repeated again, and the argument about its reliability has rather obscured the more interesting question'." },
      { q: "How does a maximiser differ from a satisficer?", options: ["They avoid making decisions altogether","They continue searching until certain nothing better exists","They rely on the recommendations of others","They set a threshold and accept the first option that meets it"], answer: 1, explanation: "'The maximiser searches for the best available option and stops only when convinced that nothing better exists.'" },
      { q: "What paradox does the research identify?", options: ["Both groups make identical decisions","Neither group can explain its choices","Maximisers get better results but are less satisfied","Satisficers earn more than maximisers"], answer: 2, explanation: "'maximisers achieve better outcomes and feel worse about them'." },
      { q: "Why does exhaustive comparison lead to later dissatisfaction?", options: ["People forget why they chose","The chosen option is usually inferior","The process takes too long to justify","The rejected alternatives remain available for comparison"], answer: 3, explanation: "'every subsequent disappointment can be measured against a specific unchosen possibility'." },
      { q: "How does the writer view the advice to lower one's standards?", options: ["As patronising and impractical","As the only realistic solution","As supported by the evidence","As sensible but difficult"], answer: 0, explanation: "'The conventional response is to advise people to lower their standards, which is both patronising and impractical.'" },
      { q: "What is the writer's main criticism of organisations offering many options?", options: ["They reduce competition","They shift research work onto individuals","They raise prices unnecessarily","They confuse their own staff"], answer: 1, explanation: "'it has transferred a burden of research from an organisation that could do it once to individuals who must each do it separately and badly'." }
    ]
  },
  {
    id: "cae-rmc8-02",
    title: "What a City Owes Its Trees",
    text: "Municipal accounts have traditionally treated street trees as a cost. They appear in budgets under maintenance, alongside street lighting and the emptying of bins, and they generate complaints about leaves, roots and obstructed light with a regularity that no other item of infrastructure can match. It is unsurprising that a department under pressure removes more of them than it plants.\nThe last two decades have produced a serious attempt to put the other side of the ledger into comparable terms. Studies now assign monetary values to the interception of rainfall, the removal of particulates, the reduction of summer temperatures and the effect of tree cover on property values, and the totals are large enough to have changed policy in several cities. A mature street tree in a temperate city is generally valued at between four and eleven thousand pounds over its remaining life, against a planting and establishment cost of perhaps four hundred.\nThe arithmetic, however, contains an assumption that deserves more scrutiny than it usually receives, which is that the tree survives to maturity. Roughly a third of newly planted street trees die within their first five years, overwhelmingly from drought stress in the second and third summers, when the initial watering regime has been discontinued and the root system has not yet reached beyond the planting pit. A city that plants four thousand trees and waters them for one season is not investing in a canopy; it is conducting an expensive annual ceremony.\nThe more radical objection to the valuation approach is that it concedes the wrong ground. If a tree is defended because it intercepts eleven cubic metres of rainfall a year, it becomes vulnerable the moment a drainage engineer demonstrates that a tank would intercept more for less. Arguments framed entirely in the currency of the accountant can be defeated in that currency, and the qualities that lead residents to chain themselves to trees are not, on the whole, hydrological.\nThe most persuasive case may therefore be the least quantitative. A street tree is one of the few pieces of public infrastructure that improves for a century after installation and that nobody has to be trained to appreciate. It is also, notably, the only one that residents routinely name.",
    questions: [
      { q: "How have municipal budgets traditionally treated street trees?", options: ["As property assets","As an investment in the future","As a cost alongside other maintenance","As a health measure"], answer: 2, explanation: "'They appear in budgets under maintenance, alongside street lighting and the emptying of bins'." },
      { q: "What has changed in the last two decades?", options: ["Cities have stopped removing trees","Trees have become cheaper to plant","Complaints have decreased","Attempts have been made to value trees' benefits in money"], answer: 3, explanation: "'Studies now assign monetary values to the interception of rainfall, the removal of particulates'." },
      { q: "Which assumption does the writer question?", options: ["That the tree reaches maturity","That planting costs are low","That residents want more trees","That trees improve property values"], answer: 0, explanation: "'The arithmetic, however, contains an assumption that deserves more scrutiny than it usually receives, which is that the tree survives to maturity.'" },
      { q: "When do most newly planted trees die?", options: ["During transport","In the second and third summers","After ten years","In their first winter"], answer: 1, explanation: "'overwhelmingly from drought stress in the second and third summers'." },
      { q: "What is the writer's deeper objection to monetary valuation?", options: ["Residents do not understand it","The figures are usually inaccurate","It allows trees to be defeated by cheaper alternatives","It is too expensive to carry out"], answer: 2, explanation: "'Arguments framed entirely in the currency of the accountant can be defeated in that currency'." },
      { q: "What does the writer suggest is the strongest argument for street trees?", options: ["Their measurable environmental services", "Their contribution to drainage", "Their low maintenance costs", "Qualities that resist quantification"], answer: 3, explanation: "'The most persuasive case may therefore be the least quantitative.'" }
    ]
  },
  {
    id: "cae-rmc8-03",
    title: "The Unpaid Work of Being Ill",
    text: "A diagnosis of a long-term condition is generally described in terms of treatment. What patients describe, when asked, is administration. Appointments to be arranged around each other, referrals to be chased, test results to be transferred between departments that cannot see one another's records, prescriptions to be reordered on a cycle that never quite aligns with the consumption of the medicine.\nResearchers have begun to give this a name: treatment burden, defined as the workload imposed on a patient by their healthcare rather than by their illness. Studies attempting to quantify it have produced figures that surprise clinicians. A patient managing three common conditions may spend the equivalent of two working days a month on coordination alone, most of it during office hours, and almost none of it clinically necessary in the sense that a different arrangement of the same system would eliminate it.\nThe distribution of this burden is what makes it a matter of policy rather than inconvenience. It falls most heavily on those least equipped to carry it: patients whose conditions affect concentration or mobility, those without a landline or reliable internet, those working shifts, those for whom the language of the letters is not their first. The result is a system that is, in effect, means-tested by administrative stamina, and the test is applied precisely when a person's capacity to pass it is lowest.\nThe standard response is to offer patients better tools, and the standard tool is an application. This is not useless and it misidentifies the problem. An application that displays four appointments made by four departments has improved the display of the fragmentation; it has not addressed it. The work exists because the coordination that should occur between institutions has been devolved, silently and without acknowledgement, to the individual who is the only person present at every stage of their own care.\nA small number of services have taken the alternative approach and employed somebody to do the coordinating. The evaluations are consistently favourable and consistently ignored, for a reason that is structurally obvious: the costs of such a post fall on one budget, while the savings, in missed appointments not missed and admissions not required, are distributed across several others. It is a familiar shape. The work is invisible because it is unpaid, and it is unpaid because the person doing it has no way of sending anybody an invoice.",
    questions: [
      { q: "What do patients emphasise when describing a long-term condition?", options: ["Administrative work","The attitude of staff","Pain and symptoms","The cost of medicines"], answer: 0, explanation: "'What patients describe, when asked, is administration.'" },
      { q: "How is treatment burden defined?", options: ["The severity of the illness itself", "Work created by healthcare rather than by illness", "The financial cost of treatment", "The time spent with clinicians"], answer: 1, explanation: "'defined as the workload imposed on a patient by their healthcare rather than by their illness'." },
      { q: "Why does the writer regard the burden as a policy matter?", options: ["It costs the health service money", "It affects clinicians as well", "It falls hardest on those least able to bear it", "It is increasing every year"], answer: 2, explanation: "'It falls most heavily on those least equipped to carry it'." },
      { q: "What criticism does the writer make of applications?", options: ["Patients cannot use them","They duplicate existing letters","They are too expensive to develop","They display fragmentation rather than removing it"], answer: 3, explanation: "'has improved the display of the fragmentation; it has not addressed it'." },
      { q: "Why has the coordinator approach not spread?", options: ["Costs and savings fall on different budgets","Suitable staff cannot be recruited","Evaluations have been unfavourable","Patients dislike it"], answer: 0, explanation: "'the costs of such a post fall on one budget, while the savings... are distributed across several others'." },
      { q: "What does the writer's final sentence suggest?", options: ["Patients should be paid for their time", "The work is unrecognised because nobody bills for it", "Invoices would solve the problem", "Coordination cannot be improved"], answer: 1, explanation: "'The work is invisible because it is unpaid, and it is unpaid because the person doing it has no way of sending anybody an invoice.'" }
    ]
  },
  {
    id: "cae-rmc8-04",
    title: "When a Standard Becomes a Barrier",
    text: "Regulation is usually debated as though the only question were how much of it there should be. The more consequential question is who can afford to comply, because a rule that is trivially easy for a large producer and prohibitively expensive for a small one does not merely regulate a market; it reshapes it.\nConsider food certification. A scheme requiring documented traceability, laboratory testing at fixed intervals and an annual audit imposes a cost that is largely fixed rather than proportional. For a processor handling four thousand tonnes a year, the cost per tonne is negligible. For one handling forty, it may exceed the margin entirely. The rule is identical for both, and its effect is to remove the smaller producer from the market, which is an outcome nobody voted for and which appears in no impact assessment as an objective.\nThe defenders of such schemes make a reasonable point. The requirements exist because a failure of traceability in the food supply can be lethal, and the record of voluntary assurance is not encouraging. The difficulty is that the design of most schemes reflects the operational assumptions of the organisations that helped to write them, which are, almost invariably, the larger participants in the sector. The result is not corruption. It is something more ordinary: a set of rules that describes safety in terms that are natural to one kind of enterprise and alien to another.\nSeveral jurisdictions have experimented with proportionate alternatives, in which the obligation scales with volume or risk rather than applying uniformly. The results are mixed and instructive. Where the alternative route is genuinely equivalent in outcome, small producers survive and consumers are no worse protected. Where it is a lighter regime justified by sentiment about small businesses, it produces exactly the failures its critics predicted.\nThe conclusion is unwelcome to both sides of the usual argument. Deregulation as a general principle is no answer, since the risks the rules address are real. Uniformity as a general principle is no answer either, since it quietly determines the structure of an industry while claiming only to govern its safety. What is required is the harder and duller work of designing obligations that are equivalent in effect rather than identical in form, and there is no constituency that finds this exciting.",
    questions: [
      { q: "What does the writer say is the more important regulatory question?", options: ["How rules are enforced","How many rules exist","Who can afford to comply","Who writes the rules"], answer: 2, explanation: "'The more consequential question is who can afford to comply'." },
      { q: "Why do fixed compliance costs affect producers differently?", options: ["Small producers face different rules","Large producers pay more in total","Small producers receive subsidies","The cost per tonne is far higher for small producers"], answer: 3, explanation: "For a small processor 'it may exceed the margin entirely'." },
      { q: "How does the writer characterise the influence of large firms on rule-making?", options: ["As an ordinary reflection of their assumptions","As entirely beneficial","As legally improper","As deliberate corruption"], answer: 0, explanation: "'The result is not corruption. It is something more ordinary'." },
      { q: "What do experiments with proportionate rules show?", options: ["They always fail", "They succeed only when outcomes are genuinely equivalent", "They protect consumers better than uniform rules", "They are impossible to enforce"], answer: 1, explanation: "'Where the alternative route is genuinely equivalent in outcome, small producers survive and consumers are no worse protected.'" },
      { q: "What does the writer think of deregulation as a general principle?", options: ["It has never been tried","It is the obvious solution","It is no answer, because the risks are real","It should apply only to small firms"], answer: 2, explanation: "'Deregulation as a general principle is no answer, since the risks the rules address are real.'" },
      { q: "What does the writer advocate?", options: ["Abolishing certification schemes","Subsidies for small producers","Identical rules applied more strictly","Obligations equivalent in effect rather than identical in form"], answer: 3, explanation: "'designing obligations that are equivalent in effect rather than identical in form'." }
    ]
  },
  {
    id: "cae-rmc8-05",
    title: "Who Speaks for a Dead Writer",
    text: "The instruction was unambiguous. Burn everything. It was given by Kafka to Max Brod, who did not comply, and the resulting library of published work has made the episode the standard reference point in every subsequent argument about posthumous publication. It is invoked, almost always, in defence of disobedience.\nThe invocation is convenient and somewhat dishonest. Brod's decision is celebrated because the manuscripts turned out to be extraordinary, which is a judgement available only after the event and not to the person holding the papers. An executor deciding today whether to publish an unfinished novel is not choosing between literature and loss; they are choosing under uncertainty, and the cases in which disobedience produced an inferior book that damaged a reputation are, for obvious reasons, less frequently cited.\nThe legal position is clearer than the ethical one and less helpful than it appears. Copyright passes to an estate, and an estate may publish what it holds. The question of whether it should is unregulated, and estates vary enormously in their conduct: some suppress work for decades, others release fragments annually, and a few have taken the view that anything the author did not destroy was implicitly permitted, which is an interpretation with a strong commercial incentive behind it.\nThere is a further complication that literary discussion tends to avoid. The material published posthumously is frequently not the work but the workings: drafts, abandoned openings, notebooks. Presenting these as a book invites a reading they cannot sustain, and it alters the reputation of the finished work by surrounding it with evidence of how ordinary its beginnings were. Some writers would have regarded that as valuable. Most, on the evidence of what they said while alive, would not.\nThe reasonable position is probably an uncomfortable one. Instructions to destroy should be treated as significant rather than binding, since an author's judgement at the end of a life is not automatically the best judgement about the work. But the burden should fall on the person choosing to publish, and it should be discharged in public: an explanation of why, on the record, at the time. What actually happens is a silence in which a decision has been taken and nobody is required to account for it, and Kafka is mentioned somewhere in the introduction.",
    questions: [
      { q: "Why does the writer regard the Kafka reference as dishonest?", options: ["It relies on knowledge only available afterwards","Kafka's work is overrated","The instruction was ambiguous","Brod did not really receive such an instruction"], answer: 0, explanation: "'Brod's decision is celebrated because the manuscripts turned out to be extraordinary, which is a judgement available only after the event'." },
      { q: "Which cases are rarely mentioned in these arguments?", options: ["Cases where estates refused to publish", "Cases where disobedience produced an inferior book", "Cases involving legal disputes", "Cases from before 1900"], answer: 1, explanation: "'the cases in which disobedience produced an inferior book that damaged a reputation are, for obvious reasons, less frequently cited'." },
      { q: "What does the writer say about the legal position?", options: ["It prevents most publication","It resolves the ethical question","It is clearer but less helpful than it seems","It varies between countries"], answer: 2, explanation: "'The legal position is clearer than the ethical one and less helpful than it appears.'" },
      { q: "What problem arises from publishing drafts and notebooks?", options: ["They are usually incomplete","They rarely sell","They are difficult to read","They invite a reading they cannot support"], answer: 3, explanation: "'Presenting these as a book invites a reading they cannot sustain'." },
      { q: "What is the writer's view of instructions to destroy work?", options: ["They are significant but not binding","They have no legal force","They should always be obeyed","They should be ignored entirely"], answer: 0, explanation: "'Instructions to destroy should be treated as significant rather than binding'." },
      { q: "What does the writer say should accompany a decision to publish?", options: ["A delay of several decades","A public explanation at the time","Approval from the author's family","A legal ruling"], answer: 1, explanation: "'an explanation of why, on the record, at the time'." }
    ]
  },
  {
    id: "cae-rmc8-06",
    title: "The Trouble With Measuring Teachers",
    text: "Any serious attempt to improve schooling encounters the same obstacle within about a fortnight. Teaching quality varies enormously and matters enormously, and identifying it reliably has defeated every measurement system so far attempted at scale.\nThe intuitive approach is to measure the progress of pupils. Modern versions are considerably more sophisticated than raw examination results and attempt to isolate the contribution of the individual teacher by comparing a class's performance with what similar pupils achieved elsewhere. The statistical machinery is impressive. The stability of the results is not. A teacher ranked in the top fifth in one year has roughly a one in three chance of appearing in the bottom two fifths in the next, which is a degree of year-to-year variation that would be regarded as disqualifying in almost any other application.\nThe explanation is not that the measurement is careless. It is that a class of thirty is a small sample, that the pupils are not assigned at random, and that a single disruptive year or an unusually strong cohort moves the figure by more than any plausible change in teaching does. Where such measures are used to determine pay or employment, the effect is to introduce a substantial element of chance into a career, and to encourage precisely the behaviours that inflate the measure without improving the education, of which teaching to the test is only the most familiar.\nObservation, the obvious alternative, performs no better without expensive safeguards. Untrained observers agree with one another at rates barely above chance. Trained observers, using a structured protocol and multiple visits, achieve respectable reliability, and the cost of doing this properly for every teacher annually is prohibitive for most systems, which is why the practice is generally a single visit by a busy senior colleague and an outcome that is largely predictable in advance.\nThe most promising work has stopped asking which teachers are best and started asking what specific practices produce learning, and then how those practices spread. This is less satisfying administratively, since it produces no ranking and no obvious lever. It has the compensating advantage of being about the thing the system is supposed to be doing, and of not attaching a consequential judgement to a number that cannot bear the weight of it.",
    questions: [
      { q: "What obstacle does school improvement quickly encounter?", options: ["A shortage of teachers","Insufficient funding","The difficulty of identifying teaching quality reliably","Resistance from parents"], answer: 2, explanation: "'identifying it reliably has defeated every measurement system so far attempted at scale'." },
      { q: "What problem does the writer identify with progress measures?", options: ["They are illegal in some systems","They are too simple","They ignore examination results","Their results are unstable from year to year"], answer: 3, explanation: "A top-fifth teacher 'has roughly a one in three chance of appearing in the bottom two fifths in the next'." },
      { q: "What explains this instability?", options: ["Small samples and non-random classes","Dishonest reporting","Changes in the curriculum","Careless measurement"], answer: 0, explanation: "'a class of thirty is a small sample, that the pupils are not assigned at random'." },
      { q: "What happens when such measures affect pay?", options: ["Teaching improves rapidly", "Chance enters careers and unhelpful behaviour is encouraged", "Teachers leave the profession", "Measurement becomes more accurate"], answer: 1, explanation: "'the effect is to introduce a substantial element of chance into a career, and to encourage precisely the behaviours that inflate the measure'." },
      { q: "What does the writer say about untrained observers?", options: ["They focus on the wrong subjects","They are more reliable than statistics","They agree at rates barely above chance","They are cheaper and equally effective"], answer: 2, explanation: "'Untrained observers agree with one another at rates barely above chance.'" },
      { q: "What approach does the writer regard as most promising?", options: ["Increasing the number of observations","Abandoning measurement entirely","Ranking teachers more accurately","Identifying practices that produce learning and spreading them"], answer: 3, explanation: "'has stopped asking which teachers are best and started asking what specific practices produce learning'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
