/* CAE Prep bank: Reading multiple choice (C1) — wave 9 */
(function () {
var BANK = [
  {
    id: "cae-rmc9-01",
    title: "The Office That Never Went Paperless",
    text: "The paperless office was announced in 1975, in a business magazine article predicting that the document would be obsolete within a decade. Paper consumption in offices subsequently rose for twenty-five years and has fallen since, though not for the reasons the prediction assumed and not to anything approaching zero.\nThe most interesting work on why is not about technology at all. Studies of how people actually use documents found that paper survives because it does things screens do a badly: it can be spread out, so that four pages are visible simultaneously and can be compared by moving the eyes rather than the interface; it can be annotated without any decision about which tool or layer to annotate with; and it is spatially memorable, so that a reader recalls a passage as being on the lower left of a right-hand page.\nThese are not nostalgic preferences. They are properties, and where a task depends on them, paper persists regardless of policy. The document types that resisted digitisation longest were precisely those involving comparison, negotiation and drafting, and the ones that disappeared fastest were those that were never read as documents at all, such as internal circulation lists and printed reports consulted for a single figure.\nThe second finding is more awkward for the organisations that pursued the paperless office as an economy. In several documented cases, removing printers reduced paper consumption and increased the time taken to complete document-heavy tasks by considerably more than the saving was worth. The cost had moved rather than disappeared, from a line in the stationery budget, where it was visible and easy to attack, to the time of employees, where it was neither.\nThe underlying error is one that recurs whenever a physical practice is replaced by a digital one. The physical version's disadvantages are obvious and its functions are invisible, because nobody has ever had to specify them. What follows is a period in which the new system is defended on the grounds that the old one was wasteful, and a slower period in which the missing functions are gradually reinvented at greater expense, generally by people who have never heard of the article from 1975.",
    questions: [
      { q: "What happened to office paper use after the 1975 prediction?", options: ["It rose for twenty-five years","It remained unchanged","It has now reached zero","It fell immediately"], answer: 0, explanation: "'Paper consumption in offices subsequently rose for twenty-five years'." },
      { q: "According to the studies, why does paper persist?", options: ["Older workers prefer it","It has properties screens handle badly","Regulations require it","It is cheaper than screens"], answer: 1, explanation: "'paper survives because it does things screens do a badly'." },
      { q: "Which documents disappeared fastest?", options: ["Drafts and negotiations","Those used for comparison","Those never really read as documents","Legal contracts"], answer: 2, explanation: "'the ones that disappeared fastest were those that were never read as documents at all'." },
      { q: "What happened in organisations that removed printers?", options: ["Employees resigned","Paper use increased","Costs fell substantially","Tasks took longer, outweighing the saving"], answer: 3, explanation: "removing printers 'increased the time taken to complete document-heavy tasks by considerably more than the saving was worth'." },
      { q: "How does the writer describe what happened to the cost?", options: ["It moved to a less visible place","It was passed to customers","It was never measured","It was eliminated"], answer: 0, explanation: "'The cost had moved rather than disappeared'." },
      { q: "What general error does the writer identify?", options: ["Assuming employees resist change","Failing to see the functions of the old practice","Introducing changes too slowly","Overestimating the price of technology"], answer: 1, explanation: "'The physical version's disadvantages are obvious and its functions are invisible'." }
    ]
  },
  {
    id: "cae-rmc9-02",
    title: "The Economics of the Encore",
    text: "Nothing about the encore is spontaneous. The set list includes it, the lighting desk has cues for it, and the performers leave the stage knowing exactly how long they will remain in the wings. Audiences are aware of all this and applaud with undiminished conviction, which makes the ritual an unusually clear example of a convention that survives despite complete transparency about its artificiality.\nThe economic reading is straightforward enough. A concert is an experience good: its value cannot be assessed before purchase and is largely determined afterwards, in memory. The encore is positioned precisely where memory is most heavily weighted, at the end, and it converts a performance that has concluded into one that has been extended by apparent demand. The audience is not deceived. It is participating in the construction of a better memory, which is a service it has paid for.\nWhat is more interesting is where the convention breaks down. Classical concerts observe it inconsistently, and in some traditions it is regarded as vulgar. Certain performers have abandoned it explicitly, announcing in advance that there will be no encore and playing the final piece as the final piece, and the reported audience response is divided in a revealing way: those who attend frequently tend to approve, and those who attend rarely feel that something has been withheld.\nThat division suggests that the encore's function is informational as well as emotional. For an inexperienced audience it signals that the performance has been well received, which is not otherwise easy to judge from inside a hall. For a frequent attender the signal is redundant and the ritual becomes an irritation, particularly where it extends the evening past the last useful train.\nThe most persuasive objection to the practice is not aesthetic but structural. Where an encore is guaranteed, the material placed in it is by definition not part of the programme, and there is a strong incentive to reserve the best-known work for that slot. The result is a main programme that concludes at a deliberately lower point, so that the sequence can be rescued. An institution that did away with encores entirely would have to end its concerts properly, which is harder and, on the evidence of the few who have tried it, considerably more effective.",
    questions: [
      { q: "What does the writer emphasise about the encore?", options: ["It is unpopular with audiences","It is genuinely unplanned","It is entirely prearranged despite appearances","It is disappearing from concerts"], answer: 2, explanation: "'The set list includes it, the lighting desk has cues for it'." },
      { q: "Why is the encore placed at the end?", options: ["To allow latecomers to arrive","Because of lighting requirements","Because performers need a rest","Because memory weights endings heavily"], answer: 3, explanation: "'The encore is positioned precisely where memory is most heavily weighted, at the end'." },
      { q: "How does the writer characterise the audience's role?", options: ["They participate in constructing a memory","They increasingly object to it","They are deceived by the ritual","They are indifferent to it"], answer: 0, explanation: "'It is participating in the construction of a better memory'." },
      { q: "How do audiences react when encores are abandoned?", options: ["Everybody objects", "Frequent attenders approve, occasional ones feel deprived", "Nobody notices", "Occasional attenders approve most"], answer: 1, explanation: "'those who attend frequently tend to approve, and those who attend rarely feel that something has been withheld'." },
      { q: "What informational function does the encore serve?", options: ["It identifies the performers","It signals the interval","It shows the performance was well received","It indicates the length of the concert"], answer: 2, explanation: "'For an inexperienced audience it signals that the performance has been well received'." },
      { q: "What is the writer's structural objection?", options: ["Performers become tired","Audiences leave early","Encores make concerts too long","The main programme is deliberately weakened"], answer: 3, explanation: "'The result is a main programme that concludes at a deliberately lower point'." }
    ]
  },
  {
    id: "cae-rmc9-03",
    title: "Why Translations Grow Old",
    text: "A novel written in 1880 may still be read with pleasure in its original language. A translation of that novel made in 1880 will almost certainly feel dated, and one made in 1950 is beginning to. The observation is commonplace among translators and rarely examined, though the explanation matters for anybody deciding what a library should hold.\nThe usual account is that language changes and translations must keep up. This is true and insufficient, since the original is subject to the same passage of time and does not date in the same way. The difference lies in what a translation is doing. An original text establishes its own register; whatever archaism or oddity it contains becomes, over time, part of its character. A translation, by contrast, is continuously making a claim about equivalence: it asserts that this English corresponds to that Russian, and the claim is made in the idiom of the moment at which the translator worked.\nThat idiom is invisible to contemporaries and glaringly visible to their grandchildren. A translation from the 1950s is not merely old-fashioned; it is legibly of the 1950s in a way that the original is not legibly of the 1880s, because the original's period features are the subject and the translation's are an artefact of the process.\nThere is a second mechanism, less often noted. Scholarship advances, and a translator working today has access to a textual apparatus, a body of criticism and a set of established solutions to recurring problems that were unavailable a century earlier. Some older translations are not merely stylistically dated but demonstrably wrong in places, and a small number contain deliberate suppressions that reflect the publishing conventions of their period rather than anything in the source.\nThe practical consequence is that a canon of foreign literature requires periodic re-translation in a way that a domestic canon does not, and that this is a recurring cost which almost no funding structure acknowledges. It also produces an uncomfortable asymmetry. The reputation of a foreign writer in any given language is mediated by a document that has a shelf life, and when that document expires the writer does not become dated. The writer simply, and quietly, stops being read.",
    questions: [
      { q: "What is the central observation of the article?", options: ["Translations date faster than originals","Modern translations are inaccurate","Libraries hold too many translations","Old novels are unreadable"], answer: 0, explanation: "'A translation of that novel made in 1880 will almost certainly feel dated'." },
      { q: "Why is the usual explanation insufficient?", options: ["Language does not really change", "The original is subject to the same passage of time", "Translators work too slowly", "Readers do not notice"], answer: 1, explanation: "'the original is subject to the same passage of time and does not date in the same way'." },
      { q: "What claim does a translation continuously make?", options: ["That it improves on the original", "That it is complete", "That this text corresponds to that one", "That it is written for scholars"], answer: 2, explanation: "'it asserts that this English corresponds to that Russian'." },
      { q: "Why are a translation's period features more visible?", options: ["They are deliberately exaggerated","Readers know the date of publication","They are marked in the text","They are an artefact rather than the subject"], answer: 3, explanation: "'the original's period features are the subject and the translation's are an artefact of the process'." },
      { q: "What second mechanism does the writer identify?", options: ["Advances in scholarship since older translations","Declining language teaching","Competition between publishers","Changes in publishing economics"], answer: 0, explanation: "'a translator working today has access to a textual apparatus, a body of criticism'." },
      { q: "What happens when a translation expires?", options: ["The writer is re-evaluated","The writer quietly stops being read","A new edition appears automatically","The original is revised"], answer: 1, explanation: "'The writer simply, and quietly, stops being read.'" }
    ]
  },
  {
    id: "cae-rmc9-04",
    title: "In Defence of Dull Infrastructure",
    text: "Public investment tends to be announced in the form of objects: a bridge, a terminal, a line on a map with a name attached to it. The projects that most reliably improve daily life are of a different kind, and they are almost impossible to announce, because they consist of the continued functioning of things that already exist.\nMaintenance is structurally disadvantaged in every political system that has been studied. Its benefits are counterfactual, consisting of failures that did not occur and journeys that were not disrupted, and counterfactuals do not photograph well. A minister who defers four years of resurfacing releases money immediately and incurs a cost that arrives after the next election, distributed across thousands of people who will attribute it to something else. The incentive is not hidden; it is simply never described aloud.\nThe consequences are visible in the condition of assets rather than in any single dramatic event. Deferred maintenance behaves non-linearly: a road surface degrades slowly for a decade and then rapidly, and the cost of intervening after the transition is several times the cost of intervening before it. Every serious study of highway spending finds the same pattern, and every mature network contains a substantial quantity of assets that have passed the point at which repair was economic and are now waiting for replacement.\nThere is a further difficulty, which is that dull infrastructure has no constituency. A new station has a community of beneficiaries who will campaign for it, a name to be attached to a politician, and an opening. Replacing the signalling on an existing line has none of these, although it may deliver more additional journeys per pound than any new construction under consideration.\nThe only durable remedies proposed are institutional rather than rhetorical: maintenance budgets ring-fenced from capital budgets so that one cannot be raided for the other; asset condition published on a fixed cycle in a form that a non-specialist can read; and, most effectively, funding formulas that treat renewal as a defined obligation rather than a discretionary sum. None of these is exciting. That is precisely the argument for legislating them, since anything that depends on the enthusiasm of a particular administration will not survive the arrival of the next one.",
    questions: [
      { q: "How is public investment usually announced?", options: ["As budget totals","As improvements to existing services","In the form of new objects","Through maintenance programmes"], answer: 2, explanation: "'Public investment tends to be announced in the form of objects'." },
      { q: "Why is maintenance politically disadvantaged?", options: ["It is technically difficult","The public opposes it","It costs more than construction","Its benefits are things that did not happen"], answer: 3, explanation: "'Its benefits are counterfactual, consisting of failures that did not occur'." },
      { q: "What is meant by deferred maintenance behaving non-linearly?", options: ["Deterioration is slow then sudden","Repairs become easier with time","Assets fail at random","Costs rise steadily over time"], answer: 0, explanation: "'a road surface degrades slowly for a decade and then rapidly'." },
      { q: "Why does dull infrastructure lack support?", options: ["It is not understood by engineers", "It has no identifiable beneficiaries to campaign for it", "It is illegal to fund privately", "It rarely works"], answer: 1, explanation: "'dull infrastructure has no constituency'." },
      { q: "What kind of remedies does the writer favour?", options: ["Private sector involvement","Better public communication","Institutional and legislative arrangements","Increased overall spending"], answer: 2, explanation: "'The only durable remedies proposed are institutional rather than rhetorical'." },
      { q: "Why does the writer argue for legislating unexciting measures?", options: ["Because engineers prefer them","Because they are cheap","Because voters demand them","Because enthusiasm does not survive changes of administration"], answer: 3, explanation: "'anything that depends on the enthusiasm of a particular administration will not survive the arrival of the next one'." }
    ]
  },
  {
    id: "cae-rmc9-05",
    title: "When Volunteers Take the Place of Staff",
    text: "The distinction between volunteering and unpaid labour is not always obvious from inside the organisation doing the asking, and the test that best separates them is rarely applied. It is not whether the work is valuable, nor whether the volunteer is willing, but whether the role would have to be filled by a paid employee if nobody volunteered.\nBy that test, a substantial proportion of what is currently described as volunteering in public services fails. A library staffed entirely by volunteers is not a library enriched by community involvement; it is a library whose staffing costs have been transferred to people who are not paid and who cannot be required to turn up. The distinction matters most at the moment when something goes wrong, because an organisation that depends on volunteers for a statutory function has no mechanism for insisting that the function is performed.\nThe evidence on outcomes is more mixed than either side of the argument usually concedes. Volunteer-run services frequently achieve high user satisfaction, partly because volunteers are present by choice and are not managing eleven other obligations. They also exhibit a characteristic pattern of failure: capacity varies with the availability of a small number of individuals, coverage is strongest in the areas with the most retired professionals, and provision is thinnest precisely where need is greatest, which is the opposite of what a public service is for.\nThere is also a question of who is excluded from volunteering. Unpaid work requires disposable time, which is distributed extremely unevenly, and a service run by volunteers is therefore run by the sections of a community that can afford to give a morning a week. This is not a criticism of the volunteers. It is an observation about representativeness that becomes serious when the volunteers are making decisions rather than shelving books.\nNone of this argues against volunteering, which produces genuine value in the roles that would not otherwise exist at all: the additional activity, the extra pair of hands, the thing nobody was funded to do. The argument is against the quiet substitution, which is generally undertaken without any decision being announced, and which is recognisable by a single feature: nobody involved is willing to say out loud what would happen if the volunteers stopped.",
    questions: [
      { q: "What test does the writer propose?", options: ["Whether a paid employee would otherwise be needed","Whether training is provided","Whether the work is valuable","Whether the volunteer is willing"], answer: 0, explanation: "'whether the role would have to be filled by a paid employee if nobody volunteered'." },
      { q: "What is the writer's view of a wholly volunteer-run library?", options: ["It represents genuine community enrichment", "Its staffing costs have simply been transferred", "It is more efficient than a staffed one", "It cannot function at all"], answer: 1, explanation: "'it is a library whose staffing costs have been transferred to people who are not paid'." },
      { q: "When does the distinction matter most?", options: ["When funding is agreed","During recruitment","When something goes wrong","At the annual audit"], answer: 2, explanation: "'The distinction matters most at the moment when something goes wrong'." },
      { q: "What pattern of failure do volunteer services show?", options: ["Users are consistently dissatisfied","Costs rise unpredictably","Volunteers work too many hours","Provision is weakest where need is greatest"], answer: 3, explanation: "'provision is thinnest precisely where need is greatest'." },
      { q: "Why does the writer raise the question of who volunteers?", options: ["Unpaid work requires time that is unevenly distributed","Volunteers demand payment eventually","Recruitment is difficult","Volunteers are usually unqualified"], answer: 0, explanation: "'Unpaid work requires disposable time, which is distributed extremely unevenly'." },
      { q: "How can quiet substitution be recognised?", options: ["By falling user numbers","By nobody saying what would happen if volunteers stopped","By increased budgets","By formal announcements"], answer: 1, explanation: "'nobody involved is willing to say out loud what would happen if the volunteers stopped'." }
    ]
  },
  {
    id: "cae-rmc9-06",
    title: "What a Pilot Project Cannot Tell You",
    text: "The pilot is the standard device by which an organisation reduces the risk of a large change. Something is tried in one department, one region or one school, and if it works it is extended. The logic is sound and the practice is unreliable, for reasons that are well understood by researchers and consistently ignored by the people commissioning the pilots.\nThe first difficulty is selection. A pilot site is rarely typical: it volunteered, or was chosen because it had capable management, or because a senior figure was enthusiastic. Every one of those characteristics predicts success independently of the intervention, and the effect is systematic rather than random. When the same programme is subsequently implemented in sites that did not volunteer, the observed benefit shrinks, sometimes to nothing, and the explanation offered is usually poor implementation rather than a flawed inference.\nThe second is attention. A pilot receives resources that a general rollout cannot: the designers are present, problems are fixed within days, and participants know they are being observed. This is not deception; it is the ordinary condition of a small, watched, well-supported project. The generalisable question is not whether the intervention works under those conditions, but whether it works when nobody is watching, and a pilot is structurally incapable of answering it.\nThe third is scale itself. Some effects reverse with size. A scheme that succeeds by drawing on a limited pool of skilled staff, or by referring difficult cases elsewhere, will behave differently when there is no elsewhere, and the failure is not visible in the pilot because at pilot scale the constraint has not bound.\nNone of this makes piloting worthless. It makes the standard interpretation of a successful pilot much weaker than it is generally taken to be. The useful pilot is designed to fail informatively: it runs in an unpromising site as well as a promising one, it deliberately withdraws support halfway through to see what survives, and it specifies in advance what result would cause the idea to be abandoned. Pilots designed in that way are rare, and the reason is not methodological ignorance. It is that the person commissioning a pilot has usually already decided.",
    questions: [
      { q: "What is the writer's overall view of pilots?", options: ["They are the only reliable method","They are too expensive","The logic is sound but the practice is unreliable","They should never be used"], answer: 2, explanation: "'The logic is sound and the practice is unreliable'." },
      { q: "What is the problem of selection?", options: ["Sites are too small","Participants are not informed","Sites are chosen at random","Pilot sites are unusually likely to succeed anyway"], answer: 3, explanation: "'Every one of those characteristics predicts success independently of the intervention'." },
      { q: "How is a disappointing rollout usually explained?", options: ["As poor implementation","As bad luck","As insufficient funding","As a flawed inference from the pilot"], answer: 0, explanation: "'the explanation offered is usually poor implementation rather than a flawed inference'." },
      { q: "Why does attention matter?", options: ["Participants resent being watched", "Pilots receive support a rollout cannot", "Observers introduce errors", "Data collection is expensive"], answer: 1, explanation: "'A pilot receives resources that a general rollout cannot'." },
      { q: "What does the writer mean by effects reversing with scale?", options: ["Staff resist expansion","Larger projects always cost more","Constraints that did not bind at pilot scale begin to bind","Results become statistically insignificant"], answer: 2, explanation: "'the failure is not visible in the pilot because at pilot scale the constraint has not bound'." },
      { q: "Why are well-designed pilots rare?", options: ["They take too long","They are technically difficult","Researchers are unaware of the problems","The commissioner has usually already decided"], answer: 3, explanation: "'It is that the person commissioning a pilot has usually already decided.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
