/* CAE Prep bank: Reading multiple choice (C1) — wave 23 */
(function () {
var BANK = [
  {
    id: "cae-rmc23-01",
    title: "What Peer Review Is For",
    text: "Peer review is defended as a guarantee of quality and attacked as a failure to guarantee it, and both positions assume that guaranteeing quality is what it does. A more accurate description is that it is a filter of limited and specific capability, and most of the disappointment surrounding it results from expecting a different instrument.\nWhat review reliably detects is a mismatch between a paper's claims and its stated methods: a conclusion the analysis does not support, an omitted control, an inappropriate test. What it cannot detect, because reviewers do not have access to the material, is whether the work was done as described. A determined fabrication passes review routinely, and the mechanisms that catch it are subsequent replication and, more often, colleagues who were present.\nThe process is also, on the evidence, considerably less reliable than its reputation suggests. Studies in which the same manuscript is sent to multiple reviewers find agreement barely above chance on recommendations to accept or reject, and experiments inserting deliberate errors find that a minority are identified. This is not evidence that review is worthless; it is evidence that it operates as a noisy filter with a modest signal, which is a useful thing to have and a poor thing to rely on.\nThe reforms proposed follow from where the deficiencies are. Publishing reviews alongside papers improves their quality by making them attributable. Requiring data and code addresses the central blind spot, since a reviewer given the material can check what a reviewer given a description cannot. Separating the assessment of soundness from the assessment of importance recognises that these are different judgements made with different reliability, the first reasonably and the second poorly.\nThe underlying difficulty is that review is unpaid work performed by people whose incentives are elsewhere, evaluated by nobody, and expanding at the rate at which publication expands. A system with those properties will produce variable results whatever its design, and no reform that does not address the economics is likely to change the outcome by very much.",
    questions: [
      { q: "How does the writer characterise peer review?", options: ["As a filter of limited capability","As entirely ineffective","As a formality","As a guarantee of quality"], answer: 0, explanation: "'it is a filter of limited and specific capability'." },
      { q: "What can review not detect?", options: ["Statistical errors", "Whether the work was done as described", "Missing controls", "Unsupported conclusions"], answer: 1, explanation: "'whether the work was done as described'." },
      { q: "What do multi-reviewer studies find?", options: ["Consistent bias","High agreement","Agreement barely above chance","Complete disagreement"], answer: 2, explanation: "'find agreement barely above chance on recommendations'." },
      { q: "How does the writer interpret that evidence?", options: ["Reviewers are dishonest","Editors should decide alone","Review is worthless","Review is a noisy filter with modest signal"], answer: 3, explanation: "'it operates as a noisy filter with a modest signal'." },
      { q: "What does requiring data and code address?", options: ["The central blind spot", "Reviewer workload", "Publication speed", "Importance judgements"], answer: 0, explanation: "'Requiring data and code addresses the central blind spot'." },
      { q: "What underlying difficulty does the writer identify?", options: ["Reviewers are unqualified", "The economics of unpaid expanding work", "Journals are too numerous", "Editors are overworked"], answer: 1, explanation: "'review is unpaid work performed by people whose incentives are elsewhere'." }
    ]
  },
  {
    id: "cae-rmc23-02",
    title: "Designing for Nobody",
    text: "In the middle of the twentieth century, an air force investigating a series of accidents measured several thousand pilots on ten dimensions and calculated the average of each, with a view to designing a cockpit that fitted the average pilot. A researcher then asked how many of the pilots measured were close to average on all ten dimensions. The answer was none.\nThe finding has been reproduced in every population subsequently examined, and its explanation is arithmetic rather than empirical. Where dimensions are imperfectly correlated, the proportion of a population close to the mean on all of them falls rapidly as dimensions are added. A person of average height is unlikely to be of average arm length; a person average on both is unlikely to be average on a third. Designing for the average therefore produces an object that fits nobody, and does so with a confidence derived from the fact that every individual figure was correct.\nThe response in that case was adjustability, which is now so ordinary in vehicle design that its origin is forgotten. The general principle is broader and is regularly ignored in domains where the variation is not physical: an assessment designed for the average student, a process designed for the average case, a schedule designed for the average journey. In each, the average conceals a distribution, and a system that accommodates only its centre fails at a rate determined by how wide the distribution is rather than by how well the centre was identified.\nThe practical implication is not that averages are useless. It is that the design question is never what the average value is but what range must be accommodated, and the two questions have different answers and require different data. An organisation that knows its mean and not its spread has the wrong number.\nWhat makes this persistent is that the average is available. It appears in every summary, it is easy to calculate, and it produces a single figure that a decision can be built around, whereas a distribution requires a judgement about how much of it to accommodate, which is a decision somebody has to be accountable for making.",
    questions: [
      { q: "What did the researcher discover?", options: ["Cockpits were too small","Most pilots were near average","No pilot was near average on all dimensions","The measurements were wrong"], answer: 2, explanation: "'The answer was none.'" },
      { q: "Why does the proportion fall as dimensions are added?", options: ["Populations vary","Averages shift","Measurements become less accurate","Dimensions are imperfectly correlated"], answer: 3, explanation: "'Where dimensions are imperfectly correlated, the proportion... falls rapidly'." },
      { q: "What was the response in aviation?", options: ["Adjustability","Larger cockpits","Better training","Selecting different pilots"], answer: 0, explanation: "'The response in that case was adjustability'." },
      { q: "How does the principle apply beyond physical design?", options: ["It does not apply", "To assessments, processes and schedules", "Only to vehicles", "Only to large populations"], answer: 1, explanation: "'an assessment designed for the average student, a process designed for the average case'." },
      { q: "What is the correct design question?", options: ["What the maximum is","What the average is","What range must be accommodated","How many people are affected"], answer: 2, explanation: "'the design question is never what the average value is but what range must be accommodated'." },
      { q: "Why does reliance on averages persist?", options: ["Distributions are secret","Regulations require averages","Averages are more accurate","The average is available and requires no accountable judgement"], answer: 3, explanation: "'a distribution requires a judgement about how much of it to accommodate, which is a decision somebody has to be accountable for making'." }
    ]
  },
  {
    id: "cae-rmc23-03",
    title: "The Consultation That Changed Nothing",
    text: "Public consultation is a statutory requirement in many decisions and a source of consistent frustration to everybody involved. Residents report that the outcome was decided in advance; officials report that responses were dominated by a small number of people repeating a single objection; and both are frequently correct.\nThe structural difficulty is timing. A consultation held early enough to influence the decision necessarily lacks the detail that makes a proposal comprehensible, and one held late enough to present a specific scheme is being conducted after the decisive commitments have been made. Most consultations are held at the second point, because that is when a document exists, and the resulting exercise asks people to comment on a design whose fundamental choices are no longer available.\nThe second difficulty is who responds. Self-selected consultation attracts those with the strongest views, the most available time and the greatest familiarity with the process, which is a description of a particular demographic. Where authorities have compared self-selected responses with representative surveys of the same population, the two frequently point in different directions, and the gap is largest on questions where the affected group is least likely to write letters.\nThe approaches that produce better outcomes share a feature: they change what is being asked. A consultation that presents options with their consequences, rather than a scheme with a comment box, elicits usable information. A deliberative process that convenes a demographically selected group for long enough to hear evidence produces recommendations that officials describe as more considered and that campaigners frequently distrust, since a randomly selected panel has no accountability to anybody.\nThe honest conclusion is that consultation cannot resolve the disagreement it exposes. A decision that will benefit many people slightly and harm a few substantially remains that decision whatever process precedes it. What a good process can do is establish that the harm was understood, that the alternatives were examined and that the reasons were stated, which is a much weaker claim than legitimacy and the only one that any procedure is capable of supporting.",
    questions: [
      { q: "What do both residents and officials get right?", options: ["Their respective complaints are frequently correct","Only the officials","Only the residents","Nothing"], answer: 0, explanation: "'and both are frequently correct'." },
      { q: "What is the structural difficulty?", options: ["Cost", "Timing", "Language", "Publicity"], answer: 1, explanation: "'The structural difficulty is timing.'" },
      { q: "Why are most consultations held late?", options: ["Residents request it","Legal requirements","That is when a document exists","Officials prefer it"], answer: 2, explanation: "'because that is when a document exists'." },
      { q: "Who responds to self-selected consultation?", options: ["Mainly young people","Only affected residents","A representative sample","Those with strong views, time and familiarity"], answer: 3, explanation: "'attracts those with the strongest views, the most available time and the greatest familiarity with the process'." },
      { q: "Why do campaigners distrust deliberative panels?", options: ["A randomly selected panel is accountable to nobody","They take too long","They exclude experts","They are expensive"], answer: 0, explanation: "'a randomly selected panel has no accountability to anybody'." },
      { q: "What can a good process establish?", options: ["Legitimacy", "That harm was understood and reasons stated", "Consensus", "That objections were wrong"], answer: 1, explanation: "'establish that the harm was understood, that the alternatives were examined and that the reasons were stated'." }
    ]
  },
  {
    id: "cae-rmc23-04",
    title: "Twenty Miles an Hour",
    text: "Reductions in urban speed limits produce a debate whose terms have remained unchanged for two decades, and the evidence has accumulated sufficiently that most of the empirical questions are now answerable, if not agreed.\nThe physics is not in dispute. The energy of a collision rises with the square of the speed, and the probability that a pedestrian struck by a vehicle is killed rises steeply between twenty and thirty miles an hour. A reduction in mean speed of one mile an hour is associated, across many studies, with a reduction in collisions of several per cent.\nThe contested question is whether posted limits change actual speeds, and the answer is that they do so modestly and unevenly. Signs alone produce small reductions that decay; enforcement produces larger ones that persist while it continues; and physical measures produce the largest and most durable changes, at a cost per street that limits how widely they are applied. Schemes that consist entirely of signage are frequently evaluated as failures of the concept when they are failures of implementation.\nThe objection that lower limits increase journey times has been examined repeatedly and is generally overstated. In dense urban networks, average speeds are determined by junctions rather than by the distance between them, and modelling and observation agree that the effect of a limit reduction on end-to-end journey time is typically under a minute. The perception of delay is nonetheless real, since a driver experiences the constrained sections and not the aggregate.\nWhat has changed the debate most is the second-order evidence. Where limits have been reduced across an area rather than on individual streets, walking and cycling increase measurably, particularly among children, and the effect on collisions is larger than the speed reduction alone would predict. The explanation appears to be a change in the perceived safety of the street rather than in its actual physics, which is an effect that no engineering assessment of a single road would ever capture.",
    questions: [
      { q: "What is not in dispute?", options: ["Public opinion","The effectiveness of signs","The physics of collisions","Journey time effects"], answer: 2, explanation: "'The physics is not in dispute.'" },
      { q: "What produces the most durable speed reductions?", options: ["Publicity campaigns","Signage","Enforcement","Physical measures"], answer: 3, explanation: "'physical measures produce the largest and most durable changes'." },
      { q: "How does the writer characterise signage-only schemes?", options: ["As failures of implementation","As successful","As untested","As failures of the concept"], answer: 0, explanation: "'when they are failures of implementation'." },
      { q: "What determines urban average speeds?", options: ["Speed limits", "Junctions", "Vehicle types", "Road width"], answer: 1, explanation: "'average speeds are determined by junctions rather than by the distance between them'." },
      { q: "Why does perceived delay persist?", options: ["Routes change","Journeys really are much longer","Drivers experience constrained sections, not aggregates","Signs are confusing"], answer: 2, explanation: "'a driver experiences the constrained sections and not the aggregate'." },
      { q: "What second-order effect has changed the debate?", options: ["Reduced fuel use","Lower enforcement costs","Fewer complaints","Increased walking and cycling across areas"], answer: 3, explanation: "'walking and cycling increase measurably, particularly among children'." }
    ]
  },
  {
    id: "cae-rmc23-05",
    title: "Deciding What Children Learn",
    text: "A curriculum is a statement about what a society believes is worth knowing, and it is revised by processes that are almost entirely unequipped to make that judgement. The revision is generally prompted by a change of administration, conducted under time pressure, and dominated by the subjects whose advocates are best organised.\nThe structural problem is that a curriculum is a fixed quantity of time. Every addition is a removal, and the removal is rarely stated: a document announcing that a topic will be added does not announce which topic has been displaced, and the displacement is discovered by teachers attempting to deliver the result. Over several revisions this produces a curriculum that is describable only as an accumulation, in which the presence of any particular item reflects the sequence of political attention rather than any coherent view of what a person should know.\nThe second problem is that the debate is conducted in terms of content when the more consequential decisions concern sequence and depth. Whether a topic appears at all matters less than whether there is time to establish it before the next thing depends on it, and the commonest failure in mathematics and science education is not the absence of a topic but its introduction at a point where the prerequisites are insecure.\nThe international evidence, such as it is, favours coverage that is narrower and deeper, and the finding is quoted approvingly by everybody and acted on by almost nobody, because narrowing requires deciding what to remove and every removal has an advocate whose subject is being diminished.\nThere is one further consideration that the process handles badly. A curriculum is delivered by teachers whose own education occurred under a previous version, and a revision that assumes capabilities the teaching workforce does not have is not a revision but an aspiration. The programmes that have succeeded internationally invested in the workforce first and changed the document afterwards, which is the reverse of the usual order and takes longer than any single administration is prepared to wait.",
    questions: [
      { q: "What prompts curriculum revision?", options: ["A change of administration","Teacher requests","International comparison","Educational research"], answer: 0, explanation: "'generally prompted by a change of administration'." },
      { q: "Why is every addition a removal?", options: ["Budgets are fixed", "A curriculum is a fixed quantity of time", "Books must be reprinted", "Teachers refuse extra work"], answer: 1, explanation: "'a curriculum is a fixed quantity of time'." },
      { q: "How is the displacement usually discovered?", options: ["By inspectors","It is announced","By teachers delivering the result","Through consultation"], answer: 2, explanation: "'the displacement is discovered by teachers attempting to deliver the result'." },
      { q: "What matters more than whether a topic appears?", options: ["Assessment method","Textbook quality","Who teaches it","Sequence and depth"], answer: 3, explanation: "'the more consequential decisions concern sequence and depth'." },
      { q: "Why is narrower coverage rarely adopted?", options: ["Every removal has an advocate","It costs more","Parents object","Evidence is weak"], answer: 0, explanation: "'every removal has an advocate whose subject is being diminished'." },
      { q: "What order have successful programmes followed?", options: ["Document first, workforce later", "Workforce first, document afterwards", "Simultaneous change", "Assessment first"], answer: 1, explanation: "'invested in the workforce first and changed the document afterwards'." }
    ]
  },
  {
    id: "cae-rmc23-06",
    title: "The Chain That Was Too Efficient",
    text: "Supply chains were optimised, over three decades, for cost under stable conditions, and the optimisation was successful. Inventory was reduced to a fraction of what it had been, suppliers were consolidated to obtain volume discounts, and production was concentrated where it was cheapest. Each decision was correct in isolation and the aggregate produced a system with a characteristic that nobody had chosen: a very low tolerance for disruption.\nThe mechanism is not complicated. Inventory is a buffer, and removing it converts a delay at one point into a stoppage at every point downstream. Consolidation removes the alternative supplier who would otherwise have been available. Concentration means that a single event affects the entire supply rather than a portion of it. What was purchased with the savings was, precisely, the capacity to absorb variation.\nThe response has been described as a shift from efficiency to resilience, which is a useful phrase concealing an unresolved question: who pays. Resilience consists of assets that are not used, suppliers who are not the cheapest and inventory that sits. These are costs incurred continuously against a benefit that materialises rarely, and the discipline of quarterly reporting is hostile to exactly this pattern.\nThe firms that have made durable changes have generally done so by making the exposure visible rather than by adopting a principle. Mapping a supply chain beyond the first tier routinely discovers that four apparently independent suppliers depend on a single facility, and this discovery changes behaviour in a way that general arguments about resilience do not.\nThere is also a public dimension that firms cannot address individually. Where a critical input is concentrated in one place, no single firm has an incentive to bear the cost of an alternative that would benefit its competitors equally, which is a straightforward collective action problem and one of the few areas where an industrial policy argument is made by people who ordinarily resist making one. What is not available is the position that the system will correct itself, since the system produced this outcome by correcting itself for thirty years.",
    questions: [
      { q: "What were supply chains optimised for?", options: ["Environmental impact","Speed","Cost under stable conditions","Resilience"], answer: 2, explanation: "'optimised, over three decades, for cost under stable conditions'." },
      { q: "What characteristic did the aggregate produce?", options: ["Slower delivery","Greater complexity","Higher costs","Low tolerance for disruption"], answer: 3, explanation: "'a very low tolerance for disruption'." },
      { q: "What does removing inventory do?", options: ["Converts delays into stoppages downstream", "Reduces quality", "Increases supplier numbers", "Speeds production"], answer: 0, explanation: "'removing it converts a delay at one point into a stoppage at every point downstream'." },
      { q: "What question does the resilience shift conceal?", options: ["Whether it works", "Who pays", "How to measure it", "Which sectors are affected"], answer: 1, explanation: "'concealing an unresolved question: who pays'." },
      { q: "What changes firms' behaviour effectively?", options: ["Insurance requirements","General arguments about resilience","Making the exposure visible through mapping","Government regulation"], answer: 2, explanation: "'by making the exposure visible rather than by adopting a principle'." },
      { q: "Why can firms not address concentration individually?", options: ["They lack information","Costs are unknown","It is illegal","The benefit would accrue to competitors equally"], answer: 3, explanation: "'no single firm has an incentive to bear the cost of an alternative that would benefit its competitors equally'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
