/* CAE Prep bank: Reading multiple choice (C1) — wave 16 */
(function () {
var BANK = [
  {
    id: "cae-rmc16-01",
    title: "The Prize That Bends the Field",
    text: "Prizes are defended on the grounds that they reward excellence and attract attention to work that deserves it. Both claims are true and neither addresses the more consequential effect, which is that a prize alters what is produced by people who hope to win it.\nThe mechanism operates through the criteria, which are necessarily narrower than the field. A prize awarded for a single outstanding contribution favours work that can be attributed to an individual, which disadvantages the collaborative and the cumulative. A prize awarded annually favours work whose value is apparent within a year, which disadvantages anything whose importance emerges slowly. These are not defects in the design; they are unavoidable consequences of having a design at all.\nThe effects are measurable where fields have been studied over long periods. The distribution of effort shifts towards the kinds of work the prize recognises, and the shift is largest among early-career participants, who are the most sensitive to signals about what is valued and the least able to ignore them. A field with a single dominant prize develops a characteristic shape within a generation.\nThere is a further and subtler consequence concerning what is recorded. Prize-winning work is more heavily cited, taught and reprinted, which alters the account of the field that the next generation receives. Where the prize has systematically favoured a particular kind of contribution, the history constructed afterwards will show that this kind of contribution was the important one, and the evidence for that claim will be entirely circular.\nNone of this is an argument for abolition, which would simply transfer the same function to less visible mechanisms of reputation. It is an argument for multiplicity and for candour: several prizes with different criteria distort less than one, and a prize whose committee states plainly what it is not able to recognise gives the field information it can use. The prizes that do this are rare, and they are noticeably the ones that are hardest to criticise.",
    questions: [
      { q: "What consequence do the usual defences of prizes ignore?", options: ["That prizes change what is produced","That judges disagree","That winners are often unknown","The cost of administering them"], answer: 0, explanation: "'a prize alters what is produced by people who hope to win it'." },
      { q: "What kind of work does an individual prize disadvantage?", options: ["Experimental work", "Collaborative and cumulative work", "Theoretical work", "Applied work"], answer: 1, explanation: "'which disadvantages the collaborative and the cumulative'." },
      { q: "Who is most affected by the shift in effort?", options: ["Prize committees","Senior figures","Early-career participants","Administrators"], answer: 2, explanation: "'the shift is largest among early-career participants'." },
      { q: "Why does the writer call the later history circular?", options: ["Historians are biased","Citations are unreliable","The records are lost","Prize-winning work shapes the account that proves its importance"], answer: 3, explanation: "'the evidence for that claim will be entirely circular'." },
      { q: "Why would abolition not help?", options: ["The function would move to less visible mechanisms","Nobody would fund research","Standards would fall","Prizes are legally protected"], answer: 0, explanation: "'would simply transfer the same function to less visible mechanisms of reputation'." },
      { q: "What does the writer recommend?", options: ["Fewer, larger prizes", "Multiple prizes and honesty about limits", "Anonymous judging", "Longer eligibility periods"], answer: 1, explanation: "'It is an argument for multiplicity and for candour'." }
    ]
  },
  {
    id: "cae-rmc16-02",
    title: "The Last Speakers",
    text: "A language is generally described as endangered when the number of speakers falls below some threshold, which is a convenient measure and a poor one. The variable that determines whether a language survives is not how many people speak it but whether children are acquiring it, and a language with fifty thousand adult speakers and no child speakers is in a considerably worse position than one with four hundred speakers of all ages.\nWhat produces the break in transmission is rarely a prohibition, though prohibitions have existed. It is more commonly a set of ordinary calculations made by parents, each of which is reasonable: that the child's prospects depend on fluency in the dominant language, that time is finite, that the local language is not used in any institution the child will encounter. The result is a generation that understands and does not speak, and the pattern is remarkably consistent across unrelated situations on several continents.\nRevitalisation efforts have accumulated enough experience to distinguish what works from what is merely visible. Documentation preserves the record and does not produce speakers. Classroom teaching produces limited fluency where the language is not used outside the classroom, which is the position in most schemes. The approaches with the strongest record create domains in which the language is the only practical option: immersion settings for young children, and, more effectively, arrangements pairing a fluent elder with a learner for several hundred hours of ordinary activity conducted entirely in the language.\nThe difficulty is that these approaches are expensive, slow and dependent on a small number of elderly people whose availability is limited. Programmes are frequently designed around what can be delivered at scale, which produces the classroom model, and evaluated by participation figures, which the classroom model generates.\nThe communities that have succeeded describe the decisive factor in similar terms, and it is not a method. It is the existence of a domain where the language is required rather than encouraged: a workplace, a governing body, a family that has decided. Encouragement produces comprehension; requirement produces speakers, and the distinction is one that funding structures find almost impossible to represent.",
    questions: [
      { q: "Why is speaker number a poor measure?", options: ["It changes seasonally","It cannot be counted accurately","Transmission to children matters more","It excludes second-language speakers"], answer: 2, explanation: "'The variable that determines whether a language survives is not how many people speak it but whether children are acquiring it'." },
      { q: "What usually breaks transmission?", options: ["Migration","Loss of written records","Legal prohibition","Ordinary parental calculations"], answer: 3, explanation: "'It is more commonly a set of ordinary calculations made by parents'." },
      { q: "What does documentation achieve?", options: ["It preserves the record only","It replaces teaching","It reverses decline","It produces new speakers"], answer: 0, explanation: "'Documentation preserves the record and does not produce speakers.'" },
      { q: "Which approach has the strongest record?", options: ["Classroom teaching", "Creating domains where the language is the only option", "Broadcasting", "Dictionary projects"], answer: 1, explanation: "'create domains in which the language is the only practical option'." },
      { q: "Why are classroom models preferred by programmes?", options: ["They are required by law","They are most effective","They can be delivered at scale and generate participation figures","Elders prefer them"], answer: 2, explanation: "'designed around what can be delivered at scale... and evaluated by participation figures'." },
      { q: "What do successful communities identify as decisive?", options: ["Government funding","Written materials","A particular teaching method","A domain where the language is required"], answer: 3, explanation: "'It is the existence of a domain where the language is required rather than encouraged'." }
    ]
  },
  {
    id: "cae-rmc16-03",
    title: "The Value of Being Able to Change Your Mind",
    text: "Decision-making is usually taught as a matter of gathering information and choosing well. A more useful frame, particularly under uncertainty, distinguishes decisions by whether they can be undone, because the appropriate amount of deliberation depends far more on reversibility than on apparent importance.\nA reversible decision taken badly costs the difference between the outcome and the alternative, plus the cost of reversing it. An irreversible one taken badly costs everything that follows from it. It follows that the two should be treated quite differently, and that the common practice of deliberating in proportion to the sums involved is a poor heuristic, since expensive decisions are frequently reversible and cheap ones occasionally are not.\nThe practical error runs in both directions. Organisations routinely spend months on choices that could have been made in a week and revised in a month, incurring the cost of delay in exchange for a precision that the decision did not require. They also, and more damagingly, treat genuinely irreversible decisions as though they were provisional: appointments, disposals of assets, commitments that create expectations in other parties, and any decision whose reversal would require the consent of somebody who now has no reason to give it.\nThe question that separates the two categories is not whether reversal is theoretically possible but what it would cost and who would have to agree. A contract can be terminated, at a price. A building can be demolished. A reputation cannot be restored on any timescale that matters to the person concerned, which is why decisions affecting other people's standing belong firmly in the irreversible category regardless of how they are described at the time.\nThe corresponding discipline is to ask the question explicitly and early, before any analysis has begun. Where a decision is reversible, the appropriate response is to take it quickly, monitor the result and accept a proportion of errors as the price of speed. Where it is not, the appropriate response is to spend the time, take the criticism for slowness, and remember that the pressure being applied to decide quickly is usually being applied by somebody who will not bear the consequences.",
    questions: [
      { q: "What distinction does the writer propose?", options: ["Between reversible and irreversible ones","Between urgent and routine ones","Between individual and group decisions","Between cheap and expensive decisions"], answer: 0, explanation: "'distinguishes decisions by whether they can be undone'." },
      { q: "Why is deliberating in proportion to cost a poor rule?", options: ["Costs are hard to estimate", "Expensive decisions are often reversible", "It takes too long", "It ignores expertise"], answer: 1, explanation: "'expensive decisions are frequently reversible and cheap ones occasionally are not'." },
      { q: "What is the more damaging error?", options: ["Consulting too widely","Over-deliberating on reversible choices","Treating irreversible decisions as provisional","Delegating decisions"], answer: 2, explanation: "'and more damagingly, treat genuinely irreversible decisions as though they were provisional'." },
      { q: "What question separates the categories?", options: ["How much money is involved","How many people are affected","Whether reversal is theoretically possible","What reversal would cost and who must agree"], answer: 3, explanation: "'not whether reversal is theoretically possible but what it would cost and who would have to agree'." },
      { q: "Why do reputational decisions count as irreversible?", options: ["Reputation cannot be restored in a relevant timescale","They are usually public","They require committee approval","They involve legal risk"], answer: 0, explanation: "'A reputation cannot be restored on any timescale that matters to the person concerned'." },
      { q: "What does the writer note about pressure to decide quickly?", options: ["It reflects genuine urgency","It usually comes from those who will not bear the consequences","It is generally justified","It comes from regulators"], answer: 1, explanation: "'usually being applied by somebody who will not bear the consequences'." }
    ]
  },
  {
    id: "cae-rmc16-04",
    title: "The Second Career of a Ship",
    text: "A commercial vessel is designed for a working life of perhaps twenty-five years, and what happens at the end of it is determined by an economic calculation that has almost nothing to do with the condition of the ship. When the cost of the next survey, the required modifications and the fuel penalty of an older design exceed the earnings the vessel can command, it is worth more as material than as transport.\nThe recycling of ships is therefore an industry, and it is one whose geography has been determined by regulation rather than by capability. The work is labour-intensive, hazardous and generates substances that require controlled handling, and it has concentrated in a small number of locations where labour is cheap and enforcement variable. The pattern is familiar from other industries and the specific difficulty here is that the asset can move: a ship approaching the end of its life can be sold, reflagged and delivered to whichever jurisdiction offers the best combination of price and regulatory tolerance.\nAttempts to address this have produced an instructive sequence. Regulation applied at the point of scrapping is straightforward to evade by changing where scrapping occurs. Regulation applied to the owner at the point of sale is harder to evade and has been substantially weakened by intermediaries who purchase vessels for a final voyage. The approach that has shown most promise applies the obligation at the point of construction: a requirement that a vessel carry, throughout its life, a documented inventory of the hazardous materials it contains, which makes safe dismantling considerably cheaper and unsafe dismantling less attractive.\nThe economics remain uncomfortable. Facilities operating to a high standard cost more, and a shipowner selling to the highest bidder has no incentive to prefer them. Several proposals would attach a recycling levy at construction, held until the vessel is dismantled at a compliant facility, which internalises the cost at the point where it can be priced and removes the incentive that currently operates at the end.\nThe industry's objection is that such a levy would apply to vessels built under one jurisdiction and not another. This is correct, and it is the objection made to every environmental cost that has ever been internalised anywhere.",
    questions: [
      { q: "What determines when a ship is scrapped?", options: ["The owner's preference","Its physical condition","An economic calculation","International regulation"], answer: 2, explanation: "'determined by an economic calculation that has almost nothing to do with the condition of the ship'." },
      { q: "What has determined where recycling happens?", options: ["Proximity to shipping routes","Availability of equipment","Technical capability","Regulation and enforcement variation"], answer: 3, explanation: "'whose geography has been determined by regulation rather than by capability'." },
      { q: "What makes this industry's regulation particularly difficult?", options: ["The asset can move", "The materials are unknown", "Owners are anonymous", "The work is seasonal"], answer: 0, explanation: "'the specific difficulty here is that the asset can move'." },
      { q: "Why has regulation at the point of sale been weakened?", options: ["Courts overturned it", "Intermediaries buy vessels for a final voyage", "Owners ignore it", "It was never enacted"], answer: 1, explanation: "'substantially weakened by intermediaries who purchase vessels for a final voyage'." },
      { q: "What approach shows most promise?", options: ["Voluntary industry standards","Higher scrapping fees","Obligations imposed at construction","Bans on export"], answer: 2, explanation: "'applies the obligation at the point of construction'." },
      { q: "How does the writer treat the industry's objection to a levy?", options: ["As dishonest","As legally invalid","As decisive","As correct but unexceptional"], answer: 3, explanation: "'This is correct, and it is the objection made to every environmental cost that has ever been internalised anywhere.'" }
    ]
  },
  {
    id: "cae-rmc16-05",
    title: "Reading a Charity's Accounts",
    text: "The most widely used measure of a charity is the proportion of income spent on administration, and it is close to worthless. It is easy to calculate, easy to compare and measures something that has almost no relationship to whether the organisation achieves anything.\nThe objections are well rehearsed among people who work in the sector and largely unknown outside it. The category is defined inconsistently, so that an organisation which classifies the salary of a programme manager as administration appears less efficient than an identical one which classifies it as programme delivery. It also creates a direct incentive to underinvest in the functions that determine effectiveness: monitoring, financial control, staff training and the evaluation that would establish whether the work does any good. An organisation that spends nothing on evaluation scores well and cannot say what it has achieved.\nA more informative reading begins elsewhere. The reserves policy indicates whether the organisation can survive a delayed grant, and an absence of reserves in a body dependent on a small number of funders is the commonest precursor to a sudden collapse. The concentration of income shows how much of the operation depends on a single relationship. The trustees' report, if it discusses anything that did not work, is a stronger signal about the culture of the organisation than any financial ratio, and it is rare enough to be notable when it occurs.\nThere is also a question of what the accounts cannot show. Charities working on advocacy, prevention or long-term change produce outcomes that materialise over decades and cannot be attributed to any single organisation, and they compete for funds against those able to report countable outputs from the current year. The reporting framework therefore favours a particular kind of work, and the effect is not neutral: it selects against precisely the activities most likely to address causes rather than symptoms.\nThe most useful question a donor can ask is not about ratios. It is what the organisation would stop doing if its income halved, because the answer reveals the priorities that the accounts describe only in aggregate.",
    questions: [
      { q: "What does the writer say about the administration ratio?", options: ["It is close to worthless","It should be calculated differently","It applies only to large charities","It is the best available measure"], answer: 0, explanation: "'and it is close to worthless'." },
      { q: "Why can identical organisations score differently?", options: ["Auditors differ", "The category is defined inconsistently", "Income varies", "Reporting periods differ"], answer: 1, explanation: "'The category is defined inconsistently'." },
      { q: "What incentive does the measure create?", options: ["To merge with other charities","To invest in evaluation","To underinvest in functions that determine effectiveness","To increase fundraising"], answer: 2, explanation: "'a direct incentive to underinvest in the functions that determine effectiveness'." },
      { q: "What does an absence of reserves indicate?", options: ["Strong donor confidence","Good governance","Efficient use of funds","A common precursor to collapse"], answer: 3, explanation: "'the commonest precursor to a sudden collapse'." },
      { q: "What signal does the writer regard as strong?", options: ["A discussion of what did not work", "A high administration ratio", "Growth in income", "Number of beneficiaries"], answer: 0, explanation: "'if it discusses anything that did not work, is a stronger signal about the culture'." },
      { q: "Which organisations does the framework disadvantage?", options: ["Those employing volunteers","Those working on long-term change","Large national charities","Those with many funders"], answer: 1, explanation: "'it selects against precisely the activities most likely to address causes rather than symptoms'." }
    ]
  },
  {
    id: "cae-rmc16-06",
    title: "The Difficulty With Anniversaries",
    text: "Commemoration operates on a decimal cycle for no reason connected to anything being commemorated. A fiftieth anniversary produces funding, exhibitions and coverage; a forty-seventh produces nothing, although the events are equally distant and the surviving participants are three years older, which in the later stages of a commemorative cycle is not a trivial consideration.\nThe pattern has consequences for what is recorded. Oral history projects cluster around anniversaries and are therefore conducted at intervals determined by arithmetic rather than by the availability of witnesses. The seventy-fifth anniversary of an event in living memory frequently arrives at the point when the youngest participants are in their nineties, and a great deal of what such projects gather is the memory of children rather than of adults, which is valuable and is a different thing.\nThere is a second effect on interpretation. An anniversary requires a subject and a shape, and the shape that fits a commemorative programme is generally a narrative with a moral. Historians invited to contribute find themselves asked for material that supports an occasion rather than an argument, and the more careful ones report a familiar difficulty: that the qualifications which make a claim accurate are the first thing removed when it is transferred to a public programme.\nThe compensating benefit is real and should be stated. Anniversaries generate resources that would otherwise not exist, and a substantial proportion of the archival work, digitisation and local research conducted in the last few decades was funded because a round number was approaching. Nobody has proposed a mechanism that would produce equivalent resources on any other schedule.\nThe workable response, adopted by several institutions, is to treat the anniversary as a funding opportunity rather than an intellectual frame: to use the money to do the work that was needed anyway, to record the interviews that should have been recorded, and to resist the pressure to produce a conclusion. The programmes that have done this are recognisable afterwards, because they left material that other people could use, rather than an interpretation that had to be revised as soon as the occasion had passed.",
    questions: [
      { q: "Why does the writer question the decimal cycle?", options: ["It excludes recent events","It is historically inaccurate","It has no connection to what is commemorated","It is too frequent"], answer: 2, explanation: "'for no reason connected to anything being commemorated'." },
      { q: "What problem affects oral history projects?", options: ["They use poor equipment","They interview too many people","They are too expensive","They are timed by arithmetic rather than witness availability"], answer: 3, explanation: "'conducted at intervals determined by arithmetic rather than by the availability of witnesses'." },
      { q: "What is often gathered at seventy-fifth anniversaries?", options: ["Memories of children","Documentary evidence","Official records","Memories of adults"], answer: 0, explanation: "'a great deal of what such projects gather is the memory of children rather than of adults'." },
      { q: "What happens to historians' qualifications?", options: ["They are emphasised", "They are the first thing removed", "They are published separately", "They are disputed"], answer: 1, explanation: "'the qualifications which make a claim accurate are the first thing removed'." },
      { q: "What benefit does the writer acknowledge?", options: ["They settle historical disputes","Anniversaries improve interpretation","They generate resources that would not otherwise exist","They attract younger audiences"], answer: 2, explanation: "'Anniversaries generate resources that would otherwise not exist'." },
      { q: "What approach does the writer recommend?", options: ["Avoiding anniversaries altogether","Commemorating more frequently","Treating the anniversary as an intellectual frame","Using it as funding while resisting conclusions"], answer: 3, explanation: "'to treat the anniversary as a funding opportunity rather than an intellectual frame'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
