/* CAE Prep bank: Reading multiple choice (C1) — wave 14 */
(function () {
var BANK = [
  {
    id: "cae-rmc14-01",
    title: "The Archive Nobody Can Open",
    text: "Digital preservation is usually imagined as a problem of storage: keeping the bits safe against decay, fire and accident. Archivists regard storage as the easy half. The difficult half is that a preserved file is not a preserved document, and the gap between the two grows with every year that passes.\nA file consists of a sequence of numbers whose meaning depends entirely on the software that interpreted it. Where that software no longer runs, or runs only on hardware that no longer exists, the numbers survive in perfect condition and convey nothing. The archives of the 1980s and 1990s contain a substantial quantity of material in exactly this condition, much of it produced by organisations that were, at the time, congratulating themselves on having moved away from paper.\nThere are three approaches and none is satisfactory alone. Migration converts material to current formats at intervals, which preserves accessibility and introduces cumulative alteration, since each conversion involves choices about what to keep. Emulation reproduces the original computing environment, which preserves the document as it was and requires maintaining a growing collection of increasingly obscure environments. Normalisation converts everything on arrival to a small number of documented formats, which is efficient and discards whatever those formats cannot express.\nThe choice between them is frequently presented as technical and is largely a judgement about what a document is. If the content is the text, migration is adequate. If the content includes the layout, the interaction or the behaviour of the original, migration destroys the thing being preserved while appearing to succeed, and the failure is invisible because the migrated file opens.\nThe most useful practical advice from those who have worked on recovery is not about technology at all. It is that the accompanying documentation matters more than the file, that formats which are open and documented survive at rates far higher than proprietary ones regardless of the popularity of the software, and that material which somebody consults regularly is preserved almost automatically, while material stored against a future need is exactly the material that is discovered, decades later, to be unreadable.",
    questions: [
      { q: "What do archivists regard as the easy half of the problem?", options: ["Storage","Format choice","Cataloguing","Documentation"], answer: 0, explanation: "'Archivists regard storage as the easy half.'" },
      { q: "Why can a perfectly preserved file convey nothing?", options: ["The numbers decay over time", "The interpreting software no longer runs", "The file is encrypted", "The content was never recorded"], answer: 1, explanation: "'Where that software no longer runs, or runs only on hardware that no longer exists'." },
      { q: "What is the drawback of migration?", options: ["It cannot be automated","It is very expensive","It introduces cumulative alteration","It requires original hardware"], answer: 2, explanation: "'preserves accessibility and introduces cumulative alteration'." },
      { q: "What does normalisation sacrifice?", options: ["Security","Documentation","Speed of access","Whatever the chosen formats cannot express"], answer: 3, explanation: "'discards whatever those formats cannot express'." },
      { q: "Why is the choice not purely technical?", options: ["It depends on what a document is taken to be", "It depends on funding", "It is decided by legislation", "It varies by country"], answer: 0, explanation: "'largely a judgement about what a document is'." },
      { q: "Which material is most likely to survive?", options: ["Material stored for future need", "Material consulted regularly", "Material in proprietary formats", "Material held in multiple copies"], answer: 1, explanation: "'material which somebody consults regularly is preserved almost automatically'." }
    ]
  },
  {
    id: "cae-rmc14-02",
    title: "The Politics of the Round Number",
    text: "Public targets are almost always round. Waiting times of eighteen weeks, emissions reductions of fifty per cent, class sizes of thirty. The roundness is not accidental and its effects are considerably larger than the arbitrariness of the figure would suggest.\nA round number is memorable, which is the reason usually given, and it is also a threshold, which is the reason that matters. Any target expressed as a limit divides the world into compliance and failure, and it therefore concentrates effort at precisely the point where the line falls. The predictable consequence is the well-documented cluster of outcomes immediately on the acceptable side of any threshold, in fields ranging from health to education to vehicle emissions, and the equally predictable absence of improvement anywhere else.\nThe response has generally been to add more targets, which multiplies the thresholds without changing the mechanism. A more effective alternative, used in a small number of systems, is to measure the whole distribution and to reward improvement wherever it occurs, which removes the incentive to concentrate effort at the margin. It is administratively harder, it produces no headline, and it is consequently rare.\nThere is a second effect of roundness that is less discussed. A figure like fifty per cent carries an implication of having been chosen by analysis, and it almost never has been. Where the derivation of a target is examined, it is frequently found to have originated as a negotiating position, a political announcement or an approximation of what somebody thought achievable, and the subsequent construction of an evidential case for it has come afterwards.\nNone of this argues against targets, which have demonstrably improved performance in several domains where the previous position was that nobody was measuring anything. It argues for a modest discipline: publishing how the number was arrived at, expecting distortion at the threshold and monitoring for it, and reviewing whether the measure is still measuring the thing it was introduced to represent, which after four or five years it commonly is not.",
    questions: [
      { q: "Why does the writer say roundness matters?", options: ["It is easy to calculate","It is memorable","It functions as a threshold","It looks scientific"], answer: 2, explanation: "'it is also a threshold, which is the reason that matters'." },
      { q: "What is the predictable consequence of a threshold?", options: ["Falling standards everywhere","Increased public trust","Uniform improvement","Clustering just on the acceptable side"], answer: 3, explanation: "'the well-documented cluster of outcomes immediately on the acceptable side of any threshold'." },
      { q: "What is wrong with adding more targets?", options: ["It multiplies thresholds without changing the mechanism","It confuses the public","It slows decision-making","It costs too much"], answer: 0, explanation: "'which multiplies the thresholds without changing the mechanism'." },
      { q: "Why is measuring the whole distribution rare?", options: ["It is statistically invalid", "It is harder and produces no headline", "It is legally restricted", "Staff oppose it"], answer: 1, explanation: "'It is administratively harder, it produces no headline'." },
      { q: "What is often found about the origin of targets?", options: ["They are set by regulators","They come from careful analysis","They began as negotiating positions or announcements","They are copied from other countries"], answer: 2, explanation: "'it is frequently found to have originated as a negotiating position, a political announcement'." },
      { q: "What discipline does the writer recommend?", options: ["Setting more ambitious figures","Delegating targets to professionals","Abolishing targets","Publishing derivations and monitoring distortion"], answer: 3, explanation: "'publishing how the number was arrived at, expecting distortion at the threshold and monitoring for it'." }
    ]
  },
  {
    id: "cae-rmc14-03",
    title: "The Second Language of the Office",
    text: "Every workplace develops a vocabulary that is opaque to outsiders, and the standard complaint about it is that it obscures meaning. That complaint is partly right and largely misses the function, which is not obfuscation but compression.\nA term of art exists because a particular group needs to refer repeatedly to a concept that has no ordinary name. Where the concept is real and the group is competent, the term does exactly what technical vocabulary does in any field: it replaces a paragraph with a word and permits a conversation that would otherwise be impossibly slow. The nurse's shorthand, the printer's terminology and the sailor's names for parts of a boat are all of this kind, and none of them is criticised in the way that the vocabulary of management is.\nThe distinction that matters is whether removing the term would require a longer explanation or a shorter one. Terminology that compresses genuine complexity resists translation; a specialist asked to explain it produces four sentences. Terminology that has been adopted for other reasons translates instantly and downwards, into a plainer phrase that says the same thing with less impressiveness, and the test is therefore easy to apply and rarely applied.\nThe second function of workplace vocabulary is social, and it is the one that generates the resentment. Fluency signals membership. A person who has not learned the terms is identifiable within a minute of a meeting, and the cost of that falls unevenly: on those who joined recently, on those who moved from a different sector, and on anybody for whom the language of the workplace is not their first. The vocabulary that compresses information for insiders simultaneously operates as a barrier at exactly the point where an organisation claims to be recruiting broadly.\nThe practical remedy is neither a ban nor a glossary, both of which have been tried and neither of which survives contact with actual meetings. What works, on the limited evidence available, is a norm that anybody may ask what a term means without any implication about themselves, and that norm is established by senior people asking, which costs them nothing and is therefore, predictably, uncommon.",
    questions: [
      { q: "What does the writer say is the real function of jargon?", options: ["Compression","Exclusion only","Formality","Obfuscation"], answer: 0, explanation: "'which is not obfuscation but compression'." },
      { q: "Which vocabularies are not criticised in the same way?", options: ["Management terms", "Nursing, printing and sailing terms", "Legal terms", "Academic terms"], answer: 1, explanation: "'The nurse's shorthand, the printer's terminology and the sailor's names'." },
      { q: "What test distinguishes useful terminology?", options: ["Whether it appears in dictionaries","Whether it sounds impressive","Whether explaining it takes longer or shorter","How old the term is"], answer: 2, explanation: "'whether removing the term would require a longer explanation or a shorter one'." },
      { q: "What is the second function of workplace vocabulary?", options: ["Speeding up writing","Recording decisions","Legal protection","Signalling membership"], answer: 3, explanation: "'Fluency signals membership.'" },
      { q: "Who bears the cost of that function?", options: ["Newcomers, sector-changers and non-native speakers","Customers","External auditors","Senior managers"], answer: 0, explanation: "'on those who joined recently, on those who moved from a different sector'." },
      { q: "What remedy does the writer favour?", options: ["A ban on jargon","A norm of asking, set by senior people","Training courses","A glossary"], answer: 1, explanation: "'a norm that anybody may ask what a term means without any implication about themselves'." }
    ]
  },
  {
    id: "cae-rmc14-04",
    title: "After the Factory Closes",
    text: "The closure of a dominant employer is generally reported as a jobs figure, and the figure understates the effect by a considerable margin. The direct redundancies are the visible part of a process whose more consequential elements unfold over the following decade and are attributed, by then, to other causes.\nThe first effect is on the local economy through spending. Employment studies consistently find a multiplier: each lost industrial job is associated with the loss of between one and two further jobs in services, retail and construction, and those losses are dispersed across many small employers, which is why they never appear as an announcement.\nThe second is demographic and slower. Those most able to move are the youngest and most qualified, and their departure alters the age structure of the town within a decade. The consequences for schools, health provision and the tax base follow arithmetically, and each is subsequently discussed as a separate problem with its own explanation.\nThe third effect is the least tractable and concerns the transmission of skill. A large employer trains, and the training benefits far more people than it retains: apprentices leave and take capability into local firms, and the presence of a substantial technical workforce sustains a network of suppliers whose expertise depends on having somebody to supply. When the employer goes, that network dissolves over about five years, and it cannot be reconstituted by attracting a replacement employer, because the replacement will find the capability gone.\nThe policy record is discouraging and instructive. Interventions concentrated on attracting a new large employer have generally failed or produced short-lived results. The more successful cases have concentrated on the network rather than the anchor: supporting the suppliers to find other markets before they fail, retaining training capacity even without an obvious employer for it, and acting in the first two years rather than the fifth. The window is short, the required spending is unglamorous, and the political attention is at its highest precisely when the least useful intervention is the most popular.",
    questions: [
      { q: "Why does the jobs figure understate the effect?", options: ["It counts only local residents","It is usually inaccurate","Later effects are attributed to other causes","It excludes part-time work"], answer: 2, explanation: "'unfold over the following decade and are attributed, by then, to other causes'." },
      { q: "Why do multiplier job losses go unannounced?", options: ["They occur elsewhere","They are temporary","They are legally confidential","They are spread across many small employers"], answer: 3, explanation: "'dispersed across many small employers, which is why they never appear as an announcement'." },
      { q: "What demographic change follows?", options: ["Departure of the youngest and most qualified","Population growth","Increased birth rates","An influx of retired people"], answer: 0, explanation: "'Those most able to move are the youngest and most qualified'." },
      { q: "Why does the supplier network dissolve?", options: ["Suppliers relocate immediately", "Their expertise depends on having somebody to supply", "They are bought by competitors", "Regulation changes"], answer: 1, explanation: "'the presence of a substantial technical workforce sustains a network of suppliers whose expertise depends on having somebody to supply'." },
      { q: "What has generally failed as policy?", options: ["Early intervention","Supporting suppliers","Attracting a new large employer","Retaining training capacity"], answer: 2, explanation: "'Interventions concentrated on attracting a new large employer have generally failed'." },
      { q: "What is the difficulty with timing?", options: ["Funding arrives too early","Data are unavailable for years","Elections delay decisions","Attention peaks when the wrong intervention is popular"], answer: 3, explanation: "'the political attention is at its highest precisely when the least useful intervention is the most popular'." }
    ]
  },
  {
    id: "cae-rmc14-05",
    title: "In Defence of Being Bored",
    text: "Boredom has acquired, over the last decade, a small literature arguing that it is valuable, and the literature is more interesting than the slogan it has produced. The claim that boredom is good for creativity is supported by evidence that is real, modest and frequently overstated by people who have read a summary of it.\nThe experimental findings are specific. Participants asked to perform a tedious task and then given a creative problem produce more unusual solutions than participants who went straight to the problem, and the effect is reasonably robust for certain kinds of task. The mechanism proposed is that an undemanding activity permits a mode of thought in which associations form without direction, which is unavailable when attention is fully occupied and which is not the same as rest.\nWhat the research does not show is that boredom is pleasant, that more of it is better, or that the state produced by a tedious laboratory task resembles the boredom of a job with no prospect of change. Chronic boredom in work and education is associated with outcomes that are uniformly bad, and the distinction between an unoccupied hour and an unoccupied life is not a detail.\nThe practical claim that survives is narrower and more useful. Attention that is continuously supplied with input never enters the undirected state, and the modern difficulty is not that people are insufficiently bored in principle but that every interval which used to produce that state has been filled. The queue, the journey, the four minutes waiting for a kettle: these were not valued at the time and were doing something.\nThe recommendation that follows is unappealing precisely because it is so small. Not a retreat, not a period of abstinence, but a decision to leave certain routine intervals unfilled and to tolerate the mild discomfort of the first two minutes, after which the state the research describes generally arrives. Almost nobody does this, and the reason is not addiction in any strong sense; it is that filling the interval is available, costs nothing and feels, at the moment of choosing, obviously better.",
    questions: [
      { q: "How does the writer characterise the evidence?", options: ["Real, modest and often overstated","Entirely unfounded","Applicable only to children","Conclusive and dramatic"], answer: 0, explanation: "'supported by evidence that is real, modest and frequently overstated'." },
      { q: "What mechanism is proposed?", options: ["Rest restores attention", "Undirected association becomes possible", "Motivation increases", "Memory improves"], answer: 1, explanation: "'an undemanding activity permits a mode of thought in which associations form without direction'." },
      { q: "What does the research not show?", options: ["That attention matters","That boredom aids creativity","That chronic boredom is beneficial","That tedious tasks exist"], answer: 2, explanation: "'Chronic boredom in work and education is associated with outcomes that are uniformly bad'." },
      { q: "What does the writer say the modern difficulty is?", options: ["Work has become harder","Attention spans have shortened","People are less creative","Intervals that produced the state have been filled"], answer: 3, explanation: "'every interval which used to produce that state has been filled'." },
      { q: "What recommendation follows?", options: ["Leaving routine intervals unfilled","Deliberately taking tedious jobs","Reducing working hours","A long period of abstinence"], answer: 0, explanation: "'a decision to leave certain routine intervals unfilled'." },
      { q: "Why do few people follow it?", options: ["It is expensive", "Filling the interval feels obviously better at the time", "It is socially unacceptable", "It requires equipment"], answer: 1, explanation: "'filling the interval is available, costs nothing and feels, at the moment of choosing, obviously better'." }
    ]
  },
  {
    id: "cae-rmc14-06",
    title: "The Boundary That Created the Place",
    text: "Administrative boundaries are drawn to make administration possible, and they are generally regarded as descriptions of places that already exist. The direction of causation is frequently the reverse: a line drawn for the convenience of a nineteenth-century registrar becomes, within a few generations, the edge of an identity.\nThe mechanism is not mysterious. A boundary determines which school a child attends, which newspaper reports the area, which team it supports, which authority collects its taxes and which set of neighbours it encounters at every institution. After sixty years of these effects, a difference in outlook exists on either side of a line that was, at the outset, arbitrary, and the difference is then cited as evidence that the boundary reflected something real.\nThe phenomenon has been studied most carefully where boundaries have moved. Where an area has been transferred between authorities, measurable convergence with the new area and divergence from the old begins within about a decade and continues for as long as anybody has measured it. Where a boundary has been abolished, the identity associated with it persists considerably longer than the administrative arrangement, sometimes for a century, which is why local loyalties frequently correspond to entities that no longer legally exist.\nThis has practical consequences for reorganisation, which is undertaken periodically on grounds of efficiency and almost always underestimates the resistance it will meet. The objection to a merger is rarely about the services, which most residents cannot describe in any detail. It is that the proposal asks people to be from somewhere else, and no financial case addresses that, because no financial case recognises it as a cost.\nThe reasonable conclusion is not that boundaries should never change. It is that a boundary is not a neutral instrument, that redrawing one is an intervention in identity as well as administration, and that the costs of the intervention arrive over decades while the savings are claimed within a single financial year. That asymmetry, and not sentimentality, is why such reorganisations so frequently disappoint the people who commissioned them.",
    questions: [
      { q: "What does the writer say about causation?", options: ["The relationship is coincidental","Boundaries describe existing places","Boundaries often create the identities they seem to describe","Identities determine boundaries"], answer: 2, explanation: "'a line drawn for the convenience of a nineteenth-century registrar becomes, within a few generations, the edge of an identity'." },
      { q: "How does a boundary produce difference?", options: ["Through language change","Through migration","Through geography","Through the institutions it determines"], answer: 3, explanation: "'A boundary determines which school a child attends, which newspaper reports the area'." },
      { q: "What happens when an area is transferred?", options: ["Convergence with the new area begins within a decade","Residents move away","The old identity strengthens","Nothing measurable changes"], answer: 0, explanation: "'measurable convergence with the new area and divergence from the old begins within about a decade'." },
      { q: "What happens when a boundary is abolished?", options: ["The identity disappears immediately", "The identity persists far longer than the arrangement", "Services improve", "A new identity forms at once"], answer: 1, explanation: "'the identity associated with it persists considerably longer than the administrative arrangement'." },
      { q: "Why do mergers meet resistance?", options: ["Staff will be dismissed","Residents fear worse services","People are asked to be from somewhere else","Costs will rise"], answer: 2, explanation: "'the proposal asks people to be from somewhere else'." },
      { q: "What asymmetry does the writer identify?", options: ["Savings never materialise","Only rural areas are affected","Larger authorities benefit most","Costs arrive over decades, savings are claimed in a year"], answer: 3, explanation: "'the costs of the intervention arrive over decades while the savings are claimed within a single financial year'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
