/* CAE Prep bank: Reading multiple choice (C1) — wave 24 */
(function () {
var BANK = [
  {
    id: "cae-rmc24-01",
    title: "The People Who Test the Product",
    text: "Products are tested, before release, by people who are unrepresentative in a specific and predictable way: they are employees of the organisation, enthusiasts recruited from a mailing list, or professional testers. Each group is competent, motivated and entirely unlike the eventual user, and the resulting evidence is systematically optimistic.\nThe employee has the deepest knowledge and the greatest blindness. Somebody who understands the intended model of a system cannot experience the interface as somebody who does not, and the attempt to simulate this is unreliable in a way that is well documented: knowledge cannot be temporarily set aside on request.\nThe enthusiast is more useful and introduces a different distortion. A person who volunteers to test something has an unusual tolerance for difficulty and an interest in the category, and their feedback consistently emphasises capability over accessibility. Products tested predominantly by enthusiasts acquire features and lose clarity, which describes the trajectory of a substantial proportion of software.\nThe professional tester detects defects reliably and cannot detect the absence of a purpose. A test plan verifies that the product does what the specification says, and the question of whether the specification describes anything anybody wants is outside the exercise.\nWhat is generally missing is the reluctant user: somebody who did not choose the product, does not care about the category and needs to accomplish one thing. Observation of such users produces findings that the other groups cannot generate, and it is rarely conducted, because recruiting people who are indifferent to a product is harder than recruiting people who are interested in it, and because the findings are unwelcome.\nThe most useful practice, on the available evidence, is small and frequent: four or five observed sessions with genuinely naive users, repeated at intervals throughout development rather than concentrated at the end. This detects the majority of significant problems, costs very little, and is displaced with remarkable consistency by a larger exercise conducted too late to change anything, which produces a report rather than a decision.",
    questions: [
      { q: "How are pre-release testers unrepresentative?", options: ["They are competent, motivated and unlike real users","They test too quickly","They are paid","They are less competent"], answer: 0, explanation: "'Each group is competent, motivated and entirely unlike the eventual user'." },
      { q: "What is the employee's limitation?", options: ["Lack of time", "Knowledge cannot be set aside on request", "Poor technical skill", "Conflict of interest"], answer: 1, explanation: "'knowledge cannot be temporarily set aside on request'." },
      { q: "What distortion do enthusiasts introduce?", options: ["Slow feedback","Focus on price","Emphasis on capability over accessibility","Excessive criticism"], answer: 2, explanation: "'their feedback consistently emphasises capability over accessibility'." },
      { q: "What can professional testers not detect?", options: ["Performance problems","Interface errors","Defects","The absence of a purpose"], answer: 3, explanation: "'cannot detect the absence of a purpose'." },
      { q: "Who is generally missing from testing?", options: ["The reluctant, indifferent user","Overseas users","Competitors","Senior managers"], answer: 0, explanation: "'What is generally missing is the reluctant user'." },
      { q: "What practice does the evidence support?", options: ["A large exercise at the end", "Small frequent sessions with naive users", "Automated testing only", "Longer test plans"], answer: 1, explanation: "'four or five observed sessions with genuinely naive users, repeated at intervals'." }
    ]
  },
  {
    id: "cae-rmc24-02",
    title: "After the Recall",
    text: "A product recall is reported as an event and is more accurately understood as a process with a long and poorly performing tail. The announcement is the beginning; what matters is the proportion of affected units actually returned, and that figure is, across most categories, far lower than the public assumes.\nCompletion rates vary enormously by product type and the variation is explicable. Recalls of vehicles achieve high rates because ownership is registered, the owner can be contacted directly, and the remedy is free and performed by a dealer the owner already visits. Recalls of small household goods achieve low rates, frequently under twenty per cent, because nobody knows who owns them, the notification relies on the customer noticing a public announcement, and the remedy requires effort from somebody who may not perceive a risk.\nThe consequence is that a substantial population of recalled items remains in use indefinitely, and the risk is concentrated among people who are least likely to encounter the notification and most likely to acquire the item second-hand, since a recalled product does not stop being sold privately.\nThe interventions that improve the figure are known and unevenly applied. Registration at the point of sale, which requires an incentive to complete. Direct notification, which requires the retailer to hold and use the record. And, most effectively, a remedy that is easier than doing nothing: collection from the address rather than return by post, which raises completion substantially and costs more per unit than every other option combined.\nThere is a reporting problem underlying all of this. In most jurisdictions, a manufacturer must announce a recall and is not required to publish its completion rate, which means the only public information concerns the announcement. An organisation that conducts a recall well and one that issues a notice and does nothing further are indistinguishable in the public record, and where a measure is not published there is no mechanism by which performing well produces any advantage.",
    questions: [
      { q: "How should a recall be understood?", options: ["As a marketing exercise","As a single event","As a process with a long tail","As a legal formality"], answer: 2, explanation: "'more accurately understood as a process with a long and poorly performing tail'." },
      { q: "Why do vehicle recalls achieve high rates?", options: ["Owners are more attentive","The law requires compliance","Vehicles are more dangerous","Ownership is registered and owners can be contacted"], answer: 3, explanation: "'ownership is registered, the owner can be contacted directly'." },
      { q: "Why are household goods rates low?", options: ["Nobody knows who owns them","Remedies are expensive","Risks are minor","Products are cheap"], answer: 0, explanation: "'because nobody knows who owns them'." },
      { q: "Where is the remaining risk concentrated?", options: ["Among original purchasers", "Among those least likely to see notices", "Among retailers", "Among manufacturers"], answer: 1, explanation: "'the risk is concentrated among people who are least likely to encounter the notification'." },
      { q: "Which remedy is most effective?", options: ["Online registration","Postal return","Collection from the address","Retail exchange"], answer: 2, explanation: "'collection from the address rather than return by post, which raises completion substantially'." },
      { q: "What is the reporting problem?", options: ["Notices are unclear","Data are inaccurate","Recalls are not announced","Completion rates are not published"], answer: 3, explanation: "'is not required to publish its completion rate'." }
    ]
  },
  {
    id: "cae-rmc24-03",
    title: "What Makes a Street Feel Safe",
    text: "The perception of safety in a public space corresponds only loosely to the recorded incidence of crime, and the divergence is not a failure of perception. People are responding to features of the environment that predict the possibility of help, the presence of witnesses and the availability of escape, and these are reasonable things to attend to.\nThe features that emerge consistently in the research are unglamorous. Sightlines matter, because a space whose exits cannot be seen produces discomfort regardless of its statistics. Lighting matters, and matters in a specific way that is regularly misunderstood: uniformity is more important than brightness, since a bright light creates a dark region beside it and produces exactly the shadowed area that causes concern. Activity at street level matters most of all, and a street of blank facades feels unsafe at a level of crime at which a street of windows and doorways does not.\nThe practical difficulty is that the interventions which improve the statistics and those which improve the perception are not the same set. Cameras affect recorded crime modestly in certain applications and do little for how a space feels, since a camera implies that somebody may review a recording later rather than that anybody is present now. Physical measures that harden a space against crime frequently make it feel more dangerous, because they announce that danger has been anticipated.\nThe intervention with the strongest evidence in both dimensions is the presence of people with a reason to be there. Where a space has been redesigned to give somebody a purpose in occupying it, both incidence and perception improve, and the effect is durable in a way that surveillance is not.\nWhat follows is that safety in public space is largely a by-product of use rather than a property that can be added to a place. A space designed to be safe and empty will be neither, and a space that is busy for reasons unconnected with security is generally safe without anybody having addressed the question.",
    questions: [
      { q: "Why is the divergence not a failure of perception?", options: ["People respond to reasonable environmental cues","Crime is under-reported","Perception is irrelevant","Statistics are unreliable"], answer: 0, explanation: "'these are reasonable things to attend to'." },
      { q: "How is lighting misunderstood?", options: ["Brightness matters more than uniformity", "Uniformity matters more than brightness", "Colour is decisive", "Timing is decisive"], answer: 1, explanation: "'uniformity is more important than brightness'." },
      { q: "Which feature matters most?", options: ["Sightlines", "Lighting", "Activity at street level", "Signage"], answer: 2, explanation: "'Activity at street level matters most of all'." },
      { q: "Why do cameras do little for perception?", options: ["They are hidden","They are unpopular","They are often broken","They imply later review rather than present help"], answer: 3, explanation: "'a camera implies that somebody may review a recording later rather than that anybody is present now'." },
      { q: "Why can hardening measures backfire?", options: ["They announce that danger has been anticipated","They block sightlines","They attract vandalism","They are expensive"], answer: 0, explanation: "'because they announce that danger has been anticipated'." },
      { q: "What does the writer conclude about safety?", options: ["It is a property that can be added", "It is largely a by-product of use", "It depends on policing", "It cannot be influenced by design"], answer: 1, explanation: "'safety in public space is largely a by-product of use'." }
    ]
  },
  {
    id: "cae-rmc24-04",
    title: "The Branch That Closed",
    text: "The closure of local bank branches is generally justified by transaction volumes, and the justification is accurate as far as it goes. Counter transactions have fallen steeply, the cost per transaction in a branch is many times that of a digital equivalent, and a network built for a population that visited weekly is expensive to maintain for one that visits twice a year.\nWhat the transaction count does not capture is the distribution of who is left. The customers still using a counter are disproportionately older, disproportionately reliant on cash, and include a category that the data describe poorly: small businesses depositing takings, which cannot be done digitally and for which the alternative is a journey with a substantial sum of money.\nThe second uncaptured effect concerns what a branch does that is not a transaction. Staff in branches identify a proportion of financial abuse cases, since a customer being coerced into withdrawing money is visible to somebody who knows them and invisible to a system that sees a valid instruction. Where branches have closed, the reporting of such cases falls, and there is no reason to believe the incidence does.\nThe replacements are instructive. Banking services delivered through post offices work reasonably for cash and poorly for anything requiring advice. Mobile branches visiting weekly serve those who can reach them at a fixed hour. Shared banking hubs, in which several institutions provide a joint counter, are the arrangement with the best evidence and the slowest deployment, since each participant would prefer another to bear the cost.\nThe underlying question is one that the industry cannot answer alone. Access to cash and to face-to-face financial services has characteristics of an infrastructure: it is used by a minority, that minority is not identifiable in advance, and its absence imposes costs elsewhere. Where such services have been left entirely to commercial judgement, the result has been a reliable and predictable withdrawal from the places where the cost per customer is highest, which are, without exception, the places where the alternatives are fewest.",
    questions: [
      { q: "What does the writer accept about the justification?", options: ["It is dishonest","It is entirely wrong","It is accurate as far as it goes","It is exaggerated"], answer: 2, explanation: "'the justification is accurate as far as it goes'." },
      { q: "Which group does the data describe poorly?", options: ["Digital users","Overseas customers","Older customers","Small businesses depositing takings"], answer: 3, explanation: "'small businesses depositing takings, which cannot be done digitally'." },
      { q: "What non-transactional role do branch staff perform?", options: ["Identifying financial abuse","Training customers","Auditing accounts","Selling products"], answer: 0, explanation: "'Staff in branches identify a proportion of financial abuse cases'." },
      { q: "What happens to reporting when branches close?", options: ["It rises", "It falls without incidence falling", "It stays the same", "It moves online"], answer: 1, explanation: "'the reporting of such cases falls, and there is no reason to believe the incidence does'." },
      { q: "Which replacement has the best evidence?", options: ["Post office services", "Mobile branches", "Shared banking hubs", "Telephone banking"], answer: 2, explanation: "'Shared banking hubs... are the arrangement with the best evidence'." },
      { q: "Why do hubs deploy slowly?", options: ["Sites are unavailable","Customers object","Regulation is unclear","Each participant wants another to bear the cost"], answer: 3, explanation: "'each participant would prefer another to bear the cost'." }
    ]
  },
  {
    id: "cae-rmc24-05",
    title: "Reporting What Went Wrong",
    text: "Organisations that handle risk seriously depend on being told about events that did not cause harm, and the willingness of individuals to report such events is the variable that determines whether the system works. It is also the variable most easily destroyed, and the mechanisms by which it is destroyed are well understood.\nThe first is consequence. Where a report can result in disciplinary action, the rate of reporting falls to a fraction of the underlying rate, and what continues to be reported is the category of event that cannot be concealed. Systems that achieve high reporting separate the safety process from the disciplinary one explicitly and demonstrably, which requires more than a stated policy: it requires a visible instance in which somebody reported something serious and was not disciplined, and until that instance occurs nobody believes the policy.\nThe second is futility. A person who reports an event and observes that nothing happens will report the next one at a lower rate, and after four such experiences will stop. Feedback is therefore not a courtesy but a functional requirement, and the feedback that matters is not thanks but evidence of consequence: this was changed, that was examined, this was found not to require action and here is why.\nThe third is the design of the form. Reporting systems that demand extensive narrative in free text produce fewer reports than those requiring a short structured entry, and this effect is large enough to determine whether a system functions. A busy person will not write four paragraphs at the end of a shift, and a system that requires it has selected for the events somebody considered worth four paragraphs, which is not the sample anybody wanted.\nWhat these have in common is that they are all decisions about the experience of the person reporting, made by people who will never use the system. The organisations with the best reporting cultures have generally arrived there by asking that person what would make it easier, which is an obvious thing to do and is done remarkably rarely.",
    questions: [
      { q: "What determines whether a reporting system works?", options: ["Individuals' willingness to report","Management commitment","Regulatory pressure","The technology used"], answer: 0, explanation: "'the willingness of individuals to report such events is the variable that determines whether the system works'." },
      { q: "What is required beyond a stated policy?", options: ["Legal protection", "A visible instance of no discipline following a report", "Anonymous reporting", "External audit"], answer: 1, explanation: "'it requires a visible instance in which somebody reported something serious and was not disciplined'." },
      { q: "What happens when reporting produces no visible result?", options: ["Nothing changes","Reports become more detailed","Reporting declines and then stops","Other channels are used"], answer: 2, explanation: "'will report the next one at a lower rate, and after four such experiences will stop'." },
      { q: "What kind of feedback matters?", options: ["Statistical summaries","Public recognition","Expressions of thanks","Evidence of consequence"], answer: 3, explanation: "'the feedback that matters is not thanks but evidence of consequence'." },
      { q: "Why do long free-text forms reduce reporting?", options: ["Busy people will not write at length","They require approval","They are not confidential","They are hard to understand"], answer: 0, explanation: "'A busy person will not write four paragraphs at the end of a shift'." },
      { q: "What do the three failures have in common?", options: ["They are technical problems", "They are decisions made by non-users about users' experience", "They result from underfunding", "They are legally mandated"], answer: 1, explanation: "'decisions about the experience of the person reporting, made by people who will never use the system'." }
    ]
  },
  {
    id: "cae-rmc24-06",
    title: "The Claim Everybody Repeats",
    text: "Certain claims circulate for decades with no evidential support, and the ones that persist share a set of properties that are worth identifying, because recognising them is more useful than checking each claim individually.\nThe first is that the claim is useful to somebody. A figure about the economic cost of a problem is quoted by the organisations addressing that problem, and a figure that is too small does not survive. This does not mean the number was invented; it means that of the several estimates available, the largest is the one that circulates.\nThe second is that the claim is unfalsifiable in practice. Assertions about what people did before records existed, or about the effects of something on a population too large to observe, cannot be checked by any reader, and the absence of correction is mistaken for confirmation.\nThe third is that a citation exists. Tracing quoted figures back through their sources frequently ends at a document that does not contain the number, at a source that cited a source, or at a paper whose careful estimate has lost its qualifications somewhere in the chain. The presence of a reference is treated as evidence in itself, and the number of readers who follow one is small enough that the practice is safe.\nThe fourth and most persistent property is that the claim is nearly true. A statement that is broadly consistent with what a reader already believes, and which exaggerates only in degree, is not challenged, because challenging it appears to require denying the underlying point.\nThe practical response is not scepticism about everything, which is exhausting and produces its own errors. It is a habit applied to figures that are doing rhetorical work: to ask who benefits from the number being this size, and to notice when a precise figure is attached to a quantity that could not plausibly have been measured. The second question disposes of a surprising proportion of them without any research at all.",
    questions: [
      { q: "What is the first property of persistent claims?", options: ["They are complex","They are recent","They are useful to somebody","They are precise"], answer: 2, explanation: "'The first is that the claim is useful to somebody.'" },
      { q: "What happens to smaller estimates?", options: ["They are published separately","They are preferred","They are corrected","They do not survive in circulation"], answer: 3, explanation: "'a figure that is too small does not survive'." },
      { q: "How is the absence of correction interpreted?", options: ["As confirmation", "As indifference", "As censorship", "As a gap in research"], answer: 0, explanation: "'the absence of correction is mistaken for confirmation'." },
      { q: "What do citation trails often end at?", options: ["The original study", "A document that does not contain the number", "A government report", "A textbook"], answer: 1, explanation: "'ends at a document that does not contain the number'." },
      { q: "Why are nearly true claims rarely challenged?", options: ["They are legally protected","They are technically correct","Challenging appears to deny the underlying point","They are trivial"], answer: 2, explanation: "'because challenging it appears to require denying the underlying point'." },
      { q: "Which question disposes of many claims quickly?", options: ["When it was first made","How often it is repeated","Who published it","Whether the quantity could plausibly have been measured"], answer: 3, explanation: "'to notice when a precise figure is attached to a quantity that could not plausibly have been measured'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
