/* CAE Prep bank: Reading multiple choice (C1) — wave 20 */
(function () {
var BANK = [
  {
    id: "cae-rmc20-01",
    title: "Why Deadlines Move",
    text: "Projects overrun with a consistency that suggests something structural rather than a series of local failures, and the research on estimation identifies the mechanism with unusual clarity. People do not fail to allow for the things that might go wrong; they fail to allow for the things they have not thought of, and no amount of care in listing risks addresses a category defined by not having occurred to anybody.\nThe most robust finding in this area is that estimates improve substantially when the estimator is asked about similar past projects rather than about the project in hand. An engineer asked how long a task will take produces a figure derived from imagining the work; the same engineer asked how long the last four comparable tasks took produces a figure that is both larger and considerably more accurate. The second question is rarely asked, in part because organisations frequently do not record the answer.\nThe second contributor is that estimates are made by people with an interest in the outcome. A figure produced by somebody who wants the project approved is not a forecast; it is a bid, and everybody involved understands this while continuing to treat the number as a prediction. Where estimates are prepared by a party without a stake in approval, the pattern of overrun reduces markedly, which is a finding with obvious institutional implications and almost no institutional uptake.\nThe third is the treatment of buffers. Time allowed for contingency at the level of an individual task is consumed by that task, because work expands and because an early finish is rarely reported. Buffers held at the level of the project, released deliberately, survive; buffers distributed into every task disappear without anybody being able to say where they went.\nThe implication is that better estimation is not primarily a matter of trying harder. It is a matter of recording what actually happened last time, asking somebody without a stake, and holding contingency where it can be seen. All three are procedural, none is difficult, and the reason they are uncommon is that each of them makes visible a number that somebody would prefer to keep imprecise.",
    questions: [
      { q: "What do estimators fail to allow for?", options: ["Things that have not occurred to anybody","Staff absences","Cost inflation","Known risks"], answer: 0, explanation: "'they fail to allow for the things they have not thought of'." },
      { q: "What improves estimates substantially?", options: ["Consulting more people","Asking about similar past projects","Allowing more time to estimate","Using software"], answer: 1, explanation: "'estimates improve substantially when the estimator is asked about similar past projects'." },
      { q: "Why is that question rarely asked?", options: ["It is considered rude","Estimators refuse","Organisations do not record the answer","It takes too long"], answer: 2, explanation: "'organisations frequently do not record the answer'." },
      { q: "What does the writer say a figure from an interested party is?", options: ["An average","A guess","A forecast","A bid"], answer: 3, explanation: "'it is a bid'." },
      { q: "What happens to buffers held within individual tasks?", options: ["They are consumed by the task","They are reported to managers","They double the estimate","They are saved for later"], answer: 0, explanation: "'Time allowed for contingency at the level of an individual task is consumed by that task'." },
      { q: "Why are the remedies uncommon?", options: ["They are expensive", "Each makes visible a number somebody prefers imprecise", "They require new software", "Staff resist them"], answer: 1, explanation: "'each of them makes visible a number that somebody would prefer to keep imprecise'." }
    ]
  },
  {
    id: "cae-rmc20-02",
    title: "What a Waiting List Is For",
    text: "A waiting list is generally understood as a symptom: evidence that demand exceeds capacity and that more capacity is required. It is also, and less obviously, an allocation mechanism, and the choice of mechanism has consequences that are frequently more significant than the length of the list.\nA list ordered by date of referral allocates by arrival, which is administratively simple and fair in a particular sense. It also allocates against people who present late, and presenting late is correlated with almost every measure of disadvantage. A list ordered by clinical urgency allocates by need and requires an assessment which is itself a resource, and where the assessment is scarce the list for the assessment becomes the operative queue.\nThe more interesting effects concern behaviour. A visible list changes what referrers do: a clinician aware that a service has a two-year wait refers fewer patients to it, which reduces the list without reducing the need and produces an apparent improvement that is entirely an artefact of the referral behaviour. Where this is not understood, the service is judged to have improved and its capacity is reduced accordingly.\nThere is also a distinction between a queue and a buffer that is routinely missed. A short list is not a failure; a service with no list at all is a service holding idle capacity, which is expensive and rarely tolerated. The optimal list is not zero, and the objective of removing all waiting produces a system that is either extremely costly or reports zero by defining the wait as beginning at a later point.\nWhat the evidence supports is unglamorous. Publishing the distribution rather than the average, since a mean of eleven weeks conceals whether that is everybody or a mixture of two weeks and two years. Measuring the wait from the patient's first contact rather than from an administrative event that occurs later. And treating the list as a description of how a service allocates rather than as a number to be reduced, since a number that is being reduced will be, and the means by which that happens is the thing that matters.",
    questions: [
      { q: "What does the writer say a waiting list also is?", options: ["A planning error","A performance measure","An allocation mechanism","A funding tool"], answer: 2, explanation: "'It is also, and less obviously, an allocation mechanism'." },
      { q: "Who is disadvantaged by ordering by referral date?", options: ["Those living far away","Those referred by specialists","Those with urgent needs","Those who present late"], answer: 3, explanation: "'It also allocates against people who present late'." },
      { q: "What happens when a service has a long visible wait?", options: ["Clinicians refer fewer patients","Capacity is expanded","Patients complain more","Referrals increase"], answer: 0, explanation: "'a clinician aware that a service has a two-year wait refers fewer patients to it'." },
      { q: "Why is a service with no list problematic?", options: ["It attracts too many referrals","It is holding idle capacity","It has no demand","It cannot be measured"], answer: 1, explanation: "'a service with no list at all is a service holding idle capacity'." },
      { q: "What does an average wait conceal?", options: ["Referral sources","The number of patients","Whether it describes everybody or a mixture","The cost of treatment"], answer: 2, explanation: "'a mean of eleven weeks conceals whether that is everybody or a mixture'." },
      { q: "What does the writer warn about targets to reduce lists?", options: ["They increase costs","They are unpopular with staff","They are impossible to meet","The number will fall and the means matter"], answer: 3, explanation: "'a number that is being reduced will be, and the means by which that happens is the thing that matters'." }
    ]
  },
  {
    id: "cae-rmc20-03",
    title: "The Third Person in the Room",
    text: "An interpreted conversation is frequently described as though it were a conversation between two people with a technical intermediary. Interpreters describe something different: a three-party interaction in which their presence changes what is said, and in which the pretence that it does not is the source of most of the difficulties.\nThe first alteration is temporal. Consecutive interpreting doubles the length of every exchange, which changes what participants choose to say: complex qualifications are dropped, digressions are abandoned, and the conversation moves towards the transactional. A speaker who would have made a subtle point in their own language frequently does not attempt it, and the loss is invisible because nothing was said.\nThe second concerns register. An interpreter must render not only content but the relationship the speaker is establishing, and the equivalent of a politeness in one language may be an insult or an absurdity in another. The resolution requires a judgement, and the judgement is the interpreter's, which means the neutral conduit described in the professional literature does not exist in any interesting case.\nThe third and most consequential is address. Participants routinely speak to the interpreter rather than to each other, in the third person, and the effect on the person being discussed is well documented and uniformly bad. Professional guidance addresses this and the guidance is followed inconsistently, particularly by people who are anxious, which describes most participants in medical and legal settings.\nThe practical recommendations that follow are simple and often ignored. Speak to the person, not the interpreter. Use short complete sentences rather than fragments, since a fragment cannot be rendered without the interpreter supplying the missing part. Allow more time and say so at the start. And never use a family member for anything consequential, which is the commonest departure from good practice and is defended on grounds of convenience by people who have not considered what a child interpreting a diagnosis is being asked to carry.",
    questions: [
      { q: "How do interpreters describe an interpreted conversation?", options: ["As a three-party interaction","As a technical process","As a translation exercise","As two people with an intermediary"], answer: 0, explanation: "'a three-party interaction in which their presence changes what is said'." },
      { q: "What is the effect of doubling exchange length?", options: ["Greater precision", "Conversation becomes more transactional", "More digressions", "Longer meetings only"], answer: 1, explanation: "'the conversation moves towards the transactional'." },
      { q: "Why is the loss invisible?", options: ["The interpreter conceals it","Records are not kept","Nothing was said","Participants do not notice time"], answer: 2, explanation: "'the loss is invisible because nothing was said'." },
      { q: "Why does the neutral conduit not exist?", options: ["Languages are too different","Guidance is unclear","Interpreters are poorly trained","Register requires the interpreter's judgement"], answer: 3, explanation: "'The resolution requires a judgement, and the judgement is the interpreter's'." },
      { q: "What is the most consequential alteration?", options: ["How participants address each other","Vocabulary","Timing","Register"], answer: 0, explanation: "'The third and most consequential is address.'" },
      { q: "What practice does the writer particularly warn against?", options: ["Using consecutive interpreting", "Using a family member for consequential matters", "Speaking too slowly", "Using written notes"], answer: 1, explanation: "'never use a family member for anything consequential'." }
    ]
  },
  {
    id: "cae-rmc20-04",
    title: "The Design of the Ballot",
    text: "The ballot paper is the point at which an intention becomes a recorded fact, and it is designed, in most jurisdictions, by people whose expertise is administrative rather than in how documents are read under pressure. The consequences are measurable and have decided elections.\nThe research findings are unambiguous where they have been studied. Position on the paper affects vote share independently of everything else, with an advantage to the first position that varies by contest and is largest where information about candidates is scarce. Instructions placed after the point at which a voter has begun marking are not read. A design requiring a different action in different sections of the same paper produces errors concentrated among voters with less formal education, which is not a statement about capability but about familiarity with document conventions.\nThe remedies are known and the obstacles are institutional. Randomising or rotating candidate order removes the position effect and complicates counting. Testing a design with actual voters before an election is standard practice in the design of any commercial form and is rare in electoral administration, where the design is frequently prescribed in legislation and can only be altered by amending it.\nThere is a further difficulty specific to this domain. Any change to a ballot design has a differential effect on the parties contesting the election, which means every proposal, however technical, is evaluated by people who can calculate whether it helps them. A reform that would reduce spoiled papers by two per cent is not assessed as an administrative improvement; it is assessed as a change with a known partisan direction, and it is generally blocked by whoever loses by it.\nThe conclusion is not that ballot design is hopeless but that it belongs with the small class of decisions that must be removed from the people affected by them. Where design has been delegated to an independent body with a published methodology and a duty to test, the errors have fallen. Where it remains with a legislature, it has not, and the difference is not a matter of technical knowledge, since both have access to the same research.",
    questions: [
      { q: "Who usually designs ballot papers?", options: ["Independent commissions","Document designers","People with administrative expertise","Political parties"], answer: 2, explanation: "'designed... by people whose expertise is administrative'." },
      { q: "When is the position advantage largest?", options: ["In local elections","When turnout is high","In national elections","Where information about candidates is scarce"], answer: 3, explanation: "'is largest where information about candidates is scarce'." },
      { q: "Who is most affected by inconsistent designs?", options: ["Voters with less formal education","First-time voters","Postal voters","Older voters"], answer: 0, explanation: "'produces errors concentrated among voters with less formal education'." },
      { q: "Why is testing rare in electoral administration?", options: ["It is expensive", "Designs are prescribed in legislation", "Voters refuse to participate", "Results are unreliable"], answer: 1, explanation: "'the design is frequently prescribed in legislation'." },
      { q: "Why are technical reforms blocked?", options: ["They delay elections","They cost too much","They have calculable partisan effects","They confuse officials"], answer: 2, explanation: "'evaluated by people who can calculate whether it helps them'." },
      { q: "What does the writer conclude?", options: ["Ballots should be simplified","Legislatures should be trained","Electronic voting is the answer","Design should be delegated to an independent body"], answer: 3, explanation: "'Where design has been delegated to an independent body with a published methodology and a duty to test, the errors have fallen.'" }
    ]
  },
  {
    id: "cae-rmc20-05",
    title: "The Arithmetic of the Small School",
    text: "A school with forty pupils costs more per pupil than one with four hundred, and no amount of good management alters that. The costs that do not scale are the ones that determine the figure: a building must be heated and insured whether it holds forty children or two hundred, and a teacher must be present for a class of nine as for a class of twenty-nine.\nThe standard response is consolidation, and the case for it is straightforward: the same money produces more teaching, more specialist provision and more resilience if it is concentrated. The case against is generally made in terms of community, which is real and difficult to price, and it is stronger when it is made in terms that can be measured.\nThe measurable costs of closure fall in three places. Transport, which is paid by the authority and rises immediately. Attendance, which falls measurably where journeys exceed a certain duration, with the effect concentrated among the pupils whose attendance was already marginal. And parental participation, which declines sharply with distance and is one of the better predictors of educational outcome available.\nThere is also an effect that appears outside the education budget. A village that loses its school loses the mechanism by which families with young children meet each other, and the demographic consequence over twenty years is documented well enough to be predictable. The saving appears in one account within a year; the cost appears in several others over a generation, which is the same asymmetry that governs almost every decision of this kind.\nThe alternatives that have worked involve neither closure nor the preservation of every school as it was. Federations sharing a head teacher and specialist staff across several sites retain the local building and capture a substantial part of the efficiency. They require an administrative structure that is harder to design than a closure and considerably harder to announce, since the achievement consists of a set of arrangements rather than a decision, and nobody has ever been photographed opening one.",
    questions: [
      { q: "Which costs determine the per-pupil figure?", options: ["Costs that do not scale with numbers","Staff salaries only","Transport","Teaching materials"], answer: 0, explanation: "'The costs that do not scale are the ones that determine the figure'." },
      { q: "How is the case against closure usually made?", options: ["In terms of cost", "In terms of community", "In terms of law", "In terms of examination results"], answer: 1, explanation: "'The case against is generally made in terms of community'." },
      { q: "Where do the measurable costs of closure fall?", options: ["Insurance and heating","Examination performance","Transport, attendance and parental participation","Buildings, staff and equipment"], answer: 2, explanation: "'Transport, which is paid by the authority and rises immediately.'" },
      { q: "Whose attendance falls most?", options: ["Pupils with long-standing illness","New arrivals","Younger pupils","Those whose attendance was already marginal"], answer: 3, explanation: "'with the effect concentrated among the pupils whose attendance was already marginal'." },
      { q: "What effect appears outside the education budget?", options: ["Demographic change in the village","Reduced insurance","Falling property values","Higher transport costs"], answer: 0, explanation: "'the demographic consequence over twenty years is documented well enough to be predictable'." },
      { q: "Why are federations hard to announce?", options: ["They save no money", "The achievement is a set of arrangements, not a decision", "They are legally complex", "They are unpopular locally"], answer: 1, explanation: "'the achievement consists of a set of arrangements rather than a decision'." }
    ]
  },
  {
    id: "cae-rmc20-06",
    title: "Attending Without Being There",
    text: "Remote attendance was, for most institutions, an emergency measure that has become permanent, and the argument about it has settled into two positions that are both partly right and that mostly talk past each other.\nThe case for is straightforward and unanswered in its own terms. Remote access removes travel, which removes cost, time and a set of barriers that fall disproportionately on people with caring responsibilities, limited mobility or restricted budgets. Attendance at events with a remote option is consistently higher and more diverse, and any argument that concludes with a return to presence-only has to explain what should be said to the people who could attend under one arrangement and not the other.\nThe case against is generally stated badly, in terms of atmosphere or commitment, and it has a more defensible version. What remote attendance reproduces well is the transmission of content. What it reproduces poorly is everything that depends on unplanned interaction: the conversation after the session, the question somebody was not confident enough to ask publicly, the introduction made by a third party who noticed two people should meet. These are not incidental benefits of attendance; in most professional settings they are the principal ones, and they are the reason organisations continue to pay for travel that transmits information they could have sent in an email.\nThe hybrid arrangement, which appears to solve the problem, has produced the least satisfactory outcome in several studies. A meeting with participants in a room and participants on a screen tends towards two conversations, and the remote group is systematically disadvantaged in a way that no amount of technology corrects, because the disadvantage is in the difficulty of interrupting.\nThe institutions that have handled this best have stopped attempting to make one format serve both purposes. Content is transmitted remotely, deliberately and to everybody. Occasions designed for interaction are held in person, less frequently, with the interaction as the explicit purpose rather than as something expected to occur around a programme. This is more work than either alternative and it is the only arrangement that treats both cases honestly.",
    questions: [
      { q: "How does the writer describe the case for remote attendance?", options: ["Based on cost alone","Weak","Straightforward and unanswered in its own terms","Exaggerated"], answer: 2, explanation: "'The case for is straightforward and unanswered in its own terms.'" },
      { q: "Who benefits most from remote access?", options: ["International participants","Younger attendees","Senior staff","People with caring responsibilities or limited mobility"], answer: 3, explanation: "'barriers that fall disproportionately on people with caring responsibilities, limited mobility or restricted budgets'." },
      { q: "What does remote attendance reproduce poorly?", options: ["Unplanned interaction","Formal presentations","Recording of sessions","Content transmission"], answer: 0, explanation: "'What it reproduces poorly is everything that depends on unplanned interaction'." },
      { q: "Why does the writer call these benefits principal?", options: ["They are enjoyable", "They are the reason organisations pay for travel", "They are easy to measure", "They are traditional"], answer: 1, explanation: "'they are the reason organisations continue to pay for travel'." },
      { q: "What is the problem with hybrid meetings?", options: ["Content is duplicated","They require expensive equipment","Remote participants cannot easily interrupt","They last longer"], answer: 2, explanation: "'the disadvantage is in the difficulty of interrupting'." },
      { q: "What approach has worked best?", options: ["Returning to presence only","Recording everything","Making one format serve both purposes","Separating content transmission from interaction"], answer: 3, explanation: "'have stopped attempting to make one format serve both purposes'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
