/* CAE Prep bank: reading multiple-choice (wave 7) */
(function () {
var BANK = [
  {
    id: "cae-rmc7-01",
    title: "The Economics of the Empty Seat",
    text: "Every performance that opens with rows of empty seats represents a peculiar kind of waste. The cost of the evening has already been incurred: the musicians are paid, the lights burn, the building is heated whether the hall is full or a third full. An unsold seat, unlike unsold bread, cannot be discounted tomorrow; the moment the curtain rises it becomes worthless. Economists call this perishability, and it explains a great deal of behaviour that audiences find irritating — the last-minute offers, the fluctuating prices, the schemes that seem to reward disloyalty by charging the eager early booker more than the person who wandered in at seven o'clock. The obvious remedy, cutting prices until the hall fills, turns out to be a trap that several venues have walked into and few have walked out of gracefully. A house sold cheaply is not merely a house sold at less profit; it is an education in what the ticket is worth. Regulars who have twice bought a twelve-pound seat that was advertised at thirty-five learn, quite rationally, to wait. The discount migrates from a tool for filling the last hundred seats to the price at which the venue does most of its business, and the finance director discovers that demand has not been created but merely rescheduled, at a lower yield. More interesting are the venues that have concluded that the empty seat is not primarily a pricing problem at all. The Alhambra in Bradford analysed three seasons of data and found that its persistent gaps were concentrated not in expensive seats but in awkward ones: the far ends of rows, the seats behind pillars, the upper side boxes with a restricted view. These were being sold as though they were ordinary seats, and buyers who ended up in them tended not to return for eighteen months. Renaming and repricing that inventory honestly — describing the obstruction, guaranteeing a move if the house was not full — cost the theatre revenue on paper and raised its retention figures within a year. The lesson is unwelcome to anyone hoping for a formula. The empty seat is a symptom, and it can indicate a price set too high, a programme that nobody wants, a building that is unpleasant to sit in, or an audience that has been quietly taught to distrust the printed price. Only the first of these is solved by a sale.",
    questions: [
      { q: "What does the writer mean by describing a theatre seat as perishable?", options: ["Its value disappears the moment the performance begins.", "It deteriorates physically over a season of use.", "It must be sold before the production is announced.", "Its price falls steadily as the evening approaches."], answer: 0, explanation: "'An unsold seat, unlike unsold bread, cannot be discounted tomorrow; the moment the curtain rises it becomes worthless.'" },
      { q: "Why does the writer describe heavy discounting as 'a trap'?", options: ["It attracts audiences who behave badly in the auditorium.", "It teaches regular customers to postpone their purchases.", "It makes accurate forecasting of demand impossible.", "It obliges venues to programme more popular work."], answer: 1, explanation: "Regulars 'learn, quite rationally, to wait', so the discount becomes the normal price." },
      { q: "What did the finance director in the example discover?", options: ["That new audiences did not return a second time.", "That cheaper seats were more expensive to service.", "That the same demand had simply been shifted, at lower yield.", "That competitors had copied the discounting strategy."], answer: 2, explanation: "'Demand has not been created but merely rescheduled, at a lower yield.'" },
      { q: "What was distinctive about the Alhambra's unsold seats?", options: ["They were mostly in the highest price bands.", "They were bought only by first-time visitors.", "They were concentrated in a single part of the season.", "They were seats with some physical drawback."], answer: 3, explanation: "The gaps were 'concentrated not in expensive seats but in awkward ones' — ends of rows, behind pillars, restricted view." },
      { q: "What was the outcome of the Alhambra's response?", options: ["A short-term financial loss but better customer retention.", "An immediate increase in both revenue and attendance.", "A reduction in the number of seats offered for sale.", "A rise in complaints from long-standing subscribers."], answer: 0, explanation: "Honest repricing 'cost the theatre revenue on paper and raised its retention figures within a year'." },
      { q: "What is the writer's main conclusion?", options: ["Venues should abandon discounting altogether.", "Empty seats have several causes, only one of which pricing can cure.", "Data analysis should replace artistic judgement in programming.", "Audiences are more price-sensitive than venues assume."], answer: 1, explanation: "The empty seat 'is a symptom' with several possible causes, and 'only the first of these is solved by a sale'." }
    ]
  },
  {
    id: "cae-rmc7-02",
    title: "Learning to Trust the Machine",
    text: "The instruments in front of a modern flight deck crew are, by almost any measure, better at flying an aeroplane than the humans sitting behind them. Automation holds a heading more precisely, manages fuel more efficiently, and does not become tired at four in the morning over the Atlantic. It has also, over four decades, made commercial aviation extraordinarily safe. What it has not done is remove the pilot from the problem; it has changed the nature of the problem, and the change is less comfortable than the safety statistics suggest. The difficulty is that automation redistributes attention rather than reducing the demand for it. A crew flying manually is continuously engaged in a task that provides its own feedback: the aircraft is doing what your hands are asking of it, or it is not, and you know within seconds. A crew monitoring an automated system is engaged in something psychologically quite different — the sustained observation of a process that is almost always working correctly. Human beings are poor at this. Vigilance decays measurably after twenty minutes of watching a reliable system, and the very reliability that makes the system worth installing is what erodes the watchfulness it requires. Investigators have a name for the failure mode that results: automation surprise, the moment when the aircraft does something the crew did not expect because it is following a logic they had lost track of. Training has moved a long way in response, though not in the direction the public might imagine. The instinctive remedy — more hand-flying practice — turns out to be only part of the answer, because most incidents are not caused by an inability to fly. They are caused by a mismatch between what the system is doing and what the crew believes it is doing. Modern simulator sessions therefore spend considerable time on scenarios in which nothing dramatic happens at all: the aircraft quietly enters a mode the crew did not select, and the exercise is whether anyone notices, and how long it takes them to say so aloud. The most useful phrase in the modern cockpit, one training captain told me, is not a technical one. It is 'what is it doing now?' — an admission of incomprehension that older cockpit cultures made it professionally awkward to voice, and which contemporary training deliberately rehearses until it becomes ordinary.",
    questions: [
      { q: "What does the writer say automation has failed to do?", options: ["Improve overall aviation safety.", "Match human precision in routine handling.", "Take the human being out of the difficulty.", "Reduce the cost of long-haul operations."], answer: 2, explanation: "'What it has not done is remove the pilot from the problem; it has changed the nature of the problem.'" },
      { q: "How does manual flying differ psychologically from monitoring?", options: ["It supplies immediate feedback on one's own actions.", "It requires far less continuous concentration.", "It is more tiring but easier to train for.", "It relies on memory rather than perception."], answer: 0, explanation: "Flying manually gives 'a task that provides its own feedback… you know within seconds'." },
      { q: "What paradox does the writer identify in reliable systems?", options: ["They are hardest to operate when working normally.", "Their reliability undermines the attention they still need.", "They fail most often when least expected.", "They become less reliable the longer they are used."], answer: 1, explanation: "'The very reliability that makes the system worth installing is what erodes the watchfulness it requires.'" },
      { q: "What is 'automation surprise'?", options: ["A sudden mechanical failure of the autopilot.", "An unexpected instruction from air traffic control.", "A crew's inability to fly the aircraft by hand.", "The aircraft following a logic the crew has lost track of."], answer: 3, explanation: "It is 'the moment when the aircraft does something the crew did not expect because it is following a logic they had lost track of'." },
      { q: "Why is more hand-flying practice an incomplete remedy?", options: ["Simulator time is too expensive to expand.", "Most incidents stem from misunderstanding, not poor handling.", "Manual skills decay too quickly to be worth training.", "Regulators do not permit manual flight in most airspace."], answer: 1, explanation: "'Most incidents are not caused by an inability to fly' but by 'a mismatch between what the system is doing and what the crew believes it is doing'." },
      { q: "Why does the training captain value the phrase 'what is it doing now?'", options: ["It normalises admitting that one does not understand.", "It is the fastest way to alert air traffic control.", "It prompts an immediate return to manual control.", "It is the standard wording required by regulators."], answer: 0, explanation: "It is 'an admission of incomprehension' that training now 'deliberately rehearses until it becomes ordinary'." }
    ]
  },
  {
    id: "cae-rmc7-03",
    title: "The Second Life of the Office Block",
    text: "Converting an obsolete office building into flats sounds like the tidiest of solutions to two problems at once: cities have too little housing and, since the working week fractured, rather too much second-rate office space. The arithmetic is seductive. The structure exists, the foundations are paid for, and the embodied carbon in all that concrete has already been spent, so reusing it avoids the substantial emissions of demolition and rebuilding. Planning authorities across Europe have accordingly relaxed the rules, and the results have been mixed in ways that are worth examining before the model is adopted wholesale. The first constraint is geometry. Offices are built deep, because a large open floor plate is efficient for desks and because artificial light and mechanical ventilation made distance from a window irrelevant. Homes are the opposite: people require daylight, and most regulations require habitable rooms to have windows. A floor plate twenty metres deep therefore yields either a ring of adequate flats around a dead core, which must be filled with corridors, lifts and storage, or, where developers are permitted to cut corners, a set of dwellings in which bedrooms face inwards into permanent gloom. The second constraint is servicing. Office buildings concentrate their plumbing in a few communal cores; dwellings need water and waste at dozens of separate points, which means threading pipework through floor slabs that were never designed to be drilled. Acoustic separation raises the same difficulty: an open floor absorbs the murmur of a hundred people typing, but not the specific, identifiable sound of a neighbour's television at midnight. Where conversion has succeeded, it has generally been on buildings whose original design happened to suit domestic use — narrower floor plates, generous windows, structural bays that align conveniently with a plausible room size. That is not an argument against conversion; it is an argument against treating it as a policy that can be applied by category. The buildings that are easiest to convert are, unsurprisingly, the ones most likely to have found another commercial tenant. The genuinely redundant stock is often redundant precisely because of the characteristics that make it hard to live in, and the question that ought to precede any relaxation of the rules is not whether conversion is possible, but whether the resulting homes are ones anybody would choose if they had a choice.",
    questions: [
      { q: "What makes office-to-housing conversion appear attractive?", options: ["It solves a housing shortage while avoiding demolition emissions.", "It is quicker to obtain planning permission than for new build.", "Office buildings are usually in the cheapest locations.", "Converted flats command higher rents than new ones."], answer: 0, explanation: "The structure exists, and reusing it 'avoids the substantial emissions of demolition and rebuilding'." },
      { q: "Why are office floor plates typically deep?", options: ["To reduce the cost of external walls.", "To satisfy older fire regulations.", "Because artificial light and ventilation made window distance irrelevant.", "Because deeper buildings are more stable structurally."], answer: 2, explanation: "'Artificial light and mechanical ventilation made distance from a window irrelevant.'" },
      { q: "What outcome does the writer describe where developers cut corners?", options: ["Flats too small to meet minimum space standards.", "Bedrooms facing inwards with no natural light.", "Buildings left with unusable upper floors.", "Corridors shared between too many dwellings."], answer: 1, explanation: "The alternative to a dead core is 'dwellings in which bedrooms face inwards into permanent gloom'." },
      { q: "Why is servicing a problem in conversions?", options: ["Existing pipework is usually beyond repair.", "Water pressure is inadequate above certain heights.", "Homes need supplies at many points, not a few cores.", "Communal boilers cannot be metered per flat."], answer: 2, explanation: "'Dwellings need water and waste at dozens of separate points', unlike offices with a few communal cores." },
      { q: "What does the writer note about sound in converted buildings?", options: ["Open floors were designed with acoustic separation in mind.", "Noise complaints are rarer than in purpose-built flats.", "Concrete floors transmit less sound than timber ones.", "General background noise differs from identifiable neighbour noise."], answer: 3, explanation: "An open floor absorbs 'the murmur of a hundred people typing, but not… a neighbour's television at midnight'." },
      { q: "What is the central irony the writer identifies?", options: ["The most convertible buildings are those least likely to be empty.", "Conversions cost more than demolition and rebuilding.", "Relaxed rules have reduced the number of conversions.", "Tenants prefer older offices to newly built flats."], answer: 0, explanation: "'The buildings that are easiest to convert are… the ones most likely to have found another commercial tenant', while genuinely redundant stock is hard to live in." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = window.READING.mc.concat(BANK);
})();
