/* CAE Prep bank: Reading multiple choice (C1) — wave 21 */
(function () {
var BANK = [
  {
    id: "cae-rmc21-01",
    title: "The Comparison That Was Never Made",
    text: "An intervention is introduced, an outcome improves, and the improvement is attributed to the intervention. This inference is made constantly, by competent people, in circumstances where it is not available, and the reason it is so persistent is that the alternative explanations are invisible while the intervention is not.\nThe first alternative is that the outcome would have improved anyway. Many measures move over time for reasons unconnected to any programme, and an intervention introduced during a period of improvement will appear to have caused it. This is not a subtle error and it survives because the counterfactual, by definition, produces no evidence of itself.\nThe second is selection. Where participation is voluntary, those who participate differ from those who do not in ways that predict the outcome independently, and the difference is almost always in the favourable direction. A programme that helps nobody will show a positive result if the people who join it were already improving faster.\nThe third is regression. Interventions are typically introduced when a measure is unusually bad, and unusually bad measures tend to be followed by less unusual ones regardless of what is done. This produces a reliable pattern in which anything introduced at a crisis appears to work, and a corresponding pattern in which the intervention is abandoned when the measure returns to its ordinary level and appears to stop working.\nThe methodological answer is a comparison group, and the objections to constructing one are practical and ethical rather than technical. It is genuinely difficult to withhold something believed to be beneficial, and it is worth stating clearly that the belief is precisely what is in question: an intervention that has not been compared is not known to be beneficial, and withholding it is not withholding a benefit but declining to assume one.\nWhere randomisation is impossible, weaker designs exist and are systematically underused: staggered introduction across sites, comparison with a similar area, or measurement of the trend for long enough beforehand to establish what would have happened. All require a decision before the programme starts, which is the moment at which nobody involved wants to discuss the possibility that it will not work.",
    questions: [
      { q: "Why is the mistaken inference so persistent?", options: ["Alternative explanations are invisible","Data are unavailable","Statistics are difficult","People are careless"], answer: 0, explanation: "'the alternative explanations are invisible while the intervention is not'." },
      { q: "What is the first alternative explanation?", options: ["The measure was wrong", "The outcome would have improved anyway", "Staff worked harder", "Reporting changed"], answer: 1, explanation: "'The first alternative is that the outcome would have improved anyway.'" },
      { q: "Why does voluntary participation cause problems?", options: ["Participants drop out","Participants are less motivated","Participants differ in ways that predict outcomes","Numbers are too small"], answer: 2, explanation: "'those who participate differ from those who do not in ways that predict the outcome'." },
      { q: "What is the effect of regression?", options: ["Measures become more extreme","Results become unpredictable","Programmes last longer","Interventions introduced at a crisis appear to work"], answer: 3, explanation: "'anything introduced at a crisis appears to work'." },
      { q: "How does the writer answer the ethical objection?", options: ["Benefit is assumed, not established", "Ethics committees are too strict", "Randomisation is always ethical", "Participants can consent"], answer: 0, explanation: "'an intervention that has not been compared is not known to be beneficial'." },
      { q: "What do weaker designs require?", options: ["More funding", "A decision before the programme starts", "Larger samples", "Independent researchers"], answer: 1, explanation: "'All require a decision before the programme starts'." }
    ]
  },
  {
    id: "cae-rmc21-02",
    title: "The Market With No Rules",
    text: "The trade in second-hand goods between private individuals is now conducted at a scale that would once have required an industry, and it operates almost entirely outside the framework of consumer protection that governs the sale of the same objects when new.\nThe legal position is generally understood in outline and misunderstood in detail. A sale between private individuals carries obligations that are considerably weaker than those in a commercial sale: the goods must be as described, and there is no requirement that they be of satisfactory quality or fit for purpose. A buyer who discovers a defect that was not concealed has, in most jurisdictions, no remedy at all.\nThis is defensible. A private seller is not a business, cannot inspect goods professionally and would be unable to trade at all under commercial obligations. The difficulty is that the boundary between private and commercial has become genuinely unclear. A person selling four hundred items a year through an online platform is, on any economic description, trading, and the tests used to determine the status are applied inconsistently and only where somebody complains.\nThe platform occupies a position that is legally comfortable and practically decisive. It sets the rules of the transaction, holds the payment, adjudicates disputes and takes a percentage, while maintaining that it is not a party to the sale. The consequence is a system of private regulation that is faster and cheaper than the legal one and that is accountable to nobody: a seller removed from a platform has lost their market and has no appeal beyond the platform's own process.\nThe reform proposals divide predictably. One approach extends consumer obligations to high-volume private sellers, which is enforceable in principle and difficult in practice. The other imposes obligations on the platform, which is administratively simpler and is resisted on the grounds that the platform is an intermediary. That resistance is weakened considerably by the fact that the platform already performs every function of a regulator except accepting responsibility for the outcome.",
    questions: [
      { q: "How do private-sale obligations compare with commercial ones?", options: ["They vary by product","They are identical","They are considerably weaker","They are stronger"], answer: 2, explanation: "'obligations that are considerably weaker than those in a commercial sale'." },
      { q: "What must a private seller ensure?", options: ["A refund period","Satisfactory quality","Fitness for purpose","That goods are as described"], answer: 3, explanation: "'the goods must be as described'." },
      { q: "Why is the weaker standard defensible?", options: ["A private seller cannot inspect goods professionally","Sales are infrequent","Platforms compensate buyers","Buyers pay less"], answer: 0, explanation: "'A private seller is not a business, cannot inspect goods professionally'." },
      { q: "What has become unclear?", options: ["The value of goods", "The boundary between private and commercial", "The identity of buyers", "The legal jurisdiction"], answer: 1, explanation: "'the boundary between private and commercial has become genuinely unclear'." },
      { q: "How does the writer describe the platform's position?", options: ["Entirely neutral","Strictly regulated","Legally comfortable and practically decisive","Legally exposed"], answer: 2, explanation: "'The platform occupies a position that is legally comfortable and practically decisive.'" },
      { q: "Why is the platform's resistance weakened?", options: ["Sellers have organised","Volumes are small","Courts have ruled against it","It already performs regulatory functions"], answer: 3, explanation: "'the platform already performs every function of a regulator except accepting responsibility'." }
    ]
  },
  {
    id: "cae-rmc21-03",
    title: "What Rehearsal Is Actually For",
    text: "Rehearsal is commonly described as the process of learning material until it can be performed reliably, which is one of its functions and not the principal one. Performers describe something else: rehearsal is where the decisions are made, and the material is the medium in which they are made rather than the object of the exercise.\nThe distinction becomes visible when rehearsal goes wrong. A group that has rehearsed only for accuracy performs correctly and inflexibly: when something unexpected occurs, as it does in a substantial proportion of performances, there is no shared basis for responding, because nobody has established what the performance is about beyond the sequence of actions.\nThe research on expert performance supports this in a specific way. Practice that consists of repetition produces improvement up to a plateau and then very little; practice that consists of attempting things at the edge of current capability, with immediate feedback, continues to produce improvement for as long as it is sustained. The second kind is more uncomfortable, which is why groups left to themselves generally do the first.\nThere is also a social function that professionals discuss more readily than they write about. Rehearsal is where a group establishes how it handles error. A room in which a mistake produces a small correction and no comment is one in which people will attempt difficult things; a room in which a mistake produces a pause and an explanation is one in which everybody plays safely, and the difference in the eventual performance is considerable and is established in the first two sessions.\nThe most efficient rehearsals, according to those who run them, spend a surprisingly small proportion of their time on the difficult passages and a large proportion on transitions, entrances and the joins between sections. These are the points at which performances actually fail, they are not what anybody worries about, and they receive attention only from directors who have been paying attention to what goes wrong rather than to what is hard.",
    questions: [
      { q: "What do performers say rehearsal is principally for?", options: ["Making decisions","Building stamina","Impressing directors","Learning material reliably"], answer: 0, explanation: "'rehearsal is where the decisions are made'." },
      { q: "What happens to a group rehearsed only for accuracy?", options: ["It performs flexibly", "It cannot respond to the unexpected", "It performs faster", "It makes more errors"], answer: 1, explanation: "'there is no shared basis for responding'." },
      { q: "What kind of practice continues to produce improvement?", options: ["Solo practice","Repetition","Work at the edge of capability with feedback","Longer sessions"], answer: 2, explanation: "'attempting things at the edge of current capability, with immediate feedback'." },
      { q: "Why do groups default to repetition?", options: ["It is traditional","Directors prefer it","It is quicker","The alternative is uncomfortable"], answer: 3, explanation: "'The second kind is more uncomfortable'." },
      { q: "What social function does rehearsal perform?", options: ["Establishing how error is handled", "Allocating roles", "Setting schedules", "Building friendships"], answer: 0, explanation: "'Rehearsal is where a group establishes how it handles error.'" },
      { q: "Where do efficient rehearsals spend most time?", options: ["On the hardest passages", "On transitions and joins", "On warming up", "On discussion"], answer: 1, explanation: "'a large proportion on transitions, entrances and the joins between sections'." }
    ]
  },
  {
    id: "cae-rmc21-04",
    title: "Why Good Advice Is Ignored",
    text: "A great deal of effort is spent producing advice that is accurate, well evidenced and not followed, and the usual explanation, that the recipient is irrational or insufficiently informed, is both unflattering and generally wrong.\nThe first reason advice fails is that it is addressed to a decision the recipient is not making. Guidance on how to eat well assumes a decision about food that many households do not make in the sense assumed: what is eaten is determined by time, budget, storage, the preferences of other people and what is available within a certain distance, and an instruction that ignores those constraints is not advice but a description of a different life.\nThe second is that the cost of following advice is borne immediately and the benefit arrives later and probabilistically. This is not a failure of reasoning; it is a correct perception of an asymmetry, and it is felt most acutely by people whose immediate circumstances are difficult, which is to say by exactly the people at whom most public advice is directed.\nThe third is source. Advice is evaluated partly on the credibility of whoever gives it, which is rational, and credibility is not a property of the evidence but of the relationship. Identical information produces different rates of adoption depending on whether it arrives from a national body, a professional the person knows, or somebody in the same situation who has done the thing, and the ordering is consistent enough to be designed around, though it rarely is.\nThe fourth and least comfortable is that advice frequently contains an implicit judgement about the recipient's previous behaviour. Anybody being told what to do is also being told, silently, that what they have been doing is wrong, and where the previous behaviour was a reasonable adaptation to circumstances the advice-giver has not understood, the judgement is both wrong and detectable.\nWhat follows is that advice which works is generally advice that has been designed with the constraints in view, delivered by somebody with standing, and framed as an addition rather than a correction. This is more expensive than publishing a leaflet, which is the principal reason leaflets continue to be published.",
    questions: [
      { q: "What does the writer say about the usual explanation?", options: ["It has never been tested","It is accurate but harsh","It is unflattering and generally wrong","It applies only to some groups"], answer: 2, explanation: "'is both unflattering and generally wrong'." },
      { q: "What is the first reason advice fails?", options: ["It is poorly written","It arrives too late","It is too complicated","It addresses a decision the recipient is not making"], answer: 3, explanation: "'it is addressed to a decision the recipient is not making'." },
      { q: "Why is the cost-benefit asymmetry not irrational?", options: ["It reflects a correct perception", "Benefits never arrive", "Costs are exaggerated", "Advice is usually wrong"], answer: 0, explanation: "'it is a correct perception of an asymmetry'." },
      { q: "What determines credibility?", options: ["The quality of evidence", "The relationship with the source", "The length of the message", "Official endorsement"], answer: 1, explanation: "'credibility is not a property of the evidence but of the relationship'." },
      { q: "What implicit message does advice often carry?", options: ["That change is easy","That the recipient is well informed","That previous behaviour was wrong","That the adviser is uncertain"], answer: 2, explanation: "'is also being told, silently, that what they have been doing is wrong'." },
      { q: "Why do leaflets continue to be published?", options: ["They are legally required","They are popular","They are effective","Better approaches are more expensive"], answer: 3, explanation: "'This is more expensive than publishing a leaflet, which is the principal reason leaflets continue to be published.'" }
    ]
  },
  {
    id: "cae-rmc21-05",
    title: "The Landscape That Was Designed",
    text: "A visitor to certain celebrated landscapes is looking at a construction: hills reshaped, watercourses diverted, entire villages removed and rebuilt out of sight, and planting arranged over decades to produce an effect of unimprovable naturalness. The achievement is that almost nobody sees it, which was the intention, and which creates a difficulty for the people now responsible for maintaining it.\nThe first difficulty is that a designed landscape has a life cycle. A planting scheme conceived to mature over eighty years is now, in many cases, two hundred years old, which is well past the intended condition. Trees planted to be seen at forty metres apart have grown into each other; views deliberately framed have closed; and a landscape that appears to be in an ideal state of maturity is frequently in a state its designer would have regarded as failure.\nThis produces an awkward conservation question. Restoring the intended appearance requires felling mature trees, which is the single most reliable way of causing public objection, and the objection is not unreasonable: a tree that is two hundred years old has a value the designer did not anticipate and that the design cannot accommodate.\nThe second difficulty concerns what is being conserved. A landscape is not a building and cannot be held at a moment; every year it is either developing or being actively prevented from developing, and the choice of which condition to maintain is a judgement about which of several past states matters most. Different professions answer differently, and the ecological answer, that the current condition supports species the designed condition would not, is frequently the strongest and least likely to be adopted.\nWhat has changed in recent practice is the acceptance that these are choices rather than technical questions with correct answers. The better managed sites now publish what they are conserving and why, which does not resolve the disagreement and does make it possible to have it, which is more than the previous arrangement of quietly making decisions and being surprised by the reaction ever offered.",
    questions: [
      { q: "What is the achievement of such landscapes?", options: ["That almost nobody sees the construction","Their cost","Their durability","Their scale"], answer: 0, explanation: "'The achievement is that almost nobody sees it, which was the intention'." },
      { q: "What is the first difficulty?", options: ["Lack of records", "A designed landscape has a life cycle", "Public access", "Climate change"], answer: 1, explanation: "'a designed landscape has a life cycle'." },
      { q: "What condition are many such landscapes now in?", options: ["Too young to judge","Their intended condition","A state the designer would call failure","Better than intended"], answer: 2, explanation: "'in a state its designer would have regarded as failure'." },
      { q: "Why is restoring the intended appearance difficult?", options: ["Records are missing","It is illegal","It costs too much","It requires felling mature trees"], answer: 3, explanation: "'Restoring the intended appearance requires felling mature trees'." },
      { q: "Which answer does the writer call strongest and least likely to be adopted?", options: ["The ecological one","The historical one","The commercial one","The architectural one"], answer: 0, explanation: "'the ecological answer... is frequently the strongest and least likely to be adopted'." },
      { q: "What has changed in recent practice?", options: ["Decisions are made faster", "Choices are published and acknowledged as choices", "Sites have closed", "Funding has increased"], answer: 1, explanation: "'The better managed sites now publish what they are conserving and why'." }
    ]
  },
  {
    id: "cae-rmc21-06",
    title: "The Rules Nobody Can Follow",
    text: "Security policies in most organisations are written to be defensible rather than to be followed, and the distinction produces a predictable outcome: a set of requirements that no competent employee can comply with while doing their job, and a workforce that has developed an entire informal system for getting work done anyway.\nThe pattern is documented in detail. Password policies requiring frequent change produce weaker passwords, because human memory imposes a constraint that policy cannot override, and the predictable result is a family of related passwords differing by a digit. Restrictions on file transfer produce the use of personal accounts. Requirements to obtain approval for routine actions produce, within about a year, a shared understanding of which approvals are theatrical and can be obtained retrospectively.\nThe significant point is not that employees break rules. It is that the informal system is where the actual security posture of the organisation is located, and it is invisible to anybody reading the policy. An organisation whose policy is strict and whose practice is a set of workarounds is less secure than one whose policy is realistic and followed, because in the second case somebody knows what is happening.\nThe research recommendation is consistent and rarely implemented: policies should be designed with the people who will have to comply, tested for whether compliance is possible while performing the job, and revised where it is not. This requires an admission that a security requirement can be wrong, which is difficult in a function whose authority rests on the seriousness of the risks it manages.\nThere is also a measurement problem that sustains the situation. Compliance with a policy can be audited; the existence of a workaround cannot, because the people who know about it have every reason not to mention it to an auditor. An organisation therefore receives regular confirmation that its rules are being followed from a process that is structurally incapable of discovering otherwise, and the first accurate information usually arrives with an incident.",
    questions: [
      { q: "How are security policies usually written?", options: ["To satisfy employees","To be followed","To be defensible","To be brief"], answer: 2, explanation: "'written to be defensible rather than to be followed'." },
      { q: "What do frequent password changes produce?", options: ["Fewer breaches","Better training","Stronger passwords","Weaker, related passwords"], answer: 3, explanation: "'produce weaker passwords'." },
      { q: "Where is the actual security posture located?", options: ["In the informal system","In the audit report","In the training material","In the written policy"], answer: 0, explanation: "'the informal system is where the actual security posture of the organisation is located'." },
      { q: "Why is a realistic followed policy safer?", options: ["It is cheaper", "Somebody knows what is happening", "It requires less training", "It satisfies regulators"], answer: 1, explanation: "'because in the second case somebody knows what is happening'." },
      { q: "What does the recommended approach require?", options: ["Stricter enforcement","More resources","Admitting a security requirement can be wrong","External consultants"], answer: 2, explanation: "'This requires an admission that a security requirement can be wrong'." },
      { q: "Why does auditing sustain the problem?", options: ["Audits are infrequent","Policies change too often","Auditors are unqualified","Workarounds cannot be discovered by audit"], answer: 3, explanation: "'the existence of a workaround cannot, because the people who know about it have every reason not to mention it'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
