/* CAE Prep bank: Reading multiple choice (C1) — wave 22 */
(function () {
var BANK = [
  {
    id: "cae-rmc22-01",
    title: "How Long a Skill Lasts",
    text: "The phrase half-life of a skill has entered workforce planning, and it is used with a precision the underlying evidence does not support. The general claim, that skills become obsolete faster than they used to, is plausible and is applied indiscriminately to categories of ability that behave very differently.\nThe distinction that matters is between skills tied to a particular implementation and skills that describe an underlying capability. Knowing how to operate a specific system is tied to that system and expires with it. Knowing how to model a problem, read a specification, or determine what a user actually needs does not expire, and practitioners who possess it acquire each new implementation in a fraction of the time required by somebody learning it from nothing.\nThis has an unfortunate implication for training policy. The skills that are easy to specify, teach and certify are precisely the perishable ones, and the durable capabilities are difficult to define, slow to develop and almost impossible to examine in a way an employer will accept. Training systems therefore concentrate on the category that will be worthless in six years, and they do so for reasons that are administrative rather than educational.\nThe evidence on retraining supports a similar reading. Programmes that succeed in moving people between sectors are generally long, expensive and built around a period of supervised practice; those that consist of short courses in a currently fashionable technology produce certificates and very limited employment effects. The second kind persists because it can be delivered at scale, counted and reported within a financial year.\nWhat is genuinely new is not the rate of obsolescence but the fragmentation of the career in which learning used to be embedded. A person who spent thirty years in one organisation acquired durable capability by exposure, without any of it appearing in a training budget. Where tenure is short, that mechanism does not operate, and the response has been to attempt to replace it with courses, which is the substitution of the specifiable for the valuable and is failing in a way that everybody involved can see and few are able to say.",
    questions: [
      { q: "What does the writer say about the phrase half-life of a skill?", options: ["It is used more precisely than the evidence allows","It is new","It applies only to technology","It is well supported"], answer: 0, explanation: "'it is used with a precision the underlying evidence does not support'." },
      { q: "Which skills expire?", options: ["Those requiring certification","Those tied to a particular implementation","Those describing underlying capability","Those learned young"], answer: 1, explanation: "'Knowing how to operate a specific system is tied to that system and expires with it.'" },
      { q: "Why do training systems focus on perishable skills?", options: ["They are more useful","Employers demand it","They are easy to specify and certify","They are cheaper to teach"], answer: 2, explanation: "'The skills that are easy to specify, teach and certify are precisely the perishable ones'." },
      { q: "What characterises successful retraining programmes?", options: ["Online delivery","Employer sponsorship","Short fashionable courses","Length, expense and supervised practice"], answer: 3, explanation: "'generally long, expensive and built around a period of supervised practice'." },
      { q: "Why do short courses persist?", options: ["They can be counted and reported within a year","Students prefer them","They are internationally recognised","They work well"], answer: 0, explanation: "'it can be delivered at scale, counted and reported within a financial year'." },
      { q: "What does the writer say is genuinely new?", options: ["The rate of obsolescence", "The fragmentation of careers", "The cost of training", "The number of skills required"], answer: 1, explanation: "'not the rate of obsolescence but the fragmentation of the career'." }
    ]
  },
  {
    id: "cae-rmc22-02",
    title: "What a Signature Was Doing",
    text: "The handwritten signature performed several functions at once, and the arrangements that have replaced it perform some of them well and others not at all, which explains most of the confusion in current practice.\nThe first function was identification, and it was always the weakest. A signature is difficult to verify, easy to forge and rarely compared against anything, and the security it provided was largely a matter of belief. Cryptographic signatures perform this function incomparably better, and the difference is not marginal.\nThe second was evidence of intention. A person who signs has performed a deliberate act at a particular moment, and the physical difficulty of the act is part of what it signifies: a signature is not something one does absent-mindedly. A checkbox is, and the substitution has removed a distinction that legal systems continue to rely on without any mechanism for detecting it.\nThe third and least discussed function was ceremonial. Signing occurred at a moment, in a place, frequently in the presence of somebody, and the arrangement created an occasion which marked the transaction as consequential. The evidence from behavioural research suggests that this is not empty formality: the point at which attestation occurs affects how carefully people report, and moving it to the beginning of a form rather than the end measurably improves the accuracy of what is written.\nCurrent electronic arrangements have inherited the vocabulary of the signature without inheriting these distinctions. A system that records a click, a system that captures a scrawl on a screen and a system that applies a certified cryptographic key are all described as signatures, and they differ enormously in what they establish. The scrawl on the screen is the worst of the three: it provides no cryptographic assurance and no evidence of deliberation, while resembling the thing it has replaced closely enough that nobody asks what it is doing.\nThe reasonable position is to describe what is required rather than to ask for a signature: an assurance about identity, a record of deliberate assent, or both. Where organisations do this, the appropriate mechanism becomes obvious. Where they ask for a signature, they receive something that looks like one.",
    questions: [
      { q: "Which signature function was always weakest?", options: ["Ceremony","Record-keeping","Identification","Evidence of intention"], answer: 2, explanation: "'The first function was identification, and it was always the weakest.'" },
      { q: "What does the physical difficulty of signing signify?", options: ["The signer's identity","The document's importance","Legal authority","That the act was deliberate"], answer: 3, explanation: "'a signature is not something one does absent-mindedly'." },
      { q: "What does behavioural research show about attestation?", options: ["Its position affects accuracy of reporting", "It has no measurable effect", "It slows completion", "It reduces fraud detection"], answer: 0, explanation: "'the point at which attestation occurs affects how carefully people report'." },
      { q: "Why is the on-screen scrawl the worst option?", options: ["It is hardest to produce", "It provides neither assurance nor evidence of deliberation", "It is illegal", "It cannot be stored"], answer: 1, explanation: "'it provides no cryptographic assurance and no evidence of deliberation'." },
      { q: "What problem does inherited vocabulary create?", options: ["Costs have risen","Systems are incompatible","Different mechanisms are all called signatures","Signatures are no longer accepted"], answer: 2, explanation: "'are all described as signatures, and they differ enormously in what they establish'." },
      { q: "What does the writer recommend?", options: ["Standardising electronic signatures","Abolishing the requirement","Returning to handwritten signatures","Describing what is required instead of asking for a signature"], answer: 3, explanation: "'to describe what is required rather than to ask for a signature'." }
    ]
  },
  {
    id: "cae-rmc22-03",
    title: "Nobody Reads the Terms",
    text: "Studies of consent to standard terms produce a consistent figure: the proportion of users who open the document is small, the proportion who read it is negligible, and the time spent by those who do is insufficient to have read it. This is generally reported as evidence of user carelessness, which is a peculiar interpretation of a behaviour that is entirely rational.\nThe calculation is straightforward. Reading the terms of the services an average person uses would take a substantial number of working days a year. The terms are non-negotiable. Declining them means not using the service, which is frequently not a practical option. A person who reads carefully and a person who does not arrive at the same outcome, having spent different amounts of time, and the difference in outcome is zero.\nThe legal fiction that a person who clicks has agreed to the terms is therefore doing considerable work, and courts have been aware of this for some time. The developing response has been to distinguish between terms a reasonable person would expect and terms that are unusual or onerous, with the latter requiring specific prominence to be enforceable. This is sensible and it places the assessment where it belongs, on the party that drafted the document.\nThe more effective interventions have not been legal at all. Requiring a short summary in prescribed form, at the point of decision, changes behaviour measurably. Prohibiting particular terms outright removes the question. And, most effectively, requiring that the default setting be the privacy-protective one shifts the outcome for the large majority who change nothing, which is the only intervention that reaches the people least likely to engage.\nWhat should be abandoned is the pretence that the problem is comprehension. Making the documents clearer improves the experience of the small minority who read them and does almost nothing to the aggregate outcome, and a policy that concentrates on clarity is choosing an intervention that is inexpensive, uncontroversial and known to be ineffective.",
    questions: [
      { q: "How does the writer characterise the usual interpretation?", options: ["As peculiar, since the behaviour is rational","As too generous to users","As legally required","As accurate"], answer: 0, explanation: "'which is a peculiar interpretation of a behaviour that is entirely rational'." },
      { q: "Why is reading terms pointless for most users?", options: ["The documents are inaccurate", "The terms are non-negotiable and declining is impractical", "They are too short", "They change frequently"], answer: 1, explanation: "'The terms are non-negotiable.'" },
      { q: "How have courts responded?", options: ["By requiring signatures","By ignoring the issue","By distinguishing expected from unusual or onerous terms","By banning standard terms"], answer: 2, explanation: "'to distinguish between terms a reasonable person would expect and terms that are unusual or onerous'." },
      { q: "Which intervention reaches those least likely to engage?", options: ["Longer decision times","Clearer language","Short summaries","Privacy-protective defaults"], answer: 3, explanation: "'requiring that the default setting be the privacy-protective one'." },
      { q: "What does the writer say about improving clarity?", options: ["It helps a small minority and changes little","It is impossible","It is legally required","It solves the problem"], answer: 0, explanation: "'improves the experience of the small minority who read them and does almost nothing to the aggregate outcome'." },
      { q: "Why is a clarity-focused policy attractive?", options: ["It is effective", "It is inexpensive and uncontroversial", "It is demanded by users", "It satisfies courts"], answer: 1, explanation: "'an intervention that is inexpensive, uncontroversial and known to be ineffective'." }
    ]
  },
  {
    id: "cae-rmc22-04",
    title: "The Price of Agreement",
    text: "Groups that agree quickly are generally regarded as functional, and the assumption is embedded in how meetings are described: a productive discussion is one that reaches a decision. The research on group decision-making suggests that speed of agreement is a poor indicator of quality and occasionally an indicator of its absence.\nThe mechanism is well established. Where a group contains a member with more authority, and where that member expresses a view early, the subsequent discussion is largely a process of accommodation. This occurs without anybody intending it, is invisible to the person whose view was expressed first, and is reported by other participants only in confidential settings.\nThe second mechanism concerns information that only one person holds. Groups discuss shared information disproportionately: an item known to everybody is mentioned early and repeatedly, while an item known to one member is frequently not raised at all, particularly where raising it would complicate an emerging agreement. The result is that groups can reliably fail to use exactly the information they were convened to combine.\nThe procedural remedies are well documented and rarely adopted. The senior person speaks last, which is easy to state and difficult to sustain. Positions are recorded independently before discussion. Somebody is assigned the explicit task of arguing against the emerging view, and the assignment is rotated so that it is a role rather than a reputation.\nThe difficulty with all of these is that they make meetings longer and less pleasant, and the benefit is a set of errors that do not occur, which nobody experiences. An organisation that adopts them will notice the cost immediately and the benefit never, which is the general problem with any procedure that prevents something.\nWhat can be said with confidence is that a group which has never disagreed is not a group whose members all think the same thing. It is a group in which the cost of disagreeing has been assessed by everybody present and found to exceed the benefit, and that assessment is a description of the group's culture rather than of the questions it has considered.",
    questions: [
      { q: "What does the research suggest about quick agreement?", options: ["It reflects expertise","It indicates good decisions","It is a poor indicator of quality","It saves resources"], answer: 2, explanation: "'speed of agreement is a poor indicator of quality'." },
      { q: "What happens when a senior member speaks early?", options: ["Others disagree openly","The meeting ends","Information improves","Discussion becomes accommodation"], answer: 3, explanation: "'the subsequent discussion is largely a process of accommodation'." },
      { q: "Which information do groups under-discuss?", options: ["Information held by one person","Written information","Financial information","Shared information"], answer: 0, explanation: "'an item known to one member is frequently not raised at all'." },
      { q: "Why is the dissent role rotated?", options: ["To share the workload", "So it is a role rather than a reputation", "To train new members", "To satisfy procedure"], answer: 1, explanation: "'the assignment is rotated so that it is a role rather than a reputation'." },
      { q: "Why are these remedies rarely adopted?", options: ["They require training","They are expensive","Costs are felt and benefits are invisible","They are legally restricted"], answer: 2, explanation: "'will notice the cost immediately and the benefit never'." },
      { q: "What does a group that never disagrees indicate?", options: ["Effective leadership","Careful selection","Genuine unanimity","That disagreement has been judged too costly"], answer: 3, explanation: "'the cost of disagreeing has been assessed by everybody present and found to exceed the benefit'." }
    ]
  },
  {
    id: "cae-rmc22-05",
    title: "The Town That Charged for Parking",
    text: "Few municipal decisions produce as reliable a reaction as a change to parking, and the reaction is generally framed as a defence of local business against a council seeking revenue. The evidence on what parking charges actually do is more interesting than either position in that argument.\nThe first finding, repeated in many surveys, is that retailers systematically overestimate the proportion of their customers who arrive by car, frequently by a factor of two or more. The estimate is honest and it is derived from a biased sample: the customers a shopkeeper discusses parking with are the ones who had difficulty parking.\nThe second is that the relationship between charging and turnover is weak, and that the variable which matters is availability rather than price. A street with free parking that is always full delivers fewer customers to its shops than one with charged parking that has spaces, because a driver who cannot park does not shop, and a driver circulating for eleven minutes is producing congestion rather than trade.\nThis is the argument for pricing that most economists make and most councils avoid: setting the charge at the level that leaves roughly one space in seven free, which maximises the number of drivers who successfully park. It is unpopular because it makes the price visible, whereas the cost of circulating is borne by drivers who do not attribute it to the absence of a charge.\nThe third finding concerns where the revenue goes. Charges are far better received where the income is visibly returned to the area in which it was collected, and considerably worse where it disappears into a general fund. This is not a point about accounting: an identical charge produces different levels of objection depending entirely on whether the objector can see what it paid for.\nWhat is rarely discussed is that free parking is not free. It is paid for in land, in the price of goods sold by shops whose rents include the space, and in the alternative uses of the same area, and the fact that no individual driver pays at the point of use makes it invisible rather than absent.",
    questions: [
      { q: "What do retailers systematically overestimate?", options: ["The proportion of customers arriving by car","Parking charges","Local competition","Their turnover"], answer: 0, explanation: "'retailers systematically overestimate the proportion of their customers who arrive by car'." },
      { q: "Why is their estimate biased?", options: ["They count deliveries", "They speak to customers who had parking difficulty", "They rely on surveys", "They exclude regular customers"], answer: 1, explanation: "'the ones who had difficulty parking'." },
      { q: "Which variable matters most?", options: ["Time limits","Price","Availability","Distance"], answer: 2, explanation: "'the variable which matters is availability rather than price'." },
      { q: "What charge level do economists recommend?", options: ["Free at all times","A flat daily rate","The highest the market bears","One that leaves about one space in seven free"], answer: 3, explanation: "'setting the charge at the level that leaves roughly one space in seven free'." },
      { q: "What affects how charges are received?", options: ["Whether revenue visibly returns to the area", "The size of the charge", "Who collects it", "The time of day"], answer: 0, explanation: "'far better received where the income is visibly returned to the area'." },
      { q: "What does the writer say about free parking?", options: ["It benefits everybody", "It is paid for in land and prices", "It increases turnover", "It reduces congestion"], answer: 1, explanation: "'It is paid for in land, in the price of goods sold by shops whose rents include the space'." }
    ]
  },
  {
    id: "cae-rmc22-06",
    title: "Collecting the Present",
    text: "A museum acquiring objects from the current decade faces a problem that does not arise with older material: it must decide what will matter before anybody knows. The alternative, waiting until significance is established, guarantees that the ordinary objects will have been thrown away, since the things that are hardest to acquire later are precisely those that nobody at the time thought worth keeping.\nThe pattern is visible in every existing collection. Museums hold exceptional examples of nineteenth-century clothing and very few ordinary work garments, because the good coat was preserved and the working one was worn until it disintegrated. The same asymmetry is being created now, and the objects that future researchers will want are the ones currently being discarded without comment: packaging, uniforms, signage, the objects of routine work.\nContemporary collecting has therefore developed a distinctive method. Rather than selecting objects believed to be significant, some institutions document a situation comprehensively: everything used by one household in a week, the complete contents of a workplace at closure, the objects associated with a single event including the ephemeral ones. This produces collections that appear indiscriminate and that answer questions nobody had thought to ask.\nThe difficulties are practical. Storage is the binding constraint in almost every museum, and contemporary material is bulky, frequently made of plastics that degrade unpredictably, and arrives without the filtering that time performs. There is also a problem of consent that older collections did not face: objects of recent life are associated with living people, and documenting a workplace requires agreement from those who worked there.\nWhat has changed the practice most is the recognition that collecting is itself an interpretation. A curator who acquires the objects of a strike is documenting a dispute in which they will be understood to have taken a position, and the honest response has been to record the reasoning alongside the acquisition. That documentation will, in a century, be as informative as the objects, and it is the part most likely to be lost, since it is the part that nobody thinks to catalogue.",
    questions: [
      { q: "What problem does contemporary collecting face?", options: ["Objects are too fragile","Objects are too expensive","Significance is not yet known","Owners refuse to sell"], answer: 2, explanation: "'it must decide what will matter before anybody knows'." },
      { q: "Why is waiting a poor strategy?", options: ["Museums lose interest","Records are lost","Prices rise","Ordinary objects will have been discarded"], answer: 3, explanation: "'guarantees that the ordinary objects will have been thrown away'." },
      { q: "What asymmetry exists in older collections?", options: ["Exceptional items preserved, ordinary ones lost","Only foreign objects survive","Objects lack documentation","Too many working garments"], answer: 0, explanation: "'Museums hold exceptional examples of nineteenth-century clothing and very few ordinary work garments'." },
      { q: "What method has developed?", options: ["Selecting only significant objects", "Documenting situations comprehensively", "Buying at auction", "Accepting donations only"], answer: 1, explanation: "'some institutions document a situation comprehensively'." },
      { q: "Which problem is new to recent collections?", options: ["Transport","Storage","Consent from living people","Cataloguing"], answer: 2, explanation: "'There is also a problem of consent that older collections did not face'." },
      { q: "What is most likely to be lost?", options: ["The storage arrangements","Photographs","The objects themselves","The record of the curator's reasoning"], answer: 3, explanation: "'it is the part most likely to be lost, since it is the part that nobody thinks to catalogue'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
