/* CAE Prep bank: Reading multiple choice (C1) — wave 11 */
(function () {
var BANK = [
  {
    id: "cae-rmc11-01",
    title: "The Committee That Could Not Refuse",
    text: "Every organisation of sufficient size contains a body whose remit has expanded until it is incapable of doing any part of its work well. The process is so consistent that it can be described almost mechanically, and it is worth describing because the usual explanations, in terms of empire-building or incompetence, are wrong about the mechanism.\nA committee is established with a defined purpose. A related question arises which nobody else is obviously responsible for, and it is added, reasonably, because the alternative is that it is not considered at all. The addition is small and the argument for it is strong. Repeat this process at intervals of a few months for five years and the body's agenda contains eleven items, four of which require expertise that nobody present possesses, and the meeting has expanded from an hour to three without any decision having been taken to expand it.\nThe crucial feature is that no individual decision in this sequence is unreasonable. Each addition is defended on the grounds that the matter is important and unowned, and both claims are usually true. What is missing is any mechanism by which items leave, and the absence is structural: adding a responsibility requires one decision by people who feel useful, while removing one requires a decision to stop doing something that somebody may later need, taken by the same people, who will be blamed if it turns out to have mattered.\nThe consequences are predictable. Attendance by senior figures declines, since the return on three hours becomes poor; the meeting is increasingly attended by deputies without authority; and decisions migrate to informal conversations before and after, which is where they are actually taken. The formal body persists as a ratifying mechanism, and its papers grow longer as its influence declines.\nThe remedies that work are procedural and slightly brutal. A fixed number of standing items, with the rule that adding one requires removing one. An automatic expiry date on every responsibility, renewable only by explicit decision. A quarterly review whose only question is what should stop. None of this is difficult to design. It is difficult to introduce, because the person proposing it is asking a group of people to agree that a substantial part of what they currently do is not worth the room.",
    questions: [
      { q: "What does the writer say about the usual explanations for committee expansion?", options: ["They misidentify the mechanism","They are deliberately misleading","They apply only to large firms","They are broadly correct"], answer: 0, explanation: "'the usual explanations, in terms of empire-building or incompetence, are wrong about the mechanism'." },
      { q: "How do items get added to a committee's remit?", options: ["Through formal expansion decisions", "Because nobody else is responsible for them", "By senior management instruction", "Through external regulation"], answer: 1, explanation: "'A related question arises which nobody else is obviously responsible for'." },
      { q: "What is the crucial feature of the process?", options: ["Committees resist all change","New members drive expansion","Each individual decision seems reasonable","The decisions are taken secretly"], answer: 2, explanation: "'no individual decision in this sequence is unreasonable'." },
      { q: "Why is it hard to remove responsibilities?", options: ["Nobody remembers why they were added","It requires external approval","Rules forbid it","Those who remove them risk later blame"], answer: 3, explanation: "'who will be blamed if it turns out to have mattered'." },
      { q: "What happens to real decision-making?", options: ["It moves to informal conversations","It passes to external consultants","It becomes faster","It stops entirely"], answer: 0, explanation: "'decisions migrate to informal conversations before and after'." },
      { q: "Why are the remedies difficult to introduce?", options: ["They cost too much", "They require admitting current work is not worthwhile", "They are technically complex", "They need legal approval"], answer: 1, explanation: "'asking a group of people to agree that a substantial part of what they currently do is not worth the room'." }
    ]
  },
  {
    id: "cae-rmc11-02",
    title: "What Becomes of the Data Afterwards",
    text: "A research project generates two products. One is a set of findings, which is published, cited and eventually superseded. The other is the underlying data, which historically disappeared into a departmental filing cabinet and then into a skip, and whose fate has become, in the last fifteen years, a matter of serious institutional concern.\nThe arguments for preservation are strong. Data collected at public expense can answer questions its collectors never asked; several important findings have come from the reanalysis of material gathered decades earlier for unrelated purposes; and the ability to check a published result against its evidence is not a courtesy but a condition of the whole enterprise. A number of funders now require a data management plan as a condition of award, and repositories have been established to hold the results.\nThe practical position is less encouraging than the policy suggests. Studies attempting to obtain data from published papers report success rates that decline sharply with the age of the paper, and the commonest obstacles are neither refusal nor confidentiality but ordinary entropy: the researcher has moved institution, the format cannot be read, the file exists and nobody can now say what the columns mean. Data without documentation is not preserved; it is merely stored, and the distinction becomes apparent about four years later.\nThere is also a question that repositories handle poorly, which is what should not be kept. Preservation is not free, and the costs are recurrent while the funding is not. A discipline that resolves to keep everything will, within a decade, be paying to maintain a great deal of material whose documentation was inadequate when it was deposited and is now unrecoverable, at the expense of curating properly the fraction that is genuinely reusable.\nThe most useful development has been the least discussed: the emergence of the data paper, a publication whose subject is the dataset itself, describing its construction, limitations and appropriate uses. It gives the person who did the tedious work of documentation something citable, which is the only incentive that has ever reliably changed academic behaviour, and it does more for reusability than any amount of policy requiring deposit.",
    questions: [
      { q: "What are the two products of a research project?", options: ["Reports and equipment","Findings and funding","Findings and data","Publications and staff"], answer: 2, explanation: "'One is a set of findings... The other is the underlying data'." },
      { q: "What is one argument for preserving data?", options: ["It speeds up publication","It attracts new funders","It reduces research costs","It can answer questions its collectors never asked"], answer: 3, explanation: "'Data collected at public expense can answer questions its collectors never asked'." },
      { q: "What are the commonest obstacles to obtaining old data?", options: ["Ordinary entropy such as moves and formats","Commercial interests","Refusal and confidentiality","Legal restrictions"], answer: 0, explanation: "'the commonest obstacles are neither refusal nor confidentiality but ordinary entropy'." },
      { q: "What distinction does the writer draw?", options: ["Between funders and institutions","Between storing and preserving","Between public and private data","Between old and new studies"], answer: 1, explanation: "'Data without documentation is not preserved; it is merely stored'." },
      { q: "What problem does keeping everything create?", options: ["Excessive citation","Legal liability","Recurrent costs at the expense of curating reusable material","Loss of researcher control"], answer: 2, explanation: "'at the expense of curating properly the fraction that is genuinely reusable'." },
      { q: "Why does the writer value the data paper?", options: ["It reduces storage costs","It is required by funders","It replaces the original publication","It makes documentation citable"], answer: 3, explanation: "'It gives the person who did the tedious work of documentation something citable'." }
    ]
  },
  {
    id: "cae-rmc11-03",
    title: "The Quiet Removal of the Public Convenience",
    text: "Between 2010 and 2020, a substantial proportion of the public lavatories in British towns closed. The closures were rarely announced as policy. They occurred as individual decisions, each locally defensible, taken by authorities whose statutory obligations did not include provision and whose budgets were under pressure, and the cumulative effect has never been assessed by anybody with responsibility for it.\nThe consequences fall on a predictable set of people. Anybody with a medical condition affecting continence, anybody pregnant, anybody caring for a small child, anybody older, and anybody whose work is conducted outdoors. For these groups the availability of facilities determines the radius within which they can move, and its removal produces a contraction of the map that does not appear in any measure of transport or public health.\nThe standard reply is that cafés and shops provide an alternative. They do, conditionally: on the ability to buy something, on opening hours, on the confidence to walk in, and on not being refused. A provision available to a paying customer during business hours is not a substitute for a public facility, and describing it as one confuses the presence of a lavatory with access to it.\nSeveral countries have adopted an intermediate model in which businesses are paid a modest annual sum to make their facilities available to non-customers, with a sign in the window and no obligation to purchase. Evaluations have been broadly positive and identify a consistent limitation: participation is highest in areas that already have many businesses, which are not the areas with the greatest need.\nWhat makes the subject unusual is not the difficulty of the problem, which is small and cheap by the standards of municipal expenditure, but the reluctance to discuss it. Public facilities are treated as a low-status matter, unsuitable for serious debate and faintly comic, and they are consequently the first thing removed and the last thing restored. The people most affected by that judgement are, almost without exception, those least likely to be in the room when it is made.",
    questions: [
      { q: "How were the closures generally carried out?", options: ["As individual local decisions","Through public consultation","By private companies","As announced national policy"], answer: 0, explanation: "'They occurred as individual decisions, each locally defensible'." },
      { q: "What effect do the closures have on affected groups?", options: ["Increased costs", "A contraction of the area they can move within", "Longer working hours", "Reduced access to healthcare"], answer: 1, explanation: "'its removal produces a contraction of the map'." },
      { q: "What is the writer's objection to relying on cafés?", options: ["Staff are unhelpful","They are too expensive","Access is conditional in several ways","They are usually closed"], answer: 2, explanation: "'They do, conditionally: on the ability to buy something, on opening hours'." },
      { q: "What limitation do payment schemes show?", options: ["Costs rise rapidly","Signs are ignored","Businesses refuse to join","Participation is lowest where need is greatest"], answer: 3, explanation: "'participation is highest in areas that already have many businesses, which are not the areas with the greatest need'." },
      { q: "What does the writer find unusual about the issue?", options: ["The reluctance to discuss it","The lack of evidence","Its technical difficulty","Its cost"], answer: 0, explanation: "'but the reluctance to discuss it'." },
      { q: "Who is least likely to influence the decision?", options: ["Local businesses", "Those most affected by it", "Council officers", "Public health specialists"], answer: 1, explanation: "'those least likely to be in the room when it is made'." }
    ]
  },
  {
    id: "cae-rmc11-04",
    title: "Why We Believe the Forecast",
    text: "Weather forecasting has improved to a degree that is difficult to convey without figures. A five-day forecast today is about as accurate as a one-day forecast was in 1980, and the improvement has been steady rather than dramatic, which is one reason the public has largely failed to notice it.\nThe improvement rests on three developments. Satellite observation supplied data from the two-thirds of the planet that is ocean and was previously almost unobserved. Computing power allowed the atmosphere to be modelled at a resolution fine enough to represent the features that actually produce weather. And, least visibly, forecasters moved from producing a single prediction to running the same model many times from slightly different starting conditions, which converts a forecast into a distribution and makes it possible to say how confident it is.\nThat last change created a communication problem that has still not been solved. A forecast of a thirty per cent chance of rain is a statement about a distribution, and it is heard by most people as a statement about a decision: will it rain or not. When it then rains, the forecast is judged wrong, although a forecaster whose thirty per cent events occur three times in ten is performing exactly as intended. Research on the presentation of probability has found that almost every graphical solution proposed is misread by a substantial proportion of viewers, and that the least misread format is often plain text.\nThere is a further difficulty of incentives. A forecaster who over-predicts severe weather is criticised occasionally and mildly; one who under-predicts it is criticised severely and memorably. The asymmetry is rational at the individual level and produces, in aggregate, a systematic bias towards warning, which erodes precisely the credibility on which warnings depend.\nThe most effective interventions have been institutional rather than technical: publishing verification statistics so that accuracy can be checked, distinguishing clearly between what is likely and what is possible, and resisting the temptation to issue a warning that is defensible rather than justified. None of these improves the model. All of them improve whether anybody acts on it.",
    questions: [
      { q: "Why has the public not noticed forecasting improvements?", options: ["The figures are disputed","They have been kept secret","The improvement has been gradual","Forecasts are still inaccurate"], answer: 2, explanation: "'the improvement has been steady rather than dramatic'." },
      { q: "What did satellite observation provide?", options: ["Better presentation","Longer forecasts","Faster computers","Data from previously unobserved oceans"], answer: 3, explanation: "'Satellite observation supplied data from the two-thirds of the planet that is ocean'." },
      { q: "What does running a model many times allow?", options: ["A statement of confidence","Longer-range prediction","Cheaper computing","Faster production of forecasts"], answer: 0, explanation: "'converts a forecast into a distribution and makes it possible to say how confident it is'." },
      { q: "How is a thirty per cent chance of rain usually heard?", options: ["As a statement about a distribution", "As a statement about whether it will rain", "As a warning", "As a certainty"], answer: 1, explanation: "'it is heard by most people as a statement about a decision: will it rain or not'." },
      { q: "What bias do incentives create?", options: ["Towards vague language","Towards under-warning","Towards warning too often","Towards longer forecasts"], answer: 2, explanation: "'a systematic bias towards warning'." },
      { q: "What do the most effective interventions improve?", options: ["The speed of production","Public interest in weather","The accuracy of the model","Whether people act on forecasts"], answer: 3, explanation: "'All of them improve whether anybody acts on it.'" }
    ]
  },
  {
    id: "cae-rmc11-05",
    title: "The Words Beside the Painting",
    text: "The wall label is the least examined element of museum practice and, on the evidence of visitor studies, one of the most consequential. It is read by a majority of visitors, frequently before the object rather than after it, and it determines what most of them will subsequently see.\nThe conventions are older than they appear. The standard sequence of artist, title, date, medium and acquisition credit developed for a scholarly audience which required exactly that information and no other, and it survives in institutions whose visitors are overwhelmingly not scholars. Studies of eye movement show that a visitor typically spends longer on a label of forty words than on the object beside it, a distribution that would alarm most curators if they were told about it and which is entirely predictable, since text is easier to consume than an unfamiliar image.\nThe reform movement of the last two decades has favoured longer, more interpretive labels, and the results are mixed in an instructive way. Interpretation increases the time spent at an object and reduces the visitor's confidence in their own reading of it. Visitors given an authoritative account of what a painting means report higher satisfaction and produce, when questioned afterwards, fewer independent observations. The label has substituted for the looking rather than supporting it.\nThe most successful experiments have therefore moved in an unexpected direction: labels that ask rather than tell, that pose the question the curator found difficult, or that state plainly what is not known. A label reading that scholars disagree about the identity of the sitter produces measurably more looking than one asserting it, because it returns the visitor to the object as the only available evidence.\nWhat this suggests is that the function of a label is not to transmit information. It is to make the object worth attending to for longer, which is a different objective, and one that most institutional processes are not organised to pursue, since the label is generally written last, by whoever is available, from material prepared for a catalogue.",
    questions: [
      { q: "What does the writer say about wall labels?", options: ["They are consequential and under-examined","They should be removed","They are written by specialists","They are rarely read"], answer: 0, explanation: "'the least examined element of museum practice and... one of the most consequential'." },
      { q: "Where did the standard label format originate?", options: ["From visitor research", "From a scholarly audience's needs", "From advertising practice", "From legal requirements"], answer: 1, explanation: "'developed for a scholarly audience which required exactly that information'." },
      { q: "What do eye movement studies show?", options: ["Visitors prefer images to text","Visitors ignore labels","Visitors spend longer on the label than the object","Visitors read labels afterwards"], answer: 2, explanation: "'a visitor typically spends longer on a label of forty words than on the object beside it'." },
      { q: "What effect does interpretive text have?", options: ["It shortens visits","It is generally disliked","It increases independent observations","It reduces confidence in the visitor's own reading"], answer: 3, explanation: "'Interpretation increases the time spent at an object and reduces the visitor's confidence in their own reading of it.'" },
      { q: "Which labels produced more looking?", options: ["Those stating scholarly disagreement", "Those giving full biographies", "Those with no text at all", "Those written by artists"], answer: 0, explanation: "'A label reading that scholars disagree about the identity of the sitter produces measurably more looking'." },
      { q: "What does the writer identify as a label's real function?", options: ["Transmitting information", "Making the object worth attending to for longer", "Recording acquisition details", "Supporting the catalogue"], answer: 1, explanation: "'It is to make the object worth attending to for longer'." }
    ]
  },
  {
    id: "cae-rmc11-06",
    title: "The Price of Being Reachable",
    text: "The right to disconnect, legislated in several countries, is generally reported as a measure protecting employees from messages sent outside working hours. This description is accurate and misses what the research suggests is the more damaging phenomenon, which is not the message received but the expectation that one may arrive.\nStudies distinguishing between actual after-hours contact and anticipated contact find that the anticipation accounts for most of the measured effect on recovery, sleep and reported wellbeing. An employee who receives four messages in an evening is interrupted four times. An employee who receives none but believes one is possible does not recover, because the psychological function of non-working time depends on the certainty that it will not be interrupted, and a probability of eleven per cent is sufficient to remove that certainty entirely.\nThis has an uncomfortable implication for the standard organisational response, which is a policy stating that nobody is required to reply outside working hours. Such policies address the obligation and leave the expectation untouched, and expectation is set by observation rather than by documents: an employee who sees a manager sending messages at ten at night draws the obvious conclusion regardless of what the policy says.\nThe interventions that work in the evidence are behavioural and specific. Delayed sending, so that messages composed at night arrive in the morning, removes the signal without restricting when anybody works. Explicit statements of response times, agreed at team level rather than issued centrally. And, most effective and least common, senior people visibly not sending anything, which functions as evidence in a way no written policy does.\nThere is a further consideration that receives little attention. The employees most affected are frequently those who most value flexibility, since the same technology that enables a message at ten enables an appointment at three. Framing the question as a straightforward restriction risks removing an arrangement that many people have organised their lives around. The workable version is not less availability but clearer availability, which is harder to legislate and considerably more useful.",
    questions: [
      { q: "What does the writer say is more damaging than out-of-hours messages?", options: ["The time taken to reply","The volume of messages","The expectation that one may arrive","The tone of the messages"], answer: 2, explanation: "'not the message received but the expectation that one may arrive'." },
      { q: "Why does anticipated contact prevent recovery?", options: ["It disturbs sleep directly","It reduces working hours","It causes physical fatigue","Non-working time depends on certainty of non-interruption"], answer: 3, explanation: "'the psychological function of non-working time depends on the certainty that it will not be interrupted'." },
      { q: "What is wrong with policies stating that replies are not required?", options: ["They address obligation but not expectation","They are too restrictive","They apply only to managers","They are legally unenforceable"], answer: 0, explanation: "'Such policies address the obligation and leave the expectation untouched'." },
      { q: "How is expectation actually set?", options: ["By written documents", "By observation of what others do", "By employment contracts", "By legislation"], answer: 1, explanation: "'expectation is set by observation rather than by documents'." },
      { q: "Which intervention does the writer consider most effective?", options: ["Delayed sending", "Agreed response times", "Senior people visibly not sending", "Central policies"], answer: 2, explanation: "'most effective and least common, senior people visibly not sending anything'." },
      { q: "Why does the writer caution against framing this as restriction?", options: ["It is expensive to enforce","It reduces productivity","Employees would object to monitoring","It could remove valued flexibility"], answer: 3, explanation: "'risks removing an arrangement that many people have organised their lives around'." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
