/* CAE Prep bank: Reading true/false/not given (C1) — wave 9 */
(function () {
var BANK = [
  {
    id: "cae-rtfng9-01",
    title: "Salvage at Sea",
    text: "The law of salvage is among the older bodies of commercial law and rests on a principle that is unusual: a person who saves property at sea without any obligation to do so may claim a reward, and the reward is assessed by a tribunal rather than agreed in advance.\nThe principle exists because of the alternative. A vessel in difficulty is frequently unable to negotiate, and a rule requiring agreement before assistance would produce either extortionate terms or no assistance at all. The salvage award is therefore calculated afterwards, taking account of the value saved, the danger, the skill exercised and the risk assumed by the salvor.\nA critical feature is that the claim depends on success. A salvor who works for a week and fails receives nothing under the traditional rule, which is intended to encourage effort and which produced, for a long period, a specific perverse consequence: a vessel carrying a cargo of low value and a substantial quantity of oil was not worth saving, since the recoverable value was small and the environmental damage was not property that anybody owned.\nThe response was a modification introduced in the 1980s under which a salvor attempting to prevent environmental damage receives expenses even where the operation fails, with an uplift where damage is prevented. The change was resisted by insurers on the grounds that it separates reward from result and was adopted because the alternative was demonstrably worse.\nThe modern position is complicated by the involvement of states. A coastal state may direct a casualty away from its waters, which is understandable in each individual case and which, applied by every state, produces a vessel that cannot obtain a place of refuge and deteriorates at sea. Several conventions address this and the practical outcome still depends on decisions taken locally under considerable political pressure.",
    questions: [
      { q: "A salvor's reward is agreed before assistance is given.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'is assessed by a tribunal rather than agreed in advance'." },
      { q: "The rule exists partly because a vessel in trouble cannot negotiate freely.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'frequently unable to negotiate'." },
      { q: "Under the traditional rule, an unsuccessful salvor receives nothing.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'receives nothing under the traditional rule'." },
      { q: "The traditional rule encouraged the salvage of low-value vessels carrying oil.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - such a vessel 'was not worth saving'." },
      { q: "The 1980s modification pays expenses even when an operation fails.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'receives expenses even where the operation fails'." },
      { q: "Insurers supported the modification.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'was resisted by insurers'." },
      { q: "Coastal states may refuse a damaged vessel entry to their waters.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'may direct a casualty away from its waters'." },
      { q: "Most salvage claims are now settled without a tribunal.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the assessment process is described but not how disputes are usually resolved." }
    ]
  },
  {
    id: "cae-rtfng9-02",
    title: "Taking the Varnish Off",
    text: "The cleaning of a painting is the most contested operation in conservation, and the disagreement is not principally about technique. It concerns what a painting is: an object as the artist left it, an object as it has become, or an object as an audience of a particular period expects it to look.\nMost old paintings carry a varnish, applied to saturate colours and to protect the surface, which yellows and darkens over decades. Removing it recovers something closer to the original appearance, and the operation is irreversible and cannot be conducted with complete certainty about what lies beneath.\nThe technical difficulty is that a varnish and the paint below it may be soluble in similar solvents, and that some artists applied final glazes in media chemically close to varnish. A cleaning conducted by somebody who does not recognise a glaze removes it, and the loss is undetectable afterwards to anybody who did not see the painting before.\nThe most famous disputes of the last century turned on this question rather than on carelessness. Cleanings that produced brighter surfaces were attacked on the grounds that the intended effect included a degree of tonal unity that the removed layers had provided, and defended on the grounds that the layers were later additions with no authority. Both positions were argued by serious people and the evidence in individual cases was frequently equivocal.\nCurrent practice has moved towards partial cleaning, thinning a varnish rather than removing it, and towards extensive analysis and documentation before any intervention. This is more defensible and it does not resolve the underlying question, which is not technical and which every generation answers slightly differently, generally without noticing that it is answering it at all.",
    questions: [
      { q: "The main disagreement about cleaning concerns technique.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the disagreement is not principally about technique'." },
      { q: "Varnish was applied both to saturate colours and to protect.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'to saturate colours and to protect the surface'." },
      { q: "Cleaning can be reversed if a mistake is made.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the operation is irreversible'." },
      { q: "Some artists' final glazes resemble varnish chemically.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'in media chemically close to varnish'." },
      { q: "The loss of a glaze can be detected afterwards by any observer.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the loss is undetectable afterwards to anybody who did not see the painting before'." },
      { q: "Historic disputes involved serious arguments on both sides.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Both positions were argued by serious people'." },
      { q: "Current practice favours thinning varnish rather than removing it.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'thinning a varnish rather than removing it'." },
      { q: "Museums now publish records of all cleaning operations online.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - documentation is mentioned but not publication." }
    ]
  },
  {
    id: "cae-rtfng9-03",
    title: "Paying for an Orchestra",
    text: "An orchestra is an unusual economic object: its costs are almost entirely labour, its productivity cannot be increased, and the number of people required to perform a work written in 1830 is the number that was required in 1830.\nThis produces the effect described by economists as cost disease. In an economy where wages rise with productivity growth generally, activities whose productivity cannot rise must either pay relatively less over time or become relatively more expensive. An orchestra's costs therefore increase faster than general inflation, indefinitely, and this is a structural feature rather than a symptom of mismanagement.\nRevenue does not follow the same path. Ticket income is limited by hall capacity and by what audiences will pay, and both are effectively fixed. The gap is met by subsidy, by private giving or by activity outside the concert hall, and the balance between these differs enormously between countries and largely determines what the institution can programme.\nThe programming effect is the part least visible to audiences. An orchestra dependent on ticket income performs repertoire that sells, which is a defined body of about four hundred works, and one with a substantial subsidy or endowment can perform music that will not fill a hall. Comparisons of programming between countries show this clearly, and the differences correspond to funding structures rather than to any difference in what audiences are willing to hear.\nThe alternative responses have limits. Reducing the number of players changes the repertoire that can be performed. Increasing the number of concerts encounters the availability of an audience and the physical limits of the players. What has expanded most is work outside performance, in education and in recording, which produces income and occupies time that the orchestra was not previously using, and which several institutions now describe as the reason they continue to exist.",
    questions: [
      { q: "Orchestral costs are mostly labour.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'its costs are almost entirely labour'." },
      { q: "An orchestra's rising costs indicate poor management.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'a structural feature rather than a symptom of mismanagement'." },
      { q: "Ticket income is constrained by capacity and willingness to pay.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'limited by hall capacity and by what audiences will pay'." },
      { q: "Funding structures affect what music is programmed.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the differences correspond to funding structures'." },
      { q: "Differences in programming reflect what audiences will accept.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'rather than to any difference in what audiences are willing to hear'." },
      { q: "Reducing player numbers has no effect on repertoire.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'changes the repertoire that can be performed'." },
      { q: "Educational and recording work has grown.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'What has expanded most is work outside performance'." },
      { q: "Orchestras in most countries receive a majority of income from subsidy.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the balance is said to differ enormously, with no majority stated." }
    ]
  },
  {
    id: "cae-rtfng9-04",
    title: "Who Crews the Lifeboat",
    text: "In several countries the sea rescue service is operated by volunteers and funded by donation, an arrangement that visitors from countries with state services find difficult to credit and that has proved remarkably durable.\nThe operational model depends on geography. A crew must be able to reach a station within a few minutes, which requires volunteers who live and work close to it, and the viability of a station is therefore determined by whether the surrounding community contains enough people whose employment permits them to leave at short notice. Stations have closed where that condition failed, generally because local employment moved rather than because volunteers could not be found.\nTraining is extensive and has become more so. The qualifications now required of a coxswain represent several hundred hours, which is a substantial commitment from somebody unpaid and which the organisations concerned regard as non-negotiable, since the equipment and the expectations have both changed.\nThe funding model has consequences that are rarely discussed. An organisation dependent on donation must maintain public visibility, which shapes what it can say publicly about risk, about the causes of incidents and about the behaviour of the people it rescues. Criticism of a group of sea users is available to a state agency and is expensive for a charity, and this is understood inside such organisations and is not usually stated.\nThe question raised periodically is whether such a service should be a public function. The arguments for are consistency and accountability; the arguments against are cost and a concern about what would be lost, since the volunteer model produces a level of local knowledge and of community identification with the service that a state agency has generally not achieved. The debate is conducted with some warmth and has produced very little change anywhere.",
    questions: [
      { q: "Volunteer sea rescue services exist in several countries.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'In several countries the sea rescue service is operated by volunteers'." },
      { q: "A station's viability depends on local employment patterns.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'whether the surrounding community contains enough people whose employment permits them'." },
      { q: "Stations have closed mainly through a shortage of volunteers.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'generally because local employment moved rather than because volunteers could not be found'." },
      { q: "Training requirements have decreased over time.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'Training is extensive and has become more so.'" },
      { q: "Reliance on donations affects what the organisation can say publicly.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'shapes what it can say publicly about risk'." },
      { q: "The constraint on public criticism is openly discussed.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'is not usually stated'." },
      { q: "Debate about making the service public has produced little change.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'has produced very little change anywhere'." },
      { q: "Volunteer crews receive an allowance for each call-out.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - they are described as unpaid, but allowances are never mentioned." }
    ]
  },
  {
    id: "cae-rtfng9-05",
    title: "Reading the Map's Names",
    text: "Place names are among the most durable artefacts a landscape contains, frequently outlasting the language in which they were formed, and they are read by historians as evidence about settlement, land use and the sequence in which populations arrived.\nThe method rests on the observation that names are rarely invented from nothing. A name typically describes something: a feature, an owner, a use, a relative position. Where the descriptive element belongs to a language no longer spoken in the area, the name preserves a layer of occupation that may have left no other trace, and the distribution of such names across a region maps a settlement pattern more finely than archaeology generally can.\nThe evidence requires care. Names are transmitted orally and are reshaped by the speakers of each subsequent language into forms that make sense to them, a process that can produce a name whose apparent meaning is entirely misleading. A name that appears to refer to a bridge may be a reworking of an unrelated word in an earlier language, and the only reliable method is to work from the earliest recorded spellings rather than from the modern form.\nDating is the weakest part of the method. A name can be shown to belong to a particular language and can rarely be assigned to a period within that language's currency with any precision, and attempts to construct chronologies from name types have been repeatedly revised.\nWhat has changed the field most is the availability of early documentary spellings in searchable form. A discipline that depended on scholars who had read a great deal now permits systematic comparison across regions, and several generalisations that had circulated for decades on the basis of a small number of well-known examples have not survived that comparison.",
    questions: [
      { q: "Place names can outlast the languages that formed them.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'frequently outlasting the language in which they were formed'." },
      { q: "Names are usually invented without reference to anything.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'names are rarely invented from nothing'." },
      { q: "Names in an extinct local language can indicate earlier settlement.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'preserves a layer of occupation that may have left no other trace'." },
      { q: "A modern form is the most reliable basis for interpretation.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'work from the earliest recorded spellings rather than from the modern form'." },
      { q: "Dating names precisely is difficult.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'can rarely be assigned to a period... with any precision'." },
      { q: "Chronologies based on name types have needed revision.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'have been repeatedly revised'." },
      { q: "Searchable early spellings have overturned some earlier generalisations.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'have not survived that comparison'." },
      { q: "Most European countries maintain official databases of historic place names.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - searchable material is mentioned without reference to official databases." }
    ]
  },
  {
    id: "cae-rtfng9-06",
    title: "What Is Recorded in Ice",
    text: "An ice core is a record of the atmosphere, and its value derives from a property of snow that is easy to state and difficult to appreciate: air is trapped in the spaces between snow crystals and is sealed as the snow compacts, so that a sample of ancient ice contains a sample of ancient air.\nThe sealing is not instantaneous. Air circulates in the porous upper layer for a period that depends on the accumulation rate, and the gas in a given layer of ice is therefore younger than the ice itself, by an interval ranging from decades at high-accumulation sites to several thousand years where accumulation is very slow. Reconciling the two chronologies is a substantial technical problem and a source of much of the uncertainty in the resulting records.\nWhat the ice itself records is different from what the trapped air records. The isotopic composition of the water provides a proxy for temperature at the time of deposition; the trapped air provides direct measurement of atmospheric composition. Dust, ash and chemical impurities provide additional information about volcanic activity, wind and, in recent layers, industrial emissions.\nCores from different regions are not equivalent. High-accumulation sites give fine resolution over short periods; low-accumulation sites give coarse resolution over very long ones, and the longest continuous records available extend back several hundred thousand years from sites where snowfall is minimal.\nThe practical difficulties of obtaining a core are considerable and are rarely described. Drilling proceeds through ice that deforms under pressure, the fluid used to prevent the hole closing must be chemically compatible with the analyses to be conducted, and a core recovered without contamination must be transported and stored at temperature for years, since the analyses are conducted in laboratories on other continents and are refined continuously as methods improve.",
    questions: [
      { q: "Ice cores contain samples of ancient air.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'a sample of ancient ice contains a sample of ancient air'." },
      { q: "Air is sealed into the ice immediately as snow falls.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'The sealing is not instantaneous.'" },
      { q: "The trapped gas is younger than the ice around it.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the gas in a given layer of ice is therefore younger than the ice itself'." },
      { q: "Temperature is measured directly from the trapped air.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the water's isotopic composition provides 'a proxy for temperature'." },
      { q: "Cores from all regions provide similar resolution.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'Cores from different regions are not equivalent.'" },
      { q: "The longest records come from areas with little snowfall.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'from sites where snowfall is minimal'." },
      { q: "Drilling fluid must be compatible with later analysis.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'must be chemically compatible with the analyses'." },
      { q: "Ice core drilling projects are typically funded by international consortia.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the practical difficulties are described, but nothing is said about who funds the work." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
