/* CAE Prep bank: Reading true/false/not given (C1) — wave 6 */
(function () {
var BANK = [
  {
    id: "cae-rtfng6-01",
    title: "The Box That Reorganised Trade",
    text: "The shipping container is usually described as an invention and is more accurately a standard. Boxes had been used to move goods for centuries; what changed in the late 1950s was an agreement about dimensions, corner fittings and lifting points, and it is the agreement rather than the box that produced the effect.\nBefore containerisation, a general cargo ship spent the majority of its working life in port. Loading was performed by gangs handling individual items, the process took days, and the cost of it accounted for a substantial share of the total cost of moving goods. The container reduced port time from days to hours and shifted the economics of distance decisively.\nThe consequences extended well beyond shipping. Because the marginal cost of moving a container a further thousand kilometres became small, the location of production could be decided on grounds other than proximity to markets, and manufacturing dispersed accordingly. Economists studying the period have argued that containerisation contributed more to the growth of trade than the tariff reductions negotiated over the same decades, although the size of the effect remains disputed.\nThe transition was resisted, and the resistance was not irrational. Dock labour was skilled, organised and rendered largely unnecessary; ports whose facilities could not accommodate cranes and container yards declined rapidly, and several major historic ports lost their trade to sites downstream with deep water and space. The distribution of gains and losses was extremely uneven and was not addressed by any mechanism at the time.\nStandardisation was not achieved quickly. Competing systems existed through the 1960s, and agreement on a common specification required negotiations that several participants had commercial reasons to obstruct. The final standard was, by most accounts, technically inferior in certain respects to at least one alternative, which is the ordinary outcome of such processes and is generally less important than having any standard at all.",
    questions: [
      { q: "The container is better understood as a standard than as an invention.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'The shipping container is usually described as an invention and is more accurately a standard.'" },
      { q: "Before containerisation, ships spent most of their time at sea.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'a general cargo ship spent the majority of its working life in port'." },
      { q: "Loading costs were a significant proportion of total transport costs.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the cost of it accounted for a substantial share of the total cost of moving goods'." },
      { q: "Economists agree precisely how much containerisation increased trade.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the size of the effect remains disputed'." },
      { q: "Opposition from dock workers is described as unreasonable.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the resistance was not irrational'." },
      { q: "Some established ports lost trade to newer locations.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'several major historic ports lost their trade to sites downstream'." },
      { q: "The agreed standard was technically the best available option.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it was 'technically inferior in certain respects to at least one alternative'." },
      { q: "Container dimensions have been revised since the original agreement.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the text describes the original standardisation but says nothing about later revision." }
    ]
  },
  {
    id: "cae-rtfng6-02",
    title: "How Resistance Travels",
    text: "Antibiotic resistance is frequently described as though bacteria acquired it through exposure in an individual patient, which occurs and is not the principal mechanism by which resistance spreads through a population.\nThe more consequential route is horizontal gene transfer. Bacteria exchange genetic material directly, including between species, by several mechanisms, and a resistance gene that arises in one organism can be transferred to an unrelated one without any inheritance in the ordinary sense. This is why resistance can appear in a species that has never been exposed to the antibiotic concerned.\nThe selective pressure that matters is therefore not confined to clinical settings. Agricultural use accounts for a substantial proportion of total antibiotic consumption in many countries, and residues in the environment maintain low-level pressure across enormous bacterial populations. Sub-lethal concentrations are, in some respects, worse than lethal ones: they do not eliminate the organism and they favour any variant with partial protection.\nThe economics of the response are unfavourable in a specific way. Developing a new antibiotic costs a sum comparable to any other drug, and the resulting product is one that clinicians will deliberately restrict in order to preserve it, and that will be used for short courses rather than continuously. A medicine whose value depends on being used as little as possible does not generate the return that the development model assumes, and several major manufacturers have withdrawn from the field entirely.\nProposals to address this generally separate the reward from the volume sold. Under such arrangements a health system pays a fixed sum for access to an antibiotic regardless of how much is used, which removes the incentive to promote it. Pilot schemes exist in a small number of countries and the evidence about them is not yet extensive, though the mechanism is widely regarded as the most plausible available.",
    questions: [
      { q: "Resistance spreads mainly through exposure within individual patients.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - that 'is not the principal mechanism by which resistance spreads'." },
      { q: "Bacteria can pass resistance genes between different species.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Bacteria exchange genetic material directly, including between species'." },
      { q: "Resistance can appear in organisms never exposed to the drug.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'resistance can appear in a species that has never been exposed'." },
      { q: "Low concentrations of antibiotics are always less harmful than high ones.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'Sub-lethal concentrations are, in some respects, worse than lethal ones'." },
      { q: "Developing a new antibiotic costs less than developing other drugs.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'costs a sum comparable to any other drug'." },
      { q: "Some large manufacturers have left this area of research.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'several major manufacturers have withdrawn from the field entirely'." },
      { q: "Proposed payment schemes would pay a fixed amount regardless of use.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'a health system pays a fixed sum for access... regardless of how much is used'." },
      { q: "Agricultural antibiotic use has been banned in most European countries.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - agricultural use is described but no legislation is mentioned." }
    ]
  },
  {
    id: "cae-rtfng6-03",
    title: "The Method That Made Accounting Possible",
    text: "Double-entry bookkeeping is generally dated to a treatise published in 1494, which is misleading in two respects: the method was in use among Italian merchants for at least two centuries before that, and the treatise was a description rather than a proposal.\nThe innovation is not the recording of transactions, which is ancient, but the recording of each transaction twice, as a debit in one account and a credit in another. The resulting system has a property that single-entry recording lacks: the totals must agree, and a discrepancy indicates an error somewhere without indicating where. This is a weak form of verification and it is considerably stronger than none.\nThe method's more consequential effect was conceptual. By requiring every transaction to be classified, it forced a distinction between the business and its owner, between capital and income, and between what is owed and what is owned. These distinctions are so familiar now that they appear natural, and they are artefacts of a recording system rather than features of commerce, and merchants operating without them had considerable difficulty establishing whether an enterprise was profitable.\nHistorians disagree about how far the method contributed to the development of commercial capitalism. One influential argument holds that systematic accounting made possible the rational calculation on which large enterprises depend; critics point out that highly profitable enterprises operated for centuries without it, and that the causal direction is difficult to establish.\nWhat is not disputed is the method's persistence. The system in use in a modern accounting package is recognisably the one described in 1494, which is unusual among technologies of comparable age, and the reason appears to be that it solves a problem whose structure has not changed. Transactions still have two sides, and any system recording only one of them still cannot be checked.",
    questions: [
      { q: "Double-entry bookkeeping was invented in 1494.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the method was in use among Italian merchants for at least two centuries before that'." },
      { q: "The 1494 work described an existing practice.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the treatise was a description rather than a proposal'." },
      { q: "A discrepancy in the totals identifies where the error occurred.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'a discrepancy indicates an error somewhere without indicating where'." },
      { q: "The distinctions the method requires are described as natural features of commerce.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'they are artefacts of a recording system rather than features of commerce'." },
      { q: "Historians disagree about the method's role in economic development.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Historians disagree about how far the method contributed'." },
      { q: "Some profitable businesses operated without the method for long periods.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'highly profitable enterprises operated for centuries without it'." },
      { q: "Modern accounting software uses a recognisably similar system.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'is recognisably the one described in 1494'." },
      { q: "The 1494 treatise was translated into English within fifty years.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - nothing is said about translations." }
    ]
  },
  {
    id: "cae-rtfng6-04",
    title: "Why Concrete Deteriorates",
    text: "Concrete is often assumed to be inert, and the assumption underlies a great deal of optimism about the durability of structures built in the twentieth century. The material is chemically active throughout its life, and most deterioration originates not in the concrete but in the steel embedded within it.\nSteel in concrete is normally protected by the alkalinity of the surrounding material, which maintains a passive oxide layer on the surface of the bar. Two processes destroy that protection. Carbonation occurs as carbon dioxide penetrates from the surface and reduces alkalinity, advancing at a rate proportional to the square root of time. Chloride penetration, from de-icing salt or a marine environment, breaks down the passive layer locally without any general change in alkalinity.\nOnce the protection fails, the steel corrodes, and the corrosion product occupies a considerably greater volume than the original metal. The expansion cracks the surrounding concrete, which admits more moisture and accelerates the process. The visible damage therefore appears long after the initiating mechanism began, and by the time a structure is spalling the deterioration is well advanced.\nThe rate depends heavily on cover, the depth of concrete between the surface and the steel, which is specified in every code and is routinely reduced in construction by displacement of reinforcement during pouring. A shortfall of ten millimetres in cover can reduce the time to initiation of corrosion by a substantial factor, and cover is checked on site far less often than its importance would suggest.\nRepair is difficult for a reason that is not obvious. Replacing damaged concrete with new material of higher alkalinity creates a difference in electrical potential between the repaired area and the surrounding original, which can accelerate corrosion immediately adjacent to the repair. This effect is well documented, is frequently unanticipated, and is the reason a substantial proportion of concrete repairs fail within a decade at the boundary rather than within the repaired area.",
    questions: [
      { q: "Most concrete deterioration begins with the steel reinforcement.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'most deterioration originates not in the concrete but in the steel embedded within it'." },
      { q: "Alkalinity in concrete protects the steel.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'protected by the alkalinity of the surrounding material'." },
      { q: "Chloride penetration works by reducing alkalinity generally.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'breaks down the passive layer locally without any general change in alkalinity'." },
      { q: "Corrosion products take up less space than the original steel.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'occupies a considerably greater volume than the original metal'." },
      { q: "Visible damage appears well after deterioration has begun.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'The visible damage therefore appears long after the initiating mechanism began'." },
      { q: "Concrete cover is frequently checked during construction.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'cover is checked on site far less often than its importance would suggest'." },
      { q: "Repairs can accelerate corrosion next to the repaired area.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'can accelerate corrosion immediately adjacent to the repair'." },
      { q: "Most twentieth-century concrete structures will require replacement before 2050.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the mechanisms are described but no such prediction is made." }
    ]
  },
  {
    id: "cae-rtfng6-05",
    title: "Crops on the Move",
    text: "The distribution of the world's staple crops bears little relation to where they were domesticated, and the reorganisation occurred largely within a few centuries following the connection of the Americas with Europe, Africa and Asia.\nThe transfers ran in both directions and were not symmetrical in their effects. Crops of American origin, including maize, potatoes, cassava and tomatoes, entered agricultural systems in Africa, Europe and Asia and in several cases became staples. Crops from the other direction, including wheat, sugar and coffee, were established in the Americas largely through plantation systems dependent on coerced labour.\nThe demographic consequences of the westward transfer are the subject of a substantial literature. The potato, in particular, produces more calories per hectare than the grains it partly replaced in northern Europe and grows in soils and climates unsuitable for them, and its adoption is associated with population increases that historians have estimated using a variety of methods with results that vary considerably.\nAdoption was slow and uneven, which the standard account tends to compress. The potato was known in Europe for roughly two centuries before it was widely cultivated, was regarded with suspicion in several regions, and was in some cases promoted by governments for reasons of food security rather than adopted by preference.\nThe risks of the resulting dependence were demonstrated in the nineteenth century. A population reliant on a single crop, propagated vegetatively and therefore genetically uniform across enormous areas, is exposed to a pathogen to which that clone has no resistance. The mechanism was not understood at the time and is now the standard argument for maintaining genetic diversity in staple crops, an argument that is widely accepted and unevenly acted upon.",
    questions: [
      { q: "Staple crops are mostly grown where they were first domesticated.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the distribution 'bears little relation to where they were domesticated'." },
      { q: "The transfers of crops went in both directions.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'The transfers ran in both directions'." },
      { q: "Crops taken to the Americas were established through plantation systems.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'established in the Americas largely through plantation systems'." },
      { q: "Historians agree on the size of the potato's demographic effect.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - estimates 'vary considerably'." },
      { q: "The potato was adopted in Europe almost immediately.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - it 'was known in Europe for roughly two centuries before it was widely cultivated'." },
      { q: "Some governments encouraged potato cultivation deliberately.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'promoted by governments for reasons of food security'." },
      { q: "Genetic uniformity increased vulnerability to disease.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'genetically uniform across enormous areas, is exposed to a pathogen'." },
      { q: "Most countries now maintain seed banks for staple crops.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the argument for diversity is mentioned, but no information about seed banks." }
    ]
  },
  {
    id: "cae-rtfng6-06",
    title: "Defining the Metre",
    text: "The metre was defined in 1795 as one ten-millionth of the distance from the equator to the North Pole along a meridian passing through Paris. The definition was intended to tie the unit to something universal rather than to the body of a monarch, and it had a practical difficulty: the quantity in question was not known.\nAn expedition was therefore mounted to measure an arc of the meridian between Dunkirk and Barcelona, a task that occupied seven years and was conducted under conditions including war and repeated arrest of the surveyors. The result was used to construct a platinum bar, and the metre thereby became, in practice, the length of that bar.\nSubsequent measurement established that the expedition's figure contained an error of about a fifth of a millimetre in the metre, arising from an incorrect assumption about the flattening of the Earth. The error was not corrected, because by then a great many instruments had been calibrated against the bar, and changing the unit would have invalidated them. The metre is therefore, and remains, slightly different from what its original definition specified.\nThe definition was subsequently changed twice for reasons unconnected with accuracy of that kind. In 1960 the metre was redefined in terms of the wavelength of a particular spectral line, which permitted any adequately equipped laboratory to realise the unit without reference to an object in France. In 1983 it was redefined again as the distance light travels in a specified fraction of a second, which fixed the speed of light by definition and transferred the metrological problem to the measurement of time.\nThe modern arrangement has a consequence that is occasionally misunderstood. The speed of light is no longer measured; it is a defined constant, and an experiment that appeared to find a different value would be interpreted as a measurement of length or of time rather than as a discovery about light.",
    questions: [
      { q: "The 1795 definition referred to a quantity that had not been measured.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the quantity in question was not known'." },
      { q: "The surveying expedition was completed without incident.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - conditions included 'war and repeated arrest of the surveyors'." },
      { q: "An error was later found in the expedition's result.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'an error of about a fifth of a millimetre in the metre'." },
      { q: "The error was corrected once it had been identified.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'The error was not corrected'." },
      { q: "The 1960 definition allowed laboratories to realise the metre independently.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'without reference to an object in France'." },
      { q: "The 1983 definition fixed the speed of light by definition.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'which fixed the speed of light by definition'." },
      { q: "The speed of light continues to be measured experimentally.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'The speed of light is no longer measured; it is a defined constant'." },
      { q: "The original platinum bar is still held in Paris.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the bar's construction is described but its present location is not." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
