/* PET Prep extra bank: listening (week 3) */
(function () {
var BANK = [
  { id: "p-lis3-01", title: "Radio Interview: The Comic Collector", kind: "dialogue",
    script: "Interviewer: With me in the studio today is David Okafor, who owns one of the biggest comic collections in the region — over four thousand comics. David, where did it all begin?\nDavid: With one wet Sunday at my uncle's house, believe it or not. I was ten, it was raining, and he pulled an old box of comics out of a cupboard to keep me quiet. By dinner time I'd read every single one.\nInterviewer: And now, four thousand comics later! Which one is the most valuable?\nDavid: Funny story, that. It's a first issue from the 1960s, and collectors would pay a lot for it. But I found it at a car boot sale, in a box marked 'everything fifty pence'. The seller had no idea. I still feel slightly guilty.\nInterviewer: Do you ever sell any of them?\nDavid: Never. That surprises people, because some are worth real money. But for me, selling one would be like selling a memory. What I do instead is lend them out. Right now, about two hundred of my comics are in an exhibition at the town library, where anyone can read them, with gloves on, of course.\nInterviewer: You also go to collectors' fairs, I hear.\nDavid: Every month. But I don't really go to buy any more — I go to swap. Trading a comic you have twice for one you've never seen is the best feeling in this hobby. And the conversations are half the fun.",
    questions: [
      { q: "How did David's interest in comics start?", options: ["His uncle gave him a box to read on a rainy day.", "He bought a box at a car boot sale.", "A librarian recommended them to him.", "He read them at a collectors' fair."], answer: 0, explanation: "At his uncle's house on a wet Sunday, his uncle 'pulled an old box of comics out of a cupboard', and he read them all." },
      { q: "Why does David feel slightly guilty about his most valuable comic?", options: ["He borrowed it and never returned it.", "He paid very little because the seller didn't know its value.", "He damaged it while reading it.", "He sold it for too much money."], answer: 1, explanation: "He found the valuable first issue in a fifty-pence box and 'the seller had no idea' of its worth." },
      { q: "Why does David refuse to sell his comics?", options: ["Nobody has offered enough money.", "He plans to give them to his uncle.", "They feel like memories to him.", "They are all damaged with age."], answer: 2, explanation: "He says 'selling one would be like selling a memory', even though some are worth real money." },
      { q: "What is happening at the town library?", options: ["David is selling comics there.", "A comic fair takes place there monthly.", "David is teaching a drawing class.", "Some of his comics are on show there."], answer: 3, explanation: "About two hundred of his comics 'are in an exhibition at the town library, where anyone can read them'." },
      { q: "Why does David go to collectors' fairs now?", options: ["To exchange comics with other collectors.", "To buy rare first issues cheaply.", "To sell his double copies.", "To advertise the library exhibition."], answer: 0, explanation: "He says 'I don't really go to buy any more — I go to swap', trading doubles for comics he's never seen." }
    ] },
  { id: "p-lis3-02", title: "Announcement: Information for Ferry Passengers", kind: "monologue",
    script: "Good afternoon, ladies and gentlemen. This is an announcement for all passengers waiting for the three o'clock ferry to Seal Island, so please listen carefully. Because of strong winds out in the bay, today's crossing will take about fifty minutes instead of the usual thirty-five. The captain has asked us to tell you that the ride may be bumpy, but it is completely safe. If you are travelling with a vehicle, please return to your car now, as cars and bicycles will board first through the lower door. Foot passengers should wait behind the yellow line until a member of staff calls them forward — this will be about ten minutes after the vehicles. Please have your tickets ready in your hand, as they will be checked before you board rather than on the boat. A note about facilities on board today: because of the weather, the small café on the lower deck will stay closed for this crossing, so if you would like snacks or hot drinks, please buy them from the kiosk in the terminal before boarding. The open upper deck remains available for those who enjoy fresh air, but please hold the rails and keep children by your side at all times. Finally, an important change for anyone returning today: the last ferry back from the island will leave at half past five, one hour earlier than the printed timetable says. Thank you, and we wish you a pleasant crossing.",
    questions: [
      { q: "Why will today's crossing take longer than usual?", options: ["The ferry is smaller than normal.", "There are strong winds in the bay.", "Extra stops have been added.", "The captain is new to the route."], answer: 1, explanation: "Because of 'strong winds out in the bay', the crossing takes about fifty minutes instead of thirty-five." },
      { q: "Who will board the ferry first?", options: ["Foot passengers with tickets.", "Families with young children.", "Passengers with cars and bicycles.", "People who bought snacks."], answer: 2, explanation: "The announcement says 'cars and bicycles will board first through the lower door', before foot passengers." },
      { q: "When will tickets be checked?", options: ["Before passengers get on the boat.", "During the crossing.", "When passengers leave at the island.", "At the kiosk in the terminal."], answer: 0, explanation: "Tickets 'will be checked before you board rather than on the boat', so passengers should have them ready." },
      { q: "What should passengers do if they want hot drinks?", options: ["Order them from staff on the boat.", "Buy them at the terminal kiosk first.", "Use the machine on the upper deck.", "Wait until the café opens on board."], answer: 1, explanation: "The on-board café is closed today, so passengers should 'buy them from the kiosk in the terminal before boarding'." },
      { q: "What has changed about the return journey?", options: ["It will leave from a different door.", "It has been cancelled completely.", "It will cost more than usual.", "The last ferry leaves an hour earlier."], answer: 3, explanation: "The last ferry back 'will leave at half past five, one hour earlier than the printed timetable says'." }
    ] },
  { id: "p-lis3-03", title: "Phone Message: We Found Your Jacket", kind: "monologue",
    script: "Hello, this is a message for Mr Alex Turner. My name's Becky and I'm calling from the reception desk at Riverside Sports Centre. Good news — we've found your blue jacket! One of our cleaners picked it up in the badminton hall late last night, after the courts closed. We knew it was yours because your membership card was in the inside pocket, which is also how we got this phone number. Now, a few important details about collecting it. The jacket is here at the main reception desk, and you can pick it up any day this week. We're open from seven in the morning until nine at night. Please bring some identification with you — a driving licence or a bank card is fine — because we always check before handing over lost property. If you can't come this week, don't worry: after seven days, lost items are moved from reception to the manager's office upstairs, where we keep them for one month. After that, I'm afraid they go to the charity shop on Green Lane, so do try to come before then. While I have you, two more quick things. First, there was also a set of keys found on the same court — if they're yours, please mention it when you come. And second, our records show your membership ends this month. If you renew before Friday, you get ten percent off the yearly price. Okay, that's everything. See you soon, hopefully. Bye!",
    questions: [
      { q: "How did the sports centre know the jacket belonged to Alex?", options: ["His name was written inside it.", "His membership card was in the pocket.", "A friend recognised it.", "He reported it missing online."], answer: 1, explanation: "Becky says 'your membership card was in the inside pocket', which also gave them his phone number." },
      { q: "What must Alex bring when he collects the jacket?", options: ["Some form of identification.", "His badminton racket.", "The keys found on the court.", "A photo of the jacket."], answer: 0, explanation: "He should bring 'some identification... a driving licence or a bank card', because staff check before returning lost property." },
      { q: "What happens to lost items after seven days at reception?", options: ["They are thrown away.", "They are sent to the police.", "They are kept in the manager's office.", "They are sold at the front desk."], answer: 2, explanation: "After seven days, items 'are moved from reception to the manager's office upstairs', where they stay for a month." },
      { q: "Where do unclaimed items finally go after one month?", options: ["To a charity shop.", "Back to the badminton hall.", "To the town's lost property office.", "To the cleaner who found them."], answer: 0, explanation: "After a month in the office, items 'go to the charity shop on Green Lane', so Alex should come before then." },
      { q: "What can Alex get if he renews his membership before Friday?", options: ["A free month of badminton.", "A discount on the yearly price.", "A new membership card.", "Free entry for a friend."], answer: 1, explanation: "Becky says if he renews before Friday, 'you get ten percent off the yearly price'." }
    ] }
,
  { id: "p-lis3-04", title: "Mountains or Beach? Choosing a Holiday", kind: "dialogue",
    script: "Zoe: Okay, Sam, we said we'd book the June holiday tonight. Beach or mountains? We've been talking about this for weeks.\nSam: I know, I know. My heart says beach, but I looked at prices yesterday and honestly, I got a shock. Everything on the coast doubles in June, and half the hotels are already full.\nZoe: Seriously? Even that little town your colleague recommended?\nSam: Especially that one. It was in some travel magazine last month, and now everyone's going. The only rooms left are the expensive ones with sea views.\nZoe: Hmm. What about the mountains, then? My cousin stayed in a wooden cabin near Pine Lake last summer and said it was really cheap — but only because they booked early.\nSam: June is early for the mountains, though, isn't it? The busy season up there is July and August, when schools finish.\nZoe: Exactly, so we'd miss the crowds and the high prices. And it's cooler up there, which suits me — I burn after ten minutes in the sun.\nSam: True. And let's be honest, I can barely swim anyway. I mostly sit under an umbrella guarding the bags.\nZoe: Ha! So why have we been dreaming about beaches? Right, mountains it is. Cabins, walking, that lake.\nSam: One problem: getting there. The nearest station is miles from Pine Lake.\nZoe: Already solved. My cousin said she'd lend us her car for the week if we pay for the petrol. She owes me a favour anyway.\nSam: Then we're actually doing this. Booking website, here we come.",
    questions: [
      { q: "Why has Sam changed his mind about a beach holiday?", options: ["He dislikes hot weather.", "Coastal prices are very high in June.", "His colleague had a bad experience.", "The beaches are too far away."], answer: 1, explanation: "Sam says prices on the coast double in June and half the hotels are already full, which shocked him." },
      { q: "Why is the small coastal town so busy now?", options: ["It appeared in a travel magazine.", "A new hotel opened there.", "It has the warmest sea in June.", "A festival takes place there."], answer: 0, explanation: "The town 'was in some travel magazine last month, and now everyone's going', so only expensive rooms remain." },
      { q: "Why does June suit a mountain holiday, according to Zoe?", options: ["The lake is warmest then.", "The cabins close in July.", "It is before the busy school holiday season.", "Her cousin will be there in June."], answer: 2, explanation: "The busy season in the mountains is July and August, so in June 'we'd miss the crowds and the high prices'." },
      { q: "What does Sam admit about himself?", options: ["He cannot swim very well.", "He gets sunburnt easily.", "He is afraid of mountain roads.", "He has never booked a holiday."], answer: 0, explanation: "Sam admits 'I can barely swim anyway' and usually sits under an umbrella guarding the bags." },
      { q: "How will they travel to Pine Lake?", options: ["By train to the nearest station.", "In a hire car from the airport.", "In Zoe's cousin's car.", "By bus with Sam's colleague."], answer: 2, explanation: "Zoe's cousin 'said she'd lend us her car for the week if we pay for the petrol', solving the transport problem." }
    ] },
  { id: "p-lis3-05", title: "Podcast: How Running Fixed My Mornings", kind: "monologue",
    script: "Welcome back to Everyday Changes, the show about small habits with big results. I'm Jon, and today I want to talk about how I became a runner — because if you'd told me three years ago that I'd run before breakfast, I would have laughed at you. Here's the surprising part: I didn't start running to get fit or to lose weight, which is what everyone assumes. I started because I couldn't sleep. I was waking up at three in the morning, staring at the ceiling, worrying about work. My doctor suggested more exercise during the day, and running was the only sport that needed no team, no booking and no equipment except shoes. My first week was honestly embarrassing. I planned to run for twenty minutes and managed five before I had to stop, breathing like an old vacuum cleaner. But here's what I learned: five minutes is fine. The next week it was seven, then ten. After two months I could run for half an hour without stopping, and — this is the point — I was sleeping through the night for the first time in years. Then a friend took me to one of those free Saturday morning group runs in the park. I expected serious athletes; instead I found people of every age and speed, including a man who walks the whole route with his dog. Nobody cares how fast you are. If you take one thing from today's episode, let it be this: don't buy fancy watches or special clothes at the start. Spend your money on one thing only — proper running shoes fitted at a real shop. Your knees will thank you for years.",
    questions: [
      { q: "Why did Jon originally take up running?", options: ["He wanted to lose weight.", "He was sleeping badly.", "His friend invited him to a race.", "His doctor said his heart was weak."], answer: 1, explanation: "He couldn't sleep and was waking at three in the morning; his doctor suggested more exercise during the day." },
      { q: "Why did running suit Jon better than other sports?", options: ["It needed no team, booking or special equipment.", "He had been good at it at school.", "It could be done indoors in winter.", "His friends were all runners already."], answer: 0, explanation: "Running 'needed no team, no booking and no equipment except shoes', unlike other sports." },
      { q: "What happened during his first week of running?", options: ["He ran for twenty minutes easily.", "He injured his knee badly.", "He could only run for five minutes.", "He gave up until the next year."], answer: 2, explanation: "He planned twenty minutes but 'managed five before I had to stop', though he improved week by week." },
      { q: "What surprised Jon about the Saturday group runs?", options: ["Everyone there was a serious athlete.", "Runners had to pay to take part.", "The route was longer than expected.", "People of all ages and speeds took part."], answer: 3, explanation: "He expected serious athletes but 'found people of every age and speed', including a man who walks with his dog." },
      { q: "What does Jon recommend spending money on?", options: ["Well-fitted running shoes.", "A fancy sports watch.", "Special running clothes.", "Membership of a running club."], answer: 0, explanation: "His advice is to spend money on 'proper running shoes fitted at a real shop' and nothing else at the start." }
    ] },
  { id: "p-lis3-06", title: "A Talk About Keeping Bees", kind: "monologue",
    script: "Thank you for inviting me to your garden club this evening. My name's Helen, and for the last six years I've kept bees at the bottom of a perfectly ordinary garden, so tonight I'd like to answer the questions people always ask me. The first is: how did you start? With one hive, one very old book, and a lot of nervousness. I'd wanted bees for years, but I only began after I joined my local beekeeping group, and honestly, that's the order I'd recommend — people first, bees second. The members let me help with their hives for a whole summer before I spent a single pound on my own equipment. The second question is always about the neighbours. Yes, mine were worried at the beginning. The lady next door imagined clouds of angry insects chasing her grandchildren. So I invited her to watch me open the hive one calm afternoon, from a safe distance, and she was amazed at how gentle it all was. These days she gets a jar of honey every autumn and calls them 'our bees'. Third: do I get stung? Rarely, and almost always when I'm careless — rushing, or skipping my gloves because it's hot. With proper clothing and slow movements, stings really aren't a big part of this hobby. And finally, people assume the honey is the point. It's lovely, of course, and one strong hive gives me more jars than my family can eat. But the real pleasure is quieter than that: sitting by the hive on a summer evening, just watching them come and go. It's better than television. If you're interested, please don't buy anything yet — come along to our group first. Visitors are always welcome.",
    questions: [
      { q: "How did Helen prepare before getting her own bees?", options: ["She read every book she could find.", "She helped group members with their hives.", "She took an online course.", "She worked on a honey farm."], answer: 1, explanation: "She joined the local beekeeping group and 'let me help with their hives for a whole summer' before buying equipment." },
      { q: "How did Helen deal with her worried neighbour?", options: ["She invited her to watch the hive being opened.", "She moved the hive to a farm.", "She built a tall fence between the gardens.", "She promised to keep only a few bees."], answer: 0, explanation: "She invited the neighbour 'to watch me open the hive one calm afternoon', and the neighbour was amazed how gentle it was." },
      { q: "When does Helen usually get stung?", options: ["When the weather is cold.", "When she opens the hive in the evening.", "When she is careless or rushing.", "When the bees are making honey."], answer: 2, explanation: "She is stung rarely and 'almost always when I'm careless — rushing, or skipping my gloves'." },
      { q: "What does Helen enjoy most about keeping bees?", options: ["Selling jars of honey.", "Quietly watching the bees at the hive.", "Winning prizes at shows.", "Teaching her family about insects."], answer: 1, explanation: "The honey is lovely, but 'the real pleasure' is 'sitting by the hive on a summer evening, just watching them'." },
      { q: "What does Helen advise interested listeners to do first?", options: ["Buy a hive while prices are low.", "Read an old beekeeping book.", "Plant flowers for the bees.", "Visit the local beekeeping group."], answer: 3, explanation: "She says 'don't buy anything yet — come along to our group first', repeating her 'people first, bees second' advice." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
