/* PET Prep extra bank: listening (week 4) */
(function () {
var BANK = [
  { id: "p-lis4-01", title: "Radio Interview: Sisters with a Jam Stall", kind: "dialogue",
    script: "Interviewer: If you've visited our town market recently, you've probably smelled the strawberries before you saw the stall. With me today is Ana Costa, who runs the Two Sisters jam stall with, of course, her sister. Ana, how did two students end up selling jam?\nAna: It started three summers ago, during the college holidays. Our mum has always made jam from the fruit in our garden — her mother's recipes, actually, from Portugal. That year the trees gave us so much fruit that we had jars everywhere. In the kitchen, under the beds, everywhere! So my sister said, why don't we take some to the market?\nInterviewer: And people liked it?\nAna: We sold out in two hours. We stood there with an empty table, looking at each other, thinking — maybe this is something.\nInterviewer: What's the hardest part of the business?\nAna: Everyone expects me to say making the jam, but that part is like therapy. Honestly, it's the market mornings. We get up at five to set up the stall, even in winter, even in the rain. My sister still can't talk before her second coffee.\nInterviewer: I hear some shops want to sell your jam now.\nAna: Yes, two food shops in the city have asked, and we've said yes to one. But we'll never give up the stall. At the market, people tell you directly what they think — which flavour to bring back, what their grandmother did differently. You can't get that from a shelf in a shop.",
    questions: [
      { q: "Where do the sisters' jam recipes come from?", options: ["A cookery course at college.", "Their grandmother in Portugal.", "A book they found at the market.", "A food shop in the city."], answer: 1, explanation: "The jam is made from 'her mother's recipes, actually, from Portugal' — their grandmother's recipes." },
      { q: "Why did they first take jam to the market?", options: ["They had far too many jars at home.", "Their mum needed money for the garden.", "A stall owner invited them.", "They wanted to leave college."], answer: 0, explanation: "The trees gave so much fruit that they had 'jars everywhere. In the kitchen, under the beds', so they tried the market." },
      { q: "What happened on their first market day?", options: ["It rained and nobody came.", "They forgot half the jars at home.", "They sold everything in two hours.", "They only sold a few jars."], answer: 2, explanation: "Ana says 'we sold out in two hours' and they stood looking at an empty table, realising the idea could work." },
      { q: "What does Ana find hardest about the business?", options: ["Cooking large amounts of jam.", "Talking to customers all day.", "Finding enough fruit in winter.", "Getting up very early on market days."], answer: 3, explanation: "She says making jam is 'like therapy'; the hard part is getting up at five to set up the stall in all weather." },
      { q: "Why will the sisters keep their market stall?", options: ["Shops take too much of the money.", "Customers give them direct opinions there.", "The market is cheaper than a shop.", "Their mother works at the market too."], answer: 1, explanation: "At the market 'people tell you directly what they think', which they can't get from a shop shelf." }
    ] },
  { id: "p-lis4-02", title: "Announcement: Museum Evening Opening This Friday", kind: "monologue",
    script: "Good afternoon, visitors. May I have your attention for a short announcement about this Friday? This Friday the museum will stay open late for our monthly evening event, closing at ten o'clock instead of the usual five thirty. Even better, entry will be completely free after seven o'clock, so do tell your friends and family. There are a few things to know before you plan your visit. First, the top-floor gallery, which normally shows our collection of old maps, will unfortunately be closed all evening while the lights up there are repaired. Everything else, including the dinosaur hall and the new ocean room, will be open as normal. Second, at eight o'clock in the main hall, Professor Lena Marsh will give a talk called Secrets Under the Sea, about the strange creatures that live in the deepest parts of the ocean. The talk is free, but seats are limited, so you will need a ticket. Tickets are available from the front desk from five o'clock onwards — one per person, and please don't ask for extras for absent friends, because we always run out. Third, the museum café will be open all evening, but in the evenings it serves cold food only: sandwiches, salads and cakes. If you would like a hot meal, there are several restaurants on the square outside. Finally, please note that the museum shop closes at eight as usual, so buy your postcards early. We look forward to seeing you on Friday night.",
    questions: [
      { q: "What is special about this Friday at the museum?", options: ["A new dinosaur hall opens.", "It stays open late with free evening entry.", "All tickets are half price.", "The old maps return to display."], answer: 1, explanation: "The museum closes at ten instead of five thirty, and 'entry will be completely free after seven o'clock'." },
      { q: "Why is the top-floor gallery closed on Friday evening?", options: ["Its lights are being repaired.", "A private event is happening there.", "The maps are being cleaned.", "It is too dark to see the maps."], answer: 0, explanation: "The top-floor gallery 'will unfortunately be closed all evening while the lights up there are repaired'." },
      { q: "What must people do to attend the eight o'clock talk?", options: ["Pay at the main hall door.", "Book on the museum website.", "Get a ticket from the front desk.", "Arrive before five o'clock."], answer: 2, explanation: "The talk is free but seats are limited, so people need a ticket 'from the front desk from five o'clock onwards'." },
      { q: "What does the café offer during the evening?", options: ["Only cold food such as sandwiches.", "A special hot dinner menu.", "Free drinks with every meal.", "Nothing, because it closes at five."], answer: 0, explanation: "In the evenings the café 'serves cold food only: sandwiches, salads and cakes'; hot meals are available outside." },
      { q: "What should visitors remember about the museum shop?", options: ["It sells talk tickets.", "It closes at eight o'clock.", "It moves to the main hall.", "It stays open until ten."], answer: 1, explanation: "The announcement says 'the museum shop closes at eight as usual, so buy your postcards early'." }
    ] },
  { id: "p-lis4-03", title: "Phone Message: About the Tent", kind: "monologue",
    script: "Hey Chris, it's Ryan, returning your call about the camping trip. Sorry I missed you — I was at football practice. So, the answer is yes, of course you can borrow the tent! It's the big green one, sleeps four people easily, and it kept us completely dry that weekend when it rained non-stop, remember? There are just a few things you need to know, so grab a pen. First, the tent isn't at my place any more. My brother borrowed it last month, so it's at his house on Mill Road, number fifteen — the one with the red door. He says you can collect it on Thursday evening after six, but not Friday, because he's driving to the airport that night. So Thursday, okay? Second, small confession: two of the metal pegs went missing on our last trip. The tent still stands fine, but if it's windy where you're going, you should buy a few spare pegs. Any outdoor shop sells them, they cost almost nothing, and honestly it's worth it for the peace of mind. Third — and don't laugh — while you're getting things from people, you still have my blue sleeping bag from last summer's festival. I completely forgot about it until Mum asked. Could you bring it when you come back from the trip? No rush, but she keeps asking. Right, I think that's everything. Text my brother before Thursday so he knows when to expect you — I'll send you his number. Have an amazing trip, and take photos of the lake for me. Bye!",
    questions: [
      { q: "Why is the tent at Ryan's brother's house?", options: ["Ryan's flat is too small to store it.", "His brother borrowed it recently.", "It is being cleaned there.", "His brother bought it from Ryan."], answer: 1, explanation: "Ryan says 'my brother borrowed it last month, so it's at his house on Mill Road'." },
      { q: "Why can't Chris collect the tent on Friday?", options: ["The brother is driving to the airport.", "Ryan has football practice then.", "The house will be empty all day.", "The tent will still be wet."], answer: 0, explanation: "Collection must be Thursday after six, 'but not Friday, because he's driving to the airport that night'." },
      { q: "What does Ryan suggest buying before the trip?", options: ["A bigger sleeping bag.", "A new green tent.", "Some spare metal pegs.", "A map of the lake."], answer: 2, explanation: "Two pegs went missing, so 'if it's windy where you're going, you should buy a few spare pegs'." },
      { q: "What does Ryan ask Chris to return?", options: ["A blue sleeping bag.", "Some camping chairs.", "His football boots.", "A pair of walking shoes."], answer: 0, explanation: "Ryan says 'you still have my blue sleeping bag from last summer's festival' and asks him to bring it back." },
      { q: "What should Chris do before Thursday?", options: ["Phone Ryan's mum about the trip.", "Send a message to Ryan's brother.", "Take photos of the tent.", "Pay Ryan for the missing pegs."], answer: 1, explanation: "Ryan tells Chris to 'text my brother before Thursday so he knows when to expect you'." }
    ] }
,
  { id: "p-lis4-04", title: "Setting Up a Study Group", kind: "dialogue",
    script: "Mia: Ali, wait a second. The history exam is in three weeks and I'm starting to panic. A few of us are setting up a study group — do you want in?\nAli: Definitely, I need it. My notes are a mess. Who else is coming?\nMia: Priya and Josh so far. Five would be perfect — with more people it just turns into chatting.\nAli: True. Where would we meet? The canteen is way too noisy.\nMia: I was thinking the small rooms at the library. They're free for students, but here's the catch: you have to book them at least two days ahead, online. They go fast around exam time.\nAli: Okay, so we plan ahead. How often are we talking? Some people do these groups every single day, and honestly I can't manage that with my job.\nMia: No, every day is too much — you stop taking it seriously. I was thinking twice a week. How about Mondays and Fridays?\nAli: Fridays are impossible for me, I work at the restaurant every Friday evening. Could we do Tuesdays and Thursdays instead?\nMia: Fine by me, I'll check with the others, but I think they're free then. Now, the important part — how we actually study. My cousin's group just read the textbook together in silence, which was pointless.\nMia: So here's my idea: each of us prepares one topic properly and teaches it to the rest. You remember things much better when you have to explain them.\nAli: I like it. Can I take the Industrial Revolution? It's the only part I actually understand.\nMia: It's yours. And let's share all our notes in one online folder, so nobody's asking for photos of pages the night before the exam.",
    questions: [
      { q: "Why does Mia want to keep the group small?", options: ["The library rooms hold five people only.", "Bigger groups turn into chatting.", "Only five students take history.", "Josh doesn't like large groups."], answer: 1, explanation: "Mia says five is perfect because 'with more people it just turns into chatting'." },
      { q: "What is the problem with the library rooms?", options: ["They must be booked two days ahead.", "They cost money for students.", "They are as noisy as the canteen.", "They close before the evening."], answer: 0, explanation: "The rooms are free, 'but you have to book them at least two days ahead, online', and they go fast at exam time." },
      { q: "Why does Ali reject meeting on Fridays?", options: ["He visits his cousin then.", "He plays football on Fridays.", "He works at a restaurant that evening.", "He thinks Fridays are for resting."], answer: 2, explanation: "Ali says 'I work at the restaurant every Friday evening', so they change to Tuesdays and Thursdays." },
      { q: "What does Mia say about her cousin's study group?", options: ["It met far too often.", "Reading silently together achieved nothing.", "It helped her cousin pass easily.", "It was too big to organise."], answer: 1, explanation: "Her cousin's group 'just read the textbook together in silence, which was pointless' — Mia wants a better method." },
      { q: "How will the group study together?", options: ["Each member will teach one topic to the others.", "They will do old exams in silence.", "A teacher will join them twice a week.", "They will watch history videos together."], answer: 0, explanation: "Mia's idea is that 'each of us prepares one topic properly and teaches it to the rest', because explaining helps memory." }
    ] },
  { id: "p-lis4-05", title: "Podcast: My Year Without a Car", kind: "monologue",
    script: "Hello and welcome to Simple Living. I'm Marta, and this week marks exactly one year since I sold my car, so today I'm answering the question everyone keeps asking me: do I regret it? Short answer — no. But let me give you the honest, longer answer too. I sold the car when I moved to the city for work. Parking near my new flat cost a fortune, and I noticed the car sitting unused for days at a time. So one Saturday, I just did it. The first thing I noticed was the money. It wasn't only the petrol — it was the insurance, the repairs, the parking, all of it, gone. I worked it out last month, and I've saved enough this year to pay for my summer holiday twice over. The second surprise was time. I expected to be slower everywhere, but for short trips across the city, my bicycle is actually faster than driving, because I go straight past the traffic jams. I'm fitter than I've been in years without ever visiting a gym. Now, the honest part: it isn't all easy. The hardest thing is visiting my parents. They live in a small village with one bus a day — one! — and it leaves at seven in the morning. These days I take the train to the nearest town and my dad picks me up from the station. It works, but I can't just appear for a surprise visit any more, and I do miss that. So, would I recommend it? Yes — but don't be dramatic about it. Try living without your car for one month before you sell anything. You'll find out very quickly what you really need.",
    questions: [
      { q: "Why did Marta decide to sell her car?", options: ["It was old and kept breaking down.", "Parking was expensive and the car sat unused.", "Her new job gave her a bicycle.", "Her parents asked her to sell it."], answer: 1, explanation: "After moving to the city, 'parking near my new flat cost a fortune' and the car sat unused for days." },
      { q: "What does Marta say about the money she has saved?", options: ["It only covers her train tickets.", "It is less than she expected.", "It would pay for her holiday twice.", "She spends it all on her bicycle."], answer: 2, explanation: "She has saved 'enough this year to pay for my summer holiday twice over' from petrol, insurance, repairs and parking." },
      { q: "Why is cycling often faster than driving for her?", options: ["She avoids the traffic jams.", "Her office is next to her flat.", "The city has no cars in the centre.", "She cycles on the motorway."], answer: 0, explanation: "For short city trips the bicycle is faster 'because I go straight past the traffic jams'." },
      { q: "What is the most difficult part of life without a car?", options: ["Carrying her shopping home.", "Getting to work in the rain.", "Paying for expensive train tickets.", "Visiting her parents' village."], answer: 3, explanation: "The hardest thing is visiting her parents, whose village has only 'one bus a day' leaving at seven in the morning." },
      { q: "What does Marta advise listeners to do?", options: ["Sell their car as soon as possible.", "Try a month without their car first.", "Move closer to their family.", "Buy a bicycle before deciding."], answer: 1, explanation: "Her advice is 'try living without your car for one month before you sell anything' to learn what you really need." }
    ] },
  { id: "p-lis4-06", title: "Talking About Last Night's Concert", kind: "dialogue",
    script: "Ella: So? Be honest. Was the concert worth all the money?\nJack: Mostly, yes. Though the first twenty minutes nearly ruined it. Something was wrong with the sound — the guitars were so loud you couldn't hear her voice at all. People around us were actually covering their ears.\nElla: Oh no. Did they fix it?\nJack: Eventually. Some engineer ran back and forth looking stressed, and then suddenly, from the third song, everything was perfect. And Ella, her voice — I'm telling you, she sounds better live than on the recordings. I didn't think that was possible.\nElla: Everyone says that about her! What did she open with?\nJack: That song about the lighthouse, the slow one. Not what I expected — usually they start with something fast, don't they? But it worked. The whole arena went silent, phones down, everything.\nElla: I'm so jealous. Did you get me a T-shirt? You promised you'd try.\nJack: I tried, I really did. But the queue for T-shirts and posters went all the way down the stairs and out the door. We would have missed half the show standing in it. So no — I bought nothing, sorry.\nElla: Ugh. Fine, you're forgiven. Only because you sent me that video.\nJack: There's good news, though. On the way out, there were signs saying she's coming back next spring — a bigger tour, two nights in our city this time.\nElla: Two nights! We're going together, no excuses.\nJack: Already ahead of you. I signed up for the email list at the door, so we'll hear the moment tickets go on sale. They say last time everything sold out in a day.",
    questions: [
      { q: "What was wrong at the start of the concert?", options: ["The singer arrived on stage late.", "The guitars drowned out the singer's voice.", "The lights kept going out.", "The first songs were too slow."], answer: 1, explanation: "For the first twenty minutes 'the guitars were so loud you couldn't hear her voice at all'." },
      { q: "What does Jack say about the singer's voice?", options: ["It sounds better live than recorded.", "It was weaker than he expected.", "It was too quiet all evening.", "It sounded exactly like the albums."], answer: 0, explanation: "Jack says 'she sounds better live than on the recordings. I didn't think that was possible'." },
      { q: "Why was the opening song surprising?", options: ["It was a brand new song.", "The whole arena sang it together.", "It was slow rather than fast.", "She sang it without music."], answer: 2, explanation: "She opened with 'the slow one' about the lighthouse, when 'usually they start with something fast'." },
      { q: "Why didn't Jack buy Ella a T-shirt?", options: ["They had sold out of her size.", "The queue was extremely long.", "He forgot his money at home.", "The T-shirts were too expensive."], answer: 1, explanation: "The queue 'went all the way down the stairs and out the door', and he would have missed half the show." },
      { q: "What has Jack done about the next tour?", options: ["Bought two tickets already.", "Booked a hotel for the spring.", "Asked the band for free passes.", "Joined an email list for ticket news."], answer: 3, explanation: "He 'signed up for the email list at the door' so they'll know the moment tickets go on sale." }
    ] }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.LISTENING = (window.LISTENING || []).concat(BANK);
})();
