/* PET Prep bank: Reading multiple choice (B1) — wave 8 */
(function () {
var BANK = [
  {
    id: "pet-rmc8-01",
    title: "The Café With No Menu",
    text: "There is a small café on Wilton Road that has never printed a menu. When you sit down, the owner, Nadia Okoye, comes over and asks you two questions: what you feel like eating, and whether there is anything you cannot eat. Then she disappears into the kitchen and brings you something twenty minutes later.\n\nNadia opened the café four years ago after working in restaurant kitchens for most of her twenties. She had grown tired of throwing food away. In a normal restaurant, she explains, you must have every item on the menu ready every day, even the dish that only three people order in a week. The rest goes in the bin on Sunday night.\n\nSo she tried something different. Every morning she goes to the market at six and buys whatever looks best and costs least, and that is what the café serves that day. Nothing is decided in advance. Some days there are six dishes and some days there are two.\n\nCustomers were confused at first. A few walked out. But most came back, and now the café is full every lunchtime, mainly with people who work nearby and who say the hardest part of lunch used to be deciding. Nadia says she throws away about a bag of food a month, which is less than most kitchens throw away in a day.\n\nThe system is not perfect. Nadia cannot take large bookings, because she does not know how much food she will have, and she has to turn away groups of more than eight. She also works longer hours than she planned, since the shopping alone takes two hours. But she says she would not go back. Every plate that leaves her kitchen is something she chose that morning, and almost every one of them comes back empty.",
    questions: [
      { q: "What does Nadia ask customers when they sit down?", options: ["What they feel like eating and what they cannot eat","How much they want to spend","How long they can wait","Which dish they want from a list"], answer: 0, explanation: "'When you sit down, the owner, Nadia Okoye, comes over and asks you two questions: what you feel like eating, and whether there is anything you cannot eat.'" },
      { q: "Why did Nadia stop working in ordinary restaurant kitchens?", options: ["She wanted to travel","She disliked wasting food","The hours were too long","She was not paid enough"], answer: 1, explanation: "'She had grown tired of throwing food away.'" },
      { q: "According to Nadia, what is the problem with a printed menu?", options: ["Customers take too long to read it","It cannot be changed in the evening","Everything must be ready daily, even unpopular dishes","It costs a lot to print"], answer: 2, explanation: "'In a normal restaurant, she explains, you must have every item on the menu ready every day, even the dish that only three people order in a week.'" },
      { q: "How does Nadia decide what to cook each day?", options: ["She follows a weekly plan","She cooks what was popular the day before","She asks her regular customers","She buys whatever is best and cheapest at the market"], answer: 3, explanation: "'Every morning she goes to the market at six and buys whatever looks best and costs least, and that is what the café serves that day.'" },
      { q: "How did customers react at the beginning?", options: ["Some were confused and a few left","They complained about the prices","They asked for a printed menu","They were all delighted"], answer: 0, explanation: "'Customers were confused at first.'" },
      { q: "What difficulty does the café still have?", options: ["The market is closing down","It cannot accept large group bookings","It has too few customers at lunchtime","The food arrives cold"], answer: 1, explanation: "'Nadia cannot take large bookings, because she does not know how much food she will have, and she has to turn away groups of more than eight.'" }
    ]
  },
  {
    id: "pet-rmc8-02",
    title: "My Grandfather's Weather Diary",
    text: "When my grandfather died last spring, we found forty-one notebooks in a box under his bed. Each one contained a single line for every day of a year: the temperature at eight in the morning, the direction of the wind, and a few words about the sky. He had written one every day since 1983, and he had never mentioned it to anybody in the family.\n\nMy mother wanted to throw them away. They were not a diary in the usual sense; there was nothing personal in them at all, no names and no events. Even the day my grandmother died has only the words cold, still, low cloud. It was my cousin Farida who suggested we show them to somebody before deciding.\n\nShe took three of the notebooks to the university, expecting to be politely thanked and sent home. Instead, a scientist called Dr Ellis spent an hour looking at them and then asked whether there were any more. Records like these, he said, are surprisingly rare and genuinely useful. Official weather stations are often outside towns, while my grandfather's readings came from a garden in the middle of one, and comparing the two shows how much warmer a town becomes as it grows.\n\nThe notebooks are now in the university library, and the readings from all forty-one years have been typed into a database by two students. Dr Ellis told us that the years between 1983 and 1996 were the most valuable, because there was no automatic station in our area then.\n\nI think about this often. My grandfather was not a scientist and he never expected anyone to read a word of it. He simply went out at the same time every morning for four decades and wrote down what he saw. It turned out to be worth more than anything else he left behind.",
    questions: [
      { q: "What did the family find under the grandfather's bed?", options: ["Money he had saved","Letters from his wife","Forty-one notebooks of weather records","Photographs of the town"], answer: 2, explanation: "'When my grandfather died last spring, we found forty-one notebooks in a box under his bed.'" },
      { q: "What did each daily entry contain?", options: ["Only the temperature","A long description of his day","News from the town","Temperature, wind direction and a note on the sky"], answer: 3, explanation: "'Each one contained a single line for every day of a year: the temperature at eight in the morning, the direction of the wind, and a few words about the sky.'" },
      { q: "Why did the writer's mother want to get rid of the notebooks?", options: ["They contained nothing personal", "They were damaged by water", "There was no room in the house", "She had never liked her father"], answer: 0, explanation: "'They were not a diary in the usual sense; there was nothing personal in them at all, no names and no events.'" },
      { q: "What did Farida expect to happen at the university?", options: ["That the notebooks would be bought", "That they would be thanked and sent home", "That a scientist would visit the house", "That the notebooks would be lost"], answer: 1, explanation: "'She took three of the notebooks to the university, expecting to be politely thanked and sent home.'" },
      { q: "Why are the grandfather's readings useful to scientists?", options: ["They were taken by a trained observer", "They cover a longer period than any other record", "They were taken in a town centre rather than outside it", "They include photographs of the sky"], answer: 2, explanation: "'Official weather stations are often outside towns, while my grandfather's readings came from a garden in the middle of one, and comparing the two shows how much warmer a town becomes as it grows.'" },
      { q: "Which period does Dr Ellis consider most valuable?", options: ["The 1970s","The years after 2000","The most recent ten years","1983 to 1996"], answer: 3, explanation: "'Dr Ellis told us that the years between 1983 and 1996 were the most valuable, because there was no automatic station in our area then.'" }
    ]
  },
  {
    id: "pet-rmc8-03",
    title: "Saving the Swimming Pool",
    text: "The swimming pool in Ashcott was built in 1962 and was due to close on the last day of March. The council said it was losing eleven thousand pounds a month and that the roof would need replacing within three years. Nobody argued with the numbers. What the campaign to save it argued was that the numbers were not the whole story.\n\nThe campaign began with a woman called Priya Raman, who teaches swimming to adults who never learned as children. She had eighty students, most of them over fifty. When she heard about the closure she wrote to the local paper, and the letter was read by far more people than she expected.\n\nWithin a fortnight there were six hundred names on a petition. But the group quickly realised that a petition alone would change nothing, because the council's problem was money rather than opinion. So they did something unusual: they asked to see the pool's accounts, and they spent two months going through them with the help of a retired accountant.\n\nWhat they found was that the pool was open only thirty-one hours a week and closed entirely on Sunday afternoons, the busiest possible time. The building also paid to heat water for a small café that had shut in 2019. The group's report suggested nine changes, none of them large.\n\nThe council agreed to a trial year. The pool now opens fifty hours a week, the café space has been rented to a physiotherapist, and schools use the water on weekday mornings when it used to be empty. In the first eight months, the loss fell from eleven thousand pounds a month to under two thousand.\n\nThe roof still needs replacing, and that argument is still to come. But Priya says the important thing was refusing to accept that a closing building was already closed.",
    questions: [
      { q: "Why did the council plan to close the pool?", options: ["It was losing money and needed a new roof","A newer pool had opened nearby","The water was unsafe","Too few people were swimming"], answer: 0, explanation: "'The council said it was losing eleven thousand pounds a month and that the roof would need replacing within three years.'" },
      { q: "Who started the campaign?", options: ["A retired accountant","A swimming teacher","A member of the council","A local newspaper editor"], answer: 1, explanation: "'The campaign began with a woman called Priya Raman, who teaches swimming to adults who never learned as children.'" },
      { q: "Why did the group decide a petition was not enough?", options: ["It arrived too late","Not enough people signed it","The council's problem was money, not opinion","The council refused to accept it"], answer: 2, explanation: "'But the group quickly realised that a petition alone would change nothing, because the council's problem was money rather than opinion.'" },
      { q: "What did the group discover about the pool's opening hours?", options: ["It opened earlier than any other pool","It was open every day until ten","Its hours had never been recorded","It closed at the busiest time of the week"], answer: 3, explanation: "'What they found was that the pool was open only thirty-one hours a week and closed entirely on Sunday afternoons, the busiest possible time.'" },
      { q: "What is the old café space used for now?", options: ["It has been rented to a physiotherapist","It is still empty","Storage for equipment","A room for swimming lessons"], answer: 0, explanation: "'The pool now opens fifty hours a week, the café space has been rented to a physiotherapist, and schools use the water on weekday mornings when it used to be empty.'" },
      { q: "What does Priya say mattered most?", options: ["Getting six hundred signatures", "Not treating the pool as already closed", "Proving the council wrong about the roof", "Finding a retired accountant"], answer: 1, explanation: "'But Priya says the important thing was refusing to accept that a closing building was already closed.'" }
    ]
  },
  {
    id: "pet-rmc8-04",
    title: "Learning to Ride at Forty",
    text: "I had wanted to ride a horse since I was six years old, and I finally booked my first lesson three weeks after my fortieth birthday. I had imagined it many times. In none of those imaginings was I as frightened as I actually was.\n\nThe stable was twenty minutes outside town, and my teacher, a woman called Bridget, met me at the gate. The first thing she told me was that I would not be riding at all that day. Instead I spent an hour leading a large brown horse called Pepper around a field, learning where to stand, how to hold the rope, and what a horse does with its ears when it is nervous. I was disappointed and I said so. Bridget said that people who get on too early spend a year being afraid.\n\nShe was right, although I only understood it later. By my third lesson I could tell from ten metres away what sort of mood Pepper was in, and when I finally sat on him in week four, it did not feel like sitting on a machine I could not control.\n\nWhat surprised me most was how tiring it is. After forty minutes I could barely walk to the car, and my legs hurt for two days. Riding looks still from the outside, but the rider is working constantly, making tiny corrections that nobody watching can see.\n\nI am now in my second year. I am not good, and I will never compete, but I can take Pepper out along the lanes on a Sunday morning without anyone else there, which is all I ever actually wanted.\n\nThe strangest part is that the thing I feared for thirty-four years turned out to be difficult for reasons I had never once considered.",
    questions: [
      { q: "When did the writer have a first riding lesson?", options: ["Two years ago","Just before turning forty","Three weeks after turning forty","At the age of six"], answer: 2, explanation: "'I had wanted to ride a horse since I was six years old, and I finally booked my first lesson three weeks after my fortieth birthday.'" },
      { q: "What happened during the first lesson?", options: ["Bridget was late","The writer rode Pepper around the field","The lesson was cancelled","The writer led a horse and learned about its behaviour"], answer: 3, explanation: "'Instead I spent an hour leading a large brown horse called Pepper around a field, learning where to stand, how to hold the rope, and what a horse does with its ears when it is nervous.'" },
      { q: "How did the writer feel about the first lesson at the time?", options: ["Disappointed", "Relieved", "Delighted", "Bored"], answer: 0, explanation: "'I was disappointed and I said so.'" },
      { q: "Why does Bridget make beginners wait before riding?", options: ["The horses need to rest", "Those who start too early stay frightened for a long time", "It is a rule at the stable", "It costs less"], answer: 1, explanation: "'Bridget said that people who get on too early spend a year being afraid.'" },
      { q: "What surprised the writer most about riding?", options: ["How expensive it is", "How quickly it is learned", "How physically tiring it is", "How quiet horses are"], answer: 2, explanation: "'What surprised me most was how tiring it is.'" },
      { q: "What does the writer want from riding now?", options: ["To compete one day", "To teach other beginners", "To buy a horse", "To ride alone in the lanes on Sundays"], answer: 3, explanation: "'I am not good, and I will never compete, but I can take Pepper out along the lanes on a Sunday morning without anyone else there, which is all I ever actually wanted.'" }
    ]
  },
  {
    id: "pet-rmc8-05",
    title: "The Postcard That Took Fifty Years",
    text: "In October a postcard was delivered to a house in Sandhill Lane. It showed a beach in Cornwall, it was addressed to a Mrs D. Hartley, and it had been posted in August 1974.\n\nThe woman who lives in the house now is called Sam Whitlock, and she has lived there for six years. She had never heard of Mrs Hartley. The card said very little: the weather was good, the children had been in the sea twice, and they would be home on the Tuesday. It was signed simply Joan.\n\nSam's first thought was that somebody had found the card and posted it as a joke, but the post office said this was unlikely. Cards do occasionally reappear after decades, usually because they have fallen behind machinery in a sorting office and are found during building work. A card from 1974 is unusual but not unheard of.\n\nSam could have thrown it away. Instead she posted a photograph of it in a local group online, and within a day somebody recognised the handwriting. Joan had been her aunt. Mrs Hartley, it turned out, was Joan's sister, and she had lived at the house until 1988. Both women died in the 1990s.\n\nWhat nobody expected was that Joan's daughter, who had been one of the children in the sea, was still alive and living nine miles away. She was seventy-three. Sam drove over one afternoon and gave her the card.\n\nShe told Sam afterwards that she had no photographs at all from that holiday, and almost no memory of it, and that she had read her mother's handwriting perhaps twice in thirty years. The card is now in a frame in her hallway. It is, she says, the only letter she has ever received that took fifty years to arrive.",
    questions: [
      { q: "What was unusual about the postcard?", options: ["It had been posted in 1974","It was written in another language","It showed a place that no longer exists","It had no address on it"], answer: 0, explanation: "'It showed a beach in Cornwall, it was addressed to a Mrs D. Hartley, and it had been posted in August 1974.'" },
      { q: "What did Sam think at first?", options: ["That it was very valuable","That it was a joke","That it was addressed to a neighbour","That it had been sent by mistake from abroad"], answer: 1, explanation: "'Sam's first thought was that somebody had found the card and posted it as a joke, but the post office said this was unlikely.'" },
      { q: "According to the post office, why do old cards sometimes reappear?", options: ["They are kept and released after many years", "They are returned by other countries", "They fall behind machinery and are found later", "They are discovered in old post boxes"], answer: 2, explanation: "'Cards do occasionally reappear after decades, usually because they have fallen behind machinery in a sorting office and are found during building work.'" },
      { q: "How was the writer of the card identified?", options: ["The post office kept a record","Her name was printed on it","A neighbour remembered her","Somebody online recognised the handwriting"], answer: 3, explanation: "'Instead she posted a photograph of it in a local group online, and within a day somebody recognised the handwriting.'" },
      { q: "Who finally received the postcard?", options: ["Joan's daughter","Sam kept it herself","Mrs Hartley's son","A local museum"], answer: 0, explanation: "'Sam drove over one afternoon and gave her the card.'" },
      { q: "Why did the card mean so much to the woman who received it?", options: ["It was worth a lot of money", "She had nothing else from that holiday", "It proved where her family had lived", "She had written it herself"], answer: 1, explanation: "'She told Sam afterwards that she had no photographs at all from that holiday, and almost no memory of it, and that she had read her mother's handwriting perhaps twice in thirty years.'" }
    ]
  },
  {
    id: "pet-rmc8-06",
    title: "Working at the Ice Rink",
    text: "My Saturday job for two years was at the ice rink on Carter Street, and people always assume it involved skating. It did not. I worked in the boot room, and in two years I skated exactly four times.\n\nThe boot room is a long counter with two thousand pairs of skates behind it in wooden racks. A session takes ninety minutes and about two hundred people come to each one, which means that in the ten minutes before a session begins you are handing out roughly twenty pairs a minute. You learn to guess a size from a person's height before they reach the counter, because asking and then walking to the rack takes eleven seconds and you do not have eleven seconds.\n\nThe part nobody warns you about is the questions. Skaters do not only want boots. They want to know whether the rink is cold, whether their four-year-old will manage, where the toilets are, and whether we can look after a bag, a coat, a cake and once a small dog. My manager, Ray, used to say that we were not renting boots at all; we were the only people in the building that anyone could find.\n\nBy my second winter I could do the job without thinking, and that was when it became interesting. I started watching who came back. There were people who came every single week for the whole season and never once fell over, and there were people who fell nine times in an hour and laughed and never returned. The ones who lasted were almost always the ones who had come with somebody else.\n\nI left when I went away to study. Ray still sends me a message every October when the rink reopens, and I still know my own skate size in three different makes, which has never once been useful.",
    questions: [
      { q: "What did the writer's job involve?", options: ["Selling tickets","Teaching beginners to skate","Handing out skating boots","Cleaning the ice"], answer: 2, explanation: "'I worked in the boot room, and in two years I skated exactly four times.'" },
      { q: "Why does the writer guess people's sizes?", options: ["Because the sizes are unusual","Because customers often do not know their size","Because the racks are badly organised","Because there is no time to ask"], answer: 3, explanation: "'You learn to guess a size from a person's height before they reach the counter, because asking and then walking to the rack takes eleven seconds and you do not have eleven seconds.'" },
      { q: "What was the writer not prepared for?", options: ["The number of questions from customers", "The cold in the building", "Working alone", "The weight of the boots"], answer: 0, explanation: "'The part nobody warns you about is the questions.'" },
      { q: "What did Ray say about the boot room staff?", options: ["That they worked harder than anyone", "That they were the only staff customers could find", "That they should skate more often", "That they were paid too little"], answer: 1, explanation: "'My manager, Ray, used to say that we were not renting boots at all; we were the only people in the building that anyone could find.'" },
      { q: "What did the writer notice about the skaters who kept coming back?", options: ["They were mostly children", "They rarely fell over", "They usually came with someone else", "They brought their own boots"], answer: 2, explanation: "'The ones who lasted were almost always the ones who had come with somebody else.'" },
      { q: "Why did the writer leave the job?", options: ["There was an argument with Ray","The hours changed","The rink closed","To go away and study"], answer: 3, explanation: "'I left when I went away to study.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
