/* PET Prep bank: Reading multiple choice (B1) — wave 12 */
(function () {
var BANK = [
  {
    id: "pet-rmc12-01",
    title: "The Hotel Run by Students",
    text: "The Kilmarsh Hotel has thirty-one bedrooms, a restaurant and a bar, and almost everybody working there is between sixteen and nineteen years old. It is a real hotel: guests pay ordinary prices, complain when the shower is cold, and leave reviews online like anywhere else.\n\nThe hotel belongs to the local college, which bought the building in 2009 after years of sending students on work placements that varied enormously in quality. Some employers taught students a great deal. Others, the head of department Nia Cadwallader admits, used them as free labour for three weeks and taught them nothing at all.\n\nStudents work in every department and change roles every six weeks, which is the part that makes the hotel unusual and also the part that costs money. A commercial hotel would never move a competent receptionist to the kitchen, but a student who has only worked at reception has learned one job rather than an industry.\n\nGuests are told before booking, and about one in fifteen chooses to book elsewhere. The rest, according to the hotel's own surveys, rate it slightly higher than comparable hotels nearby. Nia thinks she knows why. Students have not yet learned to hide behind procedure, so when something goes wrong they tend to deal with the person in front of them rather than explaining a policy.\n\nThe hotel does not make a profit and is not expected to. It costs the college about seventy thousand pounds a year more than it earns, which is less than the department spent on visits to placements before 2009.\n\nWhat pleases Nia most is a number she did not plan to collect. Eleven of the current staff, including the general manager, studied at the hotel themselves and came back to work in it after several years elsewhere.",
    questions: [
      { q: "Who works at the Kilmarsh Hotel?", options: ["Mainly teenagers from a college","Trainee managers from other hotels","Retired hotel staff","Volunteers from the village"], answer: 0, explanation: "'It is a real hotel: guests pay ordinary prices, complain when the shower is cold, and leave reviews online like anywhere else.'" },
      { q: "Why did the college buy the hotel?", options: ["Students had asked for one","Work placements varied too much in quality","There was no hotel in the town","The building was very cheap"], answer: 1, explanation: "'The hotel belongs to the local college, which bought the building in 2009 after years of sending students on work placements that varied enormously in quality.'" },
      { q: "Why do students change roles every six weeks?", options: ["To match the college timetable","To keep them interested","So they learn an industry, not one job","Because staff leave often"], answer: 2, explanation: "'A commercial hotel would never move a competent receptionist to the kitchen, but a student who has only worked at reception has learned one job rather than an industry.'" },
      { q: "How do guests rate the hotel?", options: ["Exactly the same as others","Guests are not asked","Slightly worse than similar hotels","Slightly better than similar hotels"], answer: 3, explanation: "'The rest, according to the hotel's own surveys, rate it slightly higher than comparable hotels nearby.'" },
      { q: "Why does Nia think guests are satisfied?", options: ["Students deal with people rather than quoting rules","Guests expect very little","The prices are lower","The rooms are newer"], answer: 0, explanation: "'Students have not yet learned to hide behind procedure, so when something goes wrong they tend to deal with the person in front of them rather than explaining a policy.'" },
      { q: "What pleases Nia most?", options: ["The hotel almost breaks even", "Former students have returned as staff", "The reviews online", "The number of applications"], answer: 1, explanation: "'Eleven of the current staff, including the general manager, studied at the hotel themselves and came back to work in it after several years elsewhere.'" }
    ]
  },
  {
    id: "pet-rmc12-02",
    title: "The Cinema That Came Back",
    text: "The Regal in Blythe Mill showed its last film in 1987 and then spent twenty-six years as a carpet warehouse. It reopened as a cinema in 2015, and it now sells about forty thousand tickets a year in a town of nine thousand people.\n\nThe building was saved almost by accident. A local plumber, Dev Anand, was called to fix a leak in the warehouse and noticed, above a false ceiling that had been installed in 1991, the entire original decorated roof of the cinema, undamaged. He photographed it and put the photographs online, and within a month there was a committee.\n\nRaising the money took four years and was, everybody involved agrees, less difficult than deciding what the cinema should be. The first plan was to show old films, which the committee assumed the town wanted, since the campaign had been about nostalgia. A survey of eight hundred residents said something different. People wanted current films, at a time and price that suited a family, in a building they could walk to.\n\nSo the Regal shows new releases, six days a week, at about two-thirds of the price of the multiplex eighteen kilometres away. Wednesday afternoons are quiet screenings for people who prefer low sound and some light, which began for parents with babies and turned out to be used mostly by older residents.\n\nIt employs four people and about sixty volunteers. Dev, who is still a plumber, sits on the board and has never taken a free ticket, which he says is a rule he made for himself early and would not now be able to explain sensibly.\n\nThe original roof, incidentally, was too fragile to restore. It is protected above a new ceiling, and photographs of it hang in the foyer.",
    questions: [
      { q: "What was the Regal used for between 1987 and 2013?", options: ["It was a sports hall","It was empty","It stored carpets","It was a theatre"], answer: 2, explanation: "'The Regal in Blythe Mill showed its last film in 1987 and then spent twenty-six years as a carpet warehouse.'" },
      { q: "How was the building rediscovered?", options: ["A newspaper published old photographs","The council inspected it","A film company visited","A plumber found the original ceiling"], answer: 3, explanation: "'A local plumber, Dev Anand, was called to fix a leak in the warehouse and noticed, above a false ceiling that had been installed in 1991, the entire original decorated roof of the cinema, undamaged.'" },
      { q: "What did the committee find hardest?", options: ["Deciding what kind of cinema it should be","Getting permission to rebuild","Finding volunteers","Raising the money"], answer: 0, explanation: "'Raising the money took four years and was, everybody involved agrees, less difficult than deciding what the cinema should be.'" },
      { q: "What did the survey of residents show?", options: ["They wanted old films", "They wanted current films at a convenient time and price", "They preferred the multiplex", "They wanted a theatre instead"], answer: 1, explanation: "'People wanted current films, at a time and price that suited a family, in a building they could walk to.'" },
      { q: "Who mostly uses the Wednesday quiet screenings?", options: ["Parents with babies", "Schools", "Older residents", "Students"], answer: 2, explanation: "'Wednesday afternoons are quiet screenings for people who prefer low sound and some light, which began for parents with babies and turned out to be used mostly by older residents.'" },
      { q: "What happened to the original decorated roof?", options: ["It was fully restored", "It was moved to a museum", "It was sold to pay for the work", "It was protected above a new ceiling"], answer: 3, explanation: "'It is protected above a new ceiling, and photographs of it hang in the foyer.'" }
    ]
  },
  {
    id: "pet-rmc12-03",
    title: "A Year Delivering Letters",
    text: "I delivered post for fourteen months, and the first thing I would tell anybody thinking of doing it is that the walking is not the hard part. I walked about eighteen kilometres a day and was fitter than I have ever been. The hard part is that you cannot stop.\n\nA delivery round is timed. Mine had four hundred and ten addresses and had to be finished by half past one, which is possible in dry weather with no problems. It is not possible if a gate is locked, a parcel needs a signature, three houses have new residents, and it rains, all of which happen most days. You do not lose ten minutes; you lose ten minutes seven times.\n\nWhat surprised me was how much you learn about a street without wanting to. You know which houses receive letters from hospitals. You know who has stopped receiving birthday cards. Postal workers are told not to discuss any of it and almost none of them do, but you cannot help knowing.\n\nThe part I found genuinely difficult was the dogs, and not for the reason people assume. I was bitten once, mildly. The problem was the four or five dogs that waited at the door every morning for the sound of the letterbox, and the knowledge that the animal's entire day contained one event, which I was.\n\nI left because my knees began to hurt at twenty-six, which the older staff said was normal and treated as a joke, and I decided I did not want it to be normal.\n\nI still know that round. I walked past part of it last winter, eight years later, and could tell you which houses take a newspaper.",
    questions: [
      { q: "According to the writer, what is the hardest part of the job?", options: ["The lack of any chance to stop","Working outdoors in winter","Carrying heavy bags","The distance walked"], answer: 0, explanation: "'The hard part is that you cannot stop.'" },
      { q: "Why is the timing of a round often impossible?", options: ["Rounds are too long for one person", "Small delays happen repeatedly", "Post arrives late at the office", "The route changes every day"], answer: 1, explanation: "'You do not lose ten minutes; you lose ten minutes seven times.'" },
      { q: "What did the writer learn without intending to?", options: ["Which streets are oldest","How to read handwriting","Private details about residents' lives","How the postal system works"], answer: 2, explanation: "'What surprised me was how much you learn about a street without wanting to.'" },
      { q: "What did the writer find difficult about the dogs?", options: ["That owners complained","Being bitten regularly","Their noise early in the morning","That the postman was the highlight of their day"], answer: 3, explanation: "'The problem was the four or five dogs that waited at the door every morning for the sound of the letterbox, and the knowledge that the animal's entire day contained one event, which I was.'" },
      { q: "Why did the writer leave the job?", options: ["Knee pain that colleagues treated as normal","A move to another town","A disagreement with a manager","The pay was too low"], answer: 0, explanation: "'I left because my knees began to hurt at twenty-six, which the older staff said was normal and treated as a joke, and I decided I did not want it to be normal.'" },
      { q: "What does the ending show about the writer?", options: ["The writer still delivers occasionally","The round is still remembered in detail","The writer regrets leaving","The route has completely changed"], answer: 1, explanation: "'I walked past part of it last winter, eight years later, and could tell you which houses take a newspaper.'" }
    ]
  },
  {
    id: "pet-rmc12-04",
    title: "Choosing a Tree for the Square",
    text: "When the old lime tree in Marchbank Square was taken down after a storm, the council expected to plant a replacement within a month. Instead, the decision took two years and involved more residents than any local election in the town's history.\n\nThe delay began with a question from a schoolgirl at a public meeting. She asked what the new tree would be like in 2090. Nobody on the council had thought about the square that far ahead, and the honest answer was that the species being proposed, chosen because it grows quickly and looks good within a decade, would probably be near the end of its life by then.\n\nWhat followed was an unusually detailed public argument. Fast-growing trees give shade sooner but live shorter lives and drop more branches. Slow-growing trees such as oaks may take sixty years to shade a bench and can then stand for four centuries. Some residents wanted fruit, which brings wasps; others wanted the tree to be native, which rules out several species that will cope better with hotter summers.\n\nA vote was held, and the winning choice was not on the council's original list at all. It is a small-leaved lime, the same species as the one lost, chosen partly because two residents in their nineties remembered it being planted in 1934.\n\nThe tree went in last March, protected by a low fence that will be removed in about eight years. It is three metres tall and will shade the bench beneath it in roughly 2055.\n\nThe council has since changed its procedure. Any tree planted in a public space must now come with an estimate of what it will be like in seventy years, which one officer described as the most unusual piece of paperwork he has ever had to complete.",
    questions: [
      { q: "Why was the old tree removed?", options: ["The square was being rebuilt","It blocked a new road","It was damaged in a storm","It was diseased"], answer: 2, explanation: "'When the old lime tree in Marchbank Square was taken down after a storm, the council expected to plant a replacement within a month.'" },
      { q: "What caused the long delay?", options: ["An argument between councillors","Bad weather","A shortage of money","A schoolgirl's question about the distant future"], answer: 3, explanation: "'She asked what the new tree would be like in 2090.'" },
      { q: "What is a disadvantage of fast-growing trees?", options: ["They live shorter lives and drop branches","They are not native","They need more water","They are more expensive"], answer: 0, explanation: "'Fast-growing trees give shade sooner but live shorter lives and drop more branches.'" },
      { q: "What was unusual about the winning choice?", options: ["It was chosen by the council alone","It was not on the council's list","It was the cheapest option","It came from another country"], answer: 1, explanation: "'A vote was held, and the winning choice was not on the council's original list at all.'" },
      { q: "Why was the small-leaved lime chosen?", options: ["It grows fastest of all", "It produces fruit", "Elderly residents remembered the original being planted", "It needs no protection"], answer: 2, explanation: "'It is a small-leaved lime, the same species as the one lost, chosen partly because two residents in their nineties remembered it being planted in 1934.'" },
      { q: "What has the council changed?", options: ["It plants trees only in spring","It no longer holds public meetings","It plants only native species","New public trees need a seventy-year estimate"], answer: 3, explanation: "'Any tree planted in a public space must now come with an estimate of what it will be like in seventy years, which one officer described as the most unusual piece of paperwork he has ever had to complete.'" }
    ]
  },
  {
    id: "pet-rmc12-05",
    title: "The Map of Every Bench",
    text: "There is a website that shows every public bench in a city of half a million people. There are, at the last count, four thousand two hundred and eleven of them, and each one has a photograph, a note on whether it has arms, and how far it is from the previous bench.\n\nThe project was started by Marianne Okoro after her mother had a hip operation. Her mother could walk about two hundred metres before needing to sit down, which meant that the question of whether a journey was possible depended entirely on where the benches were. No such map existed, and the council's records turned out to be incomplete and, in about a fifth of cases, wrong.\n\nMarianne began walking streets and photographing benches at weekends. After eight months she had covered a quarter of the city and realised she would never finish alone. So she made it possible for anybody to add one, and about nine hundred people have.\n\nThe detail that matters most is the one visitors find strangest: arms. A bench without arms is very difficult to get up from for many older people, and a fifth of the benches in the city have none. The distance between benches matters too, and the map shows several routes to the hospital along which the gap is more than six hundred metres.\n\nThe council was initially uninterested and is now the map's largest user. When a bench is replaced, its department checks the site, and eleven new benches have been installed in gaps the map made visible.\n\nMarianne's mother died in 2022. The map now has versions in four other cities, all started by somebody who wrote to Marianne after finding out that the thing they needed did not exist anywhere.",
    questions: [
      { q: "What does the website show?", options: ["Every public bench in a city", "The city's bus routes", "Places to walk for exercise", "Hospitals and clinics"], answer: 0, explanation: "'There is a website that shows every public bench in a city of half a million people.'" },
      { q: "Why did Marianne start the project?", options: ["She worked for the council", "Her mother could walk only short distances", "She wanted to photograph the city", "She was asked by a hospital"], answer: 1, explanation: "'Her mother could walk about two hundred metres before needing to sit down, which meant that the question of whether a journey was possible depended entirely on where the benches were.'" },
      { q: "What was wrong with the council's records?", options: ["They were kept on paper only", "They were secret", "They were incomplete and often wrong", "They covered only the city centre"], answer: 2, explanation: "'No such map existed, and the council's records turned out to be incomplete and, in about a fifth of cases, wrong.'" },
      { q: "Why did she open the project to other people?", options: ["She wanted to raise money","Photographs were needed in winter","The council asked her to","She could not finish it alone"], answer: 3, explanation: "'After eight months she had covered a quarter of the city and realised she would never finish alone.'" },
      { q: "Why does the map record whether a bench has arms?", options: ["Getting up is hard without them for many older people","Arms make a bench more comfortable in rain","Benches with arms last longer","Arms show the bench's age"], answer: 0, explanation: "'A bench without arms is very difficult to get up from for many older people, and a fifth of the benches in the city have none.'" },
      { q: "How does the council use the map now?", options: ["It uses it to remove old benches","It checks the site and has filled gaps","It has taken the project over","It pays Marianne to run it"], answer: 1, explanation: "'When a bench is replaced, its department checks the site, and eleven new benches have been installed in gaps the map made visible.'" }
    ]
  },
  {
    id: "pet-rmc12-06",
    title: "The Language My Grandmother Stopped Speaking",
    text: "My grandmother spoke two languages until she was eleven and one afterwards. She was not forbidden to speak the second one exactly, but she was laughed at twice in her first month at a new school, and that was enough.\n\nI knew none of this until I was nineteen. She had never mentioned it, and my mother, who grew up in the house, had heard perhaps forty words of it in her whole childhood, mostly names of foods.\n\nWhat brought it back was an accident. My grandmother was in hospital after an operation, still partly asleep from the anaesthetic, and a nurse spoke to another nurse in the corridor in a language my grandmother had not heard properly in sixty-three years. She answered from the bed, in whole sentences, and then could not stop crying.\n\nThe nurse, whose family came from a valley about thirty kilometres from my grandmother's, visited her twice more before she was discharged. They spoke for about two hours in total. My grandmother said afterwards that the strangest part was not remembering the words. It was remembering what she was like when she used them, which she described as meeting somebody she used to know.\n\nShe tried to teach me a little in the four years that followed. It did not really work, because she had no adult vocabulary in it; her language had stopped growing at eleven, so we could discuss weather, food and animals in great detail and nothing else at all.\n\nI have about two hundred words. My daughter has perhaps nine, all of them names of vegetables, and she uses them without knowing they come from anywhere.",
    questions: [
      { q: "Why did the grandmother stop using her second language?", options: ["She simply forgot it","Her school forbade it","She was laughed at when she moved school","She moved to another country"], answer: 2, explanation: "'She was not forbidden to speak the second one exactly, but she was laughed at twice in her first month at a new school, and that was enough.'" },
      { q: "What did the writer's mother know of the language?", options: ["She spoke it well","Only songs","Nothing at all","About forty words, mostly food names"], answer: 3, explanation: "'She had never mentioned it, and my mother, who grew up in the house, had heard perhaps forty words of it in her whole childhood, mostly names of foods.'" },
      { q: "What happened in the hospital?", options: ["She heard nurses speaking her old language","She was asked to translate","She met a relative she had lost touch with","She was treated by a doctor from her village"], answer: 0, explanation: "'My grandmother was in hospital after an operation, still partly asleep from the anaesthetic, and a nurse spoke to another nurse in the corridor in a language my grandmother had not heard properly in sixty-three years.'" },
      { q: "What did the grandmother find strangest about the experience?", options: ["That her family were surprised","That she remembered who she had been","That she remembered the words","That the nurse understood her"], answer: 1, explanation: "'It was remembering what she was like when she used them, which she described as meeting somebody she used to know.'" },
      { q: "Why could she not teach the writer much?", options: ["She was too ill", "There was not enough time", "Her vocabulary had stopped developing at eleven", "The writer was not interested"], answer: 2, explanation: "'It did not really work, because she had no adult vocabulary in it; her language had stopped growing at eleven, so we could discuss weather, food and animals in great detail and nothing else at all.'" },
      { q: "What does the writer's daughter know?", options: ["As much as the writer","Only how to count","Nothing of the language","About nine words, without knowing their origin"], answer: 3, explanation: "'My daughter has perhaps nine, all of them names of vegetables, and she uses them without knowing they come from anywhere.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
