/* PET Prep bank: Reading multiple choice (B1) — wave 15 */
(function () {
var BANK = [
  {
    id: "pet-rmc15-01",
    title: "Why Bread Goes Hard",
    text: "Most people believe that bread goes hard because it dries out. This is only partly true, and the more important process is a different one that food scientists call retrogradation.\\n\\nBread is mostly starch. During baking, the starch absorbs water and its structure opens out, which is what makes fresh bread soft. As the loaf cools, that structure slowly begins to reorganise itself into a firmer arrangement, and it continues to do so for days. The water is still inside the loaf; it has simply become trapped in a way that makes the bread feel dry.\\n\\nThe clearest evidence for this is what happens in a refrigerator. Cold air does not dry bread out faster than warm air, yet bread kept in a fridge goes hard several times more quickly than bread left on a worktop. The reason is that the reorganisation happens fastest at temperatures just above freezing, which is exactly the temperature inside a fridge.\\n\\nThis also explains why warming an old slice works. Heating bread above about sixty degrees reverses part of the process and the slice becomes noticeably softer, which is why toast made from day-old bread is perfectly good. The effect is temporary, and the same slice will be hard again within an hour.\\n\\nFreezing, on the other hand, is effective, because below freezing the process almost stops. A loaf frozen on the day it is baked and defrosted a month later is very close to fresh. Bakers generally recommend slicing before freezing, since slices can be taken out individually.\\n\\nThe practical advice, then, is straightforward and slightly surprising: keep bread in a bread bin or a paper bag at room temperature for two days, freeze anything you will not eat by then, and never put a loaf in the fridge.",
    questions: [
      { q: "What is the main cause of bread going hard?", options: ["Starch reorganising into a firmer structure","Air getting inside the loaf","Bacteria in the bread","Water escaping into the air"], answer: 0, explanation: "'As the loaf cools, that structure slowly begins to reorganise itself into a firmer arrangement, and it continues to do so for days.'" },
      { q: "What happens to the water in old bread?", options: ["It turns to ice","It stays inside but becomes trapped","It moves to the crust","It evaporates completely"], answer: 1, explanation: "'The water is still inside the loaf; it has simply become trapped in a way that makes the bread feel dry.'" },
      { q: "Why does bread go hard quickly in a fridge?", options: ["The bread is squashed","Fridge air is very dry","The process is fastest just above freezing","Bread absorbs other smells"], answer: 2, explanation: "'The reason is that the reorganisation happens fastest at temperatures just above freezing, which is exactly the temperature inside a fridge.'" },
      { q: "Why does toasting old bread work?", options: ["Toasting removes the water","Heat kills bacteria","The surface is burnt away","Heat partly reverses the process"], answer: 3, explanation: "'Heating bread above about sixty degrees reverses part of the process and the slice becomes noticeably softer, which is why toast made from day-old bread is perfectly good.'" },
      { q: "Why is freezing effective?", options: ["Below freezing the process nearly stops","It makes the starch absorb more water","It dries the bread completely","It kills everything in the bread"], answer: 0, explanation: "'Freezing, on the other hand, is effective, because below freezing the process almost stops.'" },
      { q: "What advice does the article give?", options: ["Never freeze bread","Store at room temperature and freeze the rest","Buy only small loaves","Keep bread in the fridge after two days"], answer: 1, explanation: "'The practical advice, then, is straightforward and slightly surprising: keep bread in a bread bin or a paper bag at room temperature for two days, freeze anything you will not eat by then, and never put a loaf in the fridge.'" }
    ]
  },
  {
    id: "pet-rmc15-02",
    title: "The Long History of the Zip",
    text: "The zip is such an ordinary object that most people assume it has always existed. In fact it took about sixty years and several inventors to arrive at the design used today, and for most of that time nobody wanted it.\\n\\nThe first version was shown at a fair in Chicago in 1893 by Whitcomb Judson, who had designed it to fasten boots. It worked, but not reliably: it opened by itself, it caught in cloth, and it was expensive because each one had to be made largely by hand. Judson sold perhaps twenty in the following decade.\\n\\nThe design that actually works was produced in 1913 by an engineer named Gideon Sundback, who realised that the problem was the shape of the teeth. Instead of hooks, he used small spoon-shaped pieces, each of which fits into a hollow in the one opposite. He also built a machine that could produce a metre of the finished fastener in a few seconds, which mattered as much as the design itself.\\n\\nEven then, clothing makers were not interested. The first large orders came from the army during the First World War, for money belts and flying suits, and then from the makers of rubber boots. The word zipper comes from a boot sold in 1923, whose manufacturer named it after the sound it made.\\n\\nClothing came last. Zips did not appear widely in men's trousers until the 1930s, and then only after a public argument in which several tailors insisted that buttons were more respectable.\\n\\nToday something over two billion zips are made each year, most of them by one company in Japan. The teeth on a modern zip are shaped almost exactly as Sundback shaped them in 1913, which is unusual for any object more than a century old.",
    questions: [
      { q: "When was the first version of the zip shown?", options: ["1923","The 1930s","1893","1913"], answer: 2, explanation: "'The first version was shown at a fair in Chicago in 1893 by Whitcomb Judson, who had designed it to fasten boots.'" },
      { q: "What was wrong with Judson's design?", options: ["It could not be made in different sizes","It rusted quickly","It was too heavy","It opened by itself and caught in cloth"], answer: 3, explanation: "'It worked, but not reliably: it opened by itself, it caught in cloth, and it was expensive because each one had to be made largely by hand.'" },
      { q: "What was Sundback's key idea?", options: ["Changing the shape of the teeth","Adding a stronger pull tab","Using plastic instead of metal","Making the zip much smaller"], answer: 0, explanation: "'The design that actually works was produced in 1913 by an engineer named Gideon Sundback, who realised that the problem was the shape of the teeth.'" },
      { q: "What else was as important as the design?", options: ["A cheaper metal","A machine that made zips quickly","An advertising campaign","Support from the army"], answer: 1, explanation: "'He also built a machine that could produce a metre of the finished fastener in a few seconds, which mattered as much as the design itself.'" },
      { q: "Where does the word zipper come from?", options: ["A Japanese company","The inventor's name","A boot named after the sound","An army term"], answer: 2, explanation: "'The word zipper comes from a boot sold in 1923, whose manufacturer named it after the sound it made.'" },
      { q: "Why were zips slow to appear in clothing?", options: ["They were considered dangerous","Factories could not fit them","They were too expensive","Some tailors thought buttons more respectable"], answer: 3, explanation: "'Zips did not appear widely in men's trousers until the 1930s, and then only after a public argument in which several tailors insisted that buttons were more respectable.'" }
    ]
  },
  {
    id: "pet-rmc15-03",
    title: "The Invention of the Shopping Trolley",
    text: "In 1936 a shop owner in Oklahoma called Sylvan Goldman noticed something that had probably been true for as long as shops had existed: customers stopped buying when their basket became heavy. They did not stop because they had everything they wanted. They stopped because their arms were full.\\n\\nHis solution was a folding chair with wheels and a basket on the seat. The first trolleys were exactly that, and the design was crude, but the principle was sound: if the shop carried the weight, the customer would keep shopping.\\n\\nHe put them in his store and almost nobody used them. This is the part of the story that is usually left out. Men said the trolleys made them look weak; women said they had pushed enough prams. For several weeks the trolleys stood by the entrance, ignored.\\n\\nGoldman then did something clever. He hired people of various ages to walk around his shop using trolleys and looking entirely comfortable, and he instructed his staff to offer one to every customer at the door rather than leaving them in a stack. Within a month the trolleys were in use, and within two years he was manufacturing them for other shops.\\n\\nThe effect on shopping was enormous and not only in the obvious way. Larger trolleys led to larger shops, since a customer who can carry more will walk further, and shops that could hold more customers with full trolleys could be built further from town centres, where land was cheap. The modern supermarket is difficult to imagine without it.\\n\\nGoldman became very rich. He is said to have remarked, late in life, that the invention itself took an evening, and that persuading people to use it took two years, which he considered the harder piece of work by a considerable distance.",
    questions: [
      { q: "What did Goldman notice about customers?", options: ["They bought less when their basket was heavy", "They preferred small shops", "They shopped mainly at weekends", "They disliked queuing"], answer: 0, explanation: "'In 1936 a shop owner in Oklahoma called Sylvan Goldman noticed something that had probably been true for as long as shops had existed: customers stopped buying when their basket became heavy.'" },
      { q: "What was the first trolley made from?", options: ["A wooden box on wheels", "A folding chair with wheels and a basket", "A converted pram", "A metal frame from a factory"], answer: 1, explanation: "'His solution was a folding chair with wheels and a basket on the seat.'" },
      { q: "What happened when he first offered trolleys?", options: ["They broke quickly","They were stolen","Almost nobody used them","They were immediately popular"], answer: 2, explanation: "'He put them in his store and almost nobody used them.'" },
      { q: "How did he change customers' minds?", options: ["He removed all the baskets","He reduced his prices","He advertised in newspapers","He hired people to use them and had staff offer them"], answer: 3, explanation: "'He hired people of various ages to walk around his shop using trolleys and looking entirely comfortable, and he instructed his staff to offer one to every customer at the door rather than leaving them in a stack.'" },
      { q: "How did trolleys change shops themselves?", options: ["Shops became larger and moved out of town", "Shops needed fewer staff", "Shops opened for longer hours", "Shops reduced their range of goods"], answer: 0, explanation: "'Larger trolleys led to larger shops, since a customer who can carry more will walk further, and shops that could hold more customers with full trolleys could be built further from town centres, where land was cheap.'" },
      { q: "What did Goldman consider the harder task?", options: ["Manufacturing them cheaply","Getting people to use them","Selling them to other shops","Designing the trolley"], answer: 1, explanation: "'He is said to have remarked, late in life, that the invention itself took an evening, and that persuading people to use it took two years, which he considered the harder piece of work by a considerable distance.'" }
    ]
  },
  {
    id: "pet-rmc15-04",
    title: "The Woman Who Walked the Whole Coast",
    text: "It took Rosalind Meehan four years, walking mostly at weekends, to complete the entire coastline of the country on foot. The distance is usually given as about eleven thousand kilometres, though she says this figure is close to meaningless, since it depends entirely on how closely a walker follows the shape of the land.\\n\\nShe did not set out to do it. She walked a short section on a Saturday in 2018 because a train was cancelled and she had nothing else to do, and then walked the next section the following month because the first one had ended in an awkward place.\\n\\nThe hardest parts were not the mountains. They were the industrial areas, where the coast is fenced, and estuaries, where the sea comes inland for thirty kilometres and a walker must go round. She calculates that estuaries added about a fifth to the total distance.\\n\\nShe kept one rule that made everything slower and, she says, made the whole thing worthwhile: she went home between sections. Every walk began and ended at a bus stop or a station, and she never stayed overnight on the route. It meant more travelling than walking on some weekends, and it also meant she saw the coast in every season instead of walking through summer for four months.\\n\\nShe is careful about the way people describe what she did. She was not raising money, she did not sleep outdoors, and she had a normal job throughout. What she likes is that anybody able to walk fifteen kilometres could do the same thing, given enough Saturdays.\\n\\nShe finished at the same beach where she started, on a wet Sunday, with two friends and a flask of tea, and she says the strongest feeling she had was mild disappointment that there was nothing left to plan.",
    questions: [
      { q: "How long did the walk take?", options: ["Four months","One year","Four years","Eleven years"], answer: 2, explanation: "'It took Rosalind Meehan four years, walking mostly at weekends, to complete the entire coastline of the country on foot.'" },
      { q: "Why does she dislike the usual distance figure?", options: ["Nobody has ever measured it","It changes with the tide","It is far too small","It depends on how closely a walker follows the land"], answer: 3, explanation: "'The distance is usually given as about eleven thousand kilometres, though she says this figure is close to meaningless, since it depends entirely on how closely a walker follows the shape of the land.'" },
      { q: "How did the project begin?", options: ["A cancelled train left her free one Saturday","A friend suggested it","She read about somebody else doing it","She planned it for years"], answer: 0, explanation: "'She walked a short section on a Saturday in 2018 because a train was cancelled and she had nothing else to do, and then walked the next section the following month because the first one had ended in an awkward place.'" },
      { q: "What did she find hardest?", options: ["Bad weather","Fenced industrial coast and estuaries","Finding places to eat","Mountain paths"], answer: 1, explanation: "'They were the industrial areas, where the coast is fenced, and estuaries, where the sea comes inland for thirty kilometres and a walker must go round.'" },
      { q: "What rule did she keep?", options: ["She always walked alone", "She never walked in winter", "She went home between sections", "She carried all her food"], answer: 2, explanation: "'She kept one rule that made everything slower and, she says, made the whole thing worthwhile: she went home between sections.'" },
      { q: "How did she feel at the end?", options: ["Extremely proud","Relieved that it was over","Determined to do it again","Slightly disappointed that there was nothing left to plan"], answer: 3, explanation: "'She finished at the same beach where she started, on a wet Sunday, with two friends and a flask of tea, and she says the strongest feeling she had was mild disappointment that there was nothing left to plan.'" }
    ]
  },
  {
    id: "pet-rmc15-05",
    title: "Living Above the Shop",
    text: "My family lived above a hardware shop for eleven years, in three rooms reached by a staircase that came up through the storeroom. My parents ran the shop, and until I was about fourteen I assumed this was a normal way to live.\\n\\nThere were obvious advantages. My father's journey to work was nine steps. If I forgot my lunch, it was upstairs. When I was ill, somebody was always thirty seconds away, which is not true of most children whose parents work.\\n\\nThe disadvantages were less obvious and took me years to identify. The main one is that a shop has no closing time in a family that lives above it. People knocked on the side door in the evening, and my father almost always went down, because the person needed a fuse or a key cut and he could not bring himself to say no. Sunday was the only day the shop was genuinely shut, and even then the telephone rang.\\n\\nIt also meant that our family conversations were conducted in a shop. Every argument between my parents happened in a room where somebody might walk in. I did not realise until I visited a friend's house that most families discuss things in rooms with doors that stay closed.\\n\\nWhat I took from it was a strange sort of usefulness. By twelve I could mix paint to a customer's sample and cut a key. I knew the price of everything in a shop with four thousand items, which turned out to be the sort of memory that examiners like.\\n\\nThe shop closed in 2009, and the building is now a flat with no staircase to the ground floor. My father says he does not miss it and my mother says he is not telling the truth.",
    questions: [
      { q: "Where did the writer's family live?", options: ["In three rooms above the shop","In a flat across the street","In a house behind the shop","Next to a hardware shop"], answer: 0, explanation: "'My family lived above a hardware shop for eleven years, in three rooms reached by a staircase that came up through the storeroom.'" },
      { q: "What was one clear advantage?", options: ["The family always had company","Help was always seconds away","The shop was quiet","The rent was very low"], answer: 1, explanation: "'When I was ill, somebody was always thirty seconds away, which is not true of most children whose parents work.'" },
      { q: "What was the main disadvantage?", options: ["The building was cold","Customers were unfriendly","The shop never really closed","The rooms were too small"], answer: 2, explanation: "'The main one is that a shop has no closing time in a family that lives above it.'" },
      { q: "Why did the father go down in the evenings?", options: ["He enjoyed the company","The shop had to be checked","He needed the money","He could not refuse people who needed something"], answer: 3, explanation: "'People knocked on the side door in the evening, and my father almost always went down, because the person needed a fuse or a key cut and he could not bring himself to say no.'" },
      { q: "What did the writer realise after visiting a friend?", options: ["Most families talk privately behind closed doors", "Most children had their own rooms", "Other parents worked longer hours", "Shops were usually larger"], answer: 0, explanation: "'I did not realise until I visited a friend's house that most families discuss things in rooms with doors that stay closed.'" },
      { q: "What skills did the writer gain?", options: ["Bookkeeping and typing","Mixing paint, cutting keys and remembering prices","Driving a delivery van","Cooking and cleaning"], answer: 1, explanation: "'By twelve I could mix paint to a customer's sample and cut a key.'" }
    ]
  },
  {
    id: "pet-rmc15-06",
    title: "The Person You Never See at the Theatre",
    text: "At the back of the stalls in most theatres there is a desk with a small light, and behind it sits the person responsible for everything the audience hears. Aiofe Brennan has done this job for eleven years, and she says the aim of it is that nobody should ever notice her work.\\n\\nA modern play may use sixty separate sound effects, some lasting a quarter of a second. Aiofe operates them live, following the script and the actors, because timing that is one second late is worse than no effect at all. She has one rehearsal with the full cast and then does it for however many performances the run lasts.\\n\\nThe difficulty people do not expect is that no two audiences are the same. A full house absorbs sound, and a half-empty theatre reflects it, so the same setting can be too loud on a Tuesday and too quiet on a Saturday. Aiofe adjusts throughout every performance, and says she is really listening to the room rather than the equipment.\\n\\nHer worst moment was in her second year, when a piece of equipment failed nineteen minutes into a performance and a telephone that had to ring, in a scene where a character answers it, did not. She made the sound herself, into a microphone, badly. Two reviewers mentioned the play's odd telephone.\\n\\nActors, she says, notice everything. She has been thanked by name from the stage exactly once, which embarrassed her, and she has had four actors ask her to change a sound because it was affecting how they played a scene, all of which she did.\\n\\nShe was asked recently whether she would prefer a job where the work is visible. She said that she has sat in a full theatre where eight hundred people jumped at the same moment because of something she did with her left hand, and that this is quite visible enough.",
    questions: [
      { q: "What is Aiofe's aim in her job?", options: ["To finish before the actors","To be noticed for good work","That nobody notices her work","To use as many effects as possible"], answer: 2, explanation: "'Aiofe Brennan has done this job for eleven years, and she says the aim of it is that nobody should ever notice her work.'" },
      { q: "Why does she operate the effects live?", options: ["She prefers working by hand","The director insists","The equipment cannot be automated","Timing must match the actors exactly"], answer: 3, explanation: "'Aiofe operates them live, following the script and the actors, because timing that is one second late is worse than no effect at all.'" },
      { q: "Why does the same setting sound different on different nights?", options: ["A full audience absorbs sound","The building expands in heat","The equipment changes","The actors speak differently"], answer: 0, explanation: "'A full house absorbs sound, and a half-empty theatre reflects it, so the same setting can be too loud on a Tuesday and too quiet on a Saturday.'" },
      { q: "What does she say she is really listening to?", options: ["The music","The room","The equipment","The actors' voices"], answer: 1, explanation: "'Aiofe adjusts throughout every performance, and says she is really listening to the room rather than the equipment.'" },
      { q: "What happened during her worst moment?", options: ["An actor forgot a line","The theatre lost power","A telephone effect failed and she imitated it","She started an effect too early"], answer: 2, explanation: "'She made the sound herself, into a microphone, badly.'" },
      { q: "Why does she not want a more visible job?", options: ["She plans to become a director","She dislikes attention from reviewers","She is happy with her pay","She has seen a whole audience react to her work"], answer: 3, explanation: "'She said that she has sat in a full theatre where eight hundred people jumped at the same moment because of something she did with her left hand, and that this is quite visible enough.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
