/* PET Prep bank: Reading multiple choice (B1) — wave 17 */
(function () {
var BANK = [
  {
    id: "pet-rmc17-01",
    title: "How Languages Name Colours",
    text: "Languages do not divide the rainbow in the same way. Some have as few as two colour words, while English has around eleven that ordinary speakers use without thinking. What is surprising is that colour words appear in different languages in a fairly predictable order.\n\nIn the late 1960s two researchers, Brent Berlin and Paul Kay, compared the colour words of ninety-eight languages. They found that a language with only two colour terms always divides the world into something like dark and light. If a third is added, it is almost always red. Green and yellow tend to follow, then blue, then brown, and then a group including grey, orange, pink and purple.\n\nThe pattern was controversial when it was published and remains debated, mainly because the original study used speakers living in societies where another language was also present. Later work with more careful methods has supported the general order while showing that the boundaries are less sharp than first claimed.\n\nOne famous example concerns blue and green. Several languages, including Japanese historically and many others today, use a single word covering both, and speakers of those languages see the colours perfectly well but group them differently. The Japanese word ao originally covered both, which is why traffic lights in Japan are still described using it although the light is green.\n\nBlue is the last common colour to be named in most language families, and this is probably practical rather than mysterious. Blue is rare in nature as a material: there are blue skies and blue seas, but almost no blue plants, animals or stones that early people could hold, point at and use.\n\nThe conclusion researchers now generally accept is that language and vision both matter. Human eyes are the same everywhere, and what a community needs to talk about decides which differences get a word.",
    questions: [
      { q: "What did Berlin and Kay compare?", options: ["Colour words in ninety-eight languages","Paintings from many countries","How children learn colours","The eyes of different peoples"], answer: 0, explanation: "'In the late 1960s two researchers, Brent Berlin and Paul Kay, compared the colour words of ninety-eight languages.'" },
      { q: "What is the third colour term to appear?", options: ["Green","Red","Yellow","Blue"], answer: 1, explanation: "'If a third is added, it is almost always red.'" },
      { q: "Why was the original study criticised?", options: ["The results were never repeated","The researchers were colour-blind","The speakers also knew another language","Too few languages were studied"], answer: 2, explanation: "'The pattern was controversial when it was published and remains debated, mainly because the original study used speakers living in societies where another language was also present.'" },
      { q: "What is true of speakers whose language has one word for blue and green?", options: ["They avoid using the word","They borrow words from other languages","They cannot see the difference","They see the colours but group them differently"], answer: 3, explanation: "'Several languages, including Japanese historically and many others today, use a single word covering both, and speakers of those languages see the colours perfectly well but group them differently.'" },
      { q: "Why is blue usually named last?", options: ["There are few blue things people could handle","It was considered unlucky","It is difficult to see","It has no name in old writing"], answer: 0, explanation: "'Blue is rare in nature as a material: there are blue skies and blue seas, but almost no blue plants, animals or stones that early people could hold, point at and use.'" },
      { q: "What do researchers now generally accept?", options: ["Only vision matters","Both language and vision play a part","The whole question cannot be studied","Only language matters"], answer: 1, explanation: "'The conclusion researchers now generally accept is that language and vision both matter.'" }
    ]
  },
  {
    id: "pet-rmc17-02",
    title: "On Call for the Mountain",
    text: "Mountain rescue in this country is done almost entirely by volunteers. The team covering the hills above Glenmarrick has thirty-eight members, none of whom is paid, and it was called out one hundred and twelve times last year.\n\nMembers carry a pager and may be called at any hour. Fiona Duthie, a veterinary nurse who has been on the team for nine years, has left a supermarket queue, a wedding reception and, twice, her own bed at three in the morning. Her employer allows her to leave work for callouts, which she describes as the single thing that makes her membership possible.\n\nThe public imagines dramatic rescues from cliffs. Most callouts are far more ordinary: a walker with a twisted ankle three kilometres from a road, somebody who set off at two in the afternoon in November and lost the light, or a group who followed a path shown on a map that no longer exists on the ground.\n\nCarrying a person is the physically hardest part, and it is the reason the team needs so many members. A stretcher on rough ground requires eight people, changing regularly, and a rescue three kilometres from a road can take five hours.\n\nThe team is careful about how it talks to the people it rescues. Nobody is told they were foolish, even when they were. Fiona says this is not politeness: a person who fears being lectured is a person who delays calling, and delay in bad weather is what turns an injury into something worse.\n\nThe team's costs, about forty-one thousand pounds a year, come entirely from donations. Fiona says the number that surprises people most is a different one. Roughly a third of last year's callouts were to local residents rather than visitors, and the single largest category was people out walking dogs.",
    questions: [
      { q: "Who carries out mountain rescue in the area described?", options: ["The army","Police officers","Unpaid volunteers","Full-time professionals"], answer: 2, explanation: "'The team covering the hills above Glenmarrick has thirty-eight members, none of whom is paid, and it was called out one hundred and twelve times last year.'" },
      { q: "What does Fiona say makes her membership possible?", options: ["Her training as a nurse","Having no children","Living close to the hills","Her employer letting her leave work"], answer: 3, explanation: "'Her employer allows her to leave work for callouts, which she describes as the single thing that makes her membership possible.'" },
      { q: "What are most callouts actually like?", options: ["Ordinary problems such as injuries or darkness","Rescues of climbers only","Dramatic cliff rescues","Searches lasting several days"], answer: 0, explanation: "'Most callouts are far more ordinary: a walker with a twisted ankle three kilometres from a road, somebody who set off at two in the afternoon in November and lost the light, or a group who followed a path shown on a map that no longer exists on the ground.'" },
      { q: "Why does the team need so many members?", options: ["Callouts happen at night", "Carrying a stretcher needs eight people at a time", "Members live far apart", "Equipment is heavy to store"], answer: 1, explanation: "'A stretcher on rough ground requires eight people, changing regularly, and a rescue three kilometres from a road can take five hours.'" },
      { q: "Why does the team never criticise those it rescues?", options: ["Volunteers are trained to say nothing","It is a legal requirement","Fear of criticism makes people delay calling","The rescued often complain"], answer: 2, explanation: "'Fiona says this is not politeness: a person who fears being lectured is a person who delays calling, and delay in bad weather is what turns an injury into something worse.'" },
      { q: "Which fact surprises people most?", options: ["The team is entirely unpaid","Most rescues happen in summer","Costs come from donations","Many rescues involve local dog walkers"], answer: 3, explanation: "'Roughly a third of last year's callouts were to local residents rather than visitors, and the single largest category was people out walking dogs.'" }
    ]
  },
  {
    id: "pet-rmc17-03",
    title: "Why Some Roads Run Straight",
    text: "Anybody looking at a map of Britain will notice a number of unusually straight roads, often running for twenty or thirty kilometres with barely a bend. Almost all of them were built by the Romans, and the reason for the straightness is not what most people assume.\n\nIt is often said that the Romans built straight roads because straight is shortest. That is true but incomplete, because Roman roads are not straight overall: they are made of long straight sections joined at angles, usually at high points in the landscape.\n\nThe reason is the method of surveying. Roman engineers set out a route by sighting between fixed points, often fires or poles on hilltops, and then working out a line between them. This produces exactly what the maps show: a series of straight lines that change direction where a surveyor could see from one high point to the next.\n\nStraightness also had a purpose beyond distance. These were military roads. Soldiers marched about thirty kilometres a day, and a straight road with a good surface allowed an army to move predictably, which mattered more than comfort. The roads were also built up above the surrounding land, which kept them dry and made them visible from a distance.\n\nWhat is remarkable is how many are still in use. A number of major routes follow Roman lines almost exactly, and in some places the modern surface sits directly on the original layers of stone. Where a modern road bends away from a Roman line, the reason is usually a medieval landowner rather than a hill.\n\nThe roads outlasted the empire that built them by fifteen centuries, largely because for most of that time nobody in Britain had the organisation, the money or the reason to build anything better.",
    questions: [
      { q: "What is said about Roman roads overall?", options: ["They are straight sections joined at angles","They follow rivers","They avoid high ground","They are perfectly straight from end to end"], answer: 0, explanation: "'That is true but incomplete, because Roman roads are not straight overall: they are made of long straight sections joined at angles, usually at high points in the landscape.'" },
      { q: "What caused this pattern?", options: ["The availability of stone","The method of surveying between visible points","The shape of the hills","A rule made in Rome"], answer: 1, explanation: "'Roman engineers set out a route by sighting between fixed points, often fires or poles on hilltops, and then working out a line between them.'" },
      { q: "Why did straightness matter militarily?", options: ["It reduced building costs","It made roads harder to attack","It allowed armies to move predictably","It confused enemies"], answer: 2, explanation: "'Soldiers marched about thirty kilometres a day, and a straight road with a good surface allowed an army to move predictably, which mattered more than comfort.'" },
      { q: "Why were the roads built up above the land?", options: ["To make them wider","To protect nearby fields","To use less stone","To keep them dry and visible"], answer: 3, explanation: "'The roads were also built up above the surrounding land, which kept them dry and made them visible from a distance.'" },
      { q: "Why do some modern roads bend away from Roman lines?", options: ["Because of medieval landowners","Because of railway building","Because of hills","Because of rivers"], answer: 0, explanation: "'Where a modern road bends away from a Roman line, the reason is usually a medieval landowner rather than a hill.'" },
      { q: "Why did the roads last so long?", options: ["They were repaired every century", "Nobody could build better for a very long time", "They were protected by law", "They were rarely used"], answer: 1, explanation: "'The roads outlasted the empire that built them by fifteen centuries, largely because for most of that time nobody in Britain had the organisation, the money or the reason to build anything better.'" }
    ]
  },
  {
    id: "pet-rmc17-04",
    title: "The Farmer Who Stopped Ploughing",
    text: "Bramble Hill Farm has not been ploughed since 2014. Its owner, Duncan Sherratt, farms four hundred hectares of cereals and now sows seed directly into the ground left by the previous crop, without turning the soil at all.\n\nPloughing has been standard practice for thousands of years, and its purposes are real: it buries weeds, breaks up compacted ground and warms the surface in spring. Its cost is also real. Turning soil exposes it to rain and wind, and the material lost is the thin upper layer where almost all the biological activity happens.\n\nDuncan changed after two seasons in which he watched soil leave his own fields in visible brown water. He read for a year before doing anything, and then converted one field of thirty hectares rather than the farm.\n\nThe first three years were worse than before. Yields fell by about a tenth, weeds increased, and neighbours were, he says, extremely polite about it in a way that made everything clear. Soil that has been ploughed annually for decades takes several years to develop the structure that makes the method work.\n\nBy year five the yields had returned to their earlier level and his costs had not. He uses roughly sixty per cent less diesel, has sold two tractors, and spends about half as many hours in a machine during the autumn.\n\nHe is careful about giving advice, because his soil is a particular type and his rainfall is moderate. On heavy clay in a wet region, he says, the same method can fail badly, and he has watched two farmers try it after visiting him and give up within two years.\n\nHis measure of success is not the yield. It is a spade. He digs a hole in the same corner of the same field every March, and he says the difference between 2014 and now is something he would not have believed if somebody had described it to him.",
    questions: [
      { q: "What is unusual about Bramble Hill Farm?", options: ["It has no owner","It grows no cereals","The soil is never ploughed","It uses no machinery"], answer: 2, explanation: "'Bramble Hill Farm has not been ploughed since 2014.'" },
      { q: "What is the disadvantage of ploughing?", options: ["It damages machinery","It takes too long","It buries weeds too deeply","It exposes soil to rain and wind"], answer: 3, explanation: "'Turning soil exposes it to rain and wind, and the material lost is the thin upper layer where almost all the biological activity happens.'" },
      { q: "What made Duncan change?", options: ["Seeing soil washing off his fields", "Advice from a neighbour", "New government rules", "A drop in crop prices"], answer: 0, explanation: "'Duncan changed after two seasons in which he watched soil leave his own fields in visible brown water.'" },
      { q: "What happened in the first three years?", options: ["Yields rose immediately", "Yields fell and weeds increased", "Nothing changed", "He had to buy more machines"], answer: 1, explanation: "'Yields fell by about a tenth, weeds increased, and neighbours were, he says, extremely polite about it in a way that made everything clear.'" },
      { q: "What has changed by now?", options: ["He has returned to ploughing part of the farm","He grows different crops","Yields recovered and costs fell","Yields are higher than ever"], answer: 2, explanation: "'By year five the yields had returned to their earlier level and his costs had not.'" },
      { q: "Why is he cautious about advising others?", options: ["He does not want competitors","The rules may change","He is not sure it worked","The method suits particular soils and rainfall"], answer: 3, explanation: "'He is careful about giving advice, because his soil is a particular type and his rainfall is moderate.'" }
    ]
  },
  {
    id: "pet-rmc17-05",
    title: "The Chess Tables in the Park",
    text: "There are six concrete chess tables in Alderman Park, installed in 1974, and on most afternoons between March and October all six are in use. The park has no chess club, no organiser and no timetable, and the tables have produced something that a club, according to several of the players, would probably have prevented.\n\nNobody arranges a game in advance. A player sits down and sets out the pieces, and somebody else appears within a few minutes. The players range in age from about eleven to ninety-one, and several of them do not share a language beyond the names of the pieces.\n\nThe pieces themselves are the interesting part. They belong to nobody. Some are kept in a bag behind the café counter, some are brought by individual players, and sets have been mixed for so long that a single game may contain pieces of four different sizes.\n\nThere are unwritten rules that a newcomer learns quickly. The winner keeps the table. A game may be watched but not commented on. Anybody who has waited two games goes next, and the person who has been waiting will always be pointed out to a newcomer by somebody else rather than by themselves.\n\nThe council proposed removing two tables in 2019 to make room for an exercise area, and the response taught it something. The objections did not come from chess players. They came from parents, from the café, and from a doctor who had spent a decade telling isolated older patients to go and sit in that particular corner of that particular park.\n\nThe tables stayed. Two more were added last year at the other end of the park, and, so far, almost nobody uses them, which the players in the original corner find funny and cannot explain either.",
    questions: [
      { q: "How are games arranged in the park?", options: ["Not at all; players simply sit down","By booking at the café","Through a club","By a timetable on a board"], answer: 0, explanation: "'A player sits down and sets out the pieces, and somebody else appears within a few minutes.'" },
      { q: "What is unusual about the chess pieces?", options: ["They are made of concrete","They belong to nobody and are mixed together","They are very valuable","They are kept by the council"], answer: 1, explanation: "'They belong to nobody.'" },
      { q: "What is one of the unwritten rules?", options: ["The loser keeps the table", "Games must last under an hour", "Watchers must not comment", "Newcomers play first"], answer: 2, explanation: "'A game may be watched but not commented on.'" },
      { q: "How does a newcomer learn who is next?", options: ["The waiting player says so","The café keeps the order","A list is kept","Someone else points the waiting player out"], answer: 3, explanation: "'Anybody who has waited two games goes next, and the person who has been waiting will always be pointed out to a newcomer by somebody else rather than by themselves.'" },
      { q: "Who objected to removing two tables?", options: ["Parents, the café and a doctor","The council's own staff","Nobody at all","Only the chess players"], answer: 0, explanation: "'They came from parents, from the café, and from a doctor who had spent a decade telling isolated older patients to go and sit in that particular corner of that particular park.'" },
      { q: "What has happened to the two new tables?", options: ["They were removed again","Almost nobody uses them","They are used only in winter","They are used more than the old ones"], answer: 1, explanation: "'Two more were added last year at the other end of the park, and, so far, almost nobody uses them, which the players in the original corner find funny and cannot explain either.'" }
    ]
  },
  {
    id: "pet-rmc17-06",
    title: "The Midwife Who Works at Night",
    text: "Around one baby in fifty in this country is born at home, and in the district around Thornaby most of those births are attended by Marguerite Osei, who has been a midwife for twenty-two years and has worked exclusively with home births since 2015.\n\nHer working life is unlike almost anybody else's. Babies do not arrive on a timetable, and she has been called out at every hour of the twenty-four. She keeps a bag packed by the door and a second one in her car, and she has learned to sleep in short pieces, which she says took about two years and cannot be taught.\n\nSafety is the question she is asked about most and she answers it the same way every time. Home birth is suitable for pregnancies without complications, it is not offered to everybody, and the assessment continues throughout: about one in eight of the women she books ends up giving birth in hospital because something changes. Transferring is not a failure, she says, and telling people that clearly beforehand is part of her job.\n\nWhat she notices most is the difference in a room. In hospital the woman is a visitor and the staff belong. At home the woman belongs and Marguerite is the visitor, and she says the effect of this on how people behave is far larger than she expected when she changed.\n\nThe part she finds hardest is not emergencies, for which she is trained, but the ordinary loneliness of the work. There is nobody in the next room. Decisions are made alone at four in the morning, and although a second midwife attends the birth itself, the hours before it are usually hers.\n\nShe intends to work five more years and is training two younger colleagues, one of whom, she notes with some amusement, was born at home in 1998 with Marguerite in the room.",
    questions: [
      { q: "How common are home births in the country described?", options: ["They are very rare indeed","About one baby in five","About one in fifty","About half of all births"], answer: 2, explanation: "'Around one baby in fifty in this country is born at home, and in the district around Thornaby most of those births are attended by Marguerite Osei, who has been a midwife for twenty-two years and has worked exclusively with home births since 2015.'" },
      { q: "What has she had to learn?", options: ["To drive at night","To work without equipment","To use several languages","To sleep in short periods"], answer: 3, explanation: "'She keeps a bag packed by the door and a second one in her car, and she has learned to sleep in short pieces, which she says took about two years and cannot be taught.'" },
      { q: "What happens to about one in eight of her bookings?", options: ["They give birth in hospital","They cancel the booking","They give birth early","They change midwife"], answer: 0, explanation: "'Home birth is suitable for pregnancies without complications, it is not offered to everybody, and the assessment continues throughout: about one in eight of the women she books ends up giving birth in hospital because something changes.'" },
      { q: "What difference does she notice between home and hospital?", options: ["Home is quieter", "At home the woman belongs and she is the visitor", "Hospitals are better equipped", "There is more time at home"], answer: 1, explanation: "'At home the woman belongs and Marguerite is the visitor, and she says the effect of this on how people behave is far larger than she expected when she changed.'" },
      { q: "What does she find hardest?", options: ["Explaining risks to families","Emergencies","The loneliness of working alone","The travelling"], answer: 2, explanation: "'The part she finds hardest is not emergencies, for which she is trained, but the ordinary loneliness of the work.'" },
      { q: "What is amusing about one of her trainees?", options: ["She is older than Marguerite","She refuses to work at night","She lives in the same street","She was born at home with Marguerite present"], answer: 3, explanation: "'She intends to work five more years and is training two younger colleagues, one of whom, she notes with some amusement, was born at home in 1998 with Marguerite in the room.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
