/* PET Prep bank: Reading multiple choice (B1) — wave 23 */
(function () {
var BANK = [
  {
    id: "pet-rmc23-01",
    title: "Why Do Cats Purr?",
    text: "Purring is one of the most familiar sounds in a house with a cat, and it is neither as simple nor as cheerful as most people assume.\nThe sound is produced in the throat. Signals from the brain make the muscles of the voice box open and close the space between the vocal folds about twenty-five times a second, and air passing through in both directions produces a continuous vibration. This is why a purr does not stop when the cat breathes in, which is what makes it different from almost any other animal sound.\nThe assumption that a purring cat is a happy cat is only partly correct. Cats also purr when they are injured, when they are giving birth, when they are being examined by a vet, and, sometimes, when they are dying. Whatever purring is for, contentment is not the whole answer.\nOne explanation that has received serious attention concerns healing. The frequencies produced by purring, between about twenty-five and one hundred and fifty vibrations a second, are within the range that has been shown in laboratory studies to encourage bone growth. Whether purring actually does this in a living cat has not been demonstrated, and researchers are careful about the claim.\nA better supported idea is that purring is a signal that asks for care without threatening anybody. A kitten purrs from two days old, before it can see, and a purring animal is telling its mother where it is and that it is not a danger.\nThere is one variation that has been studied closely. Cats that live with humans sometimes add a higher, more urgent cry inside the purr when they want food, at a frequency close to that of a human baby's cry. People asked to listen to recordings consistently describe that version as harder to ignore.",
    questions: [
      { q: "What makes a purr different from other animal sounds?", options: ["It continues while breathing in","It comes from the chest","It has no rhythm","It is very loud"], answer: 0, explanation: "'This is why a purr does not stop when the cat breathes in, which is what makes it different from almost any other animal sound.'" },
      { q: "When else do cats purr?", options: ["Only when hungry","When injured, giving birth or at the vet","Only in the presence of humans","Only when contented"], answer: 1, explanation: "'Cats also purr when they are injured, when they are giving birth, when they are being examined by a vet, and, sometimes, when they are dying.'" },
      { q: "What is said about the healing theory?", options: ["It is proved", "It is completely rejected", "The frequencies are promising but unproven in living cats", "It applies only to kittens"], answer: 2, explanation: "'Whether purring actually does this in a living cat has not been demonstrated, and researchers are careful about the claim.'" },
      { q: "What is the better supported explanation?", options: ["Purring keeps cats warm","Purring frightens other animals","Purring helps digestion","Purring is a request for care"], answer: 3, explanation: "'A better supported idea is that purring is a signal that asks for care without threatening anybody.'" },
      { q: "From what age do kittens purr?", options: ["From two days old", "From two weeks old", "From two months old", "Only when they can see"], answer: 0, explanation: "'A kitten purrs from two days old, before it can see, and a purring animal is telling its mother where it is and that it is not a danger.'" },
      { q: "What is special about the food-asking purr?", options: ["It is much quieter", "It contains a cry like a human baby's", "It lasts longer", "It is only used at night"], answer: 1, explanation: "'Cats that live with humans sometimes add a higher, more urgent cry inside the purr when they want food, at a frequency close to that of a human baby's cry.'" }
    ]
  },
  {
    id: "pet-rmc23-02",
    title: "The Woman Who Writes the Timetable",
    text: "Somebody has to decide that the 07:42 leaves at 07:42, and for the regional railway around Kestrel Bay that person is Wendy Achterberg. She has done it for thirteen years and describes the work as solving the same puzzle every year with different pieces.\nA timetable looks like a list and is really a set of promises that must all be possible at once. Trains share tracks, and two trains cannot occupy the same section, so every departure decides several others. A single train delayed at a junction can affect services two hours later and forty kilometres away.\nThe part passengers never see is that the timetable is written backwards from the connections that matter most. Wendy begins with the school arrivals, the hospital shifts and the ferry, because those are the journeys where five minutes makes the difference between useful and useless. Everything else is arranged around them.\nShe also builds in what the industry calls recovery time: small amounts of extra time in the schedule that allow a late train to catch up. Too little and the whole day collapses after one problem. Too much and the trains are slower than they need to be, and passengers notice a journey that takes forty minutes for a distance they can drive in twenty-five.\nThe complaint she receives most often is about a train that leaves four minutes before a connecting bus arrives. She can usually explain why, and the explanation is almost always that changing it would break something worse elsewhere, which she says is true and is not a satisfying thing to tell somebody standing in the rain.\nHer own measure of success is a number the public never sees: how quickly the service returns to normal after a disruption. A good timetable, she says, is not one where nothing goes wrong. It is one that recovers by lunchtime.",
    questions: [
      { q: "What does Wendy do?", options: ["She repairs track","She drives trains","She writes the railway timetable","She manages stations"], answer: 2, explanation: "'Somebody has to decide that the 07:42 leaves at 07:42, and for the regional railway around Kestrel Bay that person is Wendy Achterberg.'" },
      { q: "Why does one departure affect others?", options: ["Drivers work fixed hours","Stations have few platforms","Passengers change trains","Trains share tracks"], answer: 3, explanation: "'Trains share tracks, and two trains cannot occupy the same section, so every departure decides several others.'" },
      { q: "How does she begin planning?", options: ["With the connections that matter most","With the longest journeys","With the earliest trains","With the busiest stations"], answer: 0, explanation: "'Wendy begins with the school arrivals, the hospital shifts and the ferry, because those are the journeys where five minutes makes the difference between useful and useless.'" },
      { q: "What is recovery time for?", options: ["Loading luggage","Allowing late trains to catch up","Giving drivers a break","Cleaning the trains"], answer: 1, explanation: "'She also builds in what the industry calls recovery time: small amounts of extra time in the schedule that allow a late train to catch up.'" },
      { q: "What is the problem with too much recovery time?", options: ["Connections are missed","Trains become unreliable","Journeys become noticeably slow","Staff costs rise"], answer: 2, explanation: "'Too much and the trains are slower than they need to be, and passengers notice a journey that takes forty minutes for a distance they can drive in twenty-five.'" },
      { q: "How does she judge a good timetable?", options: ["By passenger numbers","By punctuality figures","By how fast the trains are","By how quickly the service recovers"], answer: 3, explanation: "'A good timetable, she says, is not one where nothing goes wrong.'" }
    ]
  },
  {
    id: "pet-rmc23-03",
    title: "The Barcode Turns Fifty",
    text: "The first item ever sold using a barcode was a packet of chewing gum, in a supermarket in Ohio, in June 1974. The technology had taken twenty-six years to get that far.\nThe idea came from a graduate student, Bernard Silver, who overheard a shop owner asking a university professor whether anything could read product information automatically at a till. Silver and a colleague, Joseph Woodland, patented a design in 1952. It was circular, like a target, so that it could be read from any angle, and Woodland later said he had arrived at the idea by drawing lines in sand on a beach.\nNothing happened for twenty years, for a simple reason: there was no light source strong and precise enough to read the pattern reliably or a computer cheap enough to process it. Both problems were solved by the laser and by falling computer costs in the late 1960s.\nThe design that finally succeeded was rectangular rather than circular, and the choice was practical. Printing presses of the time produced ink that spread slightly along the direction of the paper's travel, which would distort a circle but merely thicken the lines of a rectangle, and a scanner could be built to cope with that.\nThe barcode's real effect was not speed at the till, although that is what shoppers noticed. It was that a shop could, for the first time, know exactly what it had sold within minutes. This changed ordering, warehousing and what shops chose to stock, and it made possible the very large stores of the following decades.\nSilver died in 1963, aged thirty-eight, eleven years before the chewing gum. Woodland lived until 2012 and said several times in interviews that the invention was not the pattern but the decision to keep working on something that had no use for two decades.",
    questions: [
      { q: "What was the first barcoded item sold?", options: ["A packet of chewing gum", "A tin of soup", "A newspaper", "A bar of soap"], answer: 0, explanation: "'The first item ever sold using a barcode was a packet of chewing gum, in a supermarket in Ohio, in June 1974.'" },
      { q: "How did the idea begin?", options: ["A university research project", "A student overhearing a shop owner's question", "A government competition", "A printing company's request"], answer: 1, explanation: "'The idea came from a graduate student, Bernard Silver, who overheard a shop owner asking a university professor whether anything could read product information automatically at a till.'" },
      { q: "What shape was the original design?", options: ["Triangular","Rectangular","Circular","Square"], answer: 2, explanation: "'It was circular, like a target, so that it could be read from any angle, and Woodland later said he had arrived at the idea by drawing lines in sand on a beach.'" },
      { q: "Why did nothing happen for twenty years?", options: ["Nobody could print the patterns","Shops refused to use it","The patent was disputed","Lights and computers were not good enough"], answer: 3, explanation: "'Nothing happened for twenty years, for a simple reason: there was no light source strong and precise enough to read the pattern reliably or a computer cheap enough to process it.'" },
      { q: "Why was a rectangle chosen in the end?", options: ["Ink spreading would distort a circle","It could hold more information","Scanners were rectangular","It was cheaper to print"], answer: 0, explanation: "'Printing presses of the time produced ink that spread slightly along the direction of the paper's travel, which would distort a circle but merely thicken the lines of a rectangle, and a scanner could be built to cope with that.'" },
      { q: "What was the barcode's real effect?", options: ["Faster queues at the till", "Shops knowing instantly what they had sold", "Lower prices for shoppers", "Smaller packaging"], answer: 1, explanation: "'It was that a shop could, for the first time, know exactly what it had sold within minutes.'" }
    ]
  },
  {
    id: "pet-rmc23-04",
    title: "The Sewing Group at the Health Centre",
    text: "On Tuesday afternoons, in a room at the back of a health centre in Ferry Hill, between twelve and twenty people sit around three tables and sew. Most of them were sent there by a doctor.\nThe group was set up in 2019 by a practice nurse, Kirsty Mbeki, who had noticed how many of her appointments were with people whose main problem was that they spoke to nobody from Friday to Monday. She was clear from the beginning that she did not want a group about health. People who are told to attend something for their wellbeing, she says, mostly do not, and those who do arrive expecting to be improved.\nSo the group is about sewing. Members repair their own clothes, make things for a local children's ward, and are currently working through a large donation of curtain fabric. There is a proper teacher, a retired seamstress named Vi, and members are expected to get better at it.\nThe rules are unusual. Nobody is asked why they are there. Nobody is asked how they are. Kirsty says the second rule took some explaining to colleagues, and that the point is that a person who is asked how they are must either lie or begin a conversation they may not want.\nThe practice has tried to measure the effect and has been honest about the difficulty. Appointments among regular attenders fell by about a fifth in two years, which sounds convincing and cannot be separated from the possibility that people willing to join such a group were improving anyway.\nWhat Kirsty offers instead is an observation. Eleven members have been coming for more than three years, and four of them now meet outside the group as well, which she regards as the actual outcome, and which no health measurement she has been given is able to record.",
    questions: [
      { q: "How do most members come to the group?", options: ["They are invited by friends","They apply online","They are sent by a doctor","They see a poster"], answer: 2, explanation: "'Most of them were sent there by a doctor.'" },
      { q: "What had Kirsty noticed?", options: ["The health centre had spare rooms","Sewing skills were disappearing","Patients could not afford clothes","Many patients spoke to nobody at weekends"], answer: 3, explanation: "'The group was set up in 2019 by a practice nurse, Kirsty Mbeki, who had noticed how many of her appointments were with people whose main problem was that they spoke to nobody from Friday to Monday.'" },
      { q: "Why is the group not presented as being about health?", options: ["People told to attend for wellbeing usually do not","The health centre forbids it","Members find it embarrassing","Health groups are expensive"], answer: 0, explanation: "'People who are told to attend something for their wellbeing, she says, mostly do not, and those who do arrive expecting to be improved.'" },
      { q: "What is one of the group's rules?", options: ["Members take turns to teach","Nobody is asked how they are","Members must attend weekly","Everyone must finish a project"], answer: 1, explanation: "'Nobody is asked why they are there.'" },
      { q: "What does Kirsty say about the fall in appointments?", options: ["It was too small to matter","It proves the group works","It cannot be separated from other explanations","It was caused by staff shortages"], answer: 2, explanation: "'Appointments among regular attenders fell by about a fifth in two years, which sounds convincing and cannot be separated from the possibility that people willing to join such a group were improving anyway.'" },
      { q: "What does she regard as the real outcome?", options: ["The number of new members","The items made for the hospital","The quality of the sewing","Members meeting outside the group"], answer: 3, explanation: "'Eleven members have been coming for more than three years, and four of them now meet outside the group as well, which she regards as the actual outcome, and which no health measurement she has been given is able to record.'" }
    ]
  },
  {
    id: "pet-rmc23-05",
    title: "The Island School With Nine Pupils",
    text: "There are nine children at the school on Innisbeg, aged between four and eleven, taught by one teacher and one assistant in a single room built in 1897.\nThe teacher, Ronan Delaney, moved from a city school with four hundred and ninety pupils. He says the differences are not the ones people expect. The workload is heavier rather than lighter, because he plans for seven year groups every day, and he has nobody in the next room to ask.\nWhat works remarkably well is the mixing of ages. The older children explain things to the younger ones constantly, which is the most reliable way of finding out whether somebody understands something, and the younger ones hear material two or three years ahead of themselves for years before they meet it formally.\nThe difficulties are social rather than academic. Nine children cannot form a football team. A child who falls out with the only other child of their age has nowhere else to go for the rest of the year, and Ronan says managing that is the part of the job he was least prepared for.\nThe school works hard at contact with the mainland. There are four joint days a year with a school in the nearest town, video lessons in two subjects, and a week of activities each June that the island children attend on the mainland.\nThe school has closed twice in its history and reopened both times. Its future depends on arithmetic that has nothing to do with education: the island needs young families, young families need housing, and housing on the island is bought as holiday property at prices no islander can pay.\nRonan says the parents understand this better than any visiting official. Every one of them, he says, can name the exact number of children who will start school in each of the next five years.",
    questions: [
      { q: "How is the school organised?", options: ["Nine children in one room with one teacher", "Two classes with two teachers", "Children taught by video only", "Nine children in separate year groups"], answer: 0, explanation: "'There are nine children at the school on Innisbeg, aged between four and eleven, taught by one teacher and one assistant in a single room built in 1897.'" },
      { q: "What does Ronan say about the workload?", options: ["It is much lighter", "It is heavier than in a big school", "It is about the same", "It varies by term"], answer: 1, explanation: "'The workload is heavier rather than lighter, because he plans for seven year groups every day, and he has nobody in the next room to ask.'" },
      { q: "What advantage does mixing ages bring?", options: ["Fewer resources are needed","Children finish school earlier","Older children explain things to younger ones","Lessons are shorter"], answer: 2, explanation: "'The older children explain things to the younger ones constantly, which is the most reliable way of finding out whether somebody understands something, and the younger ones hear material two or three years ahead of themselves for years before they meet it formally.'" },
      { q: "What is the main difficulty?", options: ["The age of the building","Lack of equipment","Academic standards","Social problems between children"], answer: 3, explanation: "'A child who falls out with the only other child of their age has nowhere else to go for the rest of the year, and Ronan says managing that is the part of the job he was least prepared for.'" },
      { q: "What threatens the school's future?", options: ["Housing being bought as holiday property","Parents moving away for work","Falling standards","The cost of the teacher"], answer: 0, explanation: "'Its future depends on arithmetic that has nothing to do with education: the island needs young families, young families need housing, and housing on the island is bought as holiday property at prices no islander can pay.'" },
      { q: "What does Ronan say about the parents?", options: ["They are all from the mainland","They know exactly how many children will start each year","They want the school to close","They rarely discuss the school"], answer: 1, explanation: "'Every one of them, he says, can name the exact number of children who will start school in each of the next five years.'" }
    ]
  },
  {
    id: "pet-rmc23-06",
    title: "The Night the River Rose",
    text: "The river at Aldbourne rose two metres in five hours on a Sunday night in February, and by Monday morning water was standing in sixty-one houses. What is remembered locally is not the flood itself but the fifty minutes of warning.\nThe warning came from a system the village had built for itself in 2016 after a smaller flood. Three simple depth sensors were placed upstream, one of them twenty-two kilometres away, sending readings every fifteen minutes to a computer in the village hall. When the upstream gauge passed a level agreed in advance, twenty-six volunteers received a message and began telephoning a list.\nThe national warning service covers the river and issued its own alert. It arrived forty minutes later than the village system, which is not a criticism, since a national service must be certain before it warns thousands of people, and certainty takes time.\nIn fifty minutes a great deal can be done. Cars were moved to higher ground and almost none were lost. Ground-floor rooms were cleared of what could be carried, two residents on oxygen were taken out early, and the primary school's records and computers were moved upstairs by nine people in eleven minutes.\nThe flood still caused about four million pounds of damage. Insurance assessors later estimated that the warning reduced the loss by roughly a third, and the village's system had cost eleven thousand pounds.\nWhat the organisers stress to the many other villages that have contacted them is the least technical part. The sensors were the easy bit. The list of who telephones whom, kept current for nine years, checked twice a year, with a named substitute for every volunteer, is the part that takes work, and it is the part that made fifty minutes into something useful.",
    questions: [
      { q: "What is remembered most about the flood?", options: ["The speed of the repairs","The height of the water","The fifty minutes of warning","The damage to the school"], answer: 2, explanation: "'What is remembered locally is not the flood itself but the fifty minutes of warning.'" },
      { q: "How did the village system work?", options: ["The council telephoned residents","A siren sounded automatically","Volunteers watched the river","Sensors upstream sent readings to the village hall"], answer: 3, explanation: "'Three simple depth sensors were placed upstream, one of them twenty-two kilometres away, sending readings every fifteen minutes to a computer in the village hall.'" },
      { q: "Why did the national warning arrive later?", options: ["It must be certain before warning many people","It did not cover the river","The message was delayed by weather","Its equipment had failed"], answer: 0, explanation: "'It arrived forty minutes later than the village system, which is not a criticism, since a national service must be certain before it warns thousands of people, and certainty takes time.'" },
      { q: "What was done during the warning time?", options: ["The river was diverted", "Cars were moved and rooms cleared", "The school was closed for a week", "Sandbags were built into a wall"], answer: 1, explanation: "'Cars were moved to higher ground and almost none were lost.'" },
      { q: "What did assessors estimate?", options: ["The system cost too much","The flood was worse than expected","The warning cut losses by about a third","The warning made no difference"], answer: 2, explanation: "'Insurance assessors later estimated that the warning reduced the loss by roughly a third, and the village's system had cost eleven thousand pounds.'" },
      { q: "What do the organisers say is the hardest part?", options: ["Finding funding","Getting council permission","Installing the sensors","Keeping the telephone list current"], answer: 3, explanation: "'The sensors were the easy bit.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
