/* PET Prep bank: Reading true/false/not given (B1) — wave 9 */
(function () {
var BANK = [
  {
    id: "p-rtfng9-01",
    title: "Why Some Cheese Has Holes",
    text: "The holes in certain cheeses are made by gas. During ripening, particular bacteria consume lactic acid and release carbon dioxide, and because the cheese is firm the gas cannot escape, so it collects in pockets that grow slowly over weeks.\nFor most of the twentieth century that was the whole explanation, and it left one question unanswered: why the number of holes had been falling steadily since the 1950s. Cheesemakers had noticed the change and blamed cleaner equipment, without being able to say why cleanliness would matter.\nResearch published in 2015 supported them. The gas needs somewhere to start collecting, and the study found that tiny particles of hay dust, present in milk collected in open buckets, provided exactly that. When milking moved to closed steel systems, the dust disappeared and so did many of the holes. Adding a controlled amount of fine particles back into the milk restored them.\nThe size of the holes depends on temperature and time. A warmer ripening room produces more gas and larger holes, and the size is regulated by law in some countries, because a hole that is too large causes problems in slicing machines and a cheese sold by weight with more air in it is a commercial matter as well as a culinary one.\nNot all holes are the same. Small irregular openings in some cheeses are not gas at all; they are gaps left where the pieces of curd did not press together completely, which is a different process with a different name.\nA cheese with no holes is not a failed cheese. Most of the world's cheeses have never had any, and the varieties that do are a small and geographically limited group.",
    questions: [
      { q: "The holes are formed by gas produced during ripening.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - bacteria 'consume lactic acid and release carbon dioxide'." },
      { q: "The number of holes has increased since the 1950s.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the number of holes had been falling steadily since the 1950s'." },
      { q: "Research supported the cheesemakers' suspicion about cleanliness.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Research published in 2015 supported them.'" },
      { q: "Hay dust in milk helped the gas to collect.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - hay dust 'provided exactly that'." },
      { q: "Hole size is unaffected by ripening temperature.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'A warmer ripening room produces more gas and larger holes'." },
      { q: "All openings in cheese are caused by gas.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - some are 'gaps left where the pieces of curd did not press together completely'." },
      { q: "Cheeses with holes are more expensive than those without.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - commercial issues are mentioned but no comparison of prices is made." }
    ]
  },
  {
    id: "p-rtfng9-02",
    title: "Who Gives Way at Sea",
    text: "Ships do not have lanes, and the rules that prevent them colliding are a set of agreed conventions rather than roads. They are international, they have been in their present form since 1972, and they are studied by anybody who takes a boat out legally.\nThe basic principle is that one vessel is the stand-on vessel and the other is the give-way vessel, and that both have duties. The give-way vessel must alter course early and clearly. The stand-on vessel must hold its course and speed, so that the other can predict what it will do, and must act only if it becomes obvious that nothing else is going to happen.\nWhich is which depends on the situation. Two power-driven vessels meeting head on both turn to their right. When they cross, the one that has the other on its right gives way. A vessel overtaking another must keep clear, whatever the two vessels are.\nThere is also an order of priority based on how easily a vessel can manoeuvre. A large ship in a narrow channel cannot get out of the way and is treated accordingly, and a vessel engaged in fishing with gear in the water has limited freedom to move.\nAt night, lights carry all of this information. A red light on the left side and a green on the right mean that a vessel showing red to you is crossing from your right, and the combination of lights visible tells an observer the type and direction of a vessel without any communication at all.\nThe most quoted of the rules is the last one in spirit: no rule excuses a collision, and anything necessary to avoid one must be done.",
    questions: [
      { q: "The rules for avoiding collisions at sea are international.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'They are international, they have been in their present form since 1972'." },
      { q: "Only the give-way vessel has responsibilities.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'both have duties'." },
      { q: "The stand-on vessel should normally maintain course and speed.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'must hold its course and speed'." },
      { q: "A vessel overtaking another has right of way.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'A vessel overtaking another must keep clear'." },
      { q: "Ability to manoeuvre affects priority.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - there is 'an order of priority based on how easily a vessel can manoeuvre'." },
      { q: "Lights indicate which side of a vessel is being seen.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'A red light on the left side and a green on the right'." },
      { q: "Most collisions at sea happen at night.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - night lights are described but no statistics on collisions are given." }
    ]
  },
  {
    id: "p-rtfng9-03",
    title: "What Banknotes Are Made Of",
    text: "Paper money has rarely been made of ordinary paper. For most of its history it was made of cotton and linen fibre, which is far stronger than wood pulp and survives being wet, folded and left in a pocket through a wash.\nSince the 1990s an increasing number of countries have moved to polymer, a thin flexible plastic. The change is not primarily about appearance. A polymer note lasts around two and a half times as long as a cotton one, which reduces both cost and the environmental impact of replacement, and it can carry security features that are extremely difficult to copy, including a completely transparent window.\nThe transparent window is the single most useful feature. It cannot be produced by any ordinary printing or photocopying process, and it can be checked by anybody in about a second without equipment.\nPolymer has disadvantages that were not fully anticipated. Notes stick together when new, which caused difficulties in counting machines and at cash desks in the first months of issue in several countries. They are also damaged by heat: a note left in a hot car or ironed will shrink and become unusable, which does not happen to cotton.\nCotton notes are not disappearing everywhere. Some central banks have decided that the higher initial cost of polymer is not justified at their volumes, and others have kept cotton for the highest denominations while moving lower ones to polymer.\nOld notes are usually shredded and then, in most countries, either burned for energy or composted. A small number of central banks sell shredded material to the public in sealed packets, which raises a negligible amount of money and generates a surprising amount of interest.",
    questions: [
      { q: "Traditional banknotes were made from wood pulp.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - they were 'made of cotton and linen fibre'." },
      { q: "Polymer notes last considerably longer than cotton ones.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'A polymer note lasts around two and a half times as long as a cotton one'." },
      { q: "The transparent window can be checked without any equipment.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'can be checked by anybody in about a second without equipment'." },
      { q: "Polymer notes are unaffected by heat.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'a note left in a hot car or ironed will shrink and become unusable'." },
      { q: "New polymer notes caused problems with counting machines.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - notes stick together when new, which 'caused difficulties in counting machines'." },
      { q: "Some countries use polymer for low values and cotton for high ones.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - others 'have kept cotton for the highest denominations while moving lower ones to polymer'." },
      { q: "Australia was the first country to issue polymer notes.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the move to polymer since the 1990s is described, but no country is named as the first." }
    ]
  },
  {
    id: "p-rtfng9-04",
    title: "Before Everybody Agreed What Time It Was",
    text: "Until the middle of the nineteenth century, towns kept their own time. Noon was the moment the sun was highest in that particular place, which meant that a town fifty kilometres to the west was a few minutes behind its neighbour, and everybody found this perfectly workable because nobody travelled fast enough for it to matter.\nRailways ended it. A timetable requires a single time, and a train leaving one town at ten and arriving in another whose clocks read differently is a scheduling problem and, more seriously, a safety one, because two trains on one line must be somewhere definite at a definite moment.\nIn Britain the railway companies adopted a single time from 1840, taken from Greenwich and carried along the lines by telegraph. For some years towns kept two times: the railway time and their own, and a number of public clocks were fitted with two minute hands to show both.\nLegal recognition came much later, in 1880. In the United States, time zones were introduced by the railways in 1883 and the government did not formalise them until 1918.\nThe international system of zones was agreed at a conference in 1884, which fixed the prime meridian at Greenwich, a decision made partly because a large proportion of the world's shipping already used charts based on it.\nSome places do not use whole-hour offsets. Several countries use half-hour or quarter-hour differences, and one country uses a single time zone across a distance that would naturally cover five, which produces sunrise at very different clock times across its territory.",
    questions: [
      { q: "Before the railways, each town kept its own local time.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Until the middle of the nineteenth century, towns kept their own time.'" },
      { q: "Local time differences caused problems before the railways existed.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'everybody found this perfectly workable because nobody travelled fast enough for it to matter'." },
      { q: "Some public clocks displayed two different times.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'a number of public clocks were fitted with two minute hands to show both'." },
      { q: "British law recognised standard time in 1840.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'Legal recognition came much later, in 1880.'" },
      { q: "American time zones were created by railway companies first.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'time zones were introduced by the railways in 1883'." },
      { q: "Shipping charts influenced the choice of the prime meridian.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'a large proportion of the world's shipping already used charts based on it'." },
      { q: "More than twenty countries attended the 1884 conference.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the conference and its decision are described, but the number of countries present is never stated." }
    ]
  },
  {
    id: "p-rtfng9-05",
    title: "What Happens to a Glass Bottle",
    text: "Glass is one of the few materials that can be recycled repeatedly without any loss of quality. A bottle can become a bottle indefinitely, which is not true of paper or of most plastics.\nThe process begins with sorting by colour, which matters more than most people realise. Clear glass contaminated with even a small proportion of green or brown cannot be made clear again, so mixed glass is used for green bottles or for aggregate rather than for new clear ones. This is why some collection systems separate colours at the kerbside and others sort them mechanically later using optical scanners.\nAfter sorting, the glass is crushed into small pieces called cullet, cleaned, and melted with raw materials. Every tonne of cullet used replaces about a tonne and a fifth of raw material, and, more importantly, melts at a lower temperature. A furnace running on a high proportion of cullet uses noticeably less energy, which is the main environmental benefit and is larger than the saving in raw material.\nSome things must not go into glass recycling. Window glass, drinking glasses and ovenware are made to different formulas and melt at different temperatures, and a single heat-resistant dish can spoil a whole batch. Ceramics are worse still, because they do not melt at all and leave hard fragments in the finished glass.\nBottles that are returned and refilled rather than melted are better again, and this system remains common in several countries. A refillable bottle is heavier and more expensive to make and can be reused twenty or thirty times before it is finally melted down.",
    questions: [
      { q: "Glass can be recycled repeatedly without losing quality.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it is recycled 'repeatedly without any loss of quality'." },
      { q: "Mixed-colour glass can be made into clear bottles.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - contaminated clear glass 'cannot be made clear again'." },
      { q: "Using cullet lowers the temperature needed in the furnace.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - cullet 'melts at a lower temperature'." },
      { q: "The saving in raw material is greater than the energy saving.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the energy benefit 'is larger than the saving in raw material'." },
      { q: "Ovenware should not be put in with bottles.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'a single heat-resistant dish can spoil a whole batch'." },
      { q: "Refillable bottles can be used many times before melting.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'can be reused twenty or thirty times'." },
      { q: "Optical sorting equipment has become cheaper in recent years.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - optical scanners are mentioned but their cost is not." }
    ]
  },
  {
    id: "p-rtfng9-06",
    title: "Why Aircraft Fly So High",
    text: "A passenger aircraft cruises at around eleven kilometres, which is above almost all weather and about a third of the way to the point where the atmosphere effectively ends. The height is chosen for reasons of efficiency rather than comfort or safety.\nAir at that height is roughly a quarter as dense as at sea level. Thin air produces less drag, so an aircraft moving through it uses considerably less fuel for the same speed. The limit is that engines need air to burn fuel and wings need air to produce lift, and above a certain height there is not enough of either.\nThe most efficient height therefore rises during a flight. As fuel is burned the aircraft becomes lighter and can fly higher, which is why long flights often climb in steps of about six hundred metres rather than cruising at one level, a practice sometimes visible on flight tracking maps.\nHeight has other advantages. Most weather occurs below it, so flights are smoother; there is space between aircraft; and altitude gives time, because an aircraft at eleven kilometres that loses all engine power can glide for well over a hundred and fifty kilometres.\nThe cabin is pressurised to a level equivalent to about two thousand four hundred metres, not to sea level, because a smaller difference means less stress on the structure. This is why some passengers notice mild effects on long flights, and why food is often described as tasting different, since the combination of low pressure and very dry air reduces the sense of taste noticeably.\nNewer aircraft made largely of composite material are pressurised to a lower equivalent altitude, which is one of the few changes in modern flying that passengers can genuinely feel.",
    questions: [
      { q: "Aircraft fly high mainly to avoid turbulence.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'The height is chosen for reasons of efficiency rather than comfort or safety.'" },
      { q: "Thinner air reduces drag on the aircraft.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Thin air produces less drag'." },
      { q: "The best cruising height changes during a flight.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'The most efficient height therefore rises during a flight.'" },
      { q: "An aircraft losing all engine power can glide a long distance.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'can glide for well over a hundred and fifty kilometres'." },
      { q: "Cabins are pressurised to sea-level conditions.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the cabin is pressurised 'to a level equivalent to about two thousand four hundred metres, not to sea level'." },
      { q: "Low pressure and dry air affect the sense of taste.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - the combination 'reduces the sense of taste noticeably'." },
      { q: "Composite aircraft use less fuel than metal ones.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - composite aircraft are mentioned only in relation to cabin pressure." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
