/* PET Prep bank: Reading multiple choice (B1) — wave 13 */
(function () {
var BANK = [
  {
    id: "pet-rmc13-01",
    title: "Swimming in the Harbour in January",
    text: "At seven o'clock on a January morning, when the air is around two degrees, between thirty and fifty people walk down the steps at Ganton Harbour and get into the sea. They stay in for between three and eight minutes. Then they stand on the quay drinking tea and, according to almost all of them, feel better than they have all week.\\n\\nThe group has no name and no membership. It began in 2018 with four friends and grew mostly by people watching from the harbour wall and eventually asking how to start.\\n\\nThe advice they give is always the same and is mainly about safety. Never swim alone. Get in slowly rather than jumping, because cold water makes people gasp, and gasping under water is what actually kills. Stay much less time than you think you can, since the danger comes after you get out, when blood that has been kept away from the skin returns to it. Most of the group leave the water while they still feel fine.\\n\\nWhat the cold does to the body is well understood, and what it does to the mood is less so. Several studies suggest a real effect on mood, though they are small, and one of the swimmers, a doctor called Priya Ferreira, is careful to say that a group of people who meet outdoors at dawn and talk for half an hour would probably feel better anyway.\\n\\nThe group has two firm rules and both are social. Nobody comments on anybody's body, and nobody is congratulated for staying in longer. Priya says the second rule was added after a difficult winter in which two people clearly stayed in too long.\\n\\nIn July, when the water is pleasant, attendance falls by about half.",
    questions: [
      { q: "How long do the swimmers usually stay in the water?", options: ["Between three and eight minutes","As long as they can manage","Until they feel cold","About half an hour"], answer: 0, explanation: "'They stay in for between three and eight minutes.'" },
      { q: "How did the group grow?", options: ["Through a swimming club","People watched and then asked to join","A newspaper article","Through advertising"], answer: 1, explanation: "'It began in 2018 with four friends and grew mostly by people watching from the harbour wall and eventually asking how to start.'" },
      { q: "Why should swimmers enter the water slowly?", options: ["To warm up gradually","To check the depth","To avoid gasping under water","To keep the water calm"], answer: 2, explanation: "'Get in slowly rather than jumping, because cold water makes people gasp, and gasping under water is what actually kills.'" },
      { q: "When is the most dangerous moment?", options: ["While walking to the steps","On entering the water","In the middle of the swim","After leaving the water"], answer: 3, explanation: "'Stay much less time than you think you can, since the danger comes after you get out, when blood that has been kept away from the skin returns to it.'" },
      { q: "What does Dr Ferreira point out about the effect on mood?", options: ["Meeting and talking outdoors might explain it","It only affects new swimmers","It disappears in summer","It has been fully proved"], answer: 0, explanation: "'Several studies suggest a real effect on mood, though they are small, and one of the swimmers, a doctor called Priya Ferreira, is careful to say that a group of people who meet outdoors at dawn and talk for half an hour would probably feel better anyway.'" },
      { q: "Why was the second social rule introduced?", options: ["Someone had been rude about a swimmer","Some swimmers had stayed in too long","New members were arriving late","People were competing over distance"], answer: 1, explanation: "'Priya says the second rule was added after a difficult winter in which two people clearly stayed in too long.'" }
    ]
  },
  {
    id: "pet-rmc13-02",
    title: "The Man Who Counts Birds",
    text: "Every Sunday morning since 1994, Warren Ashfield has walked the same four-kilometre path along the river and written down every bird he sees. He has never missed a week. He has done it with a broken wrist, on the morning of his daughter's wedding, and twice in weather in which nobody else was outdoors at all.\\n\\nThe count takes two hours, and he is precise about how it is done. Same route, same direction, same start time, and no counting of anything heard but not seen. Consistency, he says, is the only thing that makes such records worth anything: a survey done differently each week measures the surveyor rather than the birds.\\n\\nHis notebooks now cover thirty-one years, and they show things that no shorter study could. One species that appeared in nearly every count until about 2004 has not been recorded since 2011. Another, unknown on the river when he started, is now seen most weeks. Neither change was noticed by anybody at the time, because both happened at a speed of a few birds a year.\\n\\nUniversity researchers began using his data in 2015. What made it valuable was not the number of birds but the number of Sundays: statistical methods can do a great deal with a long unbroken series and very little with an occasional one.\\n\\nWarren is seventy-six. He has been training a replacement for two years, a woman in her thirties who works shifts and can manage most Sundays, and he says the handover is the only part of the whole project that has ever worried him.\\n\\nHe does not describe himself as a birdwatcher and dislikes the word. He describes what he does as writing down what is there, which he says anybody could do and almost nobody does for thirty years.",
    questions: [
      { q: "What has Warren done every Sunday since 1994?", options: ["Written a nature diary","Photographed the river","Counted the birds on a fixed route","Led a walking group"], answer: 2, explanation: "'Every Sunday morning since 1994, Warren Ashfield has walked the same four-kilometre path along the river and written down every bird he sees.'" },
      { q: "Why does he keep the method exactly the same?", options: ["It makes the walk easier","It saves time","The university requires it","Otherwise the results measure the observer"], answer: 3, explanation: "'Consistency, he says, is the only thing that makes such records worth anything: a survey done differently each week measures the surveyor rather than the birds.'" },
      { q: "What do his notebooks reveal?", options: ["Slow changes nobody noticed at the time", "That bird numbers stay constant", "That the river is polluted", "That birds prefer certain weather"], answer: 0, explanation: "'Neither change was noticed by anybody at the time, because both happened at a speed of a few birds a year.'" },
      { q: "Why is his data valuable to researchers?", options: ["He counted rare species", "The series is long and unbroken", "He used scientific equipment", "He covered a large area"], answer: 1, explanation: "'What made it valuable was not the number of birds but the number of Sundays: statistical methods can do a great deal with a long unbroken series and very little with an occasional one.'" },
      { q: "What has worried Warren about the project?", options: ["The cost of notebooks", "Losing interest", "Handing the count over to somebody else", "Changes to the path"], answer: 2, explanation: "'He has been training a replacement for two years, a woman in her thirties who works shifts and can manage most Sundays, and he says the handover is the only part of the whole project that has ever worried him.'" },
      { q: "How does Warren describe what he does?", options: ["Protecting the river","Scientific research","Birdwatching as a hobby","Simply writing down what is there"], answer: 3, explanation: "'He describes what he does as writing down what is there, which he says anybody could do and almost nobody does for thirty years.'" }
    ]
  },
  {
    id: "pet-rmc13-03",
    title: "My First Month in a New Country",
    text: "I arrived in February with two suitcases, a phone that did not work, and enough of the language to order coffee and to say that I did not understand. I had expected the first month to be difficult in obvious ways. It was difficult in ways I had not imagined at all.\\n\\nThe obvious things were easier than I feared. Finding a room took nine days. Opening a bank account took an afternoon, once somebody explained which document I needed, which nobody had thought to mention because everybody here is given it at birth.\\n\\nWhat exhausted me was smaller. In my own language I know how polite to be. I know the difference between the way you speak to a neighbour and the way you speak to somebody selling you a bus ticket. Here I had one register, and it was slightly too formal for everything, so for a month I sounded, a friend told me later, like a person reading from a letter.\\n\\nI also stopped being funny. This is the loss that nobody warns you about and the one that made me consider going home in the third week. Everything I said arrived as a plain sentence, and the person I am in my own language, who talks quickly and makes jokes, simply did not exist here.\\n\\nWhat helped was a Tuesday evening cookery class. The teacher spoke fast and did not slow down for me, and there was no way to be polite about a burnt onion. In eight weeks I understood more from that room than from four months of an online course.\\n\\nI have been here three years. I am funny again, though in a different way, and I have noticed that I am gentler with people whose sentences come out slowly, which I certainly was not before.",
    questions: [
      { q: "What did the writer expect about the first month?", options: ["That it would be difficult in obvious ways", "That it would be easy", "That the language would be no problem", "That finding a room would be impossible"], answer: 0, explanation: "'I had expected the first month to be difficult in obvious ways.'" },
      { q: "Why was opening a bank account complicated at first?", options: ["The banks were closed", "Nobody mentioned a document everybody local already has", "The writer had no address", "The writer's phone did not work"], answer: 1, explanation: "'Opening a bank account took an afternoon, once somebody explained which document I needed, which nobody had thought to mention because everybody here is given it at birth.'" },
      { q: "What tired the writer most?", options: ["Travelling around the city", "Finding somewhere to live", "Having only one level of politeness in the language", "Working long hours"], answer: 2, explanation: "'Here I had one register, and it was slightly too formal for everything, so for a month I sounded, a friend told me later, like a person reading from a letter.'" },
      { q: "Which loss almost made the writer go home?", options: ["Missing family","The cold weather","Losing contact with friends","Being unable to be funny"], answer: 3, explanation: "'This is the loss that nobody warns you about and the one that made me consider going home in the third week.'" },
      { q: "Why was the cookery class helpful?", options: ["Real conversation happened at normal speed","The other students were foreign too","The teacher spoke slowly and clearly","It was cheaper than a language course"], answer: 0, explanation: "'The teacher spoke fast and did not slow down for me, and there was no way to be polite about a burnt onion.'" },
      { q: "How has the writer changed after three years?", options: ["Fluent in four languages","More patient with slow speakers","Less interested in language","Keen to return home"], answer: 1, explanation: "'I am funny again, though in a different way, and I have noticed that I am gentler with people whose sentences come out slowly, which I certainly was not before.'" }
    ]
  },
  {
    id: "pet-rmc13-04",
    title: "The Kitchen That Cooks for a Street",
    text: "In a former shop on Anderby Road, four people cook one meal a day for about ninety households. There is no menu, no choice, and no restaurant. Everything is collected in containers between five and seven in the evening.\\n\\nThe kitchen was started by Selin Aydemir, who had noticed something about her own street. Most households were cooking small quantities separately every evening, which is the least efficient way food can possibly be prepared. Buying for ninety and cooking once uses roughly a third of the energy and about half the ingredients per person.\\n\\nCustomers pay a monthly amount and receive a meal every weekday. The price works out at less than most people spend on ingredients alone, and Selin is open about why: the saving comes almost entirely from buying in quantity and from having no waste, since the number of meals is known a week in advance.\\n\\nThe hardest part was not the cooking. It was persuading people to give up choice. In the first year, about half of those who joined left within two months, almost all of them saying the same thing, which was that they did not like being told what they were eating. Those who stayed generally say the opposite after a while: that the removal of a daily decision was the main benefit.\\n\\nThe kitchen cooks meat twice a week and takes account of about thirty dietary requirements, which is manageable, and refuses individual preferences, which would not be. Somebody who dislikes mushrooms is told, politely, that Thursdays will sometimes be difficult.\\n\\nSelin has been asked whether the model could work anywhere. She thinks it needs a street where a hundred households live within four hundred metres, and she says that is the real limit, not cooking and not money.",
    questions: [
      { q: "What does the kitchen provide?", options: ["Meals only at weekends","A restaurant service","One meal a day, collected in containers","Ingredients for households to cook"], answer: 2, explanation: "'Everything is collected in containers between five and seven in the evening.'" },
      { q: "What had Selin noticed about her street?", options: ["Food was expensive locally","Many people ate in restaurants","Nobody cooked at all","Households cooked small amounts separately"], answer: 3, explanation: "'Most households were cooking small quantities separately every evening, which is the least efficient way food can possibly be prepared.'" },
      { q: "Where does the saving come from?", options: ["Buying in quantity and having no waste","Government support","Cheap ingredients of low quality","Unpaid volunteers"], answer: 0, explanation: "'The price works out at less than most people spend on ingredients alone, and Selin is open about why: the saving comes almost entirely from buying in quantity and from having no waste, since the number of meals is known a week in advance.'" },
      { q: "What was the biggest difficulty?", options: ["Cooking large quantities","Persuading people to give up choice","Hiring cooks","Finding a building"], answer: 1, explanation: "'It was persuading people to give up choice.'" },
      { q: "What do long-term members say?", options: ["The price should be lower","The food is better than they expected","Not deciding each day is the main benefit","They would like more choice"], answer: 2, explanation: "'Those who stayed generally say the opposite after a while: that the removal of a daily decision was the main benefit.'" },
      { q: "What does Selin see as the real limit on the idea?", options: ["Dietary requirements","The cost of equipment","Finding enough cooks","How many households live close together"], answer: 3, explanation: "'She thinks it needs a street where a hundred households live within four hundred metres, and she says that is the real limit, not cooking and not money.'" }
    ]
  },
  {
    id: "pet-rmc13-05",
    title: "The School That Starts at Ten",
    text: "Fairmount Academy begins lessons at ten past ten in the morning and finishes at twenty past four. It has done so since 2019, and it is one of a small number of schools in the country to have made this change and kept it.\\n\\nThe reason is biological rather than educational. During the teenage years the body's natural sleep timing shifts later by roughly two hours, which is not a matter of habit or willingness and cannot be corrected by going to bed earlier. A fifteen-year-old asked to concentrate at half past eight is, in terms of the body clock, in the position an adult would be in at half past six.\\n\\nThe school's head, Gordon Achebe, had read the research for years before acting. What finally decided him was a small experiment: for one term, the school moved its most demanding examinations to the afternoon and found a measurable difference in results.\\n\\nSince the change, absence has fallen by about a fifth and lateness by considerably more. Examination results improved in the first two years and have since stayed at the new level. Mr Achebe is careful, however, not to claim too much: the school made three other changes in the same period, and he says that separating the effects honestly is impossible.\\n\\nThe difficulties are practical and were underestimated. Buses are shared with other schools and had to be renegotiated. Sports fixtures against other schools now require students to leave lessons early. Some parents found the later finish impossible for childcare reasons, and about a dozen families moved their children to other schools.\\n\\nMr Achebe says the question he is asked most often by other head teachers is whether students simply go to bed later. The school surveyed this twice. On average they go to bed eleven minutes later and sleep about fifty minutes more.",
    questions: [
      { q: "When does the school day begin at Fairmount Academy?", options: ["At ten past ten","At nine o'clock","At twenty past four","At half past eight"], answer: 0, explanation: "'Fairmount Academy begins lessons at ten past ten in the morning and finishes at twenty past four.'" },
      { q: "Why was the change made?", options: ["It saved money on heating","Teenagers' body clocks shift later","Parents requested it","The buses arrived late"], answer: 1, explanation: "'During the teenage years the body's natural sleep timing shifts later by roughly two hours, which is not a matter of habit or willingness and cannot be corrected by going to bed earlier.'" },
      { q: "What finally persuaded the head teacher?", options: ["A visit to another school", "A survey of students", "An experiment with afternoon examinations", "Advice from doctors"], answer: 2, explanation: "'What finally decided him was a small experiment: for one term, the school moved its most demanding examinations to the afternoon and found a measurable difference in results.'" },
      { q: "Why is Mr Achebe cautious about the results?", options: ["The tests were not comparable","Only one year group was studied","The improvement was very small","Other changes were made at the same time"], answer: 3, explanation: "'Mr Achebe is careful, however, not to claim too much: the school made three other changes in the same period, and he says that separating the effects honestly is impossible.'" },
      { q: "Which problem was not expected?", options: ["Practical issues with buses and fixtures","A drop in examination entries","Students falling asleep in lessons","Teachers refusing the new hours"], answer: 0, explanation: "'The difficulties are practical and were underestimated.'" },
      { q: "What did the school's surveys show about bedtimes?", options: ["Students go to bed much later", "Bedtimes barely changed but sleep increased", "Students sleep less than before", "Bedtimes became earlier"], answer: 1, explanation: "'On average they go to bed eleven minutes later and sleep about fifty minutes more.'" }
    ]
  },
  {
    id: "pet-rmc13-06",
    title: "Working in Lost Property",
    text: "The lost property office of a large railway station receives about four hundred items a day. I worked in one for two years, and the question I was asked most often at parties was what the strangest object was. The honest answer is that after a month nothing is strange.\\n\\nUmbrellas and gloves arrive in quantities that are difficult to describe. So do single shoes, which nobody has ever adequately explained to me. We received, during my time there, a stuffed bear the size of a person, a set of false teeth, and a violin worth more than my annual salary, which was collected within two hours by a man who had run the whole way from another station.\\n\\nThe rules are strict and, at first, seem unkind. An item is held for three months. Nothing may be described to a caller: the caller must describe the item to us. This sounds unhelpful when somebody is upset on the telephone, and it exists because people who have lost nothing occasionally telephone to see what is available.\\n\\nWhat surprised me was how many items are never collected. Roughly two thirds are not, including things of real value. Bags are collected far more often than coats, and laptops far more often than phones, which we never satisfactorily explained.\\n\\nThe part of the job I remember is different from all of this. About once a fortnight somebody would come in for something small and worth nothing at all: a scarf, a book, a child's toy. Those were the people who cried. A woman once collected a supermarket carrier bag containing a jumper her mother had knitted, and could not speak for a minute.\\n\\nI stopped being able to walk past a lost glove on a pavement. I still pick them up and put them on walls, which does no good whatsoever.",
    questions: [
      { q: "What answer does the writer give about strange objects?", options: ["Most items are ordinary clothes","The office keeps a list of them","Nothing seems strange after a month","The strangest was a violin"], answer: 2, explanation: "'The honest answer is that after a month nothing is strange.'" },
      { q: "What happened with the violin?", options: ["It was sent to another station","It was never collected","It was sold after three months","Its owner collected it within two hours"], answer: 3, explanation: "'We received, during my time there, a stuffed bear the size of a person, a set of false teeth, and a violin worth more than my annual salary, which was collected within two hours by a man who had run the whole way from another station.'" },
      { q: "Why must callers describe the item themselves?", options: ["Because some callers have lost nothing","It is a legal requirement","To save time on the telephone","Because staff cannot see the items"], answer: 0, explanation: "'This sounds unhelpful when somebody is upset on the telephone, and it exists because people who have lost nothing occasionally telephone to see what is available.'" },
      { q: "What surprised the writer about collection?", options: ["Items are collected months later","Most items are never collected","Valuable items are collected fastest","Almost everything is collected"], answer: 1, explanation: "'Roughly two thirds are not, including things of real value.'" },
      { q: "Which people upset the writer most?", options: ["Those who came too late","Those who had lost expensive items","Those collecting things of no value","Those who were angry with staff"], answer: 2, explanation: "'About once a fortnight somebody would come in for something small and worth nothing at all: a scarf, a book, a child's toy.'" },
      { q: "How did the job change the writer's behaviour?", options: ["Keeping a list of belongings","Avoiding railway stations","Never losing anything","Picking up lost gloves in the street"], answer: 3, explanation: "'I still pick them up and put them on walls, which does no good whatsoever.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
