/* PET Prep bank: Reading multiple choice (B1) — wave 11 */
(function () {
var BANK = [
  {
    id: "pet-rmc11-01",
    title: "The Shop That Opens for Two Hours",
    text: "The only shop in Ferndale opens from ten until twelve, six days a week, and it is run by a rota of twenty-nine villagers, none of whom is paid.\n\nThe shop that was there before closed in 2017 after its owner retired and nobody bought the business. For eighteen months the nearest bread was eleven kilometres away, which is a short drive and an impossible journey for the fourteen households in the village without a car.\n\nThe replacement is not really a shop in the commercial sense. It occupies one room of the village hall, it stocks about two hundred items rather than the four thousand of a small supermarket, and it makes almost no profit, which is the intention. Prices are set to cover costs plus five per cent, and the five per cent has so far paid for a freezer and a new door.\n\nThe rota is the difficult part. Each volunteer works one morning a month and everybody agreed at the start that a shop opening unpredictably would be worse than no shop at all. So there is a system of reserves, and a rule that a volunteer who cannot attend is responsible for finding the replacement themselves rather than telling the organiser.\n\nThe two-hour opening was chosen after an argument. Some wanted longer hours, but the woman who set the shop up, a retired postmistress called Ruth Ambleside, insisted that a small commitment kept for years is worth more than a large one abandoned in a season. Nine years later, twenty-two of the original volunteers are still on the rota.\n\nThe shop takes about four hundred pounds a week. Ruth says the number that actually matters is different: on an average morning, eleven people come in, and roughly half of them speak to nobody else that day.",
    questions: [
      { q: "Who runs the shop in Ferndale?", options: ["Twenty-nine unpaid villagers","The village council","A small supermarket company","A retired postmistress alone"], answer: 0, explanation: "'The only shop in Ferndale opens from ten until twelve, six days a week, and it is run by a rota of twenty-nine villagers, none of whom is paid.'" },
      { q: "Why was the closure of the old shop a serious problem?", options: ["The building was needed for housing", "Fourteen households had no car", "The village hall was too small", "Nobody could bake bread"], answer: 1, explanation: "'For eighteen months the nearest bread was eleven kilometres away, which is a short drive and an impossible journey for the fourteen households in the village without a car.'" },
      { q: "How are prices decided?", options: ["Customers pay what they can","They match the nearest supermarket","They are set to cover costs plus five per cent","Volunteers decide each week"], answer: 2, explanation: "'Prices are set to cover costs plus five per cent, and the five per cent has so far paid for a freezer and a new door.'" },
      { q: "What must a volunteer do if they cannot work their shift?", options: ["Pay for a substitute","Tell the organiser as soon as possible","Close the shop that morning","Find their own replacement"], answer: 3, explanation: "'So there is a system of reserves, and a rule that a volunteer who cannot attend is responsible for finding the replacement themselves rather than telling the organiser.'" },
      { q: "Why did Ruth Ambleside insist on short opening hours?", options: ["A small commitment lasts longer than a large one","The shop had too little stock","The hall was needed in the afternoons","Volunteers were hard to find"], answer: 0, explanation: "'Some wanted longer hours, but the woman who set the shop up, a retired postmistress called Ruth Ambleside, insisted that a small commitment kept for years is worth more than a large one abandoned in a season.'" },
      { q: "Which figure does Ruth consider most important?", options: ["The number of volunteers remaining","How many customers speak to nobody else that day","The weekly takings","The number of items in stock"], answer: 1, explanation: "'Ruth says the number that actually matters is different: on an average morning, eleven people come in, and roughly half of them speak to nobody else that day.'" }
    ]
  },
  {
    id: "pet-rmc11-02",
    title: "Everyone at Work Learns to Sign",
    text: "At a furniture workshop in Salford, all nineteen employees can hold a conversation in sign language. Two of them are deaf. The other seventeen learned because of a decision the owner made six years ago that he now describes as the most useful thing he has ever done for the business.\n\nWhen Marcus Trent hired his first deaf employee, a joiner called Wesley, he did what most employers do. He booked an interpreter for meetings and assumed everything else would sort itself out. It did not. Wesley did his work perfectly well, but he missed the conversations at the machines, the jokes, and the quick decisions that are made between two people passing in a corridor, which is where most of a workshop's real information travels.\n\nMarcus's solution was expensive and slow. He paid for weekly classes for the whole staff during working hours for two years. Several employees were not enthusiastic at the beginning, and two left, although Marcus says neither of them left because of the classes.\n\nThe unexpected result was noise. A furniture workshop is extremely loud, and until then everybody had been shouting, stopping machines, or waiting. Now instructions are given across a room full of running saws without anybody switching anything off, and Marcus estimates the workshop is measurably faster than it was.\n\nA second deaf employee joined in 2021 and was, she says, the first person interviewed for a job in her own language by a hearing manager. She had expected to spend her first month explaining herself.\n\nMarcus is careful about how he talks about this. He does not think of it as kindness, and he is uncomfortable when local newspapers describe it that way. He hired somebody, he says, and then made it possible for that person to actually do the job, which is what hiring means.",
    questions: [
      { q: "How many employees at the workshop can sign?", options: ["Only the two deaf employees", "About half", "All nineteen", "Seventeen of them"], answer: 2, explanation: "'At a furniture workshop in Salford, all nineteen employees can hold a conversation in sign language.'" },
      { q: "What problem did Wesley have at first?", options: ["The interpreter was often absent","He was given the wrong tools","He could not do the work","He missed informal conversation and quick decisions"], answer: 3, explanation: "'Wesley did his work perfectly well, but he missed the conversations at the machines, the jokes, and the quick decisions that are made between two people passing in a corridor, which is where most of a workshop's real information travels.'" },
      { q: "What did Marcus do about it?", options: ["He paid for classes for all staff during work hours", "He moved Wesley to a quieter room", "He hired a full-time interpreter", "He asked staff to learn in their own time"], answer: 0, explanation: "'He paid for weekly classes for the whole staff during working hours for two years.'" },
      { q: "What unexpected benefit did signing bring?", options: ["Lower training costs", "Communication despite the noise of machines", "Fewer accidents", "More customers"], answer: 1, explanation: "'Now instructions are given across a room full of running saws without anybody switching anything off, and Marcus estimates the workshop is measurably faster than it was.'" },
      { q: "What was different about the second deaf employee's interview?", options: ["It was held online", "It lasted much longer than usual", "It was conducted in her own language", "It was arranged by a charity"], answer: 2, explanation: "'A second deaf employee joined in 2021 and was, she says, the first person interviewed for a job in her own language by a hearing manager.'" },
      { q: "How does Marcus describe what he did?", options: ["As an experiment that might fail","As an act of kindness","As good publicity","As simply making it possible to do the job"], answer: 3, explanation: "'He hired somebody, he says, and then made it possible for that person to actually do the job, which is what hiring means.'" }
    ]
  },
  {
    id: "pet-rmc11-03",
    title: "The Race With No Winner",
    text: "On the first Sunday of every month, about two hundred people run five kilometres around Ashley Park. Nobody is timed, there are no numbers, and the organisers refuse to publish any list of finishers.\n\nThe event was set up by two sisters, Bea and Marguerite Alloway, who had both run in ordinary races for years. Their complaint was not with competition itself. It was that a timed race, however friendly, sorts everybody present into an order, and that this order is the thing most people take home.\n\nSo their event removed the clock. Runners set off in whatever group they like, and the only instruction is that everybody waits at the finish until the last person arrives, which usually takes about fifty-five minutes. Nobody leaves early. That rule, Bea says, is the entire event, and the rest is decoration.\n\nAt first, experienced runners were the ones who complained. Several said the run was pointless without a time, and a few ran with their own watches, which is allowed but not encouraged. Most of them stopped coming. What replaced them was a group the sisters had not planned for: people who had not run since school, people recovering from illness, and a large number of people over sixty.\n\nThe organisers do keep one record, which is the number of people who attend more than six times. Of the four hundred and ten who have come at least once, one hundred and ninety have come back at least six times, a rate that Marguerite says would be extraordinary for a timed event.\n\nThey have been asked to expand to other parks and have refused every time. A second event, Bea argues, would need organisers who understood why there is no clock, and she says she has not yet met anybody outside her own family who does.",
    questions: [
      { q: "What is unusual about the event in Ashley Park?", options: ["Runners are not timed","It is longer than most races","Only local people may enter","It takes place at night"], answer: 0, explanation: "'Nobody is timed, there are no numbers, and the organisers refuse to publish any list of finishers.'" },
      { q: "What was the sisters' objection to ordinary races?", options: ["They are too competitive for children","They put everybody into an order","They are held too early in the morning","They cost too much to enter"], answer: 1, explanation: "'It was that a timed race, however friendly, sorts everybody present into an order, and that this order is the thing most people take home.'" },
      { q: "What is the event's only rule?", options: ["Runners must start together","Runners must finish within an hour","Everybody waits for the last runner","Nobody may wear a watch"], answer: 2, explanation: "'Runners set off in whatever group they like, and the only instruction is that everybody waits at the finish until the last person arrives, which usually takes about fifty-five minutes.'" },
      { q: "Who complained at the beginning?", options: ["Parents of young children","Local residents","Park staff","Experienced runners"], answer: 3, explanation: "'At first, experienced runners were the ones who complained.'" },
      { q: "What record do the organisers keep?", options: ["How many people attend more than six times","The ages of all participants","How far each person runs","The fastest time each month"], answer: 0, explanation: "'The organisers do keep one record, which is the number of people who attend more than six times.'" },
      { q: "Why have the sisters refused to open events elsewhere?", options: ["The parks have refused permission","They have not found organisers who understand the idea","They are too busy with the first event","They cannot afford it"], answer: 1, explanation: "'A second event, Bea argues, would need organisers who understood why there is no clock, and she says she has not yet met anybody outside her own family who does.'" }
    ]
  },
  {
    id: "pet-rmc11-04",
    title: "Bread That Takes Three Days",
    text: "A loaf in a supermarket can be mixed, risen, baked and wrapped in under four hours. At a bakery in Coldwell the same weight of bread takes three days, and the owner, Idris Vaughn, will not shorten the process for anybody.\n\nThe difference is not the ingredients, which are flour, water, salt and nothing else. It is the waiting. After mixing, the dough is left in a cool room for about twenty hours before it is shaped, and after shaping it rests overnight again. Almost nothing appears to happen during this time, which is why the method disappeared from most bakeries in the 1960s.\n\nWhat happens is chemical. Slow rising changes the structure of the dough in ways that fast rising does not, and a number of customers who avoid ordinary bread find they can eat Idris's without difficulty. He is very careful not to make medical claims about this and always tells such customers to speak to a doctor first.\n\nThe business model is unusual. Because the bread must be started three days early, Idris cannot respond to demand, so almost everything is ordered and paid for in advance. He bakes two hundred and forty loaves on Wednesdays and Saturdays and no more, and there is a waiting list of about six weeks.\n\nHe employs nobody. This is deliberate, and he explains that the timings are the problem: a bakery that starts work at four in the morning three days a week cannot offer anybody sensible employment, and he is not willing to pretend otherwise.\n\nIdris was an engineer until he was forty-one. He says that people expect a story about escaping an office, and that the truth is duller. He read one article about slow fermentation, could not stop thinking about it for a year, and eventually accepted that this was not going to pass.",
    questions: [
      { q: "How long does Idris's bread take to make?", options: ["Four hours", "One day", "Three days", "Six weeks"], answer: 2, explanation: "'At a bakery in Coldwell the same weight of bread takes three days, and the owner, Idris Vaughn, will not shorten the process for anybody.'" },
      { q: "What makes his bread different from supermarket bread?", options: ["A special oven","The type of flour only","Unusual ingredients","The long waiting time"], answer: 3, explanation: "'The difference is not the ingredients, which are flour, water, salt and nothing else.'" },
      { q: "Why did this method largely disappear?", options: ["Nothing seems to happen during the long waits","Ovens changed","The bread tasted worse","Ingredients became expensive"], answer: 0, explanation: "'Almost nothing appears to happen during this time, which is why the method disappeared from most bakeries in the 1960s.'" },
      { q: "What does Idris say to customers who find his bread easier to eat?", options: ["That they should buy more","That they should speak to a doctor","That the flour is medically tested","That all slow bread is the same"], answer: 1, explanation: "'He is very careful not to make medical claims about this and always tells such customers to speak to a doctor first.'" },
      { q: "Why must customers order in advance?", options: ["To keep prices low","The bakery is difficult to find","Baking starts three days before collection","The bank requires it"], answer: 2, explanation: "'Because the bread must be started three days early, Idris cannot respond to demand, so almost everything is ordered and paid for in advance.'" },
      { q: "Why does Idris employ nobody?", options: ["There are no trained bakers nearby","He cannot afford wages","He prefers working alone","The working hours would be unreasonable for staff"], answer: 3, explanation: "'This is deliberate, and he explains that the timings are the problem: a bakery that starts work at four in the morning three days a week cannot offer anybody sensible employment, and he is not willing to pretend otherwise.'" }
    ]
  },
  {
    id: "pet-rmc11-05",
    title: "The Beach That Keeps Moving",
    text: "The beach at Sanderness is about four hundred metres further east than it was in 1990. This is not unusual. Almost every beach moves, and Sanderness has been moving for as long as anybody has measured it, at an average of roughly twelve metres a year.\n\nSand travels along a coast in the direction the waves push it, and a beach is best understood not as a place but as a quantity of sand passing through. What arrives at Sanderness comes from cliffs some nine kilometres west, which are slowly falling into the sea.\n\nThis has caused an argument that has lasted thirty years. In the 1990s the cliffs were protected with large rocks to save eleven houses at the top. The houses were saved. But the sand that had been arriving at Sanderness for centuries largely stopped, and within a decade the beach had thinned enough that the sea began reaching a car park and, later, the road behind it.\n\nThe council's own engineers now describe the 1990s decision as a mistake, though they are careful to say it was a reasonable mistake at the time, made with the knowledge then available. Nobody expected the effect to appear nine kilometres away.\n\nThe current plan is unpopular in a different way. Some of the rock defences are being removed to let the cliffs erode again, which will supply sand to the beach and, eventually, protect the village behind it. Three of the eleven houses will probably be lost within twenty years, and their owners have been offered a payment that most of them consider far too low.\n\nDr Selina Ngata, who advises the council, says the honest position is uncomfortable: coastal defence rarely stops a problem, and mostly decides which place, and which people, will experience it.",
    questions: [
      { q: "What has happened to the beach at Sanderness?", options: ["It has moved about four hundred metres east","It has grown much wider","It has been rebuilt with imported sand","It has disappeared completely"], answer: 0, explanation: "'The beach at Sanderness is about four hundred metres further east than it was in 1990.'" },
      { q: "Where does the beach's sand come from?", options: ["The sea bed","Cliffs nine kilometres to the west","Nearby building work","A river to the north"], answer: 1, explanation: "'What arrives at Sanderness comes from cliffs some nine kilometres west, which are slowly falling into the sea.'" },
      { q: "What was the result of protecting the cliffs in the 1990s?", options: ["The beach grew rapidly","Nothing changed for thirty years","The beach thinned and the sea reached a car park","The cliffs collapsed anyway"], answer: 2, explanation: "'But the sand that had been arriving at Sanderness for centuries largely stopped, and within a decade the beach had thinned enough that the sea began reaching a car park and, later, the road behind it.'" },
      { q: "How do the council's engineers describe the 1990s decision?", options: ["As entirely correct","As too expensive","As deliberately dishonest","As a reasonable mistake for its time"], answer: 3, explanation: "'The council's own engineers now describe the 1990s decision as a mistake, though they are careful to say it was a reasonable mistake at the time, made with the knowledge then available.'" },
      { q: "What is the current plan?", options: ["To remove some defences and let the cliffs erode","To bring in sand by lorry","To build a higher sea wall","To move the village inland"], answer: 0, explanation: "'Some of the rock defences are being removed to let the cliffs erode again, which will supply sand to the beach and, eventually, protect the village behind it.'" },
      { q: "What is Dr Ngata's view of coastal defence?", options: ["It should always be avoided","It mainly decides who suffers the problem","It is too expensive to be worthwhile","It usually solves the problem"], answer: 1, explanation: "'Dr Selina Ngata, who advises the council, says the honest position is uncomfortable: coastal defence rarely stops a problem, and mostly decides which place, and which people, will experience it.'" }
    ]
  },
  {
    id: "pet-rmc11-06",
    title: "The Doctor Who Prescribes Walks",
    text: "In a medical centre in Kirkbride, some patients leave with a piece of paper that is not a prescription for medicine. It gives the name of a walking group, a meeting point and a time.\n\nDr Oyelaran Bakare began doing this in 2018, after realising how many of his appointments could not be helped by anything he was trained to give. A man with pains that had no physical cause had not left his house in six weeks. A woman with high blood pressure had been widowed the year before. In both cases, Dr Bakare says, he could write a prescription and both of them would still be alone on Thursday.\n\nThe walks are led by trained volunteers, last around ninety minutes, and are deliberately slow. Nobody is told to walk faster and the route always includes somewhere to sit. Around a third of those referred never attend, which Dr Bakare regards as a normal rate for anything.\n\nMeasuring the effect is genuinely difficult, and he refuses to claim more than he can show. Blood pressure readings in the group have improved slightly. Prescriptions for sleeping tablets among regular walkers have fallen by about a quarter. Whether the walking caused this, or whether the people who attend were already improving, he says he cannot prove with the numbers he has.\n\nWhat he is more confident about is a change in his own practice. Patients who walk together phone the surgery less, and when they do phone, they describe their symptoms differently, because they have already talked about them to somebody on a path.\n\nThe scheme costs the surgery about nine hundred pounds a year, mostly for training and insurance. Dr Bakare points out that this is less than the annual medicine cost of two patients, and that the walking group currently has sixty-one members.",
    questions: [
      { q: "What do some patients receive instead of medicine?", options: ["A book about health","An appointment with a specialist","Details of a walking group","A gym membership"], answer: 2, explanation: "'It gives the name of a walking group, a meeting point and a time.'" },
      { q: "What made Dr Bakare start the scheme?", options: ["A study he had read","A request from the council","A shortage of medicines","Many problems could not be treated with medicine"], answer: 3, explanation: "'Dr Oyelaran Bakare began doing this in 2018, after realising how many of his appointments could not be helped by anything he was trained to give.'" },
      { q: "What are the walks like?", options: ["Slow, with somewhere to sit on the route","Different every week","Led by medical staff","Fast and physically demanding"], answer: 0, explanation: "'The walks are led by trained volunteers, last around ninety minutes, and are deliberately slow.'" },
      { q: "What does Dr Bakare admit he cannot prove?", options: ["That patients enjoy the walks","That the walking caused the improvements","That the scheme is cheap","That blood pressure has improved"], answer: 1, explanation: "'Whether the walking caused this, or whether the people who attend were already improving, he says he cannot prove with the numbers he has.'" },
      { q: "What change has he noticed in his own work?", options: ["Fewer patients register at the surgery","He writes more prescriptions","Walkers phone less and describe symptoms differently","He has more time for appointments"], answer: 2, explanation: "'Patients who walk together phone the surgery less, and when they do phone, they describe their symptoms differently, because they have already talked about them to somebody on a path.'" },
      { q: "How does he justify the cost?", options: ["It brings new patients to the surgery","It replaces a more expensive scheme","It is paid for by the volunteers","It is less than the medicine cost of two patients"], answer: 3, explanation: "'Dr Bakare points out that this is less than the annual medicine cost of two patients, and that the walking group currently has sixty-one members.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
