/* PET Prep bank: Reading multiple choice (B1) — wave 16 */
(function () {
var BANK = [
  {
    id: "pet-rmc16-01",
    title: "Why Do We Yawn?",
    text: "Almost every animal with a backbone yawns, including fish, and human babies yawn before they are born. Despite this, there is still no explanation that all scientists agree on.\n\nThe oldest idea was that yawning brings in extra oxygen when the blood is low on it. This was tested directly in the 1980s, when volunteers breathed air containing more oxygen than usual and then air containing more carbon dioxide. Neither changed how often they yawned, and the theory has been largely abandoned since.\n\nThe explanation most researchers currently favour is temperature. The brain works best within a narrow range of temperature, and a yawn draws a large volume of air across the roof of the mouth, where blood vessels lie close to the surface. Several studies have found that people yawn more when the air is cooler than their body and hardly at all when the air is hotter, which is what this theory predicts and which the oxygen theory cannot explain.\n\nThe most familiar fact about yawning is also the least understood. Yawning is contagious: reading this paragraph makes a proportion of people yawn. It spreads between friends more easily than between strangers, and it does not appear in children until around the age of four or five, at roughly the same time as other social abilities develop.\n\nDogs yawn when their owners do, and there is evidence that this works across species in both directions. Studies of contagious yawning in dogs, however, have produced mixed results, and researchers disagree about what they show.\n\nWhat can be said with confidence is unusually little. Yawning is ancient, it is nearly universal among animals with backbones, it probably has something to do with temperature, and it spreads socially for reasons nobody has established. It is a good example of how an everyday thing can remain genuinely unexplained.",
    questions: [
      { q: "What is unusual about yawning in babies?", options: ["They yawn before birth", "They yawn less than adults", "They only yawn when tired", "They do not yawn at all"], answer: 0, explanation: "'Almost every animal with a backbone yawns, including fish, and human babies yawn before they are born.'" },
      { q: "What happened when the oxygen theory was tested?", options: ["Yawning stopped completely","Neither gas changed yawning","The results were never published","Yawning increased with more oxygen"], answer: 1, explanation: "'Neither changed how often they yawned, and the theory has been largely abandoned since.'" },
      { q: "What do most researchers now think yawning does?", options: ["Signals tiredness to others","Increases oxygen","Helps cool the brain","Relaxes the jaw"], answer: 2, explanation: "'The brain works best within a narrow range of temperature, and a yawn draws a large volume of air across the roof of the mouth, where blood vessels lie close to the surface.'" },
      { q: "What evidence supports the temperature theory?", options: ["People yawn more at night","Yawning lowers body temperature quickly","Animals yawn only in winter","People yawn more in cool air than hot"], answer: 3, explanation: "'Several studies have found that people yawn more when the air is cooler than their body and hardly at all when the air is hotter, which is what this theory predicts and which the oxygen theory cannot explain.'" },
      { q: "When does contagious yawning appear in children?", options: ["At around four or five","In the teenage years","At birth","At about one year"], answer: 0, explanation: "'It spreads between friends more easily than between strangers, and it does not appear in children until around the age of four or five, at roughly the same time as other social abilities develop.'" },
      { q: "What is the article's overall conclusion?", options: ["Yawning is caused by tiredness","Surprisingly little is known for certain","Only humans yawn socially","Yawning is now fully explained"], answer: 1, explanation: "'What can be said with confidence is unusually little.'" }
    ]
  },
  {
    id: "pet-rmc16-02",
    title: "Before the Traffic Light",
    text: "The first traffic light in the world was installed outside the Houses of Parliament in London in December 1868, more than thirty years before cars were common. It was there for horses.\n\nThe streets of central London at that time were extremely dangerous. Thousands of horse-drawn vehicles used them daily, and crossing a busy junction on foot was genuinely risky. A railway engineer named John Peake Knight suggested adapting a system already used on the railways, where signals told drivers when to stop, and applying it to the road.\n\nThe signal had two arms that were raised and lowered by a police officer, and at night it showed red and green gas lamps. It worked. Accidents at that junction fell, and newspapers wrote about it approvingly.\n\nIt lasted twenty-two days. In January 1869 a gas leak caused the lamp to explode, injuring the officer operating it. The idea was abandoned, and no traffic light was installed anywhere in the world for another forty-five years.\n\nThe next attempt was in Cleveland, Ohio, in 1914, this time electric and driven by the arrival of the motor car. The amber light, which most people assume was there from the start, did not appear until 1920, and its inventor, a Detroit police officer named William Potts, is often forgotten. Before amber, drivers had no warning of the change at all.\n\nAutomatic timing arrived in the 1920s, and the first lights controlled by the traffic itself, using a sensor under the road, in the 1930s. Most modern city systems still work on the same principle.\n\nThe original London signal is remembered by a small plaque near the site. Almost nobody who passes it notices, which would perhaps not have surprised Knight, who died before the invention returned.",
    questions: [
      { q: "Why was the first traffic light installed?", options: ["To slow down cyclists","To control motor cars","To manage horse-drawn traffic","To test electric lighting"], answer: 2, explanation: "'The first traffic light in the world was installed outside the Houses of Parliament in London in December 1868, more than thirty years before cars were common.'" },
      { q: "Where did the idea come from?", options: ["Ship signals","Military flags","Another city abroad","Railway signals"], answer: 3, explanation: "'A railway engineer named John Peake Knight suggested adapting a system already used on the railways, where signals told drivers when to stop, and applying it to the road.'" },
      { q: "How was the first signal operated?", options: ["By a police officer raising arms","By drivers themselves","Automatically by a clock","By electricity"], answer: 0, explanation: "'The signal had two arms that were raised and lowered by a police officer, and at night it showed red and green gas lamps.'" },
      { q: "Why was it abandoned?", options: ["It caused more accidents","A gas explosion injured the operator","It cost too much to run","Drivers ignored it"], answer: 1, explanation: "'In January 1869 a gas leak caused the lamp to explode, injuring the officer operating it.'" },
      { q: "When did the amber light appear?", options: ["1868", "1914", "1920", "The 1930s"], answer: 2, explanation: "'The amber light, which most people assume was there from the start, did not appear until 1920, and its inventor, a Detroit police officer named William Potts, is often forgotten.'" },
      { q: "What is said about the plaque in London?", options: ["It gives the wrong date","It is visited by many tourists","It was removed recently","Almost nobody notices it"], answer: 3, explanation: "'Almost nobody who passes it notices, which would perhaps not have surprised Knight, who died before the invention returned.'" }
    ]
  },
  {
    id: "pet-rmc16-03",
    title: "The Library in the Telephone Box",
    text: "The red telephone box at the crossroads in Little Hexham has held no telephone since 2012. It holds around two hundred books, on five shelves built by a retired carpenter, and anybody may take one at any hour without asking anybody.\n\nThe box was going to be removed. Telephone companies across the country have been taking them away for years, since a box that takes about eleven calls a year costs several hundred pounds to maintain. A scheme exists, however, under which a community may buy the box itself for one pound, on the condition that it removes the telephone equipment and takes on the upkeep.\n\nThe village bought it, and the argument about what to put inside it lasted four months. A defibrillator was the obvious answer and was rejected because the village already had one, forty metres away. Somebody suggested a noticeboard, which the village hall already had. The library was proposed by an eleven-year-old at a parish meeting, in what several adults present described as the shortest and best speech of the evening.\n\nThere is one rule, on a card by the door: leave it as you would like to find it. There is no borrowing record and no limit. Books that nobody wants are removed once a month by whoever notices, and about forty books a year are quietly disposed of.\n\nWhat has surprised the village is the traffic. The box is on a road used by drivers passing through, and a surprising proportion of the books that arrive come from people who do not live in the village and stopped because they saw it.\n\nThe carpenter who built the shelves died in 2021. His own books, about two hundred of them, went into the box over the following year, a few at a time, on the instruction of his daughter, who said he would have hated a ceremony.",
    questions: [
      { q: "What is inside the telephone box now?", options: ["About two hundred books","A public telephone","A defibrillator","A noticeboard"], answer: 0, explanation: "'It holds around two hundred books, on five shelves built by a retired carpenter, and anybody may take one at any hour without asking anybody.'" },
      { q: "Why are telephone boxes being removed?", options: ["The design has changed","They are very rarely used but cost money","They are unsafe","They are needed elsewhere"], answer: 1, explanation: "'Telephone companies across the country have been taking them away for years, since a box that takes about eleven calls a year costs several hundred pounds to maintain.'" },
      { q: "How can a village keep its box?", options: ["By proving it is still used","By paying the yearly running costs","By buying it for one pound and maintaining it","By collecting enough signatures"], answer: 2, explanation: "'A scheme exists, however, under which a community may buy the box itself for one pound, on the condition that it removes the telephone equipment and takes on the upkeep.'" },
      { q: "Who suggested the library?", options: ["The parish council chair","A visiting driver","The retired carpenter","An eleven-year-old"], answer: 3, explanation: "'The library was proposed by an eleven-year-old at a parish meeting, in what several adults present described as the shortest and best speech of the evening.'" },
      { q: "What has surprised the village?", options: ["How many books come from people passing through", "How few books are taken", "How often books are stolen", "How quickly the shelves filled"], answer: 0, explanation: "'The box is on a road used by drivers passing through, and a surprising proportion of the books that arrive come from people who do not live in the village and stopped because they saw it.'" },
      { q: "What happened to the carpenter's own books?", options: ["They were given to a school","They went into the box gradually","They were kept by his daughter","They were sold for the village hall"], answer: 1, explanation: "'His own books, about two hundred of them, went into the box over the following year, a few at a time, on the instruction of his daughter, who said he would have hated a ceremony.'" }
    ]
  },
  {
    id: "pet-rmc16-04",
    title: "Cleaning the Windows of a Tall Building",
    text: "A large office tower may have eight thousand windows, and cleaning all of them takes a team of four about nine weeks. By the time they finish, it is time to start again.\n\nThe work is done from a cradle, a platform suspended from a machine on the roof that runs on rails. The cradle is lowered a floor at a time. Almost everybody assumes the danger is height, and everybody who does the job says the danger is wind. Air moves unpredictably around tall buildings, and a gust that would be unremarkable at street level can push a cradle several metres. Work stops at a wind speed most people would describe as a pleasant day.\n\nJordan Farrelly has cleaned windows for sixteen years and now trains new workers. He says that about one person in three who begins the training does not complete it, and that the ones who leave are almost never the ones who are frightened. Frightened people, he says, are careful. The ones who worry him are entirely relaxed on the second day.\n\nThe cleaning itself is unglamorous. Water, a rubber blade, and a technique that takes months to do quickly and about a day to do adequately. Rain is not a problem; ice is, and so is sunshine, because water dries before it can be removed and leaves marks.\n\nThe part of the job Jordan finds strangest is the people inside. He is a metre from somebody's desk, on the other side of glass, several hours a day. Most people ignore him completely. A few wave every time. One man, over three years, held up a piece of paper each week with the score of a football match on it, and Jordan never learned his name.",
    questions: [
      { q: "How long does one full clean of the tower take?", options: ["Three months","A year","About nine weeks","About a fortnight"], answer: 2, explanation: "'A large office tower may have eight thousand windows, and cleaning all of them takes a team of four about nine weeks.'" },
      { q: "What do the workers regard as the main danger?", options: ["Broken glass","Faulty equipment","Height","Wind"], answer: 3, explanation: "'Almost everybody assumes the danger is height, and everybody who does the job says the danger is wind.'" },
      { q: "Which trainees worry Jordan most?", options: ["Those who are completely relaxed early on","Those who work slowly","Those who ask many questions","Those who are frightened"], answer: 0, explanation: "'The ones who worry him are entirely relaxed on the second day.'" },
      { q: "Which weather causes problems?", options: ["Rain", "Ice and strong sunshine", "Cloud", "Fog"], answer: 1, explanation: "'Rain is not a problem; ice is, and so is sunshine, because water dries before it can be removed and leaves marks.'" },
      { q: "How do most office workers react to him?", options: ["They complain to management","They open the windows","They ignore him","They wave every time"], answer: 2, explanation: "'Most people ignore him completely.'" },
      { q: "What did one man do for three years?", options: ["Photograph him working","Complain about the noise","Bring him coffee","Show football scores on paper"], answer: 3, explanation: "'One man, over three years, held up a piece of paper each week with the score of a football match on it, and Jordan never learned his name.'" }
    ]
  },
  {
    id: "pet-rmc16-05",
    title: "The Sheep That Do the Mowing",
    text: "Since 2016 the grassland at Hartcliffe Common has not been cut by machine. It is grazed instead by a flock of about forty sheep of an old breed, which are moved between six areas of the site according to a plan drawn up each spring.\n\nThe reason is not cost, although the sheep are cheaper. A mower cuts everything to the same height on the same day. Sheep eat selectively, preferring some plants to others, and they move about, so the result is grass of many different heights across one field. That variety is what most insects need, and insects are what most of the birds on the site eat.\n\nThe results have been measured. In the first six years, the number of plant species recorded rose from thirty-one to fifty-four. Two butterfly species have returned that had not been recorded since the 1990s.\n\nThe method is not simple. Too many sheep, or sheep left too long, produce a field as uniform as a mown one and considerably muddier. The plan is written by an ecologist and the flock is moved every ten to fourteen days, which requires somebody to be available, and volunteers to check the animals daily.\n\nThe biggest practical difficulty is dogs. The common is a popular place to walk, and a sheep chased by a dog may die of stress hours later without any visible injury. The site has lost four animals this way. Signs make little difference, and the volunteers say a conversation on a path works far better than any notice, although it takes a great deal longer.\n\nThe council estimates the grazing costs about a third of what mowing cost. It has been careful, however, not to present the scheme as a saving, because a scheme presented as a saving is judged only on money.",
    questions: [
      { q: "How is the grass at Hartcliffe Common managed?", options: ["By grazing sheep","It is left uncut","By volunteers with hand tools","By machine every month"], answer: 0, explanation: "'It is grazed instead by a flock of about forty sheep of an old breed, which are moved between six areas of the site according to a plan drawn up each spring.'" },
      { q: "Why is grazing better than mowing for wildlife?", options: ["It removes weeds completely","It produces grass of many different heights","It happens less often","It is quieter"], answer: 1, explanation: "'Sheep eat selectively, preferring some plants to others, and they move about, so the result is grass of many different heights across one field.'" },
      { q: "What has been measured since 2016?", options: ["No change at all","A rise in visitor numbers","A large rise in plant species","A fall in bird numbers"], answer: 2, explanation: "'In the first six years, the number of plant species recorded rose from thirty-one to fifty-four.'" },
      { q: "What happens if sheep stay too long in one area?", options: ["They eat only one plant","The grass stops growing","They become ill","The field becomes uniform and muddy"], answer: 3, explanation: "'Too many sheep, or sheep left too long, produce a field as uniform as a mown one and considerably muddier.'" },
      { q: "What is the biggest practical problem?", options: ["Dogs", "Weather", "Cost of moving the sheep", "Lack of volunteers"], answer: 0, explanation: "'The biggest practical difficulty is dogs.'" },
      { q: "Why does the council avoid calling the scheme a saving?", options: ["It is not actually cheaper", "A scheme called a saving is judged only on money", "The figures are uncertain", "Volunteers would object"], answer: 1, explanation: "'It has been careful, however, not to present the scheme as a saving, because a scheme presented as a saving is judged only on money.'" }
    ]
  },
  {
    id: "pet-rmc16-06",
    title: "The Village That Shares One Car",
    text: "Twenty-three households in Ellersby share four cars. There is no company involved: the vehicles belong to a group that the residents themselves set up in 2017, and each household pays a monthly amount plus a charge for every hour and kilometre used.\n\nThe idea came from a simple calculation. A private car in this country is parked, on average, for about ninety-five per cent of its life. In a village where most journeys are a weekly shop and a monthly trip to a larger town, that figure is even higher, and several residents were paying to insure, tax and repair a vehicle they used twice a week.\n\nBooking is done on a website and, for two households without internet, by telephone to a neighbour who enters it for them. This detail matters more than it sounds: the group's rules were written so that nobody is excluded by not being online, which its founders say is the reason four older residents joined at all.\n\nThe difficulties have been social rather than technical. One vehicle was returned with an empty tank three times by the same household, and dealing with it took a meeting and a written rule that nobody enjoyed writing. Another household left after a year, saying honestly that they had not realised how much they liked deciding to go somewhere at eight minutes' notice.\n\nThe group estimates that its members save around two thousand pounds a year each and that the village has about eleven fewer cars than it would otherwise. There is now a waiting list, and a fifth vehicle is being discussed.\n\nThe founder, a retired teacher called Ines Marchetti, says the hardest part was never the money or the software. It was persuading people that a car in a shared space, four minutes' walk away, still counts as available.",
    questions: [
      { q: "Who owns the cars in Ellersby?", options: ["A car hire company", "The village council", "A group set up by residents", "Individual households in turn"], answer: 2, explanation: "'There is no company involved: the vehicles belong to a group that the residents themselves set up in 2017, and each household pays a monthly amount plus a charge for every hour and kilometre used.'" },
      { q: "What calculation led to the idea?", options: ["Fuel prices were rising","The village was too far from a station","Insurance had doubled","Cars are parked about ninety-five per cent of the time"], answer: 3, explanation: "'A private car in this country is parked, on average, for about ninety-five per cent of its life.'" },
      { q: "How can households without internet book a car?", options: ["By telephoning a neighbour","By writing in a book in the village hall","By asking at the shop","They cannot join the scheme"], answer: 0, explanation: "'Booking is done on a website and, for two households without internet, by telephone to a neighbour who enters it for them.'" },
      { q: "Why does that arrangement matter?", options: ["It makes booking faster","It stopped older residents being excluded","It reduces mistakes","It saves the group money"], answer: 1, explanation: "'This detail matters more than it sounds: the group's rules were written so that nobody is excluded by not being online, which its founders say is the reason four older residents joined at all.'" },
      { q: "Why did one household leave?", options: ["They disliked the rules about fuel","The cost was too high","They missed leaving at very short notice","They moved away"], answer: 2, explanation: "'Another household left after a year, saying honestly that they had not realised how much they liked deciding to go somewhere at eight minutes' notice.'" },
      { q: "What does Ines say was hardest?", options: ["Raising the money","Building the website","Finding parking space","Persuading people that a nearby shared car counts as available"], answer: 3, explanation: "'It was persuading people that a car in a shared space, four minutes' walk away, still counts as available.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
