/* PET Prep bank: Reading true/false/not given (B1) — wave 8 */
(function () {
var BANK = [
  {
    id: "p-rtfng8-01",
    title: "The Small Hole in an Aircraft Window",
    text: "Anybody sitting beside a window on a passenger aircraft can see a small hole near the bottom of it. It is deliberate, it is essential, and it is one of the neatest pieces of design on the aeroplane.\nEach window is made of three panes with small gaps between them. The outer pane is the one that carries the pressure difference between the cabin and the thin air outside, which at cruising height is considerable. The middle pane has the hole in it. The inner pane, the one passengers touch, carries no pressure load at all and exists mainly to protect the others from scratches and knocks.\nThe hole allows the air between the outer and middle panes to reach the same pressure as the cabin. This means the outer pane takes the whole load, which is what it is designed for, and the middle pane sits unloaded, ready to take over if the outer one were ever to fail.\nThe hole has a second job. Air inside the cabin contains moisture, and if it were sealed between two cold panes it would condense and freeze, and passengers would look out at a sheet of ice. The hole lets that moisture escape, which is why the window stays clear.\nWindows are also round-cornered rather than square, for reasons learned expensively in the 1950s, and they are small because every window is a hole in a pressurised tube and each one requires reinforcement around it.\nThe hole is often called a bleed hole or a breather hole. Cabin crew are asked about it regularly and the commonest passenger theory, which is that it lets air in if the cabin loses pressure, is not correct.",
    questions: [
      { q: "The hole in the window is there by design.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'It is deliberate, it is essential, and it is one of the neatest pieces of design on the aeroplane.'" },
      { q: "The inner pane carries most of the pressure.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the inner pane 'carries no pressure load at all'." },
      { q: "The hole equalises pressure between two of the panes and the cabin.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'allows the air between the outer and middle panes to reach the same pressure as the cabin'." },
      { q: "The middle pane would take over if the outer one failed.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it sits 'ready to take over if the outer one were ever to fail'." },
      { q: "Without the hole, ice could form between the panes.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - moisture 'would condense and freeze, and passengers would look out at a sheet of ice'." },
      { q: "The common passenger explanation of the hole is correct.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - the commonest theory 'is not correct'." },
      { q: "Window panes are made of the same material on all aircraft.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the text describes the panes but never says what they are made of." }
    ]
  },
  {
    id: "p-rtfng8-02",
    title: "What a Postcode Is For",
    text: "A postcode is not an address. It is an instruction to a sorting machine, and understanding that explains most of what seems strange about it.\nThe British system, introduced nationally between 1959 and 1974, divides the country first into areas, then into districts, then into sectors, and finally into units of about fifteen addresses. The first half of the code gets a letter to the right delivery office; the second half tells the machine which walk it belongs to and roughly where along that walk it falls.\nThe last part is deliberately small rather than precise. A unit code covering fifteen houses is enough to sort automatically and does not need to identify an individual building, which is why a postcode plus a house number is treated as a complete address by almost every system in the country.\nPostcodes were not designed for anything except post, and they are now used for a great many other things: insurance pricing, delivery charges, school admissions, statistical reporting and emergency response. Most of those uses assume that a postcode describes a small, consistent area, and that assumption is often wrong. In cities a postcode may cover a few dozen metres; in the countryside it can cover several square kilometres.\nSome codes are unusual. A very large organisation may have its own code, and there are codes assigned to single buildings that receive enormous volumes of post.\nThe system is updated constantly as new streets are built, and codes are occasionally withdrawn and reused elsewhere after a period. That last fact causes problems for organisations that treat a postcode as permanent, which many of them do.",
    questions: [
      { q: "A postcode was designed primarily for sorting post.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'It is an instruction to a sorting machine'." },
      { q: "The first half of a British postcode identifies the delivery office.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'The first half of the code gets a letter to the right delivery office'." },
      { q: "Each postcode unit identifies exactly one building.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - a unit covers 'about fifteen addresses' and 'does not need to identify an individual building'." },
      { q: "Postcode areas are the same size everywhere.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - in cities one may cover metres, 'in the countryside it can cover several square kilometres'." },
      { q: "Some large organisations have their own postcode.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'A very large organisation may have its own code'." },
      { q: "Postcodes can be withdrawn and used again elsewhere.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'codes are occasionally withdrawn and reused elsewhere after a period'." },
      { q: "Other countries copied the British system directly.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - only the British system is described." }
    ]
  },
  {
    id: "p-rtfng8-03",
    title: "Why Eggs Come in Sixes",
    text: "Eggs are almost always sold in boxes of six, twelve or thirty, and the reason is neither tradition nor packaging convenience alone. It is that twelve divides neatly in a way that ten does not.\nBefore decimal systems became standard, a great deal of trade in Europe used dozens. Twelve can be divided by two, three, four and six without leaving a remainder, which matters enormously when goods are being shared, sold in parts, or counted by hand. Ten divides only by two and five. For anybody selling to several customers from one basket, twelve is simply a more useful number.\nThere is a second, physical reason. Eggs stacked in a rectangle of two by three, or two by six, sit against each other and support one another, and the resulting box is compact and rigid. Trays of thirty, used throughout the trade, are five by six for the same reason.\nEgg boxes themselves are a relatively recent invention. Before the 1910s eggs were sold loose from baskets and breakages were routine, and the first moulded box was designed by a Canadian newspaper editor after an argument between a farmer and a hotel owner about who was responsible for a broken delivery.\nBoxes today are usually made of moulded paper pulp, which is cheap, protective and recyclable, and which performs better than plastic in cushioning tests. The shape is not decorative: each cup holds the egg at the point where its shell is strongest, and the ridges between cups absorb the impact.\nThe wide end of an egg contains a small air pocket, and eggs are placed in boxes with that end upwards, which helps to keep the yolk centred and the egg fresher for longer.",
    questions: [
      { q: "Twelve can be divided evenly in more ways than ten.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'Twelve can be divided by two, three, four and six without leaving a remainder'." },
      { q: "Egg boxes have existed for several centuries.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'Egg boxes themselves are a relatively recent invention.'" },
      { q: "The first egg box was designed after a dispute over breakages.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it followed 'an argument between a farmer and a hotel owner about who was responsible for a broken delivery'." },
      { q: "Plastic performs better than paper pulp in cushioning tests.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - pulp 'performs better than plastic in cushioning tests'." },
      { q: "The shape of each cup relates to the strength of the shell.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'each cup holds the egg at the point where its shell is strongest'." },
      { q: "Eggs are stored with the wide end upwards.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'eggs are placed in boxes with that end upwards'." },
      { q: "Most shoppers prefer boxes of six to boxes of twelve.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - both sizes are mentioned but no preference is described." }
    ]
  },
  {
    id: "p-rtfng8-04",
    title: "The Moving Staircase",
    text: "The escalator was first shown in public as an amusement ride. In 1896 a version was installed at Coney Island in New York, where people paid to travel up a moving slope, and it was moved to a bridge two weeks later.\nEarly designs came in two forms. One had a flat, sloping belt with no steps at all, which passengers stood on as though on a ramp. The other formed steps, and it was this design that survived, because a flat belt becomes uncomfortable and unsafe above quite a shallow angle.\nThe modern escalator was largely settled by the 1920s, and the mechanism has changed less than most people assume: a chain of linked steps, a pair of handrails driven at the same speed, and comb plates at each end where the steps flatten and disappear.\nThe handrail is the part that causes most difficulty. It is driven by a separate system from the steps and stretches with age, and a handrail moving very slightly faster or slower than the stairs is the commonest cause of complaint and of minor accidents.\nA question that is often argued about is whether standing on one side and walking on the other moves more people. Studies in busy stations have found that on long escalators asking everybody to stand carries significantly more people, because far fewer people walk than stand and the walking side is therefore poorly used. Trials of this have met strong resistance from passengers, and most operators have not adopted it.\nEscalators are also unusual among machines in that they are safest when full and moving steadily, and most incidents occur at the two ends rather than along the length.",
    questions: [
      { q: "The escalator was originally presented as entertainment.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it 'was first shown in public as an amusement ride'." },
      { q: "The flat-belt design became the standard one.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'it was this design that survived', referring to the stepped one." },
      { q: "The handrail is driven by the same system as the steps.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'It is driven by a separate system from the steps'." },
      { q: "Studies found that everybody standing can move more people.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'asking everybody to stand carries significantly more people'." },
      { q: "Most operators have adopted the standing-only approach.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'most operators have not adopted it'." },
      { q: "Most accidents happen at the ends of an escalator.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'most incidents occur at the two ends rather than along the length'." },
      { q: "Escalators use more electricity than lifts.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - energy use is never mentioned." }
    ]
  },
  {
    id: "p-rtfng8-05",
    title: "Measuring Rain",
    text: "A rain gauge is one of the simplest scientific instruments in existence and one of the hardest to use accurately. In principle it is a straight-sided container that collects rain, and the depth collected is reported in millimetres.\nThe difficulty is that a gauge measures the rain that falls into it, which is not necessarily the rain that fell. Wind carries drops over the opening rather than into it, and this effect is large: in strong wind a standard gauge may catch twenty per cent less than the true amount, and with snow the shortfall can be far greater.\nFor this reason the position of a gauge matters more than the gauge itself. The standard is that the opening should be about thirty centimetres above the ground, in an open space, at a distance from any obstacle of at least twice the obstacle's height. A gauge beside a wall or under a tree produces figures that mean nothing.\nMost official gauges now empty themselves automatically. A common design uses a small bucket balanced so that it tips when it has collected a fixed amount, usually a fifth of a millimetre, and each tip is counted electronically. This gives not only totals but intensity, which is what matters for flooding.\nAmateur records can be genuinely valuable, and several national weather services accept them, provided the gauge is correctly sited and read at the same time each day, which is traditionally nine in the morning.\nRainfall varies over very short distances. Two gauges a kilometre apart can differ by half in a single summer storm, which is why a single figure for a town is always an approximation.",
    questions: [
      { q: "A rain gauge is difficult to use accurately.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - it is 'one of the hardest to use accurately'." },
      { q: "Wind can cause a gauge to under-record rainfall.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'in strong wind a standard gauge may catch twenty per cent less than the true amount'." },
      { q: "The design of the gauge matters more than where it is placed.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'the position of a gauge matters more than the gauge itself'." },
      { q: "A gauge should be at least twice an obstacle's height away from it.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'at a distance from any obstacle of at least twice the obstacle's height'." },
      { q: "Tipping bucket gauges record intensity as well as totals.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'This gives not only totals but intensity'." },
      { q: "Amateur measurements are never accepted officially.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'several national weather services accept them'." },
      { q: "Most amateur observers in Britain read their gauge at nine.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - nine is the traditional time, but nothing is said about how many observers keep to it." }
    ]
  },
  {
    id: "p-rtfng8-06",
    title: "The Blank Pages at the End of a Book",
    text: "Many printed books end with one to three blank pages, and readers occasionally assume this is an error or a way of making a book look longer. It is neither. It is a consequence of how books are physically made.\nA book is not printed page by page. Large sheets of paper are printed with a number of pages on each side, then folded, cut and bound. The folded unit is called a signature, and it usually contains sixteen or thirty-two pages, because the sheet is folded four or five times.\nThis means that the total number of pages in a book is a multiple of the signature size. A text that ends on page three hundred and one is printed in a book of three hundred and twelve, and the remaining eleven pages must be filled with something or left blank.\nPublishers use them in various ways. Some print advertisements for other titles, some add notes about the typeface, and some leave them entirely blank, which many designers prefer. A page marked in small type as intentionally blank appears mainly in technical documents, where a reader needs to know that nothing is missing.\nThe same arithmetic explains a fact that surprises people: adding a short preface to a book can force the addition of sixteen pages, and removing three pages of text may save nothing at all. Authors asked to cut a manuscript are sometimes asked for a specific number of pages for exactly this reason.\nDigital printing has changed this for short runs, where any number of pages can now be produced economically, but the great majority of books printed in large quantities are still made in signatures.",
    questions: [
      { q: "Blank pages at the end of a book are usually a printing mistake.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - 'It is neither. It is a consequence of how books are physically made.'" },
      { q: "A signature normally contains sixteen or thirty-two pages.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'it usually contains sixteen or thirty-two pages'." },
      { q: "The total number of pages must be a multiple of the signature size.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'the total number of pages in a book is a multiple of the signature size'." },
      { q: "Notices saying a page is intentionally blank are common in novels.", options: ["True", "False", "Not Given"], answer: 1, explanation: "False - such a page 'appears mainly in technical documents'." },
      { q: "Adding a short preface can require sixteen extra pages.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'adding a short preface to a book can force the addition of sixteen pages'." },
      { q: "Digital printing allows short runs of any page count.", options: ["True", "False", "Not Given"], answer: 0, explanation: "True - 'any number of pages can now be produced economically'." },
      { q: "Most readers notice the blank pages at the end.", options: ["True", "False", "Not Given"], answer: 2, explanation: "Not Given - the text says readers occasionally assume it is an error, but gives no proportion." }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.tfng = (window.READING.tfng || []).concat(BANK);
})();
