/* PET Prep bank: Reading multiple choice (B1) — wave 25 */
(function () {
var BANK = [
  {
    id: "pet-rmc25-01",
    title: "What Are Fingerprints For?",
    text: "Every human being has patterns of ridges on the skin of the fingers, and the usual explanation is that they help us grip things. Recent work suggests this explanation is probably wrong.\nThe grip theory sounds sensible, because car tyres have patterns and so do the soles of shoes. But tyres and shoes work by pushing water out of the way on a hard surface, while human skin is soft and behaves quite differently. In 2009 researchers measured the friction between fingers and a smooth surface directly and found that ridged skin gripped slightly less well than flat skin would, because the ridges reduce the area actually touching the object.\nThe explanation now considered most likely concerns touch rather than grip. The ridges amplify vibrations. When a finger moves across a surface, the ridges cause tiny regular vibrations that are picked up by nerve endings sitting directly beneath them, and these nerves are particularly sensitive to exactly the frequencies the ridges produce. Fingerprints, on this theory, are a way of turning texture into a signal the nervous system can read.\nThere is a second possibility that may also be true. Ridged skin stretches differently from flat skin, and this may help the finger keep contact with an uneven object as it deforms.\nThe patterns themselves form before birth, between about the tenth and sixteenth weeks, as the skin grows at a different rate from the tissue beneath it. The result depends on tiny differences in pressure and position in the womb, which is why identical twins, who share their DNA exactly, have different fingerprints.\nThat last fact is what makes fingerprints useful for identification, and it is worth noticing that it is a side effect. Nothing about the pattern evolved in order to be unique.",
    questions: [
      { q: "What did the 2009 research find?", options: ["Ridged skin gripped slightly less well", "Ridges doubled the grip", "Ridges only help when wet", "Grip depends on skin thickness"], answer: 0, explanation: "'In 2009 researchers measured the friction between fingers and a smooth surface directly and found that ridged skin gripped slightly less well than flat skin would, because the ridges reduce the area actually touching the object.'" },
      { q: "Why is the comparison with tyres misleading?", options: ["Tyres are much larger", "Skin is soft and behaves differently", "Tyres are used on wet roads", "Skin has no pattern when dry"], answer: 1, explanation: "'But tyres and shoes work by pushing water out of the way on a hard surface, while human skin is soft and behaves quite differently.'" },
      { q: "What is the leading explanation now?", options: ["Ridges protect the skin", "Ridges help the finger cool", "Ridges amplify vibrations for touch", "Ridges make skin stronger"], answer: 2, explanation: "'The ridges amplify vibrations.'" },
      { q: "What is the second possible function?", options: ["Reducing sweat","Slowing down wear","Improving temperature sensing","Helping skin stay in contact with uneven objects"], answer: 3, explanation: "'Ridged skin stretches differently from flat skin, and this may help the finger keep contact with an uneven object as it deforms.'" },
      { q: "When do fingerprint patterns form?", options: ["Between the tenth and sixteenth weeks before birth","During childhood","They change through life","In the first weeks after birth"], answer: 0, explanation: "'The patterns themselves form before birth, between about the tenth and sixteenth weeks, as the skin grows at a different rate from the tissue beneath it.'" },
      { q: "Why do identical twins have different fingerprints?", options: ["Their DNA differs slightly", "Patterns depend on conditions in the womb", "Patterns form after birth", "One twin's skin grows faster"], answer: 1, explanation: "'The result depends on tiny differences in pressure and position in the womb, which is why identical twins, who share their DNA exactly, have different fingerprints.'" }
    ]
  },
  {
    id: "pet-rmc25-02",
    title: "The Man Who Paints the Pier",
    text: "The pier at Southmere is four hundred and eleven metres long, made of iron, and standing in salt water. Painting it is not decoration. It is the only thing preventing the structure from rusting into the sea, and it is a job that never finishes.\nDerek Ashworth has led the painting team for nineteen years. Work begins at one end in March and reaches the other end, if the weather allows, in about three years, at which point the first section needs attention again.\nThe difficulty is not the painting. It is preparing the surface. Old paint and rust have to be removed completely, because paint applied over rust seals moisture in and the metal continues to corrode invisibly beneath a perfect-looking surface. Preparation takes about four times as long as painting and is the part that inexperienced contractors underestimate.\nSalt is the enemy in a way that people who work inland do not appreciate. Salt sits on the metal, attracts moisture from the air even on a dry day, and must be washed off with fresh water before any paint is applied. A section washed on Monday and painted on Thursday has to be washed again.\nWeather decides everything. Paint will not cure below about eight degrees or when the humidity is high, which in a coastal town removes most of the year. Derek's team works around one hundred and thirty days a year and spends a good deal of the rest maintaining equipment and waiting.\nHe has been asked whether the work is discouraging, since it can never be completed. He says it is the opposite. A painter on a building paints it and leaves. He has walked the same four hundred metres for nineteen years, knows every plate and rivet, and can tell from the colour of a stain which repair was done badly in 2011 and by whom.",
    questions: [
      { q: "Why is the pier painted?", options: ["To protect the wood beneath","To make it attractive to visitors","To prevent the iron rusting away","Because the council requires it"], answer: 2, explanation: "'It is the only thing preventing the structure from rusting into the sea, and it is a job that never finishes.'" },
      { q: "How long does one full pass take?", options: ["Nineteen years","Six months","One season","About three years"], answer: 3, explanation: "'Work begins at one end in March and reaches the other end, if the weather allows, in about three years, at which point the first section needs attention again.'" },
      { q: "Why must rust be removed completely?", options: ["Otherwise corrosion continues under the paint", "Rust makes the paint the wrong colour", "The paint will not stick at all", "Rust is dangerous to workers"], answer: 0, explanation: "'Old paint and rust have to be removed completely, because paint applied over rust seals moisture in and the metal continues to corrode invisibly beneath a perfect-looking surface.'" },
      { q: "What must be done about salt?", options: ["It is covered with a special primer","It must be washed off shortly before painting","It must be scraped off with tools","It is removed by rain"], answer: 1, explanation: "'Salt sits on the metal, attracts moisture from the air even on a dry day, and must be washed off with fresh water before any paint is applied.'" },
      { q: "How many working days does the team get?", options: ["Almost the whole year","About two hundred","About one hundred and thirty","Fewer than eighty"], answer: 2, explanation: "'Derek's team works around one hundred and thirty days a year and spends a good deal of the rest maintaining equipment and waiting.'" },
      { q: "How does Derek feel about the endless job?", options: ["He plans to leave soon","He finds it repetitive","Discouraged by it","Positive, because he knows the structure intimately"], answer: 3, explanation: "'He has walked the same four hundred metres for nineteen years, knows every plate and rivet, and can tell from the colour of a stain which repair was done badly in 2011 and by whom.'" }
    ]
  },
  {
    id: "pet-rmc25-03",
    title: "Why Aircraft Windows Are Round",
    text: "The windows on a passenger aircraft are rounded at the corners, and the reason is one of the most expensive lessons in the history of engineering.\nThe first jet airliner to carry passengers was the de Havilland Comet, which entered service in 1952 and was far ahead of anything else flying. It had square windows.\nIn 1954 two Comets broke apart in flight within four months of each other. The investigation that followed was unusually thorough: a complete aircraft was placed in a tank of water and pressurised and depressurised thousands of times to reproduce years of flying, and it failed in the same way.\nThe cause was metal fatigue. Every flight pressurises the cabin and stretches the metal skin slightly, and every landing releases it. Repeated over thousands of cycles, this causes cracks to begin at any point where stress is concentrated.\nA square corner concentrates stress enormously. The forces flowing through the metal must turn a sharp angle, and at that point the stress can be several times higher than in the surrounding material. A curve allows the forces to turn gradually. The Comet's windows were not weak; they were the wrong shape, and the difference was enough to destroy an aircraft.\nEvery pressurised aircraft since has had rounded openings, not only for windows but for doors and hatches. The same principle appears elsewhere: ship portholes are round, and the corners of aircraft cargo openings are curved for exactly the same reason.\nThe Comet was redesigned and flew successfully for decades, but the delay allowed American manufacturers to take the market. The investigation's findings were published in full and shared internationally, which was not required, and every jet flying today is safer because of it.",
    questions: [
      { q: "What was unusual about the Comet's windows?", options: ["They were square","They could be opened","They were made of plastic","They were very large"], answer: 0, explanation: "'It had square windows.'" },
      { q: "How was the cause investigated?", options: ["By interviewing pilots", "By testing an aircraft in a water tank", "By examining the wreckage only", "By computer modelling"], answer: 1, explanation: "'The investigation that followed was unusually thorough: a complete aircraft was placed in a tank of water and pressurised and depressurised thousands of times to reproduce years of flying, and it failed in the same way.'" },
      { q: "What causes metal fatigue in an aircraft?", options: ["Salt in the air","Heat from the engines","Repeated pressurising and depressurising","Vibration in flight"], answer: 2, explanation: "'Every flight pressurises the cabin and stretches the metal skin slightly, and every landing releases it.'" },
      { q: "Why is a square corner dangerous?", options: ["It allows water in","It is harder to seal","It weakens the glass","It concentrates stress"], answer: 3, explanation: "'A square corner concentrates stress enormously.'" },
      { q: "Where else is the principle applied?", options: ["Doors, hatches and cargo openings", "Only in aircraft windows", "In engine design", "In runway construction"], answer: 0, explanation: "'Every pressurised aircraft since has had rounded openings, not only for windows but for doors and hatches.'" },
      { q: "What was the effect of publishing the findings?", options: ["Other manufacturers copied the design illegally","All later jets became safer","The investigation was criticised","The Comet was never flown again"], answer: 1, explanation: "'The investigation's findings were published in full and shared internationally, which was not required, and every jet flying today is safer because of it.'" }
    ]
  },
  {
    id: "pet-rmc25-04",
    title: "The Cricket Club That Nearly Closed",
    text: "Marlow Vale Cricket Club, founded in 1889, came within one vote of closing in 2017. It now has four teams, a waiting list for two of them, and more members than at any time in its history.\nThe problem in 2017 was the ordinary one. The club had thirty-one playing members with an average age of forty-six, a pavilion that needed twenty thousand pounds of repairs, and nobody willing to take on the roles that keep a club running.\nThe committee did something unusual before deciding. It asked forty people who had left the club in the previous five years why they had gone. Almost nobody said they had stopped enjoying cricket. What they described was time: a match lasting seven hours on a Saturday is not possible for most people with young children, and a club that offers only that is offering something most adults cannot accept.\nSo the club kept its Saturday teams and added two formats alongside them. One is a two-hour evening match on Wednesdays with a shorter game and simplified rules. The other is a Sunday morning session where adults and children play together and anybody can leave when they need to.\nThe Wednesday league now has more members than the Saturday teams. About a third of them had never played cricket before, and eleven of them have since joined a Saturday side, having discovered that they wanted the longer game after all.\nThe pavilion was repaired with a grant, some borrowing and eight weekends of work by members.\nThe club's chair, Ruth Okonjo, is asked for advice by other clubs and gives the same answer each time. Do not ask your members what would improve the club, she says, because they are the people who stayed. Ask the ones who left.",
    questions: [
      { q: "What was the club's situation in 2017?", options: ["It had moved to a new ground","It had too many members","It nearly voted to close","It had just been founded"], answer: 2, explanation: "'Marlow Vale Cricket Club, founded in 1889, came within one vote of closing in 2017.'" },
      { q: "What did the committee do before deciding?", options: ["Raised the membership fee","Employed a coach","Sold part of the ground","Asked people who had left why they went"], answer: 3, explanation: "'It asked forty people who had left the club in the previous five years why they had gone.'" },
      { q: "What did those people say?", options: ["A seven-hour Saturday match was impossible","They had lost interest in cricket","The club was unfriendly","The cost was too high"], answer: 0, explanation: "'What they described was time: a match lasting seven hours on a Saturday is not possible for most people with young children, and a club that offers only that is offering something most adults cannot accept.'" },
      { q: "What did the club add?", options: ["An indoor centre","A two-hour evening match and a Sunday family session","Two more Saturday teams","A junior academy"], answer: 1, explanation: "'One is a two-hour evening match on Wednesdays with a shorter game and simplified rules.'" },
      { q: "What happened to the Wednesday league?", options: ["It was moved to Sundays","It failed after a season","It has more members than the Saturday teams","It is only for beginners"], answer: 2, explanation: "'The Wednesday league now has more members than the Saturday teams.'" },
      { q: "What advice does Ruth give other clubs?", options: ["Reduce the membership fee","Advertise more widely","Improve the pavilion first","Ask the people who left, not those who stayed"], answer: 3, explanation: "'Do not ask your members what would improve the club, she says, because they are the people who stayed.'" }
    ]
  },
  {
    id: "pet-rmc25-05",
    title: "Anybody Can Learn to Draw",
    text: "Most adults believe that drawing is a talent people either have or do not have. Teachers of drawing generally disagree, and their reasons are more interesting than encouragement.\nThe usual argument is that drawing is not mainly a skill of the hand. It is a skill of looking. A person drawing a face from memory draws what they know about faces: eyes too large, placed too high, because that is how the brain stores the idea of a face rather than its geometry. The eyes of an adult are, in fact, roughly halfway down the head, which almost nobody believes until they measure it.\nMost teaching therefore concentrates on interfering with what the brain expects. One well-known exercise is to copy a photograph placed upside down. Turned the wrong way, the picture stops being a face and becomes a set of shapes, and beginners who have been drawing badly for an hour produce something noticeably better within twenty minutes.\nA second common exercise is to draw the spaces between objects rather than the objects, because the brain has no strong expectations about the shape of a gap.\nProgress is quicker than most beginners expect and slower than they hope. Teachers commonly say that a person practising three hours a week will draw recognisably well within about six months, which is neither instant nor a lifetime.\nWhat almost every teacher describes as the real obstacle is not ability. It is that adults compare their first attempts with finished work by people who have practised for years, and stop. Children draw for a long time without doing this, which is one reason they improve.\nThe teacher Miriam Oyelaran puts it more directly: nobody expects to play the piano without lessons, yet the same person picks up a pencil, produces something disappointing, and concludes that they lack a gift.",
    questions: [
      { q: "What do teachers say drawing mainly requires?", options: ["Skill in looking","Expensive materials","A steady hand","Natural talent"], answer: 0, explanation: "'It is a skill of looking.'" },
      { q: "What mistake do people make drawing faces from memory?", options: ["They draw the mouth too wide","They make the eyes too large and too high","They forget the ears","They make the head too small"], answer: 1, explanation: "'A person drawing a face from memory draws what they know about faces: eyes too large, placed too high, because that is how the brain stores the idea of a face rather than its geometry.'" },
      { q: "Why does copying an upside-down photograph help?", options: ["It slows the drawing down","It is easier to see the lines","The image stops being a face and becomes shapes","It makes the paper easier to position"], answer: 2, explanation: "'Turned the wrong way, the picture stops being a face and becomes a set of shapes, and beginners who have been drawing badly for an hour produce something noticeably better within twenty minutes.'" },
      { q: "Why is drawing the spaces useful?", options: ["It uses less pencil","It is quicker","Spaces are simpler shapes","The brain has no expectations about gaps"], answer: 3, explanation: "'A second common exercise is to draw the spaces between objects rather than the objects, because the brain has no strong expectations about the shape of a gap.'" },
      { q: "How long does reasonable progress take?", options: ["About six months at three hours a week","Several years","It cannot be predicted","A few weeks"], answer: 0, explanation: "'Teachers commonly say that a person practising three hours a week will draw recognisably well within about six months, which is neither instant nor a lifetime.'" },
      { q: "What do teachers regard as the real obstacle?", options: ["Bad early teaching","Comparing first attempts with expert work","Poor materials","Lack of time"], answer: 1, explanation: "'It is that adults compare their first attempts with finished work by people who have practised for years, and stop.'" }
    ]
  },
  {
    id: "pet-rmc25-06",
    title: "The Library That Lends Seeds",
    text: "In a corner of the public library in Waverly Bridge there is a wooden cabinet of small drawers containing seeds. Members may take up to six packets a season, free, and are asked to bring seeds back in the autumn from whatever they grow.\nThe collection holds about two hundred varieties of vegetable and flower, and roughly sixty of them are local: kinds that were grown in the area for generations and are not sold by any seed company, because a company must produce a variety in quantity and register it, and a bean grown by fifteen families in one valley will never justify that.\nThe librarian who started it, Marguerite Okafor, is careful about the returning part. Not every plant produces seed that grows true. Peas and beans mostly do; anything in the cabbage or squash families crosses easily with its neighbours, so the seed of a courgette may produce something nobody planned. The cabinet is therefore arranged in three sections by difficulty, and the labels say plainly which ones a beginner should not save.\nAbout a third of borrowers return seed, which Marguerite says is roughly what she expected and is enough. Twelve regular savers supply most of what comes back, and she has learned to concentrate her time on them rather than on persuading everybody.\nThe collection's most valuable variety arrived by accident. A man of ninety brought in an envelope of tomato seed his mother had saved every year since 1946, kept in a tin in a cold bedroom. It grew, and it turned out to be a variety recorded in a 1930s catalogue and believed lost.\nIt is now grown by about four hundred people in eleven countries, all from that envelope, and Marguerite says that fact is worth more than any argument she could make about why the cabinet exists.",
    questions: [
      { q: "How does the seed library work?", options: ["Only gardeners may join","Members buy seeds cheaply","Members take seeds free and may return some","Seeds are lent for one week"], answer: 2, explanation: "'Members may take up to six packets a season, free, and are asked to bring seeds back in the autumn from whatever they grow.'" },
      { q: "Why are some varieties not sold commercially?", options: ["They produce no seed","They grow badly","They are protected by law","Small local varieties are not worth registering"], answer: 3, explanation: "'The collection holds about two hundred varieties of vegetable and flower, and roughly sixty of them are local: kinds that were grown in the area for generations and are not sold by any seed company, because a company must produce a variety in quantity and register it, and a bean grown by fifteen families in one valley will never justify that.'" },
      { q: "Why is the cabinet divided into three sections?", options: ["By difficulty of saving seed","By season","By popularity","By plant size"], answer: 0, explanation: "'The cabinet is therefore arranged in three sections by difficulty, and the labels say plainly which ones a beginner should not save.'" },
      { q: "Which plants are easiest to save seed from?", options: ["Tomatoes","Peas and beans","Courgettes","Cabbages"], answer: 1, explanation: "'Peas and beans mostly do; anything in the cabbage or squash families crosses easily with its neighbours, so the seed of a courgette may produce something nobody planned.'" },
      { q: "How does Marguerite use her time?", options: ["Visiting other libraries","Persuading all borrowers to return seed","Concentrating on twelve regular savers","Growing seed herself"], answer: 2, explanation: "'Twelve regular savers supply most of what comes back, and she has learned to concentrate her time on them rather than on persuading everybody.'" },
      { q: "What was special about the tomato seed?", options: ["It came from another country","It produced enormous fruit","It was the oldest seed ever grown","It was a lost variety from the 1930s"], answer: 3, explanation: "'It grew, and it turned out to be a variety recorded in a 1930s catalogue and believed lost.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
