/* PET Prep bank: Reading multiple choice (B1) — wave 19 */
(function () {
var BANK = [
  {
    id: "pet-rmc19-01",
    title: "Why Onions Make You Cry",
    text: "Cutting an onion makes most people's eyes water, and the reason is a chemical defence that only works when the plant is damaged.\nAn onion contains two things that are kept apart while the plant is whole: a group of sulphur compounds, and an enzyme stored in a separate part of the cell. Cutting the onion breaks the cell walls and allows them to mix. A series of reactions follows within seconds, and the final product is a gas that rises from the cut surface.\nWhen this gas reaches the eye, it dissolves in the thin layer of liquid on its surface and forms a mild acid. The eye responds as it would to any irritation, by producing tears to wash it away, and this happens whether or not the person wants it to.\nThe purpose, from the plant's point of view, is defence. An animal that bites into an onion gets an unpleasant surprise, and one that does so twice generally learns.\nThe usual advice is a mixture of the useful and the useless. Chilling the onion for half an hour genuinely helps, because the reactions are slower at low temperatures and less gas is produced. A sharp knife helps, because it cuts cells rather than crushing them. Cutting under running water works and makes the onion difficult to hold. Holding a piece of bread in your mouth, a very popular suggestion, has no effect that anybody has been able to measure.\nOne further point is worth knowing. The gas is heavier than air but rises from the board on the warm air around it, so cutting on a low surface, or simply standing back a little, reduces the effect noticeably. Onions that have been stored for a long time generally produce more of it than fresh ones.",
    questions: [
      { q: "What happens when an onion is cut?", options: ["Two substances that were separate mix together","The onion begins to dry out","Sugar turns into acid","Water escapes from the cells"], answer: 0, explanation: "'Cutting the onion breaks the cell walls and allows them to mix.'" },
      { q: "Why do the eyes water?", options: ["The eye becomes dry","The gas forms a mild acid on the eye","The gas is very hot","Dust from the onion enters the eye"], answer: 1, explanation: "'When this gas reaches the eye, it dissolves in the thin layer of liquid on its surface and forms a mild acid.'" },
      { q: "What is the purpose of the reaction for the plant?", options: ["To attract insects", "To keep the onion fresh", "To defend against animals", "To help the onion grow"], answer: 2, explanation: "'The purpose, from the plant's point of view, is defence.'" },
      { q: "Why does chilling the onion help?", options: ["It stops the enzyme forming","It makes the onion easier to cut","It hardens the skin","Reactions are slower when cold"], answer: 3, explanation: "'Chilling the onion for half an hour genuinely helps, because the reactions are slower at low temperatures and less gas is produced.'" },
      { q: "What is said about holding bread in your mouth?", options: ["No measurable effect has been found","It is dangerous","It works very well","It works only for large onions"], answer: 0, explanation: "'Holding a piece of bread in your mouth, a very popular suggestion, has no effect that anybody has been able to measure.'" },
      { q: "Which onions produce more of the gas?", options: ["Ones grown in warm countries","Ones stored for a long time","Very fresh ones","Small ones"], answer: 1, explanation: "'Onions that have been stored for a long time generally produce more of it than fresh ones.'" }
    ]
  },
  {
    id: "pet-rmc19-02",
    title: "Recording the Sounds of a City",
    text: "For nine years, Ottilie Vance has been recording the ordinary sounds of the city she lives in. She has about four thousand recordings, each between one and ten minutes long, and every one is labelled with a place, a date and a time.\nShe is not a musician and does not use the recordings to make anything. The project began when the market near her flat was rebuilt and she realised, standing in the new one, that she could not remember what the old one had sounded like, although she had walked through it several times a week for eleven years.\nWhat she records is deliberately unremarkable: a bus stop in the rain, a school at half past three, a launderette, a particular stairwell. Anything that seems interesting she tends to avoid, because interesting sounds get recorded by other people and ordinary ones do not.\nThe collection has already become historical in ways she did not plan. Three of her recordings are of a factory that closed in 2019, and one is of a type of ticket machine that no longer exists anywhere in the city. She has two hours of a swimming pool that is now a block of flats.\nShe has noticed something that she cannot fully explain. People react much more strongly to old recordings of places than to old photographs of them. When she played twenty minutes of the old market at a local history evening, several people in the room cried, and nobody had reacted that way to the photographs shown earlier.\nThe collection is kept in three places, one of them a library, because she is aware that a hard drive in a flat is not a way of keeping anything for fifty years, which is roughly when she thinks the recordings will start to be genuinely useful.",
    questions: [
      { q: "What does Ottilie record?", options: ["Sounds of birds and animals","Interviews with residents","Ordinary everyday city sounds","Music performed in the street"], answer: 2, explanation: "'What she records is deliberately unremarkable: a bus stop in the rain, a school at half past three, a launderette, a particular stairwell.'" },
      { q: "Why did she begin?", options: ["She was asked by a library","She studied sound at university","She wanted to make music","She could not remember how a rebuilt market sounded"], answer: 3, explanation: "'The project began when the market near her flat was rebuilt and she realised, standing in the new one, that she could not remember what the old one had sounded like, although she had walked through it several times a week for eleven years.'" },
      { q: "Why does she avoid interesting sounds?", options: ["Other people already record them","They are too loud","They change too quickly","They are harder to record"], answer: 0, explanation: "'Anything that seems interesting she tends to avoid, because interesting sounds get recorded by other people and ordinary ones do not.'" },
      { q: "How has the collection changed in value?", options: ["It has been copied by others","It has become historical unexpectedly","It has been sold to a museum","It is used by film makers"], answer: 1, explanation: "'The collection has already become historical in ways she did not plan.'" },
      { q: "What has she noticed about people's reactions?", options: ["They prefer photographs", "They find recordings confusing", "They react more strongly to sound than to photographs", "They rarely recognise the places"], answer: 2, explanation: "'People react much more strongly to old recordings of places than to old photographs of them.'" },
      { q: "Why is the collection kept in three places?", options: ["Because the library requested it","To keep copies at different quality","To share it with other cities","Because one hard drive will not last fifty years"], answer: 3, explanation: "'The collection is kept in three places, one of them a library, because she is aware that a hard drive in a flat is not a way of keeping anything for fifty years, which is roughly when she thinks the recordings will start to be genuinely useful.'" }
    ]
  },
  {
    id: "pet-rmc19-03",
    title: "Two Years on the Night Desk",
    text: "I worked as a night porter in a small hotel from eleven at night until seven in the morning, alone, for two years. People assume the job is quiet. It is quiet for about five hours and then it is not, and the difficulty is that you cannot predict which five.\nThe work itself was simple: check in late arrivals, answer the telephone, deal with anything that happened, and prepare the breakfast room at six. What made it hard was being the only person in a building containing forty sleeping strangers, responsible for all of them, at three in the morning.\nMost nights nothing happened. During my two years I dealt with one small fire in a kitchen, two people who needed an ambulance, one guest locked out of the building in a towel, and a very large number of people who could not work the coffee machine.\nThe part that surprised me was the conversations. People who cannot sleep come downstairs, and a person at four in the morning in a hotel lobby will tell a stranger things they would not tell anybody in daylight. I heard about divorces, job interviews, illnesses and, on three occasions, funerals people were travelling to. My job was to listen and to make tea, and I became reasonably good at both.\nThe damage was to my sleep, and it lasted longer than the job did. Working nights is not simply being awake at unusual hours; the body's clock does not adjust properly, and mine took about eight months to return to normal after I stopped.\nI would not do it again. But I learned something in that lobby that I have never learned anywhere else, which is that almost everybody is carrying something, and that most of them will tell you if you have nothing else to do and are not going anywhere.",
    questions: [
      { q: "What is the difficulty with the job's quiet hours?", options: ["You cannot predict when they will be","They are always at the same time","There is nothing to do at all","They make the night pass slowly"], answer: 0, explanation: "'It is quiet for about five hours and then it is not, and the difficulty is that you cannot predict which five.'" },
      { q: "What made the job hard?", options: ["The low pay","Being alone and responsible for everyone","The number of guests arriving late","The physical work"], answer: 1, explanation: "'What made it hard was being the only person in a building containing forty sleeping strangers, responsible for all of them, at three in the morning.'" },
      { q: "What surprised the writer?", options: ["How little there was to do","How dangerous the building was","The conversations with guests who could not sleep","How often emergencies happened"], answer: 2, explanation: "'The part that surprised me was the conversations.'" },
      { q: "What was the writer's role in those conversations?", options: ["To record complaints","To call for help","To give advice","To listen and make tea"], answer: 3, explanation: "'My job was to listen and to make tea, and I became reasonably good at both.'" },
      { q: "What lasting effect did the job have?", options: ["Damage to sleep lasting months afterwards", "A fear of hotels", "Problems with the writer's hearing", "A permanent change of career"], answer: 0, explanation: "'Working nights is not simply being awake at unusual hours; the body's clock does not adjust properly, and mine took about eight months to return to normal after I stopped.'" },
      { q: "What did the writer learn?", options: ["That hotels are dangerous at night", "That most people carry something and will talk", "That night work suits some people", "That guests are usually difficult"], answer: 1, explanation: "'I learned something in that lobby that I have never learned anywhere else, which is that almost everybody is carrying something, and that most of them will tell you if you have nothing else to do and are not going anywhere.'" }
    ]
  },
  {
    id: "pet-rmc19-04",
    title: "The Roof of the Village Hall",
    text: "Kilmaddy Village Hall needed a new roof. The estimate was one hundred and six thousand pounds, and the hall's income, from a playgroup, a badminton club and about forty bookings a year, was under nine thousand.\nThe committee's first plan was the obvious one: apply for grants. Over eighteen months they applied to eleven organisations and received two refusals, eight non-replies and one grant of four thousand pounds. The chair at the time, an accountant called Peter Nwosu, described the process afterwards as an education, and said the most useful thing he learned was that almost all such funds want to pay for something new rather than to repair something old.\nSo the committee changed its approach entirely. They stopped asking for money for a roof and started asking for money for what the roof would allow. The hall was the only large indoor space within nine kilometres, and once it closed, four groups would have nowhere to go. Two of those groups were for older residents, and one of the funds that had refused a roof was willing to fund a programme for isolated older people, which happened to require a building that did not leak.\nThe money came from six sources in the end, including a company that paid for the scaffolding rather than the roof, because scaffolding was something its own business understood.\nThe work took eleven weeks. During that time the playgroup met in a farm building and the badminton club did not meet at all, losing eleven of its thirty members permanently.\nThe hall reopened in April. Mr Nwosu, who has since stepped down, says the committee's real mistake was not the failed applications. It was waiting until the roof was leaking before starting, when the same work would have cost about a third as much four years earlier.",
    questions: [
      { q: "What was the problem with the hall's finances?", options: ["Its money had been spent on other repairs","It owed money to the council","Its income was far below the cost of the roof","It had no bookings at all"], answer: 2, explanation: "'The estimate was one hundred and six thousand pounds, and the hall's income, from a playgroup, a badminton club and about forty bookings a year, was under nine thousand.'" },
      { q: "What was the result of the first eighteen months?", options: ["The committee gave up entirely","The council paid for the work","Most funds agreed to help","Only one small grant was received"], answer: 3, explanation: "'Over eighteen months they applied to eleven organisations and received two refusals, eight non-replies and one grant of four thousand pounds.'" },
      { q: "What did Peter Nwosu learn?", options: ["That funds prefer new projects to repairs","That small halls are never funded","That applications must be written by experts","That grants take years to arrive"], answer: 0, explanation: "'The chair at the time, an accountant called Peter Nwosu, described the process afterwards as an education, and said the most useful thing he learned was that almost all such funds want to pay for something new rather than to repair something old.'" },
      { q: "How did the committee change its approach?", options: ["They applied to the same funds again","They asked for money for what the roof would allow","They raised the hire charges","They asked residents for donations"], answer: 1, explanation: "'They stopped asking for money for a roof and started asking for money for what the roof would allow.'" },
      { q: "What happened to the badminton club?", options: ["It grew during the closure","It moved to a farm building","It lost eleven members permanently","It closed completely"], answer: 2, explanation: "'During that time the playgroup met in a farm building and the badminton club did not meet at all, losing eleven of its thirty members permanently.'" },
      { q: "What does Mr Nwosu see as the real mistake?", options: ["Closing the hall for too long","Applying to the wrong organisations","Choosing an expensive builder","Waiting until the roof leaked"], answer: 3, explanation: "'It was waiting until the roof was leaking before starting, when the same work would have cost about a third as much four years earlier.'" }
    ]
  },
  {
    id: "pet-rmc19-05",
    title: "How Bees Tell Each Other Where to Go",
    text: "A honeybee that finds a good source of food returns to the hive and dances. The dance is not decoration: it contains the direction and the distance of the food, and other bees leave the hive and fly to it.\nThis was worked out in the 1940s by Karl von Frisch, who spent years marking individual bees with paint and watching what happened. He found that a bee walks in a figure of eight, and that the straight part in the middle is the part that carries the information.\nThe angle of that straight run, measured against vertical, is the angle between the sun and the food. A bee dancing straight upwards is saying that the food lies in the direction of the sun. A bee dancing thirty degrees to the left is saying that the food is thirty degrees to the left of it.\nDistance is given by the length of the straight run and the time the bee spends on it. A longer run means further away, and the relationship is close enough that a researcher watching a dance can predict where the food is to within a few metres.\nThe most impressive part is that the sun moves. A bee that dances for an hour changes the angle of its dance gradually, by about fifteen degrees, keeping the message correct as the sun crosses the sky. The bee is, in effect, doing the calculation continuously in the dark, inside the hive, where it cannot see the sun at all.\nVon Frisch's work was doubted for decades. It was accepted after other researchers built an artificial bee that could perform the dance, released it in a hive, and watched real bees fly to a place where no bee had been.",
    questions: [
      { q: "What information does the dance carry?", options: ["Direction and distance of the food","The number of bees needed","The time of day","Only the type of flower"], answer: 0, explanation: "'The dance is not decoration: it contains the direction and the distance of the food, and other bees leave the hive and fly to it.'" },
      { q: "How did von Frisch study the bees?", options: ["By using artificial bees","By marking individuals with paint","By filming the hive","By counting bees at flowers"], answer: 1, explanation: "'This was worked out in the 1940s by Karl von Frisch, who spent years marking individual bees with paint and watching what happened.'" },
      { q: "What does dancing straight upwards mean?", options: ["The hive must move","The food is very close","The food is in the direction of the sun","The food is directly above"], answer: 2, explanation: "'A bee dancing straight upwards is saying that the food lies in the direction of the sun.'" },
      { q: "How is distance communicated?", options: ["By the loudness of the sound","By the speed of the wings","By how many times the dance repeats","By the length and duration of the straight run"], answer: 3, explanation: "'Distance is given by the length of the straight run and the time the bee spends on it.'" },
      { q: "Why is the changing angle so impressive?", options: ["The bee cannot see the sun inside the hive", "The bee dances for many hours", "Other bees must copy it exactly", "The hive is completely silent"], answer: 0, explanation: "'The bee is, in effect, doing the calculation continuously in the dark, inside the hive, where it cannot see the sun at all.'" },
      { q: "How was the theory finally accepted?", options: ["Von Frisch repeated his own work", "An artificial bee made real bees fly to a new place", "New microscopes were invented", "Bees were tracked by radio"], answer: 1, explanation: "'It was accepted after other researchers built an artificial bee that could perform the dance, released it in a hive, and watched real bees fly to a place where no bee had been.'" }
    ]
  },
  {
    id: "pet-rmc19-06",
    title: "The Bookshop Where You Decide the Price",
    text: "There are no prices in the second-hand bookshop on Fennel Street. Customers choose their books, take them to the counter, and pay whatever they think is right, into a box that the owner does not watch.\nThe owner, Hal Bercovitch, did not begin with a philosophy. He began with a practical problem: pricing second-hand books takes an enormous amount of time. He estimated that he was spending eleven hours a week deciding whether a particular paperback was worth two pounds or three, and that the total difference across a year was smaller than what those hours were worth.\nSo he stopped. The sign in the window explains the system in four sentences and asks customers to consider what the book is worth to them and what keeps a shop open.\nThe results have been consistent for six years. His average payment per book is slightly higher than the prices he used to charge. A small number of people pay nothing, which he expected, and a small number pay a great deal more than any price he would have set, which he did not.\nHe is careful about how this is reported, because journalists want a story about human goodness and he does not think that is quite the story. His shop is small, customers can be seen by other customers, and most people are in the shop for twenty minutes and speak to him. He believes those three things do most of the work, and that the same system in a large anonymous shop would probably fail.\nThere is one rule. Anybody who says they cannot pay is told to take the book anyway, and Hal says that in six years this has been said to him about forty times, and that on every occasion but two the person came back later and put money in the box.",
    questions: [
      { q: "How do customers pay?", options: ["Only by card","A fixed price per book","Whatever they decide, into a box","By weight"], answer: 2, explanation: "'Customers choose their books, take them to the counter, and pay whatever they think is right, into a box that the owner does not watch.'" },
      { q: "Why did Hal introduce the system?", options: ["Because a friend suggested it","To compete with online shops","To attract more customers","Because pricing books took too much time"], answer: 3, explanation: "'He began with a practical problem: pricing second-hand books takes an enormous amount of time.'" },
      { q: "What has been the financial result?", options: ["Slightly higher average payments than his old prices", "A large fall in income", "Exactly the same as before", "Income too irregular to measure"], answer: 0, explanation: "'His average payment per book is slightly higher than the prices he used to charge.'" },
      { q: "What surprised him?", options: ["That some people paid nothing", "That some paid far more than he would have charged", "That customers complained", "That other shops copied him"], answer: 1, explanation: "'A small number of people pay nothing, which he expected, and a small number pay a great deal more than any price he would have set, which he did not.'" },
      { q: "Why does he doubt the system would work elsewhere?", options: ["Other owners would not accept it", "Books are cheaper elsewhere", "His shop is small and personal", "Larger shops sell new books"], answer: 2, explanation: "'He believes those three things do most of the work, and that the same system in a large anonymous shop would probably fail.'" },
      { q: "What happens if somebody cannot pay?", options: ["They may come back another day","They leave their name","They do work in the shop","They take the book anyway"], answer: 3, explanation: "'Anybody who says they cannot pay is told to take the book anyway, and Hal says that in six years this has been said to him about forty times, and that on every occasion but two the person came back later and put money in the box.'" }
    ]
  }
];
if (typeof module !== "undefined") { module.exports = BANK; return; }
window.READING = window.READING || { mc: [], gap: [], match: [] };
window.READING.mc = (window.READING.mc || []).concat(BANK);
})();
