/* PET Prep extra bank: speaking */
(function () {
  var BANK = [
    { question: "Describe a meal you really enjoyed recently.", bullets: ["what you ate", "who you were with", "why it was special"] },
    { question: "Talk about a journey you will never forget.", bullets: ["where you went", "how you travelled", "what happened on the way"] },
    { question: "Describe your favourite room at home.", bullets: ["what it looks like", "what you do there", "why you like it best"] },
    { question: "Talk about a film or series you have watched more than once.", bullets: ["what it is about", "when you first saw it", "why you watch it again"] },
    { question: "Describe a present you gave to someone.", bullets: ["what it was", "who it was for", "how they reacted"] },
    { question: "Talk about a sport or game you play with friends.", bullets: ["how you play it", "where and when you play", "why it is fun together"] },
    { question: "Describe a shop you often go to.", bullets: ["what it sells", "how often you go", "why you prefer it to others"] },
    { question: "Talk about something new you learned to do this year.", bullets: ["what you learned", "who or what helped you", "how you feel about it now"] },
    { question: "Describe a festival or celebration in your country.", bullets: ["when it happens", "what people do", "what you enjoy most about it"] },
    { question: "Talk about your favourite way to spend a Sunday.", bullets: ["what you usually do", "who you spend it with", "why it helps you relax"] },
    { question: "Describe an animal you like.", bullets: ["what it looks like", "where you can see it", "why you find it interesting"] },
    { question: "Talk about a song you often listen to.", bullets: ["what kind of music it is", "when you listen to it", "how it makes you feel"] },
    { question: "Describe a teacher you remember well.", bullets: ["what subject they taught", "what they were like", "why you remember them"] },
    { question: "Talk about a time you cooked something yourself.", bullets: ["what you made", "how it went", "what you would do differently"] },
    { question: "Describe your ideal holiday.", bullets: ["where you would go", "who you would take", "what you would do there"] },
    { question: "Talk about a book or comic you enjoyed.", bullets: ["what it was about", "how you found it", "who you would recommend it to"] },
    { question: "Describe a market or shopping centre in your town.", bullets: ["where it is", "what you can buy there", "what the atmosphere is like"] },
    { question: "Talk about a piece of technology you use every day.", bullets: ["what it is", "what you use it for", "how life would be without it"] },
    { question: "Describe a birthday you remember well.", bullets: ["how old you were", "how you celebrated", "why it was memorable"] },
    { question: "Talk about the weather you like best.", bullets: ["what kind of weather it is", "what you do on days like that", "why you prefer it"] },
    { question: "Describe a friend you often spend time with.", bullets: ["how you met", "what you do together", "what makes them a good friend"] },
    { question: "Talk about something you collected or would like to collect.", bullets: ["what it is", "how you started or would start", "why it interests you"] },
    { question: "Describe a building in your town that you find interesting.", bullets: ["where it is", "what it looks like", "why you notice it"] },
    { question: "Talk about a day trip you took with your family or class.", bullets: ["where you went", "what you did there", "what the best moment was"] },
    { question: "Describe your morning routine on a school or work day.", bullets: ["what time you get up", "what you do first", "what you would like to change"] },
    { question: "Talk about a hobby you would like to try in the future.", bullets: ["what it is", "why it attracts you", "what you need to start"] },
    { question: "Describe a photo you like looking at.", bullets: ["who or what is in it", "when it was taken", "why it means a lot to you"] },
    { question: "Talk about a competition you took part in or watched.", bullets: ["what kind of competition it was", "what happened", "how you felt at the end"] },
    { question: "Describe the town or city where you live.", bullets: ["how big it is", "what visitors can do there", "what you would improve"] },
    { question: "Talk about clothes you wear at weekends.", bullets: ["what you usually wear", "where you buy your clothes", "why comfort or style matters to you"] },
    { question: "Describe a game you played when you were younger.", bullets: ["how you played it", "who you played with", "why children enjoy it"] },
    { question: "Talk about a language you would like to learn.", bullets: ["which language it is", "why you chose it", "how you would practise it"] },
    { question: "Describe a café or restaurant you like.", bullets: ["where it is", "what you usually order", "why you keep going back"] },
    { question: "Talk about how you use the internet for studying.", bullets: ["what websites or apps you use", "what works well for you", "what problems there are"] },
    { question: "Describe an evening you spent with friends recently.", bullets: ["where you were", "what you did", "why it was a good evening"] },
    { question: "Talk about a job you think is very difficult.", bullets: ["what the job is", "why it is hard", "whether you could do it"] },
    { question: "Describe something you own that is very old.", bullets: ["what it is", "where it came from", "why you still keep it"] },
    { question: "Talk about the best time of day for you.", bullets: ["which time it is", "what you do then", "why you feel good at that time"] },
    { question: "Describe a park or green space you know well.", bullets: ["where it is", "what people do there", "when you usually go"] },
    { question: "Talk about a surprise you once had.", bullets: ["what the surprise was", "who organised it", "how you reacted"] },
    { question: "Describe how you travel to school or work.", bullets: ["what transport you use", "how long it takes", "what you do during the journey"] },
    { question: "Talk about a famous person you would like to meet.", bullets: ["who they are", "what you would ask them", "why you admire them"] },
    { question: "Describe a lesson or class you really enjoyed.", bullets: ["what the subject was", "what you did in the lesson", "why it was different from usual"] },
    { question: "Talk about something you do to help at home.", bullets: ["what jobs you do", "how often you do them", "how you feel about helping"] },
    { question: "Describe an item you lost and how you felt.", bullets: ["what you lost", "how you tried to find it", "what happened in the end"] },
    { question: "Talk about a place in your country you want to visit one day.", bullets: ["where it is", "what it is famous for", "why you haven't been yet"] },
    { question: "Describe the kind of films you enjoy most.", bullets: ["which type you prefer", "where you usually watch them", "who you watch them with"] },
    { question: "Talk about a small change that made your life better.", bullets: ["what you changed", "why you decided to do it", "what difference it has made"] }
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  SPEAKING = SPEAKING.concat(BANK);
})();
