/* PET Prep extra bank: vocab wave 3 */
(function () {
  var BANK = [
    /* ---------- House & home ---------- */
    { front: "attic", pos: "n.", def: "the room at the top of a house under the roof", example: "We keep old boxes and toys in the attic.", zh: "閣樓" },
    { front: "basement", pos: "n.", def: "a room or floor below the level of the ground", example: "The washing machine is down in the basement.", zh: "地下室" },
    { front: "blanket", pos: "n.", def: "a thick warm cover for a bed", example: "She put an extra blanket on the bed in winter.", zh: "毯子" },
    { front: "bookcase", pos: "n.", def: "a piece of furniture with shelves for books", example: "The bookcase in the living room is completely full.", zh: "書櫃" },
    { front: "carpet", pos: "n.", def: "thick material that covers a floor", example: "Don't spill juice on the new carpet!", zh: "地毯" },
    { front: "ceiling", pos: "n.", def: "the top inside surface of a room", example: "The lamp hangs from the middle of the ceiling.", zh: "天花板" },
    { front: "cellar", pos: "n.", def: "an underground room, often used for storing things", example: "The old house has a cellar full of dusty bottles.", zh: "地窖" },
    { front: "chest of drawers", pos: "n.", def: "a piece of furniture with drawers for keeping clothes", example: "Your socks are in the top drawer of the chest of drawers.", zh: "五斗櫃" },
    { front: "cottage", pos: "n.", def: "a small house, usually in the countryside", example: "They rented a cottage near the lake for a week.", zh: "小屋、村舍" },
    { front: "curtain", pos: "n.", def: "a piece of cloth that covers a window", example: "She opened the curtains to let the sunshine in.", zh: "窗簾" },
    { front: "cushion", pos: "n.", def: "a soft bag filled with material that you sit on or lean against", example: "The sofa has four bright red cushions.", zh: "抱枕、坐墊" },
    { front: "drawer", pos: "n.", def: "a box-shaped part of furniture that slides in and out", example: "The scissors are in the kitchen drawer.", zh: "抽屜" },
    { front: "duvet", pos: "n.", def: "a thick warm cover filled with feathers or soft material for a bed", example: "In summer we use a lighter duvet.", zh: "羽絨被" },
    { front: "fence", pos: "n.", def: "a wooden or metal structure around a garden or field", example: "The dog jumped over the fence into the neighbour's garden.", zh: "圍籬" },
    { front: "flat", pos: "n.", def: "a set of rooms for living in, on one floor of a building", example: "They live in a flat on the top floor.", zh: "公寓" },
    { front: "furniture", pos: "n.", def: "things such as chairs, tables and beds in a room", example: "The furniture in their house is old but beautiful.", zh: "家具" },
    { front: "garage sale", pos: "n.", def: "a sale of used things outside someone's house", example: "I bought this lamp for a pound at a garage sale.", zh: "舊物出售" },
    { front: "gate", pos: "n.", def: "a door in a fence or outside wall", example: "Please close the gate so the dog doesn't get out.", zh: "大門、柵門" },
    { front: "ground floor", pos: "n.", def: "the floor of a building at street level", example: "The kitchen and living room are on the ground floor.", zh: "一樓" },
    { front: "housework", pos: "n.", def: "the work of keeping a house clean and tidy", example: "We share the housework between everyone in the family.", zh: "家事" },
    { front: "iron", pos: "n.", def: "an electrical object used to make clothes smooth", example: "Be careful, the iron is still hot.", zh: "熨斗" },
    { front: "kettle", pos: "n.", def: "a container used for boiling water", example: "Put the kettle on and let's have some tea.", zh: "熱水壺" },
    { front: "ladder", pos: "n.", def: "a piece of equipment with steps for climbing up", example: "He climbed a ladder to clean the windows.", zh: "梯子" },
    { front: "landlord", pos: "n.", def: "a person who owns a house or flat and rents it to others", example: "The landlord promised to repair the heating.", zh: "房東" },
    { front: "lawn", pos: "n.", def: "an area of short grass in a garden", example: "Dad cuts the lawn every Sunday morning.", zh: "草坪" },
    { front: "microwave", pos: "n.", def: "a small oven that heats food very quickly", example: "Just heat the soup in the microwave for two minutes.", zh: "微波爐" },
    { front: "mirror", pos: "n.", def: "a piece of glass in which you can see yourself", example: "She checked her hair in the mirror before leaving.", zh: "鏡子" },
    { front: "neighbour", pos: "n.", def: "a person who lives next to or near you", example: "Our neighbours water our plants when we're away.", zh: "鄰居" },
    { front: "oven", pos: "n.", def: "the part of a cooker where you bake or roast food", example: "The bread needs forty minutes in the oven.", zh: "烤箱" },
    { front: "pillow", pos: "n.", def: "a soft object you rest your head on in bed", example: "This pillow is too hard for me to sleep well.", zh: "枕頭" },
    { front: "plug", pos: "n.", def: "the object at the end of a wire that connects a machine to electricity", example: "The plug on the lamp needs changing.", zh: "插頭" },
    { front: "property", pos: "n.", def: "a building or land that someone owns", example: "House prices are high, so property is hard to buy.", zh: "房地產、財產" },
    { front: "rent", pos: "n.", def: "money paid regularly to live in someone else's house", example: "The rent for this flat is eight hundred pounds a month.", zh: "房租" },
    { front: "roof", pos: "n.", def: "the top outside covering of a building", example: "The storm blew several tiles off the roof.", zh: "屋頂" },
    { front: "shelf", pos: "n.", def: "a flat board fixed to a wall for putting things on", example: "Put the cups back on the top shelf.", zh: "架子" },
    { front: "sink", pos: "n.", def: "the bowl in a kitchen where you wash dishes", example: "Leave the dirty plates in the sink; I'll wash them later.", zh: "水槽" },
    { front: "stairs", pos: "n.", def: "a set of steps inside a building", example: "My bedroom is at the top of the stairs.", zh: "樓梯" },
    { front: "switch", pos: "n.", def: "a small object that turns electricity on or off", example: "The light switch is just inside the door.", zh: "開關" },
    { front: "tap", pos: "n.", def: "the object that controls water coming from a pipe", example: "Turn off the tap while you brush your teeth.", zh: "水龍頭" },
    { front: "tenant", pos: "n.", def: "a person who pays rent to live in a house or flat", example: "The previous tenants left the flat very clean.", zh: "房客" },
    { front: "vacuum cleaner", pos: "n.", def: "a machine that cleans floors by sucking up dirt", example: "The vacuum cleaner is too loud to use at night.", zh: "吸塵器" },
    { front: "wallpaper", pos: "n.", def: "decorated paper that covers the walls of a room", example: "The bedroom has flowery blue wallpaper.", zh: "壁紙" },
    { front: "wardrobe", pos: "n.", def: "a tall cupboard for hanging clothes in", example: "Hang your jacket in the wardrobe.", zh: "衣櫃" },
    { front: "washing machine", pos: "n.", def: "a machine that washes clothes", example: "The washing machine broke down in the middle of a wash.", zh: "洗衣機" },
    { front: "cupboard", pos: "n.", def: "a piece of furniture with doors, used for storing things", example: "The glasses are in the cupboard above the sink.", zh: "櫥櫃" },
    { front: "fridge", pos: "n.", def: "a machine that keeps food and drinks cold", example: "There's some cold juice in the fridge.", zh: "冰箱" },
    { front: "freezer", pos: "n.", def: "a machine that keeps food frozen", example: "Take the fish out of the freezer for dinner.", zh: "冷凍庫" },
    { front: "doorbell", pos: "n.", def: "a button by a door that makes a sound when pressed", example: "The doorbell rang while we were having lunch.", zh: "門鈴" },
    { front: "garden", pos: "n.", def: "the area of grass and plants next to a house", example: "The children are playing in the back garden.", zh: "花園、庭院" },
    { front: "chimney", pos: "n.", def: "the pipe that takes smoke from a fire up through the roof", example: "Smoke rose from the cottage chimney.", zh: "煙囪" },
    /* ---------- Food & drink ---------- */
    { front: "beef", pos: "n.", def: "meat from a cow", example: "We had roast beef with vegetables for Sunday lunch.", zh: "牛肉" },
    { front: "biscuit", pos: "n.", def: "a small flat dry cake, usually sweet", example: "She dipped a biscuit in her tea.", zh: "餅乾" },
    { front: "boil", pos: "v.", def: "to cook something in very hot water", example: "Boil the eggs for six minutes.", zh: "煮沸、水煮" },
    { front: "bowl", pos: "n.", def: "a round deep dish for food", example: "He had a big bowl of cereal for breakfast.", zh: "碗" },
    { front: "cabbage", pos: "n.", def: "a large round vegetable with thick green leaves", example: "Grandma makes soup with cabbage and potatoes.", zh: "高麗菜、甘藍" },
    { front: "cereal", pos: "n.", def: "a breakfast food made from grain, eaten with milk", example: "The children have cereal and fruit every morning.", zh: "麥片" },
    { front: "cherry", pos: "n.", def: "a small round red or black fruit with a stone", example: "The cake was decorated with fresh cherries.", zh: "櫻桃" },
    { front: "chilli", pos: "n.", def: "a small vegetable with a very hot taste", example: "Be careful; this sauce has a lot of chilli in it.", zh: "辣椒" },
    { front: "cream", pos: "n.", def: "the thick fatty liquid that comes from milk", example: "Would you like cream with your strawberries?", zh: "鮮奶油" },
    { front: "cucumber", pos: "n.", def: "a long green vegetable eaten raw in salads", example: "She made sandwiches with cucumber and cheese.", zh: "小黃瓜" },
    { front: "curry", pos: "n.", def: "a dish of meat or vegetables cooked in a spicy sauce", example: "We ordered a mild chicken curry with rice.", zh: "咖哩" },
    { front: "dessert", pos: "n.", def: "sweet food eaten at the end of a meal", example: "For dessert there's apple pie or ice cream.", zh: "甜點" },
    { front: "dish", pos: "n.", def: "food prepared in a particular way, or a plate for food", example: "The restaurant's most famous dish is grilled fish.", zh: "菜餚、盤" },
    { front: "flavour", pos: "n.", def: "the taste of food or drink", example: "Which flavour of ice cream do you want?", zh: "口味" },
    { front: "flour", pos: "n.", def: "a powder made from grain, used for making bread and cakes", example: "Mix the flour with the eggs and milk.", zh: "麵粉" },
    { front: "fork", pos: "n.", def: "a tool with points used for eating food", example: "He ate the noodles with a fork instead of chopsticks.", zh: "叉子" },
    { front: "fry", pos: "v.", def: "to cook food in hot oil", example: "Fry the onions until they turn golden.", zh: "油煎、油炸" },
    { front: "grape", pos: "n.", def: "a small green or purple fruit that grows in bunches", example: "She brought a bunch of grapes to the picnic.", zh: "葡萄" },
    { front: "grill", pos: "v.", def: "to cook food under or over direct heat", example: "Grill the fish for five minutes on each side.", zh: "燒烤" },
    { front: "herb", pos: "n.", def: "a plant used to add flavour to food", example: "She grows herbs like basil and mint on the balcony.", zh: "香草" },
    { front: "honey", pos: "n.", def: "the sweet sticky food made by bees", example: "I like honey on toast for breakfast.", zh: "蜂蜜" },
    { front: "ingredient", pos: "n.", def: "one of the foods used to make a dish", example: "The only ingredients are eggs, sugar and flour.", zh: "食材、原料" },
    { front: "jam", pos: "n.", def: "a sweet food made from fruit and sugar, spread on bread", example: "Grandma's strawberry jam is the best.", zh: "果醬" },
    { front: "jug", pos: "n.", def: "a container with a handle for holding and pouring liquids", example: "There's a jug of water on the table.", zh: "水壺、壺" },
    { front: "lamb", pos: "n.", def: "meat from a young sheep", example: "The menu includes roast lamb with mint sauce.", zh: "羊肉" },
    { front: "lettuce", pos: "n.", def: "a vegetable with large green leaves eaten in salads", example: "Wash the lettuce before you make the salad.", zh: "萵苣、生菜" },
    { front: "melon", pos: "n.", def: "a large sweet juicy fruit with a thick skin", example: "We had cold melon as a starter.", zh: "甜瓜、哈密瓜" },
    { front: "mushroom", pos: "n.", def: "a plant with a round top that is often eaten", example: "Do you want mushrooms on your pizza?", zh: "蘑菇" },
    { front: "onion", pos: "n.", def: "a round vegetable with layers and a strong smell", example: "Cutting onions always makes me cry.", zh: "洋蔥" },
    { front: "pan", pos: "n.", def: "a metal container used for cooking", example: "Heat some oil in a large pan.", zh: "平底鍋" },
    { front: "peach", pos: "n.", def: "a soft round fruit with sweet yellow flesh and furry skin", example: "The peaches from the market are wonderfully sweet.", zh: "桃子" },
    { front: "pear", pos: "n.", def: "a sweet green or yellow fruit that is narrow at the top", example: "He packed a pear and a sandwich for lunch.", zh: "梨子" },
    { front: "pepper", pos: "n.", def: "a spicy powder for food, or a red, green or yellow vegetable", example: "Add a little salt and pepper to the soup.", zh: "胡椒；甜椒" },
    { front: "pineapple", pos: "n.", def: "a large sweet tropical fruit with rough skin", example: "Some people love pineapple on pizza; others hate it.", zh: "鳳梨" },
    { front: "plum", pos: "n.", def: "a small soft round fruit with red or purple skin", example: "The plum tree in our garden gives fruit every August.", zh: "李子" },
    { front: "pork", pos: "n.", def: "meat from a pig", example: "This region is famous for its pork dishes.", zh: "豬肉" },
    { front: "portion", pos: "n.", def: "the amount of food served to one person", example: "The portions in that restaurant are enormous.", zh: "一份（食物）" },
    { front: "raw", pos: "adj.", def: "not cooked", example: "Some fish can be eaten raw if it's very fresh.", zh: "生的" },
    { front: "recipe", pos: "n.", def: "instructions for cooking a dish", example: "Can you give me the recipe for this cake?", zh: "食譜" },
    { front: "roast", pos: "v.", def: "to cook food such as meat in an oven", example: "We roasted a chicken with potatoes and carrots.", zh: "烘烤" },
    { front: "sauce", pos: "n.", def: "a thick liquid eaten with food to add flavour", example: "The pasta comes with a tomato and basil sauce.", zh: "醬汁" },
    { front: "slice", pos: "n.", def: "a thin flat piece cut from something", example: "Would you like another slice of cake?", zh: "薄片、一片" },
    { front: "snack", pos: "n.", def: "a small amount of food eaten between meals", example: "Fruit is a healthier snack than crisps.", zh: "點心、零食" },
    { front: "sour", pos: "adj.", def: "having a sharp taste like a lemon", example: "The apples were too sour to eat.", zh: "酸的" },
    { front: "spicy", pos: "adj.", def: "having a strong hot flavour", example: "Thai food is often quite spicy.", zh: "辣的、加香料的" },
    { front: "spoon", pos: "n.", def: "a tool with a round end used for eating soup or stirring", example: "You'll need a spoon for the soup.", zh: "湯匙" },
    { front: "strawberry", pos: "n.", def: "a small soft red fruit with tiny seeds on the outside", example: "Strawberries with cream is a classic summer dessert.", zh: "草莓" },
    { front: "tasty", pos: "adj.", def: "having a good flavour", example: "The soup was simple but really tasty.", zh: "美味的" },
    { front: "vegetarian", pos: "n.", def: "a person who does not eat meat or fish", example: "My sister has been a vegetarian for five years.", zh: "素食者" },
    { front: "yoghurt", pos: "n.", def: "a thick slightly sour food made from milk", example: "I usually have yoghurt and fruit for breakfast.", zh: "優格" },
    /* ---------- Restaurants & eating out ---------- */
    { front: "menu", pos: "n.", def: "the list of food you can order in a restaurant", example: "The waiter brought us the menu and some water.", zh: "菜單" },
    { front: "order", pos: "v.", def: "to ask for food or drink in a restaurant", example: "Are you ready to order, or do you need a minute?", zh: "點餐" },
    { front: "starter", pos: "n.", def: "a small dish eaten at the beginning of a meal", example: "For my starter I'll have the vegetable soup.", zh: "前菜" },
    { front: "main course", pos: "n.", def: "the largest dish of a meal", example: "The main course was grilled salmon with rice.", zh: "主菜" },
    { front: "bill", pos: "n.", def: "a piece of paper showing how much you must pay", example: "Could we have the bill, please?", zh: "帳單" },
    { front: "tip", pos: "n.", def: "extra money you give to thank someone for service", example: "We left a good tip because the service was excellent.", zh: "小費" },
    { front: "service", pos: "n.", def: "the help and attention you get in a shop or restaurant", example: "The food was great, but the service was slow.", zh: "服務" },
    { front: "book a table", pos: "phrase", def: "to reserve a table in a restaurant", example: "I booked a table for four at eight o'clock.", zh: "訂位" },
    { front: "takeaway", pos: "n.", def: "food you buy in a restaurant and eat somewhere else", example: "Let's get a takeaway and watch a film at home.", zh: "外帶餐點" },
    { front: "self-service", pos: "adj.", def: "describing a place where you serve yourself", example: "The station café is self-service, so it's quick.", zh: "自助式的" },
    { front: "buffet", pos: "n.", def: "a meal where you serve yourself from many dishes", example: "The hotel breakfast is a buffet with hot and cold food.", zh: "自助餐" },
    { front: "thirsty", pos: "adj.", def: "needing to drink something", example: "After the match we were all really thirsty.", zh: "口渴的" },
    { front: "hungry", pos: "adj.", def: "needing to eat something", example: "I'm so hungry I could eat two pizzas.", zh: "飢餓的" },
    { front: "chopsticks", pos: "n.", def: "a pair of thin sticks used for eating East Asian food", example: "He's learning to eat noodles with chopsticks.", zh: "筷子" },
    { front: "napkin", pos: "n.", def: "a piece of cloth or paper used to keep clean while eating", example: "She wiped her fingers on a paper napkin.", zh: "餐巾" },
    { front: "toast", pos: "n.", def: "bread made brown by heating", example: "I had toast with butter and jam this morning.", zh: "吐司" },
    { front: "soft drink", pos: "n.", def: "a cold sweet drink without alcohol", example: "The children ordered soft drinks with their meal.", zh: "無酒精飲料、汽水" },
    { front: "mineral water", pos: "n.", def: "water from underground sold in bottles", example: "A bottle of mineral water, please, still not sparkling.", zh: "礦泉水" },
    { front: "taste", pos: "v.", def: "to have a particular flavour, or to try food", example: "This sauce tastes a bit too salty to me.", zh: "嚐起來；品嚐" },
    { front: "smell", pos: "v.", def: "to have a particular smell, or to notice a smell", example: "Something smells wonderful in the kitchen.", zh: "聞起來；聞" },
    { front: "chew", pos: "v.", def: "to break food into small pieces with your teeth", example: "Chew your food slowly and enjoy the meal.", zh: "咀嚼" },
    { front: "swallow", pos: "v.", def: "to make food or drink go down your throat", example: "The tablet was so big it was hard to swallow.", zh: "吞嚥" },
    { front: "pour", pos: "v.", def: "to make a liquid flow out of a container", example: "He poured tea into all the cups.", zh: "倒（液體）" },
    { front: "stir", pos: "v.", def: "to mix a liquid by moving a spoon round", example: "Stir the soup so it doesn't stick to the pan.", zh: "攪拌" },
    { front: "mix", pos: "v.", def: "to put different things together to make one thing", example: "Mix the butter and sugar until smooth.", zh: "混合" },
    { front: "add", pos: "v.", def: "to put something with something else", example: "Add a little milk and stir again.", zh: "加入" },
    { front: "bake", pos: "v.", def: "to cook something such as bread or cakes in an oven", example: "We baked biscuits for the school fair.", zh: "烘焙" },
    { front: "serve", pos: "v.", def: "to give food or drink to someone", example: "Dinner is served between seven and nine.", zh: "上菜、服務" },
    { front: "peel", pos: "v.", def: "to remove the skin of fruit or vegetables", example: "Peel the potatoes and cut them into pieces.", zh: "削皮" },
    { front: "freeze", pos: "v.", def: "to become solid because of cold, or to keep food very cold", example: "You can freeze the extra soup for next week.", zh: "結冰、冷凍" },
    /* ---------- Shopping & money ---------- */
    { front: "afford", pos: "v.", def: "to have enough money to buy something", example: "We can't afford a new car this year.", zh: "負擔得起" },
    { front: "bargain", pos: "n.", def: "something bought for less than its usual price", example: "This coat was a real bargain in the sale.", zh: "便宜貨、划算的交易" },
    { front: "brand", pos: "n.", def: "the name of a product made by a particular company", example: "Which brand of trainers do you usually buy?", zh: "品牌" },
    { front: "cash", pos: "n.", def: "money in coins and notes", example: "Are you paying in cash or by card?", zh: "現金" },
    { front: "cash machine", pos: "n.", def: "a machine that gives you money from your bank account", example: "I need to find a cash machine before dinner.", zh: "提款機" },
    { front: "change", pos: "n.", def: "the money you get back when you pay too much", example: "The shop assistant gave me the wrong change.", zh: "找零" },
    { front: "cheque", pos: "n.", def: "a printed piece of paper you write on to pay from your bank", example: "Very few shops accept cheques these days.", zh: "支票" },
    { front: "coin", pos: "n.", def: "a piece of metal money", example: "The machine only takes one-pound coins.", zh: "硬幣" },
    { front: "cost", pos: "v.", def: "to have a particular price", example: "How much does a ticket to the concert cost?", zh: "花費、值……錢" },
    { front: "credit card", pos: "n.", def: "a plastic card used to buy things and pay later", example: "He paid for the flights with his credit card.", zh: "信用卡" },
    { front: "discount", pos: "n.", def: "a reduction in the price of something", example: "Students get a ten per cent discount at this shop.", zh: "折扣" },
    { front: "exchange", pos: "v.", def: "to change something for something else", example: "Can I exchange this shirt for a larger one?", zh: "交換、兌換" },
    { front: "banknote", pos: "n.", def: "a piece of paper money", example: "He paid with a fifty-euro banknote.", zh: "紙鈔" },
    { front: "on sale", pos: "phrase", def: "available to buy, especially at a lower price", example: "Winter coats are on sale this week.", zh: "特價中、出售中" },
    { front: "price", pos: "n.", def: "the amount of money you must pay for something", example: "The price of coffee has gone up again.", zh: "價格" },
    { front: "purse", pos: "n.", def: "a small bag for money, used especially by women", example: "She keeps her coins in a small leather purse.", zh: "錢包（女用）" },
    { front: "receipt", pos: "n.", def: "a piece of paper that proves you paid for something", example: "Keep the receipt in case you need to return it.", zh: "收據" },
    { front: "reduce", pos: "v.", def: "to make something smaller or less", example: "The shop reduced all prices by half.", zh: "減少、降低" },
    { front: "refund", pos: "n.", def: "money given back to you when you return something", example: "The shirt had a hole, so I asked for a refund.", zh: "退款" },
    { front: "shop assistant", pos: "n.", def: "a person who serves customers in a shop", example: "The shop assistant helped me find my size.", zh: "店員" },
    { front: "shopping centre", pos: "n.", def: "a large building with many shops inside", example: "The new shopping centre has a cinema on the top floor.", zh: "購物中心" },
    { front: "spend money on", pos: "phrase", def: "to use money to buy something", example: "He spends most of his money on computer games.", zh: "把錢花在……" },
    { front: "till", pos: "n.", def: "the machine in a shop where money is kept", example: "Please pay at the till by the exit.", zh: "收銀機" },
    { front: "trolley", pos: "n.", def: "a large basket on wheels used in supermarkets", example: "Our trolley was full by the time we reached the checkout.", zh: "購物推車" },
    { front: "try on", pos: "phr. v.", def: "to put on clothes to see if they fit", example: "Can I try on these jeans in a smaller size?", zh: "試穿" },
    { front: "wallet", pos: "n.", def: "a small flat case for money and cards", example: "I left my wallet at home, so I couldn't pay.", zh: "皮夾" },
    { front: "worth", pos: "adj.", def: "having a particular value", example: "This old watch is worth a lot of money.", zh: "值……的" },
    { front: "cost of living", pos: "phrase", def: "the amount of money people need for everyday life", example: "The cost of living in the capital is very high.", zh: "生活費用" },
    { front: "pocket money", pos: "n.", def: "money that parents give children regularly", example: "She saves half her pocket money every week.", zh: "零用錢" },
    { front: "second-hand", pos: "adj.", def: "not new; owned by someone else before", example: "He bought a second-hand bike in good condition.", zh: "二手的" },
    { front: "for sale", pos: "phrase", def: "available to be bought", example: "The house next door is for sale.", zh: "出售中" },
    { front: "in stock", pos: "phrase", def: "available in the shop now", example: "Sorry, we don't have that size in stock.", zh: "有存貨" },
    { front: "sold out", pos: "phrase", def: "with none left to buy", example: "Tickets for the show are completely sold out.", zh: "售完" },
    { front: "special offer", pos: "n.", def: "a lower price for a short time", example: "These biscuits are on special offer this week.", zh: "特價優惠" },
    { front: "window shopping", pos: "n.", def: "looking at things in shops without buying them", example: "We spent the afternoon window shopping in town.", zh: "逛街看櫥窗" },
    /* ---------- Phrasal verbs C ---------- */
    { front: "pay back", pos: "phr. v.", def: "to return money that you borrowed", example: "I'll pay you back as soon as I get my pocket money.", zh: "還錢" },
    { front: "save up", pos: "phr. v.", def: "to keep money over time to buy something", example: "She's saving up for a new laptop.", zh: "存錢" },
    { front: "give away", pos: "phr. v.", def: "to give something to someone without asking for money", example: "The shop is giving away free samples today.", zh: "贈送" },
    { front: "throw away", pos: "phr. v.", def: "to get rid of something you do not want", example: "Don't throw away those boxes; we can reuse them.", zh: "丟棄" },
    { front: "take back", pos: "phr. v.", def: "to return something to the shop where you bought it", example: "The radio didn't work, so I took it back.", zh: "退回" },
    { front: "put away", pos: "phr. v.", def: "to put something in the place where it is kept", example: "Put away your clothes before dinner, please.", zh: "收好" },
    { front: "tidy up", pos: "phr. v.", def: "to make a place neat and organised", example: "Let's tidy up the kitchen before Mum gets home.", zh: "整理、收拾" },
    { front: "clean up", pos: "phr. v.", def: "to remove dirt and make a place clean", example: "It took hours to clean up after the party.", zh: "清理" },
    { front: "wash up", pos: "phr. v.", def: "to wash the dishes after a meal", example: "You cooked, so I'll wash up tonight.", zh: "洗碗" },
    { front: "heat up", pos: "phr. v.", def: "to make food warm again", example: "I'll heat up the leftovers for lunch.", zh: "加熱" },
    { front: "cut up", pos: "phr. v.", def: "to cut something into small pieces", example: "Cut up the vegetables for the salad.", zh: "切碎" },
    { front: "eat out", pos: "phr. v.", def: "to have a meal in a restaurant instead of at home", example: "We eat out about once a month.", zh: "外出用餐" },
    { front: "turn on", pos: "phr. v.", def: "to make a machine or light start working", example: "Turn on the oven ten minutes before you start.", zh: "打開（電器）" },
    { front: "turn off", pos: "phr. v.", def: "to make a machine or light stop working", example: "Remember to turn off the lights when you leave.", zh: "關掉（電器）" },
    { front: "turn down", pos: "phr. v.", def: "to make a machine produce less sound or heat, or to refuse an offer", example: "Please turn down the music; the baby is sleeping.", zh: "調低；拒絕" },
    { front: "turn up (volume)", pos: "phr. v.", def: "to make a machine produce more sound or heat", example: "Turn up the radio; I love this song!", zh: "調高" },
    { front: "plug in", pos: "phr. v.", def: "to connect a machine to the electricity supply", example: "Plug in the kettle and make some tea.", zh: "插電" },
    { front: "hang up", pos: "phr. v.", def: "to put clothes on a hook, or to end a phone call", example: "Hang up your coat by the door.", zh: "掛起；掛斷電話" },
    { front: "run out", pos: "phr. v.", def: "to be used completely so that none is left", example: "The milk has run out; can you buy some more?", zh: "耗盡" },
    { front: "look for", pos: "phr. v.", def: "to try to find something", example: "I'm looking for my other shoe; have you seen it?", zh: "尋找" },
    /* ---------- Meals & everyday home life ---------- */
    { front: "breakfast", pos: "n.", def: "the first meal of the day", example: "We usually have breakfast at seven thirty.", zh: "早餐" },
    { front: "brunch", pos: "n.", def: "a late morning meal instead of breakfast and lunch", example: "On Sundays we often have brunch at a café.", zh: "早午餐" },
    { front: "picnic basket", pos: "n.", def: "a basket used for carrying food for a picnic", example: "She filled the picnic basket with sandwiches and fruit.", zh: "野餐籃" },
    { front: "housewarming", pos: "n.", def: "a party to celebrate moving into a new home", example: "They're having a housewarming party on Saturday.", zh: "喬遷派對" },
    { front: "chore", pos: "n.", def: "a boring job you must do regularly, especially at home", example: "Emptying the bins is my least favourite chore.", zh: "家務雜事" },
    { front: "decorate", pos: "v.", def: "to paint a room or make a place look attractive", example: "We decorated the hall with balloons for the party.", zh: "裝飾、粉刷" },
    { front: "hang", pos: "v.", def: "to fix something at the top so the lower part is free", example: "Let's hang the picture above the sofa.", zh: "懸掛" },
    { front: "lock", pos: "v.", def: "to close something with a key", example: "Did you lock the front door when you left?", zh: "鎖上" },
    { front: "sweep", pos: "v.", def: "to clean a floor with a brush", example: "He swept the kitchen floor after dinner.", zh: "掃地" },
    { front: "polish", pos: "v.", def: "to rub something to make it shine", example: "She polished her shoes before the interview.", zh: "擦亮" },
    { front: "dust", pos: "v.", def: "to remove dust from furniture", example: "I dust the shelves once a week.", zh: "撢灰塵" },
    { front: "leak", pos: "v.", def: "to let liquid or gas escape through a hole", example: "The roof leaks when it rains heavily.", zh: "漏水" },
    { front: "repairman", pos: "n.", def: "a person whose job is fixing things", example: "The repairman fixed the washing machine in an hour.", zh: "修理工" },
    { front: "electricity", pos: "n.", def: "the power that makes lights and machines work", example: "The storm cut off the electricity for two hours.", zh: "電力" },
    { front: "gas", pos: "n.", def: "a substance like air used for cooking and heating", example: "We cook with gas, but the heating is electric.", zh: "瓦斯" },
    /* ---------- Containers & quantities ---------- */
    { front: "bottle", pos: "n.", def: "a glass or plastic container for liquids", example: "Take a bottle of water with you on the walk.", zh: "瓶子" },
    { front: "box", pos: "n.", def: "a container with straight sides, often made of cardboard", example: "She gave me a box of chocolates for my birthday.", zh: "盒子" },
    { front: "can", pos: "n.", def: "a metal container for food or drink", example: "He opened a can of tomatoes for the sauce.", zh: "罐頭" },
    { front: "carton", pos: "n.", def: "a cardboard or plastic container for food or drink", example: "There's a carton of orange juice in the fridge.", zh: "紙盒（裝）" },
    { front: "packet", pos: "n.", def: "a small paper or plastic container for goods", example: "We shared a packet of crisps on the bus.", zh: "小包" },
    { front: "tin", pos: "n.", def: "a metal container in which food is sold", example: "Open a tin of beans for lunch.", zh: "罐頭、錫罐" },
    { front: "tub", pos: "n.", def: "a round plastic container with a lid", example: "There's a tub of ice cream in the freezer.", zh: "圓盒、桶" },
    { front: "loaf", pos: "n.", def: "bread baked in one large piece", example: "Could you buy a loaf of brown bread?", zh: "一條（麵包）" },
    { front: "bunch", pos: "n.", def: "a group of things growing or tied together", example: "He arrived with a bunch of flowers for his mother.", zh: "一束、一串" },
    { front: "bar", pos: "n.", def: "a small block of something such as chocolate or soap", example: "She keeps a bar of chocolate in her desk.", zh: "一條、一塊" },
    { front: "litre", pos: "n.", def: "a unit for measuring liquid", example: "The recipe needs half a litre of milk.", zh: "公升" },
    { front: "kilogram", pos: "n.", def: "a unit for measuring weight, equal to 1000 grams", example: "I bought two kilograms of apples at the market.", zh: "公斤" },
    { front: "spoonful", pos: "n.", def: "the amount that a spoon can hold", example: "Add two spoonfuls of sugar to the mixture.", zh: "一匙的量" },
    { front: "plenty of", pos: "phrase", def: "a lot of; more than enough", example: "Don't hurry; we have plenty of time.", zh: "許多、充足" },
    { front: "a couple of", pos: "phrase", def: "two, or a small number of", example: "I'll be ready in a couple of minutes.", zh: "幾個、兩個" },
    /* ---------- Money & banking ---------- */
    { front: "owe", pos: "v.", def: "to need to pay money back to someone", example: "You owe me five pounds for the cinema ticket.", zh: "欠（錢）" },
    { front: "waste", pos: "v.", def: "to use money, time or things badly", example: "Don't waste your money on things you don't need.", zh: "浪費" },
    { front: "earn a living", pos: "phrase", def: "to get money for the things you need by working", example: "He earns a living as a taxi driver.", zh: "謀生" },
    { front: "in debt", pos: "phrase", def: "owing money to someone", example: "Many students leave university in debt.", zh: "負債" },
    { front: "account", pos: "n.", def: "an arrangement to keep money in a bank, or a record of money", example: "I put half my birthday money into my savings account.", zh: "帳戶" },
    { front: "savings", pos: "n.", def: "money that you have kept and not spent", example: "They used their savings to buy a small boat.", zh: "存款、積蓄" },
    { front: "loan", pos: "n.", def: "money that you borrow, especially from a bank", example: "They took out a loan to open the café.", zh: "貸款" },
    { front: "interest", pos: "n.", def: "extra money you pay for borrowing, or receive for saving", example: "The bank pays very little interest on savings now.", zh: "利息" },
    { front: "tax", pos: "n.", def: "money that people must pay to the government", example: "Part of everyone's salary goes on tax.", zh: "稅" },
    { front: "wealthy", pos: "adj.", def: "having a lot of money", example: "The hotel is popular with wealthy tourists.", zh: "富有的" },
    { front: "broke", pos: "adj.", def: "having no money, used in informal speech", example: "I can't come out tonight; I'm completely broke.", zh: "沒錢的" },
    { front: "generous", pos: "adj.", def: "happy to give money, help or time to others", example: "It was generous of her to pay for everyone.", zh: "慷慨的" },
    { front: "mean", pos: "adj.", def: "not liking to spend money or share things", example: "He's too mean to buy his friends a coffee.", zh: "小氣的" },
    { front: "value", pos: "n.", def: "how much something is worth", example: "The value of the painting has doubled in ten years.", zh: "價值" },
    { front: "free of charge", pos: "phrase", def: "costing nothing", example: "Delivery is free of charge on orders over fifty pounds.", zh: "免費" },
    /* ---------- Describing homes ---------- */
    { front: "cosy", pos: "adj.", def: "warm, comfortable and pleasant", example: "The cottage has a cosy living room with a fireplace.", zh: "溫馨舒適的" },
    { front: "spacious", pos: "adj.", def: "having a lot of room", example: "The kitchen is bright and spacious.", zh: "寬敞的" },
    { front: "furnished", pos: "adj.", def: "containing furniture", example: "They rented a fully furnished flat near the university.", zh: "附家具的" },
    { front: "messy", pos: "adj.", def: "untidy; not clean or organised", example: "His bedroom is always messy, with clothes everywhere.", zh: "凌亂的" },
    { front: "well-equipped", pos: "adj.", def: "having all the useful equipment that is needed", example: "The apartment has a small but well-equipped kitchen.", zh: "設備齊全的" },
    { front: "downstairs", pos: "adv.", def: "on or to a lower floor of a building", example: "The bathroom is downstairs, next to the kitchen.", zh: "樓下" },
    { front: "upstairs", pos: "adv.", def: "on or to a higher floor of a building", example: "The children are playing upstairs in their room.", zh: "樓上" },
    { front: "indoors", pos: "adv.", def: "inside a building", example: "It started to rain, so we moved the party indoors.", zh: "在室內" },
    { front: "outdoors", pos: "adv.", def: "outside, not in a building", example: "In summer we eat outdoors almost every evening.", zh: "在戶外" },
    { front: "next door", pos: "phrase", def: "in the house or room beside yours", example: "The family next door have three noisy dogs.", zh: "隔壁" },
    /* ---------- Food shopping ---------- */
    { front: "grocery", pos: "n.", def: "food and other goods sold in a food shop", example: "I do the grocery shopping on Friday evenings.", zh: "食品雜貨" },
    { front: "butcher", pos: "n.", def: "a person or shop that sells meat", example: "The butcher recommended this cut for roasting.", zh: "肉販、肉舖" },
    { front: "greengrocer", pos: "n.", def: "a shop or person that sells fruit and vegetables", example: "The greengrocer always gives us the freshest tomatoes.", zh: "蔬果店" },
    { front: "checkout", pos: "n.", def: "the place in a supermarket where you pay", example: "There were long queues at every checkout.", zh: "結帳櫃檯" },
    { front: "shopping list", pos: "n.", def: "a list of things you plan to buy", example: "I forgot my shopping list and bought all the wrong things.", zh: "購物清單" },
    { front: "label", pos: "n.", def: "a piece of paper on a product that gives information", example: "Read the label to check the sugar content.", zh: "標籤" },
    { front: "sell-by date", pos: "n.", def: "the date printed on food showing when it should be sold by", example: "Check the sell-by date on the milk before you buy it.", zh: "有效期限" },
    { front: "frozen", pos: "adj.", def: "kept at a very low temperature so it stays fresh", example: "We keep frozen vegetables for busy evenings.", zh: "冷凍的" },
    { front: "organic", pos: "adj.", def: "grown without artificial chemicals", example: "Organic eggs cost more but taste better.", zh: "有機的" },
    { front: "product", pos: "n.", def: "something that is made or grown to be sold", example: "This shop only sells products from local farms.", zh: "產品" },
    /* ---------- More food & drink ---------- */
    { front: "beans", pos: "n.", def: "seeds of a plant that are cooked and eaten", example: "Beans on toast is a quick and cheap meal.", zh: "豆子" },
    { front: "carrot", pos: "n.", def: "a long orange vegetable that grows underground", example: "Rabbits love eating carrots.", zh: "紅蘿蔔" },
    { front: "corn", pos: "n.", def: "a tall plant with yellow seeds that are eaten", example: "We grilled some corn at the barbecue.", zh: "玉米" },
    { front: "garlic", pos: "n.", def: "a plant like a small onion with a strong taste", example: "Fry the garlic gently so it doesn't burn.", zh: "大蒜" },
    { front: "ham", pos: "n.", def: "meat from a pig's leg, usually eaten cold", example: "I'd like a ham and cheese sandwich, please.", zh: "火腿" },
    { front: "nut", pos: "n.", def: "a dry fruit with a hard shell", example: "This cake contains nuts, so check for allergies.", zh: "堅果" },
    { front: "oil", pos: "n.", def: "a liquid from plants used for cooking", example: "Use olive oil for the salad dressing.", zh: "油" },
    { front: "pea", pos: "n.", def: "a small round green seed eaten as a vegetable", example: "We had fish with peas and mashed potato.", zh: "豌豆" },
    { front: "pumpkin", pos: "n.", def: "a large round orange vegetable", example: "Mum makes delicious pumpkin soup in autumn.", zh: "南瓜" },
    { front: "salmon", pos: "n.", def: "a large fish with pink flesh", example: "Grilled salmon is the most popular dish here.", zh: "鮭魚" },
    { front: "sausage", pos: "n.", def: "meat pressed into a long thin shape", example: "We cooked sausages over the campfire.", zh: "香腸" },
    { front: "seafood", pos: "n.", def: "fish and other sea creatures that you can eat", example: "The harbour restaurants serve wonderful seafood.", zh: "海鮮" },
    { front: "spinach", pos: "n.", def: "a vegetable with large dark green leaves", example: "Add the spinach at the end of cooking.", zh: "菠菜" },
    { front: "steak", pos: "n.", def: "a thick flat piece of meat or fish", example: "He ordered his steak well done.", zh: "牛排" },
    { front: "tuna", pos: "n.", def: "a large sea fish, often sold in tins", example: "She made a salad with tuna and sweetcorn.", zh: "鮪魚" },
    { front: "vinegar", pos: "n.", def: "a sour liquid used in cooking and salads", example: "Mix oil and vinegar for a simple dressing.", zh: "醋" },
    { front: "wheat", pos: "n.", def: "the grain used for making flour and bread", example: "Fields of wheat stretched to the horizon.", zh: "小麥" },
    { front: "dairy", pos: "adj.", def: "made from milk", example: "She avoids dairy products because of an allergy.", zh: "乳製的" },
    { front: "juicy", pos: "adj.", def: "full of juice", example: "These oranges are wonderfully sweet and juicy.", zh: "多汁的" },
    { front: "crispy", pos: "adj.", def: "pleasantly hard and dry, breaking easily", example: "The chips were hot and crispy.", zh: "酥脆的" },
    { front: "bitter", pos: "adj.", def: "having a strong sharp taste that is not sweet", example: "The coffee was too bitter without sugar.", zh: "苦的" },
    { front: "salty", pos: "adj.", def: "tasting of salt", example: "Sea water is too salty to drink.", zh: "鹹的" },
    { front: "fizzy", pos: "adj.", def: "containing many small bubbles", example: "The children aren't allowed fizzy drinks at school.", zh: "有氣泡的" },
    { front: "still", pos: "adj.", def: "describing a drink without bubbles", example: "Would you like still or sparkling water?", zh: "無氣泡的" },
    { front: "ripe", pos: "adj.", def: "ready to be eaten, used about fruit", example: "Wait until the bananas are ripe before eating them.", zh: "成熟的" },
    { front: "rotten", pos: "adj.", def: "old and no longer good to eat", example: "There was a rotten apple at the bottom of the bag.", zh: "腐爛的" },
    { front: "vegan", pos: "n.", def: "a person who eats no animal products at all", example: "The café has a separate menu for vegans.", zh: "純素食者" },
    { front: "diet", pos: "n.", def: "the food you usually eat, or a plan to eat less", example: "A balanced diet includes plenty of vegetables.", zh: "飲食、節食" },
    { front: "appetite", pos: "n.", def: "the feeling of wanting to eat", example: "The long walk gave us all a huge appetite.", zh: "食慾" },
    { front: "leftovers", pos: "n.", def: "food remaining after a meal", example: "We had the leftovers from Sunday lunch on Monday.", zh: "剩菜" },
    /* ---------- At home: rooms & parts ---------- */
    { front: "hall", pos: "n.", def: "the area just inside the front door of a house", example: "Leave your wet shoes in the hall, please.", zh: "玄關、門廳" },
    { front: "landing", pos: "n.", def: "the area at the top of the stairs in a house", example: "The bathroom is on the landing, first door on the right.", zh: "樓梯平台" },
    { front: "study", pos: "n.", def: "a room in a house used for reading and working", example: "Dad works from home in his study.", zh: "書房" },
    { front: "utility room", pos: "n.", def: "a room for washing machines and cleaning equipment", example: "The freezer is out in the utility room.", zh: "洗衣間、雜物間" },
    { front: "porch", pos: "n.", def: "a covered area at the entrance of a house", example: "We sat on the porch and watched the rain.", zh: "門廊" },
    { front: "terrace", pos: "n.", def: "a flat outdoor area beside a building", example: "Breakfast is served on the terrace in summer.", zh: "露臺" },
    { front: "shutter", pos: "n.", def: "a wooden or metal cover for a window", example: "The houses have blue shutters on every window.", zh: "百葉窗板" },
    { front: "brick", pos: "n.", def: "a small hard block used for building walls", example: "The old school is built of red brick.", zh: "磚塊" },
    { front: "concrete", pos: "n.", def: "a hard grey building material made with cement", example: "The new car park is a plain concrete building.", zh: "混凝土" },
    { front: "wooden", pos: "adj.", def: "made of wood", example: "They ate at a long wooden table in the kitchen.", zh: "木製的" },
    /* ---------- Everyday objects ---------- */
    { front: "alarm clock", pos: "n.", def: "a clock that wakes you up with a sound", example: "My alarm clock didn't go off, so I overslept.", zh: "鬧鐘" },
    { front: "candle", pos: "n.", def: "a stick of wax that gives light when it burns", example: "We lit candles when the electricity went off.", zh: "蠟燭" },
    { front: "comb", pos: "n.", def: "a flat object with teeth for making hair tidy", example: "He pulled a comb through his wet hair.", zh: "梳子" },
    { front: "matches", pos: "n.", def: "short sticks that make fire when rubbed on a box", example: "Keep matches away from small children.", zh: "火柴" },
    { front: "scissors", pos: "n.", def: "a tool with two blades for cutting paper or cloth", example: "Use scissors to cut along the dotted line.", zh: "剪刀" },
    { front: "soap", pos: "n.", def: "a substance used for washing your body", example: "There's a new bar of soap by the bath.", zh: "肥皂" },
    { front: "toothpaste", pos: "n.", def: "a substance you put on a brush to clean your teeth", example: "We're nearly out of toothpaste.", zh: "牙膏" },
    { front: "shampoo", pos: "n.", def: "liquid soap for washing your hair", example: "This shampoo smells of coconut.", zh: "洗髮精" },
    { front: "bucket", pos: "n.", def: "an open container with a handle for carrying water", example: "He filled a bucket with water to wash the car.", zh: "水桶" },
    { front: "string", pos: "n.", def: "thin rope used for tying things", example: "Tie the box with a piece of string.", zh: "細繩" },
    /* ---------- Cafés & drinks ---------- */
    { front: "café", pos: "n.", def: "a small restaurant serving drinks and light meals", example: "We met at the little café opposite the park.", zh: "咖啡館" },
    { front: "barista", pos: "n.", def: "a person who makes and serves coffee in a café", example: "The barista drew a heart in the milk foam.", zh: "咖啡師" },
    { front: "espresso", pos: "n.", def: "very strong coffee served in a small cup", example: "He drinks a double espresso every morning.", zh: "濃縮咖啡" },
    { front: "herbal tea", pos: "n.", def: "a hot drink made from plants rather than tea leaves", example: "She ordered a herbal tea before bed.", zh: "花草茶" },
    { front: "smoothie", pos: "n.", def: "a thick drink made from mixed fruit", example: "I had a mango and banana smoothie for breakfast.", zh: "果昔" },
    { front: "milkshake", pos: "n.", def: "a cold drink made of milk mixed with fruit or chocolate", example: "The diner is famous for its strawberry milkshakes.", zh: "奶昔" },
    { front: "straw", pos: "n.", def: "a thin tube for drinking through", example: "The café has switched to paper straws.", zh: "吸管" },
    { front: "lemonade", pos: "n.", def: "a sweet drink with a lemon flavour", example: "We made fresh lemonade for the summer party.", zh: "檸檬水" },
    { front: "cocoa", pos: "n.", def: "a hot chocolate drink, or the powder it is made from", example: "A cup of hot cocoa is perfect on a snowy evening.", zh: "可可" },
    { front: "refill", pos: "n.", def: "another drink to fill your empty cup or glass", example: "Coffee refills are free before ten o'clock.", zh: "續杯" },
    /* ---------- Ordering & complaining ---------- */
    { front: "overcooked", pos: "adj.", def: "cooked for too long", example: "The vegetables were soft and overcooked.", zh: "煮過頭的" },
    { front: "undercooked", pos: "adj.", def: "not cooked for long enough", example: "Send the chicken back if it looks undercooked.", zh: "沒煮熟的" },
    { front: "speciality", pos: "n.", def: "a food or dish that a place is famous for", example: "Seafood soup is the speciality of this restaurant.", zh: "招牌菜、特產" },
    { front: "reserve", pos: "v.", def: "to arrange for something to be kept for you", example: "I've reserved two seats in the front row.", zh: "預訂、保留" },
    { front: "cancel an order", pos: "phrase", def: "to say you no longer want what you asked for", example: "We had to cancel our order because the wait was too long.", zh: "取消訂單" },
    { front: "out of order", pos: "phrase", def: "not working, used about machines", example: "The coffee machine is out of order again.", zh: "故障" },
    { front: "make a complaint", pos: "phrase", def: "to formally say that something is wrong", example: "She made a complaint about the dirty table.", zh: "提出投訴" },
    /* ---------- Extra home, food & shopping ---------- */
    { front: "apartment block", pos: "n.", def: "a large building divided into many flats", example: "They live on the ninth floor of an apartment block.", zh: "公寓大樓" },
    { front: "bungalow", pos: "n.", def: "a house built all on one level", example: "My grandparents moved to a bungalow because of the stairs.", zh: "平房" },
    { front: "estate agent", pos: "n.", def: "a person whose job is selling houses and flats", example: "The estate agent showed us three flats in one afternoon.", zh: "房仲" },
    { front: "mortgage", pos: "n.", def: "money borrowed from a bank to buy a house", example: "They'll be paying the mortgage for twenty-five years.", zh: "房貸" },
    { front: "neighbouring", pos: "adj.", def: "next to or near a place", example: "People come from neighbouring towns to visit the market.", zh: "鄰近的" },
    { front: "removal van", pos: "n.", def: "a large vehicle used when people move house", example: "The removal van arrived at eight on moving day.", zh: "搬家貨車" },
    { front: "doormat", pos: "n.", def: "a small mat by a door for cleaning your shoes", example: "Wipe your boots on the doormat before you come in.", zh: "門墊" },
    { front: "smoke alarm", pos: "n.", def: "a device that makes a loud noise if there is smoke", example: "Test your smoke alarm once a month.", zh: "煙霧警報器" },
    { front: "power cut", pos: "n.", def: "a time when the electricity supply stops", example: "We played cards by candlelight during the power cut.", zh: "停電" },
    { front: "central heating", pos: "n.", def: "a system that heats a whole building from one place", example: "The house is old and has no central heating.", zh: "中央暖氣" },
    { front: "flatmate", pos: "n.", def: "a person you share a flat with", example: "My flatmate cooks and I do the washing-up.", zh: "室友" },
    { front: "spare room", pos: "n.", def: "an extra bedroom for guests", example: "You can sleep in the spare room when you visit.", zh: "客房" },
    { front: "sofa", pos: "n.", def: "a long comfortable seat for two or more people", example: "The cat is asleep on the sofa again.", zh: "沙發" },
    { front: "armchair", pos: "n.", def: "a comfortable chair with parts for resting your arms", example: "Grandpa reads in his favourite armchair every evening.", zh: "扶手椅" },
    { front: "lamp", pos: "n.", def: "a device that gives light, especially one on a table", example: "She turned on the lamp beside her bed.", zh: "檯燈" },
    { front: "blind", pos: "n.", def: "a cover that you pull down over a window", example: "Pull down the blinds to keep the room cool.", zh: "窗簾（捲簾）" },
    { front: "tile", pos: "n.", def: "a flat square piece used to cover floors, walls or roofs", example: "The bathroom has white tiles on the walls.", zh: "磁磚" },
    { front: "stool", pos: "n.", def: "a seat without a back or arms", example: "He sat on a stool at the kitchen counter.", zh: "凳子" },
    { front: "tablecloth", pos: "n.", def: "a cloth that covers a table", example: "She spread a clean tablecloth for the guests.", zh: "桌巾" },
    { front: "tray", pos: "n.", def: "a flat object used for carrying food and drinks", example: "He brought breakfast upstairs on a tray.", zh: "托盤" },
    { front: "teapot", pos: "n.", def: "a container with a handle and spout for making tea", example: "The teapot holds enough tea for four cups.", zh: "茶壺" },
    { front: "saucer", pos: "n.", def: "a small plate that you put a cup on", example: "She put the cup back on its saucer.", zh: "茶碟" },
    { front: "mug", pos: "n.", def: "a large cup with straight sides, used without a saucer", example: "He drinks coffee from an enormous blue mug.", zh: "馬克杯" },
    { front: "corkscrew", pos: "n.", def: "a tool for opening bottles with corks", example: "We couldn't open the wine without a corkscrew.", zh: "開瓶器" },
    { front: "tin opener", pos: "n.", def: "a tool for opening tins of food", example: "The tin opener is in the top drawer.", zh: "開罐器" },
    { front: "dishwasher", pos: "n.", def: "a machine that washes plates and cups", example: "Load the dishwasher after dinner, please.", zh: "洗碗機" },
    { front: "cooker", pos: "n.", def: "a large piece of kitchen equipment for cooking food", example: "The new cooker has five gas rings.", zh: "爐具" },
    { front: "toaster", pos: "n.", def: "a machine that makes bread brown and crisp", example: "The toaster burned my bread again this morning.", zh: "烤麵包機" },
    { front: "blender", pos: "n.", def: "a machine that mixes food into liquid", example: "Put the fruit and yoghurt in the blender.", zh: "果汁機" },
    { front: "apron", pos: "n.", def: "a piece of clothing worn over clothes to keep them clean while cooking", example: "He put on an apron before making the pizza.", zh: "圍裙" },
    { front: "grater", pos: "n.", def: "a kitchen tool for cutting food into very small pieces", example: "Use the grater to add some cheese on top.", zh: "刨絲器" },
    { front: "rolling pin", pos: "n.", def: "a kitchen tool shaped like a tube for making pastry flat", example: "Roll out the dough with a rolling pin.", zh: "擀麵棍" },
    { front: "burnt", pos: "adj.", def: "damaged by too much heat or cooking", example: "The toast was completely burnt.", zh: "燒焦的" },
    { front: "homemade", pos: "adj.", def: "made at home, not bought from a shop", example: "Nothing beats homemade bread straight from the oven.", zh: "自製的" },
    { front: "instant", pos: "adj.", def: "able to be prepared very quickly", example: "He lives on instant noodles during exam week.", zh: "即食的、速成的" },
    { front: "nutritious", pos: "adj.", def: "containing things that help your body grow and stay healthy", example: "Beans are cheap and highly nutritious.", zh: "營養的" },
    { front: "filling", pos: "adj.", def: "making your stomach feel full", example: "The soup was surprisingly filling.", zh: "有飽足感的" },
    { front: "mild", pos: "adj.", def: "not strong or hot in flavour", example: "Choose the mild curry if you don't like spice.", zh: "溫和的、不辣的" },
    { front: "greasy", pos: "adj.", def: "containing or covered in too much oil", example: "The chips were too greasy for me.", zh: "油膩的" },
    { front: "stale", pos: "adj.", def: "no longer fresh, used about bread or air", example: "This bread has gone stale; let's feed it to the birds.", zh: "不新鮮的" },
    { front: "grocer", pos: "n.", def: "a person or shop selling food and household goods", example: "The corner grocer stays open until midnight.", zh: "雜貨商" },
    { front: "pharmacy", pos: "n.", def: "a shop where medicines are prepared and sold", example: "The pharmacy can give you advice about your cough.", zh: "藥房" },
    { front: "florist", pos: "n.", def: "a shop or person that sells flowers", example: "He stopped at the florist to buy roses.", zh: "花店" },
    { front: "jeweller", pos: "n.", def: "a shop or person that sells rings, necklaces and watches", example: "The ring was repaired at the jeweller's in town.", zh: "珠寶商" },
    { front: "kiosk", pos: "n.", def: "a small open shop selling newspapers, drinks or tickets", example: "We bought water from a kiosk by the beach.", zh: "小亭、攤位" },
    { front: "stall", pos: "n.", def: "a table or small shop in a market", example: "The fruit stall at the end has the best prices.", zh: "攤位" },
    { front: "shopkeeper", pos: "n.", def: "a person who owns or manages a small shop", example: "The shopkeeper knows all his regular customers by name.", zh: "店主" },
    { front: "browse", pos: "v.", def: "to look at things in a shop without planning to buy", example: "I spent an hour browsing in the bookshop.", zh: "隨意瀏覽" },
    { front: "wrap", pos: "v.", def: "to cover something in paper or material", example: "Could you wrap the vase carefully, please?", zh: "包裝" },
    { front: "queue-jump", pos: "v.", def: "to go in front of people who were waiting before you", example: "Everyone was annoyed when he tried to queue-jump.", zh: "插隊" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
