/* PET Prep extra bank: vocab wave 4 */
(function () {
  var BANK = [
    /* ---------- Health & the body ---------- */
    { front: "ache", pos: "n.", def: "a continuous pain that is not sharp", example: "I've had a dull ache in my back all day.", zh: "疼痛" },
    { front: "ankle", pos: "n.", def: "the joint between your foot and your leg", example: "She twisted her ankle playing volleyball.", zh: "腳踝" },
    { front: "appointment", pos: "n.", def: "an arranged time to see a doctor, dentist or other professional", example: "I've made an appointment with the doctor for Tuesday.", zh: "預約" },
    { front: "bandage", pos: "n.", def: "a long piece of cloth tied around an injury", example: "The nurse put a bandage on his cut knee.", zh: "繃帶" },
    { front: "bleed", pos: "v.", def: "to lose blood", example: "His nose started to bleed during the match.", zh: "流血" },
    { front: "blood", pos: "n.", def: "the red liquid inside your body", example: "The doctor took some blood for a test.", zh: "血液" },
    { front: "bone", pos: "n.", def: "one of the hard parts inside your body", example: "Luckily, the X-ray showed no broken bones.", zh: "骨頭" },
    { front: "brain", pos: "n.", def: "the organ inside your head that controls your body and thoughts", example: "Reading is good exercise for the brain.", zh: "大腦" },
    { front: "breath", pos: "n.", def: "the air that goes in and out of your body", example: "Take a deep breath and relax.", zh: "呼吸、氣息" },
    { front: "breathe", pos: "v.", def: "to take air into your body and let it out", example: "It was hard to breathe at the top of the mountain.", zh: "呼吸" },
    { front: "chemist's", pos: "n.", def: "a shop where you can buy medicine", example: "Pick up some plasters from the chemist's.", zh: "藥妝店、藥局" },
    { front: "chest", pos: "n.", def: "the front part of your body between your neck and stomach", example: "He went to the doctor with chest pains.", zh: "胸部" },
    { front: "chin", pos: "n.", def: "the part of your face below your mouth", example: "The footballer had a small cut on his chin.", zh: "下巴" },
    { front: "cough", pos: "n.", def: "the act of sending air out of your throat with a sudden sound", example: "She's had a bad cough for a week.", zh: "咳嗽" },
    { front: "cure", pos: "n.", def: "something that makes an illness go away", example: "There's still no cure for the common cold.", zh: "治療法" },
    { front: "dizzy", pos: "adj.", def: "feeling as if everything is turning around", example: "The heat made him feel dizzy.", zh: "頭暈的" },
    { front: "elbow", pos: "n.", def: "the joint in the middle of your arm", example: "He hurt his elbow when he fell off the bike.", zh: "手肘" },
    { front: "emergency", pos: "n.", def: "a serious situation that needs quick action", example: "In an emergency, call this number immediately.", zh: "緊急情況" },
    { front: "faint", pos: "v.", def: "to suddenly become unconscious for a short time", example: "She fainted because she hadn't eaten all day.", zh: "昏倒" },
    { front: "fever", pos: "n.", def: "a body temperature that is higher than normal", example: "He stayed in bed with a high fever.", zh: "發燒" },
    { front: "first aid", pos: "n.", def: "simple medical help given quickly after an accident", example: "All the coaches have done a first aid course.", zh: "急救" },
    { front: "flu", pos: "n.", def: "an illness like a bad cold with fever and aching", example: "Half the class is off school with flu.", zh: "流感" },
    { front: "forehead", pos: "n.", def: "the part of your face above your eyes", example: "Mum touched my forehead to see if I was hot.", zh: "額頭" },
    { front: "germ", pos: "n.", def: "a very small living thing that can make you ill", example: "Cover your mouth when you sneeze to stop germs spreading.", zh: "細菌、病菌" },
    { front: "headache", pos: "n.", def: "a pain in your head", example: "Loud music always gives me a headache.", zh: "頭痛" },
    { front: "heart", pos: "n.", def: "the organ that pumps blood around your body", example: "Running is good for your heart.", zh: "心臟" },
    { front: "heel", pos: "n.", def: "the back part of your foot", example: "These new shoes have rubbed my heel.", zh: "腳跟" },
    { front: "hurt", pos: "v.", def: "to feel pain, or to cause pain", example: "My legs hurt after the long climb.", zh: "疼痛、傷害" },
    { front: "illness", pos: "n.", def: "a disease of the body or mind", example: "He missed a month of school because of illness.", zh: "疾病" },
    { front: "injection", pos: "n.", def: "medicine put into your body with a needle", example: "The nurse gave me an injection in my arm.", zh: "注射" },
    { front: "injury", pos: "n.", def: "damage to a person's body", example: "The player is out of the team with a knee injury.", zh: "受傷" },
    { front: "knee", pos: "n.", def: "the joint in the middle of your leg", example: "She fell and cut her knee on the path.", zh: "膝蓋" },
    { front: "medicine", pos: "n.", def: "something you take to treat an illness", example: "Take this medicine three times a day after meals.", zh: "藥" },
    { front: "muscle", pos: "n.", def: "one of the parts inside your body that make you move", example: "Warm up properly so you don't pull a muscle.", zh: "肌肉" },
    { front: "operation", pos: "n.", def: "the process of cutting into someone's body to repair it", example: "Grandad needs an operation on his hip.", zh: "手術" },
    { front: "pain", pos: "n.", def: "the feeling you have when part of your body hurts", example: "She felt a sharp pain in her shoulder.", zh: "疼痛" },
    { front: "painful", pos: "adj.", def: "causing pain", example: "The injection was quick but painful.", zh: "疼痛的" },
    { front: "patient (person)", pos: "n.", def: "a person receiving medical treatment", example: "The hospital treats hundreds of patients every day.", zh: "病人" },
    { front: "pill", pos: "n.", def: "a small round piece of medicine that you swallow", example: "He takes a pill for his blood pressure every morning.", zh: "藥丸" },
    { front: "plaster", pos: "n.", def: "a small sticky cover for a cut on your skin", example: "She put a plaster on her blister.", zh: "OK繃" },
    { front: "prescription", pos: "n.", def: "a doctor's written order for medicine", example: "Take this prescription to the pharmacy.", zh: "處方箋" },
    { front: "recover", pos: "v.", def: "to become well again after an illness or injury", example: "It took him six weeks to recover from the operation.", zh: "康復" },
    { front: "sneeze", pos: "v.", def: "to suddenly blow air out of your nose and mouth", example: "The dust made everyone sneeze.", zh: "打噴嚏" },
    { front: "sore throat", pos: "n.", def: "a painful feeling in your throat", example: "I've got a sore throat and can hardly speak.", zh: "喉嚨痛" },
    { front: "stomach ache", pos: "n.", def: "a pain in your stomach", example: "Too much ice cream gave him a stomach ache.", zh: "胃痛、肚子痛" },
    { front: "surgery", pos: "n.", def: "the place where a doctor sees patients, or medical operations", example: "The doctor's surgery opens at eight thirty.", zh: "診所；手術" },
    { front: "swollen", pos: "adj.", def: "larger than usual because of injury or illness", example: "Her ankle was swollen after the fall.", zh: "腫脹的" },
    { front: "tablet", pos: "n.", def: "a small hard piece of medicine that you swallow", example: "Take two tablets with water every four hours.", zh: "藥錠" },
    { front: "temperature (fever)", pos: "n.", def: "a higher body heat than normal, showing illness", example: "The baby has a temperature, so we called the doctor.", zh: "發燒" },
    { front: "thumb", pos: "n.", def: "the short thick finger at the side of your hand", example: "He hit his thumb with the hammer.", zh: "拇指" },
    { front: "toe", pos: "n.", def: "one of the five parts at the end of your foot", example: "The water was so cold it froze my toes.", zh: "腳趾" },
    { front: "tongue", pos: "n.", def: "the soft part inside your mouth that you taste with", example: "The hot soup burned my tongue.", zh: "舌頭" },
    { front: "waist", pos: "n.", def: "the middle part of your body above your hips", example: "The dancer wore a red belt around her waist.", zh: "腰部" },
    { front: "wound", pos: "n.", def: "an injury where your skin is cut", example: "The nurse cleaned the wound before covering it.", zh: "傷口" },
    { front: "wrist", pos: "n.", def: "the joint between your hand and your arm", example: "She wears a watch on her left wrist.", zh: "手腕" },
    { front: "X-ray", pos: "n.", def: "a photograph of the inside of your body", example: "The X-ray showed a small crack in the bone.", zh: "X光" },
    { front: "healthy", pos: "adj.", def: "well and not ill, or good for your body", example: "A healthy breakfast gives you energy for the day.", zh: "健康的" },
    { front: "unhealthy", pos: "adj.", def: "not good for your body, or not well", example: "Eating crisps every day is an unhealthy habit.", zh: "不健康的" },
    { front: "fit", pos: "adj.", def: "healthy and strong because of exercise", example: "Swimming twice a week keeps her fit.", zh: "健壯的" },
    { front: "exhausted", pos: "adj.", def: "extremely tired", example: "After the marathon he was completely exhausted.", zh: "筋疲力盡的" },
    { front: "stress", pos: "n.", def: "worry caused by problems or too much work", example: "Exercise is a good way to deal with stress.", zh: "壓力" },
    { front: "relax", pos: "v.", def: "to rest and become calm", example: "I relax by listening to music in the evening.", zh: "放鬆" },
    { front: "checkup", pos: "n.", def: "a general medical examination to see if you are healthy", example: "I go to the dentist for a checkup twice a year.", zh: "健康檢查" },
    { front: "allergy", pos: "n.", def: "a medical condition in which something makes you ill", example: "She has an allergy to cats and starts sneezing near them.", zh: "過敏" },
    { front: "vitamin", pos: "n.", def: "a natural substance in food that keeps you healthy", example: "Oranges are full of vitamin C.", zh: "維他命" },
    /* ---------- Sport ---------- */
    { front: "athlete", pos: "n.", def: "a person who is good at sport, especially running and jumping", example: "The athletes trained twice a day before the games.", zh: "運動員" },
    { front: "athletics", pos: "n.", def: "sports such as running, jumping and throwing", example: "She competes in athletics at national level.", zh: "田徑" },
    { front: "beat", pos: "v.", def: "to win against someone in a game", example: "Our team beat the champions two-nil.", zh: "擊敗" },
    { front: "champion", pos: "n.", def: "the winner of a competition", example: "At sixteen she became the national chess champion.", zh: "冠軍" },
    { front: "championship", pos: "n.", def: "a competition to find the best team or player", example: "The world championship takes place next summer.", zh: "錦標賽" },
    { front: "coach (trainer)", pos: "n.", def: "a person who trains a sports team or player", example: "The coach made us practise the same move fifty times.", zh: "教練" },
    { front: "compete", pos: "v.", def: "to take part in a race or competition", example: "Runners from forty countries will compete in the race.", zh: "競賽" },
    { front: "competition", pos: "n.", def: "an event in which people try to win", example: "She entered a photography competition and won.", zh: "比賽" },
    { front: "competitor", pos: "n.", def: "a person who takes part in a competition", example: "Each competitor gets three attempts.", zh: "參賽者" },
    { front: "court", pos: "n.", def: "an area for playing sports such as tennis or basketball", example: "The hotel has two tennis courts.", zh: "球場" },
    { front: "defeat", pos: "v.", def: "to win against someone", example: "They defeated the home team in the final minute.", zh: "打敗" },
    { front: "draw", pos: "n.", def: "a result in which both teams have the same score", example: "The match ended in a two-all draw.", zh: "平局" },
    { front: "goal", pos: "n.", def: "a point scored in football, or the place the ball must go", example: "He scored the winning goal in extra time.", zh: "進球、球門" },
    { front: "gym", pos: "n.", def: "a place with equipment for doing exercise", example: "She goes to the gym before work three times a week.", zh: "健身房" },
    { front: "gymnastics", pos: "n.", def: "a sport with exercises that show strength and control of the body", example: "The girls have gymnastics practice on Wednesdays.", zh: "體操" },
    { front: "kick", pos: "v.", def: "to hit something with your foot", example: "He kicked the ball over the fence by mistake.", zh: "踢" },
    { front: "match (game)", pos: "n.", def: "a sports game between two teams or players", example: "Are you watching the match tonight?", zh: "比賽" },
    { front: "net", pos: "n.", def: "the material with holes used in sports like tennis and football", example: "The ball hit the top of the net.", zh: "球網" },
    { front: "opponent", pos: "n.", def: "the person or team you play against", example: "Her opponent in the final is the world number one.", zh: "對手" },
    { front: "pitch", pos: "n.", def: "an area of ground for playing team sports", example: "The players ran onto the pitch to loud cheers.", zh: "球場（足球等）" },
    { front: "prize", pos: "n.", def: "something given to the winner of a competition", example: "First prize is a weekend for two in Paris.", zh: "獎品" },
    { front: "race", pos: "n.", def: "a competition to see who is fastest", example: "Thousands took part in the city's annual race.", zh: "賽跑、競速" },
    { front: "referee", pos: "n.", def: "the person who makes sure players follow the rules", example: "The referee showed the defender a yellow card.", zh: "裁判" },
    { front: "score", pos: "v.", def: "to win a point or goal in a game", example: "She scored twice in the second half.", zh: "得分" },
    { front: "team", pos: "n.", def: "a group of people who play a sport together", example: "He plays for the school basketball team.", zh: "隊伍" },
    { front: "tournament", pos: "n.", def: "a competition with many games between many players", example: "The tennis tournament lasts two weeks.", zh: "錦標賽、巡迴賽" },
    { front: "train (exercise)", pos: "v.", def: "to practise a sport regularly to get better", example: "The team trains every evening after school.", zh: "訓練" },
    { front: "whistle", pos: "n.", def: "a small object that makes a high sound when you blow it", example: "The referee blew his whistle for half-time.", zh: "哨子" },
    { front: "warm up", pos: "phr. v.", def: "to do gentle exercises to prepare your body for sport", example: "Always warm up before you go running.", zh: "熱身" },
    { front: "join in", pos: "phr. v.", def: "to take part in an activity with others", example: "Everyone joined in the game, even the teachers.", zh: "加入、一起參加" },
    { front: "knock out", pos: "phr. v.", def: "to defeat a player or team so they leave a competition", example: "Our team was knocked out in the semi-final.", zh: "淘汰" },
    { front: "give up (sport)", pos: "phr. v.", def: "to stop doing an activity you used to do", example: "He gave up rugby after injuring his shoulder.", zh: "放棄" },
    { front: "take up", pos: "phr. v.", def: "to start doing a new activity or hobby", example: "She took up climbing when she was forty.", zh: "開始從事" },
    /* ---------- Sports & activities ---------- */
    { front: "badminton", pos: "n.", def: "a sport in which players hit a small object with feathers over a net", example: "We play badminton in the sports hall on Fridays.", zh: "羽毛球" },
    { front: "bowling", pos: "n.", def: "a game in which you roll a ball to knock down pins", example: "It's her birthday, so we're going bowling.", zh: "保齡球" },
    { front: "boxing", pos: "n.", def: "a sport in which two people fight with their fists", example: "Boxing requires speed as well as strength.", zh: "拳擊" },
    { front: "cricket", pos: "n.", def: "a game played with a bat and ball by two teams of eleven", example: "Cricket matches can last a whole day or longer.", zh: "板球" },
    { front: "diving", pos: "n.", def: "the sport of jumping into water or swimming underwater", example: "The diving competition takes place at the new pool.", zh: "跳水、潛水" },
    { front: "hockey", pos: "n.", def: "a team game played with curved sticks and a small ball", example: "She's the captain of the school hockey team.", zh: "曲棍球" },
    { front: "jogging", pos: "n.", def: "running slowly for exercise", example: "He goes jogging in the park before breakfast.", zh: "慢跑" },
    { front: "martial arts", pos: "n.", def: "fighting sports such as judo and karate", example: "Martial arts teach discipline as well as self-defence.", zh: "武術" },
    { front: "rock climbing", pos: "n.", def: "the sport of climbing steep rocks", example: "You need special shoes and ropes for rock climbing.", zh: "攀岩" },
    { front: "rugby", pos: "n.", def: "a team game in which players carry, kick and pass an oval ball", example: "Rugby players have to be strong and fast.", zh: "橄欖球" },
    { front: "skateboarding", pos: "n.", def: "the sport of riding on a board with small wheels", example: "The park has a special area for skateboarding.", zh: "滑板" },
    { front: "skiing", pos: "n.", def: "the sport of moving over snow on long narrow boards", example: "We're going skiing in the Alps in February.", zh: "滑雪" },
    { front: "snowboarding", pos: "n.", def: "the sport of moving over snow standing on one wide board", example: "Snowboarding looks easier than it is.", zh: "單板滑雪" },
    { front: "squash", pos: "n.", def: "a game in which two players hit a small ball against a wall", example: "He plays squash with a colleague every Thursday.", zh: "壁球" },
    { front: "volleyball", pos: "n.", def: "a game in which two teams hit a ball over a high net with their hands", example: "We played volleyball on the beach all afternoon.", zh: "排球" },
    { front: "yoga", pos: "n.", def: "exercises for the body and mind that involve stretching and breathing", example: "Yoga has really improved my flexibility.", zh: "瑜伽" },
    { front: "captain", pos: "n.", def: "the leader of a sports team", example: "The captain encouraged her team at half-time.", zh: "隊長" },
    { front: "supporter", pos: "n.", def: "a person who wants a particular team to win", example: "Thousands of supporters travelled to the away game.", zh: "支持者、球迷" },
    { front: "spectator", pos: "n.", def: "a person who watches a sports event", example: "The stadium was full of excited spectators.", zh: "觀眾" },
    { front: "changing room", pos: "n.", def: "a room where you change clothes for sport or swimming", example: "The team talked tactics in the changing room.", zh: "更衣室" },
    { front: "racket", pos: "n.", def: "the object with strings that you use to hit a ball in tennis", example: "She got a new tennis racket for her birthday.", zh: "球拍" },
    { front: "medal", pos: "n.", def: "a metal disc given as a prize in a competition", example: "He won a gold medal in the swimming relay.", zh: "獎牌" },
    { front: "record", pos: "n.", def: "the best result ever achieved in a sport", example: "She broke the national record for the 100 metres.", zh: "紀錄" },
    { front: "energetic", pos: "adj.", def: "full of energy and activity", example: "My little brother is too energetic to sit still.", zh: "精力充沛的" },
    { front: "strength", pos: "n.", def: "the quality of being physically strong", example: "Rowing builds strength in your arms and back.", zh: "力量" },
    /* ---------- Weather ---------- */
    { front: "breeze", pos: "n.", def: "a light gentle wind", example: "A cool breeze came in from the sea.", zh: "微風" },
    { front: "chilly", pos: "adj.", def: "slightly cold in an uncomfortable way", example: "Take a jumper; the evenings get chilly here.", zh: "寒冷的" },
    { front: "cloudy", pos: "adj.", def: "with many clouds in the sky", example: "It was too cloudy to see the stars.", zh: "多雲的" },
    { front: "damp", pos: "adj.", def: "slightly wet", example: "The grass was still damp from last night's rain.", zh: "潮濕的" },
    { front: "drought", pos: "n.", def: "a long period without rain", example: "The drought lasted all summer and ruined the crops.", zh: "乾旱" },
    { front: "flood", pos: "n.", def: "a large amount of water covering dry land", example: "Heavy rain caused floods in the town centre.", zh: "洪水" },
    { front: "fog", pos: "n.", def: "thick cloud near the ground that is hard to see through", example: "The airport closed because of thick fog.", zh: "霧" },
    { front: "forecast", pos: "n.", def: "a statement about what the weather will be like", example: "The forecast says sunshine all weekend.", zh: "天氣預報" },
    { front: "freezing", pos: "adj.", def: "extremely cold", example: "Close the window; it's freezing in here!", zh: "極冷的" },
    { front: "frost", pos: "n.", def: "a thin white layer of ice on surfaces when it is very cold", example: "The cars were covered in frost this morning.", zh: "霜" },
    { front: "gale", pos: "n.", def: "a very strong wind", example: "The ferry was cancelled because of the gale.", zh: "強風" },
    { front: "hail", pos: "n.", def: "small balls of ice that fall like rain", example: "Hail the size of peas hit the windows.", zh: "冰雹" },
    { front: "heatwave", pos: "n.", def: "a period of unusually hot weather", example: "During the heatwave we slept with all the windows open.", zh: "熱浪" },
    { front: "humid", pos: "adj.", def: "hot and slightly wet, used about air", example: "Summers here are humid and uncomfortable.", zh: "潮濕悶熱的" },
    { front: "lightning", pos: "n.", def: "the bright flashes of light in the sky during a storm", example: "Lightning lit up the whole sky.", zh: "閃電" },
    { front: "mist", pos: "n.", def: "light fog", example: "Morning mist hung over the fields.", zh: "薄霧" },
    { front: "shower", pos: "n.", def: "a short period of rain", example: "There will be showers in the afternoon.", zh: "陣雨" },
    { front: "snowstorm", pos: "n.", def: "heavy snow with strong winds", example: "The snowstorm closed all the mountain roads.", zh: "暴風雪" },
    { front: "sunny", pos: "adj.", def: "with bright light from the sun", example: "It was a perfect sunny day for the beach.", zh: "晴朗的" },
    { front: "thunder", pos: "n.", def: "the loud noise in the sky during a storm", example: "The dog hides under the bed when he hears thunder.", zh: "雷" },
    { front: "thunderstorm", pos: "n.", def: "a storm with thunder and lightning", example: "A thunderstorm broke just as we reached the car.", zh: "雷雨" },
    { front: "windy", pos: "adj.", def: "with a lot of wind", example: "It's too windy to use an umbrella today.", zh: "多風的" },
    { front: "icy", pos: "adj.", def: "covered in ice, or extremely cold", example: "Be careful on the icy pavement.", zh: "結冰的" },
    { front: "boiling", pos: "adj.", def: "extremely hot", example: "It's boiling in this classroom; can we open a window?", zh: "酷熱的" },
    /* ---------- Nature & environment ---------- */
    { front: "branch", pos: "n.", def: "a part of a tree that grows out from the trunk", example: "A bird built its nest on the highest branch.", zh: "樹枝" },
    { front: "bush", pos: "n.", def: "a plant like a small low tree", example: "A hedgehog was hiding under the bush.", zh: "灌木" },
    { front: "environment", pos: "n.", def: "the natural world of land, sea, air and living things", example: "Plastic waste is a serious danger to the environment.", zh: "環境" },
    { front: "forest", pos: "n.", def: "a large area covered with trees", example: "Wolves still live in the forests of eastern Europe.", zh: "森林" },
    { front: "grass", pos: "n.", def: "the common green plant that covers fields and gardens", example: "We lay on the grass and watched the clouds.", zh: "草" },
    { front: "leaf", pos: "n.", def: "one of the flat green parts of a plant or tree", example: "The leaves turn red and gold in autumn.", zh: "葉子" },
    { front: "moon", pos: "n.", def: "the round object that shines in the sky at night", example: "The full moon lit up the whole garden.", zh: "月亮" },
    { front: "planet", pos: "n.", def: "a large round object in space that moves around a star", example: "Mars is the planet closest to Earth.", zh: "行星" },
    { front: "pollution", pos: "n.", def: "damage to air, water or land from harmful substances", example: "Air pollution is worst in the city centre.", zh: "污染" },
    { front: "recycle", pos: "v.", def: "to treat used things so they can be used again", example: "We recycle glass, paper and plastic at home.", zh: "回收" },
    { front: "recycling", pos: "n.", def: "the process of treating waste so it can be used again", example: "Put the bottles in the recycling, not the bin.", zh: "資源回收" },
    { front: "rainforest", pos: "n.", def: "a thick forest in hot wet parts of the world", example: "Thousands of species live in the Amazon rainforest.", zh: "雨林" },
    { front: "rubbish", pos: "n.", def: "things that you throw away", example: "The rubbish is collected every Tuesday morning.", zh: "垃圾" },
    { front: "soil", pos: "n.", def: "the earth that plants grow in", example: "The soil here is perfect for growing vegetables.", zh: "土壤" },
    { front: "star", pos: "n.", def: "a bright point of light in the night sky", example: "Far from the city you can see thousands of stars.", zh: "星星" },
    { front: "stone", pos: "n.", def: "a small piece of rock", example: "The children threw stones into the lake.", zh: "石頭" },
    { front: "trunk", pos: "n.", def: "the thick main stem of a tree", example: "The tree trunk was too wide for three people to reach around.", zh: "樹幹" },
    { front: "wildlife", pos: "n.", def: "animals and plants living in natural conditions", example: "The island is famous for its rare wildlife.", zh: "野生動植物" },
    { front: "climate change", pos: "n.", def: "changes in the world's weather patterns", example: "Climate change is making summers hotter and drier.", zh: "氣候變遷" },
    { front: "global warming", pos: "n.", def: "the slow rise in the Earth's temperature", example: "Global warming is melting the polar ice.", zh: "全球暖化" },
    { front: "renewable", pos: "adj.", def: "describing energy that never runs out, like wind or sun", example: "The country gets half its power from renewable energy.", zh: "可再生的" },
    { front: "solar", pos: "adj.", def: "using the power of the sun", example: "They put solar panels on the roof last year.", zh: "太陽能的" },
    { front: "earthquake", pos: "n.", def: "a sudden shaking of the ground", example: "The earthquake damaged several old buildings.", zh: "地震" },
    { front: "volcano", pos: "n.", def: "a mountain that can send out hot melted rock", example: "The volcano last erupted a hundred years ago.", zh: "火山" },
    { front: "glacier", pos: "n.", def: "a huge mass of ice that moves slowly", example: "The glacier has shrunk dramatically in fifty years.", zh: "冰河" },
    /* ---------- Animals ---------- */
    { front: "bee", pos: "n.", def: "a flying insect that makes honey", example: "Bees are essential for growing fruit and vegetables.", zh: "蜜蜂" },
    { front: "butterfly", pos: "n.", def: "an insect with large coloured wings", example: "A blue butterfly landed on the flower.", zh: "蝴蝶" },
    { front: "camel", pos: "n.", def: "a desert animal with one or two humps on its back", example: "We rode camels across the sand dunes.", zh: "駱駝" },
    { front: "creature", pos: "n.", def: "any living thing that is not a plant", example: "The rock pool was full of tiny sea creatures.", zh: "生物" },
    { front: "deer", pos: "n.", def: "a fast wild animal with long legs, the male having horns", example: "We saw a family of deer at the edge of the forest.", zh: "鹿" },
    { front: "dolphin", pos: "n.", def: "an intelligent sea animal that looks like a large fish", example: "Dolphins swam alongside our boat for miles.", zh: "海豚" },
    { front: "donkey", pos: "n.", def: "an animal like a small horse with long ears", example: "A donkey carried our bags up the steep path.", zh: "驢子" },
    { front: "eagle", pos: "n.", def: "a large bird that hunts small animals", example: "An eagle circled high above the valley.", zh: "老鷹" },
    { front: "feather", pos: "n.", def: "one of the light soft things that cover a bird's body", example: "The peacock dropped a beautiful blue feather.", zh: "羽毛" },
    { front: "fur", pos: "n.", def: "the soft hair that covers some animals", example: "The kitten's fur is incredibly soft.", zh: "毛皮" },
    { front: "goat", pos: "n.", def: "a farm animal with horns that climbs well", example: "Mountain goats can climb almost vertical rocks.", zh: "山羊" },
    { front: "insect", pos: "n.", def: "a small creature with six legs, such as an ant or fly", example: "Use this spray to keep insects away at night.", zh: "昆蟲" },
    { front: "mosquito", pos: "n.", def: "a small flying insect that bites people", example: "I was bitten by mosquitoes all night at the campsite.", zh: "蚊子" },
    { front: "owl", pos: "n.", def: "a bird with large eyes that hunts at night", example: "We heard an owl calling from the old oak tree.", zh: "貓頭鷹" },
    { front: "parrot", pos: "n.", def: "a brightly coloured bird that can copy human speech", example: "Their parrot says 'good morning' to visitors.", zh: "鸚鵡" },
    { front: "penguin", pos: "n.", def: "a black and white sea bird that cannot fly", example: "The penguins slid down the ice into the water.", zh: "企鵝" },
    { front: "pet", pos: "n.", def: "an animal you keep at home for pleasure", example: "Our neighbours have three pets: two cats and a hamster.", zh: "寵物" },
    { front: "pigeon", pos: "n.", def: "a grey bird common in towns and cities", example: "Pigeons gathered around the tourists eating sandwiches.", zh: "鴿子" },
    { front: "shark", pos: "n.", def: "a large fish with sharp teeth", example: "Most sharks are not dangerous to people.", zh: "鯊魚" },
    { front: "snake", pos: "n.", def: "a long thin animal with no legs", example: "A small green snake slid across the path.", zh: "蛇" },
    { front: "spider", pos: "n.", def: "a small creature with eight legs that makes webs", example: "There's a huge spider in the bath!", zh: "蜘蛛" },
    { front: "tortoise", pos: "n.", def: "a slow animal with a hard shell on its back", example: "Their tortoise is over fifty years old.", zh: "陸龜" },
    { front: "whale", pos: "n.", def: "the largest animal in the sea", example: "We watched whales from the cliff top.", zh: "鯨魚" },
    { front: "wing", pos: "n.", def: "the part of a bird, insect or plane used for flying", example: "The little bird had hurt its wing.", zh: "翅膀" },
    { front: "zoo", pos: "n.", def: "a place where wild animals are kept for people to see", example: "The zoo's new baby elephant attracts big crowds.", zh: "動物園" },
    /* ---------- Environment issues & actions ---------- */
    { front: "protect the environment", pos: "phrase", def: "to keep the natural world safe from damage", example: "Small daily choices help protect the environment.", zh: "保護環境" },
    { front: "save energy", pos: "phrase", def: "to use less electricity, gas or fuel", example: "Turning off lights is an easy way to save energy.", zh: "節約能源" },
    { front: "public transport", pos: "n.", def: "buses, trains and trams that everyone can use", example: "Using public transport reduces traffic and pollution.", zh: "大眾運輸" },
    { front: "reuse", pos: "v.", def: "to use something again instead of throwing it away", example: "We reuse glass jars for storing rice and pasta.", zh: "重複使用" },
    { front: "plastic bag", pos: "n.", def: "a bag made of thin plastic for carrying shopping", example: "Bring your own bag instead of buying a plastic bag.", zh: "塑膠袋" },
    { front: "bottle bank", pos: "n.", def: "a large container in the street for used glass bottles", example: "There's a bottle bank in the supermarket car park.", zh: "玻璃回收桶" },
    { front: "endangered", pos: "adj.", def: "in danger of no longer existing", example: "The giant panda was an endangered species for decades.", zh: "瀕臨絕種的" },
    { front: "extinct", pos: "adj.", def: "no longer existing, used about animals and plants", example: "Dinosaurs became extinct millions of years ago.", zh: "絕種的" },
    { front: "species", pos: "n.", def: "a group of animals or plants of the same type", example: "This forest is home to over a hundred bird species.", zh: "物種" },
    { front: "habitat", pos: "n.", def: "the natural home of an animal or plant", example: "Cutting down forests destroys animals' habitats.", zh: "棲息地" },
    { front: "nature reserve", pos: "n.", def: "an area of land where animals and plants are protected", example: "The nature reserve is closed during the nesting season.", zh: "自然保護區" },
    { front: "charity", pos: "n.", def: "an organisation that helps people, animals or the environment", example: "She runs marathons to raise money for charity.", zh: "慈善機構" },
    { front: "volunteer", pos: "n.", def: "a person who works without being paid", example: "Volunteers cleaned the beach on Saturday morning.", zh: "志工" },
    { front: "campaign", pos: "n.", def: "a series of planned activities to achieve a goal", example: "Students started a campaign against plastic straws.", zh: "活動、運動" },
    { front: "poison", pos: "n.", def: "a substance that can kill or harm living things", example: "Some wild mushrooms contain deadly poison.", zh: "毒物" },
    /* ---------- Daily routine & lifestyle ---------- */
    { front: "get up", pos: "phr. v.", def: "to leave your bed in the morning", example: "On school days I get up at half past six.", zh: "起床" },
    { front: "wake up", pos: "phr. v.", def: "to stop sleeping", example: "The birds wake me up at five in summer.", zh: "醒來" },
    { front: "lie down", pos: "phr. v.", def: "to put your body flat, especially to rest", example: "I felt dizzy, so I lay down for a while.", zh: "躺下" },
    { front: "sit down", pos: "phr. v.", def: "to move from standing to sitting", example: "Please sit down; the doctor will see you soon.", zh: "坐下" },
    { front: "stand up", pos: "phr. v.", def: "to move from sitting to standing", example: "Everyone stood up when the judge entered.", zh: "站起來" },
    { front: "stay up", pos: "phr. v.", def: "to not go to bed at the usual time", example: "We stayed up late watching the fireworks.", zh: "熬夜" },
    { front: "sleep in", pos: "phr. v.", def: "to sleep later than usual in the morning", example: "On Sundays I love sleeping in until ten.", zh: "睡懶覺" },
    { front: "go off", pos: "phr. v.", def: "to make a sudden loud noise, used about alarms", example: "My alarm went off at six, but I ignored it.", zh: "（鬧鐘）響起" },
    { front: "get dressed", pos: "phrase", def: "to put your clothes on", example: "Get dressed quickly; the taxi is waiting.", zh: "穿衣服" },
    { front: "brush your teeth", pos: "phrase", def: "to clean your teeth with a brush", example: "Brush your teeth for two minutes, twice a day.", zh: "刷牙" },
    { front: "have a shower", pos: "phrase", def: "to wash your whole body standing under running water", example: "I always have a shower after football practice.", zh: "淋浴" },
    { front: "go to bed", pos: "phrase", def: "to lie down in bed to sleep at night", example: "The children go to bed at nine on weekdays.", zh: "上床睡覺" },
    { front: "fall asleep", pos: "phrase", def: "to start sleeping", example: "He fell asleep in front of the television.", zh: "入睡" },
    { front: "have a rest", pos: "phrase", def: "to relax or sleep for a short time", example: "Let's have a rest before we climb the last part.", zh: "休息" },
    { front: "keep fit", pos: "phrase", def: "to stay healthy through exercise", example: "Cycling to work helps me keep fit.", zh: "保持健康" },
    { front: "go for a walk", pos: "phrase", def: "to walk somewhere for pleasure or exercise", example: "We went for a walk along the river after lunch.", zh: "去散步" },
    { front: "take exercise", pos: "phrase", def: "to do physical activity to stay healthy", example: "Doctors say adults should take exercise every day.", zh: "做運動" },
    { front: "lose weight", pos: "phrase", def: "to become less heavy", example: "He lost weight by walking everywhere.", zh: "減重" },
    { front: "put on weight", pos: "phrase", def: "to become heavier", example: "I put on weight during the winter holidays.", zh: "變胖" },
    { front: "catch a cold", pos: "phrase", def: "to become ill with a cold", example: "Wear a coat, or you'll catch a cold.", zh: "感冒" },
    /* ---------- Illness & recovery ---------- */
    { front: "get better", pos: "phrase", def: "to recover from an illness", example: "Drink plenty of water and you'll soon get better.", zh: "好轉、康復" },
    { front: "get worse", pos: "phrase", def: "to become more ill or more serious", example: "If the pain gets worse, come back immediately.", zh: "惡化" },
    { front: "look after yourself", pos: "phrase", def: "to take care of your own health", example: "You must look after yourself during exam season.", zh: "照顧自己" },
    { front: "come down with", pos: "phr. v.", def: "to start to suffer from an illness", example: "She came down with flu the day before the trip.", zh: "染上（病）" },
    { front: "get over", pos: "phr. v.", def: "to recover from an illness or bad experience", example: "It took weeks to get over the infection.", zh: "痊癒、克服" },
    { front: "pass out", pos: "phr. v.", def: "to become unconscious", example: "The runner passed out just after the finish line.", zh: "昏倒" },
    { front: "throw up", pos: "phr. v.", def: "to bring food up from your stomach through your mouth", example: "The boat trip made him throw up twice.", zh: "嘔吐" },
    { front: "ambulance service", pos: "n.", def: "the organisation that sends vehicles to help sick people", example: "The ambulance service answered the call in minutes.", zh: "救護服務" },
    { front: "casualty", pos: "n.", def: "the hospital department for accidents and emergencies", example: "They rushed him to casualty with a broken arm.", zh: "急診室" },
    { front: "ward", pos: "n.", def: "a large room in a hospital with beds for patients", example: "The children's ward is decorated with cartoon characters.", zh: "病房" },
    { front: "waiting list", pos: "n.", def: "a list of people waiting for something such as treatment", example: "There's a long waiting list for the operation.", zh: "等候名單" },
    { front: "symptom", pos: "n.", def: "a sign that you have an illness", example: "A high temperature is a common symptom of flu.", zh: "症狀" },
    { front: "treatment", pos: "n.", def: "medical care given to make someone better", example: "The new treatment has helped thousands of patients.", zh: "治療" },
    { front: "bruise", pos: "n.", def: "a dark mark on your skin caused by a knock", example: "He had a big purple bruise on his leg after the game.", zh: "瘀青" },
    { front: "blister", pos: "n.", def: "a painful bubble of skin caused by rubbing or burning", example: "New shoes always give me blisters.", zh: "水泡" },
    /* ---------- Nature description & farming ---------- */
    { front: "harvest", pos: "n.", def: "the time when crops are collected, or the crops themselves", example: "The apple harvest was excellent this year.", zh: "收成" },
    { front: "crop", pos: "n.", def: "a plant grown in large amounts for food", example: "Rice is the main crop in this region.", zh: "農作物" },
    { front: "seed", pos: "n.", def: "the small hard part of a plant from which a new plant grows", example: "We planted tomato seeds in little pots.", zh: "種子" },
    { front: "root", pos: "n.", def: "the part of a plant that grows underground", example: "The tree's roots had damaged the garden wall.", zh: "根" },
    { front: "blossom", pos: "n.", def: "the flowers on a tree in spring", example: "The cherry blossom attracts crowds every April.", zh: "花（樹上的）" },
    { front: "meadow", pos: "n.", def: "a field of grass and wild flowers", example: "Cows grazed peacefully in the meadow.", zh: "草地" },
    { front: "pond", pos: "n.", def: "a small area of still water", example: "Frogs live in the pond at the bottom of the garden.", zh: "池塘" },
    { front: "bank (river)", pos: "n.", def: "the land along the side of a river", example: "We had lunch on the grassy bank of the river.", zh: "河岸" },
    { front: "mud", pos: "n.", def: "soft wet earth", example: "The football pitch was covered in mud after the rain.", zh: "泥巴" },
    { front: "dirt", pos: "n.", def: "dust, soil or any substance that makes things not clean", example: "His boots were covered in dirt after the walk.", zh: "泥土、污垢" },
    { front: "shade", pos: "n.", def: "an area out of the sunlight", example: "We sat in the shade of a large tree.", zh: "陰涼處" },
    { front: "sunshine", pos: "n.", def: "the light and heat from the sun", example: "The cat loves lying in the morning sunshine.", zh: "陽光" },
    { front: "rainbow", pos: "n.", def: "the curve of colours in the sky after rain", example: "A double rainbow appeared over the valley.", zh: "彩虹" },
    { front: "sky", pos: "n.", def: "the space above the earth where you see clouds and stars", example: "The sky turned pink as the sun went down.", zh: "天空" },
    { front: "ocean", pos: "n.", def: "one of the very large seas of the world", example: "The Pacific is the largest ocean on Earth.", zh: "海洋" },
    /* ---------- Sports events & fitness ---------- */
    { front: "final", pos: "n.", def: "the last game in a competition, which decides the winner", example: "They reached the final for the first time in twenty years.", zh: "決賽" },
    { front: "semi-final", pos: "n.", def: "one of the two games before the final", example: "Both semi-finals will be played on Saturday.", zh: "準決賽" },
    { front: "victory", pos: "n.", def: "success in a game, competition or war", example: "The fans celebrated the victory all night.", zh: "勝利" },
    { front: "defeat (loss)", pos: "n.", def: "the fact of losing a game or competition", example: "It was their third defeat in a row.", zh: "失敗、敗北" },
    { front: "extra time", pos: "n.", def: "additional playing time when a match is a draw", example: "The winning goal came in the last minute of extra time.", zh: "延長賽" },
    { front: "half-time", pos: "n.", def: "the rest period in the middle of a match", example: "The score was one-all at half-time.", zh: "中場休息" },
    { front: "training", pos: "n.", def: "the process of practising to improve at a sport or job", example: "She never misses training, even in the rain.", zh: "訓練" },
    { front: "stretch", pos: "v.", def: "to make your arms, legs or body as long as possible", example: "Stretch carefully before and after running.", zh: "伸展" },
    { front: "bounce", pos: "v.", def: "to move up and away after hitting a surface", example: "The ball bounced twice before crossing the line.", zh: "彈跳" },
    { front: "throw", pos: "v.", def: "to send something through the air with your hand", example: "He threw the ball to the other end of the pitch.", zh: "投擲" },
    { front: "catch", pos: "v.", def: "to take hold of something moving through the air", example: "She caught the ball with one hand.", zh: "接住" },
    { front: "hit", pos: "v.", def: "to touch something with force", example: "He hit the ball over the net with a powerful serve.", zh: "打、擊" },
    { front: "jump", pos: "v.", def: "to push your body off the ground into the air", example: "The horse jumped the final fence easily.", zh: "跳" },
    { front: "chase", pos: "v.", def: "to run after someone or something to catch them", example: "The dog chased the ball across the park.", zh: "追逐" },
    { front: "dive (jump)", pos: "v.", def: "to jump head first, especially to reach a ball", example: "The goalkeeper dived to his left and saved the penalty.", zh: "撲、飛身" },
    /* ---------- Body & appearance ---------- */
    { front: "beard", pos: "n.", def: "hair on the lower part of a man's face", example: "My uncle has grown a long grey beard.", zh: "鬍子" },
    { front: "curly", pos: "adj.", def: "with many curves, used about hair", example: "She has dark curly hair like her mother.", zh: "捲的" },
    { front: "straight (hair)", pos: "adj.", def: "without curls or waves", example: "His straight hair falls over his eyes.", zh: "直的（頭髮）" },
    { front: "fringe", pos: "n.", def: "hair cut short over the forehead", example: "Her new fringe makes her look younger.", zh: "瀏海" },
    { front: "plait", pos: "n.", def: "hair twisted together in a long shape", example: "She wears her hair in two long plaits for school.", zh: "辮子" },
    { front: "ponytail", pos: "n.", def: "hair tied at the back of the head so it hangs down", example: "She pulled her hair into a ponytail before the race.", zh: "馬尾" },
    { front: "freckle", pos: "n.", def: "one of the small brown spots on someone's skin", example: "The sun brings out the freckles on her nose.", zh: "雀斑" },
    { front: "wrinkle", pos: "n.", def: "a small line in the skin caused by age", example: "His face is full of wrinkles from years in the sun.", zh: "皺紋" },
    { front: "slim", pos: "adj.", def: "attractively thin", example: "She stays slim by swimming every day.", zh: "苗條的" },
    { front: "skinny", pos: "adj.", def: "very thin, often too thin", example: "The stray cat was skinny and hungry.", zh: "皮包骨的" },
    { front: "well-built", pos: "adj.", def: "having a strong, muscular body", example: "The rugby player is tall and well-built.", zh: "體格健壯的" },
    { front: "middle-aged", pos: "adj.", def: "no longer young but not yet old", example: "A middle-aged couple moved in next door.", zh: "中年的" },
    { front: "elderly", pos: "adj.", def: "a polite word for old, used about people", example: "He helps his elderly neighbours with their shopping.", zh: "年長的" },
    { front: "good-looking", pos: "adj.", def: "attractive in appearance", example: "The actor is talented as well as good-looking.", zh: "好看的" },
    { front: "smart (appearance)", pos: "adj.", def: "clean, tidy and stylish in appearance", example: "You look very smart in that new jacket.", zh: "整潔體面的" },
    { front: "scruffy", pos: "adj.", def: "untidy and slightly dirty in appearance", example: "You can't wear those scruffy jeans to the interview.", zh: "邋遢的" },
    { front: "bald", pos: "adj.", def: "with little or no hair on the head", example: "My dad started going bald in his thirties.", zh: "禿頭的" },
    { front: "pale", pos: "adj.", def: "with light skin, often because of illness", example: "You look pale; are you feeling all right?", zh: "蒼白的" },
    { front: "tanned", pos: "adj.", def: "with skin made brown by the sun", example: "They came back from Greece looking tanned and relaxed.", zh: "曬黑的" },
    { front: "resemble", pos: "v.", def: "to look like someone or something", example: "She strongly resembles her grandmother at the same age.", zh: "相像" },
    /* ---------- Weather & nature phrases ---------- */
    { front: "pour with rain", pos: "phrase", def: "to rain very heavily", example: "It poured with rain during the whole match.", zh: "下傾盆大雨" },
    { front: "the sun comes out", pos: "phrase", def: "the sun appears from behind clouds", example: "The sun came out just in time for the picnic.", zh: "太陽出來" },
    { front: "clear up", pos: "phr. v.", def: "to become brighter, used about weather", example: "If it clears up later, we'll go to the beach.", zh: "放晴" },
    { front: "cool down", pos: "phr. v.", def: "to become less hot", example: "The evenings cool down quickly in the desert.", zh: "變涼" },
    { front: "die out", pos: "phr. v.", def: "to disappear completely, used about species or customs", example: "Many languages are dying out around the world.", zh: "滅絕、消失" },
    { front: "cut down", pos: "phr. v.", def: "to make a tree fall, or to do less of something", example: "They cut down the old oak to build the road.", zh: "砍伐；減少" },
    { front: "throw out", pos: "phr. v.", def: "to get rid of something you no longer want", example: "Don't throw out those jars; we can recycle them.", zh: "扔掉" },
    { front: "use up", pos: "phr. v.", def: "to finish all of something", example: "We've used up all the hot water again.", zh: "用光" },
    { front: "heat (energy)", pos: "n.", def: "the quality of being hot, or hot weather", example: "The heat in July makes it hard to sleep.", zh: "高溫、熱" },
    { front: "melt", pos: "v.", def: "to change from solid to liquid because of heat", example: "The snowman melted overnight.", zh: "融化" },
    { front: "shine", pos: "v.", def: "to give out bright light", example: "The sun shone all week during our holiday.", zh: "照耀" },
    { front: "blow", pos: "v.", def: "to move air, used about wind or your mouth", example: "The wind blew my hat into the river.", zh: "吹" },
    { front: "drop (fall)", pos: "v.", def: "to fall or become lower", example: "Temperatures dropped sharply after sunset.", zh: "下降" },
    { front: "rise", pos: "v.", def: "to go up or become higher", example: "The river rises every spring when the snow melts.", zh: "上升" },
    { front: "flow", pos: "v.", def: "to move continuously, used about liquid", example: "The stream flows down into the lake.", zh: "流動" },
    /* ---------- Feelings about health & activity ---------- */
    { front: "sweat", pos: "v.", def: "to lose liquid through your skin when hot", example: "Everyone was sweating by the end of the climb.", zh: "流汗" },
    { front: "shiver", pos: "v.", def: "to shake because you are cold or afraid", example: "We stood shivering at the bus stop in the snow.", zh: "發抖" },
    { front: "yawn", pos: "v.", def: "to open your mouth wide because you are tired or bored", example: "He kept yawning during the long lecture.", zh: "打呵欠" },
    { front: "sigh", pos: "v.", def: "to breathe out slowly to show tiredness or sadness", example: "She sighed and started the exercise again.", zh: "嘆氣" },
    { front: "energy", pos: "n.", def: "the power you need to be active", example: "A good breakfast gives you energy for the morning.", zh: "能量、精力" },
    { front: "thirst", pos: "n.", def: "the feeling of needing to drink", example: "Nothing beats cold water when you have a real thirst.", zh: "口渴" },
    { front: "hunger", pos: "n.", def: "the feeling of needing to eat", example: "By noon, hunger made it hard to concentrate.", zh: "飢餓" },
    { front: "in good shape", pos: "phrase", def: "healthy and physically fit", example: "For seventy, my grandfather is in very good shape.", zh: "健康狀況良好" },
    { front: "out of breath", pos: "phrase", def: "breathing fast because of effort", example: "I was out of breath after just two flights of stairs.", zh: "上氣不接下氣" },
    { front: "under the weather", pos: "idiom", def: "feeling slightly ill", example: "I'm a bit under the weather, so I'll stay home tonight.", zh: "身體不舒服" },
    /* ---------- Extra sport & outdoors ---------- */
    { front: "surfboard", pos: "n.", def: "the long board used for riding waves", example: "He carried his surfboard down to the water.", zh: "衝浪板" },
    { front: "goggles", pos: "n.", def: "special glasses that protect your eyes", example: "You need goggles to see underwater in the pool.", zh: "護目鏡、泳鏡" },
    { front: "track", pos: "n.", def: "a path or circuit used for running or racing", example: "The athletes did ten laps of the track.", zh: "跑道" },
    { front: "lap", pos: "n.", def: "one complete journey around a track", example: "She swam twenty laps of the pool before breakfast.", zh: "一圈" },
    { front: "rope", pos: "n.", def: "very thick strong string", example: "The climbers were connected by a safety rope.", zh: "繩索" },
    { front: "kite", pos: "n.", def: "a light frame with material that flies in the wind on a string", example: "The beach is perfect for flying kites.", zh: "風箏" },
    { front: "sledge", pos: "n.", def: "an object for sliding over snow", example: "The children pulled their sledge up the hill again and again.", zh: "雪橇" },
    { front: "ice rink", pos: "n.", def: "an area of ice for skating", example: "An outdoor ice rink opens in the square every December.", zh: "溜冰場" },
    { front: "skates", pos: "n.", def: "boots with blades or wheels for moving on ice or ground", example: "She got her first pair of skates at six.", zh: "溜冰鞋" },
    { front: "swimming costume", pos: "n.", def: "the clothing you wear for swimming", example: "Don't forget your swimming costume for the school trip.", zh: "泳裝" },
    { front: "beginner's luck", pos: "idiom", def: "surprising success the first time you try something", example: "He won his first ever game of chess: beginner's luck!", zh: "新手好運" },
    { front: "fair play", pos: "n.", def: "honest behaviour in sport or life", example: "The award celebrates fair play, not just winning.", zh: "公平競爭" },
    { front: "personal best", pos: "n.", def: "the best result a person has ever achieved", example: "She ran a personal best in the final.", zh: "個人最佳成績" },
    { front: "keep score", pos: "phrase", def: "to record the points during a game", example: "Who's keeping score in this match?", zh: "計分" },
    { front: "take the lead", pos: "phrase", def: "to move into first position in a race or game", example: "Our team took the lead just before half-time.", zh: "取得領先" },
    /* ---------- More animals & nature ---------- */
    { front: "ant", pos: "n.", def: "a very small insect that lives in large groups", example: "A line of ants marched across the picnic blanket.", zh: "螞蟻" },
    { front: "bat (animal)", pos: "n.", def: "a small flying animal that comes out at night", example: "Bats flew out of the cave at dusk.", zh: "蝙蝠" },
    { front: "bear", pos: "n.", def: "a large strong wild animal with thick fur", example: "Campers must keep food away from bears.", zh: "熊" },
    { front: "bull", pos: "n.", def: "a male cow", example: "Never cross a field with a bull in it.", zh: "公牛" },
    { front: "crab", pos: "n.", def: "a sea creature with a hard shell and large front claws", example: "The children caught tiny crabs in the rock pools.", zh: "螃蟹" },
    { front: "fox", pos: "n.", def: "a wild animal like a dog with red fur and a thick tail", example: "A fox visits our garden most nights.", zh: "狐狸" },
    { front: "frog", pos: "n.", def: "a small green animal that lives near water and jumps", example: "We could hear frogs croaking by the pond.", zh: "青蛙" },
    { front: "hedgehog", pos: "n.", def: "a small animal covered in sharp spines", example: "A hedgehog was asleep under the pile of leaves.", zh: "刺蝟" },
    { front: "lamb (animal)", pos: "n.", def: "a young sheep", example: "The lambs were born early this spring.", zh: "小羊" },
    { front: "seal", pos: "n.", def: "a sea animal with smooth fur that eats fish", example: "Seals lay on the rocks in the morning sun.", zh: "海豹" },
    { front: "squirrel", pos: "n.", def: "a small animal with a big tail that climbs trees", example: "A squirrel buried nuts all over the lawn.", zh: "松鼠" },
    { front: "swan", pos: "n.", def: "a large white bird with a long neck that lives on water", example: "Two swans glided across the lake.", zh: "天鵝" },
    { front: "wasp", pos: "n.", def: "a black and yellow flying insect that can sting", example: "A wasp kept landing on our sandwiches.", zh: "黃蜂" },
    { front: "worm", pos: "n.", def: "a long thin creature with no legs that lives in soil", example: "Birds pull worms out of the wet grass.", zh: "蟲、蚯蚓" },
    { front: "cage", pos: "n.", def: "a box made of bars for keeping birds or animals", example: "The parrot's cage door was left open.", zh: "籠子" },
    { front: "nest", pos: "n.", def: "the home a bird builds for its eggs", example: "There's a robin's nest in the hedge.", zh: "鳥巢" },
    { front: "paw", pos: "n.", def: "the foot of an animal such as a dog or cat", example: "The dog lifted its muddy paw to shake hands.", zh: "腳掌" },
    { front: "tail", pos: "n.", def: "the part at the back end of an animal's body", example: "The puppy wags its tail whenever we come home.", zh: "尾巴" },
    { front: "bark", pos: "v.", def: "to make the loud short sound a dog makes", example: "The dog barks at everyone who passes the gate.", zh: "吠叫" },
    { front: "bite", pos: "v.", def: "to cut something with your teeth", example: "Careful, that horse sometimes bites.", zh: "咬" },
    { front: "sting", pos: "v.", def: "to hurt with a small sharp point, used about insects", example: "A bee stung me on the foot at the beach.", zh: "螫、叮" },
    { front: "feed", pos: "v.", def: "to give food to a person or animal", example: "Please don't feed the animals at the zoo.", zh: "餵食" },
    { front: "hunt", pos: "v.", def: "to chase animals to catch or kill them", example: "Owls hunt small animals at night.", zh: "獵捕" },
    { front: "breed", pos: "v.", def: "to have babies, used about animals", example: "These birds breed on the cliffs every summer.", zh: "繁殖" },
    { front: "tame", pos: "adj.", def: "not wild; not afraid of people", example: "The deer in the park are surprisingly tame.", zh: "溫馴的" },
    { front: "fierce", pos: "adj.", def: "angry and likely to attack", example: "The farm dog looks fierce but is actually gentle.", zh: "兇猛的" },
    { front: "poisonous", pos: "adj.", def: "containing poison", example: "Some brightly coloured frogs are extremely poisonous.", zh: "有毒的" },
    { front: "wild", pos: "adj.", def: "living in nature, not kept by people", example: "Wild horses still live on these hills.", zh: "野生的" },
    { front: "male", pos: "adj.", def: "belonging to the sex that cannot have babies", example: "The male birds have brighter feathers than the females.", zh: "雄性的" },
    { front: "female", pos: "adj.", def: "belonging to the sex that can have babies", example: "The female lion does most of the hunting.", zh: "雌性的" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
