/* PET Prep extra bank: vocab wave 2 */
(function () {
  var BANK = [
    /* ---------- Travel & holidays ---------- */
    { front: "abroad", pos: "adv.", def: "in or to a foreign country", example: "She has never travelled abroad before.", zh: "在國外、到國外" },
    { front: "accommodation", pos: "n.", def: "a place to stay, such as a hotel or flat", example: "The price includes flights and accommodation.", zh: "住宿" },
    { front: "adventure", pos: "n.", def: "an exciting and sometimes dangerous experience", example: "Their trip across the desert was a real adventure.", zh: "冒險" },
    { front: "backpack", pos: "n.", def: "a large bag that you carry on your back", example: "He packed his backpack the night before the hike.", zh: "背包" },
    { front: "baggage", pos: "n.", def: "the bags and suitcases you take when travelling", example: "You can leave your baggage at the hotel reception.", zh: "行李" },
    { front: "boarding pass", pos: "n.", def: "a card that allows you to get on a plane", example: "Please show your boarding pass at the gate.", zh: "登機證" },
    { front: "book", pos: "v.", def: "to arrange to have a ticket, room or table in advance", example: "We booked our flights three months early.", zh: "預訂" },
    { front: "brochure", pos: "n.", def: "a small magazine with pictures and information about a product or place", example: "I picked up a brochure about boat trips on the lake.", zh: "小冊子" },
    { front: "campsite", pos: "n.", def: "a place where people can stay in tents", example: "The campsite is right next to a beautiful river.", zh: "露營地" },
    { front: "cancel", pos: "v.", def: "to decide that a planned event will not happen", example: "They cancelled the ferry because of the storm.", zh: "取消" },
    { front: "crossing", pos: "n.", def: "a journey across water, or a place to cross a road", example: "The sea crossing took about ninety minutes.", zh: "橫渡；穿越處" },
    { front: "currency", pos: "n.", def: "the money used in a particular country", example: "What currency do they use in Switzerland?", zh: "貨幣" },
    { front: "delay", pos: "n.", def: "a situation when something happens later than planned", example: "There was a two-hour delay because of fog.", zh: "延誤" },
    { front: "departure", pos: "n.", def: "the act of leaving a place, especially on a journey", example: "Check the departure time on your ticket.", zh: "出發、離境" },
    { front: "destination", pos: "n.", def: "the place you are travelling to", example: "After ten hours on the train, we finally reached our destination.", zh: "目的地" },
    { front: "excursion", pos: "n.", def: "a short journey made for pleasure, usually in a group", example: "The hotel organises excursions to the old town.", zh: "短途旅行" },
    { front: "ferry", pos: "n.", def: "a boat that carries people and cars across water regularly", example: "We took the ferry from the mainland to the island.", zh: "渡輪" },
    { front: "flight", pos: "n.", def: "a journey made by plane", example: "Our flight to Tokyo leaves at seven in the morning.", zh: "航班" },
    { front: "foreigner", pos: "n.", def: "a person from another country", example: "The city is full of foreigners during the festival.", zh: "外國人" },
    { front: "guidebook", pos: "n.", def: "a book with information for tourists", example: "According to the guidebook, the temple is a thousand years old.", zh: "旅遊指南" },
    { front: "hitchhike", pos: "v.", def: "to travel by asking drivers for free rides", example: "It can be risky to hitchhike alone at night.", zh: "搭便車" },
    { front: "immigration", pos: "n.", def: "the place at a border where officials check passports", example: "There was a long queue at immigration.", zh: "入境檢查；移民" },
    { front: "insurance", pos: "n.", def: "an agreement in which you pay money and a company pays if something bad happens", example: "Always buy travel insurance before a trip abroad.", zh: "保險" },
    { front: "itinerary", pos: "n.", def: "a plan of a journey, showing places and times", example: "The itinerary includes two days in Vienna.", zh: "行程表" },
    { front: "landscape", pos: "n.", def: "everything you can see when you look across an area of land", example: "The train passed through some beautiful mountain landscape.", zh: "風景、地貌" },
    { front: "luggage", pos: "n.", def: "the bags you take with you when you travel", example: "You're only allowed one piece of hand luggage.", zh: "行李" },
    { front: "nationality", pos: "n.", def: "the state of belonging to a particular country", example: "Please write your name and nationality on the form.", zh: "國籍" },
    { front: "passenger", pos: "n.", def: "a person travelling in a vehicle but not driving it", example: "The bus can carry fifty passengers.", zh: "乘客" },
    { front: "passport", pos: "n.", def: "an official document that shows who you are, used for travel", example: "Don't forget your passport, or you can't board the plane.", zh: "護照" },
    { front: "platform", pos: "n.", def: "the place in a station where you get on a train", example: "The train to York leaves from platform six.", zh: "月台" },
    { front: "reservation", pos: "n.", def: "an arrangement to keep a room, seat or table for you", example: "I'd like to make a reservation for two nights.", zh: "預訂" },
    { front: "resort", pos: "n.", def: "a place where many people go on holiday", example: "This ski resort is popular with families.", zh: "度假勝地" },
    { front: "route", pos: "n.", def: "the way you follow to get from one place to another", example: "We took the coastal route to enjoy the sea views.", zh: "路線" },
    { front: "sightseeing", pos: "n.", def: "the activity of visiting interesting places as a tourist", example: "We spent the first day sightseeing in the capital.", zh: "觀光" },
    { front: "souvenir", pos: "n.", def: "something you buy to remember a place you visited", example: "She bought a small model of the tower as a souvenir.", zh: "紀念品" },
    { front: "suitcase", pos: "n.", def: "a large case with a handle for carrying clothes when travelling", example: "My suitcase was too heavy, so I had to pay extra.", zh: "行李箱" },
    { front: "tour", pos: "n.", def: "a visit to a place during which you look around it", example: "We went on a guided tour of the palace.", zh: "遊覽、導覽" },
    { front: "tourism", pos: "n.", def: "the business of providing services for people on holiday", example: "The island depends on tourism for most of its income.", zh: "觀光業" },
    { front: "tourist", pos: "n.", def: "a person visiting a place for pleasure", example: "Thousands of tourists visit the castle every summer.", zh: "觀光客" },
    { front: "travel agency", pos: "n.", def: "a company that arranges holidays and journeys for people", example: "The travel agency found us a cheap package holiday.", zh: "旅行社" },
    { front: "trip", pos: "n.", def: "a journey to a place and back again", example: "Our class is going on a trip to the science museum.", zh: "旅行、行程" },
    { front: "view", pos: "n.", def: "what you can see from a particular place", example: "Our hotel room had a wonderful view of the bay.", zh: "景色" },
    { front: "visa", pos: "n.", def: "an official mark in your passport that allows you to enter a country", example: "You need a visa to work in that country.", zh: "簽證" },
    { front: "voyage", pos: "n.", def: "a long journey by sea or in space", example: "The voyage across the Atlantic took two weeks.", zh: "航行" },
    { front: "youth hostel", pos: "n.", def: "a cheap place to stay, especially for young travellers", example: "We stayed in a youth hostel to save money.", zh: "青年旅舍" },
    { front: "sunbathe", pos: "v.", def: "to sit or lie in the sun to make your skin brown", example: "She spent the afternoon sunbathing by the pool.", zh: "做日光浴" },
    { front: "explore", pos: "v.", def: "to travel around a place to learn about it", example: "We spent the morning exploring the old part of the city.", zh: "探索" },
    { front: "pack", pos: "v.", def: "to put things into a bag or case before a journey", example: "I haven't packed for the trip yet.", zh: "打包" },
    { front: "unpack", pos: "v.", def: "to take things out of a bag or case", example: "We unpacked quickly and went straight to the beach.", zh: "打開行李" },
    { front: "overseas", pos: "adv.", def: "in or to a country across the sea", example: "Many students go overseas to study English.", zh: "海外" },
    /* ---------- Transport ---------- */
    { front: "airline", pos: "n.", def: "a company that carries passengers by plane", example: "Which airline are you flying with to London?", zh: "航空公司" },
    { front: "airport", pos: "n.", def: "a place where planes take off and land", example: "We arrived at the airport two hours before the flight.", zh: "機場" },
    { front: "ambulance", pos: "n.", def: "a vehicle that takes sick or injured people to hospital", example: "An ambulance arrived within five minutes of the call.", zh: "救護車" },
    { front: "brake", pos: "n.", def: "the part of a vehicle that makes it slow down or stop", example: "He pressed the brake hard to avoid the cat.", zh: "煞車" },
    { front: "coach", pos: "n.", def: "a comfortable bus for long journeys", example: "The coach to Edinburgh takes about eight hours.", zh: "長途巴士" },
    { front: "crash", pos: "n.", def: "an accident in which a vehicle hits something", example: "Luckily, no one was hurt in the crash.", zh: "撞車事故" },
    { front: "cycle", pos: "v.", def: "to ride a bicycle", example: "I cycle to work when the weather is good.", zh: "騎腳踏車" },
    { front: "driving licence", pos: "n.", def: "an official document that allows you to drive", example: "You must carry your driving licence when you drive.", zh: "駕照" },
    { front: "engine", pos: "n.", def: "the part of a vehicle that makes it move", example: "The mechanic checked the engine carefully.", zh: "引擎" },
    { front: "fare", pos: "n.", def: "the money you pay for a journey by bus, train or taxi", example: "The bus fare into town is two pounds.", zh: "車資" },
    { front: "fuel", pos: "n.", def: "a substance such as petrol that is burned to make energy", example: "We stopped at a garage to buy some fuel.", zh: "燃料" },
    { front: "garage", pos: "n.", def: "a place where cars are repaired, or a building for keeping a car", example: "The car is at the garage for repairs.", zh: "修車廠、車庫" },
    { front: "handlebars", pos: "n.", def: "the bar at the front of a bicycle that you hold", example: "Keep both hands on the handlebars when you ride.", zh: "（腳踏車）把手" },
    { front: "helicopter", pos: "n.", def: "an aircraft with blades on top that can fly straight up", example: "A helicopter took the injured climber to hospital.", zh: "直升機" },
    { front: "helmet", pos: "n.", def: "a hard hat that protects your head", example: "Always wear a helmet when you ride a motorbike.", zh: "安全帽" },
    { front: "lorry", pos: "n.", def: "a large vehicle for carrying goods by road", example: "A lorry delivered the new furniture this morning.", zh: "卡車" },
    { front: "motorway", pos: "n.", def: "a wide road for fast traffic between cities", example: "Take the motorway if you want to get there quickly.", zh: "高速公路" },
    { front: "overtake", pos: "v.", def: "to pass a vehicle that is moving more slowly", example: "It's dangerous to overtake on a bend.", zh: "超車" },
    { front: "parking space", pos: "n.", def: "an area where you can leave a car", example: "It took ages to find a parking space near the market.", zh: "停車位" },
    { front: "pavement", pos: "n.", def: "the path beside a road where people walk", example: "Cyclists shouldn't ride on the pavement.", zh: "人行道" },
    { front: "pedestrian", pos: "n.", def: "a person walking in the street", example: "This street is closed to cars; only pedestrians can use it.", zh: "行人" },
    { front: "petrol", pos: "n.", def: "the liquid fuel used in most cars", example: "The price of petrol has gone up again.", zh: "汽油" },
    { front: "puncture", pos: "n.", def: "a small hole in a tyre that lets the air out", example: "I got a puncture on my way home and had to push my bike.", zh: "爆胎、輪胎破洞" },
    { front: "roundabout", pos: "n.", def: "a circular area where roads meet, which traffic drives around", example: "Turn left at the next roundabout.", zh: "圓環" },
    { front: "seatbelt", pos: "n.", def: "a belt that holds you in your seat in a car or plane", example: "Please fasten your seatbelt before we take off.", zh: "安全帶" },
    { front: "cyclist", pos: "n.", def: "a person who rides a bicycle", example: "The new path is for cyclists and walkers only.", zh: "自行車騎士" },
    { front: "traffic", pos: "n.", def: "all the vehicles moving along a road", example: "The traffic is terrible in the city centre at five o'clock.", zh: "交通、車流" },
    { front: "traffic jam", pos: "n.", def: "a long line of vehicles that cannot move or moves slowly", example: "We were stuck in a traffic jam for an hour.", zh: "塞車" },
    { front: "traffic lights", pos: "n.", def: "lights that control traffic at road junctions", example: "Turn right at the traffic lights.", zh: "紅綠燈" },
    { front: "tram", pos: "n.", def: "an electric vehicle that runs on rails along city streets", example: "You can take a tram from the station to the old town.", zh: "路面電車" },
    { front: "tyre", pos: "n.", def: "the rubber ring around a wheel", example: "Check your tyres before a long journey.", zh: "輪胎" },
    { front: "underground", pos: "n.", def: "a railway system that runs under a city", example: "The underground is the fastest way to cross London.", zh: "地下鐵" },
    { front: "vehicle", pos: "n.", def: "a machine such as a car or bus that carries people or things", example: "This car park is for small vehicles only.", zh: "車輛" },
    { front: "land", pos: "v.", def: "to arrive on the ground after flying", example: "The plane landed safely despite the strong wind.", zh: "降落" },
    { front: "take off", pos: "phr. v.", def: "to leave the ground and begin flying", example: "The plane took off twenty minutes late.", zh: "起飛" },
    { front: "get on", pos: "phr. v.", def: "to enter a bus, train or plane", example: "We got on the bus at the main square.", zh: "上車" },
    { front: "get off", pos: "phr. v.", def: "to leave a bus, train or plane", example: "Get off at the third stop for the museum.", zh: "下車" },
    { front: "get in", pos: "phr. v.", def: "to enter a car, or to arrive", example: "Get in the car quickly; it's starting to rain.", zh: "上（車）；到達" },
    { front: "pick up", pos: "phr. v.", def: "to collect someone in a car, or to lift something", example: "Dad will pick us up outside the cinema at nine.", zh: "接（人）；拿起" },
    { front: "drop off", pos: "phr. v.", def: "to take someone to a place by car and leave them there", example: "Can you drop me off at the station on your way?", zh: "順道送到" },
    { front: "set off", pos: "phr. v.", def: "to start a journey", example: "We set off early to avoid the morning traffic.", zh: "出發" },
    { front: "check in", pos: "phr. v.", def: "to show your ticket at an airport or arrive at a hotel desk", example: "Passengers should check in two hours before the flight.", zh: "辦理登機／入住" },
    { front: "check out", pos: "phr. v.", def: "to pay and leave a hotel", example: "Guests must check out by eleven o'clock.", zh: "退房" },
    { front: "get away", pos: "phr. v.", def: "to go somewhere to have a rest or holiday", example: "We're hoping to get away for a few days in June.", zh: "外出度假、脫身" },
    { front: "look around", pos: "phr. v.", def: "to walk through a place and look at it", example: "We spent an hour looking around the old market.", zh: "四處參觀" },
    { front: "see off", pos: "phr. v.", def: "to go to a station or airport to say goodbye to someone", example: "The whole family came to see her off at the airport.", zh: "送行" },
    { front: "speed up", pos: "phr. v.", def: "to move or happen faster", example: "The train speeded up as it left the city.", zh: "加速" },
    { front: "slow down", pos: "phr. v.", def: "to move or happen more slowly", example: "Slow down when you drive past the school.", zh: "減速" },
    { front: "break down", pos: "phr. v.", def: "to stop working, used about machines and vehicles", example: "Our car broke down on the way to the coast.", zh: "拋錨、故障" },
    { front: "run out of", pos: "phr. v.", def: "to use all of something so there is none left", example: "We ran out of petrol miles from the nearest town.", zh: "用完" },
    /* ---------- Town, places & services ---------- */
    { front: "bakery", pos: "n.", def: "a shop where bread and cakes are made and sold", example: "The bakery on the corner sells wonderful croissants.", zh: "麵包店" },
    { front: "bank account", pos: "n.", def: "an arrangement with a bank to keep your money there", example: "She opened a bank account when she started her job.", zh: "銀行帳戶" },
    { front: "bookshop", pos: "n.", def: "a shop that sells books", example: "I found a second-hand copy in the little bookshop.", zh: "書店" },
    { front: "bridge", pos: "n.", def: "a structure that carries a road or path over a river", example: "Walk across the bridge and the gallery is on your left.", zh: "橋" },
    { front: "car park", pos: "n.", def: "an area or building where cars can be left", example: "The car park behind the cinema is free after six.", zh: "停車場" },
    { front: "cathedral", pos: "n.", def: "a large and important church", example: "The cathedral is the oldest building in the city.", zh: "大教堂" },
    { front: "chemist", pos: "n.", def: "a shop where you can buy medicines", example: "You can get something for your cough at the chemist.", zh: "藥局" },
    { front: "cinema", pos: "n.", def: "a place where you go to watch films", example: "There's a new comedy on at the cinema this week.", zh: "電影院" },
    { front: "corner", pos: "n.", def: "the place where two roads or walls meet", example: "The bus stop is just around the corner.", zh: "轉角" },
    { front: "crossroads", pos: "n.", def: "a place where two roads cross each other", example: "At the crossroads, go straight on towards the park.", zh: "十字路口" },
    { front: "department store", pos: "n.", def: "a large shop that sells many different kinds of goods", example: "The department store has a sale on this weekend.", zh: "百貨公司" },
    { front: "district", pos: "n.", def: "a part of a town or country", example: "They live in a quiet district near the river.", zh: "地區、區域" },
    { front: "embassy", pos: "n.", def: "the office of a country's government in a foreign country", example: "If you lose your passport, contact your embassy.", zh: "大使館" },
    { front: "entrance", pos: "n.", def: "the door or gate where you go into a place", example: "I'll meet you at the main entrance of the stadium.", zh: "入口" },
    { front: "exit", pos: "n.", def: "the door or gate where you leave a place", example: "In an emergency, use the nearest exit.", zh: "出口" },
    { front: "fire station", pos: "n.", def: "the building where firefighters and their equipment are based", example: "The fire station is opposite the swimming pool.", zh: "消防局" },
    { front: "fountain", pos: "n.", def: "a structure that sends water up into the air, often for decoration", example: "Tourists throw coins into the famous fountain.", zh: "噴泉" },
    { front: "gallery", pos: "n.", def: "a building where you can look at paintings and other art", example: "The gallery has free entry on Sundays.", zh: "美術館、畫廊" },
    { front: "hairdresser's", pos: "n.", def: "the shop where you have your hair cut", example: "She spends every Saturday morning at the hairdresser's.", zh: "美髮店" },
    { front: "inhabitant", pos: "n.", def: "a person who lives in a particular place", example: "The town has about ten thousand inhabitants.", zh: "居民" },
    { front: "library", pos: "n.", def: "a place where you can read and borrow books", example: "The library stays open late during exam time.", zh: "圖書館" },
    { front: "market", pos: "n.", def: "a place, often outside, where people buy and sell goods", example: "The Saturday market sells cheese from local farms.", zh: "市場" },
    { front: "monument", pos: "n.", def: "a building or statue that reminds people of an event or person", example: "The monument in the square honours the town's war heroes.", zh: "紀念碑" },
    { front: "mosque", pos: "n.", def: "a building where Muslims pray", example: "The old mosque is famous for its beautiful tiles.", zh: "清真寺" },
    { front: "neighbourhood", pos: "n.", def: "the area of a town where you live", example: "It's a friendly neighbourhood with lots of families.", zh: "社區、街坊" },
    { front: "newsagent", pos: "n.", def: "a shop that sells newspapers, magazines and sweets", example: "I bought a magazine at the newsagent by the station.", zh: "書報攤" },
    { front: "police station", pos: "n.", def: "the office of the local police", example: "He went to the police station to report the theft.", zh: "警察局" },
    { front: "post office", pos: "n.", def: "a place where you can send letters and parcels", example: "Could you take this parcel to the post office?", zh: "郵局" },
    { front: "queue", pos: "n.", def: "a line of people waiting for something", example: "There was a long queue outside the ticket office.", zh: "隊伍" },
    { front: "signpost", pos: "n.", def: "a sign beside a road that shows directions and distances", example: "The signpost says it's five kilometres to the coast.", zh: "路標" },
    { front: "square", pos: "n.", def: "an open area in a town, often with buildings around it", example: "There's a concert in the main square tonight.", zh: "廣場" },
    { front: "stadium", pos: "n.", def: "a large building with seats around a sports field", example: "The new stadium holds sixty thousand people.", zh: "體育場" },
    { front: "statue", pos: "n.", def: "a model of a person or animal made of stone or metal", example: "There's a statue of the poet in front of the theatre.", zh: "雕像" },
    { front: "suburb", pos: "n.", def: "an area of houses outside the centre of a city", example: "They moved to a quiet suburb when the baby was born.", zh: "郊區" },
    { front: "temple", pos: "n.", def: "a building where people of some religions pray", example: "Visitors must take off their shoes before entering the temple.", zh: "寺廟" },
    { front: "tourist office", pos: "n.", def: "a place that gives free information to visitors", example: "The tourist office gave us a free map of the city.", zh: "遊客服務中心" },
    { front: "town hall", pos: "n.", def: "the building where the local government works", example: "The meeting about the new park is at the town hall.", zh: "市政廳" },
    { front: "zebra crossing", pos: "n.", def: "a place with black and white lines where people can cross the road", example: "Cars must stop for people at a zebra crossing.", zh: "斑馬線" },
    { front: "airmail", pos: "n.", def: "the system of sending letters by plane", example: "How much does it cost to send this by airmail?", zh: "航空郵件" },
    { front: "envelope", pos: "n.", def: "a paper cover for a letter", example: "Write the address clearly on the envelope.", zh: "信封" },
    { front: "parcel", pos: "n.", def: "something wrapped in paper so it can be posted", example: "A parcel arrived for you this morning.", zh: "包裹" },
    { front: "postcard", pos: "n.", def: "a card with a picture that you send without an envelope", example: "Send me a postcard from Italy!", zh: "明信片" },
    { front: "stamp", pos: "n.", def: "a small piece of paper you stick on a letter to post it", example: "You need two stamps for a letter to Australia.", zh: "郵票" },
    { front: "postman", pos: "n.", def: "a person who delivers letters to houses", example: "The postman comes at about eight every morning.", zh: "郵差" },
    { front: "noticeboard", pos: "n.", def: "a board on a wall where notices are put for people to read", example: "The trip details are on the noticeboard in the hall.", zh: "布告欄" },
    { front: "poster", pos: "n.", def: "a large printed picture or notice put on a wall", example: "They put up posters to advertise the school play.", zh: "海報" },
    { front: "litter", pos: "n.", def: "pieces of rubbish left in a public place", example: "Please don't drop litter in the park.", zh: "垃圾" },
    { front: "rubbish bin", pos: "n.", def: "a container for waste", example: "Throw your empty bottle in the rubbish bin.", zh: "垃圾桶" },
    { front: "bench", pos: "n.", def: "a long seat for two or more people, usually outside", example: "We sat on a bench and watched the ducks.", zh: "長椅" },
    { front: "path", pos: "n.", def: "a narrow way for people to walk along", example: "Follow the path through the woods to the lake.", zh: "小路" },
    /* ---------- Directions & position ---------- */
    { front: "opposite", pos: "prep.", def: "on the other side of the road or space from something", example: "The bank is opposite the supermarket.", zh: "在……對面" },
    { front: "towards", pos: "prep.", def: "in the direction of something", example: "Walk towards the river and you'll see the hotel.", zh: "朝向" },
    { front: "through", pos: "prep.", def: "from one side of something to the other", example: "The train goes through a long tunnel.", zh: "穿過" },
    { front: "along", pos: "prep.", def: "following the length of something such as a road", example: "We walked along the beach at sunset.", zh: "沿著" },
    { front: "across", pos: "prep.", def: "from one side to the other side of something", example: "There's a small café just across the street.", zh: "橫越、在對面" },
    { front: "beside", pos: "prep.", def: "next to something or someone", example: "She sat beside me on the bus.", zh: "在旁邊" },
    { front: "between", pos: "prep.", def: "in the space that separates two things", example: "The chemist is between the bakery and the bank.", zh: "在……之間" },
    { front: "behind", pos: "prep.", def: "at the back of something", example: "The bike shed is behind the school building.", zh: "在後面" },
    { front: "above", pos: "prep.", def: "in a higher position than something", example: "Our flat is above a small restaurant.", zh: "在上方" },
    { front: "below", pos: "prep.", def: "in a lower position than something", example: "The temperature fell below zero last night.", zh: "在下方、低於" },
    { front: "straight on", pos: "phrase", def: "continuing in the same direction without turning", example: "Go straight on until you reach the church.", zh: "直走" },
    { front: "on the left", pos: "phrase", def: "on the left side", example: "The post office is on the left, next to the café.", zh: "在左邊" },
    { front: "on the right", pos: "phrase", def: "on the right side", example: "You'll see the museum on the right after the bridge.", zh: "在右邊" },
    { front: "in front of", pos: "prep.", def: "directly before someone or something", example: "A tall man was standing in front of me in the queue.", zh: "在前面" },
    { front: "next to", pos: "prep.", def: "at the side of; beside", example: "The hotel is right next to the beach.", zh: "在旁邊、緊鄰" },
    { front: "far from", pos: "phrase", def: "at a great distance from a place", example: "The campsite isn't far from the village shop.", zh: "離……遠" },
    { front: "nearby", pos: "adv.", def: "close to where you are", example: "Is there a cash machine nearby?", zh: "在附近" },
    { front: "somewhere", pos: "adv.", def: "in or to a place that you do not name exactly", example: "Let's go somewhere quiet for lunch.", zh: "某處" },
    { front: "everywhere", pos: "adv.", def: "in or to all places", example: "We looked everywhere for the car keys.", zh: "到處" },
    { front: "get lost", pos: "phrase", def: "to not know where you are or which way to go", example: "We got lost in the old town without a map.", zh: "迷路" },
    /* ---------- Holiday activities & experiences ---------- */
    { front: "camping", pos: "n.", def: "the activity of staying in a tent on holiday", example: "We go camping in the mountains every summer.", zh: "露營" },
    { front: "cruise", pos: "n.", def: "a holiday on a large ship that visits several places", example: "My grandparents went on a cruise around the Mediterranean.", zh: "郵輪之旅" },
    { front: "hiking", pos: "n.", def: "the activity of going for long walks in the countryside", example: "The area is perfect for hiking and cycling.", zh: "健行" },
    { front: "picnic", pos: "n.", def: "a meal that you eat outside, away from home", example: "We had a picnic by the lake on Sunday.", zh: "野餐" },
    { front: "sunset", pos: "n.", def: "the time when the sun goes down in the evening", example: "We watched the sunset from the top of the hill.", zh: "日落" },
    { front: "sunrise", pos: "n.", def: "the time when the sun comes up in the morning", example: "We got up early to see the sunrise over the sea.", zh: "日出" },
    { front: "postpone", pos: "v.", def: "to change an event to a later time or date", example: "They postponed the boat trip until the weather improved.", zh: "延期" },
    { front: "recommendation", pos: "n.", def: "a suggestion that something is good or suitable", example: "We chose the hotel on a friend's recommendation.", zh: "推薦" },
    { front: "guide", pos: "n.", def: "a person who shows tourists around a place", example: "The guide told us funny stories about the palace.", zh: "導遊" },
    { front: "map", pos: "n.", def: "a drawing that shows the roads, rivers and towns of an area", example: "Can you find our street on the map?", zh: "地圖" },
    { front: "surroundings", pos: "n.", def: "the area around a place or person", example: "The hotel is set in beautiful surroundings.", zh: "周圍環境" },
    { front: "atmosphere", pos: "n.", def: "the feeling that a place gives you", example: "The little harbour town has a relaxed atmosphere.", zh: "氣氛" },
    { front: "culture", pos: "n.", def: "the customs, art and way of life of a country or group", example: "Travelling helps you learn about other cultures.", zh: "文化" },
    { front: "custom", pos: "n.", def: "a traditional way of behaving in a particular society", example: "It's a local custom to give guests tea when they arrive.", zh: "習俗" },
    { front: "tradition", pos: "n.", def: "a belief or way of doing something that has existed for a long time", example: "Watching the parade is a family tradition.", zh: "傳統" },
    { front: "festival", pos: "n.", def: "a special series of public events, such as music or celebrations", example: "The town holds a music festival every July.", zh: "節慶" },
    { front: "firework", pos: "n.", def: "a small object that explodes in the sky with coloured lights", example: "The fireworks over the harbour were spectacular.", zh: "煙火" },
    { front: "parade", pos: "n.", def: "a line of people or vehicles moving through the streets to celebrate", example: "Children in costumes walked in the parade.", zh: "遊行" },
    { front: "carnival", pos: "n.", def: "a public celebration with music and dancing in the streets", example: "The carnival attracts visitors from all over the world.", zh: "嘉年華" },
    { front: "occasion", pos: "n.", def: "a special event or the time when something happens", example: "The wedding was a very happy occasion.", zh: "場合、時刻" },
    { front: "ceremony", pos: "n.", def: "a formal event held for a special occasion", example: "The opening ceremony of the games lasted two hours.", zh: "典禮" },
    { front: "unforgettable", pos: "adj.", def: "so good or special that you will always remember it", example: "The balloon ride was an unforgettable experience.", zh: "難以忘懷的" },
    { front: "memorable", pos: "adj.", def: "worth remembering; hard to forget", example: "Watching whales from the boat was a memorable experience.", zh: "難忘的" },
    { front: "impressive", pos: "adj.", def: "causing admiration because it is very good or very large", example: "The waterfall was even more impressive than the photos.", zh: "令人印象深刻的" },
    { front: "spectacular", pos: "adj.", def: "extremely exciting to look at", example: "The mountain scenery was absolutely spectacular.", zh: "壯觀的" },
    { front: "picturesque", pos: "adj.", def: "pretty and pleasant to look at, like a picture", example: "We stayed in a picturesque fishing village.", zh: "如畫的" },
    { front: "lively", pos: "adj.", def: "full of energy and activity", example: "The market is at its most lively on Saturday mornings.", zh: "熱鬧的、活潑的" },
    { front: "local", pos: "adj.", def: "belonging to the area where you are", example: "Try the local cheese; it's delicious.", zh: "當地的" },
    { front: "remote", pos: "adj.", def: "far away from towns and cities", example: "They spent a week in a remote mountain village.", zh: "偏遠的" },
    { front: "peak", pos: "n.", def: "the pointed top of a mountain", example: "The highest peak was covered in snow all year.", zh: "山峰" },
    /* ---------- Hotels & staying away ---------- */
    { front: "single room", pos: "n.", def: "a hotel room for one person", example: "I'd like to book a single room for two nights.", zh: "單人房" },
    { front: "double room", pos: "n.", def: "a hotel room for two people with one big bed", example: "A double room with a sea view costs more.", zh: "雙人房" },
    { front: "reception", pos: "n.", def: "the desk in a hotel or office where visitors are welcomed", example: "Please leave your key at reception when you go out.", zh: "接待處、櫃檯" },
    { front: "lift", pos: "n.", def: "a machine that carries people up and down in a building", example: "Take the lift to the fourth floor.", zh: "電梯" },
    { front: "key card", pos: "n.", def: "a plastic card used to open a hotel room door", example: "My key card stopped working, so I went back to reception.", zh: "房卡" },
    { front: "guest", pos: "n.", def: "a person staying in a hotel or visiting someone's home", example: "Breakfast is free for all hotel guests.", zh: "客人、房客" },
    { front: "vacancy", pos: "n.", def: "a room that is available in a hotel", example: "The sign outside the hotel said 'No vacancies'.", zh: "空房" },
    { front: "bed and breakfast", pos: "n.", def: "a small hotel offering a room for the night and breakfast", example: "We stayed at a lovely bed and breakfast by the sea.", zh: "民宿（含早餐）" },
    { front: "balcony", pos: "n.", def: "a small platform on the outside wall of a building, above the ground", example: "You can see the mountains from the balcony.", zh: "陽台" },
    { front: "air conditioning", pos: "n.", def: "a system that keeps the air in a building cool", example: "In August you really need air conditioning here.", zh: "空調" },
    { front: "complaint", pos: "n.", def: "a statement that you are not happy about something", example: "The manager received several complaints about the noise.", zh: "投訴" },
    { front: "facilities", pos: "n.", def: "rooms, equipment or services provided for a purpose", example: "The hotel has excellent sports facilities.", zh: "設施" },
    { front: "heating", pos: "n.", def: "the system that keeps a building warm", example: "The heating wasn't working, so the room was freezing.", zh: "暖氣" },
    { front: "laundry", pos: "n.", def: "clothes that need washing, or the service that washes them", example: "The hotel offers a same-day laundry service.", zh: "送洗衣物、洗衣服務" },
    { front: "deposit", pos: "n.", def: "money you pay in advance as part of the full price", example: "You have to pay a deposit to book the apartment.", zh: "訂金、押金" },
    /* ---------- Travel collocations & phrases ---------- */
    { front: "go abroad", pos: "phrase", def: "to travel to a foreign country", example: "More and more students go abroad during the summer.", zh: "出國" },
    { front: "go sightseeing", pos: "phrase", def: "to visit famous or interesting places as a tourist", example: "On our first day we went sightseeing in the old city.", zh: "去觀光" },
    { front: "catch a train", pos: "phrase", def: "to get on a train before it leaves", example: "We have to catch the train at half past eight.", zh: "趕搭火車" },
    { front: "miss the bus", pos: "phrase", def: "to arrive too late to get on the bus", example: "Hurry up, or we'll miss the bus again!", zh: "錯過公車" },
    { front: "by heart", pos: "phrase", def: "from memory, without reading", example: "She knows the whole poem by heart.", zh: "熟記、背下來" },
    { front: "on foot", pos: "phrase", def: "walking rather than using transport", example: "The castle is only ten minutes away on foot.", zh: "步行" },
    { front: "on holiday", pos: "phrase", def: "away from home or work, having a rest", example: "They're on holiday in Portugal until Friday.", zh: "度假中" },
    { front: "on board", pos: "phrase", def: "on a ship, plane, bus or train", example: "Welcome on board this flight to Rome.", zh: "在（交通工具）上" },
    { front: "make a booking", pos: "phrase", def: "to reserve a seat, room or table", example: "I made a booking for a table by the window.", zh: "預訂" },
    { front: "go camping", pos: "phrase", def: "to have a holiday sleeping in a tent", example: "We're going camping in the national park next month.", zh: "去露營" },
    /* ---------- More travel verbs & adjectives ---------- */
    { front: "arrive", pos: "v.", def: "to reach the place you are going to", example: "What time does the coach arrive in Manchester?", zh: "到達" },
    { front: "depart", pos: "v.", def: "to leave, especially when starting a journey", example: "The next ferry departs at noon.", zh: "出發、啟程" },
    { front: "board", pos: "v.", def: "to get on a plane, ship or train", example: "Passengers for Madrid should board at gate twelve.", zh: "登上（交通工具）" },
    { front: "cross", pos: "v.", def: "to go from one side of something to the other", example: "Look both ways before you cross the road.", zh: "穿越" },
    { front: "wander", pos: "v.", def: "to walk around slowly with no clear direction", example: "We wandered through the narrow streets of the old town.", zh: "漫步、閒逛" },
    { front: "tow", pos: "v.", def: "to pull a vehicle behind another vehicle", example: "Our car had to be towed to the nearest garage.", zh: "拖吊、拖曳" },
    { front: "park", pos: "v.", def: "to leave a vehicle in a place for a time", example: "You can't park in front of the hospital entrance.", zh: "停車" },
    { front: "sail", pos: "v.", def: "to travel across water in a boat or ship", example: "They sailed from the port early in the morning.", zh: "航行" },
    { front: "punctual", pos: "adj.", def: "arriving at the correct time; not late", example: "The trains in this country are famously punctual.", zh: "準時的" },
    { front: "direct", pos: "adj.", def: "going straight to a place without stopping or changing", example: "Is there a direct flight to New York from here?", zh: "直達的" },
    { front: "return ticket", pos: "n.", def: "a ticket to travel to a place and back again", example: "A return ticket is cheaper than two singles.", zh: "來回票" },
    { front: "single ticket", pos: "n.", def: "a ticket to travel to a place but not back", example: "A single ticket to Oxford, please.", zh: "單程票" },
    { front: "season ticket", pos: "n.", def: "a ticket that you can use many times during a period", example: "A monthly season ticket saves commuters a lot of money.", zh: "定期票、月票" },
    { front: "rush hour", pos: "n.", def: "the busy time when people travel to or from work", example: "Avoid the underground during the rush hour.", zh: "尖峰時間" },
    { front: "duty-free", pos: "adj.", def: "sold at airports without tax", example: "She bought some duty-free perfume at the airport.", zh: "免稅的" },
    { front: "first class", pos: "n.", def: "the most expensive and comfortable seats on a train or plane", example: "They travelled first class on the express train.", zh: "頭等艙、頭等座" },
    { front: "aisle", pos: "n.", def: "the long passage between rows of seats", example: "Would you like a window seat or an aisle seat?", zh: "走道" },
    { front: "cabin", pos: "n.", def: "a small room on a ship, or the inside of a plane", example: "Our cabin on the ferry had two small beds.", zh: "船艙、機艙" },
    { front: "deck", pos: "n.", def: "the open top part of a ship", example: "We stood on the deck and watched the coast disappear.", zh: "甲板" },
    { front: "harbour", pos: "n.", def: "an area of water where ships stop and are safe", example: "Fishing boats returned to the harbour in the evening.", zh: "港口" },
    { front: "port", pos: "n.", def: "a town or area where ships load and unload", example: "The cruise ship visits three ports in five days.", zh: "港市、港口" },
    { front: "runway", pos: "n.", def: "the long road at an airport where planes take off and land", example: "The plane waited on the runway for twenty minutes.", zh: "跑道" },
    { front: "terminal", pos: "n.", def: "a large airport building where journeys begin and end", example: "International flights leave from Terminal Two.", zh: "航廈" },
    { front: "customs", pos: "n.", def: "the place at a border where your bags can be checked", example: "We went through customs without any problems.", zh: "海關" },
    { front: "border", pos: "n.", def: "the line that separates two countries", example: "The village is close to the border with France.", zh: "邊界" },
    /* ---------- Beach & coast holidays ---------- */
    { front: "coast", pos: "n.", def: "the land next to the sea", example: "We drove along the coast, stopping at little beaches.", zh: "海岸" },
    { front: "cliff", pos: "n.", def: "a high steep rock face, often by the sea", example: "The path along the cliff has amazing views.", zh: "懸崖" },
    { front: "bay", pos: "n.", def: "a part of the coast where the land curves in", example: "The boats in the bay looked tiny from the hill.", zh: "海灣" },
    { front: "island", pos: "n.", def: "a piece of land surrounded by water", example: "The island can only be reached by boat.", zh: "島嶼" },
    { front: "sand", pos: "n.", def: "the very small grains that cover beaches and deserts", example: "The children built a castle out of sand.", zh: "沙" },
    { front: "wave", pos: "n.", def: "a line of water that moves across the surface of the sea", example: "The waves were too big for swimming that day.", zh: "海浪" },
    { front: "tide", pos: "n.", def: "the regular rise and fall of the sea level", example: "Check the tide times before you walk to the caves.", zh: "潮汐" },
    { front: "shore", pos: "n.", def: "the land along the edge of the sea or a lake", example: "We walked along the shore collecting shells.", zh: "岸邊" },
    { front: "shell", pos: "n.", def: "the hard outer covering of a sea creature", example: "She keeps a jar of shells from every beach she visits.", zh: "貝殼" },
    { front: "sunscreen", pos: "n.", def: "cream that protects your skin from the sun", example: "Put on plenty of sunscreen before you go to the beach.", zh: "防曬乳" },
    { front: "sunburn", pos: "n.", def: "red, painful skin caused by too much sun", example: "He got terrible sunburn on his shoulders.", zh: "曬傷" },
    { front: "towel", pos: "n.", def: "a piece of cloth used to dry yourself", example: "Don't forget to take a towel to the pool.", zh: "毛巾" },
    { front: "swimsuit", pos: "n.", def: "a piece of clothing worn for swimming", example: "She packed two swimsuits for the beach holiday.", zh: "泳衣" },
    { front: "dive", pos: "v.", def: "to jump into water with your head first, or swim underwater", example: "He dived into the pool from the highest board.", zh: "跳水、潛水" },
    { front: "float", pos: "v.", def: "to stay on the surface of water", example: "It's easier to float in the sea than in a pool.", zh: "漂浮" },
    { front: "surfing", pos: "n.", def: "the sport of riding waves on a special board", example: "The west coast is famous for its surfing.", zh: "衝浪" },
    { front: "sailing", pos: "n.", def: "the sport or activity of travelling in a boat with sails", example: "They go sailing on the lake most weekends.", zh: "帆船運動" },
    { front: "lighthouse", pos: "n.", def: "a tall tower with a light that guides ships", example: "The old lighthouse is now a small museum.", zh: "燈塔" },
    { front: "seaside", pos: "n.", def: "an area next to the sea where people go on holiday", example: "We spent a week at the seaside with my cousins.", zh: "海邊" },
    { front: "horizon", pos: "n.", def: "the line where the sky seems to meet the land or sea", example: "A ship appeared on the horizon at sunset.", zh: "地平線" },
    /* ---------- Countryside trips ---------- */
    { front: "countryside", pos: "n.", def: "land away from towns and cities, with farms and fields", example: "We cycled through miles of peaceful countryside.", zh: "鄉間" },
    { front: "farm", pos: "n.", def: "land and buildings where crops are grown and animals are kept", example: "The children loved feeding the lambs at the farm.", zh: "農場" },
    { front: "field", pos: "n.", def: "an area of land used for growing crops or keeping animals", example: "The path crosses a field full of sheep.", zh: "田野" },
    { front: "hill", pos: "n.", def: "an area of land that is higher than the land around it", example: "From the top of the hill you can see the whole valley.", zh: "山丘" },
    { front: "valley", pos: "n.", def: "the low land between hills or mountains", example: "A small river runs through the valley.", zh: "山谷" },
    { front: "stream", pos: "n.", def: "a small narrow river", example: "We crossed the stream on stepping stones.", zh: "小溪" },
    { front: "waterfall", pos: "n.", def: "water that falls from a high place, such as over rocks", example: "It's an hour's walk to the waterfall.", zh: "瀑布" },
    { front: "cave", pos: "n.", def: "a large natural hole in rock or under the ground", example: "The caves are lit so that visitors can walk through safely.", zh: "洞穴" },
    { front: "scenery", pos: "n.", def: "the natural beauty of an area of countryside", example: "The scenery in the highlands is breathtaking.", zh: "風景" },
    { front: "tent", pos: "n.", def: "a shelter made of cloth that you sleep in when camping", example: "It took us half an hour to put up the tent.", zh: "帳篷" },
    { front: "sleeping bag", pos: "n.", def: "a warm bag that you sleep in when camping", example: "My sleeping bag kept me warm even on cold nights.", zh: "睡袋" },
    { front: "torch", pos: "n.", def: "a small electric light that you carry in your hand", example: "Take a torch if you're walking back after dark.", zh: "手電筒" },
    { front: "compass", pos: "n.", def: "an instrument that shows you which direction is north", example: "A compass is essential when hiking in the mountains.", zh: "指南針" },
    { front: "trail", pos: "n.", def: "a path through the countryside for walking", example: "The forest trail is marked with yellow signs.", zh: "步道" },
    { front: "picnic area", pos: "n.", def: "a place with tables where people can eat outside", example: "There's a picnic area near the entrance to the park.", zh: "野餐區" },
    /* ---------- Phrasal verbs B ---------- */
    { front: "come back", pos: "phr. v.", def: "to return to a place", example: "What time are you coming back from the mountains?", zh: "回來" },
    { front: "go away", pos: "phr. v.", def: "to leave home for a holiday or trip", example: "We're going away for the long weekend.", zh: "外出、離開" },
    { front: "get back", pos: "phr. v.", def: "to return, especially to your home", example: "We didn't get back from the airport until midnight.", zh: "返回" },
    { front: "set out", pos: "phr. v.", def: "to begin a journey", example: "The climbers set out before sunrise.", zh: "啟程" },
    { front: "stop over", pos: "phr. v.", def: "to stay somewhere for a short time during a long journey", example: "We stopped over in Dubai on the way to Sydney.", zh: "中途停留" },
    { front: "get around", pos: "phr. v.", def: "to travel to different places in an area", example: "The best way to get around the city is by bike.", zh: "四處移動" },
    { front: "show around", pos: "phr. v.", def: "to take someone to see the interesting parts of a place", example: "My cousin showed us around his university.", zh: "帶……參觀" },
    { front: "hurry up", pos: "phr. v.", def: "to do something more quickly", example: "Hurry up, or we'll be late for the ferry!", zh: "趕快" },
    { front: "get out of", pos: "phr. v.", def: "to leave a car, building or situation", example: "He got out of the taxi and paid the driver.", zh: "離開、下（車）" },
    { front: "pull over", pos: "phr. v.", def: "to drive to the side of the road and stop", example: "The police officer asked the driver to pull over.", zh: "靠邊停車" },
    { front: "fill up", pos: "phr. v.", def: "to make something completely full, especially a fuel tank", example: "We filled up the car before joining the motorway.", zh: "加滿、裝滿" },
    { front: "get through", pos: "phr. v.", def: "to manage to pass or finish something", example: "It took an hour to get through passport control.", zh: "通過、完成" },
    { front: "come along", pos: "phr. v.", def: "to go somewhere with someone", example: "We're going to the beach; why don't you come along?", zh: "一起來" },
    { front: "look forward to", pos: "phr. v.", def: "to feel happy about something that is going to happen", example: "I'm really looking forward to our trip to Japan.", zh: "期待" },
    { front: "put up", pos: "phr. v.", def: "to build or fix something in place, or let someone stay in your home", example: "We put up the tent just before it started to rain.", zh: "搭建；留宿" },
    /* ---------- Countries, languages & world ---------- */
    { front: "capital", pos: "n.", def: "the most important city of a country, where the government is", example: "Wellington is the capital of New Zealand.", zh: "首都" },
    { front: "continent", pos: "n.", def: "one of the seven large areas of land in the world", example: "Africa is the second largest continent.", zh: "洲、大陸" },
    { front: "population", pos: "n.", def: "the number of people living in a place", example: "The city has a population of two million.", zh: "人口" },
    { front: "region", pos: "n.", def: "a large area of a country or the world", example: "This region is famous for its wine.", zh: "區域" },
    { front: "climate", pos: "n.", def: "the usual weather conditions of a place", example: "The island has a warm climate all year round.", zh: "氣候" },
    { front: "desert", pos: "n.", def: "a large dry area with little rain and few plants", example: "Camels can survive for days in the desert.", zh: "沙漠" },
    { front: "language", pos: "n.", def: "the words used by the people of a country to communicate", example: "How many languages are spoken in Switzerland?", zh: "語言" },
    { front: "national", pos: "adj.", def: "relating to a whole country", example: "The national museum is free on the first Sunday of the month.", zh: "國家的、全國的" },
    { front: "international", pos: "adj.", def: "involving two or more countries", example: "The airport handles international flights only.", zh: "國際的" },
    { front: "accent", pos: "n.", def: "the way people from a place pronounce words", example: "She speaks English with a slight French accent.", zh: "口音" },
    { front: "phrase book", pos: "n.", def: "a small book of useful expressions in a foreign language", example: "I used my phrase book to order food in Italian.", zh: "常用語手冊" },
    { front: "communication", pos: "n.", def: "the act of sharing information with others", example: "Good communication is important when you travel with friends.", zh: "溝通" },
    /* ---------- Getting around town ---------- */
    { front: "direction", pos: "n.", def: "the way you go to get somewhere", example: "We asked a police officer for directions to the harbour.", zh: "方向、指路" },
    { front: "sign", pos: "n.", def: "a board or notice that gives information or directions", example: "The sign says the pool is closed on Mondays.", zh: "標誌" },
    { front: "junction", pos: "n.", def: "a place where roads or railway lines meet", example: "Leave the motorway at junction eight.", zh: "交流道、交叉口" },
    { front: "tunnel", pos: "n.", def: "a long passage under the ground or through a hill", example: "The new tunnel goes right under the harbour.", zh: "隧道" },
    { front: "taxi rank", pos: "n.", def: "a place where taxis wait for passengers", example: "There's a taxi rank just outside the station.", zh: "計程車招呼站" },
    { front: "bus stop", pos: "n.", def: "a place where buses stop for passengers", example: "Wait for me at the bus stop opposite the school.", zh: "公車站牌" },
    { front: "ticket office", pos: "n.", def: "a place where tickets are sold", example: "The ticket office closes at ten in the evening.", zh: "售票處" },
    { front: "waiting room", pos: "n.", def: "a room where people wait, for example at a station", example: "It was cold, so we sat in the waiting room.", zh: "候車室、候診室" },
    { front: "escalator", pos: "n.", def: "moving stairs that carry people up or down", example: "Take the escalator down to the underground platform.", zh: "手扶梯" },
    { front: "left luggage", pos: "n.", def: "a place at a station where you can leave your bags", example: "We put our suitcases in left luggage and explored the town.", zh: "行李寄放處" },
    { front: "lost property", pos: "n.", def: "the office where things people have lost are kept", example: "Someone handed my phone in to lost property.", zh: "失物招領處" },
    { front: "announcement", pos: "n.", def: "important information told to the public, often through speakers", example: "Listen for the announcement about our platform.", zh: "廣播、公告" },
    { front: "connection", pos: "n.", def: "a train, bus or plane that you catch after the first one", example: "If the flight is late, we'll miss our connection.", zh: "轉乘班次" },
    { front: "transfer", pos: "v.", def: "to move from one vehicle or place to another during a journey", example: "You'll need to transfer to a local bus at the border.", zh: "轉乘、轉移" },
    { front: "commuter", pos: "n.", def: "a person who travels regularly between home and work", example: "The early trains are full of commuters.", zh: "通勤者" },
    { front: "cab", pos: "n.", def: "another word for a taxi", example: "Let's take a cab; it's raining too hard to walk.", zh: "計程車" },
    { front: "fine", pos: "n.", def: "money you must pay for breaking a rule or law", example: "He got a fine for parking on the pavement.", zh: "罰款" },
    { front: "speed limit", pos: "n.", def: "the fastest speed allowed on a road", example: "The speed limit near schools is thirty kilometres an hour.", zh: "速限" },
    /* ---------- Describing journeys ---------- */
    { front: "comfortable journey", pos: "phrase", def: "a journey that is pleasant and relaxing", example: "Thanks to the new seats, it was a very comfortable journey.", zh: "舒適的旅程" },
    { front: "heavy traffic", pos: "phrase", def: "a large number of vehicles on the road", example: "We left early because of the heavy traffic near the stadium.", zh: "交通壅塞" },
    { front: "package holiday", pos: "n.", def: "a holiday where travel and hotel are arranged together at one price", example: "They booked a cheap package holiday to the islands.", zh: "套裝行程" },
    { front: "high season", pos: "n.", def: "the time of year when most people travel and prices are high", example: "Hotel rooms double in price during the high season.", zh: "旺季" },
    { front: "low season", pos: "n.", def: "the time of year when few people travel and prices are low", example: "The resort is quiet and cheap in the low season.", zh: "淡季" },
    { front: "day trip", pos: "n.", def: "a visit to a place and back within one day", example: "We went on a day trip to the caves and the castle.", zh: "一日遊" },
    { front: "round trip", pos: "n.", def: "a journey to a place and back again", example: "The round trip to the glacier takes six hours.", zh: "來回行程" },
    { front: "travel light", pos: "phrase", def: "to travel with very little luggage", example: "I always travel light: just one small backpack.", zh: "輕裝旅行" },
    { front: "home town", pos: "n.", def: "the town where you were born or grew up", example: "She went back to her home town for the festival.", zh: "家鄉" },
    { front: "landmark", pos: "n.", def: "a famous building or place that is easy to recognise", example: "The tower is the city's best-known landmark.", zh: "地標" },
    { front: "attraction", pos: "n.", def: "a place that people visit for interest or pleasure", example: "The aquarium is the town's most popular attraction.", zh: "景點" },
    { front: "exhibition", pos: "n.", def: "a public show of art or interesting objects", example: "There's a photography exhibition at the gallery this month.", zh: "展覽" },
    { front: "entrance fee", pos: "n.", def: "money you pay to enter a place", example: "The entrance fee includes a free audio guide.", zh: "門票費" },
    { front: "opening hours", pos: "n.", def: "the times when a shop or place is open", example: "Check the opening hours before you visit the palace.", zh: "營業時間" },
    { front: "leaflet", pos: "n.", def: "a piece of printed paper giving information", example: "A leaflet about the boat trips was pushed under our door.", zh: "傳單" },
    { front: "audio guide", pos: "n.", def: "a recorded guide you listen to while visiting a place", example: "The audio guide is available in eight languages.", zh: "語音導覽" },
    { front: "queue up", pos: "phr. v.", def: "to stand in a line and wait for something", example: "We queued up for an hour to see the exhibition.", zh: "排隊" },
    { front: "wait for", pos: "phr. v.", def: "to stay somewhere until someone or something arrives", example: "We waited for the bus in the pouring rain.", zh: "等候" },
    { front: "ask for", pos: "phr. v.", def: "to say that you want something", example: "He asked for a window seat at check-in.", zh: "要求" },
    { front: "pay for", pos: "phr. v.", def: "to give money in exchange for something", example: "My parents paid for the whole trip.", zh: "付錢買" },
    { front: "get to", pos: "phr. v.", def: "to arrive at a place", example: "How long does it take to get to the airport from here?", zh: "到達" },
    { front: "head for", pos: "phr. v.", def: "to move in the direction of a place", example: "After lunch we headed for the beach.", zh: "前往" },
    { front: "turn back", pos: "phr. v.", def: "to return the way you came", example: "The snow got heavier, so we had to turn back.", zh: "折返" },
    { front: "move in", pos: "phr. v.", def: "to start living in a new home", example: "Our new neighbours moved in last weekend.", zh: "搬入" },
    { front: "move out", pos: "phr. v.", def: "to leave the home where you have been living", example: "She's moving out of her parents' house next month.", zh: "搬出" },
    { front: "sightsee", pos: "v.", def: "to visit interesting places as a tourist", example: "We were too tired to sightsee after the long flight.", zh: "觀光" },
    { front: "surf", pos: "v.", def: "to ride on waves using a special board", example: "He learned to surf during his holiday in Australia.", zh: "衝浪" },
    { front: "ride", pos: "v.", def: "to travel on a bicycle, motorbike or horse", example: "She rides her horse in the fields every morning.", zh: "騎乘" },
    { front: "row", pos: "v.", def: "to move a boat through water using oars", example: "We rowed across the lake to the little island.", zh: "划船" },
    { front: "climb", pos: "v.", def: "to go up something using your hands and feet", example: "They climbed the mountain in just four hours.", zh: "攀爬" },
    { front: "stroll", pos: "v.", def: "to walk slowly in a relaxed way", example: "We strolled along the promenade after dinner.", zh: "散步" },
    { front: "departure lounge", pos: "n.", def: "the area at an airport where you wait for your flight", example: "We bought coffee in the departure lounge.", zh: "候機室" },
    { front: "hand luggage", pos: "n.", def: "small bags you carry onto a plane with you", example: "Liquids in hand luggage must be in small bottles.", zh: "手提行李" },
    { front: "window seat", pos: "n.", def: "a seat next to the window on a plane or train", example: "I always choose a window seat so I can enjoy the view.", zh: "靠窗座位" },
    { front: "travel sickness", pos: "n.", def: "the feeling of being ill when travelling in a vehicle", example: "She takes tablets for travel sickness on long journeys.", zh: "暈車、暈船" },
    { front: "jet lag", pos: "n.", def: "tiredness after flying across different time zones", example: "It took me three days to get over the jet lag.", zh: "時差" },
    { front: "go on holiday", pos: "phrase", def: "to leave home to have a rest somewhere else", example: "We usually go on holiday in early September.", zh: "去度假" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
