/* PET Prep extra bank: vocab wave 6 */
(function () {
  var BANK = [
    /* ---------- Feelings & emotions ---------- */
    { front: "afraid", pos: "adj.", def: "feeling fear", example: "She's afraid of spiders, even tiny ones.", zh: "害怕的" },
    { front: "amazed", pos: "adj.", def: "very surprised", example: "I was amazed at how quickly he learned to swim.", zh: "驚訝的" },
    { front: "annoyed", pos: "adj.", def: "slightly angry", example: "He was annoyed that nobody had told him about the change.", zh: "惱怒的" },
    { front: "anxious", pos: "adj.", def: "worried and nervous", example: "She felt anxious before the results came out.", zh: "焦慮的" },
    { front: "ashamed", pos: "adj.", def: "feeling bad because of something you have done", example: "He was ashamed of the way he had spoken to her.", zh: "羞愧的" },
    { front: "bored", pos: "adj.", def: "tired and uninterested because nothing is happening", example: "The children got bored on the long car journey.", zh: "感到無聊的" },
    { front: "calm", pos: "adj.", def: "relaxed and not worried or angry", example: "Stay calm and read every question carefully.", zh: "冷靜的" },
    { front: "confident", pos: "adj.", def: "sure about your own abilities", example: "She walked into the interview feeling confident.", zh: "有自信的" },
    { front: "confused", pos: "adj.", def: "unable to understand what is happening", example: "The instructions left everyone completely confused.", zh: "困惑的" },
    { front: "curious", pos: "adj.", def: "wanting to know about something", example: "The cat was curious about the new box.", zh: "好奇的" },
    { front: "delighted", pos: "adj.", def: "very pleased", example: "They were delighted with their exam results.", zh: "高興的" },
    { front: "depressed", pos: "adj.", def: "very unhappy for a long time", example: "The grey winter weather makes some people depressed.", zh: "沮喪的" },
    { front: "embarrassed", pos: "adj.", def: "feeling shy or ashamed in front of others", example: "I was so embarrassed when I forgot her name.", zh: "尷尬的" },
    { front: "excited", pos: "adj.", def: "very happy about something that is going to happen", example: "The kids are excited about the trip to the zoo.", zh: "興奮的" },
    { front: "frightened", pos: "adj.", def: "afraid", example: "The loud thunder frightened the little boy.", zh: "受驚的" },
    { front: "frustrated", pos: "adj.", def: "annoyed because you cannot do what you want", example: "He got frustrated when the wifi kept dropping.", zh: "受挫的" },
    { front: "grateful", pos: "adj.", def: "feeling thankful", example: "We're really grateful for all your help.", zh: "感激的" },
    { front: "guilty", pos: "adj.", def: "feeling bad because you did something wrong", example: "She felt guilty about missing her friend's party.", zh: "內疚的" },
    { front: "jealous", pos: "adj.", def: "unhappy because someone has what you want", example: "He was jealous of his brother's new bike.", zh: "嫉妒的" },
    { front: "miserable", pos: "adj.", def: "very unhappy", example: "The team looked miserable after the defeat.", zh: "悲慘的、痛苦的" },
    { front: "nervous", pos: "adj.", def: "worried about something that is going to happen", example: "I always feel nervous before speaking in public.", zh: "緊張的" },
    { front: "pleased", pos: "adj.", def: "happy and satisfied", example: "The teacher was pleased with our project.", zh: "滿意的" },
    { front: "proud", pos: "adj.", def: "feeling pleased about something you or others have done", example: "Her parents are very proud of her medal.", zh: "驕傲的、自豪的" },
    { front: "relieved", pos: "adj.", def: "happy because something bad did not happen", example: "I was relieved to hear that everyone was safe.", zh: "鬆一口氣的" },
    { front: "satisfied", pos: "adj.", def: "pleased because something is as good as you expected", example: "The customer seemed satisfied with the repair.", zh: "滿意的" },
    { front: "shocked", pos: "adj.", def: "very surprised and upset", example: "We were shocked by the news of the accident.", zh: "震驚的" },
    { front: "shy", pos: "adj.", def: "nervous about talking to people you do not know", example: "He was too shy to ask a question in class.", zh: "害羞的" },
    { front: "surprised", pos: "adj.", def: "feeling that something unexpected has happened", example: "She was surprised to see snow in April.", zh: "感到驚訝的" },
    { front: "terrified", pos: "adj.", def: "extremely frightened", example: "I'm terrified of flying, so we take the train.", zh: "驚恐的" },
    { front: "upset", pos: "adj.", def: "unhappy because something bad has happened", example: "She was upset when her best friend moved away.", zh: "難過的" },
    { front: "worried", pos: "adj.", def: "unhappy because you keep thinking about a problem", example: "They were worried about the rising cost of rent.", zh: "擔心的" },
    { front: "cheerfulness", pos: "n.", def: "the quality of being happy and positive", example: "Her cheerfulness makes the whole office brighter.", zh: "開朗" },
    { front: "fear", pos: "n.", def: "the feeling you have when you are afraid", example: "He overcame his fear of heights on the climbing wall.", zh: "恐懼" },
    { front: "joy", pos: "n.", def: "a feeling of great happiness", example: "The children jumped for joy at the news.", zh: "喜悅" },
    { front: "pride", pos: "n.", def: "the feeling of being proud", example: "She showed us her garden with great pride.", zh: "自豪" },
    { front: "sorrow", pos: "n.", def: "a feeling of great sadness", example: "The whole town shared the family's sorrow.", zh: "悲傷" },
    { front: "excitement", pos: "n.", def: "the feeling of being excited", example: "There was great excitement before the final.", zh: "興奮" },
    { front: "surprise", pos: "n.", def: "an unexpected event, or the feeling it causes", example: "The party was a complete surprise for Dad.", zh: "驚喜、驚訝" },
    { front: "mood", pos: "n.", def: "the way you feel at a particular time", example: "He's in a good mood because his team won.", zh: "心情" },
    { front: "temper", pos: "n.", def: "the tendency to become angry", example: "She lost her temper when the bus was cancelled again.", zh: "脾氣" },
    { front: "sense of humour", pos: "n.", def: "the ability to find things funny", example: "You need a sense of humour to work here.", zh: "幽默感" },
    { front: "laughter", pos: "n.", def: "the sound of people laughing", example: "Laughter came from the classroom next door.", zh: "笑聲" },
    { front: "tear", pos: "n.", def: "a drop of water that comes from your eye when you cry", example: "A tear rolled down her cheek during the film.", zh: "眼淚" },
    { front: "smile", pos: "v.", def: "to make your mouth curve up to show you are happy", example: "The baby smiled at everyone on the bus.", zh: "微笑" },
    { front: "laugh", pos: "v.", def: "to make sounds that show you think something is funny", example: "We laughed so hard that we cried.", zh: "笑" },
    { front: "cry", pos: "v.", def: "to produce tears because you are sad or hurt", example: "The little girl cried when her balloon flew away.", zh: "哭" },
    { front: "frown", pos: "v.", def: "to move your eyebrows together to show anger or worry", example: "He frowned at the difficult question.", zh: "皺眉" },
    { front: "blush", pos: "v.", def: "to become red in the face because you are embarrassed", example: "She blushed when the teacher praised her in front of everyone.", zh: "臉紅" },
    { front: "complain about", pos: "phrase", def: "to say you are unhappy about something", example: "He's always complaining about the weather.", zh: "抱怨" },
    { front: "calm down", pos: "phr. v.", def: "to become less angry or excited", example: "Take a deep breath and calm down.", zh: "冷靜下來" },
    /* ---------- Personality ---------- */
    { front: "ambitious", pos: "adj.", def: "wanting very much to be successful", example: "She's ambitious and plans to start her own company.", zh: "有抱負的" },
    { front: "bossy", pos: "adj.", def: "always telling other people what to do", example: "My older sister can be quite bossy at home.", zh: "愛指揮人的" },
    { front: "cheeky", pos: "adj.", def: "slightly rude but often in a funny way", example: "The cheeky boy asked for a second dessert.", zh: "調皮無禮的" },
    { front: "confident person", pos: "phrase", def: "someone who believes in their own abilities", example: "A confident person finds interviews much easier.", zh: "有自信的人" },
    { front: "easy-going", pos: "adj.", def: "relaxed and not easily worried or annoyed", example: "Our teacher is easy-going but expects hard work.", zh: "隨和的" },
    { front: "honest", pos: "adj.", def: "always telling the truth", example: "Be honest with me: do you like the painting?", zh: "誠實的" },
    { front: "dishonest", pos: "adj.", def: "not telling the truth; likely to cheat", example: "It was dishonest of him to copy her answers.", zh: "不誠實的" },
    { front: "kind", pos: "adj.", def: "caring about others and wanting to help", example: "It was kind of you to carry her shopping.", zh: "仁慈的" },
    { front: "unkind", pos: "adj.", def: "slightly cruel; not kind", example: "Laughing at his mistake was unkind.", zh: "不友善的" },
    { front: "loyal", pos: "adj.", def: "always supporting your friends or group", example: "A loyal friend stays with you in difficult times.", zh: "忠誠的" },
    { front: "modest", pos: "adj.", def: "not talking proudly about your abilities", example: "She's modest about her success and never boasts.", zh: "謙虛的" },
    { front: "optimistic", pos: "adj.", def: "believing that good things will happen", example: "He's optimistic about passing his driving test.", zh: "樂觀的" },
    { front: "pessimistic", pos: "adj.", def: "believing that bad things will happen", example: "Don't be so pessimistic; we still have a chance.", zh: "悲觀的" },
    { front: "reliable", pos: "adj.", def: "able to be trusted to do what is expected", example: "She's reliable and always arrives on time.", zh: "可靠的" },
    { front: "unreliable", pos: "adj.", def: "not able to be trusted or depended on", example: "The old bus service was slow and unreliable.", zh: "不可靠的" },
    { front: "selfish", pos: "adj.", def: "caring only about yourself", example: "It's selfish to take the biggest piece every time.", zh: "自私的" },
    { front: "sensible", pos: "adj.", def: "showing good judgement; practical", example: "Taking a spare key was a sensible idea.", zh: "明智的" },
    { front: "sensitive", pos: "adj.", def: "easily hurt emotionally, or understanding others' feelings", example: "Be careful what you say; he's quite sensitive.", zh: "敏感的、體貼的" },
    { front: "sociable", pos: "adj.", def: "enjoying being with other people", example: "She's sociable and makes friends everywhere.", zh: "善於交際的" },
    { front: "stubborn", pos: "adj.", def: "refusing to change your ideas or plans", example: "He's too stubborn to admit he was wrong.", zh: "固執的" },
    { front: "talkative", pos: "adj.", def: "talking a lot", example: "My grandmother is the most talkative person I know.", zh: "健談的" },
    { front: "hard-working", pos: "adj.", def: "putting a lot of effort into work or study", example: "She's the most hard-working student in the class.", zh: "勤奮的" },
    { front: "punctuality", pos: "n.", def: "the habit of arriving at the right time", example: "The company values punctuality very highly.", zh: "守時" },
    { front: "personality", pos: "n.", def: "the type of person you are, shown by your behaviour", example: "The twins look alike but have different personalities.", zh: "個性" },
    { front: "behaviour", pos: "n.", def: "the way a person acts", example: "The teacher praised the class for their excellent behaviour.", zh: "行為" },
    /* ---------- Family & relationships ---------- */
    { front: "acquaintance", pos: "n.", def: "a person you know slightly but not well", example: "He's just an acquaintance from my old job.", zh: "點頭之交" },
    { front: "close friend", pos: "n.", def: "a friend you know very well and trust", example: "Only close friends were invited to the small wedding.", zh: "摯友" },
    { front: "couple", pos: "n.", def: "two people who are married or in a relationship", example: "The couple at the next table were celebrating.", zh: "情侶、夫婦" },
    { front: "engaged (couple)", pos: "adj.", def: "having formally agreed to marry", example: "They got engaged on the beach at sunset.", zh: "訂婚的" },
    { front: "ex-wife", pos: "n.", def: "the woman a man was married to before", example: "He stays friendly with his ex-wife for the children.", zh: "前妻" },
    { front: "fiancé", pos: "n.", def: "the man a woman is going to marry", example: "Her fiancé works as an architect in the city.", zh: "未婚夫" },
    { front: "generation", pos: "n.", def: "all the people of about the same age in a family or society", example: "Three generations live together in their house.", zh: "世代" },
    { front: "get engaged", pos: "phrase", def: "to formally agree to marry someone", example: "They got engaged after two years together.", zh: "訂婚" },
    { front: "get married", pos: "phrase", def: "to become husband and wife", example: "They're getting married in the village church.", zh: "結婚" },
    { front: "godmother", pos: "n.", def: "a woman who promises to help care for a child", example: "Her godmother sends a card every birthday.", zh: "教母" },
    { front: "great-grandfather", pos: "n.", def: "the father of your grandmother or grandfather", example: "My great-grandfather built this house in 1930.", zh: "曾祖父" },
    { front: "half-brother", pos: "n.", def: "a brother with only one parent the same as you", example: "His half-brother lives with them at weekends.", zh: "同父異母／同母異父兄弟" },
    { front: "in-laws", pos: "n.", def: "the family of your husband or wife", example: "They spend New Year with her in-laws.", zh: "姻親" },
    { front: "nephew", pos: "n.", def: "the son of your brother or sister", example: "My nephew starts school in September.", zh: "姪子、外甥" },
    { front: "niece", pos: "n.", def: "the daughter of your brother or sister", example: "Her niece is learning to play the piano.", zh: "姪女、外甥女" },
    { front: "only child", pos: "n.", def: "a child with no brothers or sisters", example: "As an only child, she loved visiting her cousins.", zh: "獨生子女" },
    { front: "relative", pos: "n.", def: "a member of your family", example: "Relatives from three countries came to the wedding.", zh: "親戚" },
    { front: "single parent", pos: "n.", def: "a mother or father bringing up children alone", example: "As a single parent, she balances work and family.", zh: "單親家長" },
    { front: "stepfather", pos: "n.", def: "the man married to your mother who is not your father", example: "His stepfather taught him to fish.", zh: "繼父" },
    { front: "twin", pos: "n.", def: "one of two children born to the same mother at the same time", example: "The twins finish each other's sentences.", zh: "雙胞胎之一" },
    { front: "widow", pos: "n.", def: "a woman whose husband has died", example: "The widow moved closer to her daughter's family.", zh: "寡婦" },
    { front: "bring up", pos: "phr. v.", def: "to care for a child until they are an adult", example: "She was brought up by her grandparents.", zh: "撫養" },
    { front: "grow up", pos: "phr. v.", def: "to change from a child into an adult", example: "He grew up in a small fishing village.", zh: "長大" },
    { front: "fall out", pos: "phr. v.", def: "to stop being friends after an argument", example: "The brothers fell out over money years ago.", zh: "鬧翻" },
    { front: "make up (after argument)", pos: "phr. v.", def: "to become friends again after a disagreement", example: "They argued at lunch but made up by dinner.", zh: "和好" },
    /* ---------- Relationships & social life ---------- */
    { front: "get to know", pos: "phrase", def: "to slowly learn what someone is like", example: "It takes time to get to know new classmates.", zh: "逐漸認識" },
    { front: "keep in touch", pos: "phrase", def: "to continue communicating with someone", example: "We kept in touch by email after the exchange trip.", zh: "保持聯絡" },
    { front: "lose touch", pos: "phrase", def: "to stop communicating with someone", example: "Sadly, I lost touch with my school friends.", zh: "失去聯絡" },
    { front: "have something in common", pos: "phrase", def: "to share the same interests or qualities", example: "We became friends because we have a lot in common.", zh: "有共同點" },
    { front: "go out with", pos: "phr. v.", def: "to have a romantic relationship with someone", example: "She's been going out with Marco for a year.", zh: "與……交往" },
    { front: "split up", pos: "phr. v.", def: "to end a romantic relationship", example: "The couple split up after five years together.", zh: "分手" },
    { front: "get on well", pos: "phrase", def: "to have a friendly relationship", example: "Luckily, I get on well with my new flatmates.", zh: "相處融洽" },
    { front: "look up to", pos: "phr. v.", def: "to admire and respect someone", example: "He really looks up to his older cousin.", zh: "敬仰" },
    { front: "count on", pos: "phr. v.", def: "to depend on someone to do something", example: "You can always count on her in an emergency.", zh: "依靠、指望" },
    { front: "let down", pos: "phr. v.", def: "to disappoint someone by not doing what you promised", example: "He promised to help and didn't let us down.", zh: "使失望" },
    { front: "cheer up", pos: "phr. v.", def: "to become or make someone happier", example: "We took her to the funfair to cheer her up.", zh: "振作、使開心" },
    { front: "tell off", pos: "phr. v.", def: "to speak angrily to someone who did something wrong", example: "The coach told him off for missing training.", zh: "責罵" },
    { front: "show off", pos: "phr. v.", def: "to try to make people admire you in an annoying way", example: "He's always showing off about his expensive phone.", zh: "炫耀" },
    { front: "take after", pos: "phr. v.", def: "to look or behave like an older family member", example: "She takes after her father in her love of music.", zh: "像（家人）" },
    { front: "get together with", pos: "phrase", def: "to meet someone socially", example: "Let's get together with the whole team after exams.", zh: "與……聚會" },
    { front: "invitation", pos: "n.", def: "a written or spoken request to come to an event", example: "The invitation says the party starts at eight.", zh: "邀請" },
    { front: "guest of honour", pos: "n.", def: "the most important person invited to an event", example: "The retired coach was guest of honour at the dinner.", zh: "主賓" },
    { front: "stranger", pos: "n.", def: "a person you do not know", example: "Don't share your address with strangers online.", zh: "陌生人" },
    { front: "penfriend", pos: "n.", def: "a person you exchange letters with but may never meet", example: "My penfriend in Brazil writes to me every month.", zh: "筆友" },
    { front: "companion", pos: "n.", def: "a person you spend time or travel with", example: "Her dog is her constant companion on walks.", zh: "同伴" },
    /* ---------- Life events ---------- */
    { front: "birth", pos: "n.", def: "the time when a baby comes into the world", example: "They announced the birth of their daughter.", zh: "出生" },
    { front: "childhood", pos: "n.", def: "the time when you are a child", example: "She spent her childhood by the sea.", zh: "童年" },
    { front: "teenager", pos: "n.", def: "a person between thirteen and nineteen years old", example: "The club runs evening activities for teenagers.", zh: "青少年" },
    { front: "adult", pos: "n.", def: "a fully grown person", example: "Tickets cost ten pounds for adults and five for children.", zh: "成人" },
    { front: "adulthood", pos: "n.", def: "the time of life when you are an adult", example: "Moving abroad marked the start of his adulthood.", zh: "成年期" },
    { front: "old age", pos: "n.", def: "the time of life when you are old", example: "She stayed active well into old age.", zh: "老年" },
    { front: "funeral", pos: "n.", def: "a ceremony for a person who has died", example: "The whole village attended the fisherman's funeral.", zh: "葬禮" },
    { front: "wedding", pos: "n.", def: "the ceremony where two people get married", example: "The wedding was held in the hotel garden.", zh: "婚禮" },
    { front: "bride", pos: "n.", def: "a woman on her wedding day", example: "The bride arrived ten minutes late, smiling widely.", zh: "新娘" },
    { front: "bridegroom", pos: "n.", def: "a man on his wedding day", example: "The nervous bridegroom dropped the ring.", zh: "新郎" },
    { front: "anniversary", pos: "n.", def: "the date on which something happened in a past year", example: "It's my parents' twentieth wedding anniversary today.", zh: "週年紀念" },
    { front: "retirement", pos: "n.", def: "the time after you stop working because of age", example: "He plans to travel widely in retirement.", zh: "退休生活" },
    { front: "move house", pos: "phrase", def: "to go and live in a different home", example: "We're moving house at the end of the month.", zh: "搬家" },
    { front: "start a family", pos: "phrase", def: "to have your first child", example: "They want to start a family in a few years.", zh: "生兒育女" },
    { front: "pass away", pos: "phr. v.", def: "a gentle way to say someone has died", example: "Her grandfather passed away peacefully last winter.", zh: "過世" },
    /* ---------- Communication & opinions ---------- */
    { front: "agree with", pos: "phrase", def: "to have the same opinion as someone", example: "I agree with you about the new timetable being better.", zh: "同意" },
    { front: "in my opinion", pos: "phrase", def: "used to introduce what you think", example: "In my opinion, the book is better than the film.", zh: "依我看" },
    { front: "point of view", pos: "n.", def: "a way of thinking about a situation", example: "Try to see the problem from her point of view.", zh: "觀點" },
    { front: "discussion", pos: "n.", def: "a conversation about something important", example: "We had a long discussion about the class trip.", zh: "討論" },
    { front: "argument", pos: "n.", def: "an angry disagreement, or a reason supporting an idea", example: "They had an argument about whose turn it was.", zh: "爭論" },
    { front: "debate", pos: "n.", def: "a formal discussion where people give different opinions", example: "The class held a debate about school uniforms.", zh: "辯論" },
    { front: "persuade", pos: "v.", def: "to make someone agree to do something by giving reasons", example: "She persuaded her parents to let her go camping.", zh: "說服" },
    { front: "convince", pos: "v.", def: "to make someone believe that something is true", example: "He convinced the teacher that the dog really ate his homework.", zh: "使相信" },
    { front: "admit to", pos: "phrase", def: "to agree that you did something wrong", example: "He admitted to breaking the window.", zh: "承認" },
    { front: "deny", pos: "v.", def: "to say that something is not true", example: "She denied taking the last biscuit, but had crumbs on her shirt.", zh: "否認" },
    { front: "insist", pos: "v.", def: "to say firmly that something must happen or is true", example: "Grandma insisted that we stay for dinner.", zh: "堅持" },
    { front: "swap", pos: "v.", def: "to give something and receive something in return", example: "The players swapped shirts after the match.", zh: "交換" },
    { front: "gossip", pos: "n.", def: "talk about other people's private lives", example: "The café was full of village gossip.", zh: "八卦" },
    { front: "rumour", pos: "n.", def: "a story that people repeat but that may not be true", example: "There's a rumour that the school will get a pool.", zh: "謠言" },
    // ---- Linking words & discourse B ----
    { front: "moreover", pos: "adv.", def: "used to add another important point", example: "The hotel was cheap; moreover, it was close to the beach.", zh: "此外" },
    { front: "despite", pos: "prep.", def: "without being affected by something", example: "We enjoyed the walk despite the rain.", zh: "儘管" },
    { front: "in spite of", pos: "phrase", def: "although something is true or happens", example: "In spite of the noise, the baby slept well.", zh: "儘管" },
    { front: "as well as", pos: "phrase", def: "in addition to", example: "She speaks French as well as English.", zh: "以及；除…之外還" },
    { front: "in addition", pos: "phrase", def: "used to add extra information", example: "In addition, the price includes breakfast.", zh: "此外" },
    { front: "on the other hand", pos: "phrase", def: "used to give a different point of view", example: "Trains are fast; on the other hand, they can be expensive.", zh: "另一方面" },
    { front: "for example", pos: "phrase", def: "used to give an example of what you mean", example: "Many sports, for example tennis, need special equipment.", zh: "例如" },
    { front: "so that", pos: "conj.", def: "in order to make something possible", example: "Speak slowly so that everyone can understand you.", zh: "以便" },
    { front: "even though", pos: "conj.", def: "although; despite the fact that", example: "Even though he was tired, he finished the race.", zh: "即使" },
    { front: "even if", pos: "conj.", def: "whether or not something happens", example: "We will go even if it rains.", zh: "即便" },
    { front: "anyway", pos: "adv.", def: "used to say something is true whatever else happens", example: "It was expensive, but I bought it anyway.", zh: "無論如何" },
    { front: "by the way", pos: "phrase", def: "used to introduce a new subject", example: "By the way, have you seen my keys?", zh: "順帶一提" },
    { front: "at first", pos: "phrase", def: "in the beginning", example: "At first I didn't like the city, but now I love it.", zh: "起初" },
    { front: "at last", pos: "phrase", def: "finally, after a long time", example: "At last the bus arrived, an hour late.", zh: "終於" },
    { front: "eventually", pos: "adv.", def: "in the end, after some time or effort", example: "We eventually found a parking space.", zh: "最終" },
    { front: "actually", pos: "adv.", def: "in fact; really", example: "I thought he was Spanish, but actually he's Italian.", zh: "實際上" },
    { front: "in fact", pos: "phrase", def: "used to add or stress true information", example: "It wasn't hard; in fact, it was quite easy.", zh: "事實上" },
    { front: "of course", pos: "phrase", def: "certainly; as everyone knows", example: "Of course you can borrow my pen.", zh: "當然" },
    { front: "perhaps", pos: "adv.", def: "possibly; maybe", example: "Perhaps we should leave earlier tomorrow.", zh: "或許" },
    { front: "definitely", pos: "adv.", def: "without any doubt", example: "I will definitely come to your party.", zh: "肯定地" },
    { front: "because of", pos: "phrase", def: "as a result of something", example: "The match was cancelled because of the storm.", zh: "因為" },
    { front: "due to", pos: "phrase", def: "caused by something", example: "The delay was due to heavy traffic.", zh: "由於" },
    { front: "according to", pos: "phrase", def: "as said or shown by someone or something", example: "According to the weather report, it will snow tonight.", zh: "根據" },
    { front: "apart from", pos: "phrase", def: "except for; in addition to", example: "Apart from maths, I enjoy all my subjects.", zh: "除了" },
    { front: "instead of", pos: "phrase", def: "in the place of something else", example: "Let's walk instead of taking the bus.", zh: "而不是" },
    { front: "as a result", pos: "phrase", def: "because of what has happened", example: "He missed the train and, as a result, arrived late.", zh: "因此" },
    { front: "in time", pos: "phrase", def: "early enough; not late", example: "We got to the station just in time for the train.", zh: "及時" },
    { front: "first of all", pos: "phrase", def: "before anything else", example: "First of all, let me thank you for coming.", zh: "首先" },
    { front: "in conclusion", pos: "phrase", def: "used to introduce the final part of a talk or essay", example: "In conclusion, recycling helps protect our planet.", zh: "總而言之" },
    { front: "on the whole", pos: "phrase", def: "generally; considering everything", example: "On the whole, the trip was a great success.", zh: "整體而言" },
    { front: "in general", pos: "phrase", def: "usually; in most situations", example: "In general, I prefer tea to coffee.", zh: "一般來說" },
    { front: "to be honest", pos: "phrase", def: "used when giving your true opinion", example: "To be honest, I didn't enjoy the film.", zh: "老實說" },
    // ---- Degree & quantity ----
    { front: "almost", pos: "adv.", def: "nearly but not completely", example: "It's almost midnight, so let's go home.", zh: "幾乎" },
    { front: "rather", pos: "adv.", def: "quite; to some degree", example: "The exam was rather difficult this year.", zh: "相當" },
    { front: "fairly", pos: "adv.", def: "to some degree, but not very", example: "The test was fairly easy for most students.", zh: "還算" },
    { front: "extremely", pos: "adv.", def: "very; to a very high degree", example: "Be careful — the soup is extremely hot.", zh: "極其" },
    { front: "totally", pos: "adv.", def: "completely", example: "I totally agree with your idea.", zh: "完全地" },
    { front: "absolutely", pos: "adv.", def: "completely; totally", example: "The view from the top was absolutely amazing.", zh: "絕對地" },
    { front: "barely", pos: "adv.", def: "only just; almost not", example: "I could barely hear her on the phone.", zh: "勉強；幾乎不" },
    { front: "particularly", pos: "adv.", def: "especially; more than usual", example: "I particularly liked the ending of the book.", zh: "尤其" },
    { front: "generally", pos: "adv.", def: "usually; in most cases", example: "Buses are generally on time in this town.", zh: "通常" },
    { front: "normally", pos: "adv.", def: "usually; in the normal way", example: "I normally get up at seven o'clock.", zh: "通常" },
    { front: "lately", pos: "adv.", def: "recently; in the last few days or weeks", example: "Have you seen any good films lately?", zh: "最近" },
    { front: "a few", pos: "phrase", def: "a small number of things or people", example: "I invited a few friends to dinner.", zh: "一些（可數）" },
    { front: "a little", pos: "phrase", def: "a small amount of something", example: "Add a little salt to the soup.", zh: "一點（不可數）" },
    { front: "several", pos: "adj.", def: "more than two but not very many", example: "I've read this book several times.", zh: "幾個" },
    { front: "neither", pos: "conj.", def: "not one and not the other of two", example: "Neither of the answers is correct.", zh: "兩者皆非" },
    { front: "either", pos: "conj.", def: "one or the other of two", example: "You can sit either here or by the window.", zh: "兩者之一" },
    { front: "loads of", pos: "phrase", def: "a lot of (informal)", example: "There were loads of people at the concert.", zh: "大量的" },
    { front: "hardly ever", pos: "phrase", def: "almost never", example: "We hardly ever eat out on weekdays.", zh: "幾乎不曾" },
    // ---- Idioms & fixed phrases ----
    { front: "piece of cake", pos: "idiom", def: "something that is very easy to do", example: "The maths test was a piece of cake for Anna.", zh: "輕而易舉的事" },
    { front: "once in a blue moon", pos: "idiom", def: "very rarely", example: "We only see our cousins once in a blue moon.", zh: "千載難逢；極少" },
    { front: "it's up to you", pos: "phrase", def: "you are the one who must decide", example: "We can eat in or go out — it's up to you.", zh: "由你決定" },
    { front: "make up your mind", pos: "idiom", def: "to decide something", example: "Hurry up and make up your mind about the film.", zh: "下定決心" },
    { front: "change your mind", pos: "idiom", def: "to change a decision or opinion", example: "She changed her mind and ordered pizza instead.", zh: "改變主意" },
    { front: "keep an eye on", pos: "idiom", def: "to watch something or someone carefully", example: "Can you keep an eye on my bag while I buy a ticket?", zh: "留意；看管" },
    { front: "have a good time", pos: "phrase", def: "to enjoy yourself", example: "We had a really good time at the festival.", zh: "玩得開心" },
    { front: "take it easy", pos: "idiom", def: "to relax and not do too much", example: "The doctor told him to take it easy for a week.", zh: "放輕鬆" },
    { front: "in a hurry", pos: "phrase", def: "needing to do something quickly", example: "Sorry, I can't stop — I'm in a hurry.", zh: "匆忙" },
    { front: "on your own", pos: "phrase", def: "alone; without help", example: "She painted the whole room on her own.", zh: "獨自" },
    { front: "on purpose", pos: "phrase", def: "deliberately; not by accident", example: "He didn't break the cup on purpose.", zh: "故意地" },
    { front: "by accident", pos: "phrase", def: "without planning or intending to", example: "I deleted the photo by accident.", zh: "不小心；意外地" },
    { front: "by chance", pos: "phrase", def: "without being planned; luckily", example: "We met by chance at the airport.", zh: "碰巧" },
    { front: "make sense", pos: "phrase", def: "to be easy to understand or logical", example: "These instructions don't make sense to me.", zh: "有道理；說得通" },
    { front: "take place", pos: "phrase", def: "to happen, especially a planned event", example: "The concert will take place in the park.", zh: "舉行；發生" },
    { front: "get rid of", pos: "phrase", def: "to throw away or remove something you don't want", example: "We should get rid of these old magazines.", zh: "擺脫；丟掉" },
    { front: "be about to", pos: "phrase", def: "to be going to do something very soon", example: "I was about to leave when the phone rang.", zh: "即將" },
    { front: "be used to", pos: "phrase", def: "to be familiar with something so it seems normal", example: "She's used to getting up early for work.", zh: "習慣於" },
    { front: "used to", pos: "phrase", def: "describes something that happened regularly in the past", example: "We used to live near the sea.", zh: "過去常常" },
    { front: "would rather", pos: "phrase", def: "to prefer to do one thing instead of another", example: "I would rather stay home tonight.", zh: "寧願" },
    { front: "had better", pos: "phrase", def: "used to say what someone should do", example: "You had better take an umbrella — it looks like rain.", zh: "最好" },
    { front: "right away", pos: "phrase", def: "immediately", example: "I'll send you the photos right away.", zh: "立刻" },
    { front: "so far", pos: "phrase", def: "until now", example: "So far, the holiday has been perfect.", zh: "到目前為止" },
    { front: "at the moment", pos: "phrase", def: "now; at the present time", example: "She's busy at the moment — can you call later?", zh: "目前" },
    { front: "these days", pos: "phrase", def: "at the present time; nowadays", example: "Everyone shops online these days.", zh: "現今" },
    { front: "the other day", pos: "phrase", def: "a few days ago", example: "I saw your brother in town the other day.", zh: "前幾天" },
    { front: "from time to time", pos: "phrase", def: "sometimes, but not often", example: "We visit our grandparents from time to time.", zh: "偶爾" },
    { front: "once in a while", pos: "phrase", def: "occasionally", example: "Once in a while we treat ourselves to a big dinner.", zh: "偶爾" },
    { front: "now and then", pos: "phrase", def: "sometimes; occasionally", example: "He still writes to me now and then.", zh: "時不時" },
    { front: "straight away", pos: "phrase", def: "immediately; without delay", example: "When I heard the news, I phoned her straight away.", zh: "馬上" },
    { front: "take care of", pos: "phrase", def: "to look after someone or something", example: "My aunt takes care of the garden while we're away.", zh: "照顧" },
    { front: "give someone a hand", pos: "idiom", def: "to help someone", example: "Could you give me a hand with these boxes?", zh: "幫忙" },
    { front: "tell the truth", pos: "phrase", def: "to say what really happened", example: "You should always tell the truth to your friends.", zh: "說實話" },
    { front: "tell a lie", pos: "phrase", def: "to say something that is not true", example: "He told a lie about where he had been.", zh: "說謊" },
    { front: "play a joke", pos: "phrase", def: "to do something funny to trick someone", example: "The students played a joke on their teacher.", zh: "開玩笑；惡作劇" },
    { front: "waste of time", pos: "phrase", def: "an activity that is not useful", example: "Arguing with him is a complete waste of time.", zh: "浪費時間" },
    { front: "no wonder", pos: "phrase", def: "it is not surprising", example: "No wonder you're tired — you got up at five!", zh: "難怪" },
    { front: "never mind", pos: "phrase", def: "used to tell someone not to worry", example: "Never mind — we can catch the next train.", zh: "沒關係" },
    { front: "what a pity", pos: "phrase", def: "used to say you are sorry about something", example: "What a pity you can't come to the wedding.", zh: "真可惜" },
    { front: "good luck", pos: "phrase", def: "said to wish someone success", example: "Good luck with your driving test tomorrow!", zh: "祝好運" },
    { front: "well done", pos: "phrase", def: "said to praise someone's success", example: "Well done — you passed all your exams!", zh: "做得好" },
    { front: "in trouble", pos: "phrase", def: "in a difficult situation, often because of doing something wrong", example: "He was in trouble for forgetting his homework again.", zh: "有麻煩" },
    { front: "on the way", pos: "phrase", def: "while going somewhere", example: "We can buy snacks on the way to the cinema.", zh: "在路上" },
    { front: "at the same time", pos: "phrase", def: "together; not one after another", example: "Don't all talk at the same time!", zh: "同時" },
    { front: "for ages", pos: "phrase", def: "for a very long time (informal)", example: "I haven't seen you for ages!", zh: "好久" },
    { front: "have fun", pos: "phrase", def: "to enjoy yourself", example: "Have fun at the party tonight!", zh: "玩得愉快" },
    { front: "come true", pos: "phrase", def: "to really happen after being hoped for", example: "Her dream of visiting Japan finally came true.", zh: "實現" },
    { front: "cost a fortune", pos: "idiom", def: "to be very expensive", example: "Those concert tickets cost a fortune.", zh: "花大錢" },
    { front: "sooner or later", pos: "phrase", def: "at some time in the future, certainly", example: "Sooner or later you'll have to tell them the truth.", zh: "遲早" },
    { front: "all of a sudden", pos: "phrase", def: "quickly and unexpectedly", example: "All of a sudden, the lights went out.", zh: "突然間" },
    // ---- Crime, law & rules ----
    { front: "crime", pos: "n.", def: "an action that is against the law", example: "The police work hard to prevent crime in the city.", zh: "犯罪" },
    { front: "thief", pos: "n.", def: "a person who steals things", example: "A thief took her bike from outside the shop.", zh: "小偷" },
    { front: "steal", pos: "v.", def: "to take something that belongs to someone else", example: "Someone stole my phone on the train.", zh: "偷竊" },
    { front: "rob", pos: "v.", def: "to steal from a person or place, often with force", example: "Two men tried to rob the bank last night.", zh: "搶劫" },
    { front: "robbery", pos: "n.", def: "the crime of stealing from a place or person", example: "There was a robbery at the jewellery shop.", zh: "搶案" },
    { front: "burglar", pos: "n.", def: "a person who enters a building to steal", example: "The burglar climbed in through the kitchen window.", zh: "竊賊" },
    { front: "pickpocket", pos: "n.", def: "a person who steals from people's pockets or bags", example: "Watch out for pickpockets in the crowded market.", zh: "扒手" },
    { front: "arrest", pos: "v.", def: "to take someone to a police station because of a crime", example: "The police arrested the driver for speeding.", zh: "逮捕" },
    { front: "punish", pos: "v.", def: "to make someone suffer for doing something wrong", example: "The teacher punished the boys for cheating.", zh: "懲罰" },
    { front: "punishment", pos: "n.", def: "what is done to someone who breaks a rule or law", example: "His punishment was to clean the classroom for a week.", zh: "處罰" },
    { front: "prison", pos: "n.", def: "a building where criminals are kept", example: "The thief spent two years in prison.", zh: "監獄" },
    { front: "law", pos: "n.", def: "a rule made by a government", example: "There is a law against dropping litter here.", zh: "法律" },
    { front: "illegal", pos: "adj.", def: "not allowed by law", example: "It is illegal to park on this street.", zh: "非法的" },
    { front: "fine (punishment)", pos: "n.", def: "money you must pay for breaking a rule", example: "He got a fine for cycling on the pavement.", zh: "罰款" },
    { front: "judge", pos: "n.", def: "the person who decides punishments in a court", example: "The judge listened carefully to both sides.", zh: "法官" },
    { front: "innocent", pos: "adj.", def: "not guilty of a crime", example: "The court decided that the man was innocent.", zh: "無辜的" },
    { front: "victim", pos: "n.", def: "a person who is hurt by a crime or accident", example: "The victim described the thief to the police.", zh: "受害者" },
    { front: "detective", pos: "n.", def: "a police officer who tries to solve crimes", example: "The detective found an important clue in the garden.", zh: "偵探" },
    { front: "investigate", pos: "v.", def: "to try to find out the truth about something", example: "The police are investigating the robbery.", zh: "調查" },
    { front: "suspect", pos: "n.", def: "a person the police think may have done a crime", example: "The main suspect was seen near the bank.", zh: "嫌疑犯" },
    { front: "evidence", pos: "n.", def: "facts that show something is true", example: "There wasn't enough evidence to arrest anyone.", zh: "證據" },
    { front: "witness", pos: "n.", def: "a person who sees a crime or accident happen", example: "A witness saw the car drive away quickly.", zh: "目擊者" },
    { front: "break into", pos: "phr. v.", def: "to enter a building illegally", example: "Someone broke into the office over the weekend.", zh: "闖入" },
    { front: "run away", pos: "phr. v.", def: "to leave a place quickly to escape", example: "The boys ran away when the alarm went off.", zh: "逃跑" },
    { front: "shoplifting", pos: "n.", def: "stealing things from a shop", example: "The store uses cameras to stop shoplifting.", zh: "順手牽羊" },
    { front: "vandalism", pos: "n.", def: "the crime of damaging property on purpose", example: "The park was closed because of vandalism.", zh: "破壞公物" },
    { front: "graffiti", pos: "n.", def: "writing or drawings on walls in public places", example: "The wall by the station is covered in graffiti.", zh: "塗鴉" },
    { front: "security", pos: "n.", def: "things done to keep a place or people safe", example: "Airport security checked all our bags.", zh: "安全措施" },
    { front: "alarm", pos: "n.", def: "a machine that makes a loud noise as a warning", example: "The fire alarm went off during the lesson.", zh: "警報器" },
    { front: "unlock", pos: "v.", def: "to open a lock with a key or code", example: "She unlocked the door and let us in.", zh: "解鎖" },
    { front: "belongings", pos: "n.", def: "the things that you own", example: "Please keep your belongings with you at all times.", zh: "隨身物品" },
    { front: "identity", pos: "n.", def: "who a person is", example: "The police checked the identity of every passenger.", zh: "身分" },
    { front: "permission", pos: "n.", def: "when someone says you are allowed to do something", example: "You need your parents' permission to join the trip.", zh: "許可" },
    { front: "permit", pos: "n.", def: "an official document that allows you to do something", example: "You need a permit to fish in this river.", zh: "許可證" },
    { front: "forbid", pos: "v.", def: "to say that something is not allowed", example: "The school forbids mobile phones in class.", zh: "禁止" },
    { front: "rule", pos: "n.", def: "an official instruction about what you must or must not do", example: "One rule of the library is to stay quiet.", zh: "規則" },
    { front: "obey", pos: "v.", def: "to do what a rule or person tells you", example: "Drivers must obey the speed limit.", zh: "遵守" },
    { front: "freedom", pos: "n.", def: "the state of being able to do what you want", example: "Working from home gives her more freedom.", zh: "自由" },
    { front: "guard", pos: "n.", def: "a person whose job is to protect a place or people", example: "A guard stands at the museum entrance.", zh: "警衛" },
    { front: "reward", pos: "n.", def: "something given for good work or help", example: "There's a reward for finding the lost dog.", zh: "獎賞" },
    { front: "clue", pos: "n.", def: "a piece of information that helps solve a problem", example: "The muddy footprints were an important clue.", zh: "線索" },
    { front: "disappear", pos: "v.", def: "to stop being seen or to go missing", example: "The cat disappeared for three days.", zh: "消失" },
    { front: "escape", pos: "v.", def: "to get away from a place or dangerous situation", example: "The bird escaped from its cage.", zh: "逃脫" },
    { front: "hide", pos: "v.", def: "to put something where it cannot be seen", example: "She hid the presents under the bed.", zh: "藏" },
    { front: "doubt", pos: "n.", def: "a feeling of not being sure", example: "There's no doubt that she will win the prize.", zh: "懷疑" },
    { front: "lie", pos: "n.", def: "something you say that you know is not true", example: "He told a lie to avoid getting into trouble.", zh: "謊言" },
    { front: "honesty", pos: "n.", def: "the quality of telling the truth", example: "Thank you for your honesty about the mistake.", zh: "誠實" },
    { front: "fault", pos: "n.", def: "responsibility for a mistake or problem", example: "It wasn't my fault that we missed the bus.", zh: "過錯" },
    { front: "blame", pos: "v.", def: "to say someone is responsible for something bad", example: "Don't blame me for the broken window!", zh: "責怪" },
    { front: "yell", pos: "v.", def: "to shout loudly", example: "The coach yelled at the players to run faster.", zh: "大喊" },
    // ---- Phrasal verbs D ----
    { front: "fill out", pos: "phr. v.", def: "to complete a form with information", example: "Please fill out this form before your appointment.", zh: "填寫" },
    { front: "sort out", pos: "phr. v.", def: "to solve a problem or organise something", example: "I need to sort out my desk — it's a mess.", zh: "整理；解決" },
    { front: "carry out", pos: "phr. v.", def: "to do a task or piece of work", example: "Scientists carried out an experiment on plants.", zh: "執行" },
    { front: "turn out", pos: "phr. v.", def: "to happen or be discovered in a particular way", example: "The party turned out better than we expected.", zh: "結果是" },
    { front: "figure out", pos: "phr. v.", def: "to understand or find the answer to something", example: "I can't figure out how to open this box.", zh: "弄清楚" },
    { front: "work on", pos: "phr. v.", def: "to spend time improving or making something", example: "She's working on a project about whales.", zh: "致力於" },
    { front: "settle down", pos: "phr. v.", def: "to become calm, or start a quiet life in one place", example: "The class settled down when the teacher arrived.", zh: "安定下來" },
    { front: "give out", pos: "phr. v.", def: "to give something to each person in a group", example: "The teacher gave out the exam papers.", zh: "分發" },
    { front: "pass on", pos: "phr. v.", def: "to give information or a thing to another person", example: "Please pass on my thanks to your parents.", zh: "轉達；傳遞" },
    { front: "put out", pos: "phr. v.", def: "to stop a fire or light from burning", example: "Firefighters put out the fire in an hour.", zh: "撲滅" },
    { front: "break out", pos: "phr. v.", def: "to start suddenly, like a fire or war", example: "A fire broke out in the kitchen last night.", zh: "爆發" },
    { front: "go through", pos: "phr. v.", def: "to experience something difficult, or check something carefully", example: "Let's go through your answers together.", zh: "經歷；檢查" },
    { front: "look into", pos: "phr. v.", def: "to try to find out more about something", example: "The manager promised to look into my complaint.", zh: "調查" },
    { front: "take on", pos: "phr. v.", def: "to accept extra work or responsibility", example: "She took on the job of organising the school fair.", zh: "承擔" },
    { front: "bring back", pos: "phr. v.", def: "to return something, or make someone remember", example: "This song brings back memories of last summer.", zh: "帶回；勾起回憶" },
    { front: "call off", pos: "phr. v.", def: "to cancel something that was planned", example: "They called off the picnic because of the storm.", zh: "取消" },
    { front: "put up with", pos: "phr. v.", def: "to accept something unpleasant without complaining", example: "I can't put up with this noise any longer.", zh: "忍受" },
    { front: "get along", pos: "phr. v.", def: "to have a friendly relationship with someone", example: "Do you get along with your neighbours?", zh: "相處融洽" },
    { front: "fall behind", pos: "phr. v.", def: "to fail to stay level with others", example: "He fell behind with his homework after being ill.", zh: "落後" },
    { front: "keep up", pos: "phr. v.", def: "to continue at the same speed or level as others", example: "You're doing well — keep up the good work!", zh: "跟上；保持" },
    { front: "drop out", pos: "phr. v.", def: "to leave school or a course before finishing", example: "He dropped out of the course after one month.", zh: "退出；輟學" },
    { front: "look out", pos: "phr. v.", def: "used to warn someone of danger", example: "Look out! There's a car coming!", zh: "小心" },
    { front: "watch out", pos: "phr. v.", def: "to be careful about danger", example: "Watch out for ice on the path this morning.", zh: "當心" },
    { front: "end up", pos: "phr. v.", def: "to finally be in a place or situation", example: "We got lost and ended up in a tiny village.", zh: "最終落得" },
    { front: "turn into", pos: "phr. v.", def: "to change and become something different", example: "The argument turned into a big fight.", zh: "變成" },
    { front: "come up", pos: "phr. v.", def: "to happen unexpectedly, or be mentioned", example: "Something came up, so I had to cancel dinner.", zh: "出現；被提及" },
    { front: "come up with", pos: "phr. v.", def: "to think of an idea or plan", example: "She came up with a great idea for the poster.", zh: "想出" },
    { front: "go up", pos: "phr. v.", def: "to increase or rise", example: "Bus fares went up again this year.", zh: "上漲" },
    { front: "go down", pos: "phr. v.", def: "to decrease or become lower", example: "The price of laptops has gone down recently.", zh: "下降" },
    { front: "let off", pos: "phr. v.", def: "to not punish someone, or only punish them lightly", example: "The police let him off with a warning.", zh: "從輕發落" },
    // ---- Society & citizenship ----
    { front: "society", pos: "n.", def: "people living together in an organised way", example: "Volunteering is a way to help society.", zh: "社會" },
    { front: "government", pos: "n.", def: "the group of people who control a country", example: "The government plans to build new schools.", zh: "政府" },
    { front: "citizen", pos: "n.", def: "a person who belongs to a country or city", example: "Every citizen has the right to vote.", zh: "公民" },
    { front: "vote", pos: "v.", def: "to choose someone or something officially", example: "We voted for a new class president today.", zh: "投票" },
    { front: "election", pos: "n.", def: "a time when people vote to choose leaders", example: "The school election takes place next Friday.", zh: "選舉" },
    { front: "president", pos: "n.", def: "the leader of a country or organisation", example: "The club president welcomed the new members.", zh: "總統；主席" },
    { front: "mayor", pos: "n.", def: "the leader of a town or city", example: "The mayor opened the new sports centre.", zh: "市長" },
    { front: "council", pos: "n.", def: "a group that manages a town or organisation", example: "The town council decided to plant more trees.", zh: "議會；委員會" },
    { front: "community", pos: "n.", def: "the people who live in an area", example: "The whole community helped clean the beach.", zh: "社區" },
    { front: "donate", pos: "v.", def: "to give money or things to help others", example: "We donated our old clothes to the shelter.", zh: "捐贈" },
    { front: "instruction", pos: "n.", def: "information that tells you how to do something", example: "Read the instructions before using the machine.", zh: "說明；指示" },
    { front: "regulation", pos: "n.", def: "an official rule", example: "New regulations ban smoking near the school.", zh: "規定" },
    { front: "hurry", pos: "v.", def: "to move or do something quickly", example: "Hurry, or we'll miss the beginning of the film!", zh: "趕快" },
    { front: "celebration", pos: "n.", def: "a special event for a happy occasion", example: "There was a big celebration for the town's birthday.", zh: "慶祝活動" },
    { front: "flag", pos: "n.", def: "a piece of cloth that represents a country or group", example: "The children waved flags during the parade.", zh: "旗幟" },
    { front: "media", pos: "n.", def: "television, radio, newspapers and the internet", example: "The story was reported in all the media.", zh: "媒體" },
    { front: "peace", pos: "n.", def: "a time without war or noise", example: "I love the peace of the countryside.", zh: "和平；寧靜" },
    { front: "war", pos: "n.", def: "fighting between countries or groups", example: "The museum has photos from the war.", zh: "戰爭" },
    { front: "leader", pos: "n.", def: "a person who guides or controls a group", example: "She was chosen as leader of the team.", zh: "領導者" },
    { front: "politics", pos: "n.", def: "activities connected with governing a country", example: "My uncle loves talking about politics at dinner.", zh: "政治" },
    // ---- Final mix: world, beliefs & extra phrasal verbs ----
    { front: "poverty", pos: "n.", def: "the state of being very poor", example: "The charity works to reduce poverty in the region.", zh: "貧窮" },
    { front: "wealth", pos: "n.", def: "a large amount of money or possessions", example: "The family's wealth came from their hotel business.", zh: "財富" },
    { front: "soldier", pos: "n.", def: "a person who serves in an army", example: "The soldiers marched through the town square.", zh: "士兵" },
    { front: "army", pos: "n.", def: "a large group of soldiers", example: "Her brother joined the army last year.", zh: "軍隊" },
    { front: "hero", pos: "n.", def: "a person admired for bravery or good actions", example: "The firefighter was a hero to the whole town.", zh: "英雄" },
    { front: "economy", pos: "n.", def: "the system of money and trade in a country", example: "Tourism is important for the island's economy.", zh: "經濟" },
    { front: "industry", pos: "n.", def: "the production of goods in factories", example: "The car industry employs thousands of people here.", zh: "工業；產業" },
    { front: "agriculture", pos: "n.", def: "farming and growing crops", example: "Agriculture is the main activity in this valley.", zh: "農業" },
    { front: "religion", pos: "n.", def: "belief in a god or gods", example: "We learn about different religions at school.", zh: "宗教" },
    { front: "belief", pos: "n.", def: "something that you think is true", example: "It's my belief that everyone deserves a second chance.", zh: "信念" },
    { front: "faith", pos: "n.", def: "strong trust or religious belief", example: "She has great faith in her doctor.", zh: "信任；信仰" },
    { front: "pray", pos: "v.", def: "to speak to a god, or hope strongly for something", example: "We're praying for good weather on sports day.", zh: "祈禱" },
    { front: "church", pos: "n.", def: "a building where Christians go to pray", example: "The old church has a beautiful tower.", zh: "教堂" },
    { front: "immigrant", pos: "n.", def: "a person who comes to live in a new country", example: "Many immigrants opened restaurants in this street.", zh: "移民" },
    { front: "go over", pos: "phr. v.", def: "to check or review something again", example: "Let's go over the plan one more time.", zh: "複習；再檢查" },
    { front: "put together", pos: "phr. v.", def: "to build something by joining its parts", example: "It took an hour to put the bookshelf together.", zh: "組裝" },
    { front: "move on", pos: "phr. v.", def: "to start doing or talking about something new", example: "Let's move on to the next question.", zh: "繼續進行" },
    { front: "stay over", pos: "phr. v.", def: "to sleep at someone's house for a night", example: "Can I stay over at Jake's house on Saturday?", zh: "過夜" },
  ];
  if (typeof module !== 'undefined') { module.exports = BANK; return; }
  VOCAB = VOCAB.concat(BANK);
})();
